/****** Object:  Function [BI].[fnGetLedgerCode]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE FUNCTION [BI].[fnGetLedgerCode](@TRANSID INT)
RETURNS VARCHAR(15)
BEGIN  
  DECLARE @ALLOCATION VARCHAR(15)
    DECLARE @LEDGERCODE VARCHAR(15)
  SELECT @ALLOCATION = ALLOCATION , @LEDGERCODE = LEDGERCODE FROM TRANSACTIONS WHERE TRANSID=@TRANSID 
  IF @ALLOCATION ='Balance Sheet' 
   BEGIN
	  DECLARE @STORE VARCHAR(15)
	  DECLARE @STKCODE VARCHAR(15)
	
	  SELECT @STORE = STORE, @STKCODE = STOCKNO  FROM TRANSACTIONS   WHERE TRANSID=@TRANSID 
	  SELECT @LEDGERCODE = STKDEFGL FROM INVENTORY WHERE STKCODE=@STKCODE AND STKSTORE=@STORE 
   END

  RETURN @LEDGERCODE 

End