/****** Object:  Table [EI].[DEBTINVOICEDETAILS]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [EI].[DEBTINVOICEDETAILS](
	[DETAILINDEX] [int] IDENTITY(1,1) NOT NULL,
	[HEADERID] [int] NULL,
	[WORKDONE] [decimal](18, 2) NULL,
	[GSTPERCENTAGE] [decimal](18, 2) NULL,
	[CGST] [decimal](18, 2) NULL,
	[SGST] [decimal](18, 2) NULL,
	[IGST] [decimal](18, 2) NULL,
	[TOTALGROSSAMOUNT] [decimal](18, 2) NULL,
	[NARRATION] [varchar](100) NULL,
	[HSNCODE] [varchar](10) NULL,
 CONSTRAINT [PK_DEBTINVOICEDETAILS] PRIMARY KEY CLUSTERED 
(
	[DETAILINDEX] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]