/****** Object:  Table [EI].[DEBTORINVOICEHEADER]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [EI].[DEBTORINVOICEHEADER](
	[INVOICEINDEX] [int] IDENTITY(1,1) NOT NULL,
	[DEBTRECONID] [int] NULL,
	[RULESETCODE] [varchar](15) NULL,
	[DEBTORNUMBER] [int] NULL,
	[BORGID] [int] NULL,
	[FINYEAR] [int] NULL,
	[PERIOD] [int] NULL,
	[INVOICETYPE] [varchar](3) NULL,
	[PARTYCODE] [varchar](15) NULL,
	[INVOICENUMBER] [varchar](25) NULL,
	[INVOICEDATE] [datetime] NULL,
	[NETRECEIVABLE] [decimal](18, 2) NULL,
	[EISTATUS] [int] NULL,
	[USERNAME] [varchar](25) NULL,
	[PARTYNAME] [varchar](100) NULL,
	[JSONFILENAME] [varchar](100) NULL,
	[APPROVED] [int] NULL,
	[TRANGRP] [int] NULL,
 CONSTRAINT [PK__DEBTORIN__A71D5C55F018E6DB] PRIMARY KEY CLUSTERED 
(
	[INVOICEINDEX] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]