/****** Object:  Table [EI].[EINVOICE]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [EI].[EINVOICE](
	[INVOICEID] [int] IDENTITY(1,1) NOT NULL,
	[REFERENCEHEADERID] [int] NOT NULL,
	[BORGID] [int] NULL,
	[INVOICENUMBER] [varchar](20) NULL,
	[INVOICEDATE] [datetime] NULL,
	[PARTYCODE] [varchar](20) NULL,
	[PARTYNAME] [varchar](200) NULL,
	[INVOICETYPE] [char](3) NULL,
	[INVOICEAMOUNT] [decimal](18, 2) NULL,
	[ACKNUMBER] [varchar](25) NULL,
	[ACKDATE] [datetime] NULL,
	[IRN] [varchar](100) NULL,
	[QRCODE] [image] NULL,
	[IMAGESIZE] [bigint] NULL,
	[TRANSGROUP] [bigint] NULL,
 CONSTRAINT [PK__EINVOICE__1F023060B92DC1EE] PRIMARY KEY CLUSTERED 
(
	[INVOICEID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]