/****** Object:  Table [EI].[EINVOICEDETAILS]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [EI].[EINVOICEDETAILS](
	[DETAILINDEX] [int] IDENTITY(1,1) NOT NULL,
	[HEADERID] [int] NULL,
	[CONTRALINENUMBER] [int] NULL,
	[EINVOICETYPE] [char](1) NULL,
	[SERIALNUMBER] [int] NULL,
	[LEDGERCODE] [varchar](15) NULL,
	[FIXEDDISPLAYNAME] [varchar](100) NULL,
	[VARIABLEDISPLAYNAME] [varchar](100) NULL,
	[CONTRADESC] [varchar](100) NULL,
	[ITEMDESCRIPTION] [varchar](100) NULL,
	[HSNCODE] [varchar](15) NULL,
	[QTY] [decimal](18, 2) NULL,
	[UOM] [varchar](3) NULL,
	[RATE] [decimal](18, 2) NULL,
	[GSTPERCENTAGE] [decimal](18, 2) NULL,
	[CGSTAMOUNT] [decimal](18, 2) NULL,
	[SGSTAMOUNT] [decimal](18, 2) NULL,
	[IGSTAMOUNT] [decimal](18, 2) NULL,
	[JSONFILENAME] [varchar](100) NULL,
	[QRCODEFILENAME] [varchar](100) NULL,
	[IRNUMBER] [varchar](100) NULL,
 CONSTRAINT [PK__EINVOICE__3E701F506BEFD4C9] PRIMARY KEY CLUSTERED 
(
	[DETAILINDEX] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]