/****** Object:  Table [EI].[EINVOICEHEADER]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [EI].[EINVOICEHEADER](
	[INVOICEINDEX] [int] IDENTITY(1,1) NOT NULL,
	[SUBCRECONID] [int] NULL,
	[SUBCONNUMBER] [int] NULL,
	[BORGID] [int] NULL,
	[FINYEAR] [int] NULL,
	[PERIOD] [int] NULL,
	[INVOICECATEGORY] [varchar](10) NULL,
	[PARTYCODE] [varchar](15) NULL,
	[WORKORDERNUMBER] [varchar](25) NULL,
	[CERTIFICATENUMBER] [int] NULL,
	[INVOICENUMBER] [varchar](25) NULL,
	[INVOICEDATE] [datetime] NULL,
	[GROSSBILLING] [decimal](18, 2) NULL,
	[DEBITNOTEAMOUNT] [decimal](18, 2) NULL,
	[CREDITNOTEAMOUNT] [decimal](18, 2) NULL,
	[NETPAYABLE] [decimal](18, 2) NULL,
	[EISTATUS] [int] NULL,
	[USERNAME] [varchar](25) NULL,
	[PARTYNAME] [varchar](100) NULL,
	[ORDERNUMBER] [varchar](50) NULL,
 CONSTRAINT [PK__EINVOICE__A71D5C55343CFC4D] PRIMARY KEY CLUSTERED 
(
	[INVOICEINDEX] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]