/****** Object:  Table [EI].[LEDGERMAPPING]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [EI].[LEDGERMAPPING](
	[INDEXCODE] [int] IDENTITY(1,1) NOT NULL,
	[LEDGERCODE] [varchar](15) NULL,
	[LEDGERNAME] [varchar](100) NULL,
	[DISPLAYNAME] [varchar](100) NULL,
	[HSNCODE] [varchar](15) NULL,
PRIMARY KEY CLUSTERED 
(
	[INDEXCODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]