/****** Object:  Table [EI].[STATECODE]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [EI].[STATECODE](
	[SLNO] [int] NOT NULL,
	[STATENAME] [varchar](100) NULL,
	[STATECODE] [varchar](15) NULL,
	[GSTIN] [varchar](50) NULL,
	[NICUSERID] [varchar](100) NULL,
	[NICPASSWORD] [varchar](100) NULL,
	[OWNERID] [varchar](100) NULL,
	[AUTHTOKEN] [varchar](255) NULL,
 CONSTRAINT [PK__STATCODE__A43D2D7C61379E3F] PRIMARY KEY CLUSTERED 
(
	[SLNO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]