/****** Object:  Procedure [BI].[DEBTORAGING]    Committed by VersionSQL https://www.versionsql.com ******/

 

CREATE PROCEDURE [BI].[DEBTORAGING](@LEDGERCODE VARCHAR(10), @AGEDTOPERIOD INT, @FINYEAR INT,  @LISTCREDITORS  LISTCREDNUMBERS  READONLY  ,@LISTORGIDS  LISTORGIDS READONLY   )  
AS
BEGIN
 
 
 
  CREATE TABLE #CREDITORS(CREDNUMBER VARCHAR(10))
  INSERT INTO #CREDITORS 
  SELECT CREDNUMBER FROM @LISTCREDITORS 
  DELETE FROM #CREDITORS WHERE CREDNUMBER IS NULL 
 
  CREATE TABLE #BORGS(ORGID INT)
  INSERT INTO #BORGS 
  SELECT ORGID  FROM @LISTORGIDS
  DELETE FROM #BORGS WHERE ORGID IS NULL

  /* JNL WILL NOT HAVE ANY RECEIVED DATE ; HENCE WE ARE PUTTING CURRENT DATE AS RECEIVED DATE */ 
  DECLARE @REFERENCEDATE DATETIME 
  UPDATE TRANSACTIONS SET RECEIVEDDATE = PDATE   WHERE YEAR=@FINYEAR AND TRANSTYPE='JNL' AND RECEIVEDDATE IS NULL  

  DECLARE @CREDITOR_LEDGER VARCHAR(10)
  SELECT @CREDITOR_LEDGER = @LEDGERCODE 

  DECLARE @CUTOFFDATE DATETIME


  SELECT @CUTOFFDATE = PEDATE FROM PERIODSETUP WHERE YEAR=@FINYEAR AND PERIOD = @AGEDTOPERIOD AND ORGID=2 

  CREATE TABLE #DUMPS (ORGID INT,YEAR INT,PERIOD INT,PDATE DATETIME,BATCHREF VARCHAR(10),TRANSREF VARCHAR(10), TRANSTYPE VARCHAR(3),
                       DESCRIPTION VARCHAR(50),CURRENCY VARCHAR(3),DEBIT DECIMAL(18,2),CREDIT DECIMAL(18,2),CREDNO VARCHAR(10),
					   TRANGRP INT,  TRANSID INT, HOMECURRAMOUNT DECIMAL(18,2),RECEIVEDDATE DATETIME )
  INSERT INTO #DUMPS
       SELECT
       ORGID,
       YEAR,
	   PERIOD,
	   PDATE,
	   BATCHREF,
	   TRANSREF,
	   LEFT(TRANSTYPE,3) TRANSTYPE ,
	   LEFT(DESCRIPTION,50) DESCRIPTION,
	   CURRENCY,
	   DEBIT,
	   CREDIT,
	   CREDNO,
	   TRANGRP,
	   TRANSID,
	   HOMECURRAMOUNT,
	   RECEIVEDDATE
	 FROM 
	   TRANSACTIONS 
	 WHERE 
	   PERIOD <= @AGEDTOPERIOD  AND 
	   YEAR = @FINYEAR  AND
	   LEDGERCODE = @CREDITOR_LEDGER  AND
	   ORGID IN (SELECT ORGID FROM #BORGS)  AND
	   CREDNO IN (SELECT CREDNUMBER FROM #CREDITORS) 
	  
 


    UPDATE #DUMPS SET CREDIT=HOMECURRAMOUNT WHERE CREDIT>0 AND CURRENCY <>'INR'
	UPDATE #DUMPS SET DEBIT=HOMECURRAMOUNT WHERE DEBIT>0 AND CURRENCY <>'INR'

	ALTER TABLE #DUMPS ADD NETAMOUNT DECIMAL(18,2)
	UPDATE #DUMPS SET NETAMOUNT = DEBIT WHERE DEBIT>0
	UPDATE #DUMPS SET NETAMOUNT = -1*CREDIT WHERE CREDIT>0



	


  
    ALTER TABLE #DUMPS ADD AGEINDAYS INT 

    UPDATE #DUMPS SET AGEINDAYS = DATEDIFF(DAY,PDATE,@CUTOFFDATE) 

	ALTER TABLE #DUMPS ADD ORGNAME VARCHAR(75)
	ALTER TABLE #DUMPS ADD SUPPLIERNAME VARCHAR(55)
	
	UPDATE #DUMPS SET ORGNAME = B.BORGNAME FROM BORGS B INNER JOIN #DUMPS ON #DUMPS.ORGID = B.BORGID  
	UPDATE #DUMPS SET SUPPLIERNAME = C.DEBTNAME FROM DEBTORS C INNER JOIN #DUMPS ON #DUMPS.CREDNO = C.DEBTNUMBER 



	CREATE TABLE #FINAL 
	(
	  ID  INT PRIMARY KEY IDENTITY (1,1) ,
	  SUPPLIERID    VARCHAR(10),
	  SUPPLIERNAME  VARCHAR(55),
	  ORGID         INT,
	  ORGNAME       VARCHAR(75),
	  TRANSTYPE     VARCHAR(3),
	  INVOICENUMBER VARCHAR(10),
	  INVOICEDATE   DATETIME,
	  INVOICEAMOUNT MONEY,
	  AGEINDAYS     INT,
	  BUCKET0       MONEY,
	  BUCKET1       MONEY,
	  BUCKET2       MONEY,
	  BUCKET3       MONEY,
	  BUCKET4       MONEY,
	  BUCKET5       MONEY,
	  BUCKET6       MONEY,
	  BUCKET7	    MONEY,
	  UNMATCHED     MONEY,
	  NARRATION     VARCHAR(50)
	)

	CREATE TABLE #FINALEXPORT 
	(
	  ID  INT PRIMARY KEY IDENTITY (1,1) ,
	  SUPPLIERID    VARCHAR(10),
	  SUPPLIERNAME  VARCHAR(55),
	  ORGID         INT,
	  ORGNAME       VARCHAR(75),
	  TRANSTYPE     VARCHAR(3),
	  INVOICENUMBER VARCHAR(10),
	  INVOICEDATE   DATETIME,
	  INVOICEAMOUNT MONEY,
	  AGEINDAYS     INT,
	  BUCKET0       MONEY,
	  BUCKET1       MONEY,
	  BUCKET2       MONEY,
	  BUCKET3       MONEY,
	  BUCKET4       MONEY,
	  BUCKET5       MONEY,
	  BUCKET6       MONEY,
	  BUCKET7	    MONEY,
	  UNMATCHED     MONEY,
	  LINETOTAL     MONEY,
	  NARRATION     VARCHAR(50)
	)

	CREATE TABLE #FINALCONSOLIDATED 
	(
	  ID  INT PRIMARY KEY IDENTITY (1,1) ,
	  SUPPLIERID    VARCHAR(10),
	  SUPPLIERNAME  VARCHAR(55),
	  ORGID         INT, 
	  ORGNAME       VARCHAR(75),
	  BUCKET0       MONEY,
	  BUCKET1       MONEY,
	  BUCKET2       MONEY,
	  BUCKET3       MONEY,
	  BUCKET4       MONEY,
	  BUCKET5       MONEY,
	  BUCKET6       MONEY,
	  BUCKET7	    MONEY,
	  UNMATCHED     MONEY,
	  ORGTOTAL      MONEY,
	)
	
	
	CREATE TABLE #FINALCONSOLIDATEDORGLEVEL 
	(
	  ID  INT PRIMARY KEY IDENTITY (1,1) ,
	  SUPPLIERID    VARCHAR(10),
	  SUPPLIERNAME  VARCHAR(55),
	  BUCKET0       MONEY,
	  BUCKET1       MONEY,
	  BUCKET2       MONEY,
	  BUCKET3       MONEY,
	  BUCKET4       MONEY,
	  BUCKET5       MONEY,
	  BUCKET6       MONEY,
	  BUCKET7       MONEY,
	  UNMATCHED     MONEY,
	  SUPPTOTAL     MONEY

	)

	INSERT INTO #FINAL 
	SELECT CREDNO ,SUPPLIERNAME,ORGID,ORGNAME,TRANSTYPE,TRANSREF,PDATE,NETAMOUNT,AGEINDAYS,     NETAMOUNT, 0 , 0, 0, 0, 0 ,0 ,0, 0 , SPACE(10)   FROM #DUMPS  WHERE AGEINDAYS <= 30  
	 AND TRANSTYPE NOT IN  ( 'CBC' ,'CBD' , 'PCP','PCR'    ) 

	INSERT INTO #FINAL 
	SELECT CREDNO ,SUPPLIERNAME,ORGID,ORGNAME,TRANSTYPE,TRANSREF,PDATE,NETAMOUNT,AGEINDAYS,     0, NETAMOUNT , 0, 0, 0, 0 ,0 ,0, 0,  SPACE(10)   FROM #DUMPS  WHERE AGEINDAYS BETWEEN 31 AND 60  
	 AND TRANSTYPE NOT IN  ( 'CBC' ,'CBD' , 'PCP','PCR'    ) 

	INSERT INTO #FINAL 
	SELECT CREDNO ,SUPPLIERNAME,ORGID,ORGNAME,TRANSTYPE,TRANSREF,PDATE,NETAMOUNT,AGEINDAYS,     0, 0 , NETAMOUNT, 0, 0, 0 ,0 ,0, 0,  SPACE(10)   FROM #DUMPS  WHERE AGEINDAYS BETWEEN 61 AND 90  
	 AND TRANSTYPE NOT IN  ( 'CBC' ,'CBD' , 'PCP','PCR'    ) 

	INSERT INTO #FINAL 
	SELECT CREDNO ,SUPPLIERNAME,ORGID,ORGNAME,TRANSTYPE,TRANSREF,PDATE,NETAMOUNT,AGEINDAYS,     0, 0 , 0, NETAMOUNT, 0, 0 ,0 ,0, 0,  SPACE(10)   FROM #DUMPS  WHERE AGEINDAYS BETWEEN 91 AND 180
	 AND TRANSTYPE NOT IN  ( 'CBC' ,'CBD' , 'PCP','PCR'    ) 

	INSERT INTO #FINAL 
	SELECT CREDNO ,SUPPLIERNAME,ORGID,ORGNAME,TRANSTYPE,TRANSREF,PDATE,NETAMOUNT,AGEINDAYS,     0, 0 , 0, 0, NETAMOUNT, 0 ,0 ,0, 0, SPACE(10)   FROM #DUMPS  WHERE AGEINDAYS BETWEEN 181 AND 365  
	 AND TRANSTYPE NOT IN  ( 'CBC' ,'CBD' , 'PCP','PCR'    ) 

	INSERT INTO #FINAL 
	SELECT CREDNO ,SUPPLIERNAME,ORGID,ORGNAME,TRANSTYPE,TRANSREF,PDATE,NETAMOUNT,AGEINDAYS,     0, 0 , 0, 0, 0, NETAMOUNT ,0 ,0, 0, SPACE(10)   FROM #DUMPS  WHERE AGEINDAYS BETWEEN 366 AND 730  
	 AND TRANSTYPE NOT IN  ( 'CBC' ,'CBD' , 'PCP','PCR'    ) 

	INSERT INTO #FINAL 
	SELECT CREDNO ,SUPPLIERNAME,ORGID,ORGNAME,TRANSTYPE,TRANSREF,PDATE,NETAMOUNT,AGEINDAYS,     0, 0 , 0, 0, 0, 0 ,NETAMOUNT ,0, 0, SPACE(10)   FROM #DUMPS  WHERE AGEINDAYS BETWEEN 731 AND 1095  
	 AND TRANSTYPE NOT IN  ( 'CBC' ,'CBD' , 'PCP','PCR'    ) 

    INSERT INTO #FINAL 
	SELECT CREDNO ,SUPPLIERNAME,ORGID,ORGNAME,TRANSTYPE,TRANSREF,PDATE,NETAMOUNT,AGEINDAYS,     0, 0 , 0, 0, 0, 0 ,0 ,NETAMOUNT, 0, SPACE(10)   FROM #DUMPS  WHERE AGEINDAYS > 1095  
	 AND TRANSTYPE NOT IN  ( 'CBC' ,'CBD' , 'PCP','PCR'    ) 

    INSERT INTO #FINAL 
	SELECT CREDNO ,SUPPLIERNAME,ORGID,ORGNAME,TRANSTYPE,TRANSREF,PDATE,NETAMOUNT,AGEINDAYS,     0, 0 , 0, 0, 0, 0 ,0 ,CREDIT,DEBIT, DESCRIPTION    FROM #DUMPS  WHERE 
	  TRANSTYPE   IN  ( 'CBC' ,'CBD' , 'PCP','PCR'    )


	UPDATE #FINAL SET UNMATCHED = INVOICEAMOUNT WHERE TRANSTYPE IN ('CBD','CBC' , 'PCP','PCR' )
	UPDATE #FINAL SET INVOICEAMOUNT = 0,AGEINDAYS=0,BUCKET0=0,BUCKET1=0,BUCKET2=0,BUCKET3=0,BUCKET4=0,BUCKET5=0,BUCKET6=0,BUCKET7=0 WHERE TRANSTYPE IN ( 'CBC' ,'CBD' , 'PCP','PCR') 
	
	
	INSERT INTO #FINALCONSOLIDATED 
	SELECT SUPPLIERID,SUPPLIERNAME,ORGID,ORGNAME,SUM(BUCKET0) BUCKET0,SUM(BUCKET1) BUCKET1, SUM(BUCKET2) BUCKET2, SUM(BUCKET3) BUCKET3,SUM(BUCKET4) BUCKET4,
	SUM(BUCKET5) BUCKET5,SUM(BUCKET6) BUCKET6,SUM(BUCKET7) BUCKET7, SUM(UNMATCHED) UNMATCHED,SUM( UNMATCHED ) ORGTOTAL FROM #FINAL 
	GROUP BY SUPPLIERID,SUPPLIERNAME,ORGID,ORGNAME  
 
	
	DECLARE @INDEXID INT
	DECLARE @MAXID   INT
	DECLARE @UNMATCHEDVALUE DECIMAL(18,2)
	DECLARE @NEWCELLVALUE   DECIMAL(18,2)
	DECLARE @OLDCELLVALUE   DECIMAL(18,2)
	SELECT @MAXID = MAX(ID) FROM #FINALCONSOLIDATED
	SET @INDEXID = 1

	WHILE @INDEXID <= @MAXID 
	BEGIN
       SELECT  @UNMATCHEDVALUE = UNMATCHED FROM #FINALCONSOLIDATED WHERE ID=@INDEXID 
	   
	   IF  @UNMATCHEDVALUE > 0 
	    BEGIN
	      SELECT @OLDCELLVALUE = BUCKET7 FROM #FINALCONSOLIDATED WHERE ID= @INDEXID 
		  IF @OLDCELLVALUE >= @UNMATCHEDVALUE 
		    BEGIN
		     SET @NEWCELLVALUE = @OLDCELLVALUE - @UNMATCHEDVALUE 
			 UPDATE #FINALCONSOLIDATED SET BUCKET7 = @NEWCELLVALUE,UNMATCHED=0 WHERE ID=@INDEXID 
			 SET @UNMATCHEDVALUE = 0
			END
		  ELSE
		    BEGIN
			    SET @UNMATCHEDVALUE = @UNMATCHEDVALUE-@OLDCELLVALUE 
				UPDATE #FINALCONSOLIDATED SET BUCKET7=0,UNMATCHED=@UNMATCHEDVALUE  WHERE ID=@INDEXID 
		    END
	    END		    
        
	   
	   IF  @UNMATCHEDVALUE > 0 
	    BEGIN
	      SELECT @OLDCELLVALUE = BUCKET6 FROM #FINALCONSOLIDATED WHERE ID= @INDEXID 
		  IF @OLDCELLVALUE >= @UNMATCHEDVALUE 
		    BEGIN
		     SET @NEWCELLVALUE = @OLDCELLVALUE - @UNMATCHEDVALUE 
			 UPDATE #FINALCONSOLIDATED SET BUCKET6 = @NEWCELLVALUE,UNMATCHED=0 WHERE ID=@INDEXID 
			 SET @UNMATCHEDVALUE = 0
			END
		  ELSE
		    BEGIN
			    SET @UNMATCHEDVALUE = @UNMATCHEDVALUE-@OLDCELLVALUE 
				UPDATE #FINALCONSOLIDATED SET BUCKET6=0,UNMATCHED=@UNMATCHEDVALUE WHERE ID=@INDEXID 
		    END
	    END		    

		
	   IF  @UNMATCHEDVALUE > 0 
	    BEGIN
	      SELECT @OLDCELLVALUE = BUCKET5 FROM #FINALCONSOLIDATED WHERE ID= @INDEXID 
		  IF @OLDCELLVALUE >= @UNMATCHEDVALUE 
		    BEGIN
		     SET @NEWCELLVALUE = @OLDCELLVALUE - @UNMATCHEDVALUE 
			 UPDATE #FINALCONSOLIDATED SET BUCKET5 = @NEWCELLVALUE,UNMATCHED=0 WHERE ID=@INDEXID 
			 SET @UNMATCHEDVALUE = 0
			END
		  ELSE
		    BEGIN
			    SET @UNMATCHEDVALUE = @UNMATCHEDVALUE-@OLDCELLVALUE 
				UPDATE #FINALCONSOLIDATED SET BUCKET5=0,UNMATCHED=@UNMATCHEDVALUE  WHERE ID=@INDEXID 
		    END
	    END	

		IF  @UNMATCHEDVALUE > 0 
	    BEGIN
	      SELECT @OLDCELLVALUE = BUCKET4 FROM #FINALCONSOLIDATED WHERE ID= @INDEXID 
		  IF @OLDCELLVALUE >= @UNMATCHEDVALUE 
		    BEGIN
		     SET @NEWCELLVALUE = @OLDCELLVALUE - @UNMATCHEDVALUE 
			 UPDATE #FINALCONSOLIDATED SET BUCKET4 = @NEWCELLVALUE,UNMATCHED=0 WHERE ID=@INDEXID 
			 SET @UNMATCHEDVALUE = 0 
			END
		  ELSE
		    BEGIN
			    SET @UNMATCHEDVALUE = @UNMATCHEDVALUE-@OLDCELLVALUE 
				UPDATE #FINALCONSOLIDATED SET BUCKET4=0,UNMATCHED=@UNMATCHEDVALUE  WHERE ID=@INDEXID 
		    END
	    END	

		IF  @UNMATCHEDVALUE > 0 
	    BEGIN
	      SELECT @OLDCELLVALUE = BUCKET3 FROM #FINALCONSOLIDATED WHERE ID= @INDEXID 
		  IF @OLDCELLVALUE >= @UNMATCHEDVALUE 
		    BEGIN
		     SET @NEWCELLVALUE = @OLDCELLVALUE - @UNMATCHEDVALUE 
			 UPDATE #FINALCONSOLIDATED SET BUCKET3 = @NEWCELLVALUE,UNMATCHED=0 WHERE ID=@INDEXID 
			 SET @UNMATCHEDVALUE = 0 
			END
		  ELSE
		    BEGIN
			    SET @UNMATCHEDVALUE = @UNMATCHEDVALUE-@OLDCELLVALUE 
				UPDATE #FINALCONSOLIDATED SET BUCKET3=0,UNMATCHED=@UNMATCHEDVALUE  WHERE ID=@INDEXID 
		    END
	    END	

		IF  @UNMATCHEDVALUE > 0 
	    BEGIN
	      SELECT @OLDCELLVALUE = BUCKET2 FROM #FINALCONSOLIDATED WHERE ID= @INDEXID 
		  IF @OLDCELLVALUE >= @UNMATCHEDVALUE 
		    BEGIN
		     SET @NEWCELLVALUE = @OLDCELLVALUE - @UNMATCHEDVALUE 
			 UPDATE #FINALCONSOLIDATED SET BUCKET2 = @NEWCELLVALUE,UNMATCHED=0 WHERE ID=@INDEXID 
			 SET @UNMATCHEDVALUE = 0 
			END
		  ELSE
		    BEGIN
			    SET @UNMATCHEDVALUE = @UNMATCHEDVALUE-@OLDCELLVALUE 
				UPDATE #FINALCONSOLIDATED SET BUCKET2=0 , UNMATCHED=@UNMATCHEDVALUE WHERE ID=@INDEXID 
		    END
	    END	

		IF  @UNMATCHEDVALUE > 0 
	    BEGIN
	      SELECT @OLDCELLVALUE = BUCKET1 FROM #FINALCONSOLIDATED WHERE ID= @INDEXID 
		  IF @OLDCELLVALUE >= @UNMATCHEDVALUE 
		    BEGIN
		     SET @NEWCELLVALUE = @OLDCELLVALUE - @UNMATCHEDVALUE 
			 UPDATE #FINALCONSOLIDATED SET BUCKET1 = @NEWCELLVALUE,UNMATCHED=0 WHERE ID=@INDEXID 
			 SET @UNMATCHEDVALUE = 0 
			END
		  ELSE
		    BEGIN
			    SET @UNMATCHEDVALUE = @UNMATCHEDVALUE-@OLDCELLVALUE 
				UPDATE #FINALCONSOLIDATED SET BUCKET1=0 , UNMATCHED=@UNMATCHEDVALUE WHERE ID=@INDEXID 
		    END
	    END	

		IF  @UNMATCHEDVALUE > 0 
	    BEGIN
	      SELECT @OLDCELLVALUE = BUCKET0 FROM #FINALCONSOLIDATED WHERE ID= @INDEXID 
		  IF @OLDCELLVALUE >= @UNMATCHEDVALUE 
		    BEGIN
		     SET @NEWCELLVALUE = @OLDCELLVALUE - @UNMATCHEDVALUE 
			 UPDATE #FINALCONSOLIDATED SET BUCKET0 = @NEWCELLVALUE,UNMATCHED=0 WHERE ID=@INDEXID 
			 SET @UNMATCHEDVALUE = 0 
			END
		  ELSE
		    BEGIN
			    SET @UNMATCHEDVALUE = @UNMATCHEDVALUE-@OLDCELLVALUE 
				UPDATE #FINALCONSOLIDATED SET BUCKET0=0 ,UNMATCHED=@UNMATCHEDVALUE WHERE ID=@INDEXID 
		    END
	    END	

		IF @UNMATCHEDVALUE > 0 
		   UPDATE #FINALCONSOLIDATED  SET UNMATCHED = @UNMATCHEDVALUE WHERE ID = @INDEXID 


        SET @INDEXID = @INDEXID + 1
	END

	 
	
    UPDATE #FINALCONSOLIDATED SET ORGTOTAL = (    (BUCKET0+BUCKET1+BUCKET2+BUCKET3+BUCKET4+BUCKET5+BUCKET6+BUCKET7 )   ) 

	DELETE FROM #FINALCONSOLIDATED WHERE ORGTOTAL = 0 


	INSERT INTO #FINALCONSOLIDATEDORGLEVEL
	SELECT SUPPLIERID,SUPPLIERNAME,SUM(BUCKET0) BUCKET0,SUM(BUCKET1) BUCKET1,SUM(BUCKET2) BUCKET2,
	SUM(BUCKET3) BUCKET3,SUM(BUCKET4) BUCKET4,SUM(BUCKET5) BUCKET5,SUM(BUCKET6) BUCKET6,SUM(BUCKET7) BUCKET7,
	SUM(UNMATCHED) UNMATCHED ,SUM(ORGTOTAL) SUPPTOTAL
	FROM  #FINALCONSOLIDATED
	GROUP BY SUPPLIERID,SUPPLIERNAME 

    SELECT @MAXID = MAX(ID) FROM #FINALCONSOLIDATEDORGLEVEL
	SET @INDEXID = 1
	SET @UNMATCHEDVALUE =0 

	WHILE @INDEXID <= @MAXID 
	BEGIN

       SELECT  @UNMATCHEDVALUE = UNMATCHED FROM #FINALCONSOLIDATEDORGLEVEL WHERE ID=@INDEXID  
	  

	   IF  @UNMATCHEDVALUE > 0 
	    BEGIN
	      SELECT @OLDCELLVALUE = BUCKET7 FROM #FINALCONSOLIDATEDORGLEVEL WHERE ID= @INDEXID 
		  IF @OLDCELLVALUE >= @UNMATCHEDVALUE 
		    BEGIN
		     SET @NEWCELLVALUE = @OLDCELLVALUE - @UNMATCHEDVALUE 
			 UPDATE #FINALCONSOLIDATEDORGLEVEL SET BUCKET7 = @NEWCELLVALUE,UNMATCHED=0 WHERE ID=@INDEXID 
			 SET @UNMATCHEDVALUE = @UNMATCHEDVALUE-@OLDCELLVALUE
			END
		  ELSE
		    BEGIN
			    SET @UNMATCHEDVALUE = @UNMATCHEDVALUE-@OLDCELLVALUE 
				UPDATE #FINALCONSOLIDATEDORGLEVEL SET BUCKET7=0,UNMATCHED=@UNMATCHEDVALUE   WHERE ID=@INDEXID 
		    END
	    END		    

	   
	   IF  @UNMATCHEDVALUE > 0 
	    BEGIN
	      SELECT @OLDCELLVALUE = BUCKET6 FROM #FINALCONSOLIDATEDORGLEVEL WHERE ID= @INDEXID 
		  IF @OLDCELLVALUE >= @UNMATCHEDVALUE 
		    BEGIN
		     SET @NEWCELLVALUE = @OLDCELLVALUE - @UNMATCHEDVALUE 
			 UPDATE #FINALCONSOLIDATEDORGLEVEL SET BUCKET6 = @NEWCELLVALUE,UNMATCHED=0 WHERE ID=@INDEXID 
			 SET @UNMATCHEDVALUE = @UNMATCHEDVALUE-@OLDCELLVALUE
			END
		  ELSE
		    BEGIN
			    SET @UNMATCHEDVALUE = @UNMATCHEDVALUE-@OLDCELLVALUE 
				UPDATE #FINALCONSOLIDATEDORGLEVEL SET BUCKET6=0,UNMATCHED=@UNMATCHEDVALUE  WHERE ID=@INDEXID 
		    END
	    END		    

		
	   IF  @UNMATCHEDVALUE > 0 
	    BEGIN
	      SELECT @OLDCELLVALUE = BUCKET5 FROM #FINALCONSOLIDATEDORGLEVEL WHERE ID= @INDEXID 
		  IF @OLDCELLVALUE >= @UNMATCHEDVALUE 
		    BEGIN
		     SET @NEWCELLVALUE = @OLDCELLVALUE - @UNMATCHEDVALUE 
			 UPDATE #FINALCONSOLIDATEDORGLEVEL SET BUCKET5 = @NEWCELLVALUE,UNMATCHED=0 WHERE ID=@INDEXID 
			 SET @UNMATCHEDVALUE = @UNMATCHEDVALUE-@OLDCELLVALUE
			END
		  ELSE
		    BEGIN
			    SET @UNMATCHEDVALUE = @UNMATCHEDVALUE-@OLDCELLVALUE 
				UPDATE #FINALCONSOLIDATEDORGLEVEL SET BUCKET5=0 ,UNMATCHED=@UNMATCHEDVALUE WHERE ID=@INDEXID 
		    END
	    END	

		IF  @UNMATCHEDVALUE > 0 
	    BEGIN
	      SELECT @OLDCELLVALUE = BUCKET4 FROM #FINALCONSOLIDATEDORGLEVEL WHERE ID= @INDEXID 
		  IF @OLDCELLVALUE >= @UNMATCHEDVALUE 
		    BEGIN
		     SET @NEWCELLVALUE = @OLDCELLVALUE - @UNMATCHEDVALUE 
			 UPDATE #FINALCONSOLIDATEDORGLEVEL SET BUCKET4 = @NEWCELLVALUE,UNMATCHED=0 WHERE ID=@INDEXID 
			 SET @UNMATCHEDVALUE = @UNMATCHEDVALUE-@OLDCELLVALUE
			 
			END
		  ELSE
		    BEGIN
			    SET @UNMATCHEDVALUE = @UNMATCHEDVALUE-@OLDCELLVALUE 
				UPDATE #FINALCONSOLIDATEDORGLEVEL SET BUCKET4=0,UNMATCHED=@UNMATCHEDVALUE  WHERE ID=@INDEXID 
		    END
	    END	

		IF  @UNMATCHEDVALUE > 0 
	    BEGIN
	      SELECT @OLDCELLVALUE = BUCKET3 FROM #FINALCONSOLIDATEDORGLEVEL WHERE ID= @INDEXID 
		  IF @OLDCELLVALUE >= @UNMATCHEDVALUE 
		    BEGIN
		     SET @NEWCELLVALUE = @OLDCELLVALUE - @UNMATCHEDVALUE 
			 UPDATE #FINALCONSOLIDATEDORGLEVEL SET BUCKET3 = @NEWCELLVALUE,UNMATCHED=0 WHERE ID=@INDEXID 
			 SET @UNMATCHEDVALUE = @UNMATCHEDVALUE-@OLDCELLVALUE
			 
			END
		  ELSE
		    BEGIN
			    SET @UNMATCHEDVALUE = @UNMATCHEDVALUE-@OLDCELLVALUE 
				UPDATE #FINALCONSOLIDATEDORGLEVEL SET BUCKET3=0 ,UNMATCHED=@UNMATCHEDVALUE WHERE ID=@INDEXID 
		    END
	    END	

		IF  @UNMATCHEDVALUE > 0 
	    BEGIN
	      SELECT @OLDCELLVALUE = BUCKET2 FROM #FINALCONSOLIDATEDORGLEVEL WHERE ID= @INDEXID 
		  IF @OLDCELLVALUE >= @UNMATCHEDVALUE 
		    BEGIN
		     SET @NEWCELLVALUE = @OLDCELLVALUE - @UNMATCHEDVALUE 
			 UPDATE #FINALCONSOLIDATEDORGLEVEL SET BUCKET2 = @NEWCELLVALUE,UNMATCHED=0 WHERE ID=@INDEXID 
			 SET @UNMATCHEDVALUE = @UNMATCHEDVALUE-@OLDCELLVALUE
			END
		  ELSE
		    BEGIN
			    SET @UNMATCHEDVALUE = @UNMATCHEDVALUE-@OLDCELLVALUE 
				UPDATE #FINALCONSOLIDATEDORGLEVEL SET BUCKET2=0 ,UNMATCHED=@UNMATCHEDVALUE WHERE ID=@INDEXID 
		    END
	    END	

		IF  @UNMATCHEDVALUE > 0 
	    BEGIN
	      SELECT @OLDCELLVALUE = BUCKET1 FROM #FINALCONSOLIDATEDORGLEVEL WHERE ID= @INDEXID 
		  IF @OLDCELLVALUE >= @UNMATCHEDVALUE 
		    BEGIN
		     SET @NEWCELLVALUE = @OLDCELLVALUE - @UNMATCHEDVALUE 
			 UPDATE #FINALCONSOLIDATEDORGLEVEL SET BUCKET1 = @NEWCELLVALUE,UNMATCHED=0 WHERE ID=@INDEXID 
			 SET @UNMATCHEDVALUE = @UNMATCHEDVALUE-@OLDCELLVALUE
			END
		  ELSE
		    BEGIN
			    SET @UNMATCHEDVALUE = @UNMATCHEDVALUE-@OLDCELLVALUE 
				UPDATE #FINALCONSOLIDATEDORGLEVEL SET BUCKET1=0 ,UNMATCHED=@UNMATCHEDVALUE WHERE ID=@INDEXID 
		    END
	    END	

		IF  @UNMATCHEDVALUE > 0 
	    BEGIN
	      SELECT @OLDCELLVALUE = BUCKET0 FROM #FINALCONSOLIDATEDORGLEVEL WHERE ID= @INDEXID 
		  IF @OLDCELLVALUE >= @UNMATCHEDVALUE 
		    BEGIN
		     SET @NEWCELLVALUE = @OLDCELLVALUE - @UNMATCHEDVALUE 
			 UPDATE #FINALCONSOLIDATEDORGLEVEL SET BUCKET0 = @NEWCELLVALUE,UNMATCHED=0 WHERE ID=@INDEXID 
			 SET @UNMATCHEDVALUE = @UNMATCHEDVALUE-@OLDCELLVALUE
			END
		  ELSE
		    BEGIN
			    SET @UNMATCHEDVALUE = @UNMATCHEDVALUE-@OLDCELLVALUE 
				UPDATE #FINALCONSOLIDATEDORGLEVEL SET BUCKET0=0 ,UNMATCHED=@UNMATCHEDVALUE WHERE ID=@INDEXID 
		    END
	    END	

		IF @UNMATCHEDVALUE > 0 
		   UPDATE #FINALCONSOLIDATEDORGLEVEL  SET UNMATCHED = @UNMATCHEDVALUE WHERE ID = @INDEXID 


        SET @INDEXID = @INDEXID + 1
	END

 	
	UPDATE #FINALCONSOLIDATEDORGLEVEL SET SUPPTOTAL = (    (BUCKET0+BUCKET1+BUCKET2+BUCKET3+BUCKET4+BUCKET5+BUCKET6+BUCKET7 )   )

	DELETE FROM #FINALCONSOLIDATEDORGLEVEL WHERE SUPPTOTAL = 0



    INSERT INTO #FINALEXPORT 
	SELECT SUPPLIERID,SUPPLIERNAME,ORGID,ORGNAME,TRANSTYPE,INVOICENUMBER,INVOICEDATE,INVOICEAMOUNT,
	AGEINDAYS,BUCKET0,BUCKET1,BUCKET2,BUCKET3,BUCKET4,BUCKET5,BUCKET6,BUCKET7,UNMATCHED,0, NARRATION 
	FROM #FINAL ORDER BY SUPPLIERID 

 
	UPDATE #FINALEXPORT SET LINETOTAL = (BUCKET0+BUCKET1+BUCKET2+BUCKET3+BUCKET4+BUCKET5+BUCKET6+BUCKET7+UNMATCHED)  
 

	SELECT * FROM #FINALEXPORT               ORDER BY ID
    SELECT * FROM #FINALCONSOLIDATED         ORDER BY SUPPLIERID,ORGID   
    SELECT * FROM #FINALCONSOLIDATEDORGLEVEL ORDER BY ID

 END
 
  