/****** Object:  Procedure [BI].[LOCKUSERS]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE [BI].[LOCKUSERS] (@ACTION INT)
AS
 
IF @ACTION = 1 
   BEGIN
        DELETE FROM BI.LOGINSUSPENS 
		DBCC CHECKIDENET("BI.LOGINSUSPENS", RESEED,0) 
		INSERT INTO BI.LOGINSUSPENS
		SELECT GETDATE(),USERID,LOCKED  FROM USERS 
		UPDATE USERS SET LOCKED=0 WHERE LOGINID IN ('CIPL814','CIPL367','admin' ) 
   END
ELSE
   BEGIN
        UPDATE USERS SET LOCKED=0
		UPDATE USERS SET LOCKED = L.STATUS FROM BI.LOGINSUSPENS L INNER JOIN USERS ON USERS.USERID=L.USERID 
		DELETE FROM BI.LOGINSUSPENS
   END
 