/****** Object:  Procedure [BI].[MONTHLYDEPRECIATION]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE  PROCEDURE [BI].[MONTHLYDEPRECIATION](@CURRENTYEAR INT,@CURRENTMONTH INT,@ID INT)
AS
IF @ID=1 
  EXEC [BI].[spPOSTDEPRECIATION] @CURRENTYEAR,@CURRENTMONTH,'2200007'

IF @ID=2
  EXEC [BI].[spPOSTDEPRECIATION] @CURRENTYEAR,@CURRENTMONTH,'2201000'

IF @ID=3
  EXEC [BI].[spPOSTDEPRECIATION] @CURRENTYEAR,@CURRENTMONTH,'2200005'

IF @ID=4
   EXEC [BI].[spPOSTDEPRECIATION] @CURRENTYEAR,@CURRENTMONTH,'2200006'

IF @ID=5
   EXEC [BI].[spPOSTDEPRECIATION] @CURRENTYEAR,@CURRENTMONTH,'2200003'

IF @ID=6
   EXEC [BI].[spPOSTDEPRECIATION] @CURRENTYEAR,@CURRENTMONTH,'2200004'

IF @ID=7
   EXEC [BI].[spPOSTDEPRECIATION] @CURRENTYEAR,@CURRENTMONTH,'2200002'

IF @ID=8
   EXEC [BI].[spPOSTDEPRECIATION] @CURRENTYEAR,@CURRENTMONTH,'2200001'