/****** Object:  Procedure [BI].[PeriodTB]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE [BI].[PeriodTB](@FINYEAR INT)
AS

DELETE FROM BS.PERIODTB

INSERT INTO BS.PERIODTB(LEDGERCODE,LEDGERNAME)
SELECT LEDGERCODE,LEDGERNAME FROM LEDGERCODES 
WHERE  LEDGERALLOC='Balance Sheet'  ORDER BY LEDGERCODE 

SELECT BORGID INTO #BORGS FROM BORGS WHERE PARENTBORG IN (23,24,25,26,172,209) 
SELECT LEDGERCODE INTO #LEDGERCODES FROM BS.PERIODTB 

DECLARE @PERIODID INT
SET @PERIODID = 0
DECLARE @STARTPERIOD INT 
SET @STARTPERIOD = 0

WHILE @PERIODID <=12 
BEGIN

  SELECT @PERIODID 

  SELECT LEDGERCODE,ISNULL(SUM(DEBIT-CREDIT),0) AMOUNT INTO #TRANS 
  FROM TRANSACTIONS 
  WHERE 
  YEAR=@FINYEAR AND 
  PERIOD BETWEEN @STARTPERIOD AND @PERIODID AND 
  ORGID  IN (SELECT BORGID FROM #BORGS) AND 
  ALLOCATION='Balance Sheet' 
  GROUP BY LEDGERCODE 



  IF @PERIODID = 0 
  BEGIN
     UPDATE BS.PERIODTB SET OB=0
	 UPDATE BS.PERIODTB SET OB=T.AMOUNT FROM #TRANS T INNER JOIN BS.PERIODTB BSP ON BSP.LEDGERCODE=T.LEDGERCODE 
  END 

  IF @PERIODID = 1 
  BEGIN
     UPDATE BS.PERIODTB SET APRIL=0
	 UPDATE BS.PERIODTB SET APRIL=T.AMOUNT FROM #TRANS T INNER JOIN BS.PERIODTB BSP ON BSP.LEDGERCODE=T.LEDGERCODE 
  END

  IF @PERIODID = 2 
  BEGIN
     UPDATE BS.PERIODTB SET MAY=0
	 UPDATE BS.PERIODTB SET MAY=T.AMOUNT FROM #TRANS T INNER JOIN BS.PERIODTB BSP ON BSP.LEDGERCODE=T.LEDGERCODE 
  END

 IF @PERIODID = 3 
 BEGIN
     UPDATE BS.PERIODTB SET JUNE=0
	 UPDATE BS.PERIODTB SET JUNE=T.AMOUNT FROM #TRANS T INNER JOIN BS.PERIODTB BSP ON BSP.LEDGERCODE=T.LEDGERCODE 
 END

 IF @PERIODID = 4 
 BEGIN
     UPDATE BS.PERIODTB SET JULY=0
	 UPDATE BS.PERIODTB SET JULY=T.AMOUNT FROM #TRANS T INNER JOIN BS.PERIODTB BSP ON BSP.LEDGERCODE=T.LEDGERCODE 
 END

 IF @PERIODID =5 
 BEGIN
     UPDATE BS.PERIODTB SET AUGUST=0
	 UPDATE BS.PERIODTB SET AUGUST=T.AMOUNT FROM #TRANS T INNER JOIN BS.PERIODTB BSP ON BSP.LEDGERCODE=T.LEDGERCODE 
 END

 IF @PERIODID = 6
 BEGIN
     UPDATE BS.PERIODTB SET SEPTEMBER=0
	 UPDATE BS.PERIODTB SET SEPTEMBER=T.AMOUNT FROM #TRANS T INNER JOIN BS.PERIODTB BSP ON BSP.LEDGERCODE=T.LEDGERCODE 
 END
 
  IF @PERIODID = 7
  BEGIN
     UPDATE BS.PERIODTB SET OCTOBER=0
	 UPDATE BS.PERIODTB SET OCTOBER=T.AMOUNT FROM #TRANS T INNER JOIN BS.PERIODTB BSP ON BSP.LEDGERCODE=T.LEDGERCODE 
  END

  IF @PERIODID = 8
  BEGIN
     UPDATE BS.PERIODTB SET NOVEMBER=0
	 UPDATE BS.PERIODTB SET NOVEMBER =T.AMOUNT FROM #TRANS T INNER JOIN BS.PERIODTB BSP ON BSP.LEDGERCODE=T.LEDGERCODE 
  END

  IF @PERIODID = 9
  BEGIN
     UPDATE BS.PERIODTB SET DECEMBER =0
	 UPDATE BS.PERIODTB SET DECEMBER =T.AMOUNT FROM #TRANS T INNER JOIN BS.PERIODTB BSP ON BSP.LEDGERCODE=T.LEDGERCODE 
  END

  IF @PERIODID = 10
  BEGIN
     UPDATE BS.PERIODTB SET JANUARY =0
	 UPDATE BS.PERIODTB SET JANUARY=T.AMOUNT FROM #TRANS T INNER JOIN BS.PERIODTB BSP ON BSP.LEDGERCODE=T.LEDGERCODE 
 END

  IF @PERIODID = 11
  BEGIN
     UPDATE BS.PERIODTB SET FEBRUARY =0
	 UPDATE BS.PERIODTB SET FEBRUARY=T.AMOUNT FROM #TRANS T INNER JOIN BS.PERIODTB BSP ON BSP.LEDGERCODE=T.LEDGERCODE 
  END

  IF @PERIODID = 12
  BEGIN
     UPDATE BS.PERIODTB SET MARCH =0
	 UPDATE BS.PERIODTB SET MARCH=T.AMOUNT FROM #TRANS T INNER JOIN BS.PERIODTB BSP ON BSP.LEDGERCODE=T.LEDGERCODE 
  END
 
  DROP TABLE #TRANS 

  SET @PERIODID=@PERIODID+1
END


SELECT * FROM BS.PERIODTB 


SELECT SUM(OB) FROM BS.PERIODTB
SELECT SUM(APRIL) FROM BS.PERIODTB
SELECT SUM(MAY) FROM BS.PERIODTB
SELECT SUM(JUNE) FROM BS.PERIODTB
SELECT SUM(JULY) FROM BS.PERIODTB
SELECT SUM(AUGUST) FROM BS.PERIODTB
SELECT SUM(SEPTEMBER) FROM BS.PERIODTB
SELECT SUM(OCTOBER) FROM BS.PERIODTB
SELECT SUM(NOVEMBER) FROM BS.PERIODTB
SELECT SUM(DECEMBER) FROM BS.PERIODTB
SELECT SUM(JANUARY) FROM BS.PERIODTB
SELECT SUM(FEBRUARY) FROM BS.PERIODTB
SELECT SUM(MARCH) FROM BS.PERIODTB
SELECT * FROM BS.PERIODTB 