/****** Object:  Procedure [BI].[spAssetYearEnd]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE  PROCEDURE [BI].[spAssetYearEnd](@YEAR INT)
AS

DECLARE @NEWYEAR INT
SET @NEWYEAR = @YEAR+1

SELECT DISTINCT ASSETID,ASSETNUMBER              INTO #TEMPASSET    FROM BI.ASSETPOSTS 
SELECT DISTINCT ASSETID,LEDGERCODE               INTO #TEMPLEDGERS  FROM BI.ASSETPOSTS
 
SELECT ASSETID,MAX(CURRNETCOUNT) CURRENTCOUNT    INTO #TEMPCOUNTS   FROM BI.ASSETPOSTS GROUP BY ASSETID 

SELECT 
  ASSETID,SUM(DEBIT) DEBIT 
INTO
  #TEMP0 
FROM 
  BI.ASSETPOSTS 
WHERE 
  YEAR = @YEAR
GROUP BY 
  ASSETID 
ORDER BY 
  ASSETID 

ALTER TABLE #TEMP0 ADD ASSETNUMBER VARCHAR(15)
ALTER TABLE #TEMP0 ADD LEDGERCODE VARCHAR(10)
ALTER TABLE #TEMP0 ADD CURRENTCOUNT INT 

UPDATE #TEMP0 SET ASSETNUMBER  = A.ASSETNUMBER   FROM #TEMPASSET   A INNER JOIN #TEMP0 ON #TEMP0.ASSETID=A.ASSETID 
UPDATE #TEMP0 SET LEDGERCODE   = A.LEDGERCODE    FROM #TEMPLEDGERS A INNER JOIN #TEMP0 ON #TEMP0.ASSETID=A.ASSETID 
UPDATE #TEMP0 SET CURRENTCOUNT = A.CURRENTCOUNT  FROM #TEMPCOUNTS  A INNER JOIN #TEMP0 ON #TEMP0.ASSETID=A.ASSETID

DELETE FROM BI.ASSETPOSTS WHERE YEAR=@NEWYEAR AND PERIOD=0

INSERT INTO BI.ASSETPOSTS(YEAR,PERIOD,ASSETID, ASSETNUMBER,LEDGERCODE,DEBIT,CURRNETCOUNT,BOOKINGDATE,DEPTYPE )
SELECT @NEWYEAR,0,ASSETID,ASSETNUMBER,LEDGERCODE,DEBIT,CURRENTCOUNT,GETDATE(),'SYSTEM' FROM #TEMP0 

SELECT LEDGERCODE,sum(debit) debit  FROM #TEMP0 group by LEDGERCODE  order by LEDGERCODE