/****** Object:  Procedure [BI].[spCashFlow]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE   PROCEDURE  [BI].[spCashFlow](@FINYEAR INT,@FROMPERIOD INT,@TOPERIOD INT,@BORGS ListOrgIDS ReadOnly)
AS

--  PROCEDURE FOR BSMIS CASH FLOW 
--  MODIFIED ON 06 MARCH 2019
--  UPDATED BI.CASHFLOWTEMPLATE TABLE ALSO

--DECLARE @BORGID INT 
--DELETE  FROM BI.CASHFLOWTEMPLATE
--DBCC CHECKIDENT ("BI.CASHFLOWTEMPLATE",RESEED,0)
--INSERT INTO  BI.CASHFLOWTEMPLATE
--SELECT   1, DESCRIPTION  FROM BS.CASHFLOWINDICATORS_NEW WHERE PAGENO=1 AND COLINDEX = 1  ORDER BY POSTIONINDEX 
--INSERT INTO BI.CASHFLOWTEMPLATE
--SELECT   2,  DESCRIPTION  FROM BS.CASHFLOWINDICATORS_NEW WHERE PAGENO=1 AND COLINDEX = 2  ORDER BY POSTIONINDEX 
--DELETE FROM  BI.CASHFLOWTEMPLATE WHERE ITEMNAME IN ('OUTFLOW','INFLOW') 



DECLARE @BORGID INT 

DECLARE @UNRECONDELIVERY DECIMAL(18,2)
CREATE TABLE #BORGS(ORGID INT)
INSERT INTO #BORGS  
SELECT ORGID  FROM @BORGS
DELETE FROM #BORGS WHERE ORGID IS NULL

 

CREATE TABLE #FINALOUTPUT(ID INT PRIMARY KEY IDENTITY(1,1),  ORGID INT, SLNO INT ,FLOWTYPE INT, ITEMNAME VARCHAR(60), AMOUNT DECIMAL(18,2) )
DELETE FROM #FINALOUTPUT 





DECLARE @STORECODE VARCHAR(25)
SELECT  DISTINCT @STORECODE=  STKSTORE FROM INVENTORY WHERE BORGID=@BORGID AND LEFT(STKSTORE,2)='MS'
DECLARE @STORELEDGER VARCHAR(10)
SELECT @STORELEDGER = STKCTL FROM INVSTORES WHERE STORECODE=@STORECODE 
 
DECLARE @WIP VARCHAR(10)
DECLARE @RETAINED VARCHAR(10)
SELECT @WIP = CONTROLFROMGL FROM CONTROLCODES WHERE CONTROLNAME='Work In Progress'                   
SELECT @RETAINED = CONTROLFROMGL FROM CONTROLCODES WHERE CONTROLNAME='Retained Income'                    

DELETE FROM BS.CASHFLOW_NEW 

DECLARE @COL1MAX DECIMAL(6,2)
DECLARE @COL2MAX DECIMAL(6,2)
DECLARE @MAXROW INT
DECLARE @I  DECIMAL(6,2)
SELECT @COL1MAX = MAX(POSTIONINDEX) FROM BS.CASHFLOWINDICATORS_NEW WHERE COLINDEX=1 AND PAGENO=1
SELECT @COL2MAX = MAX(POSTIONINDEX) FROM BS.CASHFLOWINDICATORS_NEW WHERE COLINDEX=2 AND PAGENO=1
IF @COL1MAX > @COL2MAX 
  SET @MAXROW = @COL1MAX
ELSE 
  SET @MAXROW = @COL2MAX

SET @I  = 1
WHILE @I <= @MAXROW 
BEGIN
  INSERT INTO BS.CASHFLOW_NEW(ROWINDEX) VALUES ( @I )
  SET @I = @I+1
END

UPDATE BS.CASHFLOW_NEW 
 SET CATEGORY  = I.CATEGORY ,
     COL1INDEX = I.INDEXCODE,
	 COL1CODE  = I.COLID,
	 COL1NAME  = I.DESCRIPTION,
	 COL1FONT  = I.FONTID ,
	 COL1VALUE  = 0,
	 PAGENO = I.PAGENO 
FROM 
     BS.CASHFLOWINDICATORS_NEW I 
	 INNER JOIN BS.CASHFLOW_NEW ON BS.CASHFLOW_NEW.ROWINDEX = I.POSTIONINDEX AND I.COLINDEX = 1 AND I.PAGENO=1

UPDATE BS.CASHFLOW_NEW 
 SET CATEGORY  = I.CATEGORY ,
     COL2INDEX = I.INDEXCODE,
	 COL2CODE  = I.COLID,
	 COL2NAME  = I.DESCRIPTION,
	 COL2FONT  = I.FONTID ,
	 COL1VALUE  = 0,
	 PAGENO = I.PAGENO 
FROM 
     BS.CASHFLOWINDICATORS_NEW I 
	 INNER JOIN BS.CASHFLOW_NEW ON BS.CASHFLOW_NEW.ROWINDEX = I.POSTIONINDEX AND I.COLINDEX = 2 AND I.PAGENO=1
 
SELECT @COL1MAX = MAX(POSTIONINDEX) FROM BS.CASHFLOWINDICATORS_NEW WHERE COLINDEX=1 AND PAGENO=2
SELECT @COL2MAX = MAX(POSTIONINDEX) FROM BS.CASHFLOWINDICATORS_NEW WHERE COLINDEX=2 AND PAGENO=2
IF @COL1MAX > @COL2MAX 
  SET @MAXROW = @COL1MAX
ELSE 
  SET @MAXROW = @COL2MAX

--SET @I  = 1
WHILE @I <= @MAXROW 
BEGIN
  INSERT INTO BS.CASHFLOW_NEW(ROWINDEX) VALUES ( @I )
  SET @I = @I+1
END

UPDATE BS.CASHFLOW_NEW 
 SET CATEGORY  = I.CATEGORY ,
     COL1INDEX = I.INDEXCODE,
	 COL1CODE  = I.COLID,
	 COL1NAME  = I.DESCRIPTION,
	 COL1FONT  = I.FONTID ,
	 COL1VALUE  = 0,
	 PAGENO = I.PAGENO 
FROM 
     BS.CASHFLOWINDICATORS_NEW I 
	 INNER JOIN BS.CASHFLOW_NEW ON BS.CASHFLOW_NEW.ROWINDEX = I.POSTIONINDEX AND I.COLINDEX = 1 AND I.PAGENO=2

UPDATE BS.CASHFLOW_NEW 
 SET CATEGORY  = I.CATEGORY ,
     COL2INDEX = I.INDEXCODE,
	 COL2CODE  = I.COLID,
	 COL2NAME  = I.DESCRIPTION,
	 COL2FONT  = I.FONTID ,
	 COL1VALUE  = 0,
	 PAGENO = I.PAGENO 
FROM 
     BS.CASHFLOWINDICATORS_NEW I 
	 INNER JOIN BS.CASHFLOW_NEW ON BS.CASHFLOW_NEW.ROWINDEX = I.POSTIONINDEX AND I.COLINDEX = 2 AND I.PAGENO=2

UPDATE BS.CASHFLOW_NEW SET COL1VALUE  = 0,COL2VALUE= 0

 

DECLARE @TEMPSUM DECIMAL(18,2)
DECLARE @ITEMONE DECIMAL(18,2)
DECLARE @ITEMTWO DECIMAL(18,2)


CREATE TABLE #TEMPUNRECONDLVRY (ORDID INT,PRICE DECIMAL(18,2), DLVRQTY DECIMAL(18,2),CURRENCY VARCHAR(10),EXCHANGERATE DECIMAL(18,2),HOMECURRENCY VARCHAR(10))

DECLARE PROJECTS CURSOR FOR SELECT ORGID FROM #BORGS 
OPEN PROJECTS 
FETCH NEXT FROM PROJECTS INTO @BORGID 

WHILE @@FETCH_STATUS = 0 
BEGIN 

          
			-- FOREIGN EXCHANGE TO BE CONSIDERED - UN RECON DELIVERY --
			 
			INSERT INTO #TEMPUNRECONDLVRY
			SELECT D.ORDID,D.PRICE,D.DLVRQTY,'INR',0,0 
			FROM DELIVERIES D
			WHERE D.TBORGID=@BORGID AND D.ALLOCATED=0 
			 
			--ALTER TABLE #TEMPUNRECONDLVRY ADD CURRENCY VARCHAR(10)
			--ALTER TABLE #TEMPUNRECONDLVRY ADD EXCHANGERATE DECIMAL(18,2)
			--ALTER TABLE #TEMPUNRECONDLVRY ADD HOMECURRENCY VARCHAR(10)

			UPDATE #TEMPUNRECONDLVRY
			SET CURRENCY =O.CURRENCY , EXCHANGERATE = O.EXCHRATE, HOMECURRENCY = O.HOMECURRENCY 
			FROM ORD O INNER JOIN #TEMPUNRECONDLVRY ON #TEMPUNRECONDLVRY.ORDID = O.ORDID 

			UPDATE #TEMPUNRECONDLVRY SET PRICE = PRICE * EXCHANGERATE WHERE CURRENCY <>'INR' 
			SELECT @UNRECONDELIVERY= SUM(DLVRQTY*PRICE) FROM #TEMPUNRECONDLVRY

 
			---- FE ENDS HERE 

		    INSERT INTO #FINALOUTPUT(ORGID,SLNO,FLOWTYPE,ITEMNAME,AMOUNT) 
			SELECT @BORGID,ID,FLOWTYPE,ITEMNAME,0 FROM BI.CASHFLOWTEMPLATE
		

			SELECT PDATE,BATCHREF,TRANSREF,LEDGERCODE,DESCRIPTION,DEBIT,CREDIT,CREDNO,TRANGRP,CURRENCY,HOMECURRAMOUNT	
			INTO #MASTERLIST 
			FROM TRANSACTIONS 
			WHERE YEAR = @FINYEAR AND ORGID = @BORGID AND PERIOD BETWEEN @FROMPERIOD  AND @TOPERIOD 
			ORDER BY TRANGRP 

			ALTER TABLE #MASTERLIST ADD NETAMOUNT DECIMAL(18,2) 
			UPDATE #MASTERLIST SET NETAMOUNT = (DEBIT-CREDIT) WHERE CURRENCY = 'INR'
			UPDATE #MASTERLIST SET NETAMOUNT = HomeCurrAmount WHERE CURRENCY <> 'INR' AND DEBIT>0
			UPDATE #MASTERLIST SET NETAMOUNT = -1.0*HOMECURRAMOUNT WHERE CURRENCY <>'INR' AND CREDIT>0 

			SELECT LEDGERCODE, (SUM(NETAMOUNT)) AMOUNT 
			INTO #TEMP0 
			FROM #MASTERLIST  
			GROUP BY LEDGERCODE
			ORDER BY LEDGERCODE 

 

			-- ADD EXTRA TWO COLUMNS INDEX AND MARKEER NAME 
			ALTER TABLE #MASTERLIST ADD CASHFLOWINDEX  NVARCHAR(55)
			ALTER TABLE #MASTERLIST ADD CASHFLOWMARKER VARCHAR(50)
			ALTER TABLE #MASTERLIST ADD COLID VARCHAR(10) 
			UPDATE #MASTERLIST SET CASHFLOWINDEX = AV.VALUE   FROM  ATTRIBVALUE AV INNER JOIN #MASTERLIST 
			ON #MASTERLIST.LedgerCode = AV.COLKEY AND AV.TABLENAME = 'LEDGERCODES' AND ATTRIBUTE = 'Cash Flow Markers' 
			UPDATE #MASTERLIST SET    CASHFLOWMARKER = FI.DESCRIPTION , COLID = FI.COLID  FROM   BS.CASHFLOWINDICATORS_NEW FI
			 INNER JOIN #MASTERLIST ON #MASTERLIST.CASHFLOWINDEX = FI.INDEXCODE WHERE FI.PAGENO=1
			DELETE  FROM #MASTERLIST WHERE CASHFLOWINDEX IS NULL 
			DELETE  FROM #MASTERLIST WHERE CASHFLOWINDEX = '0' 
			DELETE  FROM #MASTERLIST WHERE CASHFLOWMARKER IS NULL
			DELETE  FROM #MASTERLIST WHERE COLID IS NULL
			ALTER TABLE #MASTERLIST ADD COLINDEX INT
			ALTER TABLE #MASTERLIST ADD POSITIONINDEX INT
			UPDATE #MASTERLIST SET COLINDEX = IND.COLINDEX,POSITIONINDEX = IND.POSTIONINDEX
			FROM #MASTERLIST INNER JOIN BS.CASHFLOWINDICATORS_NEW IND ON #MASTERLIST.COLID = IND.COLID WHERE IND.PAGENO=1 
 

			-- ADD EXTRA TWO COLUMNS INDEX AND MARKEER NAME 
			ALTER TABLE #TEMP0 ADD CASHFLOWINDEX  NVARCHAR(55)
			ALTER TABLE #TEMP0 ADD CASHFLOWMARKER VARCHAR(50)
			UPDATE #TEMP0 SET CASHFLOWINDEX = AV.VALUE   FROM  ATTRIBVALUE AV INNER JOIN #TEMP0 
			ON #TEMP0.LedgerCode = AV.COLKEY AND AV.TABLENAME = 'LEDGERCODES' AND ATTRIBUTE = 'Cash Flow Markers' 
			UPDATE #TEMP0 SET    CASHFLOWMARKER = AV.DESCR  FROM   ATTRIBLOOKUP AV
			 INNER JOIN #TEMP0 ON #TEMP0.CASHFLOWINDEX = AV.VALUE WHERE AV.TABLENAME='LEDGERCODES' AND AV.ATTRIBUTE='Cash Flow Markers'
			DELETE  FROM #TEMP0 WHERE CASHFLOWINDEX IS NULL 
			DELETE  FROM #TEMP0 WHERE CASHFLOWINDEX = '0' 
 
			SELECT CASHFLOWMARKER,CASHFLOWINDEX,SUM(AMOUNT) NETAMOUNT 
			INTO #TEMP1
			FROM #TEMP0 
			GROUP BY CASHFLOWMARKER,CASHFLOWINDEX
			DELETE FROM #TEMP1 WHERE CASHFLOWINDEX IS NULL 
			UPDATE #TEMP1 SET NETAMOUNT = NETAMOUNT/100000.00

			UPDATE BS.CASHFLOW_NEW SET COL1VALUE = T.NETAMOUNT FROM #TEMP1 T INNER JOIN BS.CASHFLOW_NEW ON BS.CASHFLOW_NEW.COL1INDEX=T.CASHFLOWINDEX WHERE PAGENO=1
			UPDATE BS.CASHFLOW_NEW SET COL2VALUE =-1.0 * T.NETAMOUNT FROM #TEMP1 T INNER JOIN BS.CASHFLOW_NEW ON BS.CASHFLOW_NEW.COL2INDEX=T.CASHFLOWINDEX WHERE PAGENO=1
			-- THIS LINE HAS BEEN MODIFIED - PUT A MULTIPLICATION FACTOR -1.0 FOR COLUMN 2 VALUES 


			-- REPLACING UNRECON DELIVERY AND COMMITTED COST TO TEMPLATE 

			UPDATE BS.CASHFLOW_NEW SET COL1VALUE = @UNRECONDELIVERY/100000.00 WHERE BS.CASHFLOW_NEW.COL1INDEX=1001
			UPDATE BS.CASHFLOW_NEW SET COL1VALUE = -1.0*@UNRECONDELIVERY/100000.00 WHERE BS.CASHFLOW_NEW.COL1INDEX=1121


			-- TOTAL DIRECT EXPENSE AND PURCHASE 
			SET @TEMPSUM = 0
			SELECT @TEMPSUM = SUM(COL1VALUE) FROM BS.CASHFLOW_NEW WHERE COL1INDEX IN ( '1000','1001', '1005', '1010', '1020') 
			UPDATE BS.CASHFLOW_NEW SET COL1VALUE = @TEMPSUM WHERE COL1INDEX = 1  AND PAGENO=1

			-- TOTAL ASSETS 
			SET @TEMPSUM = 0
			SELECT @TEMPSUM = SUM(COL1VALUE) FROM BS.CASHFLOW_NEW WHERE COL1INDEX IN ( '1030', '1040', '1050', '1060',  '1080', '1090', '1100 ')  
			UPDATE BS.CASHFLOW_NEW SET COL1VALUE = @TEMPSUM WHERE COL1INDEX=2 AND PAGENO=1

			-- TOTAL CREDITOR / OUTSTANDING 
			SET @TEMPSUM = 0
			SELECT @TEMPSUM = SUM(COL1VALUE) FROM BS.CASHFLOW_NEW WHERE COL1INDEX IN ( '1120','1121', '1130', '1160' , '1170', '1180')  
			UPDATE BS.CASHFLOW_NEW SET COL1VALUE = @TEMPSUM WHERE  COL1INDEX=3 AND PAGENO=1

			-- DIVIDEND
			DECLARE @DIVIDEND DECIMAL(18,2)
			SET @DIVIDEND = 0 
			SELECT @DIVIDEND = ISNULL( SUM(COL1VALUE),0 ) FROM BS.CASHFLOW_NEW WHERE COL1INDEX='8020'  AND COL1CODE='E21' 

 
			--INVESTMENTS 
			DECLARE @INVESTMENT  DECIMAL(18,2)
			SET @INVESTMENT = 0 
			SELECT @INVESTMENT = ISNULL( SUM(COL1VALUE),0 ) FROM BS.CASHFLOW_NEW WHERE COL1INDEX='8040'  AND COL1CODE='E22' 

			-- Total Outflow  ( SUM OF  1 ,  2 AND 3 ) 
			SET @TEMPSUM = 0
			SELECT @TEMPSUM = SUM(COL1VALUE) FROM BS.CASHFLOW_NEW WHERE COL1INDEX IN (  '1', '2', '3')  AND PAGENO=1
			--ADD DIVIDEND AND INVESTMENT TOO
			SET @TEMPSUM = @TEMPSUM + @DIVIDEND + @INVESTMENT 

			UPDATE BS.CASHFLOW_NEW SET COL1VALUE = @TEMPSUM WHERE  COL1INDEX=4 AND PAGENO=1

			-- Advance + Sales (R1..R11)
			SET @TEMPSUM =0
			SELECT @TEMPSUM = SUM(COL2VALUE) FROM BS.CASHFLOW_NEW WHERE COL2INDEX IN ( '5000','5005', '5010',  '5020',  '5030','5035', '5040', '5041', '6515', '5070' )
			UPDATE BS.CASHFLOW_NEW SET COL2VALUE = @TEMPSUM  WHERE  COL2INDEX=1 AND PAGENO=1
 

			-- Total Deduction (R10..R14)
			SET @TEMPSUM =0
			SELECT @TEMPSUM = SUM(COL2VALUE) FROM BS.CASHFLOW_NEW WHERE COL2INDEX IN ( '5050','5060', '5090', '5100', '5110' )
			UPDATE BS.CASHFLOW_NEW SET COL2VALUE = @TEMPSUM  WHERE  COL2INDEX=2 AND PAGENO=1
			-- Total Receivables   
			SET @TEMPSUM =0
			SELECT @TEMPSUM = SUM(COL2VALUE) FROM BS.CASHFLOW_NEW WHERE COL2INDEX IN ( '5120', '5140')
			UPDATE BS.CASHFLOW_NEW SET COL2VALUE = @TEMPSUM  WHERE  COL2INDEX=3 AND PAGENO=1


			-- Total Inflow   ( SUM OF  1 ,  2 AND 3 ) 
			SET @TEMPSUM = 0
			SELECT @TEMPSUM = SUM(COL2VALUE) FROM BS.CASHFLOW_NEW WHERE COL2INDEX IN (  '1', '2', '3')  AND PAGENO=1

			-- Share Capital 
			DECLARE @SHARE DECIMAL(18,2)
			SET @SHARE = 0
			SELECT @SHARE = ISNULL(SUM(COL2VALUE),0) FROM BS.CASHFLOW_NEW WHERE COL2INDEX='8000' AND COL2CODE='T4' 

			-- IND Adjustment 
			DECLARE @IND DECIMAL(18,2)
			SET @IND= 0 
			SELECT @IND =ISNULL( SUM(COL2VALUE),0) FROM BS.CASHFLOW_NEW WHERE COL2INDEX='8010'  AND COL2CODE = 'T5' 

			-- ADDING FINAL INFLOW WITH SHARE AND IND 

			SET @TEMPSUM = @TEMPSUM+ @SHARE+@IND 
			UPDATE BS.CASHFLOW_NEW SET COL2VALUE = @TEMPSUM WHERE  COL2INDEX=4 AND PAGENO=1




			-- Final NET CASH FLOW
			SELECT @ITEMONE    = COL2VALUE FROM BS.CASHFLOW_NEW WHERE COL2INDEX= 4 AND PAGENO = 1
			SELECT @ITEMTWO    = COL1VALUE FROM BS.CASHFLOW_NEW WHERE COL1INDEX= 4 AND PAGENO = 1
			SET @TEMPSUM =    @ITEMONE - @ITEMTWO 
			UPDATE BS.CASHFLOW_NEW SET COL1VALUE = @TEMPSUM WHERE COL1INDEX=5

 

			-- Cash and Bank Balances - This is a Special Case where Cash + Bank caputre in Single Field 
			SET @TEMPSUM = 0
			SELECT @TEMPSUM = SUM(AMOUNT) FROM #TEMP0 WHERE CASHFLOWINDEX IN ( '2010','2020','2030' )  
 
			--SELECT @TEMPSUM = SUM(COL1VALUE) FROM BS.CASHFLOW_NEW WHERE COL1INDEX IN (  '5', '1070' )  AND PAGENO=1
			UPDATE BS.CASHFLOW_NEW SET COL1VALUE =+1.0* @TEMPSUM / 100000.00 WHERE  COL1INDEX=6 AND PAGENO=1
 

			--- PAGE NUMBER 2
			-- Line Number 101 to 106 & 109
			UPDATE BS.CASHFLOW_NEW SET COL2VALUE = (SELECT COL2VALUE FROM BS.CASHFLOW_NEW WHERE COL2INDEX='5010' AND PAGENO=1 ) WHERE COL2INDEX='5010' AND PAGENO=2
			UPDATE BS.CASHFLOW_NEW SET COL2VALUE = (SELECT COL2VALUE FROM BS.CASHFLOW_NEW WHERE COL2INDEX='5020' AND PAGENO=1 ) WHERE COL2INDEX='5020' AND PAGENO=2
			UPDATE BS.CASHFLOW_NEW SET COL2VALUE = (SELECT COL2VALUE FROM BS.CASHFLOW_NEW WHERE COL2INDEX='5030' AND PAGENO=1 ) WHERE COL2INDEX='5030' AND PAGENO=2
			UPDATE BS.CASHFLOW_NEW SET COL2VALUE = (SELECT COL2VALUE FROM BS.CASHFLOW_NEW WHERE COL2INDEX='5040' AND PAGENO=1 ) WHERE COL2INDEX='5040' AND PAGENO=2
 
			UPDATE BS.CASHFLOW_NEW SET COL2VALUE = (SELECT COL2VALUE FROM BS.CASHFLOW_NEW WHERE COL2INDEX='5120' AND PAGENO=1 ) WHERE COL2INDEX='5120' AND PAGENO=2
			-- Line 107 which is sum of 101 to 106
			SET @TEMPSUM = 0
			SELECT @TEMPSUM = SUM(COL2VALUE) FROM BS.CASHFLOW_NEW WHERE 
			COL2INDEX IN ( '5010','5020', '5030', '5040' )   AND 
			COL2CODE IN ('S1','S2','S3','S4') AND
			PAGENO=2
			UPDATE BS.CASHFLOW_NEW SET COL2VALUE = @TEMPSUM WHERE  COL2INDEX=11 AND PAGENO=2


			DECLARE @TOTALPAYMENTOUTSTANDING  DECIMAL(18,2)
			DECLARE @TOTALSALES DECIMAL(18,2)
			SELECT  @TOTALPAYMENTOUTSTANDING = COL2VALUE FROM BS.CASHFLOW_NEW WHERE COL2INDEX='5120' AND PAGENO=2 
			SET @TOTALSALES = @TEMPSUM  
			UPDATE  BS.CASHFLOW_NEW SET COL2VALUE = ( @TEMPSUM -  @TOTALPAYMENTOUTSTANDING)  WHERE PAGENO=2 AND COL2INDEX = '12'

			SET @TEMPSUM = 0
			SELECT @TEMPSUM = SUM(COL2VALUE) FROM BS.CASHFLOW_NEW WHERE COL2INDEX IN (  '12', '5120' )  AND PAGENO=2
			UPDATE BS.CASHFLOW_NEW SET COL2VALUE = @TEMPSUM WHERE  COL2INDEX=13 AND PAGENO=2


			-- Proftablity 
			UPDATE BS.CASHFLOW_NEW SET COL1VALUE = (SELECT COL1VALUE FROM BS.CASHFLOW_NEW WHERE COL1INDEX='1000' AND PAGENO=1 ) WHERE COL1INDEX='1000' AND PAGENO=2
			UPDATE BS.CASHFLOW_NEW SET COL1VALUE = (SELECT COL1VALUE FROM BS.CASHFLOW_NEW WHERE COL1INDEX='1010' AND PAGENO=1 ) WHERE COL1INDEX='1010' AND PAGENO=2
			UPDATE BS.CASHFLOW_NEW SET COL1VALUE = (SELECT COL1VALUE FROM BS.CASHFLOW_NEW WHERE COL1INDEX='1020' AND PAGENO=1 ) WHERE COL1INDEX='1020' AND PAGENO=2



			-- Profitablity Column 2

			UPDATE BS.CASHFLOW_NEW SET COL2VALUE = (SELECT COL2VALUE FROM BS.CASHFLOW_NEW WHERE COL2INDEX='11' AND PAGENO=2 ) WHERE PAGENO=2 AND COL2INDEX = '30000'


			SET @TEMPSUM = 0
			SELECT @TEMPSUM = ISNULL(SUM(COL2VALUE),0) FROM  BS.CASHFLOW_NEW  WHERE COL2CODE IN ('R10')  AND PAGENO=1
			UPDATE BS.CASHFLOW_NEW SET COL2VALUE = @TEMPSUM WHERE  COL2INDEX = '30100' AND PAGENO=2 


			DECLARE @MATERIALSTORE   DECIMAL(18,2)


			SELECT  @MATERIALSTORE =  ISNULL(SUM(AMOUNT),0)/100000.00 FROM #TEMP0 WHERE LEDGERCODE IN (@STORELEDGER, '2512002') 

			SET @MATERIALSTORE = @MATERIALSTORE * -1.0 

			UPDATE BS.CASHFLOW_NEW SET COL2VALUE = @MATERIALSTORE WHERE PAGENO=2 AND COL2INDEX = '30110'


			DECLARE @WIPAMOUT   DECIMAL(18,2)
			SELECT @WIPAMOUT =    ISNULL(SUM(AMOUNT),0)/100000.00 FROM #TEMP0 WHERE LEDGERCODE IN ('2990100') 

			SET @WIPAMOUT = -1.0 * @WIPAMOUT

			UPDATE BS.CASHFLOW_NEW SET COL2VALUE = @WIPAMOUT WHERE PAGENO=2 AND COL2INDEX = '30120'

			DECLARE @PLYBATTERN   DECIMAL(18,2)
			SELECT @PLYBATTERN =  ISNULL(SUM(AMOUNT),0)/100000.00 FROM #TEMP0 WHERE LEDGERCODE IN ('2990101') 

			SET @PLYBATTERN = -1.0 * @PLYBATTERN

			UPDATE BS.CASHFLOW_NEW SET COL2VALUE = @PLYBATTERN WHERE PAGENO=2 AND COL2INDEX = '30130'
 
			DECLARE @SITEESTABLISHMENTAMT   DECIMAL(18,2)
			SELECT @SITEESTABLISHMENTAMT =  ISNULL(SUM(AMOUNT),0)/100000.00 FROM #TEMP0 WHERE LEDGERCODE IN ( '2510097','2512000','2100099')

			SET @SITEESTABLISHMENTAMT = -1.0  * @SITEESTABLISHMENTAMT

			UPDATE BS.CASHFLOW_NEW SET COL2VALUE = @SITEESTABLISHMENTAMT WHERE PAGENO=2 AND COL2INDEX = '30140'

			DECLARE @SITEESTABLISHMENT   DECIMAL(18,2)
			SELECT @SITEESTABLISHMENT =   ISNULL(SUM(AMOUNT),0)/100000.00 FROM #TEMP0 WHERE LEDGERCODE IN ( '2512001','2560000')
 
			SET @SITEESTABLISHMENT = -1.0 * @SITEESTABLISHMENT

			UPDATE BS.CASHFLOW_NEW SET COL2VALUE = @SITEESTABLISHMENT WHERE PAGENO=2 AND COL2INDEX = '30150'
  
			DECLARE @TOTALB   DECIMAL(18,2)
			SELECT @TOTALB = ISNULL(SUM(COL2VALUE),0) FROM BS.CASHFLOW_NEW WHERE COL2INDEX IN ('30000','30100', '30110', '30120','30130', '30140', '30150')
			UPDATE BS.CASHFLOW_NEW SET COL2VALUE = @TOTALB WHERE PAGENO=2 AND COL2INDEX = '21'



			DECLARE @TOTALA   DECIMAL(18,2)
			SELECT @TOTALA = SUM(COL1VALUE) FROM BS.CASHFLOW_NEW WHERE COL1INDEX IN (  '1000', '1010', '1020' )  AND PAGENO=2
			UPDATE BS.CASHFLOW_NEW SET COL1VALUE =( @TOTALA) WHERE  COL1INDEX=11  AND   PAGENO=2 


			SET @TEMPSUM=0.0
			SET @TEMPSUM =  @TOTALB+@TOTALA  
			UPDATE BS.CASHFLOW_NEW SET COL1VALUE = @TEMPSUM WHERE PAGENO=2 AND COL1INDEX = '12'

			DELETE FROM BS.CASHFLOW_NEW WHERE PAGENO<>1 
        

		    -- MODIFICATIONS FOR OVER HEAD VALUES 
			-- O1 TO O6  OVER HEADS

			DECLARE @TOTALOVERHEAD1 DECIMAL(18,2)
			DECLARE @TOTALOVERHEAD2 DECIMAL(18,2)
			DECLARE @TOTALOVERHEAD3 DECIMAL(18,2)
			DECLARE @TOTALOVERHEAD4 DECIMAL(18,2)
			DECLARE @TOTALOVERHEAD5 DECIMAL(18,2)
			DECLARE @TOTALOVERHEADS DECIMAL(18,2)
			-- OVERHEADS = 5120060
			-- FORMWORK = 5081005
			-- EQUIPMENT = 5081006
			-- IT CHARGES = 5120201
			-- 1% CONTIGENCIES = 5081017

			SELECT @TOTALOVERHEAD1=ISNULL(SUM(DEBIT-CREDIT),0) FROM TRANSACTIONS WHERE LEDGERCODE='5120060' AND 
			YEAR = @FINYEAR AND ORGID = @BORGID AND PERIOD BETWEEN @FROMPERIOD  AND @TOPERIOD 


			SELECT @TOTALOVERHEAD2=ISNULL(SUM(DEBIT-CREDIT),0) FROM TRANSACTIONS WHERE LEDGERCODE='5081005' AND 
			YEAR = @FINYEAR AND ORGID = @BORGID AND PERIOD BETWEEN @FROMPERIOD  AND @TOPERIOD 

			SELECT @TOTALOVERHEAD3=ISNULL(SUM(DEBIT-CREDIT),0) FROM TRANSACTIONS WHERE LEDGERCODE='5081006' AND 
			YEAR = @FINYEAR AND ORGID = @BORGID AND PERIOD BETWEEN @FROMPERIOD  AND @TOPERIOD 

			SELECT @TOTALOVERHEAD4=ISNULL(SUM(DEBIT-CREDIT),0) FROM TRANSACTIONS WHERE LEDGERCODE='5120201' AND 
			YEAR = @FINYEAR AND ORGID = @BORGID AND PERIOD BETWEEN @FROMPERIOD  AND @TOPERIOD 

			SELECT @TOTALOVERHEAD5=ISNULL(SUM(DEBIT-CREDIT),0) FROM TRANSACTIONS WHERE LEDGERCODE='5081017' AND 
			YEAR = @FINYEAR AND ORGID = @BORGID AND PERIOD BETWEEN @FROMPERIOD  AND @TOPERIOD 

			SET @TOTALOVERHEADS = @TOTALOVERHEAD1 + @TOTALOVERHEAD2 + @TOTALOVERHEAD3 + @TOTALOVERHEAD4 + @TOTALOVERHEAD5


			SET @TOTALOVERHEAD1 = @TOTALOVERHEAD1/100000.00
			SET @TOTALOVERHEAD2 = @TOTALOVERHEAD2/100000.00
			SET @TOTALOVERHEAD3 = @TOTALOVERHEAD3/100000.00
			SET @TOTALOVERHEAD4 = @TOTALOVERHEAD4/100000.00
			SET @TOTALOVERHEAD5 = @TOTALOVERHEAD5/100000.00
			SET @TOTALOVERHEADS = @TOTALOVERHEADS /100000.00

			UPDATE #FINALOUTPUT SET AMOUNT = @TOTALOVERHEAD1 WHERE ITEMNAME='Overheads'  AND #FINALOUTPUT.ORGID = @BORGID 
			UPDATE #FINALOUTPUT SET AMOUNT = @TOTALOVERHEAD2 WHERE ITEMNAME='Formwork'   AND #FINALOUTPUT.ORGID = @BORGID 
			UPDATE #FINALOUTPUT SET AMOUNT = @TOTALOVERHEAD3 WHERE ITEMNAME='Equipment'  AND #FINALOUTPUT.ORGID = @BORGID 
			UPDATE #FINALOUTPUT SET AMOUNT = @TOTALOVERHEAD4 WHERE ITEMNAME='IT Charges'  AND #FINALOUTPUT.ORGID = @BORGID 
			UPDATE #FINALOUTPUT SET AMOUNT = @TOTALOVERHEAD5 WHERE ITEMNAME='1 % Contigencies' AND #FINALOUTPUT.ORGID = @BORGID 
			UPDATE #FINALOUTPUT SET AMOUNT = @TOTALOVERHEADS WHERE ITEMNAME='Total HO Charges ( 53 to 57 )' AND #FINALOUTPUT.ORGID = @BORGID 


		    UPDATE #FINALOUTPUT SET AMOUNT = CF.COL1VALUE 
			  FROM BS.CASHFLOW_NEW CF INNER JOIN #FINALOUTPUT ON #FINALOUTPUT.ITEMNAME =  CF.COL1NAME WHERE #FINALOUTPUT.FLOWTYPE=1 AND #FINALOUTPUT.ORGID = @BORGID 
	        UPDATE #FINALOUTPUT SET AMOUNT = CF.COL2VALUE 
			  FROM BS.CASHFLOW_NEW CF INNER JOIN #FINALOUTPUT ON #FINALOUTPUT.ITEMNAME =  CF.COL2NAME WHERE #FINALOUTPUT.FLOWTYPE=2 AND #FINALOUTPUT.ORGID = @BORGID
	        UPDATE #FINALOUTPUT SET AMOUNT = CF.COL1VALUE 
			  FROM BS.CASHFLOW_NEW CF INNER JOIN #FINALOUTPUT ON #FINALOUTPUT.ITEMNAME =  CF.COL1NAME WHERE #FINALOUTPUT.FLOWTYPE=3 AND #FINALOUTPUT.ORGID = @BORGID

			---- change of Sign of Net Cash Flow 
			--Net Cash Flow (+) / (-)  *

			UPDATE #FINALOUTPUT SET AMOUNT = -1.0*AMOUNT WHERE ITEMNAME='Net Cash Flow (+) / (-)  *'
			

	        UPDATE BS.CASHFLOW_NEW SET COL1VALUE  = 0,COL2VALUE= 0
			DROP TABLE #MASTERLIST 
			DROP TABLE #TEMP0
			DROP TABLE #TEMP1 
	

 FETCH NEXT FROM PROJECTS INTO @BORGID  
  
END
CLOSE PROJECTS
DEALLOCATE PROJECTS 

ALTER TABLE #FINALOUTPUT ADD BORGNAME VARCHAR(6)
UPDATE #FINALOUTPUT SET BORGNAME =  LEFT(B.BORGNAME,6) FROM BORGS B INNER JOIN #FINALOUTPUT ON #FINALOUTPUT.ORGID = B.BORGID 

 
Exec [BI].[CrossTab_ForCF] 'SELECT  SLNO,BORGNAME,ITEMNAME,AMOUNT FROM #FINALOUTPUT  ', 'BORGNAME','SUM(AMOUNT ELSE 0)[]' ,'SLNO,ITEMNAME'  
 