/****** Object:  Procedure [BI].[spCheckGSTEntries]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE BI.spCheckGSTEntries 
as


SELECT TRANGRP,SUM(DEBIT-CREDIT) CGST FROM TRANSACTIONS  WHERE YEAR=2018 AND PERIOD BETWEEN 3 AND 9 AND LEDGERCODE='1310025' AND ORGID NOT IN (28,29) GROUP BY TRANGRP ORDER BY TRANGRP 

SELECT TRANGRP,SUM(CGST_AMOUNT) CGST FROM BI.PURCHASEHISTORY WHERE FINYEAR=2018 AND PERIOD BETWEEN 3 AND 9 AND GSTTYPE='INPUT' AND ORGID NOT IN (28,29)
AND TRANGRP IN ( SELECT TRANGRP  FROM TRANSACTIONS  WHERE YEAR=2018 AND PERIOD BETWEEN 3 AND 9 AND LEDGERCODE='1310025' AND ORGID NOT IN (28,29) )
GROUP BY TRANGRP ORDER BY TRANGRP 