/****** Object:  Procedure [BI].[spCREDITORSDONETRANS]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE [BI].[spCREDITORSDONETRANS](@FINYEAR INT)
AS
SELECT 
 DISTINCT CREDNO  
 INTO #TEMP0 
 FROM TRANSACTIONS WHERE  LEDGERCODE='1315000' AND 
 ORGID  IN (SELECT BORGID FROM BORGS WHERE PARENTBORG IN (23,24,25,26,27,172,209) )
ALTER TABLE #TEMP0 ADD CREDNAME VARCHAR(150)
UPDATE #TEMP0 SET CREDNAME = C.CREDNAME FROM CREDITORS C INNER JOIN #TEMP0 ON #TEMP0.CREDNO=C.CREDNUMBER 
UPDATE #TEMP0 SET CREDNAME =LTRIM(RTRIM(CREDNAME))+ ' ('+ LTRIM(RTRIM(CREDNO)) + ')'
DELETE FROM #TEMP0 WHERE CREDNO IS NULL
UPDATE #TEMP0 SET CREDNAME = 'UNKNOWN' WHERE CREDNAME IS NULL 
SELECT CREDNO CREDNUMBER, CREDNAME   FROM #TEMP0 ORDER BY CREDNAME

-- YEAR=@FINYEAR AND  modifed this criteria


 