/****** Object:  Procedure [BI].[spCrossCheckGSTEntries]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE [BI].[spCrossCheckGSTEntries] 
as

-- Checking CGST Input - 1310025 
DECLARE @YEAR INT 
DECLARE @STARTPERIOD INT 
DECLARE @ENDPERIOD INT

SET @YEAR = 2019
SET @STARTPERIOD = 1
SET @ENDPERIOD = 1 


SELECT 
  TRANGRP,SUM(DEBIT-CREDIT) CGST 
  INTO #TEMP_TRANS_CGST_INPUT
  FROM 
    TRANSACTIONS  
  WHERE 
    YEAR=@YEAR AND PERIOD BETWEEN @STARTPERIOD AND @ENDPERIOD AND LEDGERCODE='1310025' AND ORGID NOT IN (28,29) 
  GROUP BY TRANGRP ORDER BY TRANGRP 


SELECT
  TRANGRP,SUM(CGST_AMOUNT) CGST 
  INTO #TEMP_PURCHASE_INPUT_CGST
  FROM BI.PURCHASEHISTORY 
WHERE 
    FINYEAR=@YEAR AND PERIOD BETWEEN @STARTPERIOD AND @ENDPERIOD AND GSTTYPE='INPUT' AND ORGID NOT IN (28,29) AND
   TRANGRP IN ( SELECT TRANGRP  FROM #TEMP_TRANS_CGST_INPUT )
GROUP BY 
   TRANGRP ORDER BY TRANGRP 

SELECT 'MISSING TRANSGROUP IN CGST PURCHASE' 
SELECT * FROM #TEMP_TRANS_CGST_INPUT WHERE TRANGRP NOT IN (SELECT TRANGRP FROM #TEMP_PURCHASE_INPUT_CGST) 

-- SGST 

SELECT 
  TRANGRP,SUM(DEBIT-CREDIT) SGST 
  INTO #TEMP_TRANS_SGST_INPUT
  FROM 
    TRANSACTIONS  
  WHERE 
    YEAR=@YEAR AND PERIOD BETWEEN @STARTPERIOD AND @ENDPERIOD AND LEDGERCODE='1310026' AND ORGID NOT IN (28,29) 
  GROUP BY TRANGRP ORDER BY TRANGRP 


SELECT
  TRANGRP,SUM(SGST_AMOUNT) SGST 
  INTO #TEMP_PURCHASE_INPUT_SGST
  FROM BI.PURCHASEHISTORY 
WHERE 
    FINYEAR=@YEAR AND PERIOD BETWEEN @STARTPERIOD AND @ENDPERIOD AND GSTTYPE='INPUT' AND ORGID NOT IN (28,29) AND
   TRANGRP IN ( SELECT TRANGRP  FROM #TEMP_TRANS_SGST_INPUT )
GROUP BY 
   TRANGRP ORDER BY TRANGRP 

SELECT 'MISSING TRANSGROUP IN SGST PURCHASE' 
SELECT * FROM #TEMP_TRANS_SGST_INPUT WHERE TRANGRP NOT IN (SELECT TRANGRP FROM #TEMP_PURCHASE_INPUT_SGST) 

-- IGST

SELECT 
  TRANGRP,SUM(DEBIT-CREDIT) IGST 
  INTO #TEMP_TRANS_IGST_INPUT
  FROM 
    TRANSACTIONS  
  WHERE 
    YEAR=@YEAR AND PERIOD BETWEEN @STARTPERIOD AND @ENDPERIOD AND LEDGERCODE='1310027' AND ORGID NOT IN (28,29) 
  GROUP BY TRANGRP ORDER BY TRANGRP 


SELECT
  TRANGRP,SUM(IGST_AMOUNT) IGST 
  INTO #TEMP_PURCHASE_INPUT_IGST
  FROM BI.PURCHASEHISTORY 
WHERE 
    FINYEAR=@YEAR AND PERIOD BETWEEN @STARTPERIOD AND @ENDPERIOD AND GSTTYPE='INPUT' AND ORGID NOT IN (28,29) AND
   TRANGRP IN ( SELECT TRANGRP  FROM #TEMP_TRANS_IGST_INPUT )
GROUP BY 
   TRANGRP ORDER BY TRANGRP 

SELECT 'MISSING TRANSGROUP IN IGST PURCHASE' 
SELECT * FROM #TEMP_TRANS_IGST_INPUT WHERE TRANGRP NOT IN (SELECT TRANGRP FROM #TEMP_PURCHASE_INPUT_IGST) 


SELECT 'CGST  - TRANSACTION AMOUNT DIFFERENT FROM PURCHASE REGISTER ENTRIES '
SELECT T.*,P.*  FROM #TEMP_TRANS_CGST_INPUT T  INNER JOIN #TEMP_PURCHASE_INPUT_CGST P  ON T.TRANGRP = P.TRANGRP WHERE ABS(T.CGST-P.CGST)>1

SELECT 'SGST  - TRANSACTION AMOUNT DIFFERENT FROM PURCHASE REGISTER ENTRIES '
SELECT T.*,P.*  FROM #TEMP_TRANS_SGST_INPUT T  INNER JOIN #TEMP_PURCHASE_INPUT_SGST P  ON T.TRANGRP = P.TRANGRP WHERE ABS(T.SGST-P.SGST)>1 

SELECT 'IGST  - TRANSACTION AMOUNT DIFFERENT FROM PURCHASE REGISTER ENTRIES '
SELECT T.*,P.*  FROM #TEMP_TRANS_IGST_INPUT T  INNER JOIN #TEMP_PURCHASE_INPUT_IGST P  ON T.TRANGRP = P.TRANGRP WHERE ABS(T.IGST-P.IGST)>1  



------- NOW THE REVERSE ---- TAKING BASE AS  PURCHASE ENTRY CHECKING ANY EXTRA ENTRIES IN PURCHASE REGISTER ----- 

-- CGST ENTRIES 

SELECT TRANGRP,SUM(CGST_AMOUNT) CGST
INTO #GST_PURCHASE_CGST_INPUT 
FROM BI.PURCHASEHISTORY
WHERE FINYEAR = @YEAR AND PERIOD BETWEEN @STARTPERIOD AND @ENDPERIOD AND GSTTYPE ='INPUT' AND CGST_AMOUNT <>0 AND ORGID NOT IN (28,29) GROUP BY TRANGRP 

DELETE FROM #GST_PURCHASE_CGST_INPUT WHERE CGST=0 

SELECT 'ITME IN PURCHASE HISTORY NOT IN TRANS - CGST '
SELECT * FROM #GST_PURCHASE_CGST_INPUT G1 
 WHERE TRANGRP NOT IN (SELECT TRANGRP FROM  #TEMP_TRANS_CGST_INPUT T WHERE  T.CGST<>0 )


-- SGST ENTRIES 

SELECT TRANGRP,SUM(SGST_AMOUNT) SGST
INTO #GST_PURCHASE_SGST_INPUT 
FROM BI.PURCHASEHISTORY
WHERE FINYEAR = @YEAR AND PERIOD BETWEEN @STARTPERIOD AND @ENDPERIOD AND GSTTYPE ='INPUT' AND SGST_AMOUNT <>0 AND ORGID NOT IN (28,29) GROUP BY TRANGRP 

DELETE FROM #GST_PURCHASE_SGST_INPUT WHERE SGST=0 

SELECT 'ITME IN PURCHASE HISTORY NOT IN TRANS - SGST '
SELECT * FROM #GST_PURCHASE_SGST_INPUT G2  
  WHERE TRANGRP NOT IN (SELECT TRANGRP FROM  #TEMP_TRANS_SGST_INPUT T WHERE  T.SGST<>0 )

-- IGST ENTRIES 

SELECT TRANGRP,SUM(IGST_AMOUNT) IGST
INTO #GST_PURCHASE_IGST_INPUT 
FROM BI.PURCHASEHISTORY
WHERE FINYEAR = @YEAR AND PERIOD BETWEEN @STARTPERIOD AND @ENDPERIOD AND GSTTYPE ='INPUT' AND IGST_AMOUNT <>0 AND ORGID NOT IN (28,29) GROUP BY TRANGRP 

DELETE FROM #GST_PURCHASE_IGST_INPUT WHERE IGST=0 

SELECT 'ITME IN PURCHASE HISTORY NOT IN TRANS - IGST '
SELECT * FROM #GST_PURCHASE_IGST_INPUT G3 
 WHERE TRANGRP NOT IN (SELECT TRANGRP FROM  #TEMP_TRANS_IGST_INPUT T WHERE  T.IGST<>0 )



SELECT ' *****  OUTPUT  **********************'
-- CGST OUTPUT 

SELECT 
  TRANGRP,SUM(DEBIT-CREDIT) CGST 
  INTO #TEMP_TRANS_CGST_OUTPUT
  FROM 
    TRANSACTIONS  
  WHERE 
    YEAR=@YEAR AND PERIOD BETWEEN @STARTPERIOD AND @ENDPERIOD AND LEDGERCODE='1310028' AND ORGID NOT IN (28,29) 
  GROUP BY TRANGRP ORDER BY TRANGRP 


SELECT
  TRANGRP,SUM(CGST_AMOUNT) CGST 
  INTO #TEMP_SALES_OUTPUT_CGST
  FROM BI.SALESHISTORY
WHERE 
    FINYEAR=@YEAR AND PERIOD BETWEEN @STARTPERIOD AND @ENDPERIOD AND GSTTYPE='OUTPUT' AND ORGID NOT IN (28,29) AND
    TRANGRP IN ( SELECT TRANGRP  FROM #TEMP_TRANS_CGST_OUTPUT )
GROUP BY 
   TRANGRP ORDER BY TRANGRP 

SELECT 'MISSING TRANSGROUP IN CGST SALES ' 
SELECT * FROM #TEMP_TRANS_CGST_OUTPUT WHERE TRANGRP NOT IN (SELECT TRANGRP FROM #TEMP_SALES_OUTPUT_CGST) 

-- SGST 

SELECT 
  TRANGRP,SUM(DEBIT-CREDIT) SGST 
  INTO #TEMP_TRANS_SGST_OUTPUT
  FROM 
    TRANSACTIONS  
  WHERE 
    YEAR=@YEAR AND PERIOD BETWEEN @STARTPERIOD AND @ENDPERIOD AND LEDGERCODE='1310029' AND ORGID NOT IN (28,29) 
  GROUP BY TRANGRP ORDER BY TRANGRP 


SELECT
  TRANGRP,SUM(SGST_AMOUNT) SGST 
  INTO #TEMP_SALES_OUTPUT_SGST
  FROM BI.SALESHISTORY 
WHERE 
    FINYEAR=@YEAR AND PERIOD BETWEEN @STARTPERIOD AND @ENDPERIOD AND GSTTYPE='OUTPUT' AND ORGID NOT IN (28,29) AND
   TRANGRP IN ( SELECT TRANGRP  FROM #TEMP_TRANS_SGST_OUTPUT )
GROUP BY 
   TRANGRP ORDER BY TRANGRP 

SELECT 'MISSING TRANSGROUP IN SGST SALES' 
SELECT * FROM #TEMP_TRANS_SGST_OUTPUT WHERE TRANGRP NOT IN (SELECT TRANGRP FROM #TEMP_SALES_OUTPUT_SGST) 

-- IGST

SELECT 
  TRANGRP,SUM(DEBIT-CREDIT) IGST 
  INTO #TEMP_TRANS_IGST_OUTPUT
  FROM 
    TRANSACTIONS  
  WHERE 
    YEAR=@YEAR AND PERIOD BETWEEN @STARTPERIOD AND @ENDPERIOD AND LEDGERCODE='1310030' AND ORGID NOT IN (28,29) 
  GROUP BY TRANGRP ORDER BY TRANGRP 


SELECT
  TRANGRP,SUM(IGST_AMOUNT) IGST 
  INTO #TEMP_SALES_OUTPUT_IGST
  FROM BI.SALESHISTORY 
WHERE 
    FINYEAR=@YEAR AND PERIOD BETWEEN @STARTPERIOD AND @ENDPERIOD AND GSTTYPE='OUTPUT' AND ORGID NOT IN (28,29) AND
   TRANGRP IN ( SELECT TRANGRP  FROM #TEMP_TRANS_IGST_OUTPUT )
GROUP BY 
   TRANGRP ORDER BY TRANGRP 

SELECT 'MISSING TRANSGROUP IN IGST SALES' 
SELECT * FROM #TEMP_TRANS_IGST_OUTPUT WHERE TRANGRP NOT IN (SELECT TRANGRP FROM #TEMP_SALES_OUTPUT_IGST) 


SELECT 'CGST  - TRANSACTION AMOUNT DIFFERENT FROM SALES REGISTER ENTRIES '
SELECT T.*,P.*  FROM #TEMP_TRANS_CGST_OUTPUT T  INNER JOIN #TEMP_SALES_OUTPUT_CGST P  ON T.TRANGRP = P.TRANGRP WHERE ABS(T.CGST-P.CGST)>1

SELECT 'SGST  - TRANSACTION AMOUNT DIFFERENT FROM SALES REGISTER ENTRIES '
SELECT T.*,P.*  FROM #TEMP_TRANS_SGST_OUTPUT T  INNER JOIN #TEMP_SALES_OUTPUT_SGST P  ON T.TRANGRP = P.TRANGRP WHERE ABS(T.SGST-P.SGST)>1 

SELECT 'IGST  - TRANSACTION AMOUNT DIFFERENT FROM SALES REGISTER ENTRIES '
SELECT T.*,P.*  FROM #TEMP_TRANS_IGST_OUTPUT T  INNER JOIN #TEMP_SALES_OUTPUT_IGST P  ON T.TRANGRP = P.TRANGRP WHERE ABS(T.IGST-P.IGST)>1  




------- NOW THE REVERSE ---- TAKING BASE AS  SALES  ENTRY CHECKING ANY EXTRA ENTRIES IN SALES  REGISTER ----- 

-- CGST ENTRIES 

SELECT TRANGRP,SUM(CGST_AMOUNT) CGST
INTO #GST_SALES_CGST_OUTPUT 
FROM BI.PURCHASEHISTORY
WHERE FINYEAR = @YEAR AND PERIOD BETWEEN @STARTPERIOD AND @ENDPERIOD AND GSTTYPE ='OUTPUT' AND CGST_AMOUNT <>0 AND ORGID NOT IN (28,29) GROUP BY TRANGRP 

DELETE FROM #GST_SALES_CGST_OUTPUT WHERE CGST=0 

SELECT 'ITME IN SALES HISTORY NOT IN TRANS - CGST '
SELECT * FROM #GST_SALES_CGST_OUTPUT G1 
 WHERE TRANGRP NOT IN (SELECT TRANGRP FROM  #TEMP_TRANS_CGST_OUTPUT T WHERE  T.CGST<>0 )


-- SGST ENTRIES 

SELECT TRANGRP,SUM(SGST_AMOUNT) SGST
INTO #GST_SALES_SGST_OUTPUT 
FROM BI.PURCHASEHISTORY
WHERE FINYEAR = @YEAR AND PERIOD BETWEEN @STARTPERIOD AND @ENDPERIOD AND GSTTYPE ='OUTPUT' AND SGST_AMOUNT <>0 AND ORGID NOT IN (28,29) GROUP BY TRANGRP 

DELETE FROM #GST_SALES_SGST_OUTPUT WHERE SGST=0 

SELECT 'ITME IN SALES HISTORY NOT IN TRANS - SGST '
SELECT * FROM #GST_SALES_SGST_OUTPUT G2  
  WHERE TRANGRP NOT IN (SELECT TRANGRP FROM  #TEMP_TRANS_SGST_OUTPUT T WHERE  T.SGST<>0 )

-- IGST ENTRIES 

SELECT TRANGRP,SUM(IGST_AMOUNT) IGST
INTO #GST_SALES_IGST_OUTPUT 
FROM BI.PURCHASEHISTORY
WHERE FINYEAR = @YEAR AND PERIOD BETWEEN @STARTPERIOD AND @ENDPERIOD AND GSTTYPE ='OUTPUT' AND IGST_AMOUNT <>0 AND ORGID NOT IN (28,29) GROUP BY TRANGRP 

DELETE FROM #GST_SALES_IGST_OUTPUT WHERE IGST=0 

SELECT 'ITME IN SALES HISTORY NOT IN TRANS - IGST '
SELECT * FROM #GST_SALES_IGST_OUTPUT G3 
 WHERE TRANGRP NOT IN (SELECT TRANGRP FROM  #TEMP_TRANS_IGST_OUTPUT T WHERE  T.IGST<>0 )