/****** Object:  Procedure [BI].[spDEBTORDONETRANS]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE [BI].[spDEBTORDONETRANS](@FINYEAR INT,@LEDGERCODE VARCHAR(10))
AS
SELECT 
 DISTINCT CREDNO  
 INTO #TEMP0 
 FROM TRANSACTIONS WHERE  LEDGERCODE=@LEDGERCODE AND 
 ORGID  IN (SELECT BORGID FROM BORGS WHERE PARENTBORG IN (23,24,25,26,27) )
ALTER TABLE #TEMP0 ADD CREDNAME VARCHAR(150)
UPDATE #TEMP0 SET CREDNAME = C.DEBTNAME FROM DEBTORS C INNER JOIN #TEMP0 ON #TEMP0.CREDNO=C.DEBTNUMBER
UPDATE #TEMP0 SET CREDNAME =LTRIM(RTRIM(CREDNAME))+ ' ('+ LTRIM(RTRIM(CREDNO)) + ')'
DELETE FROM #TEMP0 WHERE CREDNO IS NULL
UPDATE #TEMP0 SET CREDNAME = 'UNKNOWN' WHERE CREDNAME IS NULL 
SELECT CREDNO CREDNUMBER, CREDNAME   FROM #TEMP0 ORDER BY CREDNAME


--YEAR=@FINYEAR AND  Modifed on 11 April 2017; Just removed the Year Constraints