/****** Object:  Procedure [BI].[spDEBTORSDONETRANS]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE [BI].[spDEBTORSDONETRANS](@FINYEAR INT)
AS
DECLARE @DEBTOR_F VARCHAR(10)
DECLARE @DEBTOR_T VARCHAR(10)
SELECT @DEBTOR_F = CONTROLFROMGL FROM CONTROLCODES WHERE CONTROLNAME='Debtors'
SELECT @DEBTOR_T = CONTROLFROMGL FROM CONTROLCODES WHERE CONTROLNAME='Debtors'
SELECT 
 DISTINCT CREDNO  
 INTO #TEMP0 
 FROM TRANSACTIONS WHERE YEAR=@FINYEAR AND LEDGERCODE BETWEEN @DEBTOR_F AND @DEBTOR_T  AND 
 ORGID  IN (SELECT BORGID FROM BORGS WHERE PARENTBORG IN (23,24,25,26) )
ALTER TABLE #TEMP0 ADD CREDNAME VARCHAR(150)
UPDATE #TEMP0 SET CREDNAME = C.DEBTNAME FROM DEBTORS C INNER JOIN #TEMP0 ON #TEMP0.CREDNO=C.DEBTNUMBER
UPDATE #TEMP0 SET CREDNAME =LTRIM(RTRIM(CREDNAME))+ ' ('+ LTRIM(RTRIM(CREDNO)) + ')'
DELETE FROM #TEMP0 WHERE CREDNO IS NULL
UPDATE #TEMP0 SET CREDNAME = 'UNKNOWN' WHERE CREDNAME IS NULL 
SELECT CREDNO CREDNUMBER, CREDNAME   FROM #TEMP0 ORDER BY CREDNAME