/****** Object:  Procedure [BI].[spDebtorRegister]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE [BI].[spDebtorRegister] (@FINYEAR INT, @FROMPERIOD INT,@TOPERIOD INT , @LISTCREDITORS  LISTCREDNUMBERS  READONLY  ,@LISTORGIDS  LISTORGIDS READONLY   )
As
 --DECLARE @FINYEAR INT
 --DECLARE @FROMPERIOD INT
 --DECLARE @TOPERIOD INT

 --SET @FINYEAR=2017
 --SET @FROMPERIOD = 8
 --SET @TOPERIOD = 8

DECLARE @COLID INT
DECLARE @EXISTING INT
DECLARE @COLTEXT VARCHAR(50)
DECLARE @VATCONTROL_FROM  VARCHAR(10)
DECLARE @VATCONTROL_TO    VARCHAR(10)
DECLARE @RETAINED VARCHAR(10)
DECLARE @WIP VARCHAR(10)
DECLARE @CREDITORCONTROL VARCHAR(10)
DECLARE @CREDITOR_LEDGER VARCHAR(10)
DECLARE @SUBBIE_LEDGER VARCHAR(10)
DECLARE @STOCK_FROM VARCHAR(10)
DECLARE @STOCK_TO VARCHAR(10)
DECLARE @LEDGERCODE VARCHAR(10)
DECLARE @LEDGERNAME VARCHAR(50)
DECLARE @COLUMHEADING   VARCHAR(50)
DECLARE @DEBTOR_LEDGER_F VARCHAR(10)
DECLARE @DEBTOR_LEDGER_L VARCHAR(10) 


 
SELECT @CREDITOR_LEDGER = CONTROLFROMGL FROM CONTROLCODES WHERE CONTROLNAME='Creditors'
SELECT @SUBBIE_LEDGER = CONTROLFROMGL FROM CONTROLCODES WHERE CONTROLNAME = 'Sub Contractors'
SELECT @DEBTOR_LEDGER_F = CONTROLFROMGL FROM CONTROLCODES WHERE CONTROLNAME='Debtors'
SELECT @DEBTOR_LEDGER_L = CONTROLTOGL   FROM CONTROLCODES WHERE CONTROLNAME='Debtors'

SELECT @RETAINED = CONTROLFROMGL FROM CONTROLCODES WHERE CONTROLNAME='Retained Income'
SELECT @WIP = CONTROLFROMGL FROM CONTROLCODES WHERE CONTROLNAME='Work In Progress'
SELECT @VATCONTROL_FROM = CONTROLFROMGL FROM CONTROLCODES WHERE CONTROLNAME='Value Added Tax'
SELECT @VATCONTROL_TO = CONTROLTOGL FROM CONTROLCODES WHERE CONTROLNAME='Value Added Tax'


CREATE TABLE #DEBTORS(CREDNUMBER VARCHAR(10))
INSERT INTO #DEBTORS  
 SELECT CREDNUMBER FROM @LISTCREDITORS 
 
DELETE FROM #DEBTORS WHERE CREDNUMBER IS NULL 


CREATE TABLE #DEBTORLEDGERS(DEBTORCONTROLCODES VARCHAR(10))
INSERT INTO #DEBTORLEDGERS 
SELECT LEDGERCODE FROM LEDGERCODES WHERE LEDGERCODE BETWEEN @DEBTOR_LEDGER_F AND @DEBTOR_LEDGER_L

CREATE TABLE #BORGS(ORGID INT)
INSERT INTO #BORGS  
 SELECT ORGID  FROM @LISTORGIDS
 
DELETE FROM #BORGS WHERE ORGID IS NULL
 

-- TO FINDOUT WHICH ARE ALL THE LEDGERS IN THE TRANSGROUPS WHERE DEBTOR CONTROLCODE INVOLVED - FIRST STEP EXTRACT TRANSGROUPS
SELECT 
 DISTINCT  T.TRANGRP 
INTO 
 #TRANGRPMASTER 
FROM 
 TRANSACTIONS T 
WHERE 
 T.YEAR=@FINYEAR AND 
 T.PERIOD BETWEEN @FROMPERIOD AND @TOPERIOD AND 
 T.LEDGERCODE IN (SELECT DEBTORCONTROLCODES FROM #DEBTORLEDGERS ) AND
 T.ORGID IN (SELECT ORGID FROM #BORGS) AND 
 T.CREDNO IN (SELECT CREDNO FROM #DEBTORS) 

-- STEP 2 - EXTRACT LEDGERCODES 
SELECT DISTINCT LEDGERCODE 
INTO #LEDGERCODELIST 
FROM TRANSACTIONS 
WHERE TRANGRP IN (SELECT TRANGRP FROM  #TRANGRPMASTER )


--STEP 3  - DEBTOR AMOUNT
SELECT 
 TRANGRP,
 SUM(DEBIT-CREDIT) NETAMOUNT 
INTO 
 #NETAMOUNT
FROM 
 TRANSACTIONS 
WHERE 
 TRANGRP IN (SELECT TRANGRP FROM  #TRANGRPMASTER) 
GROUP BY 
 TRANGRP 

 

SELECT 
 T.TRANGRP,
 T.ORGID,
 B.BORGNAME,
 T.YEAR,
 T.PERIOD,
 P.PERIODDESC,
 T.BATCHREF,
 T.PDATE ,
 T.TRANSREF,
 T.LEDGERCODE,
 LEFT(L.LEDGERNAME,15) LEDGERNAME,
 123456789 AS DEBTORCODE,
 T.CREDNO,
 D.DEBTNAME  ,
 T.DEBIT,
 T.CREDIT 
INTO #TEMP0 
FROM
 TRANSACTIONS T 
 INNER JOIN BORGS B ON T.ORGID = B.BORGID 
 INNER JOIN PERIODMASTER P ON T.PERIOD=P.PERIODID 
 LEFT  JOIN DEBTORS D ON T.CREDNO=D.DEBTNUMBER
 INNER JOIN LEDGERCODES L ON T.LEDGERCODE=L.LEDGERCODE
WHERE 
 TRANGRP IN (SELECT TRANGRP FROM #TRANGRPMASTER  )
 
DELETE FROM #TEMP0 WHERE LEDGERCODE   IN (@WIP,@RETAINED) 

UPDATE #TEMP0 SET DEBTORCODE = D.DEBTCONTROL FROM DEBTORS D INNER JOIN #TEMP0 ON #TEMP0.CREDNO=D.DEBTNUMBER 

UPDATE #TEMP0 SET LEDGERNAME = LEFT(LEDGERNAME,15)

SELECT 
 TRANGRP,
 ORGID,
 BORGNAME,
 YEAR,
 PERIOD,
 PERIODDESC,
 BATCHREF,
 PDATE ,
 TRANSREF,
 LEDGERCODE,
 LTRIM(RTRIM(LEDGERCODE))+'-'+LTRIM(RTRIM(LEDGERNAME)) LEDGERNAME ,
 DEBTORCODE,
 CREDNO,
 DEBTNAME  ,
 DEBIT,
 CREDIT 
INTO #TEMP1 
FROM #TEMP0 


   -- DEBTORCODE   AS   DEBTORCODE,
SELECT 
 TRANGRP      AS   TRANGRP,
 BATCHREF     AS   BATCHREF,
 TRANSREF     AS   INVOICENO,
 DEBTORCODE   AS   DEBTORCODE,
 DEBTNAME     AS   SUPPLIER,
 ORGID        AS   ORGID,
 PERIOD       AS   PERIODID,
 PERIODDESC   AS   PERIOD,
 PDATE        AS   INVOICEDATE,
 LEDGERCODE   AS   LEDGERCODE,
 LEDGERNAME   AS   LEDGERNAME,
 SUM(DEBIT-CREDIT) AS AMOUNT 
INTO 
 #FINAL
FROM
 #TEMP1 
GROUP BY
 TRANGRP,BATCHREF,TRANSREF,DEBTORCODE,DEBTNAME,ORGID,PERIOD,PERIODDESC,PDATE,LEDGERCODE,LEDGERNAME 
ORDER BY
 LEDGERCODE 


ALTER TABLE #FINAL ADD PROJECT VARCHAR(100)
UPDATE #FINAL SET PROJECT = LEFT(B.BORGNAME,100) 
FROM BORGS B 
INNER JOIN #FINAL ON  B.BORGID = #FINAL.ORGID 

-- ADD COLUMN FOR NET AMOUNT
ALTER TABLE #FINAL ADD NETAMOUNT DECIMAL(18,2)
UPDATE #FINAL SET NETAMOUNT = N.NETAMOUNT 
FROM #NETAMOUNT N 
INNER JOIN #FINAL ON #FINAL.TRANGRP = N.TRANGRP 

 
Exec [BI].[CrossTab]  'SELECT * FROM #FINAL', 'LEDGERNAME','SUM(AMOUNT ELSE 0)[]','TRANGRP,DEBTORCODE,SUPPLIER,PROJECT,PERIODID,PERIOD,BATCHREF,INVOICENO,INVOICEDATE,NETAMOUNT' 
 
 

 