/****** Object:  Procedure [BI].[spFetchPODetails]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE [BI].[spFetchPODetails](@ORDERNUMBER VARCHAR(35))
AS
BEGIN
DECLARE @EXISTING INT 
DECLARE @ORDID INT

SET @EXISTING = 0
SELECT @EXISTING = COUNT(*) FROM ORD WHERE ORDNUMBER=@ORDERNUMBER 
 

IF @EXISTING >0 
 BEGIN
   
    SELECT @ORDID=ORDID FROM ORD WHERE ORDNUMBER=@ORDERNUMBER 

    SELECT O.ORDNUMBER,O.CREATEDATE PODATE,S.SUPPNAME SUPPLIER ,S.SUPPCODE SUPPCODE,O.ORDID
    FROM ORD O INNER JOIN SUPPLIERS S ON O.SUPPID=S.SUPPID 
    WHERE ORDID=@ORDID 

	SELECT DISTINCT REQNO AS GRNNO,TRANSREF INVOICENUMBER,PDATE AS INVOICEDATE , TRANGRP  FROM TRANSACTIONS WHERE ORDERNO=@ORDERNUMBER AND REQNO<>''
 

 END

END