/****** Object:  Procedure [BI].[spFetchWODetails]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE [BI].[spFetchWODetails](@ORDERNUMBER VARCHAR(35))
AS
BEGIN
DECLARE @EXISTING INT 
DECLARE @ORDID INT
DECLARE @SUBBIE VARCHAR(10)
DECLARE @TRANSID INT

DECLARE @INVOICEDATE DATETIME
DECLARE @INVOICEAMOUNT DECIMAL(18,2)
DECLARE @INVOICENUMBER VARCHAR(10) 

SELECT @SUBBIE= CONTROLFROMGL FROM CONTROLCODES WHERE CONTROLNAME='Sub Contractors'

SET @EXISTING = 0
SELECT @EXISTING = COUNT(*) FROM ORD WHERE ORDNUMBER=@ORDERNUMBER 
 

IF @EXISTING >0 
 BEGIN
   
    SELECT @ORDID=ORDID FROM ORD WHERE ORDNUMBER=@ORDERNUMBER 

    SELECT O.ORDNUMBER,O.CREATEDATE PODATE,S.SUPPNAME SUPPLIER ,S.SUPPCODE SUPPCODE,O.ORDID
    FROM ORD O INNER JOIN SUPPLIERS S ON O.SUPPID=S.SUPPID 
    WHERE ORDID=@ORDID 

    SELECT @INVOICEDATE =MAX(PDATE)    FROM TRANSACTIONS WHERE ORDERNO=@ORDERNUMBER 

    SELECT @INVOICENUMBER = TRANSREF FROM TRANSACTIONS  WHERE ORDERNO=@ORDERNUMBER AND PDATE=@INVOICEDATE

    SELECT @INVOICEAMOUNT = SUM(CREDIT-DEBIT)  FROM TRANSACTIONS WHERE ORDERNO=@ORDERNUMBER  AND LEDGERCODE=@SUBBIE
	IF @INVOICEAMOUNT>0 
	   SELECT @INVOICEAMOUNT AS INVOICEAMOUNT,@INVOICEDATE AS INVOICEDATE , @INVOICENUMBER AS INVOICENUMBER 

 END
ELSE
 SELECT 0 AS ORDNUMBER
END