/****** Object:  Procedure [BI].[spFetchNegativeDeliveries]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE BI.spFetchNegativeDeliveries
AS
SELECT B.BORGNAME,O.ORDNUMBER,OI.ITEMDESCRIPTION,D.LYEAR,D.PERIOD,D.GRNNO,D.DLVRNO,D.ALLOCATION,D.DLVRQTY,D.TBORGID,D.ORDID,D.ORDITEMLINENO ,D.DLVRID
FROM DELIVERIES  D INNER JOIN BORGS B ON D.TBORGID = B.BORGID 
              INNER JOIN ORD O ON D.ORDID = O.ORDID 
			  INNER JOIN ORDITEMS OI ON O.ORDID = OI.ORDID  AND OI.LINENUMBER = D.ORDITEMLINENO 
WHERE D.ALLOCATED=0 AND D.DLVRQTY <0  ORDER BY TBORGID , ORDID 