/****** Object:  Procedure [BI].[spFetchDebtRecons]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE BI.spFetchDebtRecons(@ORGID INT) 
AS
 DECLARE @LASTRECONID INT 
 DECLARE @RECONID INT 
 DECLARE @TAXPERCENTAGE DECIMAL(18,2)

 DECLARE @SCRAPSALE DECIMAL(18,2)
 DECLARE @WORKDONE DECIMAL(18,2)
 DECLARE @MOBADVANCE DECIMAL(18,2) 
 DECLARE @SECADVANCE DECIMAL(18,2)
 DECLARE @MIVANADVANCE DECIMAL(18,2) 
 DECLARE @MOBADVREC DECIMAL(18,2)
 DECLARE @SECADVREC DECIMAL(18,2)
 DECLARE @MIVADVREC DECIMAL(18,2) 
 DECLARE @TDS DECIMAL(18,2) 
 DECLARE @TDSCGST DECIMAL(18,2)
 DECLARE @TDSSGST DECIMAL(18,2) 
 DECLARE @CGST DECIMAL(18,2)
 DECLARE @SGST DECIMAL(18,2)
 DECLARE @IGST DECIMAL(18,2) 
 
 DECLARE @CGSTREC DECIMAL(18,2)
 DECLARE @SGSTREC DECIMAL(18,2)
 DECLARE @IGSTREC DECIMAL(18,2) 

 DECLARE @RETENTION DECIMAL(18,2) 

 DECLARE @TCS DECIMAL(18,2) 

 DECLARE @DUE DECIMAL(18,2) 

 DECLARE @CONTRAAMOUNT DECIMAL(18,2)
 DECLARE @CONTRATAX DECIMAL(18,2) 

 DECLARE @HEADERID INT 
 DECLARE @DETAILALREADYEXISTING INT


 DECLARE @INVOICEDATE DATETIME
 DECLARE @INVOICENUMBER VARCHAR(25) 


 SET @LASTRECONID=0
 SELECT @LASTRECONID = ISNULL(DEBTRECONID,0) FROM EI.DEBTORINVOICEHEADER WHERE BORGID=@ORGID 

 
 SELECT SUBCONNUMBER,SUPNAME,CODE,POSTED,RECONID,USERID,POSTREF,ORDERNO,RETRELEASEDATE,LOGDATETIME,POSTDATE 
 INTO #TEMPRECONS 
 FROM DEBTRECONS  
 WHERE ORGID=@ORGID AND RECONID>@LASTRECONID 
 SELECT * FROM #TEMPRECONS
 ALTER TABLE #TEMPRECONS ADD FINYEAR INT
 ALTER TABLE #TEMPRECONS ADD PERIOD  INT
 ALTER TABLE #TEMPRECONS ADD INVOICENUMBER VARCHAR(25)
 UPDATE #TEMPRECONS SET INVOICENUMBER = LTRIM(RTRIM(POSTREF))+LTRIM(RTRIM(ORDERNO)) 
 UPDATE #TEMPRECONS SET RETRELEASEDATE = POSTDATE WHERE RETRELEASEDATE IS NULL
 UPDATE #TEMPRECONS SET FINYEAR = YEAR(RETRELEASEDATE),PERIOD= MONTH(RETRELEASEDATE) 
 INSERT INTO EI.DEBTORINVOICEHEADER (DEBTRECONID,DEBTORNUMBER,BORGID,FINYEAR,PERIOD,INVOICETYPE,PARTYCODE,INVOICENUMBER,INVOICEDATE,EISTATUS,RULESETCODE,APPROVED) 
 SELECT RECONID,SUBCONNUMBER,@ORGID,FINYEAR,PERIOD,'INV','',INVOICENUMBER,RETRELEASEDATE,-1,CODE,1  FROM #TEMPRECONS

 -- CODE : 16.13  SCRAP SALES - IGST 

 DECLARE SCRAPIGST CURSOR FOR 
    SELECT INVOICEINDEX , DEBTRECONID FROM EI.DEBTORINVOICEHEADER WHERE RULESETCODE ='16.13'  AND EISTATUS=-1
 OPEN  SCRAPIGST 
 FETCH NEXT FROM SCRAPIGST INTO @HEADERID, @RECONID 
 WHILE @@FETCH_STATUS = 0 
 BEGIN
   SET @TCS = 0
   SET @CONTRAAMOUNT = 0
   SET @CONTRATAX = 0 
   SET @CGST = 0 
   SET @SGST = 0
   SET @IGST = 0 
   SET @TAXPERCENTAGE = 0
   SET @SCRAPSALE = 0
   SET @DUE = 0 
   SELECT @TAXPERCENTAGE=  PERC   FROM DEBTRECONDETAIL WHERE RECONID=@RECONID AND VARCODE ='TAX1'
   SELECT @SCRAPSALE =     MVALUE FROM DEBTRECONDETAIL WHERE RECONID=@RECONID AND VARCODE ='TGB' 
   SELECT @IGST      =     MVALUE FROM DEBTRECONDETAIL WHERE RECONID=@RECONID AND VARCODE ='TAXC' 
   SELECT @TCS       =     MVALUE FROM DEBTRECONDETAIL WHERE RECONID=@RECONID AND VARCODE ='WH2' 
   SELECT @DUE       =     MVALUE FROM DEBTRECONDETAIL WHERE RECONID=@RECONID AND VARCODE ='DUE' 
   SELECT @CONTRAAMOUNT =  MVALUE FROM DEBTRECONDETAIL WHERE RECONID=@RECONID AND VARCODE ='CC'
   SELECT @CONTRATAX    =  MVALUE FROM DEBTRECONDETAIL WHERE RECONID=@RECONID AND VARCODE ='TAX3'

   SET @DETAILALREADYEXISTING = 0
   SELECT @DETAILALREADYEXISTING = ISNULL(COUNT(*),0) FROM EI.DEBTINVOICEDETAILS WHERE HEADERID=@HEADERID 

   IF @DETAILALREADYEXISTING = 0 
     BEGIN 
	   INSERT INTO EI.DEBTINVOICEDETAILS(HEADERID,SCRAPSALE,GSTPERCENTAGE,IGST,TCS,CONTRAAMOUNT,CONTRATAX,NETRECEIVABLE)
       SELECT @HEADERID,@SCRAPSALE,@TAXPERCENTAGE,@IGST,@TCS,@CONTRAAMOUNT,@CONTRATAX,@DUE
     END
   ELSE
     BEGIN 
	   UPDATE EI.DEBTINVOICEDETAILS
	    SET SCRAPSALE = @SCRAPSALE, GSTPERCENTAGE = @TAXPERCENTAGE, 
		IGST = @IGST , TCS = @TCS , NETRECEIVABLE = @DUE ,
		CONTRAAMOUNT =@CONTRAAMOUNT, CONTRATAX=@CONTRATAX
		WHERE HEADERID=@HEADERID 
     END 
 
   SELECT @INVOICEDATE=RETRELEASEDATE,@INVOICENUMBER = LTRIM(RTRIM(POSTREF))+LTRIM(RTRIM(ORDERNO))   FROM DEBTRECONS WHERE RECONID=@RECONID 
   UPDATE EI.DEBTORINVOICEHEADER SET INVOICEDATE=@INVOICEDATE,INVOICENUMBER = @INVOICENUMBER   WHERE INVOICEINDEX = @HEADERID 
   UPDATE EI.DEBTORINVOICEHEADER SET FINYEAR = YEAR(@INVOICEDATE),PERIOD =MONTH(@INVOICEDATE) WHERE INVOICEINDEX = @HEADERID 
   UPDATE EI.DEBTORINVOICEHEADER SET APPROVED = 0 WHERE @CONTRAAMOUNT<>0 AND @CONTRATAX<>0 AND  INVOICEINDEX = @HEADERID 

   FETCH NEXT FROM SCRAPIGST INTO @HEADERID,  @RECONID 


 END
 CLOSE SCRAPIGST
 DEALLOCATE SCRAPIGST


 -- CODE : 16.14  SCRAP SALES - CGST AND SGST

 DECLARE SCRAPCGST CURSOR FOR 
    SELECT INVOICEINDEX , DEBTRECONID FROM EI.DEBTORINVOICEHEADER WHERE RULESETCODE ='16.14'  AND EISTATUS=-1
 OPEN  SCRAPCGST 
 FETCH NEXT FROM SCRAPCGST INTO @HEADERID, @RECONID 
 WHILE @@FETCH_STATUS = 0 
 BEGIN
   SET @TCS = 0
   SET @CONTRAAMOUNT = 0
   SET @CONTRATAX = 0 
   SET @CGST = 0 
   SET @SGST = 0
   SET @IGST = 0 
   SET @TAXPERCENTAGE = 0
   SET @SCRAPSALE = 0
   SET @DUE = 0 
   SELECT @TAXPERCENTAGE=  PERC   FROM DEBTRECONDETAIL WHERE RECONID=@RECONID AND VARCODE ='TAX1'
   SELECT @SCRAPSALE =     MVALUE FROM DEBTRECONDETAIL WHERE RECONID=@RECONID AND VARCODE ='TGB' 
   SELECT @CGST      =     MVALUE FROM DEBTRECONDETAIL WHERE RECONID=@RECONID AND VARCODE ='TAXC' 
   SELECT @SGST      =     MVALUE FROM DEBTRECONDETAIL WHERE RECONID=@RECONID AND VARCODE ='TAX2' 
   SELECT @TCS       =     MVALUE FROM DEBTRECONDETAIL WHERE RECONID=@RECONID AND VARCODE ='WH2' 
   SELECT @DUE       =     MVALUE FROM DEBTRECONDETAIL WHERE RECONID=@RECONID AND VARCODE ='DUE'
   SELECT @CONTRAAMOUNT =  MVALUE FROM DEBTRECONDETAIL WHERE RECONID=@RECONID AND VARCODE ='CC'
   SELECT @CONTRATAX    =  MVALUE FROM DEBTRECONDETAIL WHERE RECONID=@RECONID AND VARCODE ='TAX3'

   SET @IGST = 0 
   SET @DETAILALREADYEXISTING = 0
   SELECT @DETAILALREADYEXISTING = ISNULL(COUNT(*),0) FROM EI.DEBTINVOICEDETAILS WHERE HEADERID=@HEADERID 

   IF @DETAILALREADYEXISTING = 0 
     BEGIN 
	   INSERT INTO EI.DEBTINVOICEDETAILS(HEADERID,SCRAPSALE,GSTPERCENTAGE,CGST,SGST,IGST,TCS,CONTRAAMOUNT,CONTRATAX,NETRECEIVABLE)
       SELECT @HEADERID,@SCRAPSALE,@TAXPERCENTAGE,@CGST,@SGST,@IGST,@TCS,@CONTRAAMOUNT,@CONTRATAX ,@DUE
     END
   ELSE
     BEGIN 
	   UPDATE EI.DEBTINVOICEDETAILS
	    SET SCRAPSALE = @SCRAPSALE, 
		GSTPERCENTAGE = @TAXPERCENTAGE,
		CGST=@CGST,SGST=@SGST,IGST = @IGST , 
		TCS = @TCS , NETRECEIVABLE = @DUE, CONTRAAMOUNT =@CONTRAAMOUNT, CONTRATAX=@CONTRATAX  WHERE HEADERID=@HEADERID 
     END 
 
   SELECT @INVOICEDATE=RETRELEASEDATE,@INVOICENUMBER = LTRIM(RTRIM(POSTREF))+LTRIM(RTRIM(ORDERNO))   FROM DEBTRECONS WHERE RECONID=@RECONID 
   UPDATE EI.DEBTORINVOICEHEADER SET INVOICEDATE=@INVOICEDATE,INVOICENUMBER = @INVOICENUMBER   WHERE INVOICEINDEX = @HEADERID 
   UPDATE EI.DEBTORINVOICEHEADER SET FINYEAR = YEAR(@INVOICEDATE),PERIOD =MONTH(@INVOICEDATE) WHERE INVOICEINDEX = @HEADERID 
   UPDATE EI.DEBTORINVOICEHEADER SET APPROVED = 0 WHERE @CONTRAAMOUNT<>0 AND @CONTRATAX<>0 AND  INVOICEINDEX = @HEADERID 


   FETCH NEXT FROM SCRAPCGST INTO @HEADERID,  @RECONID 


 END
 CLOSE SCRAPCGST
 DEALLOCATE SCRAPCGST


 -- CODE : 16.21    PRIVATE CERTIFIED

 DECLARE GOVTPRIVATE  CURSOR FOR 
    SELECT INVOICEINDEX , DEBTRECONID FROM EI.DEBTORINVOICEHEADER WHERE RULESETCODE ='16.21'  AND EISTATUS=-1
 OPEN  GOVTPRIVATE 
 FETCH NEXT FROM GOVTPRIVATE INTO @HEADERID, @RECONID 
 WHILE @@FETCH_STATUS = 0 
 BEGIN
   SET @WORKDONE = 0
   SET @SCRAPSALE = 0 

   SET @MOBADVREC= 0
   SET @SECADVREC=0
   SET @MIVADVREC =0
  
   SET @TAXPERCENTAGE = 0
  
   SET @CGST = 0 
   SET @SGST = 0
   SET @IGST = 0 

   SET @CGSTREC = 0
   SET @SGSTREC = 0
   SET @IGSTREC = 0 

   SET @CONTRAAMOUNT = 0
   SET @CONTRATAX = 0 
   SET @RETENTION = 0 

   SET @TDS =0
   SET @TCS = 0
   SET @DUE = 0 

   SELECT @TAXPERCENTAGE=  PERC   FROM DEBTRECONDETAIL WHERE RECONID=@RECONID AND VARCODE ='TAXC'
   SELECT @WORKDONE  =     MVALUE FROM DEBTRECONDETAIL WHERE RECONID=@RECONID AND VARCODE ='TGB' 
   SELECT @CGST      =     MVALUE FROM DEBTRECONDETAIL WHERE RECONID=@RECONID AND VARCODE ='TAX1' 
   SELECT @SGST      =     MVALUE FROM DEBTRECONDETAIL WHERE RECONID=@RECONID AND VARCODE ='TAX2' 
   SELECT @MOBADVREC =     MVALUE FROM DEBTRECONDETAIL WHERE RECONID=@RECONID AND VARCODE ='ADV1' 
   SELECT @SECADVREC =     MVALUE FROM DEBTRECONDETAIL WHERE RECONID=@RECONID AND VARCODE ='ADV2' 
   SELECT @MIVADVREC =     MVALUE FROM DEBTRECONDETAIL WHERE RECONID=@RECONID AND VARCODE ='ADV2C' 
   SELECT @RETENTION =     MVALUE FROM DEBTRECONDETAIL WHERE RECONID=@RECONID AND VARCODE ='RET' 
   SELECT @TDS       =     MVALUE FROM DEBTRECONDETAIL WHERE RECONID=@RECONID AND VARCODE ='WH2' 
   SELECT @TCS       =     MVALUE FROM DEBTRECONDETAIL WHERE RECONID=@RECONID AND VARCODE ='WH3' 
   SELECT @DUE       =     MVALUE FROM DEBTRECONDETAIL WHERE RECONID=@RECONID AND VARCODE ='DUE'
   SELECT @CONTRAAMOUNT =  MVALUE FROM DEBTRECONDETAIL WHERE RECONID=@RECONID AND VARCODE ='CC'
   SELECT @CONTRATAX    =  MVALUE FROM DEBTRECONDETAIL WHERE RECONID=@RECONID AND VARCODE ='TAX3'
   SELECT @CGSTREC      =  MVALUE FROM DEBTRECONDETAIL WHERE RECONID=@RECONID AND VARCODE ='GSTA'
   SELECT @SGSTREC      =  MVALUE FROM DEBTRECONDETAIL WHERE RECONID=@RECONID AND VARCODE ='GSTS'
  
   SET @DETAILALREADYEXISTING = 0
   SELECT @DETAILALREADYEXISTING = ISNULL(COUNT(*),0) FROM EI.DEBTINVOICEDETAILS WHERE HEADERID=@HEADERID 

   IF @DETAILALREADYEXISTING = 0 
     BEGIN 
	   INSERT INTO EI.DEBTINVOICEDETAILS(HEADERID,WORKDONE,GSTPERCENTAGE,CGST,SGST,IGST,MOBADVRECOVERY,SECUREDADVRECOVERY,MIVANADVRECOVERY
	   ,CONTRAAMOUNT,CONTRATAX,RETENTION,TDS,TCS,NETRECEIVABLE,CGSTRECOVERY,SGSTRECOVERY,IGSTRECOVERY)
       SELECT @HEADERID,@WORKDONE,@TAXPERCENTAGE,@CGST,@SGST,@IGST,@MOBADVREC,@SECADVREC,@MIVADVREC 
	   ,@CONTRAAMOUNT,@CONTRATAX,@RETENTION,@TDS,@TCS,@DUE,@CGSTREC,@SGSTREC,@IGSTREC  
     END
   ELSE
     BEGIN 
	   UPDATE EI.DEBTINVOICEDETAILS
	    SET WORKDONE = @WORKDONE,MOBADVRECOVERY = @MOBADVREC,SECUREDADVRECOVERY=@SECADVREC,MIVANADVRECOVERY=@MIVADVREC,RETENTION=@RETENTION, 
		GSTPERCENTAGE = @TAXPERCENTAGE,
		CGST=@CGST,SGST=@SGST,IGST = @IGST , TDS=@TDS,CGSTRECOVERY =@CGSTREC, SGSTRECOVERY=@SGSTREC, IGSTRECOVERY=@IGSTREC ,
		TCS = @TCS , NETRECEIVABLE = @DUE, CONTRAAMOUNT =@CONTRAAMOUNT, CONTRATAX=@CONTRATAX  WHERE HEADERID=@HEADERID 
     END 
 
   SELECT @INVOICEDATE=RETRELEASEDATE,@INVOICENUMBER = LTRIM(RTRIM(POSTREF))+LTRIM(RTRIM(ORDERNO))   FROM DEBTRECONS WHERE RECONID=@RECONID 
   UPDATE EI.DEBTORINVOICEHEADER SET INVOICEDATE=@INVOICEDATE,INVOICENUMBER = @INVOICENUMBER  WHERE INVOICEINDEX = @HEADERID 
   UPDATE EI.DEBTORINVOICEHEADER SET FINYEAR = YEAR(@INVOICEDATE),PERIOD =MONTH(@INVOICEDATE) WHERE INVOICEINDEX = @HEADERID 
   UPDATE EI.DEBTORINVOICEHEADER SET APPROVED = 0 WHERE @CONTRAAMOUNT<>0 AND @CONTRATAX<>0 AND  INVOICEINDEX = @HEADERID 


   FETCH NEXT FROM GOVTPRIVATE INTO @HEADERID,  @RECONID 


 END
 CLOSE GOVTPRIVATE
 DEALLOCATE GOVTPRIVATE




 -- CODE : 16.23    PRIVATE CERTIFIED 

 DECLARE GOVTPRIVATE  CURSOR FOR 
    SELECT INVOICEINDEX , DEBTRECONID FROM EI.DEBTORINVOICEHEADER WHERE RULESETCODE ='16.23'  AND EISTATUS=-1
 OPEN  GOVTPRIVATE 
 FETCH NEXT FROM GOVTPRIVATE INTO @HEADERID, @RECONID 
 WHILE @@FETCH_STATUS = 0 
 BEGIN
   SET @WORKDONE = 0
   SET @SCRAPSALE = 0 

   SET @MOBADVREC= 0
   SET @SECADVREC=0
   SET @MIVADVREC =0
  
   SET @TAXPERCENTAGE = 0
  
   SET @CGST = 0 
   SET @SGST = 0
   SET @IGST = 0 

   SET @TDSCGST = 0
   SET @TDSSGST = 0 
   
   SET @CGSTREC = 0
   SET @SGSTREC = 0
   SET @IGSTREC = 0 

   SET @CONTRAAMOUNT = 0
   SET @CONTRATAX = 0 
   SET @RETENTION = 0 

   SET @TDS =0
   SET @TCS = 0
   SET @DUE = 0 

   SELECT @TAXPERCENTAGE=  PERC   FROM DEBTRECONDETAIL WHERE RECONID=@RECONID AND VARCODE ='TAXC'
   SELECT @WORKDONE  =     MVALUE FROM DEBTRECONDETAIL WHERE RECONID=@RECONID AND VARCODE ='TGB' 
   SELECT @CGST      =     MVALUE FROM DEBTRECONDETAIL WHERE RECONID=@RECONID AND VARCODE ='TAX1' 
   SELECT @SGST      =     MVALUE FROM DEBTRECONDETAIL WHERE RECONID=@RECONID AND VARCODE ='TAX2' 
   SELECT @MOBADVREC =     MVALUE FROM DEBTRECONDETAIL WHERE RECONID=@RECONID AND VARCODE ='ADV1' 
   SELECT @SECADVREC =     MVALUE FROM DEBTRECONDETAIL WHERE RECONID=@RECONID AND VARCODE ='ADV2' 
   SELECT @MIVADVREC =     MVALUE FROM DEBTRECONDETAIL WHERE RECONID=@RECONID AND VARCODE ='ADV2C' 
   SELECT @RETENTION =     MVALUE FROM DEBTRECONDETAIL WHERE RECONID=@RECONID AND VARCODE ='RET' 
   SELECT @TDS       =     MVALUE FROM DEBTRECONDETAIL WHERE RECONID=@RECONID AND VARCODE ='WH2' 
   SELECT @TCS       =     MVALUE FROM DEBTRECONDETAIL WHERE RECONID=@RECONID AND VARCODE ='WH3' 
   SELECT @DUE       =     MVALUE FROM DEBTRECONDETAIL WHERE RECONID=@RECONID AND VARCODE ='DUE'
   SELECT @CONTRAAMOUNT =  MVALUE FROM DEBTRECONDETAIL WHERE RECONID=@RECONID AND VARCODE ='CC'
   SELECT @CONTRATAX    =  MVALUE FROM DEBTRECONDETAIL WHERE RECONID=@RECONID AND VARCODE ='TAX3'
   SELECT @CGSTREC      =  MVALUE FROM DEBTRECONDETAIL WHERE RECONID=@RECONID AND VARCODE ='GSTA'
   SELECT @SGSTREC      =  MVALUE FROM DEBTRECONDETAIL WHERE RECONID=@RECONID AND VARCODE ='GSTS'
   SELECT @TDSCGST      =  MVALUE FROM DEBTRECONDETAIL WHERE RECONID=@RECONID AND VARCODE ='WHT1'
   SELECT @TDSSGST      =  MVALUE FROM DEBTRECONDETAIL WHERE RECONID=@RECONID AND VARCODE ='WHT2'
   SET @DETAILALREADYEXISTING = 0
   SELECT @DETAILALREADYEXISTING = ISNULL(COUNT(*),0) FROM EI.DEBTINVOICEDETAILS WHERE HEADERID=@HEADERID 

   IF @DETAILALREADYEXISTING = 0 
     BEGIN 
	   INSERT INTO EI.DEBTINVOICEDETAILS(HEADERID,WORKDONE,GSTPERCENTAGE,CGST,SGST,IGST,MOBADVRECOVERY,SECUREDADVRECOVERY,MIVANADVRECOVERY
	   ,CONTRAAMOUNT,CONTRATAX,RETENTION,TDS,TCS,NETRECEIVABLE,CGSTRECOVERY,SGSTRECOVERY,IGSTRECOVERY,TDSCGST,TDSSGST)
       SELECT @HEADERID,@WORKDONE,@TAXPERCENTAGE,@CGST,@SGST,@IGST,@MOBADVREC,@SECADVREC,@MIVADVREC 
	   ,@CONTRAAMOUNT,@CONTRATAX,@RETENTION,@TDS,@TCS,@DUE,@CGSTREC,@SGSTREC,@IGSTREC,@TDSCGST,@TDSSGST   
     END
   ELSE
     BEGIN 
	   UPDATE EI.DEBTINVOICEDETAILS
	    SET WORKDONE = @WORKDONE,MOBADVRECOVERY = @MOBADVREC,SECUREDADVRECOVERY=@SECADVREC,MIVANADVRECOVERY=@MIVADVREC,RETENTION=@RETENTION, 
		GSTPERCENTAGE = @TAXPERCENTAGE,
		CGST=@CGST,SGST=@SGST,IGST = @IGST , TDS=@TDS,CGSTRECOVERY =@CGSTREC, SGSTRECOVERY=@SGSTREC, IGSTRECOVERY=@IGSTREC ,
		TCS = @TCS , NETRECEIVABLE = @DUE, CONTRAAMOUNT =@CONTRAAMOUNT, CONTRATAX=@CONTRATAX ,
		TDSCGST = @TDSCGST , TDSSGST = @TDSSGST   WHERE HEADERID=@HEADERID 
     END 
 
   SELECT @INVOICEDATE=RETRELEASEDATE,@INVOICENUMBER = LTRIM(RTRIM(POSTREF))+LTRIM(RTRIM(ORDERNO))   FROM DEBTRECONS WHERE RECONID=@RECONID 
   UPDATE EI.DEBTORINVOICEHEADER SET INVOICEDATE=@INVOICEDATE,INVOICENUMBER = @INVOICENUMBER  WHERE INVOICEINDEX = @HEADERID 
   UPDATE EI.DEBTORINVOICEHEADER SET FINYEAR = YEAR(@INVOICEDATE),PERIOD =MONTH(@INVOICEDATE) WHERE INVOICEINDEX = @HEADERID 
   UPDATE EI.DEBTORINVOICEHEADER SET APPROVED = 0 WHERE @CONTRAAMOUNT<>0 AND @CONTRATAX<>0 AND  INVOICEINDEX = @HEADERID 


   FETCH NEXT FROM GOVTPRIVATE INTO @HEADERID,  @RECONID 


 END
 CLOSE GOVTPRIVATE
 DEALLOCATE GOVTPRIVATE




 -- CODE : 16.24    ADVANCE PRIVATE 

 DECLARE ADVPRIVATE   CURSOR FOR 
    SELECT INVOICEINDEX , DEBTRECONID FROM EI.DEBTORINVOICEHEADER WHERE RULESETCODE IN ('16.24','16.25')  AND EISTATUS=-1
 OPEN  ADVPRIVATE 
 FETCH NEXT FROM ADVPRIVATE INTO @HEADERID, @RECONID 
 WHILE @@FETCH_STATUS = 0 
 BEGIN
   SET @WORKDONE = 0
   SET @SCRAPSALE = 0 
   SET @MOBADVANCE =0
   SET @SECADVANCE = 0
   SET @MIVANADVANCE =0
 
   SET @MOBADVREC= 0
   SET @SECADVREC=0
   SET @MIVADVREC =0
  
   SET @TAXPERCENTAGE = 0
  
   SET @CGST = 0 
   SET @SGST = 0
   SET @IGST = 0 

   SET @TDSCGST = 0
   SET @TDSSGST = 0 
   
   SET @CGSTREC = 0
   SET @SGSTREC = 0
   SET @IGSTREC = 0 

   SET @CONTRAAMOUNT = 0
   SET @CONTRATAX = 0 
   SET @RETENTION = 0 

   SET @TDS =0
   SET @TCS = 0
   SET @DUE = 0 

   SELECT @TAXPERCENTAGE=  PERC   FROM DEBTRECONDETAIL WHERE RECONID=@RECONID AND VARCODE ='TAXC'
  
   SELECT @CGST      =     MVALUE FROM DEBTRECONDETAIL WHERE RECONID=@RECONID AND VARCODE ='TAX1' 
   SELECT @SGST      =     MVALUE FROM DEBTRECONDETAIL WHERE RECONID=@RECONID AND VARCODE ='TAX2' 
   SELECT @MOBADVANCE =     MVALUE FROM DEBTRECONDETAIL WHERE RECONID=@RECONID AND VARCODE ='ADV1' 
   SELECT @SECADVANCE =     MVALUE FROM DEBTRECONDETAIL WHERE RECONID=@RECONID AND VARCODE ='ADV2' 
   SELECT @MIVANADVANCE =   MVALUE FROM DEBTRECONDETAIL WHERE RECONID=@RECONID AND VARCODE ='ADV3' 
   SELECT @RETENTION =     MVALUE FROM DEBTRECONDETAIL WHERE RECONID=@RECONID AND VARCODE ='RET' 
   SELECT @TDS       =     MVALUE FROM DEBTRECONDETAIL WHERE RECONID=@RECONID AND VARCODE ='WH2' 
   SELECT @TCS       =     MVALUE FROM DEBTRECONDETAIL WHERE RECONID=@RECONID AND VARCODE ='WH3' 
   SELECT @DUE       =     MVALUE FROM DEBTRECONDETAIL WHERE RECONID=@RECONID AND VARCODE ='DUE'
   SELECT @CONTRAAMOUNT =  MVALUE FROM DEBTRECONDETAIL WHERE RECONID=@RECONID AND VARCODE ='CC'
   SELECT @CONTRATAX    =  MVALUE FROM DEBTRECONDETAIL WHERE RECONID=@RECONID AND VARCODE ='TAX3'
   SELECT @TDSCGST      =  MVALUE FROM DEBTRECONDETAIL WHERE RECONID=@RECONID AND VARCODE ='WHT1'
   SELECT @TDSSGST      =  MVALUE FROM DEBTRECONDETAIL WHERE RECONID=@RECONID AND VARCODE ='WHT2'
   SET @DETAILALREADYEXISTING = 0
   SELECT @DETAILALREADYEXISTING = ISNULL(COUNT(*),0) FROM EI.DEBTINVOICEDETAILS WHERE HEADERID=@HEADERID 

   IF @DETAILALREADYEXISTING = 0 
     BEGIN 
	   INSERT INTO EI.DEBTINVOICEDETAILS(HEADERID,WORKDONE,MOBADVANCE,SECUREDADVANCE,MIVANADVANCE,
	   GSTPERCENTAGE,CGST,SGST,IGST,MOBADVRECOVERY,SECUREDADVRECOVERY,MIVANADVRECOVERY
	   ,CONTRAAMOUNT,CONTRATAX,RETENTION,TDS,TCS,NETRECEIVABLE,CGSTRECOVERY,SGSTRECOVERY,IGSTRECOVERY,TDSCGST,TDSSGST)
       SELECT @HEADERID,@WORKDONE,@MOBADVANCE,@SECADVANCE,@MIVANADVANCE,
	   @TAXPERCENTAGE,@CGST,@SGST,@IGST,@MOBADVREC,@SECADVREC,@MIVADVREC 
	   ,@CONTRAAMOUNT,@CONTRATAX,@RETENTION,@TDS,@TCS,@DUE,@CGSTREC,@SGSTREC,@IGSTREC,@TDSCGST,@TDSSGST   
     END
   ELSE
     BEGIN 
	   UPDATE EI.DEBTINVOICEDETAILS
	    SET WORKDONE = @WORKDONE,MOBADVRECOVERY = @MOBADVREC,SECUREDADVRECOVERY=@SECADVREC,MIVANADVRECOVERY=@MIVADVREC,RETENTION=@RETENTION, 
		GSTPERCENTAGE = @TAXPERCENTAGE,
		CGST=@CGST,SGST=@SGST,IGST = @IGST , TDS=@TDS,CGSTRECOVERY =@CGSTREC, SGSTRECOVERY=@SGSTREC, IGSTRECOVERY=@IGSTREC ,
		TCS = @TCS , NETRECEIVABLE = @DUE, CONTRAAMOUNT =@CONTRAAMOUNT, CONTRATAX=@CONTRATAX ,MOBADVANCE=@MOBADVANCE,SECUREDADVANCE=@SECADVANCE,
		MIVANADVANCE=@MIVANADVANCE,TDSCGST = @TDSCGST , TDSSGST = @TDSSGST   WHERE HEADERID=@HEADERID 
     END 
 
   SELECT @INVOICEDATE=RETRELEASEDATE,@INVOICENUMBER = LTRIM(RTRIM(POSTREF))+LTRIM(RTRIM(ORDERNO))   FROM DEBTRECONS WHERE RECONID=@RECONID 
   UPDATE EI.DEBTORINVOICEHEADER SET INVOICEDATE=@INVOICEDATE,INVOICENUMBER = @INVOICENUMBER  WHERE INVOICEINDEX = @HEADERID 
   UPDATE EI.DEBTORINVOICEHEADER SET FINYEAR = YEAR(@INVOICEDATE),PERIOD =MONTH(@INVOICEDATE) WHERE INVOICEINDEX = @HEADERID 
   UPDATE EI.DEBTORINVOICEHEADER SET APPROVED = 0 WHERE @CONTRAAMOUNT<>0 AND @CONTRATAX<>0 AND  INVOICEINDEX = @HEADERID 


   FETCH NEXT FROM ADVPRIVATE INTO @HEADERID,  @RECONID 


 END
 CLOSE ADVPRIVATE
 DEALLOCATE ADVPRIVATE








UPDATE EI.DEBTINVOICEDETAILS SET MOBADVANCE=0 WHERE MOBADVANCE IS NULL
UPDATE EI.DEBTINVOICEDETAILS SET SECUREDADVANCE=0 WHERE SECUREDADVANCE IS NULL 
UPDATE EI.DEBTINVOICEDETAILS SET MIVANADVANCE=0 WHERE MIVANADVANCE IS NULL 
UPDATE EI.DEBTINVOICEDETAILS SET WORKDONE=0 WHERE WORKDONE IS NULL
UPDATE EI.DEBTINVOICEDETAILS SET SCRAPSALE=0 WHERE SCRAPSALE IS NULL
UPDATE EI.DEBTINVOICEDETAILS SET MOBADVRECOVERY=0 WHERE MOBADVRECOVERY IS NULL 
UPDATE EI.DEBTINVOICEDETAILS SET SECUREDADVRECOVERY=0 WHERE SECUREDADVRECOVERY IS NULL 
UPDATE EI.DEBTINVOICEDETAILS SET MIVANADVRECOVERY=0 WHERE MIVANADVRECOVERY IS NULL
UPDATE EI.DEBTINVOICEDETAILS SET CGST=0 WHERE CGST IS NULL 
UPDATE EI.DEBTINVOICEDETAILS SET SGST=0 WHERE SGST IS NULL 
UPDATE EI.DEBTINVOICEDETAILS SET IGST=0 WHERE IGST IS NULL
UPDATE EI.DEBTINVOICEDETAILS SET CONTRAAMOUNT=0 WHERE CONTRAAMOUNT IS NULL 
UPDATE EI.DEBTINVOICEDETAILS SET RETENTION=0 WHERE RETENTION IS NULL 
UPDATE EI.DEBTINVOICEDETAILS SET TDS=0 WHERE TDS IS NULL 
UPDATE EI.DEBTINVOICEDETAILS SET TCS=0 WHERE TCS IS NULL 
UPDATE EI.DEBTINVOICEDETAILS SET CONTRATAX = 0 WHERE CONTRATAX IS NULL 
UPDATE EI.DEBTINVOICEDETAILS SET CGSTRECOVERY = 0 WHERE CGSTRECOVERY IS NULL
UPDATE EI.DEBTINVOICEDETAILS SET SGSTRECOVERY = 0 WHERE SGSTRECOVERY IS NULL
UPDATE EI.DEBTINVOICEDETAILS SET IGSTRECOVERY = 0 WHERE IGSTRECOVERY IS NULL
UPDATE EI.DEBTINVOICEDETAILS SET CONTRAAMOUNT = CONTRAAMOUNT - CONTRATAX WHERE CONTRATAX <>0 
UPDATE EI.DEBTINVOICEDETAILS SET TDSCGST = 0 WHERE TDSCGST IS NULL
UPDATE EI.DEBTINVOICEDETAILS SET TDSSGST = 0 WHERE TDSSGST IS NULL
 
SELECT * FROM EI.DEBTORINVOICEHEADER ORDER BY RULESETCODE 
SELECT * FROM EI.DEBTINVOICEDETAILS