/****** Object:  Procedure [BI].[spFetchAttributes]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE  PROCEDURE [BI].[spFetchAttributes](@ASSETID  INT)
AS
BEGIN




DECLARE @ORDID INT 
DECLARE @GRN VARCHAR(25)
DECLARE @INVOICENUMBER VARCHAR(25)
DECLARE @ORDERNUMBER VARCHAR(50)
DECLARE @DUTYBENEFITS DECIMAL(18,2)
DECLARE @FEREVALUATION DECIMAL(18,2) 
DECLARE @PONUMBER VARCHAR(25)
DECLARE @PODATE DATE
DECLARE @SUPPLIERCODE VARCHAR(10)
DECLARE @SUPPLIERNAME VARCHAR(200)
DECLARE @INVOICEDATE DATE
DECLARE @INVOICEAMOUNT DECIMAL(18,2)
DECLARE @ORDERTYPE INT;
DECLARE @TAXAMOUNT DECIMAL(18,2) 

SET @ORDID=0

SELECT @ORDID =ISNULL( VALUE,0)  FROM ATTRIBVALUE WHERE TABLENAME='Assets' and ATTRIBUTE='ORDID'  AND COLKEY=@ASSETID 
IF @ORDID <> 0
 BEGIN
   SELECT @GRN = VALUE FROM ATTRIBVALUE WHERE TABLENAME='Assets' and ATTRIBUTE='GRN'  AND COLKEY=@ASSETID 
   SELECT @INVOICENUMBER = VALUE FROM ATTRIBVALUE WHERE TABLENAME='Assets' and ATTRIBUTE='INVOICENO'  AND COLKEY=@ASSETID 
   SELECT @DUTYBENEFITS = VALUE FROM ATTRIBVALUE WHERE TABLENAME='Assets' and ATTRIBUTE='DUTYBENEFITS'  AND COLKEY=@ASSETID 
   SELECT @FEREVALUATION = VALUE FROM ATTRIBVALUE WHERE TABLENAME='Assets' and ATTRIBUTE='FEREVALUATION'  AND COLKEY=@ASSETID 

   SELECT @PONUMBER = VALUE FROM ATTRIBVALUE WHERE TABLENAME='Assets' and ATTRIBUTE='PONUMBER'  AND COLKEY=@ASSETID 
   SELECT @PODATE = VALUE FROM ATTRIBVALUE WHERE TABLENAME='Assets' and ATTRIBUTE='PODATE'  AND COLKEY=@ASSETID 
   SELECT @SUPPLIERCODE = VALUE FROM ATTRIBVALUE WHERE TABLENAME='Assets' and ATTRIBUTE='SUPPLIERCODE'  AND COLKEY=@ASSETID 
   SELECT @SUPPLIERNAME = VALUE FROM ATTRIBVALUE WHERE TABLENAME='Assets' and ATTRIBUTE='SUPPLIERNAME'  AND COLKEY=@ASSETID 
   SELECT @INVOICEDATE = VALUE FROM ATTRIBVALUE WHERE TABLENAME='Assets' and ATTRIBUTE='INVOICEDATE'  AND COLKEY=@ASSETID 
   SELECT @INVOICEAMOUNT = VALUE FROM ATTRIBVALUE WHERE TABLENAME='Assets' and ATTRIBUTE='INVOICEAMOUNT'  AND COLKEY=@ASSETID 

   SELECT @ORDERTYPE = VALUE FROM ATTRIBVALUE WHERE TABLENAME='Assets' and ATTRIBUTE='ORDERTYPE'  AND COLKEY=@ASSETID 
   SELECT @TAXAMOUNT = VALUE FROM ATTRIBVALUE WHERE TABLENAME='Assets' and ATTRIBUTE='TAXAMOUNT'  AND COLKEY=@ASSETID 


   SELECT @ORDERNUMBER = ORDNUMBER FROM ORD WHERE ORDID=@ORDID 
   SELECT @ASSETID AS ASSETID,@ORDID AS ORDID ,@ORDERNUMBER AS ORDERNUMBER ,@GRN AS GRN ,
          @INVOICENUMBER AS INVOICENUMBER,@DUTYBENEFITS AS DUTYBENEFITS ,@FEREVALUATION AS FEREVALUATION ,
		  @PONUMBER AS PONUMBER,@PODATE AS PODATE,@SUPPLIERCODE AS SUPPLIERCODE,@SUPPLIERNAME AS SUPPLIERNAME,
		  @INVOICEDATE AS INVOICEDATE, @INVOICEAMOUNT AS INVOICEAMOUNT , @ORDERTYPE AS ORDERTYPE, @TAXAMOUNT AS TAXAMOUNT
 END
ELSE
 SELECT @ASSETID,0 AS ORDID,0 AS ORDERNUMBER,0 AS GRN,0 AS INVOICENUMBER,0 AS DUTYBENEFITS,0 AS FEREVALUATION

  

END