/****** Object:  Procedure [BI].[spGetPeriodToLastDepreciated]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE [BI].[spGetPeriodToLastDepreciated](@FINYEAR INT)
as
DECLARE @CURRENTDEPYEAR INT
DECLARE @CURRENTDEPMONTH INT
SELECT @CURRENTDEPYEAR = DEPYEAR ,@CURRENTDEPMONTH = DEPMONTH FROM  BI.ASSETDEPHISTORY WHERE ACTIVEMONTH=1
IF (@FINYEAR=@CURRENTDEPYEAR) 
   SELECT DEPMONTH PERIODID,DEPMONTHNAME PERIODDESC FROM  BI.ASSETDEPHISTORY WHERE DEPMONTH<=@CURRENTDEPMONTH AND
   DEPYEAR = @FINYEAR ORDER BY HISTORYID 
ELSE
   SELECT DEPMONTH PERIODID,DEPMONTHNAME PERIODDESC FROM  BI.ASSETDEPHISTORY WHERE 
   DEPYEAR = @FINYEAR ORDER BY HISTORYID 