/****** Object:  Procedure [BI].[spGetLedgerAmount]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE [BI].[spGetLedgerAmount](@BORGID INT, @FINYEAR INT, @FROMPERIOD INT, @TOPERIOD INT)
AS

--SELECT LEDGERCODE,SUM(DEBIT-CREDIT) TOTALLEDGERAMOUNT 
--FROM TRANSACTIONS 
--WHERE ORGID = @BORGID AND PERIOD BETWEEN @FROMPERIOD AND @TOPERIOD 
--GROUP BY LEDGERCODE 

SELECT 
  T.ORGID,
  B.BORGNAME,
  T.PDATE,
  T.PERIOD,
  T.BATCHREF,
  T.TRANSREF,
  T.TRANSTYPE,
  T.LEDGERCODE,
  G.MAJORGROUP,
  G.MINORGROUP,
  G.SHEETCODE,
  L.LEDGERNAME,
  T.DESCRIPTION,
  T.CREDNO,
  [BS].[fnGetParty](T.CREDNO) PARTY,
  T.STORE,
  T.Stockno,
  T.Quantity,
  T.RATE,
  T.ORDERNO,
  T.USERID,
  T.SYSDATE ,
  T.TRANGRP
FROM
  TRANSACTIONS T
  INNER JOIN LEDGERCODES L ON T.LEDGERCODE=L.LEDGERCODE 
  INNER JOIN BORGS B ON T.ORGID = B.BORGID 
  INNER JOIN BI.LEDGERGROUPS G ON G.LEDGERCODE = T.LEDGERCODE 
WHERE 
   T.ORGID  = @BORGID AND
   T.PERIOD BETWEEN @FROMPERIOD AND @TOPERIOD 