/****** Object:  Procedure [BI].[spGetBorgsSelected]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE procedure [BI].[spGetBorgsSelected](@ZoneNames varchar(255))
AS

CREATE TABLE #TEMP0(BORGID INT,BORGNAME VARCHAR(100))

CREATE TABLE #ZONENAMES(ZONENAME  VARCHAR(50))

INSERT INTO #ZONENAMES 
SELECT * FROM [dbo].[Split](@ZoneNames,',') 
DELETE FROM #ZONENAMES WHERE ZONENAME IS NULL 

ALTER TABLE #ZONENAMES ADD   PARENTBORG INT 
UPDATE #ZONENAMES SET PARENTBORG = 23  WHERE ZONENAME='North Zone'
UPDATE #ZONENAMES SET PARENTBORG = 24  WHERE ZONENAME='South Zone'
UPDATE #ZONENAMES SET PARENTBORG = 25  WHERE ZONENAME='East Zone'
UPDATE #ZONENAMES SET PARENTBORG = 26  WHERE ZONENAME='West Zone' 
UPDATE #ZONENAMES SET PARENTBORG = 27  WHERE ZONENAME='Joint Ventures' 
UPDATE #ZONENAMES SET PARENTBORG = 172 WHERE ZONENAME='BSNL' 
UPDATE #ZONENAMES SET PARENTBORG = 26  WHERE ZONENAME='Corporate' 
UPDATE #ZONENAMES SET PARENTBORG = 209 WHERE ZONENAME='CIDCO' 

DECLARE @CORPORATESELECTED  INT
SET @CORPORATESELECTED = 0
SELECT @CORPORATESELECTED = COUNT(*) FROM #ZONENAMES WHERE ZONENAME = 'Corporate' 

DECLARE @WESTZONESELECTED INT
SET @WESTZONESELECTED = 0
SELECT @WESTZONESELECTED=COUNT(*) FROM #ZONENAMES  WHERE ZONENAME='West Zone' 

IF UPPER(@ZONENAMES)='CORPORATE' 
    INSERT INTO #TEMP0 
    SELECT BORGID,BORGNAME FROM BORGS WHERE BORGID=2 
ELSE 
  BEGIN 
	INSERT INTO #TEMP0 
    SELECT BORGID,BORGNAME FROM BORGS WHERE PARENTBORG IN (SELECT PARENTBORG FROM #ZONENAMES)  
	IF @WESTZONESELECTED = 1
	   DELETE FROM  #TEMP0  WHERE BORGID=2  
	IF @CORPORATESELECTED = 1 
	   INSERT INTO #TEMP0  
	     SELECT BORGID,BORGNAME FROM BORGS WHERE BORGID=2 
 END 
DECLARE @CNT INT
SELECT @CNT=COUNT(*) FROM #TEMP0
IF @CNT = 0 
   INSERT INTO #TEMP0 VALUES  (0,'No Projects' )

SELECT * FROM #TEMP0  ORDER BY BORGNAME
SELECT DISTINCT COMPREG FROM BORGS WHERE BORGID IN (SELECT BORGID FROM #TEMP0) 

 