/****** Object:  Procedure [BI].[spGetFinYearFromDate]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE procedure [BI].[spGetFinYearFromDate](@GIVENDATE VARCHAR(15))
AS
DECLARE @THIDATE DATETIME
SELECT  @THIDATE = CONVERT(DATETIME, @GIVENDATE,103)
DECLARE @MONTH INT
DECLARE @YEAR INT

DECLARE @FINYEAR INT
SET @MONTH = MONTH(@THIDATE)
SET @YEAR = YEAR(@THIDATE)
IF @MONTH BETWEEN 1 AND 3 
  SET @FINYEAR = @YEAR
ELSE IF @MONTH BETWEEN 4 AND 12
  SET @FINYEAR = @YEAR+1
SELECT @FINYEAR 