/****** Object:  Procedure [BI].[spGetInvoiceDetails]    Committed by VersionSQL https://www.versionsql.com ******/

--[BI].[spFetchPODetails] 'CIPL/90060/968/15-16' 

--BI.spGetInvoiceDetails 41290 
create PROCEDURE [BI].[spGetInvoiceDetails](@TRANGRP INT)
AS
DECLARE @CREDITOR VARCHAR(10)
DECLARE @TAXFROM  VARCHAR(10)
DECLARE @TAXTO    VARCHAR(10)
SELECT  @CREDITOR = CONTROLFROMGL  FROM CONTROLCODES WHERE CONTROLNAME='Creditors'
SELECT  @TAXFROM  = CONTROLFROMGL  FROM CONTROLCODES WHERE CONTROLNAME='Value Added Tax'
SELECT  @TAXTO    = CONTROLTOGL    FROM CONTROLCODES WHERE CONTROLNAME='Value Added Tax'
DECLARE @INVOICEAMOUNT DECIMAL(18,2)
DECLARE @TAXAMOUNT DECIMAL(18,2)

SELECT @TAXAMOUNT = ISNULL( SUM(DEBIT) ,0 ) 
       FROM TRANSACTIONS WHERE TRANGRP=@TRANGRP AND LEDGERCODE BETWEEN @TAXFROM  AND @TAXTO
SELECT @INVOICEAMOUNT = ISNULL(CREDIT,0)   
       FROM TRANSACTIONS WHERE TRANGRP=@TRANGRP AND LEDGERCODE = @CREDITOR

SELECT  @INVOICEAMOUNT AS INVOICEAMOUNT ,@TAXAMOUNT AS TAXAMOUNT
 