/****** Object:  Procedure [BI].[spGenerateAssetSummary]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE [BI].[spGenerateAssetSummary](@FINYEAR INT,@PERIOD INT )
AS
    DECLARE @TRANSSTARTDATE    DATETIME
	DECLARE @TRANSENDDATE      DATETIME
	DECLARE @DATESTRING   VARCHAR(25)
	DECLARE @MONTH VARCHAR(15)
	SELECT  @MONTH = LTRIM(RTRIM(PERIODDESC)) FROM PERIODMASTER WHERE PERIODID=@PERIOD 

	
	SET @DATESTRING ='01/04/'+LTRIM(RTRIM(@FINYEAR-1)) 
 

	SELECT @TRANSSTARTDATE = CONVERT(DATE,@DATESTRING,103)
    IF @PERIOD = 0
	   SET @TRANSENDDATE  = @TRANSSTARTDATE
	ELSE
	   SELECT @TRANSENDDATE = PEDATE FROM PERIODSETUP WHERE YEAR=@FINYEAR AND PERIOD=@PERIOD
 

 

	CREATE TABLE #ASSETSUMMARY(LEDGERCODE VARCHAR(10),LEDGERNAME VARCHAR(150),OPENING DECIMAL(18,2), ADDITIONS DECIMAL(18,2), DELETIONS DECIMAL(18,2), CLOSING DECIMAL(18,2),
	OPENIGDEP  DECIMAL(18,2), ADDITIONSDEP DECIMAL(18,2), DELETIONSDEP DECIMAL(18,2), CLOSINGDEP DECIMAL(18,2),NETVALUE DECIMAL(18,2)  ) 

	SELECT 
	  ASSETOPPCODE,SUM(ASSETPPRICE) OPENING   
	  INTO #TEMP0 
	  FROM ASSETS 
	  WHERE CONVERT(DATE,AssetPDate) <  @TRANSSTARTDATE 
      GROUP BY ASSETOPPCODE  

	  --SELECT * FROM #TEMP0 

    SELECT  
	  ASSETOPPCODE,SUM(ASSETPPRICE) DELETIONS
	  INTO #TEMPDEL
      FROM ASSETS 
	  WHERE ASSETID IN (SELECT ASSETID FROM BI.ASSETPOSTS WHERE   YEAR<@FINYEAR AND DEPTYPE='Sale') 
	  GROUP BY ASSETOPPCODE
    

	INSERT INTO #ASSETSUMMARY(LEDGERCODE,OPENING ) 
	SELECT * FROM #TEMP0 
	--SELECT * FROM #ASSETSUMMARY
 
	UPDATE #ASSETSUMMARY SET OPENING = #ASSETSUMMARY.OPENING-DEL.DELETIONS
	       FROM #TEMPDEL DEL INNER JOIN #ASSETSUMMARY ON #ASSETSUMMARY.LEDGERCODE = DEL.AssetOppCode
	-- INCORPORATING THE PREVIOUS YEARS DELETIONS

	UPDATE #ASSETSUMMARY SET ADDITIONS = 0.0, ADDITIONSDEP = 0.0 ,OPENIGDEP=0

	SELECT LEDGERCODE,SUM(DEBIT) OPENINGDEP 
	INTO #TEMPOPDEP
	FROM BI.ASSETPOSTS WHERE  YEAR=@FINYEAR  AND PERIOD=0   GROUP BY LEDGERCODE 

	UPDATE #ASSETSUMMARY SET OPENIGDEP = TP.OPENINGDEP FROM #TEMPOPDEP TP INNER JOIN #ASSETSUMMARY ON #ASSETSUMMARY.LEDGERCODE =TP.LEDGERCODE 


 
    IF @PERIOD <>0  -- OB
	  BEGIN 
	    SELECT 
	      ASSETOPPCODE,SUM(ASSETPPRICE) SUMADDITIONS   
	      INTO #TEMP1 
	      FROM ASSETS 
	      WHERE CONVERT(DATE,AssetPDate) >=  @TRANSSTARTDATE AND CONVERT(DATE,ASSETPDATE)<=   @TRANSENDDATE
          GROUP BY ASSETOPPCODE  
    

	      SELECT ASSETID 
	      INTO #ADDDEDASSETS 
	      FROM ASSETS 
	      WHERE CONVERT(DATE,AssetPDate) >=  @TRANSSTARTDATE AND CONVERT(DATE,ASSETPDATE)<=   @TRANSENDDATE

 

	      SELECT LEDGERCODE,SUM(DEBIT) DEPADDS 
	      INTO #TEMPADDS 
	      FROM BI.ASSETPOSTS WHERE YEAR=@FINYEAR AND PERIOD BETWEEN 1 AND @PERIOD AND  DEPTYPE<>'SALE'
	      --AND ASSETID IN (SELECT ASSETID FROM #ADDDEDASSETS)
	      GROUP BY LEDGERCODE 

	      UPDATE #ASSETSUMMARY 
	      SET ADDITIONSDEP = #TEMPADDS.DEPADDS FROM #TEMPADDS INNER JOIN #ASSETSUMMARY ON #ASSETSUMMARY.LEDGERCODE = #TEMPADDS.LEDGERCODE
    


	      DECLARE @STARTPERIOD INT 
		  DECLARE @ENDPERIOD INT

		  UPDATE #ASSETSUMMARY SET DELETIONS = 0,DELETIONSDEP = 0.0 
		  SELECT 
			  LEDGERCODE ,SUM(DEBIT) SUMDELETEDEP 
			  INTO #TEMP2 
			  FROM BI.ASSETPOSTS
			  WHERE PERIOD <= @PERIOD AND YEAR=@FINYEAR  AND DEPTYPE='Sale'
			  GROUP BY LEDGERCODE  

 

			SELECT ASSETNUMBER,ASSETOPPCODE,ASSETPPRICE 
			INTO #DELETEMASTER 
			FROM ASSETS WHERE ASSETID IN (SELECT ASSETID FROM BI.ASSETPOSTS WHERE PERIOD<=@PERIOD AND YEAR=@FINYEAR AND DEPTYPE='Sale') 
 
			SELECT ASSETOPPCODE LEDGERCODE ,SUM(ASSETPPRICE) SALEAMT 
			INTO #SALEAMT 
			FROM #DELETEMASTER 
			GROUP BY ASSETOPPCODE 
 
			UPDATE #ASSETSUMMARY 
			SET DELETIONS = #SALEAMT.SALEAMT FROM #SALEAMT INNER JOIN #ASSETSUMMARY ON #ASSETSUMMARY.LEDGERCODE = #SALEAMT.LEDGERCODE

			UPDATE #ASSETSUMMARY 
			SET ADDITIONS = #TEMP1.SUMADDITIONS   FROM #TEMP1 INNER JOIN #ASSETSUMMARY ON #ASSETSUMMARY.LEDGERCODE = #TEMP1.AssetOppCode

			UPDATE #ASSETSUMMARY 
			SET   DELETIONSDEP =-1.0 * #TEMP2.SUMDELETEDEP  FROM #TEMP2 INNER JOIN #ASSETSUMMARY ON #ASSETSUMMARY.LEDGERCODE = #TEMP2.LEDGERCODE
      END
    ELSE
		    BEGIN
			   UPDATE #ASSETSUMMARY SET ADDITIONS = 0, DELETIONS = 0, ADDITIONSDEP = 0, DELETIONSDEP = 0 
			END

	UPDATE #ASSETSUMMARY SET CLOSING = OPENING+ADDITIONS-DELETIONS
	UPDATE #ASSETSUMMARY SET CLOSINGDEP = OPENIGDEP+ADDITIONSDEP-DELETIONSDEP 
	UPDATE #ASSETSUMMARY SET NETVALUE = CLOSING - CLOSINGDEP 


	UPDATE #ASSETSUMMARY SET LEDGERNAME = 'PLANT AND MACHINERY   ' WHERE LEDGERCODE = '2200001'
	UPDATE #ASSETSUMMARY SET LEDGERNAME = 'FURNITURE AND FIXTURES' WHERE LEDGERCODE = '2200002'
	UPDATE #ASSETSUMMARY SET LEDGERNAME = 'COMPUTERS AND PRINTERS' WHERE LEDGERCODE = '2200003'
	UPDATE #ASSETSUMMARY SET LEDGERNAME = 'FORMWORK              ' WHERE LEDGERCODE = '2200004'
	UPDATE #ASSETSUMMARY SET LEDGERNAME = 'VEHICLES              ' WHERE LEDGERCODE = '2200005'
	UPDATE #ASSETSUMMARY SET LEDGERNAME = 'OFFICE EQUIPMENTS     ' WHERE LEDGERCODE = '2200006'
	UPDATE #ASSETSUMMARY SET LEDGERNAME = 'BUILDINGS             ' WHERE LEDGERCODE = '2200007'
	UPDATE #ASSETSUMMARY SET LEDGERNAME = 'COMPUTER SOFTWARE     ' WHERE LEDGERCODE = '2201000'


	ALTER TABLE #ASSETSUMMARY ADD STARTDATE DATETIME 
	ALTER TABLE #ASSETSUMMARY ADD ENDDATE   DATETIME

	UPDATE #ASSETSUMMARY SET STARTDATE = @TRANSSTARTDATE
	UPDATE #ASSETSUMMARY SET ENDDATE   = @TRANSENDDATE 

	SELECT * FROM #ASSETSUMMARY ORDER BY LEDGERNAME 