/****** Object:  Procedure [BI].[spGetCILGSTIN]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE  PROCEDURE BI.spGetCILGSTIN(@LISTORGIDS  LISTORGIDS READONLY)
AS

CREATE TABLE #BORGS(ORGID INT)
INSERT INTO #BORGS 
SELECT ORGID  FROM @LISTORGIDS
DELETE FROM #BORGS WHERE ORGID IS NULL

SELECT DISTINCT COMPREG FROM BORGS WHERE BORGID IN (SELECT ORGID FROM #BORGS) 