/****** Object:  Procedure [BI].[spGenerateCashFlowMarkers]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE BI.spGenerateCashFlowMarkers
as

SELECT * FROM ATTRIBVALUE WHERE ATTRIBUTE='Cash Flow Markers'  ORDER BY VALUE 
SELECT * FROM BS.CASHFLOWINDICATORS

SELECT CF.INDEXCODE,CF.DESCRIPTION,AT.VALUE,AT.COLKEY,LE.LEDGERNAME 
FROM BS.CASHFLOWINDICATORS CF  INNER JOIN ATTRIBVALUE AT ON CF.INDEXCODE=AT.VALUE 
                               INNER JOIN LEDGERCODES LE ON  LE.LEDGERCODE = AT.COLKEY WHERE CF.FONTID=3

SELECT INDEXCODE,DESCRIPTION INTO VRCASHFLOWS FROM BS.CASHFLOWINDICATORS WHERE FONTID=3 ORDER BY INDEXCODE 
SELECT VALUE,COLKEY INTO VRCASHFLOWS1  FROM ATTRIBVALUE WHERE ATTRIBUTE='Cash Flow Markers'  ORDER BY VALUE
SELECT A.*,B.*  INTO VRCASHFLOWS2 FROM VRCASHFLOWS A INNER JOIN VRCASHFLOWS1 B ON A.INDEXCODE = B.VALUE 
ALTER TABLE VRCASHFLOWS2 ADD  LEDGERNAME VARCHAR(200)
SELECT * FROM VRCASHFLOWS2
UPDATE VRCASHFLOWS2 SET LEDGERNAME  = L.LEDGERNAME FROM LEDGERCODES L INNER JOIN VRCASHFLOWS2 ON VRCASHFLOWS2.COLKEY=L.LEDGERCODE 


SELECT INDEXCODE,UPPER(DESCRIPTION),COLKEY , UPPER(LEDGERNAME) FROM VRCASHFLOWS2 ORDER BY INDEXCODE 

  