/****** Object:  Procedure [BI].[spGetLedgerIDs]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE [BI].[spGetLedgerIDs](@FINYEAR INT)
AS

DECLARE @RETAINED VARCHAR(10)
DECLARE @WIP      VARCHAR(10)

SELECT @RETAINED = CONTROLFROMGL FROM CONTROLCODES WHERE CONTROLNAME='Retained Income'
SELECT @WIP      = CONTROLFROMGL FROM CONTROLCODES WHERE CONTROLNAME='Work In Progress'

SELECT L.LEDGERCODE,(L.LEDGERCODE+'- '+ L.LEDGERNAME) LEDGERNAME ,L.LEDGERID,L.LEDGERALLOC FROM LEDGERCODES L 
WHERE L.LEDGERCODE NOT IN (@WIP,@RETAINED)  AND 
      L.LEDGERCODE IN ( SELECT DISTINCT LEDGERCODE FROM TRANSACTIONS  ) 
ORDER BY LEDGERCODE