/****** Object:  Procedure [BI].[spGetLedgerSummary]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE [BI].[spGetLedgerSummary](@LEDGERCODE VARCHAR(10),@CURRENTYEAR INT  )
AS

DECLARE @LASTYEAR INT
SET @LASTYEAR = @CURRENTYEAR -1 

SELECT 
  ORGID,
  [YEAR] FINYEAR,
  PERIOD,
  CREDNO,
  SUM(DEBIT-CREDIT) AMOUNT
INTO 
  #TEMP0 
FROM 
  TRANSACTIONS 
WHERE
  [YEAR] IN (@CURRENTYEAR,@LASTYEAR) AND LEDGERCODE = @LEDGERCODE AND PERIOD<>0
GROUP BY
  ORGID,[YEAR],PERIOD,CREDNO 



DELETE FROM #TEMP0 WHERE AMOUNT=0
SELECT * FROM #TEMP0 ORDER BY ORGID,FINYEAR,CREDNO 

SELECT ORGID,FINYEAR,CREDNO,[1],[2],[3],[4],[5],[6],[7],[8],[9],[10],[11],[12]
INTO #TEMP1
FROM 
( SELECT ORGID,FINYEAR,PERIOD,CREDNO,AMOUNT FROM #TEMP0 ) AS SOURCETABLE 
PIVOT 
  (
    SUM(AMOUNT) FOR PERIOD IN ( [1],[2],[3],[4],[5],[6],[7],[8],[9],[10],[11],[12] ) 
  ) AS PIVOTTABLE
ORDER BY ORGID,FINYEAR,CREDNO 


UPDATE #TEMP1 SET CREDNO='NA' WHERE CREDNO=''
UPDATE #TEMP1 SET [1]=0 WHERE [1] IS NULL
UPDATE #TEMP1 SET [2]=0 WHERE [2] IS NULL
UPDATE #TEMP1 SET [3]=0 WHERE [3] IS NULL
UPDATE #TEMP1 SET [4]=0 WHERE [4] IS NULL
UPDATE #TEMP1 SET [5]=0 WHERE [5] IS NULL
UPDATE #TEMP1 SET [6]=0 WHERE [6] IS NULL
UPDATE #TEMP1 SET [7]=0 WHERE [7] IS NULL
UPDATE #TEMP1 SET [8]=0 WHERE [8] IS NULL
UPDATE #TEMP1 SET [9]=0 WHERE [9] IS NULL
UPDATE #TEMP1 SET [10]=0 WHERE [10] IS NULL
UPDATE #TEMP1 SET [11]=0 WHERE [11] IS NULL
UPDATE #TEMP1 SET [12]=0 WHERE [12] IS NULL

SELECT * FROM #TEMP1