/****** Object:  Procedure [BI].[spGlobalPeriodLockUnlock]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE [BI].[spGlobalPeriodLockUnlock](@FINYEAR INT,@PERIOD INT,@LISTORGIDS  LISTORGIDS READONLY,@STATUS INT)
AS
BEGIN 

   CREATE TABLE #ORGS(ORGID INT)
   INSERT INTO #ORGS   
   SELECT ORGID  FROM @LISTORGIDS
   DELETE FROM #ORGS WHERE ORGID IS NULL

   UPDATE PERIODSETUP SET STATUS=@STATUS WHERE YEAR=@FINYEAR AND ORGID IN (SELECT ORGID FROM #ORGS) AND PERIOD=@PERIOD 

   RETURN 1
    
END