/****** Object:  Procedure [BI].[spGlobalPeriodChange]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE [BI].[spGlobalPeriodChange](@FINYEAR INT,@PERIOD INT,@LISTORGIDS  LISTORGIDS READONLY)
AS
BEGIN 
   CREATE TABLE #ORGS(ORGID INT)
   INSERT INTO #ORGS   
   SELECT ORGID  FROM @LISTORGIDS
   DELETE FROM #ORGS WHERE ORGID IS NULL
   RETURN 1
   --UPDATE BORGS SET CURRENTYEAR=@FINYEAR , CURRENTPERIOD=@PERIOD WHERE BORGID IN (SELECT ORGID FROM #ORGS) 
END