/****** Object:  Procedure [BI].[spGRNRegisterFull]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE  PROCEDURE [BI].[spGRNRegisterFull]  
AS

 

 


SELECT 
 D.DLVRID,
 D.DLVRNO,
 D.GRNNO,
 D.DLVRQTY DELIVERYQTY,
 D.ORDID,
 D.ORDITEMLINENO,
 D.DLVRDATE  DELIVERYDATE,
 D.RECONQTY,
 D.TBORGID,
 D.PRICE,
 D.RECONQTY RECONCILEDQTY,
 D.USERID
INTO 
 #TEMP0
FROM DELIVERIES D
WHERE  
(D.DLVRQTY-D.RECONQTY)>0 AND ALLOCATED<>1

 
 

-- FOREIGN EXCHANGE 
-- CONSIDERING FOREIGN EXCHANGE RATES 
SELECT
   ORDID,
   CURRENCY,
   EXCHRATE,
   HOMECURRENCY
INTO #TEMPFOREIGNEXCHANGE
FROM 
   ORD 
WHERE 
   CURRENCY<>'INR'

-- FE RATE MODIFICATIONS 
UPDATE #TEMP0 
  SET PRICE = PRICE * FE.EXCHRATE 
  FROM #TEMPFOREIGNEXCHANGE FE
  INNER JOIN #TEMP0 ON #TEMP0.ORDID = FE.ORDID 

--- FE ENDS HERE 


ALTER TABLE #TEMP0 ADD   BORGNAME VARCHAR(250) 
UPDATE  #TEMP0 SET BORGNAME = B.BORGNAME FROM BORGS B INNER JOIN #TEMP0 ON #TEMP0.TBORGID=B.BORGID 


ALTER TABLE #TEMP0 ADD ORDERNUMBER VARCHAR(250) 
ALTER TABLE #TEMP0 ADD ORDERDATE DATETIME 
ALTER TABLE #TEMP0 ADD SUPPID INT 
UPDATE #TEMP0 SET ORDERNUMBER = O.ORDNUMBER,ORDERDATE = O.CREATEDATE , SUPPID  = O.SUPPID FROM ORD O INNER JOIN #TEMP0 ON #TEMP0.ORDID = O.ORDID 

ALTER TABLE #TEMP0 ADD CREDNO VARCHAR(25) 
ALTER TABLE #TEMP0 ADD SUPPLIER VARCHAR(255)
UPDATE #TEMP0 SET SUPPLIER  = SUPPNAME, CREDNO=SUPPCODE  FROM SUPPLIERS  S INNER JOIN #TEMP0  ON #TEMP0.SUPPID = S.SUPPID  


ALTER TABLE #TEMP0 ADD STOCKCODE VARCHAR(25)


ALTER TABLE #TEMP0 ADD PURCHASEORDERQTY DECIMAL(18,4)
ALTER TABLE #TEMP0 ADD PURCHASEORDERRATE DECIMAL(18,2)
ALTER TABLE #TEMP0 ADD GSTPERCENTAGE DECIMAL(18,2)
ALTER TABLE #TEMP0 ADD GSTAMOUNT DECIMAL(18,2) 
ALTER TABLE #TEMP0 ADD ITEM VARCHAR(255) 
ALTER TABLE #TEMP0 ADD UNIT VARCHAR(25)
ALTER TABLE #TEMP0 ADD GLCODEID INT
ALTER TABLE #TEMP0 ADD LEDGERCODE VARCHAR(15)
ALTER TABLE #TEMP0 ADD DISCOUNT DECIMAL(18,2) 


UPDATE #TEMP0 SET STOCKCODE = 0 

UPDATE #TEMP0 SET STOCKCODE = BUYERPARTNUMBER,
                  PURCHASEORDERQTY = OI.QTY,
				  PURCHASEORDERRATE = OI.PRICE ,
				  GSTPERCENTAGE = OI.VATPERC,
				  GSTAMOUNT = OI.VATAMOUNT ,
				  ITEM = OI.ITEMDESCRIPTION,
				  GLCODEID = OI.GLCODEID  ,
				  UNIT = OI.UOM,
				  DISCOUNT = OI.DISCOUNT
               FROM ORDITEMS OI INNER JOIN #TEMP0 ON #TEMP0.ORDID=OI.ORDID AND #TEMP0.ORDITEMLINENO = OI.LINENUMBER


-- FE   IN PURCHASE ORDER RATE ALSO 

UPDATE #TEMP0 
  SET PURCHASEORDERRATE = PURCHASEORDERRATE * FE.EXCHRATE 
  FROM #TEMPFOREIGNEXCHANGE FE
  INNER JOIN #TEMP0 ON #TEMP0.ORDID = FE.ORDID 



-- FE ENDS HERE 


UPDATE #TEMP0 SET LEDGERCODE = L.LEDGERCODE FROM LEDGERCODES L INNER JOIN #TEMP0 ON #TEMP0.GLCODEID = L.LEDGERID 


UPDATE #TEMP0 SET ITEM = I.STKDESC     FROM INVENTORY I INNER JOIN #TEMP0 ON #TEMP0.STOCKCODE=I.STKCODE WHERE I.STKSTORE='VMAINSTORE' 
UPDATE #TEMP0 SET ITEM = I.STKDESC     FROM INVENTORY I INNER JOIN #TEMP0 ON #TEMP0.STOCKCODE=I.STKCODE WHERE I.STKSTORE='FORMWORK' 
 
ALTER TABLE #TEMP0 ADD USERNAME VARCHAR(250)
UPDATE #TEMP0 SET USERNAME = U.USERNAME FROM USERS U INNER JOIN #TEMP0 ON #TEMP0.USERID = U.USERID 



DELETE FROM #TEMP0 WHERE LEFT(BORGNAME,1)=''
DELETE FROM #TEMP0 WHERE LEFT(BORGNAME,1)='5'
DELETE FROM #TEMP0 WHERE BORGNAME IS NULL


UPDATE #TEMP0 SET GSTAMOUNT = 0   
SELECT   
 BORGNAME PROJECTNAME,
 CREDNO SUPPLIERCODE,
 SUPPLIER SUPPLIERNAME,
 ORDERNUMBER,
 ORDERDATE,
 ITEM,
 UNIT,
 PURCHASEORDERQTY,
 PURCHASEORDERRATE,
 DELIVERYDATE,
 GRNNO,
 DLVRNO,
 DELIVERYQTY,
 RECONCILEDQTY,
 (DELIVERYQTY*PURCHASEORDERRATE) GRNVALUE
FROM
 #TEMP0 
ORDER BY  BORGNAME,DELIVERYDATE



 
 






 