/****** Object:  Procedure [BI].[spINSERTBUDGET]    Committed by VersionSQL https://www.versionsql.com ******/

--CREATE TABLE BI.MATERIALBUDGET(BUDGETID INT PRIMARY KEY IDENTITY(1,1), ORGID INT , STOCKID VARCHAR(15), QTY DECIMAL(18,3), RATE DECIMAL(18,2), UPLOADDATE DATETIME) 

CREATE PROCEDURE [BI].[spINSERTBUDGET](@ORGID INT,@STOCKCODE VARCHAR(15),@QTY DECIMAL(18,3), @RATE DECIMAL(18,2),@UOM VARCHAR(15), @LASTSNAPSHOTID INT)
AS
INSERT INTO BI.MATERIALBUDGET(ORGID,STOCKID,QTY,RATE,SNAPSHOTID,UOM,UPLOADDATE) 
VALUES(@ORGID,@STOCKCODE,@QTY,@RATE,@LASTSNAPSHOTID,@UOM, GETDATE() ) 