/****** Object:  Procedure [BI].[spJournalExtractForGST]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE BI.spJournalExtractForGST
AS

DECLARE @TRANGRP INT
DECLARE @GSTCOUNT  INT
DECLARE @CREDITORCOUNT INT
DECLARE @EXPENSECOUNT INT
DECLARE @GSTEXPENSE INT

DECLARE JNLCURSOR CURSOR FOR 
SELECT DISTINCT TRANGRP FROM TRANSACTIONS 
WHERE YEAR=2018 AND PERIOD>3 AND TRANSTYPE='JNL'  AND LEDGERCODE BETWEEN '1310025'  AND '1310033' 

OPEN JNLCURSOR 
FETCH NEXT FROM JNLCURSOR INTO @TRANGRP 

WHILE @@FETCH_STATUS = 0
BEGIN
  SET @GSTCOUNT = 0
  SET @CREDITORCOUNT = 0

  SELECT @GSTCOUNT = COUNT(*) FROM TRANSACTIONS WHERE TRANGRP = @TRANGRP AND ( LEDGERCODE ='1310025' OR LEDGERCODE='1310028' )
  
  SELECT @CREDITORCOUNT = COUNT(*) FROM TRANSACTIONS WHERE TRANGRP = @TRANGRP AND LEDGERCODE ='1315000' 
  SELECT @EXPENSECOUNT = COUNT(*) FROM TRANSACTIONS WHERE TRANGRP=@TRANGRP AND ALLOCATION='Contracts' AND LEDGERCODE <>'5130001' 
  SELECT @GSTEXPENSE = COUNT(*) FROM TRANSACTIONS WHERE TRANGRP = @TRANGRP AND LEDGERCODE='5130001' 

  SELECT @TRANGRP,@GSTCOUNT,@CREDITORCOUNT,@EXPENSECOUNT,@GSTEXPENSE  



  FETCH NEXT FROM JNLCURSOR INTO @TRANGRP 

END
CLOSE JNLCURSOR
DEALLOCATE JNLCURSOR 
 