/****** Object:  Procedure [BI].[spLoadYearBudget]    Committed by VersionSQL https://www.versionsql.com ******/

--select year,orgid,ledgercode,1,april  from bi.BUDGET where orgid=128
--select * from bi.YEARLYBUDGETS

CREATE PROCEDURE BI.spLoadYearBudget(@BORGID INT)
AS
DECLARE @PERIOD INT 
SET @PERIOD=1
SELECT YEAR,LEDGERCODE,SUM(APRIL) BUDGETVALUE INTO #TEMP0 FROM BI.BUDGET WHERE ORGID=@BORGID GROUP BY YEAR,LEDGERCODE 

WHILE @PERIOD<12 
BEGIN
 INSERT INTO BI.YEARLYBUDGETS 
 SELECT YEAR,@BORGID,LEDGERCODE,@PERIOD,BUDGETVALUE FROM #TEMP0  
 SET @PERIOD=@PERIOD+1
END 