/****** Object:  Procedure [BI].[spLogin]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE [BI].[spLogin](@USERID VARCHAR(15),@PWD VARCHAR(15))
AS
DECLARE @VALIDUSER INT 
SELECT @VALIDUSER = COUNT(*) FROM USERS WHERE LOGINID=@USERID AND PASSWORD=@PWD
IF @VALIDUSER >= 1
 BEGIN
  DECLARE @ROLE VARCHAR(50)
  SELECT  @ROLE= UPPER(ROLENAME)  FROM ROLEHEADER WHERE ROLEHEADERID = (SELECT ROLEID FROM USERSINBORG 
          WHERE BORGID=2 AND USERID= (SELECT USERID FROM USERS WHERE LOGINID=@USERID  AND PASSWORD =@PWD ) )
  SELECT 1,@ROLE 
 END
ELSE
 SELECT 0,'INVALID'  



 