/****** Object:  Procedure [BI].[spLoadSalesForGST_02FEB]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE  PROCEDURE [BI].[spLoadSalesForGST_02FEB]
as
 
--DELETE FROM BI.SALESHISTORY 
--DBCC CHECKIDENT ("BI.SALESHISTORY",RESEED,0)

DECLARE @WIP VARCHAR(10)
DECLARE @RETAINED VARCHAR(10)
DECLARE @GSTEXPENSE VARCHAR(10)

DECLARE @CREDNO VARCHAR(10) 
DECLARE @GSTCOUNT  INT
DECLARE @CREDITORCOUNT INT
DECLARE @EXPENSECOUNT INT
 
CREATE TABLE #GSTOUTPUT(LEDGERCODE VARCHAR(10)) 
INSERT INTO #GSTOUTPUT VALUES ( '1310028' )
INSERT INTO #GSTOUTPUT VALUES ( '1310029' )
INSERT INTO #GSTOUTPUT VALUES ( '1310030' )


SET @GSTEXPENSE= '5130001'
  

SELECT @WIP= CONTROLFROMGL FROM CONTROLCODES WHERE CONTROLNAME ='Work in Progress' 
SELECT @RETAINED = CONTROLFROMGL FROM CONTROLCODES WHERE CONTROLNAME = 'Retained Income' 



DECLARE @LASTTRANGRP INT
DECLARE @STOCKFROM VARCHAR(10)
DECLARE @STOCKTO   VARCHAR(10)
DECLARE @FAFROM    VARCHAR(10)
DECLARE @FATO      VARCHAR(10)
DECLARE @CREDITORCODE VARCHAR(10)
DECLARE @TRANSFROM INT
DECLARE @TRANSEND  INT
DECLARE @TRANGRP INT
DECLARE @DEBTORCODE_FROM VARCHAR(10)
DECLARE @DEBTORCODE_TO VARCHAR(10)

DECLARE @CGSTPERC DECIMAL(15,2)
DECLARE @CGSTAMOUNT DECIMAL(15,2)

DECLARE @SGSTPERC DECIMAL(15,2)
DECLARE @SGSTAMOUNT DECIMAL(15,2)

DECLARE @IGSTPERC DECIMAL(15,2)
DECLARE @IGSTAMOUNT DECIMAL(15,2)

DECLARE @CESSPERC DECIMAL(15,2)
DECLARE @CESSAMOUNT DECIMAL(15,2)

DECLARE @TAXABLEAMOUNT DECIMAL(15,2)

DECLARE @SUPPLIERNAME VARCHAR(90)
DECLARE @SUPPLIERADDRESS VARCHAR(80)
DECLARE @SUPPLIERGSTN VARCHAR(15)
DECLARE @STATEOFSUPPLY CHAR(2)
DECLARE @SUPPLIERCITY  VARCHAR(40)
DECLARE @SUPPLIERPROVINCE INT 
DECLARE @STATECODE CHAR(2)

DECLARE @ORGGSTN  VARCHAR(15)

DECLARE @GRN VARCHAR(50)
DECLARE @GRNQTY DECIMAL(15,2) 
DECLARE @GRNDATE DATETIME
DECLARE @GRNAMOUNT DECIMAL(15,2)

DECLARE @ORGID INT 
DECLARE @SUPPLIERCODE VARCHAR(10)
DECLARE @INDEXCOUNTER INT
DECLARE @TRANSID  INT
DECLARE @LINECOUNT INT 
DECLARE @LEDGERALLOC VARCHAR(15)
DECLARE @LEDGERCODE VARCHAR(10)
DECLARE @ITEMCOUNT INT 
DECLARE @TAXAMOUNT DECIMAL(18,2) 
DECLARE @TRANSACTIONORG INT 
DECLARE @NARRATION VARCHAR(255)
DECLARE @GSTLEDGERS INT 
DECLARE @GSTEXPENSECOUNT DECIMAL(18,2) 
DECLARE @CONTRA INT

DECLARE @CRILEDGERCODE VARCHAR(10)
DECLARE @CRIINVOICEDATE DATETIME 
DECLARE @CBCRECEIVEDATE DATETIME 
DECLARE @CBCTRANSID INT
DECLARE @CBCLEDGERCODE VARCHAR(15)
DECLARE @CBDRECEIVEDATE DATETIME 
DECLARE @CBDTRANSID INT
DECLARE @CBDLEDGERCODE VARCHAR(15)

SELECT @STOCKFROM=CONTROLFROMGL , @STOCKTO=CONTROLTOGL FROM CONTROLCODES WHERE CONTROLNAME='Stock' 
SELECT @FAFROM =CONTROLFROMGL , @FATO=CONTROLTOGL FROM CONTROLCODES WHERE CONTROLNAME='Fixed Asset' 
SELECT @CREDITORCODE = CONTROLFROMGL FROM CONTROLCODES WHERE CONTROLNAME='Creditors' 
SELECT @DEBTORCODE_FROM = CONTROLFROMGL FROM CONTROLCODES WHERE CONTROLNAME='Debtors' 
SELECT @DEBTORCODE_TO = CONTROLTOGL FROM  CONTROLCODES WHERE CONTROLNAME='Debtors' 

SELECT ICGLCODE INTO #TEMPICLA  FROM BORGS  WHERE BORGID NOT IN (SELECT BORGID FROM BORGS WHERE ICGLCODE IS NULL ) 
INSERT INTO #TEMPICLA VALUES (@WIP)
INSERT INTO #TEMPICLA VALUES (@RETAINED) 
 

---- CRI Transactions 
CREATE TABLE #CRITEMP(LINECOUNT INT PRIMARY KEY , ORGID INT,  YEAR INT,PERIOD INT,PDATE DATE, INVOICEDATE DATE,
BATCHREF VARCHAR(25), TRANSREF VARCHAR(50), CREDNO VARCHAR(25), TRANGRP INT,TRANSID INT,LEDGERCODE VARCHAR(25),DESCRIPTION VARCHAR(400),DEBIT DECIMAL(18,2),CREDIT DECIMAL(18,2),
INPUTCGST DECIMAL(18,2),INPUTSGST DECIMAL(18,2),INPUTIGST DECIMAL(18,2),INPUTRCMCGST DECIMAL(18,2),INPUTRCMSGST DECIMAL(18,2),INPUTRCMIGST DECIMAL(18,2),
OUTPUTRCMCGST DECIMAL(18,2),OUTPUTRCMSGST DECIMAL(18,2),OUTPUTRCMIGST DECIMAL(18,2) )

SET @ITEMCOUNT = 0  


SELECT @LASTTRANGRP = MAX(TRANGRP) FROM BI.SALESHISTORY WHERE TRANSTYPE='CRI' 
DECLARE CRITRANGRP  CURSOR FOR 
SELECT DISTINCT TRANGRP 
FROM TRANSACTIONS WHERE YEAR>=2018 AND PERIOD>3 AND TRANSTYPE='CRI' AND LEDGERCODE IN (SELECT LEDGERCODE FROM #GSTOUTPUT) AND TRANGRP>@LASTTRANGRP 
 

OPEN CRITRANGRP 
FETCH NEXT FROM CRITRANGRP INTO @TRANGRP 

WHILE @@FETCH_STATUS=0
BEGIN
  SELECT @CRILEDGERCODE =XGLCODE ,@CRIINVOICEDATE = RECEIVEDDATE FROM TRANSACTIONS WHERE TRANGRP = @TRANGRP AND LEDGERCODE=@CREDITORCODE 
 

  IF LTRIM(RTRIM(@CRILEDGERCODE))=''
     SELECT @CRILEDGERCODE=LEDGERCODE FROM TRANSACTIONS WHERE TRANGRP=@TRANGRP AND ALLOCATION='Contracts'
 
  CREATE TABLE #TEMP(LINEINDEX INT PRIMARY  KEY IDENTITY(1,1), TRANSID  INT ) 
  DELETE FROM #TEMP

  INSERT INTO #TEMP 
  SELECT TRANSID FROM TRANSACTIONS WHERE TRANGRP = @TRANGRP AND LEDGERCODE NOT IN(SELECT ICGLCODE FROM #TEMPICLA) ORDER BY TRANSID 
 
  SELECT  @LINECOUNT = COUNT(*) FROM #TEMP  
  SET @INDEXCOUNTER = 1


  WHILE @INDEXCOUNTER<=@LINECOUNT
  BEGIN
    
    SELECT   @TRANSID = TRANSID FROM #TEMP   WHERE LINEINDEX=@INDEXCOUNTER 
	SELECT @LEDGERALLOC=ALLOCATION, @LEDGERCODE = LEDGERCODE, @TAXAMOUNT = (DEBIT-CREDIT),@TRANSACTIONORG=ORGID
	FROM TRANSACTIONS WHERE TRANSID =( SELECT TRANSID FROM #TEMP WHERE LINEINDEX = @INDEXCOUNTER )  
	 

	IF @LEDGERALLOC IN ('Contracts','Overheads') 
	BEGIN 
	  SET @ITEMCOUNT = @ITEMCOUNT + 1
	  INSERT INTO #CRITEMP(LINECOUNT,ORGID,YEAR,PERIOD,PDATE,INVOICEDATE,BATCHREF,TRANSREF,CREDNO,TRANGRP,TRANSID, LEDGERCODE,DESCRIPTION,DEBIT,CREDIT)
	  SELECT @ITEMCOUNT,ORGID,YEAR,PERIOD,PDATE,@CRIINVOICEDATE,BATCHREF,TRANSREFEXT,CREDNO,TRANGRP,TRANSID, @CRILEDGERCODE,DESCRIPTION,DEBIT,CREDIT FROM TRANSACTIONS WHERE TRANSID = @TRANSID
	END 
  
    IF  @LEDGERCODE = '1310031'    UPDATE #CRITEMP SET INPUTRCMCGST= @TAXAMOUNT WHERE LINECOUNT=@ITEMCOUNT
	IF  @LEDGERCODE = '1310032'    UPDATE #CRITEMP SET INPUTRCMSGST= @TAXAMOUNT WHERE LINECOUNT=@ITEMCOUNT
	IF  @LEDGERCODE = '1310033'    UPDATE #CRITEMP SET INPUTRCMIGST= @TAXAMOUNT WHERE LINECOUNT=@ITEMCOUNT
	IF  @LEDGERCODE = '1310034'    UPDATE #CRITEMP SET OUTPUTRCMCGST= @TAXAMOUNT WHERE LINECOUNT=@ITEMCOUNT
	IF  @LEDGERCODE = '1310035'    UPDATE #CRITEMP SET OUTPUTRCMSGST= @TAXAMOUNT WHERE LINECOUNT=@ITEMCOUNT
	IF  @LEDGERCODE = '1310036'    UPDATE #CRITEMP SET OUTPUTRCMIGST= @TAXAMOUNT WHERE LINECOUNT=@ITEMCOUNT
	

	IF @LEDGERCODE = @CREDITORCODE 
	BEGIN
	   UPDATE #CRITEMP SET DESCRIPTION = LTRIM(RTRIM(DESCRIPTION))+ '(InterCompany-' +LTRIM(RTRIM(STR(ORGID)))+')'  
	   WHERE @TRANSACTIONORG<>ORGID  AND LINECOUNT=@ITEMCOUNT 
	   UPDATE #CRITEMP SET ORGID=@TRANSACTIONORG WHERE LINECOUNT=@ITEMCOUNT 
	END 

    SET @INDEXCOUNTER = @INDEXCOUNTER + 1
  END

  DROP TABLE #TEMP 

  FETCH NEXT FROM CRITRANGRP INTO @TRANGRP 
END

CLOSE CRITRANGRP
DEALLOCATE   CRITRANGRP 

ALTER TABLE #CRITEMP ADD CGSTPERCENTAGE DECIMAL(18,2)
ALTER TABLE #CRITEMP ADD SGSTPERCENTAGE DECIMAL(18,2)
ALTER TABLE #CRITEMP ADD IGSTPERCENTAGE DECIMAL(18,2)

UPDATE #CRITEMP SET CGSTPERCENTAGE =0
UPDATE #CRITEMP SET SGSTPERCENTAGE =0
UPDATE #CRITEMP SET IGSTPERCENTAGE =0

UPDATE #CRITEMP SET INPUTCGST=0 WHERE INPUTCGST IS NULL
UPDATE #CRITEMP SET INPUTSGST=0 WHERE INPUTSGST IS NULL
UPDATE #CRITEMP SET INPUTIGST=0 WHERE INPUTIGST IS NULL

UPDATE #CRITEMP SET INPUTRCMCGST=0 WHERE INPUTRCMCGST IS NULL
UPDATE #CRITEMP SET INPUTRCMSGST=0 WHERE INPUTRCMSGST IS NULL
UPDATE #CRITEMP SET INPUTRCMIGST=0 WHERE INPUTRCMIGST IS NULL

UPDATE #CRITEMP SET OUTPUTRCMCGST=0 WHERE OUTPUTRCMCGST IS NULL
UPDATE #CRITEMP SET OUTPUTRCMSGST=0 WHERE OUTPUTRCMSGST IS NULL
UPDATE #CRITEMP SET OUTPUTRCMIGST=0 WHERE OUTPUTRCMIGST IS NULL

UPDATE #CRITEMP SET CGSTPERCENTAGE = ROUND( ( (INPUTCGST)/(DEBIT-CREDIT) ) * 100, 2 ) WHERE INPUTCGST<>0 
UPDATE #CRITEMP SET SGSTPERCENTAGE = ROUND( ( (INPUTSGST)/(DEBIT-CREDIT) ) * 100 ,2 ) WHERE INPUTSGST<>0 
UPDATE #CRITEMP SET IGSTPERCENTAGE = ROUND( ( (INPUTIGST)/(DEBIT-CREDIT) ) * 100, 2 ) WHERE INPUTIGST<>0 

UPDATE #CRITEMP SET CGSTPERCENTAGE = ROUND( ( (INPUTRCMCGST)/(DEBIT-CREDIT) ) * 100, 2 ) WHERE INPUTRCMCGST<>0 
UPDATE #CRITEMP SET SGSTPERCENTAGE = ROUND( ( (INPUTRCMSGST)/(DEBIT-CREDIT) ) * 100 ,2 ) WHERE INPUTRCMSGST<>0 
UPDATE #CRITEMP SET IGSTPERCENTAGE = ROUND( ( (INPUTRCMIGST)/(DEBIT-CREDIT) ) * 100, 2 ) WHERE INPUTRCMIGST<>0 
 

INSERT INTO BI.SALESHISTORY
(ORGID,FINYEAR,PERIOD,TRANGRP,TRANSID,TRANSTYPE,INVOICENUMBER,TRANSACTIONDATE,SUPPCODE,ITEM,LEDGERCODE,BATCHREF,INVOICEDATE,
TAXABLE_VALUE,CGST_RATE,CGST_AMOUNT,SGST_RATE,SGST_AMOUNT,IGST_RATE,IGST_AMOUNT,CGST_INPUT_RCM_AMOUNT,CGST_OUTPUT_RCM_AMOUNT,
SGST_INPUT_RCM_AMOUNT,SGST_OUTPUT_RCM_AMOUNT,IGST_INPUT_RCM_AMOUNT,IGST_OUTPUT_RCM_AMOUNT)
SELECT
 ORGID,YEAR,PERIOD,TRANGRP,TRANSID,'CRI',TRANSREF,PDATE,CREDNO,UPPER(DESCRIPTION),LEDGERCODE,BATCHREF,INVOICEDATE,
 ABS((DEBIT-CREDIT)),CGSTPERCENTAGE,INPUTCGST,SGSTPERCENTAGE,INPUTSGST,IGSTPERCENTAGE,INPUTIGST,INPUTRCMCGST,OUTPUTRCMCGST,
  INPUTRCMSGST,OUTPUTRCMSGST,INPUTRCMIGST,OUTPUTRCMIGST 
FROM #CRITEMP




---- SUBCONTRACTOR BILL BOOKINGS (CONTRA CHARGES + RCM ) 


CREATE TABLE #SCITEMP(LINECOUNT INT PRIMARY KEY , ORGID INT,  YEAR INT,PERIOD INT,PDATE DATE,INVOICEDATE DATE,  
BATCHREF VARCHAR(15), TRANSREF VARCHAR(25), CREDNO VARCHAR(15), TRANGRP INT,TRANSID INT,LEDGERCODE VARCHAR(15),DESCRIPTION VARCHAR(300),DEBIT DECIMAL(18,2),CREDIT DECIMAL(18,2),
OUTPUTCGST DECIMAL(18,2),OUTPUTSGST DECIMAL(18,2),OUTPUTIGST DECIMAL(18,2),INPUTRCMCGST DECIMAL(18,2),INPUTRCMSGST DECIMAL(18,2),INPUTRCMIGST DECIMAL(18,2),
OUTPUTRCMCGST DECIMAL(18,2),OUTPUTRCMSGST DECIMAL(18,2),OUTPUTRCMIGST DECIMAL(18,2) )

SET @ITEMCOUNT = 0  

SELECT @LASTTRANGRP = MAX(TRANGRP) FROM BI.SALESHISTORY WHERE TRANSTYPE='SCI' 
DECLARE SCITRANGRP  CURSOR FOR 
SELECT DISTINCT TRANGRP 
FROM TRANSACTIONS WHERE YEAR>=2018 AND PERIOD>3 AND LEFT(TRANSTYPE,3)='SCI'   AND LEDGERCODE IN (SELECT LEDGERCODE FROM #GSTOUTPUT) AND TRANGRP>@LASTTRANGRP 
  

OPEN SCITRANGRP 
FETCH NEXT FROM SCITRANGRP INTO @TRANGRP 

WHILE @@FETCH_STATUS=0
BEGIN
  SET @CONTRA=0
  SELECT @CONTRA = COUNT(*) FROM TRANSACTIONS WHERE TRANGRP = @TRANGRP AND LEDGERCODE='1310028' 
  CREATE TABLE #TEMPSCI(LINEINDEX INT PRIMARY  KEY IDENTITY(1,1), TRANSID  INT ) 
  DELETE FROM #TEMPSCI
  INSERT INTO #TEMPSCI 
  SELECT TRANSID FROM TRANSACTIONS WHERE TRANGRP = @TRANGRP AND LEDGERCODE NOT IN(SELECT ICGLCODE FROM #TEMPICLA) ORDER BY TRANSID 
  SELECT  @LINECOUNT = COUNT(*) FROM #TEMPSCI  
  SET @INDEXCOUNTER = 1
  WHILE @INDEXCOUNTER<=@LINECOUNT
  BEGIN
 
    SELECT @TRANSID = TRANSID FROM #TEMPSCI   WHERE LINEINDEX=@INDEXCOUNTER 
	SELECT @LEDGERCODE = LEDGERCODE, @TAXAMOUNT = (DEBIT-CREDIT),@NARRATION = DESCRIPTION ,@LEDGERALLOC = ALLOCATION 
	FROM TRANSACTIONS WHERE TRANSID =  (SELECT TRANSID FROM #TEMPSCI WHERE LINEINDEX = @INDEXCOUNTER )   
	
	IF (@NARRATION LIKE  'Total Gross Billing%') OR (@LEDGERALLOC ='Contracts' AND (@CONTRA<>0) )                                                                                                                                                                                                                                
	BEGIN 
	  SET @ITEMCOUNT = @ITEMCOUNT + 1
	  INSERT INTO #SCITEMP(LINECOUNT,ORGID,YEAR,PERIOD,PDATE,BATCHREF,TRANSREF,CREDNO,TRANGRP,TRANSID, LEDGERCODE,DESCRIPTION,DEBIT,CREDIT,INVOICEDATE)
	  SELECT @ITEMCOUNT,ORGID,YEAR,PERIOD,PDATE,BATCHREF,TRANSREF,CREDNO,TRANGRP,TRANSID, LEDGERCODE,DESCRIPTION,DEBIT,CREDIT,PDATE  FROM TRANSACTIONS WHERE TRANSID = @TRANSID
	END 
    IF  @LEDGERCODE = '1310028'    UPDATE #SCITEMP SET OUTPUTCGST= ABS(@TAXAMOUNT) WHERE LINECOUNT=@ITEMCOUNT 
    IF  @LEDGERCODE = '1310029'    UPDATE #SCITEMP SET OUTPUTSGST= ABS(@TAXAMOUNT) WHERE LINECOUNT=@ITEMCOUNT
    IF  @LEDGERCODE = '1310030'    UPDATE #SCITEMP SET OUTPUTIGST= ABS(@TAXAMOUNT) WHERE LINECOUNT=@ITEMCOUNT 
    IF  @LEDGERCODE = '1310031'    UPDATE #SCITEMP SET INPUTRCMCGST= @TAXAMOUNT WHERE LINECOUNT=@ITEMCOUNT
	IF  @LEDGERCODE = '1310032'    UPDATE #SCITEMP SET INPUTRCMSGST= @TAXAMOUNT WHERE LINECOUNT=@ITEMCOUNT
	IF  @LEDGERCODE = '1310033'    UPDATE #SCITEMP SET INPUTRCMIGST= @TAXAMOUNT WHERE LINECOUNT=@ITEMCOUNT
	IF  @LEDGERCODE = '1310034'    UPDATE #SCITEMP SET OUTPUTRCMCGST= @TAXAMOUNT WHERE LINECOUNT=@ITEMCOUNT
	IF  @LEDGERCODE = '1310035'    UPDATE #SCITEMP SET OUTPUTRCMSGST= @TAXAMOUNT WHERE LINECOUNT=@ITEMCOUNT
    SET @INDEXCOUNTER = @INDEXCOUNTER + 1
  END
  DROP TABLE #TEMPSCI
  FETCH NEXT FROM SCITRANGRP INTO @TRANGRP 
END

CLOSE SCITRANGRP
DEALLOCATE   SCITRANGRP 

ALTER TABLE #SCITEMP ADD CGSTPERCENTAGE DECIMAL(18,2)
ALTER TABLE #SCITEMP ADD SGSTPERCENTAGE DECIMAL(18,2)
ALTER TABLE #SCITEMP ADD IGSTPERCENTAGE DECIMAL(18,2)
UPDATE #SCITEMP SET CGSTPERCENTAGE =0
UPDATE #SCITEMP SET SGSTPERCENTAGE =0
UPDATE #SCITEMP SET IGSTPERCENTAGE =0
UPDATE #SCITEMP SET OUTPUTCGST=0 WHERE OUTPUTCGST IS NULL
UPDATE #SCITEMP SET OUTPUTSGST=0 WHERE OUTPUTSGST IS NULL
UPDATE #SCITEMP SET OUTPUTIGST=0 WHERE OUTPUTIGST IS NULL
UPDATE #SCITEMP SET INPUTRCMCGST=0 WHERE INPUTRCMCGST IS NULL
UPDATE #SCITEMP SET INPUTRCMSGST=0 WHERE INPUTRCMSGST IS NULL
UPDATE #SCITEMP SET INPUTRCMIGST=0 WHERE INPUTRCMIGST IS NULL
UPDATE #SCITEMP SET OUTPUTRCMCGST=0 WHERE OUTPUTRCMCGST IS NULL
UPDATE #SCITEMP SET OUTPUTRCMSGST=0 WHERE OUTPUTRCMSGST IS NULL
UPDATE #SCITEMP SET OUTPUTRCMIGST=0 WHERE OUTPUTRCMIGST IS NULL

UPDATE #SCITEMP SET CGSTPERCENTAGE = ROUND( ( (OUTPUTCGST)/(DEBIT-CREDIT) ) * 100, 2 ) WHERE OUTPUTCGST<>0 
UPDATE #SCITEMP SET SGSTPERCENTAGE = ROUND( ( (OUTPUTSGST)/(DEBIT-CREDIT) ) * 100 ,2 ) WHERE OUTPUTSGST<>0 
UPDATE #SCITEMP SET IGSTPERCENTAGE = ROUND( ( (OUTPUTIGST)/(DEBIT-CREDIT) ) * 100, 2 ) WHERE OUTPUTIGST<>0 

UPDATE #SCITEMP SET CGSTPERCENTAGE = ROUND( ( (INPUTRCMCGST)/(DEBIT-CREDIT) ) * 100, 2 ) WHERE INPUTRCMCGST<>0 
UPDATE #SCITEMP SET SGSTPERCENTAGE = ROUND( ( (INPUTRCMSGST)/(DEBIT-CREDIT) ) * 100 ,2 ) WHERE INPUTRCMSGST<>0 
UPDATE #SCITEMP SET IGSTPERCENTAGE = ROUND( ( (INPUTRCMIGST)/(DEBIT-CREDIT) ) * 100, 2 ) WHERE INPUTRCMIGST<>0 

 
UPDATE  #SCITEMP SET CGSTPERCENTAGE = 6.0 WHERE CGSTPERCENTAGE BETWEEN 5.5 AND 6.9
UPDATE  #SCITEMP SET CGSTPERCENTAGE = 9.0 WHERE CGSTPERCENTAGE BETWEEN 7 AND 11
UPDATE  #SCITEMP SET SGSTPERCENTAGE = 9.0 WHERE SGSTPERCENTAGE BETWEEN 7 AND 11
UPDATE  #SCITEMP SET IGSTPERCENTAGE = 18.0 WHERE IGSTPERCENTAGE BETWEEN 17 AND 19
UPDATE  #SCITEMP SET CGSTPERCENTAGE = 14.0 WHERE CGSTPERCENTAGE BETWEEN 13 AND 14
UPDATE  #SCITEMP SET SGSTPERCENTAGE = 14.0 WHERE SGSTPERCENTAGE BETWEEN 13 AND 14
 
DELETE FROM #SCITEMP WHERE (OUTPUTCGST=0) AND (OUTPUTSGST=0) AND (OUTPUTIGST=0) AND (INPUTRCMCGST=0) AND (INPUTRCMSGST=0) AND (INPUTRCMIGST=0) 

UPDATE #SCITEMP SET DESCRIPTION =''



INSERT INTO BI.SALESHISTORY
(ORGID,FINYEAR,PERIOD,TRANGRP,TRANSID,TRANSTYPE,INVOICENUMBER,TRANSACTIONDATE,SUPPCODE,ITEM,LEDGERCODE,BATCHREF,INVOICEDATE,
TAXABLE_VALUE,CGST_RATE,CGST_AMOUNT,SGST_RATE,SGST_AMOUNT,IGST_RATE,IGST_AMOUNT,CGST_INPUT_RCM_AMOUNT,CGST_OUTPUT_RCM_AMOUNT,
SGST_INPUT_RCM_AMOUNT,SGST_OUTPUT_RCM_AMOUNT,IGST_INPUT_RCM_AMOUNT,IGST_OUTPUT_RCM_AMOUNT)
SELECT
 ORGID,YEAR,PERIOD,TRANGRP,TRANSID,'SCI',TRANSREF,PDATE,CREDNO,DESCRIPTION,LEDGERCODE,BATCHREF,PDATE,
 ABS((DEBIT-CREDIT)),CGSTPERCENTAGE,OUTPUTCGST,SGSTPERCENTAGE,OUTPUTSGST,IGSTPERCENTAGE,OUTPUTIGST,INPUTRCMCGST,OUTPUTRCMCGST,
  INPUTRCMSGST,OUTPUTRCMSGST,INPUTRCMIGST,OUTPUTRCMIGST 
FROM #SCITEMP
 


---- CBC / PCP TRANSACTIONS
DECLARE @CONTRACTDEBIT DECIMAL(18,2)
DECLARE @CONTRACTCREDIT DECIMAL(18,2) 

CREATE TABLE #CBCTEMP(LINECOUNT INT PRIMARY KEY , ORGID INT,  YEAR INT,PERIOD INT,PDATE DATETIME,INVOICEDATE DATETIME,
BATCHREF VARCHAR(10), TRANSREF VARCHAR(10), CREDNO VARCHAR(10), TRANGRP INT,TRANSID INT,LEDGERCODE VARCHAR(10) ,
DESCRIPTION VARCHAR(300),DEBIT DECIMAL(18,2),CREDIT DECIMAL(18,2),
OUTPUTCGST DECIMAL(18,2),OUTPUTSGST DECIMAL(18,2),OUTPUTIGST DECIMAL(18,2),INPUTRCMCGST DECIMAL(18,2),INPUTRCMSGST DECIMAL(18,2),INPUTRCMIGST DECIMAL(18,2),
OUTPUTRCMCGST DECIMAL(18,2),OUTPUTRCMSGST DECIMAL(18,2),OUTPUTRCMIGST DECIMAL(18,2),TRANSTYPE CHAR(3), GSTEXPENSE DECIMAL(18,2) )

SET @ITEMCOUNT = 0  

SELECT @LASTTRANGRP =MAX(TRANGRP) FROM BI.SALESHISTORY WHERE TRANSTYPE IN ('CBC','PCP') 
DECLARE CBCTRANGRP  CURSOR FOR SELECT DISTINCT TRANGRP FROM TRANSACTIONS WHERE YEAR>=2018 AND PERIOD>3 AND LEFT(TRANSTYPE,3) IN ('CBC'  ,'PCP' ) AND 
                    LEDGERCODE IN (SELECT LEDGERCODE FROM #GSTOUTPUT)  AND TRANGRP >@LASTTRANGRP 
OPEN CBCTRANGRP 
FETCH NEXT FROM CBCTRANGRP INTO @TRANGRP 

WHILE @@FETCH_STATUS=0
BEGIN
  SELECT  @CBCRECEIVEDATE =MAX(RECEIVEDDATE)  FROM TRANSACTIONS WHERE TRANGRP=@TRANGRP  
  SELECT  @CBCTRANSID =MIN(TRANSID)  FROM TRANSACTIONS WHERE  TRANGRP = @TRANGRP AND LEDGERCODE IN (SELECT LEDGERCODE  FROM #GSTOUTPUT)
  SELECT  @CBCLEDGERCODE = LEDGERCODE FROM TRANSACTIONS WHERE TRANGRP = @TRANGRP AND TRANSID < @CBCTRANSID AND  LEDGERCODE NOT IN(SELECT ICGLCODE FROM #TEMPICLA) AND CREDIT>0
  SELECT @CONTRACTDEBIT = SUM(DEBIT),@CONTRACTCREDIT=SUM(CREDIT) FROM TRANSACTIONS WHERE TRANGRP = @TRANGRP  AND (VATDEBIT-VATCREDIT)<>0
  SELECT TOP 1  @TRANSID = TRANSID FROM TRANSACTIONS WHERE TRANGRP = @TRANGRP AND  VATDEBIT>0 
  SET @ITEMCOUNT = @ITEMCOUNT + 1
   

  INSERT INTO #CBCTEMP(LINECOUNT,ORGID,YEAR,PERIOD,PDATE,BATCHREF,TRANSREF,CREDNO,TRANGRP,TRANSID, LEDGERCODE,DESCRIPTION,DEBIT,CREDIT,INVOICEDATE,TRANSTYPE)
  SELECT @ITEMCOUNT,ORGID,YEAR,PERIOD,PDATE,BATCHREF,TRANSREF,CREDNO,TRANGRP,TRANSID, @CBCLEDGERCODE,DESCRIPTION,@CONTRACTDEBIT,@CONTRACTCREDIT,@CBCRECEIVEDATE,LEFT(TRANSTYPE,3) 
  FROM TRANSACTIONS WHERE TRANSID = @TRANSID AND TRANGRP = @TRANGRP 

 

  CREATE TABLE #TEMPCBC(LINEINDEX INT PRIMARY  KEY IDENTITY(1,1), TRANSID  INT ) 
  DELETE FROM #TEMPCBC

  INSERT INTO #TEMPCBC
  SELECT TRANSID FROM TRANSACTIONS WHERE TRANGRP = @TRANGRP AND  LEDGERCODE IN (SELECT LEDGERCODE FROM #GSTOUTPUT)  ORDER BY TRANSID 

  SELECT  @LINECOUNT = COUNT(*) FROM #TEMPCBC  
  SET @INDEXCOUNTER = 1


  WHILE @INDEXCOUNTER<=@LINECOUNT
  BEGIN
 
    SELECT @LEDGERCODE = LEDGERCODE, @TAXAMOUNT = (DEBIT-CREDIT)  FROM TRANSACTIONS WHERE TRANSID =(SELECT TRANSID FROM  #TEMPCBC WHERE LINEINDEX=@INDEXCOUNTER) 


 	   IF  @LEDGERCODE = '1310028'    UPDATE #CBCTEMP SET OUTPUTCGST= @TAXAMOUNT WHERE LINECOUNT=@ITEMCOUNT AND TRANGRP = @TRANGRP 
       IF  @LEDGERCODE = '1310029'    UPDATE #CBCTEMP SET OUTPUTSGST= @TAXAMOUNT WHERE LINECOUNT=@ITEMCOUNT AND TRANGRP = @TRANGRP 
	   IF  @LEDGERCODE = '1310030'    UPDATE #CBCTEMP SET OUTPUTIGST= @TAXAMOUNT WHERE LINECOUNT=@ITEMCOUNT  AND TRANGRP = @TRANGRP 
       IF  @LEDGERCODE = '1310031'    UPDATE #CBCTEMP SET INPUTRCMCGST= @TAXAMOUNT WHERE LINECOUNT=@ITEMCOUNT AND TRANGRP = @TRANGRP 
	   IF  @LEDGERCODE = '1310032'    UPDATE #CBCTEMP SET INPUTRCMSGST= @TAXAMOUNT WHERE LINECOUNT=@ITEMCOUNT AND TRANGRP = @TRANGRP 
	   IF  @LEDGERCODE = '1310033'    UPDATE #CBCTEMP SET INPUTRCMIGST= @TAXAMOUNT WHERE LINECOUNT=@ITEMCOUNT AND TRANGRP = @TRANGRP 
	   IF  @LEDGERCODE = '1310034'    UPDATE #CBCTEMP SET OUTPUTRCMCGST= @TAXAMOUNT WHERE LINECOUNT=@ITEMCOUNT AND TRANGRP = @TRANGRP 
	   IF  @LEDGERCODE = '1310035'    UPDATE #CBCTEMP SET OUTPUTRCMSGST= @TAXAMOUNT WHERE LINECOUNT=@ITEMCOUNT AND TRANGRP = @TRANGRP 
	   IF  @LEDGERCODE = '1310036'    UPDATE #CBCTEMP SET OUTPUTRCMIGST= @TAXAMOUNT WHERE LINECOUNT=@ITEMCOUNT AND TRANGRP = @TRANGRP 
	   IF  @LEDGERCODE = @GSTEXPENSE  UPDATE #CBCTEMP SET GSTEXPENSE = @TAXAMOUNT WHERE LINECOUNT = @ITEMCOUNT AND TRANGRP = @TRANGRP 
    SET @INDEXCOUNTER = @INDEXCOUNTER + 1
  END

  DROP TABLE #TEMPCBC 

  FETCH NEXT FROM CBCTRANGRP INTO @TRANGRP 
END

CLOSE CBCTRANGRP
DEALLOCATE   CBCTRANGRP 

ALTER TABLE #CBCTEMP ADD CGSTPERCENTAGE DECIMAL(18,2)
ALTER TABLE #CBCTEMP ADD SGSTPERCENTAGE DECIMAL(18,2)
ALTER TABLE #CBCTEMP ADD IGSTPERCENTAGE DECIMAL(18,2)

ALTER TABLE #CBCTEMP ADD CGSTRCMPERCENTAGE DECIMAL(18,2)
ALTER TABLE #CBCTEMP ADD SGSTRCMPERCENTAGE DECIMAL(18,2)
ALTER TABLE #CBCTEMP ADD IGSTRCMPERCENTAGE DECIMAL(18,2)

UPDATE #CBCTEMP SET CGSTPERCENTAGE =0
UPDATE #CBCTEMP SET SGSTPERCENTAGE =0
UPDATE #CBCTEMP SET IGSTPERCENTAGE =0

UPDATE #CBCTEMP SET CGSTRCMPERCENTAGE =0
UPDATE #CBCTEMP SET SGSTRCMPERCENTAGE =0
UPDATE #CBCTEMP SET IGSTRCMPERCENTAGE =0

UPDATE #CBCTEMP SET OUTPUTCGST=0 WHERE OUTPUTCGST IS NULL
UPDATE #CBCTEMP SET OUTPUTSGST=0 WHERE OUTPUTSGST IS NULL
UPDATE #CBCTEMP SET OUTPUTIGST=0 WHERE OUTPUTIGST IS NULL

UPDATE #CBCTEMP SET INPUTRCMCGST=0 WHERE INPUTRCMCGST IS NULL
UPDATE #CBCTEMP SET INPUTRCMSGST=0 WHERE INPUTRCMSGST IS NULL
UPDATE #CBCTEMP SET INPUTRCMIGST=0 WHERE INPUTRCMIGST IS NULL

UPDATE #CBCTEMP SET OUTPUTRCMCGST=0 WHERE OUTPUTRCMCGST IS NULL
UPDATE #CBCTEMP SET OUTPUTRCMSGST=0 WHERE OUTPUTRCMSGST IS NULL
UPDATE #CBCTEMP SET OUTPUTRCMIGST=0 WHERE OUTPUTRCMIGST IS NULL

UPDATE #CBCTEMP SET CGSTPERCENTAGE = ROUND( ( (OUTPUTCGST)/(DEBIT-CREDIT) ) * 100, 2 ) WHERE OUTPUTCGST<>0 
UPDATE #CBCTEMP SET SGSTPERCENTAGE = ROUND( ( (OUTPUTSGST)/(DEBIT-CREDIT) ) * 100 ,2 ) WHERE OUTPUTSGST<>0 
UPDATE #CBCTEMP SET IGSTPERCENTAGE = ROUND( ( (OUTPUTIGST)/(DEBIT-CREDIT) ) * 100, 2 ) WHERE OUTPUTIGST<>0 





UPDATE #CBCTEMP SET CGSTPERCENTAGE = 6.0 WHERE CGSTPERCENTAGE BETWEEN 4 AND 8
UPDATE #CBCTEMP SET CGSTPERCENTAGE = 9.0 WHERE CGSTPERCENTAGE BETWEEN 7 AND 11
UPDATE #CBCTEMP SET SGSTPERCENTAGE = 9.0 WHERE SGSTPERCENTAGE BETWEEN 7 AND 11
UPDATE #CBCTEMP SET IGSTPERCENTAGE =18.0 WHERE IGSTPERCENTAGE BETWEEN 17 AND 19
UPDATE  #CBCTEMP SET CGSTPERCENTAGE = 14.0 WHERE CGSTPERCENTAGE BETWEEN 13 AND 14
UPDATE  #CBCTEMP SET SGSTPERCENTAGE = 14.0 WHERE SGSTPERCENTAGE BETWEEN 13 AND 14

 

 

INSERT INTO BI.SALESHISTORY
(ORGID,FINYEAR,PERIOD,TRANGRP,TRANSID,TRANSTYPE,INVOICENUMBER,TRANSACTIONDATE,SUPPCODE,ITEM,LEDGERCODE,INVOICEDATE,BATCHREF,
TAXABLE_VALUE,CGST_RATE,CGST_AMOUNT,SGST_RATE,SGST_AMOUNT,IGST_RATE,IGST_AMOUNT,CGST_INPUT_RCM_AMOUNT,CGST_OUTPUT_RCM_AMOUNT,
SGST_INPUT_RCM_AMOUNT,SGST_OUTPUT_RCM_AMOUNT,IGST_INPUT_RCM_AMOUNT,IGST_OUTPUT_RCM_AMOUNT  )
SELECT
 ORGID,YEAR,PERIOD,TRANGRP,TRANSID,TRANSTYPE,TRANSREF,PDATE,CREDNO,DESCRIPTION,LEDGERCODE,INVOICEDATE, BATCHREF,
 ABS( (DEBIT-CREDIT)) ,CGSTPERCENTAGE,OUTPUTCGST,SGSTPERCENTAGE,OUTPUTSGST,IGSTPERCENTAGE,OUTPUTIGST,INPUTRCMCGST,OUTPUTRCMCGST,
  INPUTRCMSGST,OUTPUTRCMSGST,INPUTRCMIGST,OUTPUTRCMIGST  
FROM #CBCTEMP



---------- CBD TRANSACTIONS



CREATE TABLE #CBDTEMP(LINECOUNT INT PRIMARY KEY , ORGID INT,  YEAR INT,PERIOD INT,PDATE DATETIME,INVOICEDATE DATETIME,
BATCHREF VARCHAR(10), TRANSREF VARCHAR(10), CREDNO VARCHAR(10), TRANGRP INT,TRANSID INT,LEDGERCODE VARCHAR(10) ,
DESCRIPTION VARCHAR(300),DEBIT DECIMAL(18,2),CREDIT DECIMAL(18,2),
OUTPUTCGST DECIMAL(18,2),OUTPUTSGST DECIMAL(18,2),OUTPUTIGST DECIMAL(18,2),INPUTRCMCGST DECIMAL(18,2),INPUTRCMSGST DECIMAL(18,2),INPUTRCMIGST DECIMAL(18,2),
OUTPUTRCMCGST DECIMAL(18,2),OUTPUTRCMSGST DECIMAL(18,2),OUTPUTRCMIGST DECIMAL(18,2) , TRANSTYPE CHAR(3), GSTEXPENSE DECIMAL(18,2) )

SET @ITEMCOUNT = 0  

 
SELECT @LASTTRANGRP = MAX(TRANGRP) FROM BI.SALESHISTORY WHERE TRANSTYPE IN ('CBD','PCR')
DECLARE CBDTRANGRP  CURSOR FOR SELECT DISTINCT TRANGRP FROM TRANSACTIONS WHERE YEAR>=2018 AND PERIOD>3 AND LEFT(TRANSTYPE,3) IN ('CBD'  ,'PCR' ) AND
 LEDGERCODE IN (SELECT LEDGERCODE FROM #GSTOUTPUT)  AND TRANGRP >@LASTTRANGRP 
OPEN CBDTRANGRP 
FETCH NEXT FROM CBDTRANGRP INTO @TRANGRP 

WHILE @@FETCH_STATUS=0
BEGIN

  SELECT  @CBDRECEIVEDATE =MAX(RECEIVEDDATE)  FROM TRANSACTIONS WHERE TRANGRP=@TRANGRP  
  SELECT  @CBDTRANSID =MIN(TRANSID)  FROM TRANSACTIONS WHERE  TRANGRP = @TRANGRP AND LEDGERCODE IN (SELECT LEDGERCODE FROM #GSTOUTPUT) 
  SELECT  @CBDLEDGERCODE = LEDGERCODE FROM TRANSACTIONS WHERE TRANGRP = @TRANGRP  AND ALLOCATION='Contracts' 

  SELECT @CONTRACTDEBIT = SUM(DEBIT),@CONTRACTCREDIT=SUM(CREDIT) FROM TRANSACTIONS WHERE TRANGRP = @TRANGRP  AND (VATDEBIT-VATCREDIT)<0
  SELECT TOP 1  @TRANSID = TRANSID FROM TRANSACTIONS WHERE TRANGRP = @TRANGRP AND  VATCREDIT>0 
  SET @ITEMCOUNT = @ITEMCOUNT + 1
 
  

  INSERT INTO #CBDTEMP(LINECOUNT,ORGID,YEAR,PERIOD,PDATE,BATCHREF,TRANSREF,CREDNO,TRANGRP,TRANSID, LEDGERCODE,DESCRIPTION,DEBIT,CREDIT,INVOICEDATE,TRANSTYPE)
  SELECT @ITEMCOUNT,ORGID,YEAR,PERIOD,PDATE,BATCHREF,TRANSREF,CREDNO,TRANGRP,TRANSID, @CBDLEDGERCODE,DESCRIPTION,@CONTRACTDEBIT,@CONTRACTCREDIT,@CBDRECEIVEDATE,LEFT(TRANSTYPE,3) 
  FROM TRANSACTIONS WHERE TRANSID = @TRANSID AND TRANGRP = @TRANGRP 

 

  CREATE TABLE #TEMPCBD(LINEINDEX INT PRIMARY  KEY IDENTITY(1,1), TRANSID  INT ) 
  DELETE FROM #TEMPCBD

  INSERT INTO #TEMPCBD
  SELECT TRANSID FROM TRANSACTIONS WHERE TRANGRP = @TRANGRP AND  LEDGERCODE IN (SELECT LEDGERCODE FROM #GSTOUTPUT)

  SELECT  @LINECOUNT = COUNT(*) FROM #TEMPCBD 
  SET @INDEXCOUNTER = 1


  WHILE @INDEXCOUNTER<=@LINECOUNT
  BEGIN
 
    SELECT @LEDGERCODE = LEDGERCODE, @TAXAMOUNT = (CREDIT-DEBIT)  FROM TRANSACTIONS WHERE TRANSID =(SELECT TRANSID FROM  #TEMPCBD WHERE LINEINDEX=@INDEXCOUNTER) 


 	   IF  @LEDGERCODE = '1310025'    UPDATE #CBDTEMP SET OUTPUTCGST= @TAXAMOUNT WHERE LINECOUNT=@ITEMCOUNT AND TRANGRP = @TRANGRP 
       IF  @LEDGERCODE = '1310026'    UPDATE #CBDTEMP SET OUTPUTSGST= @TAXAMOUNT WHERE LINECOUNT=@ITEMCOUNT AND TRANGRP = @TRANGRP 
	   IF  @LEDGERCODE = '1310027'    UPDATE #CBDTEMP SET OUTPUTIGST= @TAXAMOUNT WHERE LINECOUNT=@ITEMCOUNT  AND TRANGRP = @TRANGRP 
       IF  @LEDGERCODE = '1310031'    UPDATE #CBDTEMP SET INPUTRCMCGST= @TAXAMOUNT WHERE LINECOUNT=@ITEMCOUNT AND TRANGRP = @TRANGRP 
	   IF  @LEDGERCODE = '1310032'    UPDATE #CBDTEMP SET INPUTRCMSGST= @TAXAMOUNT WHERE LINECOUNT=@ITEMCOUNT AND TRANGRP = @TRANGRP 
	   IF  @LEDGERCODE = '1310033'    UPDATE #CBDTEMP SET INPUTRCMIGST= @TAXAMOUNT WHERE LINECOUNT=@ITEMCOUNT AND TRANGRP = @TRANGRP 
	   IF  @LEDGERCODE = '1310034'    UPDATE #CBDTEMP SET OUTPUTRCMCGST= @TAXAMOUNT WHERE LINECOUNT=@ITEMCOUNT AND TRANGRP = @TRANGRP 
	   IF  @LEDGERCODE = '1310035'    UPDATE #CBDTEMP SET OUTPUTRCMSGST= @TAXAMOUNT WHERE LINECOUNT=@ITEMCOUNT AND TRANGRP = @TRANGRP 
	   IF  @LEDGERCODE = @GSTEXPENSE  UPDATE #CBDTEMP SET GSTEXPENSE = @TAXAMOUNT WHERE LINECOUNT = @ITEMCOUNT AND TRANGRP = @TRANGRP 

    SET @INDEXCOUNTER = @INDEXCOUNTER + 1
  END

  DROP TABLE #TEMPCBD

  FETCH NEXT FROM CBDTRANGRP INTO @TRANGRP 
END

CLOSE CBDTRANGRP
DEALLOCATE   CBDTRANGRP 

ALTER TABLE #CBDTEMP ADD CGSTPERCENTAGE DECIMAL(18,2)
ALTER TABLE #CBDTEMP ADD SGSTPERCENTAGE DECIMAL(18,2)
ALTER TABLE #CBDTEMP ADD IGSTPERCENTAGE DECIMAL(18,2)

ALTER TABLE #CBDTEMP ADD CGSTRCMPERCENTAGE DECIMAL(18,2)
ALTER TABLE #CBDTEMP ADD SGSTRCMPERCENTAGE DECIMAL(18,2)
ALTER TABLE #CBDTEMP ADD IGSTRCMPERCENTAGE DECIMAL(18,2)

UPDATE #CBDTEMP SET CGSTPERCENTAGE =0
UPDATE #CBDTEMP SET SGSTPERCENTAGE =0
UPDATE #CBDTEMP SET IGSTPERCENTAGE =0

UPDATE #CBDTEMP SET CGSTRCMPERCENTAGE =0
UPDATE #CBDTEMP SET SGSTRCMPERCENTAGE =0
UPDATE #CBDTEMP SET IGSTRCMPERCENTAGE =0
UPDATE #CBDTEMP SET  OUTPUTCGST=0 WHERE  OUTPUTCGST IS NULL
UPDATE #CBDTEMP SET  OUTPUTSGST=0 WHERE  OUTPUTSGST IS NULL
UPDATE #CBDTEMP SET  OUTPUTIGST=0 WHERE  OUTPUTIGST IS NULL
UPDATE #CBDTEMP SET INPUTRCMCGST=0 WHERE INPUTRCMCGST IS NULL
UPDATE #CBDTEMP SET INPUTRCMSGST=0 WHERE INPUTRCMSGST IS NULL
UPDATE #CBDTEMP SET INPUTRCMIGST=0 WHERE INPUTRCMIGST IS NULL
UPDATE #CBDTEMP SET OUTPUTRCMCGST=0 WHERE OUTPUTRCMCGST IS NULL
UPDATE #CBDTEMP SET OUTPUTRCMSGST=0 WHERE OUTPUTRCMSGST IS NULL
UPDATE #CBDTEMP SET OUTPUTRCMIGST=0 WHERE OUTPUTRCMIGST IS NULL
UPDATE #CBDTEMP SET CGSTPERCENTAGE = ROUND( ( ( OUTPUTCGST)/(DEBIT-CREDIT) ) * 100, 2 ) WHERE  OUTPUTCGST<>0 
UPDATE #CBDTEMP SET SGSTPERCENTAGE = ROUND( ( ( OUTPUTSGST)/(DEBIT-CREDIT) ) * 100 ,2 ) WHERE  OUTPUTSGST<>0 
UPDATE #CBDTEMP SET IGSTPERCENTAGE = ROUND( ( ( OUTPUTIGST)/(DEBIT-CREDIT) ) * 100, 2 ) WHERE  OUTPUTIGST<>0 
UPDATE #CBDTEMP SET CGSTPERCENTAGE = 6.0 WHERE CGSTPERCENTAGE BETWEEN 4 AND 8
UPDATE #CBDTEMP SET CGSTRCMPERCENTAGE = 6.0 WHERE CGSTRCMPERCENTAGE BETWEEN 4 AND 8
UPDATE #CBDTEMP SET CGSTPERCENTAGE = 9.0 WHERE CGSTPERCENTAGE BETWEEN 7 AND 11
UPDATE #CBDTEMP SET CGSTRCMPERCENTAGE = 9.0 WHERE CGSTRCMPERCENTAGE BETWEEN 7 AND 11
UPDATE #CBDTEMP SET SGSTPERCENTAGE = 9.0 WHERE SGSTPERCENTAGE BETWEEN 7 AND 11
UPDATE #CBDTEMP SET SGSTRCMPERCENTAGE = 9.0 WHERE SGSTRCMPERCENTAGE BETWEEN 7 AND 11
UPDATE #CBDTEMP SET IGSTPERCENTAGE =18.0 WHERE IGSTPERCENTAGE BETWEEN 17 AND 19
UPDATE #CBDTEMP SET IGSTRCMPERCENTAGE = 18.0 WHERE IGSTRCMPERCENTAGE BETWEEN 17 AND 19

 

INSERT INTO BI.SALESHISTORY
(ORGID,FINYEAR,PERIOD,TRANGRP,TRANSID,TRANSTYPE,INVOICENUMBER,TRANSACTIONDATE,SUPPCODE,ITEM,LEDGERCODE,INVOICEDATE,BATCHREF,
TAXABLE_VALUE,CGST_RATE,CGST_AMOUNT,SGST_RATE,SGST_AMOUNT,IGST_RATE,IGST_AMOUNT,CGST_INPUT_RCM_AMOUNT,CGST_OUTPUT_RCM_AMOUNT,
SGST_INPUT_RCM_AMOUNT,SGST_OUTPUT_RCM_AMOUNT,IGST_INPUT_RCM_AMOUNT,IGST_OUTPUT_RCM_AMOUNT )
SELECT
 ORGID,YEAR,PERIOD,TRANGRP,TRANSID,TRANSTYPE,TRANSREF,PDATE,CREDNO,DESCRIPTION,LEDGERCODE,INVOICEDATE, BATCHREF,
 (DEBIT-CREDIT),CGSTPERCENTAGE, OUTPUTCGST,SGSTPERCENTAGE, OUTPUTSGST,IGSTPERCENTAGE, OUTPUTIGST,INPUTRCMCGST,OUTPUTRCMCGST,
  INPUTRCMSGST,OUTPUTRCMSGST,INPUTRCMIGST,OUTPUTRCMIGST  
FROM #CBDTEMP


---- JOURNALS

CREATE TABLE #JNLTEMP(LINECOUNT INT PRIMARY KEY , ORGID INT,  YEAR INT,PERIOD INT,PDATE DATETIME,INVOICEDATE DATETIME,
BATCHREF VARCHAR(10), TRANSREF VARCHAR(10), CREDNO VARCHAR(10), TRANGRP INT,TRANSID INT,LEDGERCODE VARCHAR(10) ,
DESCRIPTION VARCHAR(300),DEBIT DECIMAL(18,2),CREDIT DECIMAL(18,2),
INPUTCGST DECIMAL(18,2),INPUTSGST DECIMAL(18,2),INPUTIGST DECIMAL(18,2),
INPUTRCMCGST DECIMAL(18,2),INPUTRCMSGST DECIMAL(18,2),INPUTRCMIGST DECIMAL(18,2),
OUTPUTCGST DECIMAL(18,2),OUTPUTSGST DECIMAL(18,2),OUTPUTIGST DECIMAL(18,2),
OUTPUTRCMCGST DECIMAL(18,2),OUTPUTRCMSGST DECIMAL(18,2),OUTPUTRCMIGST DECIMAL(18,2) , 
GSTEXPENSE DECIMAL(18,2), TRANSTYPE CHAR(3) )

 
DECLARE @ALLOCATION VARCHAR(15) 

SELECT @LASTTRANGRP = MAX(TRANGRP) FROM BI.SALESHISTORY WHERE TRANSTYPE ='JNL' 
DECLARE JNLCURSOR CURSOR FOR 
SELECT DISTINCT TRANGRP FROM TRANSACTIONS 
WHERE YEAR>=2018 AND PERIOD>3 AND TRANSTYPE='JNL'  AND   LEDGERCODE IN (SELECT LEDGERCODE FROM #GSTOUTPUT )  AND TRANGRP >@LASTTRANGRP 
  
OPEN JNLCURSOR 
FETCH NEXT FROM JNLCURSOR INTO @TRANGRP 

SET @ITEMCOUNT = 0

WHILE @@FETCH_STATUS = 0
BEGIN
  SET @GSTCOUNT = 0
  SET @CREDITORCOUNT = 0
  SELECT @GSTCOUNT = COUNT(*) FROM TRANSACTIONS WHERE TRANGRP = @TRANGRP AND ( LEDGERCODE ='1310025' OR LEDGERCODE='1310028' OR LEDGERCODE='1310034'     )
  SELECT @CREDITORCOUNT = COUNT(*) FROM TRANSACTIONS WHERE TRANGRP = @TRANGRP AND LEDGERCODE ='1315000' 
  SELECT @EXPENSECOUNT = COUNT(*) FROM TRANSACTIONS WHERE TRANGRP=@TRANGRP AND ALLOCATION='Contracts' AND LEDGERCODE <>'5130001' 
  SELECT @GSTEXPENSECOUNT = COUNT(*) FROM TRANSACTIONS WHERE TRANGRP = @TRANGRP AND LEDGERCODE='5130001' 
  
  
 
	  CREATE TABLE #TEMPJNL11(LINEINDEX INT PRIMARY  KEY IDENTITY(1,1), TRANSID  INT ) 
      DELETE FROM #TEMPJNL11

      INSERT INTO #TEMPJNL11
      SELECT TRANSID FROM TRANSACTIONS WHERE TRANGRP = @TRANGRP AND  LEDGERCODE <>'2990000'   ORDER BY TRANSID 
      SELECT  @LINECOUNT = COUNT(*) FROM #TEMPJNL11 
	  SET @INDEXCOUNTER = 1
	  WHILE @INDEXCOUNTER<=@LINECOUNT
      BEGIN
	   SELECT  @ALLOCATION = ALLOCATION,
	           @TAXAMOUNT = (CREDIT-DEBIT),
			   @LEDGERCODE=LEDGERCODE ,
			   @TRANSID = TRANSID ,
			   @CREDNO = CREDNO
			   FROM TRANSACTIONS WHERE TRANSID =(SELECT TRANSID FROM  #TEMPJNL11 WHERE LINEINDEX=@INDEXCOUNTER)
	   IF ( (@ALLOCATION ='Contracts') AND (@LEDGERCODE<>@GSTEXPENSE)) 
	   BEGIN
	      SET @ITEMCOUNT = @ITEMCOUNT + 1
	      INSERT INTO #JNLTEMP(LINECOUNT,ORGID,YEAR,PERIOD,PDATE,INVOICEDATE,BATCHREF,TRANSREF,CREDNO,TRANGRP,TRANSID,LEDGERCODE,DESCRIPTION,DEBIT,CREDIT,TRANSTYPE)
		  SELECT @ITEMCOUNT,ORGID,YEAR,PERIOD,PDATE,PDATE,BATCHREF,TRANSREF,CREDNO,TRANGRP,TRANSID,LEDGERCODE,DESCRIPTION,DEBIT,CREDIT,TRANSTYPE 
		  FROM TRANSACTIONS WHERE TRANSID = @TRANSID 
	   END 
       IF  @LEDGERCODE = '1310031'    UPDATE #JNLTEMP SET INPUTRCMCGST= @TAXAMOUNT WHERE LINECOUNT=@ITEMCOUNT AND TRANGRP = @TRANGRP 
	   IF  @LEDGERCODE = '1310032'    UPDATE #JNLTEMP SET INPUTRCMSGST= @TAXAMOUNT WHERE LINECOUNT=@ITEMCOUNT AND TRANGRP = @TRANGRP 
	   IF  @LEDGERCODE = '1310033'    UPDATE #JNLTEMP SET INPUTRCMIGST= @TAXAMOUNT WHERE LINECOUNT=@ITEMCOUNT AND TRANGRP = @TRANGRP 
	   IF  @LEDGERCODE = '1310034'    UPDATE #JNLTEMP SET OUTPUTRCMCGST= @TAXAMOUNT WHERE LINECOUNT=@ITEMCOUNT AND TRANGRP = @TRANGRP 
	   IF  @LEDGERCODE = '1310035'    UPDATE #JNLTEMP SET OUTPUTRCMSGST= @TAXAMOUNT WHERE LINECOUNT=@ITEMCOUNT AND TRANGRP = @TRANGRP 
	   IF  @LEDGERCODE = '1310028'    UPDATE #JNLTEMP SET OUTPUTCGST= @TAXAMOUNT WHERE LINECOUNT=@ITEMCOUNT AND TRANGRP = @TRANGRP 
	   IF  @LEDGERCODE = '1310028'    UPDATE #JNLTEMP SET OUTPUTSGST= @TAXAMOUNT WHERE LINECOUNT=@ITEMCOUNT  AND TRANGRP = @TRANGRP 
	   IF  @LEDGERCODE = @GSTEXPENSE  UPDATE #JNLTEMP SET GSTEXPENSE = @TAXAMOUNT WHERE LINECOUNT = @ITEMCOUNT AND TRANGRP = @TRANGRP 
	   IF  @LEDGERCODE = '1315000'    UPDATE #JNLTEMP SET CREDNO = CREDNO WHERE LINECOUNT = @ITEMCOUNT AND TRANGRP = @TRANGRP 
	   SET @INDEXCOUNTER = @INDEXCOUNTER + 1
	  END
   DROP TABLE #TEMPJNL11
   FETCH  NEXT FROM JNLCURSOR INTO @TRANGRP 

END

CLOSE    JNLCURSOR
DEALLOCATE JNLCURSOR
 

UPDATE #JNLTEMP SET DEBIT = 0 WHERE DEBIT IS NULL
UPDATE #JNLTEMP SET CREDIT =0  WHERE CREDIT IS NULL
UPDATE #JNLTEMP SET INPUTCGST = 0 WHERE INPUTCGST IS NULL
UPDATE #JNLTEMP SET INPUTSGST = 0 WHERE INPUTSGST IS NULL

UPDATE #JNLTEMP SET INPUTIGST = 0 WHERE INPUTIGST IS NULL
UPDATE #JNLTEMP SET INPUTRCMCGST =0  WHERE INPUTRCMCGST IS NULL
UPDATE #JNLTEMP SET INPUTRCMSGST = 0 WHERE INPUTRCMSGST IS NULL
UPDATE #JNLTEMP SET INPUTRCMIGST = 0 WHERE INPUTRCMIGST IS NULL

UPDATE #JNLTEMP SET OUTPUTCGST = 0 WHERE OUTPUTCGST IS NULL
UPDATE #JNLTEMP SET OUTPUTSGST =0  WHERE OUTPUTSGST IS NULL
UPDATE #JNLTEMP SET OUTPUTIGST = 0 WHERE OUTPUTIGST IS NULL
UPDATE #JNLTEMP SET OUTPUTRCMCGST = 0 WHERE OUTPUTRCMCGST IS NULL

UPDATE #JNLTEMP SET OUTPUTRCMSGST =0  WHERE OUTPUTRCMSGST IS NULL
UPDATE #JNLTEMP SET OUTPUTRCMIGST = 0 WHERE OUTPUTRCMIGST IS NULL
UPDATE #JNLTEMP SET GSTEXPENSE = 0 WHERE GSTEXPENSE IS NULL
 
 
 
DELETE   FROM #JNLTEMP WHERE (GSTEXPENSE = 0) AND (INPUTRCMIGST=0) AND   (INPUTRCMIGST = 0) AND (INPUTRCMSGST = 0) AND (INPUTIGST = 0) AND (INPUTSGST = 0) AND (INPUTCGST = 0) 
AND (OUTPUTCGST = 0 ) AND (OUTPUTSGST=0) AND (OUTPUTIGST=0)

ALTER TABLE #JNLTEMP ADD CGSTPERCENTAGE DECIMAL(18,2)
ALTER TABLE #JNLTEMP ADD SGSTPERCENTAGE DECIMAL(18,2)
ALTER TABLE #JNLTEMP ADD IGSTPERCENTAGE DECIMAL(18,2)

ALTER TABLE #JNLTEMP ADD CGSTRCMPERCENTAGE DECIMAL(18,2)
ALTER TABLE #JNLTEMP ADD SGSTRCMPERCENTAGE DECIMAL(18,2)
ALTER TABLE #JNLTEMP ADD IGSTRCMPERCENTAGE DECIMAL(18,2)

UPDATE #JNLTEMP SET CGSTPERCENTAGE =0
UPDATE #JNLTEMP SET SGSTPERCENTAGE =0
UPDATE #JNLTEMP SET IGSTPERCENTAGE =0
UPDATE #JNLTEMP SET CGSTRCMPERCENTAGE =0
UPDATE #JNLTEMP SET SGSTRCMPERCENTAGE =0
UPDATE #JNLTEMP SET IGSTRCMPERCENTAGE =0
UPDATE #JNLTEMP SET INPUTCGST=0 WHERE INPUTCGST IS NULL
UPDATE #JNLTEMP SET INPUTSGST=0 WHERE INPUTSGST IS NULL
UPDATE #JNLTEMP SET INPUTIGST=0 WHERE INPUTIGST IS NULL
UPDATE #JNLTEMP SET INPUTRCMCGST=0 WHERE INPUTRCMCGST IS NULL
UPDATE #JNLTEMP SET INPUTRCMSGST=0 WHERE INPUTRCMSGST IS NULL
UPDATE #JNLTEMP SET INPUTRCMIGST=0 WHERE INPUTRCMIGST IS NULL
UPDATE #JNLTEMP SET OUTPUTRCMCGST=0 WHERE OUTPUTRCMCGST IS NULL
UPDATE #JNLTEMP SET OUTPUTRCMSGST=0 WHERE OUTPUTRCMSGST IS NULL
UPDATE #JNLTEMP SET OUTPUTRCMIGST=0 WHERE OUTPUTRCMIGST IS NULL
UPDATE #JNLTEMP SET CGSTPERCENTAGE = ROUND( ( (INPUTCGST)/(DEBIT-CREDIT) ) * 100, 2 ) WHERE INPUTCGST<>0 
UPDATE #JNLTEMP SET SGSTPERCENTAGE = ROUND( ( (INPUTSGST)/(DEBIT-CREDIT) ) * 100 ,2 ) WHERE INPUTSGST<>0 
UPDATE #JNLTEMP SET IGSTPERCENTAGE = ROUND( ( (INPUTIGST)/(DEBIT-CREDIT) ) * 100, 2 ) WHERE INPUTIGST<>0 



UPDATE #JNLTEMP SET CGSTPERCENTAGE =ABS(CGSTPERCENTAGE),SGSTPERCENTAGE=ABS(SGSTPERCENTAGE), IGSTPERCENTAGE=ABS(IGSTPERCENTAGE) 
UPDATE #JNLTEMP SET CGSTPERCENTAGE = 6.0 WHERE CGSTPERCENTAGE BETWEEN 4 AND 8
UPDATE #JNLTEMP SET CGSTPERCENTAGE = 9.0 WHERE CGSTPERCENTAGE BETWEEN 7 AND 11
UPDATE #JNLTEMP SET SGSTPERCENTAGE = 9.0 WHERE SGSTPERCENTAGE BETWEEN 7 AND 11
UPDATE #JNLTEMP SET IGSTPERCENTAGE =18.0 WHERE IGSTPERCENTAGE BETWEEN 17 AND 19
 


 

INSERT INTO BI.SALESHISTORY
(ORGID,FINYEAR,PERIOD,TRANGRP,TRANSID,TRANSTYPE,INVOICENUMBER,TRANSACTIONDATE,SUPPCODE,ITEM,LEDGERCODE,INVOICEDATE,BATCHREF,
TAXABLE_VALUE,CGST_RATE,CGST_AMOUNT,SGST_RATE,SGST_AMOUNT,IGST_RATE,IGST_AMOUNT,CGST_INPUT_RCM_AMOUNT,CGST_OUTPUT_RCM_AMOUNT,
SGST_INPUT_RCM_AMOUNT,SGST_OUTPUT_RCM_AMOUNT,IGST_INPUT_RCM_AMOUNT,IGST_OUTPUT_RCM_AMOUNT ,GST_EXPENSE)
SELECT
 ORGID,YEAR,PERIOD,TRANGRP,TRANSID,TRANSTYPE,TRANSREF,PDATE,CREDNO,DESCRIPTION,LEDGERCODE,INVOICEDATE, BATCHREF,
 (DEBIT-CREDIT),CGSTPERCENTAGE,INPUTCGST,SGSTPERCENTAGE,INPUTSGST,IGSTPERCENTAGE,INPUTIGST,INPUTRCMCGST,OUTPUTRCMCGST,
  INPUTRCMSGST,OUTPUTRCMSGST,INPUTRCMIGST,OUTPUTRCMIGST  ,GSTEXPENSE
FROM #JNLTEMP

 
-- SALES 



CREATE TABLE #DTITEMP(LINECOUNT INT PRIMARY KEY , ORGID INT,  YEAR INT,PERIOD INT,PDATE DATE,INVOICEDATE DATE,  
BATCHREF VARCHAR(15), TRANSREF VARCHAR(25), CREDNO VARCHAR(15), TRANGRP INT,TRANSID INT,LEDGERCODE VARCHAR(15),DESCRIPTION VARCHAR(300),DEBIT DECIMAL(18,2),CREDIT DECIMAL(18,2),
OUTPUTCGST DECIMAL(18,2),OUTPUTSGST DECIMAL(18,2),OUTPUTIGST DECIMAL(18,2),INPUTRCMCGST DECIMAL(18,2),INPUTRCMSGST DECIMAL(18,2),INPUTRCMIGST DECIMAL(18,2),
OUTPUTRCMCGST DECIMAL(18,2),OUTPUTRCMSGST DECIMAL(18,2),OUTPUTRCMIGST DECIMAL(18,2) )

SET @ITEMCOUNT = 0  


SELECT @LASTTRANGRP = MAX(TRANGRP) FROM BI.SALESHISTORY WHERE TRANSTYPE='DTI'
DECLARE DTITRANGRP  CURSOR FOR 
SELECT DISTINCT TRANGRP FROM TRANSACTIONS WHERE YEAR>=2018 AND PERIOD>3 AND LEFT(TRANSTYPE,3)='DTI' AND TRANGRP >@LASTTRANGRP 
  AND LEDGERCODE IN (SELECT LEDGERCODE FROM #GSTOUTPUT)   
  

OPEN DTITRANGRP 
FETCH NEXT FROM DTITRANGRP INTO @TRANGRP 

WHILE @@FETCH_STATUS=0
BEGIN
   
   
  CREATE TABLE #TEMPDTI(LINEINDEX INT PRIMARY  KEY IDENTITY(1,1), TRANSID  INT ) 
  DELETE FROM #TEMPDTI
  INSERT INTO #TEMPDTI
  SELECT TRANSID FROM TRANSACTIONS WHERE TRANGRP = @TRANGRP AND LEDGERCODE NOT IN(SELECT ICGLCODE FROM #TEMPICLA) ORDER BY TRANSID 
  SELECT  @LINECOUNT = COUNT(*) FROM #TEMPDTI
  SET @INDEXCOUNTER = 1
  WHILE @INDEXCOUNTER<=@LINECOUNT
  BEGIN                                                                                                                                                                                                                                                       
 
    SELECT @TRANSID = TRANSID FROM #TEMPDTI   WHERE LINEINDEX=@INDEXCOUNTER 
	SELECT @LEDGERCODE = LEDGERCODE, @TAXAMOUNT = (DEBIT-CREDIT),@NARRATION = DESCRIPTION ,@LEDGERALLOC = ALLOCATION 
	FROM TRANSACTIONS WHERE TRANSID =  (SELECT TRANSID FROM #TEMPDTI WHERE LINEINDEX = @INDEXCOUNTER )   
	 
	IF  ((@NARRATION LIKE 'Total Gross Billing%') OR (@NARRATION LIKE 'Total Work Done%' ) OR ( @LEDGERCODE IN ( '2541000','2541001','2541002'   )  )  )                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
	BEGIN 
	  SET @ITEMCOUNT = @ITEMCOUNT + 1
	  INSERT INTO #DTITEMP(LINECOUNT,ORGID,YEAR,PERIOD,PDATE,BATCHREF,TRANSREF,CREDNO,TRANGRP,TRANSID, LEDGERCODE,DESCRIPTION,DEBIT,CREDIT,INVOICEDATE)
	  SELECT @ITEMCOUNT,ORGID,YEAR,PERIOD,PDATE,BATCHREF,TRANSREF,CREDNO,TRANGRP,TRANSID, LEDGERCODE,DESCRIPTION,DEBIT,CREDIT,PDATE  FROM TRANSACTIONS WHERE TRANSID = @TRANSID
	END 
    IF  @LEDGERCODE = '1310028'    UPDATE #DTITEMP SET OUTPUTCGST=    (@TAXAMOUNT) WHERE LINECOUNT=@ITEMCOUNT 
    IF  @LEDGERCODE = '1310029'    UPDATE #DTITEMP SET OUTPUTSGST=    (@TAXAMOUNT) WHERE LINECOUNT=@ITEMCOUNT
    IF  @LEDGERCODE = '1310030'    UPDATE #DTITEMP SET OUTPUTIGST=    (@TAXAMOUNT) WHERE LINECOUNT=@ITEMCOUNT 
    IF  @LEDGERCODE = '1310031'    UPDATE #DTITEMP SET INPUTRCMCGST=  @TAXAMOUNT WHERE LINECOUNT=@ITEMCOUNT
	IF  @LEDGERCODE = '1310032'    UPDATE #DTITEMP SET INPUTRCMSGST=  @TAXAMOUNT WHERE LINECOUNT=@ITEMCOUNT
	IF  @LEDGERCODE = '1310033'    UPDATE #DTITEMP SET INPUTRCMIGST=  @TAXAMOUNT WHERE LINECOUNT=@ITEMCOUNT
	IF  @LEDGERCODE = '1310034'    UPDATE #DTITEMP SET OUTPUTRCMCGST= @TAXAMOUNT WHERE LINECOUNT=@ITEMCOUNT
	IF  @LEDGERCODE = '1310035'    UPDATE #DTITEMP SET OUTPUTRCMSGST= @TAXAMOUNT WHERE LINECOUNT=@ITEMCOUNT
    SET @INDEXCOUNTER = @INDEXCOUNTER + 1
  END
  DROP TABLE #TEMPDTI
  FETCH NEXT FROM DTITRANGRP INTO @TRANGRP 
END

CLOSE DTITRANGRP
DEALLOCATE   DTITRANGRP 

ALTER TABLE #DTITEMP ADD CGSTPERCENTAGE DECIMAL(18,2)
ALTER TABLE #DTITEMP ADD SGSTPERCENTAGE DECIMAL(18,2)
ALTER TABLE #DTITEMP ADD IGSTPERCENTAGE DECIMAL(18,2)
UPDATE #DTITEMP SET CGSTPERCENTAGE =0
UPDATE #DTITEMP SET SGSTPERCENTAGE =0
UPDATE #DTITEMP SET IGSTPERCENTAGE =0
UPDATE #DTITEMP SET OUTPUTCGST=0 WHERE OUTPUTCGST IS NULL
UPDATE #DTITEMP SET OUTPUTSGST=0 WHERE OUTPUTSGST IS NULL
UPDATE #DTITEMP SET OUTPUTIGST=0 WHERE OUTPUTIGST IS NULL
UPDATE #DTITEMP SET INPUTRCMCGST=0 WHERE INPUTRCMCGST IS NULL
UPDATE #DTITEMP SET INPUTRCMSGST=0 WHERE INPUTRCMSGST IS NULL
UPDATE #DTITEMP SET INPUTRCMIGST=0 WHERE INPUTRCMIGST IS NULL
UPDATE #DTITEMP SET OUTPUTRCMCGST=0 WHERE OUTPUTRCMCGST IS NULL
UPDATE #DTITEMP SET OUTPUTRCMSGST=0 WHERE OUTPUTRCMSGST IS NULL
UPDATE #DTITEMP SET OUTPUTRCMIGST=0 WHERE OUTPUTRCMIGST IS NULL

UPDATE #DTITEMP SET CGSTPERCENTAGE = ROUND( ( (OUTPUTCGST)/(DEBIT-CREDIT) ) * 100, 2 ) WHERE OUTPUTCGST<>0 
UPDATE #DTITEMP SET SGSTPERCENTAGE = ROUND( ( (OUTPUTSGST)/(DEBIT-CREDIT) ) * 100 ,2 ) WHERE OUTPUTSGST<>0 
UPDATE #DTITEMP SET IGSTPERCENTAGE = ROUND( ( (OUTPUTIGST)/(DEBIT-CREDIT) ) * 100, 2 ) WHERE OUTPUTIGST<>0 

UPDATE #DTITEMP SET CGSTPERCENTAGE = ROUND( ( (INPUTRCMCGST)/(DEBIT-CREDIT) ) * 100, 2 ) WHERE INPUTRCMCGST<>0 
UPDATE #DTITEMP SET SGSTPERCENTAGE = ROUND( ( (INPUTRCMSGST)/(DEBIT-CREDIT) ) * 100 ,2 ) WHERE INPUTRCMSGST<>0 
UPDATE #DTITEMP SET IGSTPERCENTAGE = ROUND( ( (INPUTRCMIGST)/(DEBIT-CREDIT) ) * 100, 2 ) WHERE INPUTRCMIGST<>0 

 
UPDATE  #DTITEMP SET CGSTPERCENTAGE = 6.0 WHERE CGSTPERCENTAGE BETWEEN 5.5 AND 6.9
UPDATE  #DTITEMP SET CGSTPERCENTAGE = 9.0 WHERE CGSTPERCENTAGE BETWEEN 7 AND 11
UPDATE  #DTITEMP SET SGSTPERCENTAGE = 9.0 WHERE SGSTPERCENTAGE BETWEEN 7 AND 11
UPDATE  #DTITEMP SET IGSTPERCENTAGE = 18.0 WHERE IGSTPERCENTAGE BETWEEN 17 AND 19
UPDATE  #DTITEMP SET CGSTPERCENTAGE = 14.0 WHERE CGSTPERCENTAGE BETWEEN 13 AND 14
UPDATE  #DTITEMP SET SGSTPERCENTAGE = 14.0 WHERE SGSTPERCENTAGE BETWEEN 13 AND 14
 

SELECT * FROM #DTITEMP 

DELETE FROM #DTITEMP WHERE  ((DEBIT=0) AND (CREDIT=0) AND  (OUTPUTCGST=0) AND (OUTPUTSGST=0) AND (OUTPUTIGST=0) AND (INPUTRCMCGST=0) AND (INPUTRCMSGST=0) AND (INPUTRCMIGST=0) )

UPDATE #DTITEMP SET DESCRIPTION =''

SELECT * FROM #DTITEMP 

INSERT INTO BI.SALESHISTORY
(ORGID,FINYEAR,PERIOD,TRANGRP,TRANSID,TRANSTYPE,INVOICENUMBER,TRANSACTIONDATE,SUPPCODE,ITEM,LEDGERCODE,BATCHREF,INVOICEDATE,
TAXABLE_VALUE,CGST_RATE,CGST_AMOUNT,SGST_RATE,SGST_AMOUNT,IGST_RATE,IGST_AMOUNT,CGST_INPUT_RCM_AMOUNT,CGST_OUTPUT_RCM_AMOUNT,
SGST_INPUT_RCM_AMOUNT,SGST_OUTPUT_RCM_AMOUNT,IGST_INPUT_RCM_AMOUNT,IGST_OUTPUT_RCM_AMOUNT)
SELECT
 ORGID,YEAR,PERIOD,TRANGRP,TRANSID,'DTI',TRANSREF,PDATE,CREDNO,DESCRIPTION,LEDGERCODE,BATCHREF,PDATE,
((DEBIT-CREDIT)),CGSTPERCENTAGE,OUTPUTCGST,SGSTPERCENTAGE,OUTPUTSGST,IGSTPERCENTAGE,OUTPUTIGST,INPUTRCMCGST,OUTPUTRCMCGST,
  INPUTRCMSGST,OUTPUTRCMSGST,INPUTRCMIGST,OUTPUTRCMIGST 
FROM #DTITEMP 
 





UPDATE BI.SALESHISTORY SET CGST_RATE =ABS(CGST_RATE),SGST_RATE=ABS(SGST_RATE), IGST_RATE=ABS(IGST_RATE) 
UPDATE BI.SALESHISTORY SET LEDGERNAME = UPPER(L.LEDGERNAME) FROM LEDGERCODES L INNER JOIN BI.SALESHISTORY BIP ON BIP.LEDGERCODE=L.LEDGERCODE 
UPDATE BI.SALESHISTORY SET SUPPLIERCITY =LTRIM(RTRIM(STR(C.PROVINCEID))), SUPPLIERGSTN=C.ISOCERTIFICATION,SUPPLIERNAME=UPPER(C.CREDNAME)
FROM CREDITORS C INNER JOIN BI.SALESHISTORY BIP ON BIP.SUPPCODE=C.CREDNUMBER 
UPDATE BI.SALESHISTORY SET SUPPLIERCITY =LTRIM(RTRIM(STR(S.PROVINCEID))), SUPPLIERGSTN=S.ISOCERTIFICATION,SUPPLIERNAME=UPPER(S.SUBNAME)
FROM SUBCONTRACTORS  S INNER JOIN BI.SALESHISTORY BIP ON BIP.SUPPCODE=S.SUBNUMBER 
UPDATE BI.SALESHISTORY SET SUPPLIERCITY =LTRIM(RTRIM(STR(D.PROVINCEID))), SUPPLIERGSTN=D.ISOCERTIFICATION,SUPPLIERNAME=UPPER(D.DEBTNAME)
FROM DEBTORS D INNER JOIN BI.SALESHISTORY BIP ON BIP.SUPPCODE=D.DEBTNUMBER 
UPDATE BI.SALESHISTORY SET SUPPLIERCITY = UPPER(BIS.SHORTNAME) FROM BI.STATES BIS INNER JOIN BI.SALESHISTORY BIP ON BIP.SUPPLIERCITY =BIS.PROVINCEID 
UPDATE BI.SALESHISTORY SET SUPPLIERCITYNAME = UPPER(BIS.STATENAME) FROM BI.STATES BIS INNER JOIN BI.SALESHISTORY BIP ON BIP.SUPPLIERCITY=BIS.SHORTNAME
UPDATE BI.SALESHISTORY SET CGST_RATE=0 ,CGST_AMOUNT=0  WHERE CGST_RATE IS NULL
UPDATE BI.SALESHISTORY SET SGST_RATE=0, SGST_AMOUNT=0  WHERE SGST_RATE IS NULL
UPDATE BI.SALESHISTORY SET IGST_RATE=0, IGST_AMOUNT=0  WHERE IGST_RATE IS NULL
UPDATE BI.SALESHISTORY SET CGST_INPUT_RCM_AMOUNT=0,CGST_OUTPUT_RCM_AMOUNT=0 WHERE CGST_INPUT_RCM_AMOUNT IS NULL 
UPDATE BI.SALESHISTORY SET SGST_INPUT_RCM_AMOUNT=0,SGST_OUTPUT_RCM_AMOUNT=0 WHERE SGST_INPUT_RCM_AMOUNT IS NULL 
UPDATE BI.SALESHISTORY SET IGST_INPUT_RCM_AMOUNT=0,IGST_OUTPUT_RCM_AMOUNT=0 WHERE IGST_INPUT_RCM_AMOUNT IS NULL 
UPDATE BI.SALESHISTORY SET GST_EXPENSE =0 WHERE GST_EXPENSE IS NULL
UPDATE BI.SALESHISTORY SET UOM='' WHERE UOM IS NULL
UPDATE BI.SALESHISTORY SET QTY=0 WHERE QTY IS NULL
UPDATE BI.SALESHISTORY SET RATE =0 WHERE RATE IS NULL
UPDATE BI.SALESHISTORY SET ITEM= UPPER(ITEM) ,SUPPLIERNAME = UPPER(SUPPLIERNAME),SUPPLIERCITY =UPPER(SUPPLIERCITY),SUPPLIERCITYNAME = UPPER(SUPPLIERCITYNAME) 
UPDATE BI.SALESHISTORY SET ORDERNO ='' WHERE ORDERNO IS NULL
UPDATE BI.SALESHISTORY SET SUPPLIERNAME='',SUPPLIERGSTN='' , SUPPLIERCITY='',SUPPLIERCITYNAME='' WHERE SUPPLIERNAME IS NULL

UPDATE BI.SALESHISTORY SET BORGNAME = B.BORGNAME , CILGSTIN = B.COMPREG FROM BORGS B INNER JOIN BI.SALESHISTORY BIP ON BIP.ORGID=B.BORGID 
UPDATE BI.SALESHISTORY SET DOCTYPE = TRANSTYPE 
UPDATE BI.SALESHISTORY SET GSTTYPE = 'OUTPUT' WHERE ABS(CGST_AMOUNT) > 0 
UPDATE BI.SALESHISTORY SET GSTTYPE = 'OUTPUT' WHERE ABS(IGST_AMOUNT) > 0 
UPDATE BI.SALESHISTORY SET GSTTYPE = 'RCM' WHERE ABS(CGST_INPUT_RCM_AMOUNT) > 0 
UPDATE BI.SALESHISTORY SET GSTTYPE = 'GST EXPENSE' WHERE ABS(GST_EXPENSE) > 0
UPDATE BI.SALESHISTORY SET DOCTYPE='SCI-CONTRA' WHERE TRANSTYPE='SCI' AND CGST_AMOUNT >0 


UPDATE BI.SALESHISTORY SET CGST_RATE = 2.5  WHERE CGST_RATE  BETWEEN 2 AND 3
UPDATE BI.SALESHISTORY SET SGST_RATE = 2.5  WHERE SGST_RATE  BETWEEN 2 AND 3


UPDATE BI.SALESHISTORY SET CGST_RATE = 6.0 WHERE CGST_RATE  BETWEEN 4 AND 8
UPDATE BI.SALESHISTORY SET SGST_RATE = 6.0 WHERE SGST_RATE  BETWEEN 4 AND 8


UPDATE BI.SALESHISTORY SET CGST_RATE = 9.0 WHERE CGST_RATE BETWEEN 7 AND 11
UPDATE BI.SALESHISTORY SET SGST_RATE = 9.0 WHERE SGST_RATE BETWEEN 7 AND 11



UPDATE BI.SALESHISTORY SET IGST_RATE =18.0 WHERE IGST_RATE BETWEEN 17 AND 19
UPDATE BI.SALESHISTORY SET IGST_RATE = 18.0 WHERE IGST_RATE BETWEEN 17 AND 19


UPDATE BI.SALESHISTORY SET PERIODNAME = P.PERIODDESC FROM PERIODMASTER P INNER JOIN BI.SALESHISTORY BIP ON BIP.PERIOD = P.PERIODID 
 
SELECT * FROM BI.SALESHISTORY    ORDER BY ORGID,PERIOD,TRANSTYPE 


 