/****** Object:  Procedure [BI].[spLoadSalesForGST]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE  PROCEDURE [BI].[spLoadSalesForGST]
as
 
--DELETE FROM BI.SALESHISTORY 
--DBCC CHECKIDENT ("BI.SALESHISTORY",RESEED,0)

DECLARE @CURRENTLASTTRANGRP INT
SELECT  @CURRENTLASTTRANGRP = MAX(TRANGRP) FROM BI.SALESHISTORY 


DECLARE @WIP VARCHAR(10)
DECLARE @RETAINED VARCHAR(10)
DECLARE @GSTEXPENSE VARCHAR(10)

DECLARE @CREDNO VARCHAR(10) 
DECLARE @GSTCOUNT  INT
DECLARE @CREDITORCOUNT INT
DECLARE @EXPENSECOUNT INT
 
CREATE TABLE #GSTOUTPUT(LEDGERCODE VARCHAR(10)) 
INSERT INTO #GSTOUTPUT VALUES ( '1310028' )
INSERT INTO #GSTOUTPUT VALUES ( '1310029' )
INSERT INTO #GSTOUTPUT VALUES ( '1310030' )


SET @GSTEXPENSE= '5130001'
  

SELECT @WIP= CONTROLFROMGL FROM CONTROLCODES WHERE CONTROLNAME ='Work in Progress' 
SELECT @RETAINED = CONTROLFROMGL FROM CONTROLCODES WHERE CONTROLNAME = 'Retained Income' 



DECLARE @LASTTRANGRP INT
DECLARE @STOCKFROM VARCHAR(10)
DECLARE @STOCKTO   VARCHAR(10)
DECLARE @FAFROM    VARCHAR(10)
DECLARE @FATO      VARCHAR(10)
DECLARE @CREDITORCODE VARCHAR(10)
DECLARE @TRANSFROM INT
DECLARE @TRANSEND  INT
DECLARE @TRANGRP INT
DECLARE @DEBTORCODE_FROM VARCHAR(10)
DECLARE @DEBTORCODE_TO VARCHAR(10)

DECLARE @CGSTPERC DECIMAL(15,2)
DECLARE @CGSTAMOUNT DECIMAL(15,2)

DECLARE @SGSTPERC DECIMAL(15,2)
DECLARE @SGSTAMOUNT DECIMAL(15,2)

DECLARE @IGSTPERC DECIMAL(15,2)
DECLARE @IGSTAMOUNT DECIMAL(15,2)

DECLARE @CESSPERC DECIMAL(15,2)
DECLARE @CESSAMOUNT DECIMAL(15,2)

DECLARE @TAXABLEAMOUNT DECIMAL(15,2)

DECLARE @SUPPLIERNAME VARCHAR(90)
DECLARE @SUPPLIERADDRESS VARCHAR(80)
DECLARE @SUPPLIERGSTN VARCHAR(15)
DECLARE @STATEOFSUPPLY CHAR(2)
DECLARE @SUPPLIERCITY  VARCHAR(40)
DECLARE @SUPPLIERPROVINCE INT 
DECLARE @STATECODE CHAR(2)

DECLARE @ORGGSTN  VARCHAR(15)

DECLARE @GRN VARCHAR(50)
DECLARE @GRNQTY DECIMAL(15,2) 
DECLARE @GRNDATE DATETIME
DECLARE @GRNAMOUNT DECIMAL(15,2)

DECLARE @ORGID INT 
DECLARE @SUPPLIERCODE VARCHAR(10)
DECLARE @INDEXCOUNTER INT
DECLARE @TRANSID  INT
DECLARE @LINECOUNT INT 
DECLARE @LEDGERALLOC VARCHAR(15)
DECLARE @LEDGERCODE VARCHAR(10)
DECLARE @ITEMCOUNT INT 
DECLARE @TAXAMOUNT DECIMAL(18,2) 
DECLARE @TRANSACTIONORG INT 
DECLARE @NARRATION VARCHAR(255)
DECLARE @GSTLEDGERS INT 
DECLARE @GSTEXPENSECOUNT DECIMAL(18,2) 
DECLARE @CONTRA INT

DECLARE @CRILEDGERCODE VARCHAR(10)
DECLARE @CRIINVOICEDATE DATETIME 
DECLARE @CBCRECEIVEDATE DATETIME 
DECLARE @CBCTRANSID INT
DECLARE @CBCLEDGERCODE VARCHAR(15)
DECLARE @CBDRECEIVEDATE DATETIME 
DECLARE @CBDTRANSID INT
DECLARE @CBDLEDGERCODE VARCHAR(15)

DECLARE @RCMCGSTCOUNT INT
DECLARE @RCMCGSTRATE DECIMAL(18,2)

DECLARE @RCMIGSTCOUNT INT
DECLARE @RCMIGSTRATE DECIMAL(18,2)

DECLARE @CGSTCOUNT INT
DECLARE @RCMSGSTAMOUNT DECIMAL(18,2) 
DECLARE @IGSTCOUNT INT 


DECLARE @LINEALREADYENTERED INT 

SELECT @STOCKFROM=CONTROLFROMGL , @STOCKTO=CONTROLTOGL FROM CONTROLCODES WHERE CONTROLNAME='Stock' 
SELECT @FAFROM =CONTROLFROMGL , @FATO=CONTROLTOGL FROM CONTROLCODES WHERE CONTROLNAME='Fixed Asset' 
SELECT @CREDITORCODE = CONTROLFROMGL FROM CONTROLCODES WHERE CONTROLNAME='Creditors' 
SELECT @DEBTORCODE_FROM = CONTROLFROMGL FROM CONTROLCODES WHERE CONTROLNAME='Debtors' 
SELECT @DEBTORCODE_TO = CONTROLTOGL FROM  CONTROLCODES WHERE CONTROLNAME='Debtors' 

SELECT ICGLCODE INTO #TEMPICLA  FROM BORGS  WHERE BORGID NOT IN (SELECT BORGID FROM BORGS WHERE ICGLCODE IS NULL ) 
INSERT INTO #TEMPICLA VALUES (@WIP)
INSERT INTO #TEMPICLA VALUES (@RETAINED) 
 
CREATE TABLE #GSTTRANS (LEDGERCODE VARCHAR(15),PERC DECIMAL(18,2) ) 
CREATE TABLE #TAXAMOUNT (LEDGERCODE VARCHAR(10),TAXAMOUNT DECIMAL(18,2))
CREATE TABLE #TAXAMOUNTSCI (LEDGERCODE VARCHAR(10),TAXAMOUNT DECIMAL(18,2),WORKDONE DECIMAL(18,2),PERC DECIMAL(18,2) )

------ DTI

SELECT TRANGRP INTO #DTICGST FROM TRANSACTIONS WHERE YEAR>=2021  AND LEFT(BATCHREF,3)='DTI' AND LEDGERCODE ='1310028'
       AND TRANGRP NOT IN (SELECT TRANGRP FROM BI.SALESHISTORY WHERE LEDGERCODE='1310028' AND DOCTYPE='DTI' )
SELECT TRANGRP INTO #DTISGST FROM TRANSACTIONS WHERE YEAR>=2021  AND LEFT(BATCHREF,3)='DTI' AND LEDGERCODE ='1310029' 
       AND TRANGRP NOT IN (SELECT TRANGRP FROM BI.SALESHISTORY WHERE LEDGERCODE='1310029' AND DOCTYPE='DTI' )
SELECT TRANGRP INTO #DTIIGST FROM TRANSACTIONS WHERE YEAR>=2021  AND LEFT(BATCHREF,3)='DTI' AND LEDGERCODE ='1310030'
       AND TRANGRP NOT IN (SELECT TRANGRP FROM BI.SALESHISTORY WHERE LEDGERCODE='1310030' AND DOCTYPE='DTI' )

SELECT TRANGRP INTO #DTIRCGST FROM TRANSACTIONS WHERE YEAR>=2021  AND LEFT(BATCHREF,3)='DTI' AND LEDGERCODE ='1310031'
      AND TRANGRP NOT IN (SELECT TRANGRP FROM BI.SALESHISTORY WHERE LEDGERCODE='1310031' AND DOCTYPE='DTI' )
SELECT TRANGRP INTO #DTIRSGST FROM TRANSACTIONS WHERE YEAR>=2021  AND LEFT(BATCHREF,3)='DTI' AND LEDGERCODE ='1310032'
      AND TRANGRP NOT IN (SELECT TRANGRP FROM BI.SALESHISTORY WHERE LEDGERCODE='1310032' AND DOCTYPE='DTI' )
SELECT TRANGRP INTO #DTIRIGST FROM TRANSACTIONS WHERE YEAR>=2021  AND LEFT(BATCHREF,3)='DTI' AND LEDGERCODE ='1310033'
      AND TRANGRP NOT IN (SELECT TRANGRP FROM BI.SALESHISTORY WHERE LEDGERCODE='1310033' AND DOCTYPE='DTI' )


INSERT INTO BI.SALESHISTORY(ORGID,FINYEAR,PERIOD,TRANGRP,TRANSID,INVOICENUMBER,SUPPCODE,ITEM,LEDGERCODE,INVOICEDATE,BATCHREF,CGST_AMOUNT,DOCTYPE,SUPPLIERGSTN,ORDERNO)
SELECT ORGID,YEAR,PERIOD,TRANGRP,TRANSID,TRANSREF,CREDNO,DESCRIPTION,LEDGERCODE,PDATE,BATCHREF,(DEBIT-CREDIT),'DTI',VATTYPE,ORDERNO   FROM TRANSACTIONS 
WHERE  LEDGERCODE ='1310028'  AND TRANGRP IN (SELECT TRANGRP FROM #DTICGST) 

INSERT INTO BI.SALESHISTORY(ORGID,FINYEAR,PERIOD,TRANGRP,TRANSID,INVOICENUMBER,SUPPCODE,ITEM,LEDGERCODE,INVOICEDATE,BATCHREF,SGST_AMOUNT,DOCTYPE,SUPPLIERGSTN,ORDERNO)
SELECT ORGID,YEAR,PERIOD,TRANGRP,TRANSID,TRANSREF,CREDNO,DESCRIPTION,LEDGERCODE,PDATE,BATCHREF,(DEBIT-CREDIT),'DTI',VATTYPE,ORDERNO  FROM TRANSACTIONS 
WHERE  LEDGERCODE ='1310029' AND TRANGRP IN (SELECT TRANGRP FROM #DTISGST) 

INSERT INTO BI.SALESHISTORY(ORGID,FINYEAR,PERIOD,TRANGRP,TRANSID,INVOICENUMBER,SUPPCODE,ITEM,LEDGERCODE,INVOICEDATE,BATCHREF,IGST_AMOUNT,DOCTYPE,SUPPLIERGSTN,ORDERNO)
SELECT ORGID,YEAR,PERIOD,TRANGRP,TRANSID,TRANSREF,CREDNO,DESCRIPTION,LEDGERCODE,PDATE,BATCHREF,(DEBIT-CREDIT),'DTI',VATTYPE,ORDERNO  FROM TRANSACTIONS 
WHERE  LEDGERCODE ='1310030' AND TRANGRP IN (SELECT TRANGRP FROM #DTIIGST) 

INSERT INTO BI.SALESHISTORY(ORGID,FINYEAR,PERIOD,TRANGRP,TRANSID,INVOICENUMBER,SUPPCODE,ITEM,LEDGERCODE,INVOICEDATE,BATCHREF,CGST_INPUT_RCM_AMOUNT,DOCTYPE,SUPPLIERGSTN,ORDERNO)
SELECT ORGID,YEAR,PERIOD,TRANGRP,TRANSID,TRANSREF,CREDNO,DESCRIPTION,LEDGERCODE,PDATE,BATCHREF,(DEBIT-CREDIT),'DTI',VATTYPE,ORDERNO  FROM TRANSACTIONS 
WHERE  LEDGERCODE ='1310031' AND  TRANGRP IN (SELECT TRANGRP FROM #DTIRCGST) 

INSERT INTO BI.SALESHISTORY(ORGID,FINYEAR,PERIOD,TRANGRP,TRANSID,INVOICENUMBER,SUPPCODE,ITEM,LEDGERCODE,INVOICEDATE,BATCHREF,SGST_INPUT_RCM_AMOUNT,DOCTYPE,SUPPLIERGSTN,ORDERNO)
SELECT ORGID,YEAR,PERIOD,TRANGRP,TRANSID,TRANSREF,CREDNO,DESCRIPTION,LEDGERCODE,PDATE,BATCHREF,(DEBIT-CREDIT),'DTI',VATTYPE,ORDERNO  FROM TRANSACTIONS 
WHERE  LEDGERCODE ='1310032' AND  TRANGRP IN (SELECT TRANGRP FROM #DTIRSGST) 

INSERT INTO BI.SALESHISTORY(ORGID,FINYEAR,PERIOD,TRANGRP,TRANSID,INVOICENUMBER,SUPPCODE,ITEM,LEDGERCODE,INVOICEDATE,BATCHREF,IGST_INPUT_RCM_AMOUNT,DOCTYPE,SUPPLIERGSTN,ORDERNO)
SELECT ORGID,YEAR,PERIOD,TRANGRP,TRANSID,TRANSREF,CREDNO,DESCRIPTION,LEDGERCODE,PDATE,BATCHREF,(DEBIT-CREDIT),'DTI',VATTYPE,ORDERNO  FROM TRANSACTIONS 
WHERE  LEDGERCODE ='1310033' AND  TRANGRP IN (SELECT TRANGRP FROM #DTIRIGST)


UPDATE BI.SALESHISTORY SET GSTTYPE='OUTPUT',TRANSTYPE='DTI',TRANSACTIONDATE=INVOICEDATE WHERE DOCTYPE='DTI' 

UPDATE BI.SALESHISTORY SET CGST_AMOUNT=0   WHERE CGST_AMOUNT IS NULL
UPDATE BI.SALESHISTORY SET SGST_AMOUNT=0   WHERE SGST_AMOUNT IS NULL
UPDATE BI.SALESHISTORY SET IGST_AMOUNT=0   WHERE IGST_AMOUNT IS NULL
UPDATE BI.SALESHISTORY SET TAXABLE_VALUE=0 WHERE TAXABLE_VALUE IS NULL
 
UPDATE BI.SALESHISTORY SET INVOICEDATE=EIV.INVOICEDATE,INVOICENUMBER=EIV.INVOICENUMBER FROM EI.EINVOICE EIV INNER JOIN BI.SALESHISTORY ON BI.SALESHISTORY.TRANGRP=EIV.TRANSGROUP


 





-- CRI Transactions
CREATE TABLE #CRITEMP(LINECOUNT INT PRIMARY KEY IDENTITY (1,1) , ORGID INT,  YEAR INT,PERIOD INT,PDATE DATE, INVOICEDATE DATE,
BATCHREF VARCHAR(25), TRANSREF VARCHAR(50), CREDNO VARCHAR(25), TRANGRP INT,TRANSID INT,LEDGERCODE VARCHAR(25),DESCRIPTION VARCHAR(400),
TAXABLEVALUE DECIMAL(18,2),DEBIT DECIMAL(18,2),CREDIT DECIMAL(18,2),
CGSTRATE DECIMAL(18,2),CGST DECIMAL(18,2),
SGSTRATE DECIMAL(18,2),SGST DECIMAL(18,2),
IGSTRATE DECIMAL(18,2),IGST DECIMAL(18,2),
RCMCGSTRATE DECIMAL(18,2), RCMCGST DECIMAL(18,2),
RCMSGSTRATE DECIMAL(18,2), RCMSGST DECIMAL(18,2),
RCMIGSTRATE DECIMAL(18,2), RCMIGST DECIMAL(18,2)
)

SET @LINECOUNT = 0 
DECLARE CRITRANGRP CURSOR 
FOR 
SELECT 
  DISTINCT TRANGRP FROM TRANSACTIONS 
  WHERE
  YEAR>=2021 AND 
  LEFT(BATCHREF,3)='CRI' AND 
  LEDGERCODE IN (SELECT LEDGERCODE FROM #GSTOUTPUT) AND
  TRANGRP NOT IN (SELECT TRANGRP FROM BI.SALESHISTORY WHERE DOCTYPE='CRI') 

 
OPEN CRITRANGRP 
FETCH NEXT FROM CRITRANGRP INTO @TRANGRP 

WHILE @@FETCH_STATUS=0
BEGIN
  SELECT @TRANSFROM = MIN(TRANSID), @TRANSEND = MAX(TRANSID) FROM TRANSACTIONS WHERE TRANGRP=@TRANGRP 
  
  DELETE FROM #TAXAMOUNT 
  INSERT INTO #TAXAMOUNT 
  SELECT LEDGERCODE,SUM(DEBIT-CREDIT) TAXAMOUNT 
  FROM TRANSACTIONS 
  WHERE TRANGRP = @TRANGRP  AND LEDGERCODE IN (SELECT LEDGERCODE FROM #GSTOUTPUT) GROUP BY LEDGERCODE 

  DELETE FROM #GSTTRANS 
  INSERT INTO #GSTTRANS
  SELECT DISTINCT  LEDGERCODE,PERC    FROM TAXTRANS  WHERE TRANSID BETWEEN @TRANSFROM AND @TRANSEND  
   
  INSERT INTO #CRITEMP(TRANGRP,  CGST ) 
  SELECT @TRANGRP,   TAXAMOUNT FROM #TAXAMOUNT  WHERE LEDGERCODE='1310028'  
  
  SET @SGSTAMOUNT = 0
  SET @RCMSGSTAMOUNT = 0 

  SELECT @SGSTAMOUNT = TAXAMOUNT FROM #TAXAMOUNT WHERE LEDGERCODE='1310029'  
  UPDATE #CRITEMP SET SGST = @SGSTAMOUNT  WHERE TRANGRP = @TRANGRP 

  SELECT @CGSTCOUNT = COUNT(*) FROM #GSTTRANS WHERE LEDGERCODE='1310028' 
  IF @CGSTCOUNT = 1
     BEGIN 
	   SELECT @CGSTPERC = PERC FROM #GSTTRANS WHERE LEDGERCODE='1310028' 
	   UPDATE #CRITEMP SET CGSTRATE = @CGSTPERC,SGSTRATE = @CGSTPERC  WHERE   TRANGRP = @TRANGRP 
	 END

  INSERT INTO #CRITEMP(TRANGRP, IGST ) 
  SELECT @TRANGRP,   TAXAMOUNT FROM #TAXAMOUNT  WHERE LEDGERCODE='1310030' 
  SELECT @IGSTCOUNT = COUNT(*) FROM #GSTTRANS WHERE LEDGERCODE='1310030' 
  IF @IGSTCOUNT = 1
     BEGIN 
	   SELECT @IGSTPERC = PERC FROM #GSTTRANS WHERE LEDGERCODE='1310030' 
	   UPDATE #CRITEMP SET IGSTRATE = @IGSTPERC WHERE    TRANGRP = @TRANGRP 
	 END


  
  UPDATE  #CRITEMP 
  SET ORGID=T.ORGID,YEAR=T.YEAR,PERIOD=T.PERIOD,PDATE=T.PDATE,INVOICEDATE=T.RECEIVEDDATE,BATCHREF=T.BATCHREF,TRANSREF =T.TRANSREFEXT,TRANSID=T.TRANSID,
      CREDNO=T.CREDNO, TAXABLEVALUE = T.CREDIT  FROM TRANSACTIONS T  INNER JOIN #CRITEMP ON #CRITEMP.TRANGRP = T.TRANGRP  WHERE  T.LEDGERCODE ='1315000' 

  
  UPDATE #CRITEMP 
   SET LEDGERCODE = T.LEDGERCODE,DESCRIPTION=T.DESCRIPTION FROM TRANSACTIONS T WHERE #CRITEMP.TRANGRP = @TRANGRP AND T.TRANSID = @TRANSFROM
  
  UPDATE #CRITEMP SET  CREDIT=0 WHERE CREDIT IS NULL AND TRANGRP = @TRANGRP 
  UPDATE #CRITEMP SET  CGST=0 WHERE  CGST IS NULL AND TRANGRP = @TRANGRP 
  UPDATE #CRITEMP SET  SGST=0 WHERE  SGST IS NULL  AND TRANGRP = @TRANGRP 
  UPDATE #CRITEMP SET  IGST=0 WHERE  IGST IS NULL  AND TRANGRP = @TRANGRP 
  UPDATE #CRITEMP SET  RCMCGST=0 WHERE  RCMCGST IS NULL  AND TRANGRP = @TRANGRP 
  UPDATE #CRITEMP SET  RCMSGST=0 WHERE  RCMSGST IS NULL  AND TRANGRP = @TRANGRP 
  UPDATE #CRITEMP SET  RCMIGST=0 WHERE  RCMIGST IS NULL  AND TRANGRP = @TRANGRP 
  UPDATE #CRITEMP SET  CREDIT=0 WHERE CREDIT IS NULL 
	UPDATE #CRITEMP SET  CGST=0 WHERE  CGST IS NULL
	UPDATE #CRITEMP SET  SGST=0 WHERE  SGST IS NULL
	UPDATE #CRITEMP SET  IGST=0 WHERE  IGST IS NULL
	UPDATE #CRITEMP SET  RCMCGST=0 WHERE  RCMCGST IS NULL
	UPDATE #CRITEMP SET  RCMSGST=0 WHERE  RCMSGST IS NULL
	UPDATE #CRITEMP SET  RCMIGST=0 WHERE  RCMIGST IS NULL
	UPDATE #CRITEMP SET  RCMCGSTRATE=0 WHERE RCMCGSTRATE IS NULL
	UPDATE #CRITEMP SET  RCMIGSTRATE=0 WHERE RCMIGSTRATE IS NULL
    UPDATE #CRITEMP SET CGSTRATE=RCMCGSTRATE , SGSTRATE=RCMSGSTRATE WHERE RCMCGSTRATE>0 
    UPDATE #CRITEMP SET IGSTRATE = RCMIGSTRATE WHERE RCMIGSTRATE>0 
	INSERT INTO BI.SALESHISTORY
	(ORGID,FINYEAR,PERIOD,TRANGRP,TRANSID,TRANSTYPE,INVOICENUMBER,TRANSACTIONDATE,SUPPCODE,ITEM,LEDGERCODE,BATCHREF,INVOICEDATE,
	TAXABLE_VALUE,CGST_RATE,CGST_AMOUNT,SGST_RATE,SGST_AMOUNT,IGST_RATE,IGST_AMOUNT,CGST_INPUT_RCM_AMOUNT,SGST_INPUT_RCM_AMOUNT,IGST_INPUT_RCM_AMOUNT,DOCTYPE)
	SELECT 
	ORGID,YEAR,PERIOD,TRANGRP,TRANSID,'CRI',TRANSREF,PDATE,CREDNO,UPPER(DESCRIPTION),LEDGERCODE,BATCHREF,INVOICEDATE,
	TAXABLEVALUE,CGSTRATE,CGST,SGSTRATE,SGST,IGSTRATE,IGST,RCMCGST,RCMSGST,RCMIGST,'CRI'
	FROM #CRITEMP

	DROP TABLE #CRITEMP
  FETCH NEXT FROM CRITRANGRP INTO @TRANGRP 
END


CLOSE CRITRANGRP
DEALLOCATE CRITRANGRP






 
  




---- SUBCONTRACTOR BILL BOOKINGS 
---- SCI

SELECT TRANGRP INTO #SCICGST FROM TRANSACTIONS WHERE YEAR>=2021  AND LEFT(BATCHREF,3)='SCI' AND LEDGERCODE ='1310028'
       AND TRANGRP NOT IN (SELECT TRANGRP FROM BI.SALESHISTORY WHERE LEDGERCODE='1310028' AND DOCTYPE='SCI' )
SELECT TRANGRP INTO #SCISGST FROM TRANSACTIONS WHERE YEAR>=2021  AND LEFT(BATCHREF,3)='SCI' AND LEDGERCODE ='1310029' 
       AND TRANGRP NOT IN (SELECT TRANGRP FROM BI.SALESHISTORY WHERE LEDGERCODE='1310029' AND DOCTYPE='SCI' )
SELECT TRANGRP INTO #SCIIGST FROM TRANSACTIONS WHERE YEAR>=2021  AND LEFT(BATCHREF,3)='SCI' AND LEDGERCODE ='1310030'
       AND TRANGRP NOT IN (SELECT TRANGRP FROM BI.SALESHISTORY WHERE LEDGERCODE='1310030' AND DOCTYPE='SCI' )

 

INSERT INTO BI.SALESHISTORY(ORGID,FINYEAR,PERIOD,TRANGRP,TRANSID,INVOICENUMBER,SUPPCODE,ITEM,LEDGERCODE,INVOICEDATE,BATCHREF,CGST_AMOUNT,DOCTYPE,SUPPLIERGSTN,ORDERNO)
SELECT ORGID,YEAR,PERIOD,TRANGRP,TRANSID,TRANSREF,CREDNO,DESCRIPTION,LEDGERCODE,PDATE,BATCHREF,(DEBIT-CREDIT),'SCI',VATTYPE,ORDERNO   FROM TRANSACTIONS 
WHERE  LEDGERCODE ='1310028'  AND TRANGRP IN (SELECT TRANGRP FROM #SCICGST) 

INSERT INTO BI.SALESHISTORY(ORGID,FINYEAR,PERIOD,TRANGRP,TRANSID,INVOICENUMBER,SUPPCODE,ITEM,LEDGERCODE,INVOICEDATE,BATCHREF,SGST_AMOUNT,DOCTYPE,SUPPLIERGSTN,ORDERNO)
SELECT ORGID,YEAR,PERIOD,TRANGRP,TRANSID,TRANSREF,CREDNO,DESCRIPTION,LEDGERCODE,PDATE,BATCHREF,(DEBIT-CREDIT),'SCI',VATTYPE,ORDERNO  FROM TRANSACTIONS 
WHERE  LEDGERCODE ='1310029' AND TRANGRP IN (SELECT TRANGRP FROM #SCISGST) 

INSERT INTO BI.SALESHISTORY(ORGID,FINYEAR,PERIOD,TRANGRP,TRANSID,INVOICENUMBER,SUPPCODE,ITEM,LEDGERCODE,INVOICEDATE,BATCHREF,IGST_AMOUNT,DOCTYPE,SUPPLIERGSTN,ORDERNO)
SELECT ORGID,YEAR,PERIOD,TRANGRP,TRANSID,TRANSREF,CREDNO,DESCRIPTION,LEDGERCODE,PDATE,BATCHREF,(DEBIT-CREDIT),'SCI',VATTYPE,ORDERNO  FROM TRANSACTIONS 
WHERE  LEDGERCODE ='1310030' AND TRANGRP IN (SELECT TRANGRP FROM #SCIIGST) 

SELECT S.RECONID,S.SUBCONNUMBER,S.ORDERNO,C.CONTRARECONID,C.REMARKS
INTO #CONTRAINVOICE
FROM SUBCRECONS S INNER JOIN CONTRAS C ON S.RECONID=C.CONTRARECONID WHERE C.REMARKS IS NOT NULL
  

UPDATE BI.SALESHISTORY SET INVOICENUMBER = CI.REMARKS FROM #CONTRAINVOICE CI INNER JOIN BI.SALESHISTORY  BIS ON  CI.ORDERNO=BIS.ORDERNO 
WHERE BIS.TRANGRP IN (SELECT TRANGRP FROM #SCISGST)
UPDATE BI.SALESHISTORY SET INVOICENUMBER = CI.REMARKS FROM #CONTRAINVOICE CI INNER JOIN BI.SALESHISTORY  BIS ON  CI.ORDERNO=BIS.ORDERNO 
WHERE BIS.TRANGRP IN (SELECT TRANGRP FROM #SCICGST)
UPDATE BI.SALESHISTORY SET INVOICENUMBER = CI.REMARKS FROM #CONTRAINVOICE CI INNER JOIN BI.SALESHISTORY  BIS ON  CI.ORDERNO=BIS.ORDERNO 
WHERE BIS.TRANGRP IN (SELECT TRANGRP FROM #SCIIGST)


UPDATE BI.SALESHISTORY SET GSTTYPE='OUTPUT',TRANSTYPE='SCI',TRANSACTIONDATE=INVOICEDATE WHERE DOCTYPE='SCI' 

UPDATE BI.SALESHISTORY SET CGST_AMOUNT=0   WHERE CGST_AMOUNT IS NULL
UPDATE BI.SALESHISTORY SET SGST_AMOUNT=0   WHERE SGST_AMOUNT IS NULL
UPDATE BI.SALESHISTORY SET IGST_AMOUNT=0   WHERE IGST_AMOUNT IS NULL
UPDATE BI.SALESHISTORY SET TAXABLE_VALUE=0 WHERE TAXABLE_VALUE IS NULL








 
 
 


-------- CBC / PCP TRANSACTIONS-----------------------------------------------------------------------------------------

-------- CBC, CBD, PCP, PCR 


DECLARE @BANKSTART VARCHAR(10)
DECLARE @BANKEND   VARCHAR(10)
SELECT  @BANKSTART = CONTROLFROMGL, @BANKEND = CONTROLTOGL FROM CONTROLCODES WHERE CONTROLNAME='Bank' 

CREATE TABLE #BANKLEDGERS(LEDGERCODE VARCHAR(10))
INSERT INTO #BANKLEDGERS 
SELECT LEDGERCODE FROM LEDGERCODES WHERE LEDGERCODE BETWEEN @BANKSTART AND @BANKEND AND LedgerSummary=0
INSERT INTO #BANKLEDGERS VALUES ('2551000')


 
CREATE TABLE #GSTTRANSCBC (LEDGERCODE VARCHAR(15),PERC DECIMAL(18,2) , BILLAMOUNT DECIMAL(18,2) ) 

DECLARE @BILLVALUE  DECIMAL(18,2) 
DECLARE @DOCTYPE VARCHAR(3) 
DECLARE @FOREIGNID INT 
DECLARE @TOTALTAX DECIMAL(18,2)
DECLARE @DERIVEDPERC DECIMAL(18,2) 
DECLARE @ENTRYEXISTS INT 
DECLARE @BILLAMOUNT DECIMAL(18,2) 
DECLARE @CBCTAXPERCENT DECIMAL(18,2) 

CREATE TABLE #CBCTEMP(LINECOUNT INT PRIMARY KEY IDENTITY (1,1) , ORGID INT,  YEAR INT,PERIOD INT,PDATE DATE, INVOICEDATE DATE,
BATCHREF VARCHAR(25), TRANSREF VARCHAR(50), CREDNO VARCHAR(25), TRANGRP INT,TRANSID INT,LEDGERCODE VARCHAR(25),DESCRIPTION VARCHAR(400),
TAXABLEVALUE DECIMAL(18,2),DEBIT DECIMAL(18,2),CREDIT DECIMAL(18,2),
CGSTRATE DECIMAL(18,2),CGST DECIMAL(18,2),
SGSTRATE DECIMAL(18,2),SGST DECIMAL(18,2),
IGSTRATE DECIMAL(18,2),IGST DECIMAL(18,2),
RCMCGSTRATE DECIMAL(18,2), RCMCGST DECIMAL(18,2),
RCMSGSTRATE DECIMAL(18,2), RCMSGST DECIMAL(18,2),
RCMIGSTRATE DECIMAL(18,2), RCMIGST DECIMAL(18,2),
DOCTYPE VARCHAR(3)
)



 



SET @LINECOUNT = 0 
DECLARE CBCTRANGRP CURSOR 
FOR 
SELECT 
  DISTINCT TRANGRP FROM TRANSACTIONS 
  WHERE 
  YEAR>=2021 AND 
  LEFT(BATCHREF,3) IN ('CBC','CBD','PCP','PCR') AND
  LEDGERCODE IN (SELECT LEDGERCODE FROM #GSTOUTPUT)   AND
  TRANGRP NOT IN (SELECT TRANGRP FROM BI.SALESHISTORY WHERE DOCTYPE IN ( 'CBC','CBD','PCP','PCR' ) )  
   

 
OPEN CBCTRANGRP 
FETCH NEXT FROM CBCTRANGRP INTO @TRANGRP 

WHILE @@FETCH_STATUS=0
BEGIN
  
  SELECT @TRANSFROM = MIN(TRANSID), @TRANSEND = MAX(TRANSID) FROM TRANSACTIONS WHERE TRANGRP=@TRANGRP 
  SELECT @DOCTYPE = LEFT(BATCHREF,3) FROM TRANSACTIONS WHERE TRANGRP =@TRANGRP AND TRANSID=@TRANSFROM 
  SET @ENTRYEXISTS = 0 
  SELECT @ENTRYEXISTS = COUNT(*) FROM TAXTRANS WHERE TRANSID BETWEEN @TRANSFROM AND @TRANSEND 

  IF @ENTRYEXISTS > 0
    BEGIN
	 SELECT LEDGERCODE,SUM(CUMCOST) TOTALCOST 
	 INTO #TEMP0 
	 FROM TAXTRANS 
	 WHERE TRANSID BETWEEN @TRANSFROM AND @TRANSEND
	 GROUP BY LEDGERCODE 
     DELETE FROM #GSTTRANSCBC
     INSERT INTO #GSTTRANSCBC 
	 SELECT  LEDGERCODE,PERC,0  FROM TAXTRANS WHERE TRANSID BETWEEN @TRANSFROM AND @TRANSEND
	 UPDATE #GSTTRANSCBC SET BILLAMOUNT=T.TOTALCOST FROM #TEMP0 T INNER JOIN #GSTTRANSCBC ON T.LEDGERCODE=#GSTTRANSCBC.LEDGERCODE 
	 DROP TABLE #TEMP0 
    END
  ELSE
    SET @BILLAMOUNT = 0 
  
  DELETE FROM #TAXAMOUNT 
  INSERT INTO #TAXAMOUNT 
  SELECT LEDGERCODE,SUM(DEBIT-CREDIT) TAXAMOUNT  
  FROM TRANSACTIONS 
  WHERE TRANGRP = @TRANGRP  AND LEDGERCODE IN (SELECT LEDGERCODE FROM #GSTOUTPUT) GROUP BY LEDGERCODE 

  
  SET @BILLAMOUNT = 0
  SELECT @BILLAMOUNT = BILLAMOUNT,@CBCTAXPERCENT =PERC  FROM #GSTTRANSCBC WHERE LEDGERCODE='1310028' AND @ENTRYEXISTS <> 0
  IF @BILLAMOUNT = 0 
     SET @BILLAMOUNT = @BILLVALUE 
  INSERT INTO #CBCTEMP(TRANGRP,  CGST ,TAXABLEVALUE ,CGSTRATE  ) 
  SELECT @TRANGRP,   TAXAMOUNT ,@BILLAMOUNT,@CBCTAXPERCENT   FROM #TAXAMOUNT   WHERE LEDGERCODE='1310028'  
  

  SELECT @LINEALREADYENTERED = COUNT(*) FROM #CBCTEMP 
  IF @LINEALREADYENTERED = 0 
   BEGIN
      INSERT INTO #CBCTEMP(TRANGRP,  SGST ,TAXABLEVALUE ,CGSTRATE  ) 
      SELECT @TRANGRP,   TAXAMOUNT ,@BILLAMOUNT,@CBCTAXPERCENT   FROM #TAXAMOUNT   WHERE LEDGERCODE='1310029'  
   END
  
  SET @LINEALREADYENTERED = 0 
  SET @SGSTAMOUNT = 0
  SET @RCMSGSTAMOUNT = 0 


  SELECT @SGSTAMOUNT = TAXAMOUNT FROM #TAXAMOUNT  WHERE LEDGERCODE='1310029'  
  UPDATE #CBCTEMP SET SGST = @SGSTAMOUNT ,SGSTRATE = @CBCTAXPERCENT     WHERE TRANGRP = @TRANGRP 

  SET @BILLAMOUNT = 0
  SELECT @BILLAMOUNT = BILLAMOUNT,@CBCTAXPERCENT =PERC FROM #GSTTRANSCBC WHERE LEDGERCODE='1310030' AND @ENTRYEXISTS <> 0
  IF @BILLAMOUNT = 0 
     SET @BILLAMOUNT = @BILLVALUE 
  INSERT INTO #CBCTEMP(TRANGRP, IGST ,TAXABLEVALUE,IGSTRATE   ) 
  SELECT @TRANGRP,   TAXAMOUNT ,@BILLAMOUNT ,@CBCTAXPERCENT   FROM #TAXAMOUNT   WHERE LEDGERCODE='1310030' 
  

  SET @BILLAMOUNT = 0
  SELECT @BILLAMOUNT = BILLAMOUNT,@CBCTAXPERCENT =PERC  FROM #GSTTRANSCBC WHERE LEDGERCODE='1310031' AND @ENTRYEXISTS <> 0
  IF @BILLAMOUNT = 0 
     SET @BILLAMOUNT = @BILLVALUE 
  INSERT INTO #CBCTEMP(TRANGRP,  RCMCGST  ,TAXABLEVALUE ,RCMCGSTRATE  ) 
  SELECT @TRANGRP,   TAXAMOUNT ,@BILLAMOUNT , @CBCTAXPERCENT   FROM #TAXAMOUNT  WHERE LEDGERCODE='1310031'
  SELECT @RCMSGSTAMOUNT = TAXAMOUNT FROM #TAXAMOUNT  WHERE LEDGERCODE='1310032'  
  UPDATE #CBCTEMP SET RCMSGST = @RCMSGSTAMOUNT  ,RCMSGSTRATE = @CBCTAXPERCENT   WHERE TRANGRP = @TRANGRP AND @RCMSGSTAMOUNT>0 

  SET @BILLAMOUNT = 0
  SELECT @BILLAMOUNT = BILLAMOUNT,@CBCTAXPERCENT  = PERC FROM #GSTTRANSCBC WHERE LEDGERCODE='1310033' 
  IF @BILLAMOUNT = 0 
     SET @BILLAMOUNT = @BILLVALUE 
  INSERT INTO #CBCTEMP(TRANGRP ,  RCMIGST, TAXABLEVALUE,RCMIGSTRATE  ) 
  SELECT @TRANGRP,   TAXAMOUNT ,@BILLAMOUNT ,@CBCTAXPERCENT  FROM #TAXAMOUNT   WHERE LEDGERCODE='1310033'

  
  UPDATE #CBCTEMP 
   SET ORGID=T.ORGID,YEAR=T.YEAR,PERIOD=T.PERIOD,PDATE=T.PDATE,INVOICEDATE=T.PDATE,BATCHREF=T.BATCHREF,TRANSREF =T.TRANSREF,TRANSID=T.TRANSID,
       CREDNO=T.CREDNO, DOCTYPE=LEFT(T.BATCHREF,3), LEDGERCODE = T.LEDGERCODE,DESCRIPTION=T.DESCRIPTION FROM TRANSACTIONS T 
	   INNER JOIN #CBCTEMP ON #CBCTEMP.TRANGRP=T.TRANGRP 
	   WHERE  T.TRANSID = @TRANSFROM AND T.TRANGRP=@TRANGRP 

  IF @ENTRYEXISTS = 0
  BEGIN 
     SET @FOREIGNID = 0
     SELECT   @FOREIGNID= MAX(TRANSID) FROM TRANSACTIONS WHERE TRANGRP = @TRANGRP AND LEDGERCODE IN (SELECT LEDGERCODE FROM #BANKLEDGERS) 
 
     IF @FOREIGNID<>0  
        BEGIN 
 	      SELECT @BILLAMOUNT = (CREDIT-DEBIT) FROM TRANSACTIONS WHERE TRANSID=@FOREIGNID 
	      UPDATE #CBCTEMP SET  TAXABLEVALUE = @BILLAMOUNT WHERE TRANGRP = @TRANGRP 
		  UPDATE #CBCTEMP SET  CREDIT=0 WHERE CREDIT IS NULL AND TRANGRP = @TRANGRP 
		  UPDATE #CBCTEMP SET  CGST=0 WHERE  CGST IS NULL AND TRANGRP = @TRANGRP 
	  	  UPDATE #CBCTEMP SET  SGST=0 WHERE  SGST IS NULL  AND TRANGRP = @TRANGRP 
		  UPDATE #CBCTEMP SET  IGST=0 WHERE  IGST IS NULL  AND TRANGRP = @TRANGRP 
	 	  UPDATE #CBCTEMP SET  RCMCGST=0 WHERE  RCMCGST IS NULL  AND TRANGRP = @TRANGRP 
		  UPDATE #CBCTEMP SET  RCMSGST=0 WHERE  RCMSGST IS NULL  AND TRANGRP = @TRANGRP 
		  UPDATE #CBCTEMP SET  RCMIGST=0 WHERE  RCMIGST IS NULL  AND TRANGRP = @TRANGRP 
          SELECT @TOTALTAX = CGST+SGST+IGST,@TAXABLEAMOUNT = TAXABLEVALUE  FROM #CBCTEMP WHERE TRANGRP = @TRANGRP
          SET @DERIVEDPERC = 0 
		  IF (@TAXABLEAMOUNT-@TOTALTAX)  >0  
		    BEGIN
		      SET @DERIVEDPERC =ROUND ( (  @TOTALTAX / (@TAXABLEAMOUNT-@TOTALTAX) ) * 100 ,0 ) 
	          UPDATE #CBCTEMP SET CGSTRATE = @DERIVEDPERC/2.0 WHERE TRANGRP = @TRANGRP AND CGST>0  AND CGSTRATE=0
			  UPDATE #CBCTEMP SET SGSTRATE = @DERIVEDPERC/2.0 WHERE TRANGRP = @TRANGRP AND SGST>0  AND SGSTRATE=0
			  UPDATE #CBCTEMP SET IGSTRATE = @DERIVEDPERC WHERE TRANGRP = @TRANGRP AND IGST>0  AND IGSTRATE=0
			  UPDATE #CBCTEMP SET TAXABLEVALUE = (@TAXABLEAMOUNT-@TOTALTAX) WHERE TRANGRP = @TRANGRP
           END 
		END
   END
    UPDATE #CBCTEMP SET  CREDIT=0 WHERE CREDIT IS NULL 
	UPDATE #CBCTEMP SET DEBIT = 0 WHERE DEBIT IS NULL
	UPDATE #CBCTEMP SET  CGST=0 WHERE  CGST IS NULL
	UPDATE #CBCTEMP SET  SGST=0 WHERE  SGST IS NULL
	UPDATE #CBCTEMP SET  IGST=0 WHERE  IGST IS NULL
	UPDATE #CBCTEMP SET  RCMCGST=0 WHERE  RCMCGST IS NULL
	UPDATE #CBCTEMP SET  RCMSGST=0 WHERE  RCMSGST IS NULL
	UPDATE #CBCTEMP SET  RCMIGST=0 WHERE  RCMIGST IS NULL
	UPDATE #CBCTEMP SET  RCMCGSTRATE=0 WHERE RCMCGSTRATE IS NULL
	UPDATE #CBCTEMP SET  RCMIGSTRATE=0 WHERE RCMIGSTRATE IS NULL
	UPDATE #CBCTEMP SET CGSTRATE = 0 WHERE CGSTRATE IS NULL
	UPDATE #CBCTEMP SET SGSTRATE = 0 WHERE SGSTRATE IS NULL
	UPDATE #CBCTEMP SET IGSTRATE = 0 WHERE IGSTRATE IS NULL

	UPDATE #CBCTEMP SET CGSTRATE=RCMCGSTRATE , SGSTRATE=RCMSGSTRATE WHERE RCMCGSTRATE>0 
	UPDATE #CBCTEMP SET IGSTRATE = RCMIGSTRATE WHERE RCMIGSTRATE>0 
	INSERT INTO BI.SALESHISTORY
	(ORGID,FINYEAR,PERIOD,TRANGRP,TRANSID,TRANSTYPE,INVOICENUMBER,TRANSACTIONDATE,SUPPCODE,ITEM,LEDGERCODE,BATCHREF,INVOICEDATE,
	TAXABLE_VALUE,CGST_RATE,CGST_AMOUNT,SGST_RATE,SGST_AMOUNT,IGST_RATE,IGST_AMOUNT,CGST_INPUT_RCM_AMOUNT,SGST_INPUT_RCM_AMOUNT,IGST_INPUT_RCM_AMOUNT,DOCTYPE)
	SELECT 
	ORGID,YEAR,PERIOD,TRANGRP,TRANSID,DOCTYPE,TRANSREF,PDATE,CREDNO,UPPER(DESCRIPTION),LEDGERCODE,BATCHREF,INVOICEDATE,
	TAXABLEVALUE,CGSTRATE,CGST,SGSTRATE,SGST,IGSTRATE,IGST,RCMCGST,RCMSGST,RCMIGST,DOCTYPE
	FROM #CBCTEMP

	UPDATE BI.SALESHISTORY SET GSTTYPE='OUTPUT' WHERE GSTTYPE IS NULL

	DELETE FROM #CBCTEMP
   FETCH NEXT FROM CBCTRANGRP INTO @TRANGRP 
END


CLOSE CBCTRANGRP
DEALLOCATE CBCTRANGRP



 



 





------ JOURNALS

SELECT TRANGRP INTO #JNLCGST FROM TRANSACTIONS WHERE YEAR>=2021  AND LEFT(BATCHREF,3)='JNL' AND LEDGERCODE='1310028'
       AND TRANGRP NOT IN (SELECT TRANGRP FROM BI.SALESHISTORY WHERE LEDGERCODE='1310028' AND DOCTYPE='JNL' )
SELECT TRANGRP INTO #JNLSGST FROM TRANSACTIONS WHERE YEAR>=2021  AND LEFT(BATCHREF,3)='JNL' AND LEDGERCODE='1310029'
       AND TRANGRP NOT IN (SELECT TRANGRP FROM BI.SALESHISTORY WHERE LEDGERCODE='1310029' AND DOCTYPE='JNL' )
SELECT TRANGRP INTO #JNLIGST FROM TRANSACTIONS WHERE YEAR>=2021  AND LEFT(BATCHREF,3)='JNL' AND LEDGERCODE='1310030' 
       AND TRANGRP NOT IN (SELECT TRANGRP FROM BI.SALESHISTORY WHERE LEDGERCODE='1310030' AND DOCTYPE='JNL' )

SELECT TRANGRP INTO #JNLRCGST FROM TRANSACTIONS WHERE YEAR>=2021  AND LEFT(BATCHREF,3)='JNL' AND LEDGERCODE='1310031'
      AND TRANGRP NOT IN (SELECT TRANGRP FROM BI.SALESHISTORY WHERE LEDGERCODE='1310031' AND DOCTYPE='JNL' )
SELECT TRANGRP INTO #JNLRSGST FROM TRANSACTIONS WHERE YEAR>=2021  AND LEFT(BATCHREF,3)='JNL' AND LEDGERCODE='1310032'
      AND TRANGRP NOT IN (SELECT TRANGRP FROM BI.SALESHISTORY WHERE LEDGERCODE='1310032' AND DOCTYPE='JNL' )
SELECT TRANGRP INTO #JNLRIGST FROM TRANSACTIONS WHERE YEAR>=2021  AND LEFT(BATCHREF,3)='JNL' AND LEDGERCODE='1310033' 
      AND TRANGRP NOT IN (SELECT TRANGRP FROM BI.SALESHISTORY WHERE LEDGERCODE='1310033' AND DOCTYPE='JNL' )


INSERT INTO BI.SALESHISTORY(ORGID,FINYEAR,PERIOD,TRANGRP,TRANSID,INVOICENUMBER,SUPPCODE,ITEM,LEDGERCODE,INVOICEDATE,BATCHREF,CGST_AMOUNT,DOCTYPE)
SELECT ORGID,YEAR,PERIOD,TRANGRP,TRANSID,TRANSREF,CREDNO,DESCRIPTION,LEDGERCODE,PDATE,BATCHREF,(DEBIT-CREDIT),'JNL'  FROM TRANSACTIONS 
WHERE LEDGERCODE='1310028'  AND TRANGRP IN (SELECT TRANGRP FROM #JNLCGST) 

INSERT INTO BI.SALESHISTORY(ORGID,FINYEAR,PERIOD,TRANGRP,TRANSID,INVOICENUMBER,SUPPCODE,ITEM,LEDGERCODE,INVOICEDATE,BATCHREF,SGST_AMOUNT,DOCTYPE)
SELECT ORGID,YEAR,PERIOD,TRANGRP,TRANSID,TRANSREF,CREDNO,DESCRIPTION,LEDGERCODE,PDATE,BATCHREF,(DEBIT-CREDIT),'JNL'  FROM TRANSACTIONS 
WHERE LEDGERCODE='1310029' AND TRANGRP IN (SELECT TRANGRP FROM #JNLSGST) 

INSERT INTO BI.SALESHISTORY(ORGID,FINYEAR,PERIOD,TRANGRP,TRANSID,INVOICENUMBER,SUPPCODE,ITEM,LEDGERCODE,INVOICEDATE,BATCHREF,IGST_AMOUNT,DOCTYPE)
SELECT ORGID,YEAR,PERIOD,TRANGRP,TRANSID,TRANSREF,CREDNO,DESCRIPTION,LEDGERCODE,PDATE,BATCHREF,(DEBIT-CREDIT),'JNL'  FROM TRANSACTIONS 
WHERE LEDGERCODE='1310030' AND TRANGRP IN (SELECT TRANGRP FROM #JNLIGST) 

INSERT INTO BI.SALESHISTORY(ORGID,FINYEAR,PERIOD,TRANGRP,TRANSID,INVOICENUMBER,SUPPCODE,ITEM,LEDGERCODE,INVOICEDATE,BATCHREF,CGST_INPUT_RCM_AMOUNT,DOCTYPE)
SELECT ORGID,YEAR,PERIOD,TRANGRP,TRANSID,TRANSREF,CREDNO,DESCRIPTION,LEDGERCODE,PDATE,BATCHREF,(DEBIT-CREDIT),'JNL'  FROM TRANSACTIONS 
WHERE LEDGERCODE='1310031' AND TRANGRP IN (SELECT TRANGRP FROM #JNLRCGST) 

INSERT INTO BI.SALESHISTORY(ORGID,FINYEAR,PERIOD,TRANGRP,TRANSID,INVOICENUMBER,SUPPCODE,ITEM,LEDGERCODE,INVOICEDATE,BATCHREF,SGST_INPUT_RCM_AMOUNT,DOCTYPE)
SELECT ORGID,YEAR,PERIOD,TRANGRP,TRANSID,TRANSREF,CREDNO,DESCRIPTION,LEDGERCODE,PDATE,BATCHREF,(DEBIT-CREDIT),'JNL'  FROM TRANSACTIONS 
WHERE LEDGERCODE='1310032' AND TRANGRP IN (SELECT TRANGRP FROM #JNLRSGST) 

INSERT INTO BI.SALESHISTORY(ORGID,FINYEAR,PERIOD,TRANGRP,TRANSID,INVOICENUMBER,SUPPCODE,ITEM,LEDGERCODE,INVOICEDATE,BATCHREF,IGST_INPUT_RCM_AMOUNT,DOCTYPE)
SELECT ORGID,YEAR,PERIOD,TRANGRP,TRANSID,TRANSREF,CREDNO,DESCRIPTION,LEDGERCODE,PDATE,BATCHREF,(DEBIT-CREDIT),'JNL'  FROM TRANSACTIONS 
WHERE LEDGERCODE='1310033' AND TRANGRP IN (SELECT TRANGRP FROM #JNLRIGST)

UPDATE BI.SALESHISTORY SET GSTTYPE='OUTPUT',TRANSTYPE='JNL',TRANSACTIONDATE=INVOICEDATE WHERE DOCTYPE='JNL' 
 


-------- CCN CREDIT NOTE TO SUPPLIERS 

-------- CCN Transactions


CREATE TABLE #CCNTEMP(LINECOUNT INT PRIMARY KEY IDENTITY (1,1) , ORGID INT,  YEAR INT,PERIOD INT,PDATE DATE, INVOICEDATE DATE,
BATCHREF VARCHAR(25), TRANSREF VARCHAR(50), CREDNO VARCHAR(25), TRANGRP INT,TRANSID INT,LEDGERCODE VARCHAR(25),DESCRIPTION VARCHAR(400),
TAXABLEVALUE DECIMAL(18,2),DEBIT DECIMAL(18,2),CREDIT DECIMAL(18,2),
CGSTRATE DECIMAL(18,2),CGST DECIMAL(18,2),
SGSTRATE DECIMAL(18,2),SGST DECIMAL(18,2),
IGSTRATE DECIMAL(18,2),IGST DECIMAL(18,2),
RCMCGSTRATE DECIMAL(18,2), RCMCGST DECIMAL(18,2),
RCMSGSTRATE DECIMAL(18,2), RCMSGST DECIMAL(18,2),
RCMIGSTRATE DECIMAL(18,2), RCMIGST DECIMAL(18,2)
)

SET @LINECOUNT = 0 
DECLARE CCNTRANGRP CURSOR 
FOR 
SELECT 
  DISTINCT TRANGRP FROM TRANSACTIONS 
  WHERE 
  YEAR>=2021 AND 
  LEFT(BATCHREF,3)='CCN' AND 
  LEDGERCODE IN (SELECT LEDGERCODE FROM #GSTOUTPUT) AND
  TRANGRP NOT IN (SELECT TRANGRP FROM BI.SALESHISTORY WHERE DOCTYPE='CCN') 

 
OPEN CCNTRANGRP 
FETCH NEXT FROM CCNTRANGRP INTO @TRANGRP 

WHILE @@FETCH_STATUS=0
BEGIN
  SELECT @TRANSFROM = MIN(TRANSID), @TRANSEND = MAX(TRANSID) FROM TRANSACTIONS WHERE TRANGRP=@TRANGRP 
  
  DELETE FROM #TAXAMOUNT 
  INSERT INTO #TAXAMOUNT 
  SELECT LEDGERCODE,SUM(DEBIT-CREDIT) TAXAMOUNT 
  FROM TRANSACTIONS 
  WHERE TRANGRP = @TRANGRP  AND LEDGERCODE IN (SELECT LEDGERCODE FROM #GSTOUTPUT) GROUP BY LEDGERCODE 

  DELETE FROM #GSTTRANS 
  INSERT INTO #GSTTRANS
  SELECT DISTINCT  LEDGERCODE,PERC    FROM TAXTRANS  WHERE TRANSID BETWEEN @TRANSFROM AND @TRANSEND  
   
  INSERT INTO #CCNTEMP(TRANGRP,  CGST ) 
  SELECT @TRANGRP,   TAXAMOUNT FROM #TAXAMOUNT  WHERE LEDGERCODE='1310028'  
  
  SET @SGSTAMOUNT = 0
  SET @RCMSGSTAMOUNT = 0 

  SELECT @SGSTAMOUNT = TAXAMOUNT FROM #TAXAMOUNT WHERE LEDGERCODE='1310029'  
  UPDATE #CCNTEMP SET SGST = @SGSTAMOUNT  WHERE TRANGRP = @TRANGRP 

  SELECT @CGSTCOUNT = COUNT(*) FROM #GSTTRANS WHERE LEDGERCODE='1310028' 
  IF @CGSTCOUNT = 1
     BEGIN 
	   SELECT @CGSTPERC = PERC FROM #GSTTRANS WHERE LEDGERCODE='1310028' 
	   UPDATE #CCNTEMP SET CGSTRATE = @CGSTPERC,SGSTRATE = @CGSTPERC  WHERE   TRANGRP = @TRANGRP 
	 END

  INSERT INTO #CCNTEMP(TRANGRP, IGST ) 
  SELECT @TRANGRP,   TAXAMOUNT FROM #TAXAMOUNT  WHERE LEDGERCODE='1310030' 
  SELECT @IGSTCOUNT = COUNT(*) FROM #GSTTRANS WHERE LEDGERCODE='1310030' 
  IF @IGSTCOUNT = 1
     BEGIN 
	   SELECT @IGSTPERC = PERC FROM #GSTTRANS WHERE LEDGERCODE='1310030' 
	   UPDATE #CCNTEMP SET IGSTRATE = @IGSTPERC WHERE    TRANGRP = @TRANGRP 
	 END


  INSERT INTO #CCNTEMP(TRANGRP,  RCMCGST ) 
  SELECT @TRANGRP,   TAXAMOUNT FROM #TAXAMOUNT  WHERE LEDGERCODE='1310031'
  SELECT @RCMCGSTCOUNT = COUNT(*) FROM #GSTTRANS WHERE LEDGERCODE='1310031' 
  IF @RCMCGSTCOUNT = 1
     BEGIN 
	   SELECT @RCMCGSTRATE = PERC FROM #GSTTRANS WHERE LEDGERCODE='1310031' 
	   UPDATE #CCNTEMP SET RCMCGSTRATE  = @RCMCGSTRATE, RCMSGSTRATE  = @RCMCGSTRATE  WHERE    TRANGRP = @TRANGRP 
	 END
  SELECT @RCMSGSTAMOUNT = TAXAMOUNT FROM #TAXAMOUNT WHERE LEDGERCODE='1310032'  
  UPDATE #CCNTEMP SET RCMSGST = @RCMSGSTAMOUNT  WHERE TRANGRP = @TRANGRP 

  INSERT INTO #CCNTEMP(TRANGRP ,  RCMIGST ) 
  SELECT @TRANGRP,   TAXAMOUNT FROM #TAXAMOUNT  WHERE LEDGERCODE='1310033'
  SELECT @RCMIGSTCOUNT = COUNT(*) FROM #GSTTRANS WHERE LEDGERCODE='1310033' 
  IF @RCMIGSTCOUNT = 1
     BEGIN 
	   SELECT @RCMIGSTRATE = PERC FROM #GSTTRANS WHERE LEDGERCODE='1310033' 
	   UPDATE #CCNTEMP SET IGSTRATE = @RCMIGSTRATE WHERE    TRANGRP = @TRANGRP 
	 END

  UPDATE  #CCNTEMP 
  SET ORGID=T.ORGID,YEAR=T.YEAR,PERIOD=T.PERIOD,PDATE=T.PDATE,INVOICEDATE=T.RECEIVEDDATE,BATCHREF=T.BATCHREF,TRANSREF =T.TRANSREFEXT,TRANSID=T.TRANSID,
      CREDNO=T.CREDNO, TAXABLEVALUE = (T.CREDIT-T.DEBIT)  FROM TRANSACTIONS T  INNER JOIN #CCNTEMP ON #CCNTEMP.TRANGRP = T.TRANGRP  WHERE  T.LEDGERCODE ='1315000' 

  
  UPDATE #CCNTEMP 
   SET LEDGERCODE = T.LEDGERCODE,DESCRIPTION=T.DESCRIPTION FROM TRANSACTIONS T WHERE #CCNTEMP.TRANGRP = @TRANGRP AND T.TRANSID = @TRANSFROM
  
  UPDATE #CCNTEMP SET  CREDIT=0 WHERE CREDIT IS NULL AND TRANGRP = @TRANGRP 
  UPDATE #CCNTEMP SET  CGST=0 WHERE  CGST IS NULL AND TRANGRP = @TRANGRP 
  UPDATE #CCNTEMP SET  SGST=0 WHERE  SGST IS NULL  AND TRANGRP = @TRANGRP 
  UPDATE #CCNTEMP SET  IGST=0 WHERE  IGST IS NULL  AND TRANGRP = @TRANGRP 
  UPDATE #CCNTEMP SET  RCMCGST=0 WHERE  RCMCGST IS NULL  AND TRANGRP = @TRANGRP 
  UPDATE #CCNTEMP SET  RCMSGST=0 WHERE  RCMSGST IS NULL  AND TRANGRP = @TRANGRP 
  UPDATE #CCNTEMP SET  RCMIGST=0 WHERE  RCMIGST IS NULL  AND TRANGRP = @TRANGRP 

  
	UPDATE #CCNTEMP SET  CREDIT=0 WHERE CREDIT IS NULL 
	UPDATE #CCNTEMP SET  CGST=0 WHERE  CGST IS NULL
	UPDATE #CCNTEMP SET  SGST=0 WHERE  SGST IS NULL
	UPDATE #CCNTEMP SET  IGST=0 WHERE  IGST IS NULL
	UPDATE #CCNTEMP SET  RCMCGST=0 WHERE  RCMCGST IS NULL
	UPDATE #CCNTEMP SET  RCMSGST=0 WHERE  RCMSGST IS NULL
	UPDATE #CCNTEMP SET  RCMIGST=0 WHERE  RCMIGST IS NULL
	UPDATE #CCNTEMP SET  RCMCGSTRATE=0 WHERE RCMCGSTRATE IS NULL
	UPDATE #CCNTEMP SET  RCMIGSTRATE=0 WHERE RCMIGSTRATE IS NULL


	UPDATE #CCNTEMP SET CGSTRATE=RCMCGSTRATE , SGSTRATE=RCMSGSTRATE WHERE RCMCGSTRATE>0 
	UPDATE #CCNTEMP SET IGSTRATE = RCMIGSTRATE WHERE RCMIGSTRATE>0 

	INSERT INTO BI.SALESHISTORY
	(ORGID,FINYEAR,PERIOD,TRANGRP,TRANSID,TRANSTYPE,INVOICENUMBER,TRANSACTIONDATE,SUPPCODE,ITEM,LEDGERCODE,BATCHREF,INVOICEDATE,
	TAXABLE_VALUE,CGST_RATE,CGST_AMOUNT,SGST_RATE,SGST_AMOUNT,IGST_RATE,IGST_AMOUNT,CGST_INPUT_RCM_AMOUNT,SGST_INPUT_RCM_AMOUNT,IGST_INPUT_RCM_AMOUNT,DOCTYPE)
	SELECT 
	ORGID,YEAR,PERIOD,TRANGRP,TRANSID,'CCN',TRANSREF,PDATE,CREDNO,UPPER(DESCRIPTION),LEDGERCODE,BATCHREF,INVOICEDATE,
	TAXABLEVALUE,CGSTRATE,CGST,SGSTRATE,SGST,IGSTRATE,IGST,RCMCGST,RCMSGST,RCMIGST,'CCN'
	FROM #CCNTEMP

	DELETE FROM #CCNTEMP

  FETCH NEXT FROM CCNTRANGRP INTO @TRANGRP 
END


CLOSE CCNTRANGRP
DEALLOCATE CCNTRANGRP


 
  







UPDATE BI.SALESHISTORY SET CGST_RATE =ABS(CGST_RATE),SGST_RATE=ABS(SGST_RATE), IGST_RATE=ABS(IGST_RATE) 
UPDATE BI.SALESHISTORY SET LEDGERNAME = UPPER(L.LEDGERNAME) FROM LEDGERCODES L INNER JOIN BI.SALESHISTORY BIP ON BIP.LEDGERCODE=L.LEDGERCODE 
UPDATE BI.SALESHISTORY SET SUPPLIERCITY =LTRIM(RTRIM(STR(C.PROVINCEID))), SUPPLIERGSTN=C.ISOCERTIFICATION,SUPPLIERNAME=UPPER(C.CREDNAME)
FROM CREDITORS C INNER JOIN BI.SALESHISTORY BIP ON BIP.SUPPCODE=C.CREDNUMBER 
UPDATE BI.SALESHISTORY SET SUPPLIERCITY =LTRIM(RTRIM(STR(S.PROVINCEID))), SUPPLIERGSTN=S.ISOCERTIFICATION,SUPPLIERNAME=UPPER(S.SUBNAME)
FROM SUBCONTRACTORS  S INNER JOIN BI.SALESHISTORY BIP ON BIP.SUPPCODE=S.SUBNUMBER 
UPDATE BI.SALESHISTORY SET SUPPLIERCITY =LTRIM(RTRIM(STR(D.PROVINCEID))), SUPPLIERGSTN=D.ISOCERTIFICATION,SUPPLIERNAME=UPPER(D.DEBTNAME)
FROM DEBTORS D INNER JOIN BI.SALESHISTORY BIP ON BIP.SUPPCODE=D.DEBTNUMBER 
UPDATE BI.SALESHISTORY SET SUPPLIERCITY = UPPER(BIS.SHORTNAME) FROM BI.STATES BIS INNER JOIN BI.SALESHISTORY BIP ON BIP.SUPPLIERCITY =BIS.PROVINCEID 
UPDATE BI.SALESHISTORY SET SUPPLIERCITYNAME = UPPER(BIS.STATENAME) FROM BI.STATES BIS INNER JOIN BI.SALESHISTORY BIP ON BIP.SUPPLIERCITY=BIS.SHORTNAME

UPDATE BI.SALESHISTORY SET CGST_INPUT_RCM_AMOUNT=0,CGST_OUTPUT_RCM_AMOUNT=0 WHERE CGST_INPUT_RCM_AMOUNT IS NULL 
UPDATE BI.SALESHISTORY SET SGST_INPUT_RCM_AMOUNT=0,SGST_OUTPUT_RCM_AMOUNT=0 WHERE SGST_INPUT_RCM_AMOUNT IS NULL 
UPDATE BI.SALESHISTORY SET IGST_INPUT_RCM_AMOUNT=0,IGST_OUTPUT_RCM_AMOUNT=0 WHERE IGST_INPUT_RCM_AMOUNT IS NULL 
UPDATE BI.SALESHISTORY SET GST_EXPENSE =0 WHERE GST_EXPENSE IS NULL
UPDATE BI.SALESHISTORY SET UOM='' WHERE UOM IS NULL
UPDATE BI.SALESHISTORY SET QTY=0 WHERE QTY IS NULL
UPDATE BI.SALESHISTORY SET RATE =0 WHERE RATE IS NULL
UPDATE BI.SALESHISTORY SET ITEM= UPPER(ITEM) ,SUPPLIERNAME = UPPER(SUPPLIERNAME),SUPPLIERCITY =UPPER(SUPPLIERCITY),SUPPLIERCITYNAME = UPPER(SUPPLIERCITYNAME) 
UPDATE BI.SALESHISTORY SET ORDERNO ='' WHERE ORDERNO IS NULL
UPDATE BI.SALESHISTORY SET SUPPLIERNAME='',SUPPLIERGSTN='' , SUPPLIERCITY='',SUPPLIERCITYNAME='' WHERE SUPPLIERNAME IS NULL

UPDATE BI.SALESHISTORY SET BORGNAME = B.BORGNAME , CILGSTIN = B.COMPREG FROM BORGS B INNER JOIN BI.SALESHISTORY BIP ON BIP.ORGID=B.BORGID 
UPDATE BI.SALESHISTORY SET DOCTYPE = TRANSTYPE 
UPDATE BI.SALESHISTORY SET GSTTYPE = 'OUTPUT' WHERE ABS(CGST_AMOUNT) > 0 
UPDATE BI.SALESHISTORY SET GSTTYPE = 'OUTPUT' WHERE ABS(IGST_AMOUNT) > 0 
UPDATE BI.SALESHISTORY SET GSTTYPE = 'RCM' WHERE ABS(CGST_INPUT_RCM_AMOUNT) > 0 
UPDATE BI.SALESHISTORY SET GSTTYPE = 'GST EXPENSE' WHERE ABS(GST_EXPENSE) > 0
UPDATE BI.SALESHISTORY SET DOCTYPE='SCI' WHERE TRANSTYPE='SCI' AND CGST_AMOUNT >0 


UPDATE BI.SALESHISTORY SET CGST_RATE = 2.5  WHERE CGST_RATE  BETWEEN 2 AND 3
UPDATE BI.SALESHISTORY SET SGST_RATE = 2.5  WHERE SGST_RATE  BETWEEN 2 AND 3


UPDATE BI.SALESHISTORY SET CGST_RATE = 6.0 WHERE CGST_RATE  BETWEEN 4 AND 8
UPDATE BI.SALESHISTORY SET SGST_RATE = 6.0 WHERE SGST_RATE  BETWEEN 4 AND 8


UPDATE BI.SALESHISTORY SET CGST_RATE = 9.0 WHERE CGST_RATE BETWEEN 7 AND 11
UPDATE BI.SALESHISTORY SET SGST_RATE = 9.0 WHERE SGST_RATE BETWEEN 7 AND 11



UPDATE BI.SALESHISTORY SET IGST_RATE =18.0 WHERE IGST_RATE BETWEEN 17 AND 19
UPDATE BI.SALESHISTORY SET IGST_RATE = 18.0 WHERE IGST_RATE BETWEEN 17 AND 19


UPDATE BI.SALESHISTORY SET PERIODNAME = P.PERIODDESC FROM PERIODMASTER P INNER JOIN BI.SALESHISTORY BIP ON BIP.PERIOD = P.PERIODID 


UPDATE BI.SALESHISTORY  SET SUPPLIERGSTN=C.ISOCERTIFICATION FROM CREDITORS C INNER JOIN BI.SALESHISTORY  B ON B.SUPPCODE=C.CREDNUMBER 
UPDATE BI.SALESHISTORY  SET SUPPLIERGSTN=S.ISOCERTIFICATION FROM SUBCONTRACTORS S INNER JOIN BI.SALESHISTORY  B ON B.SUPPCODE=S.SUBNUMBER 
UPDATE BI.SALESHISTORY  SET SUPPLIERGSTN=D.ISOCERTIFICATION FROM DEBTORS D INNER JOIN BI.SALESHISTORY B ON B.SUPPCODE=D.DEBTNUMBER 
 
-- The Procedure used for updating the Total value and Rate for DTI and SCI

EXEC [BI].[spUpdateDTI_FORGST]  @CURRENTLASTTRANGRP


--SELECT * FROM BI.SALESHISTORY    ORDER BY ORGID,PERIOD,TRANSTYPE 


 