/****** Object:  Procedure [BI].[spLoadPurchasesForGST]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE [BI].[spLoadPurchasesForGST]
as
 
--DELETE FROM BI.PURCHASEHISTORY 
--DBCC CHECKIDENT ("BI.PURCHASEHISTORY",RESEED,0)
 
 
DECLARE @GSTSTART VARCHAR(10)
DECLARE @GSTEND   VARCHAR(10)
DECLARE @WIP VARCHAR(10)
DECLARE @RETAINED VARCHAR(10)
DECLARE @GSTEXPENSE VARCHAR(10)

DECLARE @CREDNO VARCHAR(10) 
DECLARE @GSTCOUNT  INT
DECLARE @CREDITORCOUNT INT
DECLARE @EXPENSECOUNT INT
DECLARE @LASTTRANGRP INT 

CREATE TABLE #GSTINPUT(LEDGERCODE VARCHAR(10)) 
INSERT INTO #GSTINPUT VALUES ( '1310025' )
INSERT INTO #GSTINPUT VALUES ( '1310026' )
INSERT INTO #GSTINPUT VALUES ( '1310027' )
INSERT INTO #GSTINPUT VALUES ( '1310031' )
INSERT INTO #GSTINPUT VALUES ( '1310032' )
INSERT INTO #GSTINPUT VALUES ( '1310033' )
 

  

SELECT @WIP= CONTROLFROMGL FROM CONTROLCODES WHERE CONTROLNAME ='Work in Progress' 
SELECT @RETAINED = CONTROLFROMGL FROM CONTROLCODES WHERE CONTROLNAME = 'Retained Income' 

SET @GSTSTART = '1310025'
SET @GSTEND = '1310035' 
SET @GSTEXPENSE= '5130001'

DECLARE @STOCKFROM VARCHAR(10)
DECLARE @STOCKTO   VARCHAR(10)
DECLARE @FAFROM    VARCHAR(10)
DECLARE @FATO      VARCHAR(10)
DECLARE @CREDITORCODE VARCHAR(10)
DECLARE @TRANSFROM INT
DECLARE @TRANSEND  INT
DECLARE @TRANGRP INT

DECLARE @CGSTPERC DECIMAL(15,2)
DECLARE @CGSTAMOUNT DECIMAL(15,2)

DECLARE @SGSTPERC DECIMAL(15,2)
DECLARE @SGSTAMOUNT DECIMAL(15,2)

DECLARE @IGSTPERC DECIMAL(15,2)
DECLARE @IGSTAMOUNT DECIMAL(15,2)

DECLARE @CESSPERC DECIMAL(15,2)
DECLARE @CESSAMOUNT DECIMAL(15,2)

DECLARE @TAXABLEAMOUNT DECIMAL(15,2)

DECLARE @SUPPLIERNAME VARCHAR(90)
DECLARE @SUPPLIERADDRESS VARCHAR(80)
DECLARE @SUPPLIERGSTN VARCHAR(15)
DECLARE @STATEOFSUPPLY CHAR(2)
DECLARE @SUPPLIERCITY  VARCHAR(40)
DECLARE @SUPPLIERPROVINCE INT 
DECLARE @STATECODE CHAR(2)

DECLARE @ORGGSTN  VARCHAR(15)

DECLARE @GRN VARCHAR(50)
DECLARE @GRNQTY DECIMAL(15,2) 
DECLARE @GRNDATE DATETIME
DECLARE @GRNAMOUNT DECIMAL(15,2)

DECLARE @ORGID INT 
DECLARE @SUPPLIERCODE VARCHAR(10)
DECLARE @INDEXCOUNTER INT
DECLARE @TRANSID  INT
DECLARE @LINECOUNT INT 
DECLARE @LEDGERALLOC VARCHAR(15)
DECLARE @LEDGERCODE VARCHAR(10)
DECLARE @ITEMCOUNT INT 
DECLARE @TAXAMOUNT DECIMAL(18,2) 
DECLARE @TRANSACTIONORG INT 
DECLARE @NARRATION VARCHAR(255)
DECLARE @GSTLEDGERS INT 
DECLARE @GSTEXPENSECOUNT DECIMAL(18,2) 

DECLARE @CRILEDGERCODE VARCHAR(10)
DECLARE @CRIINVOICEDATE DATETIME 
DECLARE @CBCRECEIVEDATE DATETIME 
DECLARE @CBCTRANSID INT
DECLARE @CBCLEDGERCODE VARCHAR(15)
DECLARE @CBDRECEIVEDATE DATETIME 
DECLARE @CBDTRANSID INT
DECLARE @CBDLEDGERCODE VARCHAR(15)
DECLARE @INSERTED INT 

DECLARE @PURCHASETOSTOCK INT 
DECLARE @WHOISHE VARCHAR(15) 
DECLARE @WHICHISRECEIVINGORG INT 

DECLARE @CGSTCOUNT INT
DECLARE @CGSTRATE DECIMAL(18,2)

DECLARE @IGSTCOUNT INT
DECLARE @IGSTRATE DECIMAL(18,2)

DECLARE @RCMCGSTCOUNT INT
DECLARE @RCMCGSTRATE DECIMAL(18,2)

DECLARE @RCMIGSTCOUNT INT
DECLARE @RCMIGSTRATE DECIMAL(18,2)

DECLARE @RCMSGSTAMOUNT DECIMAL(18,2) 

SELECT @STOCKFROM=CONTROLFROMGL , @STOCKTO=CONTROLTOGL FROM CONTROLCODES WHERE CONTROLNAME='Stock' 
SELECT @FAFROM =CONTROLFROMGL , @FATO=CONTROLTOGL FROM CONTROLCODES WHERE CONTROLNAME='Fixed Asset' 
SELECT @CREDITORCODE = CONTROLFROMGL FROM CONTROLCODES WHERE CONTROLNAME='Creditors' 

SELECT ICGLCODE INTO #TEMPICLA  FROM BORGS  WHERE BORGID NOT IN (SELECT BORGID FROM BORGS WHERE ICGLCODE IS NULL ) 
INSERT INTO #TEMPICLA VALUES (@WIP)
INSERT INTO #TEMPICLA VALUES (@RETAINED) 

CREATE TABLE #TAXAMOUNTSCI (LEDGERCODE VARCHAR(10),TAXAMOUNT DECIMAL(18,2),WORKDONE DECIMAL(18,2),PERC DECIMAL(18,2) )
CREATE TABLE #STKADJ (TRANSID INT) 
CREATE TABLE #GSTTRANS (LEDGERCODE VARCHAR(15),PERC DECIMAL(18,2) ) 
CREATE TABLE #TAXAMOUNT (LEDGERCODE VARCHAR(10),TAXAMOUNT DECIMAL(18,2))

 
 -- PURCHASE

CREATE TABLE #DELTEMP(LINECOUNT INT PRIMARY KEY IDENTITY (1,1) , ORGID INT,  YEAR INT,PERIOD INT,PDATE DATE, INVOICEDATE DATE,
BATCHREF VARCHAR(25), TRANSREF VARCHAR(50), CREDNO VARCHAR(25), TRANGRP INT,TRANSID INT,LEDGERCODE VARCHAR(25),DESCRIPTION VARCHAR(400),
TAXABLEVALUE DECIMAL(18,2),DEBIT DECIMAL(18,2),CREDIT DECIMAL(18,2),
CGSTRATE DECIMAL(18,2),CGST DECIMAL(18,2),
SGSTRATE DECIMAL(18,2),SGST DECIMAL(18,2),
IGSTRATE DECIMAL(18,2),IGST DECIMAL(18,2),
RCMCGSTRATE DECIMAL(18,2), RCMCGST DECIMAL(18,2),
RCMSGSTRATE DECIMAL(18,2), RCMSGST DECIMAL(18,2),
RCMIGSTRATE DECIMAL(18,2), RCMIGST DECIMAL(18,2)
)

 
  
SET @LINECOUNT = 0 

DECLARE PURTRANGRP CURSOR 
FOR 
SELECT 
  DISTINCT TRANGRP FROM TRANSACTIONS 
  WHERE 
   YEAR>=2019    AND 
   TRANSTYPE='DEL' AND 
   LEDGERCODE IN (SELECT LEDGERCODE FROM #GSTINPUT) AND
   TRANGRP NOT IN (SELECT TRANGRP FROM BI.PURCHASEHISTORY WHERE DOCTYPE='DEL') 

 
OPEN PURTRANGRP 
FETCH NEXT FROM PURTRANGRP INTO @TRANGRP 

WHILE @@FETCH_STATUS=0
BEGIN
  DELETE FROM #STKADJ 
  INSERT INTO #STKADJ 
  SELECT TRANSID  FROM TRANSACTIONS WHERE TRANGRP = @TRANGRP AND LEDGERCODE='2513000' 
  
       
  SELECT @TRANSFROM = MIN(TRANSID), @TRANSEND = MAX(TRANSID) FROM TRANSACTIONS WHERE TRANGRP=@TRANGRP 

  DELETE FROM #GSTTRANS 
  INSERT INTO #GSTTRANS
  SELECT DISTINCT  LEDGERCODE,PERC    FROM TAXTRANS  WHERE TRANSID BETWEEN @TRANSFROM AND @TRANSEND AND TRANSID NOT IN (SELECT TRANSID FROM #STKADJ) 
  
  DELETE FROM #TAXAMOUNT 
  INSERT INTO #TAXAMOUNT 
  SELECT LEDGERCODE,SUM(DEBIT-CREDIT) TAXAMOUNT 
  FROM TRANSACTIONS 
  WHERE TRANGRP = @TRANGRP  AND LEDGERCODE IN (SELECT LEDGERCODE FROM #GSTINPUT) GROUP BY LEDGERCODE 

 
   
  INSERT INTO #DELTEMP(TRANGRP,  CGST ) 
  SELECT @TRANGRP,   TAXAMOUNT FROM #TAXAMOUNT  WHERE LEDGERCODE='1310025'  
  
  SET @SGSTAMOUNT = 0
  SET @RCMSGSTAMOUNT = 0 

  SELECT @SGSTAMOUNT = TAXAMOUNT FROM #TAXAMOUNT WHERE LEDGERCODE='1310026'  
  UPDATE #DELTEMP SET SGST = @SGSTAMOUNT  WHERE TRANGRP = @TRANGRP 

  SELECT @CGSTCOUNT = COUNT(*) FROM #GSTTRANS WHERE LEDGERCODE='1310025' 
  IF @CGSTCOUNT = 1
     BEGIN 
	   SELECT @CGSTPERC = PERC FROM #GSTTRANS WHERE LEDGERCODE='1310025' 
	   UPDATE #DELTEMP SET CGSTRATE = @CGSTPERC,SGSTRATE = @CGSTPERC  WHERE   TRANGRP = @TRANGRP 
	 END

  INSERT INTO #DELTEMP(TRANGRP, IGST ) 
  SELECT @TRANGRP,   TAXAMOUNT FROM #TAXAMOUNT  WHERE LEDGERCODE='1310027' 
  SELECT @IGSTCOUNT = COUNT(*) FROM #GSTTRANS WHERE LEDGERCODE='1310027' 
  IF @IGSTCOUNT = 1
     BEGIN 
	   SELECT @IGSTPERC = PERC FROM #GSTTRANS WHERE LEDGERCODE='1310027' 
	   UPDATE #DELTEMP SET IGSTRATE = @IGSTPERC WHERE    TRANGRP = @TRANGRP 
	 END


  INSERT INTO #DELTEMP(TRANGRP,  RCMCGST ) 
  SELECT @TRANGRP,   TAXAMOUNT FROM #TAXAMOUNT  WHERE LEDGERCODE='1310031'
  SELECT @RCMCGSTCOUNT = COUNT(*) FROM #GSTTRANS WHERE LEDGERCODE='1310031' 
  IF @RCMCGSTCOUNT = 1
     BEGIN 
	   SELECT @RCMCGSTRATE = PERC FROM #GSTTRANS WHERE LEDGERCODE='1310031' 
	   UPDATE #DELTEMP SET RCMCGSTRATE  = @RCMCGSTRATE, RCMSGSTRATE  = @RCMCGSTRATE  WHERE    TRANGRP = @TRANGRP 
	 END
  SELECT @RCMSGSTAMOUNT = TAXAMOUNT FROM #TAXAMOUNT WHERE LEDGERCODE='1310032'  
  UPDATE #DELTEMP SET RCMSGST = @RCMSGSTAMOUNT  WHERE TRANGRP = @TRANGRP 

  INSERT INTO #DELTEMP(TRANGRP ,  RCMIGST ) 
  SELECT @TRANGRP,   TAXAMOUNT FROM #TAXAMOUNT  WHERE LEDGERCODE='1310033'
  SELECT @RCMIGSTCOUNT = COUNT(*) FROM #GSTTRANS WHERE LEDGERCODE='1310033' 
  IF @RCMIGSTCOUNT = 1
     BEGIN 
	   SELECT @RCMIGSTRATE = PERC FROM #GSTTRANS WHERE LEDGERCODE='1310033' 
	   UPDATE #DELTEMP SET IGSTRATE = @RCMIGSTRATE WHERE    TRANGRP = @TRANGRP 
	 END

  UPDATE  #DELTEMP 
  SET ORGID=T.ORGID,YEAR=T.YEAR,PERIOD=T.PERIOD,PDATE=T.PDATE,INVOICEDATE=T.RECEIVEDDATE,BATCHREF=T.BATCHREF,TRANSREF =T.TRANSREFEXT,TRANSID=T.TRANSID,
      CREDNO=T.CREDNO, TAXABLEVALUE = T.CREDIT  FROM TRANSACTIONS T  INNER JOIN #DELTEMP ON #DELTEMP.TRANGRP = T.TRANGRP  WHERE  T.LEDGERCODE ='1315000' 

  
  UPDATE #DELTEMP 
   SET LEDGERCODE = T.LEDGERCODE,DESCRIPTION=T.DESCRIPTION FROM TRANSACTIONS T WHERE #DELTEMP.TRANGRP = @TRANGRP AND T.TRANSID = @TRANSFROM
  
  UPDATE #DELTEMP SET  CREDIT=0 WHERE CREDIT IS NULL AND TRANGRP = @TRANGRP 
  UPDATE #DELTEMP SET  CGST=0 WHERE  CGST IS NULL AND TRANGRP = @TRANGRP 
  UPDATE #DELTEMP SET  SGST=0 WHERE  SGST IS NULL  AND TRANGRP = @TRANGRP 
  UPDATE #DELTEMP SET  IGST=0 WHERE  IGST IS NULL  AND TRANGRP = @TRANGRP 
  UPDATE #DELTEMP SET  RCMCGST=0 WHERE  RCMCGST IS NULL  AND TRANGRP = @TRANGRP 
  UPDATE #DELTEMP SET  RCMSGST=0 WHERE  RCMSGST IS NULL  AND TRANGRP = @TRANGRP 
  UPDATE #DELTEMP SET  RCMIGST=0 WHERE  RCMIGST IS NULL  AND TRANGRP = @TRANGRP 
  UPDATE #DELTEMP SET  CREDIT=0 WHERE CREDIT IS NULL 
  UPDATE #DELTEMP SET  CGST=0 WHERE  CGST IS NULL
  UPDATE #DELTEMP SET  SGST=0 WHERE  SGST IS NULL
  UPDATE #DELTEMP SET  IGST=0 WHERE  IGST IS NULL
  UPDATE #DELTEMP SET  RCMCGST=0 WHERE  RCMCGST IS NULL
  UPDATE #DELTEMP SET  RCMSGST=0 WHERE  RCMSGST IS NULL
  UPDATE #DELTEMP SET  RCMIGST=0 WHERE  RCMIGST IS NULL
  UPDATE #DELTEMP SET  RCMCGSTRATE=0 WHERE RCMCGSTRATE IS NULL
  UPDATE #DELTEMP SET  RCMIGSTRATE=0 WHERE RCMIGSTRATE IS NULL
  UPDATE #DELTEMP SET CGSTRATE=RCMCGSTRATE , SGSTRATE=RCMSGSTRATE WHERE RCMCGSTRATE>0 
  UPDATE #DELTEMP SET IGSTRATE = RCMIGSTRATE WHERE RCMIGSTRATE>0 

  INSERT INTO BI.PURCHASEHISTORY
  (ORGID,FINYEAR,PERIOD,TRANGRP,TRANSID,TRANSTYPE,INVOICENUMBER,TRANSACTIONDATE,SUPPCODE,ITEM,LEDGERCODE,BATCHREF,INVOICEDATE,
  TAXABLE_VALUE,CGST_RATE,CGST_AMOUNT,SGST_RATE,SGST_AMOUNT,IGST_RATE,IGST_AMOUNT,CGST_INPUT_RCM_AMOUNT,SGST_INPUT_RCM_AMOUNT,IGST_INPUT_RCM_AMOUNT,DOCTYPE)
  SELECT 
   ORGID,YEAR,PERIOD,TRANGRP,TRANSID,'DEL',TRANSREF,PDATE,CREDNO,UPPER(DESCRIPTION),LEDGERCODE,BATCHREF,INVOICEDATE,
   TAXABLEVALUE,CGSTRATE,CGST,SGSTRATE,SGST,IGSTRATE,IGST,RCMCGST,RCMSGST,RCMIGST,'DEL'
   FROM #DELTEMP

  DELETE FROM #DELTEMP

  FETCH NEXT FROM PURTRANGRP INTO @TRANGRP 
END


CLOSE PURTRANGRP
DEALLOCATE PURTRANGRP





---- CRI Transactions
CREATE TABLE #CRITEMP(LINECOUNT INT PRIMARY KEY IDENTITY (1,1) , ORGID INT,  YEAR INT,PERIOD INT,PDATE DATE, INVOICEDATE DATE,
BATCHREF VARCHAR(25), TRANSREF VARCHAR(50), CREDNO VARCHAR(25), TRANGRP INT,TRANSID INT,LEDGERCODE VARCHAR(25),DESCRIPTION VARCHAR(400),
TAXABLEVALUE DECIMAL(18,2),DEBIT DECIMAL(18,2),CREDIT DECIMAL(18,2),
CGSTRATE DECIMAL(18,2),CGST DECIMAL(18,2),
SGSTRATE DECIMAL(18,2),SGST DECIMAL(18,2),
IGSTRATE DECIMAL(18,2),IGST DECIMAL(18,2),
RCMCGSTRATE DECIMAL(18,2), RCMCGST DECIMAL(18,2),
RCMSGSTRATE DECIMAL(18,2), RCMSGST DECIMAL(18,2),
RCMIGSTRATE DECIMAL(18,2), RCMIGST DECIMAL(18,2)
)

SET @LINECOUNT = 0 
DECLARE CRITRANGRP CURSOR 
FOR 
SELECT 
  DISTINCT TRANGRP FROM TRANSACTIONS 
  WHERE 
  YEAR>=2019   AND 
  LEFT(BATCHREF,3)='CRI' AND 
  LEDGERCODE IN (SELECT LEDGERCODE FROM #GSTINPUT) AND
  TRANGRP NOT IN (SELECT TRANGRP FROM BI.PURCHASEHISTORY WHERE DOCTYPE='CRI') 

 
OPEN CRITRANGRP 
FETCH NEXT FROM CRITRANGRP INTO @TRANGRP 

WHILE @@FETCH_STATUS=0
BEGIN
  SELECT @TRANSFROM = MIN(TRANSID), @TRANSEND = MAX(TRANSID) FROM TRANSACTIONS WHERE TRANGRP=@TRANGRP 
  
  DELETE FROM #TAXAMOUNT 
  INSERT INTO #TAXAMOUNT 
  SELECT LEDGERCODE,SUM(DEBIT-CREDIT) TAXAMOUNT 
  FROM TRANSACTIONS 
  WHERE TRANGRP = @TRANGRP  AND LEDGERCODE IN (SELECT LEDGERCODE FROM #GSTINPUT) GROUP BY LEDGERCODE 

  DELETE FROM #GSTTRANS 
  INSERT INTO #GSTTRANS
  SELECT DISTINCT  LEDGERCODE,PERC    FROM TAXTRANS  WHERE TRANSID BETWEEN @TRANSFROM AND @TRANSEND  
   
  INSERT INTO #CRITEMP(TRANGRP,  CGST ) 
  SELECT @TRANGRP,   TAXAMOUNT FROM #TAXAMOUNT  WHERE LEDGERCODE='1310025'  
  
  SET @SGSTAMOUNT = 0
  SET @RCMSGSTAMOUNT = 0 

  SELECT @SGSTAMOUNT = TAXAMOUNT FROM #TAXAMOUNT WHERE LEDGERCODE='1310026'  
  UPDATE #CRITEMP SET SGST = @SGSTAMOUNT  WHERE TRANGRP = @TRANGRP 

  SELECT @CGSTCOUNT = COUNT(*) FROM #GSTTRANS WHERE LEDGERCODE='1310025' 
  IF @CGSTCOUNT = 1
     BEGIN 
	   SELECT @CGSTPERC = PERC FROM #GSTTRANS WHERE LEDGERCODE='1310025' 
	   UPDATE #CRITEMP SET CGSTRATE = @CGSTPERC,SGSTRATE = @CGSTPERC  WHERE   TRANGRP = @TRANGRP 
	 END

  INSERT INTO #CRITEMP(TRANGRP, IGST ) 
  SELECT @TRANGRP,   TAXAMOUNT FROM #TAXAMOUNT  WHERE LEDGERCODE='1310027' 
  SELECT @IGSTCOUNT = COUNT(*) FROM #GSTTRANS WHERE LEDGERCODE='1310027' 
  IF @IGSTCOUNT = 1
     BEGIN 
	   SELECT @IGSTPERC = PERC FROM #GSTTRANS WHERE LEDGERCODE='1310027' 
	   UPDATE #CRITEMP SET IGSTRATE = @IGSTPERC WHERE    TRANGRP = @TRANGRP 
	 END


  INSERT INTO #CRITEMP(TRANGRP,  RCMCGST ) 
  SELECT @TRANGRP,   TAXAMOUNT FROM #TAXAMOUNT  WHERE LEDGERCODE='1310031'
  SELECT @RCMCGSTCOUNT = COUNT(*) FROM #GSTTRANS WHERE LEDGERCODE='1310031' 
  IF @RCMCGSTCOUNT = 1
     BEGIN 
	   SELECT @RCMCGSTRATE = PERC FROM #GSTTRANS WHERE LEDGERCODE='1310031' 
	   UPDATE #CRITEMP SET RCMCGSTRATE  = @RCMCGSTRATE, RCMSGSTRATE  = @RCMCGSTRATE  WHERE    TRANGRP = @TRANGRP 
	 END
  SELECT @RCMSGSTAMOUNT = TAXAMOUNT FROM #TAXAMOUNT WHERE LEDGERCODE='1310032'  
  UPDATE #CRITEMP SET RCMSGST = @RCMSGSTAMOUNT  WHERE TRANGRP = @TRANGRP 

  INSERT INTO #CRITEMP(TRANGRP ,  RCMIGST ) 
  SELECT @TRANGRP,   TAXAMOUNT FROM #TAXAMOUNT  WHERE LEDGERCODE='1310033'
  SELECT @RCMIGSTCOUNT = COUNT(*) FROM #GSTTRANS WHERE LEDGERCODE='1310033' 
  IF @RCMIGSTCOUNT = 1
     BEGIN 
	   SELECT @RCMIGSTRATE = PERC FROM #GSTTRANS WHERE LEDGERCODE='1310033' 
	   UPDATE #CRITEMP SET IGSTRATE = @RCMIGSTRATE WHERE    TRANGRP = @TRANGRP 
	 END

  UPDATE  #CRITEMP 
  SET ORGID=T.ORGID,YEAR=T.YEAR,PERIOD=T.PERIOD,PDATE=T.PDATE,INVOICEDATE=T.RECEIVEDDATE,BATCHREF=T.BATCHREF,TRANSREF =T.TRANSREFEXT,TRANSID=T.TRANSID,
      CREDNO=T.CREDNO, TAXABLEVALUE = T.CREDIT  FROM TRANSACTIONS T  INNER JOIN #CRITEMP ON #CRITEMP.TRANGRP = T.TRANGRP  WHERE  T.LEDGERCODE ='1315000' 

  
  UPDATE #CRITEMP 
   SET LEDGERCODE = T.LEDGERCODE,DESCRIPTION=T.DESCRIPTION FROM TRANSACTIONS T WHERE #CRITEMP.TRANGRP = @TRANGRP AND T.TRANSID = @TRANSFROM
  
	  UPDATE #CRITEMP SET  CREDIT=0 WHERE CREDIT IS NULL AND TRANGRP = @TRANGRP 
	  UPDATE #CRITEMP SET  CGST=0 WHERE  CGST IS NULL AND TRANGRP = @TRANGRP 
	  UPDATE #CRITEMP SET  SGST=0 WHERE  SGST IS NULL  AND TRANGRP = @TRANGRP 
	  UPDATE #CRITEMP SET  IGST=0 WHERE  IGST IS NULL  AND TRANGRP = @TRANGRP 
	  UPDATE #CRITEMP SET  RCMCGST=0 WHERE  RCMCGST IS NULL  AND TRANGRP = @TRANGRP 
	  UPDATE #CRITEMP SET  RCMSGST=0 WHERE  RCMSGST IS NULL  AND TRANGRP = @TRANGRP 
	  UPDATE #CRITEMP SET  RCMIGST=0 WHERE  RCMIGST IS NULL  AND TRANGRP = @TRANGRP 
	  UPDATE #CRITEMP SET  CREDIT=0 WHERE CREDIT IS NULL 
	  UPDATE #CRITEMP SET  CGST=0 WHERE  CGST IS NULL
	  UPDATE #CRITEMP SET  SGST=0 WHERE  SGST IS NULL
	  UPDATE #CRITEMP SET  IGST=0 WHERE  IGST IS NULL
	  UPDATE #CRITEMP SET  RCMCGST=0 WHERE  RCMCGST IS NULL
	  UPDATE #CRITEMP SET  RCMSGST=0 WHERE  RCMSGST IS NULL
	  UPDATE #CRITEMP SET  RCMIGST=0 WHERE  RCMIGST IS NULL
	  UPDATE #CRITEMP SET  RCMCGSTRATE=0 WHERE RCMCGSTRATE IS NULL
	  UPDATE #CRITEMP SET  RCMIGSTRATE=0 WHERE RCMIGSTRATE IS NULL 
	  UPDATE #CRITEMP SET CGSTRATE=RCMCGSTRATE , SGSTRATE=RCMSGSTRATE WHERE RCMCGSTRATE>0 
	  UPDATE #CRITEMP SET IGSTRATE = RCMIGSTRATE WHERE RCMIGSTRATE>0 

	 INSERT INTO BI.PURCHASEHISTORY
	 (ORGID,FINYEAR,PERIOD,TRANGRP,TRANSID,TRANSTYPE,INVOICENUMBER,TRANSACTIONDATE,SUPPCODE,ITEM,LEDGERCODE,BATCHREF,INVOICEDATE,
	 TAXABLE_VALUE,CGST_RATE,CGST_AMOUNT,SGST_RATE,SGST_AMOUNT,IGST_RATE,IGST_AMOUNT,CGST_INPUT_RCM_AMOUNT,SGST_INPUT_RCM_AMOUNT,IGST_INPUT_RCM_AMOUNT,DOCTYPE)
	 SELECT 
	 ORGID,YEAR,PERIOD,TRANGRP,TRANSID,'CRI',TRANSREF,PDATE,CREDNO,UPPER(DESCRIPTION),LEDGERCODE,BATCHREF,INVOICEDATE,
	 TAXABLEVALUE,CGSTRATE,CGST,SGSTRATE,SGST,IGSTRATE,IGST,RCMCGST,RCMSGST,RCMIGST,'CRI'
	 FROM #CRITEMP

	 DELETE FROM #CRITEMP

  FETCH NEXT FROM CRITRANGRP INTO @TRANGRP 
END


CLOSE CRITRANGRP
DEALLOCATE CRITRANGRP






 
  




 



---- SUBCONTRACTOR BILL BOOKINGS 
---- SCI

DECLARE @WORKDONE DECIMAL(18,2) 

CREATE TABLE #SCITEMP(LINECOUNT INT PRIMARY KEY IDENTITY (1,1) , ORGID INT,  YEAR INT,PERIOD INT,PDATE DATE, INVOICEDATE DATE,
BATCHREF VARCHAR(25), TRANSREF VARCHAR(50), CREDNO VARCHAR(25), TRANGRP INT,TRANSID INT,LEDGERCODE VARCHAR(25),DESCRIPTION VARCHAR(400),
TAXABLEVALUE DECIMAL(18,2),DEBIT DECIMAL(18,2),CREDIT DECIMAL(18,2),
CGSTRATE DECIMAL(18,2),CGST DECIMAL(18,2),
SGSTRATE DECIMAL(18,2),SGST DECIMAL(18,2),
IGSTRATE DECIMAL(18,2),IGST DECIMAL(18,2),
RCMCGSTRATE DECIMAL(18,2), RCMCGST DECIMAL(18,2),
RCMSGSTRATE DECIMAL(18,2), RCMSGST DECIMAL(18,2),
RCMIGSTRATE DECIMAL(18,2), RCMIGST DECIMAL(18,2)
)

SET @LINECOUNT = 0 
DECLARE SCITRANGRP CURSOR 
FOR 
SELECT 
  DISTINCT TRANGRP FROM TRANSACTIONS 
  WHERE 
  YEAR>=2019    AND 
  LEFT(BATCHREF,3)='SCI' AND
  LEDGERCODE IN (SELECT LEDGERCODE FROM #GSTINPUT)  AND
  TRANGRP NOT IN (SELECT TRANGRP FROM BI.PURCHASEHISTORY WHERE DOCTYPE='SCI')  
 

 
OPEN SCITRANGRP 
FETCH NEXT FROM SCITRANGRP INTO @TRANGRP 

WHILE @@FETCH_STATUS=0
BEGIN
 
  SELECT @TRANSFROM = MIN(TRANSID), @TRANSEND = MAX(TRANSID) FROM TRANSACTIONS WHERE TRANGRP=@TRANGRP 
  SELECT @WORKDONE = (DEBIT-CREDIT) FROM TRANSACTIONS WHERE TRANGRP =@TRANGRP AND TRANSID=@TRANSFROM 
  
  DELETE FROM #TAXAMOUNTSCI 
  INSERT INTO #TAXAMOUNTSCI 
  SELECT LEDGERCODE,SUM(DEBIT-CREDIT) TAXAMOUNT ,@WORKDONE,0 
  FROM TRANSACTIONS 
  WHERE TRANGRP = @TRANGRP  AND LEDGERCODE IN (SELECT LEDGERCODE FROM #GSTINPUT) GROUP BY LEDGERCODE 

  UPDATE #TAXAMOUNTSCI SET PERC = ROUND( (TAXAMOUNT/WORKDONE)*100.00,0 ) WHERE WORKDONE>0 
  
  INSERT INTO #SCITEMP(TRANGRP,  CGST ,CGSTRATE  ) 
  SELECT @TRANGRP,   TAXAMOUNT , PERC  FROM #TAXAMOUNTSCI  WHERE LEDGERCODE='1310025'  
  
  SET @SGSTAMOUNT = 0
  SET @RCMSGSTAMOUNT = 0 

  SELECT @SGSTAMOUNT = TAXAMOUNT FROM #TAXAMOUNTSCI WHERE LEDGERCODE='1310026'  
  UPDATE #SCITEMP SET SGST = @SGSTAMOUNT ,SGSTRATE=CGSTRATE    WHERE TRANGRP = @TRANGRP 


  INSERT INTO #SCITEMP(TRANGRP, IGST ,IGSTRATE ) 
  SELECT @TRANGRP,   TAXAMOUNT  ,PERC  FROM #TAXAMOUNTSCI  WHERE LEDGERCODE='1310027' 
  

  INSERT INTO #SCITEMP(TRANGRP,  RCMCGST ,RCMCGSTRATE  ) 
  SELECT @TRANGRP,   TAXAMOUNT ,PERC  FROM #TAXAMOUNTSCI  WHERE LEDGERCODE='1310031'
  SELECT @RCMSGSTAMOUNT = TAXAMOUNT FROM #TAXAMOUNTSCI WHERE LEDGERCODE='1310032'  
  UPDATE #SCITEMP SET RCMSGST = @RCMSGSTAMOUNT, RCMSGSTRATE = RCMCGSTRATE   WHERE TRANGRP = @TRANGRP 

 
  INSERT INTO #SCITEMP(TRANGRP ,  RCMIGST ,RCMIGSTRATE ) 
  SELECT @TRANGRP,   TAXAMOUNT , PERC  FROM #TAXAMOUNTSCI  WHERE LEDGERCODE='1310033'
  SELECT @RCMIGSTCOUNT = COUNT(*) FROM #GSTTRANS WHERE LEDGERCODE='1310033' 
 
  UPDATE  #SCITEMP 
  SET ORGID=T.ORGID,YEAR=T.YEAR,PERIOD=T.PERIOD,PDATE=T.PDATE,INVOICEDATE=T.PDATE,BATCHREF=T.BATCHREF,TRANSREF =T.TRANSREF,TRANSID=T.TRANSID,
      CREDNO=T.CREDNO, TAXABLEVALUE = T.CREDIT  FROM TRANSACTIONS T  INNER JOIN #SCITEMP ON #SCITEMP.TRANGRP = T.TRANGRP  WHERE  T.LEDGERCODE ='1320000' 

  
  UPDATE #SCITEMP 
   SET LEDGERCODE = T.LEDGERCODE,DESCRIPTION=T.DESCRIPTION FROM TRANSACTIONS T WHERE #SCITEMP.TRANGRP = @TRANGRP AND T.TRANSID = @TRANSFROM

 

  
  UPDATE #SCITEMP SET  CREDIT=0 WHERE CREDIT IS NULL AND TRANGRP = @TRANGRP 
  UPDATE #SCITEMP SET  CGST=0 WHERE  CGST IS NULL AND TRANGRP = @TRANGRP 
  UPDATE #SCITEMP SET  SGST=0 WHERE  SGST IS NULL  AND TRANGRP = @TRANGRP 
  UPDATE #SCITEMP SET  IGST=0 WHERE  IGST IS NULL  AND TRANGRP = @TRANGRP 
  UPDATE #SCITEMP SET  RCMCGST=0 WHERE  RCMCGST IS NULL  AND TRANGRP = @TRANGRP 
  UPDATE #SCITEMP SET  RCMSGST=0 WHERE  RCMSGST IS NULL  AND TRANGRP = @TRANGRP 
  UPDATE #SCITEMP SET  RCMIGST=0 WHERE  RCMIGST IS NULL  AND TRANGRP = @TRANGRP 
  UPDATE #SCITEMP SET  CREDIT=0 WHERE CREDIT IS NULL 
  UPDATE #SCITEMP SET  CGST=0 WHERE  CGST IS NULL
  UPDATE #SCITEMP SET  SGST=0 WHERE  SGST IS NULL
  UPDATE #SCITEMP SET  IGST=0 WHERE  IGST IS NULL
  UPDATE #SCITEMP SET  RCMCGST=0 WHERE  RCMCGST IS NULL
  UPDATE #SCITEMP SET  RCMSGST=0 WHERE  RCMSGST IS NULL
  UPDATE #SCITEMP SET  RCMIGST=0 WHERE  RCMIGST IS NULL
  UPDATE #SCITEMP SET  RCMCGSTRATE=0 WHERE RCMCGSTRATE IS NULL
  UPDATE #SCITEMP SET  RCMIGSTRATE=0 WHERE RCMIGSTRATE IS NULL
 
  
  UPDATE #SCITEMP SET CGSTRATE=RCMCGSTRATE , SGSTRATE=RCMSGSTRATE WHERE RCMCGSTRATE>0 
  UPDATE #SCITEMP SET IGSTRATE = RCMIGSTRATE WHERE RCMIGSTRATE>0

  INSERT INTO BI.PURCHASEHISTORY
  (ORGID,FINYEAR,PERIOD,TRANGRP,TRANSID,TRANSTYPE,INVOICENUMBER,TRANSACTIONDATE,SUPPCODE,ITEM,LEDGERCODE,BATCHREF,INVOICEDATE,
  TAXABLE_VALUE,CGST_RATE,CGST_AMOUNT,SGST_RATE,SGST_AMOUNT,IGST_RATE,IGST_AMOUNT,CGST_INPUT_RCM_AMOUNT,SGST_INPUT_RCM_AMOUNT,IGST_INPUT_RCM_AMOUNT,DOCTYPE)
  SELECT 
   ORGID,YEAR,PERIOD,TRANGRP,TRANSID,'SCI',TRANSREF,PDATE,CREDNO,UPPER(DESCRIPTION),LEDGERCODE,BATCHREF,INVOICEDATE,
   TAXABLEVALUE,CGSTRATE,CGST,SGSTRATE,SGST,IGSTRATE,IGST,RCMCGST,RCMSGST,RCMIGST,'SCI'
  FROM #SCITEMP

  DELETE FROM #SCITEMP

  FETCH NEXT FROM SCITRANGRP INTO @TRANGRP 

  

  
END


CLOSE SCITRANGRP
DEALLOCATE SCITRANGRP



 
  



 
 
---- CBC / PCP TRANSACTIONS-----------------------------------------------------------------------------------------

---- CBC, CBD, PCP, PCR 


DECLARE @BANKSTART VARCHAR(10)
DECLARE @BANKEND   VARCHAR(10)
SELECT @BANKSTART = CONTROLFROMGL, @BANKEND = CONTROLTOGL FROM CONTROLCODES WHERE CONTROLNAME='Bank' 

CREATE TABLE #BANKLEDGERS(LEDGERCODE VARCHAR(10))
INSERT INTO #BANKLEDGERS 
SELECT LEDGERCODE FROM LEDGERCODES WHERE LEDGERCODE BETWEEN @BANKSTART AND @BANKEND AND LedgerSummary=0
INSERT INTO #BANKLEDGERS VALUES ('2551000')


 
CREATE TABLE #GSTTRANSCBC (LEDGERCODE VARCHAR(15),PERC DECIMAL(18,2) , BILLAMOUNT DECIMAL(18,2) ) 

DECLARE @BILLVALUE  DECIMAL(18,2) 
DECLARE @DOCTYPE VARCHAR(3) 
DECLARE @FOREIGNID INT 
DECLARE @TOTALTAX DECIMAL(18,2)
DECLARE @DERIVEDPERC DECIMAL(18,2) 
DECLARE @ENTRYEXISTS INT 
DECLARE @BILLAMOUNT DECIMAL(18,2) 
DECLARE @CBCTAXPERCENT DECIMAL(18,2) 

CREATE TABLE #CBCTEMP(LINECOUNT INT PRIMARY KEY IDENTITY (1,1) , ORGID INT,  YEAR INT,PERIOD INT,PDATE DATE, INVOICEDATE DATE,
BATCHREF VARCHAR(25), TRANSREF VARCHAR(50), CREDNO VARCHAR(25), TRANGRP INT,TRANSID INT,LEDGERCODE VARCHAR(25),DESCRIPTION VARCHAR(400),
TAXABLEVALUE DECIMAL(18,2),DEBIT DECIMAL(18,2),CREDIT DECIMAL(18,2),
CGSTRATE DECIMAL(18,2),CGST DECIMAL(18,2),
SGSTRATE DECIMAL(18,2),SGST DECIMAL(18,2),
IGSTRATE DECIMAL(18,2),IGST DECIMAL(18,2),
RCMCGSTRATE DECIMAL(18,2), RCMCGST DECIMAL(18,2),
RCMSGSTRATE DECIMAL(18,2), RCMSGST DECIMAL(18,2),
RCMIGSTRATE DECIMAL(18,2), RCMIGST DECIMAL(18,2),
DOCTYPE VARCHAR(3)
)






SET @LINECOUNT = 0 
DECLARE CBCTRANGRP CURSOR 
FOR 
SELECT 
  DISTINCT TRANGRP FROM TRANSACTIONS 
  WHERE 
  YEAR>=2019   AND 
  LEFT(BATCHREF,3) IN ('CBC','CBD','PCP','PCR') AND
  LEDGERCODE IN (SELECT LEDGERCODE FROM #GSTINPUT)   AND
  TRANGRP NOT IN (SELECT TRANGRP FROM BI.PURCHASEHISTORY WHERE DOCTYPE IN ( 'CBC','CBD','PCP','PCR' ) )  
 

 
OPEN CBCTRANGRP 
FETCH NEXT FROM CBCTRANGRP INTO @TRANGRP 

WHILE @@FETCH_STATUS=0
BEGIN
  
  SELECT @TRANSFROM = MIN(TRANSID), @TRANSEND = MAX(TRANSID) FROM TRANSACTIONS WHERE TRANGRP=@TRANGRP 
  SELECT @DOCTYPE = LEFT(BATCHREF,3) FROM TRANSACTIONS WHERE TRANGRP =@TRANGRP AND TRANSID=@TRANSFROM 
  SET @ENTRYEXISTS = 0 
  SELECT @ENTRYEXISTS = COUNT(*) FROM TAXTRANS WHERE TRANSID BETWEEN @TRANSFROM AND @TRANSEND 

  IF @ENTRYEXISTS > 0
    BEGIN
	 SELECT LEDGERCODE,SUM(CUMCOST) TOTALCOST 
	 INTO #TEMP0 
	 FROM TAXTRANS 
	 WHERE TRANSID BETWEEN @TRANSFROM AND @TRANSEND
	 GROUP BY LEDGERCODE 
     DELETE FROM #GSTTRANSCBC
     INSERT INTO #GSTTRANSCBC 
	 SELECT  LEDGERCODE,PERC,0  FROM TAXTRANS WHERE TRANSID BETWEEN @TRANSFROM AND @TRANSEND
	 UPDATE #GSTTRANSCBC SET BILLAMOUNT=T.TOTALCOST FROM #TEMP0 T INNER JOIN #GSTTRANSCBC ON T.LEDGERCODE=#GSTTRANSCBC.LEDGERCODE 
	 DROP TABLE #TEMP0 
    END
  ELSE
    SET @BILLAMOUNT = 0 
  
  DELETE FROM #TAXAMOUNT 
  INSERT INTO #TAXAMOUNT 
  SELECT LEDGERCODE,SUM(DEBIT-CREDIT) TAXAMOUNT  
  FROM TRANSACTIONS 
  WHERE TRANGRP = @TRANGRP  AND LEDGERCODE IN (SELECT LEDGERCODE FROM #GSTINPUT) GROUP BY LEDGERCODE 

  
  SET @BILLAMOUNT = 0
  SELECT @BILLAMOUNT = BILLAMOUNT,@CBCTAXPERCENT =PERC  FROM #GSTTRANSCBC WHERE LEDGERCODE='1310025' AND @ENTRYEXISTS <> 0
  IF @BILLAMOUNT = 0 
     SET @BILLAMOUNT = @BILLVALUE 
  INSERT INTO #CBCTEMP(TRANGRP,  CGST ,TAXABLEVALUE ,CGSTRATE  ) 
  SELECT @TRANGRP,   TAXAMOUNT ,@BILLAMOUNT,@CBCTAXPERCENT   FROM #TAXAMOUNT   WHERE LEDGERCODE='1310025'  
  
  SET @SGSTAMOUNT = 0
  SET @RCMSGSTAMOUNT = 0 

  SELECT @SGSTAMOUNT = TAXAMOUNT FROM #TAXAMOUNT  WHERE LEDGERCODE='1310026'  
  UPDATE #CBCTEMP SET SGST = @SGSTAMOUNT ,SGSTRATE = @CBCTAXPERCENT     WHERE TRANGRP = @TRANGRP 

  SET @BILLAMOUNT = 0
  SELECT @BILLAMOUNT = BILLAMOUNT,@CBCTAXPERCENT =PERC FROM #GSTTRANSCBC WHERE LEDGERCODE='1310027' AND @ENTRYEXISTS <> 0
  IF @BILLAMOUNT = 0 
     SET @BILLAMOUNT = @BILLVALUE 
  INSERT INTO #CBCTEMP(TRANGRP, IGST ,TAXABLEVALUE,IGSTRATE   ) 
  SELECT @TRANGRP,   TAXAMOUNT ,@BILLAMOUNT ,@CBCTAXPERCENT   FROM #TAXAMOUNT   WHERE LEDGERCODE='1310027' 
  

  SET @BILLAMOUNT = 0
  SELECT @BILLAMOUNT = BILLAMOUNT,@CBCTAXPERCENT =PERC  FROM #GSTTRANSCBC WHERE LEDGERCODE='1310031' AND @ENTRYEXISTS <> 0
  IF @BILLAMOUNT = 0 
     SET @BILLAMOUNT = @BILLVALUE 
  INSERT INTO #CBCTEMP(TRANGRP,  RCMCGST  ,TAXABLEVALUE ,RCMCGSTRATE  ) 
  SELECT @TRANGRP,   TAXAMOUNT ,@BILLAMOUNT , @CBCTAXPERCENT   FROM #TAXAMOUNT  WHERE LEDGERCODE='1310031'
  SELECT @RCMSGSTAMOUNT = TAXAMOUNT FROM #TAXAMOUNT  WHERE LEDGERCODE='1310032'  
  UPDATE #CBCTEMP SET RCMSGST = @RCMSGSTAMOUNT  ,RCMSGSTRATE = @CBCTAXPERCENT   WHERE TRANGRP = @TRANGRP AND @RCMSGSTAMOUNT>0 

  SET @BILLAMOUNT = 0
  SELECT @BILLAMOUNT = BILLAMOUNT,@CBCTAXPERCENT  = PERC FROM #GSTTRANSCBC WHERE LEDGERCODE='1310033' 
  IF @BILLAMOUNT = 0 
     SET @BILLAMOUNT = @BILLVALUE 
  INSERT INTO #CBCTEMP(TRANGRP ,  RCMIGST, TAXABLEVALUE,RCMIGSTRATE  ) 
  SELECT @TRANGRP,   TAXAMOUNT ,@BILLAMOUNT ,@CBCTAXPERCENT  FROM #TAXAMOUNT   WHERE LEDGERCODE='1310033'

  
  UPDATE #CBCTEMP 
   SET ORGID=T.ORGID,YEAR=T.YEAR,PERIOD=T.PERIOD,PDATE=T.PDATE,INVOICEDATE=T.PDATE,BATCHREF=T.BATCHREF,TRANSREF =T.TRANSREF,TRANSID=T.TRANSID,
       CREDNO=T.CREDNO, DOCTYPE=LEFT(T.BATCHREF,3), LEDGERCODE = T.LEDGERCODE,DESCRIPTION=T.DESCRIPTION FROM TRANSACTIONS T 
	   INNER JOIN #CBCTEMP ON #CBCTEMP.TRANGRP=T.TRANGRP 
	   WHERE  T.TRANSID = @TRANSFROM AND T.TRANGRP=@TRANGRP 
  

  -- SOMETIMES THE CREDNO MAY BE BLANK - DOUBLE CHECKING 
  SET @WHOISHE = '' 
  SET @WHICHISRECEIVINGORG = 0 
  SELECT @WHOISHE = CREDNO,@WHICHISRECEIVINGORG = ORGID  FROM TRANSACTIONS WHERE TRANGRP = @TRANGRP AND LEDGERCODE IN ('1310025','1310027') 
  
  UPDATE #CBCTEMP SET CREDNO=@WHOISHE, ORGID = @WHICHISRECEIVINGORG  WHERE TRANGRP = @TRANGRP 
  
  
  IF @ENTRYEXISTS = 0
  BEGIN 
     SET @FOREIGNID = 0
     SELECT   @FOREIGNID= MAX(TRANSID) FROM TRANSACTIONS WHERE TRANGRP = @TRANGRP AND LEDGERCODE IN (SELECT LEDGERCODE FROM #BANKLEDGERS) 
 
     IF @FOREIGNID<>0  
        BEGIN 
 	      SELECT @BILLAMOUNT = (CREDIT-DEBIT) FROM TRANSACTIONS WHERE TRANSID=@FOREIGNID 
	      UPDATE #CBCTEMP SET  TAXABLEVALUE = @BILLAMOUNT WHERE TRANGRP = @TRANGRP 
		  UPDATE #CBCTEMP SET  CREDIT=0 WHERE CREDIT IS NULL AND TRANGRP = @TRANGRP 
		  UPDATE #CBCTEMP SET  CGST=0 WHERE  CGST IS NULL AND TRANGRP = @TRANGRP 
	  	  UPDATE #CBCTEMP SET  SGST=0 WHERE  SGST IS NULL  AND TRANGRP = @TRANGRP 
		  UPDATE #CBCTEMP SET  IGST=0 WHERE  IGST IS NULL  AND TRANGRP = @TRANGRP 
	 	  UPDATE #CBCTEMP SET  RCMCGST=0 WHERE  RCMCGST IS NULL  AND TRANGRP = @TRANGRP 
		  UPDATE #CBCTEMP SET  RCMSGST=0 WHERE  RCMSGST IS NULL  AND TRANGRP = @TRANGRP 
		  UPDATE #CBCTEMP SET  RCMIGST=0 WHERE  RCMIGST IS NULL  AND TRANGRP = @TRANGRP 
          SELECT @TOTALTAX = CGST+SGST+IGST,@TAXABLEAMOUNT = TAXABLEVALUE  FROM #CBCTEMP WHERE TRANGRP = @TRANGRP
          SET @DERIVEDPERC = 0 
		  IF (@TAXABLEAMOUNT-@TOTALTAX)  >0  
		    BEGIN
		      SET @DERIVEDPERC =ROUND ( (  @TOTALTAX / (@TAXABLEAMOUNT-@TOTALTAX) ) * 100 ,0 ) 
	          UPDATE #CBCTEMP SET CGSTRATE = @DERIVEDPERC/2.0 WHERE TRANGRP = @TRANGRP AND CGST>0  AND CGSTRATE=0
			  UPDATE #CBCTEMP SET SGSTRATE = @DERIVEDPERC/2.0 WHERE TRANGRP = @TRANGRP AND SGST>0  AND SGSTRATE=0
			  UPDATE #CBCTEMP SET IGSTRATE = @DERIVEDPERC WHERE TRANGRP = @TRANGRP AND IGST>0  AND IGSTRATE=0
			  UPDATE #CBCTEMP SET TAXABLEVALUE = (@TAXABLEAMOUNT-@TOTALTAX) WHERE TRANGRP = @TRANGRP
           END 
		END
   END
    UPDATE #CBCTEMP SET  CREDIT=0 WHERE CREDIT IS NULL 
	UPDATE #CBCTEMP SET DEBIT = 0 WHERE DEBIT IS NULL
	UPDATE #CBCTEMP SET  CGST=0 WHERE  CGST IS NULL
	UPDATE #CBCTEMP SET  SGST=0 WHERE  SGST IS NULL
	UPDATE #CBCTEMP SET  IGST=0 WHERE  IGST IS NULL
	UPDATE #CBCTEMP SET  RCMCGST=0 WHERE  RCMCGST IS NULL
	UPDATE #CBCTEMP SET  RCMSGST=0 WHERE  RCMSGST IS NULL
	UPDATE #CBCTEMP SET  RCMIGST=0 WHERE  RCMIGST IS NULL
	UPDATE #CBCTEMP SET  RCMCGSTRATE=0 WHERE RCMCGSTRATE IS NULL
	UPDATE #CBCTEMP SET  RCMIGSTRATE=0 WHERE RCMIGSTRATE IS NULL
	UPDATE #CBCTEMP SET CGSTRATE = 0 WHERE CGSTRATE IS NULL
	UPDATE #CBCTEMP SET SGSTRATE = 0 WHERE SGSTRATE IS NULL
	UPDATE #CBCTEMP SET IGSTRATE = 0 WHERE IGSTRATE IS NULL

	UPDATE #CBCTEMP SET CGSTRATE=RCMCGSTRATE , SGSTRATE=RCMSGSTRATE WHERE RCMCGSTRATE>0 
	UPDATE #CBCTEMP SET IGSTRATE = RCMIGSTRATE WHERE RCMIGSTRATE>0


 

	INSERT INTO BI.PURCHASEHISTORY
	(ORGID,FINYEAR,PERIOD,TRANGRP,TRANSID,TRANSTYPE,INVOICENUMBER,TRANSACTIONDATE,SUPPCODE,ITEM,LEDGERCODE,BATCHREF,INVOICEDATE,
	TAXABLE_VALUE,CGST_RATE,CGST_AMOUNT,SGST_RATE,SGST_AMOUNT,IGST_RATE,IGST_AMOUNT,CGST_INPUT_RCM_AMOUNT,SGST_INPUT_RCM_AMOUNT,IGST_INPUT_RCM_AMOUNT,DOCTYPE)
	SELECT 
	 ORGID,YEAR,PERIOD,TRANGRP,TRANSID,DOCTYPE,TRANSREF,PDATE,CREDNO,UPPER(DESCRIPTION),LEDGERCODE,BATCHREF,INVOICEDATE,
	 TAXABLEVALUE,CGSTRATE,CGST,SGSTRATE,SGST,IGSTRATE,IGST,RCMCGST,RCMSGST,RCMIGST,DOCTYPE
	FROM #CBCTEMP


    DELETE FROM #CBCTEMP

   FETCH NEXT FROM CBCTRANGRP INTO @TRANGRP 
END


CLOSE CBCTRANGRP
DEALLOCATE CBCTRANGRP

 

 





---- JOURNALS

SELECT TRANGRP INTO #JNLCGST FROM TRANSACTIONS WHERE YEAR>=2019 AND LEFT(BATCHREF,3)='JNL' AND LEDGERCODE='1310025'
       AND TRANGRP NOT IN (SELECT TRANGRP FROM BI.PURCHASEHISTORY WHERE LEDGERCODE='1310025' AND DOCTYPE='JNL' )
SELECT TRANGRP INTO #JNLSGST FROM TRANSACTIONS WHERE YEAR>=2019 AND  LEFT(BATCHREF,3)='JNL' AND LEDGERCODE='1310026'
       AND TRANGRP NOT IN (SELECT TRANGRP FROM BI.PURCHASEHISTORY WHERE LEDGERCODE='1310026' AND DOCTYPE='JNL' )
SELECT TRANGRP INTO #JNLIGST FROM TRANSACTIONS WHERE YEAR>=2019 AND LEFT(BATCHREF,3)='JNL' AND LEDGERCODE='1310027' 
       AND TRANGRP NOT IN (SELECT TRANGRP FROM BI.PURCHASEHISTORY WHERE LEDGERCODE='1310027' AND DOCTYPE='JNL' )

SELECT TRANGRP INTO #JNLRCGST FROM TRANSACTIONS WHERE YEAR>=2019   AND LEFT(BATCHREF,3)='JNL' AND LEDGERCODE='1310031'
      AND TRANGRP NOT IN (SELECT TRANGRP FROM BI.PURCHASEHISTORY WHERE LEDGERCODE='1310031' AND DOCTYPE='JNL' )
SELECT TRANGRP INTO #JNLRSGST FROM TRANSACTIONS WHERE YEAR>=2019   AND LEFT(BATCHREF,3)='JNL' AND LEDGERCODE='1310032'
      AND TRANGRP NOT IN (SELECT TRANGRP FROM BI.PURCHASEHISTORY WHERE LEDGERCODE='1310032' AND DOCTYPE='JNL' )
SELECT TRANGRP INTO #JNLRIGST FROM TRANSACTIONS WHERE YEAR>=2019   AND LEFT(BATCHREF,3)='JNL' AND LEDGERCODE='1310033' 
      AND TRANGRP NOT IN (SELECT TRANGRP FROM BI.PURCHASEHISTORY WHERE LEDGERCODE='1310033' AND DOCTYPE='JNL' )


INSERT INTO BI.PURCHASEHISTORY(ORGID,FINYEAR,PERIOD,TRANGRP,TRANSID,INVOICENUMBER,SUPPCODE,ITEM,LEDGERCODE,INVOICEDATE,BATCHREF,CGST_AMOUNT,DOCTYPE)
SELECT ORGID,YEAR,PERIOD,TRANGRP,TRANSID,TRANSREF,CREDNO,DESCRIPTION,LEDGERCODE,PDATE,BATCHREF,(DEBIT-CREDIT),'JNL'  FROM TRANSACTIONS 
WHERE LEDGERCODE='1310025'  AND TRANGRP IN (SELECT TRANGRP FROM #JNLCGST) 

INSERT INTO BI.PURCHASEHISTORY(ORGID,FINYEAR,PERIOD,TRANGRP,TRANSID,INVOICENUMBER,SUPPCODE,ITEM,LEDGERCODE,INVOICEDATE,BATCHREF,SGST_AMOUNT,DOCTYPE)
SELECT ORGID,YEAR,PERIOD,TRANGRP,TRANSID,TRANSREF,CREDNO,DESCRIPTION,LEDGERCODE,PDATE,BATCHREF,(DEBIT-CREDIT),'JNL'  FROM TRANSACTIONS 
WHERE LEDGERCODE='1310026' AND TRANGRP IN (SELECT TRANGRP FROM #JNLSGST) 

INSERT INTO BI.PURCHASEHISTORY(ORGID,FINYEAR,PERIOD,TRANGRP,TRANSID,INVOICENUMBER,SUPPCODE,ITEM,LEDGERCODE,INVOICEDATE,BATCHREF,IGST_AMOUNT,DOCTYPE)
SELECT ORGID,YEAR,PERIOD,TRANGRP,TRANSID,TRANSREF,CREDNO,DESCRIPTION,LEDGERCODE,PDATE,BATCHREF,(DEBIT-CREDIT),'JNL'  FROM TRANSACTIONS 
WHERE LEDGERCODE='1310027' AND TRANGRP IN (SELECT TRANGRP FROM #JNLIGST) 

INSERT INTO BI.PURCHASEHISTORY(ORGID,FINYEAR,PERIOD,TRANGRP,TRANSID,INVOICENUMBER,SUPPCODE,ITEM,LEDGERCODE,INVOICEDATE,BATCHREF,CGST_INPUT_RCM_AMOUNT,DOCTYPE)
SELECT ORGID,YEAR,PERIOD,TRANGRP,TRANSID,TRANSREF,CREDNO,DESCRIPTION,LEDGERCODE,PDATE,BATCHREF,(DEBIT-CREDIT),'JNL'  FROM TRANSACTIONS 
WHERE LEDGERCODE='1310031' AND TRANGRP IN (SELECT TRANGRP FROM #JNLRCGST) 

INSERT INTO BI.PURCHASEHISTORY(ORGID,FINYEAR,PERIOD,TRANGRP,TRANSID,INVOICENUMBER,SUPPCODE,ITEM,LEDGERCODE,INVOICEDATE,BATCHREF,SGST_INPUT_RCM_AMOUNT,DOCTYPE)
SELECT ORGID,YEAR,PERIOD,TRANGRP,TRANSID,TRANSREF,CREDNO,DESCRIPTION,LEDGERCODE,PDATE,BATCHREF,(DEBIT-CREDIT),'JNL'  FROM TRANSACTIONS 
WHERE LEDGERCODE='1310032' AND TRANGRP IN (SELECT TRANGRP FROM #JNLRSGST) 

INSERT INTO BI.PURCHASEHISTORY(ORGID,FINYEAR,PERIOD,TRANGRP,TRANSID,INVOICENUMBER,SUPPCODE,ITEM,LEDGERCODE,INVOICEDATE,BATCHREF,IGST_INPUT_RCM_AMOUNT,DOCTYPE)
SELECT ORGID,YEAR,PERIOD,TRANGRP,TRANSID,TRANSREF,CREDNO,DESCRIPTION,LEDGERCODE,PDATE,BATCHREF,(DEBIT-CREDIT),'JNL'  FROM TRANSACTIONS 
WHERE LEDGERCODE='1310033' AND TRANGRP IN (SELECT TRANGRP FROM #JNLRIGST)

UPDATE BI.PURCHASEHISTORY SET GSTTYPE='INPUT',TRANSTYPE='JNL',TRANSACTIONDATE=INVOICEDATE WHERE DOCTYPE='JNL' 
 
---- DTI

SELECT TRANGRP INTO #DTICGST FROM TRANSACTIONS WHERE YEAR>=2019   AND LEFT(BATCHREF,3)='DTI' AND LEDGERCODE ='1310025'
       AND TRANGRP NOT IN (SELECT TRANGRP FROM BI.PURCHASEHISTORY WHERE LEDGERCODE='1310025' AND DOCTYPE='DTI' )
SELECT TRANGRP INTO #DTISGST FROM TRANSACTIONS WHERE YEAR>=2019   AND LEFT(BATCHREF,3)='DTI' AND LEDGERCODE ='1310026' 
       AND TRANGRP NOT IN (SELECT TRANGRP FROM BI.PURCHASEHISTORY WHERE LEDGERCODE='1310026' AND DOCTYPE='DTI' )
SELECT TRANGRP INTO #DTIIGST FROM TRANSACTIONS WHERE YEAR>=2019   AND LEFT(BATCHREF,3)='DTI' AND LEDGERCODE ='1310027'
       AND TRANGRP NOT IN (SELECT TRANGRP FROM BI.PURCHASEHISTORY WHERE LEDGERCODE='1310027' AND DOCTYPE='DTI' )

SELECT TRANGRP INTO #DTIRCGST FROM TRANSACTIONS WHERE YEAR>=2019   AND LEFT(BATCHREF,3)='DTI' AND LEDGERCODE ='1310031'
      AND TRANGRP NOT IN (SELECT TRANGRP FROM BI.PURCHASEHISTORY WHERE LEDGERCODE='1310031' AND DOCTYPE='DTI' )
SELECT TRANGRP INTO #DTIRSGST FROM TRANSACTIONS WHERE YEAR>=2019  AND LEFT(BATCHREF,3)='DTI' AND LEDGERCODE ='1310032'
      AND TRANGRP NOT IN (SELECT TRANGRP FROM BI.PURCHASEHISTORY WHERE LEDGERCODE='1310032' AND DOCTYPE='DTI' )
SELECT TRANGRP INTO #DTIRIGST FROM TRANSACTIONS WHERE YEAR>=2019   AND LEFT(BATCHREF,3)='DTI' AND LEDGERCODE ='1310033'
      AND TRANGRP NOT IN (SELECT TRANGRP FROM BI.PURCHASEHISTORY WHERE LEDGERCODE='1310033' AND DOCTYPE='DTI' )

--SELECT * FROM #DTICGST
INSERT INTO BI.PURCHASEHISTORY(ORGID,FINYEAR,PERIOD,TRANGRP,TRANSID,INVOICENUMBER,SUPPCODE,ITEM,LEDGERCODE,INVOICEDATE,BATCHREF,CGST_AMOUNT,DOCTYPE,SUPPLIERGSTN,ORDERNO)
SELECT ORGID,YEAR,PERIOD,TRANGRP,TRANSID,TRANSREF,CREDNO,DESCRIPTION,LEDGERCODE,PDATE,BATCHREF,(DEBIT-CREDIT),'DTI',VATTYPE,ORDERNO   FROM TRANSACTIONS 
WHERE  LEDGERCODE ='1310025'  AND TRANGRP IN (SELECT TRANGRP FROM #DTICGST) 

INSERT INTO BI.PURCHASEHISTORY(ORGID,FINYEAR,PERIOD,TRANGRP,TRANSID,INVOICENUMBER,SUPPCODE,ITEM,LEDGERCODE,INVOICEDATE,BATCHREF,SGST_AMOUNT,DOCTYPE,SUPPLIERGSTN,ORDERNO)
SELECT ORGID,YEAR,PERIOD,TRANGRP,TRANSID,TRANSREF,CREDNO,DESCRIPTION,LEDGERCODE,PDATE,BATCHREF,(DEBIT-CREDIT),'DTI',VATTYPE,ORDERNO  FROM TRANSACTIONS 
WHERE  LEDGERCODE ='1310026' AND TRANGRP IN (SELECT TRANGRP FROM #DTISGST) 

INSERT INTO BI.PURCHASEHISTORY(ORGID,FINYEAR,PERIOD,TRANGRP,TRANSID,INVOICENUMBER,SUPPCODE,ITEM,LEDGERCODE,INVOICEDATE,BATCHREF,IGST_AMOUNT,DOCTYPE,SUPPLIERGSTN,ORDERNO)
SELECT ORGID,YEAR,PERIOD,TRANGRP,TRANSID,TRANSREF,CREDNO,DESCRIPTION,LEDGERCODE,PDATE,BATCHREF,(DEBIT-CREDIT),'DTI',VATTYPE,ORDERNO  FROM TRANSACTIONS 
WHERE  LEDGERCODE ='1310027' AND TRANGRP IN (SELECT TRANGRP FROM #DTIIGST) 

INSERT INTO BI.PURCHASEHISTORY(ORGID,FINYEAR,PERIOD,TRANGRP,TRANSID,INVOICENUMBER,SUPPCODE,ITEM,LEDGERCODE,INVOICEDATE,BATCHREF,CGST_INPUT_RCM_AMOUNT,DOCTYPE,SUPPLIERGSTN,ORDERNO)
SELECT ORGID,YEAR,PERIOD,TRANGRP,TRANSID,TRANSREF,CREDNO,DESCRIPTION,LEDGERCODE,PDATE,BATCHREF,(DEBIT-CREDIT),'DTI',VATTYPE,ORDERNO  FROM TRANSACTIONS 
WHERE  LEDGERCODE ='1310031' AND  TRANGRP IN (SELECT TRANGRP FROM #DTIRCGST) 

INSERT INTO BI.PURCHASEHISTORY(ORGID,FINYEAR,PERIOD,TRANGRP,TRANSID,INVOICENUMBER,SUPPCODE,ITEM,LEDGERCODE,INVOICEDATE,BATCHREF,SGST_INPUT_RCM_AMOUNT,DOCTYPE,SUPPLIERGSTN,ORDERNO)
SELECT ORGID,YEAR,PERIOD,TRANGRP,TRANSID,TRANSREF,CREDNO,DESCRIPTION,LEDGERCODE,PDATE,BATCHREF,(DEBIT-CREDIT),'DTI',VATTYPE,ORDERNO  FROM TRANSACTIONS 
WHERE  LEDGERCODE ='1310032' AND  TRANGRP IN (SELECT TRANGRP FROM #DTIRSGST) 

INSERT INTO BI.PURCHASEHISTORY(ORGID,FINYEAR,PERIOD,TRANGRP,TRANSID,INVOICENUMBER,SUPPCODE,ITEM,LEDGERCODE,INVOICEDATE,BATCHREF,IGST_INPUT_RCM_AMOUNT,DOCTYPE,SUPPLIERGSTN,ORDERNO)
SELECT ORGID,YEAR,PERIOD,TRANGRP,TRANSID,TRANSREF,CREDNO,DESCRIPTION,LEDGERCODE,PDATE,BATCHREF,(DEBIT-CREDIT),'DTI',VATTYPE,ORDERNO  FROM TRANSACTIONS 
WHERE  LEDGERCODE ='1310033' AND  TRANGRP IN (SELECT TRANGRP FROM #DTIRIGST)


UPDATE BI.PURCHASEHISTORY SET GSTTYPE='INPUT',TRANSTYPE='DTI',TRANSACTIONDATE=INVOICEDATE WHERE DOCTYPE='DTI' 
UPDATE BI.PURCHASEHISTORY SET CGST_RATE = VT.VATPERC FROM VATTYPES VT INNER JOIN BI.PURCHASEHISTORY ON BI.PURCHASEHISTORY.SUPPLIERGSTN=VT.VATID AND BI.PURCHASEHISTORY.ORGID=VT.BORGID 
WHERE BI.PURCHASEHISTORY.DOCTYPE ='DTI' AND BI.PURCHASEHISTORY.LEDGERCODE='1310025' 

UPDATE BI.PURCHASEHISTORY SET SGST_RATE = VT.VATPERC FROM VATTYPES VT INNER JOIN BI.PURCHASEHISTORY ON BI.PURCHASEHISTORY.SUPPLIERGSTN=VT.VATID AND BI.PURCHASEHISTORY.ORGID=VT.BORGID 
WHERE BI.PURCHASEHISTORY.DOCTYPE ='DTI' AND BI.PURCHASEHISTORY.LEDGERCODE='1310026' 

UPDATE BI.PURCHASEHISTORY SET IGST_RATE = VT.VATPERC FROM VATTYPES VT INNER JOIN BI.PURCHASEHISTORY ON BI.PURCHASEHISTORY.SUPPLIERGSTN=VT.VATID AND BI.PURCHASEHISTORY.ORGID=VT.BORGID 
WHERE BI.PURCHASEHISTORY.DOCTYPE ='DTI' AND BI.PURCHASEHISTORY.LEDGERCODE='1310027' 

UPDATE BI.PURCHASEHISTORY SET CGST_AMOUNT=0 WHERE CGST_AMOUNT IS NULL
UPDATE BI.PURCHASEHISTORY SET SGST_AMOUNT=0 WHERE SGST_AMOUNT IS NULL
UPDATE BI.PURCHASEHISTORY SET IGST_AMOUNT=0 WHERE IGST_AMOUNT IS NULL

UPDATE BI.PURCHASEHISTORY SET TAXABLE_VALUE = (  (CGST_AMOUNT)   * 100 / CGST_RATE ) WHERE CGST_AMOUNT > 0 AND DOCTYPE='DTI' 
UPDATE BI.PURCHASEHISTORY SET TAXABLE_VALUE = (  (SGST_AMOUNT)   * 100 / SGST_RATE ) WHERE SGST_AMOUNT > 0 AND DOCTYPE='DTI'
UPDATE BI.PURCHASEHISTORY SET TAXABLE_VALUE = (  (IGST_AMOUNT)   * 100 / IGST_RATE ) WHERE IGST_AMOUNT > 0 AND DOCTYPE='DTI'


---- CCN CREDIT NOTE TO SUPPLIERS 

---- CCN Transactions


CREATE TABLE #CCNTEMP(LINECOUNT INT PRIMARY KEY IDENTITY (1,1) , ORGID INT,  YEAR INT,PERIOD INT,PDATE DATE, INVOICEDATE DATE,
BATCHREF VARCHAR(25), TRANSREF VARCHAR(50), CREDNO VARCHAR(25), TRANGRP INT,TRANSID INT,LEDGERCODE VARCHAR(25),DESCRIPTION VARCHAR(400),
TAXABLEVALUE DECIMAL(18,2),DEBIT DECIMAL(18,2),CREDIT DECIMAL(18,2),
CGSTRATE DECIMAL(18,2),CGST DECIMAL(18,2),
SGSTRATE DECIMAL(18,2),SGST DECIMAL(18,2),
IGSTRATE DECIMAL(18,2),IGST DECIMAL(18,2),
RCMCGSTRATE DECIMAL(18,2), RCMCGST DECIMAL(18,2),
RCMSGSTRATE DECIMAL(18,2), RCMSGST DECIMAL(18,2),
RCMIGSTRATE DECIMAL(18,2), RCMIGST DECIMAL(18,2)
)

SET @LINECOUNT = 0 
DECLARE CCNTRANGRP CURSOR 
FOR 
SELECT 
  DISTINCT TRANGRP FROM TRANSACTIONS 
  WHERE 
  YEAR>=2019   AND 
  LEFT(BATCHREF,3)='CCN' AND 
  LEDGERCODE IN (SELECT LEDGERCODE FROM #GSTINPUT) AND
  TRANGRP NOT IN (SELECT TRANGRP FROM BI.PURCHASEHISTORY WHERE DOCTYPE='CCN') 

 
OPEN CCNTRANGRP 
FETCH NEXT FROM CCNTRANGRP INTO @TRANGRP 

WHILE @@FETCH_STATUS=0
BEGIN
  SELECT @TRANSFROM = MIN(TRANSID), @TRANSEND = MAX(TRANSID) FROM TRANSACTIONS WHERE TRANGRP=@TRANGRP 
  
  DELETE FROM #TAXAMOUNT 
  INSERT INTO #TAXAMOUNT 
  SELECT LEDGERCODE,SUM(DEBIT-CREDIT) TAXAMOUNT 
  FROM TRANSACTIONS 
  WHERE TRANGRP = @TRANGRP  AND LEDGERCODE IN (SELECT LEDGERCODE FROM #GSTINPUT) GROUP BY LEDGERCODE 

  DELETE FROM #GSTTRANS 
  INSERT INTO #GSTTRANS
  SELECT DISTINCT  LEDGERCODE,PERC    FROM TAXTRANS  WHERE TRANSID BETWEEN @TRANSFROM AND @TRANSEND  
   
  INSERT INTO #CCNTEMP(TRANGRP,  CGST ) 
  SELECT @TRANGRP,   TAXAMOUNT FROM #TAXAMOUNT  WHERE LEDGERCODE='1310025'  
  
  SET @SGSTAMOUNT = 0
  SET @RCMSGSTAMOUNT = 0 

  SELECT @SGSTAMOUNT = TAXAMOUNT FROM #TAXAMOUNT WHERE LEDGERCODE='1310026'  
  UPDATE #CCNTEMP SET SGST = @SGSTAMOUNT  WHERE TRANGRP = @TRANGRP 

  SELECT @CGSTCOUNT = COUNT(*) FROM #GSTTRANS WHERE LEDGERCODE='1310025' 
  IF @CGSTCOUNT = 1
     BEGIN 
	   SELECT @CGSTPERC = PERC FROM #GSTTRANS WHERE LEDGERCODE='1310025' 
	   UPDATE #CCNTEMP SET CGSTRATE = @CGSTPERC,SGSTRATE = @CGSTPERC  WHERE   TRANGRP = @TRANGRP 
	 END

  INSERT INTO #CCNTEMP(TRANGRP, IGST ) 
  SELECT @TRANGRP,   TAXAMOUNT FROM #TAXAMOUNT  WHERE LEDGERCODE='1310027' 
  SELECT @IGSTCOUNT = COUNT(*) FROM #GSTTRANS WHERE LEDGERCODE='1310027' 
  IF @IGSTCOUNT = 1
     BEGIN 
	   SELECT @IGSTPERC = PERC FROM #GSTTRANS WHERE LEDGERCODE='1310027' 
	   UPDATE #CCNTEMP SET IGSTRATE = @IGSTPERC WHERE    TRANGRP = @TRANGRP 
	 END


  INSERT INTO #CCNTEMP(TRANGRP,  RCMCGST ) 
  SELECT @TRANGRP,   TAXAMOUNT FROM #TAXAMOUNT  WHERE LEDGERCODE='1310031'
  SELECT @RCMCGSTCOUNT = COUNT(*) FROM #GSTTRANS WHERE LEDGERCODE='1310031' 
  IF @RCMCGSTCOUNT = 1
     BEGIN 
	   SELECT @RCMCGSTRATE = PERC FROM #GSTTRANS WHERE LEDGERCODE='1310031' 
	   UPDATE #CCNTEMP SET RCMCGSTRATE  = @RCMCGSTRATE, RCMSGSTRATE  = @RCMCGSTRATE  WHERE    TRANGRP = @TRANGRP 
	 END
  SELECT @RCMSGSTAMOUNT = TAXAMOUNT FROM #TAXAMOUNT WHERE LEDGERCODE='1310032'  
  UPDATE #CCNTEMP SET RCMSGST = @RCMSGSTAMOUNT  WHERE TRANGRP = @TRANGRP 

  INSERT INTO #CCNTEMP(TRANGRP ,  RCMIGST ) 
  SELECT @TRANGRP,   TAXAMOUNT FROM #TAXAMOUNT  WHERE LEDGERCODE='1310033'
  SELECT @RCMIGSTCOUNT = COUNT(*) FROM #GSTTRANS WHERE LEDGERCODE='1310033' 
  IF @RCMIGSTCOUNT = 1
     BEGIN 
	   SELECT @RCMIGSTRATE = PERC FROM #GSTTRANS WHERE LEDGERCODE='1310033' 
	   UPDATE #CCNTEMP SET IGSTRATE = @RCMIGSTRATE WHERE    TRANGRP = @TRANGRP 
	 END

  UPDATE  #CCNTEMP 
  SET ORGID=T.ORGID,YEAR=T.YEAR,PERIOD=T.PERIOD,PDATE=T.PDATE,INVOICEDATE=T.RECEIVEDDATE,BATCHREF=T.BATCHREF,TRANSREF =T.TRANSREFEXT,TRANSID=T.TRANSID,
      CREDNO=T.CREDNO, TAXABLEVALUE = (T.CREDIT-T.DEBIT)  FROM TRANSACTIONS T  INNER JOIN #CCNTEMP ON #CCNTEMP.TRANGRP = T.TRANGRP  WHERE  T.LEDGERCODE ='1315000' 

  
  UPDATE #CCNTEMP 
   SET LEDGERCODE = T.LEDGERCODE,DESCRIPTION=T.DESCRIPTION FROM TRANSACTIONS T WHERE #CCNTEMP.TRANGRP = @TRANGRP AND T.TRANSID = @TRANSFROM
  
  UPDATE #CCNTEMP SET  CREDIT=0 WHERE CREDIT IS NULL AND TRANGRP = @TRANGRP 
  UPDATE #CCNTEMP SET  CGST=0 WHERE  CGST IS NULL AND TRANGRP = @TRANGRP 
  UPDATE #CCNTEMP SET  SGST=0 WHERE  SGST IS NULL  AND TRANGRP = @TRANGRP 
  UPDATE #CCNTEMP SET  IGST=0 WHERE  IGST IS NULL  AND TRANGRP = @TRANGRP 
  UPDATE #CCNTEMP SET  RCMCGST=0 WHERE  RCMCGST IS NULL  AND TRANGRP = @TRANGRP 
  UPDATE #CCNTEMP SET  RCMSGST=0 WHERE  RCMSGST IS NULL  AND TRANGRP = @TRANGRP 
  UPDATE #CCNTEMP SET  RCMIGST=0 WHERE  RCMIGST IS NULL  AND TRANGRP = @TRANGRP 
  
	UPDATE #CCNTEMP SET  CREDIT=0 WHERE CREDIT IS NULL 
	UPDATE #CCNTEMP SET  CGST=0 WHERE  CGST IS NULL
	UPDATE #CCNTEMP SET  SGST=0 WHERE  SGST IS NULL
	UPDATE #CCNTEMP SET  IGST=0 WHERE  IGST IS NULL
	UPDATE #CCNTEMP SET  RCMCGST=0 WHERE  RCMCGST IS NULL
	UPDATE #CCNTEMP SET  RCMSGST=0 WHERE  RCMSGST IS NULL
	UPDATE #CCNTEMP SET  RCMIGST=0 WHERE  RCMIGST IS NULL
	UPDATE #CCNTEMP SET  RCMCGSTRATE=0 WHERE RCMCGSTRATE IS NULL
	UPDATE #CCNTEMP SET  RCMIGSTRATE=0 WHERE RCMIGSTRATE IS NULL
	UPDATE #CCNTEMP SET CGSTRATE=RCMCGSTRATE , SGSTRATE=RCMSGSTRATE WHERE RCMCGSTRATE>0 
	UPDATE #CCNTEMP SET IGSTRATE = RCMIGSTRATE WHERE RCMIGSTRATE>0 

	INSERT INTO BI.PURCHASEHISTORY
	(ORGID,FINYEAR,PERIOD,TRANGRP,TRANSID,TRANSTYPE,INVOICENUMBER,TRANSACTIONDATE,SUPPCODE,ITEM,LEDGERCODE,BATCHREF,INVOICEDATE,
	TAXABLE_VALUE,CGST_RATE,CGST_AMOUNT,SGST_RATE,SGST_AMOUNT,IGST_RATE,IGST_AMOUNT,CGST_INPUT_RCM_AMOUNT,SGST_INPUT_RCM_AMOUNT,IGST_INPUT_RCM_AMOUNT,DOCTYPE)
	SELECT 
	 ORGID,YEAR,PERIOD,TRANGRP,TRANSID,'CCN',TRANSREF,PDATE,CREDNO,UPPER(DESCRIPTION),LEDGERCODE,BATCHREF,INVOICEDATE,
	 TAXABLEVALUE,CGSTRATE,CGST,SGSTRATE,SGST,IGSTRATE,IGST,RCMCGST,RCMSGST,RCMIGST,'CCN'
	FROM #CCNTEMP
	 
    DELETE FROM #CCNTEMP

  FETCH NEXT FROM CCNTRANGRP INTO @TRANGRP 
END


CLOSE CCNTRANGRP
DEALLOCATE CCNTRANGRP




 
  





 


----- FINAL OUTPUT 
UPDATE BI.PURCHASEHISTORY SET CGST_RATE =ABS(CGST_RATE),SGST_RATE=ABS(SGST_RATE), IGST_RATE=ABS(IGST_RATE) 
UPDATE BI.PURCHASEHISTORY SET LEDGERNAME = UPPER(L.LEDGERNAME) FROM LEDGERCODES L INNER JOIN BI.PURCHASEHISTORY BIP ON BIP.LEDGERCODE=L.LEDGERCODE 
UPDATE BI.PURCHASEHISTORY SET SUPPLIERCITY =LTRIM(RTRIM(STR(C.PROVINCEID))), SUPPLIERGSTN=C.ISOCERTIFICATION,SUPPLIERNAME=UPPER(C.CREDNAME)
FROM CREDITORS C INNER JOIN BI.PURCHASEHISTORY BIP ON BIP.SUPPCODE=C.CREDNUMBER 
UPDATE BI.PURCHASEHISTORY SET SUPPLIERCITY =LTRIM(RTRIM(STR(S.PROVINCEID))), SUPPLIERGSTN=S.ISOCERTIFICATION,SUPPLIERNAME=UPPER(S.SUBNAME)
FROM SUBCONTRACTORS  S INNER JOIN BI.PURCHASEHISTORY BIP ON BIP.SUPPCODE=S.SUBNUMBER 
UPDATE BI.PURCHASEHISTORY SET SUPPLIERCITY = UPPER(BIS.SHORTNAME) FROM BI.STATES BIS INNER JOIN BI.PURCHASEHISTORY BIP ON BIP.SUPPLIERCITY =BIS.PROVINCEID 
UPDATE BI.PURCHASEHISTORY SET SUPPLIERCITY =LTRIM(RTRIM(STR(D.PROVINCEID))), SUPPLIERGSTN=D.ISOCERTIFICATION,SUPPLIERNAME=UPPER(D.DEBTNAME)
FROM DEBTORS D INNER JOIN BI.PURCHASEHISTORY BIP ON BIP.SUPPCODE=D.DEBTNUMBER 
UPDATE BI.PURCHASEHISTORY SET SUPPLIERCITYNAME = UPPER(BIS.STATENAME) FROM BI.STATES BIS INNER JOIN BI.PURCHASEHISTORY BIP ON BIP.SUPPLIERCITY=BIS.SHORTNAME

UPDATE BI.PURCHASEHISTORY SET GST_EXPENSE =0 WHERE GST_EXPENSE IS NULL
UPDATE BI.PURCHASEHISTORY SET UOM='' WHERE UOM IS NULL
UPDATE BI.PURCHASEHISTORY SET QTY=0 WHERE QTY IS NULL
UPDATE BI.PURCHASEHISTORY SET RATE =0 WHERE RATE IS NULL
UPDATE BI.PURCHASEHISTORY SET ITEM= UPPER(ITEM) ,SUPPLIERNAME = UPPER(SUPPLIERNAME),SUPPLIERCITY =UPPER(SUPPLIERCITY),SUPPLIERCITYNAME = UPPER(SUPPLIERCITYNAME) 
UPDATE BI.PURCHASEHISTORY SET ORDERNO ='' WHERE ORDERNO IS NULL
UPDATE BI.PURCHASEHISTORY SET SUPPLIERNAME='',SUPPLIERGSTN='' , SUPPLIERCITY='',SUPPLIERCITYNAME='' WHERE SUPPLIERNAME IS NULL

UPDATE BI.PURCHASEHISTORY SET BORGNAME = B.BORGNAME , CILGSTIN = B.COMPREG FROM BORGS B INNER JOIN BI.PURCHASEHISTORY BIP ON BIP.ORGID=B.BORGID 
UPDATE BI.PURCHASEHISTORY SET DOCTYPE = TRANSTYPE 
UPDATE BI.PURCHASEHISTORY SET GSTTYPE = 'INPUT' WHERE ABS(CGST_AMOUNT) > 0 
UPDATE BI.PURCHASEHISTORY SET GSTTYPE = 'INPUT' WHERE ABS(IGST_AMOUNT) > 0 
UPDATE BI.PURCHASEHISTORY SET GSTTYPE = 'RCM' WHERE ABS(CGST_INPUT_RCM_AMOUNT) > 0 
UPDATE BI.PURCHASEHISTORY SET GSTTYPE = 'GST EXPENSE' WHERE ABS(GST_EXPENSE) > 0


UPDATE BI.PURCHASEHISTORY SET CGST_RATE = 2.5  WHERE CGST_RATE  BETWEEN 2 AND 3
UPDATE BI.PURCHASEHISTORY SET SGST_RATE = 2.5  WHERE SGST_RATE  BETWEEN 2 AND 3


UPDATE BI.PURCHASEHISTORY SET CGST_RATE = 6.0 WHERE CGST_RATE  BETWEEN 4 AND 8
UPDATE BI.PURCHASEHISTORY SET SGST_RATE = 6.0 WHERE SGST_RATE  BETWEEN 4 AND 8

UPDATE BI.PURCHASEHISTORY SET CGST_RATE = 9.0 WHERE CGST_RATE BETWEEN 7 AND 11
UPDATE BI.PURCHASEHISTORY SET SGST_RATE = 9.0 WHERE SGST_RATE BETWEEN 7 AND 11

UPDATE BI.PURCHASEHISTORY SET IGST_RATE =18.0 WHERE IGST_RATE BETWEEN 17 AND 19
UPDATE BI.PURCHASEHISTORY SET IGST_RATE = 18.0 WHERE IGST_RATE BETWEEN 17 AND 19

UPDATE BI.PURCHASEHISTORY SET PERIODNAME = P.PERIODDESC FROM PERIODMASTER P INNER JOIN BI.PURCHASEHISTORY BIP ON BIP.PERIOD = P.PERIODID 
 

UPDATE BI.PURCHASEHISTORY SET SUPPLIERGSTN=C.ISOCERTIFICATION FROM CREDITORS C INNER JOIN BI.PURCHASEHISTORY B ON B.SUPPCODE=C.CREDNUMBER 
UPDATE BI.PURCHASEHISTORY SET SUPPLIERGSTN=S.ISOCERTIFICATION FROM SUBCONTRACTORS S INNER JOIN BI.PURCHASEHISTORY B ON B.SUPPCODE=S.SUBNUMBER 
UPDATE BI.PURCHASEHISTORY SET SUPPLIERGSTN=D.ISOCERTIFICATION FROM DEBTORS D INNER JOIN BI.PURCHASEHISTORY B ON B.SUPPCODE=D.DEBTNUMBER 

update BI.PURCHASEHISTORY set TAXABLE_VALUE=0 where TAXABLE_VALUE is null
UPDATE BI.PURCHASEHISTORY SET CGST_RATE=0 WHERE CGST_RATE IS NULL
UPDATE BI.PURCHASEHISTORY SET SGST_RATE=0 WHERE SGST_RATE IS NULL
UPDATE BI.PURCHASEHISTORY SET IGST_RATE=0 WHERE IGST_RATE IS NULL
UPDATE BI.PURCHASEHISTORY SET CGST_INPUT_RCM_AMOUNT =0  WHERE CGST_INPUT_RCM_AMOUNT IS NULL
UPDATE BI.PURCHASEHISTORY SET CGST_OUTPUT_RCM_AMOUNT =0  WHERE CGST_OUTPUT_RCM_AMOUNT IS NULL
UPDATE BI.PURCHASEHISTORY SET SGST_OUTPUT_RCM_AMOUNT =0  WHERE SGST_OUTPUT_RCM_AMOUNT IS NULL
UPDATE BI.PURCHASEHISTORY SET SGST_INPUT_RCM_AMOUNT =0  WHERE SGST_INPUT_RCM_AMOUNT IS NULL
UPDATE BI.PURCHASEHISTORY SET IGST_INPUT_RCM_AMOUNT =0  WHERE IGST_INPUT_RCM_AMOUNT IS NULL
UPDATE BI.PURCHASEHISTORY SET IGST_OUTPUT_RCM_AMOUNT =0  WHERE IGST_OUTPUT_RCM_AMOUNT IS NULL

SELECT * FROM BI.PURCHASEHISTORY ORDER BY ORGID,PERIOD,TRANSTYPE 


 