/****** Object:  Procedure [BI].[spOppositeLedgerRegisterSubbie]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE [BI].[spOppositeLedgerRegisterSubbie] (@FROMYEAR INT,@FROMPERIOD INT,@TOYEAR INT,@TOPERIOD INT, @PARTYCODE  VARCHAR(25)  )
 --
As
 ---- @LISTORGIDS  LISTORGIDS READONLY,
DECLARE @RETAINED VARCHAR(10)
DECLARE @WIP VARCHAR(10)
DECLARE @CREDITOR_FROM VARCHAR(15)
DECLARE @CREDITOR_TO VARCHAR(15)
DECLARE @SUBCONTRACTOR_FROM VARCHAR(15)
DECLARE @SUBCONTRACTOR_TO VARCHAR(15)
DECLARE @DEBTOR_FROM VARCHAR(15)
DECLARE @DEBTOR_TO VARCHAR(15)


SELECT @CREDITOR_FROM = CONTROLFROMGL FROM CONTROLCODES WHERE CONTROLNAME='Creditors'    
SELECT @CREDITOR_TO = CONTROLTOGL FROM CONTROLCODES WHERE CONTROLNAME='Creditors' 

SELECT @SUBCONTRACTOR_FROM  = CONTROLFROMGL FROM CONTROLCODES WHERE CONTROLNAME='Sub Contractors'
SELECT @SUBCONTRACTOR_TO  = CONTROLTOGL FROM CONTROLCODES WHERE CONTROLNAME='Sub Contractors'

SELECT @DEBTOR_FROM = CONTROLFROMGL FROM CONTROLCODES WHERE CONTROLNAME='Debtors'                            
SELECT @DEBTOR_TO = CONTROLTOGL FROM CONTROLCODES WHERE CONTROLNAME='Debtors'   


SELECT @RETAINED = CONTROLFROMGL FROM CONTROLCODES WHERE CONTROLNAME='Retained Income'
SELECT @WIP = CONTROLFROMGL FROM CONTROLCODES WHERE CONTROLNAME='Work In Progress'

DECLARE @BANKSTART VARCHAR(15)
DECLARE @BANKEND VARCHAR(15)
SELECT  @BANKSTART=CONTROLFROMGL ,@BANKEND=CONTROLTOGL FROM CONTROLCODES WHERE CONTROLNAME='Bank' 


DECLARE @TGRP INT
DECLARE @CNT DECIMAL(18,5)
DECLARE @NEWTGP DECIMAL(18,2) 

 
DECLARE @ICLASTART VARCHAR(15)
DECLARE @ICLAEND VARCHAR(15)
SELECT ICGLCODE INTO #ICGLCODE FROM BORGS 
DELETE FROM #ICGLCODE WHERE ICGLCODE IS NULL

SELECT @ICLASTART=MIN(ICGLCODE) FROM #ICGLCODE
SELECT @ICLAEND =MAX(ICGLCODE) FROM #ICGLCODE

DECLARE @CONTRACTFIRST VARCHAR(15)
DECLARE @CONTRACTEND VARCHAR(15)
SELECT  @CONTRACTFIRST=MIN(LEDGERCODE) FROM LEDGERCODES WHERE LEDGERALLOC='Contracts' 
SELECT  @CONTRACTEND =MAX(LEDGERCODE) FROM LEDGERCODES WHERE LEDGERALLOC='Contracts' 

DECLARE @VATSTART VARCHAR(15)
DECLARE @VATEND VARCHAR(15)
SELECT  @VATSTART=CONTROLFROMGL,@VATEND=CONTROLTOGL FROM CONTROLCODES WHERE CONTROLNAME='Value Added Tax' 


 

CREATE TABLE #BORGS(ORGID INT)
INSERT INTO #BORGS  
SELECT BORGID FROM BORGS 

DELETE FROM #BORGS WHERE ORGID IS NULL


CREATE TABLE #TRANSGROUPS (TRANGRP INT,YEAR INT,PERIOD INT) 

INSERT INTO #TRANSGROUPS 
SELECT 
 DISTINCT T.TRANGRP,T.YEAR,T.PERIOD 
FROM 
 TRANSACTIONS T
WHERE 
 T.YEAR>=@FROMYEAR  AND T.YEAR<=@TOYEAR AND 
 T.ORGID IN (SELECT ORGID FROM #BORGS)  AND
 T.CREDNO = @PARTYCODE AND
 T.LEDGERCODE BETWEEN @CREDITOR_FROM AND @CREDITOR_TO

INSERT INTO #TRANSGROUPS 
SELECT 
 DISTINCT T.TRANGRP,T.YEAR,T.PERIOD 
FROM 
 TRANSACTIONS T
WHERE 
 T.YEAR>=@FROMYEAR  AND T.YEAR<=@TOYEAR AND 
 T.ORGID IN (SELECT ORGID FROM #BORGS)  AND
 T.CREDNO = @PARTYCODE AND
 T.LEDGERCODE BETWEEN @SUBCONTRACTOR_FROM AND @SUBCONTRACTOR_TO


INSERT INTO #TRANSGROUPS 
SELECT 
 DISTINCT T.TRANGRP,T.YEAR,T.PERIOD 
FROM 
 TRANSACTIONS T
WHERE 
 T.YEAR>=@FROMYEAR  AND T.YEAR<=@TOYEAR AND 
 T.ORGID IN (SELECT ORGID FROM #BORGS)  AND
 T.CREDNO = @PARTYCODE AND
 T.LEDGERCODE BETWEEN @DEBTOR_FROM AND @DEBTOR_TO
 
DELETE FROM #TRANSGROUPS WHERE YEAR=@FROMYEAR AND PERIOD<@FROMPERIOD 
DELETE FROM #TRANSGROUPS WHERE YEAR=@TOYEAR AND PERIOD>@TOPERIOD 
DELETE FROM #TRANSGROUPS WHERE PERIOD=0

 

CREATE TABLE #DUMMYTRANS(TRANGRP INT,TRANSID INT,ORGID INT, TRANSTYPE VARCHAR(3),YEAR INT, PERIOD INT,BATCHREF VARCHAR(10),PDATE DATETIME,TRANSREF VARCHAR(10),
LEDGERCODE VARCHAR(10),CREDNO VARCHAR(10),DEBIT DECIMAL(18,2),CREDIT DECIMAL(18,2),CURRENCY VARCHAR(15),HOMECURRAMOUNT  DECIMAL(18,2),CATEGORY VARCHAR(60)  ) 

CREATE TABLE #TEMP0(TRANGRP INT,TRANSID INT,ORGID INT, TRANSTYPE VARCHAR(3),YEAR INT, PERIOD INT,BATCHREF VARCHAR(10),PDATE DATETIME,TRANSREF VARCHAR(10),LEDGERCODE VARCHAR(10),CREDNO VARCHAR(10),
DEBIT DECIMAL(18,2),CREDIT DECIMAL(18,2),CATEGORY VARCHAR(60),LEDGERINDEX  CHAR(2) ) 


DECLARE @GROUPID INT 
DECLARE @HOWMANYDEBITS INT 
DECLARE @HOWMANYCREDITS INT 
DECLARE @HOWMANYBORGS INT 
DECLARE @DEBITORGID INT 
DECLARE @CREDITORGID INT

DECLARE @TRANSTYPE VARCHAR(15)

DECLARE TGROUP CURSOR FOR SELECT DISTINCT TRANGRP FROM #TRANSGROUPS 

OPEN TGROUP 
FETCH NEXT FROM TGROUP INTO @GROUPID

WHILE @@FETCH_STATUS = 0 
BEGIN
  
 
  INSERT INTO #DUMMYTRANS 
		SELECT TRANGRP,TRANSID,ORGID,LEFT(BATCHREF,3),YEAR,PERIOD,BATCHREF,PDATE,TRANSREF,LEDGERCODE,CREDNO,DEBIT,CREDIT,CURRENCY,HOMECURRAMOUNT,' '   
		FROM TRANSACTIONS 
  WHERE TRANGRP = @GROUPID ORDER BY LEDGERCODE
  
  DELETE FROM #DUMMYTRANS WHERE LEDGERCODE IN (@WIP,@RETAINED) 
 
  SELECT @TRANSTYPE=LEFT(BATCHREF,3) FROM #DUMMYTRANS  

  SET @HOWMANYBORGS=1
  SET @HOWMANYDEBITS=0
  SET @HOWMANYCREDITS=0

  SELECT @HOWMANYBORGS = COUNT(DISTINCT ORGID) FROM #DUMMYTRANS
  IF @HOWMANYBORGS >1 
     UPDATE #DUMMYTRANS SET CATEGORY=CATEGORY+' InterCompany'

  SELECT @HOWMANYDEBITS = COUNT(CREDNO) FROM #DUMMYTRANS WHERE  CREDNO<>@PARTYCODE   
  IF @HOWMANYDEBITS > 1
     UPDATE #DUMMYTRANS SET CATEGORY=CATEGORY+ ' Multiple Party'

  IF @TRANSTYPE IN ('JNL','WHT')
   BEGIN
     UPDATE #DUMMYTRANS SET CATEGORY = CATEGORY + ' Journal ' 
	 DELETE FROM #DUMMYTRANS WHERE CREDNO<>@PARTYCODE 
   END
 
 
  
  
  
  
  INSERT INTO #TEMP0(TRANGRP,TRANSID,ORGID,TRANSTYPE,YEAR,PERIOD,BATCHREF,PDATE,TRANSREF,LEDGERCODE,CREDNO,DEBIT,CREDIT,CATEGORY,LEDGERINDEX) 
  SELECT TRANGRP,TRANSID,ORGID,TRANSTYPE,YEAR,PERIOD,BATCHREF,PDATE,TRANSREF,LEDGERCODE,CREDNO,DEBIT,CREDIT,CATEGORY,0 FROM #DUMMYTRANS
  
  DELETE FROM #DUMMYTRANS

  FETCH NEXT FROM TGROUP INTO @GROUPID

END
CLOSE TGROUP
DEALLOCATE TGROUP 

 




UPDATE #TEMP0 SET LEDGERINDEX = 'B.'  WHERE LEDGERCODE BETWEEN @VATSTART AND @VATEND 

UPDATE #TEMP0 SET LEDGERINDEX = 'C.'  WHERE LEDGERCODE BETWEEN @BANKSTART AND @BANKEND

UPDATE #TEMP0 SET LEDGERINDEX = 'D.'  WHERE LEDGERCODE BETWEEN @ICLASTART AND @ICLAEND 
 


UPDATE #TEMP0 SET LEDGERINDEX = 'Z.'  WHERE LEDGERCODE BETWEEN @CONTRACTFIRST AND @CONTRACTEND
UPDATE #TEMP0 SET LEDGERINDEX = 'A.'  WHERE LEDGERCODE BETWEEN @CREDITOR_FROM AND @CREDITOR_TO 
UPDATE #TEMP0 SET LEDGERINDEX = 'A.'  WHERE LEDGERCODE BETWEEN @DEBTOR_FROM AND @DEBTOR_TO 
UPDATE #TEMP0 SET LEDGERINDEX = 'A.'  WHERE LEDGERCODE BETWEEN @SUBCONTRACTOR_FROM AND @SUBCONTRACTOR_TO
 

ALTER TABLE #TEMP0 ADD BORGNAME VARCHAR(200)
ALTER TABLE #TEMP0 ADD PERIODDESC VARCHAR(50)
ALTER TABLE #TEMP0 ADD SUPPLIERNAME VARCHAR(150)
ALTER TABLE #TEMP0 ADD LEDGERNAME VARCHAR(100)
UPDATE #TEMP0 SET LEDGERNAME = L.LEDGERNAME FROM LEDGERCODES L INNER JOIN #TEMP0 ON #TEMP0.LEDGERCODE =L.LEDGERCODE 
UPDATE #TEMP0 SET BORGNAME = B.BORGNAME FROM BORGS B INNER JOIN #TEMP0 ON #TEMP0.ORGID = B.BORGID 
UPDATE #TEMP0 SET PERIODDESC = P.PERIODDESC FROM PERIODMASTER P INNER JOIN #TEMP0 ON #TEMP0.PERIOD = P.PERIODID 
UPDATE #TEMP0 SET SUPPLIERNAME=C.CREDNAME FROM CREDITORS C INNER JOIN #TEMP0 ON #TEMP0.CREDNO=C.CREDNUMBER 
UPDATE #TEMP0 SET SUPPLIERNAME=D.DEBTNAME FROM DEBTORS D INNER JOIN #TEMP0 ON #TEMP0.CREDNO=D.DEBTNUMBER  
UPDATE #TEMP0 SET SUPPLIERNAME=S.SUBNAME FROM SUBCONTRACTORS S INNER JOIN #TEMP0 ON #TEMP0.CREDNO=S.SUBNUMBER 
  
 



 
DELETE FROM #TEMP0 WHERE BORGNAME='99999 - TEST BUDGET TOOL' 

 

SELECT 
   TRANGRP,
   TRANSID,
   CATEGORY,
   BORGNAME,
   YEAR,
   PERIODDESC,
   PDATE ,
   BATCHREF,
   TRANSREF,
   TRANSTYPE,
   CREDNO,
   SUPPLIERNAME AS PARTYNAME,
   LTRIM(RTRIM(LEDGERINDEX))+(LTRIM(RTRIM(LEDGERCODE))+'-'+LEFT(LEDGERNAME,25)) AS LEDGERNAME,
   (DEBIT-CREDIT) AMOUNT  
  
  INTO 
   #FINAL
  FROM 
   #TEMP0
  ORDER BY 
   TRANGRP,TRANSID,LEDGERINDEX 


UPDATE #FINAL SET LEDGERNAME = LTRIM(RTRIM(LEDGERNAME))

 
 
 
 

Exec [BI].[CrossTab] 'SELECT  TRANGRP,CATEGORY,BORGNAME,YEAR,PERIODDESC,PDATE,BATCHREF,TRANSREF,TRANSTYPE,CREDNO,PARTYNAME,LEDGERNAME,AMOUNT  FROM #FINAL', 'LEDGERNAME','SUM(AMOUNT ELSE 0)[]','TRANGRP,CATEGORY,BORGNAME,YEAR,PERIODDESC,PDATE,BATCHREF,TRANSREF,TRANSTYPE,CREDNO,PARTYNAME'

 
 