/****** Object:  Procedure [BI].[spOppositeLedgerRegisterMaster]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE [BI].[spOppositeLedgerRegisterMaster]
(@MASTERTYPE INT,@FROMYEAR INT,@FROMPERIOD INT,@TOYEAR INT,@TOPERIOD INT,@LISTCREDITORS  LISTCREDNUMBERS  READONLY, @LISTORGIDS  LISTORGIDS READONLY  )

As


DECLARE @RETAINED VARCHAR(10)
DECLARE @WIP VARCHAR(10)
DECLARE @CREDITOR_FROM VARCHAR(15)
DECLARE @CREDITOR_TO VARCHAR(15)
DECLARE @SUBCONTRACTOR_FROM VARCHAR(15)
DECLARE @SUBCONTRACTOR_TO VARCHAR(15)
DECLARE @DEBTOR_FROM VARCHAR(15)
DECLARE @DEBTOR_TO VARCHAR(15)
DECLARE @PARTYNAME VARCHAR(200)
DECLARE @PARTYCATEGORY CHAR(1)
DECLARE @PARTYCODE VARCHAR(15)

IF @MASTERTYPE=1
   SET @PARTYCATEGORY='C'
ELSE IF @MASTERTYPE=2
   SET @PARTYCATEGORY='S'
ELSE
   SET @PARTYCATEGORY='D'

SELECT @CREDITOR_FROM = CONTROLFROMGL FROM CONTROLCODES WHERE CONTROLNAME='Creditors'    
SELECT @CREDITOR_TO = CONTROLTOGL FROM CONTROLCODES WHERE CONTROLNAME='Creditors' 

SELECT @SUBCONTRACTOR_FROM  = CONTROLFROMGL FROM CONTROLCODES WHERE CONTROLNAME='Sub Contractors'
SELECT @SUBCONTRACTOR_TO  = CONTROLTOGL FROM CONTROLCODES WHERE CONTROLNAME='Sub Contractors'

SELECT @DEBTOR_FROM = CONTROLFROMGL FROM CONTROLCODES WHERE CONTROLNAME='Debtors'                            
SELECT @DEBTOR_TO = CONTROLTOGL FROM CONTROLCODES WHERE CONTROLNAME='Debtors'   


SELECT @RETAINED = CONTROLFROMGL FROM CONTROLCODES WHERE CONTROLNAME='Retained Income'
SELECT @WIP = CONTROLFROMGL FROM CONTROLCODES WHERE CONTROLNAME='Work In Progress'

 
CREATE TABLE #CREDITORS(CREDNUMBER VARCHAR(10),MASTERINDEX CHAR(1) )
INSERT INTO #CREDITORS( CREDNUMBER,MASTERINDEX)
SELECT CREDNUMBER,'C' FROM @LISTCREDITORS 
DELETE FROM #CREDITORS WHERE CREDNUMBER IS NULL 

UPDATE #CREDITORS SET MASTERINDEX='C' WHERE CREDNUMBER IN (SELECT CREDNUMBER FROM CREDITORS)
UPDATE #CREDITORS SET MASTERINDEX='S' WHERE CREDNUMBER IN (SELECT SUBNUMBER FROM SUBCONTRACTORS)
UPDATE #CREDITORS SET MASTERINDEX='D' WHERE CREDNUMBER IN (SELECT DEBTNUMBER FROM DEBTORS) 



CREATE TABLE #BORGS(ORGID INT)
INSERT INTO #BORGS 
SELECT ORGID  FROM @LISTORGIDS

DELETE FROM #BORGS WHERE ORGID IS NULL

  


CREATE TABLE #TRANSGROUPS (TRANGRP INT,YEAR INT,PERIOD INT) 
 

CREATE TABLE #TEMP0(
PARTYCATEGORY VARCHAR(15),PARTYCODE VARCHAR(15),PARTYNAME VARCHAR(200),
TRANGRP INT,TRANSID INT,ORGID INT,ORGNAME VARCHAR(150),TRANSTYPE VARCHAR(3),YEAR INT,PERIOD INT,
PDATE DATETIME,BATCHREF VARCHAR(10),TRANSREF VARCHAR(10),DESCRIPTION VARCHAR(255),LEDGERCODE VARCHAR(10),LEDGERNAME VARCHAR(250),
CREDNO VARCHAR(10),CREDNAME VARCHAR(200),
DEBIT DECIMAL(18,2),CREDIT DECIMAL(18,2),CURRENCY VARCHAR(15), HOMECURRAMOUNT DECIMAL(18,2) ) 


DECLARE MASTERLIST CURSOR FOR SELECT CREDNUMBER,MASTERINDEX  FROM #CREDITORS 
OPEN MASTERLIST 
FETCH NEXT FROM MASTERLIST INTO @PARTYCODE,@PARTYCATEGORY
WHILE @@FETCH_STATUS = 0 
BEGIN
      IF @PARTYCATEGORY ='C'
          BEGIN
           INSERT INTO #TRANSGROUPS 
	       SELECT 
			 DISTINCT T.TRANGRP,T.YEAR,T.PERIOD 
	       FROM 
			 TRANSACTIONS T
		   WHERE 
			 T.YEAR>=@FROMYEAR  AND T.YEAR<=@TOYEAR AND 
			 T.ORGID IN (SELECT ORGID FROM #BORGS)  AND
			 T.CREDNO =@PARTYCODE   AND
			 T.LEDGERCODE BETWEEN @CREDITOR_FROM AND @CREDITOR_TO
		  END 

       IF @PARTYCATEGORY = 'S'
          BEGIN 
    		INSERT INTO #TRANSGROUPS 
			SELECT 
			 DISTINCT T.TRANGRP,T.YEAR,T.PERIOD 
			FROM 
			 TRANSACTIONS T
			WHERE 
			 T.YEAR>=@FROMYEAR  AND T.YEAR<=@TOYEAR AND 
			 T.ORGID IN (SELECT ORGID FROM #BORGS)  AND
			 T.CREDNO =@PARTYCODE   AND
			 T.LEDGERCODE BETWEEN @SUBCONTRACTOR_FROM AND @SUBCONTRACTOR_TO
		  END

        IF @PARTYCATEGORY = 'D'
          BEGIN
 			   INSERT INTO #TRANSGROUPS 
				SELECT 
				 DISTINCT T.TRANGRP,T.YEAR,T.PERIOD 
				FROM 
				 TRANSACTIONS T
				WHERE 
					 T.YEAR>=@FROMYEAR  AND T.YEAR<=@TOYEAR AND 
					 T.ORGID IN (SELECT ORGID FROM #BORGS)  AND
					 T.CREDNO =@PARTYCODE   AND
					 T.LEDGERCODE BETWEEN @DEBTOR_FROM AND @DEBTOR_TO
		  END 


		DELETE FROM #TRANSGROUPS WHERE YEAR=@FROMYEAR AND PERIOD<@FROMPERIOD 
		DELETE FROM #TRANSGROUPS WHERE YEAR=@TOYEAR AND PERIOD>@TOPERIOD 
		DELETE FROM #TRANSGROUPS WHERE PERIOD=0








		IF @PARTYCATEGORY = 'C'
		   SELECT  @PARTYNAME =   CREDNAME FROM CREDITORS WHERE CREDNUMBER=@PARTYCODE 
		ELSE IF @PARTYCATEGORY= 'S'
		   SELECT @PARTYNAME = SUBNAME FROM SUBCONTRACTORS WHERE SUBNUMBER=@PARTYCODE 
		ELSE 
		   SELECT @PARTYNAME = DEBTNAME FROM DEBTORS WHERE DEBTNUMBER = @PARTYCODE 

		INSERT INTO #TEMP0 
		SELECT @PARTYCODE,@PARTYCODE,@PARTYNAME,
		TRANGRP,TRANSID,ORGID,SPACE(10),LEFT(BATCHREF,3),YEAR,PERIOD,
		PDATE,BATCHREF,TRANSREF,DESCRIPTION,LEDGERCODE,SPACE(10),
		CREDNO,SPACE(10),
		DEBIT,CREDIT,CURRENCY,HOMECURRAMOUNT 
		FROM TRANSACTIONS 
		WHERE TRANGRP IN (SELECT TRANGRP FROM #TRANSGROUPS)


		FETCH NEXT FROM MASTERLIST INTO @PARTYCODE ,@PARTYCATEGORY

END 
DELETE FROM #TEMP0 WHERE LEDGERCODE IN (@WIP,@RETAINED) 
DELETE FROM #TEMP0 WHERE PERIOD=0

UPDATE #TEMP0 SET CREDIT=HOMECURRAMOUNT WHERE CREDIT>0 AND CURRENCY <>'INR'
UPDATE #TEMP0 SET DEBIT=HOMECURRAMOUNT WHERE DEBIT>0 AND CURRENCY <>'INR'


UPDATE #TEMP0 SET ORGNAME=B.BORGNAME FROM BORGS B INNER JOIN #TEMP0 ON #TEMP0.ORGID = B.BORGID 
UPDATE #TEMP0 SET LEDGERNAME=L.LEDGERNAME FROM LEDGERCODES L INNER JOIN #TEMP0 ON #TEMP0.LEDGERCODE = L.LEDGERCODE 
UPDATE #TEMP0 SET CREDNAME = C.CREDNAME FROM CREDITORS C INNER JOIN #TEMP0 ON #TEMP0.CREDNO = C.CREDNUMBER 
UPDATE #TEMP0 SET CREDNAME = D.DEBTNAME FROM DEBTORS D INNER JOIN #TEMP0 ON #TEMP0.CREDNO = D.DEBTNUMBER
UPDATE #TEMP0 SET CREDNAME = S.SUBNAME  FROM SUBCONTRACTORS S INNER JOIN #TEMP0 ON #TEMP0.CREDNO = S.SUBNUMBER 
 
  
SELECT 
    PARTYCODE,
	PARTYNAME,
	TRANGRP,
	TRANSID,
	ORGID,
	ORGNAME,
	TRANSTYPE,
	YEAR,
	PERIOD,
	PDATE,
	BATCHREF,
	TRANSREF,
	DESCRIPTION,
	LEDGERCODE,
	LEDGERNAME,
	CREDNO SUBLEDGERCODE,
	CREDNAME SUBLEDGERNAME,
	DEBIT,
	CREDIT
FROM 
    #TEMP0 
ORDER BY 
    ORGID,TRANGRP
  
 

 

 
 
 
 