/****** Object:  Procedure [BI].[spPOSTDEPRECIATION]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE [BI].[spPOSTDEPRECIATION](@FINYEAR INT,@PERIOD INT,@OPPLEDGERCODE VARCHAR(10))
AS


-- ASSETTAXYEARS IS THE FIELD TO CONTROL STOPPING OF DEPRECIAITON FROM FURHTER 
-- ASSETTAXYEARS = 99 MEANS THIS ASSET NEED NOT BE DEPRECIATED FURHTER - FINAL POINT REACHED


-- FINAL POINT 
-- ASSET RESIDUAL VALUE <= ACCUMULATED DEPRECIATION  THEN FINAL POINT REACHED
-- ASSET RESIDUAL VALUE = ASSET PURCHASE VALUE - ASSET SALVAGE VALUE  ; 95 % OF ASSET PURCHASE PRICE AS 5 % IS SALAVAGE VALUE 
-- IN THE LAST MONTH , WE MAY HAVE TO PUT THE BALANCE AMOUNT IF ONE PORTION OF THIS MONTH DEPRECIAION IS MORE THAN THE DIFFERENCE

UPDATE ASSETS SET ASSETTAXYEARS = 0 
UPDATE ASSETS SET ASSETTAXYEARS = 99  WHERE ASSETBOOKVALUE <= ASSETSALVAGE AND ASSETPPRICE>0
UPDATE ASSETS SET ASSETTAXYEARS = 99  WHERE ASSETBOOKVALUE >= ASSETSALVAGE AND ASSETPPRICE<0



----


DECLARE @ASSETPOSTDATE DATETIME
DECLARE @LASTDEPTM DECIMAL(18,2)
DECLARE @ASSETNUMBER VARCHAR(15)
DECLARE @LASTDENUMBER INT
DECLARE @ASSETID INT 

DECLARE @BALANCEDEP DECIMAL(18,2)

-- TO CONTROL ITEMS TO EXCLUDE - WHICH ARE PURCHASED LATER THAN THE PERIOD END DATE 
DECLARE @STARTDATE DATETIME
DECLARE @ENDDATE DATETIME
DECLARE @STARTDATESTRING VARCHAR(15)
DECLARE @ENDDATESTRING   VARCHAR(15)
IF @PERIOD BETWEEN 1 AND 9 
     SET @STARTDATESTRING = '01/'+ LTRIM(RTRIM(STR(@PERIOD+3)))+'/'+LTRIM(RTRIM(STR(@FINYEAR-1))) 
  ELSE
     SET @STARTDATESTRING = '01/'+ LTRIM(RTRIM(STR(@PERIOD-9)))+ '/'+STR(@FINYEAR)
SELECT @STARTDATE = CONVERT(DATETIME,@STARTDATESTRING,103) 
SELECT @ENDDATE   = PEDATE FROM PERIODSETUP WHERE ORGID=2 AND YEAR=@FINYEAR AND PERIOD=@PERIOD 



UPDATE ASSETS 
	   SET LASTDEPTM=(ASSETPPRICE-ASSETSALVAGE)/ASSETPERIOD  
	   WHERE LASTDEPTM = 0 AND ASSETOPPCODE=@OPPLEDGERCODE

SELECT @ASSETPOSTDATE = PEDATE FROM PERIODSETUP WHERE ORGID=2 AND PERIOD=@PERIOD   AND YEAR=@FINYEAR 

 
 


DECLARE ASSETS CURSOR FOR
SELECT ASSETID,ASSETNUMBER,LASTDEPTM,ASSETDEPPROG FROM ASSETS 
WHERE  
 ASSETTAXYEARS <> 99  AND 
 ASSETOPPCODE=@OPPLEDGERCODE AND 
 ASSETID  NOT IN (SELECT ASSETID FROM [BI].[ASSETPOSTS] WHERE PERIOD=@PERIOD AND LEDGERCODE = @OPPLEDGERCODE AND YEAR = @FINYEAR  ) AND 
 ASSETPDATE < @ENDDATE  
  

OPEN ASSETS 
FETCH NEXT FROM ASSETS INTO @ASSETID,@ASSETNUMBER,@LASTDEPTM,@LASTDENUMBER  

WHILE @@FETCH_STATUS = 0
BEGIN
  
  SELECT @BALANCEDEP = (ASSETBOOKVALUE - ASSETSALVAGE  )  FROM ASSETS WHERE ASSETID = @ASSETID 
 

  IF (@BALANCEDEP < @LASTDEPTM ) AND (@BALANCEDEP>0)
      SET @LASTDEPTM = @BALANCEDEP 
  
  IF (@BALANCEDEP > @LASTDEPTM ) AND (@BALANCEDEP<0)
     SET @LASTDEPTM = @BALANCEDEP 

  
  SET @LASTDENUMBER = @LASTDENUMBER + 1 

  BEGIN TRAN
   INSERT INTO [BI].[ASSETPOSTS] (YEAR,PERIOD,ASSETID,ASSETNUMBER,LEDGERCODE,DEBIT,CURRNETCOUNT,BOOKINGDATE,DEPTYPE)
   VALUES (@FINYEAR,@PERIOD,@ASSETID,@ASSETNUMBER,@OPPLEDGERCODE,@LASTDEPTM,@LASTDENUMBER,@ASSETPOSTDATE,'SYSTEM')

   UPDATE ASSETS SET AssetBookValue = AssetBookValue-@LASTDEPTM,
                     AssetAccumDep =  AssetAccumDep+@LASTDEPTM, 
					 ASSETPOST=1, ASSETDEP=ASSETDEP+ 1,
					 ASSETDEPPROG= @LASTDENUMBER , 
					 ASSETLASTPOSTDATE  = @ASSETPOSTDATE 
					 WHERE ASSETID = @ASSETID 
   UPDATE ASSETS SET ASSETTAXYEARS = 99  WHERE ASSETBOOKVALUE <= ASSETSALVAGE AND ASSETPPRICE>0 AND  ASSETID=@ASSETID 
   UPDATE ASSETS SET ASSETTAXYEARS = 99  WHERE ASSETBOOKVALUE >= ASSETSALVAGE AND ASSETPPRICE<0 AND  ASSETID=@ASSETID 
   --UPDATE ASSETS SET ASSETTAXYEARS = 99  WHERE (AssetPPrice - AssetSale ) < AssetAccumDep AND  ASSETID=@ASSETID 

  COMMIT TRAN

  FETCH NEXT FROM ASSETS INTO @ASSETID,@ASSETNUMBER,@LASTDEPTM,@LASTDENUMBER  


END

CLOSE ASSETS
DEALLOCATE ASSETS 


Select 'Succes !!!!! ' AS RESULT




 