/****** Object:  Procedure [BI].[spPurchaseRegister]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE [BI].[spPurchaseRegister](@FINYEAR INT, @FROMPERIOD INT,@TOPERIOD INT, @LISTCREDITORS  LISTCREDNUMBERS  READONLY  ,@LISTORGIDS  LISTORGIDS READONLY   )
As
 --DECLARE @FINYEAR INT
 --DECLARE @FROMPERIOD INT
 --DECLARE @TOPERIOD INT

 --SET @FINYEAR=2017
 --SET @FROMPERIOD = 1
 --SET @TOPERIOD = 12

DECLARE @EXISTING INT
DECLARE @COLID INT
DECLARE @COLTEXT VARCHAR(60)
DECLARE @COLHEADTOSEARCH VARCHAR(30) 
DECLARE @COLHEADFOUND INT
DECLARE @VATCONTROL_FROM  VARCHAR(15)
DECLARE @VATCONTROL_TO    VARCHAR(15)
DECLARE @RETAINED VARCHAR(15)
DECLARE @WIP VARCHAR(15)
DECLARE @CREDITORCONTROL VARCHAR(15)
DECLARE @CREDITOR_LEDGER VARCHAR(15)
DECLARE @SUBBIE_LEDGER VARCHAR(15)
DECLARE @STOCK_FROM VARCHAR(15)
DECLARE @STOCK_TO VARCHAR(15)
DECLARE @LEDGERCODE VARCHAR(15)
DECLARE @LEDGERNAME VARCHAR(250)
DECLARE @COLUMHEADING   VARCHAR(250)
 
SELECT @CREDITOR_LEDGER = CONTROLFROMGL FROM CONTROLCODES WHERE CONTROLNAME='Creditors'
SELECT @SUBBIE_LEDGER = CONTROLFROMGL FROM CONTROLCODES WHERE CONTROLNAME = 'Sub Contractors'
SELECT @RETAINED = CONTROLFROMGL FROM CONTROLCODES WHERE CONTROLNAME='Retained Income'
SELECT @WIP = CONTROLFROMGL FROM CONTROLCODES WHERE CONTROLNAME='Work In Progress'
SELECT @VATCONTROL_FROM = CONTROLFROMGL FROM CONTROLCODES WHERE CONTROLNAME='Value Added Tax'
SELECT @VATCONTROL_TO = CONTROLTOGL FROM CONTROLCODES WHERE CONTROLNAME='Value Added Tax'
SELECT @STOCK_FROM =CONTROLFROMGL FROM CONTROLCODES WHERE CONTROLNAME='Stock'
SELECT @STOCK_TO  = CONTROLTOGL FROM CONTROLCODES WHERE CONTROLNAME='Stock'

--CREATE TABLE #CREDITORS(CREDNUMBER VARCHAR(10))
--INSERT INTO #CREDITORS
-- SELECT CREDNUMBER FROM @LISTCREDITORS 
--DELETE FROM #CREDITORS WHERE CREDNUMBER IS NULL 

CREATE TABLE #XPENSELEDGERS(LEDGERCODE VARCHAR(10),LEDGERNAME VARCHAR(50))

CREATE TABLE #TEMP0( TRANGRP INT, ORGID INT, BORGNAME VARCHAR(250),YEAR INT,  PERIOD INT, PERIODDESC VARCHAR(50), PDATE DATETIME, BATCHREF VARCHAR(50), TRANSREF VARCHAR(50),
                     LEDGERCODE VARCHAR(20), LEDGERNAME VARCHAR(250),CREDNO VARCHAR(20), PARTY VARCHAR(250),DEBIT DECIMAL(18,2),CREDIT DECIMAL(18,2) )

 
CREATE TABLE #BORGS(ORGID INT)
INSERT INTO #BORGS  
 SELECT ORGID  FROM @LISTORGIDS
DELETE FROM #BORGS WHERE ORGID IS NULL
 

DECLARE @START VARCHAR(20)
DECLARE @END   VARCHAR(20)
SELECT @START = CONTROLFROMGL FROM CONTROLCODES WHERE CONTROLNAME='Stock'
SELECT @END   = CONTROLTOGL   FROM CONTROLCODES WHERE CONTROLNAME='Stock'
CREATE TABLE #STORECODES ( LEDGERCODE VARCHAR(10) )
INSERT INTO #STORECODES SELECT LEDGERCODE FROM LEDGERCODES WHERE LEDGERCODE BETWEEN @START  AND @END
 
INSERT INTO #XPENSELEDGERS(LEDGERCODE,LEDGERNAME)
SELECT LEDGERCODE,'10.Inventory' FROM LEDGERCODES WHERE LEDGERCODE BETWEEN @START AND @END

INSERT INTO #XPENSELEDGERS(LEDGERCODE,LEDGERNAME)
SELECT LEDGERCODE,'11.VAT' FROM LEDGERCODES WHERE LEDGERCODE BETWEEN @VATCONTROL_FROM AND @VATCONTROL_TO


INSERT INTO #XPENSELEDGERS(LEDGERCODE,LEDGERNAME) VALUES ( '2513000', '12.Stock Adj')

INSERT INTO #XPENSELEDGERS(LEDGERCODE,LEDGERNAME) 
SELECT LEDGERCODE,'13.Expense' FROM LEDGERCODES WHERE LEDGERCODE IN ( SELECT LEDGERCODE FROM LEDGERCODES WHERE LEDGERALLOC='Contracts' ) 

INSERT INTO  #XPENSELEDGERS VALUES ( @CREDITOR_LEDGER, '15.Creditor');
INSERT INTO  #XPENSELEDGERS VALUES ( @SUBBIE_LEDGER, '15.Creditor') 

DECLARE POSTLEDGERS CURSOR FOR SELECT * FROM #XPENSELEDGERS  

SELECT 
 DISTINCT  T.TRANGRP , T.ORGID 
INTO 
 #TRANGRP 
FROM 
 TRANSACTIONS T 
WHERE 
 T.YEAR=@FINYEAR AND 
 T.PERIOD BETWEEN @FROMPERIOD AND @TOPERIOD AND 
 T.LEDGERCODE IN ( SELECT LEDGERCODE FROM #STORECODES ) AND
 T.ORGID IN (SELECT ORGID FROM #BORGS)  AND
 T.TRANSTYPE='DEL'
 
 

DECLARE @TGRP INT
DECLARE @TORGID INT
DECLARE @BORGNAME VARCHAR(150)

DECLARE OUTERLINK CURSOR FOR SELECT TRANGRP,ORGID FROM #TRANGRP
OPEN OUTERLINK

FETCH NEXT FROM OUTERLINK INTO @TGRP,@TORGID 

WHILE @@FETCH_STATUS = 0
BEGIN
  SELECT @BORGNAME = BORGNAME FROM BORGS WHERE BORGID = @TORGID 
  SELECT 
	 T.TRANGRP,
	 T.ORGID,
	 SPACE(150) BORGNAME,
	 T.YEAR,
	 T.PERIOD,
	 P.PERIODDESC,
	 T.PDATE,
	 T.BATCHREF,
	 T.TRANSREF,
	 T.LEDGERCODE,
	 SPACE(25) LEDGERNAME,
	 T.CREDNO,
	 BS.FNGETPARTY(T.CREDNO) SUBNAME  ,
	 SUM(T.DEBIT) DEBIT,
	 SUM(T.CREDIT) CREDIT
	INTO #TEMP2
	FROM
	 TRANSACTIONS T 
	 INNER JOIN PERIODMASTER P ON T.PERIOD=P.PERIODID 
	WHERE 
	 TRANGRP = @TGRP  AND 
	 T.LEDGERCODE NOT IN (@RETAINED,@WIP)   
	GROUP BY
	 T.TRANGRP,
	 T.ORGID,
	 T.YEAR,
	 T.PERIOD,
	 PERIODDESC,
	 PDATE,
	 BATCHREF,
	 TRANSREF,
	 LEDGERCODE,
	 CREDNO
	
    UPDATE #TEMP2 SET BORGNAME=@BORGNAME 
    UPDATE #TEMP2 SET LEDGERNAME='NA'

   
  
    
    DECLARE @POSTLEDGERCODE VARCHAR(10)
    DECLARE @POSTLEDGERNAME VARCHAR(15)

 

   
    OPEN POSTLEDGERS
	FETCH NEXT FROM POSTLEDGERS INTO @POSTLEDGERCODE ,@POSTLEDGERNAME 
	WHILE @@FETCH_STATUS = 0 
		BEGIN
			SELECT  @EXISTING = COUNT(*) FROM #TEMP2 WHERE LEDGERCODE=@POSTLEDGERCODE AND ORGID = @TORGID
			IF @EXISTING > 0 
			BEGIN
			    SELECT @COLHEADFOUND = COUNT(*) FROM #XPENSELEDGERS WHERE LEDGERCODE = @POSTLEDGERCODE 
			    IF (@COLHEADFOUND>0)
			      BEGIN
			       SELECT @COLHEADTOSEARCH = LEDGERNAME  FROM #XPENSELEDGERS WHERE LEDGERCODE = @POSTLEDGERCODE 
			       SET @COLTEXT = LTRIM(RTRIM(@COLHEADTOSEARCH))
			      END
			    ELSE
			      BEGIN
				     SET @COLID = @COLID+1 
			         SET @COLHEADTOSEARCH = LTRIM(RTRIM(STR(@COLID)))+'.'+@POSTLEDGERNAME
				     INSERT INTO #XPENSELEDGERS VALUES (@POSTLEDGERNAME,@COLHEADTOSEARCH)  
				     SET @COLTEXT =@COLHEADTOSEARCH
			      END  
			      UPDATE #TEMP2 SET LEDGERNAME = @COLTEXT WHERE LEDGERCODE=@POSTLEDGERCODE AND ORGID = @TORGID
			END
			FETCH NEXT FROM POSTLEDGERS INTO @POSTLEDGERCODE ,@POSTLEDGERNAME 
		END
	CLOSE POSTLEDGERS 
	SET @COLTEXT = '14.Others'
	UPDATE #TEMP2 SET LEDGERNAME = @COLTEXT WHERE LEDGERNAME='NA' AND ORGID = @TORGID
	
	DELETE FROM #TEMP2 WHERE LEDGERNAME='NA'
 
	INSERT INTO #TEMP0 
	SELECT * FROM #TEMP2

	DROP TABLE #TEMP2 

	FETCH NEXT FROM OUTERLINK INTO @TGRP,@TORGID 
END
	 

DEALLOCATE POSTLEDGERS 
CLOSE OUTERLINK
DEALLOCATE OUTERLINK




SELECT 
 TRANGRP      AS   TRANGRP,
 PARTY        AS   SUPPLIER,
 BORGNAME     AS   PROJECT,
 PERIOD       AS   PERIODID,
 PERIODDESC   AS   PERIOD,
 PDATE        AS   POSTDATE,
 BATCHREF     AS   BATCHREF,
 TRANSREF     AS   INVOICENO,
 LEDGERCODE   AS   LEDGERCODE,
 LEDGERNAME   AS   LEDGERNAME,
 SUM(DEBIT-CREDIT) AS AMOUNT 
INTO 
 #TEMP1
FROM
 #TEMP0 
GROUP BY
 TRANGRP,PARTY,BORGNAME,PERIOD,PERIODDESC,PDATE,BATCHREF,TRANSREF,LEDGERCODE,LEDGERNAME 
ORDER BY
 LEDGERCODE 




 
Exec [BI].[CrossTab]  'SELECT * FROM #TEMP1', 'LEDGERNAME','SUM(AMOUNT ELSE 0)[]','TRANGRP,SUPPLIER,PROJECT,PERIODID,PERIOD,BATCHREF,INVOICENO,POSTDATE' 




 
 
 

 