/****** Object:  Procedure [BI].[spPurchaseOrderRegister]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE [BI].[spPurchaseOrderRegister] 
(@STARTDATESTRING AS VARCHAR(15),@ENDDATESTRING AS VARCHAR(15) , @ORDSTATUSID INT  ,@LISTCREDITORS  LISTCREDNUMBERS  READONLY  ,@LISTORGIDS  LISTORGIDS READONLY )
AS
  
-- ,@LISTCREDITORS  LISTCREDNUMBERS  READONLY  ,@LISTORGIDS  LISTORGIDS READONLY
-- Order Status = 37 is Cancelled
-- Order Status = 500  Change Order Process
-- Order Status = 274  PO Ready
-- Order Status = 41   Completed


--declare @startdatestring varchar(15)
--declare @enddatestring varchar(15)
--set @startdatestring ='01-oct-2017'
--set @enddatestring ='05-oct-2017' 

--declare @ORDSTATUSID int
--set @ORDSTATUSID = 1


DECLARE @TRANSSTARTDATE    DATETIME
DECLARE @TRANSENDDATE      DATETIME
SELECT  @TRANSSTARTDATE = CONVERT(DATETIME, @STARTDATESTRING,103) -- dd/mm/yyyy 
SELECT  @TRANSENDDATE   = CONVERT(DATETIME, @ENDDATESTRING,103) -- dd/mm/yyyy 

CREATE TABLE #CREDITORS(CREDNUMBER VARCHAR(15))
INSERT INTO #CREDITORS  
--select crednumber from creditors 
SELECT CREDNUMBER FROM @LISTCREDITORS 
DELETE FROM #CREDITORS WHERE CREDNUMBER IS NULL 

CREATE TABLE #SUPPLIERS(SUPPID INT)
INSERT INTO  #SUPPLIERS
SELECT SUPPID FROM SUPPLIERS WHERE SUPPCODE IN  (SELECT CREDNUMBER FROM #CREDITORS) 

CREATE TABLE #BORGS(ORGID INT)
INSERT INTO #BORGS  
--select borgid from borgs 
SELECT ORGID  FROM @LISTORGIDS
DELETE FROM #BORGS WHERE ORGID IS NULL

CREATE TABLE #ORDSTATUS(ORDSTATUS INT)

IF @ORDSTATUSID=4
   BEGIN 
     -- ALL 
     INSERT INTO #ORDSTATUS VALUES(37)
	 INSERT INTO #ORDSTATUS VALUES(41)
	 INSERT INTO #ORDSTATUS VALUES(274)
	END

IF @ORDSTATUSID=1
  -- PO READY
  INSERT INTO #ORDSTATUS VALUES(274)

IF @ORDSTATUSID=2 
  -- COMPLETED
  INSERT INTO #ORDSTATUS VALUES(41)

IF @ORDSTATUSID=3
  -- CANCELLED
  INSERT INTO #ORDSTATUS VALUES(37)


SELECT 
 B.BORGNAME         PROJECT,
 O.ORDNUMBER        ORDERNUMBER,
 O.CREATEDATE       ORDERDATE,
 O.ORDSTATUSID      ORDSTATUSID,
 S.SUPPNAME         SUPPLIER,
 OI.STOCKID         STOCKID,
 I.STKCODE          STOCKCODE,
 I.STKDESC          STOCKNAME,
 SUBSTRING(OI.INSTRUCTIONS,1,50) INSTRUCTIONS,
 OI.ORDID           ORDID,
 OI.LINENUMBER      LINENUMBER,
 OI.UOM             UNIT,
 OI.QTY             QUANTITY,
 OI.PRICE           RATE,
 OI.DISCOUNT        DISCOUNT,
 OI.ITEMDESCRIPTION ITEMDESCRIPTION,
 (OI.QTY* ( OI.PRICE * (100-DISCOUNT)/100.00 ) )  AMOUNT
INTO #TEMP0
FROM 
 ORD O 
 INNER JOIN ORDITEMS OI ON O.ORDID = OI.ORDID 
 INNER JOIN BORGS     B ON O.BORGID=B.BORGID 
 INNER JOIN SUPPLIERS S ON O.SUPPID = S.SUPPID 
 LEFT OUTER  JOIN INVENTORY I ON OI.STOCKID = I.STKID 
WHERE
 CREATEDATE BETWEEN  @TRANSSTARTDATE AND @TRANSENDDATE AND
 B.BORGID IN (SELECT ORGID FROM #BORGS)  AND
 S.SUPPID  IN (SELECT SUPPID FROM #SUPPLIERS) 



-- FOREIGN EXCHANGE 
-- CONSIDERING FOREIGN EXCHANGE RATES 
SELECT
   ORDID,
   CURRENCY,
   EXCHRATE,
   HOMECURRENCY
INTO #TEMPFOREIGNEXCHANGE
FROM 
   ORD 
WHERE 
   CURRENCY<>'INR'

-- FE RATE MODIFICATIONS 
UPDATE #TEMP0 
  SET RATE = RATE * FE.EXCHRATE 
  FROM #TEMPFOREIGNEXCHANGE FE
  INNER JOIN #TEMP0 ON #TEMP0.ORDID = FE.ORDID 

UPDATE #TEMP0 
  SET AMOUNT = (QUANTITY  * ( RATE * (100-DISCOUNT)/100.00 ) )
 

--- FE ENDS HERE 








UPDATE #TEMP0 SET STOCKNAME = SUBSTRING(ITEMDESCRIPTION,1,250) WHERE STOCKID<=0 


ALTER  TABLE #TEMP0 ADD ORDERSTATUS VARCHAR(50)
UPDATE #TEMP0 SET ORDERSTATUS = 'Ready' WHERE ORDSTATUSID=274
UPDATE #TEMP0 SET ORDERSTATUS = 'Completed' WHERE ORDSTATUSID=41 
UPDATE #TEMP0 SET STOCKNAME = UPPER(STOCKNAME) ,PROJECT = UPPER(PROJECT) 

 


SELECT * INTO #TEMP1 FROM #TEMP0 WHERE 1=2


IF @ORDSTATUSID = 1 
   INSERT INTO #TEMP1 
   SELECT *   FROM #TEMP0 WHERE ORDSTATUSID=274
ELSE 
  IF @ORDSTATUSID = 2
        INSERT INTO #TEMP1 
        SELECT *   FROM #TEMP0 WHERE ORDSTATUSID=41
  ELSE IF @ORDSTATUSID=3 
        INSERT INTO #TEMP1 
		SELECT * FROM #TEMP0 WHERE ORDSTATUSID=37
	   ELSE
	      INSERT INTO #TEMP1 
		  SELECT * FROM #TEMP0 



 

SELECT ORDID,ORDITEMLINENO,SUM(DLVRQTY) DLVRQTY 
INTO #DELIVERIES
FROM DELIVERIES 
GROUP BY ORDID,ORDITEMLINENO 

ALTER TABLE #TEMP1 ADD DLVRQTY DECIMAL(18,4)
UPDATE #TEMP1 SET DLVRQTY=0

UPDATE #TEMP1 SET DLVRQTY = D.DLVRQTY 
FROM #DELIVERIES D
LEFT OUTER  JOIN #TEMP1 ON #TEMP1.ORDID=D.ORDID AND #TEMP1.LINENUMBER = D.ORDITEMLINENO 



SELECT SUPPLIER,ORDERNUMBER,ORDERDATE,PROJECT,STOCKCODE,STOCKNAME,UNIT,QUANTITY,RATE,DISCOUNT,AMOUNT,INSTRUCTIONS,DLVRQTY  FROM #TEMP1   
ORDER BY SUPPLIER,PROJECT 