/****** Object:  Procedure [BI].[spRequisitionRegister]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE  PROCEDURE [BI].[spRequisitionRegister] (@STARTDATESTRING AS VARCHAR(15),@ENDDATESTRING AS VARCHAR(15), @LISTORGIDS  LISTORGIDS READONLY) 
AS


CREATE TABLE #BORGS(ORGID INT)
INSERT INTO #BORGS 
SELECT ORGID  FROM @LISTORGIDS
DELETE FROM #BORGS WHERE ORGID IS NULL

 

-- REQ STATUS  32 Awaiting Approval, 36 Cancelled  163 Open  173 PO Created  202 Rejected  500 Change Order Process  501 Change Order Created.

DECLARE @TRANSSTARTDATE    DATETIME
DECLARE @TRANSENDDATE      DATETIME
SELECT  @TRANSSTARTDATE = CONVERT(DATETIME, @STARTDATESTRING,103) -- dd/mm/yyyy 
SELECT  @TRANSENDDATE   = CONVERT(DATETIME, @ENDDATESTRING,103) -- dd/mm/yyyy 
 



SELECT 
 R.REQID            REQID,
 R.BORGID           BORGID,
 R.REQNUMBER        REQNUMBER,
 R.REQSUBJECT       REQSUBJECT,
 R.SHORTDESCR       SHORTDESCR,
 R.REQSTATUSID      REQSTATUSID,
 R.CREATEDATE       CREATED 
INTO #REQMASTER 
FROM REQ R
WHERE R.BORGID IN (SELECT ORGID FROM #BORGS) AND  
      CONVERT(DATE,R.CREATEDATE ) BETWEEN @TRANSSTARTDATE AND @TRANSENDDATE 
ALTER TABLE #REQMASTER ADD PROJECT VARCHAR(200)
UPDATE #REQMASTER SET PROJECT = B.BORGNAME  FROM BORGS B INNER JOIN #REQMASTER ON #REQMASTER.BORGID = B.BORGID 
 
 

SELECT 
 RI.REQID           REQID,
 RI.SUPPID          SUPPID,
 RI.LINENUMBER      LINENUMBER,
 RI.ITEMDESCRIPTION ITEMDESCRIPTION,
 RI.BUYERPARTNUMBER STOCKID,
 RI.UOM             UNIT,
 RI.QTY             QTY,
 RI.PRICE           PRICE,
 RI.DISCOUNT        DISCOUNT,
 RI.SUPPID          SUPPLIERID,
 SUBSTRING(RI.INSTRUCTIONS,1,50) INSTRUCTIONS,
 (RI.QTY* ( RI.PRICE * (100-DISCOUNT)/100.00 ) )  AMOUNT,
 RI.GLCODEID        GLCODEID 
INTO #REQDETAILS 
FROM 
 REQITEMS RI 
WHERE 
 REQID IN (SELECT REQID FROM #REQMASTER) 

ALTER TABLE #REQDETAILS ADD SUPPCODE VARCHAR(15)
ALTER TABLE #REQDETAILS ADD SUPPLIER  VARCHAR(150)
UPDATE #REQDETAILS SET SUPPCODE=S.SUPPCODE, SUPPLIER=S.SUPPNAME FROM SUPPLIERS S INNER JOIN #REQDETAILS R ON R.SUPPID = S.SUPPID 

ALTER TABLE #REQDETAILS ADD LEDGERCODE VARCHAR(15)
ALTER TABLE #REQDETAILS ADD LEDGERNAME VARCHAR(100)
UPDATE #REQDETAILS SET LEDGERCODE = L.LEDGERCODE ,LEDGERNAME=L.LEDGERNAME FROM LEDGERCODES L INNER JOIN #REQDETAILS R ON R.GLCODEID=L.LedgerID 



SELECT 
              M.REQID REQID ,
              BORGID,
              PROJECT,
              SUPPCODE,
              SUPPLIER,
              REQNUMBER,
              REQSUBJECT,
              SHORTDESCR,
              REQSTATUSID,
              CREATED,
              LINENUMBER,
              ITEMDESCRIPTION,
              STOCKID,
              UNIT,
              QTY,
              PRICE,
              DISCOUNT,
              SUPPLIERID,
              INSTRUCTIONS,
              AMOUNT,
              LEDGERCODE,
              LEDGERNAME
INTO #TEMP0
FROM #REQMASTER M INNER JOIN #REQDETAILS D ON M.REQID  = D.REQID  

  
 
 
ALTER TABLE #TEMP0 ADD APPROVERNAME VARCHAR(50)
UPDATE #TEMP0 SET APPROVERNAME=SPACE(50) 

SELECT REQID,APPROVER 
INTO #APPROVER
FROM REQ WHERE REQID IN (SELECT REQID FROM #TEMP0 WHERE REQSTATUSID=32) 

ALTER TABLE #APPROVER ADD APPROVERNAME VARCHAR(100)
UPDATE #APPROVER SET APPROVERNAME=U.USERNAME FROM USERS U INNER JOIN #APPROVER ON #APPROVER.APPROVER = U.USERID 



UPDATE  #TEMP0 SET APPROVERNAME=SPACE(50) 
UPDATE #TEMP0 SET APPROVERNAME = A.APPROVERNAME FROM #APPROVER A INNER JOIN #TEMP0 ON #TEMP0.REQID = A.REQID 


 
 


ALTER  TABLE #TEMP0 ADD ORDERSTATUS VARCHAR(25)

UPDATE #TEMP0 SET ORDERSTATUS = 'Awaiting Approval' WHERE REQSTATUSID=32
UPDATE #TEMP0 SET ORDERSTATUS = 'Cancelled' WHERE REQSTATUSID=36
UPDATE #TEMP0 SET ORDERSTATUS = 'Open' WHERE REQSTATUSID=163
UPDATE #TEMP0 SET ORDERSTATUS = 'PO Created' WHERE REQSTATUSID=173
UPDATE #TEMP0 SET ORDERSTATUS = 'Rejected' WHERE REQSTATUSID=202
UPDATE #TEMP0 SET ORDERSTATUS = 'Change Order' WHERE REQSTATUSID=500
UPDATE #TEMP0 SET ORDERSTATUS = 'Change Order Done' WHERE REQSTATUSID=501

UPDATE #TEMP0 SET APPROVERNAME='' WHERE REQSTATUSID<>32 
			  
SELECT ORDERSTATUS,APPROVERNAME,SUPPCODE,SUPPLIER,PROJECT,REQNUMBER,REQSUBJECT,SHORTDESCR,CREATED,LINENUMBER,ITEMDESCRIPTION,STOCKID,UNIT,QTY,PRICE,DISCOUNT, AMOUNT,LEDGERCODE,LEDGERNAME  FROM #TEMP0
ORDER BY ORDERSTATUS,PROJECT,SUPPCODE,REQNUMBER 


 