/****** Object:  Procedure [BI].[spStockOfADay]    Committed by VersionSQL https://www.versionsql.com ******/

 CREATE procedure [BI].[spStockOfADay](@CUTOFFDATE AS VARCHAR(15) , @LISTINVENTORY   LISTSTOCKITEMS READONLY , @LISTORGIDS  LISTORGIDS READONLY)
AS

CREATE TABLE #FINALAGING ( STKSTORE VARCHAR(25), STKCODE VARCHAR(15), STKDESC VARCHAR(250), STKUNIT VARCHAR(15), 
							OB_0_QTY DECIMAL(18,2),OB_O_VALUE DECIMAL(18,2)  )



CREATE TABLE #IPLA(LEDGERCODE VARCHAR(10))
INSERT INTO #IPLA 
SELECT ICGLCODE  FROM BORGS 
DELETE FROM #IPLA WHERE LEDGERCODE IS NULL

 

CREATE TABLE #STOCKS(STOCKCODE  VARCHAR(15))
INSERT INTO  #STOCKS  
SELECT STOCKNO FROM @LISTINVENTORY
DELETE FROM #STOCKS WHERE STOCKCODE IS NULL 

 
CREATE TABLE #BORGS(ORGID INT)
INSERT INTO #BORGS   
SELECT ORGID  FROM @LISTORGIDS
DELETE FROM #BORGS WHERE ORGID IS NULL





DECLARE @CUTDATE DATETIME
SELECT  @CUTDATE = CONVERT(DATETIME, @CUTOFFDATE,103)

DECLARE @YEAR INT
DECLARE @MONTH INT
DECLARE @FINYEAR INT
DECLARE @CUTOFFINYEAR INT 

DECLARE @PERIODSTART DATETIME
DECLARE @PERIODEND   DATETIME
DECLARE @DATESTRING VARCHAR(15)
DECLARE @YEARBEGIN DATETIME
DECLARE @YEAREND   DATETIME 

SELECT @YEAR = YEAR(@CUTDATE) 
SELECT @MONTH = MONTH(@CUTDATE)

SET @DATESTRING = '01/01/'+LTRIM(RTRIM(@YEAR)) 

SELECT @YEARBEGIN = CONVERT(DATETIME, @DATESTRING, 103) 
SET @DATESTRING = '31/03/'+LTRIM(RTRIM(@YEAR)) 
SELECT @YEAREND   = CONVERT(DATETIME ,@DATESTRING,103)


IF @CUTDATE>=@YEARBEGIN AND @CUTDATE<=@YEAREND 
   SET @CUTOFFINYEAR = @YEAR
ELSE
   SET @CUTOFFINYEAR = @YEAR+1

 

CREATE TABLE #STORES(STORECODE VARCHAR(15))
INSERT INTO #STORES 
SELECT DISTINCT STKSTORE FROM INVENTORY WHERE BORGID IN (SELECT ORGID FROM #BORGS)  AND LEFT(STKSTORE,4)='MS-9'


DECLARE @STORECODE VARCHAR(15)

-- GET THE LIVE STOCK

DECLARE LISTOFSTORES CURSOR FOR SELECT STORECODE FROM #STORES 
OPEN LISTOFSTORES 
FETCH NEXT FROM LISTOFSTORES INTO @STORECODE 

WHILE @@FETCH_STATUS = 0 
BEGIN
	    IF OBJECT_ID('tempdb..#TEMP0') IS NOT NULL DROP TABLE   #TEMP0 

		SELECT STKSTORE,STKCODE,STKDESC,STKUNIT,ISNULL(STKQUANTITY,0) LIVESTOCK ,ISNULL(STKCOSTRATE,0) STKCOSTRATE ,ISNULL( (STKQUANTITY*STKCOSTRATE),0 )  LIVESTOCKVALUE, STKID,BORGID
		INTO #TEMP0 
		FROM INVENTORY 
		WHERE STKSTORE = @STORECODE   AND STKCODE IN (SELECT STOCKCODE FROM #STOCKS) 

		--SELECT * FROM #TEMP0 
 
 
		-- GET ALL XFRS 
		IF OBJECT_ID('tempdb..#TEMPXFR') IS NOT NULL DROP TABLE   #TEMPXFR
		SELECT STORE,STOCKNO,QUANTITY,UNIT,RATE,DEBIT,CREDIT,ORGID  
		INTO #TEMPXFR
		FROM TRANSACTIONS 
		WHERE 
		PDATE >@CUTDATE AND 
			  STORE = @STORECODE  AND 
			  STOCKNO IN (SELECT STOCKCODE FROM #STOCKS) AND 
			  ORGID IN (SELECT ORGID FROM #BORGS)  AND
			  TRANSTYPE = 'XFR' AND 
			  LEDGERCODE NOT IN (SELECT LEDGERCODE FROM #IPLA) 

        IF OBJECT_ID('tempdb..#XFRPLUS') IS NOT NULL DROP TABLE   #XFRPLUS
   		SELECT ORGID,STORE,STOCKNO,SUM(QUANTITY) PLUSQTY ,SUM(DEBIT) PLUSVALUE INTO #XFRPLUS FROM #TEMPXFR WHERE QUANTITY>0  GROUP BY ORGID,STORE,STOCKNO
 
        IF OBJECT_ID('tempdb..#XFRMINUS') IS NOT NULL DROP TABLE   #XFRMINUS  
		SELECT ORGID,STORE,STOCKNO,SUM(QUANTITY) MINUSQTY, SUM(CREDIT) MINUSVALUE INTO #XFRMINUS FROM #TEMPXFR WHERE QUANTITY<0 GROUP BY ORGID,STORE,STOCKNO 
 

		ALTER TABLE #XFRPLUS ADD STKID INT 
		ALTER TABLE #XFRMINUS ADD STKID INT 
		UPDATE #XFRPLUS  SET STKID = INV.STKID FROM INVENTORY INV INNER JOIN #XFRPLUS ON #XFRPLUS.STOCKNO = INV.STKCODE  AND #XFRPLUS.STORE = INV.STKSTORE  
		UPDATE #XFRMINUS SET STKID = INV.STKID FROM INVENTORY INV INNER JOIN #XFRPLUS ON #XFRPLUS.STOCKNO = INV.STKCODE  AND #XFRPLUS.STORE = INV.STKSTORE  
 
 


		--GET ALL THE DELIVERIES 
		IF OBJECT_ID('tempdb..#TEMPDELIVERY') IS NOT NULL DROP TABLE   #TEMPDELIVERY
		 
		SELECT  DLVRQTY,DLVRDATE,ORDID,ORDITEMLINENO,TBORGID,PRICE,(DLVRQTY*PRICE) DLVRAMOUNT
		INTO #TEMPDELIVERY 
		FROM DELIVERIES
		WHERE TBORGID IN (SELECT ORGID FROM #BORGS) 

 

		ALTER TABLE #TEMPDELIVERY ADD STKID INT
		UPDATE #TEMPDELIVERY SET STKID=OI.STOCKID FROM ORDITEMS OI INNER JOIN #TEMPDELIVERY T ON T.ORDID=OI.ORDID AND T.ORDITEMLINENO=OI.LINENUMBER
		ALTER TABLE #TEMPDELIVERY ADD STOCKCODE VARCHAR(15)
		UPDATE #TEMPDELIVERY SET STOCKCODE = OI.BUYERPARTNUMBER  FROM ORDITEMS OI INNER JOIN #TEMPDELIVERY T ON T.ORDID= OI.ORDID AND T.ORDITEMLINENO = OI.LINENUMBER 
		DELETE FROM #TEMPDELIVERY WHERE STKID=-1
		DELETE FROM #TEMPDELIVERY	WHERE STOCKCODE NOT IN (SELECT  STOCKCODE FROM #STOCKS) 


		INSERT INTO #TEMPDELIVERY(DLVRQTY,TBORGID,DLVRAMOUNT,STKID,STOCKCODE,DLVRDATE,ORDID,ORDITEMLINENO,PRICE) 
		SELECT PLUSQTY,ORGID,PLUSVALUE,STKID,STOCKNO,GETDATE(),0,0,0 FROM #XFRPLUS


      
		--GET SUM OF DELIVERIES HAPPENED BETWEEN CUTOFF DATE AND CURRENT DATE
		IF OBJECT_ID('tempdb..#PERIODDELIVERY') IS NOT NULL DROP TABLE   #PERIODDELIVERY
	
		SELECT STKID,SUM(DLVRQTY) DELIVERYQTY,SUM(DLVRAMOUNT) DELIVERYAMOUNT 
		INTO #PERIODDELIVERY
		FROM #TEMPDELIVERY
		WHERE DLVRDATE >@CUTDATE 
		GROUP BY STKID 

 



		ALTER TABLE #TEMP0  ADD PERIODDELIVERY DECIMAL(18,2) 
		ALTER TABLE #TEMP0  ADD PERIODAMOUNT   DECIMAL(18,2)
		UPDATE #TEMP0 SET PERIODDELIVERY=0.0, PERIODAMOUNT = 0.0
		UPDATE #TEMP0 SET PERIODDELIVERY = P.DELIVERYQTY, PERIODAMOUNT = P.DELIVERYAMOUNT  
		FROM #PERIODDELIVERY P INNER JOIN #TEMP0 ON #TEMP0.STKID = P.STKID


 


		-- INCORPORATING XFR INTO ISSUE
		UPDATE #PERIODDELIVERY 
		SET DELIVERYQTY	= DELIVERYQTY	+ X.PLUSQTY , DELIVERYAMOUNT= DELIVERYAMOUNT+X.PLUSVALUE 
		FROM #PERIODDELIVERY INNER JOIN #XFRPLUS X ON X.STKID = #PERIODDELIVERY.STKID 


 

		-- GET STOCK ISSUE BETWEEN CUTOFFDATE AND LIVE DATE 
		IF OBJECT_ID('tempdb..#PERIODISSUE') IS NOT NULL DROP TABLE   #PERIODISSUE
	
		SELECT ORGID,STOCKNO,QUANTITY ,(CREDIT-DEBIT) AMOUNT
		INTO #PERIODISSUE
		FROM TRANSACTIONS 
		WHERE ORGID IN (SELECT  ORGID FROM #BORGS)  AND LEFT(TRANSTYPE,3) IN ('SIC','SSR') AND STORE = @STORECODE 
		AND PDATE>@CUTDATE  AND YEAR>=@CUTOFFINYEAR AND ALLOCATION='Balance Sheet' AND LEDGERCODE <> '2990000' AND STOCKNO IN (SELECT STOCKCODE FROM #STOCKS)
 

		INSERT INTO #PERIODISSUE(ORGID,STOCKNO,QUANTITY,AMOUNT) 
		SELECT  ORGID, STOCKNO, MINUSQTY ,MINUSVALUE     FROM #XFRMINUS

 
        IF OBJECT_ID('tempdb..#ISSUEDETAILS') IS NOT NULL DROP TABLE   #ISSUEDETAILS
		SELECT ORGID,STOCKNO,SUM(QUANTITY) ISSUEQTY,SUM(AMOUNT) ISSUEAMOUNT 
		INTO  #ISSUEDETAILS
		FROM #PERIODISSUE 
		GROUP BY STOCKNO,ORGID 

 


		ALTER TABLE #TEMP0 ADD PERIODISSUE DECIMAL(18,2)
		ALTER TABLE #TEMP0 ADD ISSUEAMOUNT DECIMAL(18,2) 
		UPDATE #TEMP0 SET PERIODISSUE = 0.0 ,ISSUEAMOUNT = 0.0

		UPDATE #TEMP0 SET PERIODISSUE = ABS(P.ISSUEQTY) ,ISSUEAMOUNT =ABS(P.ISSUEAMOUNT) FROM #ISSUEDETAILS P INNER JOIN #TEMP0 ON #TEMP0.STKCODE = P.STOCKNO 

		ALTER TABLE #PERIODISSUE ADD STKID INT

		UPDATE #PERIODISSUE SET STKID = INV.STKID FROM INVENTORY INV INNER JOIN #PERIODISSUE ON #PERIODISSUE.OrgID = INV.BORGID AND #PERIODISSUE.Stockno=INV.STKCODE 
 
 


 
		-- OBQTY is the Opening Quantity as on the Cut off Date 

		ALTER TABLE #TEMP0 ADD OB_0_QTY   DECIMAL(18,2)
		ALTER TABLE #TEMP0 ADD OB_0_VALUE DECIMAL(18,2) 

		UPDATE #TEMP0 SET OB_0_QTY=0.0,OB_0_VALUE = 0.0
		UPDATE #TEMP0 SET OB_0_QTY = LIVESTOCK-PERIODDELIVERY+PERIODISSUE  , OB_0_VALUE = LIVESTOCKVALUE-PERIODAMOUNT+ISSUEAMOUNT 


        IF OBJECT_ID('tempdb..#TEMP1') IS NOT NULL DROP TABLE   #TEMP1
    
		SELECT * 
		INTO #TEMP1 
		FROM #TEMP0 
		WHERE OB_0_QTY>0


		DELETE FROM #TEMPDELIVERY WHERE DLVRDATE >=@CUTDATE 



	
 

		-- Final Bucket 
        INSERT INTO #FINALAGING
		SELECT 
		 STKSTORE,STKCODE,STKDESC,STKUNIT,OB_0_QTY,OB_0_VALUE 
		FROM 
		 #TEMP1 


         FETCH NEXT FROM LISTOFSTORES INTO @STORECODE 
END
CLOSE LISTOFSTORES
DEALLOCATE LISTOFSTORES 
SELECT * FROM #FINALAGING

 