/****** Object:  Procedure [BI].[spStoreLedgerSummary]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE [BI].[spStoreLedgerSummary]
AS

DECLARE @CURRENTFINYEAR INT
DECLARE @STORECODE VARCHAR(15)
DECLARE @STOCKVALUE DECIMAL(18,2)
DECLARE @LEDGERCODE VARCHAR(10)
DECLARE @LEDGERVALUE DECIMAL(18,2)

SELECT @CURRENTFINYEAR = CURRENTYEAR  FROM BORGS WHERE BORGID=2 

SELECT 
 STORECODE,STORENAME,STKCTL 
 INTO #TEMP0 
 FROM INVSTORES 
 WHERE LEFT(STORECODE,4)='MS-9' 
 ORDER BY STORECODE 

ALTER TABLE #TEMP0 ADD STOCKVALUE DECIMAL(18,2)
ALTER TABLE #TEMP0 ADD LEDGERVALUE DECIMAL(18,2)


DECLARE STORES CURSOR FOR SELECT STORECODE,STKCTL FROM #TEMP0 
OPEN STORES

FETCH NEXT FROM STORES INTO @STORECODE,@LEDGERCODE 

WHILE @@FETCH_STATUS=0 
BEGIN

  SELECT @STOCKVALUE = SUM ( STKQUANTITY * STKCOSTRATE ) FROM INVENTORY WHERE STKSTORE=@STORECODE 
  SELECT @LEDGERVALUE = SUM(DEBIT-CREDIT) FROM TRANSACTIONS WHERE YEAR=@CURRENTFINYEAR AND LEDGERCODE=@LEDGERCODE 
  UPDATE #TEMP0 SET STOCKVALUE = @STOCKVALUE,LEDGERVALUE = @LEDGERVALUE WHERE STORECODE = @STORECODE 

  FETCH NEXT FROM STORES INTO @STORECODE,@LEDGERCODE
END
CLOSE STORES
DEALLOCATE STORES

SELECT * FROM #TEMP0 