/****** Object:  Procedure [BI].[spSubContractorRegister1]    Committed by VersionSQL https://www.versionsql.com ******/

 
CREATE PROCEDURE [BI].[spSubContractorRegister1](@FINYEAR INT, @FROMPERIOD INT,@TOPERIOD INT)
--, @LISTCREDITORS  LISTCREDNUMBERS  READONLY  ,@LISTORGIDS  LISTORGIDS READONLY   )
As
 --DECLARE @FINYEAR INT
 --DECLARE @FROMPERIOD INT
 --DECLARE @TOPERIOD INT

 --SET @FINYEAR=2017
 --SET @FROMPERIOD =1
 --SET @TOPERIOD =12


DECLARE @EXISTING INT
DECLARE @COLTEXT VARCHAR(50)
DECLARE @RETAINED VARCHAR(10)
DECLARE @WIP VARCHAR(10)
DECLARE @LEDGERCODE VARCHAR(10)
DECLARE @LEDGERNAME VARCHAR(50)
DECLARE @COLUMHEADING   VARCHAR(50)

CREATE TABLE #COLHEADS(ID INT,COLHEAD VARCHAR(20), TITLENAME VARCHAR(25)) 
INSERT INTO #COLHEADS VALUES (10,'SubCon(5008012)','10.SubCon(5008012)')
INSERT INTO #COLHEADS VALUES (11,'Labour(5008006)','11.Labour(5008006)')
INSERT INTO #COLHEADS VALUES (99,'Others','99.Others')
DECLARE @COLID INT
DECLARE @COLHEADTOSEARCH VARCHAR(20) 
DECLARE @COLHEADFOUND INT
SET @COLID = 12

SELECT @RETAINED = CONTROLFROMGL FROM CONTROLCODES WHERE CONTROLNAME='Retained Income'
SELECT @WIP = CONTROLFROMGL FROM CONTROLCODES WHERE CONTROLNAME='Work In Progress'

 
CREATE TABLE #BORGS(ORGID INT)
INSERT INTO #BORGS 
SELECT BORGID FROM BORGS 
--SELECT ORGID  FROM @LISTORGIDS
DELETE FROM #BORGS WHERE ORGID IS NULL
 
CREATE TABLE #REVENUECODES ( LEDGERCODE VARCHAR(10) )
INSERT INTO  #REVENUECODES VALUES ( '5008012')
INSERT INTO  #REVENUECODES VALUES ( '5008006')

SELECT 
 DISTINCT  T.TRANGRP , T.ORGID 
INTO 
 #TRANGRP 
FROM 
 TRANSACTIONS T 
WHERE 
 T.YEAR=@FINYEAR AND 
 T.PERIOD BETWEEN @FROMPERIOD AND @TOPERIOD AND 
 T.LEDGERCODE IN (SELECT LEDGERCODE FROM #REVENUECODES ) AND
 T.ORGID IN (SELECT ORGID FROM #BORGS)  AND CREDNO='AAFCR5460H'
 


SELECT DISTINCT DEFAULTALLOC AS LEDGERCODE INTO #SUBBIELEDGERS FROM SUBCRECONRULES 
DELETE FROM #SUBBIELEDGERS WHERE LEDGERCODE IS NULL 
DELETE FROM #SUBBIELEDGERS WHERE LEDGERCODE = ''
ALTER TABLE #SUBBIELEDGERS ADD LEDGERNAME VARCHAR(15)
UPDATE #SUBBIELEDGERS SET LEDGERNAME='VATPayable'  WHERE LEDGERCODE = '1310000'
UPDATE #SUBBIELEDGERS SET LEDGERNAME='STPayable'   WHERE LEDGERCODE = '1310002'                 
UPDATE #SUBBIELEDGERS SET LEDGERNAME='TDS'         WHERE LEDGERCODE = '1310005'
UPDATE #SUBBIELEDGERS SET LEDGERNAME='RCPayable'   WHERE LEDGERCODE = '1310008'     
UPDATE #SUBBIELEDGERS SET LEDGERNAME='RCPay(WCT)'  WHERE LEDGERCODE = '1310010'
UPDATE #SUBBIELEDGERS SET LEDGERNAME='SC Control'  WHERE LEDGERCODE = '1320000'
UPDATE #SUBBIELEDGERS SET LEDGERNAME='Retention'   WHERE LEDGERCODE = '1320001'     
UPDATE #SUBBIELEDGERS SET LEDGERNAME='WithHeld'    WHERE LEDGERCODE = '1320002' 
UPDATE #SUBBIELEDGERS SET LEDGERNAME='Advance'     WHERE LEDGERCODE = '1320003' 
UPDATE #SUBBIELEDGERS SET LEDGERNAME='Courier'     WHERE LEDGERCODE = '5120035'     
UPDATE #SUBBIELEDGERS SET LEDGERNAME='AdmnCharge'  WHERE LEDGERCODE = '5120241' 
UPDATE #SUBBIELEDGERS SET LEDGERNAME='WithHeld'    WHERE LEDGERCODE = '5120242' 

DECLARE @JNLTRANSREF VARCHAR(10)
 
DECLARE @BANKSTART VARCHAR(10)
DECLARE @BANKEND   VARCHAR(10)
DECLARE @CASHSTART VARCHAR(10)

SELECT @BANKSTART=CONTROLFROMGL FROM CONTROLCODES WHERE CONTROLNAME  = 'Bank'
SELECT @BANKEND  =CONTROLTOGL   FROM CONTROLCODES WHERE CONTROLNAME  = 'Bank'
SELECT @CASHSTART=CONTROLFROMGL  FROM CONTROLCODES WHERE CONTROLNAME = 'Petty Cash'

INSERT INTO #SUBBIELEDGERS(LEDGERCODE,LEDGERNAME) 
SELECT LEDGERCODE,'Cash' FROM LEDGERCODES WHERE LEDGERCODE BETWEEN @BANKSTART AND @BANKEND

INSERT INTO #SUBBIELEDGERS(LEDGERCODE,LEDGERNAME)
SELECT @CASHSTART,'Cash' 


DELETE FROM #SUBBIELEDGERS WHERE LEDGERCODE IN (SELECT LEDGERCODE FROM #REVENUECODES) 

INSERT INTO #SUBBIELEDGERS(LEDGERCODE,LEDGERNAME) 
SELECT *,'XYZ' FROM #REVENUECODES

DECLARE POSTLEDGERS CURSOR FOR SELECT * FROM #SUBBIELEDGERS WHERE LEDGERNAME NOT IN ( 'Expense' ,'XYZ' ) 
DECLARE @POSTLEDGERCODE VARCHAR(10)
DECLARE @POSTLEDGERNAME VARCHAR(15)

SET @COLID=11

CREATE TABLE #TEMP0( TRANGRP INT, ORGID INT, BORGNAME VARCHAR(150),YEAR INT,  PERIOD INT, PERIODDESC VARCHAR(20), PDATE DATETIME, BATCHREF VARCHAR(10), TRANSREF VARCHAR(10),
                     LEDGERCODE VARCHAR(10), LEDGERNAME VARCHAR(25),CREDNO VARCHAR(10), PARTY VARCHAR(150),DEBIT DECIMAL(18,2),CREDIT DECIMAL(18,2) )


DECLARE @TGRP INT
DECLARE @TORGID INT
DECLARE @BORGNAME VARCHAR(150)

DECLARE OUTERLINK CURSOR FOR SELECT TRANGRP,ORGID FROM #TRANGRP
OPEN OUTERLINK

FETCH NEXT FROM OUTERLINK INTO @TGRP,@TORGID 

WHILE @@FETCH_STATUS = 0
BEGIN
   SELECT @BORGNAME = BORGNAME FROM BORGS WHERE BORGID = @TORGID 
  
   SELECT 
         T.TRANGRP,
 		 T.ORGID,
		 SPACE(150) BORGNAME,
		 T.YEAR,
		 T.PERIOD,
		 P.PERIODDESC,
		 T.PDATE,
		 T.BATCHREF,
		 T.TRANSREF,
		 T.LEDGERCODE,
		 SPACE(25) LEDGERNAME,
		 T.CREDNO,
		 BS.FNGETPARTY(T.CREDNO) SUBNAME,
		 T.DEBIT,
		 T.CREDIT 
		INTO #TEMP2
		FROM
		 TRANSACTIONS T 
		 INNER JOIN PERIODMASTER P ON T.PERIOD=P.PERIODID 
	 	WHERE 
		 TRANGRP = @TGRP  AND 
		 T.LEDGERCODE NOT IN (@RETAINED,@WIP)   

      UPDATE #TEMP2 SET BORGNAME=@BORGNAME 
	  UPDATE #TEMP2 SET LEDGERNAME='NA'
	


	  SET @COLHEADFOUND = 0
	  SELECT  @EXISTING = COUNT(*) FROM #TEMP2 WHERE LEDGERCODE='5008012' AND ORGID = @TORGID
	  IF @EXISTING > 0 
		   BEGIN
		     SELECT @COLHEADFOUND = COUNT(*) FROM #COLHEADS WHERE COLHEAD='SubCon(5008012)'
			 IF (@COLHEADFOUND>0)
			  BEGIN
			     SELECT @COLHEADTOSEARCH = TITLENAME FROM #COLHEADS WHERE COLHEAD='SubCon(5008012)'
			     SET @COLTEXT = LTRIM(RTRIM(@COLHEADTOSEARCH))
			  END
			 ELSE
			  BEGIN
			     SET @COLID = @COLID+1 
			     SET @COLHEADTOSEARCH = LTRIM(RTRIM(STR(@COLID)))+'.SubCon(5008012)'
				 INSERT INTO #COLHEADS VALUES (@COLID,'SubCon(5008012)',@COLHEADTOSEARCH)  
				 SET @COLTEXT =@COLHEADTOSEARCH
			  END  
			 UPDATE #TEMP2 SET LEDGERNAME = @COLTEXT WHERE LEDGERCODE='5008012' AND ORGID = @TORGID
	  END

	 

	  SELECT  @EXISTING = COUNT(*) FROM #TEMP2 WHERE LEDGERCODE='5008006' AND ORGID = @TORGID
	  IF @EXISTING > 0 
		   BEGIN
		     SELECT @COLHEADFOUND = COUNT(*) FROM #COLHEADS WHERE COLHEAD='Labour(5008006)'
			 IF (@COLHEADFOUND>0)
			  BEGIN
			     SELECT @COLHEADTOSEARCH = TITLENAME FROM #COLHEADS WHERE COLHEAD='Labour(5008006)'
			     SET @COLTEXT = LTRIM(RTRIM(@COLHEADTOSEARCH))
			  END
			 ELSE
			  BEGIN
			     SET @COLID = @COLID+1 
			     SET @COLHEADTOSEARCH = LTRIM(RTRIM(STR(@COLID)))+'.Labour(5008006)'
				 INSERT INTO #COLHEADS VALUES (@COLID,'SubCon(5008012)',@COLHEADTOSEARCH)  
				 SET @COLTEXT =@COLHEADTOSEARCH
     		  END  
			 SET @COLTEXT =@COLHEADTOSEARCH
			 UPDATE #TEMP2 SET LEDGERNAME = @COLTEXT WHERE LEDGERCODE='5008006' AND ORGID = @TORGID
	  END

      

	
	OPEN POSTLEDGERS
	FETCH NEXT FROM POSTLEDGERS INTO @POSTLEDGERCODE ,@POSTLEDGERNAME 
	WHILE @@FETCH_STATUS = 0 
		BEGIN
			SELECT  @EXISTING = COUNT(*) FROM #TEMP2 WHERE LEDGERCODE=@POSTLEDGERCODE AND ORGID = @TORGID
			IF @EXISTING > 0 
			BEGIN
			    SELECT @COLHEADFOUND = COUNT(*) FROM #COLHEADS WHERE COLHEAD=@POSTLEDGERNAME
			    IF (@COLHEADFOUND>0)
			      BEGIN
			       SELECT @COLHEADTOSEARCH = TITLENAME FROM #COLHEADS WHERE COLHEAD= @POSTLEDGERNAME
			       SET @COLTEXT = LTRIM(RTRIM(@COLHEADTOSEARCH))
			      END
			    ELSE
			      BEGIN
				     SET @COLID = @COLID+1 
			         SET @COLHEADTOSEARCH = LTRIM(RTRIM(STR(@COLID)))+'.'+@POSTLEDGERNAME
				     INSERT INTO #COLHEADS VALUES (@COLID,@POSTLEDGERNAME,@COLHEADTOSEARCH)  
				     SET @COLTEXT =@COLHEADTOSEARCH
			      END  
			      UPDATE #TEMP2 SET LEDGERNAME = @COLTEXT WHERE LEDGERCODE=@POSTLEDGERCODE AND ORGID = @TORGID
			END
			FETCH NEXT FROM POSTLEDGERS INTO @POSTLEDGERCODE ,@POSTLEDGERNAME 
		END
	CLOSE POSTLEDGERS 
	SET @COLTEXT = '99.Others'
	UPDATE #TEMP2 SET LEDGERNAME = @COLTEXT WHERE LEDGERNAME='NA' AND ORGID = @TORGID
	
	DELETE FROM #TEMP2 WHERE LEDGERNAME='NA'

	SELECT  TOP 1 @JNLTRANSREF = ISNULL(TRANSREF,'' ) FROM #TEMP2 WHERE
	  LEFT(BATCHREF,3)='JNL' AND LEDGERCODE IN (SELECT LEDGERCODE FROM #REVENUECODES ) AND ORGID=@TORGID 
	
	UPDATE #TEMP2 SET TRANSREF=@JNLTRANSREF WHERE LEFT(BATCHREF,3)=  'JNL'

	INSERT INTO #TEMP0 
	SELECT * FROM #TEMP2

	DROP TABLE #TEMP2 

	FETCH NEXT FROM OUTERLINK INTO @TGRP,@TORGID 
END
	 

DEALLOCATE POSTLEDGERS 
CLOSE OUTERLINK
DEALLOCATE OUTERLINK

----SELECT CREDNUMBER  INTO #PARTYCODES  FROM @LISTCREDITORS
----DELETE FROM #PARTYCODES WHERE CREDNUMBER IS NULL
--INSERT INTO #PARTYCODES VALUES ('AAFCR5460H')
 

--DELETE FROM #TEMP0 
--WHERE CREDNO NOT IN (SELECT CREDNUMBER FROM #PARTYCODES) 

 


SELECT 
 TRANGRP      AS   TRANGRP,
 BORGNAME     AS   PROJECT,
 PARTY        AS   SUPPLIER,
 PERIOD       AS   PERIODID,
 PERIODDESC   AS   PERIOD,
 PDATE        AS   POSTDATE,
 BATCHREF     AS   BATCHREF,
 TRANSREF     AS   TRANSREF,
 LEDGERNAME   AS   LEDGERNAME,
 SUM(DEBIT-CREDIT) AS AMOUNT 
INTO 
 #TEMP1
FROM
 #TEMP0 
GROUP BY
 TRANGRP,BORGNAME,PARTY,PERIOD,PERIODDESC,PDATE,BATCHREF,TRANSREF,LEDGERNAME 
ORDER BY
 BORGNAME 


Exec [BI].[CrossTab]  'SELECT * FROM #TEMP1', 'LEDGERNAME','SUM(AMOUNT ELSE 0)[]','TRANGRP,PROJECT,SUPPLIER,PERIODID,PERIOD,POSTDATE,BATCHREF,TRANSREF' 
 
 

 