/****** Object:  Procedure [BI].[spSubbiesDoneTrans]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE [BI].[spSubbiesDoneTrans](@FINYEAR INT)
AS
--SELECT 
-- DISTINCT CREDNO  
-- INTO #TEMP0 
-- FROM TRANSACTIONS WHERE  LEDGERCODE='1320000' 

--ALTER TABLE #TEMP0 ADD CREDNAME VARCHAR(150)
--UPDATE #TEMP0 SET CREDNAME = C.SUBNAME FROM SUBCONTRACTORS  C INNER JOIN #TEMP0 ON #TEMP0.CREDNO=C.SUBNUMBER
--UPDATE #TEMP0 SET CREDNAME =LTRIM(RTRIM(CREDNAME))+ ' ('+ LTRIM(RTRIM(CREDNO)) + ')'
--DELETE FROM #TEMP0 WHERE CREDNO IS NULL
--UPDATE #TEMP0 SET CREDNAME = 'UNKNOWN' WHERE CREDNAME IS NULL 
--SELECT CREDNO CREDNUMBER, CREDNAME   FROM #TEMP0 ORDER BY CREDNAME

SELECT SUBNUMBER CREDNUMBER,( LTRIM(RTRIM(UPPER(SUBNAME)))+' - '+LTRIM(RTRIM(UPPER(SUBNUMBER))) ) CREDNAME FROM SUBCONTRACTORS WHERE SUBSTATUS=0 ORDER BY CREDNAME 





-- YEAR=@FINYEAR AND modified on 13 April - Remove this constraint
 --AND  ORGID  IN (SELECT BORGID FROM BORGS WHERE PARENTBORG IN (23,24,25,26) ) - Removed this constraint - let all select