/****** Object:  Procedure [BI].[spUpdateEngineeringTranGrpCodes]    Committed by VersionSQL https://www.versionsql.com ******/

--select * from INVENTORY where borgID=65
--SELECT * FROM INVENTORY WHERE BORGID=65 AND STKDESC LIKE '%Ready%'

 

--select * from debtrecons  where reconid=51500

--select * from transactions WHERE ORGID=65 ORDER BY TRANSID DESC 

 
 
--SELECT * FROM BI.ENGINEERINGCODES

CREATE PROCEDURE [BI].[spUpdateEngineeringTranGrpCodes]
AS
DECLARE @RECONID INT
DECLARE @ORGID INT
DECLARE @SUBCONNUMBER INT 
DECLARE @DEBTNUMBER VARCHAR(15)
DECLARE @POSTDATE DATETIME
DECLARE @POSTREF VARCHAR(15)
DECLARE @ORDERNO VARCHAR(15)
DECLARE @LEDGERCODE VARCHAR(15) 
DECLARE @WORKDONETOTAL DECIMAL(18,2) 
DECLARE @TRANGRP INT 

DECLARE RECONLIST CURSOR FOR 
SELECT DISTINCT RECONID FROM BI.ENGINEERINGCODES WHERE TRANGRP = -1
OPEN RECONLIST 
FETCH NEXT FROM RECONLIST INTO @RECONID 
WHILE @@FETCH_STATUS = 0 
BEGIN
  SELECT TOP 1 @LEDGERCODE=LEDGERCODE FROM BI.ENGINEERINGCODES WHERE RECONID=@RECONID 
  SELECT @WORKDONETOTAL = SUM(AMOUNT) FROM BI.ENGINEERINGCODES WHERE RECONID=@RECONID 

  SELECT @ORGID=ORGID,@SUBCONNUMBER=SUBCONNUMBER,@POSTDATE=POSTDATE,@POSTREF=CERTNO,@ORDERNO=ORDERNO  
  FROM DEBTRECONS WHERE POSTED=1 AND RECONID=@RECONID 

  SELECT @DEBTNUMBER = DEBTNUMBER  FROM DEBTORS  WHERE DEBTID = @SUBCONNUMBER 
  select @orgid,@subconnumber,@postdate,@postref,@orderno,@DEBTNUMBER,@reconid ,@LEDGERCODE ,@WORKDONETOTAL
  SET @TRANGRP = -1
  IF @WORKDONETOTAL >0 
   BEGIN
	SELECT @TRANGRP =ISNULL(TRANGRP ,-1)
	FROM TRANSACTIONS 
	WHERE LEFT(BATCHREF,3)='DTI' AND 
        ORGID=@ORGID  AND 
   	    CREDNO = @DEBTNUMBER  AND 
        PDATE = @POSTDATE AND 
        LEDGERCODE = @LEDGERCODE AND 
        CREDIT= @WORKDONETOTAL AND
		ORDERNO = @ORDERNO AND 
		TRANSREF = @POSTREF 
   END
  ELSE
   BEGIN
   
    SELECT @TRANGRP =ISNULL(TRANGRP ,-1)
	FROM TRANSACTIONS 
	WHERE LEFT(BATCHREF,3)='DTI' AND 
        ORGID=@ORGID  AND 
   	    CREDNO = @DEBTNUMBER  AND 
        PDATE = @POSTDATE AND 
        LEDGERCODE = @LEDGERCODE AND 
        DEBIT= ABS(@WORKDONETOTAL) AND
		ORDERNO = @ORDERNO AND 
		TRANSREF = @POSTREF 
   END
   
  IF @TRANGRP <>0 
     UPDATE BI.ENGINEERINGCODES SET TRANGRP=@TRANGRP  WHERE RECONID=@RECONID 
  
  FETCH NEXT FROM RECONLIST INTO @RECONID 

END
CLOSE RECONLIST
DEALLOCATE RECONLIST 