/****** Object:  Procedure [BI].[spUpdateDTI_FORGST]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE  PROCEDURE [BI].[spUpdateDTI_FORGST](@LASTTRANGRP INT) 
AS
DECLARE @TRANGRP INT
DECLARE @TRANSID INT
DECLARE @NARRATION VARCHAR(255) 
DECLARE @CGST_AMOUNT DECIMAL(18,2)
DECLARE @SGST_AMOUNT DECIMAL(18,2)
DECLARE @IGST_AMOUNT DECIMAL(18,2)   
DECLARE @TAXABLEVALUE DECIMAL(18,2)

DECLARE @CGSTPERCENT DECIMAL(18,2)
DECLARE @SGSTPERCENT DECIMAL(18,2)
DECLARE @IGSTPERCENT DECIMAL(18,2) 

DECLARE MISSINGTAXVALUE CURSOR FOR
    SELECT    TRANSID  FROM BI.SALESHISTORY WHERE DOCTYPE='DTI'  AND ( TAXABLE_VALUE IS NULL OR TAXABLE_VALUE=0 ) AND TRANGRP >=@LASTTRANGRP
OPEN MISSINGTAXVALUE
FETCH NEXT FROM MISSINGTAXVALUE INTO @TRANSID 

WHILE @@FETCH_STATUS=0
BEGIN
  SELECT @TRANGRP = TRANGRP,@NARRATION = ITEM  FROM BI.SALESHISTORY WHERE TRANSID = @TRANSID 
  SET @CGST_AMOUNT=0
  SET @SGST_AMOUNT=0                         
 
  SET @IGST_AMOUNT=0
  SET @CGSTPERCENT = 0
  SET @SGSTPERCENT = 0
  SET @IGSTPERCENT = 0
  SELECT @CGST_AMOUNT = CGST_AMOUNT FROM BI.SALESHISTORY WHERE TRANSID = @TRANSID AND LEDGERCODE='1310028' 
  SELECT @SGST_AMOUNT = SGST_AMOUNT FROM BI.SALESHISTORY WHERE TRANSID = @TRANSID AND LEDGERCODE='1310029'
  SELECT @IGST_AMOUNT = IGST_AMOUNT FROM BI.SALESHISTORY WHERE TRANSID = @TRANSID AND LEDGERCODE='1310030'

   

  SET @TAXABLEVALUE=0.0 
   SELECT @TAXABLEVALUE = (DEBIT-CREDIT) 
   FROM TRANSACTIONS 
   WHERE TRANGRP = @TRANGRP  AND ( TRANSID BETWEEN @TRANSID-3 AND @TRANSID  ) AND LEDGERCODE IN ('2541000','2541001','2541002','4010000' )

  IF @TAXABLEVALUE = 0 
   SELECT @TAXABLEVALUE = (DEBIT-CREDIT) 
   FROM TRANSACTIONS 
   WHERE TRANGRP = @TRANGRP AND TRANSID BETWEEN @TRANSID-3 AND @TRANSID  AND DESCRIPTION LIKE 'Total Work Done'  

  IF @TAXABLEVALUE = 0
   SELECT @TAXABLEVALUE = SUM(DEBIT-CREDIT) FROM TRANSACTIONS WHERE TRANGRP = @TRANGRP AND ALLOCATION='Balance Sheet' AND LEDGERCODE='2990000' 
                                                                                                                                                                                                                                           
  IF @TAXABLEVALUE >0 
  BEGIN 
     SET @CGSTPERCENT =ROUND( (@CGST_AMOUNT/@TAXABLEVALUE)*100 ,1) 
	 SET @SGSTPERCENT = @CGSTPERCENT 
	 SET @IGSTPERCENT =ROUND( (@IGST_AMOUNT/@TAXABLEVALUE)*100, 1) 
	 
  END

  IF @TAXABLEVALUE <0 
  BEGIN 
     SET @CGSTPERCENT =ROUND( (@CGST_AMOUNT/@TAXABLEVALUE)*100 ,1) 
	 SET @SGSTPERCENT = @CGSTPERCENT 
	 SET @IGSTPERCENT =ROUND( (@IGST_AMOUNT/@TAXABLEVALUE)*100, 1) 
  END
 
  UPDATE BI.SALESHISTORY SET TAXABLE_VALUE=@TAXABLEVALUE ,CGST_RATE=@CGSTPERCENT , SGST_RATE=@SGSTPERCENT,IGST_RATE=@IGSTPERCENT WHERE TRANSID=@TRANSID 

  FETCH NEXT FROM MISSINGTAXVALUE INTO @TRANSID 
 
END
CLOSE MISSINGTAXVALUE
DEALLOCATE  MISSINGTAXVALUE 




-- SCI
DECLARE MISSINGTAXVALUE CURSOR FOR
    SELECT    TRANSID  FROM BI.SALESHISTORY WHERE DOCTYPE='SCI'  AND ( TAXABLE_VALUE IS NULL OR TAXABLE_VALUE=0 ) AND TRANGRP >=@LASTTRANGRP
OPEN MISSINGTAXVALUE
FETCH NEXT FROM MISSINGTAXVALUE INTO @TRANSID 

WHILE @@FETCH_STATUS=0
BEGIN
  SELECT @TRANGRP = TRANGRP   FROM BI.SALESHISTORY WHERE TRANSID = @TRANSID 
  SET @CGST_AMOUNT=0
  SET @SGST_AMOUNT=0                         
 
  SET @IGST_AMOUNT=0
  SET @CGSTPERCENT = 0
  SET @SGSTPERCENT = 0
  SET @IGSTPERCENT = 0
  SELECT @CGST_AMOUNT = CGST_AMOUNT FROM BI.SALESHISTORY WHERE TRANSID = @TRANSID AND LEDGERCODE='1310028' 
  SELECT @SGST_AMOUNT = SGST_AMOUNT FROM BI.SALESHISTORY WHERE TRANSID = @TRANSID AND LEDGERCODE='1310029'
  SELECT @IGST_AMOUNT = IGST_AMOUNT FROM BI.SALESHISTORY WHERE TRANSID = @TRANSID AND LEDGERCODE='1310030'

   

  SET @TAXABLEVALUE=0.0 
   SELECT @TAXABLEVALUE = (DEBIT-CREDIT) 
   FROM TRANSACTIONS 
   WHERE TRANGRP = @TRANGRP  AND ( TRANSID BETWEEN @TRANSID-2 AND @TRANSID  ) AND LEDGERCODE='2990000' 

                                                                                                                                                                                                                                           
  IF @TAXABLEVALUE >0 
  BEGIN 
     SET @CGSTPERCENT =ROUND( (@CGST_AMOUNT/@TAXABLEVALUE)*100 ,1) 
	 SET @SGSTPERCENT = @CGSTPERCENT 
	 SET @IGSTPERCENT =ROUND( (@IGST_AMOUNT/@TAXABLEVALUE)*100, 1) 
	 
  END

  IF @TAXABLEVALUE <0 
  BEGIN 
     SET @CGSTPERCENT =ROUND( (@CGST_AMOUNT/@TAXABLEVALUE)*100 ,1) 
	 SET @SGSTPERCENT = @CGSTPERCENT 
	 SET @IGSTPERCENT =ROUND( (@IGST_AMOUNT/@TAXABLEVALUE)*100, 1) 
  END
 
  UPDATE BI.SALESHISTORY SET TAXABLE_VALUE=@TAXABLEVALUE ,CGST_RATE=@CGSTPERCENT , SGST_RATE=@SGSTPERCENT,IGST_RATE=@IGSTPERCENT WHERE TRANSID=@TRANSID 

  FETCH NEXT FROM MISSINGTAXVALUE INTO @TRANSID 
 
END
CLOSE MISSINGTAXVALUE
DEALLOCATE  MISSINGTAXVALUE 






UPDATE BI.SALESHISTORY SET CGST_RATE=0 WHERE CGST_RATE IS NULL 
UPDATE BI.SALESHISTORY SET SGST_RATE=0 WHERE SGST_RATE IS NULL
UPDATE BI.SALESHISTORY SET IGST_RATE=0 WHERE IGST_RATE IS NULL 


UPDATE BI.SALESHISTORY SET CGST_RATE=0,SGST_RATE=0,IGST_RATE=0 WHERE DOCTYPE='JNL' 

SELECT DISTINCT TRANGRP,FINYEAR,PERIOD INTO #SALESPOSTING FROM BI.SALESHISTORY 
ALTER TABLE #SALESPOSTING ADD ACTUALYEAR INT
ALTER TABLE #SALESPOSTING ADD ACTUALPERIOD INT 

UPDATE #SALESPOSTING SET ACTUALYEAR=T.YEAR,ACTUALPERIOD=T.PERIOD  FROM TRANSACTIONS T INNER JOIN #SALESPOSTING ON T.TRANGRP=#SALESPOSTING.TRANGRP 
DELETE  FROM #SALESPOSTING WHERE ACTUALYEAR=FINYEAR AND  ACTUALPERIOD=PERIOD  
--SELECT * FROM #SALESPOSTING

UPDATE BI.SALESHISTORY SET PERIOD=ACTUALPERIOD FROM #SALESPOSTING INNER JOIN BI.SALESHISTORY BIS ON BIS.TRANGRP=#SALESPOSTING.TRANGRP  