/****** Object:  Procedure [BI].[spUpdateActuals]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE  PROCEDURE [BI].[spUpdateActuals](@FINYEAR INT , @ORGID INT ) 
AS

SELECT LEDGERCODE,PERIOD,SUM(DEBIT-CREDIT) ACTUAL
INTO #ACTUAL 
FROM TRANSACTIONS 
WHERE
  YEAR=@FINYEAR AND 
  LEDGERCODE IN (SELECT LEDGERCODE FROM LEDGERCODES WHERE LEDGERALLOC='Contracts') AND 
  ORGID=@ORGID AND 
  PERIOD<>0
GROUP BY LEDGERCODE,PERIOD 

 

CREATE TABLE #FINAL(LEDGERCODE VARCHAR(15), LEDGERNAME VARCHAR(200),
APRIL_B DECIMAL(18,2),APRIL_A DECIMAL(18,2), 
MAY_B DECIMAL(18,2),MAY_A DECIMAL(18,2),
JUNE_B DECIMAL(18,2),JUNE_A DECIMAL(18,2),
JULY_B DECIMAL(18,2), JULY_A DECIMAL(18,2),
AUGUST_B DECIMAL(18,2),AUGUST_A DECIMAL(18,2),
SEPTEMBER_B DECIMAL(18,2),SEPTEMBER_A DECIMAL(18,2),
OCTOBER_B DECIMAL(18,2), OCTOBER_A DECIMAL(18,2),
NOVEMBER_B DECIMAL(18,2), NOVEMBER_A DECIMAL(18,2),
DECEMBER_B DECIMAL(18,2), DECEMBER_A DECIMAL(18,2),
JANUARY_B DECIMAL(18,2), JANUARY_A DECIMAL(18,2),
FEBRARARY_B DECIMAL(18,2), FEBRARARY_A DECIMAL(18,2),
MARCH_B DECIMAL(18,2), MARCH_A DECIMAL(18,2)   ) 


SELECT DISTINCT LEDGERCODE 
INTO #AVAILABLELEDGERS 
FROM ( SELECT LEDGERCODE FROM #ACTUAL 
       UNION 
	   SELECT LEDGERCODE FROM BI.YEARLYBUDGETS WHERE [FINYEAR] = @FINYEAR AND  ORGID = @ORGID ) T

INSERT INTO #FINAL(LEDGERCODE) 
SELECT LEDGERCODE  FROM #AVAILABLELEDGERS 


DECLARE @APR_PERC DECIMAL(6,2) 
DECLARE @MAY_PERC DECIMAL(6,2)
DECLARE @JUN_PERC DECIMAL(6,2) 
DECLARE @JUL_PERC DECIMAL(6,2)
DECLARE @AUG_PERC DECIMAL(6,2) 
DECLARE @SEP_PERC DECIMAL(6,2)
DECLARE @OCT_PERC DECIMAL(6,2)
DECLARE @NOV_PERC DECIMAL(6,2)
DECLARE @DEC_PERC DECIMAL(6,2)
DECLARE @JAN_PERC DECIMAL(6,2)
DECLARE @FEB_PERC DECIMAL(6,2)
DECLARE @MAR_PERC DECIMAL(6,2)

SELECT @APR_PERC = ISNULL(PRODPERCENTAGE,1) FROM BI.SALESPERCENTAGE WHERE YEAR=@FINYEAR AND PERIOD=1 AND ORGID=@ORGID 
SELECT @MAY_PERC = ISNULL(PRODPERCENTAGE,1) FROM BI.SALESPERCENTAGE WHERE YEAR=@FINYEAR AND PERIOD=2 AND ORGID=@ORGID 
SELECT @JUN_PERC = ISNULL(PRODPERCENTAGE,1) FROM BI.SALESPERCENTAGE WHERE YEAR=@FINYEAR AND PERIOD=3 AND ORGID=@ORGID 
SELECT @JUL_PERC = ISNULL(PRODPERCENTAGE,1) FROM BI.SALESPERCENTAGE WHERE YEAR=@FINYEAR AND PERIOD=4 AND ORGID=@ORGID 
SELECT @AUG_PERC = ISNULL(PRODPERCENTAGE,1) FROM BI.SALESPERCENTAGE WHERE YEAR=@FINYEAR AND PERIOD=5 AND ORGID=@ORGID 
SELECT @SEP_PERC = ISNULL(PRODPERCENTAGE,1) FROM BI.SALESPERCENTAGE WHERE YEAR=@FINYEAR AND PERIOD=6 AND ORGID=@ORGID 
SELECT @OCT_PERC = ISNULL(PRODPERCENTAGE,1) FROM BI.SALESPERCENTAGE WHERE YEAR=@FINYEAR AND PERIOD=7 AND ORGID=@ORGID 
SELECT @NOV_PERC = ISNULL(PRODPERCENTAGE,1) FROM BI.SALESPERCENTAGE WHERE YEAR=@FINYEAR AND PERIOD=8 AND ORGID=@ORGID 
SELECT @DEC_PERC = ISNULL(PRODPERCENTAGE,1) FROM BI.SALESPERCENTAGE WHERE YEAR=@FINYEAR AND PERIOD=9 AND ORGID=@ORGID 
SELECT @JAN_PERC = ISNULL(PRODPERCENTAGE,1) FROM BI.SALESPERCENTAGE WHERE YEAR=@FINYEAR AND PERIOD=10 AND ORGID=@ORGID 
SELECT @FEB_PERC = ISNULL(PRODPERCENTAGE,1) FROM BI.SALESPERCENTAGE WHERE YEAR=@FINYEAR AND PERIOD=11 AND ORGID=@ORGID 
SELECT @MAR_PERC = ISNULL(PRODPERCENTAGE,1) FROM BI.SALESPERCENTAGE WHERE YEAR=@FINYEAR AND PERIOD=12 AND ORGID=@ORGID 

 

UPDATE #FINAL SET APRIL_B=0, MAY_B=0, JUNE_B=0, JULY_B = 0, AUGUST_B=0, SEPTEMBER_B=0, OCTOBER_B =0, NOVEMBER_B=0, DECEMBER_B=0, JANUARY_B=0,FEBRARARY_B=0, MARCH_B=0 
UPDATE #FINAL SET APRIL_A=0, MAY_A=0, JUNE_A=0, JULY_A = 0, AUGUST_A=0, SEPTEMBER_A=0, OCTOBER_A =0, NOVEMBER_A=0, DECEMBER_A=0, JANUARY_A=0,FEBRARARY_A=0, MARCH_A=0 


UPDATE #FINAL SET APRIL_B=YB.BUDGET  FROM BI.YEARLYBUDGETS YB INNER JOIN #FINAL ON #FINAL.LEDGERCODE = YB.LEDGERCODE AND YB.PERIOD=1  AND ORGID = @ORGID
UPDATE #FINAL SET MAY_B=YB.BUDGET    FROM BI.YEARLYBUDGETS YB INNER JOIN #FINAL ON #FINAL.LEDGERCODE = YB.LEDGERCODE AND YB.PERIOD=2   AND ORGID = @ORGID
UPDATE #FINAL SET JUNE_B=YB.BUDGET    FROM BI.YEARLYBUDGETS YB INNER JOIN #FINAL ON #FINAL.LEDGERCODE = YB.LEDGERCODE AND YB.PERIOD=3   AND ORGID = @ORGID
UPDATE #FINAL SET JULY_B=YB.BUDGET    FROM BI.YEARLYBUDGETS YB INNER JOIN #FINAL ON #FINAL.LEDGERCODE = YB.LEDGERCODE AND YB.PERIOD=4   AND ORGID = @ORGID
UPDATE #FINAL SET AUGUST_B=YB.BUDGET    FROM BI.YEARLYBUDGETS YB INNER JOIN #FINAL ON #FINAL.LEDGERCODE = YB.LEDGERCODE AND YB.PERIOD=5   AND ORGID = @ORGID
UPDATE #FINAL SET SEPTEMBER_B=YB.BUDGET   FROM BI.YEARLYBUDGETS YB INNER JOIN #FINAL ON #FINAL.LEDGERCODE = YB.LEDGERCODE AND YB.PERIOD=6   AND ORGID = @ORGID
UPDATE #FINAL SET OCTOBER_B=YB.BUDGET    FROM BI.YEARLYBUDGETS YB INNER JOIN #FINAL ON #FINAL.LEDGERCODE = YB.LEDGERCODE AND YB.PERIOD=7   AND ORGID = @ORGID
UPDATE #FINAL SET NOVEMBER_B=YB.BUDGET    FROM BI.YEARLYBUDGETS YB INNER JOIN #FINAL ON #FINAL.LEDGERCODE = YB.LEDGERCODE AND YB.PERIOD=8   AND ORGID = @ORGID
UPDATE #FINAL SET DECEMBER_B=YB.BUDGET    FROM BI.YEARLYBUDGETS YB INNER JOIN #FINAL ON #FINAL.LEDGERCODE = YB.LEDGERCODE AND YB.PERIOD=9   AND ORGID = @ORGID
UPDATE #FINAL SET JANUARY_B=YB.BUDGET   FROM BI.YEARLYBUDGETS YB INNER JOIN #FINAL ON #FINAL.LEDGERCODE = YB.LEDGERCODE AND YB.PERIOD=10   AND ORGID = @ORGID
UPDATE #FINAL SET FEBRARARY_B=YB.BUDGET   FROM BI.YEARLYBUDGETS YB INNER JOIN #FINAL ON #FINAL.LEDGERCODE = YB.LEDGERCODE AND YB.PERIOD=11   AND ORGID = @ORGID
UPDATE #FINAL SET MARCH_B=YB.BUDGET   FROM BI.YEARLYBUDGETS YB INNER JOIN #FINAL ON #FINAL.LEDGERCODE = YB.LEDGERCODE AND YB.PERIOD=12   AND ORGID = @ORGID

  

SELECT LEDGERCODE INTO #TEMPLEDGERCODES FROM LEDGERCODES 
WHERE LEDGERCODE IN ( SELECT COLKEY FROM ATTRIBVALUE WHERE TABLENAME='LEDGERCODES' AND ATTRIBUTE= 'Sales % Effect in Budget' AND VALUE=1)

 
UPDATE #FINAL SET APRIL_B = APRIL_B * (@APR_PERC/100) WHERE LEDGERCODE IN (SELECT LEDGERCODE FROM #TEMPLEDGERCODES) 
UPDATE #FINAL SET MAY_B = MAY_B * (@MAY_PERC/100) WHERE LEDGERCODE IN (SELECT LEDGERCODE FROM #TEMPLEDGERCODES) 
UPDATE #FINAL SET JUNE_B = JUNE_B * (@JUN_PERC/100) WHERE LEDGERCODE IN (SELECT LEDGERCODE FROM #TEMPLEDGERCODES) 
UPDATE #FINAL SET JULY_B = JULY_B * (@JUL_PERC/100) WHERE LEDGERCODE IN (SELECT LEDGERCODE FROM #TEMPLEDGERCODES) 
UPDATE #FINAL SET AUGUST_B = AUGUST_B * (@AUG_PERC/100) WHERE LEDGERCODE IN (SELECT LEDGERCODE FROM #TEMPLEDGERCODES) 
UPDATE #FINAL SET SEPTEMBER_B = SEPTEMBER_B * (@SEP_PERC/100) WHERE LEDGERCODE IN (SELECT LEDGERCODE FROM #TEMPLEDGERCODES) 
UPDATE #FINAL SET OCTOBER_B = OCTOBER_B * (@OCT_PERC/100) WHERE LEDGERCODE IN (SELECT LEDGERCODE FROM #TEMPLEDGERCODES) 
UPDATE #FINAL SET NOVEMBER_B = NOVEMBER_B * (@NOV_PERC/100) WHERE LEDGERCODE IN (SELECT LEDGERCODE FROM #TEMPLEDGERCODES) 
UPDATE #FINAL SET DECEMBER_B = DECEMBER_B * (@DEC_PERC/100) WHERE LEDGERCODE IN (SELECT LEDGERCODE FROM #TEMPLEDGERCODES) 
UPDATE #FINAL SET JANUARY_B = JANUARY_B * (@JAN_PERC/100) WHERE LEDGERCODE IN (SELECT LEDGERCODE FROM #TEMPLEDGERCODES) 
UPDATE #FINAL SET FEBRARARY_B = FEBRARARY_B * (@FEB_PERC/100) WHERE LEDGERCODE IN (SELECT LEDGERCODE FROM #TEMPLEDGERCODES) 
UPDATE #FINAL SET MARCH_B = MARCH_B * (@MAR_PERC/100) WHERE LEDGERCODE IN (SELECT LEDGERCODE FROM #TEMPLEDGERCODES) 

  

UPDATE #FINAL SET APRIL_A=YB.Actual  FROM #ACTUAL   YB INNER JOIN #FINAL ON #FINAL.LEDGERCODE = YB.LEDGERCODE AND YB.PERIOD=1  
UPDATE #FINAL SET MAY_A=YB.Actual  FROM #ACTUAL    YB INNER JOIN #FINAL ON #FINAL.LEDGERCODE = YB.LEDGERCODE AND YB.PERIOD=2  
UPDATE #FINAL SET JUNE_A=YB.Actual  FROM #ACTUAL   YB INNER JOIN #FINAL ON #FINAL.LEDGERCODE = YB.LEDGERCODE AND YB.PERIOD=3  
UPDATE #FINAL SET JULY_A=YB.Actual  FROM #ACTUAL   YB INNER JOIN #FINAL ON #FINAL.LEDGERCODE = YB.LEDGERCODE AND YB.PERIOD=4  
UPDATE #FINAL SET AUGUST_A=YB.Actual  FROM #ACTUAL   YB INNER JOIN #FINAL ON #FINAL.LEDGERCODE = YB.LEDGERCODE AND YB.PERIOD=5  
UPDATE #FINAL SET SEPTEMBER_A=YB.Actual  FROM #ACTUAL   YB INNER JOIN #FINAL ON #FINAL.LEDGERCODE = YB.LEDGERCODE AND YB.PERIOD=6  
UPDATE #FINAL SET OCTOBER_A=YB.Actual  FROM #ACTUAL   YB INNER JOIN #FINAL ON #FINAL.LEDGERCODE = YB.LEDGERCODE AND YB.PERIOD=7  
UPDATE #FINAL SET NOVEMBER_A=YB.Actual  FROM #ACTUAL   YB INNER JOIN #FINAL ON #FINAL.LEDGERCODE = YB.LEDGERCODE AND YB.PERIOD=8  
UPDATE #FINAL SET DECEMBER_A=YB.Actual  FROM #ACTUAL   YB INNER JOIN #FINAL ON #FINAL.LEDGERCODE = YB.LEDGERCODE AND YB.PERIOD=9  
UPDATE #FINAL SET JANUARY_A=YB.Actual  FROM #ACTUAL   YB INNER JOIN #FINAL ON #FINAL.LEDGERCODE = YB.LEDGERCODE AND YB.PERIOD=10  
UPDATE #FINAL SET FEBRARARY_A=YB.Actual  FROM #ACTUAL   YB INNER JOIN #FINAL ON #FINAL.LEDGERCODE = YB.LEDGERCODE AND YB.PERIOD=11  
UPDATE #FINAL SET MARCH_A=YB.Actual  FROM #ACTUAL   YB INNER JOIN #FINAL ON #FINAL.LEDGERCODE = YB.LEDGERCODE AND YB.PERIOD=12  


UPDATE #FINAL SET LEDGERNAME = UPPER(L.LEDGERNAME) FROM LEDGERCODES L INNER JOIN #FINAL ON #FINAL.LEDGERCODE  = L.LEDGERCODE  

 
  
SELECT 
 LEDGERCODE,
 LEDGERNAME,
 APRIL_B      APRIL_BUDGET ,
 APRIL_A      APRIL_ACTUAL ,
 MAY_B        MAY_BUDGET ,
 MAY_A        MAY_ACTUAL ,
 JUNE_B       JUNE_BUDGET ,
 JUNE_A       JUNE_ACTUAL ,
 JULY_B       JULY_BUDGET ,
 JULY_A       JULY_ACTUAL ,
 AUGUST_B     AUGUST_BUDGET ,
 AUGUST_A     AUGUST_ACTUAL ,
 SEPTEMBER_B   SEPTEMBER_BUDGET ,
 SEPTEMBER_A   SEPTEMBER_ACTUAL ,
 OCTOBER_B     OCTOBER_BUDGET ,
 OCTOBER_A     OCTOBER_ACTUAL ,
 NOVEMBER_B    NOVEMBER_BUDGET ,
 NOVEMBER_A    NOVEMBER_ACTUAL ,
 DECEMBER_B    DECEMBER_BUDGET ,
 DECEMBER_A    DECEMBER_ACTUAL ,
 JANUARY_B     JANUARY_BUDGET ,
 JANUARY_A     JANUARY_ACTUAL ,
 FEBRARARY_B    FEBRUARY_BUDGET ,
 FEBRARARY_A    FEBRUARY_ACTUAL ,
 MARCH_B       MARCH_BUDGET ,
 MARCH_A       MARCH_ACTUAL  
FROM 
 #FINAL 
ORDER BY LEDGERCODE 

 