/****** Object:  View [dbo].[ACC_User_Admin_Access]    Committed by VersionSQL https://www.versionsql.com ******/

 
CREATE VIEW ACC_User_Admin_Access as 
SELECT USERADMINPROCESSES.USERID [User ID], USERS.LOGINID [Login ID], USERS.USERNAME [User Name], 
USERADMINPROCESSES.PROCESS, USERADMINPROCESSES.ALLOW, USERADMINPROCESSES.ORGID 
FROM USERADMINPROCESSES 
INNER JOIN USERS ON USERADMINPROCESSES.USERID = USERS.USERID
WHERE USERADMINPROCESSES.ALLOW = 1