/****** Object:  View [dbo].[ACTIVITIESALLOWED]    Committed by VersionSQL https://www.versionsql.com ******/

  CREATE VIEW ACTIVITIESALLOWED  AS  	SELECT ACTIVITIES.*, ACTIVITIESINGROUP.SYS, ACTIVITIESINGROUP.CONTRID, ACTIVITIESINGROUP.BORGID  	FROM ACTIVITIES  	INNER JOIN ACTIVITIESINGROUP  	ON ACTIVITIES.ActID = ACTIVITIESINGROUP.ACTID 