/****** Object:  View [dbo].[bs_EMPLOYEE_TOTAL_LOANS_INTEREST]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE VIEW bs_EMPLOYEE_TOTAL_LOANS_INTEREST AS SELECT EMPLOANS.PRLID, EMPLOANS.EMPNUMBER, SUM(EMPLOANSINTR.INTERESTAMOUNT) AS INTEREST FROM EMPLOANS INNER JOIN EMPLOANSINTR ON EMPLOANS.LOANID = EMPLOANSINTR.LOANID GROUP BY EMPLOANS.PRLID, EMPLOANS.EMPNUMBER 