/****** Object:  View [dbo].[bs_EMP_CLOCKCARDS_COST]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE VIEW dbo.bs_EMP_CLOCKCARDS_COST
AS
SELECT     dbo.EMPLOYEES.EMPID, dbo.EMPLOYEES.EMPNUMBER, dbo.EMPLOYEES.EMPNAME, dbo.EMPLOYEES.KNOWNAS, dbo.EMPLOYEES.PAYPOINT, 
                      dbo.EMPLOYEES.TERMDATE, dbo.EMPLOYEES.SEX, dbo.EMPLOYEES.PERIODPAYMENT, dbo.EMPLOYEES.TYPEPAYMENT, 
                      dbo.EMPLOYEES.RATE1, dbo.EMPLOYEES.RATE2, dbo.EMPLOYEES.RATE3, dbo.EMPLOYEES.COST, dbo.EMPLOYEES.TOBETERMDATE, 
                      dbo.EMPLOYEES.EDSHID, dbo.EMPLOYEES.TRAVELRATE, dbo.EMPLOYEES.ISFOREMAN, dbo.EMPLOYEES.FOREMANNUM, 
                      dbo.EMPLOYEES.DEFNT, dbo.EMPLOYEES.DEFOT1, dbo.EMPLOYEES.DEFOT2, dbo.EMPLOYEES.DEFOT3, dbo.EMPLOYEES.DEFOT4, 
                      dbo.EMPLOYEES.DEFOT5, dbo.EMPLOYEES.DEFCOSTALLOC, dbo.EMPLOYEES.DEFCONTRID, dbo.EMPLOYEES.DEFCONTRNUM, 
                      dbo.EMPLOYEES.DEFACTID, dbo.EMPLOYEES.DEFACTNUM, dbo.EMPLOYEES.DEFLEDGERID, dbo.EMPLOYEES.DEFLEDGERCODE, 
                      dbo.EMPLOYEES.DEFPLANT, dbo.EMPLOYEES.DEFDIVISIONID, dbo.EMPLOYEES.CONTRACTEXPDATE, dbo.EMPLOYEES.DEBTNUMBER, 
                      dbo.EMPLOYEES.PAYROLLID, dbo.CLOCKCARDS.CCID, dbo.CLOCKCARDS.NT, dbo.CLOCKCARDS.OT1, dbo.CLOCKCARDS.OT2, dbo.CLOCKCARDS.OT3,
                       dbo.CLOCKCARDS.OT4, dbo.CLOCKCARDS.OT5, dbo.CLOCKCARDS.WEEKNO, dbo.CLOCKCARDS.DAYNO, dbo.CLOCKCARDS.PENUMBER, 
                      dbo.CLOCKCARDS.ALLOCATION, dbo.CLOCKCARDS.CONTRID, dbo.CLOCKCARDS.CONTRNUMBER, dbo.CLOCKCARDS.ACTID, 
                      dbo.CLOCKCARDS.ACTNUMBER, dbo.CLOCKCARDS.LEDGERID, dbo.CLOCKCARDS.LEDGERCODE, dbo.CLOCKCARDS.DIVID, 
                      dbo.CLOCKCARDS.USERATE, dbo.CLOCKCARDS.PERIODNO, dbo.CLOCKCARDS.RUNNO, dbo.CLOCKCARDS.YEARNO, 
                      dbo.CLOCKCARDS.COST AS CCCOST, dbo.CLOCKCARDS.ADDADVAMNT, dbo.CONTRACTS.CONTRNAME, dbo.PROJECTS.ProjNumber, 
                      dbo.PROJECTS.ProjName, dbo.ACTIVITIES.ActName, dbo.LEDGERCODES.LedgerName, dbo.PLANTANDEQ.PeName, dbo.DIVISIONS.DivName, 
                      dbo.bs_EDSETS_EDS_VALUES.NTM AS NTMVAL, dbo.bs_EDSETS_EDS_VALUES.OT1 AS OT1VAL, dbo.bs_EDSETS_EDS_VALUES.OT2 AS OT2VAL, 
                      dbo.bs_EDSETS_EDS_VALUES.OT3 AS OT3VAL, dbo.bs_EDSETS_EDS_VALUES.OT4 AS OT4VAL, dbo.bs_EDSETS_EDS_VALUES.OT5 AS OT5VAL
FROM         dbo.ACTIVITIES RIGHT OUTER JOIN
                      dbo.LEDGERCODES RIGHT OUTER JOIN
                      dbo.CLOCKCARDS INNER JOIN
                      dbo.EMPLOYEES ON dbo.CLOCKCARDS.PAYROLLID = dbo.EMPLOYEES.PAYROLLID AND 
                      dbo.CLOCKCARDS.EMPNUMBER = dbo.EMPLOYEES.EMPNUMBER INNER JOIN
                      dbo.bs_EDSETS_EDS_VALUES ON dbo.EMPLOYEES.EDSHID = dbo.bs_EDSETS_EDS_VALUES.edshid ON 
                      dbo.LEDGERCODES.LedgerCode = dbo.CLOCKCARDS.LEDGERCODE LEFT OUTER JOIN
                      dbo.DIVISIONS ON dbo.CLOCKCARDS.DIVID = dbo.DIVISIONS.DivID ON dbo.ACTIVITIES.ActNumber = dbo.CLOCKCARDS.ACTNUMBER LEFT OUTER JOIN
                      dbo.PROJECTS INNER JOIN
                      dbo.CONTRACTS ON dbo.PROJECTS.PROJID = dbo.CONTRACTS.PROJID ON 
                      dbo.CLOCKCARDS.CONTRNUMBER = dbo.CONTRACTS.CONTRNUMBER LEFT OUTER JOIN
                      dbo.PLANTANDEQ ON dbo.CLOCKCARDS.PENUMBER = dbo.PLANTANDEQ.PeNumber