/****** Object:  View [dbo].[bs_EMPLOYEE_HOURS_MONTHLY]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE VIEW dbo.bs_EMPLOYEE_HOURS_MONTHLY
AS
SELECT     dbo.CLOCKCARDS.PAYROLLID, dbo.CLOCKCARDS.EMPNUMBER, SUM(dbo.CLOCKCARDS.NT) AS SUMNT, SUM(dbo.CLOCKCARDS.OT1) AS SUMOT1, 
                      SUM(dbo.CLOCKCARDS.OT2) AS SUMOT2, SUM(dbo.CLOCKCARDS.OT3) AS SUMOT3, SUM(dbo.CLOCKCARDS.OT4) AS SUMOT4, 
                      SUM(dbo.CLOCKCARDS.OT5) AS SUMOT5, YEAR(dbo.PERIODENDDATES.PENDDATE) AS YEARNO, MONTH(dbo.PERIODENDDATES.PENDDATE) 
                      AS MONTHNO
FROM         dbo.CLOCKCARDS INNER JOIN
                      dbo.PERIODENDDATES ON dbo.CLOCKCARDS.PERIODNO = dbo.PERIODENDDATES.PERIODNO AND 
                      dbo.CLOCKCARDS.PAYROLLID = dbo.PERIODENDDATES.PAYROLLID
GROUP BY dbo.CLOCKCARDS.PAYROLLID, dbo.CLOCKCARDS.EMPNUMBER, YEAR(dbo.PERIODENDDATES.PENDDATE), 
                      MONTH(dbo.PERIODENDDATES.PENDDATE)