/****** Object:  View [dbo].[bs_ORDITEMS_SHORT_DESCRIPTION]    Committed by VersionSQL https://www.versionsql.com ******/

    CREATE VIEW bs_ORDITEMS_SHORT_DESCRIPTION    AS    SELECT CONVERT(VARCHAR(255), LEFT(ITEMDESCRIPTION, 255)) AS SHORTDESCRIPTION, ORDID, LINENUMBER    FROM ORDITEMS 