/****** Object:  View [dbo].[bs_PERIODEND_SDL]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE VIEW dbo.bs_PERIODEND_SDL AS SELECT TOP 100 PERCENT PERIODNO, YEARNO, RUNNO, SUM(SDLAMOUNT) AS SDLAMOUNT, PRLID FROM dbo.EMPLOYEESSDL GROUP BY PERIODNO, YEARNO, RUNNO, PRLID ORDER BY PRLID, YEARNO, PERIODNO, RUNNO 