/****** Object:  View [dbo].[bs_PSLP_LOANS]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE VIEW dbo.bs_PSLP_LOANS
AS
SELECT     TOP 100 PERCENT dbo.bs_EMPLOYEE_TOTAL_LOANS.PRLID, dbo.bs_EMPLOYEE_TOTAL_LOANS.EMPNUMBER, 
                      dbo.bs_EMPLOYEE_TOTAL_LOANS.LOANSAMOUNT - dbo.bs_EMPLOYEE_TOTAL_LOANS_PAYMENTS.PAYMENTS AS outstandingloans
FROM         dbo.bs_EMPLOYEE_TOTAL_LOANS LEFT OUTER JOIN
                      dbo.bs_EMPLOYEE_TOTAL_LOANS_PAYMENTS ON 
                      dbo.bs_EMPLOYEE_TOTAL_LOANS.PRLID = dbo.bs_EMPLOYEE_TOTAL_LOANS_PAYMENTS.PRLID AND 
                      dbo.bs_EMPLOYEE_TOTAL_LOANS.EMPNUMBER = dbo.bs_EMPLOYEE_TOTAL_LOANS_PAYMENTS.EMPNUMBER
ORDER BY dbo.bs_EMPLOYEE_TOTAL_LOANS.EMPNUMBER