/****** Object:  View [dbo].[bs_PERIODEND_WCA]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE VIEW dbo.bs_PERIODEND_WCA AS SELECT TOP 100 PERCENT PRLID, PERIODNO, YEARNO, RUNNO, SUM(WCAAMOUNT) AS WCAAMOUNT FROM dbo.EMPLOYEESWCA GROUP BY PRLID, PERIODNO, YEARNO, RUNNO ORDER BY PRLID, YEARNO, PERIODNO, RUNNO 