/****** Object:  View [dbo].[bs_RCS_REM]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE VIEW dbo.bs_RCS_REM
AS
SELECT     TOP 100 PERCENT dbo.EMPED.PRLID, SUM(dbo.EMPED.THEMONEY) AS REMUNERATION, dbo.EMPED.YEARNO, dbo.EMPED.PERIODNO, 
                      dbo.EMPED.EMPNUMBER, dbo.EMPLOYEES.TERMDATE, dbo.EMPED.RUNNO
FROM         dbo.EMPED INNER JOIN
                      dbo.EDSETS ON dbo.EMPED.EDSNUMBER = dbo.EDSETS.EDSNUMBER AND dbo.EMPED.PRLID = dbo.EDSETS.PAYROLLID AND 
                      dbo.EMPED.EDSHID = dbo.EDSETS.EDSHID INNER JOIN
                      dbo.EMPLOYEES ON dbo.EMPED.PRLID = dbo.EMPLOYEES.PAYROLLID AND dbo.EMPED.EMPNUMBER = dbo.EMPLOYEES.EMPNUMBER
WHERE     (dbo.EDSETS.ISDEDUCTION = 0) AND (dbo.EDSETS.ISRSC = 1)
GROUP BY dbo.EMPED.PRLID, dbo.EMPED.YEARNO, dbo.EMPED.PERIODNO, dbo.EMPED.EMPNUMBER, dbo.EMPLOYEES.TERMDATE, 
                      dbo.EMPED.RUNNO
HAVING      (SUM(dbo.EMPED.THEMONEY) <> 0)
ORDER BY dbo.EMPED.PRLID, dbo.EMPED.YEARNO, dbo.EMPED.PERIODNO