/****** Object:  View [dbo].[bs_SUM_DELIVERIES_BY_ORDLINEITEM]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE VIEW dbo.bs_SUM_DELIVERIES_BY_ORDLINEITEM
AS
SELECT     TOP 100 PERCENT SUM(DLVRQTY) AS Expr1, ALLOCATION, ORDID, ORDITEMLINENO
FROM         dbo.DELIVERIES
GROUP BY ALLOCATION, ORDID, ORDITEMLINENO
ORDER BY ORDID, ORDITEMLINENO