/****** Object:  View [dbo].[bs_YTD_PSLP_DEDU]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE VIEW dbo.bs_YTD_PSLP_DEDU
AS
SELECT     TOP 100 PERCENT dbo.EMPED.PRLID, dbo.EMPED.EMPNUMBER, SUM(dbo.EMPED.THEMONEY) AS THEMONEY, dbo.EMPED.YEARNO, 
                      dbo.EMPED.EDSHID, dbo.EMPED.EDSNUMBER, dbo.EDSETS.ISDEDUCTION
FROM         dbo.EMPED INNER JOIN
                      dbo.EDSETS ON dbo.EMPED.EDSNUMBER = dbo.EDSETS.EDSNUMBER AND dbo.EMPED.PRLID = dbo.EDSETS.PAYROLLID AND 
                      dbo.EMPED.EDSHID = dbo.EDSETS.EDSHID
GROUP BY dbo.EMPED.PRLID, dbo.EMPED.EMPNUMBER, dbo.EMPED.YEARNO, dbo.EMPED.EDSHID, dbo.EMPED.EDSNUMBER, 
                      dbo.EDSETS.ISDEDUCTION
HAVING      (dbo.EDSETS.ISDEDUCTION = 1)
ORDER BY dbo.EMPED.PRLID, dbo.EMPED.EMPNUMBER, dbo.EMPED.EDSNUMBER, dbo.EMPED.EDSHID