/****** Object:  View [dbo].[DEBTRECON_ATTRIB]    Committed by VersionSQL https://www.versionsql.com ******/

	CREATE VIEW DEBTRECON_ATTRIB
	AS
	SELECT 
	DEBTRECONS.ORGID AS [ORGID],
	DEBTRECONS.VALNO AS [Valuation Number], 
	ISNULL(DEBTORS.DEBTNUMBER, '') AS [Debtor Code], 
	ISNULL(DEBTORS.DEBTNAME, '') AS [Debtor Name], 
	ACTIVITIES.ACTNAME AS [Activity Name], 
	ACTIVITIES.ActNumber AS [Activity Code],
	ISNULL(CONTRACTS.CONTRNUMBER, '') AS [Contract Code], 
	ISNULL(CONTRACTS.CONTRNAME, '') AS [Contract Name], 
	ISNULL(DEBTRECONS.CONTVALUE, 0) AS [Contract Value], 
	ISNULL(DEBTRECONS.AMOUNTDUE, 0) AS [Amount Due], 
	ISNULL(DEBTRECONS.PREVPAID, 0) AS [Prev Paid], 
	ISNULL(DEBTRECONS.VATAMOUNT, 0) AS [VAT Amount], 
	ISNULL(DEBTRECONS.PAID, 0) AS [Due This Period], 
	DEBTRECONS.USERID [Owner],  
	ISNULL(DEBTRECONS.CONTRATHISMONTH, 0) AS [Contra Charges This Month], 
	ISNULL(DEBTRECONS.CONTRATOT, 0) AS [Contra Charges Total To Date], 
	DEBTRECONS.ORDERNO AS [Order Number], 
	DEBTRECONS.POSTREF AS [Reference], 
	ISNULL(DEBTRECONS.DRAPPDATE, CONVERT(DATETIME, '01/01/1900', 103)) AS [Last Update Date], 
	isnull(DEBTRECONS.CODE, '') AS [Code], 
	DEBTRECONS.CURRENCY AS [Currency], 
	case when DEBTRECONS.LPOSTED = 1 then 'Archived' else case when DEBTRECONS.POSTED = 1 then 'Posted' else 'Active' end end AS [Status], 
	CONVERT(VARCHAR(10), DEBTRECONS.POSTDATE, 103) AS [Last Posted Date],
	DEBTRECONS.CERTNO AS [Invoice Number],
	CONVERT(DATETIME, DEBTRECONS.RETRELEASEDATE, 103) AS [Retention Release Date]
	, A1.VALUE [CONTRACTS Attribute.Client Name], A2.VALUE [CONTRACTS Attribute.CST REGISTRATION NUMBER], A3.VALUE [CONTRACTS Attribute.Location], A4.VALUE [CONTRACTS Attribute.LOI/LOA Date], A5.VALUE [CONTRACTS Attribute.Name of the Work], A6.VALUE [CONTRACTS Attribute.Total Area in Sft], A7.VALUE [CONTRACTS Attribute.Work Order Date], A8.VALUE [CONTRACTS Attribute.Zone], A10.VALUE [DEBTORS Attribute.2-Block], A11.VALUE [DEBTORS Attribute.3-Floor], A12.VALUE [DEBTORS Attribute.4-Flat], A13.VALUE [DEBTORS Attribute.GST], A9.VALUE [DEBTORS Attribute.1-Project]
	FROM DEBTRECONS 
	INNER JOIN DEBTORS ON DEBTORS.DebtID = DEBTRECONS.SubConNumber 
	LEFT OUTER JOIN CONTRACTS ON CONTRACTS.CONTRID = DEBTRECONS.Contract 
	LEFT OUTER JOIN ACTIVITIES ON ACTIVITIES.ActID = DEBTRECONS.Activity 
	 LEFT OUTER JOIN ATTRIBVALUE A1 on A1.TABLENAME = 'CONTRACTS' and A1.ATTRIBUTE = 'Client Name' and A1.COLKEY = CONTRACTS.CONTRNUMBER and A1.ARRAYINDEX = 0 LEFT OUTER JOIN ATTRIBVALUE A2 on A2.TABLENAME = 'CONTRACTS' and A2.ATTRIBUTE = 'CST REGISTRATION NUMBER' and A2.COLKEY = CONTRACTS.CONTRNUMBER and A2.ARRAYINDEX = 0 LEFT OUTER JOIN ATTRIBVALUE A3 on A3.TABLENAME = 'CONTRACTS' and A3.ATTRIBUTE = 'Location' and A3.COLKEY = CONTRACTS.CONTRNUMBER and A3.ARRAYINDEX = 0 LEFT OUTER JOIN ATTRIBVALUE A4 on A4.TABLENAME = 'CONTRACTS' and A4.ATTRIBUTE = 'LOI/LOA Date' and A4.COLKEY = CONTRACTS.CONTRNUMBER and A4.ARRAYINDEX = 0 LEFT OUTER JOIN ATTRIBVALUE A5 on A5.TABLENAME = 'CONTRACTS' and A5.ATTRIBUTE = 'Name of the Work' and A5.COLKEY = CONTRACTS.CONTRNUMBER and A5.ARRAYINDEX = 0 LEFT OUTER JOIN ATTRIBVALUE A6 on A6.TABLENAME = 'CONTRACTS' and A6.ATTRIBUTE = 'Total Area in Sft' and A6.COLKEY = CONTRACTS.CONTRNUMBER and A6.ARRAYINDEX = 0 LEFT OUTER JOIN ATTRIBVALUE A7 on A7.TABLENAME = 'CONTRACTS' and A7.ATTRIBUTE = 'Work Order Date' and A7.COLKEY = CONTRACTS.CONTRNUMBER and A7.ARRAYINDEX = 0 LEFT OUTER JOIN ATTRIBVALUE A8 on A8.TABLENAME = 'CONTRACTS' and A8.ATTRIBUTE = 'Zone' and A8.COLKEY = CONTRACTS.CONTRNUMBER and A8.ARRAYINDEX = 0 LEFT OUTER JOIN ATTRIBVALUE A10 on A10.TABLENAME = 'DEBTORS' and A10.ATTRIBUTE = '2-Block' and A10.COLKEY = DEBTORS.DEBTNUMBER and A10.ARRAYINDEX = 0 LEFT OUTER JOIN ATTRIBVALUE A11 on A11.TABLENAME = 'DEBTORS' and A11.ATTRIBUTE = '3-Floor' and A11.COLKEY = DEBTORS.DEBTNUMBER and A11.ARRAYINDEX = 0 LEFT OUTER JOIN ATTRIBVALUE A12 on A12.TABLENAME = 'DEBTORS' and A12.ATTRIBUTE = '4-Flat' and A12.COLKEY = DEBTORS.DEBTNUMBER and A12.ARRAYINDEX = 0 LEFT OUTER JOIN ATTRIBVALUE A13 on A13.TABLENAME = 'DEBTORS' and A13.ATTRIBUTE = 'GST' and A13.COLKEY = DEBTORS.DEBTNUMBER and A13.ARRAYINDEX = 0 LEFT OUTER JOIN ATTRIBVALUE A9 on A9.TABLENAME = 'DEBTORS' and A9.ATTRIBUTE = '1-Project' and A9.COLKEY = DEBTORS.DEBTNUMBER and A9.ARRAYINDEX = 0