/****** Object:  View [dbo].[INVENTORY_ATTRIBUTES]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE VIEW INVENTORY_ATTRIBUTES AS SELECT INVENTORY.* , A21.VALUE [Attribute.HSN Code] FROM INVENTORY  LEFT OUTER JOIN ATTRIBVALUE A21 on A21.TABLENAME = 'INVENTORY' and A21.ATTRIBUTE = 'HSN Code' and A21.COLKEY = INVENTORY.STKID and A21.ARRAYINDEX = 0