/****** Object:  View [dbo].[POS_User_Access_Per_Borg]    Committed by VersionSQL https://www.versionsql.com ******/

 
CREATE VIEW POS_User_Access_Per_Borg as 
SELECT USERSINBORGP.BORGID [Org ID], USERSINBORGP.USERID [User ID], USERS.LOGINID [Login ID], USERS.USERNAME [User Name], ROLEHEADERP.ROLENAME [Role], 
USERSINBORGP.CANOVERDLVR AS [Can Accept Over Delivery], USERSINBORGP.EXTPO AS [Can Create PO for External Org], 
USERSINBORGP.CANNEGDLVR AS [Can Take Negative Deliveries]
FROM USERS 
INNER JOIN USERSINBORGP ON USERS.USERID = USERSINBORGP.USERID 
INNER JOIN ROLEHEADERP ON USERSINBORGP.ROLEID = ROLEHEADERP.ROLEID