/****** Object:  View [dbo].[REQAPPROVALS]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE VIEW REQAPPROVALS as SELECT REQ.REQNUMBER [Requisition Number], 
REQ.REQSUBJECT [Subject], 
USERS.USERNAME AS Creator, 
convert(datetime, CONVERT(nvarchar(15), REQ.CREATEDATE, 106) + ' ' + CONVERT(nvarchar(15), REQ.CREATEDATE, 108)) AS [Create Date], 
REQ.SHORTDESCR [Short Description], 
CASE REQ.REQSTATUSID 
	WHEN 26 THEN 'Approved' 
	WHEN 32 THEN 'Awaiting Approval' 
	WHEN 36 THEN 'Cancelled' 
	WHEN 163 THEN 'Open' 
	WHEN 173 THEN 'PO Created' 
	WHEN 202 THEN 'Rejected' 
	WHEN 500 THEN 'Change Order Process' 
	WHEN 99 THEN 'Owner Changed' 
	WHEN 98 THEN 'Submitted' 
	WHEN 97 THEN 'Approver Changed' 
	WHEN 501 THEN 'Change Order Done' 
	WHEN 808 THEN 'ERFQ Pending' 
END AS [Current Status], 
BORGS.BORGNAME AS Organization,  
convert(datetime, CONVERT(nvarchar(15), isnull(REQAPPROVALHIST.THEDATE, isnull(REQ.LASTCHANGE,REQ.CREATEDATE)), 106) + ' ' + CONVERT(nvarchar(15), isnull(REQAPPROVALHIST.THEDATE, isnull(REQ.LASTCHANGE,REQ.CREATEDATE)), 108)) AS [Action Date], 
CURRENCIES.CURRCODE + ' - ' + CURRENCIES.CURRNAME AS Currency, 
ISNULL(NEXTAPPR.USERNAME, 'Any Selected Approver') AS [Selected Approver], 
ISNULL(USERSAPPR.USERNAME, '') AS [Approver Name], 
CASE isnull(REQAPPROVALHIST.REQSTATUSID, REQ.REQSTATUSID)
	WHEN 26 THEN 'Approved' 
	WHEN 32 THEN 'Awaiting Approval' 
	WHEN 36 THEN 'Cancelled' 
	WHEN 163 THEN 'Open' 
	WHEN 173 THEN 'PO Created' 
	WHEN 202 THEN 'Rejected'
	WHEN 500 THEN 'Change Order Process' 
	WHEN 99 THEN 'Owner Changed' 
	WHEN 98 THEN 'Submitted' 
	WHEN 97 THEN 'Approver Changed' 
	WHEN 501 THEN 'Change Order Done' 
	WHEN 808 THEN 'ERFQ Pending' 
END AS [Action], 
ISNULL(REQAPPROVALHIST.DESCRIPTION, '') AS Description,
ISNULL(WORKFLOWHEADER.DESCR, '') AS [Workflow Header], 
ISNULL(WORKFLOWDETAIL.DESCR, '') AS [Workflow Description], 
ISNULL(WORKFLOWDETAIL.SEQ, - 1) AS [Workflow Sequence],   
ISNULL(U2.USERNAME, '') AS [Workflow User Name], 
ISNULL(REQAPPROVALHIST.WFVALUEAPPROVED, '') AS [Workflow Value Approved],
isnull(REQITEMSSUMM.AMOUNT, 0) [Value], isnull(REQITEMSSUMM.BLANKSUPP, 0) [Blank Supplier], isnull(REQITEMSSUMM.REQITEMSCOUNT, 0) [Line Items]
FROM REQ 
LEFT OUTER JOIN USERS AS USERS ON REQ.ORIGUSERID = USERS.USERID 
LEFT OUTER JOIN REQAPPROVALHIST ON REQ.REQID = REQAPPROVALHIST.REQID 
LEFT OUTER JOIN USERS AS USERSAPPR ON isnull(REQAPPROVALHIST.USERID, REQ.LASTCHANGEBY) = USERSAPPR.USERID 
LEFT JOIN BORGS ON REQ.BORGID = BORGS.BORGID 
LEFT JOIN CURRENCIES ON REQ.CURRENCY = CURRENCIES.CURRCODE 
LEFT OUTER JOIN USERS AS NEXTAPPR ON REQ.APPROVER = NEXTAPPR.USERID 
LEFT OUTER JOIN WORKFLOWDETAIL ON WORKFLOWDETAIL.WDID = REQAPPROVALHIST.WDID 
LEFT OUTER JOIN WORKFLOWHEADER ON WORKFLOWHEADER.WHID = WORKFLOWDETAIL.WHID 
LEFT OUTER JOIN USERS AS U2 ON WORKFLOWDETAIL.USERID = U2.USERID
OUTER APPLY (
	select 
	count (DISTINCT  REQITEMS.LINENUMBER) REQITEMSCOUNT,
	sum((REQITEMS.QTY * REQITEMS.PRICE * (1 - (REQITEMS.DISCOUNT / 100))) + (REQITEMS.VATAMOUNT)) as AMOUNT,
	sum(case when isnull(REQITEMS.SUPPID, -1) < 0 then 1 else 0 end) BLANKSUPP
	from REQITEMS	
	WHERE REQITEMS.REQID = REQ.REQID
	group by REQITEMS.REQID
) REQITEMSSUMM 