/****** Object:  View [dbo].[SUBCRECON_ATTRIB]    Committed by VersionSQL https://www.versionsql.com ******/

	CREATE VIEW SUBCRECON_ATTRIB
	AS
	SELECT
	SUBCRECONS.ORGID AS [ORGID],
	SUBCRECONS.VALNO AS [Valuation Number], 
	ISNULL(SUBCONTRACTORS.SUBNUMBER, '') AS [Sub Contractor Code], 
	ISNULL(SUBCONTRACTORS.SUBNAME, '') AS [Sub Contractor Name], 
	ACTIVITIES.ACTNAME AS [Activity Name], 
	ACTIVITIES.ActNumber AS [Activity Code],
	ISNULL(CONTRACTS.CONTRNUMBER, '') AS [Contract Code], 
	ISNULL(CONTRACTS.CONTRNAME, '') AS [Contract Name], 
	ISNULL(SUBCRECONS.CONTVALUE, 0) AS [Contract Value], 
	ISNULL(SUBCRECONS.AMOUNTDUE, 0) AS [Amount Due], 
	ISNULL(SUBCRECONS.PREVPAID, 0) AS [Prev Paid], 
	ISNULL(SUBCRECONS.VATAMOUNT, 0) AS [VAT Amount], 
	ISNULL(SUBCRECONS.PAID, 0) AS [Due This Period], 
	SUBCRECONS.USERID [Owner],  
	ISNULL(SUBCRECONS.CONTRATHISMONTH, 0) AS [Contra Charges This Month], 
	ISNULL(SUBCRECONS.CONTRATOT, 0) AS [Contra Charges Total To Date], 
	SUBCRECONS.ORDERNO AS [Order Number], 
	SUBCRECONS.POSTREF AS [Reference], 
	ISNULL(SUBCRECONS.SCAPPDATE, CONVERT(DATETIME, '01/01/1900', 103)) AS [Last Update Date], 
	isnull(SUBCRECONS.CODE, '') AS [Code], 
	SUBCRECONS.CURRENCY AS [Currency], 
	case when SUBCRECONS.LPOSTED=1 then 'Archived' else case when SUBCRECONS.POSTED = 1 then 'Posted' else 'Active' end end AS [Status], 
	CONVERT(VARCHAR(10), SUBCRECONS.POSTDATE, 103) AS [Last Posted Date],
	SUBCRECONS.CERTNO AS [Invoice Number],
	case when ISNULL(BOQ.RECONID, -1) = -1 then 'Yes' else 'No' end AS HASBOQ, 
	ISNULL(PROVINCES.PROVINCENAME,'UNKNOWN') AS [Province],  
	ISNULL(SUBCRECONS.WORKDONETOT, 0) AS [Total Work Done],
	CONVERT(DATETIME, SUBCRECONS.RETRELEASEDATE, 103) AS [Retention Release Date]
	, A1.VALUE [CONTRACTS Attribute.Client Name], A2.VALUE [CONTRACTS Attribute.CST REGISTRATION NUMBER], A3.VALUE [CONTRACTS Attribute.Location], A4.VALUE [CONTRACTS Attribute.LOI/LOA Date], A5.VALUE [CONTRACTS Attribute.Name of the Work], A6.VALUE [CONTRACTS Attribute.Total Area in Sft], A7.VALUE [CONTRACTS Attribute.Work Order Date], A8.VALUE [CONTRACTS Attribute.Zone], A14.VALUE [SUBCRECONS Attribute.EC], A15.VALUE [SUBCRECONS Attribute.EI]
	FROM SUBCRECONS
	INNER JOIN SUBCONTRACTORS ON SUBCONTRACTORS.SUBID = SUBCRECONS.SUBCONNUMBER
	LEFT OUTER JOIN CONTRACTS ON CONTRACTS.CONTRID = SUBCRECONS.CONTRACT
	LEFT OUTER JOIN ACTIVITIES ON ACTIVITIES.ACTID = SUBCRECONS.ACTIVITY
	LEFT OUTER JOIN PROVINCES ON PROVINCES.PROVINCEID = SUBCONTRACTORS.PROVINCEID
	LEFT OUTER JOIN ACCBOQHEADER BOQ ON BOQ.RECONID = SUBCRECONS.RECONID
	 LEFT OUTER JOIN ATTRIBVALUE A1 on A1.TABLENAME = 'CONTRACTS' and A1.ATTRIBUTE = 'Client Name' and A1.COLKEY = CONTRACTS.CONTRNUMBER and A1.ARRAYINDEX = 0 LEFT OUTER JOIN ATTRIBVALUE A2 on A2.TABLENAME = 'CONTRACTS' and A2.ATTRIBUTE = 'CST REGISTRATION NUMBER' and A2.COLKEY = CONTRACTS.CONTRNUMBER and A2.ARRAYINDEX = 0 LEFT OUTER JOIN ATTRIBVALUE A3 on A3.TABLENAME = 'CONTRACTS' and A3.ATTRIBUTE = 'Location' and A3.COLKEY = CONTRACTS.CONTRNUMBER and A3.ARRAYINDEX = 0 LEFT OUTER JOIN ATTRIBVALUE A4 on A4.TABLENAME = 'CONTRACTS' and A4.ATTRIBUTE = 'LOI/LOA Date' and A4.COLKEY = CONTRACTS.CONTRNUMBER and A4.ARRAYINDEX = 0 LEFT OUTER JOIN ATTRIBVALUE A5 on A5.TABLENAME = 'CONTRACTS' and A5.ATTRIBUTE = 'Name of the Work' and A5.COLKEY = CONTRACTS.CONTRNUMBER and A5.ARRAYINDEX = 0 LEFT OUTER JOIN ATTRIBVALUE A6 on A6.TABLENAME = 'CONTRACTS' and A6.ATTRIBUTE = 'Total Area in Sft' and A6.COLKEY = CONTRACTS.CONTRNUMBER and A6.ARRAYINDEX = 0 LEFT OUTER JOIN ATTRIBVALUE A7 on A7.TABLENAME = 'CONTRACTS' and A7.ATTRIBUTE = 'Work Order Date' and A7.COLKEY = CONTRACTS.CONTRNUMBER and A7.ARRAYINDEX = 0 LEFT OUTER JOIN ATTRIBVALUE A8 on A8.TABLENAME = 'CONTRACTS' and A8.ATTRIBUTE = 'Zone' and A8.COLKEY = CONTRACTS.CONTRNUMBER and A8.ARRAYINDEX = 0 LEFT OUTER JOIN ATTRIBVALUE A14 on A14.TABLENAME = 'SUBCRECONS' and A14.ATTRIBUTE = 'EC' and A14.COLKEY = SUBCRECONS.ReconID and A14.ARRAYINDEX = 0 LEFT OUTER JOIN ATTRIBVALUE A15 on A15.TABLENAME = 'SUBCRECONS' and A15.ATTRIBUTE = 'EI' and A15.COLKEY = SUBCRECONS.ReconID and A15.ARRAYINDEX = 0