/****** Object:  View [dbo].[SUBCONTRACTORS_ATTRIBUTES]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE VIEW SUBCONTRACTORS_ATTRIBUTES AS SELECT SUBCONTRACTORS.* , A28.VALUE [Attribute.GST] FROM SUBCONTRACTORS  LEFT OUTER JOIN ATTRIBVALUE A28 on A28.TABLENAME = 'SUBCONTRACTORS' and A28.ATTRIBUTE = 'GST' and A28.COLKEY = SUBCONTRACTORS.SUBNUMBER and A28.ARRAYINDEX = 0