/****** Object:  View [dbo].[TempStampListing]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE VIEW dbo.TempStampListing
AS
SELECT     TOP 100 PERCENT dbo.CLOCKCARDS.WEEKNO, SUM(dbo.CLOCKCARDS.STAMPHOURS) AS sumstamphours, dbo.STAMPSETS.REGNO, 
                      dbo.EMPLOYEES.SSCODE, dbo.STAMPSETS.SSCATEGORY, dbo.STAMPSETS.MINHRS, dbo.EMPLOYEES.PAYROLLID, dbo.EMPLOYEES.EMPNAME, 
                      dbo.STAMPSETS.SSTOTAL, dbo.STAMPSETS.SSNAME, dbo.CLOCKCARDS.PERIODNO, dbo.CLOCKCARDS.RUNNO, dbo.CLOCKCARDS.YEARNO, 
                      dbo.BORGS.BORGNAME, dbo.EMPLOYEES.IDNUM, dbo.EMPLOYEES.HFNUMBER, dbo.EMPLOYEES.BIRTHDAY, dbo.EMPLOYEES.TAXNUMBER, 
                      dbo.EMPLOYEES.EMPNUMBER, dbo.EMPLOYEES.SURNAME, dbo.EMPLOYEES.INITIALS
FROM         dbo.CLOCKCARDS INNER JOIN
                      dbo.EMPLOYEES ON dbo.CLOCKCARDS.PAYROLLID = dbo.EMPLOYEES.PAYROLLID AND 
                      dbo.CLOCKCARDS.EMPNUMBER = dbo.EMPLOYEES.EMPNUMBER INNER JOIN
                      dbo.STAMPSETS ON dbo.EMPLOYEES.EDSHID = dbo.STAMPSETS.EDSHID AND dbo.EMPLOYEES.SSCODE = dbo.STAMPSETS.SSCODE INNER JOIN
                      dbo.PAYROLLS ON dbo.EMPLOYEES.PAYROLLID = dbo.PAYROLLS.PAYROLLID INNER JOIN
                      dbo.BORGS ON dbo.PAYROLLS.BORGID = dbo.BORGS.BORGID
WHERE     (NOT (dbo.EMPLOYEES.SSCODE IS NULL)) AND (dbo.EMPLOYEES.SSCATEGORY = dbo.STAMPSETS.SSCATEGORY) AND 
                      (dbo.EMPLOYEES.SSCODE <> N'') OR
                      (dbo.EMPLOYEES.SSCODE <> N'') AND (dbo.EMPLOYEES.SSCATEGORY = N'') AND (dbo.EMPLOYEES.RATE1 >= dbo.STAMPSETS.FROMVAL) AND 
                      (dbo.EMPLOYEES.RATE1 <= dbo.STAMPSETS.TOVAL)
GROUP BY dbo.EMPLOYEES.SSCODE, dbo.STAMPSETS.SSCATEGORY, dbo.CLOCKCARDS.WEEKNO, dbo.STAMPSETS.MINHRS, dbo.EMPLOYEES.PAYROLLID, 
                      dbo.EMPLOYEES.EMPNAME, dbo.STAMPSETS.SSTOTAL, dbo.STAMPSETS.SSNAME, dbo.CLOCKCARDS.PERIODNO, dbo.CLOCKCARDS.RUNNO, 
                      dbo.CLOCKCARDS.YEARNO, dbo.BORGS.BORGNAME, dbo.STAMPSETS.REGNO, dbo.EMPLOYEES.IDNUM, dbo.EMPLOYEES.HFNUMBER, 
                      dbo.EMPLOYEES.BIRTHDAY, dbo.EMPLOYEES.TAXNUMBER, dbo.EMPLOYEES.EMPNUMBER, dbo.EMPLOYEES.SURNAME, 
                      dbo.EMPLOYEES.INITIALS