/****** Object:  Procedure [dbo].[BHOOPATHI]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE BHOOPATHI
AS

SELECT ORDID,ORDNUMBER,BORGID,USERID,CREATEDATE,SHORTDESCR,REQID 
INTO #ORD
FROM ORD WHERE SUPPID=2704

ALTER TABLE #ORD ADD PROJECTNAME VARCHAR(200)
UPDATE #ORD SET PROJECTNAME=B.BORGNAME FROM BORGS B INNER JOIN #ORD  ON #ORD.BORGID=B.BORGID 

SELECT ORDID,LINENUMBER,ITEMDESCRIPTION,UOM,QTY,PRICE,INSTRUCTIONS
INTO #ORDITEMS 
FROM ORDITEMS WHERE ORDID IN (SELECT ORDID FROM #ORD)

 
SELECT REQID,SEQ,USERID,DESCRIPTION,THEDATE APPROVALDATE 
INTO #APPROVALHIST 
FROM REQAPPROVALHIST 
WHERE REQID IN (SELECT REQID FROM #ORD) ORDER BY REQID 

ALTER TABLE #APPROVALHIST ADD USERNAME VARCHAR(100)
UPDATE #APPROVALHIST SET USERNAME=U.USERNAME FROM USERS U INNER JOIN #APPROVALHIST ON #APPROVALHIST.USERID=U.USERID 

SELECT * FROM #ORD ORDER BY REQID 
SELECT * FROM #ORDITEMS 
SELECT * FROM #APPROVALHIST ORDER BY REQID,SEQ 