/****** Object:  Procedure [dbo].[VR790]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE VR790
AS            
DECLARE @ASSETID INT
DECLARE @LASTCOUNT INT
DECLARE ASSETREC CURSOR FOR 
SELECT DISTINCT ASSETID FROM BI.ASSETPOSTS 
OPEN ASSETREC 
FETCH NEXT FROM ASSETREC INTO @ASSETID 
WHILE @@FETCH_STATUS=0
BEGIN
    SELECT @LASTCOUNT=CURRNETCOUNT   FROM BI.ASSETPOSTS WHERE ASSETID=@ASSETID AND PERIOD=10
	UPDATE BI.ASSETPOSTS  SET CURRNETCOUNT= @LASTCOUNT-1 WHERE  ASSETID=@ASSETID AND PERIOD=9
	UPDATE BI.ASSETPOSTS  SET CURRNETCOUNT= @LASTCOUNT-2 WHERE  ASSETID=@ASSETID AND PERIOD=8
	UPDATE BI.ASSETPOSTS  SET CURRNETCOUNT= @LASTCOUNT-3 WHERE  ASSETID=@ASSETID AND PERIOD=7
	UPDATE BI.ASSETPOSTS  SET CURRNETCOUNT= @LASTCOUNT-4 WHERE  ASSETID=@ASSETID AND PERIOD=6
	UPDATE BI.ASSETPOSTS  SET CURRNETCOUNT= @LASTCOUNT-5 WHERE  ASSETID=@ASSETID AND PERIOD=5
	UPDATE BI.ASSETPOSTS  SET CURRNETCOUNT= @LASTCOUNT-6 WHERE  ASSETID=@ASSETID AND PERIOD=4
	UPDATE BI.ASSETPOSTS  SET CURRNETCOUNT= @LASTCOUNT-7 WHERE  ASSETID=@ASSETID AND PERIOD=3
	UPDATE BI.ASSETPOSTS  SET CURRNETCOUNT= @LASTCOUNT-8 WHERE  ASSETID=@ASSETID AND PERIOD=2
	UPDATE BI.ASSETPOSTS  SET CURRNETCOUNT= @LASTCOUNT-0 WHERE  ASSETID=@ASSETID AND PERIOD=1
	UPDATE BI.ASSETPOSTS  SET CURRNETCOUNT= @LASTCOUNT-10 WHERE  ASSETID=@ASSETID AND PERIOD=0
	FETCH NEXT FROM ASSETREC INTO @ASSETID 
END
CLOSE ASSETREC
DEALLOCATE ASSETREC