/****** Object:  Procedure [dbo].[VRASSETMONIUPDATE]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE VRASSETMONIUPDATE
AS

DECLARE @ASSETNUMBER VARCHAR(15)
DECLARE @AMOUNT DECIMAL(18,2)
DECLARE @ASSETID INT

UPDATE ASSETS SET AssetAccumDep=0.0

DECLARE VINODS CURSOR FOR
SELECT * FROM VRASSETMONI  

OPEN VINODS

FETCH NEXT FROM VINODS INTO @ASSETNUMBER,@AMOUNT,@ASSETID 

WHILE @@FETCH_STATUS=0
BEGIN
  
  

  UPDATE  ASSETS SET AssetAccumDep = @AMOUNT WHERE ASSETID=@ASSETID 

  FETCH NEXT FROM VINODS INTO @ASSETNUMBER,@AMOUNT,@ASSETID 

END
CLOSE VINODS
DEALLOCATE VINODS 

SELECT SUM(AMOUNT) FROM ASSETMONI  
SELECT SUM(AssetAccumDep) FROM ASSETS 