/****** Object:  Procedure [dbo].[VRCHECKGARDENCITY]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE VRCHECKGARDENCITY
AS 
SELECT ITEMID INTO #TEMP0 FROM TENDERITEMS WHERE BORG=191 AND CATEGORY='SUBCONTRACTORS'
SELECT * FROM #TEMP0 ORDER BY ITEMID 
SELECT  CATALOGITEMID,REQID, QTY, (QTY*PRICE) AMOUNT  INTO #ORDERED 
FROM REQITEMS WHERE CATALOGITEMID IN (SELECT  ITEMID FROM #TEMP0)

SELECT * FROM #ORDERED 
SELECT REQID,CATALOGITEMID,SUM(QTY) QTY, SUM(AMOUNT) BUDGETAMOUNT
INTO #BUDGETS
FROM #ORDERED 
GROUP BY REQID,CATALOGITEMID 
SELECT * FROM TENDERITEMS WHERE ITEMID=915
SELECT * FROM #BUDGETS ORDER BY CATALOGITEMID 

DECLARE @ID INT
DECLARE @QTY DECIMAL(18,4) 
DECLARE @AMOUNT DECIMAL(18,4) 

DECLARE VINOD CURSOR FOR  SELECT  CATALOGITEMID,QTY,BUDGETAMOUNT FROM #BUDGETS 
OPEN VINOD
FETCH NEXT FROM VINOD INTO @ID,@QTY,@AMOUNT 
WHILE @@FETCH_STATUS=0
BEGIN
UPDATE TENDERITEMS SET ORDEREDQTY = ORDEREDQTY+@QTY, ORDEREDAMOUNT=ORDEREDAMOUNT+@AMOUNT WHERE ITEMID=@ID 
FETCH NEXT FROM VINOD INTO @ID,@QTY,@AMOUNT 
END
CLOSE VINOD
DEALLOCATE VINOD