/****** Object:  Table [BS].[ASSSETDEPHISTORY]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [BS].[ASSSETDEPHISTORY](
	[HISTORYID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[ASSETID] [int] NULL,
	[ASSETNUMBER] [varchar](30) NULL,
	[FINYEAR] [int] NULL,
	[PERIOD] [int] NULL,
	[DEPCOUNT] [int] NULL,
	[DEPAMOUNT] [decimal](18, 2) NULL,
PRIMARY KEY CLUSTERED 
(
	[HISTORYID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]