/****** Object:  Table [BS].[CASHFLOWINDICATORS_NEW]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [BS].[CASHFLOWINDICATORS_NEW](
	[PRIMARYID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[PAGENO] [int] NULL,
	[POSTIONINDEX] [decimal](6, 2) NULL,
	[COLINDEX] [int] NULL,
	[INDEXCODE] [int] NULL,
	[CATEGORY] [int] NULL,
	[COLID] [varchar](10) NULL,
	[DESCRIPTION] [varchar](50) NULL,
	[FONTID] [int] NULL,
	[AMOUNT] [decimal](18, 2) NULL,
 CONSTRAINT [PK__CASHFLOW__2C4884CA77025E03] PRIMARY KEY CLUSTERED 
(
	[PRIMARYID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]