/****** Object:  Table [BS].[PAYBATCHWORKFLOW]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [BS].[PAYBATCHWORKFLOW](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[FROMROLEID] [int] NULL,
	[BATCHTYPE] [char](1) NULL,
	[TOROLEID] [int] NULL,
	[DEFAULTLOGINID] [varchar](15) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]