/****** Object:  Table [BS].[PAYBATCHROLES]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [BS].[PAYBATCHROLES](
	[BATCHROLEID] [int] IDENTITY(1,1) NOT NULL,
	[ROLENAME] [varchar](55) NULL,
	[BSROLEHEADID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[BATCHROLEID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]