/****** Object:  Table [BS].[PAYBATCHMASTER]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [BS].[PAYBATCHMASTER](
	[BATCHID] [int] IDENTITY(1,1) NOT NULL,
	[BATCHNO] [int] NULL,
	[BATORGID] [int] NULL,
	[BATPROCESS] [char](1) NULL,
	[BATCHSTATUS] [int] NULL,
	[CURRENTLOGINID] [varchar](15) NULL,
	[CURRENTROLEID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[BATCHID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]