/****** Object:  Table [BS].[PAYBATCHUSERS]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [BS].[PAYBATCHUSERS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[LOGINID] [varchar](15) NULL,
	[USERNAME] [varchar](50) NULL,
	[LOGINTYPE] [varchar](25) NULL,
	[BATCHROLEID] [int] NULL,
 CONSTRAINT [PK__PAYBATCH__3214EC270A2E7149] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]