/****** Object:  Table [BS].[SPLITSUBCONS]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [BS].[SPLITSUBCONS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[TRANSID] [int] NULL,
	[AMOUNT_HOLD] [decimal](18, 2) NULL,
	[AMOUNT_KNOCK] [decimal](18, 2) NULL,
	[TOTALA] [decimal](18, 2) NULL,
	[TOTALFROMT] [decimal](18, 2) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]