/****** Object:  Table [BS].[STATIONARYMASTER]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [BS].[STATIONARYMASTER](
	[MATERIALCODE] [varchar](15) NOT NULL,
	[MATERIALNAME] [varchar](255) NULL,
	[UOM] [varchar](25) NULL,
	[STOCKID] [int] NULL,
	[CONVERSIONFATCTOR] [decimal](8, 2) NULL,
	[LASTPURCHASERATE] [decimal](18, 2) NULL,
 CONSTRAINT [PK__STATIONA__68C19A537C0E7A71] PRIMARY KEY CLUSTERED 
(
	[MATERIALCODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]