/****** Object:  Table [BS].[STOCKARCHIEVE]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [BS].[STOCKARCHIEVE](
	[CURRENTDATE] [datetime] NULL,
	[STORE] [varchar](15) NULL,
	[STOCKCODE] [varchar](15) NULL,
	[STKQUANTITY] [decimal](18, 4) NULL,
	[STKRATE] [decimal](18, 2) NULL,
	[ID] [bigint] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
 CONSTRAINT [PK_STOCKARCHIEVE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]