/****** Object:  Table [EC].[OPENINGBALANCE]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [EC].[OPENINGBALANCE](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ORGID] [int] NULL,
	[FINYEAR] [int] NULL,
	[PERIOD] [int] NULL,
	[CATEGORY] [varchar](25) NULL,
	[ACTIVITYCODE] [varchar](15) NULL,
	[AMOUNT] [decimal](18, 2) NULL,
 CONSTRAINT [PK_OPENINGBALANCE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]