/****** Object:  Table [EC].[SALESDETAILS]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [EC].[SALESDETAILS](
	[ENGCODEINDEX] [int] IDENTITY(1,1) NOT NULL,
	[ORGID] [int] NULL,
	[RECONID] [int] NULL,
	[LEDGERCODE] [varchar](15) NULL,
	[ACTIVITYCODE] [int] NULL,
	[AMOUNT] [decimal](18, 2) NULL,
	[REVERSALRECONID] [int] NULL,
	[TRANGRP] [int] NULL,
 CONSTRAINT [PK_ENGINEERINGCODES] PRIMARY KEY CLUSTERED 
(
	[ENGCODEINDEX] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]