/****** Object:  Table [EC].[SUBBIEHEADER]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [EC].[SUBBIEHEADER](
	[HEADERID] [int] IDENTITY(1,1) NOT NULL,
	[RECONID] [int] NULL,
	[VALNO] [int] NULL,
	[CERTNO] [varchar](15) NULL,
	[POSTREF] [varchar](25) NULL,
	[TRANGRP] [int] NULL,
 CONSTRAINT [PK__SUBBIEHE__134054187340DCCE] PRIMARY KEY CLUSTERED 
(
	[HEADERID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]