/****** Object:  Table [EC].[SUBBIEDETAILS]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [EC].[SUBBIEDETAILS](
	[ENGCODEINDEX] [bigint] IDENTITY(1,1) NOT NULL,
	[HEADERID] [int] NULL,
	[ACCBOQDETAILID] [bigint] NULL,
	[ORDID] [bigint] NULL,
	[LINENUMBER] [int] NULL,
	[LEDGERCODE] [varchar](15) NULL,
	[ECCATEGORY] [varchar](25) NULL,
	[ACTIVITYCODE] [varchar](15) NULL,
	[QTY] [decimal](18, 2) NULL,
	[RATE] [decimal](18, 2) NULL,
	[AMOUNT] [decimal](18, 2) NULL,
 CONSTRAINT [PK__ENGCODES__D7121499D36DCD10] PRIMARY KEY CLUSTERED 
(
	[ENGCODEINDEX] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]