/****** Object:  Table [PB].[APPROVALLEVELS]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [PB].[APPROVALLEVELS](
	[APPROVERLEVELID] [int] NOT NULL,
	[LEVELCODE] [int] NULL,
	[LEVELID] [varchar](10) NULL,
	[LEVELNAME] [varchar](50) NULL,
 CONSTRAINT [PK_APPROVALLEVELS] PRIMARY KEY CLUSTERED 
(
	[APPROVERLEVELID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]