/****** Object:  Table [PB].[BATCHLOG]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [PB].[BATCHLOG](
	[LOGID] [int] IDENTITY(1,1) NOT NULL,
	[BATCHID] [int] NULL,
	[DETAILID] [int] NULL,
	[APPROVALLEVELID] [int] NULL,
	[LOGINID] [varchar](15) NULL,
	[TIMESTAMP] [datetime] NULL,
 CONSTRAINT [PK__BATCHLOG__E39E279EA672D0AE] PRIMARY KEY CLUSTERED 
(
	[LOGID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]