/****** Object:  Table [PB].[BENEFICIARYBANKS]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [PB].[BENEFICIARYBANKS](
	[INDEXNO] [int] IDENTITY(1,1) NOT NULL,
	[PARTYCODE] [varchar](20) NULL,
	[PARTYNAME] [varchar](200) NULL,
	[PARTYTYPE] [varchar](20) NULL,
	[BENEFICIARYNAME] [varchar](200) NULL,
	[BENEFICIARYBANKACCOUNTNUMBER] [varchar](50) NULL,
	[BANKNAME] [varchar](150) NULL,
	[BRANCHNAME] [varchar](150) NULL,
	[IFSCCODE] [varchar](50) NULL,
	[ADDRESS1] [varchar](250) NULL,
	[ADDRESS2] [varchar](250) NULL,
	[ADDRESS3] [varchar](250) NULL,
	[EMAILID] [varchar](150) NULL,
	[UPDATED] [int] NULL,
 CONSTRAINT [PK__BENEFICI__39195AC2D796A78A] PRIMARY KEY CLUSTERED 
(
	[INDEXNO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]