/****** Object:  Table [PB].[PAYMENTBATCHUSERS]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [PB].[PAYMENTBATCHUSERS](
	[BSLOGINID] [varchar](15) NOT NULL,
	[BSUSERNAME] [varchar](50) NULL,
	[BSPASSWORD] [varchar](15) NULL,
	[APPROVERLEVELID] [int] NULL,
	[UPLOADRIGHTS] [int] NULL,
 CONSTRAINT [PK_PAYBATCHUSERS] PRIMARY KEY CLUSTERED 
(
	[BSLOGINID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]