/****** Object:  Table [PB].[PAYMENTBATCHORGS]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [PB].[PAYMENTBATCHORGS](
	[BSORGID] [int] NOT NULL,
	[BSORGNAME] [varchar](100) NULL,
 CONSTRAINT [PK_PBORGS_2] PRIMARY KEY CLUSTERED 
(
	[BSORGID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]