/****** Object:  Table [PB].[PAYMENTBATCHPROCESS]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [PB].[PAYMENTBATCHPROCESS](
	[PROCESSCODE] [char](1) NOT NULL,
	[PROCESSNAME] [varchar](25) NULL,
 CONSTRAINT [PK_PAYMENTBATCHPROCESS] PRIMARY KEY CLUSTERED 
(
	[PROCESSCODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]