/****** Object:  Table [PB].[PAYMENTBATCHHEADER]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [PB].[PAYMENTBATCHHEADER](
	[BATCHID] [int] IDENTITY(1,1) NOT NULL,
	[BATCHNO] [int] NOT NULL,
	[BATORGID] [int] NOT NULL,
	[BATPROCESS] [char](1) NOT NULL,
	[BATSTATUS] [int] NOT NULL,
	[BATLOGINID] [varchar](15) NULL,
	[APPROVERLEVELID] [int] NOT NULL,
	[BATBANKLEDGERCODE] [varchar](10) NULL,
	[BATCHDESCRIPTION] [nchar](50) NULL,
 CONSTRAINT [PK__PAYMENTB__0902163432858405] PRIMARY KEY CLUSTERED 
(
	[BATCHID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [PB].[PAYMENTBATCHHEADER]  WITH CHECK ADD FOREIGN KEY([BATPROCESS])
REFERENCES [PB].[PAYMENTBATCHPROCESS] ([PROCESSCODE])