/****** Object:  Table [PB].[UTRDETAILS]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [PB].[UTRDETAILS](
	[UTRDETAILID] [int] IDENTITY(1,1) NOT NULL,
	[UTRHEADERID] [int] NULL,
	[BENEFICIARY] [varchar](300) NULL,
	[IFSC] [varchar](100) NULL,
	[ACCOUNTNUMBER] [varchar](50) NULL,
	[AMOUNT] [decimal](18, 2) NULL,
	[POSTINGDATE] [datetime] NULL,
	[RTGSDETAILID] [int] NULL,
 CONSTRAINT [PK__UTRDETAI__C6853A038E1DBC9A] PRIMARY KEY CLUSTERED 
(
	[UTRDETAILID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]