/****** Object:  Procedure [EI].[spContraEntryToEInvoice]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE [EI].[spContraEntryToEInvoice](@BORGID INT)
AS
DECLARE @RECONID INT
DECLARE @CERTNO VARCHAR(15)
DECLARE @POSTREF VARCHAR(15)
DECLARE @ORDERNO VARCHAR(20)
DECLARE @INVOICEDATE DATETIME 
DECLARE @TRANSACTIONDATE DATETIME 
DECLARE @PARTYCODE VARCHAR(15)
DECLARE @ORGID INT
DECLARE @SUBCONNUMBER INT 
DECLARE @VALNO INT
DECLARE @SUPNAME VARCHAR(100)
 
DECLARE @FINYEAR INT
DECLARE @PERIOD INT

DECLARE @HEADEREXISTS INT
DECLARE  @CUTOFFRECONID INT 

DECLARE @LASTRECONID INT 
SET @LASTRECONID=0 
SELECT @LASTRECONID=ISNULL(MIN(SUBCRECONID),0) FROM EI.EINVOICEHEADER WHERE BORGID=@BORGID AND EISTATUS=-1

IF (@LASTRECONID = 0 )
   BEGIN 
     SELECT @CUTOFFRECONID = ISNULL(LASTRECON_SUBBIE,0) FROM EC.PROJECTS WHERE BSBORGID=@BORGID 
	 SET @LASTRECONID=@CUTOFFRECONID -1
   END 
 

DECLARE RECONLISTS CURSOR FOR 
   SELECT RECONID FROM SUBCRECONS WHERE    ContraThisMonth<>0 AND ORGID=@BORGID AND RECONID >=@LASTRECONID  AND POSTED=0  AND RETRELEASEDATE<>''  
 
  
OPEN RECONLISTS 
FETCH NEXT FROM RECONLISTS INTO @RECONID 

WHILE @@FETCH_STATUS = 0
BEGIN
  
    SELECT  @ORGID=ORGID,
	        @SUBCONNUMBER=SUBCONNUMBER,
			@VALNO=VALNO,
			@CERTNO=CERTNO,
			@POSTREF=POSTREF,
			@ORDERNO=ORDERNO,
			@CERTNO=CERTNOA,
			@INVOICEDATE=RETRELEASEDATE,
			@TRANSACTIONDATE = SCPOSTDATE ,
			@SUPNAME = SUPNAME 
	FROM SUBCRECONS WHERE RECONID=@RECONID 


	SELECT @PARTYCODE  = SUBNUMBER FROM SUBCONTRACTORS WHERE SUBID=@SUBCONNUMBER

    SELECT @FINYEAR = YEAR(@TRANSACTIONDATE) 
	SELECT @PERIOD  = MONTH(@TRANSACTIONDATE)

	IF @PERIOD BETWEEN 4 AND 12 
	 BEGIN
	   SET @FINYEAR=@FINYEAR+1
	   SET @PERIOD = @PERIOD-3
	END
   ELSE
       SET @PERIOD = 9 + @PERIOD 

	SET @HEADEREXISTS  = 0 
	SELECT @HEADEREXISTS = ISNULL(INVOICEINDEX,0) FROM EI.EINVOICEHEADER 
	WHERE SUBCRECONID=@RECONID AND BORGID=@ORGID AND SUBCONNUMBER=@SUBCONNUMBER  
	 

	IF @HEADEREXISTS = 0
	   INSERT INTO EI.EINVOICEHEADER(SUBCRECONID,SUBCONNUMBER  ,BORGID, INVOICECATEGORY,WORKORDERNUMBER,CERTIFICATENUMBER,INVOICENUMBER,INVOICEDATE, FINYEAR, PERIOD, PARTYCODE, PARTYNAME,EISTATUS,ORDERNUMBER)
	   SELECT                        @RECONID,   @SUBCONNUMBER, @ORGID,'SUBCON',        @ORDERNO,       @VALNO,           @CERTNO ,     @INVOICEDATE,@FINYEAR,@PERIOD,@PARTYCODE,@SUPNAME,-1,@ORDERNO
    ELSE
	   UPDATE EI.EINVOICEHEADER SET CERTIFICATENUMBER=@VALNO,INVOICENUMBER=@CERTNO,INVOICEDATE=@INVOICEDATE,FINYEAR=@FINYEAR,PERIOD=@PERIOD 
	   WHERE INVOICEINDEX = @HEADEREXISTS

 FETCH NEXT FROM RECONLISTS INTO @RECONID
END
CLOSE RECONLISTS
DEALLOCATE RECONLISTS 


-- POPULATING DETAILS ALSO / WITHOUT OUTPUT 

EXEC [EI].[spContraEntryToEInvoice_Details] @BORGID  ,0


SELECT   INVOICEINDEX,PARTYCODE,PARTYNAME,WORKORDERNUMBER,CERTIFICATENUMBER,INVOICENUMBER,INVOICEDATE,GROSSBILLING,DEBITNOTEAMOUNT,CREDITNOTEAMOUNT,NETPAYABLE  
         FROM EI.EINVOICEHEADER WHERE BORGID=@BORGID AND EISTATUS = -1