/****** Object:  Procedure [EI].[spContraEntryToEInvoice_Details]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE [EI].[spContraEntryToEInvoice_Details](@BORGID INT,@WITHOUTPUT INT) 
AS
DECLARE @INDEX INT 
DECLARE @RECONID INT 

DECLARE @LIVECONTRA DECIMAL(18,2)

	
DECLARE @CONTRAID INT
DECLARE @LEDGERCODE VARCHAR(15)
DECLARE @UNIT VARCHAR(15)
DECLARE @CONTRRATE DECIMAL(18,2)
DECLARE @QTY DECIMAL(18,2)
DECLARE @TOTAL DECIMAL(18,2)
DECLARE @GSTTYPE VARCHAR(50)
DECLARE @GSTAMOUNT DECIMAL(18,2)

DECLARE @GSTPERCENTAGE DECIMAL(18,2) 
DECLARE @CGSTAMOUNT DECIMAL(18,2)
DECLARE @SGSTAMOUNT DECIMAL(18,2)
DECLARE @IGSTAMOUNT DECIMAL(18,2)
DECLARE @HSNCODE VARCHAR(10)
DECLARE @LEDGERNAME VARCHAR(100)

DECLARE @DEBITSERIALNUMBER INT
DECLARE @CREDITSERIALNUMBER INT 
DECLARE @ROWCOUNT INT 

DECLARE @FIXEDDISPLAYNAME VARCHAR(100)
DECLARE @CONTRAENTRYNAME VARCHAR(100)

DECLARE @EINVOICETYPE VARCHAR(3)

DECLARE @DEBITTOTAL DECIMAL(18,2)
DECLARE @CREDITTOTAL DECIMAL(18,2) 
DECLARE @WORKDONETOTAL DECIMAL(18,2) 
DECLARE @NETPAYABLE DECIMAL(18,2) 

DECLARE @ITEMS    VARCHAR(15)
DECLARE @TAXRATE  DECIMAL(18,2)
DECLARE @TAXGROUP CHAR(2)
DECLARE @TAXTYPE  CHAR(2) 
 
DECLARE @CONTRAITEMEXISTS INT
DECLARE @CHECKANEWCONTRALINE INT


CREATE TABLE #GSTPERCENTAGE(ITEMS VARCHAR(50),RATE DECIMAL(18,2),TAXGROUP VARCHAR(5), TAXTYPE VARCHAR(5) )

DECLARE HEADERLIST CURSOR FOR SELECT INVOICEINDEX,SUBCRECONID FROM EI.EINVOICEHEADER WHERE BORGID=@BORGID AND EISTATUS= -1  
OPEN HEADERLIST
FETCH NEXT FROM HEADERLIST INTO @INDEX,@RECONID 

CREATE TABLE #EXISTINGCONTAIDS(CONTRAID INT)

WHILE @@FETCH_STATUS = 0 
BEGIN
 -- TO CHECK WHETHER CONTRA AMOUNT EXISTS OR NOT ; IF MADE ZERO THEN WE HAVE TO DELETE HEADER AND DETAILS
 SELECT @LIVECONTRA = CONTRATHISMONTH FROM SUBCRECONS WHERE RECONID=@RECONID 
 IF @LIVECONTRA = 0 
   BEGIN
 	DELETE FROM EI.EINVOICEDETAILS WHERE HEADERID = @INDEX 
    DELETE FROM EI.EINVOICEHEADER  WHERE INVOICEINDEX = @INDEX 
   END 
ELSE
   BEGIN
        DELETE FROM #EXISTINGCONTAIDS
		INSERT INTO #EXISTINGCONTAIDS
        SELECT CONTRAID   FROM CONTRAS WHERE CONTRARECONID=@RECONID
		DELETE FROM EI.EINVOICEDETAILS WHERE CONTRALINENUMBER NOT IN (SELECT CONTRAID FROM #EXISTINGCONTAIDS) AND HEADERID=@INDEX
   END


 SET @DEBITSERIALNUMBER = 0
 SET @CREDITSERIALNUMBER = 0 
 

 DECLARE CONTRALISTS CURSOR FOR 
	SELECT CONTRAID,CONTRAALLOC,CONTRAUNIT,CONTRARATE,CONTRAQTY,CONTRATHISMONTH,CONTRAVATTYPE,CONTRAVATAMNT,CONTRADESC
	FROM CONTRAS WHERE CONTRARECONID=@RECONID

	OPEN CONTRALISTS 
	FETCH NEXT FROM CONTRALISTS INTO @CONTRAID,@LEDGERCODE,@UNIT,@CONTRRATE,@QTY,@TOTAL,@GSTTYPE,@GSTAMOUNT,@CONTRAENTRYNAME

	WHILE @@FETCH_STATUS = 0
	BEGIN
	   SET @GSTPERCENTAGE=0
	   SET @CGSTAMOUNT=0
	   SET @SGSTAMOUNT=0
	   SET @IGSTAMOUNT=0
	   SET @HSNCODE = ''

	   DELETE FROM #GSTPERCENTAGE 
	   INSERT INTO #GSTPERCENTAGE(ITEMS) 
	   SELECT * FROM SPLIT( @GSTTYPE,',') 
	   DELETE FROM #GSTPERCENTAGE WHERE ITEMS='' OR ITEMS IS NULL
	   UPDATE #GSTPERCENTAGE SET RATE=V.VATPERC FROM VATTYPES V INNER JOIN #GSTPERCENTAGE ON LEFT(ITEMS,2) = V.VATID AND RIGHT(ITEMS,2)=V.VATGC AND V.BORGID=@BORGID 
	   SELECT @ROWCOUNT = COUNT(*) FROM #GSTPERCENTAGE
	   UPDATE #GSTPERCENTAGE SET TAXGROUP=RIGHT(ITEMS,2)
	   UPDATE #GSTPERCENTAGE SET TAXTYPE=LEFT(ITEMS,2)

	   SET @CGSTAMOUNT=0
	   SET @SGSTAMOUNT=0
	   SET @IGSTAMOUNT=0
	   SET @GSTPERCENTAGE=0

	   DECLARE TAXITEMS CURSOR FOR SELECT * FROM #GSTPERCENTAGE
	   OPEN TAXITEMS 
	   FETCH NEXT FROM TAXITEMS INTO @ITEMS,@TAXRATE,@TAXGROUP,@TAXTYPE 
	   WHILE @@FETCH_STATUS = 0 
	   BEGIN
	      IF @TAXGROUP = 'G6'
		     BEGIN
				SET @IGSTAMOUNT = @GSTAMOUNT
				SET @GSTPERCENTAGE = @TAXRATE
			 END
          IF @TAXGROUP = 'G5'
		     BEGIN
			   SET @SGSTAMOUNT = @GSTAMOUNT/2.0
			   SET @GSTPERCENTAGE = @GSTPERCENTAGE+@TAXRATE
			 END 
		  IF @TAXGROUP = 'G4'
		     BEGIN
			   SET @CGSTAMOUNT = @GSTAMOUNT/2.0
			   SET @GSTPERCENTAGE = @GSTPERCENTAGE+@TAXRATE
			 END 

		  FETCH NEXT FROM TAXITEMS INTO @ITEMS,@TAXRATE,@TAXGROUP,@TAXTYPE 
	   END
	   CLOSE TAXITEMS 
	   DEALLOCATE TAXITEMS 
	  
	   SELECT @FIXEDDISPLAYNAME=DISPLAYNAME,@HSNCODE=HSNCODE  FROM EI.LEDGERMAPPING  WHERE LEDGERCODE=@LEDGERCODE

	   SET @CHECKANEWCONTRALINE =0
       SELECT @CHECKANEWCONTRALINE = ISNULL( COUNT(*),0) FROM EI.EINVOICEDETAILS WHERE CONTRALINENUMBER=@CONTRAID 

	   IF @CHECKANEWCONTRALINE = 0
	    BEGIN 
		   IF @TOTAL  > 0 
			BEGIN
			  SET @DEBITSERIALNUMBER = @DEBITSERIALNUMBER+1
			  INSERT INTO EI.EINVOICEDETAILS(HEADERID,CONTRALINENUMBER,EINVOICETYPE,SERIALNUMBER,LEDGERCODE,
			  FIXEDDISPLAYNAME,CONTRADESC,HSNCODE,QTY,UOM,RATE,GSTPERCENTAGE,CGSTAMOUNT,SGSTAMOUNT,IGSTAMOUNT)
			  VALUES
			  (
				@INDEX,@CONTRAID,'D',@DEBITSERIALNUMBER,@LEDGERCODE,
				@FIXEDDISPLAYNAME,@CONTRAENTRYNAME,@HSNCODE,@QTY,UPPER(@UNIT),@CONTRRATE,@GSTPERCENTAGE,@CGSTAMOUNT,@SGSTAMOUNT,@IGSTAMOUNT
			  )
			END 
		   ELSE IF @TOTAL < 0 
			BEGIN
			 SET @CREDITSERIALNUMBER = @CREDITSERIALNUMBER+1
			 INSERT INTO EI.EINVOICEDETAILS(HEADERID,CONTRALINENUMBER,EINVOICETYPE,SERIALNUMBER,LEDGERCODE,
			 FIXEDDISPLAYNAME,CONTRADESC,HSNCODE,QTY,UOM,RATE,GSTPERCENTAGE,CGSTAMOUNT,SGSTAMOUNT,IGSTAMOUNT)
			 VALUES
			  (
				@INDEX,@CONTRAID,'C',@CREDITSERIALNUMBER,@LEDGERCODE,
				@FIXEDDISPLAYNAME,@CONTRAENTRYNAME,@HSNCODE,ABS(@QTY),UPPER(@UNIT),ABS(@CONTRRATE),ABS(@GSTPERCENTAGE),ABS(@CGSTAMOUNT),ABS(@SGSTAMOUNT),ABS(@IGSTAMOUNT)
			  )
			END
        END
       ELSE
	    BEGIN
		    IF @TOTAL >0 
			   SET @EINVOICETYPE='D'
			ELSE
			   SET @EINVOICETYPE='C'

		    UPDATE EI.EINVOICEDETAILS
			SET EINVOICETYPE=@EINVOICETYPE, LEDGERCODE=@LEDGERCODE, FIXEDDISPLAYNAME=@FIXEDDISPLAYNAME,CONTRADESC=@CONTRAENTRYNAME,HSNCODE=@HSNCODE,QTY=ABS(@QTY),
			UOM=UPPER(@UNIT),RATE=ABS(@CONTRRATE),GSTPERCENTAGE=ABS(@GSTPERCENTAGE),CGSTAMOUNT=ABS(@CGSTAMOUNT),SGSTAMOUNT=ABS(@SGSTAMOUNT),
			IGSTAMOUNT=ABS(@IGSTAMOUNT)  WHERE CONTRALINENUMBER=@CONTRAID

		END

	    SET @DEBITTOTAL=0
		SET @CREDITTOTAL = 0
		SELECT @DEBITTOTAL = SUM(CONTRATHISMONTH) FROM CONTRAS WHERE CONTRARECONID = @RECONID AND CONTRATHISMONTH>0
		SELECT @CREDITTOTAL  = ABS(SUM(CONTRATHISMONTH)) FROM CONTRAS WHERE CONTRARECONID = @RECONID AND CONTRATHISMONTH<0
		SELECT @WORKDONETOTAL = WORKDONETOT ,@NETPAYABLE  = PAID FROM SUBCRECONS WHERE RECONID=@RECONID 
		UPDATE EI.EINVOICEHEADER SET GROSSBILLING=@WORKDONETOTAL,DEBITNOTEAMOUNT=@DEBITTOTAL,CREDITNOTEAMOUNT=@CREDITTOTAL,NETPAYABLE=@NETPAYABLE WHERE INVOICEINDEX=@INDEX 
		
	  FETCH NEXT FROM CONTRALISTS INTO @CONTRAID,@LEDGERCODE,@UNIT,@CONTRRATE,@QTY,@TOTAL,@GSTTYPE,@GSTAMOUNT,@CONTRAENTRYNAME 
	END 
	CLOSE CONTRALISTS
	DEALLOCATE CONTRALISTS 
	-- IF ANY CONTRA LINE IN DETAIL IS HAVING ZERO VALUE - DELETE IT 
	DELETE FROM EI.EINVOICEDETAILS WHERE QTY * RATE = 0  AND  HEADERID=@INDEX 
	-- CHECK UNIT OF MEASURE
	UPDATE EI.EINVOICEDETAILS SET UOM='NOS' WHERE UOM NOT IN (SELECT UOM FROM EI.UOM) AND HEADERID=@INDEX 


 FETCH NEXT FROM HEADERLIST INTO @INDEX,@RECONID 
END
CLOSE HEADERLIST
DEALLOCATE HEADERLIST 





-- DETAILS MISSING IN CONTRA TABLE ; IF SO DELETE IT  - Orphan Entries 
SELECT INVOICEINDEX INTO #MISSINGDETAILS 
FROM EI.EINVOICEHEADER WHERE INVOICEINDEX NOT IN (SELECT HEADERID FROM EI.EINVOICEDETAILS) AND BORGID=@BORGID 
UPDATE SUBCRECONS SET ContraThisMonth = 0 WHERE RECONID IN (
SELECT SUBCRECONID FROM EI.EINVOICEHEADER WHERE INVOICEINDEX IN (SELECT INVOICEINDEX FROM #MISSINGDETAILS))
DELETE FROM EI.EINVOICEHEADER WHERE  INVOICEINDEX IN (SELECT INVOICEINDEX FROM #MISSINGDETAILS)
---

IF @WITHOUTPUT = 1
BEGIN

	SELECT   DETAILINDEX,HEADERID,CONTRALINENUMBER,SERIALNUMBER,FIXEDDISPLAYNAME,VARIABLEDISPLAYNAME,CONTRADESC, QTY,UOM,RATE,GSTPERCENTAGE,CGSTAMOUNT,SGSTAMOUNT,IGSTAMOUNT
         FROM EI.EINVOICEDETAILS WHERE EINVOICETYPE='D' AND HEADERID IN (SELECT INVOICEINDEX  FROM EI.EINVOICEHEADER WHERE BORGID=@BORGID) ORDER BY SERIALNUMBER
	SELECT   DETAILINDEX,HEADERID,CONTRALINENUMBER,SERIALNUMBER,FIXEDDISPLAYNAME,VARIABLEDISPLAYNAME,CONTRADESC, QTY,UOM,RATE,GSTPERCENTAGE,CGSTAMOUNT,SGSTAMOUNT,IGSTAMOUNT 
         FROM EI.EINVOICEDETAILS WHERE EINVOICETYPE='C' AND HEADERID IN (SELECT INVOICEINDEX  FROM EI.EINVOICEHEADER WHERE BORGID=@BORGID) ORDER BY SERIALNUMBER 

END