/****** Object:  Procedure [EI].[spDebtReconItemList]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE [EI].[spDebtReconItemList](@HEADERID INT) 
AS

CREATE TABLE #ITEMLISTS(HEADERID INT,INDEXID INT,SLNO INT, ITEMDESCRIPTION VARCHAR(100),QTY INT,UOM VARCHAR(3), RATE DECIMAL(18,2),GSTPERCENTAGE DECIMAL(18,2),CGST DECIMAL(18,2), SGST DECIMAL(18,2),IGST DECIMAL(18,2), LINETOTAL DECIMAL(18,2),HSNCODE VARCHAR(15)) 
CREATE TABLE #FINAL(SLNO INT PRIMARY KEY IDENTITY(1,1),ITEMDESCRIPTION VARCHAR(100),QTY INT,UOM VARCHAR(3), RATE DECIMAL(18,2),GSTPERCENTAGE DECIMAL(18,2),CGST DECIMAL(18,2), SGST DECIMAL(18,2),IGST DECIMAL(18,2), LINETOTAL DECIMAL(18,2),HSNCODE VARCHAR(15) ) 

INSERT INTO #ITEMLISTS(HEADERID,INDEXID,SLNO,ITEMDESCRIPTION,QTY,UOM,RATE) VALUES (@HEADERID,1,0,'Total Work Done',1,'NOS',0)

DECLARE	   @GSTPERCENTAGE DECIMAL (18,2)
DECLARE	   @CGST DECIMAL (18,2)
DECLARE	   @SGST DECIMAL (18,2)
DECLARE	   @IGST DECIMAL (18,2)
DECLARE    @WORKDONE DECIMAL(18,2) 
DECLARE    @NETRECEIVABLE DECIMAL(18,2) 
DECLARE    @NARRATION VARCHAR(100)
DECLARE    @HSNCODE   VARCHAR(15)

SELECT 
	   @GSTPERCENTAGE=GSTPERCENTAGE,
	   @CGST = CGST,
	   @SGST = SGST,
	   @IGST = IGST,
	   @WORKDONE = WORKDONE,
	   @NETRECEIVABLE  = TOTALGROSSAMOUNT,
	   @NARRATION = NARRATION,
	   @HSNCODE = HSNCODE
FROM EI.DEBTINVOICEDETAILS 
WHERE HEADERID = @HEADERID 


IF @WORKDONE <> 0          UPDATE #ITEMLISTS SET RATE = @WORKDONE   WHERE INDEXID=4

UPDATE #ITEMLISTS SET ITEMDESCRIPTION = @NARRATION ,HSNCODE = @HSNCODE 

UPDATE #ITEMLISTS SET GSTPERCENTAGE=@GSTPERCENTAGE  
 
UPDATE #ITEMLISTS SET CGST =0.5* (RATE * GSTPERCENTAGE)/100.0 WHERE GSTPERCENTAGE<>0  

UPDATE #ITEMLISTS SET SGST =0.5* (RATE * GSTPERCENTAGE)/100.00 WHERE GSTPERCENTAGE<>0  
 
UPDATE #ITEMLISTS SET CGST=@CGST,SGST=@SGST, IGST = @IGST  WHERE GSTPERCENTAGE<>0  

UPDATE #ITEMLISTS SET CGST=0 WHERE CGST IS NULL
UPDATE #ITEMLISTS SET SGST=0 WHERE SGST IS NULL
UPDATE #ITEMLISTS SET IGST=0 WHERE IGST IS NULL
UPDATE #ITEMLISTS SET LINETOTAL = 0 

UPDATE #ITEMLISTS SET LINETOTAL = RATE+CGST+SGST+IGST 

 

DELETE FROM #ITEMLISTS WHERE RATE=0

INSERT INTO #FINAL(ITEMDESCRIPTION ,QTY,UOM,RATE,CGST,SGST,IGST,LINETOTAL,GSTPERCENTAGE) 
SELECT ITEMDESCRIPTION,QTY,UOM,RATE,CGST,SGST,IGST,LINETOTAL,GSTPERCENTAGE   FROM #ITEMLISTS ORDER BY INDEXID  

SELECT  * FROM #FINAL 

DECLARE @BASETOTAL DECIMAL(18,2)
DECLARE @CGSTTOTAL DECIMAL(18,2)
DECLARE @SGSTTOTAL DECIMAL(18,2)
DECLARE @IGSTTOTAL DECIMAL(18,2)
DECLARE @LINESUMTOTAL DECIMAL(18,2) 

SELECT @BASETOTAL=SUM(RATE),@CGSTTOTAL=SUM(CGST), @SGSTTOTAL=SUM(SGST),@IGSTTOTAL=SUM(IGST),@LINESUMTOTAL=SUM(RATE+CGST+SGST+IGST) FROM #FINAL WHERE GSTPERCENTAGE <> 0 AND RATE>0


SELECT  ITEMDESCRIPTION,'995412' AS HSNCODE,QTY,UOM,RATE,RATE AS TOTAL,GSTPERCENTAGE,CGST AS CGSTAMOUNT,SGST AS SGSTAMOUNT,IGST AS IGSTAMOUNT,(RATE+CGST+SGST+IGST) AS LINETOTAL 
FROM #FINAL WHERE GSTPERCENTAGE<>0 AND RATE>0  ORDER BY SLNO 
 

SELECT @BASETOTAL AS BASETOTAL, @CGSTTOTAL AS CGSTTOTAL, @SGSTTOTAL AS SGSTTOTAL ,@IGSTTOTAL AS IGSTTOTAL ,@LINESUMTOTAL AS LINESUMTOTAL 