/****** Object:  Procedure [EI].[spFetchDebtRecons]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE [EI].[spFetchDebtRecons](@BORGID  INT) 
AS
 DECLARE @LASTRECONID INT 
 DECLARE @RECONID INT 
 DECLARE @TAXPERCENTAGE DECIMAL(18,2)

 DECLARE @WORKDONE DECIMAL(18,2)

 DECLARE @CGST DECIMAL(18,2)
 DECLARE @SGST DECIMAL(18,2)
 DECLARE @IGST DECIMAL(18,2) 
  
 DECLARE @HEADERID INT 
 DECLARE @DETAILALREADYEXISTING INT


 DECLARE @INVOICEDATE DATETIME
 DECLARE @INVOICENUMBER VARCHAR(25) 

 DECLARE  @CUTOFFRECONID INT 
 


 SET @LASTRECONID=0
 SELECT @LASTRECONID = ISNULL(DEBTRECONID,0) FROM EI.DEBTORINVOICEHEADER WHERE BORGID=@BORGID  
 IF (@LASTRECONID = 0 )
   BEGIN 
     SELECT @CUTOFFRECONID = ISNULL(LASTRECON_DEBTOR,0) FROM EC.PROJECTS WHERE BSBORGID=@BORGID 
	 SET @LASTRECONID=@CUTOFFRECONID -1
   END 
 

 

 SELECT SUBCONNUMBER,SUPNAME,CODE,POSTED,RECONID,USERID,POSTREF,ORDERNO,RETRELEASEDATE,LOGDATETIME,POSTDATE 
 INTO #TEMPRECONS 
 FROM DEBTRECONS  
 WHERE ORGID=@BORGID  AND RECONID>@LASTRECONID 
 
 ALTER TABLE #TEMPRECONS ADD FINYEAR INT
 ALTER TABLE #TEMPRECONS ADD PERIOD  INT
 ALTER TABLE #TEMPRECONS ADD INVOICENUMBER VARCHAR(25)
 UPDATE #TEMPRECONS SET INVOICENUMBER = LTRIM(RTRIM(POSTREF))+LTRIM(RTRIM(ORDERNO)) 
 UPDATE #TEMPRECONS SET RETRELEASEDATE = POSTDATE WHERE RETRELEASEDATE IS NULL
 UPDATE #TEMPRECONS SET FINYEAR = YEAR(RETRELEASEDATE),PERIOD= MONTH(RETRELEASEDATE) 
 INSERT INTO EI.DEBTORINVOICEHEADER (DEBTRECONID,DEBTORNUMBER,BORGID,FINYEAR,PERIOD,INVOICETYPE,PARTYCODE,INVOICENUMBER,INVOICEDATE,EISTATUS,RULESETCODE,APPROVED) 
 SELECT RECONID,SUBCONNUMBER,@BORGID ,FINYEAR,PERIOD,'INV','',INVOICENUMBER,RETRELEASEDATE,-1,CODE,1  FROM #TEMPRECONS

 

 -- CODE : 16.13  SCRAP SALES - IGST 

 DECLARE SCRAPIGST CURSOR FOR 
    SELECT INVOICEINDEX , DEBTRECONID FROM EI.DEBTORINVOICEHEADER WHERE RULESETCODE ='16.13'  AND EISTATUS=-1
 OPEN  SCRAPIGST 
 FETCH NEXT FROM SCRAPIGST INTO @HEADERID, @RECONID 
 WHILE @@FETCH_STATUS = 0 
 BEGIN
 
   SET @CGST = 0 
   SET @SGST = 0
   SET @IGST = 0 
   SET @TAXPERCENTAGE = 0
   SET @WORKDONE = 0
   SELECT @TAXPERCENTAGE=  PERC   FROM DEBTRECONDETAIL WHERE RECONID=@RECONID AND VARCODE ='TAX1'
   SELECT @WORKDONE =     MVALUE FROM DEBTRECONDETAIL WHERE RECONID=@RECONID AND VARCODE ='TGB' 
   SELECT @IGST      =     MVALUE FROM DEBTRECONDETAIL WHERE RECONID=@RECONID AND VARCODE ='TAXC' 

   SELECT @TAXPERCENTAGE=  PERC   FROM DEBTRECONDETAIL WHERE RECONID=@RECONID AND VARCODE ='TAX1'
  
   SET @DETAILALREADYEXISTING = 0
   SELECT @DETAILALREADYEXISTING = ISNULL(COUNT(*),0) FROM EI.DEBTINVOICEDETAILS WHERE HEADERID=@HEADERID 

   IF @DETAILALREADYEXISTING = 0 
     BEGIN 
	   INSERT INTO EI.DEBTINVOICEDETAILS(HEADERID,WORKDONE,GSTPERCENTAGE,IGST)
       SELECT @HEADERID,@WORKDONE,@TAXPERCENTAGE,@IGST
     END
   ELSE
     BEGIN 
	   UPDATE EI.DEBTINVOICEDETAILS    SET WORKDONE = @WORKDONE, GSTPERCENTAGE = @TAXPERCENTAGE, IGST = @IGST  WHERE HEADERID=@HEADERID 
     END 
 
   SELECT @INVOICEDATE=RETRELEASEDATE,@INVOICENUMBER = LTRIM(RTRIM(POSTREF))+LTRIM(RTRIM(ORDERNO))   FROM DEBTRECONS WHERE RECONID=@RECONID 
   UPDATE EI.DEBTORINVOICEHEADER SET INVOICEDATE=@INVOICEDATE,INVOICENUMBER = @INVOICENUMBER   WHERE INVOICEINDEX = @HEADERID 
   UPDATE EI.DEBTORINVOICEHEADER SET FINYEAR = YEAR(@INVOICEDATE),PERIOD =MONTH(@INVOICEDATE) WHERE INVOICEINDEX = @HEADERID 
 
   FETCH NEXT FROM SCRAPIGST INTO @HEADERID,  @RECONID 


 END
 CLOSE SCRAPIGST
 DEALLOCATE SCRAPIGST


 -- CODE : 16.14  SCRAP SALES - CGST AND SGST

 DECLARE SCRAPCGST CURSOR FOR 
    SELECT INVOICEINDEX , DEBTRECONID FROM EI.DEBTORINVOICEHEADER WHERE RULESETCODE ='16.14'  AND EISTATUS=-1
 OPEN  SCRAPCGST 
 FETCH NEXT FROM SCRAPCGST INTO @HEADERID, @RECONID 
 WHILE @@FETCH_STATUS = 0 
 BEGIN
  
   SET @CGST = 0 
   SET @SGST = 0
   SET @IGST = 0 
   SET @TAXPERCENTAGE = 0
   SET @WORKDONE = 0
   
   SELECT @TAXPERCENTAGE=  PERC   FROM DEBTRECONDETAIL WHERE RECONID=@RECONID AND VARCODE ='TAX1'
   SELECT @WORKDONE   =     MVALUE FROM DEBTRECONDETAIL WHERE RECONID=@RECONID AND VARCODE ='TGB' 
   SELECT @CGST      =     MVALUE FROM DEBTRECONDETAIL WHERE RECONID=@RECONID AND VARCODE ='TAXC' 
   SELECT @SGST      =     MVALUE FROM DEBTRECONDETAIL WHERE RECONID=@RECONID AND VARCODE ='TAX2' 

   SET @IGST = 0 
   SET @DETAILALREADYEXISTING = 0
   SELECT @DETAILALREADYEXISTING = ISNULL(COUNT(*),0) FROM EI.DEBTINVOICEDETAILS WHERE HEADERID=@HEADERID 

   IF @DETAILALREADYEXISTING = 0 
     BEGIN 
	   INSERT INTO EI.DEBTINVOICEDETAILS(HEADERID,WORKDONE,GSTPERCENTAGE,CGST,SGST,IGST)
       SELECT @HEADERID,@WORKDONE,@TAXPERCENTAGE,@CGST,@SGST,@IGST 
     END
   ELSE
     BEGIN 
	   UPDATE EI.DEBTINVOICEDETAILS
	    SET WORKDONE = @WORKDONE, 
		GSTPERCENTAGE = @TAXPERCENTAGE,
		CGST=@CGST,SGST=@SGST,IGST = @IGST 
     END 
 
   SELECT @INVOICEDATE=RETRELEASEDATE,@INVOICENUMBER = LTRIM(RTRIM(POSTREF))+LTRIM(RTRIM(ORDERNO))   FROM DEBTRECONS WHERE RECONID=@RECONID 
   UPDATE EI.DEBTORINVOICEHEADER SET INVOICEDATE=@INVOICEDATE,INVOICENUMBER = @INVOICENUMBER   WHERE INVOICEINDEX = @HEADERID 
   UPDATE EI.DEBTORINVOICEHEADER SET FINYEAR = YEAR(@INVOICEDATE),PERIOD =MONTH(@INVOICEDATE) WHERE INVOICEINDEX = @HEADERID 
  


   FETCH NEXT FROM SCRAPCGST INTO @HEADERID,  @RECONID 


 END
 CLOSE SCRAPCGST
 DEALLOCATE SCRAPCGST


 -- CODE : 16.21    PRIVATE CERTIFIED

 DECLARE GOVTPRIVATE  CURSOR FOR 
    SELECT INVOICEINDEX , DEBTRECONID FROM EI.DEBTORINVOICEHEADER WHERE RULESETCODE ='16.21'  AND EISTATUS=-1
 OPEN  GOVTPRIVATE 
 FETCH NEXT FROM GOVTPRIVATE INTO @HEADERID, @RECONID 
 WHILE @@FETCH_STATUS = 0 
 BEGIN
   SET @WORKDONE = 0
    
  
   SET @TAXPERCENTAGE = 0
  
   SET @CGST = 0 
   SET @SGST = 0
   SET @IGST = 0 

   

   SELECT @TAXPERCENTAGE=  PERC   FROM DEBTRECONDETAIL WHERE RECONID=@RECONID AND VARCODE ='TAXC'
   SELECT @WORKDONE  =     MVALUE FROM DEBTRECONDETAIL WHERE RECONID=@RECONID AND VARCODE ='TGB' 
   SELECT @CGST      =     MVALUE FROM DEBTRECONDETAIL WHERE RECONID=@RECONID AND VARCODE ='TAX1' 
   SELECT @SGST      =     MVALUE FROM DEBTRECONDETAIL WHERE RECONID=@RECONID AND VARCODE ='TAX2' 
  
   SET @DETAILALREADYEXISTING = 0
   SELECT @DETAILALREADYEXISTING = ISNULL(COUNT(*),0) FROM EI.DEBTINVOICEDETAILS WHERE HEADERID=@HEADERID 

   IF @DETAILALREADYEXISTING = 0 
     BEGIN 
	   INSERT INTO EI.DEBTINVOICEDETAILS(HEADERID,WORKDONE,GSTPERCENTAGE,CGST,SGST,IGST)
       SELECT @HEADERID,@WORKDONE,@TAXPERCENTAGE,@CGST,@SGST,@IGST
     END
   ELSE
     BEGIN 
	   UPDATE EI.DEBTINVOICEDETAILS
	    SET WORKDONE = @WORKDONE,GSTPERCENTAGE = @TAXPERCENTAGE,CGST=@CGST,SGST=@SGST,IGST = @IGST   WHERE HEADERID=@HEADERID 
     END 
 
   SELECT @INVOICEDATE=RETRELEASEDATE,@INVOICENUMBER = LTRIM(RTRIM(POSTREF))+LTRIM(RTRIM(ORDERNO))   FROM DEBTRECONS WHERE RECONID=@RECONID 
   UPDATE EI.DEBTORINVOICEHEADER SET INVOICEDATE=@INVOICEDATE,INVOICENUMBER = @INVOICENUMBER  WHERE INVOICEINDEX = @HEADERID 
   UPDATE EI.DEBTORINVOICEHEADER SET FINYEAR = YEAR(@INVOICEDATE),PERIOD =MONTH(@INVOICEDATE) WHERE INVOICEINDEX = @HEADERID 
 

   FETCH NEXT FROM GOVTPRIVATE INTO @HEADERID,  @RECONID 


 END
 CLOSE GOVTPRIVATE
 DEALLOCATE GOVTPRIVATE




 -- CODE : 16.23    PRIVATE CERTIFIED 

 DECLARE GOVTPRIVATE  CURSOR FOR 
    SELECT INVOICEINDEX , DEBTRECONID FROM EI.DEBTORINVOICEHEADER WHERE RULESETCODE ='16.23'  AND EISTATUS=-1
 OPEN  GOVTPRIVATE 
 FETCH NEXT FROM GOVTPRIVATE INTO @HEADERID, @RECONID 
 WHILE @@FETCH_STATUS = 0 
 BEGIN
   SET @WORKDONE = 0
   
  
   SET @TAXPERCENTAGE = 0
  
   SET @CGST = 0 
   SET @SGST = 0
   SET @IGST = 0 

     

   SELECT @TAXPERCENTAGE=  PERC   FROM DEBTRECONDETAIL WHERE RECONID=@RECONID AND VARCODE ='TAXC'
   SELECT @WORKDONE  =     MVALUE FROM DEBTRECONDETAIL WHERE RECONID=@RECONID AND VARCODE ='TGB' 
   SELECT @CGST      =     MVALUE FROM DEBTRECONDETAIL WHERE RECONID=@RECONID AND VARCODE ='TAX1' 
   SELECT @SGST      =     MVALUE FROM DEBTRECONDETAIL WHERE RECONID=@RECONID AND VARCODE ='TAX2' 
 
   SET @DETAILALREADYEXISTING = 0
   SELECT @DETAILALREADYEXISTING = ISNULL(COUNT(*),0) FROM EI.DEBTINVOICEDETAILS WHERE HEADERID=@HEADERID 

   IF @DETAILALREADYEXISTING = 0 
     BEGIN 
	   INSERT INTO EI.DEBTINVOICEDETAILS(HEADERID,WORKDONE,GSTPERCENTAGE,CGST,SGST,IGST)
       SELECT @HEADERID,@WORKDONE,@TAXPERCENTAGE,@CGST,@SGST,@IGST 
     END
   ELSE
     BEGIN 
	   UPDATE EI.DEBTINVOICEDETAILS
	   SET WORKDONE = @WORKDONE,GSTPERCENTAGE = @TAXPERCENTAGE,CGST=@CGST,SGST=@SGST,IGST = @IGST 	 WHERE HEADERID=@HEADERID 
     END 
 
   SELECT @INVOICEDATE=RETRELEASEDATE,@INVOICENUMBER = LTRIM(RTRIM(POSTREF))+LTRIM(RTRIM(ORDERNO))   FROM DEBTRECONS WHERE RECONID=@RECONID 
   UPDATE EI.DEBTORINVOICEHEADER SET INVOICEDATE=@INVOICEDATE,INVOICENUMBER = @INVOICENUMBER  WHERE INVOICEINDEX = @HEADERID 
   UPDATE EI.DEBTORINVOICEHEADER SET FINYEAR = YEAR(@INVOICEDATE),PERIOD =MONTH(@INVOICEDATE) WHERE INVOICEINDEX = @HEADERID 
 

   FETCH NEXT FROM GOVTPRIVATE INTO @HEADERID,  @RECONID 


 END
 CLOSE GOVTPRIVATE
 DEALLOCATE GOVTPRIVATE




 -- CODE : 16.24    ADVANCE PRIVATE  

 DECLARE ADVPRIVATE   CURSOR FOR 
    SELECT INVOICEINDEX , DEBTRECONID FROM EI.DEBTORINVOICEHEADER WHERE RULESETCODE IN ('16.24','16.25')  AND EISTATUS=-1
 OPEN  ADVPRIVATE 
 FETCH NEXT FROM ADVPRIVATE INTO @HEADERID, @RECONID 
 WHILE @@FETCH_STATUS = 0 
 BEGIN
   SET @WORKDONE = 0
   SET @TAXPERCENTAGE = 0
   SET @CGST = 0 
   SET @SGST = 0
   SET @IGST = 0 

   SELECT @TAXPERCENTAGE=  PERC   FROM DEBTRECONDETAIL WHERE RECONID=@RECONID AND VARCODE ='TAXC'
  
   SELECT @CGST      =     MVALUE FROM DEBTRECONDETAIL WHERE RECONID=@RECONID AND VARCODE ='TAX1' 
   SELECT @SGST      =     MVALUE FROM DEBTRECONDETAIL WHERE RECONID=@RECONID AND VARCODE ='TAX2' 
     SET @DETAILALREADYEXISTING = 0
   SELECT @DETAILALREADYEXISTING = ISNULL(COUNT(*),0) FROM EI.DEBTINVOICEDETAILS WHERE HEADERID=@HEADERID 

   IF @DETAILALREADYEXISTING = 0 
     BEGIN 
	   INSERT INTO EI.DEBTINVOICEDETAILS(HEADERID,WORKDONE,GSTPERCENTAGE,CGST,SGST,IGST)
       SELECT @HEADERID,@WORKDONE,@TAXPERCENTAGE,@CGST,@SGST,@IGST 
     END
   ELSE
     BEGIN 
	   UPDATE EI.DEBTINVOICEDETAILS
	    SET WORKDONE = @WORKDONE,GSTPERCENTAGE = @TAXPERCENTAGE,CGST=@CGST,SGST=@SGST,IGST = @IGST   WHERE HEADERID=@HEADERID 
     END 
 
   SELECT @INVOICEDATE=RETRELEASEDATE,@INVOICENUMBER = LTRIM(RTRIM(POSTREF))+LTRIM(RTRIM(ORDERNO))   FROM DEBTRECONS WHERE RECONID=@RECONID 
   UPDATE EI.DEBTORINVOICEHEADER SET INVOICEDATE=@INVOICEDATE,INVOICENUMBER = @INVOICENUMBER  WHERE INVOICEINDEX = @HEADERID 
   UPDATE EI.DEBTORINVOICEHEADER SET FINYEAR = YEAR(@INVOICEDATE),PERIOD =MONTH(@INVOICEDATE) WHERE INVOICEINDEX = @HEADERID 
  
   FETCH NEXT FROM ADVPRIVATE INTO @HEADERID,  @RECONID 


 END
 CLOSE ADVPRIVATE
 DEALLOCATE ADVPRIVATE




 
 -- CODE : 16.25    ADVANCE GOVT

 DECLARE ADVGOVT   CURSOR FOR 
    SELECT INVOICEINDEX , DEBTRECONID FROM EI.DEBTORINVOICEHEADER WHERE RULESETCODE ='16.25'   AND EISTATUS=-1
 OPEN  ADVGOVT 
 FETCH NEXT FROM ADVGOVT INTO @HEADERID, @RECONID 
 WHILE @@FETCH_STATUS = 0 
 BEGIN
   SET @WORKDONE = 0
    
   SET @TAXPERCENTAGE = 0
  
   SET @CGST = 0 
   SET @SGST = 0
   SET @IGST = 0 

   
   SELECT @TAXPERCENTAGE=  PERC   FROM DEBTRECONDETAIL WHERE RECONID=@RECONID AND VARCODE ='TAXC'
  
   SELECT @CGST      =     MVALUE FROM DEBTRECONDETAIL WHERE RECONID=@RECONID AND VARCODE ='TAX1' 
   SELECT @SGST      =     MVALUE FROM DEBTRECONDETAIL WHERE RECONID=@RECONID AND VARCODE ='TAX2' 
   SET @DETAILALREADYEXISTING = 0
   SELECT @DETAILALREADYEXISTING = ISNULL(COUNT(*),0) FROM EI.DEBTINVOICEDETAILS WHERE HEADERID=@HEADERID 

   IF @DETAILALREADYEXISTING = 0 
     BEGIN 
	   INSERT INTO EI.DEBTINVOICEDETAILS(HEADERID,WORKDONE,GSTPERCENTAGE,CGST,SGST,IGST)
       SELECT @HEADERID,@WORKDONE,@TAXPERCENTAGE,@CGST,@SGST,@IGST 
     END
   ELSE
     BEGIN 
	   UPDATE EI.DEBTINVOICEDETAILS
	    SET WORKDONE = @WORKDONE,GSTPERCENTAGE = @TAXPERCENTAGE,CGST=@CGST,SGST=@SGST,IGST = @IGST    WHERE HEADERID=@HEADERID 
     END 
 
   SELECT @INVOICEDATE=RETRELEASEDATE,@INVOICENUMBER = LTRIM(RTRIM(POSTREF))+LTRIM(RTRIM(ORDERNO))   FROM DEBTRECONS WHERE RECONID=@RECONID 
   UPDATE EI.DEBTORINVOICEHEADER SET INVOICEDATE=@INVOICEDATE,INVOICENUMBER = @INVOICENUMBER  WHERE INVOICEINDEX = @HEADERID 
   UPDATE EI.DEBTORINVOICEHEADER SET FINYEAR = YEAR(@INVOICEDATE),PERIOD =MONTH(@INVOICEDATE) WHERE INVOICEINDEX = @HEADERID 
  

   FETCH NEXT FROM ADVGOVT INTO @HEADERID,  @RECONID 


 END
 CLOSE ADVGOVT
 DEALLOCATE ADVGOVT





UPDATE EI.DEBTINVOICEDETAILS SET WORKDONE=0 WHERE WORKDONE IS NULL
UPDATE EI.DEBTINVOICEDETAILS SET CGST=0 WHERE CGST IS NULL 
UPDATE EI.DEBTINVOICEDETAILS SET SGST=0 WHERE SGST IS NULL 
UPDATE EI.DEBTINVOICEDETAILS SET IGST=0 WHERE IGST IS NULL
UPDATE EI.DEBTINVOICEDETAILS SET TOTALGROSSAMOUNT = WORKDONE+CGST+SGST+IGST,NARRATION='Total Work Done',HSNCODE='995412'  WHERE  TOTALGROSSAMOUNT is null
 


UPDATE EI.DEBTORINVOICEHEADER SET PARTYCODE=D.DEBTNUMBER,PARTYNAME=D.DEBTNAME FROM DEBTORS D INNER JOIN EI.DEBTORINVOICEHEADER ON EI.DEBTORINVOICEHEADER.DEBTORNUMBER=D.DEBTID 
UPDATE EI.DEBTORINVOICEHEADER SET NETRECEIVABLE = D.TOTALGROSSAMOUNT FROM EI.DEBTINVOICEDETAILS D INNER JOIN EI.DEBTORINVOICEHEADER ON EI.DEBTORINVOICEHEADER.INVOICEINDEX=D.HEADERID 
UPDATE EI.DEBTORINVOICEHEADER SET NETRECEIVABLE=0 WHERE NETRECEIVABLE IS NULL
DELETE FROM  EI.DEBTORINVOICEHEADER WHERE NETRECEIVABLE=0



SELECT INVOICEINDEX,PARTYCODE,PARTYNAME,INVOICENUMBER,INVOICEDATE,NETRECEIVABLE,(M.RULESETCODE+ '  -  ' + D.DESCRIPTION) INVOICECATEGORY FROM EI.DEBTORINVOICEHEADER M
INNER JOIN  DEBTRECONHEAD D ON M.RULESETCODE=D.CODE 
WHERE M.BORGID=@BORGID  AND M.EISTATUS = -1
ORDER BY INVOICEINDEX 
 