/****** Object:  Procedure [EI].[spGenerateEInvoiceDebtor]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE  PROCEDURE [EI].[spGenerateEInvoiceDebtor](@HEADERID INT)
AS 

DECLARE @NETINVOICEAMOUNT DECIMAL(18,2) 
DECLARE @AMOUNTINWORDSRUPEE VARCHAR(400)
DECLARE @AMOUNTINWORDSPAISE VARCHAR(400)
DECLARE @AMOUNTINWORDS  VARCHAR(400)


CREATE TABLE #EI
(FINYEAR INT, PERIOD INT, PERIODNAME VARCHAR(25),HEADERID INT,PROJECTCODE INT,PROJECTNAME VARCHAR(150),INVOICENUMBER VARCHAR(25),INVOICEDATE DATETIME,INVOICETYPE CHAR(3),
PARTYCODE VARCHAR(15),PARTYNAME VARCHAR(150),ACKNUMBER VARCHAR(25),ACKDATE DATETIME,IRN VARCHAR(200),QRCODE IMAGE,
SGSTINID INT,SGSTIN VARCHAR(16),SELLERNAME VARCHAR(200),SADDR1 VARCHAR(100),SADDR2 VARCHAR(100),SLOCATION VARCHAR(100),SSTATECODE CHAR(2),SPIN VARCHAR(6),SSTATE VARCHAR(25),
             BGSTIN VARCHAR(16),BUYERNAME  VARCHAR(200),BADDR1 VARCHAR(100),BADDR2 VARCHAR(100),BLOCATION VARCHAR(100),BSTATECODE CHAR(2),BPIN VARCHAR(6),BSTATE VARCHAR(25),
			 TOTALAMOUNTINWORDS VARCHAR(500)
) 

CREATE TABLE #EIDETAILS
(DETAILID INT,HEADERID INT,ITEMDESCRIPTION VARCHAR(100), HSNCODE VARCHAR(15),UOM VARCHAR(3), QTY DECIMAL(18,2), RATE DECIMAL(18,2), GSTPERCENTAGE DECIMAL(18,2),CGSTAMOUNT DECIMAL(18,2),
 SGSTAMOUNT DECIMAL(18,2), IGSTAMOUNT DECIMAL(18,2) )


INSERT INTO #EI(HEADERID,PROJECTCODE,INVOICENUMBER,INVOICEDATE,INVOICETYPE,PARTYCODE,PARTYNAME ) 
SELECT INVOICEINDEX,BORGID,INVOICENUMBER,INVOICEDATE,'INV',PARTYCODE,PARTYNAME 
FROM EI.DEBTORINVOICEHEADER WHERE INVOICEINDEX=@HEADERID 

UPDATE #EI SET ACKNUMBER = EINV.ACKNUMBER,ACKDATE=EINV.ACKDATE,IRN=EINV.IRN,QRCODE=EINV.QRCODE FROM EI.EINVOICE EINV INNER JOIN #EI ON #EI.HEADERID	= EINV.REFERENCEHEADERID 
UPDATE #EI SET FINYEAR = EIH.FINYEAR, PERIOD=EIH.[PERIOD] FROM EI.EINVOICEHEADER EIH INNER JOIN #EI ON #EI.HEADERID = EIH.INVOICEINDEX 
UPDATE #EI SET PERIODNAME  =  BSP.PERIODDESC FROM PERIODMASTER  BSP INNER JOIN #EI ON #EI.PERIOD = BSP.PERIODID


UPDATE #EI SET PROJECTNAME =ECP.BSBORGNAME,SGSTINID=ECP.GSTINID FROM EC.PROJECTS ECP INNER JOIN #EI ON #EI.PROJECTCODE=ECP.BSBORGID 
UPDATE #EI SET SGSTIN=EIG.GSTIN,SELLERNAME=EIG.LEGALNAME,SADDR1=EIG.ADDRESS1,SADDR2=EIG.ADDRESS2,SLOCATION=EIG.LOCATION,SSTATECODE=EIG.STATECODE,SPIN=EIG.PIN 
FROM EI.GSTINS EIG INNER JOIN #EI ON #EI.SGSTINID=EIG.GSTINID 
UPDATE #EI SET BGSTIN=EIG.GSTIN,BUYERNAME=EIG.LEGALNAME,BADDR1=EIG.ADDRESS1,BADDR2=EIG.ADDRESS2,BLOCATION=EIG.LOCATION,BSTATECODE=EIG.STATECODE,BPIN=EIG.PIN 
FROM EI.GSTINS EIG INNER JOIN #EI ON #EI.PARTYCODE=EIG.CREDNO 


CREATE TABLE #ITEMLISTS(HEADERID INT,INDEXID INT,SLNO INT, ITEMDESCRIPTION VARCHAR(100),QTY INT,UOM VARCHAR(3),HSNCODE VARCHAR(10), RATE DECIMAL(18,2),GSTPERCENTAGE DECIMAL(18,2),CGST DECIMAL(18,2), SGST DECIMAL(18,2),IGST DECIMAL(18,2), LINETOTAL DECIMAL(18,2)) 
 
--INSERT INTO #ITEMLISTS(HEADERID,INDEXID,SLNO,ITEMDESCRIPTION,QTY,UOM,RATE) VALUES (@HEADERID,1,0,'Mobilization Advance Received',1,'NOS',0)
--INSERT INTO #ITEMLISTS(HEADERID,INDEXID,SLNO,ITEMDESCRIPTION,QTY,UOM,RATE) VALUES (@HEADERID,2,0,'Material Advance Received',1,'NOS',0)
--INSERT INTO #ITEMLISTS(HEADERID,INDEXID,SLNO,ITEMDESCRIPTION,QTY,UOM,RATE) VALUES (@HEADERID,3,0,'Mivan  Advance Received',1,'NOS',0)
INSERT INTO #ITEMLISTS(HEADERID,INDEXID,SLNO,ITEMDESCRIPTION,QTY,UOM,RATE) VALUES (@HEADERID,4,0,'Total Work Done',1,'NOS',0)
--INSERT INTO #ITEMLISTS(HEADERID,INDEXID,SLNO,ITEMDESCRIPTION,QTY,UOM,RATE) VALUES (@HEADERID,5,0,'Scarp Sale/Other Income',1,'NOS',0)
--INSERT INTO #ITEMLISTS(HEADERID,INDEXID,SLNO,ITEMDESCRIPTION,QTY,UOM,RATE) VALUES (@HEADERID,6,0,'Mobilization Advance Recovery',1,'NOS',0)
--INSERT INTO #ITEMLISTS(HEADERID,INDEXID,SLNO,ITEMDESCRIPTION,QTY,UOM,RATE) VALUES (@HEADERID,7,0,'Material Advance Recovery',1,'NOS',0)
--INSERT INTO #ITEMLISTS(HEADERID,INDEXID,SLNO,ITEMDESCRIPTION,QTY,UOM,RATE) VALUES (@HEADERID,8,0,'Mivan  Advance Recovery',1,'NOS',0)
--INSERT INTO #ITEMLISTS(HEADERID,INDEXID,SLNO,ITEMDESCRIPTION,QTY,UOM,RATE) VALUES (@HEADERID,9,0,'Retention',1,'NOS',0)
--INSERT INTO #ITEMLISTS(HEADERID,INDEXID,SLNO,ITEMDESCRIPTION,QTY,UOM,RATE) VALUES (@HEADERID,10,0,'Income Tax TDS',1,'NOS',0)
--INSERT INTO #ITEMLISTS(HEADERID,INDEXID,SLNO,ITEMDESCRIPTION,QTY,UOM,RATE) VALUES (@HEADERID,11,0,'TCS',1,'NOS',0)
--INSERT INTO #ITEMLISTS(HEADERID,INDEXID,SLNO,ITEMDESCRIPTION,QTY,UOM,RATE) VALUES (@HEADERID,12,0,'TDS-CGST',1,'NOS',0)
--INSERT INTO #ITEMLISTS(HEADERID,INDEXID,SLNO,ITEMDESCRIPTION,QTY,UOM,RATE) VALUES (@HEADERID,13,0,'TDS-SGST',1,'NOS',0)
--INSERT INTO #ITEMLISTS(HEADERID,INDEXID,SLNO,ITEMDESCRIPTION,QTY,UOM,RATE) VALUES (@HEADERID,14,0,'Other Debits',1,'NOS',0)

DECLARE	   @MOBADVANCE DECIMAL (18,2)
DECLARE    @SECUREDADVANCE DECIMAL (18,2)
DECLARE	   @MIVANADVANCE DECIMAL (18,2)
DECLARE	   @GSTPERCENTAGE DECIMAL (18,2)
DECLARE	   @MOBADVRECOVERY DECIMAL (18,2)
DECLARE	   @SECUREDADVRECOVERY DECIMAL (18,2)
DECLARE	   @MIVANADVRECOVERY DECIMAL (18,2)
DECLARE	   @CGST DECIMAL (18,2)
DECLARE	   @SGST DECIMAL (18,2)
DECLARE	   @IGST DECIMAL (18,2)
DECLARE	   @CGSTSTRECOVERY DECIMAL (18,2)
DECLARE	   @SGSTRECOVERY DECIMAL (18,2)
DECLARE	   @IGSTRECOVERY DECIMAL (18,2)
DECLARE	   @OTHERDEBIT DECIMAL (18,2)
DECLARE	   @RETENTION DECIMAL (18,2)
DECLARE	   @TDS DECIMAL (18,2)
DECLARE	   @TDSCGST DECIMAL (18,2)
DECLARE	   @TDSSGST DECIMAL (18,2)
DECLARE	   @TCS DECIMAL (18,2)
DECLARE    @WORKDONE DECIMAL(18,2) 
DECLARE    @SCRAPSALE DECIMAL(18,2) 
DECLARE    @NETRECEIVABLE DECIMAL(18,2) 

SELECT @MOBADVANCE=MOBADVANCE,
       @SECUREDADVANCE=SECUREDADVANCE ,
	   @MIVANADVANCE=MIVANADVANCE,
	   @GSTPERCENTAGE=GSTPERCENTAGE,
	   @MOBADVRECOVERY = MOBADVRECOVERY,
	   @SECUREDADVRECOVERY = SECUREDADVRECOVERY,
	   @MIVANADVRECOVERY =MIVANADVRECOVERY,
	   @CGST = CGST,
	   @SGST = SGST,
	   @IGST = IGST,
	   @CGSTSTRECOVERY = CGSTRECOVERY,
	   @SGSTRECOVERY = SGSTRECOVERY,
	   @IGSTRECOVERY = IGSTRECOVERY,
	   @OTHERDEBIT = CONTRAAMOUNT,
	   @RETENTION = RETENTION,
	   @TDS = TDS,
	   @TDSCGST = TDSCGST,
	   @TDSSGST = TDSSGST,
	   @TCS = TCS,
	   @WORKDONE = WORKDONE,
	   @SCRAPSALE = SCRAPSALE,
	   @NETRECEIVABLE  = NETRECEIVABLE 
FROM EI.DEBTINVOICEDETAILS 
WHERE HEADERID = @HEADERID 

IF @MOBADVANCE <> 0        UPDATE #ITEMLISTS SET RATE = @MOBADVANCE WHERE INDEXID=1
IF @SECUREDADVANCE <> 0    UPDATE #ITEMLISTS SET RATE = @SECUREDADVANCE WHERE INDEXID=2
IF @MIVANADVANCE <> 0      UPDATE #ITEMLISTS SET RATE = @MIVANADVANCE WHERE INDEXID=3

IF @WORKDONE <> 0        UPDATE #ITEMLISTS SET RATE = @WORKDONE WHERE INDEXID=4
IF @SCRAPSALE <> 0    UPDATE #ITEMLISTS SET RATE = @SCRAPSALE WHERE INDEXID=5



IF @MOBADVRECOVERY <> 0        UPDATE #ITEMLISTS SET RATE =-1.0* @MOBADVRECOVERY WHERE INDEXID=6
IF @SECUREDADVRECOVERY <> 0    UPDATE #ITEMLISTS SET RATE =-1.0* @SECUREDADVRECOVERY WHERE INDEXID=7
IF @MIVANADVRECOVERY <> 0      UPDATE #ITEMLISTS SET RATE =-1.0* @MIVANADVRECOVERY WHERE INDEXID=8

IF @RETENTION <> 0        UPDATE #ITEMLISTS SET RATE =-1.0* @RETENTION WHERE INDEXID=9
IF @TDS <> 0    UPDATE #ITEMLISTS SET RATE =-1.0 * @TDS WHERE INDEXID=10
IF @TCS <> 0    UPDATE #ITEMLISTS SET RATE = -1.0 * @TCS WHERE INDEXID=11
IF @TDSCGST <> 0      UPDATE #ITEMLISTS SET RATE =-1.0*  @TDSCGST WHERE INDEXID=12
IF @TDSSGST <> 0        UPDATE #ITEMLISTS SET RATE = -1.0*  @TDSSGST WHERE INDEXID=13
IF @OTHERDEBIT <> 0    UPDATE #ITEMLISTS SET RATE = -1.0 * @OTHERDEBIT WHERE INDEXID=14

 

UPDATE #ITEMLISTS SET GSTPERCENTAGE=@GSTPERCENTAGE WHERE INDEXID BETWEEN 1 AND 8  
 
UPDATE #ITEMLISTS SET CGST =0.5* (RATE * GSTPERCENTAGE)/100.0 WHERE GSTPERCENTAGE<>0 AND INDEXID<>5

UPDATE #ITEMLISTS SET SGST =0.5* (RATE * GSTPERCENTAGE)/100.00 WHERE GSTPERCENTAGE<>0 AND INDEXID<>5
 
UPDATE #ITEMLISTS SET CGST=@CGST,SGST=@SGST, IGST = @IGST  WHERE GSTPERCENTAGE<>0 AND INDEXID=5

UPDATE #ITEMLISTS SET CGST=0 WHERE CGST IS NULL
UPDATE #ITEMLISTS SET SGST=0 WHERE SGST IS NULL
UPDATE #ITEMLISTS SET IGST=0 WHERE IGST IS NULL
UPDATE #ITEMLISTS SET LINETOTAL = 0 

UPDATE #ITEMLISTS SET LINETOTAL = RATE+CGST+SGST+IGST 

 

DELETE FROM #ITEMLISTS WHERE RATE=0

 

 
INSERT INTO #EIDETAILS(DETAILID,HEADERID,ITEMDESCRIPTION,HSNCODE,UOM,QTY,RATE,GSTPERCENTAGE,CGSTAMOUNT,SGSTAMOUNT,IGSTAMOUNT)
SELECT SLNO,HEADERID,ITEMDESCRIPTION,HSNCODE,UOM,QTY,RATE,GSTPERCENTAGE,CGST,SGST,IGST 
FROM #ITEMLISTS  WHERE HEADERID=@HEADERID 

UPDATE #EI SET SSTATE = EIS.STATENAME FROM EI.STATECODE EIS INNER JOIN #EI ON #EI.SSTATECODE = EIS.STATECODE 
UPDATE #EI SET BSTATE = EIS.STATENAME FROM EI.STATECODE EIS INNER JOIN #EI ON #EI.BSTATECODE = EIS.STATECODE 

SELECT @NETINVOICEAMOUNT = SUM((QTY*RATE)+CGSTAMOUNT+SGSTAMOUNT+IGSTAMOUNT) FROM #EIDETAILS 


DECLARE @RUPEES INT 
DECLARE @PAISE  INT
SET @RUPEES = FLOOR(@NETINVOICEAMOUNT) 
SET @PAISE =  CAST(CONVERT(DECIMAL(18,0),(@NETINVOICEAMOUNT % 1) * 100  ) AS INT)
 



SELECT @AMOUNTINWORDSRUPEE = [dbo].[fn_ToWords](@RUPEES, 'UK',1) 

SET @AMOUNTINWORDS ='Rupees ' +  LTRIM(RTRIM( @AMOUNTINWORDSRUPEE )) 

IF @PAISE >0  
 BEGIN 
    SELECT @AMOUNTINWORDSPAISE = [dbo].[fn_ToWords](@PAISE, 'UK',1) 
	SET @AMOUNTINWORDS = @AMOUNTINWORDS  + ' and  ' + LTRIM ( RTRIM ( @AMOUNTINWORDSPAISE  )) + ' Paisa ' 
 END 
 
 SET @AMOUNTINWORDS = @AMOUNTINWORDS + + ' Only '


 

UPDATE #EI SET TOTALAMOUNTINWORDS = @AMOUNTINWORDS  

 

--UPDATE #EIDETAILS SET HSNCODE = '7204' WHERE ITEMDESCRIPTION ='Scarp Sale/Other Income'
--UPDATE #EIDETAILS SET HSNCODE = '99542' WHERE ITEMDESCRIPTION ='Mobilization Advance Received'
--UPDATE #EIDETAILS SET HSNCODE = '99542' WHERE ITEMDESCRIPTION ='Material Advance Received'
--UPDATE #EIDETAILS SET HSNCODE = '99542' WHERE ITEMDESCRIPTION ='Mivan  Advance Received'
UPDATE #EIDETAILS SET HSNCODE = '99541' WHERE ITEMDESCRIPTION ='Total Work Done'

SELECT H.FINYEAR,PERIODNAME,
       H.PROJECTNAME,H.INVOICENUMBER,H.INVOICEDATE,H.INVOICETYPE,
	   H.PARTYCODE,H.PARTYNAME,
       H.ACKNUMBER,H.ACKDATE,H.IRN,H.QRCODE,
	   H.SGSTIN,H.SELLERNAME,H.SADDR1,H.SADDR2,H.SLOCATION,H.SSTATE,H.SPIN,
	   H.BGSTIN,H.BUYERNAME,H.BADDR1,H.BADDR2,H.BLOCATION,H.BSTATE,H.BPIN,
	   D.ITEMDESCRIPTION,D.HSNCODE,D.UOM,D.QTY,D.RATE,D.GSTPERCENTAGE,D.CGSTAMOUNT,D.SGSTAMOUNT,D.IGSTAMOUNT ,H.TOTALAMOUNTINWORDS
FROM #EI H INNER JOIN #EIDETAILS D ON H.HEADERID  = D.HEADERID 