/****** Object:  Procedure [EI].[spGenerateEInvoice]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE [EI].[spGenerateEInvoice](@HEADERID INT)
AS 

DECLARE @NETINVOICEAMOUNT DECIMAL(18,2) 
DECLARE @AMOUNTINWORDS VARCHAR(400)

CREATE TABLE #EI
(FINYEAR INT, PERIOD INT, PERIODNAME VARCHAR(25),HEADERID INT,PROJECTCODE INT,PROJECTNAME VARCHAR(150),INVOICENUMBER VARCHAR(25),INVOICEDATE DATETIME,INVOICETYPE CHAR(3),
PARTYCODE VARCHAR(15),PARTYNAME VARCHAR(150),ACKNUMBER VARCHAR(25),ACKDATE DATETIME,IRN VARCHAR(200),QRCODE IMAGE,
SGSTINID INT,SGSTIN VARCHAR(16),SELLERNAME VARCHAR(200),SADDR1 VARCHAR(100),SADDR2 VARCHAR(100),SLOCATION VARCHAR(100),SSTATECODE CHAR(2),SPIN VARCHAR(6),SSTATE VARCHAR(25),
             BGSTIN VARCHAR(16),BUYERNAME  VARCHAR(200),BADDR1 VARCHAR(100),BADDR2 VARCHAR(100),BLOCATION VARCHAR(100),BSTATECODE CHAR(2),BPIN VARCHAR(6),BSTATE VARCHAR(25),
			 TOTALAMOUNTINWORDS VARCHAR(500)
) 

CREATE TABLE #EIDETAILS
(DETAILID INT,HEADERID INT,ITEMDESCRIPTION VARCHAR(100), HSNCODE VARCHAR(15),UOM VARCHAR(3), QTY DECIMAL(18,2), RATE DECIMAL(18,2), GSTPERCENTAGE DECIMAL(18,2),CGSTAMOUNT DECIMAL(18,2),
 SGSTAMOUNT DECIMAL(18,2), IGSTAMOUNT DECIMAL(18,2) )


INSERT INTO #EI(HEADERID,PROJECTCODE,INVOICENUMBER,INVOICEDATE,INVOICETYPE,PARTYCODE,PARTYNAME,ACKNUMBER,ACKDATE,IRN,QRCODE) 
SELECT REFERENCEHEADERID,BORGID,INVOICENUMBER,INVOICEDATE,INVOICETYPE,PARTYCODE,PARTYNAME,ACKNUMBER,ACKDATE,IRN,QRCODE 
FROM EI.EINVOICE WHERE REFERENCEHEADERID=@HEADERID 

UPDATE #EI SET FINYEAR = EIH.FINYEAR, PERIOD=EIH.[PERIOD] FROM EI.EINVOICEHEADER EIH INNER JOIN #EI ON #EI.HEADERID = EIH.INVOICEINDEX 
UPDATE #EI SET PERIODNAME  =  BSP.PERIODDESC FROM PERIODMASTER  BSP INNER JOIN #EI ON #EI.PERIOD = BSP.PERIODID


UPDATE #EI SET PROJECTNAME =ECP.BSBORGNAME,SGSTINID=ECP.GSTINID FROM EC.PROJECTS ECP INNER JOIN #EI ON #EI.PROJECTCODE=ECP.BSBORGID 
UPDATE #EI SET SGSTIN=EIG.GSTIN,SELLERNAME=EIG.LEGALNAME,SADDR1=EIG.ADDRESS1,SADDR2=EIG.ADDRESS2,SLOCATION=EIG.LOCATION,SSTATECODE=EIG.STATECODE,SPIN=EIG.PIN 
FROM EI.GSTINS EIG INNER JOIN #EI ON #EI.SGSTINID=EIG.GSTINID 
UPDATE #EI SET BGSTIN=EIG.GSTIN,BUYERNAME=EIG.LEGALNAME,BADDR1=EIG.ADDRESS1,BADDR2=EIG.ADDRESS2,BLOCATION=EIG.LOCATION,BSTATECODE=EIG.STATECODE,BPIN=EIG.PIN 
FROM EI.GSTINS EIG INNER JOIN #EI ON #EI.PARTYCODE=EIG.CREDNO 

DECLARE @INVOICETYPE CHAR(3)
SELECT @INVOICETYPE=INVOICETYPE FROM #EI
IF @INVOICETYPE = 'DRN'
   INSERT INTO #EIDETAILS(DETAILID,HEADERID,ITEMDESCRIPTION,HSNCODE,UOM,QTY,RATE,GSTPERCENTAGE,CGSTAMOUNT,SGSTAMOUNT,IGSTAMOUNT)
   SELECT DETAILINDEX,HEADERID,ITEMDESCRIPTION,HSNCODE,UOM,QTY,RATE,GSTPERCENTAGE,CGSTAMOUNT,SGSTAMOUNT,IGSTAMOUNT  
   FROM EI.EINVOICEDETAILS WHERE HEADERID=@HEADERID AND EINVOICETYPE='D'

UPDATE #EI SET SSTATE = EIS.STATENAME FROM EI.STATECODE EIS INNER JOIN #EI ON #EI.SSTATECODE = EIS.STATECODE 
UPDATE #EI SET BSTATE = EIS.STATENAME FROM EI.STATECODE EIS INNER JOIN #EI ON #EI.BSTATECODE = EIS.STATECODE 

SELECT @NETINVOICEAMOUNT = SUM((QTY*RATE)+CGSTAMOUNT+SGSTAMOUNT+IGSTAMOUNT) FROM #EIDETAILS 
SELECT @AMOUNTINWORDS = [dbo].[fn_ToWords](@NETINVOICEAMOUNT, 'UK',1) 
UPDATE #EI SET TOTALAMOUNTINWORDS = @AMOUNTINWORDS

SELECT H.FINYEAR,PERIODNAME,
       H.PROJECTNAME,H.INVOICENUMBER,H.INVOICEDATE,H.INVOICETYPE,
	   H.PARTYCODE,H.PARTYNAME,
       H.ACKNUMBER,H.ACKDATE,H.IRN,H.QRCODE,
	   H.SGSTIN,H.SELLERNAME,H.SADDR1,H.SADDR2,H.SLOCATION,H.SSTATE,H.SPIN,
	   H.BGSTIN,H.BUYERNAME,H.BADDR1,H.BADDR2,H.BLOCATION,H.BSTATE,H.BPIN,
	   D.ITEMDESCRIPTION,D.HSNCODE,D.UOM,D.QTY,D.RATE,D.GSTPERCENTAGE,D.CGSTAMOUNT,D.SGSTAMOUNT,D.IGSTAMOUNT ,H.TOTALAMOUNTINWORDS
FROM #EI H INNER JOIN #EIDETAILS D ON H.HEADERID  = D.HEADERID 