/****** Object:  Procedure [EI].[spUpdateEInvoice]    Committed by VersionSQL https://www.versionsql.com ******/

 
CREATE PROCEDURE [EI].[spUpdateEInvoice](@INVOICECATEGORY INT,@INVOICEINDEX INT,@INVOICENUMBER VARCHAR(25), @ACKNUMBER VARCHAR(25), @ACKDATESTRING VARCHAR(25) ,@IRN VARCHAR(100),@INVOICETYPE CHAR(3),@QRIMAGE IMAGE,@FILESIZE INT )
AS

DECLARE @BORGID INT 
DECLARE @INVOICEDATE DATETIME 
DECLARE @PARTYID  INT 
DECLARE @PARTYCODE VARCHAR(15) 
DECLARE @PARTYNAME VARCHAR(250) 
DECLARE @INVOICEAMOUNT DECIMAL(18,2) 
DECLARE @ACKDATE DATETIME 

SET @ACKDATE = CONVERT(DATETIME,@ACKDATESTRING,103)

IF @INVOICECATEGORY = 1  -- DEBTOR INVOICE 
 BEGIN
   SELECT @BORGID=BORGID, @INVOICEDATE = INVOICEDATE , @PARTYID = DEBTORNUMBER  FROM EI.DEBTORINVOICEHEADER  WHERE INVOICEINDEX=@INVOICEINDEX
   SELECT @PARTYCODE = DEBTNUMBER , @PARTYNAME = UPPER(DEBTNAME) FROM DEBTORS WHERE DEBTID = @PARTYID 
   SELECT @INVOICEAMOUNT= NETRECEIVABLE FROM  EI.DEBTINVOICEDETAILS WHERE HEADERID=@INVOICEINDEX
 END
ELSE
 BEGIN
   SELECT @BORGID=BORGID, @INVOICEDATE = INVOICEDATE , @PARTYID = SUBCONNUMBER FROM EI.EINVOICEHEADER  WHERE INVOICEINDEX=@INVOICEINDEX
   SELECT @PARTYCODE = SUBNUMBER, @PARTYNAME = UPPER(SUBNAME) FROM SUBCONTRACTORS WHERE SUBID = @PARTYID 

   IF @INVOICETYPE='DRN' 
   SELECT @INVOICEAMOUNT= SUM( (QTY*RATE) + CGSTAMOUNT + SGSTAMOUNT + IGSTAMOUNT ) FROM EI.EINVOICEDETAILS WHERE HEADERID=@INVOICEINDEX AND EINVOICETYPE='D' 

   IF @INVOICETYPE='INV' 
   SELECT @INVOICEAMOUNT= SUM( (QTY*RATE) + CGSTAMOUNT + SGSTAMOUNT + IGSTAMOUNT ) FROM EI.EINVOICEDETAILS WHERE HEADERID=@INVOICEINDEX AND EINVOICETYPE='D' 

   IF @INVOICETYPE='CRN' 
   SELECT @INVOICEAMOUNT = SUM( (QTY*RATE) + CGSTAMOUNT + SGSTAMOUNT + IGSTAMOUNT ) FROM EI.EINVOICEDETAILS WHERE HEADERID=@INVOICEINDEX AND EINVOICETYPE='C' 

 END

INSERT INTO EI.EINVOICE(BORGID, REFERENCEHEADERID, INVOICENUMBER, INVOICEDATE, PARTYCODE, PARTYNAME, INVOICETYPE, INVOICEAMOUNT, ACKNUMBER,  ACKDATE, IRN,  QRCODE,  IMAGESIZE,TRANSGROUP)
VALUES (                @BORGID,@INVOICEINDEX,     @INVOICENUMBER,@INVOICEDATE,@PARTYCODE,@PARTYNAME,@INVOICETYPE,@INVOICEAMOUNT,@ACKNUMBER, @ACKDATE,@IRN, @QRIMAGE,@FILESIZE,-1) 