/****** Object:  Table [BI].[CASHFLOWINDICATORS]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [BI].[CASHFLOWINDICATORS](
	[INDEXCODE] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[CATEGORYCODE] [char](1) NULL,
	[POSITIONID] [int] NULL,
	[INDICATORCODE] [int] NULL,
	[LINETYPE] [varchar](10) NULL,
	[DESCRIPTIONCODE] [char](5) NULL,
	[DESCRIPTION] [varchar](50) NULL,
 CONSTRAINT [PK__CASHFLOW__0A93C88ABD3B2936] PRIMARY KEY CLUSTERED 
(
	[INDEXCODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]