/****** Object:  Table [BI].[GROUPLEDGERHEAD]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [BI].[GROUPLEDGERHEAD](
	[GROUPLEDGERCODE] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[GROUPLEDGERNAME] [varchar](50) NULL,
	[SUBLEDGERAPPLICABLE] [int] NULL,
 CONSTRAINT [PK_GROUPLEDGERHEAD] PRIMARY KEY CLUSTERED 
(
	[GROUPLEDGERCODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]