/****** Object:  Table [BI].[INDICATORDETAIL]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [BI].[INDICATORDETAIL](
	[DETAILID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[INDICATORID] [int] NULL,
	[LEDGERCODE] [varchar](15) NULL,
PRIMARY KEY CLUSTERED 
(
	[DETAILID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]