/****** Object:  Table [BI].[LockedUsers]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [BI].[LockedUsers](
	[ID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[LOGINID] [varchar](15) NULL,
	[USERID] [int] NULL,
	[USERNAME] [varchar](50) NULL,
	[LOCKEDATE] [datetime] NULL,
 CONSTRAINT [PK__LockedUs__3214EC27D6DDD85D] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]