/****** Object:  Table [BI].[STOCKTRANSACTIONS]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [BI].[STOCKTRANSACTIONS](
	[TRANSID] [bigint] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[TRANSTYPE] [char](1) NULL,
	[REFERNCEID] [int] NULL,
	[BORGID] [int] NULL,
	[STORECODE] [varchar](15) NULL,
	[STOCKCODE] [varchar](15) NULL,
	[DLVRDATE] [datetime] NULL,
	[DLVRNO] [varchar](25) NULL,
	[DLVRQTY] [decimal](18, 2) NULL,
	[DLVRRATE] [decimal](18, 2) NULL,
	[ISSUEDATE] [datetime] NULL,
	[ISSUEREF] [varchar](10) NULL,
	[ISSUETYPE] [varchar](10) NULL,
	[ISSUEQTY] [decimal](18, 2) NULL,
	[ISSUERATE] [decimal](18, 2) NULL,
	[TRANSFERDATE] [datetime] NULL,
	[TRANSFERREF] [varchar](15) NULL,
	[TRANSFEROUT] [decimal](18, 2) NULL,
	[TRANSFERIN] [decimal](18, 2) NULL,
	[TRANSFERRATE] [decimal](18, 2) NULL,
	[TRANSFERVALUE] [decimal](18, 2) NULL,
 CONSTRAINT [PK__STOCKTRA__D4B60CAFE1DB744A] PRIMARY KEY CLUSTERED 
(
	[TRANSID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]