/****** Object:  Table [BI].[YEARLYBUDGETS]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [BI].[YEARLYBUDGETS](
	[FINYEAR] [int] NOT NULL,
	[ORGID] [int] NOT NULL,
	[LEDGERCODE] [varchar](15) NOT NULL,
	[PERIOD] [int] NOT NULL,
	[BUDGET] [decimal](18, 2) NULL,
 CONSTRAINT [PK_YEARLYBUDGETS] PRIMARY KEY CLUSTERED 
(
	[FINYEAR] ASC,
	[ORGID] ASC,
	[LEDGERCODE] ASC,
	[PERIOD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]