/****** Object:  Table [dbo].[AABATCHHEADER]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[AABATCHHEADER](
	[HeaderID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[SiteRef] [char](50) NOT NULL,
	[BatchRef] [char](50) NOT NULL,
	[PAYROLLID] [int] NOT NULL,
	[PERIODNO] [smallint] NOT NULL,
	[RUNNO] [smallint] NOT NULL,
	[YEARNO] [smallint] NOT NULL,
	[LockHolder] [int] NOT NULL,
	[LockRequestor] [int] NOT NULL,
	[valid] [bit] NOT NULL,
	[posted] [bit] NOT NULL,
	[totRecords] [float] NULL,
	[totEmployees] [float] NULL,
	[totAmount] [float] NULL,
	[UseHashEmployees] [bit] NOT NULL,
	[UseHashRecords] [bit] NOT NULL,
	[UseHashAmounts] [bit] NOT NULL,
	[WORKFLOWSTATUS] [int] NOT NULL,
	[BATCHOWNER] [int] NOT NULL,
 CONSTRAINT [PK_AABATCHHEADER] PRIMARY KEY CLUSTERED 
(
	[HeaderID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[AABATCHHEADER] ADD  CONSTRAINT [DF_AABATCHHEADER_LockHolder_1]  DEFAULT (0) FOR [LockHolder]
ALTER TABLE [dbo].[AABATCHHEADER] ADD  CONSTRAINT [DF_AABATCHHEADER_LockRequestor_1]  DEFAULT (0) FOR [LockRequestor]
ALTER TABLE [dbo].[AABATCHHEADER] ADD  CONSTRAINT [DF_AABATCHHEADER_valid]  DEFAULT (0) FOR [valid]
ALTER TABLE [dbo].[AABATCHHEADER] ADD  CONSTRAINT [DF_AABATCHHEADER_posted]  DEFAULT (0) FOR [posted]
ALTER TABLE [dbo].[AABATCHHEADER] ADD  CONSTRAINT [DF__AABATCHHE__UseHa__489308B8]  DEFAULT (0) FOR [UseHashEmployees]
ALTER TABLE [dbo].[AABATCHHEADER] ADD  CONSTRAINT [DF__AABATCHHE__UseHa__49872CF1]  DEFAULT (0) FOR [UseHashRecords]
ALTER TABLE [dbo].[AABATCHHEADER] ADD  CONSTRAINT [DF__AABATCHHE__UseHa__4A7B512A]  DEFAULT (0) FOR [UseHashAmounts]
ALTER TABLE [dbo].[AABATCHHEADER] ADD  CONSTRAINT [DF_AABATCHHEADER_WORKFLOWSTATUS]  DEFAULT ((0)) FOR [WORKFLOWSTATUS]
ALTER TABLE [dbo].[AABATCHHEADER] ADD  CONSTRAINT [DF_AABATCHHEADER_BATCHOWNER]  DEFAULT ((0)) FOR [BATCHOWNER]