/****** Object:  Table [dbo].[AABATCHDETAIL]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[AABATCHDETAIL](
	[DetailId] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[HeaderID] [int] NOT NULL,
	[EMPNUMBER] [nvarchar](15) NOT NULL,
	[DAYNO] [int] NOT NULL,
	[Amount] [money] NOT NULL,
	[EDSCODE] [nvarchar](5) NOT NULL,
	[LEDGERCODE] [char](10) NULL,
	[COSTALLOCATION] [varchar](50) NULL,
	[ACTNUMBER] [char](10) NULL,
	[tDiv] [int] NULL,
	[tPayrollid] [int] NULL,
	[TEDSHID] [int] NULL,
	[WEEKNO] [int] NOT NULL,
 CONSTRAINT [PK_AABATCHDETAIL] PRIMARY KEY CLUSTERED 
(
	[DetailId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[AABATCHDETAIL] ADD  DEFAULT ((-1)) FOR [WEEKNO]