/****** Object:  Table [dbo].[ACCBOQPREV]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[ACCBOQPREV](
	[RECONID] [int] NOT NULL,
	[ACTID] [int] NOT NULL,
	[AMOUNT] [decimal](18, 4) NOT NULL,
	[FILETYPE] [nvarchar](10) NOT NULL,
 CONSTRAINT [PK_ACCBOQPREV] PRIMARY KEY CLUSTERED 
(
	[RECONID] ASC,
	[ACTID] ASC,
	[FILETYPE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]