/****** Object:  Table [dbo].[ACCRUALSSNAPSHOT]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[ACCRUALSSNAPSHOT](
	[TRANSID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[SNAPSHOTSID] [int] NOT NULL,
	[PDATE] [datetime] NULL,
	[BATCHREF] [nvarchar](15) NULL,
	[TRANSREF] [nvarchar](10) NOT NULL,
	[LEDGERCODE] [nvarchar](10) NOT NULL,
	[CONTRACT] [nvarchar](10) NULL,
	[DESCRIPTION] [nvarchar](max) NOT NULL,
	[CURRENCY] [nvarchar](3) NOT NULL,
	[DEBIT] [money] NOT NULL,
	[CREDIT] [money] NOT NULL,
	[CREDNO] [nvarchar](10) NOT NULL,
	[CREDREC] [nvarchar](127) NULL,
	[DEBTREC] [nvarchar](127) NULL,
	[SUBBREC] [nvarchar](127) NULL,
	[PLANTNO] [nvarchar](15) NOT NULL,
	[STOCKNO] [nvarchar](20) NOT NULL,
	[STORE] [nvarchar](20) NOT NULL,
	[QUANTITY] [numeric](38, 8) NOT NULL,
	[UNIT] [nvarchar](25) NULL,
	[GRNNO] [nvarchar](12) NULL,
	[HOMECURRAMOUNT] [money] NULL,
	[CONTRNAME] [nvarchar](55) NULL,
	[LEDGERNAME] [nvarchar](80) NULL,
	[PROJNAME] [nvarchar](55) NULL,
	[PROJNUMBER] [nvarchar](10) NULL,
	[YEAR] [nvarchar](10) NOT NULL,
	[PERIOD] [int] NOT NULL,
	[ORDERNO] [nvarchar](55) NOT NULL,
	[ALLOCATION] [nvarchar](55) NOT NULL,
	[ACCRUAL] [nvarchar](255) NOT NULL,
	[BORGID] [int] NOT NULL,
	[CONSTATUS] [int] NULL,
	[ACTNAME] [nvarchar](35) NULL,
	[ACTNUMBER] [nvarchar](10) NULL,
	[ACTUNIT] [nvarchar](10) NULL,
	[STKID] [int] NULL,
	[RATE] [numeric](38, 8) NOT NULL,
	[DIV] [int] NOT NULL,
	[DIVCODE] [nvarchar](10) NULL,
	[TID] [int] NOT NULL,
	[DELNO] [nvarchar](55) NULL,
	[VATID] [nvarchar](100) NULL,
 CONSTRAINT [PK_ACCRUALSSNAPSHOT] PRIMARY KEY CLUSTERED 
(
	[TRANSID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

CREATE NONCLUSTERED INDEX [IX_ACCRUALSSNAPSHOT_SNAPSHOTSID] ON [dbo].[ACCRUALSSNAPSHOT]
(
	[SNAPSHOTSID] ASC
)
INCLUDE([LEDGERCODE],[CURRENCY],[DEBIT],[CREDIT],[HOMECURRAMOUNT],[LEDGERNAME],[ACTNAME],[ACTNUMBER]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
ALTER TABLE [dbo].[ACCRUALSSNAPSHOT] ADD  CONSTRAINT [DF_ACCRUALSSNAPSHOT_DIV]  DEFAULT ((-1)) FOR [DIV]
ALTER TABLE [dbo].[ACCRUALSSNAPSHOT] ADD  CONSTRAINT [DF_ACCRUALSSNAPSHOT_TID]  DEFAULT ((0)) FOR [TID]