/****** Object:  Table [dbo].[ADVAMOUNTS]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[ADVAMOUNTS](
	[ADVAMID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[PAYROLLID] [int] NOT NULL,
	[ALLOCATION] [char](25) NOT NULL,
	[CONTRID] [int] NOT NULL,
	[CONTRNUMBER] [nvarchar](10) NOT NULL,
	[ACTID] [int] NOT NULL,
	[ACTNUMBER] [char](10) NOT NULL,
	[LEDGERID] [int] NOT NULL,
	[LEDGERCODE] [char](10) NOT NULL,
	[PENUMBER] [char](10) NOT NULL,
	[DIVID] [int] NOT NULL,
	[AMOUNT] [money] NOT NULL,
	[EDSHID] [int] NOT NULL,
	[EDSID] [int] NOT NULL,
	[EDSCODE] [nvarchar](5) NOT NULL,
	[EDSNUMBER] [nvarchar](5) NOT NULL,
	[EMPID] [int] NOT NULL,
	[EMPNUMBER] [nvarchar](15) NOT NULL,
	[PERIODNO] [int] NOT NULL,
	[RUNNO] [int] NOT NULL,
	[YEARNO] [int] NOT NULL,
	[COST] [decimal](19, 4) NOT NULL,
	[CAPTAMOUNT] [decimal](19, 4) NOT NULL,
	[HEADERID] [int] NULL,
	[DAYNO] [int] NOT NULL,
	[WEEKNO] [int] NOT NULL,
 CONSTRAINT [PK_ADVAMOUNTS] PRIMARY KEY CLUSTERED 
(
	[ADVAMID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [IX_AA_PAYROLLID_EMPNUMBER_YEARNO_PERIODNO_RUNNO] ON [dbo].[ADVAMOUNTS]
(
	[PAYROLLID] ASC,
	[EMPNUMBER] ASC,
	[YEARNO] ASC,
	[PERIODNO] ASC,
	[RUNNO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [IX_AA_PAYROLLID_EMPNUMBER_YEARNO_PERIODNO_RUNNO_CONTRNUMBER_ACTNUMBER_PENUMBER_DIVID_LEDGERCODE] ON [dbo].[ADVAMOUNTS]
(
	[PAYROLLID] ASC,
	[EMPNUMBER] ASC,
	[YEARNO] ASC,
	[PERIODNO] ASC,
	[RUNNO] ASC,
	[CONTRNUMBER] ASC,
	[ACTNUMBER] ASC,
	[PENUMBER] ASC,
	[DIVID] ASC,
	[LEDGERCODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [IX_AA_PAYROLLID_EMPNUMBER_YEARNO_PERIODNO_RUNNO_EDSNUMBER] ON [dbo].[ADVAMOUNTS]
(
	[PAYROLLID] ASC,
	[EMPNUMBER] ASC,
	[YEARNO] ASC,
	[PERIODNO] ASC,
	[RUNNO] ASC,
	[EDSNUMBER] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [IX_ADVAMOUNTS_PAYROLLID_ALLOCATION_YEARNO_RUNNO_PERIODNO_ADVAMID_CONTRID_CONTRNUMBER_LEDGERCODE_PENUMBER] ON [dbo].[ADVAMOUNTS]
(
	[PAYROLLID] ASC,
	[ALLOCATION] ASC,
	[YEARNO] ASC,
	[RUNNO] ASC,
	[PERIODNO] ASC,
	[ADVAMID] ASC,
	[CONTRID] ASC,
	[CONTRNUMBER] ASC,
	[LEDGERCODE] ASC,
	[PENUMBER] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
ALTER TABLE [dbo].[ADVAMOUNTS] ADD  CONSTRAINT [DF_ADVAMOUNTS_ALLOCATION]  DEFAULT ('') FOR [ALLOCATION]
ALTER TABLE [dbo].[ADVAMOUNTS] ADD  CONSTRAINT [DF_ADVAMOUNTS_CONTRID]  DEFAULT ((-1)) FOR [CONTRID]
ALTER TABLE [dbo].[ADVAMOUNTS] ADD  CONSTRAINT [DF_ADVAMOUNTS_CONTRNUMBER]  DEFAULT ('') FOR [CONTRNUMBER]
ALTER TABLE [dbo].[ADVAMOUNTS] ADD  CONSTRAINT [DF_ADVAMOUNTS_ACTID]  DEFAULT ((-1)) FOR [ACTID]
ALTER TABLE [dbo].[ADVAMOUNTS] ADD  CONSTRAINT [DF_ADVAMOUNTS_ACTNUMBER]  DEFAULT ('') FOR [ACTNUMBER]
ALTER TABLE [dbo].[ADVAMOUNTS] ADD  CONSTRAINT [DF_ADVAMOUNTS_LEDGERID]  DEFAULT ((-1)) FOR [LEDGERID]
ALTER TABLE [dbo].[ADVAMOUNTS] ADD  CONSTRAINT [DF_ADVAMOUNTS_LEDGERCODE]  DEFAULT ('') FOR [LEDGERCODE]
ALTER TABLE [dbo].[ADVAMOUNTS] ADD  CONSTRAINT [DF_ADVAMOUNTS_PENUMBER]  DEFAULT ('') FOR [PENUMBER]
ALTER TABLE [dbo].[ADVAMOUNTS] ADD  CONSTRAINT [DF_ADVAMOUNTS_DIVID]  DEFAULT ((-1)) FOR [DIVID]
ALTER TABLE [dbo].[ADVAMOUNTS] ADD  CONSTRAINT [DF_ADVAMOUNTS_AMOUNT_1]  DEFAULT (0) FOR [AMOUNT]
ALTER TABLE [dbo].[ADVAMOUNTS] ADD  CONSTRAINT [DF_ADVAMOUNTS_EDSCODE]  DEFAULT ('') FOR [EDSCODE]
ALTER TABLE [dbo].[ADVAMOUNTS] ADD  CONSTRAINT [DF_ADVAMOUNTS_EDSNUMBER]  DEFAULT ('') FOR [EDSNUMBER]
ALTER TABLE [dbo].[ADVAMOUNTS] ADD  CONSTRAINT [DF_ADVAMOUNTS_COST]  DEFAULT (0) FOR [COST]
ALTER TABLE [dbo].[ADVAMOUNTS] ADD  CONSTRAINT [DF__ADVAMOUNT__CAPTA__3D21560C]  DEFAULT (0) FOR [CAPTAMOUNT]
ALTER TABLE [dbo].[ADVAMOUNTS] ADD  DEFAULT ((-1)) FOR [DAYNO]
ALTER TABLE [dbo].[ADVAMOUNTS] ADD  DEFAULT ((-1)) FOR [WEEKNO]