/****** Object:  Table [dbo].[ALCHEMEXMENU]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[ALCHEMEXMENU](
	[AID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[RID] [int] NOT NULL,
	[NAME] [nvarchar](50) NOT NULL,
	[DESCR] [nvarchar](255) NOT NULL,
	[LEV] [int] NOT NULL,
	[MENUDESCR] [nvarchar](50) NOT NULL,
	[SEQ] [int] NOT NULL,
	[SYS] [nvarchar](3) NOT NULL,
	[INUSE] [bit] NOT NULL,
 CONSTRAINT [PK_ALCHEMEXMENU] PRIMARY KEY CLUSTERED 
(
	[AID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[ALCHEMEXMENU] ADD  CONSTRAINT [DF_ALCHEMEXMENU_NAME]  DEFAULT ('') FOR [NAME]
ALTER TABLE [dbo].[ALCHEMEXMENU] ADD  CONSTRAINT [DF_ALCHEMEXMENU_DESCR]  DEFAULT ('') FOR [DESCR]
ALTER TABLE [dbo].[ALCHEMEXMENU] ADD  CONSTRAINT [DF_Table_1_LEVEL]  DEFAULT ((1)) FOR [LEV]
ALTER TABLE [dbo].[ALCHEMEXMENU] ADD  CONSTRAINT [DF_ALCHEMEXMENU_MENUDESCR]  DEFAULT ('') FOR [MENUDESCR]
ALTER TABLE [dbo].[ALCHEMEXMENU] ADD  CONSTRAINT [DF_ALCHEMEXMENU_SEQ]  DEFAULT ((-1)) FOR [SEQ]
ALTER TABLE [dbo].[ALCHEMEXMENU] ADD  CONSTRAINT [DF_ALCHEMEXMENU_SYS]  DEFAULT ('') FOR [SYS]
ALTER TABLE [dbo].[ALCHEMEXMENU] ADD  CONSTRAINT [DF_ALCHEMEXMENU_INUSE]  DEFAULT ((1)) FOR [INUSE]