/****** Object:  Table [dbo].[ALCHEMEXROLE]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[ALCHEMEXROLE](
	[RID] [int] NOT NULL,
	[SYS] [nvarchar](3) NOT NULL,
	[ROLEID] [int] NOT NULL,
	[ITEMENABLED] [bit] NOT NULL,
 CONSTRAINT [PK_ALCHEMEXROLE] PRIMARY KEY CLUSTERED 
(
	[RID] ASC,
	[SYS] ASC,
	[ROLEID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[ALCHEMEXROLE] ADD  CONSTRAINT [DF_ALCHEMEXROLE_ITEMENABLED]  DEFAULT ((0)) FOR [ITEMENABLED]