/****** Object:  Table [dbo].[ALTCODES]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[ALTCODES](
	[ID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[ALTCODE] [nvarchar](50) NOT NULL,
	[ALTTYPE] [nvarchar](10) NOT NULL,
	[ACTUALCODE] [nvarchar](30) NOT NULL,
	[REFTYPE] [nvarchar](50) NOT NULL,
	[SHOWINPOS] [bit] NOT NULL,
	[DESCRIPTION] [nvarchar](255) NOT NULL,
 CONSTRAINT [PK_ALTCODES] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[ALTCODES] ADD  CONSTRAINT [DF_ALTCODES_SHOWINPOS]  DEFAULT ('0') FOR [SHOWINPOS]