/****** Object:  Table [dbo].[ASSET_UPLOAD]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[ASSET_UPLOAD](
	[ASSETID] [bigint] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[ASSETNUMBER] [varchar](25) NULL,
	[ASSETNAME] [varchar](250) NULL,
	[PURCHASEDATE] [datetime] NULL,
	[PURCHASEPRICE] [money] NULL,
	[BOOKVALUE] [money] NULL,
	[ACCUMULATEDDEP] [money] NULL,
 CONSTRAINT [PK_ASSET_UPLOAD] PRIMARY KEY CLUSTERED 
(
	[ASSETID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]