/****** Object:  Table [dbo].[ASSETPOSTS130117]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[ASSETPOSTS130117](
	[OrgID] [int] NOT NULL,
	[Year] [char](10) NOT NULL,
	[Period] [int] NOT NULL,
	[PDate] [datetime] NULL,
	[BatchRef] [char](10) NOT NULL,
	[TransRef] [char](10) NOT NULL,
	[MatchRef] [char](10) NOT NULL,
	[TransType] [char](10) NOT NULL,
	[Allocation] [char](25) NOT NULL,
	[LedgerCode] [char](10) NOT NULL,
	[Contract] [nvarchar](10) NOT NULL,
	[Activity] [char](10) NOT NULL,
	[Description] [char](255) NOT NULL,
	[ForeignDescription] [char](255) NOT NULL,
	[Currency] [nvarchar](3) NOT NULL,
	[Debit] [money] NOT NULL,
	[Credit] [money] NOT NULL,
	[VatDebit] [money] NOT NULL,
	[VatCredit] [money] NOT NULL,
	[Credno] [char](10) NOT NULL,
	[Store] [char](20) NOT NULL,
	[Plantno] [char](30) NULL,
	[Stockno] [char](20) NOT NULL,
	[Quantity] [numeric](23, 4) NOT NULL,
	[Unit] [char](10) NOT NULL,
	[Rate] [money] NOT NULL,
	[ReqNo] [char](55) NOT NULL,
	[OrderNo] [char](55) NOT NULL,
	[Age] [int] NOT NULL,
	[TransID] [int] IDENTITY(1,1) NOT NULL,
	[SubConTran] [char](20) NOT NULL,
	[VATType] [char](2) NOT NULL,
	[HomeCurrAmount] [money] NULL,
	[ConversionDate] [datetime] NULL,
	[ConversionRate] [money] NOT NULL,
	[PaidFor] [bit] NOT NULL,
	[PaidToDate] [money] NOT NULL,
	[PaidThisPeriod] [money] NOT NULL,
	[WhtThisPeriod] [money] NOT NULL,
	[DiscThisPeriod] [money] NOT NULL,
	[ReconStatus] [int] NOT NULL,
	[UserID] [char](10) NULL,
	[DivID] [int] NOT NULL,
	[ForexVal] [money] NOT NULL,
	[HeadID] [char](10) NULL,
	[XGLCODE] [char](10) NOT NULL,
	[XVATA] [money] NOT NULL,
	[XVATT] [char](2) NOT NULL,
	[DOCNUMBER] [nchar](50) NULL,
	[WHTID] [int] NULL,
	[FBID] [int] NULL,
	[TERM] [int] NULL,
	[SYSDATE] [datetime] NULL,
	[RECEIVEDDATE] [datetime] NULL,
	[ORIGTRANSID] [int] NULL,
	[HCTODATE] [numeric](18, 4) NULL,
	[TRANGRP] [int] NULL,
	[ROLLEDFWD] [int] NULL
) ON [PRIMARY]