/****** Object:  Table [dbo].[AUTOMATQUERYVAR]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[AUTOMATQUERYVAR](
	[AQVID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[AQID] [int] NOT NULL,
	[NAME] [nvarchar](55) NOT NULL,
	[DESCR] [nvarchar](255) NOT NULL,
	[COLTYPE] [nvarchar](55) NOT NULL,
	[VALUE] [nvarchar](255) NOT NULL,
 CONSTRAINT [PK_AUTOMATQUERYVAR] PRIMARY KEY CLUSTERED 
(
	[AQVID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[AUTOMATQUERYVAR] ADD  CONSTRAINT [DF_AUTOMATQUERYVAR_NAME]  DEFAULT ('') FOR [NAME]
ALTER TABLE [dbo].[AUTOMATQUERYVAR] ADD  CONSTRAINT [DF_AUTOMATQUERYVAR_DESCR]  DEFAULT ('') FOR [DESCR]
ALTER TABLE [dbo].[AUTOMATQUERYVAR] ADD  CONSTRAINT [DF_AUTOMATQUERYVAR_COLTYPE]  DEFAULT ('') FOR [COLTYPE]
ALTER TABLE [dbo].[AUTOMATQUERYVAR] ADD  CONSTRAINT [DF_AUTOMATQUERYVAR_VALUE]  DEFAULT ('') FOR [VALUE]
ALTER TABLE [dbo].[AUTOMATQUERYVAR]  WITH CHECK ADD  CONSTRAINT [FK_AUTOMATQUERYVAR_AUTOMATQUERY] FOREIGN KEY([AQID])
REFERENCES [dbo].[AUTOMATQUERY] ([AQID])
ALTER TABLE [dbo].[AUTOMATQUERYVAR] CHECK CONSTRAINT [FK_AUTOMATQUERYVAR_AUTOMATQUERY]