/****** Object:  Table [dbo].[AUTOVATLINKS]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[AUTOVATLINKS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[AUTOVATGROUPSID] [int] NOT NULL,
	[LOOKUPID] [int] NOT NULL,
 CONSTRAINT [PK_AUTOVATLINKS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[AUTOVATLINKS] ADD  CONSTRAINT [DF_AUTOVATLINKS_AUTOVATGROUPSID]  DEFAULT ((-1)) FOR [AUTOVATGROUPSID]
ALTER TABLE [dbo].[AUTOVATLINKS] ADD  CONSTRAINT [DF_AUTOVATLINKS_LOOKUPID]  DEFAULT ((-1)) FOR [LOOKUPID]