/****** Object:  Table [dbo].[AUTOVATGROUPS]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[AUTOVATGROUPS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[DESCR] [nvarchar](255) NOT NULL,
 CONSTRAINT [PK_AUTOVATGROUPS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[AUTOVATGROUPS] ADD  CONSTRAINT [DF_AUTOVATGROUPS_DESCR]  DEFAULT ('') FOR [DESCR]