/****** Object:  Table [dbo].[AUTOMATHISTORY]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[AUTOMATHISTORY](
	[AMHISTID] [int] IDENTITY(1,1) NOT NULL,
	[AMDID] [int] NOT NULL,
	[THEDATE] [datetime] NOT NULL,
	[STATUS] [nvarchar](35) NOT NULL,
	[DESCRIPTION] [nvarchar](255) NOT NULL
) ON [PRIMARY]

ALTER TABLE [dbo].[AUTOMATHISTORY] ADD  CONSTRAINT [DF_AUTOMATHISTORY_DESCRIPTION]  DEFAULT ('') FOR [DESCRIPTION]