/****** Object:  Table [dbo].[BANKSAPPROVAL]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[BANKSAPPROVAL](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[SOURCEID] [int] NOT NULL,
	[BankAccount] [nvarchar](50) NOT NULL,
	[BankBranch] [nvarchar](10) NOT NULL,
	[BankName] [nvarchar](35) NOT NULL,
	[BankAddress1] [nvarchar](35) NOT NULL,
	[BankAddress2] [nvarchar](35) NOT NULL,
	[BankAddress3] [nvarchar](35) NOT NULL,
	[BankPCode] [nvarchar](10) NOT NULL,
	[BankTel] [nvarchar](25) NOT NULL,
	[BankFax] [nvarchar](25) NOT NULL,
	[BankeMail] [nvarchar](35) NOT NULL,
	[BankContact] [nvarchar](35) NOT NULL,
	[BankManager] [nvarchar](35) NOT NULL,
	[BankURL] [nvarchar](55) NOT NULL,
	[BankLedger] [nvarchar](10) NOT NULL,
	[BankBalance] [money] NOT NULL,
	[BankBalanceClose] [money] NOT NULL,
	[BankPeriod] [nvarchar](20) NOT NULL,
	[BankBorgID] [int] NOT NULL,
	[SWIFT] [nvarchar](12) NOT NULL,
	[IFSC] [nvarchar](11) NOT NULL,
	[CHID] [int] NOT NULL,
	[BIC] [nvarchar](12) NOT NULL,
	[COUNTRY] [nvarchar](55) NOT NULL,
	[ISPDCBANK] [bit] NOT NULL,
	[PDCCONTROL] [nvarchar](10) NOT NULL,
	[REQUESTUSERID] [int] NOT NULL,
	[SUBMITDATE] [datetime] NULL,
	[SUBMITCOMMENT] [nvarchar](250) NOT NULL,
	[APPROVERUSERID] [int] NULL,
	[APPROVEDATE] [datetime] NULL,
	[STATUS] [int] NOT NULL,
	[STATUSDATE] [datetime] NULL,
	[APPROVECOMMENT] [nvarchar](250) NOT NULL,
	[COMPLETE] [bit] NOT NULL,
 CONSTRAINT [PK_BANKSAPPROVAL] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[BANKSAPPROVAL] ADD  CONSTRAINT [DF_BANKSAPPROVAL_SOURCEID]  DEFAULT ((-1)) FOR [SOURCEID]
ALTER TABLE [dbo].[BANKSAPPROVAL] ADD  CONSTRAINT [DF_BANKSAPPROVAL_BankAccount]  DEFAULT ('') FOR [BankAccount]
ALTER TABLE [dbo].[BANKSAPPROVAL] ADD  CONSTRAINT [DF_BANKSAPPROVAL_BankBranch]  DEFAULT ('') FOR [BankBranch]
ALTER TABLE [dbo].[BANKSAPPROVAL] ADD  CONSTRAINT [DF_BANKSAPPROVAL_BankName]  DEFAULT ('') FOR [BankName]
ALTER TABLE [dbo].[BANKSAPPROVAL] ADD  CONSTRAINT [DF_BANKSAPPROVAL_BankAddress1]  DEFAULT ('') FOR [BankAddress1]
ALTER TABLE [dbo].[BANKSAPPROVAL] ADD  CONSTRAINT [DF_BANKSAPPROVAL_BankAddress2]  DEFAULT ('') FOR [BankAddress2]
ALTER TABLE [dbo].[BANKSAPPROVAL] ADD  CONSTRAINT [DF_BANKSAPPROVAL_BankAddress3]  DEFAULT ('') FOR [BankAddress3]
ALTER TABLE [dbo].[BANKSAPPROVAL] ADD  CONSTRAINT [DF_BANKSAPPROVAL_BankPCode]  DEFAULT ('') FOR [BankPCode]
ALTER TABLE [dbo].[BANKSAPPROVAL] ADD  CONSTRAINT [DF_BANKSAPPROVAL_BankTel]  DEFAULT ('') FOR [BankTel]
ALTER TABLE [dbo].[BANKSAPPROVAL] ADD  CONSTRAINT [DF_BANKSAPPROVAL_BankFax]  DEFAULT ('') FOR [BankFax]
ALTER TABLE [dbo].[BANKSAPPROVAL] ADD  CONSTRAINT [DF_BANKSAPPROVAL_BankeMail]  DEFAULT ('') FOR [BankeMail]
ALTER TABLE [dbo].[BANKSAPPROVAL] ADD  CONSTRAINT [DF_BANKSAPPROVAL_BankContact]  DEFAULT ('') FOR [BankContact]
ALTER TABLE [dbo].[BANKSAPPROVAL] ADD  CONSTRAINT [DF_BANKSAPPROVAL_BankManager]  DEFAULT ('') FOR [BankManager]
ALTER TABLE [dbo].[BANKSAPPROVAL] ADD  CONSTRAINT [DF_BANKSAPPROVAL_BankURL]  DEFAULT ('') FOR [BankURL]
ALTER TABLE [dbo].[BANKSAPPROVAL] ADD  CONSTRAINT [DF_BANKSAPPROVAL_BankLedger]  DEFAULT ('') FOR [BankLedger]
ALTER TABLE [dbo].[BANKSAPPROVAL] ADD  CONSTRAINT [DF_BANKSAPPROVAL_BankBalance]  DEFAULT ((0)) FOR [BankBalance]
ALTER TABLE [dbo].[BANKSAPPROVAL] ADD  CONSTRAINT [DF_BANKSAPPROVAL_BankBalanceClose]  DEFAULT ((0)) FOR [BankBalanceClose]
ALTER TABLE [dbo].[BANKSAPPROVAL] ADD  CONSTRAINT [DF_BANKSAPPROVAL_BankPeriod]  DEFAULT ('') FOR [BankPeriod]
ALTER TABLE [dbo].[BANKSAPPROVAL] ADD  CONSTRAINT [DF_BANKSAPPROVAL_BankBorgID]  DEFAULT ((0)) FOR [BankBorgID]
ALTER TABLE [dbo].[BANKSAPPROVAL] ADD  CONSTRAINT [DF_BANKSAPPROVAL_SWIFT]  DEFAULT ('') FOR [SWIFT]
ALTER TABLE [dbo].[BANKSAPPROVAL] ADD  CONSTRAINT [DF_BANKSAPPROVAL_IFSC]  DEFAULT ('') FOR [IFSC]
ALTER TABLE [dbo].[BANKSAPPROVAL] ADD  CONSTRAINT [DF_BANKSAPPROVAL_CHID]  DEFAULT ((-1)) FOR [CHID]
ALTER TABLE [dbo].[BANKSAPPROVAL] ADD  CONSTRAINT [DF_BANKSAPPROVAL_BIC]  DEFAULT ('') FOR [BIC]
ALTER TABLE [dbo].[BANKSAPPROVAL] ADD  CONSTRAINT [DF_BANKSAPPROVAL_COUNTRY]  DEFAULT ('') FOR [COUNTRY]
ALTER TABLE [dbo].[BANKSAPPROVAL] ADD  CONSTRAINT [DF_BANKSAPPROVAL_ISPDCBANK]  DEFAULT (N'0') FOR [ISPDCBANK]
ALTER TABLE [dbo].[BANKSAPPROVAL] ADD  CONSTRAINT [DF_BANKSAPPROVAL_PDCCONTROL]  DEFAULT ('') FOR [PDCCONTROL]
ALTER TABLE [dbo].[BANKSAPPROVAL] ADD  CONSTRAINT [DF_BANKSAPPROVAL_REQUESTUSERID]  DEFAULT ((-1)) FOR [REQUESTUSERID]
ALTER TABLE [dbo].[BANKSAPPROVAL] ADD  CONSTRAINT [DF_BANKSAPPROVAL_SUBMITCOMMENT]  DEFAULT ('') FOR [SUBMITCOMMENT]
ALTER TABLE [dbo].[BANKSAPPROVAL] ADD  CONSTRAINT [DF_BANKSAPPROVAL_APPROVERUSERID]  DEFAULT ((-1)) FOR [APPROVERUSERID]
ALTER TABLE [dbo].[BANKSAPPROVAL] ADD  CONSTRAINT [DF_BANKSAPPROVAL_STATUS]  DEFAULT ((0)) FOR [STATUS]
ALTER TABLE [dbo].[BANKSAPPROVAL] ADD  CONSTRAINT [DF_BANKSAPPROVAL_APPROVECOMMENT]  DEFAULT ('') FOR [APPROVECOMMENT]
ALTER TABLE [dbo].[BANKSAPPROVAL] ADD  CONSTRAINT [DF_BANKSAPPROVAL_COMPLETE]  DEFAULT (N'0') FOR [COMPLETE]