/****** Object:  Table [dbo].[BANKRECONHISTORY]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[BANKRECONHISTORY](
	[HID] [int] IDENTITY(1,1) NOT NULL,
	[BANKID] [int] NOT NULL,
	[ORGID] [int] NOT NULL,
	[YEAR] [int] NOT NULL,
	[PERIOD] [int] NOT NULL,
	[BANKBALANCE] [money] NOT NULL,
	[BANKBALANCECLOSE] [money] NOT NULL,
	[SUBMITTED] [datetime] NOT NULL,
	[USERID] [int] NOT NULL,
 CONSTRAINT [PK_BANKRECONHISTORY] PRIMARY KEY CLUSTERED 
(
	[HID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[BANKRECONHISTORY] ADD  CONSTRAINT [DF_BANKRECONHISTORY_USERID]  DEFAULT ((-1)) FOR [USERID]