/****** Object:  Table [dbo].[BANKCANCHEQUES]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[BANKCANCHEQUES](
	[BankID] [int] NOT NULL,
	[DueDate] [datetime] NOT NULL,
	[credno] [char](10) NOT NULL,
	[period] [int] NOT NULL,
	[year] [int] NOT NULL,
	[posted] [bit] NOT NULL,
	[Description] [char](255) NOT NULL,
	[Amount] [money] NOT NULL,
	[Currency] [char](3) NOT NULL,
	[ExchRate] [decimal](18, 4) NOT NULL,
	[PDCID] [int] IDENTITY(1,1) NOT NULL,
	[Transref] [char](10) NOT NULL
) ON [PRIMARY]

ALTER TABLE [dbo].[BANKCANCHEQUES] ADD  CONSTRAINT [DF_BANKCANCHEQUES_DueDate]  DEFAULT (getdate()) FOR [DueDate]
ALTER TABLE [dbo].[BANKCANCHEQUES] ADD  CONSTRAINT [DF_BANKCANCHEQUES_credno]  DEFAULT ('') FOR [credno]
ALTER TABLE [dbo].[BANKCANCHEQUES] ADD  CONSTRAINT [DF_BANKCANCHEQUES_period]  DEFAULT ((1)) FOR [period]
ALTER TABLE [dbo].[BANKCANCHEQUES] ADD  CONSTRAINT [DF_BANKCANCHEQUES_year]  DEFAULT ('') FOR [year]
ALTER TABLE [dbo].[BANKCANCHEQUES] ADD  CONSTRAINT [DF_BANKCANCHEQUES_posted]  DEFAULT ((0)) FOR [posted]
ALTER TABLE [dbo].[BANKCANCHEQUES] ADD  CONSTRAINT [DF_BANKCANCHEQUES_Description]  DEFAULT ('') FOR [Description]
ALTER TABLE [dbo].[BANKCANCHEQUES] ADD  CONSTRAINT [DF_BANKCANCHEQUES_Amount]  DEFAULT ((0)) FOR [Amount]
ALTER TABLE [dbo].[BANKCANCHEQUES] ADD  CONSTRAINT [DF_BANKCANCHEQUES_Currency]  DEFAULT ('ZAR') FOR [Currency]
ALTER TABLE [dbo].[BANKCANCHEQUES] ADD  CONSTRAINT [DF_BANKCANCHEQUES_ExchRate]  DEFAULT ((1)) FOR [ExchRate]
ALTER TABLE [dbo].[BANKCANCHEQUES] ADD  CONSTRAINT [DF_BANKCANCHEQUES_Transref]  DEFAULT ('') FOR [Transref]