/****** Object:  Table [dbo].[BATCHNOTES]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[BATCHNOTES](
	[ID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[ORGID] [int] NOT NULL,
	[BATCHNO] [int] NOT NULL,
	[BATPROCESS] [char](1) NOT NULL,
	[SEQ] [int] NOT NULL,
	[USERID] [int] NOT NULL,
	[THEDATE] [datetime] NOT NULL,
	[OPENED] [bit] NOT NULL,
	[DESCRIPTION] [text] NOT NULL,
 CONSTRAINT [PK_BATCHNOTES] PRIMARY KEY CLUSTERED 
(
	[ORGID] ASC,
	[BATCHNO] ASC,
	[BATPROCESS] ASC,
	[SEQ] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

ALTER TABLE [dbo].[BATCHNOTES] ADD  CONSTRAINT [DF_BATCHNOTES_ORGID]  DEFAULT ((-1)) FOR [ORGID]
ALTER TABLE [dbo].[BATCHNOTES] ADD  CONSTRAINT [DF_BATCHNOTES_BATCHNO]  DEFAULT ((-1)) FOR [BATCHNO]
ALTER TABLE [dbo].[BATCHNOTES] ADD  CONSTRAINT [DF_BATCHNOTES_BATPROCESS]  DEFAULT ('') FOR [BATPROCESS]
ALTER TABLE [dbo].[BATCHNOTES] ADD  CONSTRAINT [DF_BATCHNOTES_SEQ]  DEFAULT ((-1)) FOR [SEQ]
ALTER TABLE [dbo].[BATCHNOTES] ADD  CONSTRAINT [DF_BATCHNOTES_USERID]  DEFAULT ((-1)) FOR [USERID]
ALTER TABLE [dbo].[BATCHNOTES] ADD  CONSTRAINT [DF_BATCHNOTES_THEDATE]  DEFAULT (getdate()) FOR [THEDATE]
ALTER TABLE [dbo].[BATCHNOTES] ADD  CONSTRAINT [DF_BATCHNOTES_OPENED]  DEFAULT ('0') FOR [OPENED]
ALTER TABLE [dbo].[BATCHNOTES] ADD  CONSTRAINT [DF_BATCHNOTES_DESCRIPTION]  DEFAULT ('') FOR [DESCRIPTION]