/****** Object:  Table [dbo].[BATCHREMIT]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[BATCHREMIT](
	[BATCHNO] [int] NOT NULL,
	[BATORGID] [int] NOT NULL,
	[BATPROCESS] [char](1) NOT NULL,
	[BATDESC] [nvarchar](50) NULL,
	[BATSTATUS] [int] NULL,
	[BATDATEOPEN] [datetime] NULL,
	[BATUPDATE] [datetime] NULL,
	[BATPERIOD] [int] NULL,
	[BATYEAR] [int] NULL,
	[BATOWNER] [nvarchar](15) NULL,
	[BATCURRENCY] [nvarchar](3) NULL,
	[BATBANK] [nvarchar](20) NULL,
	[BATCRATE] [decimal](18, 6) NULL,
	[BATBANKCURR] [nvarchar](3) NULL,
	[BATAPPROVER] [nvarchar](15) NULL,
	[LASTCHQDATE] [datetime] NULL,
	[LASTEFTDATE] [datetime] NULL,
	[LASTEFTREF] [nvarchar](10) NOT NULL,
	[LASTCHQREF] [nvarchar](10) NOT NULL,
	[LASTREMPRINTDATE] [datetime] NULL,
	[LOGUSERID] [int] NOT NULL,
	[LOGDATETIME] [datetime] NOT NULL,
	[SELECTFROMCRED] [nvarchar](10) NOT NULL,
	[SELECTTOCRED] [nvarchar](10) NOT NULL,
	[SELECTFROMCAT] [nvarchar](10) NOT NULL,
	[SELECTTOCAT] [nvarchar](10) NOT NULL,
	[SELECTFROMCONTRACT] [nvarchar](10) NOT NULL,
	[SELECTTOCONTRACT] [nvarchar](10) NOT NULL,
	[SELECTFROMSELCODE] [nvarchar](5) NOT NULL,
	[SELECTTOSELCODE] [nvarchar](5) NOT NULL,
	[IGNORESUBCBYCONTRACT] [bit] NOT NULL,
 CONSTRAINT [PK_BATCHREMIT] PRIMARY KEY CLUSTERED 
(
	[BATCHNO] ASC,
	[BATORGID] ASC,
	[BATPROCESS] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[BATCHREMIT] ADD  CONSTRAINT [DF_BATCHREMIT_BATCHNO]  DEFAULT ((-1)) FOR [BATCHNO]
ALTER TABLE [dbo].[BATCHREMIT] ADD  CONSTRAINT [DF_BATCHREMIT_BATORGID]  DEFAULT ((-1)) FOR [BATORGID]
ALTER TABLE [dbo].[BATCHREMIT] ADD  CONSTRAINT [DF_BATCHREMIT_BATPROCESS]  DEFAULT ('') FOR [BATPROCESS]
ALTER TABLE [dbo].[BATCHREMIT] ADD  CONSTRAINT [DF_BATCHREMIT_LASTEFTREF]  DEFAULT ('') FOR [LASTEFTREF]
ALTER TABLE [dbo].[BATCHREMIT] ADD  CONSTRAINT [DF_BATCHREMIT_LASTCHQREF]  DEFAULT ('') FOR [LASTCHQREF]
ALTER TABLE [dbo].[BATCHREMIT] ADD  CONSTRAINT [DF_BATCHREMIT_LOGUSERID]  DEFAULT ((-1)) FOR [LOGUSERID]
ALTER TABLE [dbo].[BATCHREMIT] ADD  CONSTRAINT [DF_BATCHREMIT_LOGDATETIME]  DEFAULT (getdate()) FOR [LOGDATETIME]
ALTER TABLE [dbo].[BATCHREMIT] ADD  CONSTRAINT [DF_BATCHREMIT_SELECTFROMCRED]  DEFAULT ('') FOR [SELECTFROMCRED]
ALTER TABLE [dbo].[BATCHREMIT] ADD  CONSTRAINT [DF_BATCHREMIT_SELECTTOCRED]  DEFAULT ('') FOR [SELECTTOCRED]
ALTER TABLE [dbo].[BATCHREMIT] ADD  CONSTRAINT [DF_BATCHREMIT_SELECTFROMCAT]  DEFAULT ('') FOR [SELECTFROMCAT]
ALTER TABLE [dbo].[BATCHREMIT] ADD  CONSTRAINT [DF_BATCHREMIT_SELECTTOCAT]  DEFAULT ('') FOR [SELECTTOCAT]
ALTER TABLE [dbo].[BATCHREMIT] ADD  CONSTRAINT [DF_BATCHREMIT_SELECTFROMCONTRACT]  DEFAULT ('') FOR [SELECTFROMCONTRACT]
ALTER TABLE [dbo].[BATCHREMIT] ADD  CONSTRAINT [DF_BATCHREMIT_SELECTTOCONTRACT]  DEFAULT ('') FOR [SELECTTOCONTRACT]
ALTER TABLE [dbo].[BATCHREMIT] ADD  CONSTRAINT [DF_BATCHREMIT_SELECTFROMSELCODE]  DEFAULT ('') FOR [SELECTFROMSELCODE]
ALTER TABLE [dbo].[BATCHREMIT] ADD  CONSTRAINT [DF_BATCHREMIT_SELECTTOSELCODE]  DEFAULT ('') FOR [SELECTTOSELCODE]
ALTER TABLE [dbo].[BATCHREMIT] ADD  CONSTRAINT [DF_BATCHREMIT_IGNORESUBCBYCONTRACT]  DEFAULT (N'0') FOR [IGNORESUBCBYCONTRACT]
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON

CREATE TRIGGER LOGBATCHREMIT ON BATCHREMIT
AFTER UPDATE, INSERT
AS 

SET NOCOUNT ON

declare @columnName nvarchar(500)
declare @keyColumn nvarchar(500)
declare @tableName nvarchar(500)
declare @sSql nvarchar(4000)
declare @primaryKey nvarchar(500)
declare @_ID nvarchar(500)
declare @logUserID int
declare @logDateTime datetime
declare @context_info int

SELECT @tableName = o.name
FROM sysobjects t
JOIN sysobjects o ON t.parent_obj = o.id
WHERE t.id = @@PROCID

set @context_info = -1
set @primaryKey = ''
set @logUserID = -1
set @logDateTime = DATEADD(M, -1, getDate()) 


/*GETS THE PRIMARY KEY COLUMNS*/
SELECT COLUMN_NAME
into #primanyKeys
FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE
WHERE OBJECTPROPERTY(OBJECT_ID(constraint_name), 'IsPrimaryKey') = 1
AND table_name = @tableName

select * into #inserted from INSERTED

set @sSql = 'DECLARE attribCursor CURSOR FOR '
set @sSql = @sSql + 'select '
DECLARE keyCursor CURSOR FOR
select COLUMN_NAME FROM #primanyKeys
OPEN keyCursor
FETCH NEXT FROM keyCursor into @keyColumn
WHILE @@FETCH_STATUS=0
BEGIN	
	if @primaryKey <> '' 
	BEGIN
		set @sSql = @sSql + ' + '' AND '' + '
	END
	set @sSql = @sSql + ''''+ @keyColumn +'='' + '''''''' + cast(rtrim(' + @keyColumn + ') as nvarchar(100)) + '''''''' '
	set @primaryKey = @keyColumn
FETCH NEXT FROM keyCursor into @keyColumn
END   
CLOSE keyCursor
DEALLOCATE keyCursor
set @sSql = @sSql + 'as _ID '
set @sSql = @sSql + 'FROM #inserted '
 
exec sp_executesql @sSql

SELECT @context_info = cast(replace(cast(CONTEXT_INFO as varchar(128)), char(0) COLLATE SQL_Latin1_General_CP1_CI_AS,'') as int) FROM master.dbo.sysprocesses WHERE spid = @@SPID

select @logUserID = isnull(USERID, -1),
@logDateTime = isnull(LOGDATETIME, DATEADD(M, -1, getDate()))
from logcontext 
where LOGID = @context_info
	
delete FROM LOGCONTEXT where LOGID = @context_info
  
OPEN attribCursor
FETCH NEXT FROM attribCursor into @_ID

WHILE @@FETCH_STATUS=0
BEGIN	 
  set @primaryKey = @_ID
  
  if DATEDIFF(s,@logDateTime, getDate()) > 5 or @logDateTime is null
	BEGIN
		set @logUserID= -1
	END

  set @sSql = 'UPDATE BATCHREMIT SET LOGUSERID = ' + cast(@logUserID as nvarchar(5)) + ', LOGDATETIME = getDate() WHERE ' + @primaryKey + ''
	
  exec sp_executesql @sSql

	FETCH NEXT FROM attribCursor into @_ID
END   

close attribCursor
DEALLOCATE attribCursor

DROP TABLE #inserted
DROP TABLE #primanyKeys

		
ALTER TABLE [dbo].[BATCHREMIT] ENABLE TRIGGER [LOGBATCHREMIT]
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
create TRIGGER [dbo].[PAYBATCHINSERT] ON [dbo].[BATCHREMIT]
AFTER INSERT
AS
BEGIN
    SET NOCOUNT ON;
	INSERT INTO PB.PAYMENTBATCHHEADER(BATCHNO,BATORGID,BATPROCESS,BATSTATUS,BATLOGINID,APPROVERLEVELID,BATBANKLEDGERCODE,BATCHDESCRIPTION)
	SELECT                            BATCHNO,BATORGID,BATPROCESS,BATSTATUS,BATOWNER  ,1,              BATBANK,          BATDESC         FROM INSERTED
 
END




ALTER TABLE [dbo].[BATCHREMIT] ENABLE TRIGGER [PAYBATCHINSERT]
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TRIGGER [dbo].[PAYBATCHUPDATE] ON [dbo].[BATCHREMIT]
AFTER UPDATE 
AS
BEGIN 
   SET NOCOUNT ON
   UPDATE PB.PAYMENTBATCHHEADER 
    SET BATSTATUS=I.BATSTATUS  
	FROM PB.PAYMENTBATCHHEADER PB
	INNER JOIN INSERTED I ON I.BATCHNO=PB.BATCHNO AND I.BATORGID = PB.BATORGID AND I.BATPROCESS = PB.BATPROCESS 
END 
ALTER TABLE [dbo].[BATCHREMIT] ENABLE TRIGGER [PAYBATCHUPDATE]