/****** Object:  Table [dbo].[BILLTOADDRESSES]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[BILLTOADDRESSES](
	[BILLTOID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[CONTACTID] [int] NOT NULL,
	[ADDRESSID] [int] NOT NULL,
	[COMMENTS] [nvarchar](500) NOT NULL,
	[HOMEBORG] [int] NOT NULL,
	[BILLTONAME] [nvarchar](50) NULL,
	[EID] [char](10) NOT NULL,
 CONSTRAINT [PK_BILLTOADDRESSES] PRIMARY KEY CLUSTERED 
(
	[BILLTOID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[BILLTOADDRESSES] ADD  CONSTRAINT [DF_BILLTOADDR_BILLTONAME]  DEFAULT ('') FOR [BILLTONAME]
ALTER TABLE [dbo].[BILLTOADDRESSES] ADD  DEFAULT ('') FOR [EID]