/****** Object:  Table [dbo].[BOQDETAIL]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[BOQDETAIL](
	[DetailId] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[HeaderId] [int] NOT NULL,
	[DBID] [int] NULL,
	[COUNTER] [int] NULL,
	[PAGE NO] [nvarchar](10) NULL,
	[ITEM NO] [nvarchar](15) NULL,
	[erfqflag] [nvarchar](15) NULL,
	[H1] [int] NOT NULL,
	[H2] [int] NOT NULL,
	[H3] [int] NOT NULL,
	[AMOUNT] [text] NULL,
	[BILL] [text] NULL,
	[DESCRIPTION] [text] NULL,
	[DOC REF] [text] NULL,
	[ISC] [text] NULL,
	[PAY REF] [text] NULL,
	[QUANTITY] [text] NULL,
	[RATE] [text] NULL,
	[SECTION] [text] NULL,
	[UNIT] [text] NULL,
 CONSTRAINT [PK_BOQDETAIL] PRIMARY KEY CLUSTERED 
(
	[DetailId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

ALTER TABLE [dbo].[BOQDETAIL] ADD  CONSTRAINT [DF_BOQDETAIL_PAGE NO]  DEFAULT ('') FOR [PAGE NO]
ALTER TABLE [dbo].[BOQDETAIL] ADD  CONSTRAINT [DF_BOQDETAIL_H1]  DEFAULT ((-1)) FOR [H1]
ALTER TABLE [dbo].[BOQDETAIL] ADD  CONSTRAINT [DF_BOQDETAIL_H2]  DEFAULT ((-1)) FOR [H2]
ALTER TABLE [dbo].[BOQDETAIL] ADD  CONSTRAINT [DF_BOQDETAIL_H3]  DEFAULT ((-1)) FOR [H3]
ALTER TABLE [dbo].[BOQDETAIL]  WITH NOCHECK ADD  CONSTRAINT [FK_BOQDETAIL_BOQHEADER] FOREIGN KEY([HeaderId])
REFERENCES [dbo].[BOQHEADER] ([HEADERID])
ALTER TABLE [dbo].[BOQDETAIL] CHECK CONSTRAINT [FK_BOQDETAIL_BOQHEADER]