/****** Object:  Table [dbo].[BORGSALTCONFIGHEADER]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[BORGSALTCONFIGHEADER](
	[HID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[DESCR] [nvarchar](250) NOT NULL,
 CONSTRAINT [PK_BORGSALTCONFIGHEADER] PRIMARY KEY CLUSTERED 
(
	[HID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[BORGSALTCONFIGHEADER] ADD  CONSTRAINT [DF_BORGSALTCONFIGHEADER_DESCR]  DEFAULT ('') FOR [DESCR]