/****** Object:  Table [dbo].[BORGSDEFAULTEMAIL]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[BORGSDEFAULTEMAIL](
	[BORGID] [int] NOT NULL,
	[SUBJECT] [nvarchar](150) NOT NULL,
	[EMAILTYPE] [nvarchar](20) NOT NULL,
	[BODY] [text] NOT NULL,
 CONSTRAINT [PK_BORGSDEFAULTEMAIL] PRIMARY KEY CLUSTERED 
(
	[BORGID] ASC,
	[EMAILTYPE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

ALTER TABLE [dbo].[BORGSDEFAULTEMAIL] ADD  CONSTRAINT [DF_BORGSDEFAULTEMAIL_SUBJECT]  DEFAULT ('') FOR [SUBJECT]
ALTER TABLE [dbo].[BORGSDEFAULTEMAIL] ADD  CONSTRAINT [DF_BORGSDEFAULTEMAIL_EMAILTYPE]  DEFAULT ('POEMAIL') FOR [EMAILTYPE]
ALTER TABLE [dbo].[BORGSDEFAULTEMAIL] ADD  CONSTRAINT [DF_BORGSDEFAULTEMAIL_BODY]  DEFAULT ('') FOR [BODY]