/****** Object:  Table [dbo].[BORGDELADDR]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[BORGDELADDR](
	[BORGID] [int] NOT NULL,
	[SHIPTOID] [int] NOT NULL,
 CONSTRAINT [PK_BORGDELADDR] PRIMARY KEY CLUSTERED 
(
	[BORGID] ASC,
	[SHIPTOID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]