/****** Object:  Table [dbo].[BORGSIC]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[BORGSIC](
	[BORGID] [int] NOT NULL,
	[LEV] [int] NOT NULL,
	[THEID] [int] NOT NULL,
	[INC] [bit] NOT NULL,
 CONSTRAINT [PK_BORGSIC] PRIMARY KEY CLUSTERED 
(
	[BORGID] ASC,
	[LEV] ASC,
	[THEID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[BORGSIC] ADD  CONSTRAINT [DF_BORGSIC_BORGID]  DEFAULT ((-1)) FOR [BORGID]
ALTER TABLE [dbo].[BORGSIC] ADD  CONSTRAINT [DF_BORGSIC_LEV]  DEFAULT ((-1)) FOR [LEV]
ALTER TABLE [dbo].[BORGSIC] ADD  CONSTRAINT [DF_BORGSIC_THEID]  DEFAULT ((-1)) FOR [THEID]
ALTER TABLE [dbo].[BORGSIC] ADD  CONSTRAINT [DF_BORGSIC_INC]  DEFAULT ('1') FOR [INC]