/****** Object:  Table [dbo].[BORGSALTCONFIGDETAIL]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[BORGSALTCONFIGDETAIL](
	[DID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[HID] [int] NOT NULL,
	[BORGID] [int] NOT NULL,
	[PARENTBORG] [int] NOT NULL,
	[CONPERC] [decimal](18, 4) NOT NULL,
 CONSTRAINT [PK_BORGSALTCONFIGDETAIL] PRIMARY KEY CLUSTERED 
(
	[DID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[BORGSALTCONFIGDETAIL] ADD  CONSTRAINT [DF_BORGSALTCONFIGDETAIL_HID]  DEFAULT ((-1)) FOR [HID]
ALTER TABLE [dbo].[BORGSALTCONFIGDETAIL] ADD  CONSTRAINT [DF_BORGSALTCONFIGDETAIL_BORGID]  DEFAULT ((-1)) FOR [BORGID]
ALTER TABLE [dbo].[BORGSALTCONFIGDETAIL] ADD  CONSTRAINT [DF_BORGSALTCONFIGDETAIL_PARENTBORG]  DEFAULT ((-1)) FOR [PARENTBORG]
ALTER TABLE [dbo].[BORGSALTCONFIGDETAIL] ADD  CONSTRAINT [DF_BORGSALTCONFIGDETAIL_CONPERC]  DEFAULT ((-1)) FOR [CONPERC]