/****** Object:  Table [dbo].[BORGS]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[BORGS](
	[BORGID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[BORGNAME] [nvarchar](75) NULL,
	[ADDRESS1] [nvarchar](50) NULL,
	[ADDRESS2] [nvarchar](50) NULL,
	[ADDRESS3] [nvarchar](50) NULL,
	[BILLTO] [int] NOT NULL,
	[SHIPTO] [int] NOT NULL,
	[PARENTBORG] [int] NOT NULL,
	[CURRENCY] [nvarchar](3) NOT NULL,
	[LOCALE] [int] NOT NULL,
	[ROLEID] [int] NOT NULL,
	[BORGNEWS] [nvarchar](2500) NULL,
	[SPENDINGLIMIT] [money] NOT NULL,
	[TOLERANCEID] [int] NOT NULL,
	[PONUMPREFIX] [nvarchar](15) NULL,
	[PONUMSUFFIX] [nvarchar](15) NULL,
	[POSEPARATEDBY] [char](1) NOT NULL,
	[POINCLCONTRACTNUM] [bit] NOT NULL,
	[REQNUMPREFIX] [nvarchar](15) NULL,
	[REQNUMSUFFIX] [nvarchar](15) NULL,
	[REQSEPARATEDBY] [char](1) NOT NULL,
	[REQINCLCONTRACTNUM] [bit] NOT NULL,
	[REQINCUSRNAMEINREQNAME] [bit] NOT NULL,
	[SPECREQUESTAPPRID] [int] NOT NULL,
	[TVAPPROVERID] [int] NOT NULL,
	[MARKETSITEID] [int] NOT NULL,
	[MPID] [nvarchar](36) NOT NULL,
	[TPSHORTNAME] [nvarchar](25) NOT NULL,
	[TPNAME] [nvarchar](50) NOT NULL,
	[BUYERUSERID] [nvarchar](25) NOT NULL,
	[BUYERPASSWORD] [nvarchar](50) NOT NULL,
	[CURRENTPERIOD] [int] NOT NULL,
	[STARTOFFINYEAR] [int] NOT NULL,
	[CURRENTYEAR] [int] NOT NULL,
	[YEARENDMONTH] [int] NOT NULL,
	[CURREXGRP] [int] NOT NULL,
	[PCODE] [nvarchar](10) NOT NULL,
	[VATREG] [nvarchar](15) NOT NULL,
	[COMPREG] [nvarchar](55) NOT NULL,
	[TELNO] [nvarchar](25) NOT NULL,
	[ADDRID] [int] NOT NULL,
	[EID] [char](10) NOT NULL,
	[FOREIGNL] [bit] NOT NULL,
	[FOREIGNS] [bit] NOT NULL,
	[FOREIGND] [bit] NOT NULL,
	[BORGJNLNO] [int] NOT NULL,
	[CASHFLOWM] [bit] NOT NULL,
	[ADVANCES] [bit] NOT NULL,
	[ENTERPRISE] [int] NOT NULL,
	[GRN] [int] NOT NULL,
	[ICGLCODE] [char](10) NULL,
	[COSTCURRENCY] [char](3) NOT NULL,
	[COSTEXCHRATE] [numeric](18, 0) NOT NULL,
	[CONSCURRENCY] [char](3) NOT NULL,
	[CONSEXCHRATE] [numeric](18, 0) NOT NULL,
	[DCSPREFIXFROM] [char](10) NOT NULL,
	[DCSPREFIXTO] [char](10) NOT NULL,
	[TAXREGNO] [nvarchar](30) NOT NULL,
	[STAMPREGNO] [nvarchar](30) NOT NULL,
	[UIFREGNO] [nvarchar](30) NOT NULL,
	[SDLREGNO] [nvarchar](30) NOT NULL,
	[RSCREGNO] [nvarchar](30) NOT NULL,
	[COSOCSECNO] [nvarchar](30) NOT NULL,
	[DEBTINVOICE] [char](35) NOT NULL,
	[CREDREM] [char](35) NOT NULL,
	[SCONREM] [char](35) NOT NULL,
	[SCONCERT] [char](35) NOT NULL,
	[DEBTCERT] [char](35) NOT NULL,
	[DEBTSTAT] [char](35) NOT NULL,
	[CREDCHEQUE] [char](35) NOT NULL,
	[SCONCHEQUE] [char](35) NOT NULL,
	[CBCHEQUE] [char](35) NOT NULL,
	[FAXNO] [nvarchar](25) NOT NULL,
	[DEFDIV] [int] NOT NULL,
	[LASTYETRANID] [numeric](18, 0) NOT NULL,
	[PORPT] [nvarchar](30) NOT NULL,
	[REQRPT] [nvarchar](30) NOT NULL,
	[USESELAPPROVER] [bit] NOT NULL,
	[CREATEPOASAP] [bit] NOT NULL,
	[LASTDEBTINV] [int] NOT NULL,
	[LASTSUBCONRECON] [int] NOT NULL,
	[LASTDEBTRECON] [int] NOT NULL,
	[LASTSUBCONCONTRA] [int] NOT NULL,
	[DEFSTORE] [char](15) NOT NULL,
	[BORGINVNO] [int] NOT NULL,
	[QUICKPOEDIT] [bit] NOT NULL,
	[ISEXCHRATE] [numeric](18, 6) NOT NULL,
	[SCONCERTGLO] [char](35) NOT NULL,
	[CREDREMGLO] [char](35) NOT NULL,
	[CONPERC] [decimal](18, 4) NOT NULL,
	[BORGICINVNO] [int] NOT NULL,
	[PlantHireRequisition] [int] NOT NULL,
	[PlantHireRequisitionPrefix] [char](5) NOT NULL,
	[PlantHireInvicePref] [char](5) NOT NULL,
	[PlnatHireinvoiceNum] [int] NOT NULL,
	[USECWCONTRACTS] [bit] NOT NULL,
	[CWINBOX] [nvarchar](155) NOT NULL,
	[CWOUTBOX] [nvarchar](155) NOT NULL,
	[CWCOMPANY] [nvarchar](55) NOT NULL,
	[CWUSER] [nvarchar](55) NOT NULL,
	[CWPASS] [nvarchar](55) NOT NULL,
	[USECWBUDGETS] [bit] NOT NULL,
	[USECWSUBCRECON] [bit] NOT NULL,
	[USECWPOS] [bit] NOT NULL,
	[PBHINVOICE] [char](35) NOT NULL,
	[RBHINVOICE] [char](35) NOT NULL,
	[IRECON] [int] NOT NULL,
	[AUTORFC] [bit] NOT NULL,
	[COMPTAXNO] [char](15) NOT NULL,
	[USERPERC] [numeric](18, 4) NOT NULL,
	[DEFBANK] [nvarchar](25) NOT NULL,
	[DEFBRANCHNAME] [nvarchar](25) NOT NULL,
	[DEFBRANCH] [nvarchar](15) NOT NULL,
	[DEFACC] [nvarchar](50) NOT NULL,
	[PlantHirePBInvoicePref] [char](5) NOT NULL,
	[PlantHirePBInvoiceNum] [int] NOT NULL,
	[DEFPHDIV] [int] NOT NULL,
	[DEFPDBANK] [int] NOT NULL,
	[JobCardCustom] [char](35) NOT NULL,
	[DebtDelNote] [char](35) NOT NULL,
	[FORCREDREM] [char](35) NOT NULL,
	[FORCREDREMGLO] [char](35) NOT NULL,
	[PORPTFILENAME] [nvarchar](35) NOT NULL,
	[COVERPAGE] [nvarchar](50) NOT NULL,
	[POSUBCCORPT] [nvarchar](30) NOT NULL,
	[POSUBCRPT] [nvarchar](30) NOT NULL,
	[REQREQUIREDBY] [int] NOT NULL,
	[SVN] [int] NOT NULL,
	[EXTPOC] [int] NOT NULL,
	[SUBCBYCONTRACT] [bit] NOT NULL,
	[USEVATGROUPS] [bit] NOT NULL,
	[SDVATTYPE] [nvarchar](100) NOT NULL,
	[USEWHT] [bit] NOT NULL,
	[JobCardBudgetCustom] [char](35) NOT NULL,
	[SWIFT] [nvarchar](12) NOT NULL,
	[TAXRATEFB] [numeric](18, 4) NOT NULL,
	[SYSCOMPLETE] [bit] NOT NULL,
	[APPROVNOTES] [bit] NOT NULL,
	[IFSC] [nvarchar](11) NOT NULL,
	[CUSTOMS] [nvarchar](15) NOT NULL,
	[EXCISE] [nvarchar](15) NOT NULL,
	[SERVICETAX] [nvarchar](15) NOT NULL,
	[PAN] [nvarchar](15) NOT NULL,
	[ISOCERTIFICATION] [nvarchar](15) NOT NULL,
	[SENDAPPROVALEMAIL] [bit] NOT NULL,
	[LASTREQNUMBER] [int] NULL,
	[LASTORDNUMBER] [int] NULL,
	[USEINDEPENDENTREQNO] [bit] NOT NULL,
	[USEINDEPENDENTORDNO] [bit] NOT NULL,
	[USEBULKORDERS] [bit] NOT NULL,
	[PltHireRetDocNum] [int] NOT NULL,
	[USEDATEAGING] [bit] NOT NULL,
	[FIRMNUMBER] [nvarchar](15) NOT NULL,
	[LOADTRANSARRAYS] [bit] NOT NULL,
	[TRDCLASSIFICATION] [nvarchar](4) NOT NULL,
	[ADDRUNITNUM] [nvarchar](5) NOT NULL,
	[ADDRCOMPLEX] [nvarchar](25) NOT NULL,
	[ADDRSTREETNUM] [nvarchar](5) NOT NULL,
	[ADDRSTREET] [nvarchar](25) NOT NULL,
	[ADDRSUBURB] [nvarchar](34) NOT NULL,
	[ADDRCITY] [nvarchar](24) NOT NULL,
	[ADDRPOSTALCODE] [nvarchar](8) NOT NULL,
	[USEWHTPAY] [bit] NOT NULL,
	[VATSTR] [nvarchar](3) NULL,
	[LOCKSTOCK] [bit] NOT NULL,
	[ICCREDNO] [nvarchar](10) NOT NULL,
	[ICPLANTJNL] [bit] NOT NULL,
	[USECREMITBATCH] [bit] NOT NULL,
	[USESREMITBATCH] [bit] NOT NULL,
	[PERIOD] [int] NOT NULL,
	[SINGLECONTRACT] [bit] NOT NULL,
	[USECONTRACTGROUPS] [bit] NOT NULL,
	[SUBCONTRAVAT] [nvarchar](100) NOT NULL,
	[GRNDISABLED] [bit] NOT NULL,
	[IDLETIMEOUT] [int] NOT NULL,
	[USELEDGERCODEGROUPS] [bit] NOT NULL,
	[USEWORKFLOW] [bit] NOT NULL,
	[YARDTFRNOTENO] [nvarchar](15) NOT NULL,
	[YARDINVOICENO] [nvarchar](10) NOT NULL,
	[TFRAUTO] [bit] NOT NULL,
	[USEBEE] [bit] NOT NULL,
	[DOPARKPOST] [bit] NOT NULL,
	[DOPARKPOSTPERBANK] [bit] NOT NULL,
	[YARDSTKINCRETDATE] [bit] NOT NULL,
	[AUTOSUPPTOCRED] [bit] NOT NULL,
	[RPTLETTER] [bit] NOT NULL,
	[VTWREQUIRESDATE] [bit] NOT NULL,
	[VTWNOPOSTINVALIDDATE] [bit] NOT NULL,
	[USERCM] [bit] NOT NULL,
	[ENABLEBEE] [bit] NOT NULL,
	[POSTSRECONWDEXCEEDSCONTRVAL] [bit] NOT NULL,
	[HMRCUTR] [nvarchar](10) NOT NULL,
	[HMRCAOREF] [nvarchar](13) NOT NULL,
	[USEVATCONTROLPERVATTYPE] [bit] NOT NULL,
	[TAXGROUPCODE] [nvarchar](15) NOT NULL,
	[AUTOINCREMENTINVNUMBER] [bit] NOT NULL,
	[CHECKDUPLLICATEVATREG] [bit] NOT NULL,
	[CURRENCYALT] [nvarchar](3) NULL,
	[JOBCARDINVOICENUMBER] [int] NOT NULL,
	[JOBCARDINVOICEPREFIX] [nvarchar](5) NOT NULL,
	[TAXYEARENDMONTH] [int] NULL,
	[LOCKEXCHRATEBANKTRANSFERMULTI] [bit] NOT NULL,
	[THOUSANDSEPERATOR] [char](1) NOT NULL,
	[LOCKGLONCANDYITEM] [bit] NOT NULL,
	[GRNFOREX] [bit] NOT NULL,
	[ADDSUPPLIERPARTNOTODESC] [bit] NOT NULL,
	[LOCKCATALOGUEPRICEDISCOUNT] [bit] NOT NULL,
	[LOCKCATALOGUESUPPLIER] [bit] NOT NULL,
	[POAUTOEMAIL] [bit] NOT NULL,
	[USEWHTLINEBEFOREVAT] [bit] NOT NULL,
	[USEWHTLINEAFTERVAT] [bit] NOT NULL,
	[LASTSITEREQNUMBER] [int] NULL,
	[SITEREQNUMPREFIX] [nvarchar](15) NULL,
	[SITEREQNUMSUFFIX] [nvarchar](15) NULL,
	[SITEREQSEPARATEDBY] [char](1) NOT NULL,
	[USEINDEPENDENTSITEREQNO] [bit] NOT NULL,
	[ADDSTOCKITEMSWITHZERORATE] [bit] NOT NULL,
	[USERCTI] [bit] NOT NULL,
	[BORGRCTINO] [int] NOT NULL,
	[USELEDGERCODEGROUPSACC] [bit] NOT NULL,
	[BLOCKMONTHENDSUBCRECON] [bit] NOT NULL,
	[BLOCKMONTHENDDEBTORRECON] [bit] NOT NULL,
	[USECREDITORSSOP] [bit] NOT NULL,
	[IGNORESTKSELLRATE] [bit] NOT NULL,
	[ALLOWRECONCHANGEAPPROVAL] [bit] NOT NULL,
	[IGNOREACCSPECRECON] [bit] NOT NULL,
	[CLASSIFICATIONCODESUSE] [bit] NOT NULL,
	[CLASSIFICATIONCODESDESCR] [nvarchar](20) NOT NULL,
	[POSTSRECONWDEXCEEDSBUDGET] [bit] NOT NULL,
	[INVOICERECONEXCEEDQTY] [bit] NOT NULL,
	[STKTRANSFERNO] [nvarchar](10) NOT NULL,
	[JNLFORCEAPPROVAL] [int] NOT NULL,
	[USEBANKAPPROVALS] [bit] NOT NULL,
	[INVBULKTRANSREF] [nvarchar](10) NOT NULL,
	[INVBULKTRANSREFUSE] [bit] NOT NULL,
 CONSTRAINT [PK_BORGS_1] PRIMARY KEY CLUSTERED 
(
	[BORGID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_BILLTO_1]  DEFAULT ((-1)) FOR [BILLTO]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_SHIPTO_1]  DEFAULT ((-1)) FOR [SHIPTO]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_CURRENCY]  DEFAULT ('ZAR') FOR [CURRENCY]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_LOCALE]  DEFAULT ((-1)) FOR [LOCALE]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_ROLEID]  DEFAULT ((-1)) FOR [ROLEID]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_SPENDINGLIMIT_1]  DEFAULT (0) FOR [SPENDINGLIMIT]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_TOLERANCEID_1]  DEFAULT ((-1)) FOR [TOLERANCEID]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_PONUMPREFIX]  DEFAULT (' ') FOR [PONUMPREFIX]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_PONUMSUFFIX]  DEFAULT ('') FOR [PONUMSUFFIX]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_POSEPARATEDBY_1]  DEFAULT ('.') FOR [POSEPARATEDBY]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_POINCLCONTRACTNUM_1]  DEFAULT (0) FOR [POINCLCONTRACTNUM]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_REQNUMPREFIX]  DEFAULT ('') FOR [REQNUMPREFIX]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_REQNUMSUFFIX]  DEFAULT ('') FOR [REQNUMSUFFIX]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_REQSEPARATEDBY_1]  DEFAULT ('.') FOR [REQSEPARATEDBY]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_REQINCLCONTRACTNUM_1]  DEFAULT (0) FOR [REQINCLCONTRACTNUM]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_REQINCUSRNAMEINREQNAME_1]  DEFAULT (0) FOR [REQINCUSRNAMEINREQNAME]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_SPECREQUESTAPPRID]  DEFAULT ((-1)) FOR [SPECREQUESTAPPRID]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_TVAPPROVERID]  DEFAULT ((-1)) FOR [TVAPPROVERID]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_MARKETSITEID]  DEFAULT ((-1)) FOR [MARKETSITEID]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_MPID]  DEFAULT ('') FOR [MPID]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_TPSHORTNAME]  DEFAULT ('') FOR [TPSHORTNAME]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_TPNAME]  DEFAULT ('') FOR [TPNAME]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_BUYERUSERID]  DEFAULT ('') FOR [BUYERUSERID]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_BUYERPASSWORD]  DEFAULT ('') FOR [BUYERPASSWORD]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_CURRENTPERIOD]  DEFAULT (3) FOR [CURRENTPERIOD]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_STARTOFFINYEAR]  DEFAULT (3) FOR [STARTOFFINYEAR]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_CURRENTYEAR]  DEFAULT (2002) FOR [CURRENTYEAR]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_YEARENDMONTH]  DEFAULT (2) FOR [YEARENDMONTH]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_CURREXGRP]  DEFAULT ((-1)) FOR [CURREXGRP]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_PCODE]  DEFAULT ('') FOR [PCODE]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_VATREG]  DEFAULT ('') FOR [VATREG]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_COMPREG]  DEFAULT ('') FOR [COMPREG]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_TELNO]  DEFAULT ('') FOR [TELNO]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_ADDRID]  DEFAULT ((-1)) FOR [ADDRID]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_EID]  DEFAULT ('') FOR [EID]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_FOREIGNL]  DEFAULT (0) FOR [FOREIGNL]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_FOREIGNS]  DEFAULT (0) FOR [FOREIGNS]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_FOREIGND]  DEFAULT (0) FOR [FOREIGND]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_BORGJNLNO]  DEFAULT (1) FOR [BORGJNLNO]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_CASHFLOWM]  DEFAULT (0) FOR [CASHFLOWM]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_ADVANCES]  DEFAULT (0) FOR [ADVANCES]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_ENTERPRISE]  DEFAULT (0) FOR [ENTERPRISE]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_GRN]  DEFAULT (0) FOR [GRN]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_COSTCURRENCY]  DEFAULT ('ZAR') FOR [COSTCURRENCY]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_COSTEXCHRATE]  DEFAULT (1) FOR [COSTEXCHRATE]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_CONSCURRENCY]  DEFAULT ('ZAR') FOR [CONSCURRENCY]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_CONSEXCHRATE]  DEFAULT (1) FOR [CONSEXCHRATE]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_DCSPREFIXFROM]  DEFAULT ('          ') FOR [DCSPREFIXFROM]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_DCSPREFIXTO]  DEFAULT ('zzzzzzzzzz') FOR [DCSPREFIXTO]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_TAXREGNO]  DEFAULT ('') FOR [TAXREGNO]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_STAMPREGNO]  DEFAULT ('') FOR [STAMPREGNO]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_UIFREGNO]  DEFAULT ('') FOR [UIFREGNO]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_SDLREGNO]  DEFAULT ('') FOR [SDLREGNO]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_RSCREGNO]  DEFAULT ('') FOR [RSCREGNO]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_COSOCSECNO]  DEFAULT ('') FOR [COSOCSECNO]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF__BORGS__DEBTINVOI__6326380C]  DEFAULT ('') FOR [DEBTINVOICE]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF__BORGS__CREDREM__641A5C45]  DEFAULT ('') FOR [CREDREM]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF__BORGS__SCONREM__650E807E]  DEFAULT ('') FOR [SCONREM]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF__BORGS__SCONCERT__6602A4B7]  DEFAULT ('') FOR [SCONCERT]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF__BORGS__DEBTCERT__66F6C8F0]  DEFAULT ('') FOR [DEBTCERT]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF__BORGS__DEBTSTAT__67EAED29]  DEFAULT ('') FOR [DEBTSTAT]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF__BORGS__CREDCHEQU__68DF1162]  DEFAULT ('') FOR [CREDCHEQUE]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF__BORGS__SCONCHEQU__69D3359B]  DEFAULT ('') FOR [SCONCHEQUE]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF__BORGS__CBCHEQUE__6AC759D4]  DEFAULT ('') FOR [CBCHEQUE]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF__BORGS__FAXNO__6BBB7E0D]  DEFAULT ('') FOR [FAXNO]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF__BORGS__DEFDIV__6CAFA246]  DEFAULT (1) FOR [DEFDIV]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF__BORGS__LASTYETRA__6DA3C67F]  DEFAULT (0) FOR [LASTYETRANID]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF__BORGS__PORPT__4D37C244]  DEFAULT ('') FOR [PORPT]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF__BORGS__REQRPT__4E2BE67D]  DEFAULT ('') FOR [REQRPT]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF__BORGS__USESELAPP__4F200AB6]  DEFAULT (0) FOR [USESELAPPROVER]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF__BORGS__CREATEPOA__51FC7761]  DEFAULT (0) FOR [CREATEPOASAP]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF__BORGS__LASTDEBTI__19831414]  DEFAULT (0) FOR [LASTDEBTINV]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF__BORGS__LASTSUBCO__1A77384D]  DEFAULT (0) FOR [LASTSUBCONRECON]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF__BORGS__LASTDEBTR__1B6B5C86]  DEFAULT (0) FOR [LASTDEBTRECON]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF__BORGS__LASTSUBCO__1C5F80BF]  DEFAULT (0) FOR [LASTSUBCONCONTRA]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF__BORGS__DEFSTORE__1D53A4F8]  DEFAULT ('') FOR [DEFSTORE]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF__BORGS__BORGINVNO__22D77424]  DEFAULT (0) FOR [BORGINVNO]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF__BORGS__QUICKPOED__3F73B2D2]  DEFAULT (0) FOR [QUICKPOEDIT]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF__BORGS__ISEXCHRAT__48FD1D0C]  DEFAULT (1) FOR [ISEXCHRATE]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF__BORGS__SCONCERTG__0DA74D14]  DEFAULT ('') FOR [SCONCERTGLO]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF__BORGS__CREDREMGL__0E9B714D]  DEFAULT ('') FOR [CREDREMGLO]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF__BORGS__CONPERC__70D6043C]  DEFAULT (0) FOR [CONPERC]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF__BORGS__BORGICINV__02BFAA4D]  DEFAULT (0) FOR [BORGICINVNO]
ALTER TABLE [dbo].[BORGS] ADD  DEFAULT (0) FOR [PlantHireRequisition]
ALTER TABLE [dbo].[BORGS] ADD  DEFAULT ('PHR') FOR [PlantHireRequisitionPrefix]
ALTER TABLE [dbo].[BORGS] ADD  DEFAULT ('PHI') FOR [PlantHireInvicePref]
ALTER TABLE [dbo].[BORGS] ADD  DEFAULT (0) FOR [PlnatHireinvoiceNum]
ALTER TABLE [dbo].[BORGS] ADD  DEFAULT ('0') FOR [USECWCONTRACTS]
ALTER TABLE [dbo].[BORGS] ADD  DEFAULT ('') FOR [CWINBOX]
ALTER TABLE [dbo].[BORGS] ADD  DEFAULT ('') FOR [CWOUTBOX]
ALTER TABLE [dbo].[BORGS] ADD  DEFAULT ('') FOR [CWCOMPANY]
ALTER TABLE [dbo].[BORGS] ADD  DEFAULT ('') FOR [CWUSER]
ALTER TABLE [dbo].[BORGS] ADD  DEFAULT ('') FOR [CWPASS]
ALTER TABLE [dbo].[BORGS] ADD  DEFAULT ('0') FOR [USECWBUDGETS]
ALTER TABLE [dbo].[BORGS] ADD  DEFAULT ('0') FOR [USECWSUBCRECON]
ALTER TABLE [dbo].[BORGS] ADD  DEFAULT ('0') FOR [USECWPOS]
ALTER TABLE [dbo].[BORGS] ADD  DEFAULT ('') FOR [PBHINVOICE]
ALTER TABLE [dbo].[BORGS] ADD  DEFAULT ('') FOR [RBHINVOICE]
ALTER TABLE [dbo].[BORGS] ADD  DEFAULT (0) FOR [IRECON]
ALTER TABLE [dbo].[BORGS] ADD  DEFAULT (0) FOR [AUTORFC]
ALTER TABLE [dbo].[BORGS] ADD  DEFAULT ('') FOR [COMPTAXNO]
ALTER TABLE [dbo].[BORGS] ADD  DEFAULT (0) FOR [USERPERC]
ALTER TABLE [dbo].[BORGS] ADD  DEFAULT ('') FOR [DEFBANK]
ALTER TABLE [dbo].[BORGS] ADD  DEFAULT ('') FOR [DEFBRANCHNAME]
ALTER TABLE [dbo].[BORGS] ADD  DEFAULT ('') FOR [DEFBRANCH]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_DEFACC]  DEFAULT ('') FOR [DEFACC]
ALTER TABLE [dbo].[BORGS] ADD  DEFAULT ('') FOR [PlantHirePBInvoicePref]
ALTER TABLE [dbo].[BORGS] ADD  DEFAULT ((0)) FOR [PlantHirePBInvoiceNum]
ALTER TABLE [dbo].[BORGS] ADD  DEFAULT ((-1)) FOR [DEFPHDIV]
ALTER TABLE [dbo].[BORGS] ADD  DEFAULT ((0)) FOR [DEFPDBANK]
ALTER TABLE [dbo].[BORGS] ADD  DEFAULT ('') FOR [JobCardCustom]
ALTER TABLE [dbo].[BORGS] ADD  DEFAULT ('') FOR [DebtDelNote]
ALTER TABLE [dbo].[BORGS] ADD  DEFAULT ('') FOR [FORCREDREM]
ALTER TABLE [dbo].[BORGS] ADD  DEFAULT ('') FOR [FORCREDREMGLO]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_PORPTFILENAME]  DEFAULT ('po.rpt') FOR [PORPTFILENAME]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_COVERPAGE]  DEFAULT ('erfq_CoverPage.asp') FOR [COVERPAGE]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_POSUBCCORPT]  DEFAULT ('') FOR [POSUBCCORPT]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_POSUBCRPT]  DEFAULT ('') FOR [POSUBCRPT]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_REQREQUIREDBY]  DEFAULT ((5)) FOR [REQREQUIREDBY]
ALTER TABLE [dbo].[BORGS] ADD  DEFAULT ((0)) FOR [SVN]
ALTER TABLE [dbo].[BORGS] ADD  DEFAULT ((0)) FOR [EXTPOC]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_SUBCBYCONTRACT]  DEFAULT ((0)) FOR [SUBCBYCONTRACT]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_USEVATGROUPS]  DEFAULT ((0)) FOR [USEVATGROUPS]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_SDVATTYPE]  DEFAULT ('I') FOR [SDVATTYPE]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_USEWHT]  DEFAULT ((0)) FOR [USEWHT]
ALTER TABLE [dbo].[BORGS] ADD  DEFAULT ('') FOR [JobCardBudgetCustom]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_SWIFT]  DEFAULT ('') FOR [SWIFT]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_TAXRATEFB]  DEFAULT ((0)) FOR [TAXRATEFB]
ALTER TABLE [dbo].[BORGS] ADD  DEFAULT ((0)) FOR [SYSCOMPLETE]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_APPROVNOTES]  DEFAULT ((0)) FOR [APPROVNOTES]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_IFSC]  DEFAULT ('') FOR [IFSC]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_CUSTOMS]  DEFAULT ('') FOR [CUSTOMS]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_EXCISE]  DEFAULT ('') FOR [EXCISE]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_SERVICETAX]  DEFAULT ('') FOR [SERVICETAX]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_PAN]  DEFAULT ('') FOR [PAN]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_ISOCERTIFICATION]  DEFAULT ('') FOR [ISOCERTIFICATION]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORG_SENDAPPROVALEMAIL]  DEFAULT ((0)) FOR [SENDAPPROVALEMAIL]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_USEINDEPENDENTREQNO]  DEFAULT ((0)) FOR [USEINDEPENDENTREQNO]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_USEINDEPENDENTORDNO]  DEFAULT ((0)) FOR [USEINDEPENDENTORDNO]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_USEBULKORDERS]  DEFAULT ((0)) FOR [USEBULKORDERS]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_PlnatHireRetDocNum]  DEFAULT ((0)) FOR [PltHireRetDocNum]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_USEDATEAGING]  DEFAULT ((0)) FOR [USEDATEAGING]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_FIRMNUMBER]  DEFAULT ('') FOR [FIRMNUMBER]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_LOADTRANSARRAYS]  DEFAULT ('1') FOR [LOADTRANSARRAYS]
ALTER TABLE [dbo].[BORGS] ADD  DEFAULT ('') FOR [TRDCLASSIFICATION]
ALTER TABLE [dbo].[BORGS] ADD  DEFAULT ('') FOR [ADDRUNITNUM]
ALTER TABLE [dbo].[BORGS] ADD  DEFAULT ('') FOR [ADDRCOMPLEX]
ALTER TABLE [dbo].[BORGS] ADD  DEFAULT ('') FOR [ADDRSTREETNUM]
ALTER TABLE [dbo].[BORGS] ADD  DEFAULT ('') FOR [ADDRSTREET]
ALTER TABLE [dbo].[BORGS] ADD  DEFAULT ('') FOR [ADDRSUBURB]
ALTER TABLE [dbo].[BORGS] ADD  DEFAULT ('') FOR [ADDRCITY]
ALTER TABLE [dbo].[BORGS] ADD  DEFAULT ('') FOR [ADDRPOSTALCODE]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_USEWHTPAY]  DEFAULT ('0') FOR [USEWHTPAY]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_LOCKSTOCK]  DEFAULT ('0') FOR [LOCKSTOCK]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_ICCREDNO]  DEFAULT ('') FOR [ICCREDNO]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_ICPLANTJNL]  DEFAULT ('1') FOR [ICPLANTJNL]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_USECREMITBATCH]  DEFAULT ('0') FOR [USECREMITBATCH]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_USESREMITBATCH]  DEFAULT ('0') FOR [USESREMITBATCH]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_PERIOD]  DEFAULT ((-1)) FOR [PERIOD]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_SINGLECONTRACT]  DEFAULT ('0') FOR [SINGLECONTRACT]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_USECONTRACTGROUPS]  DEFAULT ('0') FOR [USECONTRACTGROUPS]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_SUBCONTRAVAT]  DEFAULT ('Z') FOR [SUBCONTRAVAT]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_GRNDISABLED]  DEFAULT ('0') FOR [GRNDISABLED]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_IDLETIMEOUT]  DEFAULT ((-1)) FOR [IDLETIMEOUT]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_USELEDGERCODEGROUPS]  DEFAULT (N'0') FOR [USELEDGERCODEGROUPS]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_USEWORKFLOW]  DEFAULT (N'0') FOR [USEWORKFLOW]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_YARDTFRNOTENO]  DEFAULT ('') FOR [YARDTFRNOTENO]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_YARDINVOICENO]  DEFAULT ('') FOR [YARDINVOICENO]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_TFRAUTO]  DEFAULT (N'0') FOR [TFRAUTO]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_USEBEE]  DEFAULT ('0') FOR [USEBEE]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_DOPARKPOST]  DEFAULT (N'0') FOR [DOPARKPOST]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_DOPARKPOSTPERBANK]  DEFAULT (N'0') FOR [DOPARKPOSTPERBANK]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_YARDSTKINCRETDATE]  DEFAULT (N'0') FOR [YARDSTKINCRETDATE]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_AUTOSUPPTOCRED]  DEFAULT (N'0') FOR [AUTOSUPPTOCRED]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_RPTLETTER]  DEFAULT (N'0') FOR [RPTLETTER]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_VTWREQUIRESDATE]  DEFAULT (N'0') FOR [VTWREQUIRESDATE]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_VTWNOPOSTINVALIDDATE]  DEFAULT (N'0') FOR [VTWNOPOSTINVALIDDATE]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_USERCM]  DEFAULT (N'0') FOR [USERCM]
ALTER TABLE [dbo].[BORGS] ADD  DEFAULT ((0)) FOR [ENABLEBEE]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_POSTSRECONWDEXCEEDSCONTRVAL]  DEFAULT (N'0') FOR [POSTSRECONWDEXCEEDSCONTRVAL]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_HMRCUTR]  DEFAULT ('') FOR [HMRCUTR]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_HMRCAOREF]  DEFAULT ('') FOR [HMRCAOREF]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_USEVATCONTROLPERVATTYPE]  DEFAULT (N'0') FOR [USEVATCONTROLPERVATTYPE]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_TAXGROUPCODE]  DEFAULT ('') FOR [TAXGROUPCODE]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_AUTOINCREMENTINVNUMBER]  DEFAULT (N'0') FOR [AUTOINCREMENTINVNUMBER]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_CHECKDUPLLICATEVATREG]  DEFAULT (N'0') FOR [CHECKDUPLLICATEVATREG]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_JOBCARDINVOICENUMBER]  DEFAULT ((0)) FOR [JOBCARDINVOICENUMBER]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_JOBCARDINVOICEPREFIX]  DEFAULT ('') FOR [JOBCARDINVOICEPREFIX]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_LOCKEXCHRATEBANKTRANSFERMULTI]  DEFAULT ('0') FOR [LOCKEXCHRATEBANKTRANSFERMULTI]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_THOUSANDSEPERATOR]  DEFAULT (',') FOR [THOUSANDSEPERATOR]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_LOCKGLONCANDYITEM]  DEFAULT ('0') FOR [LOCKGLONCANDYITEM]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_GRNFOREX]  DEFAULT ('0') FOR [GRNFOREX]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_ADDSUPPLIERPARTNOTODESC]  DEFAULT ('0') FOR [ADDSUPPLIERPARTNOTODESC]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_LOCKCATALOGUEPRICEDISCOUNT]  DEFAULT ('0') FOR [LOCKCATALOGUEPRICEDISCOUNT]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_LOCKCATALOGUESUPPLIER]  DEFAULT ('0') FOR [LOCKCATALOGUESUPPLIER]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_POAUTOEMAIL]  DEFAULT ('0') FOR [POAUTOEMAIL]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_USEWHTLINEBEFOREVAT]  DEFAULT ('0') FOR [USEWHTLINEBEFOREVAT]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_USEWHTLINEAFTERVAT]  DEFAULT ('0') FOR [USEWHTLINEAFTERVAT]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_SITEREQNUMPREFIX]  DEFAULT ('') FOR [SITEREQNUMPREFIX]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_SITEREQNUMSUFFIX]  DEFAULT ('') FOR [SITEREQNUMSUFFIX]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_SITEREQSEPARATEDBY]  DEFAULT ('.') FOR [SITEREQSEPARATEDBY]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_USEINDEPENDENTSITEREQNO]  DEFAULT ('0') FOR [USEINDEPENDENTSITEREQNO]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_ADDSTOCKITEMSWITHZERORATE]  DEFAULT ('0') FOR [ADDSTOCKITEMSWITHZERORATE]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_USERCTI]  DEFAULT (N'0') FOR [USERCTI]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_BORGRCTINO]  DEFAULT ((0)) FOR [BORGRCTINO]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_USELEDGERCODEGROUPSACC]  DEFAULT (N'0') FOR [USELEDGERCODEGROUPSACC]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_BLOCKMONTHENDSUBCRECON]  DEFAULT (N'0') FOR [BLOCKMONTHENDSUBCRECON]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_BLOCKMONTHENDDEBTORRECON]  DEFAULT (N'0') FOR [BLOCKMONTHENDDEBTORRECON]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_USECREDITORSSOP]  DEFAULT (N'0') FOR [USECREDITORSSOP]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_IGNORESTKSELLRATE]  DEFAULT (N'0') FOR [IGNORESTKSELLRATE]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_ALLOWRECONCHANGEAPPROVAL]  DEFAULT (N'0') FOR [ALLOWRECONCHANGEAPPROVAL]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_IGNOREACCSPECRECON]  DEFAULT (N'0') FOR [IGNOREACCSPECRECON]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_CLASSIFICATIONCODESUSE]  DEFAULT (N'0') FOR [CLASSIFICATIONCODESUSE]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_CLASSIFICATIONCODESDESCR]  DEFAULT ('') FOR [CLASSIFICATIONCODESDESCR]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_POSTSRECONWDEXCEEDSBUDGET]  DEFAULT (N'1') FOR [POSTSRECONWDEXCEEDSBUDGET]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_INVOICERECONEXCEEDQTY]  DEFAULT (N'0') FOR [INVOICERECONEXCEEDQTY]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_STKTRANSFERNO]  DEFAULT ('XFER000000') FOR [STKTRANSFERNO]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_JNLFORCEAPPROVAL]  DEFAULT ((0)) FOR [JNLFORCEAPPROVAL]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_USEBANKAPPROVALS]  DEFAULT (N'0') FOR [USEBANKAPPROVALS]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_INVBULKTRANSREF]  DEFAULT ('') FOR [INVBULKTRANSREF]
ALTER TABLE [dbo].[BORGS] ADD  CONSTRAINT [DF_BORGS_INVBULKTRANSREFUSE]  DEFAULT (N'0') FOR [INVBULKTRANSREFUSE]
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON

CREATE TRIGGER LOGMASTERBORGS ON BORGS
AFTER UPDATE, DELETE, INSERT
AS 

SET NOCOUNT ON

declare @tableName varChar(25)
declare @primaryKey varChar(25)
declare @ignoreList varChar(500)

set @tableName = 'BORGS'
set @primaryKey = 'BORGID'
set @ignoreList = ''

declare @action varChar(25)
declare @logUserID int
declare @logDateTime datetime
declare @borgid int
declare @page varChar(100)
declare @info varChar(250)
declare @application varChar(3)
declare @version varChar(15)
declare @context_info int
declare @sqlTblCols nVarChar(max)
declare @sql nVarChar(max)

set @context_info = -1
set @ignoreList = ',' + replace(@ignoreList, ' ', '') + ','
set @action = ''
set @logUserID = -1
set @logDateTime = DATEADD(M, -1, getDate()) 
set @borgid = -1
set @page = ''
set @info = ''
set @application = ''
set @version = ''
set @sqlTblCols = ''
set @sql = ''

if exists(select * from INSERTED)
BEGIN
	if exists(select * from DELETED)
	BEGIN
		set @action = 'UPDATE'
	END
	ELSE
	BEGIN
		set @action = 'INSERT'
	END
END
ELSE
BEGIN
	if exists(select * from DELETED)
	BEGIN
		set @action = 'DELETE'
	END
END
 
select * into #inserted from INSERTED
select * into #deleted from DELETED

SELECT @context_info = cast(replace(cast(CONTEXT_INFO as varchar(128)), char(0) COLLATE SQL_Latin1_General_CP1_CI_AS,'') as int) FROM master.dbo.sysprocesses WHERE spid = @@SPID

select @logUserID = isnull(USERID, -1),
@logDateTime = isnull(LOGDATETIME, DATEADD(M, -1, getDate())),
@borgid = isnull(BORGID, @borgid),
@page = isnull(PAGE, @page),
@info = isnull(INFO, @info),
@application  = isnull(APPLICATION, @application),
@version = isnull(VERSION, @version)
from logcontext 
where LOGID = @context_info
	
delete FROM LOGCONTEXT where LOGID = @context_info
   
if @action = 'UPDATE'
BEGIN		
	Select @sqlTblCols = @sqlTblCols + 'Case when rtrim(cast(IsNull(i.[' + Column_Name + '],0) as varChar(100)))=rtrim(cast(IsNull(d.[' + Column_Name + '],0) as varChar(100))) then '''' else ' + '''[' + Column_Name + ']:'' + rtrim(cast(IsNull(d.[' + Column_Name + '],0) as varChar(100)) collate SQL_LATIN1_GENERAL_CP1_CI_AS) + ''' + ' -> '' + rtrim(cast(IsNull(i.[' + Column_Name + '],0) as varChar(100)) collate SQL_LATIN1_GENERAL_CP1_CI_AS) + ''' + ''' + '', ''' + ' end +'
	from information_schema.columns 
	where TABLE_NAME = @tableName
	and PATINDEX('%,' + COLUMN_NAME + ',%', @ignoreList) = 0
	and DATA_TYPE not like '%text%'
	and DATA_TYPE not like '%image%'
	and DATA_TYPE not like '%binary%' 
		
	set @sqlTblCols = Substring(@sqlTblCols, 1 , len(@sqlTblCols) - 1)

	set @sql = 'select ''' + cast(@logUserID as varChar(10)) + ''', ''' + cast(@borgid as varChar(10)) + ''', ''' + @application + ''', ''' + @tableName + ''', ''' + @action + ''', ''' + @page + ''', ''' + @info + ''', ''' + @version + ''', '''+ @primaryKey +' = '' + cast(i.'+ @primaryKey +' as varChar(10)), Substring(' + @sqlTblCols + ', 1 , len(' + @sqlTblCols + ') - 1) '
	set @sql = @sql + 'From #inserted i inner join #deleted d on i.'+ @primaryKey +' = d.'+ @primaryKey +' where isnull(' + @sqlTblCols + ', '''') <> '''' ' 

	insert into LOGMASTER (USERID, BORGID, APPLICATION, TABLENAME, ACTION, PAGE, INFO, VERSION, PRIMARYKEY, DETAILS)
	exec sp_executesql @sql
END   

if @action = 'DELETE' or @action = 'INSERT'
BEGIN
	Select @sqlTblCols = @sqlTblCols + '''[' + Column_Name + ']:'' + rtrim(cast(IsNull(d.[' + Column_Name + '],0) as varChar(100)) collate SQL_LATIN1_GENERAL_CP1_CI_AS) + '', '' + '
	from information_schema.columns 
	where TABLE_NAME = @tableName
	and PATINDEX('%,' + COLUMN_NAME + ',%', @ignoreList) = 0
	and DATA_TYPE not like '%text%'
	and DATA_TYPE not like '%image%'
	and DATA_TYPE not like '%binary%' 
		
	set @sqlTblCols = Substring(@sqlTblCols, 1, len(@sqlTblCols) - 5) + ''''
	
	set @sql = 'select ''' + cast(@logUserID as varChar(10)) + ''', ''' + cast(@borgid as varChar(10)) + ''', ''' + @application + ''', ''' + @tableName + ''', ''' + @action + ''', ''' + @page + ''', ''' + @info + ''', ''' + @version + ''', '''+ @primaryKey +' = '' + cast(d.'+ @primaryKey +' as varChar(10)), ' + @sqlTblCols + ' '
	set @sql = @sql + 'From '+ case when @action = 'DELETE' then '#deleted' else '#inserted' end +' d ' 
 
	insert into LOGMASTER (USERID, BORGID, APPLICATION, TABLENAME, ACTION, PAGE, INFO, VERSION, PRIMARYKEY, DETAILS)
	exec sp_executesql @sql
END

DROP TABLE #inserted
DROP TABLE #deleted

		
ALTER TABLE [dbo].[BORGS] ENABLE TRIGGER [LOGMASTERBORGS]