/****** Object:  Table [dbo].[BUDGETSSNAPSHOT]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[BUDGETSSNAPSHOT](
	[BSID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[BUDGETID] [int] NOT NULL,
	[QTY] [decimal](18, 4) NOT NULL,
	[BUDGET] [decimal](18, 4) NOT NULL,
	[SYSDATE] [datetime] NOT NULL,
 CONSTRAINT [PK_BUDGETSSNAPSHOT] PRIMARY KEY CLUSTERED 
(
	[BSID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[BUDGETSSNAPSHOT] ADD  CONSTRAINT [DF_BUDGETSSNAPSHOT_SYSDATE]  DEFAULT (getdate()) FOR [SYSDATE]