/****** Object:  Table [dbo].[BUYERSACCOUNTS]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[BUYERSACCOUNTS](
	[BORGID] [int] NOT NULL,
	[SUPPID] [int] NOT NULL,
	[SUPPACCID] [int] NOT NULL,
	[BUYERCATID] [int] NOT NULL,
	[DESCRIPTION] [nvarchar](255) NOT NULL,
	[VENDORNAME] [nvarchar](55) NOT NULL,
	[ALLOWBACKPO] [bit] NOT NULL,
	[ALLOWPARTSHIP] [bit] NOT NULL,
	[PREFERREDSUPP] [bit] NOT NULL,
	[SUPPAPPROVERID] [int] NOT NULL,
 CONSTRAINT [PK_BUYERACCOUNTS] PRIMARY KEY CLUSTERED 
(
	[BORGID] ASC,
	[SUPPID] ASC,
	[SUPPACCID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[BUYERSACCOUNTS] ADD  CONSTRAINT [DF_BUYERSACCOUNTS_BUYERCATID]  DEFAULT ((-1)) FOR [BUYERCATID]
ALTER TABLE [dbo].[BUYERSACCOUNTS] ADD  CONSTRAINT [DF_BUYERACCOUNTS_DESCRIPTION]  DEFAULT ('') FOR [DESCRIPTION]
ALTER TABLE [dbo].[BUYERSACCOUNTS] ADD  CONSTRAINT [DF_BUYERSACCOUNTS_ALLOWBACKPO]  DEFAULT (0) FOR [ALLOWBACKPO]
ALTER TABLE [dbo].[BUYERSACCOUNTS] ADD  CONSTRAINT [DF_BUYERSACCOUNTS_ALLOWPARTSHIP]  DEFAULT (0) FOR [ALLOWPARTSHIP]
ALTER TABLE [dbo].[BUYERSACCOUNTS] ADD  CONSTRAINT [DF_BUYERSACCOUNTS_PREFERREDSUPP]  DEFAULT (0) FOR [PREFERREDSUPP]
ALTER TABLE [dbo].[BUYERSACCOUNTS] ADD  CONSTRAINT [DF_BUYERSACCOUNTS_SUPPAPPROVER]  DEFAULT ((-1)) FOR [SUPPAPPROVERID]