/****** Object:  Table [dbo].[CANDY_SCMCERT_SUBCONTRACTOR]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[CANDY_SCMCERT_SUBCONTRACTOR](
	[SUBCONTRACTORID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[UploadListID] [int] NOT NULL,
	[ID] [int] NULL,
	[PACKCODE] [nvarchar](50) NULL,
	[PACKDESC] [nvarchar](100) NULL,
	[SUBCODE] [nvarchar](50) NULL,
	[SUBDESC] [nvarchar](100) NULL,
	[REGNO] [nvarchar](50) NULL,
	[VATNO] [nvarchar](50) NULL,
	[CONTACT] [nvarchar](50) NULL,
	[WORKDESC] [nvarchar](100) NULL,
	[CONTRACTTYPE] [nvarchar](50) NULL,
	[ORDERNUM] [nvarchar](50) NULL,
	[COSTCODE] [nvarchar](50) NULL,
	[PHONE] [nvarchar](50) NULL,
	[MOBILE] [nvarchar](50) NULL,
	[FAX] [nvarchar](50) NULL,
	[EMAIL] [nvarchar](100) NULL,
	[GUARANTEESTATUS] [nvarchar](50) NULL,
	[GUARANTEETYPE] [nvarchar](50) NULL,
	[NOTES] [nvarchar](100) NULL,
	[ADDRESS] [nvarchar](100) NULL,
 CONSTRAINT [PK_CANDY_SCMCERT_SUBCONTRACTOR] PRIMARY KEY CLUSTERED 
(
	[SUBCONTRACTORID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[CANDY_SCMCERT_SUBCONTRACTOR]  WITH CHECK ADD  CONSTRAINT [FK_CANDY_SCMCERT_SUBCONTRACTOR_CANDY_UPLOADLIST] FOREIGN KEY([UploadListID])
REFERENCES [dbo].[CANDY_UPLOADLIST] ([ID])
ALTER TABLE [dbo].[CANDY_SCMCERT_SUBCONTRACTOR] CHECK CONSTRAINT [FK_CANDY_SCMCERT_SUBCONTRACTOR_CANDY_UPLOADLIST]