/****** Object:  Table [dbo].[CANDY_RESOURCESSNAPSHOT]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[CANDY_RESOURCESSNAPSHOT](
	[CRSID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[ID] [int] NOT NULL,
	[EXCHRATE] [decimal](23, 6) NOT NULL,
	[RATE] [decimal](18, 4) NOT NULL,
	[UNIT] [nvarchar](15) NULL,
	[QTY] [decimal](22, 8) NOT NULL,
	[ORDEREDAMOUNT] [decimal](18, 4) NOT NULL,
	[ORDEREDQTY] [decimal](22, 8) NOT NULL,
	[ORDEREDDISCOUNT] [decimal](18, 4) NOT NULL,
	[PERIODUSAGE] [decimal](22, 8) NOT NULL,
	[PERIODWASTE] [decimal](22, 8) NOT NULL,
	[FINALUSAGE] [decimal](22, 8) NOT NULL,
	[FINALWASTE] [decimal](22, 8) NOT NULL,
	[COSTRATE] [decimal](22, 8) NOT NULL,
	[COSTQTY] [decimal](22, 8) NOT NULL,
	[COSTWASTE] [decimal](22, 8) NOT NULL,
	[BILLUSAGE] [decimal](22, 8) NOT NULL,
	[BILLWASTE] [decimal](22, 8) NOT NULL,
	[ACTUALUSAGE] [decimal](22, 8) NOT NULL,
	[ACTUALWASTE] [decimal](22, 8) NOT NULL,
	[CLAIMUSAGE] [decimal](22, 8) NOT NULL,
	[PAIDUSAGE] [decimal](22, 8) NOT NULL,
	[USERUSAGE] [decimal](22, 8) NOT NULL,
	[USERWASTE] [decimal](22, 8) NOT NULL,
	[VOAPPFINALUSAGE] [decimal](22, 8) NOT NULL,
	[VOAPPACTUALUSAGE] [decimal](22, 8) NOT NULL,
	[VOAPPCLAIMUSAGE] [decimal](22, 8) NOT NULL,
	[VOUNAPPFINALUSAGE] [decimal](22, 8) NOT NULL,
	[VOUNAPPACTUALUSAGE] [decimal](22, 8) NOT NULL,
	[SYSDATE] [datetime] NOT NULL,
 CONSTRAINT [PK_CANDY_RESOURCESSNAPSHOT] PRIMARY KEY CLUSTERED 
(
	[CRSID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[CANDY_RESOURCESSNAPSHOT] ADD  CONSTRAINT [DF_CANDY_RESOURCESSNAPSHOT_EXCHRATE]  DEFAULT ((0)) FOR [EXCHRATE]
ALTER TABLE [dbo].[CANDY_RESOURCESSNAPSHOT] ADD  CONSTRAINT [DF_CANDY_RESOURCESSNAPSHOT_RATE]  DEFAULT ((0)) FOR [RATE]
ALTER TABLE [dbo].[CANDY_RESOURCESSNAPSHOT] ADD  CONSTRAINT [DF_CANDY_RESOURCESSNAPSHOT_QTY]  DEFAULT ((0)) FOR [QTY]
ALTER TABLE [dbo].[CANDY_RESOURCESSNAPSHOT] ADD  CONSTRAINT [DF_CANDY_RESOURCESSNAPSHOT_ORDEREDAMOUNT]  DEFAULT ((0)) FOR [ORDEREDAMOUNT]
ALTER TABLE [dbo].[CANDY_RESOURCESSNAPSHOT] ADD  CONSTRAINT [DF_CANDY_RESOURCESSNAPSHOT_ORDEREDQTY]  DEFAULT ((0)) FOR [ORDEREDQTY]
ALTER TABLE [dbo].[CANDY_RESOURCESSNAPSHOT] ADD  CONSTRAINT [DF_CANDY_RESOURCESSNAPSHOT_ORDEREDDISCOUNT]  DEFAULT ((0)) FOR [ORDEREDDISCOUNT]
ALTER TABLE [dbo].[CANDY_RESOURCESSNAPSHOT] ADD  CONSTRAINT [DF_CANDY_RESOURCESSNAPSHOT_PERIODUSAGE]  DEFAULT ((0)) FOR [PERIODUSAGE]
ALTER TABLE [dbo].[CANDY_RESOURCESSNAPSHOT] ADD  CONSTRAINT [DF_CANDY_RESOURCESSNAPSHOT_PERIODWASTE]  DEFAULT ((0)) FOR [PERIODWASTE]
ALTER TABLE [dbo].[CANDY_RESOURCESSNAPSHOT] ADD  CONSTRAINT [DF_CANDY_RESOURCESSNAPSHOT_FINALUSAGE]  DEFAULT ((0)) FOR [FINALUSAGE]
ALTER TABLE [dbo].[CANDY_RESOURCESSNAPSHOT] ADD  CONSTRAINT [DF_CANDY_RESOURCESSNAPSHOT_FINALWASTE]  DEFAULT ((0)) FOR [FINALWASTE]
ALTER TABLE [dbo].[CANDY_RESOURCESSNAPSHOT] ADD  CONSTRAINT [DF_CANDY_RESOURCESSNAPSHOT_COSTRATE]  DEFAULT ((0)) FOR [COSTRATE]
ALTER TABLE [dbo].[CANDY_RESOURCESSNAPSHOT] ADD  CONSTRAINT [DF_CANDY_RESOURCESSNAPSHOT_COSTQTY]  DEFAULT ((0)) FOR [COSTQTY]
ALTER TABLE [dbo].[CANDY_RESOURCESSNAPSHOT] ADD  CONSTRAINT [DF_CANDY_RESOURCESSNAPSHOT_COSTWASTE]  DEFAULT ((0)) FOR [COSTWASTE]
ALTER TABLE [dbo].[CANDY_RESOURCESSNAPSHOT] ADD  CONSTRAINT [DF_CANDY_RESOURCESSNAPSHOT_BILLUSAGE]  DEFAULT ((0)) FOR [BILLUSAGE]
ALTER TABLE [dbo].[CANDY_RESOURCESSNAPSHOT] ADD  CONSTRAINT [DF_CANDY_RESOURCESSNAPSHOT_BILLWASTE]  DEFAULT ((0)) FOR [BILLWASTE]
ALTER TABLE [dbo].[CANDY_RESOURCESSNAPSHOT] ADD  CONSTRAINT [DF_CANDY_RESOURCESSNAPSHOT_ACTUALUSAGE]  DEFAULT ((0)) FOR [ACTUALUSAGE]
ALTER TABLE [dbo].[CANDY_RESOURCESSNAPSHOT] ADD  CONSTRAINT [DF_CANDY_RESOURCESSNAPSHOT_ACTUALWASTE]  DEFAULT ((0)) FOR [ACTUALWASTE]
ALTER TABLE [dbo].[CANDY_RESOURCESSNAPSHOT] ADD  CONSTRAINT [DF_CANDY_RESOURCESSNAPSHOT_CLAIMUSAGE]  DEFAULT ((0)) FOR [CLAIMUSAGE]
ALTER TABLE [dbo].[CANDY_RESOURCESSNAPSHOT] ADD  CONSTRAINT [DF_CANDY_RESOURCESSNAPSHOT_PAIDUSAGE]  DEFAULT ((0)) FOR [PAIDUSAGE]
ALTER TABLE [dbo].[CANDY_RESOURCESSNAPSHOT] ADD  CONSTRAINT [DF_CANDY_RESOURCESSNAPSHOT_USERUSAGE]  DEFAULT ((0)) FOR [USERUSAGE]
ALTER TABLE [dbo].[CANDY_RESOURCESSNAPSHOT] ADD  CONSTRAINT [DF_CANDY_RESOURCESSNAPSHOT_USERWASTE]  DEFAULT ((0)) FOR [USERWASTE]
ALTER TABLE [dbo].[CANDY_RESOURCESSNAPSHOT] ADD  CONSTRAINT [DF_CANDY_RESOURCESSNAPSHOT_VOAPPFINALUSAGE]  DEFAULT ((0)) FOR [VOAPPFINALUSAGE]
ALTER TABLE [dbo].[CANDY_RESOURCESSNAPSHOT] ADD  CONSTRAINT [DF_CANDY_RESOURCESSNAPSHOT_VOAPPACTUALUSAGE]  DEFAULT ((0)) FOR [VOAPPACTUALUSAGE]
ALTER TABLE [dbo].[CANDY_RESOURCESSNAPSHOT] ADD  CONSTRAINT [DF_CANDY_RESOURCESSNAPSHOT_VOAPPCLAIMUSAGE]  DEFAULT ((0)) FOR [VOAPPCLAIMUSAGE]
ALTER TABLE [dbo].[CANDY_RESOURCESSNAPSHOT] ADD  CONSTRAINT [DF_CANDY_RESOURCESSNAPSHOT_VOUNAPPFINALUSAGE]  DEFAULT ((0)) FOR [VOUNAPPFINALUSAGE]
ALTER TABLE [dbo].[CANDY_RESOURCESSNAPSHOT] ADD  CONSTRAINT [DF_CANDY_RESOURCESSNAPSHOT_VOUNAPPACTUALUSAGE]  DEFAULT ((0)) FOR [VOUNAPPACTUALUSAGE]
ALTER TABLE [dbo].[CANDY_RESOURCESSNAPSHOT] ADD  CONSTRAINT [DF_CANDY_RESOURCESSNAPSHOT_SYSDATE]  DEFAULT (getdate()) FOR [SYSDATE]