/****** Object:  Table [dbo].[CANDY_LABOURHOURS]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[CANDY_LABOURHOURS](
	[ID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[TASKCODE] [nvarchar](10) NOT NULL,
	[TASKNAME] [nvarchar](100) NOT NULL,
	[CONTRACT] [nvarchar](20) NOT NULL,
	[UNIT] [nvarchar](15) NULL,
	[BILLQTY] [decimal](22, 8) NOT NULL,
	[BILLNETAMT] [money] NOT NULL,
	[BILLNETHRS] [decimal](22, 8) NOT NULL,
	[ACTUALQTY] [decimal](22, 8) NOT NULL,
	[ACTUALNETAMT] [money] NOT NULL,
	[ACTUALNETHRS] [decimal](22, 8) NOT NULL,
	[FINALQTY] [decimal](22, 8) NOT NULL,
	[FINALNETAMT] [money] NOT NULL,
	[FINANETLHRS] [decimal](22, 8) NOT NULL,
	[NEXTMONTHQTY] [decimal](22, 8) NOT NULL,
	[NEXTMONTHNETAMT] [money] NOT NULL,
	[NEXTMONTHNETHRS] [decimal](22, 8) NOT NULL,
	[REMCOSTAMT] [money] NOT NULL,
	[REMCOSTHRS] [decimal](22, 8) NOT NULL,
	[SYSDATE] [datetime] NOT NULL,
	[USERQTY] [decimal](22, 8) NOT NULL,
	[USERNETAMT] [decimal](22, 8) NOT NULL,
	[USERNETHRS] [decimal](22, 8) NOT NULL,
	[FILEUPLOADDATE] [datetime] NULL,
 CONSTRAINT [PK_CANDY_LABOURHOURS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[CANDY_LABOURHOURS] ADD  CONSTRAINT [DF_CANDY_LABOURHOURS_BILLQTY]  DEFAULT ((0)) FOR [BILLQTY]
ALTER TABLE [dbo].[CANDY_LABOURHOURS] ADD  CONSTRAINT [DF_CANDY_LABOURHOURS_BILLNETHRS]  DEFAULT ((0)) FOR [BILLNETHRS]
ALTER TABLE [dbo].[CANDY_LABOURHOURS] ADD  CONSTRAINT [DF_CANDY_LABOURHOURS_ACTUALQTY]  DEFAULT ((0)) FOR [ACTUALQTY]
ALTER TABLE [dbo].[CANDY_LABOURHOURS] ADD  CONSTRAINT [DF_CANDY_LABOURHOURS_ACTUALNETHRS]  DEFAULT ((0)) FOR [ACTUALNETHRS]
ALTER TABLE [dbo].[CANDY_LABOURHOURS] ADD  CONSTRAINT [DF_CANDY_LABOURHOURS_FINALQTY]  DEFAULT ((0)) FOR [FINALQTY]
ALTER TABLE [dbo].[CANDY_LABOURHOURS] ADD  CONSTRAINT [DF_CANDY_LABOURHOURS_FINANETLHRS]  DEFAULT ((0)) FOR [FINANETLHRS]
ALTER TABLE [dbo].[CANDY_LABOURHOURS] ADD  CONSTRAINT [DF_CANDY_LABOURHOURS_NEXTMONTHQTY]  DEFAULT ((0)) FOR [NEXTMONTHQTY]
ALTER TABLE [dbo].[CANDY_LABOURHOURS] ADD  CONSTRAINT [DF_CANDY_LABOURHOURS_NEXTMONTHNETHRS]  DEFAULT ((0)) FOR [NEXTMONTHNETHRS]
ALTER TABLE [dbo].[CANDY_LABOURHOURS] ADD  CONSTRAINT [DF_CANDY_LABOURHOURS_REMCOSTHRS]  DEFAULT ((0)) FOR [REMCOSTHRS]
ALTER TABLE [dbo].[CANDY_LABOURHOURS] ADD  CONSTRAINT [DF_CANDY_LABOURHOURS_SYSDATE]  DEFAULT (getdate()) FOR [SYSDATE]
ALTER TABLE [dbo].[CANDY_LABOURHOURS] ADD  CONSTRAINT [DF_CANDY_LABOURHOURS_USERQTY]  DEFAULT ((0)) FOR [USERQTY]
ALTER TABLE [dbo].[CANDY_LABOURHOURS] ADD  CONSTRAINT [DF_CANDY_LABOURHOURS_USERNETAMT]  DEFAULT ((0)) FOR [USERNETAMT]
ALTER TABLE [dbo].[CANDY_LABOURHOURS] ADD  CONSTRAINT [DF_CANDY_LABOURHOURS_USERNETHRS]  DEFAULT ((0)) FOR [USERNETHRS]