/****** Object:  Table [dbo].[CANDY_SCMCERT_IMPORTHIST]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[CANDY_SCMCERT_IMPORTHIST](
	[ID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[ReconID] [int] NOT NULL,
	[ImportDate] [datetime] NOT NULL,
	[UserName] [nvarchar](75) NOT NULL,
	[UserID] [int] NOT NULL,
	[UploadListID] [int] NOT NULL,
 CONSTRAINT [PK_CANDY_SCMCERT_IMPORTHIST] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[CANDY_SCMCERT_IMPORTHIST] ADD  CONSTRAINT [DF_CANDY_SCMCERT_IMPORTHIST_ImportDate]  DEFAULT (getdate()) FOR [ImportDate]