/****** Object:  Table [dbo].[CATEGORIESTYPE]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[CATEGORIESTYPE](
	[CATID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[CATNAME] [nvarchar](50) NOT NULL,
	[CATDESCRIPTION] [nvarchar](250) NOT NULL,
	[EID] [nvarchar](10) NOT NULL,
 CONSTRAINT [PK_CATEGORIESTYPE] PRIMARY KEY CLUSTERED 
(
	[CATID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[CATEGORIESTYPE] ADD  CONSTRAINT [DF_CATEGORIESTYPE_CATNAME]  DEFAULT ('') FOR [CATNAME]
ALTER TABLE [dbo].[CATEGORIESTYPE] ADD  CONSTRAINT [DF_CATEGORIESTYPE_CATDESCRPTION]  DEFAULT ('') FOR [CATDESCRIPTION]
ALTER TABLE [dbo].[CATEGORIESTYPE] ADD  CONSTRAINT [DF_CATEGORIESTYPE_EID]  DEFAULT ('') FOR [EID]