/****** Object:  Table [dbo].[CCBATCHHEADER]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[CCBATCHHEADER](
	[HeaderID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[SiteRef] [char](50) NOT NULL,
	[BatchRef] [char](50) NOT NULL,
	[PAYROLLID] [int] NOT NULL,
	[WEEKNO] [int] NOT NULL,
	[PERIODNO] [smallint] NOT NULL,
	[RUNNO] [smallint] NOT NULL,
	[YEARNO] [smallint] NOT NULL,
	[LockHolder] [int] NOT NULL,
	[LockRequestor] [int] NOT NULL,
	[valid] [bit] NOT NULL,
	[posted] [bit] NOT NULL,
	[totRecords] [float] NULL,
	[totEmployees] [float] NULL,
	[totNO] [float] NULL,
	[totO1] [float] NULL,
	[totO2] [float] NULL,
	[totO3] [float] NULL,
	[totO4] [float] NULL,
	[totO5] [float] NULL,
	[totStamps] [float] NULL,
	[totShifts] [float] NULL,
	[useStamps] [bit] NOT NULL,
	[useShifts] [bit] NOT NULL,
	[UseHashEmployees] [bit] NOT NULL,
	[UseHashRecords] [bit] NOT NULL,
	[UseHashNT] [bit] NOT NULL,
	[UseHashOT1] [bit] NOT NULL,
	[UseHashOT2] [bit] NOT NULL,
	[UseHashOT3] [bit] NOT NULL,
	[UseHashOT4] [bit] NOT NULL,
	[UseHashOT5] [bit] NOT NULL,
	[UseHashStamps] [bit] NOT NULL,
	[UseHashShifts] [bit] NOT NULL,
	[USEAUTOADJUST] [bit] NOT NULL,
	[WORKFLOWSTATUS] [int] NOT NULL,
	[BATCHOWNER] [int] NOT NULL,
 CONSTRAINT [PK_CCBatchHeader] PRIMARY KEY CLUSTERED 
(
	[HeaderID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[CCBATCHHEADER] ADD  CONSTRAINT [DF_CCBATCHHEADER_LockHolder]  DEFAULT (0) FOR [LockHolder]
ALTER TABLE [dbo].[CCBATCHHEADER] ADD  CONSTRAINT [DF_CCBATCHHEADER_LockRequestor_1]  DEFAULT (0) FOR [LockRequestor]
ALTER TABLE [dbo].[CCBATCHHEADER] ADD  CONSTRAINT [DF_CCBatchHeader_valid]  DEFAULT (0) FOR [valid]
ALTER TABLE [dbo].[CCBATCHHEADER] ADD  CONSTRAINT [DF_CCBatchHeader_posted]  DEFAULT (0) FOR [posted]
ALTER TABLE [dbo].[CCBATCHHEADER] ADD  CONSTRAINT [DF_CCBATCHHEADER_useStamps]  DEFAULT (1) FOR [useStamps]
ALTER TABLE [dbo].[CCBATCHHEADER] ADD  CONSTRAINT [DF_CCBATCHHEADER_useShifts]  DEFAULT (1) FOR [useShifts]
ALTER TABLE [dbo].[CCBATCHHEADER] ADD  CONSTRAINT [DF__CCBATCHHE__UseHa__3F099E7E]  DEFAULT (0) FOR [UseHashEmployees]
ALTER TABLE [dbo].[CCBATCHHEADER] ADD  CONSTRAINT [DF__CCBATCHHE__UseHa__3FFDC2B7]  DEFAULT (0) FOR [UseHashRecords]
ALTER TABLE [dbo].[CCBATCHHEADER] ADD  CONSTRAINT [DF__CCBATCHHE__UseHa__40F1E6F0]  DEFAULT (0) FOR [UseHashNT]
ALTER TABLE [dbo].[CCBATCHHEADER] ADD  CONSTRAINT [DF__CCBATCHHE__UseHa__41E60B29]  DEFAULT (0) FOR [UseHashOT1]
ALTER TABLE [dbo].[CCBATCHHEADER] ADD  CONSTRAINT [DF__CCBATCHHE__UseHa__42DA2F62]  DEFAULT (0) FOR [UseHashOT2]
ALTER TABLE [dbo].[CCBATCHHEADER] ADD  CONSTRAINT [DF__CCBATCHHE__UseHa__43CE539B]  DEFAULT (0) FOR [UseHashOT3]
ALTER TABLE [dbo].[CCBATCHHEADER] ADD  CONSTRAINT [DF__CCBATCHHE__UseHa__44C277D4]  DEFAULT (0) FOR [UseHashOT4]
ALTER TABLE [dbo].[CCBATCHHEADER] ADD  CONSTRAINT [DF__CCBATCHHE__UseHa__45B69C0D]  DEFAULT (0) FOR [UseHashOT5]
ALTER TABLE [dbo].[CCBATCHHEADER] ADD  CONSTRAINT [DF__CCBATCHHE__UseHa__46AAC046]  DEFAULT (0) FOR [UseHashStamps]
ALTER TABLE [dbo].[CCBATCHHEADER] ADD  CONSTRAINT [DF__CCBATCHHE__UseHa__479EE47F]  DEFAULT (0) FOR [UseHashShifts]
ALTER TABLE [dbo].[CCBATCHHEADER] ADD  CONSTRAINT [DF_CCBATCHHEADER_USEAUTOADJUST]  DEFAULT ((0)) FOR [USEAUTOADJUST]
ALTER TABLE [dbo].[CCBATCHHEADER] ADD  CONSTRAINT [DF_CCBATCHHEADER_WORKFLOWSTATUS]  DEFAULT ((0)) FOR [WORKFLOWSTATUS]
ALTER TABLE [dbo].[CCBATCHHEADER] ADD  CONSTRAINT [DF_CCBATCHHEADER_BATCHOWNER]  DEFAULT ((0)) FOR [BATCHOWNER]