/****** Object:  Table [dbo].[CCBATCHDETAIL]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[CCBATCHDETAIL](
	[DetailId] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[HeaderID] [int] NOT NULL,
	[EMPNUMBER] [nvarchar](15) NOT NULL,
	[DAYNO] [int] NOT NULL,
	[NT] [decimal](18, 2) NOT NULL,
	[OT1] [decimal](18, 2) NOT NULL,
	[OT2] [decimal](18, 2) NOT NULL,
	[OT3] [decimal](18, 2) NOT NULL,
	[OT4] [decimal](18, 2) NOT NULL,
	[OT5] [decimal](18, 2) NOT NULL,
	[USERATE] [char](1) NOT NULL,
	[LEDGERCODE] [char](10) NOT NULL,
	[COSTALLOCATION] [varchar](50) NOT NULL,
	[ACTNUMBER] [char](10) NOT NULL,
	[tDiv] [int] NULL,
	[tPayrollid] [int] NULL,
	[stamps] [decimal](18, 2) NOT NULL,
	[shifts] [decimal](18, 2) NOT NULL,
	[AUTOADJUST] [bit] NOT NULL,
	[RECTYPE] [nvarchar](20) NOT NULL,
	[ABSENTDAYS] [int] NOT NULL,
	[SICKDAYS] [int] NOT NULL,
	[LEAVEDAYS] [int] NOT NULL,
	[GANGCODE] [nvarchar](10) NULL,
	[JOBGRADECODE] [int] NULL,
	[JOBTITLECODE] [int] NULL,
	[SHIFTCODE] [nvarchar](20) NULL,
	[SHIFTTYPE] [nvarchar](20) NOT NULL,
	[NSHOURS] [decimal](18, 4) NOT NULL,
	[SHIFTCOUNT] [int] NOT NULL,
	[NTO] [decimal](18, 4) NOT NULL,
	[OT1O] [decimal](18, 4) NOT NULL,
	[OT2O] [decimal](18, 4) NOT NULL,
	[OT3O] [decimal](18, 4) NOT NULL,
	[OT4O] [decimal](18, 4) NOT NULL,
	[OT5O] [decimal](18, 4) NOT NULL,
 CONSTRAINT [PK_CCBatchData] PRIMARY KEY CLUSTERED 
(
	[DetailId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[CCBATCHDETAIL] ADD  CONSTRAINT [DF_CCBATCHDETAIL_stamps]  DEFAULT (0) FOR [stamps]
ALTER TABLE [dbo].[CCBATCHDETAIL] ADD  CONSTRAINT [DF_CCBATCHDETAIL_shifts]  DEFAULT (0) FOR [shifts]
ALTER TABLE [dbo].[CCBATCHDETAIL] ADD  CONSTRAINT [DF_CCBATCHDETAIL_AUTOADJUST]  DEFAULT ((0)) FOR [AUTOADJUST]
ALTER TABLE [dbo].[CCBATCHDETAIL] ADD  CONSTRAINT [DF_CCBATCHDETAIL_RECTYPE]  DEFAULT ('PRESENT') FOR [RECTYPE]
ALTER TABLE [dbo].[CCBATCHDETAIL] ADD  DEFAULT ((0)) FOR [ABSENTDAYS]
ALTER TABLE [dbo].[CCBATCHDETAIL] ADD  DEFAULT ((0)) FOR [SICKDAYS]
ALTER TABLE [dbo].[CCBATCHDETAIL] ADD  DEFAULT ((0)) FOR [LEAVEDAYS]
ALTER TABLE [dbo].[CCBATCHDETAIL] ADD  DEFAULT ('') FOR [SHIFTTYPE]
ALTER TABLE [dbo].[CCBATCHDETAIL] ADD  DEFAULT ((-1)) FOR [NSHOURS]
ALTER TABLE [dbo].[CCBATCHDETAIL] ADD  DEFAULT ((-1)) FOR [SHIFTCOUNT]
ALTER TABLE [dbo].[CCBATCHDETAIL] ADD  DEFAULT ((-1)) FOR [NTO]
ALTER TABLE [dbo].[CCBATCHDETAIL] ADD  DEFAULT ((-1)) FOR [OT1O]
ALTER TABLE [dbo].[CCBATCHDETAIL] ADD  DEFAULT ((-1)) FOR [OT2O]
ALTER TABLE [dbo].[CCBATCHDETAIL] ADD  DEFAULT ((-1)) FOR [OT3O]
ALTER TABLE [dbo].[CCBATCHDETAIL] ADD  DEFAULT ((-1)) FOR [OT4O]
ALTER TABLE [dbo].[CCBATCHDETAIL] ADD  DEFAULT ((-1)) FOR [OT5O]