/****** Object:  Table [dbo].[CHEQUEFORMATSETUP]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[CHEQUEFORMATSETUP](
	[Description] [nvarchar](35) NOT NULL,
	[XCoord] [numeric](18, 0) NOT NULL,
	[YCoord] [numeric](18, 0) NOT NULL,
	[BorgID] [int] NOT NULL,
	[PageWidth] [numeric](18, 0) NOT NULL,
	[PageHeight] [numeric](18, 0) NOT NULL,
	[Font] [int] NOT NULL,
	[Align] [nvarchar](20) NOT NULL,
	[OutputTo] [nvarchar](55) NOT NULL,
	[TextSize] [numeric](18, 0) NOT NULL,
	[InWords] [bit] NOT NULL,
	[Denomination] [nvarchar](15) NOT NULL,
	[OnLine] [numeric](18, 0) NOT NULL,
	[InColumn] [numeric](18, 0) NOT NULL,
	[DATEFORMAT] [nvarchar](11) NOT NULL,
	[ID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[CHQSTYLE] [nvarchar](15) NOT NULL,
	[CHQSTYLEID] [int] NOT NULL,
	[ONONELINE] [bit] NOT NULL,
 CONSTRAINT [PK_CHEQUEFORMATSETUP] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[CHEQUEFORMATSETUP] ADD  CONSTRAINT [DF_CHEQUEFORMATSETUP_Description]  DEFAULT ('') FOR [Description]
ALTER TABLE [dbo].[CHEQUEFORMATSETUP] ADD  CONSTRAINT [DF_CHEQUEFORMATSETUP_XCoord]  DEFAULT ('0') FOR [XCoord]
ALTER TABLE [dbo].[CHEQUEFORMATSETUP] ADD  CONSTRAINT [DF_CHEQUEFORMATSETUP_YCoord]  DEFAULT ('0') FOR [YCoord]
ALTER TABLE [dbo].[CHEQUEFORMATSETUP] ADD  CONSTRAINT [DF_CHEQUEFORMATSETUP_BorgID]  DEFAULT ('-1') FOR [BorgID]
ALTER TABLE [dbo].[CHEQUEFORMATSETUP] ADD  CONSTRAINT [DF_CHEQUEFORMATSETUP_PageWidth]  DEFAULT ('0') FOR [PageWidth]
ALTER TABLE [dbo].[CHEQUEFORMATSETUP] ADD  CONSTRAINT [DF_CHEQUEFORMATSETUP_PageHeight]  DEFAULT ('0') FOR [PageHeight]
ALTER TABLE [dbo].[CHEQUEFORMATSETUP] ADD  CONSTRAINT [DF_CHEQUEFORMATSETUP_Font]  DEFAULT ('0') FOR [Font]
ALTER TABLE [dbo].[CHEQUEFORMATSETUP] ADD  CONSTRAINT [DF_CHEQUEFORMATSETUP_Align]  DEFAULT ('Left') FOR [Align]
ALTER TABLE [dbo].[CHEQUEFORMATSETUP] ADD  CONSTRAINT [DF_CHEQUEFORMATSETUP_OutputTo]  DEFAULT ('LPT1:') FOR [OutputTo]
ALTER TABLE [dbo].[CHEQUEFORMATSETUP] ADD  CONSTRAINT [DF_CHEQUEFORMATSETUP_TextSize]  DEFAULT ('10') FOR [TextSize]
ALTER TABLE [dbo].[CHEQUEFORMATSETUP] ADD  CONSTRAINT [DF_CHEQUEFORMATSETUP_InWords]  DEFAULT ('1') FOR [InWords]
ALTER TABLE [dbo].[CHEQUEFORMATSETUP] ADD  CONSTRAINT [DF_CHEQUEFORMATSETUP_Denomination]  DEFAULT ('') FOR [Denomination]
ALTER TABLE [dbo].[CHEQUEFORMATSETUP] ADD  CONSTRAINT [DF_CHEQUEFORMATSETUP_OnLine]  DEFAULT ('10') FOR [OnLine]
ALTER TABLE [dbo].[CHEQUEFORMATSETUP] ADD  CONSTRAINT [DF_CHEQUEFORMATSETUP_InColumn]  DEFAULT ('0') FOR [InColumn]
ALTER TABLE [dbo].[CHEQUEFORMATSETUP] ADD  CONSTRAINT [DF_CHEQUEFORMATSETUP_DATEFORMAT]  DEFAULT ('dd/mm/yyyy') FOR [DATEFORMAT]
ALTER TABLE [dbo].[CHEQUEFORMATSETUP] ADD  CONSTRAINT [DF_CHEQUEFORMATSETUP_CHQSTYLE]  DEFAULT ('') FOR [CHQSTYLE]
ALTER TABLE [dbo].[CHEQUEFORMATSETUP] ADD  CONSTRAINT [DF_CHEQUEFORMATSETUP_CHQSTYLEID]  DEFAULT ('0') FOR [CHQSTYLEID]
ALTER TABLE [dbo].[CHEQUEFORMATSETUP] ADD  CONSTRAINT [DF_CHEQUEFORMATSETUP_ONONELINE]  DEFAULT ('0') FOR [ONONELINE]