/****** Object:  Table [dbo].[CLEARSHIFTSAUDIT]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[CLEARSHIFTSAUDIT](
	[PKLAUDITID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[EMPNUMBER] [nvarchar](15) NOT NULL,
	[PAYROLLID] [int] NOT NULL,
	[YEARNO] [int] NOT NULL,
	[SHIFTSBFWD] [int] NOT NULL,
	[ACCSHIFTS] [int] NOT NULL,
	[PAIDMANUALSHIFTSYTD] [decimal](18, 4) NOT NULL,
 CONSTRAINT [PK_CLEARSHIFTSAUDIT] PRIMARY KEY CLUSTERED 
(
	[PKLAUDITID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[CLEARSHIFTSAUDIT] ADD  DEFAULT ((0)) FOR [PAIDMANUALSHIFTSYTD]