/****** Object:  Table [dbo].[CLOCKCARDS]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[CLOCKCARDS](
	[CCID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[PAYROLLID] [int] NOT NULL,
	[EMPNUMBER] [nvarchar](15) NOT NULL,
	[NT] [decimal](18, 4) NOT NULL,
	[OT1] [decimal](18, 4) NOT NULL,
	[OT2] [decimal](18, 4) NOT NULL,
	[OT3] [decimal](18, 4) NOT NULL,
	[OT4] [decimal](18, 4) NOT NULL,
	[OT5] [decimal](18, 4) NOT NULL,
	[WEEKNO] [int] NOT NULL,
	[DAYNO] [int] NOT NULL,
	[PENUMBER] [char](10) NOT NULL,
	[ALLOCATION] [char](25) NOT NULL,
	[CONTRID] [int] NOT NULL,
	[CONTRNUMBER] [nvarchar](10) NOT NULL,
	[ACTID] [int] NOT NULL,
	[ACTNUMBER] [char](10) NOT NULL,
	[LEDGERID] [int] NOT NULL,
	[LEDGERCODE] [char](10) NOT NULL,
	[DIVID] [int] NOT NULL,
	[USERATE] [char](1) NOT NULL,
	[PERIODNO] [smallint] NOT NULL,
	[RUNNO] [smallint] NOT NULL,
	[YEARNO] [smallint] NOT NULL,
	[COST] [decimal](18, 4) NOT NULL,
	[ADDADVAMNT] [int] NOT NULL,
	[STAMPHOURS] [decimal](18, 2) NOT NULL,
	[SHIFTSTW] [decimal](18, 2) NOT NULL,
	[RECTYPE] [nvarchar](20) NOT NULL,
	[NTMONEY] [decimal](19, 4) NOT NULL,
	[OT1MONEY] [decimal](19, 4) NOT NULL,
	[OT2MONEY] [decimal](19, 4) NOT NULL,
	[OT3MONEY] [decimal](19, 4) NOT NULL,
	[OT4MONEY] [decimal](19, 4) NOT NULL,
	[OT5MONEY] [decimal](19, 4) NOT NULL,
	[RATEUSED] [decimal](19, 4) NOT NULL,
	[FKLGANGID] [int] NULL,
	[PRODBONUSAMOUNT] [decimal](18, 4) NOT NULL,
	[JOBGRADECODE] [int] NULL,
	[JOBTITLECODE] [int] NULL,
	[SHIFTCODE] [nvarchar](20) NULL,
	[HEADERID] [int] NULL,
	[TOTHOURS] [decimal](18, 4) NOT NULL,
	[WEIGHT] [decimal](18, 4) NOT NULL,
	[SHIFTTYPE] [nvarchar](20) NOT NULL,
	[NSHOURS] [decimal](18, 4) NOT NULL,
	[SHIFTCOUNT] [int] NOT NULL,
	[NTO] [decimal](18, 4) NOT NULL,
	[OT1O] [decimal](18, 4) NOT NULL,
	[OT2O] [decimal](18, 4) NOT NULL,
	[OT3O] [decimal](18, 4) NOT NULL,
	[OT4O] [decimal](18, 4) NOT NULL,
	[OT5O] [decimal](18, 4) NOT NULL,
 CONSTRAINT [PK_CLOCKCARDS] PRIMARY KEY CLUSTERED 
(
	[CCID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [IX_CC_PAYROLLID_EMPNUMBER_YEARNO_PERIODNO_RUNNO] ON [dbo].[CLOCKCARDS]
(
	[PAYROLLID] ASC,
	[EMPNUMBER] ASC,
	[YEARNO] ASC,
	[PERIODNO] ASC,
	[RUNNO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [IX_CC_PAYROLLID_EMPNUMBER_YEARNO_PERIODNO_RUNNO_CONTRNUMBER_ACTNUMBER_PENUMBER_DIVID_LEDGERCODE] ON [dbo].[CLOCKCARDS]
(
	[PAYROLLID] ASC,
	[EMPNUMBER] ASC,
	[YEARNO] ASC,
	[PERIODNO] ASC,
	[RUNNO] ASC,
	[CONTRNUMBER] ASC,
	[ACTNUMBER] ASC,
	[PENUMBER] ASC,
	[DIVID] ASC,
	[LEDGERCODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [IX_CLOCKCARDS_PAYROLLID_ALLOCATION_YEARNO_RUNNO_PERIODNO_CCID_CONTRID_CONTRNUMBER_PENUMBER_LEDGERCODE_DIVID] ON [dbo].[CLOCKCARDS]
(
	[PAYROLLID] ASC,
	[ALLOCATION] ASC,
	[YEARNO] ASC,
	[RUNNO] ASC,
	[PERIODNO] ASC,
	[CCID] ASC,
	[CONTRID] ASC,
	[CONTRNUMBER] ASC,
	[PENUMBER] ASC,
	[LEDGERCODE] ASC,
	[DIVID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
ALTER TABLE [dbo].[CLOCKCARDS] ADD  CONSTRAINT [DF_CLOCKCARDS_NT]  DEFAULT (0) FOR [NT]
ALTER TABLE [dbo].[CLOCKCARDS] ADD  CONSTRAINT [DF_CLOCKCARDS_OT1]  DEFAULT (0) FOR [OT1]
ALTER TABLE [dbo].[CLOCKCARDS] ADD  CONSTRAINT [DF_CLOCKCARDS_OT2]  DEFAULT (0) FOR [OT2]
ALTER TABLE [dbo].[CLOCKCARDS] ADD  CONSTRAINT [DF_CLOCKCARDS_OT3]  DEFAULT (0) FOR [OT3]
ALTER TABLE [dbo].[CLOCKCARDS] ADD  CONSTRAINT [DF_CLOCKCARDS_OT4]  DEFAULT (0) FOR [OT4]
ALTER TABLE [dbo].[CLOCKCARDS] ADD  CONSTRAINT [DF_CLOCKCARDS_OT5]  DEFAULT (0) FOR [OT5]
ALTER TABLE [dbo].[CLOCKCARDS] ADD  CONSTRAINT [DF_CLOCKCARDS_WEEKNO]  DEFAULT (0) FOR [WEEKNO]
ALTER TABLE [dbo].[CLOCKCARDS] ADD  CONSTRAINT [DF_CLOCKCARDS_DAYNO]  DEFAULT (0) FOR [DAYNO]
ALTER TABLE [dbo].[CLOCKCARDS] ADD  CONSTRAINT [DF_CLOCKCARDS_PENUMBER]  DEFAULT ('') FOR [PENUMBER]
ALTER TABLE [dbo].[CLOCKCARDS] ADD  CONSTRAINT [DF_CLOCKCARDS_ALLOCATION]  DEFAULT ('') FOR [ALLOCATION]
ALTER TABLE [dbo].[CLOCKCARDS] ADD  CONSTRAINT [DF_CLOCKCARDS_CONTRID]  DEFAULT ((-1)) FOR [CONTRID]
ALTER TABLE [dbo].[CLOCKCARDS] ADD  CONSTRAINT [DF_CLOCKCARDS_CONTRNUMBER]  DEFAULT ('') FOR [CONTRNUMBER]
ALTER TABLE [dbo].[CLOCKCARDS] ADD  CONSTRAINT [DF_CLOCKCARDS_ACTID]  DEFAULT ((-1)) FOR [ACTID]
ALTER TABLE [dbo].[CLOCKCARDS] ADD  CONSTRAINT [DF_CLOCKCARDS_ACTNUMBER]  DEFAULT ('') FOR [ACTNUMBER]
ALTER TABLE [dbo].[CLOCKCARDS] ADD  CONSTRAINT [DF_CLOCKCARDS_LEDGERID]  DEFAULT ((-1)) FOR [LEDGERID]
ALTER TABLE [dbo].[CLOCKCARDS] ADD  CONSTRAINT [DF_CLOCKCARDS_LEDGERCODE]  DEFAULT ('') FOR [LEDGERCODE]
ALTER TABLE [dbo].[CLOCKCARDS] ADD  CONSTRAINT [DF_CLOCKCARDS_DIVID]  DEFAULT ((-1)) FOR [DIVID]
ALTER TABLE [dbo].[CLOCKCARDS] ADD  CONSTRAINT [DF_CLOCKCARDS_USERATE]  DEFAULT ('1') FOR [USERATE]
ALTER TABLE [dbo].[CLOCKCARDS] ADD  CONSTRAINT [DF_CLOCKCARDS_PERIODNO]  DEFAULT (1) FOR [PERIODNO]
ALTER TABLE [dbo].[CLOCKCARDS] ADD  CONSTRAINT [DF_CLOCKCARDS_RUNNO]  DEFAULT (1) FOR [RUNNO]
ALTER TABLE [dbo].[CLOCKCARDS] ADD  CONSTRAINT [DF_CLOCKCARDS_YEARNO]  DEFAULT ('2003') FOR [YEARNO]
ALTER TABLE [dbo].[CLOCKCARDS] ADD  CONSTRAINT [DF_CLOCKCARDS_COST]  DEFAULT (0) FOR [COST]
ALTER TABLE [dbo].[CLOCKCARDS] ADD  CONSTRAINT [DF_CLOCKCARDS_ADDADVAMNT]  DEFAULT (0) FOR [ADDADVAMNT]
ALTER TABLE [dbo].[CLOCKCARDS] ADD  CONSTRAINT [DF_CLOCKCARDS_STAMPHOURS]  DEFAULT (0) FOR [STAMPHOURS]
ALTER TABLE [dbo].[CLOCKCARDS] ADD  CONSTRAINT [DF_CLOCKCARDS_SHIFTSTW]  DEFAULT (0) FOR [SHIFTSTW]
ALTER TABLE [dbo].[CLOCKCARDS] ADD  CONSTRAINT [DF_CLOCKCARDS_RECTYPE]  DEFAULT ('PRESENT') FOR [RECTYPE]
ALTER TABLE [dbo].[CLOCKCARDS] ADD  DEFAULT ((0.00)) FOR [NTMONEY]
ALTER TABLE [dbo].[CLOCKCARDS] ADD  DEFAULT ((0.00)) FOR [OT1MONEY]
ALTER TABLE [dbo].[CLOCKCARDS] ADD  DEFAULT ((0.00)) FOR [OT2MONEY]
ALTER TABLE [dbo].[CLOCKCARDS] ADD  DEFAULT ((0.00)) FOR [OT3MONEY]
ALTER TABLE [dbo].[CLOCKCARDS] ADD  DEFAULT ((0.00)) FOR [OT4MONEY]
ALTER TABLE [dbo].[CLOCKCARDS] ADD  DEFAULT ((0.00)) FOR [OT5MONEY]
ALTER TABLE [dbo].[CLOCKCARDS] ADD  DEFAULT ((0.00)) FOR [RATEUSED]
ALTER TABLE [dbo].[CLOCKCARDS] ADD  DEFAULT ((0)) FOR [PRODBONUSAMOUNT]
ALTER TABLE [dbo].[CLOCKCARDS] ADD  DEFAULT ((0)) FOR [TOTHOURS]
ALTER TABLE [dbo].[CLOCKCARDS] ADD  DEFAULT ((0)) FOR [WEIGHT]
ALTER TABLE [dbo].[CLOCKCARDS] ADD  DEFAULT ('') FOR [SHIFTTYPE]
ALTER TABLE [dbo].[CLOCKCARDS] ADD  DEFAULT ((-1)) FOR [NSHOURS]
ALTER TABLE [dbo].[CLOCKCARDS] ADD  DEFAULT ((-1)) FOR [SHIFTCOUNT]
ALTER TABLE [dbo].[CLOCKCARDS] ADD  DEFAULT ((-1)) FOR [NTO]
ALTER TABLE [dbo].[CLOCKCARDS] ADD  DEFAULT ((-1)) FOR [OT1O]
ALTER TABLE [dbo].[CLOCKCARDS] ADD  DEFAULT ((-1)) FOR [OT2O]
ALTER TABLE [dbo].[CLOCKCARDS] ADD  DEFAULT ((-1)) FOR [OT3O]
ALTER TABLE [dbo].[CLOCKCARDS] ADD  DEFAULT ((-1)) FOR [OT4O]
ALTER TABLE [dbo].[CLOCKCARDS] ADD  DEFAULT ((-1)) FOR [OT5O]
ALTER TABLE [dbo].[CLOCKCARDS]  WITH CHECK ADD  CONSTRAINT [FK_CLOCKCARD_GANG] FOREIGN KEY([FKLGANGID])
REFERENCES [dbo].[GANGS] ([PKLGANGID])
ALTER TABLE [dbo].[CLOCKCARDS] CHECK CONSTRAINT [FK_CLOCKCARD_GANG]