/****** Object:  Table [dbo].[CODEDINCOMESTATEMENT]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[CODEDINCOMESTATEMENT](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[CODE] [nvarchar](10) NOT NULL,
	[ICDESC] [nvarchar](55) NOT NULL,
	[ALLOC] [nvarchar](15) NOT NULL,
	[SHOWVALUE] [bit] NOT NULL,
	[SHOWDESCR] [bit] NOT NULL,
	[USEFORMULA] [bit] NOT NULL,
	[FORMULA] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_CODEDINCOMESTATEMENT] PRIMARY KEY CLUSTERED 
(
	[CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

ALTER TABLE [dbo].[CODEDINCOMESTATEMENT] ADD  CONSTRAINT [DF_CODEDINCOMESTATEMENT_CODE]  DEFAULT ('') FOR [CODE]
ALTER TABLE [dbo].[CODEDINCOMESTATEMENT] ADD  CONSTRAINT [DF_CODEDINCOMESTATEMENT_ICDESC]  DEFAULT ('') FOR [ICDESC]
ALTER TABLE [dbo].[CODEDINCOMESTATEMENT] ADD  CONSTRAINT [DF_CODEDINCOMESTATEMENT_ALLOC]  DEFAULT ('') FOR [ALLOC]
ALTER TABLE [dbo].[CODEDINCOMESTATEMENT] ADD  CONSTRAINT [DF_CODEDINCOMESTATEMENT_SHOWVALUE]  DEFAULT (N'1') FOR [SHOWVALUE]
ALTER TABLE [dbo].[CODEDINCOMESTATEMENT] ADD  CONSTRAINT [DF_CODEDINCOMESTATEMENT_SHOWDESCR]  DEFAULT (N'1') FOR [SHOWDESCR]
ALTER TABLE [dbo].[CODEDINCOMESTATEMENT] ADD  CONSTRAINT [DF_CODEDINCOMESTATEMENT_USEFORMULA]  DEFAULT (N'0') FOR [USEFORMULA]
ALTER TABLE [dbo].[CODEDINCOMESTATEMENT] ADD  CONSTRAINT [DF_CODEDINCOMESTATEMENT_FORMULA]  DEFAULT ('') FOR [FORMULA]