/****** Object:  Table [dbo].[COMPADDRESSES]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[COMPADDRESSES](
	[ADDRID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[CONAME1] [nvarchar](127) NOT NULL,
	[CONAME2] [nvarchar](55) NULL,
	[CONAME3] [nvarchar](55) NULL,
	[ADDR1] [nvarchar](55) NOT NULL,
	[ADDR2] [nvarchar](55) NULL,
	[ADDR3] [nvarchar](55) NULL,
	[ADDR4] [nvarchar](55) NULL,
	[ADDR5] [nvarchar](55) NULL,
	[CITY] [nvarchar](35) NOT NULL,
	[PROVINCE] [nvarchar](35) NULL,
	[PCODE] [nvarchar](20) NOT NULL,
	[COUNTRYCODE] [nvarchar](3) NOT NULL,
	[LOCALE] [int] NOT NULL,
	[COMMENTS] [nvarchar](75) NULL,
	[HOMEBORG] [int] NOT NULL,
	[EID] [char](10) NOT NULL,
	[ISSUPPLIER] [bit] NOT NULL,
	[TELEPHONE] [nvarchar](35) NOT NULL,
	[FAX] [nvarchar](35) NOT NULL,
	[PROVINCEID] [int] NOT NULL,
 CONSTRAINT [PK_COMPADDRESSES] PRIMARY KEY CLUSTERED 
(
	[ADDRID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[COMPADDRESSES] ADD  CONSTRAINT [DF_COMPADDRESSES_CONAME1]  DEFAULT ('') FOR [CONAME1]
ALTER TABLE [dbo].[COMPADDRESSES] ADD  CONSTRAINT [DF_COMPADDRESSES_CONAME2]  DEFAULT ('') FOR [CONAME2]
ALTER TABLE [dbo].[COMPADDRESSES] ADD  CONSTRAINT [DF_COMPADDRESSES_CONAME3]  DEFAULT ('') FOR [CONAME3]
ALTER TABLE [dbo].[COMPADDRESSES] ADD  CONSTRAINT [DF_COMPADDRESSES_ADDR2]  DEFAULT ('') FOR [ADDR2]
ALTER TABLE [dbo].[COMPADDRESSES] ADD  CONSTRAINT [DF_COMPADDRESSES_ADDR3]  DEFAULT ('') FOR [ADDR3]
ALTER TABLE [dbo].[COMPADDRESSES] ADD  CONSTRAINT [DF_COMPADDRESSES_ADDR4]  DEFAULT ('') FOR [ADDR4]
ALTER TABLE [dbo].[COMPADDRESSES] ADD  CONSTRAINT [DF_COMPADDRESSES_ADDR5]  DEFAULT ('') FOR [ADDR5]
ALTER TABLE [dbo].[COMPADDRESSES] ADD  CONSTRAINT [DF_COMPADDRESSES_PROVINCE]  DEFAULT ('') FOR [PROVINCE]
ALTER TABLE [dbo].[COMPADDRESSES] ADD  CONSTRAINT [DF_COMPADDRESSES_COMMENTS]  DEFAULT ('') FOR [COMMENTS]
ALTER TABLE [dbo].[COMPADDRESSES] ADD  CONSTRAINT [DF_COMPADDRESSES_EID]  DEFAULT ('') FOR [EID]
ALTER TABLE [dbo].[COMPADDRESSES] ADD  CONSTRAINT [DF__COMPADDRE__ISSUP__4C439E0B]  DEFAULT (0) FOR [ISSUPPLIER]
ALTER TABLE [dbo].[COMPADDRESSES] ADD  CONSTRAINT [DF_COMPADDRESSES_TELEPHONE]  DEFAULT ('') FOR [TELEPHONE]
ALTER TABLE [dbo].[COMPADDRESSES] ADD  CONSTRAINT [DF_COMPADDRESSES_FAX]  DEFAULT ('') FOR [FAX]
ALTER TABLE [dbo].[COMPADDRESSES] ADD  CONSTRAINT [DF_COMPADDRESSES_PROVINCEID]  DEFAULT ((-1)) FOR [PROVINCEID]