/****** Object:  Table [dbo].[CONTRAS]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[CONTRAS](
	[ContraID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[ContraAlloc] [nvarchar](10) NOT NULL,
	[ContraAct] [nvarchar](10) NOT NULL,
	[ContraDesc] [nvarchar](250) NOT NULL,
	[ContraUnit] [nvarchar](10) NOT NULL,
	[ContraRate] [numeric](18, 4) NOT NULL,
	[ContraQty] [numeric](18, 4) NOT NULL,
	[ContraTot] [numeric](18, 4) NOT NULL,
	[ContraThisMonth] [numeric](18, 4) NOT NULL,
	[ContraPrevious] [numeric](18, 4) NOT NULL,
	[ContraReconID] [int] NOT NULL,
	[ContraBorgID] [int] NOT NULL,
	[ContraVATType] [nvarchar](100) NOT NULL,
	[ContraVATAmnt] [money] NOT NULL,
	[ContraStatus] [bit] NOT NULL,
	[ContraRecur] [bit] NOT NULL,
	[CANDYID] [int] NOT NULL,
	[ReconHistID] [int] NOT NULL,
	[INVQTY] [decimal](22, 8) NOT NULL,
	[Remarks] [nvarchar](255) NULL,
	[IsSysEntry] [bit] NOT NULL,
	[INVAMOUNT] [money] NOT NULL,
	[INVRATE] [decimal](22, 8) NOT NULL,
	[WHTID] [int] NOT NULL,
	[WHTAMOUNT] [money] NOT NULL,
	[CLASSID] [int] NOT NULL,
 CONSTRAINT [PK_CONTRAS] PRIMARY KEY CLUSTERED 
(
	[ContraID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[CONTRAS] ADD  CONSTRAINT [DF_CONTRAS_ContraAlloc]  DEFAULT ('') FOR [ContraAlloc]
ALTER TABLE [dbo].[CONTRAS] ADD  CONSTRAINT [DF_CONTRAS_ContraAct]  DEFAULT ('') FOR [ContraAct]
ALTER TABLE [dbo].[CONTRAS] ADD  CONSTRAINT [DF_CONTRAS_ContraDesc]  DEFAULT ('') FOR [ContraDesc]
ALTER TABLE [dbo].[CONTRAS] ADD  CONSTRAINT [DF_CONTRAS_ContraUnit]  DEFAULT ('') FOR [ContraUnit]
ALTER TABLE [dbo].[CONTRAS] ADD  CONSTRAINT [DF_CONTRAS_ContraRate]  DEFAULT ((0)) FOR [ContraRate]
ALTER TABLE [dbo].[CONTRAS] ADD  CONSTRAINT [DF_CONTRAS_ContraQty]  DEFAULT ((0)) FOR [ContraQty]
ALTER TABLE [dbo].[CONTRAS] ADD  CONSTRAINT [DF_CONTRAS_ContraTot]  DEFAULT ((0)) FOR [ContraTot]
ALTER TABLE [dbo].[CONTRAS] ADD  CONSTRAINT [DF_CONTRAS_ContraThisMonth]  DEFAULT ((0)) FOR [ContraThisMonth]
ALTER TABLE [dbo].[CONTRAS] ADD  CONSTRAINT [DF_CONTRAS_ContraPrevious]  DEFAULT ((0)) FOR [ContraPrevious]
ALTER TABLE [dbo].[CONTRAS] ADD  CONSTRAINT [DF_CONTRAS_ContraReconID]  DEFAULT ((-1)) FOR [ContraReconID]
ALTER TABLE [dbo].[CONTRAS] ADD  CONSTRAINT [DF_CONTRAS_ContraBorgID]  DEFAULT ((-1)) FOR [ContraBorgID]
ALTER TABLE [dbo].[CONTRAS] ADD  CONSTRAINT [DF_CONTRAS_ContraVATType]  DEFAULT ('Z') FOR [ContraVATType]
ALTER TABLE [dbo].[CONTRAS] ADD  CONSTRAINT [DF_CONTRAS_ContraVATAmnt]  DEFAULT ((0)) FOR [ContraVATAmnt]
ALTER TABLE [dbo].[CONTRAS] ADD  CONSTRAINT [DF_CONTRAS_ContraStatus]  DEFAULT ((0)) FOR [ContraStatus]
ALTER TABLE [dbo].[CONTRAS] ADD  CONSTRAINT [DF_CONTRAS_ContraRecur]  DEFAULT ((0)) FOR [ContraRecur]
ALTER TABLE [dbo].[CONTRAS] ADD  CONSTRAINT [DF_CONTRAS_CANDYID]  DEFAULT ((-1)) FOR [CANDYID]
ALTER TABLE [dbo].[CONTRAS] ADD  CONSTRAINT [DF_CONTRAS_ReconHistID]  DEFAULT ((-1)) FOR [ReconHistID]
ALTER TABLE [dbo].[CONTRAS] ADD  CONSTRAINT [DF_CONTRAS_INVQTY]  DEFAULT ((0)) FOR [INVQTY]
ALTER TABLE [dbo].[CONTRAS] ADD  CONSTRAINT [DF_CONTRAS_IsSysEntry]  DEFAULT (N'0') FOR [IsSysEntry]
ALTER TABLE [dbo].[CONTRAS] ADD  CONSTRAINT [DF_CONTRAS_INVAMOUNT]  DEFAULT ((0)) FOR [INVAMOUNT]
ALTER TABLE [dbo].[CONTRAS] ADD  CONSTRAINT [DF_CONTRAS_INVRATE]  DEFAULT ((0)) FOR [INVRATE]
ALTER TABLE [dbo].[CONTRAS] ADD  CONSTRAINT [DF_CONTRAS_WHTID]  DEFAULT ((-1)) FOR [WHTID]
ALTER TABLE [dbo].[CONTRAS] ADD  CONSTRAINT [DF_CONTRAS_WHTAMOUNT]  DEFAULT ((0)) FOR [WHTAMOUNT]
ALTER TABLE [dbo].[CONTRAS] ADD  CONSTRAINT [DF_CONTRAS_CLASSID]  DEFAULT ((-1)) FOR [CLASSID]
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE TRIGGER EInvoice_Status_Open            
   ON  CONTRAS
   AFTER   INSERT,UPDATE,DELETE
AS                                 
BEGIN
	 INSERT INTO EI.SUBBIECONTRRECONID(RECONID) 
	 SELECT CONTRARECONID  FROM INSERTED

	 INSERT INTO EI.SUBBIECONTRRECONID(RECONID) 
	 SELECT CONTRARECONID  FROM DELETED 

	 
END

ALTER TABLE [dbo].[CONTRAS] ENABLE TRIGGER [EInvoice_Status_Open]