/****** Object:  Table [dbo].[CREDITORSAC]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[CREDITORSAC](
	[BorgID] [int] NOT NULL,
	[AssCode] [char](10) NOT NULL,
	[AssLedger] [char](80) NOT NULL,
	[AssDescr] [char](80) NOT NULL,
	[AssUse] [bit] NOT NULL
) ON [PRIMARY]

ALTER TABLE [dbo].[CREDITORSAC] ADD  CONSTRAINT [DF_CREDITORSAC_BorgID]  DEFAULT ((1)) FOR [BorgID]
ALTER TABLE [dbo].[CREDITORSAC] ADD  CONSTRAINT [DF_CREDITORSAC_AssCode]  DEFAULT ('') FOR [AssCode]
ALTER TABLE [dbo].[CREDITORSAC] ADD  CONSTRAINT [DF_CREDITORSAC_AssLedger]  DEFAULT ('') FOR [AssLedger]
ALTER TABLE [dbo].[CREDITORSAC] ADD  CONSTRAINT [DF_CREDITORSAC_AssDescr]  DEFAULT ('') FOR [AssDescr]
ALTER TABLE [dbo].[CREDITORSAC] ADD  CONSTRAINT [DF_CREDITORSAC_AssUse]  DEFAULT ((0)) FOR [AssUse]