/****** Object:  Table [dbo].[CURRENCIES]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[CURRENCIES](
	[CURRCODE] [nvarchar](3) NOT NULL,
	[CURRNAME] [nvarchar](50) NOT NULL,
	[LOCALE] [decimal](23, 0) NOT NULL,
	[TOJOINC] [int] NOT NULL,
	[CURRID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[MAJORDENOM] [nvarchar](10) NOT NULL,
	[MINORDENOM] [nvarchar](10) NOT NULL,
	[DECIMALS] [int] NOT NULL,
	[CURRSTATUS] [int] NOT NULL,
 CONSTRAINT [PK_CURRENCIES] PRIMARY KEY CLUSTERED 
(
	[CURRCODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[CURRENCIES] ADD  CONSTRAINT [DF_CURRENCIES_TOJOINC]  DEFAULT (4) FOR [TOJOINC]
ALTER TABLE [dbo].[CURRENCIES] ADD  DEFAULT ('') FOR [MAJORDENOM]
ALTER TABLE [dbo].[CURRENCIES] ADD  DEFAULT ('') FOR [MINORDENOM]
ALTER TABLE [dbo].[CURRENCIES] ADD  CONSTRAINT [DF_CURRENCIES_DECIMALS]  DEFAULT ((2)) FOR [DECIMALS]
ALTER TABLE [dbo].[CURRENCIES] ADD  CONSTRAINT [DF_CURRENCIES_CURRSTATUS]  DEFAULT ((0)) FOR [CURRSTATUS]