/****** Object:  Table [dbo].[CURREXCH]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[CURREXCH](
	[GROUPID] [decimal](23, 0) NOT NULL,
	[FROMCURR] [nvarchar](3) NOT NULL,
	[TOCURR] [nvarchar](3) NOT NULL,
	[STARTDATE] [datetime] NOT NULL,
	[ENDDATE] [datetime] NOT NULL,
	[RATE] [decimal](23, 6) NOT NULL,
	[EXCHID] [decimal](23, 0) IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
 CONSTRAINT [PK_CURREXCH] PRIMARY KEY NONCLUSTERED 
(
	[EXCHID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[CURREXCH] ADD  CONSTRAINT [DF_CURREXCH_ENDDATE]  DEFAULT (convert(datetime,(getdate() + 7200),103)) FOR [ENDDATE]