/****** Object:  Table [dbo].[DEBTORSBANKAPPROVAL]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[DEBTORSBANKAPPROVAL](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[SOURCEID] [int] NOT NULL,
	[DEBTNUMBER] [nvarchar](10) NOT NULL,
	[BANKID] [int] NOT NULL,
	[BORGID] [int] NOT NULL,
	[REQUESTUSERID] [int] NOT NULL,
	[SUBMITDATE] [datetime] NULL,
	[SUBMITCOMMENT] [nvarchar](250) NOT NULL,
	[APPROVERUSERID] [int] NULL,
	[APPROVEDATE] [datetime] NULL,
	[STATUS] [int] NOT NULL,
	[STATUSDATE] [datetime] NULL,
	[APPROVECOMMENT] [nvarchar](250) NOT NULL,
	[COMPLETE] [bit] NOT NULL,
 CONSTRAINT [PK_DEBTORSBANKAPPROVAL] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[DEBTORSBANKAPPROVAL] ADD  CONSTRAINT [DF_DEBTORSBANKAPPROVAL_SOURCEID]  DEFAULT ((-1)) FOR [SOURCEID]
ALTER TABLE [dbo].[DEBTORSBANKAPPROVAL] ADD  CONSTRAINT [DF_DEBTORSBANKAPPROVAL_DEBTNUMBER]  DEFAULT ('') FOR [DEBTNUMBER]
ALTER TABLE [dbo].[DEBTORSBANKAPPROVAL] ADD  CONSTRAINT [DF_DEBTORSBANKAPPROVAL_BANKID]  DEFAULT ((-1)) FOR [BANKID]
ALTER TABLE [dbo].[DEBTORSBANKAPPROVAL] ADD  CONSTRAINT [DF_DEBTORSBANKAPPROVAL_BORGID]  DEFAULT ((-1)) FOR [BORGID]
ALTER TABLE [dbo].[DEBTORSBANKAPPROVAL] ADD  CONSTRAINT [DF_DEBTORSBANKAPPROVAL_REQUESTUSERID]  DEFAULT ((-1)) FOR [REQUESTUSERID]
ALTER TABLE [dbo].[DEBTORSBANKAPPROVAL] ADD  CONSTRAINT [DF_DEBTORSBANKAPPROVAL_SUBMITCOMMENT]  DEFAULT ('') FOR [SUBMITCOMMENT]
ALTER TABLE [dbo].[DEBTORSBANKAPPROVAL] ADD  CONSTRAINT [DF_DEBTORSBANKAPPROVAL_APPROVERUSERID]  DEFAULT ((-1)) FOR [APPROVERUSERID]
ALTER TABLE [dbo].[DEBTORSBANKAPPROVAL] ADD  CONSTRAINT [DF_DEBTORSBANKAPPROVAL_STATUS]  DEFAULT ((0)) FOR [STATUS]
ALTER TABLE [dbo].[DEBTORSBANKAPPROVAL] ADD  CONSTRAINT [DF_DEBTORSBANKAPPROVAL_APPROVECOMMENT]  DEFAULT ('') FOR [APPROVECOMMENT]
ALTER TABLE [dbo].[DEBTORSBANKAPPROVAL] ADD  CONSTRAINT [DF_DEBTORSBANKAPPROVAL_COMPLETE]  DEFAULT (N'0') FOR [COMPLETE]