/****** Object:  Table [dbo].[debtrecons14aug20]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[debtrecons14aug20](
	[OrgID] [int] NOT NULL,
	[SubConNumber] [char](10) NULL,
	[Contract] [int] NULL,
	[Activity] [int] NULL,
	[ValNo] [numeric](18, 0) NULL,
	[Certno] [numeric](18, 0) NULL,
	[ContValue] [money] NULL,
	[WorkDoneTot] [money] NULL,
	[WorkDonePrev] [money] NULL,
	[WorkDoneThisMonth] [money] NULL,
	[EscalationTot] [money] NULL,
	[EscalationPrev] [money] NULL,
	[EscalationThisMonth] [money] NULL,
	[MOSTot] [money] NULL,
	[MOSPrev] [money] NULL,
	[MOSThisMonth] [money] NULL,
	[AdvanceTot] [money] NULL,
	[AdvancePrev] [money] NULL,
	[AdvanceThisMonth] [money] NULL,
	[AdditionalTot] [money] NULL,
	[AdditionalPrev] [money] NULL,
	[AdditionalThisMonth] [money] NULL,
	[BFWDTot] [money] NULL,
	[BFWDPrev] [money] NULL,
	[BFWDThisMonth] [money] NULL,
	[VATTot] [money] NULL,
	[VATPrev] [money] NULL,
	[VATThisMonth] [money] NULL,
	[DiscountTot] [money] NULL,
	[DiscountPrev] [money] NULL,
	[DiscountThisMonth] [money] NULL,
	[RetentionTot] [money] NULL,
	[RetentionPrev] [money] NULL,
	[RetentionThisMonth] [money] NULL,
	[ContraTot] [money] NULL,
	[ContraPrev] [money] NULL,
	[ContraThisMonth] [money] NULL,
	[WithholdTot] [money] NULL,
	[WithholdPrev] [money] NULL,
	[WithholdThisMonth] [money] NULL,
	[WithholdPerc] [numeric](18, 3) NULL,
	[AmountDue] [money] NULL,
	[PrevPaid] [money] NULL,
	[TotDue] [money] NULL,
	[VATPerc] [decimal](18, 4) NOT NULL,
	[VATAmount] [money] NULL,
	[Paid] [money] NULL,
	[Name] [char](10) NULL,
	[SupName] [nvarchar](127) NOT NULL,
	[Code] [char](10) NULL,
	[Credno] [char](10) NULL,
	[Ret1] [money] NULL,
	[Ret2] [money] NULL,
	[RCo1] [money] NULL,
	[RCo2] [money] NULL,
	[Disc] [money] NULL,
	[Posted] [bit] NOT NULL,
	[LPosted] [bit] NOT NULL,
	[Printed] [bit] NOT NULL,
	[SCType] [char](10) NULL,
	[VATno] [char](10) NULL,
	[Remark] [char](200) NULL,
	[GLCode] [char](10) NULL,
	[ReconID] [int] IDENTITY(1,1) NOT NULL,
	[UserID] [nvarchar](15) NOT NULL,
	[PostDate] [datetime] NULL,
	[PostRef] [char](10) NULL,
	[Orderno] [nvarchar](35) NULL,
	[Interest] [money] NOT NULL,
	[InterestTot] [money] NOT NULL,
	[Currency] [char](3) NOT NULL,
	[Exchrate] [float] NOT NULL,
	[Contrexchrate] [float] NOT NULL,
	[DomTot] [money] NULL,
	[DomThisMonth] [money] NULL,
	[DomPrev] [money] NULL,
	[NomTot] [money] NULL,
	[NomThisMonth] [money] NULL,
	[NomPrev] [money] NULL,
	[DirTot] [money] NULL,
	[DirThisMonth] [money] NULL,
	[DirPrev] [money] NULL,
	[FltTot] [money] NULL,
	[FltThisMonth] [money] NULL,
	[FltPrev] [money] NULL,
	[VALDONETOT] [money] NOT NULL,
	[VALDONEPREV] [money] NOT NULL,
	[VALDONETHISMONTH] [money] NOT NULL,
	[MARGIN] [money] NOT NULL,
	[VATONADV] [money] NOT NULL,
	[VATONWDONE] [money] NOT NULL,
	[RETPERC] [decimal](18, 4) NOT NULL,
	[WithholdAMOUNT] [money] NOT NULL,
	[DRAPPROVER] [int] NULL,
	[DRAPPDATE] [datetime] NULL,
	[DRPOSTBY] [int] NULL,
	[DRPOSTDATE] [datetime] NULL,
	[VatType] [nvarchar](100) NULL,
	[WithholdID] [int] NULL,
	[CERTNOPREV] [numeric](18, 0) NULL,
	[FROMDATE] [datetime] NULL,
	[BOQPOSTDETAIL] [bit] NOT NULL,
	[LEDGER] [char](10) NULL,
	[RETRELEASEDATE] [datetime] NULL,
	[OVERRIDETAX] [int] NOT NULL,
	[OVERRIDEWHT] [int] NOT NULL,
	[WFVALUEAPPROVED] [bit] NOT NULL,
	[SUBMITTED] [bit] NOT NULL,
	[APPROVED] [bit] NOT NULL,
	[REJECTED] [bit] NOT NULL,
	[LOGUSERID] [int] NOT NULL,
	[LOGDATETIME] [datetime] NOT NULL,
	[INTERESTPREV] [money] NOT NULL,
	[ReconHistID] [int] NOT NULL,
	[ADVANCEPERC] [decimal](18, 4) NOT NULL,
	[CLASSID] [int] NOT NULL
) ON [PRIMARY]