/****** Object:  Table [dbo].[DEBTORCONTRAS]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[DEBTORCONTRAS](
	[CONTRAID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[CONTRAALLOC] [nvarchar](10) NOT NULL,
	[CONTRAACT] [nvarchar](10) NOT NULL,
	[CONTRADESC] [nvarchar](250) NOT NULL,
	[CONTRAUNIT] [nvarchar](10) NOT NULL,
	[CONTRARATE] [numeric](18, 4) NOT NULL,
	[CONTRAQTY] [numeric](18, 4) NOT NULL,
	[CONTRATOT] [numeric](18, 4) NOT NULL,
	[CONTRATHISMONTH] [numeric](18, 4) NOT NULL,
	[CONTRAPREVIOUS] [numeric](18, 4) NOT NULL,
	[CONTRARECONID] [int] NOT NULL,
	[CONTRABORGID] [int] NOT NULL,
	[CONTRAVATTYPE] [nvarchar](100) NOT NULL,
	[CONTRAVATAMNT] [money] NOT NULL,
	[CONTRASTATUS] [bit] NOT NULL,
	[CONTRARECUR] [bit] NOT NULL,
	[ReconHistID] [int] NOT NULL,
	[WHTID] [int] NOT NULL,
	[WHTAMOUNT] [money] NOT NULL,
	[CLASSID] [int] NOT NULL,
 CONSTRAINT [PK_DEBTORCONTRAS] PRIMARY KEY CLUSTERED 
(
	[CONTRAID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[DEBTORCONTRAS] ADD  CONSTRAINT [DF_DEBTORCONTRAS_CONTRAALLOC]  DEFAULT ('') FOR [CONTRAALLOC]
ALTER TABLE [dbo].[DEBTORCONTRAS] ADD  CONSTRAINT [DF_DEBTORCONTRAS_CONTRAACT]  DEFAULT ('') FOR [CONTRAACT]
ALTER TABLE [dbo].[DEBTORCONTRAS] ADD  CONSTRAINT [DF_DEBTORCONTRAS_CONTRADESC]  DEFAULT ('') FOR [CONTRADESC]
ALTER TABLE [dbo].[DEBTORCONTRAS] ADD  CONSTRAINT [DF_DEBTORCONTRAS_CONTRAUNIT]  DEFAULT ('') FOR [CONTRAUNIT]
ALTER TABLE [dbo].[DEBTORCONTRAS] ADD  CONSTRAINT [DF_DEBTORCONTRAS_CONTRARATE]  DEFAULT ('0') FOR [CONTRARATE]
ALTER TABLE [dbo].[DEBTORCONTRAS] ADD  CONSTRAINT [DF_DEBTORCONTRAS_CONTRAQTY]  DEFAULT ('0') FOR [CONTRAQTY]
ALTER TABLE [dbo].[DEBTORCONTRAS] ADD  CONSTRAINT [DF_DEBTORCONTRAS_CONTRATOT]  DEFAULT ('0') FOR [CONTRATOT]
ALTER TABLE [dbo].[DEBTORCONTRAS] ADD  CONSTRAINT [DF_DEBTORCONTRAS_CONTRATHISMONTH]  DEFAULT ('0') FOR [CONTRATHISMONTH]
ALTER TABLE [dbo].[DEBTORCONTRAS] ADD  CONSTRAINT [DF_DEBTORCONTRAS_CONTRAPREVIOUS]  DEFAULT ('0') FOR [CONTRAPREVIOUS]
ALTER TABLE [dbo].[DEBTORCONTRAS] ADD  CONSTRAINT [DF_DEBTORCONTRAS_CONTRARECONID]  DEFAULT ((-1)) FOR [CONTRARECONID]
ALTER TABLE [dbo].[DEBTORCONTRAS] ADD  CONSTRAINT [DF_DEBTORCONTRAS_CONTRABORGID]  DEFAULT ((-1)) FOR [CONTRABORGID]
ALTER TABLE [dbo].[DEBTORCONTRAS] ADD  CONSTRAINT [DF_DEBTORCONTRAS_CONTRAVATTYPE]  DEFAULT ('Z') FOR [CONTRAVATTYPE]
ALTER TABLE [dbo].[DEBTORCONTRAS] ADD  CONSTRAINT [DF_DEBTORCONTRAS_CONTRAVATAMNT]  DEFAULT ((0)) FOR [CONTRAVATAMNT]
ALTER TABLE [dbo].[DEBTORCONTRAS] ADD  CONSTRAINT [DF_DEBTORCONTRAS_CONTRASTATUS]  DEFAULT ('0') FOR [CONTRASTATUS]
ALTER TABLE [dbo].[DEBTORCONTRAS] ADD  CONSTRAINT [DF_DEBTORCONTRAS_CONTRARECUR]  DEFAULT ('0') FOR [CONTRARECUR]
ALTER TABLE [dbo].[DEBTORCONTRAS] ADD  CONSTRAINT [DF_DEBTORCONTRAS_ReconHistID]  DEFAULT ((-1)) FOR [ReconHistID]
ALTER TABLE [dbo].[DEBTORCONTRAS] ADD  CONSTRAINT [DF_DEBTORCONTRAS_WHTID]  DEFAULT ((-1)) FOR [WHTID]
ALTER TABLE [dbo].[DEBTORCONTRAS] ADD  CONSTRAINT [DF_DEBTORCONTRAS_WHTAMOUNT]  DEFAULT ((0)) FOR [WHTAMOUNT]
ALTER TABLE [dbo].[DEBTORCONTRAS] ADD  CONSTRAINT [DF_DEBTORCONTRAS_CLASSID]  DEFAULT ((-1)) FOR [CLASSID]