/****** Object:  Table [dbo].[DELIVERIESSNAPSHOT]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[DELIVERIESSNAPSHOT](
	[DSID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[DLVRID] [int] NOT NULL,
	[ALLOCATED] [bit] NOT NULL,
	[RECONQTY] [decimal](18, 4) NOT NULL,
	[SYSDATE] [datetime] NOT NULL,
 CONSTRAINT [PK_DELIVERIESSNAPSHOT] PRIMARY KEY CLUSTERED 
(
	[DSID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[DELIVERIESSNAPSHOT] ADD  CONSTRAINT [DF_DELIVERIESSNAPSHOT_SYSDATE]  DEFAULT (getdate()) FOR [SYSDATE]