/****** Object:  Table [dbo].[DELIVERIESHISTORY]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[DELIVERIESHISTORY](
	[DLVRHISTID] [int] IDENTITY(1,1) NOT NULL,
	[HISTDATE] [datetime] NOT NULL,
	[HISTUSERID] [int] NOT NULL,
	[DLVRID] [int] NOT NULL,
	[LYEAR] [char](10) NOT NULL,
	[PERIOD] [int] NOT NULL,
	[DLVRNO] [nvarchar](55) NOT NULL,
	[GRNNO] [nvarchar](55) NOT NULL,
	[DLVRQTY] [numeric](18, 4) NOT NULL,
	[ALLOCATION] [char](25) NOT NULL,
	[ALLOCATED] [bit] NOT NULL,
	[ORDID] [char](10) NOT NULL,
	[DLVRDATE] [datetime] NOT NULL,
	[ORDITEMLINENO] [int] NOT NULL,
	[USERID] [int] NOT NULL,
	[RECONQTY] [decimal](18, 4) NOT NULL,
	[STORECODE] [char](15) NOT NULL,
	[DLVRCAPTDATE] [datetime] NOT NULL,
	[TBORGID] [int] NULL,
	[PRICE] [money] NULL,
	[RFDID] [int] NOT NULL
) ON [PRIMARY]

ALTER TABLE [dbo].[DELIVERIESHISTORY] ADD  CONSTRAINT [DF_DELIVERIESHISTORY_PRICE]  DEFAULT ((0)) FOR [PRICE]
ALTER TABLE [dbo].[DELIVERIESHISTORY] ADD  CONSTRAINT [DF_DELIVERIESHISTORY_RFDID]  DEFAULT ((-1)) FOR [RFDID]