/****** Object:  Table [dbo].[DELIVERIESRECON]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[DELIVERIESRECON](
	[TRANSID] [int] NOT NULL,
	[DLVRID] [int] NOT NULL,
	[TRANSIDC] [int] NOT NULL,
	[INVOICENO] [nvarchar](10) NOT NULL,
	[QTY] [numeric](24, 4) NOT NULL,
	[RATE] [numeric](24, 4) NOT NULL,
	[AMOUNT] [numeric](24, 4) NOT NULL,
 CONSTRAINT [PK_DELIVERIESRECON] PRIMARY KEY CLUSTERED 
(
	[TRANSID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[DELIVERIESRECON] ADD  CONSTRAINT [DF_DELIVERIESRECON_DLVRID]  DEFAULT ('-1') FOR [DLVRID]
ALTER TABLE [dbo].[DELIVERIESRECON] ADD  CONSTRAINT [DF_DELIVERIESRECON_TRANSIDC]  DEFAULT ('-1') FOR [TRANSIDC]
ALTER TABLE [dbo].[DELIVERIESRECON] ADD  CONSTRAINT [DF_DELIVERIESRECON_INVOICENO]  DEFAULT ('') FOR [INVOICENO]
ALTER TABLE [dbo].[DELIVERIESRECON] ADD  CONSTRAINT [DF_DELIVERIESRECON_QTY]  DEFAULT ('0') FOR [QTY]
ALTER TABLE [dbo].[DELIVERIESRECON] ADD  CONSTRAINT [DF_DELIVERIESRECON_RATE]  DEFAULT ('0') FOR [RATE]
ALTER TABLE [dbo].[DELIVERIESRECON] ADD  CONSTRAINT [DF_DELIVERIESRECON_AMOUNT]  DEFAULT ('0') FOR [AMOUNT]