/****** Object:  Table [dbo].[DELIVERIES]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[DELIVERIES](
	[DLVRID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[LYEAR] [char](10) NOT NULL,
	[PERIOD] [int] NOT NULL,
	[DLVRNO] [nvarchar](55) NOT NULL,
	[GRNNO] [nvarchar](55) NOT NULL,
	[DLVRQTY] [numeric](18, 4) NOT NULL,
	[ALLOCATION] [char](25) NOT NULL,
	[ALLOCATED] [bit] NOT NULL,
	[ORDID] [int] NOT NULL,
	[DLVRDATE] [datetime] NOT NULL,
	[ORDITEMLINENO] [int] NOT NULL,
	[USERID] [int] NOT NULL,
	[RECONQTY] [decimal](18, 4) NOT NULL,
	[STORECODE] [char](15) NOT NULL,
	[DLVRCAPTDATE] [datetime] NOT NULL,
	[TBORGID] [int] NULL,
	[PRICE] [money] NULL,
	[RFDID] [int] NOT NULL,
 CONSTRAINT [PK_DELIVERIES] PRIMARY KEY CLUSTERED 
(
	[DLVRID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [IX_DELIVERIES_ALLOCATED_ORDID_DLVRDATE_ALLOCATION_LYEAR_ORDITEMLINENO_PERIOD] ON [dbo].[DELIVERIES]
(
	[ALLOCATED] ASC,
	[ORDID] ASC,
	[DLVRDATE] ASC,
	[ALLOCATION] ASC,
	[LYEAR] ASC,
	[ORDITEMLINENO] ASC,
	[PERIOD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
CREATE NONCLUSTERED INDEX [IX_DELIVERIES_ORDID] ON [dbo].[DELIVERIES]
(
	[ORDID] ASC
)
INCLUDE([DLVRQTY],[RECONQTY]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
CREATE NONCLUSTERED INDEX [IX_DELIVERIES_ORDID_ORDITEMLINENO_ORDID_ORDITEMLINENO] ON [dbo].[DELIVERIES]
(
	[ORDID] ASC,
	[ORDITEMLINENO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
ALTER TABLE [dbo].[DELIVERIES] ADD  CONSTRAINT [DF_DELIVERIES_ALLOCATION]  DEFAULT ('') FOR [ALLOCATION]
ALTER TABLE [dbo].[DELIVERIES] ADD  CONSTRAINT [DF_DELIVERIES_ALLOCATED]  DEFAULT (0) FOR [ALLOCATED]
ALTER TABLE [dbo].[DELIVERIES] ADD  CONSTRAINT [DF_DELIVERIES_DLVRDATE]  DEFAULT (getdate()) FOR [DLVRDATE]
ALTER TABLE [dbo].[DELIVERIES] ADD  CONSTRAINT [DF_DELIVERIES_RECONQTY]  DEFAULT (0) FOR [RECONQTY]
ALTER TABLE [dbo].[DELIVERIES] ADD  CONSTRAINT [DF_DELIVERIES_STORECODE]  DEFAULT ('') FOR [STORECODE]
ALTER TABLE [dbo].[DELIVERIES] ADD  CONSTRAINT [DF_DELIVERIES_DLVRCAPTDATE]  DEFAULT (getdate()) FOR [DLVRCAPTDATE]
ALTER TABLE [dbo].[DELIVERIES] ADD  CONSTRAINT [DF_DELIVERIES_RFDID]  DEFAULT ((-1)) FOR [RFDID]
ALTER TABLE [dbo].[DELIVERIES]  WITH NOCHECK ADD  CONSTRAINT [FK_DELIVERIES_INVSTORES] FOREIGN KEY([STORECODE])
REFERENCES [dbo].[INVSTORES] ([StoreCode])
ALTER TABLE [dbo].[DELIVERIES] NOCHECK CONSTRAINT [FK_DELIVERIES_INVSTORES]
ALTER TABLE [dbo].[DELIVERIES]  WITH CHECK ADD  CONSTRAINT [FK_DELIVERIES_ORDITEMS] FOREIGN KEY([ORDID], [ORDITEMLINENO])
REFERENCES [dbo].[ORDITEMS] ([ORDID], [LINENUMBER])
ALTER TABLE [dbo].[DELIVERIES] CHECK CONSTRAINT [FK_DELIVERIES_ORDITEMS]
ALTER TABLE [dbo].[DELIVERIES]  WITH CHECK ADD  CONSTRAINT [FK_DELIVERIES_USERS] FOREIGN KEY([USERID])
REFERENCES [dbo].[USERS] ([USERID])
ALTER TABLE [dbo].[DELIVERIES] CHECK CONSTRAINT [FK_DELIVERIES_USERS]
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON

CREATE TRIGGER [dbo].[TR_DELIVERIES_FutureDel] ON [dbo].[DELIVERIES]
   AFTER INSERT
AS 
BEGIN
	SET NOCOUNT ON
	declare @DelDate									datetime;
	declare @Sysdate									datetime;	
	declare @mess										nvarchar(255)

	Select @Deldate = DLVRDATE from inserted;
	Select @Sysdate = DLVRCAPTDATE from inserted;

	if (@DelDate>@Sysdate)
	begin
	Set @Mess = 'You can not capture deliveries for future dates.  (Error from FutureDel trigger on Deliveries)'
	   Raiserror( @Mess ,16,1)
	rollback transaction
	end

END

ALTER TABLE [dbo].[DELIVERIES] ENABLE TRIGGER [TR_DELIVERIES_FutureDel]
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON

CREATE TRIGGER TR_DELIVERIESSNAPSHOT ON DELIVERIES
AFTER UPDATE
AS 

SET NOCOUNT ON

insert into DELIVERIESSNAPSHOT (DLVRID, ALLOCATED, RECONQTY, SYSDATE)
SELECT D.DLVRID, D.ALLOCATED, D.RECONQTY, getDate()
FROM INSERTED I inner join DELETED D on I.DLVRID = D.DLVRID
WHERE I.ALLOCATED <> D.ALLOCATED
OR I.RECONQTY <> D.RECONQTY

		
ALTER TABLE [dbo].[DELIVERIES] ENABLE TRIGGER [TR_DELIVERIESSNAPSHOT]