/****** Object:  Table [dbo].[DOCUMENTSYNCTYPES]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[DOCUMENTSYNCTYPES](
	[ID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[DTYPE] [nvarchar](50) NOT NULL,
	[SYNCDATE] [datetime] NOT NULL,
	[STATUS] [nvarchar](50) NOT NULL,
	[ERRORDESC] [nvarchar](255) NULL,
 CONSTRAINT [PK_DOCUMENTSYNCTYPES] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[DOCUMENTSYNCTYPES] ADD  CONSTRAINT [DF_DOCUMENTSYNCTYPES_SYNCDATE]  DEFAULT (getdate()) FOR [SYNCDATE]