/****** Object:  Table [dbo].[EDSETSTEMPLATE]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[EDSETSTEMPLATE](
	[EDSID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[EDSCODE] [nvarchar](5) NOT NULL,
	[EDSNUMBER] [nvarchar](5) NOT NULL,
	[EDSDESCR] [nvarchar](75) NOT NULL,
	[IRP5CODE] [nvarchar](5) NOT NULL,
	[SDL10] [bit] NOT NULL,
	[EDSTARGET] [nvarchar](8) NOT NULL,
	[EOYCLEAR] [bit] NOT NULL,
	[MINHRS] [smallint] NOT NULL,
	[MAXHRS] [smallint] NOT NULL,
	[LEDGERCODE] [char](10) NOT NULL,
	[COMPANYFACTOR] [decimal](18, 4) NOT NULL,
	[ISWCA] [bit] NOT NULL,
	[ISSTAMP] [bit] NOT NULL,
	[EDSTYPE] [nvarchar](2) NOT NULL,
	[TAXPERC] [decimal](18, 4) NOT NULL,
	[TRIG] [char](1) NOT NULL,
	[EDTYPE] [nvarchar](20) NOT NULL,
	[PRINTYTD] [bit] NOT NULL,
	[EDSUSEAS] [nvarchar](50) NOT NULL,
	[ISDEDUCTION] [bit] NOT NULL,
	[EDSVALUE] [decimal](18, 4) NOT NULL,
	[IRP5BLOCK] [nvarchar](5) NOT NULL,
	[DEDUCTBEFORETAXPERC] [decimal](18, 4) NOT NULL,
	[ISUIF] [bit] NOT NULL,
	[ISRSC] [bit] NOT NULL,
	[ISRFI] [bit] NOT NULL,
 CONSTRAINT [PK_EDSETSTEMPLATE] PRIMARY KEY CLUSTERED 
(
	[EDSID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[EDSETSTEMPLATE] ADD  CONSTRAINT [DF_EDSETSTEMPLATE_EDSCODE]  DEFAULT ('') FOR [EDSCODE]
ALTER TABLE [dbo].[EDSETSTEMPLATE] ADD  CONSTRAINT [DF_EDSETSTEMPLATE_EDSNUMBER]  DEFAULT ('') FOR [EDSNUMBER]
ALTER TABLE [dbo].[EDSETSTEMPLATE] ADD  CONSTRAINT [DF_EDSETSTEMPLATE_EDSDESCR]  DEFAULT ('') FOR [EDSDESCR]
ALTER TABLE [dbo].[EDSETSTEMPLATE] ADD  CONSTRAINT [DF_EDSETSTEMPLATE_IRP5BLOCK]  DEFAULT ('') FOR [IRP5CODE]
ALTER TABLE [dbo].[EDSETSTEMPLATE] ADD  CONSTRAINT [DF_EDSETSTEMPLATE_SDL10]  DEFAULT (0) FOR [SDL10]
ALTER TABLE [dbo].[EDSETSTEMPLATE] ADD  CONSTRAINT [DF_EDSETSTEMPLATE_EDSTARGET]  DEFAULT (N'Wages') FOR [EDSTARGET]
ALTER TABLE [dbo].[EDSETSTEMPLATE] ADD  CONSTRAINT [DF_EDSETSTEMPLATE_EOYCLEAR]  DEFAULT (0) FOR [EOYCLEAR]
ALTER TABLE [dbo].[EDSETSTEMPLATE] ADD  CONSTRAINT [DF_EDSETSTEMPLATE_MINHRS]  DEFAULT (0) FOR [MINHRS]
ALTER TABLE [dbo].[EDSETSTEMPLATE] ADD  CONSTRAINT [DF_EDSETSTEMPLATE_MAXHRS]  DEFAULT (40) FOR [MAXHRS]
ALTER TABLE [dbo].[EDSETSTEMPLATE] ADD  CONSTRAINT [DF_EDSETSTEMPLATE_LEDGERCODE]  DEFAULT ('') FOR [LEDGERCODE]
ALTER TABLE [dbo].[EDSETSTEMPLATE] ADD  CONSTRAINT [DF_EDSETSTEMPLATE_COMPANYFACTOR]  DEFAULT (0) FOR [COMPANYFACTOR]
ALTER TABLE [dbo].[EDSETSTEMPLATE] ADD  CONSTRAINT [DF_EDSETSTEMPLATE_ISWCA]  DEFAULT (0) FOR [ISWCA]
ALTER TABLE [dbo].[EDSETSTEMPLATE] ADD  CONSTRAINT [DF_EDSETSTEMPLATE_ISSTAMP]  DEFAULT (0) FOR [ISSTAMP]
ALTER TABLE [dbo].[EDSETSTEMPLATE] ADD  CONSTRAINT [DF_EDSETSTEMPLATE_EDSTYPE]  DEFAULT ('') FOR [EDSTYPE]
ALTER TABLE [dbo].[EDSETSTEMPLATE] ADD  CONSTRAINT [DF_EDSETSTEMPLATE_ISTAXABLE]  DEFAULT (100) FOR [TAXPERC]
ALTER TABLE [dbo].[EDSETSTEMPLATE] ADD  CONSTRAINT [DF_EDSETSTEMPLATE_ISTRIGGER]  DEFAULT ('') FOR [TRIG]
ALTER TABLE [dbo].[EDSETSTEMPLATE] ADD  CONSTRAINT [DF_EDSETSTEMPLATE_ISACCUMULATOR]  DEFAULT (0) FOR [EDTYPE]
ALTER TABLE [dbo].[EDSETSTEMPLATE] ADD  CONSTRAINT [DF_EDSETSTEMPLATE_PRINT_YTD]  DEFAULT (0) FOR [PRINTYTD]
ALTER TABLE [dbo].[EDSETSTEMPLATE] ADD  CONSTRAINT [DF_EDSETSTEMPLATE_LABELTYPE]  DEFAULT ('') FOR [EDSUSEAS]
ALTER TABLE [dbo].[EDSETSTEMPLATE] ADD  CONSTRAINT [DF_EDSETSTEMPLATE_ISEARNING]  DEFAULT (0) FOR [ISDEDUCTION]
ALTER TABLE [dbo].[EDSETSTEMPLATE] ADD  CONSTRAINT [DF_EDSETSTEMPLATE_EDSVALUE]  DEFAULT (0) FOR [EDSVALUE]
ALTER TABLE [dbo].[EDSETSTEMPLATE] ADD  CONSTRAINT [DF_EDSETSTEMPLATE_IRP5BLOCK_1]  DEFAULT ('') FOR [IRP5BLOCK]
ALTER TABLE [dbo].[EDSETSTEMPLATE] ADD  CONSTRAINT [DF_EDSETSTEMPLATE_DEDUCTBEFORETAXPERC]  DEFAULT (0) FOR [DEDUCTBEFORETAXPERC]
ALTER TABLE [dbo].[EDSETSTEMPLATE] ADD  CONSTRAINT [DF_EDSETSTEMPLATE_ISUIF]  DEFAULT (0) FOR [ISUIF]
ALTER TABLE [dbo].[EDSETSTEMPLATE] ADD  CONSTRAINT [DF_EDSETSTEMPLATE_ISRSC]  DEFAULT (0) FOR [ISRSC]
ALTER TABLE [dbo].[EDSETSTEMPLATE] ADD  CONSTRAINT [DF_EDSETSTEMPLATE_ISRFI]  DEFAULT (0) FOR [ISRFI]