/****** Object:  Table [dbo].[EDSETS]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[EDSETS](
	[EDSID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[EDSCODE] [nvarchar](5) NOT NULL,
	[EDSNUMBER] [nvarchar](5) NOT NULL,
	[EDSDESCR] [nvarchar](75) NOT NULL,
	[IRP5CODE] [nvarchar](5) NOT NULL,
	[SDL10] [bit] NOT NULL,
	[PAYROLLID] [int] NOT NULL,
	[EOYCLEAR] [bit] NOT NULL,
	[MINHRS] [decimal](18, 2) NOT NULL,
	[MAXHRS] [decimal](18, 2) NOT NULL,
	[LEDGERCODE] [char](10) NOT NULL,
	[COMPANYFACTOR] [decimal](18, 4) NOT NULL,
	[ISWCA] [bit] NOT NULL,
	[ISSTAMP] [bit] NOT NULL,
	[EDSTYPE] [nvarchar](2) NOT NULL,
	[TAXPERC] [decimal](18, 4) NOT NULL,
	[TRIG] [char](1) NOT NULL,
	[EDTYPE] [nvarchar](20) NOT NULL,
	[PRINTYTD] [bit] NOT NULL,
	[EDSUSEAS] [nvarchar](50) NOT NULL,
	[ISDEDUCTION] [bit] NOT NULL,
	[EDSHID] [int] NOT NULL,
	[EDSVALUE] [decimal](18, 5) NULL,
	[IRP5BLOCK] [nvarchar](5) NOT NULL,
	[DEDUCTBEFORETAXPERC] [decimal](18, 4) NOT NULL,
	[ISUIF] [bit] NOT NULL,
	[ISRSC] [bit] NOT NULL,
	[ISLUMP] [bit] NOT NULL,
	[RFINUMBER] [nvarchar](20) NOT NULL,
	[ISCOMMISSION] [bit] NOT NULL,
	[ISRFI] [bit] NOT NULL,
	[ISONPAYSLIP] [bit] NOT NULL,
	[ISUNION] [bit] NOT NULL,
	[USEIT] [bit] NOT NULL,
	[COSTIT] [bit] NOT NULL,
	[TCPCOMPONENT] [bit] NOT NULL,
	[DAILYALL] [bit] NOT NULL,
	[UAEPRLSHEETTYPE] [nvarchar](10) NOT NULL,
	[PTSLAB] [bit] NOT NULL,
	[ISEQUITY] [bit] NOT NULL,
	[AVRG3M] [bit] NOT NULL,
	[AVRG6M] [bit] NOT NULL,
	[AVRG12M] [bit] NOT NULL,
	[PROV2PAYOUTEDCODE] [nvarchar](5) NULL,
	[PRINTAACAPTONPSLP] [bit] NOT NULL,
	[UIFCALCONDIRECTIVE] [bit] NOT NULL,
	[SDLCALCONDIRECTIVE] [bit] NOT NULL,
	[PRINT0AMOUNTONPAYSLIP] [bit] NOT NULL,
	[AVRG2M] [bit] NOT NULL,
	[ISPROVISION] [bit] NOT NULL,
 CONSTRAINT [PK_EDSETS] PRIMARY KEY CLUSTERED 
(
	[EDSID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY],
 CONSTRAINT [IX_EDSETS_EDSCODE_PRLID_EDSHID] UNIQUE NONCLUSTERED 
(
	[EDSCODE] ASC,
	[PAYROLLID] ASC,
	[EDSHID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY],
 CONSTRAINT [IX_EDSETS_EDSNUMBER_PRLID_EDSHID] UNIQUE NONCLUSTERED 
(
	[EDSNUMBER] ASC,
	[PAYROLLID] ASC,
	[EDSHID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [IX_PAYROLLID_EDSHID_EDSNUMBER] ON [dbo].[EDSETS]
(
	[PAYROLLID] ASC,
	[EDSHID] ASC,
	[EDSNUMBER] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
ALTER TABLE [dbo].[EDSETS] ADD  CONSTRAINT [DF_EDSETS_EDSCODE]  DEFAULT ('') FOR [EDSCODE]
ALTER TABLE [dbo].[EDSETS] ADD  CONSTRAINT [DF_EDSETS_EDSNUMBER]  DEFAULT ('') FOR [EDSNUMBER]
ALTER TABLE [dbo].[EDSETS] ADD  CONSTRAINT [DF_EDSETS_EDSDESCR]  DEFAULT ('') FOR [EDSDESCR]
ALTER TABLE [dbo].[EDSETS] ADD  CONSTRAINT [DF_EDSETS_IRP5BLOCK]  DEFAULT ('') FOR [IRP5CODE]
ALTER TABLE [dbo].[EDSETS] ADD  CONSTRAINT [DF_EDSETS_SDL10]  DEFAULT (0) FOR [SDL10]
ALTER TABLE [dbo].[EDSETS] ADD  CONSTRAINT [DF_EDSETS_EOYCLEAR]  DEFAULT (0) FOR [EOYCLEAR]
ALTER TABLE [dbo].[EDSETS] ADD  CONSTRAINT [DF_EDSETS_MINHRS]  DEFAULT (0) FOR [MINHRS]
ALTER TABLE [dbo].[EDSETS] ADD  CONSTRAINT [DF_EDSETS_MAXHRS]  DEFAULT (40) FOR [MAXHRS]
ALTER TABLE [dbo].[EDSETS] ADD  CONSTRAINT [DF_EDSETS_LEDGERCODE]  DEFAULT ('') FOR [LEDGERCODE]
ALTER TABLE [dbo].[EDSETS] ADD  CONSTRAINT [DF_EDSETS_COMPANYFACTOR]  DEFAULT (0) FOR [COMPANYFACTOR]
ALTER TABLE [dbo].[EDSETS] ADD  CONSTRAINT [DF_EDSETS_ISWCA]  DEFAULT (0) FOR [ISWCA]
ALTER TABLE [dbo].[EDSETS] ADD  CONSTRAINT [DF_EDSETS_ISSTAMP]  DEFAULT (0) FOR [ISSTAMP]
ALTER TABLE [dbo].[EDSETS] ADD  CONSTRAINT [DF_EDSETS_EDSTYPE]  DEFAULT ('') FOR [EDSTYPE]
ALTER TABLE [dbo].[EDSETS] ADD  CONSTRAINT [DF_EDSETS_ISTAXABLE]  DEFAULT (100) FOR [TAXPERC]
ALTER TABLE [dbo].[EDSETS] ADD  CONSTRAINT [DF_EDSETS_ISTRIGGER]  DEFAULT ('') FOR [TRIG]
ALTER TABLE [dbo].[EDSETS] ADD  CONSTRAINT [DF_EDSETS_ISACCUMULATOR]  DEFAULT (0) FOR [EDTYPE]
ALTER TABLE [dbo].[EDSETS] ADD  CONSTRAINT [DF_EDSETS_PRINT_YTD]  DEFAULT (0) FOR [PRINTYTD]
ALTER TABLE [dbo].[EDSETS] ADD  CONSTRAINT [DF_EDSETS_LABELTYPE]  DEFAULT ('') FOR [EDSUSEAS]
ALTER TABLE [dbo].[EDSETS] ADD  CONSTRAINT [DF_EDSETS_ISEARNING]  DEFAULT (0) FOR [ISDEDUCTION]
ALTER TABLE [dbo].[EDSETS] ADD  CONSTRAINT [DF_EDSETS_EDSVALUE]  DEFAULT (0) FOR [EDSVALUE]
ALTER TABLE [dbo].[EDSETS] ADD  CONSTRAINT [DF_EDSETS_IRP5BLOCK_1]  DEFAULT ('') FOR [IRP5BLOCK]
ALTER TABLE [dbo].[EDSETS] ADD  CONSTRAINT [DF_EDSETS_DEDUCTBEFORETAXPERC]  DEFAULT (0) FOR [DEDUCTBEFORETAXPERC]
ALTER TABLE [dbo].[EDSETS] ADD  CONSTRAINT [DF_EDSETS_ISUIF]  DEFAULT (0) FOR [ISUIF]
ALTER TABLE [dbo].[EDSETS] ADD  CONSTRAINT [DF_EDSETS_ISRSC]  DEFAULT (0) FOR [ISRSC]
ALTER TABLE [dbo].[EDSETS] ADD  CONSTRAINT [DF_EDSETS_ISLUMP]  DEFAULT (0) FOR [ISLUMP]
ALTER TABLE [dbo].[EDSETS] ADD  CONSTRAINT [DF_EDSETS_RFINUMBER]  DEFAULT ('') FOR [RFINUMBER]
ALTER TABLE [dbo].[EDSETS] ADD  CONSTRAINT [DF_EDSETS_ISCOMMISSION]  DEFAULT (0) FOR [ISCOMMISSION]
ALTER TABLE [dbo].[EDSETS] ADD  CONSTRAINT [DF_EDSETS_ISRFI]  DEFAULT (0) FOR [ISRFI]
ALTER TABLE [dbo].[EDSETS] ADD  CONSTRAINT [DF__EDSETS__ISONPAYS__3AAEFDB5]  DEFAULT (1) FOR [ISONPAYSLIP]
ALTER TABLE [dbo].[EDSETS] ADD  CONSTRAINT [DF_EDSETS_ISUNION]  DEFAULT (0) FOR [ISUNION]
ALTER TABLE [dbo].[EDSETS] ADD  CONSTRAINT [DF_EDSETS_USEIT]  DEFAULT (0) FOR [USEIT]
ALTER TABLE [dbo].[EDSETS] ADD  CONSTRAINT [DF_EDSETS_COSTIT]  DEFAULT (1) FOR [COSTIT]
ALTER TABLE [dbo].[EDSETS] ADD  CONSTRAINT [DF_EDSETS_TCPCOMPONENT]  DEFAULT ((0)) FOR [TCPCOMPONENT]
ALTER TABLE [dbo].[EDSETS] ADD  CONSTRAINT [DF_EDSETS_DAILYALL]  DEFAULT ((0)) FOR [DAILYALL]
ALTER TABLE [dbo].[EDSETS] ADD  CONSTRAINT [DF_EDSETS_UAEPRLSHEETTYPE]  DEFAULT ('') FOR [UAEPRLSHEETTYPE]
ALTER TABLE [dbo].[EDSETS] ADD  DEFAULT ((1)) FOR [PTSLAB]
ALTER TABLE [dbo].[EDSETS] ADD  DEFAULT ((0)) FOR [ISEQUITY]
ALTER TABLE [dbo].[EDSETS] ADD  DEFAULT ((0)) FOR [AVRG3M]
ALTER TABLE [dbo].[EDSETS] ADD  DEFAULT ((0)) FOR [AVRG6M]
ALTER TABLE [dbo].[EDSETS] ADD  DEFAULT ((0)) FOR [AVRG12M]
ALTER TABLE [dbo].[EDSETS] ADD  DEFAULT ((0)) FOR [PRINTAACAPTONPSLP]
ALTER TABLE [dbo].[EDSETS] ADD  CONSTRAINT [DF_EDSETS_UIFCALCONDIRECTIVE]  DEFAULT ((0)) FOR [UIFCALCONDIRECTIVE]
ALTER TABLE [dbo].[EDSETS] ADD  CONSTRAINT [DF_EDSETS_SDLCALCONDIRECTIVE]  DEFAULT ((0)) FOR [SDLCALCONDIRECTIVE]
ALTER TABLE [dbo].[EDSETS] ADD  DEFAULT ((0)) FOR [PRINT0AMOUNTONPAYSLIP]
ALTER TABLE [dbo].[EDSETS] ADD  DEFAULT ((0)) FOR [AVRG2M]
ALTER TABLE [dbo].[EDSETS] ADD  DEFAULT ((0)) FOR [ISPROVISION]
ALTER TABLE [dbo].[EDSETS]  WITH CHECK ADD  CONSTRAINT [FK_EDSETS_EDSHEADER] FOREIGN KEY([EDSHID])
REFERENCES [dbo].[EDSHEADER] ([EDSHID])
ALTER TABLE [dbo].[EDSETS] CHECK CONSTRAINT [FK_EDSETS_EDSHEADER]
ALTER TABLE [dbo].[EDSETS]  WITH CHECK ADD  CONSTRAINT [FK_EDSETS_EDSUSAGE] FOREIGN KEY([EDSUSEAS])
REFERENCES [dbo].[EDSUSAGE] ([DESCR])
ALTER TABLE [dbo].[EDSETS] CHECK CONSTRAINT [FK_EDSETS_EDSUSAGE]
ALTER TABLE [dbo].[EDSETS]  WITH CHECK ADD  CONSTRAINT [FK_EDSETS_PAYROLLS] FOREIGN KEY([PAYROLLID])
REFERENCES [dbo].[PAYROLLS] ([PAYROLLID])
ALTER TABLE [dbo].[EDSETS] CHECK CONSTRAINT [FK_EDSETS_PAYROLLS]