/****** Object:  Table [dbo].[EDSHEADER]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[EDSHEADER](
	[EDSHID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[EDSHNAME] [nvarchar](50) NOT NULL,
	[PAYROLLID] [int] NOT NULL,
 CONSTRAINT [PK_EDSHEADER] PRIMARY KEY CLUSTERED 
(
	[EDSHID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[EDSHEADER] ADD  CONSTRAINT [DF_EDSHEADER_EDSHNAME]  DEFAULT ('') FOR [EDSHNAME]