/****** Object:  Table [dbo].[EDSIRP5CODES]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[EDSIRP5CODES](
	[IRP5CODE] [nvarchar](5) NOT NULL,
	[IRP5NAME] [nvarchar](255) NOT NULL,
	[DESCR] [nvarchar](255) NOT NULL,
	[SORTORD] [smallint] NOT NULL,
	[PRLSPEC] [nvarchar](30) NOT NULL,
 CONSTRAINT [PK_EDSIRP5CODES] PRIMARY KEY CLUSTERED 
(
	[IRP5CODE] ASC,
	[PRLSPEC] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[EDSIRP5CODES] ADD  CONSTRAINT [DF_EDSIRP5CODES_IRP5NAME]  DEFAULT ('') FOR [IRP5NAME]
ALTER TABLE [dbo].[EDSIRP5CODES] ADD  CONSTRAINT [DF_EDSIRP5CODES_DESCR]  DEFAULT ('') FOR [DESCR]
ALTER TABLE [dbo].[EDSIRP5CODES] ADD  CONSTRAINT [DF_EDSIRP5CODES_SORTORD]  DEFAULT (0) FOR [SORTORD]
ALTER TABLE [dbo].[EDSIRP5CODES] ADD  CONSTRAINT [DF_EDSIRP5CODES_PRLSPEC]  DEFAULT ('South Africa') FOR [PRLSPEC]