/****** Object:  Table [dbo].[EDSSTAMPS]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[EDSSTAMPS](
	[EDSNUMBER] [nvarchar](5) NOT NULL,
	[EDSCODE] [nvarchar](5) NOT NULL,
	[PAYROLLID] [int] NOT NULL,
	[STAMPVAL] [money] NOT NULL,
	[EDSHID] [int] NOT NULL,
	[STAMPCODE] [nvarchar](4) NOT NULL,
 CONSTRAINT [PK_EDSSTAMPS] PRIMARY KEY CLUSTERED 
(
	[EDSNUMBER] ASC,
	[PAYROLLID] ASC,
	[EDSHID] ASC,
	[STAMPCODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[EDSSTAMPS] ADD  CONSTRAINT [DF_EDSSTAMPS_STAMPVAL]  DEFAULT (0) FOR [STAMPVAL]
ALTER TABLE [dbo].[EDSSTAMPS]  WITH CHECK ADD  CONSTRAINT [FK_EDSSTAMPS_EDSETS] FOREIGN KEY([EDSNUMBER], [PAYROLLID], [EDSHID])
REFERENCES [dbo].[EDSETS] ([EDSNUMBER], [PAYROLLID], [EDSHID])
ALTER TABLE [dbo].[EDSSTAMPS] CHECK CONSTRAINT [FK_EDSSTAMPS_EDSETS]