/****** Object:  Table [dbo].[EDSTYPES]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[EDSTYPES](
	[TYPE] [nvarchar](2) NOT NULL,
	[CALCULATE] [nvarchar](2010) NOT NULL,
	[PAYROLLID] [int] NOT NULL,
	[TYPEDESCR] [nvarchar](125) NOT NULL,
	[NOTE] [nvarchar](2010) NULL,
 CONSTRAINT [PK_EDSTYPES] PRIMARY KEY CLUSTERED 
(
	[TYPE] ASC,
	[PAYROLLID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[EDSTYPES] ADD  CONSTRAINT [DF_EDSTYPES_CALCULATE]  DEFAULT ('') FOR [CALCULATE]
ALTER TABLE [dbo].[EDSTYPES] ADD  CONSTRAINT [DF_EDSTYPES_PAYROLLID]  DEFAULT (1) FOR [PAYROLLID]
ALTER TABLE [dbo].[EDSTYPES] ADD  CONSTRAINT [DF_EDSTYPES_TYPEDESCR]  DEFAULT ('') FOR [TYPEDESCR]
ALTER TABLE [dbo].[EDSTYPES] ADD  DEFAULT ('') FOR [NOTE]