/****** Object:  Table [dbo].[EFTFORMATHEADER]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[EFTFORMATHEADER](
	[EHID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[NAME] [nvarchar](255) NOT NULL,
	[TYPE] [nvarchar](5) NOT NULL,
	[SEPERATOR] [nvarchar](5) NOT NULL,
	[FILENAME] [nvarchar](55) NOT NULL,
	[HASHTOTAL] [nvarchar](max) NULL,
 CONSTRAINT [PK_EFTFORMATHEADER] PRIMARY KEY CLUSTERED 
(
	[EHID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

ALTER TABLE [dbo].[EFTFORMATHEADER] ADD  CONSTRAINT [DF_EFTFORMATHEADER_NAME]  DEFAULT ('') FOR [NAME]
ALTER TABLE [dbo].[EFTFORMATHEADER] ADD  CONSTRAINT [DF_EFTFORMATHEADER_TYPE]  DEFAULT ('') FOR [TYPE]
ALTER TABLE [dbo].[EFTFORMATHEADER] ADD  CONSTRAINT [DF_EFTFORMATHEADER_SEPERATOR]  DEFAULT ('') FOR [SEPERATOR]
ALTER TABLE [dbo].[EFTFORMATHEADER] ADD  CONSTRAINT [DF_EFTFORMATHEADER_FILENAME]  DEFAULT ('') FOR [FILENAME]