/****** Object:  Table [dbo].[EMBATCHHEADER]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[EMBATCHHEADER](
	[HEADERID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[REFERENCE] [char](50) NOT NULL,
	[BATCHREF] [char](50) NOT NULL,
	[PAYROLLID] [int] NOT NULL,
	[LOCKHOLDER] [int] NOT NULL,
	[LOCKREQUESTOR] [int] NOT NULL,
	[VALID] [bit] NOT NULL,
	[POSTED] [bit] NOT NULL,
	[USEEMPNUMBER] [bit] NOT NULL,
	[USEEMPNAME] [bit] NOT NULL,
	[USEBIRTHDAY] [bit] NOT NULL,
	[USEBANKACCOUNT] [bit] NOT NULL,
	[USEBANKBRANCHCODE] [bit] NOT NULL,
	[USEIDNUM] [bit] NOT NULL,
	[USEDEPENDENTS] [bit] NOT NULL,
	[USESTARTDATE] [bit] NOT NULL,
	[USETYPEPAYMENT] [bit] NOT NULL,
	[USEPAYBY] [bit] NOT NULL,
	[USERATE1] [bit] NOT NULL,
	[USELDTOTALYEAR] [bit] NOT NULL,
	[USESDTOTAL] [bit] NOT NULL,
	[USEEDSHID] [bit] NOT NULL,
	[USEPREVNUMBER] [bit] NOT NULL,
	[USESURNAME] [bit] NOT NULL,
	[USEKNOWNAS] [bit] NOT NULL,
	[USEINITIALS] [bit] NOT NULL,
	[USESEX] [bit] NOT NULL,
	[USERACE] [bit] NOT NULL,
	[USEMARITALSTATUS] [bit] NOT NULL,
	[USENATURE] [bit] NOT NULL,
	[USETEL1] [bit] NOT NULL,
	[USECELL1] [bit] NOT NULL,
	[USEEMAIL] [bit] NOT NULL,
	[USEADDR1] [bit] NOT NULL,
	[USEADDR2] [bit] NOT NULL,
	[USEADDR3] [bit] NOT NULL,
	[USEPCODE] [bit] NOT NULL,
	[USEBANKACCTYPE] [bit] NOT NULL,
	[USEBANKBRANCHNAME] [bit] NOT NULL,
	[USESTANDARDBANK_PROFILE] [bit] NOT NULL,
	[USEPASSPORTNO] [bit] NOT NULL,
	[USEHFNUMBER] [bit] NOT NULL,
	[USECHILDREN] [bit] NOT NULL,
	[USESPOUSENAME] [bit] NOT NULL,
	[USESPOUSEADDR] [bit] NOT NULL,
	[USESPOUSETEL] [bit] NOT NULL,
	[USESPOUSECELL] [bit] NOT NULL,
	[USEEMPDISABILITY] [bit] NOT NULL,
	[USEMDCLNAME] [bit] NOT NULL,
	[USEMDCLNUMBER] [bit] NOT NULL,
	[USEPENSPROVNUMBER] [bit] NOT NULL,
	[USEGRSTARTDATE] [bit] NOT NULL,
	[USEPENDATE] [bit] NOT NULL,
	[USEPAYPOINT] [bit] NOT NULL,
	[USEOCCUPATION] [bit] NOT NULL,
	[USEEMPOCCCAT] [bit] NOT NULL,
	[USEEMPOCCLEVEL] [bit] NOT NULL,
	[USEEQMOVE] [bit] NOT NULL,
	[USEJOBCODE] [bit] NOT NULL,
	[USEGRADE] [bit] NOT NULL,
	[USEISFOREMAN] [bit] NOT NULL,
	[USEFOREMANNUM] [bit] NOT NULL,
	[USEFOREMANPRLID] [bit] NOT NULL,
	[USERATE2] [bit] NOT NULL,
	[USERATE3] [bit] NOT NULL,
	[USETRAVELRATE] [bit] NOT NULL,
	[USEDIRECTIVENO] [bit] NOT NULL,
	[USEDIRECTIVEPERC] [bit] NOT NULL,
	[USESSCODE] [bit] NOT NULL,
	[USESSCATEGORY] [bit] NOT NULL,
	[USEPRLSTAMP] [bit] NOT NULL,
	[USETAXNUMBER] [bit] NOT NULL,
	[USEIT3REASONCODE] [bit] NOT NULL,
	[USETAXALLOC] [bit] NOT NULL,
	[USEWCATYPE] [bit] NOT NULL,
	[USEUIFREASONCODE] [bit] NOT NULL,
	[USESTDHRSPAYPER] [bit] NOT NULL,
	[USEDEBTNUMBER] [bit] NOT NULL,
	[USECONTRACTEXPDATE] [bit] NOT NULL,
	[USENOTES] [bit] NOT NULL,
	[USEEMPUNION] [bit] NOT NULL,
	[EDSHID] [int] NULL,
	[USEEMPLOYLEVEL] [bit] NOT NULL,
	[USEFILENO] [bit] NOT NULL,
	[USECOUNTRYORG] [bit] NOT NULL,
	[USEPENSIONSTARTDATE] [bit] NOT NULL,
	[USEMEDICALSTARTDATE] [bit] NOT NULL,
	[USECOSTTOCOMP] [bit] NOT NULL,
	[USEBONUS] [bit] NOT NULL,
	[USEIPBENEFICIARY] [bit] NOT NULL,
	[USEIPADDR1] [bit] NOT NULL,
	[USEIPADDR2] [bit] NOT NULL,
	[USEIPADDR3] [bit] NOT NULL,
	[USEIPBANKACCOUNT] [bit] NOT NULL,
	[USEIPBANKNAME] [bit] NOT NULL,
	[USEIPBANKADDR1] [bit] NOT NULL,
	[USEIPBANKADDR2] [bit] NOT NULL,
	[USEIPBANKADDR3] [bit] NOT NULL,
	[USEIPBRANCHNAME] [bit] NOT NULL,
	[USEIPBANKTEL1] [bit] NOT NULL,
	[USEIPBANKTEL2] [bit] NOT NULL,
	[USEIPSWIFT] [bit] NOT NULL,
	[USEIPSORT] [bit] NOT NULL,
	[USEIPABA] [bit] NOT NULL,
	[USEIPIBAN] [bit] NOT NULL,
	[USEIPCORRESPONDENTBANKNAME] [bit] NOT NULL,
	[USEIPCORRESPONDENTABA] [bit] NOT NULL,
	[USEIPINFO] [bit] NOT NULL,
	[USETNALEDGERCODECONTRACT] [bit] NOT NULL,
	[USETNALEDGERCODEPLANT] [bit] NOT NULL,
	[USETNALEDGERCODEBS] [bit] NOT NULL,
	[USETNALEDGERCODEOH] [bit] NOT NULL,
 CONSTRAINT [PK_EMBATCHHEADER] PRIMARY KEY CLUSTERED 
(
	[HEADERID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_LockHolder]  DEFAULT ((0)) FOR [LOCKHOLDER]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_LockRequestor]  DEFAULT ((0)) FOR [LOCKREQUESTOR]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_VALID]  DEFAULT ((0)) FOR [VALID]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_POSTED]  DEFAULT ((0)) FOR [POSTED]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_use]  DEFAULT ((1)) FOR [USEEMPNUMBER]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_useEmpName]  DEFAULT ((1)) FOR [USEEMPNAME]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_useBirthday]  DEFAULT ((1)) FOR [USEBIRTHDAY]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_useBankAccount]  DEFAULT ((1)) FOR [USEBANKACCOUNT]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_useBankBranchCode]  DEFAULT ((1)) FOR [USEBANKBRANCHCODE]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_USEIDNUM]  DEFAULT ((1)) FOR [USEIDNUM]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_USEDEPENDENTS]  DEFAULT ((1)) FOR [USEDEPENDENTS]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_USESTARTDATE]  DEFAULT ((1)) FOR [USESTARTDATE]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_USETYPEPAYMENT]  DEFAULT ((1)) FOR [USETYPEPAYMENT]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_USEPAYBY]  DEFAULT ((1)) FOR [USEPAYBY]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_USERATE1]  DEFAULT ((1)) FOR [USERATE1]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_USELDTOTALYEAR]  DEFAULT ((1)) FOR [USELDTOTALYEAR]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_USESDTOTAL]  DEFAULT ((1)) FOR [USESDTOTAL]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_USEEDSHID]  DEFAULT ((1)) FOR [USEEDSHID]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_USEPREVNUMBER]  DEFAULT ((0)) FOR [USEPREVNUMBER]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_USESURNAME]  DEFAULT ((0)) FOR [USESURNAME]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_USEKNOWNAS]  DEFAULT ((0)) FOR [USEKNOWNAS]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_USEINITIALS]  DEFAULT ((0)) FOR [USEINITIALS]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_USESEX]  DEFAULT ((0)) FOR [USESEX]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_USERACE]  DEFAULT ((0)) FOR [USERACE]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_USEMARITALSTATUS]  DEFAULT ((0)) FOR [USEMARITALSTATUS]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_USENATURE]  DEFAULT ((0)) FOR [USENATURE]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_USETEL1]  DEFAULT ((0)) FOR [USETEL1]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_USECELL1]  DEFAULT ((0)) FOR [USECELL1]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_USEEMAIL]  DEFAULT ((0)) FOR [USEEMAIL]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_USEADDR1]  DEFAULT ((0)) FOR [USEADDR1]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_USEADDR2]  DEFAULT ((0)) FOR [USEADDR2]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_USEADDR3]  DEFAULT ((0)) FOR [USEADDR3]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_USEPCODE]  DEFAULT ((0)) FOR [USEPCODE]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_USEBANKACCTYPE]  DEFAULT ((0)) FOR [USEBANKACCTYPE]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_USEBANKBRANCHNAME]  DEFAULT ((0)) FOR [USEBANKBRANCHNAME]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_USESTANDARDBANK_PROFILE]  DEFAULT ((0)) FOR [USESTANDARDBANK_PROFILE]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_USEPASSPORTNO]  DEFAULT ((0)) FOR [USEPASSPORTNO]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_USEHFNUMBER]  DEFAULT ((0)) FOR [USEHFNUMBER]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_USECHILDREN]  DEFAULT ((0)) FOR [USECHILDREN]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_USESPOUSENAME]  DEFAULT ((0)) FOR [USESPOUSENAME]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_USESPOUSEADDR]  DEFAULT ((0)) FOR [USESPOUSEADDR]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_USESPOUSETEL]  DEFAULT ((0)) FOR [USESPOUSETEL]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_USESPOUSECELL]  DEFAULT ((0)) FOR [USESPOUSECELL]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_USEEMPDISABILITY]  DEFAULT ((0)) FOR [USEEMPDISABILITY]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_USEMDCLNAME]  DEFAULT ((0)) FOR [USEMDCLNAME]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_USEMDCLNUMBER]  DEFAULT ((0)) FOR [USEMDCLNUMBER]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_USEPENSPROVNUMBER]  DEFAULT ((0)) FOR [USEPENSPROVNUMBER]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_USEGRSTARTDATE]  DEFAULT ((0)) FOR [USEGRSTARTDATE]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_USEPENDATE]  DEFAULT ((0)) FOR [USEPENDATE]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_USEPAYPOINT]  DEFAULT ((0)) FOR [USEPAYPOINT]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_USEOCCUPATION]  DEFAULT ((0)) FOR [USEOCCUPATION]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_USEEMPOCCCAT]  DEFAULT ((0)) FOR [USEEMPOCCCAT]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_USEEMPOCCLEVEL]  DEFAULT ((0)) FOR [USEEMPOCCLEVEL]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_USEEQMOVE]  DEFAULT ((0)) FOR [USEEQMOVE]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_USEJOBCODE]  DEFAULT ((0)) FOR [USEJOBCODE]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_USEGRADE]  DEFAULT ((0)) FOR [USEGRADE]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_USEISFOREMAN]  DEFAULT ((0)) FOR [USEISFOREMAN]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_USEFOREMANNUM]  DEFAULT ((0)) FOR [USEFOREMANNUM]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_USEFOREMANPRLID]  DEFAULT ((0)) FOR [USEFOREMANPRLID]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_USERATE2]  DEFAULT ((0)) FOR [USERATE2]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_USERATE3]  DEFAULT ((0)) FOR [USERATE3]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_USETRAVELRATE]  DEFAULT ((0)) FOR [USETRAVELRATE]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_USEDIRECTIVENO]  DEFAULT ((0)) FOR [USEDIRECTIVENO]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_USEDIRECTIVEPERC]  DEFAULT ((0)) FOR [USEDIRECTIVEPERC]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_USESSCODE]  DEFAULT ((0)) FOR [USESSCODE]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_USESSCATEGORY]  DEFAULT ((0)) FOR [USESSCATEGORY]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_USEPRLSTAMP]  DEFAULT ((0)) FOR [USEPRLSTAMP]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_USETAXNUMBER]  DEFAULT ((0)) FOR [USETAXNUMBER]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_USEIT3REASONCODE]  DEFAULT ((0)) FOR [USEIT3REASONCODE]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_USETAXALLOC]  DEFAULT ((0)) FOR [USETAXALLOC]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_USEWCATYPE]  DEFAULT ((0)) FOR [USEWCATYPE]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_USEUIFREASONCODE]  DEFAULT ((0)) FOR [USEUIFREASONCODE]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_USESTDHRSPAYPER]  DEFAULT ((0)) FOR [USESTDHRSPAYPER]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_USEDEBTNUMBER]  DEFAULT ((0)) FOR [USEDEBTNUMBER]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_USECONTRACTEXPDATE]  DEFAULT ((0)) FOR [USECONTRACTEXPDATE]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_USENOTES]  DEFAULT ((0)) FOR [USENOTES]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_USEEMPUNION]  DEFAULT ((0)) FOR [USEEMPUNION]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_USEEMPLOYLEVEL]  DEFAULT ((0)) FOR [USEEMPLOYLEVEL]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_USEFILENO]  DEFAULT ((0)) FOR [USEFILENO]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_USECOUNTRYORG]  DEFAULT ((0)) FOR [USECOUNTRYORG]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_USEPENSIONSTARTDATE]  DEFAULT ((0)) FOR [USEPENSIONSTARTDATE]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_USEMEDICALSTARTDATE]  DEFAULT ((0)) FOR [USEMEDICALSTARTDATE]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_USECOSTTOCOMP]  DEFAULT ((0)) FOR [USECOSTTOCOMP]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_USEBONUS]  DEFAULT ((0)) FOR [USEBONUS]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_USEIPBENEFICIARY]  DEFAULT ((0)) FOR [USEIPBENEFICIARY]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_USEIPADDR1]  DEFAULT ((0)) FOR [USEIPADDR1]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_USEIPADDR2]  DEFAULT ((0)) FOR [USEIPADDR2]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_USEIPADDR3]  DEFAULT ((0)) FOR [USEIPADDR3]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_USEIPBANKACCOUNT]  DEFAULT ((0)) FOR [USEIPBANKACCOUNT]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_USEIPBANKNAME]  DEFAULT ((0)) FOR [USEIPBANKNAME]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_USEIPBANKADDR1]  DEFAULT ((0)) FOR [USEIPBANKADDR1]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_USEIPBANKADDR2]  DEFAULT ((0)) FOR [USEIPBANKADDR2]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_USEIPBANKADDR3]  DEFAULT ((0)) FOR [USEIPBANKADDR3]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_USEIPBRANCHNAME]  DEFAULT ((0)) FOR [USEIPBRANCHNAME]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_USEIPBANKTEL1]  DEFAULT ((0)) FOR [USEIPBANKTEL1]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_USEIPBANKTEL2]  DEFAULT ((0)) FOR [USEIPBANKTEL2]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_USEIPSWIFT]  DEFAULT ((0)) FOR [USEIPSWIFT]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_USEIPSORT]  DEFAULT ((0)) FOR [USEIPSORT]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_USEIPABA]  DEFAULT ((0)) FOR [USEIPABA]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_USEIPIBAN]  DEFAULT ((0)) FOR [USEIPIBAN]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_USEIPCORRESPONDENTBANKNAME]  DEFAULT ((0)) FOR [USEIPCORRESPONDENTBANKNAME]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_USEIPCORRESPONDENTABA]  DEFAULT ((0)) FOR [USEIPCORRESPONDENTABA]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_USEIPINFO]  DEFAULT ((0)) FOR [USEIPINFO]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_USETNALEDGERCODECONTRACT]  DEFAULT ((0)) FOR [USETNALEDGERCODECONTRACT]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_USETNALEDGERCODEPLANT]  DEFAULT ((0)) FOR [USETNALEDGERCODEPLANT]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_USETNALEDGERCODEBS]  DEFAULT ((0)) FOR [USETNALEDGERCODEBS]
ALTER TABLE [dbo].[EMBATCHHEADER] ADD  CONSTRAINT [DF_EMBATCHHEADER_USETNALEDGERCODEOH]  DEFAULT ((0)) FOR [USETNALEDGERCODEOH]