/****** Object:  Table [dbo].[EMPABSENTEEISM]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[EMPABSENTEEISM](
	[PAYROLLID] [int] NOT NULL,
	[EMPNUMBER] [nvarchar](15) NOT NULL,
	[PERIODNO] [int] NOT NULL,
	[YEARNO] [int] NOT NULL,
	[DNO] [decimal](18, 2) NOT NULL,
	[FROMDATE] [datetime] NOT NULL,
	[TODATE] [datetime] NOT NULL,
	[RECTYPE] [nvarchar](2) NOT NULL,
	[RUNNO] [int] NOT NULL,
 CONSTRAINT [PK_EMPABSENTEEISM] PRIMARY KEY CLUSTERED 
(
	[PAYROLLID] ASC,
	[EMPNUMBER] ASC,
	[PERIODNO] ASC,
	[YEARNO] ASC,
	[FROMDATE] ASC,
	[TODATE] ASC,
	[RECTYPE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[EMPABSENTEEISM] ADD  CONSTRAINT [DF_EMPABSENTEEISM_RUNNO]  DEFAULT ((1)) FOR [RUNNO]