/****** Object:  Table [dbo].[EMPBANKDETAILSHISTORY]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[EMPBANKDETAILSHISTORY](
	[pklBankDetailsID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[ACCOUNTHOLDERNAME] [nvarchar](250) NULL,
	[ACCOUNTHOLDERRELATIONSHIP] [nvarchar](50) NULL,
	[PAYBY] [nvarchar](50) NULL,
	[BANKACCOUNT] [nvarchar](50) NULL,
	[BANKACCTYPE] [nvarchar](150) NULL,
	[BANKBRANCHCODE] [nvarchar](50) NULL,
	[BANKBRANCHNAME] [nvarchar](250) NULL,
	[AuditDate] [datetime] NOT NULL,
	[ACTIONDATE] [datetime] NULL,
	[PAYROLLID] [int] NULL,
	[EMPNUMBER] [nvarchar](30) NULL,
 CONSTRAINT [PK_EMPBANKDETAILSHISTORY] PRIMARY KEY CLUSTERED 
(
	[pklBankDetailsID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[EMPBANKDETAILSHISTORY] ADD  CONSTRAINT [DF_EMPBANKDETAILSHISTORY_AuditDate]  DEFAULT (getdate()) FOR [AuditDate]