/****** Object:  Table [dbo].[EMPEMPLOYMENTHISTORY]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[EMPEMPLOYMENTHISTORY](
	[pklEmploymentHistoryID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[EMPNUMBER] [nvarchar](50) NOT NULL,
	[STATUSCODE] [nvarchar](50) NOT NULL,
	[GRSTARTDATE] [datetime] NULL,
	[EMPSTATUS] [nvarchar](50) NOT NULL,
	[GRADE] [nvarchar](50) NULL,
	[EMPOCCCAT] [nvarchar](150) NULL,
	[TOBETERMDATE] [datetime] NULL,
	[STARTDATE] [datetime] NOT NULL,
	[OCCUPATION] [nvarchar](150) NULL,
	[RATE1] [decimal](18, 4) NOT NULL,
	[TYPEPAYMENT] [nvarchar](150) NOT NULL,
	[TAXALLOC] [nvarchar](150) NOT NULL,
	[AuditDate] [datetime] NOT NULL,
	[ACTIONDATE] [datetime] NULL,
	[PAYROLLID] [int] NULL,
 CONSTRAINT [PK_EMPEMPLOYMENTHISTORY] PRIMARY KEY CLUSTERED 
(
	[pklEmploymentHistoryID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[EMPEMPLOYMENTHISTORY] ADD  CONSTRAINT [DF_EMPEMPLOYMENTHISTORY_AuditDate]  DEFAULT (getdate()) FOR [AuditDate]