/****** Object:  Table [dbo].[EMPEDACCUM]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[EMPEDACCUM](
	[PRLID] [int] NOT NULL,
	[EMPNUMBER] [nvarchar](15) NOT NULL,
	[EDSNUMBER] [nvarchar](5) NOT NULL,
	[EDSCODE] [nvarchar](5) NOT NULL,
	[THEMONEY] [money] NOT NULL,
	[EDSHID] [int] NOT NULL,
	[EMPEDAID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[YEARNO] [smallint] NOT NULL,
	[PERIODNO] [smallint] NOT NULL,
	[RUNNO] [smallint] NOT NULL,
	[MONEYTAXABLE] [money] NOT NULL,
 CONSTRAINT [PK_EMPEDACCUM] PRIMARY KEY CLUSTERED 
(
	[EMPEDAID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[EMPEDACCUM] ADD  CONSTRAINT [DF_EMPEDACCUM_MONEYTAXABLE]  DEFAULT (0) FOR [MONEYTAXABLE]
ALTER TABLE [dbo].[EMPEDACCUM]  WITH CHECK ADD  CONSTRAINT [FK_EMPEDACCUM_EDSETS] FOREIGN KEY([EDSNUMBER], [PRLID], [EDSHID])
REFERENCES [dbo].[EDSETS] ([EDSNUMBER], [PAYROLLID], [EDSHID])
ALTER TABLE [dbo].[EMPEDACCUM] CHECK CONSTRAINT [FK_EMPEDACCUM_EDSETS]