/****** Object:  Table [dbo].[EMPFUNDHEADER]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[EMPFUNDHEADER](
	[FUNDHID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[FUNDNAME] [nvarchar](50) NOT NULL,
	[PAYROLLID] [int] NULL,
	[FUND1ECACTEDSNUMBER] [nvarchar](5) NULL,
	[FUND1ECACTEDSCODE] [nvarchar](5) NULL,
	[FUND1ECCALCEDSNUMBER] [nvarchar](5) NULL,
	[FUND1ECCALCEDSCODE] [nvarchar](5) NULL,
	[FUND1CCACTEDSNUMBER] [nvarchar](5) NULL,
	[FUND1CCACTEDSCODE] [nvarchar](5) NULL,
	[FUND1CCCALCEDSNUMBER] [nvarchar](5) NULL,
	[FUND1CCCALCEDSCODE] [nvarchar](5) NULL,
	[FUND1DEATHACTEDSNUMBER] [nvarchar](5) NULL,
	[FUND1DEATHACTEDSCODE] [nvarchar](5) NULL,
	[FUND1DEATHCALCEDSNUMBER] [nvarchar](5) NULL,
	[FUND1DEATHCALCEDSCODE] [nvarchar](5) NULL,
	[FUND1DISACTEDSNUMBER] [nvarchar](5) NULL,
	[FUND1DISACTEDSCODE] [nvarchar](5) NULL,
	[FUND1DISCALCEDSNUMBER] [nvarchar](5) NULL,
	[FUND1DISCALCEDSCODE] [nvarchar](5) NULL,
	[FUND1EADDEDSNUMBER] [nvarchar](5) NULL,
	[FUND1EADDEDSCODE] [nvarchar](5) NULL,
	[FUND1CADDEDSNUMBER] [nvarchar](5) NULL,
	[FUND1CADDEDSCODE] [nvarchar](5) NULL,
 CONSTRAINT [PK_EMPFUNDHEADER] PRIMARY KEY CLUSTERED 
(
	[FUNDHID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[EMPFUNDHEADER]  WITH CHECK ADD  CONSTRAINT [FK_EMPFUNDHEADER_PAYROLLS] FOREIGN KEY([PAYROLLID])
REFERENCES [dbo].[PAYROLLS] ([PAYROLLID])
ALTER TABLE [dbo].[EMPFUNDHEADER] CHECK CONSTRAINT [FK_EMPFUNDHEADER_PAYROLLS]