/****** Object:  Table [dbo].[EMPFUND]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[EMPFUND](
	[FUNDID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[FUNDHID] [int] NOT NULL,
	[PAYROLLID] [int] NOT NULL,
	[EMPNUMBER] [nvarchar](15) NOT NULL,
	[ADJCODE] [nvarchar](3) NULL,
	[EDSNUMBER] [nvarchar](5) NOT NULL,
	[EDSCODE] [nvarchar](5) NOT NULL,
 CONSTRAINT [PK_EMPFUND] PRIMARY KEY CLUSTERED 
(
	[FUNDID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[EMPFUND]  WITH CHECK ADD  CONSTRAINT [FK_EMPFUND_EMPFUNDHEADER] FOREIGN KEY([FUNDHID])
REFERENCES [dbo].[EMPFUNDHEADER] ([FUNDHID])
ALTER TABLE [dbo].[EMPFUND] CHECK CONSTRAINT [FK_EMPFUND_EMPFUNDHEADER]