/****** Object:  Table [dbo].[EMPGARNPAY]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[EMPGARNPAY](
	[PAYROLLID] [int] NOT NULL,
	[EMPNUMBER] [nvarchar](15) NOT NULL,
	[GARNID] [int] NOT NULL,
	[PAYMENT] [money] NOT NULL,
	[PAYDATE] [datetime] NOT NULL,
	[PERIODNO] [smallint] NOT NULL,
	[RUNNO] [smallint] NOT NULL,
	[YEARNO] [smallint] NOT NULL,
	[GARNPAYID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[HANDFEEAMOUNT] [money] NOT NULL,
 CONSTRAINT [PK_EMPGARNPAY] PRIMARY KEY CLUSTERED 
(
	[PAYROLLID] ASC,
	[EMPNUMBER] ASC,
	[GARNID] ASC,
	[PERIODNO] ASC,
	[RUNNO] ASC,
	[YEARNO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[EMPGARNPAY] ADD  CONSTRAINT [DF_EMPGARNPAY_PAYDATE]  DEFAULT (getdate()) FOR [PAYDATE]
ALTER TABLE [dbo].[EMPGARNPAY] ADD  CONSTRAINT [DF_EMPGARNPAY_HANDFEEAMOUNT]  DEFAULT (0) FOR [HANDFEEAMOUNT]