/****** Object:  Table [dbo].[EMPGARN]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[EMPGARN](
	[PAYROLLID] [int] NOT NULL,
	[EMPNUMBER] [nvarchar](15) NOT NULL,
	[AMOUNT] [money] NOT NULL,
	[DEDUAMOUNT] [money] NOT NULL,
	[GARNID] [int] IDENTITY(1,1) NOT NULL,
	[GARNDATE] [datetime] NOT NULL,
	[EDSHID] [int] NOT NULL,
	[HANDFEE] [decimal](18, 2) NOT NULL,
	[EDSID] [int] NOT NULL,
	[EMPGARNREFNO] [nvarchar](20) NOT NULL,
	[GRREFNO] [nvarchar](10) NOT NULL,
	[ISACTIVE] [bit] NOT NULL,
	[EDSNUMBER] [nvarchar](5) NOT NULL,
 CONSTRAINT [IX_EMPGARN] UNIQUE NONCLUSTERED 
(
	[PAYROLLID] ASC,
	[EMPNUMBER] ASC,
	[GARNID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY],
 CONSTRAINT [IX_EMPGARN_GARNID] UNIQUE NONCLUSTERED 
(
	[GARNID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[EMPGARN] ADD  CONSTRAINT [DF_EMPGARN_GARNDATE]  DEFAULT (getdate()) FOR [GARNDATE]
ALTER TABLE [dbo].[EMPGARN] ADD  CONSTRAINT [DF__EMPGARN__ISACTIV__233F2673]  DEFAULT (1) FOR [ISACTIVE]
ALTER TABLE [dbo].[EMPGARN] ADD  CONSTRAINT [DF_EMPGARN_EDSNUMBER]  DEFAULT ('') FOR [EDSNUMBER]
ALTER TABLE [dbo].[EMPGARN]  WITH CHECK ADD  CONSTRAINT [FK_EMPGARN_GARNGROUPS] FOREIGN KEY([GRREFNO])
REFERENCES [dbo].[GARNGROUPS] ([REFNO])
ALTER TABLE [dbo].[EMPGARN] CHECK CONSTRAINT [FK_EMPGARN_GARNGROUPS]