/****** Object:  Table [dbo].[EMPLOYEESSDL]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[EMPLOYEESSDL](
	[PRLNUMBER] [nvarchar](10) NOT NULL,
	[PERIODNO] [smallint] NOT NULL,
	[YEARNO] [smallint] NOT NULL,
	[RUNNO] [smallint] NOT NULL,
	[EMPNUMBER] [nvarchar](15) NOT NULL,
	[SDLAMOUNT] [money] NOT NULL,
	[PRLID] [int] NOT NULL,
	[EXCLUDED] [money] NOT NULL,
	[REMUNERATION] [money] NOT NULL,
 CONSTRAINT [PK_EMPLOYEESSDL] PRIMARY KEY CLUSTERED 
(
	[PRLNUMBER] ASC,
	[PERIODNO] ASC,
	[YEARNO] ASC,
	[RUNNO] ASC,
	[EMPNUMBER] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [IX_EMPLOYEESSDL_PERIODNO_YEARNO_RUNNO_EMPNUMBER_PRLID] ON [dbo].[EMPLOYEESSDL]
(
	[PERIODNO] ASC,
	[YEARNO] ASC,
	[RUNNO] ASC,
	[EMPNUMBER] ASC,
	[PRLID] ASC
)
INCLUDE([SDLAMOUNT]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
ALTER TABLE [dbo].[EMPLOYEESSDL] ADD  CONSTRAINT [DF_EMPLOYEESSDL_SDLAMOUNT]  DEFAULT (0) FOR [SDLAMOUNT]
ALTER TABLE [dbo].[EMPLOYEESSDL] ADD  CONSTRAINT [DF_EMPLOYEESSDL_PRLID]  DEFAULT (1) FOR [PRLID]
ALTER TABLE [dbo].[EMPLOYEESSDL] ADD  CONSTRAINT [DF_EMPLOYEESSDL_EXCLUSIONS]  DEFAULT (0) FOR [EXCLUDED]
ALTER TABLE [dbo].[EMPLOYEESSDL] ADD  CONSTRAINT [DF_EMPLOYEESSDL_REMUNERATION]  DEFAULT (0) FOR [REMUNERATION]
ALTER TABLE [dbo].[EMPLOYEESSDL]  WITH CHECK ADD  CONSTRAINT [FK_EMPLOYEESSDL_EMPLOYEES] FOREIGN KEY([PRLID], [EMPNUMBER])
REFERENCES [dbo].[EMPLOYEES] ([PAYROLLID], [EMPNUMBER])
ALTER TABLE [dbo].[EMPLOYEESSDL] CHECK CONSTRAINT [FK_EMPLOYEESSDL_EMPLOYEES]
ALTER TABLE [dbo].[EMPLOYEESSDL]  WITH CHECK ADD  CONSTRAINT [FK_EMPLOYEESSDL_PAYROLLS] FOREIGN KEY([PRLNUMBER])
REFERENCES [dbo].[PAYROLLS] ([PRLNUMBER])
ALTER TABLE [dbo].[EMPLOYEESSDL] CHECK CONSTRAINT [FK_EMPLOYEESSDL_PAYROLLS]