/****** Object:  Table [dbo].[EMPLOYEES]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[EMPLOYEES](
	[PAYROLLID] [int] NOT NULL,
	[EMPID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[EMPNUMBER] [nvarchar](15) NOT NULL,
	[EMPNAME] [nvarchar](75) NOT NULL,
	[KNOWNAS] [nvarchar](25) NOT NULL,
	[PAYPOINT] [nvarchar](15) NOT NULL,
	[TERMDATE] [datetime] NULL,
	[SEX] [nvarchar](6) NOT NULL,
	[SPOUSENAME] [nvarchar](75) NOT NULL,
	[SPOUSEADDR] [nvarchar](75) NOT NULL,
	[SPOUSETEL] [nvarchar](15) NOT NULL,
	[SPOUSECELL] [nvarchar](15) NOT NULL,
	[DEPDIV] [int] NOT NULL,
	[RACE] [nvarchar](10) NOT NULL,
	[MARITALSTATUS] [nvarchar](10) NOT NULL,
	[BIRTHDAY] [datetime] NOT NULL,
	[STARTDATE] [datetime] NOT NULL,
	[TEL1] [nvarchar](15) NOT NULL,
	[TEL2] [nvarchar](15) NOT NULL,
	[CELL1] [nvarchar](15) NOT NULL,
	[CELL2] [nvarchar](15) NOT NULL,
	[EMAIL] [nvarchar](50) NOT NULL,
	[TAXNUMBER] [nvarchar](20) NOT NULL,
	[BANKACCOUNT] [nvarchar](30) NOT NULL,
	[BANKACCTYPE] [nvarchar](20) NOT NULL,
	[BANKBRANCHCODE] [nvarchar](10) NOT NULL,
	[BANKBRANCHNAME] [nvarchar](50) NOT NULL,
	[IDNUM] [nvarchar](30) NOT NULL,
	[CHILDREN] [smallint] NOT NULL,
	[PERIODPAYMENT] [nvarchar](15) NOT NULL,
	[TYPEPAYMENT] [nvarchar](15) NOT NULL,
	[OCCUPATION] [nvarchar](50) NOT NULL,
	[RATE1] [money] NOT NULL,
	[RATE2] [money] NOT NULL,
	[RATE3] [money] NOT NULL,
	[PENDATE] [datetime] NULL,
	[ADDR1] [nvarchar](50) NOT NULL,
	[ADDR2] [nvarchar](50) NOT NULL,
	[ADDR3] [nvarchar](50) NOT NULL,
	[PCODE] [nvarchar](8) NOT NULL,
	[NOTES] [text] NOT NULL,
	[INITIALS] [nvarchar](7) NOT NULL,
	[IRP5NO] [nvarchar](10) NOT NULL,
	[PASSPORTNO] [nvarchar](25) NOT NULL,
	[NETT] [decimal](19, 4) NOT NULL,
	[COST] [decimal](19, 4) NOT NULL,
	[TOBETERMDATE] [datetime] NULL,
	[EDSHID] [int] NOT NULL,
	[TRAVELRATE] [money] NOT NULL,
	[ISFOREMAN] [bit] NOT NULL,
	[FOREMANNUM] [nvarchar](15) NOT NULL,
	[TAXALLOC] [nvarchar](3) NOT NULL,
	[DEFNT] [decimal](18, 2) NOT NULL,
	[DEFOT1] [decimal](18, 2) NOT NULL,
	[DEFOT2] [decimal](18, 2) NOT NULL,
	[DEFOT3] [decimal](18, 2) NOT NULL,
	[DEFOT4] [decimal](18, 2) NOT NULL,
	[DEFOT5] [decimal](18, 2) NOT NULL,
	[DEFCOSTALLOC] [char](25) NOT NULL,
	[DEFCONTRID] [int] NOT NULL,
	[DEFCONTRNUM] [nvarchar](10) NOT NULL,
	[DEFACTID] [int] NOT NULL,
	[DEFACTNUM] [char](10) NOT NULL,
	[DEFLEDGERID] [int] NOT NULL,
	[DEFLEDGERCODE] [char](10) NOT NULL,
	[DEFPLANT] [char](10) NOT NULL,
	[DEFDIVISIONID] [char](10) NOT NULL,
	[CONTRACTEXPDATE] [datetime] NULL,
	[DEBTNUMBER] [char](10) NOT NULL,
	[PRLSTAMP] [nvarchar](4) NOT NULL,
	[WCATYPE] [char](15) NOT NULL,
	[ISREADY] [bit] NOT NULL,
	[PREVNUMBER] [nvarchar](15) NOT NULL,
	[CHEQUENO] [int] NOT NULL,
	[SURNAME] [nvarchar](75) NOT NULL,
	[GRSTARTDATE] [datetime] NULL,
	[PSLPTIMESPRINT] [int] NOT NULL,
	[HFNUMBER] [nvarchar](20) NOT NULL,
	[LDTOTALYEAR] [decimal](18, 2) NOT NULL,
	[LDTOTALTAKEN] [decimal](18, 2) NOT NULL,
	[SDCURRENT] [decimal](18, 2) NOT NULL,
	[SDTOTAL] [decimal](18, 2) NOT NULL,
	[SDTOTALTAKEN] [decimal](18, 2) NOT NULL,
	[LDTAKENTHISPER] [decimal](18, 2) NOT NULL,
	[LDCURRENT] [decimal](18, 2) NOT NULL,
	[LDACCUMULATED] [decimal](18, 2) NOT NULL,
	[PAYBY] [nvarchar](30) NOT NULL,
	[SSCODE] [nvarchar](25) NOT NULL,
	[STATUSCODE] [nvarchar](5) NOT NULL,
	[TERMNOTE] [nvarchar](145) NOT NULL,
	[SSCATEGORY] [nvarchar](25) NOT NULL,
	[DIRECTIVENO] [nvarchar](20) NOT NULL,
	[DIRECTIVEPERC] [decimal](18, 2) NOT NULL,
	[GRADE] [nvarchar](30) NULL,
	[UIFREASONCODE] [nvarchar](3) NOT NULL,
	[RSCAREA] [nvarchar](10) NOT NULL,
	[EARLYPAY] [bit] NOT NULL,
	[PREVPAID] [decimal](19, 4) NOT NULL,
	[FOREMANPRLID] [int] NOT NULL,
	[KEYSTATUS] [nvarchar](10) NOT NULL,
	[EMPUNION] [nvarchar](15) NOT NULL,
	[JOBCODE] [nvarchar](10) NOT NULL,
	[EMPSTATUS] [nvarchar](15) NOT NULL,
	[EMPDISABILITY] [nvarchar](200) NOT NULL,
	[NATURE] [nvarchar](2) NOT NULL,
	[EARLYPAYVAL] [decimal](19, 4) NOT NULL,
	[IT3REASONCODE] [nvarchar](3) NOT NULL,
	[TYAMOUNTTAX] [decimal](18, 2) NOT NULL,
	[TYAMOUNT3695] [decimal](18, 2) NOT NULL,
	[TYAMOUNT3696] [decimal](18, 2) NOT NULL,
	[TYAMOUNT3697] [decimal](18, 2) NOT NULL,
	[TYAMOUNT3698] [decimal](18, 2) NOT NULL,
	[ISRFI] [bit] NOT NULL,
	[EMPOCCCAT] [smallint] NOT NULL,
	[EMPOCCLEVEL] [smallint] NOT NULL,
	[MDCLNAME] [nvarchar](50) NOT NULL,
	[MDCLNUMBER] [nvarchar](20) NOT NULL,
	[PENSPROVNUMBER] [nvarchar](20) NOT NULL,
	[STANDARDBANK_PROFILE] [nvarchar](16) NOT NULL,
	[EQMOVE] [smallint] NOT NULL,
	[LASTROUND] [decimal](19, 4) NOT NULL,
	[THISROUND] [decimal](19, 4) NOT NULL,
	[STDHRSPAYPER] [decimal](18, 2) NOT NULL,
	[DEPENDENTS] [int] NOT NULL,
	[TPBANKACC] [nvarchar](20) NOT NULL,
	[TPBANKACCTYPE] [nvarchar](20) NOT NULL,
	[TPBANKBRCODE] [nvarchar](10) NOT NULL,
	[TPBANKBRNAME] [nvarchar](50) NOT NULL,
	[TPSTANDARDBANK_PROFILE] [nvarchar](16) NOT NULL,
	[TPNAME] [nvarchar](75) NOT NULL,
	[TPBANKACC1] [nvarchar](15) NOT NULL,
	[TPBANKACCTYPE1] [nvarchar](20) NOT NULL,
	[TPBANKBRCODE1] [nvarchar](10) NOT NULL,
	[TPBANKBRNAME1] [nvarchar](50) NOT NULL,
	[TPSTANDARDBANK_PROFILE1] [nvarchar](16) NOT NULL,
	[TPNAME1] [nvarchar](75) NOT NULL,
	[EMPMAXNTHOURS] [decimal](18, 4) NOT NULL,
	[TYAMOUNT3810] [decimal](18, 2) NOT NULL,
	[TYAMOUNT4025] [decimal](18, 2) NOT NULL,
	[EMPLOYLEVEL] [int] NOT NULL,
	[FILENO] [nvarchar](15) NOT NULL,
	[PROBPER] [int] NOT NULL,
	[COUNTRYORG] [nvarchar](55) NOT NULL,
	[PENSIONSTARTDATE] [datetime] NULL,
	[MEDICALSTARTDATE] [datetime] NULL,
	[COSTTOCOMP] [decimal](19, 4) NOT NULL,
	[SHIFTSBFWD] [decimal](18, 2) NOT NULL,
	[ACCSHIFTS] [decimal](18, 2) NOT NULL,
	[SHIFTSTP] [decimal](18, 2) NOT NULL,
	[BLOCKED] [bit] NOT NULL,
	[DOLEAVEENCASH] [bit] NOT NULL,
	[BONUS] [decimal](18, 2) NOT NULL,
	[IPBENEFICIARY] [nvarchar](75) NOT NULL,
	[IPADDR1] [nvarchar](50) NOT NULL,
	[IPADDR2] [nvarchar](50) NOT NULL,
	[IPADDR3] [nvarchar](50) NOT NULL,
	[IPBANKACCOUNT] [nvarchar](50) NOT NULL,
	[IPBANKNAME] [nvarchar](50) NOT NULL,
	[IPBANKADDR1] [nvarchar](50) NOT NULL,
	[IPBANKADDR2] [nvarchar](50) NOT NULL,
	[IPBANKADDR3] [nvarchar](50) NOT NULL,
	[IPBRANCHNAME] [nvarchar](50) NOT NULL,
	[IPBANKTEL1] [nvarchar](15) NOT NULL,
	[IPBANKTEL2] [nvarchar](15) NOT NULL,
	[IPSWIFT] [nvarchar](15) NOT NULL,
	[IPSORT] [nvarchar](15) NOT NULL,
	[IPABA] [nvarchar](20) NOT NULL,
	[IPIBAN] [nvarchar](50) NOT NULL,
	[IPCORRESPONDENTBANKNAME] [nvarchar](50) NOT NULL,
	[IPCORRESPONDENTABA] [nvarchar](20) NOT NULL,
	[IPINFO] [nvarchar](200) NOT NULL,
	[TNALEDGERCODECONTRACT] [char](10) NOT NULL,
	[TNALEDGERCODEPLANT] [char](10) NOT NULL,
	[TNALEDGERCODEBS] [char](10) NOT NULL,
	[TNALEDGERCODEOH] [char](10) NOT NULL,
	[PENSPROVNAME] [nvarchar](50) NOT NULL,
	[TITLE] [nvarchar](15) NOT NULL,
	[ACCIDENTDATE] [datetime] NULL,
	[PASSPORTEXPDATE] [smalldatetime] NULL,
	[IDEXPDATE] [smalldatetime] NULL,
	[LABCARDNO] [nvarchar](20) NOT NULL,
	[LABCARDEXPDATE] [smalldatetime] NULL,
	[VISANO] [nvarchar](20) NOT NULL,
	[VISAEXPDATE] [smalldatetime] NULL,
	[DISABUSEFORTAX] [bit] NOT NULL,
	[SPOUSEEMPLOYED] [bit] NOT NULL,
	[EXARMY] [bit] NOT NULL,
	[QUALIFIC] [nvarchar](80) NULL,
	[RELIGION] [nvarchar](30) NULL,
	[BSNEW] [bit] NOT NULL,
	[PSNEW] [bit] NOT NULL,
	[REJOININGDATE] [datetime] NULL,
	[PROVINCEID] [int] NOT NULL,
	[ESINUMBER] [nvarchar](25) NOT NULL,
	[APPNAME] [nvarchar](30) NOT NULL,
	[CARCAT] [nvarchar](10) NOT NULL,
	[LDTAKENINCYCLE] [decimal](18, 4) NULL,
	[LDFUTUREDAYSPLANNED] [decimal](18, 4) NULL,
	[LDAVAILABLE] [decimal](18, 4) NULL,
	[SDAVAILABLE] [decimal](18, 4) NULL,
	[SDACCRUEDTHISMONTH] [decimal](18, 4) NULL,
	[MOLPERSNO] [nvarchar](25) NOT NULL,
	[MOLOCCUPATION] [nvarchar](50) NOT NULL,
	[PASSCOUNTRYISSUE] [nvarchar](30) NOT NULL,
	[ADDRUNITNUM] [nvarchar](11) NOT NULL,
	[ADDRCOMPLEX] [nvarchar](25) NOT NULL,
	[ADDRSTREETNUM] [nvarchar](11) NOT NULL,
	[ADDRSTREET] [nvarchar](25) NOT NULL,
	[ADDRSUBURB] [nvarchar](34) NOT NULL,
	[ADDRCITY] [nvarchar](24) NOT NULL,
	[POSTALADDR1] [nvarchar](35) NOT NULL,
	[POSTALADDR2] [nvarchar](35) NOT NULL,
	[POSTALADDR3] [nvarchar](35) NOT NULL,
	[ACCOUNTHOLDERNAME] [nvarchar](50) NOT NULL,
	[ACCOUNTHOLDERRELATIONSHIP] [int] NOT NULL,
	[POSTALAVAILABLE] [bit] NOT NULL,
	[FAX] [nvarchar](20) NOT NULL,
	[STAMPREGISTRATION] [nvarchar](20) NOT NULL,
	[AVGWEEKDAYS] [nvarchar](10) NULL,
	[STDHRSDAY] [decimal](18, 4) NOT NULL,
	[UNIONCODE] [nvarchar](4) NOT NULL,
	[ENTERPRISEID] [nvarchar](12) NOT NULL,
	[WPSROUTINGCODE] [nvarchar](18) NOT NULL,
	[USERNAME] [nvarchar](40) NULL,
	[PASSWORD] [nvarchar](40) NULL,
	[RFISPLIT] [decimal](18, 2) NOT NULL,
	[FULL3697] [decimal](18, 2) NOT NULL,
	[INDUSTRYNO] [nvarchar](12) NOT NULL,
	[RMAREGION] [nvarchar](20) NOT NULL,
	[MINENO] [nvarchar](5) NOT NULL,
	[PAYSLIPNOTES] [nvarchar](200) NULL,
	[TOTALRATEINCREMENT] [int] NOT NULL,
 CONSTRAINT [PK_EMPLOYEES_EMPID] PRIMARY KEY CLUSTERED 
(
	[EMPID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY],
 CONSTRAINT [IX_EMPLOYEES_PAYROLLID_EMPNUMBER] UNIQUE NONCLUSTERED 
(
	[PAYROLLID] ASC,
	[EMPNUMBER] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [IX_EMPLOYEES_PREVNUMBER] ON [dbo].[EMPLOYEES]
(
	[PREVNUMBER] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_KNOWNAS]  DEFAULT ('') FOR [KNOWNAS]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_PAYPOINT]  DEFAULT ('') FOR [PAYPOINT]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_SEX]  DEFAULT ('') FOR [SEX]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_SOUSENAME]  DEFAULT ('') FOR [SPOUSENAME]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_SOUSEADDR]  DEFAULT ('') FOR [SPOUSEADDR]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_SPOUSETEL]  DEFAULT ('') FOR [SPOUSETEL]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_SPOUSECELL]  DEFAULT ('') FOR [SPOUSECELL]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_DEPARTMENT]  DEFAULT ((-1)) FOR [DEPDIV]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_RACE]  DEFAULT ('') FOR [RACE]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_MARIED]  DEFAULT ('') FOR [MARITALSTATUS]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_TEL]  DEFAULT ('') FOR [TEL1]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_TEL2]  DEFAULT ('') FOR [TEL2]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_CELL1]  DEFAULT ('') FOR [CELL1]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_CELL]  DEFAULT ('') FOR [CELL2]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_EMAIL]  DEFAULT ('') FOR [EMAIL]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_TAXNUMBER]  DEFAULT ('') FOR [TAXNUMBER]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_BANKACCOUNT]  DEFAULT ('') FOR [BANKACCOUNT]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_BANKACCTYPE]  DEFAULT ('') FOR [BANKACCTYPE]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_BANKBRANCHCODE]  DEFAULT ('') FOR [BANKBRANCHCODE]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_BANKBRANCHNAME]  DEFAULT ('') FOR [BANKBRANCHNAME]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_IDNUM]  DEFAULT ('') FOR [IDNUM]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_CHILDREN]  DEFAULT (0) FOR [CHILDREN]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_TYPEOFPAYMENT]  DEFAULT ('') FOR [PERIODPAYMENT]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_PERIODOFPAYMENT]  DEFAULT ('') FOR [TYPEPAYMENT]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_OCCUPATION]  DEFAULT ('') FOR [OCCUPATION]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_RATE1]  DEFAULT (0) FOR [RATE1]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_RATE2]  DEFAULT (0) FOR [RATE2]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_RATE3]  DEFAULT (0) FOR [RATE3]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_ADDR1]  DEFAULT ('') FOR [ADDR1]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_ADDR2]  DEFAULT ('') FOR [ADDR2]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_ADDR3]  DEFAULT ('') FOR [ADDR3]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_PCODE]  DEFAULT ('') FOR [PCODE]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_NOTES]  DEFAULT ('') FOR [NOTES]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_INITIALS]  DEFAULT ('') FOR [INITIALS]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_IRP5NO]  DEFAULT ('') FOR [IRP5NO]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_PASSPORTNO]  DEFAULT ('') FOR [PASSPORTNO]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_NETT]  DEFAULT (0) FOR [NETT]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_COST]  DEFAULT (0) FOR [COST]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_TRAVELRATE]  DEFAULT (0) FOR [TRAVELRATE]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_ISFOREMAN]  DEFAULT (0) FOR [ISFOREMAN]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_FOREMANNUM]  DEFAULT ('') FOR [FOREMANNUM]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_TAXALLOC]  DEFAULT ('') FOR [TAXALLOC]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_W1NTHRS]  DEFAULT (0) FOR [DEFNT]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_DEFOT1]  DEFAULT (0) FOR [DEFOT1]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_DEFOT2]  DEFAULT (0) FOR [DEFOT2]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_DEFOT3]  DEFAULT (0) FOR [DEFOT3]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_DEFOT4]  DEFAULT (0) FOR [DEFOT4]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_DEFOT5]  DEFAULT (0) FOR [DEFOT5]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_P1COSTALLOC]  DEFAULT ('') FOR [DEFCOSTALLOC]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_DEFCONTRID]  DEFAULT ((-1)) FOR [DEFCONTRID]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_DEFCONTRNUM]  DEFAULT ('') FOR [DEFCONTRNUM]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_DEFACTID]  DEFAULT ((-1)) FOR [DEFACTID]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_DEFACTNUM]  DEFAULT ('') FOR [DEFACTNUM]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_DEFLEDGERID]  DEFAULT ((-1)) FOR [DEFLEDGERID]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_DEFLEDGERCODE]  DEFAULT ('') FOR [DEFLEDGERCODE]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_DEFPLANT]  DEFAULT ('') FOR [DEFPLANT]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_DEFDIVISIONID]  DEFAULT ((-1)) FOR [DEFDIVISIONID]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_DEBTNUM]  DEFAULT ('') FOR [DEBTNUMBER]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_PRLSTAMP]  DEFAULT ('') FOR [PRLSTAMP]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_WCATYPE]  DEFAULT ('') FOR [WCATYPE]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_CANPOSTACC]  DEFAULT (0) FOR [ISREADY]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_PREVNUMBER]  DEFAULT ('') FOR [PREVNUMBER]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_CHEQUENO]  DEFAULT ((-1)) FOR [CHEQUENO]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_SURNAME]  DEFAULT ('') FOR [SURNAME]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_PSLPTIMESPRINT]  DEFAULT (0) FOR [PSLPTIMESPRINT]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_HFNUMBER]  DEFAULT ('') FOR [HFNUMBER]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_LDTOTALYEAR]  DEFAULT (0) FOR [LDTOTALYEAR]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_LDTAKEN]  DEFAULT (0) FOR [LDTOTALTAKEN]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_SDCURR]  DEFAULT (0) FOR [SDCURRENT]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_SDTOTAL]  DEFAULT (0) FOR [SDTOTAL]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_SDTAKEN]  DEFAULT (0) FOR [SDTOTALTAKEN]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_LDTAKENTHISPER]  DEFAULT (0) FOR [LDTAKENTHISPER]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_LDDUE]  DEFAULT (0) FOR [LDCURRENT]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_LDACCUMULATED]  DEFAULT (0) FOR [LDACCUMULATED]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_PAYBY]  DEFAULT ('Cash') FOR [PAYBY]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_SSCODE]  DEFAULT ('') FOR [SSCODE]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_STATUSCODE]  DEFAULT (1) FOR [STATUSCODE]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_TERMNOTE]  DEFAULT ('') FOR [TERMNOTE]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_SSCATEGORY]  DEFAULT ('') FOR [SSCATEGORY]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_DIRECTIVENO]  DEFAULT ('') FOR [DIRECTIVENO]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_DIRECTIVEPERC]  DEFAULT (0) FOR [DIRECTIVEPERC]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_GRADE]  DEFAULT ('') FOR [GRADE]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF__EMPLOYEES__UIFRE__0A7378A9]  DEFAULT ('') FOR [UIFREASONCODE]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF__EMPLOYEES__RSCAR__1B9F9B59]  DEFAULT ('') FOR [RSCAREA]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF__EMPLOYEES__EARLY__5C793A7D]  DEFAULT (0) FOR [EARLYPAY]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF__EMPLOYEES__PREVP__5D6D5EB6]  DEFAULT (0) FOR [PREVPAID]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF__EMPLOYEES__FOREM__52F09B9A]  DEFAULT ((-1)) FOR [FOREMANPRLID]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF__EMPLOYEES__KEYST__2A7895EC]  DEFAULT ('') FOR [KEYSTATUS]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF__EMPLOYEES__EMPUN__2B6CBA25]  DEFAULT ('') FOR [EMPUNION]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF__EMPLOYEES__JOBCO__2C60DE5E]  DEFAULT ('') FOR [JOBCODE]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF__EMPLOYEES__EMPST__226D5FD0]  DEFAULT ('Unknown') FOR [EMPSTATUS]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF__EMPLOYEES__EMPDI__23618409]  DEFAULT ('') FOR [EMPDISABILITY]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF__EMPLOYEES__NATUR__2455A842]  DEFAULT ('A') FOR [NATURE]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF__EMPLOYEES__EARLY__2B02A5D1]  DEFAULT (0) FOR [EARLYPAYVAL]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF__EMPLOYEES__IT3RE__2BF6CA0A]  DEFAULT ('') FOR [IT3REASONCODE]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF__EMPLOYEES__TYAMO__2CEAEE43]  DEFAULT (0) FOR [TYAMOUNTTAX]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF__EMPLOYEES__TYAMO__2DDF127C]  DEFAULT (0) FOR [TYAMOUNT3695]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF__EMPLOYEES__TYAMO__2ED336B5]  DEFAULT (0) FOR [TYAMOUNT3696]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF__EMPLOYEES__TYAMO__2FC75AEE]  DEFAULT (0) FOR [TYAMOUNT3697]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF__EMPLOYEES__TYAMO__30BB7F27]  DEFAULT (0) FOR [TYAMOUNT3698]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF__EMPLOYEES__ISRFI__31AFA360]  DEFAULT (0) FOR [ISRFI]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_EMPOCCCAT]  DEFAULT (0) FOR [EMPOCCCAT]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_EMPOCCLEVEL]  DEFAULT (0) FOR [EMPOCCLEVEL]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_MDCLNAME]  DEFAULT ('') FOR [MDCLNAME]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_MDCLNUMBER]  DEFAULT ('') FOR [MDCLNUMBER]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_PENSPROVNUMBER]  DEFAULT ('') FOR [PENSPROVNUMBER]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_STANDARDBANK_PROFILE]  DEFAULT ('') FOR [STANDARDBANK_PROFILE]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_EQMOVE]  DEFAULT (0) FOR [EQMOVE]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_LASTROUND]  DEFAULT (0) FOR [LASTROUND]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_THISROUND]  DEFAULT (0) FOR [THISROUND]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_STDHRSPAYPER]  DEFAULT (0) FOR [STDHRSPAYPER]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_DEPENDENTS]  DEFAULT (0) FOR [DEPENDENTS]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_TPBANKACC]  DEFAULT ('') FOR [TPBANKACC]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_TPBANKACCTYPE]  DEFAULT ('') FOR [TPBANKACCTYPE]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_TPBANKBRCODE]  DEFAULT ('') FOR [TPBANKBRCODE]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_TPBANKBRNAME]  DEFAULT ('') FOR [TPBANKBRNAME]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_TPSTANDARDBANK_PROFILE]  DEFAULT ('') FOR [TPSTANDARDBANK_PROFILE]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_TPNAME]  DEFAULT ('') FOR [TPNAME]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_TPBANKACC1]  DEFAULT ('') FOR [TPBANKACC1]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_TPBANKACCTYPE1]  DEFAULT ('') FOR [TPBANKACCTYPE1]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_TPBANKBRCODE1]  DEFAULT ('') FOR [TPBANKBRCODE1]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_TPBANKBRNAME1]  DEFAULT ('') FOR [TPBANKBRNAME1]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_TPSTANDARDBANK_PROFILE1]  DEFAULT ('') FOR [TPSTANDARDBANK_PROFILE1]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_TPNAME1]  DEFAULT ('') FOR [TPNAME1]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_EMPMAXNTHOURS]  DEFAULT ((0)) FOR [EMPMAXNTHOURS]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_TYAMOUNT3810]  DEFAULT ((0)) FOR [TYAMOUNT3810]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_TYAMOUNT4025]  DEFAULT ((0)) FOR [TYAMOUNT4025]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_EMPLOYLEVEL]  DEFAULT ((0)) FOR [EMPLOYLEVEL]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_FILENO]  DEFAULT ('') FOR [FILENO]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_PROBPER]  DEFAULT ((0)) FOR [PROBPER]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_COUNTRYORG]  DEFAULT ('') FOR [COUNTRYORG]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_COSTTOCOMP]  DEFAULT ((0)) FOR [COSTTOCOMP]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_SHIFTSBFWD]  DEFAULT ((0)) FOR [SHIFTSBFWD]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_ACCSHIFTS]  DEFAULT ((0)) FOR [ACCSHIFTS]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_SHIFTSTP]  DEFAULT ((0)) FOR [SHIFTSTP]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_BLOCKED]  DEFAULT ((0)) FOR [BLOCKED]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_DOLEAVEENCASH]  DEFAULT ((0)) FOR [DOLEAVEENCASH]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_BONUS]  DEFAULT ((0)) FOR [BONUS]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_IPBENEFICIARY]  DEFAULT ('') FOR [IPBENEFICIARY]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_IPADDR1]  DEFAULT ('') FOR [IPADDR1]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_IPADDR2]  DEFAULT ('') FOR [IPADDR2]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_IPADDR3]  DEFAULT ('') FOR [IPADDR3]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_IPBANKACCOUNT]  DEFAULT ('') FOR [IPBANKACCOUNT]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_IPBANKNAME]  DEFAULT ('') FOR [IPBANKNAME]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_IPBANKADDR1]  DEFAULT ('') FOR [IPBANKADDR1]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_IPBANKADDR2]  DEFAULT ('') FOR [IPBANKADDR2]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_IPBANKADDR3]  DEFAULT ('') FOR [IPBANKADDR3]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_IPBRANCHNAME]  DEFAULT ('') FOR [IPBRANCHNAME]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_IPBANKTEL1]  DEFAULT ('') FOR [IPBANKTEL1]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_IPBANKTEL2]  DEFAULT ('') FOR [IPBANKTEL2]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_IPSWIFT]  DEFAULT ('') FOR [IPSWIFT]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_IPSORT]  DEFAULT ('') FOR [IPSORT]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_IPABA]  DEFAULT ('') FOR [IPABA]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_IPIBAN]  DEFAULT ('') FOR [IPIBAN]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_IPCORRESPONDENTBANKNAME]  DEFAULT ('') FOR [IPCORRESPONDENTBANKNAME]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_IPCORRESPONDENTABA]  DEFAULT ('') FOR [IPCORRESPONDENTABA]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_IPINFO]  DEFAULT ('') FOR [IPINFO]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_TNALEDGERCODECONTRACT]  DEFAULT ('') FOR [TNALEDGERCODECONTRACT]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_TNALEDGERCODEPLANT]  DEFAULT ('') FOR [TNALEDGERCODEPLANT]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_TNALEDGERCODEBS]  DEFAULT ('') FOR [TNALEDGERCODEBS]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_TNALEDGERCODEOH]  DEFAULT ('') FOR [TNALEDGERCODEOH]
ALTER TABLE [dbo].[EMPLOYEES] ADD  DEFAULT ('') FOR [PENSPROVNAME]
ALTER TABLE [dbo].[EMPLOYEES] ADD  DEFAULT ('') FOR [TITLE]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_LABCARDNO]  DEFAULT ('') FOR [LABCARDNO]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_VISANO]  DEFAULT ('') FOR [VISANO]
ALTER TABLE [dbo].[EMPLOYEES] ADD  DEFAULT ((0)) FOR [DISABUSEFORTAX]
ALTER TABLE [dbo].[EMPLOYEES] ADD  DEFAULT ((0)) FOR [SPOUSEEMPLOYED]
ALTER TABLE [dbo].[EMPLOYEES] ADD  DEFAULT ((0)) FOR [EXARMY]
ALTER TABLE [dbo].[EMPLOYEES] ADD  DEFAULT ((0)) FOR [BSNEW]
ALTER TABLE [dbo].[EMPLOYEES] ADD  DEFAULT ((0)) FOR [PSNEW]
ALTER TABLE [dbo].[EMPLOYEES] ADD  DEFAULT ((-1)) FOR [PROVINCEID]
ALTER TABLE [dbo].[EMPLOYEES] ADD  DEFAULT ('') FOR [ESINUMBER]
ALTER TABLE [dbo].[EMPLOYEES] ADD  DEFAULT ('') FOR [APPNAME]
ALTER TABLE [dbo].[EMPLOYEES] ADD  DEFAULT ('') FOR [CARCAT]
ALTER TABLE [dbo].[EMPLOYEES] ADD  DEFAULT ('') FOR [MOLPERSNO]
ALTER TABLE [dbo].[EMPLOYEES] ADD  DEFAULT ('') FOR [MOLOCCUPATION]
ALTER TABLE [dbo].[EMPLOYEES] ADD  DEFAULT ('') FOR [PASSCOUNTRYISSUE]
ALTER TABLE [dbo].[EMPLOYEES] ADD  DEFAULT ('') FOR [ADDRUNITNUM]
ALTER TABLE [dbo].[EMPLOYEES] ADD  DEFAULT ('') FOR [ADDRCOMPLEX]
ALTER TABLE [dbo].[EMPLOYEES] ADD  DEFAULT ('') FOR [ADDRSTREETNUM]
ALTER TABLE [dbo].[EMPLOYEES] ADD  DEFAULT ('') FOR [ADDRSTREET]
ALTER TABLE [dbo].[EMPLOYEES] ADD  DEFAULT ('') FOR [ADDRSUBURB]
ALTER TABLE [dbo].[EMPLOYEES] ADD  DEFAULT ('') FOR [ADDRCITY]
ALTER TABLE [dbo].[EMPLOYEES] ADD  DEFAULT ('') FOR [POSTALADDR1]
ALTER TABLE [dbo].[EMPLOYEES] ADD  DEFAULT ('') FOR [POSTALADDR2]
ALTER TABLE [dbo].[EMPLOYEES] ADD  DEFAULT ('') FOR [POSTALADDR3]
ALTER TABLE [dbo].[EMPLOYEES] ADD  DEFAULT ('') FOR [ACCOUNTHOLDERNAME]
ALTER TABLE [dbo].[EMPLOYEES] ADD  DEFAULT ((1)) FOR [ACCOUNTHOLDERRELATIONSHIP]
ALTER TABLE [dbo].[EMPLOYEES] ADD  DEFAULT ((0)) FOR [POSTALAVAILABLE]
ALTER TABLE [dbo].[EMPLOYEES] ADD  DEFAULT ('') FOR [FAX]
ALTER TABLE [dbo].[EMPLOYEES] ADD  DEFAULT ('') FOR [STAMPREGISTRATION]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_STDHRSDAY]  DEFAULT ((0)) FOR [STDHRSDAY]
ALTER TABLE [dbo].[EMPLOYEES] ADD  DEFAULT ('N/A') FOR [UNIONCODE]
ALTER TABLE [dbo].[EMPLOYEES] ADD  DEFAULT ('') FOR [ENTERPRISEID]
ALTER TABLE [dbo].[EMPLOYEES] ADD  DEFAULT ('') FOR [WPSROUTINGCODE]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_RFISPLIT]  DEFAULT ((0)) FOR [RFISPLIT]
ALTER TABLE [dbo].[EMPLOYEES] ADD  CONSTRAINT [DF_EMPLOYEES_FULL3697]  DEFAULT ((0)) FOR [FULL3697]
ALTER TABLE [dbo].[EMPLOYEES] ADD  DEFAULT ('') FOR [INDUSTRYNO]
ALTER TABLE [dbo].[EMPLOYEES] ADD  DEFAULT ('') FOR [RMAREGION]
ALTER TABLE [dbo].[EMPLOYEES] ADD  DEFAULT ('') FOR [MINENO]
ALTER TABLE [dbo].[EMPLOYEES] ADD  DEFAULT ((0)) FOR [TOTALRATEINCREMENT]
ALTER TABLE [dbo].[EMPLOYEES]  WITH CHECK ADD  CONSTRAINT [FK_EMPLOYEES_PAYROLLS] FOREIGN KEY([PAYROLLID])
REFERENCES [dbo].[PAYROLLS] ([PAYROLLID])
ALTER TABLE [dbo].[EMPLOYEES] CHECK CONSTRAINT [FK_EMPLOYEES_PAYROLLS]
ALTER TABLE [dbo].[EMPLOYEES]  WITH CHECK ADD  CONSTRAINT [FK_EMPLOYEES_TAXALLOC] FOREIGN KEY([TAXALLOC])
REFERENCES [dbo].[TAXALLOC] ([TAXTBL])
ALTER TABLE [dbo].[EMPLOYEES] CHECK CONSTRAINT [FK_EMPLOYEES_TAXALLOC]