/****** Object:  Table [dbo].[EMPLOANSINTR]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[EMPLOANSINTR](
	[LOANINTRID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[LOANID] [int] NOT NULL,
	[INTERESTAMOUNT] [money] NOT NULL,
	[RUNNO] [int] NOT NULL,
	[PERIODNO] [int] NOT NULL,
	[YEARNO] [int] NOT NULL,
	[PAYROLLID] [int] NOT NULL,
 CONSTRAINT [PK_EMPLOANSINTR] PRIMARY KEY CLUSTERED 
(
	[LOANINTRID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[EMPLOANSINTR] ADD  CONSTRAINT [DF_EMPLOANSINTR_INTERESTAMOUNT]  DEFAULT (0) FOR [INTERESTAMOUNT]
ALTER TABLE [dbo].[EMPLOANSINTR] ADD  CONSTRAINT [DF_EMPLOANSINTR_RUNNO]  DEFAULT (1) FOR [RUNNO]
ALTER TABLE [dbo].[EMPLOANSINTR] ADD  CONSTRAINT [DF_EMPLOANSINTR_PERIODNO]  DEFAULT (1) FOR [PERIODNO]
ALTER TABLE [dbo].[EMPLOANSINTR] ADD  CONSTRAINT [DF_EMPLOANSINTR_YEARNO]  DEFAULT (2003) FOR [YEARNO]
ALTER TABLE [dbo].[EMPLOANSINTR] ADD  CONSTRAINT [DF_EMPLOANSINTR_PAYROLLID]  DEFAULT (1) FOR [PAYROLLID]
ALTER TABLE [dbo].[EMPLOANSINTR]  WITH CHECK ADD  CONSTRAINT [FK_EMPLOANSINTR_EMPLOANS1] FOREIGN KEY([LOANID])
REFERENCES [dbo].[EMPLOANS] ([LOANID])
ALTER TABLE [dbo].[EMPLOANSINTR] CHECK CONSTRAINT [FK_EMPLOANSINTR_EMPLOANS1]