/****** Object:  Table [dbo].[EMPLEAVEHISTORY]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[EMPLEAVEHISTORY](
	[pklLeaveHistoryID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[LDTOTALYEAR] [decimal](18, 4) NULL,
	[LDTAKENTHISPER] [decimal](18, 4) NULL,
	[LDTAKENINCYCLE] [decimal](18, 4) NULL,
	[LDAVAILABLE] [decimal](18, 4) NULL,
	[LDACCUMULATED] [decimal](18, 4) NULL,
	[LDFUTUREDAYSPLANNED] [decimal](18, 4) NULL,
	[SDTOTAL] [decimal](18, 4) NULL,
	[SDCURRENT] [decimal](18, 4) NULL,
	[SDTOTALTAKEN] [decimal](18, 4) NULL,
	[SDAVAILABLE] [decimal](18, 4) NULL,
	[SDACCRUEDTHISMONTH] [decimal](18, 4) NULL,
	[AuditDate] [datetime] NOT NULL,
	[ACTIONDATE] [datetime] NULL,
	[PAYROLLID] [int] NULL,
	[EMPNUMBER] [nvarchar](30) NULL,
 CONSTRAINT [PK_EMPLEAVEHISTORY] PRIMARY KEY CLUSTERED 
(
	[pklLeaveHistoryID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[EMPLEAVEHISTORY] ADD  CONSTRAINT [DF_EMPLEAVEHISTORY_AuditDate]  DEFAULT (getdate()) FOR [AuditDate]