/****** Object:  Table [dbo].[EMPLOYEETDSSET]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[EMPLOYEETDSSET](
	[EMPTDSID] [int] NOT NULL,
	[YEARNO] [int] NOT NULL,
	[PERNO] [int] NOT NULL,
	[AMOUNT] [money] NOT NULL,
 CONSTRAINT [PK_EMPLOYEETDSSET] PRIMARY KEY CLUSTERED 
(
	[EMPTDSID] ASC,
	[YEARNO] ASC,
	[PERNO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]