/****** Object:  Table [dbo].[EMPLOYEESCOUNTRIES]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[EMPLOYEESCOUNTRIES](
	[CODE] [nvarchar](50) NOT NULL,
	[DESCRIPTION] [nvarchar](250) NULL,
 CONSTRAINT [PK_EMPLOYEESCOUNTRIES] PRIMARY KEY CLUSTERED 
(
	[CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]