/****** Object:  Table [dbo].[EMPOTHERHISTORY]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[EMPOTHERHISTORY](
	[EVENTID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[PRLID] [int] NOT NULL,
	[EMPNUMBER] [nvarchar](15) NOT NULL,
	[EVENTDESCR] [ntext] NOT NULL,
	[EVENTDATE] [datetime] NOT NULL,
	[USERID] [int] NOT NULL,
	[PERIODNO] [int] NOT NULL,
 CONSTRAINT [PK_EMPOTHERHIST] PRIMARY KEY CLUSTERED 
(
	[EVENTID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

CREATE NONCLUSTERED INDEX [IX_EMPOTHERHIST_CREATOR] ON [dbo].[EMPOTHERHISTORY]
(
	[USERID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [IX_EMPOTHERHIST_PRLID_EMPNUMBER] ON [dbo].[EMPOTHERHISTORY]
(
	[PRLID] ASC,
	[EMPNUMBER] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
ALTER TABLE [dbo].[EMPOTHERHISTORY] ADD  CONSTRAINT [DF_EMPOTHERHIST_DESCRIPTION]  DEFAULT ('') FOR [EVENTDESCR]
ALTER TABLE [dbo].[EMPOTHERHISTORY] ADD  CONSTRAINT [DF_EMPOTHERHISTORY_PERIODNO]  DEFAULT (0) FOR [PERIODNO]
ALTER TABLE [dbo].[EMPOTHERHISTORY]  WITH CHECK ADD  CONSTRAINT [FK_EMPOTHERHIST_EMPLOYEES] FOREIGN KEY([PRLID], [EMPNUMBER])
REFERENCES [dbo].[EMPLOYEES] ([PAYROLLID], [EMPNUMBER])
ALTER TABLE [dbo].[EMPOTHERHISTORY] CHECK CONSTRAINT [FK_EMPOTHERHIST_EMPLOYEES]