/****** Object:  Table [dbo].[EMPSTAMPS]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[EMPSTAMPS](
	[PAYROLLID] [int] NOT NULL,
	[EMPNUMBER] [nvarchar](15) NOT NULL,
	[PERIODNO] [int] NOT NULL,
	[RUNNO] [int] NOT NULL,
	[YEARNO] [int] NOT NULL,
	[WEEKNO] [int] NOT NULL,
	[NOOFSTAMPS] [int] NOT NULL,
	[SSID] [int] NOT NULL,
	[SSTOTAL] [money] NOT NULL,
 CONSTRAINT [PK_EMPSTAMPS] PRIMARY KEY CLUSTERED 
(
	[PAYROLLID] ASC,
	[EMPNUMBER] ASC,
	[PERIODNO] ASC,
	[RUNNO] ASC,
	[YEARNO] ASC,
	[WEEKNO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[EMPSTAMPS] ADD  CONSTRAINT [DF_EMPSTAMPS_NOOFSTAMPS]  DEFAULT (1) FOR [NOOFSTAMPS]
ALTER TABLE [dbo].[EMPSTAMPS] ADD  CONSTRAINT [DF_EMPSTAMPS_SSID]  DEFAULT ((-1)) FOR [SSID]
ALTER TABLE [dbo].[EMPSTAMPS] ADD  CONSTRAINT [DF_EMPSTAMPS_SSTOTAL]  DEFAULT (0) FOR [SSTOTAL]