/****** Object:  Table [dbo].[EMPTERMINATIONS]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[EMPTERMINATIONS](
	[pklTermID] [uniqueidentifier] NOT NULL,
	[PAYROLLID] [int] NOT NULL,
	[YEARNO] [int] NOT NULL,
	[EDSHID] [int] NOT NULL,
	[EMPNUMBER] [nvarchar](15) NOT NULL,
	[IDNUMBER] [nvarchar](30) NOT NULL,
	[PASSPORTNUMBER] [nvarchar](25) NULL,
	[TOBETERMDATE] [datetime] NULL,
	[TERMDATE] [datetime] NULL,
	[TERMREASONCODE] [nvarchar](5) NOT NULL,
	[REINSTATEDATE] [datetime] NULL,
	[AUDITDATE] [datetime] NOT NULL,
	[TERMNOTE] [nvarchar](145) NULL,
 CONSTRAINT [PK_EMPTERMINATIONS] PRIMARY KEY CLUSTERED 
(
	[pklTermID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[EMPTERMINATIONS] ADD  CONSTRAINT [DF_EMPTERMINATIONS_pklTermID]  DEFAULT (newid()) FOR [pklTermID]
ALTER TABLE [dbo].[EMPTERMINATIONS] ADD  CONSTRAINT [DF_EMPTERMINATIONS_AUDITDATE]  DEFAULT (getdate()) FOR [AUDITDATE]