/****** Object:  Table [dbo].[EMPUNIONS]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[EMPUNIONS](
	[UNIONCODE] [nvarchar](20) NOT NULL,
 CONSTRAINT [PK_EMPUNIONS] PRIMARY KEY CLUSTERED 
(
	[UNIONCODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]