/****** Object:  Table [dbo].[ERFQSINITITEMS]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[ERFQSINITITEMS](
	[LINEID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[ERFQID] [int] NOT NULL,
	[DESCR] [ntext] NOT NULL,
	[QTY] [numeric](18, 4) NOT NULL,
	[UNIT] [nvarchar](5) NOT NULL,
	[DETAILID] [int] NULL,
	[ORDEREDQTY] [decimal](18, 4) NOT NULL,
	[ITEMID] [int] NOT NULL,
 CONSTRAINT [PK_ERFQSINITITEMS] PRIMARY KEY CLUSTERED 
(
	[LINEID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

ALTER TABLE [dbo].[ERFQSINITITEMS] ADD  CONSTRAINT [DF_ERFQSINITITEMS_DESCR]  DEFAULT ('') FOR [DESCR]
ALTER TABLE [dbo].[ERFQSINITITEMS] ADD  CONSTRAINT [DF_ERFQSINITITEMS_QTY]  DEFAULT ((0.00)) FOR [QTY]
ALTER TABLE [dbo].[ERFQSINITITEMS] ADD  CONSTRAINT [DF_ERFQSINITITEMS_UNIT]  DEFAULT ('') FOR [UNIT]
ALTER TABLE [dbo].[ERFQSINITITEMS] ADD  CONSTRAINT [DF_ERFQSINITITEMS_detailid]  DEFAULT ((-1)) FOR [DETAILID]
ALTER TABLE [dbo].[ERFQSINITITEMS] ADD  CONSTRAINT [DF_ERFQSINITITEMS_ORDEREDQTY]  DEFAULT ((0)) FOR [ORDEREDQTY]
ALTER TABLE [dbo].[ERFQSINITITEMS] ADD  CONSTRAINT [DF_ERFQSINITITEMS_ITEMID]  DEFAULT ((-1)) FOR [ITEMID]
ALTER TABLE [dbo].[ERFQSINITITEMS]  WITH CHECK ADD  CONSTRAINT [FK_ERFQSINITITEMS_ERFQS] FOREIGN KEY([ERFQID])
REFERENCES [dbo].[ERFQS] ([ERFQID])
ALTER TABLE [dbo].[ERFQSINITITEMS] CHECK CONSTRAINT [FK_ERFQSINITITEMS_ERFQS]