/****** Object:  Table [dbo].[ERFQS]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[ERFQS](
	[ERFQID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[ERFQNAME] [nvarchar](50) NOT NULL,
	[ERFQDESCR] [nvarchar](255) NOT NULL,
	[ERFQCURRCODE] [nvarchar](3) NOT NULL,
	[CATID] [int] NOT NULL,
	[CLOSEDATE] [datetime] NOT NULL,
	[ACTIVE] [bit] NOT NULL,
	[MSGTEXT] [ntext] NOT NULL,
	[CREATEDATE] [datetime] NOT NULL,
	[STARTDATE] [datetime] NOT NULL,
	[REFNO] [nvarchar](55) NOT NULL,
	[ADDRID] [int] NOT NULL,
	[CONTACTID] [int] NOT NULL,
	[EMAILSENT] [bit] NOT NULL,
	[FAXSENT] [bit] NOT NULL,
	[SMSSENT] [bit] NOT NULL,
	[TIMESEMAILSENT] [int] NOT NULL,
	[TIMESFAXSENT] [int] NOT NULL,
	[TIMESSMSSENT] [int] NOT NULL,
	[CREATORID] [int] NOT NULL,
	[BORGID] [int] NOT NULL,
	[CPMIME] [nvarchar](100) NOT NULL,
	[CPSIZEINKB] [int] NOT NULL,
	[CPSRVPATH] [nvarchar](255) NOT NULL,
	[CPORIGFILE] [nvarchar](255) NOT NULL,
	[TCPIP] [nvarchar](15) NOT NULL,
	[WHOFIRST] [nvarchar](255) NOT NULL,
	[WHONEXT] [nvarchar](255) NOT NULL,
	[WHENFIRST] [datetime] NOT NULL,
	[WHENNEXT] [datetime] NOT NULL,
	[SUPPREPLIED] [bit] NOT NULL,
	[EID] [nvarchar](10) NOT NULL,
	[ISONLINE] [bit] NOT NULL,
	[TENDER] [nvarchar](100) NULL,
	[SPECIFICATION] [nvarchar](100) NULL,
	[TENDERCLOSEDATE] [datetime] NOT NULL,
	[BOQHEADERID] [int] NULL,
	[MONTHS] [int] NOT NULL,
	[SITE] [nvarchar](50) NOT NULL,
	[CONTRNUMBER] [nvarchar](10) NOT NULL,
	[REQID] [int] NULL,
	[CODE] [nvarchar](150) NULL,
	[RECTYPE] [nvarchar](3) NOT NULL,
 CONSTRAINT [PK_ERFQS] PRIMARY KEY CLUSTERED 
(
	[ERFQID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

ALTER TABLE [dbo].[ERFQS] ADD  CONSTRAINT [DF_ERFQS_ERFQNAME]  DEFAULT ('') FOR [ERFQNAME]
ALTER TABLE [dbo].[ERFQS] ADD  CONSTRAINT [DF_ERFQS_ERFQDESCR]  DEFAULT ('') FOR [ERFQDESCR]
ALTER TABLE [dbo].[ERFQS] ADD  CONSTRAINT [DF_ERFQS_ERFQCURRCODE]  DEFAULT ('') FOR [ERFQCURRCODE]
ALTER TABLE [dbo].[ERFQS] ADD  CONSTRAINT [DF_ERFQS_CLOSEDATE]  DEFAULT (getdate()+(30)) FOR [CLOSEDATE]
ALTER TABLE [dbo].[ERFQS] ADD  CONSTRAINT [DF_ERFQS_ACTIVE]  DEFAULT ((1)) FOR [ACTIVE]
ALTER TABLE [dbo].[ERFQS] ADD  CONSTRAINT [DF_ERFQS_MSGTEXT]  DEFAULT ('') FOR [MSGTEXT]
ALTER TABLE [dbo].[ERFQS] ADD  CONSTRAINT [DF_ERFQS_CREATEDATE]  DEFAULT (getdate()) FOR [CREATEDATE]
ALTER TABLE [dbo].[ERFQS] ADD  CONSTRAINT [DF_ERFQS_STARTDATE]  DEFAULT (getdate()) FOR [STARTDATE]
ALTER TABLE [dbo].[ERFQS] ADD  CONSTRAINT [DF_ERFQS_REFNO]  DEFAULT ('') FOR [REFNO]
ALTER TABLE [dbo].[ERFQS] ADD  CONSTRAINT [DF_ERFQS_EMAILSENT]  DEFAULT ((0)) FOR [EMAILSENT]
ALTER TABLE [dbo].[ERFQS] ADD  CONSTRAINT [DF_ERFQS_FAXSENT]  DEFAULT ((0)) FOR [FAXSENT]
ALTER TABLE [dbo].[ERFQS] ADD  CONSTRAINT [DF_ERFQS_SMSSENT]  DEFAULT ((0)) FOR [SMSSENT]
ALTER TABLE [dbo].[ERFQS] ADD  CONSTRAINT [DF_ERFQS_TIMESEMAILSENT]  DEFAULT ((0)) FOR [TIMESEMAILSENT]
ALTER TABLE [dbo].[ERFQS] ADD  CONSTRAINT [DF_ERFQS_TIMESFAXSENT]  DEFAULT ((0)) FOR [TIMESFAXSENT]
ALTER TABLE [dbo].[ERFQS] ADD  CONSTRAINT [DF_ERFQS_TIMESSMSSENT]  DEFAULT ((0)) FOR [TIMESSMSSENT]
ALTER TABLE [dbo].[ERFQS] ADD  CONSTRAINT [DF_ERFQS_BORGID]  DEFAULT ((0)) FOR [BORGID]
ALTER TABLE [dbo].[ERFQS] ADD  CONSTRAINT [DF_ERFQS_CPMIME]  DEFAULT ('') FOR [CPMIME]
ALTER TABLE [dbo].[ERFQS] ADD  CONSTRAINT [DF_ERFQS_CPSIZEINKB]  DEFAULT ((0)) FOR [CPSIZEINKB]
ALTER TABLE [dbo].[ERFQS] ADD  CONSTRAINT [DF_ERFQS_CPSRVPATH]  DEFAULT ('') FOR [CPSRVPATH]
ALTER TABLE [dbo].[ERFQS] ADD  CONSTRAINT [DF_ERFQS_CPORIGFILE]  DEFAULT ('') FOR [CPORIGFILE]
ALTER TABLE [dbo].[ERFQS] ADD  CONSTRAINT [DF_ERFQS_TCPIP]  DEFAULT ('0.0.0.0') FOR [TCPIP]
ALTER TABLE [dbo].[ERFQS] ADD  CONSTRAINT [DF_ERFQS_WHO]  DEFAULT ('') FOR [WHOFIRST]
ALTER TABLE [dbo].[ERFQS] ADD  CONSTRAINT [DF_ERFQS_WHONEXT]  DEFAULT ('') FOR [WHONEXT]
ALTER TABLE [dbo].[ERFQS] ADD  CONSTRAINT [DF_ERFQS_WHENFIRST]  DEFAULT (getdate()) FOR [WHENFIRST]
ALTER TABLE [dbo].[ERFQS] ADD  CONSTRAINT [DF_ERFQS_WHENNEXT]  DEFAULT (getdate()) FOR [WHENNEXT]
ALTER TABLE [dbo].[ERFQS] ADD  CONSTRAINT [DF_ERFQS_SUPPREPLIED]  DEFAULT ((0)) FOR [SUPPREPLIED]
ALTER TABLE [dbo].[ERFQS] ADD  CONSTRAINT [DF_ERFQS_EID]  DEFAULT ('') FOR [EID]
ALTER TABLE [dbo].[ERFQS] ADD  CONSTRAINT [DF_ERFQS_ISONLINE]  DEFAULT ((0)) FOR [ISONLINE]
ALTER TABLE [dbo].[ERFQS] ADD  CONSTRAINT [DF_ERFQS_TENDER]  DEFAULT ('') FOR [TENDER]
ALTER TABLE [dbo].[ERFQS] ADD  CONSTRAINT [DF_ERFQS_SPECIFICATION]  DEFAULT ('') FOR [SPECIFICATION]
ALTER TABLE [dbo].[ERFQS] ADD  CONSTRAINT [DF_ERFQS_TENDERCLOSEDATE]  DEFAULT (getdate()) FOR [TENDERCLOSEDATE]
ALTER TABLE [dbo].[ERFQS] ADD  CONSTRAINT [DF_ERFQS_BOQHEADERID]  DEFAULT ((-1)) FOR [BOQHEADERID]
ALTER TABLE [dbo].[ERFQS] ADD  CONSTRAINT [DF_ERFQS_MONTHS]  DEFAULT ((0)) FOR [MONTHS]
ALTER TABLE [dbo].[ERFQS] ADD  CONSTRAINT [DF_ERFQS_SITE]  DEFAULT ('') FOR [SITE]
ALTER TABLE [dbo].[ERFQS] ADD  CONSTRAINT [DF_ERFQS_CONTRNUMBER]  DEFAULT ('') FOR [CONTRNUMBER]
ALTER TABLE [dbo].[ERFQS] ADD  CONSTRAINT [DF_ERFQS_RECTYPE]  DEFAULT ('STD') FOR [RECTYPE]
ALTER TABLE [dbo].[ERFQS]  WITH CHECK ADD  CONSTRAINT [FK_ERFQS_BORGS] FOREIGN KEY([BORGID])
REFERENCES [dbo].[BORGS] ([BORGID])
ALTER TABLE [dbo].[ERFQS] CHECK CONSTRAINT [FK_ERFQS_BORGS]
ALTER TABLE [dbo].[ERFQS]  WITH CHECK ADD  CONSTRAINT [FK_ERFQS_CATEGORIESTYPE] FOREIGN KEY([CATID])
REFERENCES [dbo].[CATEGORIESTYPE] ([CATID])
ALTER TABLE [dbo].[ERFQS] CHECK CONSTRAINT [FK_ERFQS_CATEGORIESTYPE]
ALTER TABLE [dbo].[ERFQS]  WITH CHECK ADD  CONSTRAINT [FK_ERFQS_COMPADDRESSES] FOREIGN KEY([ADDRID])
REFERENCES [dbo].[COMPADDRESSES] ([ADDRID])
ALTER TABLE [dbo].[ERFQS] CHECK CONSTRAINT [FK_ERFQS_COMPADDRESSES]
ALTER TABLE [dbo].[ERFQS]  WITH CHECK ADD  CONSTRAINT [FK_ERFQS_CONTACTS] FOREIGN KEY([CONTACTID])
REFERENCES [dbo].[CONTACTS] ([CONTACTID])
ALTER TABLE [dbo].[ERFQS] CHECK CONSTRAINT [FK_ERFQS_CONTACTS]
ALTER TABLE [dbo].[ERFQS]  WITH CHECK ADD  CONSTRAINT [FK_ERFQS_CURRENCIES] FOREIGN KEY([ERFQCURRCODE])
REFERENCES [dbo].[CURRENCIES] ([CURRCODE])
ALTER TABLE [dbo].[ERFQS] CHECK CONSTRAINT [FK_ERFQS_CURRENCIES]
ALTER TABLE [dbo].[ERFQS]  WITH CHECK ADD  CONSTRAINT [FK_ERFQS_USERS] FOREIGN KEY([CREATORID])
REFERENCES [dbo].[USERS] ([USERID])
ALTER TABLE [dbo].[ERFQS] CHECK CONSTRAINT [FK_ERFQS_USERS]