/****** Object:  Table [dbo].[ERFQITEMS]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[ERFQITEMS](
	[ERFQID] [int] NOT NULL,
	[LINENUMBER] [int] NOT NULL,
	[CATALOGITEMID] [int] NOT NULL,
	[ITEMDESCRIPTION] [nvarchar](255) NOT NULL,
	[BUYERPARTNUMBER] [nvarchar](50) NOT NULL,
	[SUPPID] [int] NOT NULL,
	[PARTNUMBER] [nvarchar](50) NOT NULL,
	[PARTNUMBEREXT] [nvarchar](50) NOT NULL,
	[UOM] [nvarchar](25) NOT NULL,
	[QTY] [decimal](19, 4) NOT NULL,
	[PRICE] [money] NOT NULL,
	[PAYMENTID] [int] NOT NULL,
	[DLVRID] [int] NOT NULL,
	[INSTRUCTIONS] [ntext] NOT NULL,
	[VATPERC] [decimal](18, 4) NOT NULL,
	[PROJECTID] [int] NOT NULL,
	[CONTRACTID] [int] NOT NULL,
	[MIMETYPE] [nvarchar](100) NOT NULL,
	[FILESIZEINKB] [int] NOT NULL,
	[ORIGINALFILEPATH] [nvarchar](255) NOT NULL,
	[SENDTOSUPP] [bit] NOT NULL,
	[DIVISIONID] [int] NOT NULL,
	[RESOURCECODE] [nvarchar](25) NOT NULL,
	[FILEPATH] [nvarchar](255) NOT NULL,
	[DISCOUNT] [decimal](18, 4) NOT NULL,
	[ITEMSTATUSID] [int] NOT NULL,
	[LASTCHANGE] [datetime] NULL,
	[LASTCHANGEBY] [int] NULL,
	[ITEMSTATUSDATE] [datetime] NOT NULL,
	[ISFREEITEM] [bit] NOT NULL,
	[CATORTENDITEM] [int] NOT NULL,
	[GLCODEID] [int] NOT NULL,
	[ACTID] [int] NOT NULL,
	[ALLOCATION] [char](25) NOT NULL,
	[PENUMBER] [char](10) NOT NULL,
	[STOCKID] [int] NOT NULL,
	[ATTMESSAGE] [nvarchar](200) NOT NULL,
	[VATID] [nvarchar](100) NOT NULL,
	[JOBCARDID] [int] NULL,
	[JOBCARDVATID] [char](2) NULL,
	[JOBCARDLEDGERID] [int] NULL,
	[JOBCARDACTID] [char](10) NULL,
	[TBORGID] [int] NULL,
	[TERMS] [nvarchar](250) NOT NULL,
	[EID] [char](10) NOT NULL,
	[VATAMOUNT] [decimal](18, 4) NOT NULL,
	[STKCONVERTFLAG] [bit] NOT NULL,
	[STKBUYCONV] [numeric](18, 4) NULL,
	[REQUIREDBYDATE] [datetime] NULL,
	[EXPECTEDDELIVERYDATE] [datetime] NULL,
	[NOTE] [nvarchar](800) NOT NULL,
 CONSTRAINT [PK_ERFQITEMS] PRIMARY KEY CLUSTERED 
(
	[ERFQID] ASC,
	[LINENUMBER] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

ALTER TABLE [dbo].[ERFQITEMS] ADD  CONSTRAINT [DF_ERFQITEMS_ITEMDESCRIPTION]  DEFAULT ('') FOR [ITEMDESCRIPTION]
ALTER TABLE [dbo].[ERFQITEMS] ADD  CONSTRAINT [DF_ERFQITEMS_BUYERPARTNUMBER]  DEFAULT ('') FOR [BUYERPARTNUMBER]
ALTER TABLE [dbo].[ERFQITEMS] ADD  CONSTRAINT [DF_ERFQITEMS_SUPPID]  DEFAULT ((-1)) FOR [SUPPID]
ALTER TABLE [dbo].[ERFQITEMS] ADD  CONSTRAINT [DF_ERFQITEMS_SUPPPARTNUMBER]  DEFAULT ('') FOR [PARTNUMBER]
ALTER TABLE [dbo].[ERFQITEMS] ADD  CONSTRAINT [DF_ERFQITEMS_SUPPPARTNUMBEREXT]  DEFAULT ('') FOR [PARTNUMBEREXT]
ALTER TABLE [dbo].[ERFQITEMS] ADD  CONSTRAINT [DF_ERFQITEMS_UOM]  DEFAULT ('') FOR [UOM]
ALTER TABLE [dbo].[ERFQITEMS] ADD  CONSTRAINT [DF_ERFQITEMS_QTY]  DEFAULT ((0)) FOR [QTY]
ALTER TABLE [dbo].[ERFQITEMS] ADD  CONSTRAINT [DF_ERFQITEMS_PRICE]  DEFAULT ((0)) FOR [PRICE]
ALTER TABLE [dbo].[ERFQITEMS] ADD  CONSTRAINT [DF_ERFQITEMS_PAYMENTID]  DEFAULT ((-1)) FOR [PAYMENTID]
ALTER TABLE [dbo].[ERFQITEMS] ADD  CONSTRAINT [DF_ERFQITEMS_DELIVERYTOID]  DEFAULT ((-1)) FOR [DLVRID]
ALTER TABLE [dbo].[ERFQITEMS] ADD  CONSTRAINT [DF_ERFQITEMS_INSTRUCTIONS]  DEFAULT ('') FOR [INSTRUCTIONS]
ALTER TABLE [dbo].[ERFQITEMS] ADD  CONSTRAINT [DF_ERFQITEMS_VATPERC]  DEFAULT ((0)) FOR [VATPERC]
ALTER TABLE [dbo].[ERFQITEMS] ADD  CONSTRAINT [DF_ERFQITEMS_PROJECTID]  DEFAULT ((-1)) FOR [PROJECTID]
ALTER TABLE [dbo].[ERFQITEMS] ADD  CONSTRAINT [DF_ERFQITEMS_CONTRACTID]  DEFAULT ((-1)) FOR [CONTRACTID]
ALTER TABLE [dbo].[ERFQITEMS] ADD  CONSTRAINT [DF_ERFQITEMS_MIMETYPE]  DEFAULT ('') FOR [MIMETYPE]
ALTER TABLE [dbo].[ERFQITEMS] ADD  CONSTRAINT [DF_ERFQITEMS_FILESIZEINKB]  DEFAULT ((0)) FOR [FILESIZEINKB]
ALTER TABLE [dbo].[ERFQITEMS] ADD  CONSTRAINT [DF_ERFQITEMS_ORIGINALFILEPATH]  DEFAULT ('') FOR [ORIGINALFILEPATH]
ALTER TABLE [dbo].[ERFQITEMS] ADD  CONSTRAINT [DF_ERFQITEMS_SENDTOSUPP]  DEFAULT ((0)) FOR [SENDTOSUPP]
ALTER TABLE [dbo].[ERFQITEMS] ADD  CONSTRAINT [DF_ERFQITEMS_DIVISIONID]  DEFAULT ((-1)) FOR [DIVISIONID]
ALTER TABLE [dbo].[ERFQITEMS] ADD  CONSTRAINT [DF_ERFQITEMS_RESOURCECODE]  DEFAULT ('') FOR [RESOURCECODE]
ALTER TABLE [dbo].[ERFQITEMS] ADD  CONSTRAINT [DF_ERFQITEMS_FILEPATH]  DEFAULT ('') FOR [FILEPATH]
ALTER TABLE [dbo].[ERFQITEMS] ADD  CONSTRAINT [DF_ERFQITEMS_DISCOUNT]  DEFAULT ((0)) FOR [DISCOUNT]
ALTER TABLE [dbo].[ERFQITEMS] ADD  CONSTRAINT [DF_ERFQITEMS_ERFQITEMSTATUS]  DEFAULT ((163)) FOR [ITEMSTATUSID]
ALTER TABLE [dbo].[ERFQITEMS] ADD  CONSTRAINT [DF_ERFQITEMS_ITEMSTATUSDATE]  DEFAULT (getdate()) FOR [ITEMSTATUSDATE]
ALTER TABLE [dbo].[ERFQITEMS] ADD  CONSTRAINT [DF_ERFQITEMS_ISFREEITEM]  DEFAULT ((0)) FOR [ISFREEITEM]
ALTER TABLE [dbo].[ERFQITEMS] ADD  CONSTRAINT [DF_ERFQITEMS_CATORTENDITEM]  DEFAULT ((1)) FOR [CATORTENDITEM]
ALTER TABLE [dbo].[ERFQITEMS] ADD  CONSTRAINT [DF_ERFQITEMS_GLCODEID]  DEFAULT ((-1)) FOR [GLCODEID]
ALTER TABLE [dbo].[ERFQITEMS] ADD  CONSTRAINT [DF_ERFQITEMS_ACTID]  DEFAULT ((-1)) FOR [ACTID]
ALTER TABLE [dbo].[ERFQITEMS] ADD  CONSTRAINT [DF_ERFQITEMS_ALLOCATION]  DEFAULT ('Contracts') FOR [ALLOCATION]
ALTER TABLE [dbo].[ERFQITEMS] ADD  CONSTRAINT [DF_ERFQITEMS_PENUMBER]  DEFAULT ('') FOR [PENUMBER]
ALTER TABLE [dbo].[ERFQITEMS] ADD  CONSTRAINT [DF_ERFQITEMS_STOCKID]  DEFAULT ((-1)) FOR [STOCKID]
ALTER TABLE [dbo].[ERFQITEMS] ADD  CONSTRAINT [DF__ERFQITEMS__ATTMES__4067D70B]  DEFAULT ('') FOR [ATTMESSAGE]
ALTER TABLE [dbo].[ERFQITEMS] ADD  CONSTRAINT [DF_ERFQITEMS_VATID]  DEFAULT ('Z') FOR [VATID]
ALTER TABLE [dbo].[ERFQITEMS] ADD  CONSTRAINT [DF_ERFQITEMS_TERMS]  DEFAULT ('Current') FOR [TERMS]
ALTER TABLE [dbo].[ERFQITEMS] ADD  CONSTRAINT [DF__ERFQITEMS__EID__57E03940]  DEFAULT ('') FOR [EID]
ALTER TABLE [dbo].[ERFQITEMS] ADD  CONSTRAINT [DF_ERFQITEMS_VATAMOUNT]  DEFAULT ((0)) FOR [VATAMOUNT]
ALTER TABLE [dbo].[ERFQITEMS] ADD  CONSTRAINT [DF_ERFQITEMS_STKCONVERTFLAG]  DEFAULT ((0)) FOR [STKCONVERTFLAG]
ALTER TABLE [dbo].[ERFQITEMS] ADD  CONSTRAINT [DF_ERFQITEMS_NOTE]  DEFAULT ('') FOR [NOTE]
ALTER TABLE [dbo].[ERFQITEMS]  WITH NOCHECK ADD  CONSTRAINT [FK_ERFQITEMS_CONTRACTS] FOREIGN KEY([CONTRACTID])
REFERENCES [dbo].[CONTRACTS] ([CONTRID])
ALTER TABLE [dbo].[ERFQITEMS] NOCHECK CONSTRAINT [FK_ERFQITEMS_CONTRACTS]
ALTER TABLE [dbo].[ERFQITEMS]  WITH NOCHECK ADD  CONSTRAINT [FK_ERFQITEMS_DIVISIONS] FOREIGN KEY([DIVISIONID])
REFERENCES [dbo].[DIVISIONS] ([DivID])
ALTER TABLE [dbo].[ERFQITEMS] NOCHECK CONSTRAINT [FK_ERFQITEMS_DIVISIONS]
ALTER TABLE [dbo].[ERFQITEMS]  WITH CHECK ADD  CONSTRAINT [FK_ERFQITEMS_ERFQ] FOREIGN KEY([ERFQID])
REFERENCES [dbo].[ERFQS] ([ERFQID])
ALTER TABLE [dbo].[ERFQITEMS] CHECK CONSTRAINT [FK_ERFQITEMS_ERFQ]
ALTER TABLE [dbo].[ERFQITEMS]  WITH NOCHECK ADD  CONSTRAINT [FK_ERFQITEMS_INVENTORY] FOREIGN KEY([STOCKID])
REFERENCES [dbo].[INVENTORY] ([StkID])
ALTER TABLE [dbo].[ERFQITEMS] NOCHECK CONSTRAINT [FK_ERFQITEMS_INVENTORY]
ALTER TABLE [dbo].[ERFQITEMS]  WITH NOCHECK ADD  CONSTRAINT [FK_ERFQITEMS_LEDGERCODES] FOREIGN KEY([GLCODEID])
REFERENCES [dbo].[LEDGERCODES] ([LedgerID])
ALTER TABLE [dbo].[ERFQITEMS] NOCHECK CONSTRAINT [FK_ERFQITEMS_LEDGERCODES]
ALTER TABLE [dbo].[ERFQITEMS]  WITH NOCHECK ADD  CONSTRAINT [FK_ERFQITEMS_PLANTANDEQ] FOREIGN KEY([PENUMBER])
REFERENCES [dbo].[PLANTANDEQ] ([PeNumber])
ALTER TABLE [dbo].[ERFQITEMS] NOCHECK CONSTRAINT [FK_ERFQITEMS_PLANTANDEQ]
ALTER TABLE [dbo].[ERFQITEMS]  WITH NOCHECK ADD  CONSTRAINT [FK_ERFQITEMS_PROJECTS] FOREIGN KEY([PROJECTID])
REFERENCES [dbo].[PROJECTS] ([PROJID])
ALTER TABLE [dbo].[ERFQITEMS] NOCHECK CONSTRAINT [FK_ERFQITEMS_PROJECTS]
ALTER TABLE [dbo].[ERFQITEMS]  WITH CHECK ADD  CONSTRAINT [FK_ERFQITEMS_TBORGID] FOREIGN KEY([TBORGID])
REFERENCES [dbo].[BORGS] ([BORGID])
ALTER TABLE [dbo].[ERFQITEMS] CHECK CONSTRAINT [FK_ERFQITEMS_TBORGID]