/****** Object:  Table [dbo].[ERFQSSUPPUPL]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[ERFQSSUPPUPL](
	[LINEID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[INITUPID] [int] NOT NULL,
	[FILEPATH] [nvarchar](255) NOT NULL,
	[SUPPID] [int] NOT NULL,
	[MIMETYPE] [nvarchar](100) NOT NULL,
	[FILESIZEINKB] [int] NOT NULL,
	[ATTTOTALVALUE] [money] NOT NULL,
	[DISCOUNT] [decimal](18, 3) NOT NULL,
	[ORIGINALFILEPATH] [nvarchar](255) NOT NULL,
 CONSTRAINT [PK_ERFQSSUPPUPL] PRIMARY KEY CLUSTERED 
(
	[LINEID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[ERFQSSUPPUPL] ADD  CONSTRAINT [DF_ERFQSSUPPUPL_FILEPATH]  DEFAULT ('') FOR [FILEPATH]
ALTER TABLE [dbo].[ERFQSSUPPUPL] ADD  CONSTRAINT [DF_ERFQSSUPPUPL_MIMETYPE]  DEFAULT ('') FOR [MIMETYPE]
ALTER TABLE [dbo].[ERFQSSUPPUPL] ADD  CONSTRAINT [DF_ERFQSSUPPUPL_FILESIZEINKB]  DEFAULT ((1)) FOR [FILESIZEINKB]
ALTER TABLE [dbo].[ERFQSSUPPUPL] ADD  CONSTRAINT [DF_ERFQSSUPPUPL_ATTTOTALVALUE]  DEFAULT ((0.00)) FOR [ATTTOTALVALUE]
ALTER TABLE [dbo].[ERFQSSUPPUPL] ADD  CONSTRAINT [DF_ERFQSSUPPUPL_DISCOUNT]  DEFAULT ((0.000)) FOR [DISCOUNT]
ALTER TABLE [dbo].[ERFQSSUPPUPL] ADD  CONSTRAINT [DF_ERFQSSUPPUPL_ORIGINALFILEPATH]  DEFAULT ('') FOR [ORIGINALFILEPATH]
ALTER TABLE [dbo].[ERFQSSUPPUPL]  WITH CHECK ADD  CONSTRAINT [FK_ERFQSSUPPUPL_ERFQSINITUPL] FOREIGN KEY([INITUPID])
REFERENCES [dbo].[ERFQSINITUPL] ([LINEID])
ALTER TABLE [dbo].[ERFQSSUPPUPL] CHECK CONSTRAINT [FK_ERFQSSUPPUPL_ERFQSINITUPL]
ALTER TABLE [dbo].[ERFQSSUPPUPL]  WITH CHECK ADD  CONSTRAINT [FK_ERFQSSUPPUPL_SUPPLIERS] FOREIGN KEY([SUPPID])
REFERENCES [dbo].[SUPPLIERS] ([SUPPID])
ALTER TABLE [dbo].[ERFQSSUPPUPL] CHECK CONSTRAINT [FK_ERFQSSUPPUPL_SUPPLIERS]