/****** Object:  Table [dbo].[ERFQSSUPPITEMS]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[ERFQSSUPPITEMS](
	[LINEID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[INITLINEID] [int] NOT NULL,
	[RATE] [money] NOT NULL,
	[SUPPID] [int] NOT NULL,
	[DISCOUNT] [decimal](18, 3) NOT NULL,
	[SUPPREPLIED] [bit] NOT NULL,
	[PREF] [bit] NOT NULL,
 CONSTRAINT [PK_ERFQSSUPPITEMS] PRIMARY KEY CLUSTERED 
(
	[LINEID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[ERFQSSUPPITEMS] ADD  CONSTRAINT [DF_ERFQSSUPPITEMS_RATE]  DEFAULT ((0.00)) FOR [RATE]
ALTER TABLE [dbo].[ERFQSSUPPITEMS] ADD  CONSTRAINT [DF_ERFQSSUPPITEMS_DISCOUNT]  DEFAULT ((0.000)) FOR [DISCOUNT]
ALTER TABLE [dbo].[ERFQSSUPPITEMS] ADD  CONSTRAINT [DF_ERFQSSUPPITEMS_SUPPREPLIED]  DEFAULT ((0)) FOR [SUPPREPLIED]
ALTER TABLE [dbo].[ERFQSSUPPITEMS] ADD  CONSTRAINT [DF_ERFQSINITITEMS_PREF]  DEFAULT ((0)) FOR [PREF]
ALTER TABLE [dbo].[ERFQSSUPPITEMS]  WITH CHECK ADD  CONSTRAINT [FK_ERFQSSUPPITEMS_ERFQSINITITEMS] FOREIGN KEY([INITLINEID])
REFERENCES [dbo].[ERFQSINITITEMS] ([LINEID])
ALTER TABLE [dbo].[ERFQSSUPPITEMS] CHECK CONSTRAINT [FK_ERFQSSUPPITEMS_ERFQSINITITEMS]
ALTER TABLE [dbo].[ERFQSSUPPITEMS]  WITH CHECK ADD  CONSTRAINT [FK_ERFQSSUPPITEMS_SUPPLIERS] FOREIGN KEY([SUPPID])
REFERENCES [dbo].[SUPPLIERS] ([SUPPID])
ALTER TABLE [dbo].[ERFQSSUPPITEMS] CHECK CONSTRAINT [FK_ERFQSSUPPITEMS_SUPPLIERS]