/****** Object:  Table [dbo].[ESTBOQCCRATES]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[ESTBOQCCRATES](
	[ESTID] [int] NOT NULL,
	[ACTNUMBER] [nvarchar](10) NOT NULL,
	[BOQID] [int] NOT NULL,
	[CCR1] [decimal](18, 4) NOT NULL,
	[CCR2] [decimal](18, 4) NOT NULL,
	[CCR3] [decimal](18, 4) NOT NULL,
	[CCR4] [decimal](18, 4) NOT NULL,
	[CCR5] [decimal](18, 4) NOT NULL,
	[CCR6] [decimal](18, 4) NOT NULL,
	[CCR7] [decimal](18, 4) NOT NULL,
	[CCR8] [decimal](18, 4) NOT NULL,
	[CCR9] [decimal](18, 4) NOT NULL,
 CONSTRAINT [PK_ESTBOQCCRATES] PRIMARY KEY CLUSTERED 
(
	[ESTID] ASC,
	[ACTNUMBER] ASC,
	[BOQID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[ESTBOQCCRATES] ADD  CONSTRAINT [DF_ESTBOQCCRATES_CCR1]  DEFAULT (0) FOR [CCR1]
ALTER TABLE [dbo].[ESTBOQCCRATES] ADD  CONSTRAINT [DF_ESTBOQCCRATES_CCR2]  DEFAULT (0) FOR [CCR2]
ALTER TABLE [dbo].[ESTBOQCCRATES] ADD  CONSTRAINT [DF_ESTBOQCCRATES_CCR3]  DEFAULT (0) FOR [CCR3]
ALTER TABLE [dbo].[ESTBOQCCRATES] ADD  CONSTRAINT [DF_ESTBOQCCRATES_CCR4]  DEFAULT (0) FOR [CCR4]
ALTER TABLE [dbo].[ESTBOQCCRATES] ADD  CONSTRAINT [DF_ESTBOQCCRATES_CCR5]  DEFAULT (0) FOR [CCR5]
ALTER TABLE [dbo].[ESTBOQCCRATES] ADD  CONSTRAINT [DF_ESTBOQCCRATES_CCR6]  DEFAULT (0) FOR [CCR6]
ALTER TABLE [dbo].[ESTBOQCCRATES] ADD  CONSTRAINT [DF_ESTBOQCCRATES_CCR7]  DEFAULT (0) FOR [CCR7]
ALTER TABLE [dbo].[ESTBOQCCRATES] ADD  CONSTRAINT [DF_ESTBOQCCRATES_CCR8]  DEFAULT (0) FOR [CCR8]
ALTER TABLE [dbo].[ESTBOQCCRATES] ADD  CONSTRAINT [DF_ESTBOQCCRATES_CCR9]  DEFAULT (0) FOR [CCR9]