/****** Object:  Table [dbo].[ESTBOQRESGRP]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[ESTBOQRESGRP](
	[BOQID] [int] NOT NULL,
	[RESGRPCODE] [nvarchar](10) NOT NULL,
 CONSTRAINT [PK_ESTBOQRESGRP] PRIMARY KEY CLUSTERED 
(
	[BOQID] ASC,
	[RESGRPCODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]