/****** Object:  Table [dbo].[ESTBOQ]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[ESTBOQ](
	[ESTID] [int] NOT NULL,
	[BOQID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[ITEMNO] [bigint] NOT NULL,
	[REF] [nvarchar](20) NOT NULL,
	[ITEMDESCR] [ntext] NOT NULL,
	[UNIT] [nvarchar](25) NOT NULL,
	[COSTRATE] [decimal](18, 4) NOT NULL,
	[SELLRATE] [decimal](18, 4) NOT NULL,
	[BILLEDQTY] [decimal](18, 4) NOT NULL,
	[TOTALQ] [decimal](18, 4) NOT NULL,
	[ESCALGROUP] [nvarchar](6) NOT NULL,
	[ITEMTYPE] [nvarchar](1) NOT NULL,
	[MEM] [ntext] NOT NULL,
	[QTY] [decimal](18, 4) NOT NULL,
	[PAGENO] [int] NOT NULL,
	[ACTNUMBER] [nvarchar](10) NOT NULL,
	[FINALQTY] [decimal](18, 4) NOT NULL,
	[PAYREF] [nvarchar](15) NOT NULL,
	[FORMULA] [nvarchar](500) NOT NULL,
	[FORMULANOTES] [nvarchar](500) NOT NULL,
	[FIXSELLRATE] [bit] NOT NULL,
	[UNBALSELLRATE] [decimal](18, 4) NOT NULL,
	[AUTOTEXT] [bit] NOT NULL,
	[ORGBOQID] [int] NOT NULL,
 CONSTRAINT [PK_ESTBOQ] PRIMARY KEY CLUSTERED 
(
	[BOQID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

CREATE NONCLUSTERED INDEX [IX_ESTBOQ_ESTID_ITEMNO] ON [dbo].[ESTBOQ]
(
	[ESTID] ASC,
	[ITEMNO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
ALTER TABLE [dbo].[ESTBOQ] ADD  CONSTRAINT [DF_ESTBOQ_ITEMNO]  DEFAULT (1) FOR [ITEMNO]
ALTER TABLE [dbo].[ESTBOQ] ADD  CONSTRAINT [DF_ESTBOQ_REF]  DEFAULT ('') FOR [REF]
ALTER TABLE [dbo].[ESTBOQ] ADD  CONSTRAINT [DF_ESTBOQ_ITEMDESCR]  DEFAULT ('') FOR [ITEMDESCR]
ALTER TABLE [dbo].[ESTBOQ] ADD  CONSTRAINT [DF_ESTBOQ_UNIT]  DEFAULT ('') FOR [UNIT]
ALTER TABLE [dbo].[ESTBOQ] ADD  CONSTRAINT [DF_ESTBOQ_COSTRATE]  DEFAULT (0) FOR [COSTRATE]
ALTER TABLE [dbo].[ESTBOQ] ADD  CONSTRAINT [DF_ESTBOQ_ITEMRATE]  DEFAULT (0) FOR [SELLRATE]
ALTER TABLE [dbo].[ESTBOQ] ADD  CONSTRAINT [DF_ESTBOQ_BILLEDQTY]  DEFAULT (0) FOR [BILLEDQTY]
ALTER TABLE [dbo].[ESTBOQ] ADD  CONSTRAINT [DF_ESTBOQ_TOTALQ]  DEFAULT (0) FOR [TOTALQ]
ALTER TABLE [dbo].[ESTBOQ] ADD  CONSTRAINT [DF_ESTBOQ_ESCALGROUP]  DEFAULT ('') FOR [ESCALGROUP]
ALTER TABLE [dbo].[ESTBOQ] ADD  CONSTRAINT [DF_ESTBOQ_ITEMTYPE]  DEFAULT ('A') FOR [ITEMTYPE]
ALTER TABLE [dbo].[ESTBOQ] ADD  CONSTRAINT [DF_ESTBOQ_MEM]  DEFAULT ('') FOR [MEM]
ALTER TABLE [dbo].[ESTBOQ] ADD  CONSTRAINT [DF_ESTBOQ_QTY]  DEFAULT (0) FOR [QTY]
ALTER TABLE [dbo].[ESTBOQ] ADD  CONSTRAINT [DF_ESTBOQ_PAGENO]  DEFAULT (1) FOR [PAGENO]
ALTER TABLE [dbo].[ESTBOQ] ADD  CONSTRAINT [DF_ESTBOQ_ACTNUMBER_BS]  DEFAULT ('') FOR [ACTNUMBER]
ALTER TABLE [dbo].[ESTBOQ] ADD  CONSTRAINT [DF_ESTBOQ_FINALQTY]  DEFAULT (0) FOR [FINALQTY]
ALTER TABLE [dbo].[ESTBOQ] ADD  CONSTRAINT [DF_ESTBOQ_PAYREF]  DEFAULT ('') FOR [PAYREF]
ALTER TABLE [dbo].[ESTBOQ] ADD  CONSTRAINT [DF_ESTBOQ_FORMULA]  DEFAULT ('') FOR [FORMULA]
ALTER TABLE [dbo].[ESTBOQ] ADD  CONSTRAINT [DF_ESTBOQ_FORMULANOTES]  DEFAULT ('') FOR [FORMULANOTES]
ALTER TABLE [dbo].[ESTBOQ] ADD  CONSTRAINT [DF_ESTBOQ_FIXSELLRATE]  DEFAULT (0) FOR [FIXSELLRATE]
ALTER TABLE [dbo].[ESTBOQ] ADD  CONSTRAINT [DF_ESTBOQ_UNBALSELLRATE]  DEFAULT (0) FOR [UNBALSELLRATE]
ALTER TABLE [dbo].[ESTBOQ] ADD  CONSTRAINT [DF_ESTBOQ_AUTOTEXT]  DEFAULT (1) FOR [AUTOTEXT]
ALTER TABLE [dbo].[ESTBOQ] ADD  CONSTRAINT [DF_ESTBOQ_ORGBOQID]  DEFAULT (0) FOR [ORGBOQID]
ALTER TABLE [dbo].[ESTBOQ]  WITH CHECK ADD  CONSTRAINT [FK_ESTBOQ_ESTIMATES] FOREIGN KEY([ESTID])
REFERENCES [dbo].[ESTIMATES] ([ESTID])
ALTER TABLE [dbo].[ESTBOQ] CHECK CONSTRAINT [FK_ESTBOQ_ESTIMATES]