/****** Object:  Table [dbo].[ESTCLRATES]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[ESTCLRATES](
	[ESTID] [int] NOT NULL,
	[CLCODE] [nvarchar](10) NOT NULL,
	[RATE] [decimal](18, 2) NOT NULL,
	[CCA1] [decimal](18, 2) NOT NULL,
	[CCA2] [decimal](18, 2) NOT NULL,
	[CCA3] [decimal](18, 2) NOT NULL,
	[CCA4] [decimal](18, 2) NOT NULL,
	[CCA5] [decimal](18, 2) NOT NULL,
	[CCA6] [decimal](18, 2) NOT NULL,
	[CCA7] [decimal](18, 2) NOT NULL,
	[CCA8] [decimal](18, 2) NOT NULL,
	[CCA9] [decimal](18, 2) NOT NULL,
 CONSTRAINT [PK_ESTCLRATES] PRIMARY KEY CLUSTERED 
(
	[ESTID] ASC,
	[CLCODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[ESTCLRATES] ADD  CONSTRAINT [DF_ESTCLRATES_RATE]  DEFAULT (0) FOR [RATE]
ALTER TABLE [dbo].[ESTCLRATES] ADD  CONSTRAINT [DF_ESTCLRATES_CCA1]  DEFAULT (0) FOR [CCA1]
ALTER TABLE [dbo].[ESTCLRATES] ADD  CONSTRAINT [DF_ESTCLRATES_CCA2]  DEFAULT (0) FOR [CCA2]
ALTER TABLE [dbo].[ESTCLRATES] ADD  CONSTRAINT [DF_ESTCLRATES_CCA3]  DEFAULT (0) FOR [CCA3]
ALTER TABLE [dbo].[ESTCLRATES] ADD  CONSTRAINT [DF_ESTCLRATES_CCA4]  DEFAULT (0) FOR [CCA4]
ALTER TABLE [dbo].[ESTCLRATES] ADD  CONSTRAINT [DF_ESTCLRATES_CCA5]  DEFAULT (0) FOR [CCA5]
ALTER TABLE [dbo].[ESTCLRATES] ADD  CONSTRAINT [DF_ESTCLRATES_CCA6]  DEFAULT (0) FOR [CCA6]
ALTER TABLE [dbo].[ESTCLRATES] ADD  CONSTRAINT [DF_ESTCLRATES_CCA7]  DEFAULT (0) FOR [CCA7]
ALTER TABLE [dbo].[ESTCLRATES] ADD  CONSTRAINT [DF_ESTCLRATES_CCA8]  DEFAULT (0) FOR [CCA8]
ALTER TABLE [dbo].[ESTCLRATES] ADD  CONSTRAINT [DF_ESTCLRATES_CCA9]  DEFAULT (0) FOR [CCA9]