/****** Object:  Table [dbo].[ESTCLRES]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[ESTCLRES](
	[ESTID] [int] NOT NULL,
	[CLCODE] [nvarchar](10) NOT NULL,
	[RESCODE] [nvarchar](10) NOT NULL,
	[NOOFF] [decimal](18, 4) NOT NULL,
	[PROD] [decimal](18, 4) NOT NULL,
	[CLRESID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[FAKEID] [int] NOT NULL,
 CONSTRAINT [PK_ESTCLRES] PRIMARY KEY CLUSTERED 
(
	[ESTID] ASC,
	[CLCODE] ASC,
	[RESCODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[ESTCLRES] ADD  CONSTRAINT [DF_ESTCLRES_NOOFF]  DEFAULT (0) FOR [NOOFF]
ALTER TABLE [dbo].[ESTCLRES] ADD  CONSTRAINT [DF_ESTCLRES_PROD]  DEFAULT (0) FOR [PROD]
ALTER TABLE [dbo].[ESTCLRES] ADD  CONSTRAINT [DF_ESTCLRES_FAKEID]  DEFAULT (0) FOR [FAKEID]