/****** Object:  Table [dbo].[ESTCLUSTERS]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[ESTCLUSTERS](
	[CLCODE] [nvarchar](10) NOT NULL,
	[CLNAME] [nvarchar](70) NOT NULL,
	[UNIT] [nvarchar](4) NOT NULL,
	[CLSUBCODE] [nvarchar](10) NOT NULL,
	[NOTES] [ntext] NOT NULL,
	[LASTMOD] [datetime] NOT NULL,
	[LASTMODUSERID] [int] NOT NULL,
 CONSTRAINT [PK_ESTCLUSTERS] PRIMARY KEY CLUSTERED 
(
	[CLCODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

ALTER TABLE [dbo].[ESTCLUSTERS] ADD  CONSTRAINT [DF_ESTCLUSTERS_CLNAME]  DEFAULT ('') FOR [CLNAME]
ALTER TABLE [dbo].[ESTCLUSTERS] ADD  CONSTRAINT [DF_ESTCLUSTERS_UNIT]  DEFAULT ('') FOR [UNIT]
ALTER TABLE [dbo].[ESTCLUSTERS] ADD  CONSTRAINT [DF_ESTCLUSTERS_CLSUBCODE]  DEFAULT ('') FOR [CLSUBCODE]
ALTER TABLE [dbo].[ESTCLUSTERS] ADD  CONSTRAINT [DF_ESTCLUSTERS_NOTES]  DEFAULT ('') FOR [NOTES]
ALTER TABLE [dbo].[ESTCLUSTERS] ADD  CONSTRAINT [DF_ESTCLUSTERS_LASTMOD]  DEFAULT (getdate()) FOR [LASTMOD]
ALTER TABLE [dbo].[ESTCLUSTERS] ADD  CONSTRAINT [DF_ESTCLUSTERS_LASTMODUSERID]  DEFAULT ((-1)) FOR [LASTMODUSERID]