/****** Object:  Table [dbo].[ESTRESSUPP]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[ESTRESSUPP](
	[ESTID] [int] NOT NULL,
	[RESCODE] [nvarchar](10) NOT NULL,
	[SUPPCODE] [nchar](10) NOT NULL,
	[BASICRATE] [decimal](18, 4) NOT NULL,
	[FINALRATE] [decimal](18, 4) NOT NULL,
	[TRADEDISC] [decimal](18, 4) NOT NULL,
	[LASTMOD] [datetime] NOT NULL,
	[LASTMODUSERID] [int] NOT NULL,
	[FACT1] [decimal](18, 4) NOT NULL,
	[FACT2] [decimal](18, 4) NOT NULL,
	[FACT3] [decimal](18, 4) NOT NULL,
	[FACT4] [decimal](18, 4) NOT NULL,
	[FACT5] [decimal](18, 4) NOT NULL,
	[FACT6] [decimal](18, 4) NOT NULL,
	[FACT7] [decimal](18, 4) NOT NULL,
	[FACT8] [decimal](18, 4) NOT NULL,
	[FACT9] [decimal](18, 4) NOT NULL,
	[FTYPE1] [char](1) NOT NULL,
	[FTYPE2] [char](1) NOT NULL,
	[FTYPE3] [char](1) NOT NULL,
	[FTYPE4] [char](1) NOT NULL,
	[FTYPE5] [char](1) NOT NULL,
	[FTYPE6] [char](1) NOT NULL,
	[FTYPE7] [char](1) NOT NULL,
	[FTYPE8] [char](1) NOT NULL,
	[FTYPE9] [char](1) NOT NULL,
	[FNAME1] [nvarchar](15) NOT NULL,
	[FNAME2] [nvarchar](15) NOT NULL,
	[FNAME3] [nvarchar](15) NOT NULL,
	[FNAME4] [nvarchar](15) NOT NULL,
	[FNAME5] [nvarchar](15) NOT NULL,
	[FNAME6] [nvarchar](15) NOT NULL,
	[FNAME7] [nvarchar](15) NOT NULL,
	[FNAME8] [nvarchar](15) NOT NULL,
	[FNAME9] [nvarchar](15) NOT NULL,
	[FAMNT1] [decimal](18, 4) NOT NULL,
	[FAMNT2] [decimal](18, 4) NOT NULL,
	[FAMNT3] [decimal](18, 4) NOT NULL,
	[FAMNT4] [decimal](18, 4) NOT NULL,
	[FAMNT5] [decimal](18, 4) NOT NULL,
	[FAMNT6] [decimal](18, 4) NOT NULL,
	[FAMNT7] [decimal](18, 4) NOT NULL,
	[FAMNT8] [decimal](18, 4) NOT NULL,
	[FAMNT9] [decimal](18, 4) NOT NULL,
 CONSTRAINT [PK_ESTRESSUPP] PRIMARY KEY CLUSTERED 
(
	[ESTID] ASC,
	[RESCODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[ESTRESSUPP] ADD  CONSTRAINT [DF_ESTRESSUPP_BASICRATE]  DEFAULT (0) FOR [BASICRATE]
ALTER TABLE [dbo].[ESTRESSUPP] ADD  CONSTRAINT [DF_ESTRESSUPP_FINALRATE]  DEFAULT (0) FOR [FINALRATE]
ALTER TABLE [dbo].[ESTRESSUPP] ADD  CONSTRAINT [DF_ESTRESSUPP_TRADEDISC]  DEFAULT (0) FOR [TRADEDISC]
ALTER TABLE [dbo].[ESTRESSUPP] ADD  CONSTRAINT [DF_ESTRESSUPP_LASTMOD]  DEFAULT (getdate()) FOR [LASTMOD]
ALTER TABLE [dbo].[ESTRESSUPP] ADD  CONSTRAINT [DF_ESTRESSUPP_LASTMODUSERID]  DEFAULT ((-1)) FOR [LASTMODUSERID]
ALTER TABLE [dbo].[ESTRESSUPP] ADD  CONSTRAINT [DF_ESTRESSUPP_FACT1]  DEFAULT (0) FOR [FACT1]
ALTER TABLE [dbo].[ESTRESSUPP] ADD  CONSTRAINT [DF_ESTRESSUPP_FACT2]  DEFAULT (0) FOR [FACT2]
ALTER TABLE [dbo].[ESTRESSUPP] ADD  CONSTRAINT [DF_ESTRESSUPP_FACT3]  DEFAULT (0) FOR [FACT3]
ALTER TABLE [dbo].[ESTRESSUPP] ADD  CONSTRAINT [DF_ESTRESSUPP_FACT4]  DEFAULT (0) FOR [FACT4]
ALTER TABLE [dbo].[ESTRESSUPP] ADD  CONSTRAINT [DF_ESTRESSUPP_FACT5]  DEFAULT (0) FOR [FACT5]
ALTER TABLE [dbo].[ESTRESSUPP] ADD  CONSTRAINT [DF_ESTRESSUPP_FACT6]  DEFAULT (0) FOR [FACT6]
ALTER TABLE [dbo].[ESTRESSUPP] ADD  CONSTRAINT [DF_ESTRESSUPP_FACT7]  DEFAULT (0) FOR [FACT7]
ALTER TABLE [dbo].[ESTRESSUPP] ADD  CONSTRAINT [DF_ESTRESSUPP_FACT8]  DEFAULT (0) FOR [FACT8]
ALTER TABLE [dbo].[ESTRESSUPP] ADD  CONSTRAINT [DF_ESTRESSUPP_FACT9]  DEFAULT (0) FOR [FACT9]
ALTER TABLE [dbo].[ESTRESSUPP] ADD  CONSTRAINT [DF_ESTRESSUPP_FTYPE1]  DEFAULT ('') FOR [FTYPE1]
ALTER TABLE [dbo].[ESTRESSUPP] ADD  CONSTRAINT [DF_ESTRESSUPP_FTYPE2]  DEFAULT ('') FOR [FTYPE2]
ALTER TABLE [dbo].[ESTRESSUPP] ADD  CONSTRAINT [DF_ESTRESSUPP_FTYPE3]  DEFAULT ('') FOR [FTYPE3]
ALTER TABLE [dbo].[ESTRESSUPP] ADD  CONSTRAINT [DF_ESTRESSUPP_FTYPE4]  DEFAULT ('') FOR [FTYPE4]
ALTER TABLE [dbo].[ESTRESSUPP] ADD  CONSTRAINT [DF_ESTRESSUPP_FTYPE5]  DEFAULT ('') FOR [FTYPE5]
ALTER TABLE [dbo].[ESTRESSUPP] ADD  CONSTRAINT [DF_ESTRESSUPP_FTYPE6]  DEFAULT ('') FOR [FTYPE6]
ALTER TABLE [dbo].[ESTRESSUPP] ADD  CONSTRAINT [DF_ESTRESSUPP_FTYPE7]  DEFAULT ('') FOR [FTYPE7]
ALTER TABLE [dbo].[ESTRESSUPP] ADD  CONSTRAINT [DF_ESTRESSUPP_FTYPE8]  DEFAULT ('') FOR [FTYPE8]
ALTER TABLE [dbo].[ESTRESSUPP] ADD  CONSTRAINT [DF_ESTRESSUPP_FTYPE9]  DEFAULT ('') FOR [FTYPE9]
ALTER TABLE [dbo].[ESTRESSUPP] ADD  CONSTRAINT [DF_ESTRESSUPP_FNAME1]  DEFAULT ('') FOR [FNAME1]
ALTER TABLE [dbo].[ESTRESSUPP] ADD  CONSTRAINT [DF_ESTRESSUPP_FNAME2]  DEFAULT ('') FOR [FNAME2]
ALTER TABLE [dbo].[ESTRESSUPP] ADD  CONSTRAINT [DF_ESTRESSUPP_FNAME3]  DEFAULT ('') FOR [FNAME3]
ALTER TABLE [dbo].[ESTRESSUPP] ADD  CONSTRAINT [DF_ESTRESSUPP_FNAME4]  DEFAULT ('') FOR [FNAME4]
ALTER TABLE [dbo].[ESTRESSUPP] ADD  CONSTRAINT [DF_ESTRESSUPP_FNAME5]  DEFAULT ('') FOR [FNAME5]
ALTER TABLE [dbo].[ESTRESSUPP] ADD  CONSTRAINT [DF_ESTRESSUPP_FNAME6]  DEFAULT ('') FOR [FNAME6]
ALTER TABLE [dbo].[ESTRESSUPP] ADD  CONSTRAINT [DF_ESTRESSUPP_FNAME7]  DEFAULT ('') FOR [FNAME7]
ALTER TABLE [dbo].[ESTRESSUPP] ADD  CONSTRAINT [DF_ESTRESSUPP_FNAME8]  DEFAULT ('') FOR [FNAME8]
ALTER TABLE [dbo].[ESTRESSUPP] ADD  CONSTRAINT [DF_ESTRESSUPP_FNAME9]  DEFAULT ('') FOR [FNAME9]
ALTER TABLE [dbo].[ESTRESSUPP] ADD  CONSTRAINT [DF_ESTRESSUPP_FAMNT1]  DEFAULT (0) FOR [FAMNT1]
ALTER TABLE [dbo].[ESTRESSUPP] ADD  CONSTRAINT [DF_ESTRESSUPP_FAMNT2]  DEFAULT (0) FOR [FAMNT2]
ALTER TABLE [dbo].[ESTRESSUPP] ADD  CONSTRAINT [DF_ESTRESSUPP_FAMNT3]  DEFAULT (0) FOR [FAMNT3]
ALTER TABLE [dbo].[ESTRESSUPP] ADD  CONSTRAINT [DF_ESTRESSUPP_FAMNT4]  DEFAULT (0) FOR [FAMNT4]
ALTER TABLE [dbo].[ESTRESSUPP] ADD  CONSTRAINT [DF_ESTRESSUPP_FAMNT5]  DEFAULT (0) FOR [FAMNT5]
ALTER TABLE [dbo].[ESTRESSUPP] ADD  CONSTRAINT [DF_ESTRESSUPP_FAMNT6]  DEFAULT (0) FOR [FAMNT6]
ALTER TABLE [dbo].[ESTRESSUPP] ADD  CONSTRAINT [DF_ESTRESSUPP_FAMNT7]  DEFAULT (0) FOR [FAMNT7]
ALTER TABLE [dbo].[ESTRESSUPP] ADD  CONSTRAINT [DF_ESTRESSUPP_FAMNT8]  DEFAULT (0) FOR [FAMNT8]
ALTER TABLE [dbo].[ESTRESSUPP] ADD  CONSTRAINT [DF_ESTRESSUPP_FAMNT9]  DEFAULT (0) FOR [FAMNT9]