/****** Object:  Table [dbo].[ESTRES]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[ESTRES](
	[RESCODE] [nvarchar](10) NOT NULL,
	[RESNAME] [nvarchar](70) NOT NULL,
	[UNIT] [nvarchar](25) NOT NULL,
	[RESRATE] [decimal](18, 4) NOT NULL,
	[GLCODE] [char](10) NOT NULL,
	[MVALUE] [decimal](18, 4) NOT NULL,
	[MUNIT] [nvarchar](25) NOT NULL,
	[MRATE] [decimal](18, 4) NOT NULL,
	[LONGDESCR] [nvarchar](750) NOT NULL,
	[COSTCOL] [smallint] NOT NULL,
 CONSTRAINT [PK_ESTRESURSES] PRIMARY KEY CLUSTERED 
(
	[RESCODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[ESTRES] ADD  CONSTRAINT [DF_ESTRES_RESNAME]  DEFAULT ('') FOR [RESNAME]
ALTER TABLE [dbo].[ESTRES] ADD  CONSTRAINT [DF_ESTRES_UNIT]  DEFAULT ('') FOR [UNIT]
ALTER TABLE [dbo].[ESTRES] ADD  CONSTRAINT [DF_ESTRES_RESRATE]  DEFAULT (0) FOR [RESRATE]
ALTER TABLE [dbo].[ESTRES] ADD  CONSTRAINT [DF_ESTRES_GLCODE]  DEFAULT ('') FOR [GLCODE]
ALTER TABLE [dbo].[ESTRES] ADD  CONSTRAINT [DF_ESTRES_MVALUE]  DEFAULT (0) FOR [MVALUE]
ALTER TABLE [dbo].[ESTRES] ADD  CONSTRAINT [DF_ESTRES_MUNIT]  DEFAULT ('') FOR [MUNIT]
ALTER TABLE [dbo].[ESTRES] ADD  CONSTRAINT [DF_ESTRES_MRATE]  DEFAULT (0) FOR [MRATE]
ALTER TABLE [dbo].[ESTRES] ADD  CONSTRAINT [DF_ESTRES_LONGDESCR]  DEFAULT ('') FOR [LONGDESCR]
ALTER TABLE [dbo].[ESTRES] ADD  CONSTRAINT [DF_ESTRES_COSTCOL]  DEFAULT ((-1)) FOR [COSTCOL]