/****** Object:  Table [dbo].[ETBATCHDETAIL]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[ETBATCHDETAIL](
	[DETAILID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[HEADERID] [int] NOT NULL,
	[EMPNUMBER] [nvarchar](15) NOT NULL,
	[TOBETERMDATE] [datetime] NOT NULL,
	[STATUSCODE] [nvarchar](5) NOT NULL,
	[TPAYROLLID] [int] NULL,
 CONSTRAINT [PK_ETBATCHDETAIL] PRIMARY KEY CLUSTERED 
(
	[DETAILID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]