/****** Object:  Table [dbo].[ETBATCHHEADER]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[ETBATCHHEADER](
	[HEADERID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[SITEREF] [char](50) NOT NULL,
	[BATCHREF] [char](50) NOT NULL,
	[PAYROLLID] [int] NOT NULL,
	[LOCKHOLDER] [int] NOT NULL,
	[LOCKREQUESTOR] [int] NOT NULL,
	[VALID] [bit] NOT NULL,
	[POSTED] [bit] NOT NULL,
	[USEHASHEMPLOYEES] [bit] NOT NULL,
	[USEHASHRECORDS] [bit] NOT NULL,
	[TOTEMPLOYEES] [float] NULL,
	[TOTRECORDS] [float] NULL,
 CONSTRAINT [PK_ETBATCHHEADER] PRIMARY KEY CLUSTERED 
(
	[HEADERID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[ETBATCHHEADER] ADD  CONSTRAINT [DF_ETBATCHHEADER_LOCKHOLDER]  DEFAULT ((0)) FOR [LOCKHOLDER]
ALTER TABLE [dbo].[ETBATCHHEADER] ADD  CONSTRAINT [DF_ETBATCHHEADER_LockRequestor]  DEFAULT ((0)) FOR [LOCKREQUESTOR]
ALTER TABLE [dbo].[ETBATCHHEADER] ADD  CONSTRAINT [DF_ETBATCHHEADER_VALID]  DEFAULT ((0)) FOR [VALID]
ALTER TABLE [dbo].[ETBATCHHEADER] ADD  CONSTRAINT [DF_ETBATCHHEADER_POSTED]  DEFAULT ((0)) FOR [POSTED]
ALTER TABLE [dbo].[ETBATCHHEADER] ADD  CONSTRAINT [DF_ETBATCHHEADER_USEHASHEMPLOYEES]  DEFAULT ((0)) FOR [USEHASHEMPLOYEES]
ALTER TABLE [dbo].[ETBATCHHEADER] ADD  CONSTRAINT [DF_ETBATCHHEADER_USEHASHRECORDS]  DEFAULT ((0)) FOR [USEHASHRECORDS]
ALTER TABLE [dbo].[ETBATCHHEADER]  WITH CHECK ADD  CONSTRAINT [FK_ETBATCHDETAIL_ETBATCHHEADER] FOREIGN KEY([HEADERID])
REFERENCES [dbo].[ETBATCHHEADER] ([HEADERID])
ALTER TABLE [dbo].[ETBATCHHEADER] CHECK CONSTRAINT [FK_ETBATCHDETAIL_ETBATCHHEADER]