/****** Object:  Table [dbo].[FINVENTORY]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[FINVENTORY](
	[StkStore] [char](15) NOT NULL,
	[StkCode] [char](20) NOT NULL,
	[StkDesc] [char](250) NULL,
	[StkUnit] [char](8) NULL,
	[StkBin] [char](10) NULL,
	[StkQuantity] [numeric](18, 4) NOT NULL,
	[StkCostRate] [money] NOT NULL,
	[MUMethod] [int] NULL,
	[MUValue] [numeric](18, 0) NULL,
	[StkSellRate] [money] NOT NULL,
	[StkGLCode] [char](10) NULL,
	[StkMaxBal] [numeric](18, 0) NOT NULL,
	[StkMinBal] [numeric](18, 0) NOT NULL,
	[BorgID] [int] NOT NULL,
	[StkID] [int] IDENTITY(1,1) NOT NULL,
	[ToJoinI] [int] NOT NULL,
	[StkHireRate] [money] NOT NULL,
	[StkStatus] [int] NOT NULL,
	[STKSTKTAKE] [numeric](18, 4) NOT NULL,
	[STKSHEET] [char](10) NOT NULL,
	[STKWEIGHT] [numeric](18, 4) NOT NULL,
	[STKWEIGHTUNIT] [char](10) NOT NULL,
	[STKSELLUNIT] [char](10) NOT NULL,
	[STKSELLCONV] [numeric](18, 4) NOT NULL,
	[STKBUYUNIT] [char](10) NOT NULL,
	[STKBUYCONV] [numeric](18, 4) NOT NULL,
	[STKSUPPCODE] [char](10) NOT NULL,
	[STKBUYCOST] [money] NOT NULL,
	[STKBUYDATE] [datetime] NULL,
	[STKSELLDATE] [datetime] NULL,
	[STKSELECT] [char](5) NOT NULL,
	[StkSuppProdCode] [char](20) NOT NULL,
	[OB1] [numeric](18, 4) NOT NULL,
	[OB2] [numeric](18, 4) NOT NULL,
	[OB3] [numeric](18, 4) NOT NULL,
	[OB4] [numeric](18, 4) NOT NULL,
	[OB5] [numeric](18, 4) NOT NULL,
	[OB6] [numeric](18, 4) NOT NULL,
	[OB7] [numeric](18, 4) NOT NULL,
	[OB8] [numeric](18, 4) NOT NULL,
	[OB9] [numeric](18, 4) NOT NULL,
	[OB10] [numeric](18, 4) NOT NULL,
	[OB11] [numeric](18, 4) NOT NULL,
	[OB12] [numeric](18, 4) NOT NULL,
	[OPENINGBALANCE] [numeric](18, 4) NOT NULL,
	[STKDEFGL] [char](10) NOT NULL,
	[StkDefAct] [char](10) NOT NULL,
	[StkConvertFlag] [bit] NOT NULL,
	[SerialType] [int] NOT NULL,
	[STKSTKTAKERATE] [decimal](18, 4) NOT NULL,
	[STKSHEETRATE] [nvarchar](10) NOT NULL,
	[DIVID] [int] NOT NULL
) ON [PRIMARY]