/****** Object:  Table [dbo].[GANGBONUSSET]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[GANGBONUSSET](
	[PKLGANGBONUSSETID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[PAYROLLID] [int] NOT NULL,
	[GANGCODE] [nvarchar](10) NOT NULL,
	[BONUS] [decimal](18, 4) NOT NULL,
	[PERIODNO] [int] NOT NULL,
	[YEARNO] [int] NOT NULL,
	[CONTRNUMBER] [nvarchar](10) NOT NULL,
 CONSTRAINT [PK_GANGBONUSSET] PRIMARY KEY CLUSTERED 
(
	[PKLGANGBONUSSETID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[GANGBONUSSET] ADD  DEFAULT ('') FOR [CONTRNUMBER]