/****** Object:  Table [dbo].[HIREDATARATEHISTORY]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[HIREDATARATEHISTORY](
	[ID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[ORGID] [int] NOT NULL,
	[YEAR] [int] NOT NULL,
	[PERIOD] [int] NOT NULL,
	[CONTRACT] [nvarchar](10) NOT NULL,
	[DEBTOR] [nvarchar](10) NOT NULL,
	[STORE] [nvarchar](15) NOT NULL,
	[STOCK] [nvarchar](20) NOT NULL,
	[RATE] [decimal](18, 4) NOT NULL,
	[VATID] [char](2) NOT NULL,
	[VATPERC] [decimal](18, 4) NOT NULL,
 CONSTRAINT [PK_HIREDATARATEHISTORY] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[HIREDATARATEHISTORY] ADD  CONSTRAINT [DF_HIREDATARATEHISTORY_ORGID]  DEFAULT ((0)) FOR [ORGID]
ALTER TABLE [dbo].[HIREDATARATEHISTORY] ADD  CONSTRAINT [DF_HIREDATARATEHISTORY_YEAR]  DEFAULT ((0)) FOR [YEAR]
ALTER TABLE [dbo].[HIREDATARATEHISTORY] ADD  CONSTRAINT [DF_HIREDATARATEHISTORY_PERIOD]  DEFAULT ((0)) FOR [PERIOD]
ALTER TABLE [dbo].[HIREDATARATEHISTORY] ADD  CONSTRAINT [DF_HIREDATARATEHISTORY_CONTRACT]  DEFAULT ('') FOR [CONTRACT]
ALTER TABLE [dbo].[HIREDATARATEHISTORY] ADD  CONSTRAINT [DF_HIREDATARATEHISTORY_DEBTOR]  DEFAULT ('') FOR [DEBTOR]
ALTER TABLE [dbo].[HIREDATARATEHISTORY] ADD  CONSTRAINT [DF_HIREDATARATEHISTORY_STORE]  DEFAULT ('') FOR [STORE]
ALTER TABLE [dbo].[HIREDATARATEHISTORY] ADD  CONSTRAINT [DF_HIREDATARATEHISTORY_STOCK]  DEFAULT ('') FOR [STOCK]
ALTER TABLE [dbo].[HIREDATARATEHISTORY] ADD  CONSTRAINT [DF_HIREDATARATEHISTORY_RATE]  DEFAULT ((0)) FOR [RATE]
ALTER TABLE [dbo].[HIREDATARATEHISTORY] ADD  CONSTRAINT [DF_HIREDATARATEHISTORY_VATID]  DEFAULT ('') FOR [VATID]
ALTER TABLE [dbo].[HIREDATARATEHISTORY] ADD  CONSTRAINT [DF_HIREDATARATEHISTORY_VATPERC]  DEFAULT ((-1)) FOR [VATPERC]