/****** Object:  Table [dbo].[HIREDATA]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[HIREDATA](
	[TransID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[RateUsed] [money] NOT NULL,
	[NoteNo] [char](15) NOT NULL,
	[InvNo] [char](20) NOT NULL,
	[Quantity] [numeric](18, 0) NOT NULL,
	[Site] [nvarchar](10) NOT NULL,
	[glcode] [char](10) NOT NULL,
	[SEQ] [int] NOT NULL,
	[FROMACT] [nvarchar](10) NOT NULL,
	[TOACT] [nvarchar](10) NOT NULL,
 CONSTRAINT [PK_HIREDATA] PRIMARY KEY CLUSTERED 
(
	[TransID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[HIREDATA] ADD  CONSTRAINT [DF_HIREDATA_RateUsed]  DEFAULT (0) FOR [RateUsed]
ALTER TABLE [dbo].[HIREDATA] ADD  CONSTRAINT [DF_HIREDATA_HeadID]  DEFAULT ('') FOR [NoteNo]
ALTER TABLE [dbo].[HIREDATA] ADD  CONSTRAINT [DF_HIREDATA_InvNo]  DEFAULT ('') FOR [InvNo]
ALTER TABLE [dbo].[HIREDATA] ADD  CONSTRAINT [DF_HIREDATA_Quantity]  DEFAULT (0) FOR [Quantity]
ALTER TABLE [dbo].[HIREDATA] ADD  CONSTRAINT [DF_HIREDATA_Site_1]  DEFAULT ('') FOR [Site]
ALTER TABLE [dbo].[HIREDATA] ADD  CONSTRAINT [DF_HIREDATA_glcode]  DEFAULT ('') FOR [glcode]
ALTER TABLE [dbo].[HIREDATA] ADD  CONSTRAINT [DF__HIREDATA__SEQ__6781A42C]  DEFAULT (1) FOR [SEQ]
ALTER TABLE [dbo].[HIREDATA] ADD  CONSTRAINT [DF_HIREDATA_FROMACT]  DEFAULT ('') FOR [FROMACT]
ALTER TABLE [dbo].[HIREDATA] ADD  CONSTRAINT [DF_HIREDATA_TOACT]  DEFAULT ('') FOR [TOACT]