/****** Object:  Table [dbo].[HIREDATAHEADER]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[HIREDATAHEADER](
	[NoteNo] [char](15) NOT NULL,
	[TransDate] [datetime] NULL,
	[FromSite] [nvarchar](10) NOT NULL,
	[ToSite] [nvarchar](10) NOT NULL,
	[Debtor] [char](10) NOT NULL,
	[HeadID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[BorgID] [int] NOT NULL,
	[Posted] [bit] NOT NULL,
	[Year] [char](10) NOT NULL,
	[Period] [int] NOT NULL,
	[UserID] [int] NOT NULL,
	[CAPTPERIOD] [int] NOT NULL,
	[ACTIVITY] [char](10) NOT NULL,
	[STORE] [char](15) NOT NULL,
	[DIVISION] [int] NOT NULL,
	[TRANSFERNOTE] [nvarchar](250) NOT NULL,
	[OHLEDGERCODE] [nvarchar](10) NOT NULL,
 CONSTRAINT [PK_HIREDATAHEADER] PRIMARY KEY CLUSTERED 
(
	[NoteNo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[HIREDATAHEADER] ADD  CONSTRAINT [DF_HIREDATAHEADER_NoteNo]  DEFAULT ('') FOR [NoteNo]
ALTER TABLE [dbo].[HIREDATAHEADER] ADD  CONSTRAINT [DF_HIREDATAHEADER_FromSite]  DEFAULT ('') FOR [FromSite]
ALTER TABLE [dbo].[HIREDATAHEADER] ADD  CONSTRAINT [DF_HIREDATAHEADER_ToSite]  DEFAULT ('') FOR [ToSite]
ALTER TABLE [dbo].[HIREDATAHEADER] ADD  CONSTRAINT [DF_HIREDATAHEADER_Debtor]  DEFAULT ('') FOR [Debtor]
ALTER TABLE [dbo].[HIREDATAHEADER] ADD  CONSTRAINT [DF_HIREDATAHEADER_BorgID]  DEFAULT (1) FOR [BorgID]
ALTER TABLE [dbo].[HIREDATAHEADER] ADD  CONSTRAINT [DF_HIREDATAHEADER_Posted]  DEFAULT (0) FOR [Posted]
ALTER TABLE [dbo].[HIREDATAHEADER] ADD  CONSTRAINT [DF_HIREDATAHEADER_Year]  DEFAULT ('1900') FOR [Year]
ALTER TABLE [dbo].[HIREDATAHEADER] ADD  CONSTRAINT [DF_HIREDATAHEADER_Period]  DEFAULT (1) FOR [Period]
ALTER TABLE [dbo].[HIREDATAHEADER] ADD  CONSTRAINT [DF_HIREDATAHEADER_UserID]  DEFAULT ((-1)) FOR [UserID]
ALTER TABLE [dbo].[HIREDATAHEADER] ADD  CONSTRAINT [DF__HIREDATAH__CAPTP__6875C865]  DEFAULT (1) FOR [CAPTPERIOD]
ALTER TABLE [dbo].[HIREDATAHEADER] ADD  CONSTRAINT [DF__HIREDATAH__ACTIV__6C514641]  DEFAULT ('') FOR [ACTIVITY]
ALTER TABLE [dbo].[HIREDATAHEADER] ADD  CONSTRAINT [DF_HIREDATAHEADER_STORE]  DEFAULT ('') FOR [STORE]
ALTER TABLE [dbo].[HIREDATAHEADER] ADD  CONSTRAINT [DF_HIREDATAHEADER_DIVISION]  DEFAULT ((-1)) FOR [DIVISION]
ALTER TABLE [dbo].[HIREDATAHEADER] ADD  CONSTRAINT [DF_HIREDATAHEADER_TRANSFERNOTE]  DEFAULT ('') FOR [TRANSFERNOTE]
ALTER TABLE [dbo].[HIREDATAHEADER] ADD  CONSTRAINT [DF_HIREDATAHEADER_OHLEDGERCODE]  DEFAULT ('') FOR [OHLEDGERCODE]