/****** Object:  Table [dbo].[HMRCTRANSACTIONS]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[HMRCTRANSACTIONS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[SERVICE] [nvarchar](10) NOT NULL,
	[GATEWAYURL] [nvarchar](100) NULL,
	[CORRELATIONID] [nvarchar](50) NULL,
	[CLASSTYPE] [nvarchar](50) NULL,
	[REQUESTPOSTXML] [nvarchar](max) NULL,
	[REQUESTSUBMISSIONTYPE] [nvarchar](50) NULL,
	[REQUESTRESPONSEXML] [nvarchar](max) NULL,
	[REQUESTRESPONSETYPE] [nvarchar](50) NULL,
	[POLLPOSTXML] [nvarchar](max) NULL,
	[POLLSUBMISSIONTYPE] [nvarchar](50) NULL,
	[POLLRESPONSEXML] [nvarchar](max) NULL,
	[POLLRESPONSETYPE] [nvarchar](50) NULL,
	[DELETEPOSTXML] [nvarchar](max) NULL,
	[DELETESUBMISSIONTYPE] [nvarchar](50) NULL,
	[DELETERESPONSEXML] [nvarchar](max) NULL,
	[DELETERESPONSETYPE] [nvarchar](50) NULL,
	[LISTPOSTXML] [nvarchar](max) NULL,
	[LISTSUBMISSIONTYPE] [nvarchar](50) NULL,
	[LISTRESPONSEXML] [nvarchar](max) NULL,
	[LISTRESPONSETYPE] [nvarchar](50) NULL,
	[COMPLETED] [bit] NOT NULL,
	[TIMESTAMP] [datetime] NOT NULL,
	[USERID] [int] NOT NULL,
	[DESCRIPTION] [nvarchar](250) NULL,
	[TRANSDATE] [datetime] NULL,
	[TRANGRP] [int] NOT NULL,
 CONSTRAINT [PK_HMRCTRANSACTIONS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

ALTER TABLE [dbo].[HMRCTRANSACTIONS] ADD  CONSTRAINT [DF_HMRCTRANSACTIONS_SERVICE]  DEFAULT ('') FOR [SERVICE]
ALTER TABLE [dbo].[HMRCTRANSACTIONS] ADD  CONSTRAINT [DF_HMRCTRANSACTIONS_COMPLETED]  DEFAULT (N'0') FOR [COMPLETED]
ALTER TABLE [dbo].[HMRCTRANSACTIONS] ADD  CONSTRAINT [DF_HMRCTRANSACTIONS_TIMESTAMP]  DEFAULT (getdate()) FOR [TIMESTAMP]
ALTER TABLE [dbo].[HMRCTRANSACTIONS] ADD  CONSTRAINT [DF_HMRCTRANSACTIONS_USERID]  DEFAULT ((-1)) FOR [USERID]
ALTER TABLE [dbo].[HMRCTRANSACTIONS] ADD  CONSTRAINT [DF_HMRCTRANSACTIONS_TRANGRP]  DEFAULT ((-1)) FOR [TRANGRP]