/****** Object:  Table [dbo].[HMRCURLSETTINGS]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[HMRCURLSETTINGS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[GATEWAYURL] [nvarchar](100) NOT NULL,
	[GATEWAYDEVURL] [nvarchar](100) NOT NULL,
 CONSTRAINT [PK_HMRCURLSETTINGS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[HMRCURLSETTINGS] ADD  CONSTRAINT [DF_HMRCURLSETTINGS_GATEWAYURL]  DEFAULT ('') FOR [GATEWAYURL]
ALTER TABLE [dbo].[HMRCURLSETTINGS] ADD  CONSTRAINT [DF_HMRCURLSETTINGS_GATEWAYDEVURL]  DEFAULT ('') FOR [GATEWAYDEVURL]