/****** Object:  Table [dbo].[HMRCSETTINGS]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[HMRCSETTINGS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[SERVICE] [nvarchar](10) NOT NULL,
	[SENDERID] [nvarchar](50) NOT NULL,
	[SENDERPASSWORD] [nvarchar](50) NOT NULL,
	[TAXOFFICENUMBER] [nvarchar](50) NOT NULL,
	[TAXOFFICEREFERENCE] [nvarchar](50) NOT NULL,
	[TESTFLAG] [bit] NOT NULL,
	[DEVFLAG] [bit] NOT NULL,
	[SENDERTYPE] [nvarchar](50) NOT NULL,
	[AGENTID] [nvarchar](50) NOT NULL,
	[COMPANYNAME] [nvarchar](50) NOT NULL,
	[ADDRESSLINE1] [nvarchar](50) NOT NULL,
	[ADDRESSLINE2] [nvarchar](50) NOT NULL,
	[ADDRESSLINE3] [nvarchar](50) NOT NULL,
	[ADDRESSLINE4] [nvarchar](50) NOT NULL,
	[ADDRESSLINE5] [nvarchar](50) NOT NULL,
	[POSTCODE] [nvarchar](50) NOT NULL,
	[COUNTRY] [nvarchar](50) NOT NULL,
	[CONTACTNAME] [nvarchar](50) NOT NULL,
	[CONTACTSURNAME] [nvarchar](50) NOT NULL,
	[EMAIL] [nvarchar](50) NOT NULL,
	[TELEPHONE] [nvarchar](50) NOT NULL,
	[FAX] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_HMRCSETTINGS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[HMRCSETTINGS] ADD  CONSTRAINT [DF_HMRCSETTINGS_SERVICE]  DEFAULT ('') FOR [SERVICE]
ALTER TABLE [dbo].[HMRCSETTINGS] ADD  CONSTRAINT [DF_HMRCSETTINGS_SENDERID]  DEFAULT ('') FOR [SENDERID]
ALTER TABLE [dbo].[HMRCSETTINGS] ADD  CONSTRAINT [DF_HMRCSETTINGS_SENDERPASSWORD]  DEFAULT ('') FOR [SENDERPASSWORD]
ALTER TABLE [dbo].[HMRCSETTINGS] ADD  CONSTRAINT [DF_HMRCSETTINGS_TAXOFFICENUMBER]  DEFAULT ('') FOR [TAXOFFICENUMBER]
ALTER TABLE [dbo].[HMRCSETTINGS] ADD  CONSTRAINT [DF_HMRCSETTINGS_TAXOFFICEREFERENCE]  DEFAULT ('') FOR [TAXOFFICEREFERENCE]
ALTER TABLE [dbo].[HMRCSETTINGS] ADD  CONSTRAINT [DF_HMRCSETTINGS_TESTFLAG]  DEFAULT (N'1') FOR [TESTFLAG]
ALTER TABLE [dbo].[HMRCSETTINGS] ADD  CONSTRAINT [DF_HMRCSETTINGS_DEVFLAG]  DEFAULT (N'0') FOR [DEVFLAG]
ALTER TABLE [dbo].[HMRCSETTINGS] ADD  CONSTRAINT [DF_HMRCSETTINGS_SENDERTYPE]  DEFAULT ('') FOR [SENDERTYPE]
ALTER TABLE [dbo].[HMRCSETTINGS] ADD  CONSTRAINT [DF_HMRCSETTINGS_AGENTID]  DEFAULT ('') FOR [AGENTID]
ALTER TABLE [dbo].[HMRCSETTINGS] ADD  CONSTRAINT [DF_HMRCSETTINGS_COMPANYNAME]  DEFAULT ('') FOR [COMPANYNAME]
ALTER TABLE [dbo].[HMRCSETTINGS] ADD  CONSTRAINT [DF_HMRCSETTINGS_ADDRESSLINE1]  DEFAULT ('') FOR [ADDRESSLINE1]
ALTER TABLE [dbo].[HMRCSETTINGS] ADD  CONSTRAINT [DF_HMRCSETTINGS_ADDRESSLINE2]  DEFAULT ('') FOR [ADDRESSLINE2]
ALTER TABLE [dbo].[HMRCSETTINGS] ADD  CONSTRAINT [DF_HMRCSETTINGS_ADDRESSLINE3]  DEFAULT ('') FOR [ADDRESSLINE3]
ALTER TABLE [dbo].[HMRCSETTINGS] ADD  CONSTRAINT [DF_HMRCSETTINGS_ADDRESSLINE4]  DEFAULT ('') FOR [ADDRESSLINE4]
ALTER TABLE [dbo].[HMRCSETTINGS] ADD  CONSTRAINT [DF_HMRCSETTINGS_ADDRESSLINE5]  DEFAULT ('') FOR [ADDRESSLINE5]
ALTER TABLE [dbo].[HMRCSETTINGS] ADD  CONSTRAINT [DF_HMRCSETTINGS_POSTCODE]  DEFAULT ('') FOR [POSTCODE]
ALTER TABLE [dbo].[HMRCSETTINGS] ADD  CONSTRAINT [DF_HMRCSETTINGS_COUNTRY]  DEFAULT ('') FOR [COUNTRY]
ALTER TABLE [dbo].[HMRCSETTINGS] ADD  CONSTRAINT [DF_HMRCSETTINGS_CONTACTNAME]  DEFAULT ('') FOR [CONTACTNAME]
ALTER TABLE [dbo].[HMRCSETTINGS] ADD  CONSTRAINT [DF_HMRCSETTINGS_CONTACTSURNAME]  DEFAULT ('') FOR [CONTACTSURNAME]
ALTER TABLE [dbo].[HMRCSETTINGS] ADD  CONSTRAINT [DF_HMRCSETTINGS_EMAIL]  DEFAULT ('') FOR [EMAIL]
ALTER TABLE [dbo].[HMRCSETTINGS] ADD  CONSTRAINT [DF_HMRCSETTINGS_TELEPHONE]  DEFAULT ('') FOR [TELEPHONE]
ALTER TABLE [dbo].[HMRCSETTINGS] ADD  CONSTRAINT [DF_HMRCSETTINGS_FAX]  DEFAULT ('') FOR [FAX]