/****** Object:  Table [dbo].[HMRCCISLINK]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[HMRCCISLINK](
	[TYPE] [int] NOT NULL,
	[SUBID] [int] NOT NULL,
	[ORGID] [int] NOT NULL
) ON [PRIMARY]

ALTER TABLE [dbo].[HMRCCISLINK] ADD  CONSTRAINT [DF_HMRCCISLINK_TYPE]  DEFAULT ((0)) FOR [TYPE]
ALTER TABLE [dbo].[HMRCCISLINK] ADD  CONSTRAINT [DF_HMRCCISLINK_ORGID]  DEFAULT ((-1)) FOR [ORGID]