/****** Object:  Table [dbo].[INVBULKDETAIL]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[INVBULKDETAIL](
	[DID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[HID] [int] NOT NULL,
	[STKCODE] [nvarchar](20) NOT NULL,
	[LEDGERCODE] [nvarchar](10) NOT NULL,
	[DELNUMBER] [nvarchar](10) NOT NULL,
	[DESCRIPTION] [nvarchar](255) NOT NULL,
	[REQQTY] [numeric](18, 4) NOT NULL,
	[DELQTY] [numeric](18, 4) NOT NULL,
	[ISSQTY] [numeric](18, 4) NOT NULL,
	[TBORGID] [int] NOT NULL,
	[CONTRNUMBER] [nvarchar](10) NOT NULL,
	[ACTNUMBER] [nvarchar](10) NOT NULL,
	[PENUMBER] [nvarchar](10) NOT NULL,
	[DIVID] [int] NOT NULL,
	[PLANTSMR] [numeric](18, 4) NOT NULL,
	[PLANTSMRUNIT] [nvarchar](10) NOT NULL,
	[JOBCARDID] [int] NOT NULL,
	[JOBCARDLEDGERCODE] [nvarchar](10) NOT NULL,
	[JOBCARDACTID] [nvarchar](10) NOT NULL,
	[JOBCARDVATID] [char](2) NOT NULL,
 CONSTRAINT [PK_INVBULKDETAIL] PRIMARY KEY CLUSTERED 
(
	[DID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[INVBULKDETAIL] ADD  CONSTRAINT [DF_INVBULKDETAIL_HID]  DEFAULT ((-1)) FOR [HID]
ALTER TABLE [dbo].[INVBULKDETAIL] ADD  CONSTRAINT [DF_INVBULKDETAIL_STKCODE]  DEFAULT ('') FOR [STKCODE]
ALTER TABLE [dbo].[INVBULKDETAIL] ADD  CONSTRAINT [DF_INVBULKDETAIL_LEDGERCODE]  DEFAULT ('') FOR [LEDGERCODE]
ALTER TABLE [dbo].[INVBULKDETAIL] ADD  CONSTRAINT [DF_INVBULKDETAIL_DELNUMBER]  DEFAULT ('') FOR [DELNUMBER]
ALTER TABLE [dbo].[INVBULKDETAIL] ADD  CONSTRAINT [DF_INVBULKDETAIL_DESCRIPTION]  DEFAULT ('') FOR [DESCRIPTION]
ALTER TABLE [dbo].[INVBULKDETAIL] ADD  CONSTRAINT [DF_INVBULKDETAIL_REQQTY]  DEFAULT ('0') FOR [REQQTY]
ALTER TABLE [dbo].[INVBULKDETAIL] ADD  CONSTRAINT [DF_INVBULKDETAIL_DELQTY]  DEFAULT ('0') FOR [DELQTY]
ALTER TABLE [dbo].[INVBULKDETAIL] ADD  CONSTRAINT [DF_INVBULKDETAIL_ISSQTY]  DEFAULT ('0') FOR [ISSQTY]
ALTER TABLE [dbo].[INVBULKDETAIL] ADD  CONSTRAINT [DF_INVBULKDETAIL_TBORGID]  DEFAULT ((-1)) FOR [TBORGID]
ALTER TABLE [dbo].[INVBULKDETAIL] ADD  CONSTRAINT [DF_INVBULKDETAIL_CONTRNUMBER]  DEFAULT ('') FOR [CONTRNUMBER]
ALTER TABLE [dbo].[INVBULKDETAIL] ADD  CONSTRAINT [DF_INVBULKDETAIL_ACTNUMBER]  DEFAULT ('') FOR [ACTNUMBER]
ALTER TABLE [dbo].[INVBULKDETAIL] ADD  CONSTRAINT [DF_INVBULKDETAIL_PENUMBER]  DEFAULT ('') FOR [PENUMBER]
ALTER TABLE [dbo].[INVBULKDETAIL] ADD  CONSTRAINT [DF_INVBULKDETAIL_DIVID]  DEFAULT ((-1)) FOR [DIVID]
ALTER TABLE [dbo].[INVBULKDETAIL] ADD  CONSTRAINT [DF_INVBULKDETAIL_PLANTSMR]  DEFAULT ('0') FOR [PLANTSMR]
ALTER TABLE [dbo].[INVBULKDETAIL] ADD  CONSTRAINT [DF_INVBULKDETAIL_PLANTSMRUNIT]  DEFAULT ('') FOR [PLANTSMRUNIT]
ALTER TABLE [dbo].[INVBULKDETAIL] ADD  CONSTRAINT [DF_INVBULKDETAIL_JOBCARDID]  DEFAULT ((-1)) FOR [JOBCARDID]
ALTER TABLE [dbo].[INVBULKDETAIL] ADD  CONSTRAINT [DF_INVBULKDETAIL_JOBCARDLEDGERCODE]  DEFAULT ('') FOR [JOBCARDLEDGERCODE]
ALTER TABLE [dbo].[INVBULKDETAIL] ADD  CONSTRAINT [DF_INVBULKDETAIL_JOBCARDACTID]  DEFAULT ('') FOR [JOBCARDACTID]
ALTER TABLE [dbo].[INVBULKDETAIL] ADD  CONSTRAINT [DF_INVBULKDETAIL_JOBCARDVATID]  DEFAULT ('') FOR [JOBCARDVATID]
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON

CREATE TRIGGER [dbo].[TR_INVBULKDETAIL_StopOIssue] ON [dbo].[INVBULKDETAIL]
   AFTER INSERT, UPDATE
AS 
BEGIN
	SET NOCOUNT ON
	declare @REQQTY								numeric (18,4);
	declare @DELQTY								numeric (18,4);
	declare @ISSQTY								numeric (18,4);
	declare @Mess								nvarchar(255)

	Select @REQQTY = REQQTY from inserted;
	Select @DELQTY = DELQTY from inserted;
	Select @ISSQTY = ISSQTY from inserted

	if (@REQQTY<(@DELQTY+@ISSQTY))
	begin
	Set @Mess = 'This update can not be saved as the total quantity to be issued plus previous issues exceeds the requested quantity.  (Error from TR_INVBULKDETAIL_StopOIssue trigger on INVBULKDETAIL)'
	   Raiserror( @Mess ,16,1)
	rollback transaction
	end

END

ALTER TABLE [dbo].[INVBULKDETAIL] ENABLE TRIGGER [TR_INVBULKDETAIL_StopOIssue]