/****** Object:  Table [dbo].[INVENTORYTRANSFERHEADER]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[INVENTORYTRANSFERHEADER](
	[HID] [int] IDENTITY(1,1) NOT NULL,
	[ORGID] [int] NOT NULL,
	[YEAR] [int] NOT NULL,
	[PERIOD] [int] NOT NULL,
	[STKTRANSFERNO] [nvarchar](10) NOT NULL,
	[STKSTOREFROM] [nvarchar](15) NOT NULL,
	[STKSTORETO] [nvarchar](15) NOT NULL,
	[TOBORG] [int] NOT NULL,
	[DATE] [datetime] NOT NULL,
	[NOTE] [nvarchar](250) NOT NULL,
	[TRANGRP] [int] NOT NULL,
	[USER] [int] NOT NULL,
 CONSTRAINT [PK_INVENTORYTRANSFERHEADER] PRIMARY KEY CLUSTERED 
(
	[HID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[INVENTORYTRANSFERHEADER] ADD  CONSTRAINT [DF_INVENTORYTRANSFERHEADER_ORGID]  DEFAULT ((-1)) FOR [ORGID]
ALTER TABLE [dbo].[INVENTORYTRANSFERHEADER] ADD  CONSTRAINT [DF_INVENTORYTRANSFERHEADER_YEAR]  DEFAULT ((-1)) FOR [YEAR]
ALTER TABLE [dbo].[INVENTORYTRANSFERHEADER] ADD  CONSTRAINT [DF_INVENTORYTRANSFERHEADER_PERIOD]  DEFAULT ((-1)) FOR [PERIOD]
ALTER TABLE [dbo].[INVENTORYTRANSFERHEADER] ADD  CONSTRAINT [DF_INVENTORYTRANSFERHEADER_STKTRANSFERNO]  DEFAULT ('') FOR [STKTRANSFERNO]
ALTER TABLE [dbo].[INVENTORYTRANSFERHEADER] ADD  CONSTRAINT [DF_INVENTORYTRANSFERHEADER_STKSTOREFROM]  DEFAULT ('') FOR [STKSTOREFROM]
ALTER TABLE [dbo].[INVENTORYTRANSFERHEADER] ADD  CONSTRAINT [DF_INVENTORYTRANSFERHEADER_STKSTORETO]  DEFAULT ('') FOR [STKSTORETO]
ALTER TABLE [dbo].[INVENTORYTRANSFERHEADER] ADD  CONSTRAINT [DF_INVENTORYTRANSFERHEADER_TOBORG]  DEFAULT ((-1)) FOR [TOBORG]
ALTER TABLE [dbo].[INVENTORYTRANSFERHEADER] ADD  CONSTRAINT [DF_INVENTORYTRANSFERHEADER_DATE]  DEFAULT (getdate()) FOR [DATE]
ALTER TABLE [dbo].[INVENTORYTRANSFERHEADER] ADD  CONSTRAINT [DF_INVENTORYTRANSFERHEADER_NOTE]  DEFAULT ('') FOR [NOTE]
ALTER TABLE [dbo].[INVENTORYTRANSFERHEADER] ADD  CONSTRAINT [DF_INVENTORYTRANSFERHEADER_TRANGRP]  DEFAULT ((-1)) FOR [TRANGRP]
ALTER TABLE [dbo].[INVENTORYTRANSFERHEADER] ADD  CONSTRAINT [DF_INVENTORYTRANSFERHEADER_USER]  DEFAULT ((-1)) FOR [USER]