/****** Object:  Table [dbo].[INVENTORYSERIALS]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[INVENTORYSERIALS](
	[ISID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[TRANSTYPE] [nvarchar](10) NOT NULL,
	[TRANSTYPEID] [int] NOT NULL,
	[SERIAL] [nvarchar](55) NOT NULL,
	[QUANTITY] [decimal](18, 4) NOT NULL,
	[STKSTORE] [nvarchar](15) NOT NULL,
	[STKCODE] [nvarchar](20) NOT NULL,
	[BORGID] [int] NOT NULL,
	[SYSDATE] [datetime] NULL,
 CONSTRAINT [PK_INVENTORYSERIALS] PRIMARY KEY CLUSTERED 
(
	[ISID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[INVENTORYSERIALS] ADD  CONSTRAINT [DF_INVENTORYSERIALS_TRANSTYPEID]  DEFAULT ('-1') FOR [TRANSTYPEID]
ALTER TABLE [dbo].[INVENTORYSERIALS] ADD  CONSTRAINT [DF_INVENTORYSERIALS_QUANTITY]  DEFAULT ('0') FOR [QUANTITY]
ALTER TABLE [dbo].[INVENTORYSERIALS] ADD  CONSTRAINT [DF_INVENTORYSERIALS_BORGID]  DEFAULT ('-1') FOR [BORGID]
ALTER TABLE [dbo].[INVENTORYSERIALS] ADD  CONSTRAINT [DF_INVENTORYSERIALS_SYSDATE]  DEFAULT (getdate()) FOR [SYSDATE]