/****** Object:  Table [dbo].[INVOICEITEMS]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[INVOICEITEMS](
	[InvHeadID] [int] NULL,
	[InvStockItem] [char](20) NULL,
	[InvStockStore] [char](20) NULL,
	[InvQuantity] [decimal](18, 4) NULL,
	[InvRate] [money] NULL,
	[InvVatAmnt] [money] NULL,
	[InvPlantNo] [char](10) NULL,
	[InvDesc] [char](255) NULL,
	[InvUnit] [char](8) NULL,
	[InvStockID] [int] NULL,
	[InvPlantID] [int] NULL,
	[InvAllocation] [char](25) NULL,
	[InvLedgerCode] [char](10) NULL,
	[InvContract] [char](10) NULL,
	[InvActivity] [char](10) NULL,
	[InvDivID] [int] NOT NULL,
	[InvLineID] [int] IDENTITY(1,1) NOT NULL,
	[VATTYPE] [nvarchar](100) NOT NULL,
	[INVLTYPE] [char](1) NOT NULL,
	[INVMARKUPPERC] [numeric](18, 4) NOT NULL,
	[INVMARKUPVALUE] [money] NOT NULL,
	[INVMARKUPVat] [money] NOT NULL,
	[InvLineOrder] [int] NULL,
	[CREDNO] [nvarchar](10) NOT NULL,
	[TBORGID] [int] NOT NULL,
	[WHTID] [int] NOT NULL,
	[INVWHTAMNT] [money] NOT NULL,
	[CLASSID] [int] NOT NULL
) ON [PRIMARY]

CREATE NONCLUSTERED INDEX [IX_TBORGID_VATTYPE] ON [dbo].[INVOICEITEMS]
(
	[TBORGID] ASC
)
INCLUDE([VATTYPE]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
ALTER TABLE [dbo].[INVOICEITEMS] ADD  CONSTRAINT [DF_INVOICEITEMS_INVQUANTITY]  DEFAULT ('0') FOR [InvQuantity]
ALTER TABLE [dbo].[INVOICEITEMS] ADD  CONSTRAINT [DF_INVOICEITEMS_InvDivID]  DEFAULT ((-1)) FOR [InvDivID]
ALTER TABLE [dbo].[INVOICEITEMS] ADD  CONSTRAINT [DF_INVOICEITEMS_VATTYPE]  DEFAULT ('') FOR [VATTYPE]
ALTER TABLE [dbo].[INVOICEITEMS] ADD  DEFAULT ('D') FOR [INVLTYPE]
ALTER TABLE [dbo].[INVOICEITEMS] ADD  DEFAULT (0) FOR [INVMARKUPPERC]
ALTER TABLE [dbo].[INVOICEITEMS] ADD  DEFAULT (0) FOR [INVMARKUPVALUE]
ALTER TABLE [dbo].[INVOICEITEMS] ADD  DEFAULT (0) FOR [INVMARKUPVat]
ALTER TABLE [dbo].[INVOICEITEMS] ADD  CONSTRAINT [DF_INVOICEITEMS_InvLineOrder]  DEFAULT ((0)) FOR [InvLineOrder]
ALTER TABLE [dbo].[INVOICEITEMS] ADD  CONSTRAINT [DF_INVOICEITEMS_CREDNO]  DEFAULT ('') FOR [CREDNO]
ALTER TABLE [dbo].[INVOICEITEMS] ADD  CONSTRAINT [DF_INVOICEITEMS_TBORGID]  DEFAULT ('-1') FOR [TBORGID]
ALTER TABLE [dbo].[INVOICEITEMS] ADD  CONSTRAINT [DF_INVOICEITEMS_WHTID]  DEFAULT ((-1)) FOR [WHTID]
ALTER TABLE [dbo].[INVOICEITEMS] ADD  CONSTRAINT [DF_INVOICEITEMS_INVWHTAMNT]  DEFAULT ((0)) FOR [INVWHTAMNT]
ALTER TABLE [dbo].[INVOICEITEMS] ADD  CONSTRAINT [DF_INVOICEITEMS_CLASSID]  DEFAULT ((-1)) FOR [CLASSID]