/****** Object:  Table [dbo].[INVOICEHEADER]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[INVOICEHEADER](
	[InvDate] [datetime] NULL,
	[InvIType] [char](25) NULL,
	[InvOrderNo] [char](25) NULL,
	[InvTerms] [char](25) NULL,
	[InvNumber] [char](10) NULL,
	[InvDebtor] [char](10) NULL,
	[InvHeader] [char](255) NULL,
	[InvID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[InvCurr] [nvarchar](3) NULL,
	[InvVAT] [nvarchar](100) NOT NULL,
	[InvVatPerc] [numeric](18, 4) NOT NULL,
	[InvPrinted] [bit] NOT NULL,
	[InvPosted] [bit] NOT NULL,
	[UserID] [nvarchar](15) NOT NULL,
	[BorgID] [int] NOT NULL,
	[InvDebtControl] [char](10) NOT NULL,
	[INVSITE] [char](35) NOT NULL,
	[INVBCODE] [char](25) NULL,
	[INVBSTATION] [char](15) NOT NULL,
	[INVREGION] [char](25) NOT NULL,
	[INVEXCHRATE] [numeric](18, 6) NOT NULL,
	[INVREF] [char](10) NOT NULL,
	[InvDelAddres] [int] NULL,
	[INVYEAR] [nvarchar](4) NOT NULL,
	[INVPERIOD] [int] NOT NULL,
	[INVPERIODADD] [int] NOT NULL,
	[INVAPPROVER] [int] NULL,
	[INVAPPDATE] [datetime] NULL,
	[INVPOSTBY] [int] NULL,
	[INVPOSTDATE] [datetime] NULL,
	[ARCHIVE] [bit] NOT NULL,
	[WHTID] [int] NOT NULL,
 CONSTRAINT [PK_INVOICEHEADER] PRIMARY KEY CLUSTERED 
(
	[InvID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[INVOICEHEADER] ADD  CONSTRAINT [DF_INVOICEHEADER_INVVATPERC]  DEFAULT ('0') FOR [InvVatPerc]
ALTER TABLE [dbo].[INVOICEHEADER] ADD  CONSTRAINT [DF_INVOICEHEADER_InvPrinted]  DEFAULT ((0)) FOR [InvPrinted]
ALTER TABLE [dbo].[INVOICEHEADER] ADD  CONSTRAINT [DF_INVOICEHEADER_InvPosted]  DEFAULT ((0)) FOR [InvPosted]
ALTER TABLE [dbo].[INVOICEHEADER] ADD  CONSTRAINT [DF_INVOICEHEADER_USERID]  DEFAULT ('') FOR [UserID]
ALTER TABLE [dbo].[INVOICEHEADER] ADD  CONSTRAINT [DF_INVOICEHEADER_BorgID]  DEFAULT ((1)) FOR [BorgID]
ALTER TABLE [dbo].[INVOICEHEADER] ADD  CONSTRAINT [DF_INVOICEHEADER_InvDebtControl]  DEFAULT ('') FOR [InvDebtControl]
ALTER TABLE [dbo].[INVOICEHEADER] ADD  CONSTRAINT [DF__INVOICEHE__INVSI__483D37A6]  DEFAULT ('') FOR [INVSITE]
ALTER TABLE [dbo].[INVOICEHEADER] ADD  CONSTRAINT [DF__INVOICEHE__INVBC__49315BDF]  DEFAULT ('') FOR [INVBCODE]
ALTER TABLE [dbo].[INVOICEHEADER] ADD  CONSTRAINT [DF__INVOICEHE__INVBS__4A258018]  DEFAULT ('') FOR [INVBSTATION]
ALTER TABLE [dbo].[INVOICEHEADER] ADD  CONSTRAINT [DF__INVOICEHE__INVRE__4B19A451]  DEFAULT ('') FOR [INVREGION]
ALTER TABLE [dbo].[INVOICEHEADER] ADD  CONSTRAINT [DF__INVOICEHE__INVEX__7E9A13AE]  DEFAULT ((1)) FOR [INVEXCHRATE]
ALTER TABLE [dbo].[INVOICEHEADER] ADD  CONSTRAINT [DF__INVOICEHE__INVRE__77168B72]  DEFAULT ('') FOR [INVREF]
ALTER TABLE [dbo].[INVOICEHEADER] ADD  CONSTRAINT [DF_INVOICEHEADER_INVYEAR]  DEFAULT ((-1)) FOR [INVYEAR]
ALTER TABLE [dbo].[INVOICEHEADER] ADD  CONSTRAINT [DF_INVOICEHEADER_INVPERIOD]  DEFAULT ((-1)) FOR [INVPERIOD]
ALTER TABLE [dbo].[INVOICEHEADER] ADD  CONSTRAINT [DF_INVOICEHEADER_INVPERIODADD]  DEFAULT ((0)) FOR [INVPERIODADD]
ALTER TABLE [dbo].[INVOICEHEADER] ADD  CONSTRAINT [DF_INVOICEHEADER_INVAPPROVER]  DEFAULT ((-1)) FOR [INVAPPROVER]
ALTER TABLE [dbo].[INVOICEHEADER] ADD  CONSTRAINT [DF_INVOICEHEADER_INVAPPDATE]  DEFAULT (getdate()) FOR [INVAPPDATE]
ALTER TABLE [dbo].[INVOICEHEADER] ADD  CONSTRAINT [DF_INVOICEHEADER_INVPOSTBY]  DEFAULT ((-1)) FOR [INVPOSTBY]
ALTER TABLE [dbo].[INVOICEHEADER] ADD  CONSTRAINT [DF_INVOICEHEADER_INVPOSTDATE]  DEFAULT (getdate()) FOR [INVPOSTDATE]
ALTER TABLE [dbo].[INVOICEHEADER] ADD  CONSTRAINT [DF_INVOICEHEADER_ARCHIVE]  DEFAULT ('0') FOR [ARCHIVE]
ALTER TABLE [dbo].[INVOICEHEADER] ADD  CONSTRAINT [DF_INVOICEHEADER_WHTID]  DEFAULT ((-1)) FOR [WHTID]