/****** Object:  Table [dbo].[INVOICERECURITEMS]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[INVOICERECURITEMS](
	[INVHEADID] [int] NULL,
	[INVSTOCKITEM] [char](20) NULL,
	[INVSTOCKSTORE] [char](20) NULL,
	[INVQUANTITY] [decimal](18, 4) NULL,
	[INVRATE] [money] NULL,
	[INVVATAMNT] [money] NULL,
	[INVPLANTNO] [char](10) NULL,
	[INVDESC] [char](255) NULL,
	[INVUNIT] [char](8) NULL,
	[INVSTOCKID] [int] NULL,
	[INVPLANTID] [int] NULL,
	[INVALLOCATION] [char](25) NULL,
	[INVLEDGERCODE] [char](10) NULL,
	[INVCONTRACT] [char](10) NULL,
	[INVACTIVITY] [char](10) NULL,
	[INVDIVID] [int] NOT NULL,
	[INVLINEID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[VATTYPE] [nvarchar](100) NOT NULL,
	[INVLTYPE] [char](1) NOT NULL,
	[INVMARKUPPERC] [numeric](18, 4) NOT NULL,
	[INVMARKUPVALUE] [money] NOT NULL,
	[INVMARKUPVAT] [money] NOT NULL,
	[INVLINEORDER] [int] NULL,
	[CREDNO] [nvarchar](10) NOT NULL,
	[TBORGID] [int] NOT NULL,
	[WHTID] [int] NOT NULL,
	[CLASSID] [int] NOT NULL,
	[INVWHTAMNT] [money] NOT NULL,
 CONSTRAINT [PK_INVOICERECURITEMS] PRIMARY KEY CLUSTERED 
(
	[INVLINEID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[INVOICERECURITEMS] ADD  CONSTRAINT [DF_INVOICERECURITEMS_INVQUANTITY]  DEFAULT ('0') FOR [INVQUANTITY]
ALTER TABLE [dbo].[INVOICERECURITEMS] ADD  CONSTRAINT [DF_INVOICERECURITEMS_INVDIVID]  DEFAULT ((-1)) FOR [INVDIVID]
ALTER TABLE [dbo].[INVOICERECURITEMS] ADD  CONSTRAINT [DF_INVOICERECURITEMS_VATTYPE]  DEFAULT ('') FOR [VATTYPE]
ALTER TABLE [dbo].[INVOICERECURITEMS] ADD  CONSTRAINT [DF_INVOICERECURITEMS_INVLTYPE]  DEFAULT ('D') FOR [INVLTYPE]
ALTER TABLE [dbo].[INVOICERECURITEMS] ADD  CONSTRAINT [DF_INVOICERECURITEMS_INVMARKUPPERC]  DEFAULT ((0)) FOR [INVMARKUPPERC]
ALTER TABLE [dbo].[INVOICERECURITEMS] ADD  CONSTRAINT [DF_INVOICERECURITEMS_INVMARKUPVALUE]  DEFAULT ((0)) FOR [INVMARKUPVALUE]
ALTER TABLE [dbo].[INVOICERECURITEMS] ADD  CONSTRAINT [DF_INVOICERECURITEMS_INVMARKUPVAT]  DEFAULT ((0)) FOR [INVMARKUPVAT]
ALTER TABLE [dbo].[INVOICERECURITEMS] ADD  CONSTRAINT [DF_INVOICERECURITEMS_INVLINEORDER]  DEFAULT ((0)) FOR [INVLINEORDER]
ALTER TABLE [dbo].[INVOICERECURITEMS] ADD  CONSTRAINT [DF_INVOICERECURITEMS_CREDNO]  DEFAULT ('') FOR [CREDNO]
ALTER TABLE [dbo].[INVOICERECURITEMS] ADD  CONSTRAINT [DF_INVOICERECURITEMS_TBORGID]  DEFAULT ('-1') FOR [TBORGID]
ALTER TABLE [dbo].[INVOICERECURITEMS] ADD  CONSTRAINT [DF_INVOICERECURITEMS_WHTID]  DEFAULT ((-1)) FOR [WHTID]
ALTER TABLE [dbo].[INVOICERECURITEMS] ADD  CONSTRAINT [DF_INVOICERECURITEMS_CLASSID]  DEFAULT ((-1)) FOR [CLASSID]
ALTER TABLE [dbo].[INVOICERECURITEMS] ADD  CONSTRAINT [DF_INVOICERECURITEMS_INVWHTAMNT]  DEFAULT ((0)) FOR [INVWHTAMNT]