/****** Object:  Table [dbo].[INVSTORESCOSDIV]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[INVSTORESCOSDIV](
	[STORECODE] [nvarchar](15) NOT NULL,
	[BORGID] [int] NOT NULL,
	[DIVID] [int] NOT NULL,
	[StoreLocation] [nvarchar](35) NULL,
	[StoreTel] [nvarchar](25) NULL,
	[StoreFax] [nvarchar](25) NULL,
	[StoreCell] [nvarchar](25) NULL,
	[StoreEmail] [nvarchar](60) NULL,
	[StoreContact] [nvarchar](35) NULL,
	[StoreContNumber] [nvarchar](10) NULL,
	[StoreDefContGL] [nvarchar](10) NOT NULL,
	[StoreContWriteOffGL] [nvarchar](10) NOT NULL,
	[IsYardStore] [bit] NOT NULL,
	[StoreStatus] [int] NOT NULL,
	[HIREDIVID] [int] NOT NULL,
 CONSTRAINT [PK_INVSTORESCOSDIV] PRIMARY KEY CLUSTERED 
(
	[STORECODE] ASC,
	[BORGID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[INVSTORESCOSDIV] ADD  CONSTRAINT [DF_INVSTORESCOSDIV_STORECODE]  DEFAULT ('') FOR [STORECODE]
ALTER TABLE [dbo].[INVSTORESCOSDIV] ADD  CONSTRAINT [DF_INVSTORESCOSDIV_BorgId]  DEFAULT ((-1)) FOR [BORGID]
ALTER TABLE [dbo].[INVSTORESCOSDIV] ADD  CONSTRAINT [DF_INVSTORESCOSDIV_DivId]  DEFAULT ((-1)) FOR [DIVID]
ALTER TABLE [dbo].[INVSTORESCOSDIV] ADD  CONSTRAINT [DF_INVSTORESCOSDIV_StoreDefContGL]  DEFAULT ('') FOR [StoreDefContGL]
ALTER TABLE [dbo].[INVSTORESCOSDIV] ADD  CONSTRAINT [DF_INVSTORESCOSDIV_StoreContWriteOffGL]  DEFAULT ('') FOR [StoreContWriteOffGL]
ALTER TABLE [dbo].[INVSTORESCOSDIV] ADD  CONSTRAINT [DF_INVSTORESCOSDIV_IsYardStore]  DEFAULT (N'0') FOR [IsYardStore]
ALTER TABLE [dbo].[INVSTORESCOSDIV] ADD  CONSTRAINT [DF_INVSTORESCOSDIV_StoreStatus]  DEFAULT ((0)) FOR [StoreStatus]
ALTER TABLE [dbo].[INVSTORESCOSDIV] ADD  DEFAULT ((-1)) FOR [HIREDIVID]