/****** Object:  Table [dbo].[INVXFERTEMP]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[INVXFERTEMP](
	[StkStore] [char](15) NOT NULL,
	[StkCode] [char](20) NOT NULL,
	[StkFromStore] [char](15) NOT NULL,
	[StkDesc] [char](250) NULL,
	[StkUnit] [char](8) NULL,
	[StkQuantity] [numeric](18, 4) NOT NULL,
	[BorgID] [int] NOT NULL,
	[SessionID] [int] NOT NULL,
	[TransferDate] [datetime] NOT NULL,
	[ToJoinI] [int] NOT NULL,
	[XferID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[TOORGID] [int] NOT NULL,
	[TRANSHEADERID] [int] NOT NULL,
 CONSTRAINT [PK_INVXFERTEMP] PRIMARY KEY CLUSTERED 
(
	[XferID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[INVXFERTEMP] ADD  CONSTRAINT [DF_INVXFERTEMP_StkStore]  DEFAULT (' ') FOR [StkStore]
ALTER TABLE [dbo].[INVXFERTEMP] ADD  CONSTRAINT [DF_INVXFERTEMP_StkToStore]  DEFAULT (' ') FOR [StkFromStore]
ALTER TABLE [dbo].[INVXFERTEMP] ADD  CONSTRAINT [DF_INVXFERTEMP_StkQuantity]  DEFAULT (0) FOR [StkQuantity]
ALTER TABLE [dbo].[INVXFERTEMP] ADD  CONSTRAINT [DF_INVXFERTEMP_BorgID]  DEFAULT (0) FOR [BorgID]
ALTER TABLE [dbo].[INVXFERTEMP] ADD  CONSTRAINT [DF_INVXFERTEMP_SessionID]  DEFAULT (0) FOR [SessionID]
ALTER TABLE [dbo].[INVXFERTEMP] ADD  CONSTRAINT [DF_INVXFERTEMP_TransferDate]  DEFAULT (getdate()) FOR [TransferDate]
ALTER TABLE [dbo].[INVXFERTEMP] ADD  CONSTRAINT [DF_INVXFERTEMP_ToJoinI]  DEFAULT (11) FOR [ToJoinI]
ALTER TABLE [dbo].[INVXFERTEMP] ADD  CONSTRAINT [DF_INVXFERTEMP_TOORGID]  DEFAULT ('-1') FOR [TOORGID]
ALTER TABLE [dbo].[INVXFERTEMP] ADD  CONSTRAINT [DF_INVXFERTEMP_TRANSHEADERID]  DEFAULT ((-1)) FOR [TRANSHEADERID]