/****** Object:  Table [dbo].[JOBCODESBONUSSET]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[JOBCODESBONUSSET](
	[JOBCODESBONUSID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[JOBNUMBER] [nvarchar](10) NOT NULL,
	[JOBCODEBONUSPERC] [decimal](18, 4) NOT NULL,
	[JOBTITLECODE] [int] NULL,
	[JOBGRADECODE] [int] NULL,
	[PAYROLLID] [int] NULL,
 CONSTRAINT [PK_JOBCODESBONUSID] PRIMARY KEY CLUSTERED 
(
	[JOBCODESBONUSID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]