/****** Object:  Table [dbo].[JOURNALSRECUR]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[JOURNALSRECUR](
	[JnlID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[JnlLedgerCode] [nvarchar](10) NOT NULL,
	[JnlDescription] [nvarchar](255) NOT NULL,
	[JnlContract] [nvarchar](10) NOT NULL,
	[JnlActivity] [nvarchar](10) NOT NULL,
	[JnlDivision] [nvarchar](10) NOT NULL,
	[JnlDebit] [money] NOT NULL,
	[JnlCredit] [money] NOT NULL,
	[JnlOrg] [int] NOT NULL,
	[JnlAge] [int] NOT NULL,
	[JnlSubConTran] [nvarchar](25) NOT NULL,
	[JnlVatDebit] [money] NOT NULL,
	[JnlVatCredit] [money] NOT NULL,
	[JnlHomeCurrency] [money] NOT NULL,
	[JnlPlant] [nvarchar](10) NOT NULL,
	[JnlCredno] [nvarchar](10) NOT NULL,
	[JnlHeadID] [int] NOT NULL,
	[JnlAlloc] [nvarchar](25) NOT NULL,
	[JnlVATType] [nvarchar](100) NOT NULL,
	[JnlExchRate] [float] NOT NULL,
	[JnlContExchRate] [float] NOT NULL,
	[JnlPlantHeadID] [int] NULL,
	[JNLTOORG] [int] NOT NULL,
	[JNLICGLCODE] [nvarchar](10) NOT NULL,
	[JNLTRANSREF] [nvarchar](10) NOT NULL,
	[WHTID] [int] NULL,
	[PDATE] [datetime] NULL,
	[ASSETNUMBER] [nvarchar](15) NOT NULL,
	[ASSETTYPE] [varchar](3) NOT NULL,
	[CLASSID] [int] NOT NULL,
 CONSTRAINT [PK_JOURNALSRECUR] PRIMARY KEY CLUSTERED 
(
	[JnlID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[JOURNALSRECUR] ADD  CONSTRAINT [DF_JOURNALSRECUR_JnlLedgerCode]  DEFAULT ('') FOR [JnlLedgerCode]
ALTER TABLE [dbo].[JOURNALSRECUR] ADD  CONSTRAINT [DF_JOURNALSRECUR_JnlDescription]  DEFAULT ('') FOR [JnlDescription]
ALTER TABLE [dbo].[JOURNALSRECUR] ADD  CONSTRAINT [DF_JOURNALSRECUR_JnlContract]  DEFAULT ('') FOR [JnlContract]
ALTER TABLE [dbo].[JOURNALSRECUR] ADD  CONSTRAINT [DF_JOURNALSRECUR_JnlActivity]  DEFAULT ('') FOR [JnlActivity]
ALTER TABLE [dbo].[JOURNALSRECUR] ADD  CONSTRAINT [DF_JOURNALSRECUR_JnlDivision]  DEFAULT ('-1') FOR [JnlDivision]
ALTER TABLE [dbo].[JOURNALSRECUR] ADD  CONSTRAINT [DF_JOURNALSRECUR_JnlDebit]  DEFAULT ((0)) FOR [JnlDebit]
ALTER TABLE [dbo].[JOURNALSRECUR] ADD  CONSTRAINT [DF_JOURNALSRECUR_JnlCredit]  DEFAULT ((0)) FOR [JnlCredit]
ALTER TABLE [dbo].[JOURNALSRECUR] ADD  CONSTRAINT [DF_JOURNALSRECUR_JnlOrg]  DEFAULT ('-1') FOR [JnlOrg]
ALTER TABLE [dbo].[JOURNALSRECUR] ADD  CONSTRAINT [DF_JOURNALSRECUR_JnlAge]  DEFAULT ('0') FOR [JnlAge]
ALTER TABLE [dbo].[JOURNALSRECUR] ADD  CONSTRAINT [DF_JOURNALSRECUR_JnlSubConTran]  DEFAULT ('Certified Amount') FOR [JnlSubConTran]
ALTER TABLE [dbo].[JOURNALSRECUR] ADD  CONSTRAINT [DF_JOURNALSRECUR_JnlVatDebit]  DEFAULT ((0)) FOR [JnlVatDebit]
ALTER TABLE [dbo].[JOURNALSRECUR] ADD  CONSTRAINT [DF_JOURNALSRECUR_JnlVatCredit]  DEFAULT ((0)) FOR [JnlVatCredit]
ALTER TABLE [dbo].[JOURNALSRECUR] ADD  CONSTRAINT [DF_JOURNALSRECUR_JnlHomeCurrency]  DEFAULT ((0)) FOR [JnlHomeCurrency]
ALTER TABLE [dbo].[JOURNALSRECUR] ADD  CONSTRAINT [DF_JOURNALSRECUR_JnlPlant]  DEFAULT ('') FOR [JnlPlant]
ALTER TABLE [dbo].[JOURNALSRECUR] ADD  CONSTRAINT [DF_JOURNALSRECUR_JnlCredno]  DEFAULT ('') FOR [JnlCredno]
ALTER TABLE [dbo].[JOURNALSRECUR] ADD  CONSTRAINT [DF_JOURNALSRECUR_JnlHeadID]  DEFAULT ('1') FOR [JnlHeadID]
ALTER TABLE [dbo].[JOURNALSRECUR] ADD  CONSTRAINT [DF_JOURNALSRECUR_JnlAlloc]  DEFAULT ('') FOR [JnlAlloc]
ALTER TABLE [dbo].[JOURNALSRECUR] ADD  CONSTRAINT [DF_JOURNALSRECUR_JnlVATType]  DEFAULT ('') FOR [JnlVATType]
ALTER TABLE [dbo].[JOURNALSRECUR] ADD  CONSTRAINT [DF_JOURNALSRECUR_JNLEXCHRATE]  DEFAULT ((1)) FOR [JnlExchRate]
ALTER TABLE [dbo].[JOURNALSRECUR] ADD  CONSTRAINT [DF_JOURNALSRECUR_JNLCONTEXCHRATE]  DEFAULT ((1)) FOR [JnlContExchRate]
ALTER TABLE [dbo].[JOURNALSRECUR] ADD  CONSTRAINT [DF_JOURNALSRECUR_JNLTOORG]  DEFAULT ('-1') FOR [JNLTOORG]
ALTER TABLE [dbo].[JOURNALSRECUR] ADD  CONSTRAINT [DF_JOURNALSRECUR_JNLICGLCODE]  DEFAULT ('') FOR [JNLICGLCODE]
ALTER TABLE [dbo].[JOURNALSRECUR] ADD  CONSTRAINT [DF_JOURNALSRECUR_JNLTRANSREF]  DEFAULT ('') FOR [JNLTRANSREF]
ALTER TABLE [dbo].[JOURNALSRECUR] ADD  CONSTRAINT [DF_JOURNALSRECUR_WHTID]  DEFAULT ('-1') FOR [WHTID]
ALTER TABLE [dbo].[JOURNALSRECUR] ADD  CONSTRAINT [DF_JOURNALSRECUR_ASSETNUMBER]  DEFAULT ('') FOR [ASSETNUMBER]
ALTER TABLE [dbo].[JOURNALSRECUR] ADD  CONSTRAINT [DF_JOURNALSRECUR_ASSETTYPE]  DEFAULT ('') FOR [ASSETTYPE]
ALTER TABLE [dbo].[JOURNALSRECUR] ADD  CONSTRAINT [DF_JOURNALSRECUR_CLASSID]  DEFAULT ((-1)) FOR [CLASSID]