/****** Object:  Table [dbo].[JOURNALNOTES]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[JOURNALNOTES](
	[ID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[JNLID] [int] NOT NULL,
	[USERID] [int] NOT NULL,
	[SEQ] [int] NOT NULL,
	[STATUS] [nvarchar](30) NOT NULL,
	[THEDATE] [datetime] NOT NULL,
	[OPENED] [bit] NOT NULL,
	[DESCRIPTION] [text] NOT NULL,
 CONSTRAINT [PK_JOURNALNOTES] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

ALTER TABLE [dbo].[JOURNALNOTES] ADD  CONSTRAINT [DF_JOURNALNOTES_JNLID]  DEFAULT ('-1') FOR [JNLID]
ALTER TABLE [dbo].[JOURNALNOTES] ADD  CONSTRAINT [DF_JOURNALNOTES_USERID]  DEFAULT ('-1') FOR [USERID]
ALTER TABLE [dbo].[JOURNALNOTES] ADD  CONSTRAINT [DF_JOURNALNOTES_SEQ]  DEFAULT ('-1') FOR [SEQ]
ALTER TABLE [dbo].[JOURNALNOTES] ADD  CONSTRAINT [DF_JOURNALNOTES_STATUS]  DEFAULT ('') FOR [STATUS]
ALTER TABLE [dbo].[JOURNALNOTES] ADD  CONSTRAINT [DF_JOURNALNOTES_THEDATE]  DEFAULT (getdate()) FOR [THEDATE]
ALTER TABLE [dbo].[JOURNALNOTES] ADD  CONSTRAINT [DF_JOURNALNOTES_OPENED]  DEFAULT ('0') FOR [OPENED]
ALTER TABLE [dbo].[JOURNALNOTES] ADD  CONSTRAINT [DF_JOURNALNOTES_DESCRIPTION]  DEFAULT ('') FOR [DESCRIPTION]