/****** Object:  Table [dbo].[JOURNALHEADER]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[JOURNALHEADER](
	[JnlHeadBatch] [char](10) NOT NULL,
	[JnlHeadTransRef] [char](10) NOT NULL,
	[JnlHeadDate] [datetime] NULL,
	[JnlHeadCurrency] [char](3) NOT NULL,
	[JnlHeadID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[JnlHeadDescription] [char](55) NOT NULL,
	[JnlHeadPosted] [bit] NOT NULL,
	[JnlUserID] [int] NOT NULL,
	[BorgID] [int] NOT NULL,
	[JnlHeadSubmit] [int] NOT NULL,
	[JnlHeadApproved] [int] NOT NULL,
	[JnlHeadRejected] [int] NOT NULL,
	[JnlUserName] [char](55) NOT NULL,
	[JnlPeriod] [int] NOT NULL,
	[JnlHeadExchRate] [float] NOT NULL,
	[JnlIsAutoIC] [bit] NOT NULL,
	[jnlInProgress] [bit] NOT NULL,
	[LOCKHOLDER] [int] NOT NULL,
	[BATCHMODE] [bit] NOT NULL,
	[JNLAPPROVER] [int] NULL,
	[JNLAPPDATE] [datetime] NULL,
	[JNLPOSTBY] [int] NULL,
	[JNLPOSTDATE] [datetime] NULL,
	[ARCHIVE] [bit] NOT NULL,
	[JNLYEAR] [nvarchar](4) NOT NULL,
	[ISACC] [bit] NOT NULL,
	[ISFASSET] [bit] NOT NULL,
	[ASSETTYPEDEF] [nvarchar](3) NOT NULL,
	[LOGUSERID] [int] NOT NULL,
	[LOGDATETIME] [datetime] NOT NULL,
	[JNLTYPE] [nvarchar](5) NOT NULL,
	[WFVALUEAPPROVED] [bit] NOT NULL,
	[PARKPOSTTYPENAME] [nvarchar](25) NOT NULL,
 CONSTRAINT [PK_JOURNALHEADER] PRIMARY KEY CLUSTERED 
(
	[JnlHeadID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[JOURNALHEADER] ADD  CONSTRAINT [DF_JOURNALHEAD_JnlHeadBatch]  DEFAULT (1) FOR [JnlHeadBatch]
ALTER TABLE [dbo].[JOURNALHEADER] ADD  CONSTRAINT [DF_JOURNALHEAD_JnlHeadTransRef]  DEFAULT ('') FOR [JnlHeadTransRef]
ALTER TABLE [dbo].[JOURNALHEADER] ADD  CONSTRAINT [DF_JOURNALHEAD_JnlHeadCurrency]  DEFAULT ('ZAR') FOR [JnlHeadCurrency]
ALTER TABLE [dbo].[JOURNALHEADER] ADD  CONSTRAINT [DF_JOURNALHEADER_JnlHeadDescription]  DEFAULT ('') FOR [JnlHeadDescription]
ALTER TABLE [dbo].[JOURNALHEADER] ADD  CONSTRAINT [DF_JOURNALHEADER_JnlHeadPosted]  DEFAULT (0) FOR [JnlHeadPosted]
ALTER TABLE [dbo].[JOURNALHEADER] ADD  CONSTRAINT [DF_JOURNALHEADER_JnlUserID]  DEFAULT (1) FOR [JnlUserID]
ALTER TABLE [dbo].[JOURNALHEADER] ADD  CONSTRAINT [DF_JOURNALHEADER_BorgID]  DEFAULT ((-1)) FOR [BorgID]
ALTER TABLE [dbo].[JOURNALHEADER] ADD  CONSTRAINT [DF_JOURNALHEADER_JnlHeadSubmit]  DEFAULT (0) FOR [JnlHeadSubmit]
ALTER TABLE [dbo].[JOURNALHEADER] ADD  CONSTRAINT [DF_JOURNALHEADER_JnlHeadApproved]  DEFAULT (0) FOR [JnlHeadApproved]
ALTER TABLE [dbo].[JOURNALHEADER] ADD  CONSTRAINT [DF_JOURNALHEADER_JnlHeadRejected]  DEFAULT (0) FOR [JnlHeadRejected]
ALTER TABLE [dbo].[JOURNALHEADER] ADD  CONSTRAINT [DF_JOURNALHEADER_JnlUserName]  DEFAULT ('') FOR [JnlUserName]
ALTER TABLE [dbo].[JOURNALHEADER] ADD  CONSTRAINT [DF_JOURNALHEADER_JnlPeriod]  DEFAULT (1) FOR [JnlPeriod]
ALTER TABLE [dbo].[JOURNALHEADER] ADD  CONSTRAINT [DF_JOURNALHEADER_JnlHeadExchRate]  DEFAULT ((1)) FOR [JnlHeadExchRate]
ALTER TABLE [dbo].[JOURNALHEADER] ADD  DEFAULT (0) FOR [JnlIsAutoIC]
ALTER TABLE [dbo].[JOURNALHEADER] ADD  CONSTRAINT [DF_JOURNALHEADER_jnlInProgress]  DEFAULT ((0)) FOR [jnlInProgress]
ALTER TABLE [dbo].[JOURNALHEADER] ADD  DEFAULT ('0') FOR [LOCKHOLDER]
ALTER TABLE [dbo].[JOURNALHEADER] ADD  DEFAULT ('0') FOR [BATCHMODE]
ALTER TABLE [dbo].[JOURNALHEADER] ADD  CONSTRAINT [DF_JOURNALHEADER_JNLAPPROVER]  DEFAULT ((-1)) FOR [JNLAPPROVER]
ALTER TABLE [dbo].[JOURNALHEADER] ADD  CONSTRAINT [DF_JOURNALHEADER_JNLAPPDATE]  DEFAULT (getdate()) FOR [JNLAPPDATE]
ALTER TABLE [dbo].[JOURNALHEADER] ADD  CONSTRAINT [DF_JOURNALHEADER_JNLPOSTBY]  DEFAULT ((-1)) FOR [JNLPOSTBY]
ALTER TABLE [dbo].[JOURNALHEADER] ADD  CONSTRAINT [DF_JOURNALHEADER_JNLPOSTDATE]  DEFAULT (getdate()) FOR [JNLPOSTDATE]
ALTER TABLE [dbo].[JOURNALHEADER] ADD  CONSTRAINT [DF_JOURNALHEADER_ARCHIVE]  DEFAULT ('0') FOR [ARCHIVE]
ALTER TABLE [dbo].[JOURNALHEADER] ADD  CONSTRAINT [DF_JOURNALHEADER_JNLYEAR]  DEFAULT ('') FOR [JNLYEAR]
ALTER TABLE [dbo].[JOURNALHEADER] ADD  CONSTRAINT [DF_JOURNALHEADER_ISACC]  DEFAULT ('0') FOR [ISACC]
ALTER TABLE [dbo].[JOURNALHEADER] ADD  CONSTRAINT [DF_JOURNALHEADER_ISFASSET]  DEFAULT ('0') FOR [ISFASSET]
ALTER TABLE [dbo].[JOURNALHEADER] ADD  CONSTRAINT [DF_JOURNALHEADER_ASSETTYPEDEF]  DEFAULT ('') FOR [ASSETTYPEDEF]
ALTER TABLE [dbo].[JOURNALHEADER] ADD  CONSTRAINT [DF_JOURNALHEADER_LOGUSERID]  DEFAULT ((-1)) FOR [LOGUSERID]
ALTER TABLE [dbo].[JOURNALHEADER] ADD  CONSTRAINT [DF_JOURNALHEADER_LOGDATETIME]  DEFAULT (getdate()) FOR [LOGDATETIME]
ALTER TABLE [dbo].[JOURNALHEADER] ADD  CONSTRAINT [DF_JOURNALHEADER_JNLTYPE]  DEFAULT ('') FOR [JNLTYPE]
ALTER TABLE [dbo].[JOURNALHEADER] ADD  CONSTRAINT [DF_JOURNALHEADER_WFVALUEAPPROVED]  DEFAULT (N'0') FOR [WFVALUEAPPROVED]
ALTER TABLE [dbo].[JOURNALHEADER] ADD  CONSTRAINT [DF_JOURNALHEADER_PARKPOSTTYPENAME]  DEFAULT ('') FOR [PARKPOSTTYPENAME]
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON

CREATE TRIGGER LOGJOURNALHEADER ON JOURNALHEADER
AFTER UPDATE, INSERT
AS 

SET NOCOUNT ON

declare @columnName nvarchar(500)
declare @keyColumn nvarchar(500)
declare @_ID int
declare @logUserID int
declare @logDateTime datetime
declare @context_info int

set @context_info = -1
set @logUserID = -1
set @logDateTime = DATEADD(M, -1, getDate()) 

DECLARE attribCursor CURSOR FOR
select JNLHEADID _ID FROM INSERTED

SELECT @context_info = cast(replace(cast(CONTEXT_INFO as varchar(128)), char(0) COLLATE SQL_Latin1_General_CP1_CI_AS,'') as int) FROM master.dbo.sysprocesses WHERE spid = @@SPID

select @logUserID = isnull(USERID, -1),
@logDateTime = isnull(LOGDATETIME, DATEADD(M, -1, getDate()))
from logcontext 
where LOGID = @context_info
	
delete FROM LOGCONTEXT where LOGID = @context_info
  
OPEN attribCursor
FETCH NEXT FROM attribCursor into @_ID

WHILE @@FETCH_STATUS=0
BEGIN	 
    
  if DATEDIFF(s,@logDateTime, getDate()) > 5 or @logDateTime is null
	BEGIN
		set @logUserID= -1
	END

	UPDATE JOURNALHEADER SET LOGUSERID = @logUserID, LOGDATETIME = getDate() WHERE JNLHEADID = @_ID

	FETCH NEXT FROM attribCursor into @_ID
END   

close attribCursor
DEALLOCATE attribCursor

		
ALTER TABLE [dbo].[JOURNALHEADER] ENABLE TRIGGER [LOGJOURNALHEADER]