/****** Object:  Table [dbo].[JOURNALHEADERRECUR]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[JOURNALHEADERRECUR](
	[JnlHeadID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[JnlHeadBatch] [nvarchar](10) NOT NULL,
	[JnlHeadTransRef] [nvarchar](10) NOT NULL,
	[JnlHeadDate] [datetime] NULL,
	[JnlHeadCurrency] [nvarchar](3) NOT NULL,
	[JnlHeadDescription] [nvarchar](55) NOT NULL,
	[JnlUserID] [int] NOT NULL,
	[BorgID] [int] NOT NULL,
	[JnlUserName] [nvarchar](55) NOT NULL,
	[JnlPeriod] [int] NOT NULL,
	[JnlHeadExchRate] [float] NOT NULL,
	[JNLYEAR] [nvarchar](4) NOT NULL,
	[JnlHeadPosted] [int] NOT NULL,
	[JnlHeadSubmit] [int] NOT NULL,
	[JnlHeadApproved] [int] NOT NULL,
	[JnlHeadRejected] [int] NOT NULL,
	[JnlIsAutoIC] [int] NOT NULL,
	[jnlInProgress] [int] NOT NULL,
	[LOCKHOLDER] [int] NOT NULL,
	[BATCHMODE] [int] NOT NULL,
	[ARCHIVE] [int] NOT NULL,
	[INUSE] [int] NOT NULL,
	[USEFROMPERIOD] [int] NOT NULL,
	[USEFROMYEAR] [int] NOT NULL,
	[USETOPERIOD] [int] NOT NULL,
	[USETOYEAR] [int] NOT NULL,
	[RECURPERIOD] [int] NOT NULL,
	[LASTRECURPERIOD] [int] NOT NULL,
	[LASTRECURYEAR] [int] NOT NULL,
	[ISACC] [bit] NOT NULL,
	[ISFASSET] [bit] NOT NULL,
	[ASSETTYPEDEF] [varchar](3) NOT NULL,
	[LOGUSERID] [int] NOT NULL,
	[LOGDATETIME] [datetime] NOT NULL,
	[JNLTYPE] [nvarchar](5) NOT NULL,
 CONSTRAINT [PK_JOURNALHEADERRECUR] PRIMARY KEY CLUSTERED 
(
	[JnlHeadID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[JOURNALHEADERRECUR] ADD  CONSTRAINT [DF_JOURNALHEADERRECUR_JnlHeadBatch]  DEFAULT ('') FOR [JnlHeadBatch]
ALTER TABLE [dbo].[JOURNALHEADERRECUR] ADD  CONSTRAINT [DF_JOURNALHEADERRECUR_JnlHeadTransRef]  DEFAULT ('') FOR [JnlHeadTransRef]
ALTER TABLE [dbo].[JOURNALHEADERRECUR] ADD  CONSTRAINT [DF_JOURNALHEADERRECUR_JnlHeadCurrency]  DEFAULT ('') FOR [JnlHeadCurrency]
ALTER TABLE [dbo].[JOURNALHEADERRECUR] ADD  CONSTRAINT [DF_JOURNALHEADERRECUR_JnlHeadDescription]  DEFAULT ('') FOR [JnlHeadDescription]
ALTER TABLE [dbo].[JOURNALHEADERRECUR] ADD  CONSTRAINT [DF_JOURNALHEADERRECUR_JnlUserID]  DEFAULT ('-1') FOR [JnlUserID]
ALTER TABLE [dbo].[JOURNALHEADERRECUR] ADD  CONSTRAINT [DF_JOURNALHEADERRECUR_BorgID]  DEFAULT ('-1') FOR [BorgID]
ALTER TABLE [dbo].[JOURNALHEADERRECUR] ADD  CONSTRAINT [DF_JOURNALHEADERRECUR_JnlUserName]  DEFAULT ('') FOR [JnlUserName]
ALTER TABLE [dbo].[JOURNALHEADERRECUR] ADD  CONSTRAINT [DF_JOURNALHEADERRECUR_JnlPeriod]  DEFAULT ('-1') FOR [JnlPeriod]
ALTER TABLE [dbo].[JOURNALHEADERRECUR] ADD  CONSTRAINT [DF_JOURNALHEADERRECUR_JnlHeadExchRate]  DEFAULT ('1') FOR [JnlHeadExchRate]
ALTER TABLE [dbo].[JOURNALHEADERRECUR] ADD  CONSTRAINT [DF_JOURNALHEADERRECUR_JNLYEAR]  DEFAULT ('') FOR [JNLYEAR]
ALTER TABLE [dbo].[JOURNALHEADERRECUR] ADD  CONSTRAINT [DF_JOURNALHEADERRECUR_JnlHeadPosted]  DEFAULT ('-1') FOR [JnlHeadPosted]
ALTER TABLE [dbo].[JOURNALHEADERRECUR] ADD  CONSTRAINT [DF_JOURNALHEADERRECUR_JnlHeadSubmit]  DEFAULT ('-1') FOR [JnlHeadSubmit]
ALTER TABLE [dbo].[JOURNALHEADERRECUR] ADD  CONSTRAINT [DF_JOURNALHEADERRECUR_JnlHeadApproved]  DEFAULT ('-1') FOR [JnlHeadApproved]
ALTER TABLE [dbo].[JOURNALHEADERRECUR] ADD  CONSTRAINT [DF_JOURNALHEADERRECUR_JnlHeadRejected]  DEFAULT ('-1') FOR [JnlHeadRejected]
ALTER TABLE [dbo].[JOURNALHEADERRECUR] ADD  CONSTRAINT [DF_JOURNALHEADERRECUR_JnlIsAutoIC]  DEFAULT ('-1') FOR [JnlIsAutoIC]
ALTER TABLE [dbo].[JOURNALHEADERRECUR] ADD  CONSTRAINT [DF_JOURNALHEADERRECUR_jnlInProgress]  DEFAULT ('-1') FOR [jnlInProgress]
ALTER TABLE [dbo].[JOURNALHEADERRECUR] ADD  CONSTRAINT [DF_JOURNALHEADERRECUR_LOCKHOLDER]  DEFAULT ('-1') FOR [LOCKHOLDER]
ALTER TABLE [dbo].[JOURNALHEADERRECUR] ADD  CONSTRAINT [DF_JOURNALHEADERRECUR_BATCHMODE]  DEFAULT ('-1') FOR [BATCHMODE]
ALTER TABLE [dbo].[JOURNALHEADERRECUR] ADD  CONSTRAINT [DF_JOURNALHEADERRECUR_ARCHIVE]  DEFAULT ('-1') FOR [ARCHIVE]
ALTER TABLE [dbo].[JOURNALHEADERRECUR] ADD  CONSTRAINT [DF_JOURNALHEADERRECUR_INUSE]  DEFAULT ('1') FOR [INUSE]
ALTER TABLE [dbo].[JOURNALHEADERRECUR] ADD  CONSTRAINT [DF_JOURNALHEADERRECUR_USEFROMPERIOD]  DEFAULT ('-1') FOR [USEFROMPERIOD]
ALTER TABLE [dbo].[JOURNALHEADERRECUR] ADD  CONSTRAINT [DF_JOURNALHEADERRECUR_USEFROMYEAR]  DEFAULT ('-1') FOR [USEFROMYEAR]
ALTER TABLE [dbo].[JOURNALHEADERRECUR] ADD  CONSTRAINT [DF_JOURNALHEADERRECUR_USETOPERIOD]  DEFAULT ('-1') FOR [USETOPERIOD]
ALTER TABLE [dbo].[JOURNALHEADERRECUR] ADD  CONSTRAINT [DF_JOURNALHEADERRECUR_USETOYEAR]  DEFAULT ('-1') FOR [USETOYEAR]
ALTER TABLE [dbo].[JOURNALHEADERRECUR] ADD  CONSTRAINT [DF_JOURNALHEADERRECUR_RECURPERIOD]  DEFAULT ('1') FOR [RECURPERIOD]
ALTER TABLE [dbo].[JOURNALHEADERRECUR] ADD  CONSTRAINT [DF_JOURNALHEADERRECUR_LASTRECURPERIOD]  DEFAULT ('-1') FOR [LASTRECURPERIOD]
ALTER TABLE [dbo].[JOURNALHEADERRECUR] ADD  CONSTRAINT [DF_JOURNALHEADERRECUR_LASTRECURYEAR]  DEFAULT ('-1') FOR [LASTRECURYEAR]
ALTER TABLE [dbo].[JOURNALHEADERRECUR] ADD  CONSTRAINT [DF_JOURNALHEADERRECUR_ISACC]  DEFAULT ('0') FOR [ISACC]
ALTER TABLE [dbo].[JOURNALHEADERRECUR] ADD  CONSTRAINT [DF_JOURNALHEADERRECUR_ISFASSET]  DEFAULT ('0') FOR [ISFASSET]
ALTER TABLE [dbo].[JOURNALHEADERRECUR] ADD  CONSTRAINT [DF_JOURNALHEADERRECUR_ASSETTYPEDEF]  DEFAULT ('') FOR [ASSETTYPEDEF]
ALTER TABLE [dbo].[JOURNALHEADERRECUR] ADD  CONSTRAINT [DF_JOURNALHEADERRECUR_LOGUSERID]  DEFAULT ((-1)) FOR [LOGUSERID]
ALTER TABLE [dbo].[JOURNALHEADERRECUR] ADD  CONSTRAINT [DF_JOURNALHEADERRECUR_LOGDATETIME]  DEFAULT (getdate()) FOR [LOGDATETIME]
ALTER TABLE [dbo].[JOURNALHEADERRECUR] ADD  CONSTRAINT [DF_JOURNALHEADERRECUR_JNLTYPE]  DEFAULT ('') FOR [JNLTYPE]