/****** Object:  Table [dbo].[LEDGERCODEGROUPHEADER]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[LEDGERCODEGROUPHEADER](
	[ID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[NAME] [nvarchar](55) NOT NULL,
	[SYS] [nvarchar](3) NOT NULL,
	[ALLOC] [nvarchar](15) NOT NULL,
 CONSTRAINT [PK_LEDGERCODEGROUPHEADER] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[LEDGERCODEGROUPHEADER] ADD  CONSTRAINT [DF_LEDGERCODEGROUPHEADER_NAME]  DEFAULT ('') FOR [NAME]
ALTER TABLE [dbo].[LEDGERCODEGROUPHEADER] ADD  CONSTRAINT [DF_LEDGERCODEGROUPHEADER_SYS]  DEFAULT ('') FOR [SYS]
ALTER TABLE [dbo].[LEDGERCODEGROUPHEADER] ADD  CONSTRAINT [DF_LEDGERCODEGROUPHEADER_ALLOC]  DEFAULT ('Contracts') FOR [ALLOC]