/****** Object:  Table [dbo].[LOADEDSCRIPTS]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[LOADEDSCRIPTS](
	[SCRIPT] [nvarchar](255) NOT NULL,
	[APPLICATION] [nvarchar](3) NOT NULL,
 CONSTRAINT [PK_LOADEDSCRIPTS] PRIMARY KEY CLUSTERED 
(
	[SCRIPT] ASC,
	[APPLICATION] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[LOADEDSCRIPTS] ADD  CONSTRAINT [DF_LOADEDSCRIPTS_SCRIPT]  DEFAULT ('') FOR [SCRIPT]
ALTER TABLE [dbo].[LOADEDSCRIPTS] ADD  CONSTRAINT [DF_LOADEDSCRIPTS_APPLICATION]  DEFAULT ('ACC') FOR [APPLICATION]