/****** Object:  Table [dbo].[LOGCONTEXT]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[LOGCONTEXT](
	[LOGID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[USERID] [int] NOT NULL,
	[BORGID] [int] NOT NULL,
	[LOGDATETIME] [datetime] NULL,
	[PAGE] [nvarchar](250) NOT NULL,
	[INFO] [nvarchar](250) NOT NULL,
	[APPLICATION] [nvarchar](3) NOT NULL,
	[VERSION] [nvarchar](15) NOT NULL,
 CONSTRAINT [PK_LOGCONTEXT] PRIMARY KEY CLUSTERED 
(
	[LOGID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[LOGCONTEXT] ADD  CONSTRAINT [DF_LOGCONTEXT_USERID]  DEFAULT ((-1)) FOR [USERID]
ALTER TABLE [dbo].[LOGCONTEXT] ADD  CONSTRAINT [DF_LOGCONTEXT_BORGID]  DEFAULT ((-1)) FOR [BORGID]
ALTER TABLE [dbo].[LOGCONTEXT] ADD  CONSTRAINT [DF_LOGCONTEXT_LOGDATETIME]  DEFAULT (getdate()) FOR [LOGDATETIME]
ALTER TABLE [dbo].[LOGCONTEXT] ADD  CONSTRAINT [DF_LOGCONTEXT_PAGE]  DEFAULT ('') FOR [PAGE]
ALTER TABLE [dbo].[LOGCONTEXT] ADD  CONSTRAINT [DF_LOGCONTEXT_INFO]  DEFAULT ('') FOR [INFO]
ALTER TABLE [dbo].[LOGCONTEXT] ADD  CONSTRAINT [DF_LOGCONTEXT_APPLICATION]  DEFAULT ('') FOR [APPLICATION]
ALTER TABLE [dbo].[LOGCONTEXT] ADD  CONSTRAINT [DF_LOGCONTEXT_VERSION]  DEFAULT ('') FOR [VERSION]