/****** Object:  Table [dbo].[LOGOS]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[LOGOS](
	[ID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[NAME] [nvarchar](50) NOT NULL,
	[DESCRIPTION] [nvarchar](255) NOT NULL,
	[CONTENTTYPE] [nvarchar](255) NOT NULL,
	[FILENAME] [nvarchar](255) NULL,
	[LOGO] [image] NOT NULL,
	[GRP] [nvarchar](50) NOT NULL,
	[IMAGEWIDTH] [float] NOT NULL,
	[IMAGEHEIGHT] [float] NOT NULL,
 CONSTRAINT [PK_LOGOS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

ALTER TABLE [dbo].[LOGOS] ADD  CONSTRAINT [DF_LOGOS_DESCRIPTION]  DEFAULT ('') FOR [DESCRIPTION]
ALTER TABLE [dbo].[LOGOS] ADD  CONSTRAINT [DF_LOGOS_CONTENTTYPE]  DEFAULT ('') FOR [CONTENTTYPE]
ALTER TABLE [dbo].[LOGOS] ADD  CONSTRAINT [DF_LOGOS_GRP]  DEFAULT ('') FOR [GRP]
ALTER TABLE [dbo].[LOGOS] ADD  CONSTRAINT [DF_LOGOS_IMAGEWIDTH]  DEFAULT ('0') FOR [IMAGEWIDTH]
ALTER TABLE [dbo].[LOGOS] ADD  CONSTRAINT [DF_LOGOS_IMAGEHEIGHT]  DEFAULT ('0') FOR [IMAGEHEIGHT]