/****** Object:  Table [dbo].[LOOKUP]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[LOOKUP](
	[ID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[CODE] [nvarchar](100) NOT NULL,
	[VALUE] [nvarchar](100) NOT NULL,
	[LOOKUPTYPEID] [int] NOT NULL,
	[ISDELETED] [bit] NOT NULL,
	[IsSysEntry] [bit] NOT NULL,
 CONSTRAINT [PK_LOOKUP] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[LOOKUP] ADD  CONSTRAINT [DF_LOOKUP_IsSysEntry]  DEFAULT (N'1') FOR [IsSysEntry]
ALTER TABLE [dbo].[LOOKUP]  WITH CHECK ADD  CONSTRAINT [FK_LOOKUP_LOOKUPTYPE] FOREIGN KEY([LOOKUPTYPEID])
REFERENCES [dbo].[LOOKUPTYPE] ([ID])
ALTER TABLE [dbo].[LOOKUP] CHECK CONSTRAINT [FK_LOOKUP_LOOKUPTYPE]