/****** Object:  Table [dbo].[LOOKUPTYPE]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[LOOKUPTYPE](
	[ID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[CODE] [nvarchar](100) NOT NULL,
	[VALUE] [nvarchar](100) NOT NULL,
	[CHILDID] [int] NULL,
	[ISDELETED] [bit] NOT NULL,
	[IsSysEntry] [bit] NOT NULL,
 CONSTRAINT [PK_LOOKUPTYPE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[LOOKUPTYPE] ADD  CONSTRAINT [DF_LOOKUPTYPE_IsSysEntry]  DEFAULT (N'1') FOR [IsSysEntry]
ALTER TABLE [dbo].[LOOKUPTYPE]  WITH CHECK ADD  CONSTRAINT [FK_LOOKUPTYPE_LOOKUPTYPE] FOREIGN KEY([CHILDID])
REFERENCES [dbo].[LOOKUPTYPE] ([ID])
ALTER TABLE [dbo].[LOOKUPTYPE] CHECK CONSTRAINT [FK_LOOKUPTYPE_LOOKUPTYPE]