/****** Object:  Table [dbo].[MANAMIBIA]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[MANAMIBIA](
	[MAID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[TABLETYPE] [nvarchar](20) NOT NULL,
	[FROMRATE] [decimal](18, 2) NOT NULL,
	[TORATE] [decimal](18, 2) NOT NULL,
	[D0] [decimal](18, 2) NOT NULL,
	[D1] [decimal](18, 2) NOT NULL,
	[D2] [decimal](18, 2) NOT NULL,
	[D3] [decimal](18, 2) NOT NULL,
	[D4] [decimal](18, 2) NOT NULL,
	[D5] [decimal](18, 2) NOT NULL,
	[D6] [decimal](18, 2) NOT NULL,
	[D6MORE] [decimal](18, 2) NOT NULL,
 CONSTRAINT [PK_MANAMIBIA] PRIMARY KEY CLUSTERED 
(
	[MAID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[MANAMIBIA] ADD  CONSTRAINT [DF_MANAMIBIA_TABLETYPE_1]  DEFAULT ('') FOR [TABLETYPE]
ALTER TABLE [dbo].[MANAMIBIA] ADD  CONSTRAINT [DF_MANAMIBIA_FROMRATE]  DEFAULT ((0)) FOR [FROMRATE]
ALTER TABLE [dbo].[MANAMIBIA] ADD  CONSTRAINT [DF_MANAMIBIA_UPTO]  DEFAULT ((0)) FOR [TORATE]
ALTER TABLE [dbo].[MANAMIBIA] ADD  CONSTRAINT [DF_MANAMIBIA_DEPENDANTS]  DEFAULT ((0)) FOR [D0]
ALTER TABLE [dbo].[MANAMIBIA] ADD  CONSTRAINT [DF_MANAMIBIA_TABLETYPE]  DEFAULT ((0)) FOR [D1]
ALTER TABLE [dbo].[MANAMIBIA] ADD  CONSTRAINT [DF_MANAMIBIA_MAAMOUNT]  DEFAULT ((0)) FOR [D2]
ALTER TABLE [dbo].[MANAMIBIA] ADD  CONSTRAINT [DF_MANAMIBIA_UPTOAMOUNT]  DEFAULT ((0)) FOR [D3]
ALTER TABLE [dbo].[MANAMIBIA] ADD  CONSTRAINT [DF_MANAMIBIA_D4]  DEFAULT ((0)) FOR [D4]
ALTER TABLE [dbo].[MANAMIBIA] ADD  CONSTRAINT [DF_MANAMIBIA_D5]  DEFAULT ((0)) FOR [D5]
ALTER TABLE [dbo].[MANAMIBIA] ADD  CONSTRAINT [DF_MANAMIBIA_D6]  DEFAULT ((0)) FOR [D6]
ALTER TABLE [dbo].[MANAMIBIA] ADD  CONSTRAINT [DF_MANAMIBIA_DMORE]  DEFAULT ((0)) FOR [D6MORE]