/****** Object:  Table [dbo].[MARKETSITE]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[MARKETSITE](
	[MSID] [int] NOT NULL,
	[MSNAME] [nvarchar](75) NOT NULL,
	[MSMPID] [nvarchar](36) NOT NULL,
	[MSURL] [nvarchar](254) NULL,
 CONSTRAINT [PK_MARKETSITE] PRIMARY KEY CLUSTERED 
(
	[MSID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]