/****** Object:  Table [dbo].[MATERIALS]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[MATERIALS](
	[MATERIALID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[DESCRIPTION] [nvarchar](255) NOT NULL,
	[GLCODE] [nvarchar](35) NOT NULL,
	[PARENTID] [int] NOT NULL,
	[PICTURELOCATION] [nvarchar](255) NOT NULL,
 CONSTRAINT [PK_MATERIALS] PRIMARY KEY CLUSTERED 
(
	[MATERIALID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[MATERIALS] ADD  CONSTRAINT [DF_MATERIALS_DESCRIPTION]  DEFAULT ('') FOR [DESCRIPTION]
ALTER TABLE [dbo].[MATERIALS] ADD  CONSTRAINT [DF_MATERIALS_GLCODE]  DEFAULT ('') FOR [GLCODE]
ALTER TABLE [dbo].[MATERIALS] ADD  CONSTRAINT [DF_MATERIALS_PARENTID]  DEFAULT ((-1)) FOR [PARENTID]
ALTER TABLE [dbo].[MATERIALS] ADD  CONSTRAINT [DF_MATERIALS_PICTURELOCATION]  DEFAULT ('') FOR [PICTURELOCATION]