/****** Object:  Table [dbo].[MIBFA]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[MIBFA](
	[PKLMIBFAID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[PAYROLLID] [int] NOT NULL,
	[EDSHID] [int] NOT NULL,
	[INAGREEMENTWBC] [bit] NOT NULL,
	[INDUSTRYWAGECATEGORY] [nvarchar](10) NOT NULL,
	[EMPLOYERLEVYAMOUNT] [decimal](18, 4) NOT NULL,
	[TOTALCOLLBARGEMPOYERLEVY] [decimal](18, 4) NOT NULL,
	[EMPLOYERPENSIONAMOUNT] [nvarchar](10) NOT NULL,
	[COUNCILADMINISTRATIONEMPLOYEELEVY] [nvarchar](10) NOT NULL,
	[COUNCILCOLLECTIVEBARGAININGEMPLOYEELEVY] [nvarchar](10) NOT NULL,
	[COUNCILDISPUTERESOLUTIONEMPLOYEELEVY] [nvarchar](10) NOT NULL,
	[EMPLOYEEPENSIONAMOUNT] [nvarchar](10) NOT NULL,
	[EMPLOYEEPOVIDENTAMOUNT] [nvarchar](10) NOT NULL,
	[EMPLOYERPOVIDENTAMOUNT] [nvarchar](10) NOT NULL,
	[SICKPAYEMPLOYEEAMOUNT] [nvarchar](10) NOT NULL,
	[SICKPAYEMPLOYERAMOUNT] [nvarchar](10) NOT NULL,
	[VOLUNTARYEMPLOYEEAMOUNT] [nvarchar](10) NOT NULL,
	[VOLUNTARYEMPLOYEEPOVIDENAMOUNT] [nvarchar](10) NOT NULL,
	[VOLUNTARYEMPLOYERAMOUNT] [nvarchar](10) NOT NULL,
	[VOLUNTARYEMPLOYERPOVIDENAMOUNT] [nvarchar](10) NOT NULL,
	[ISMEMBEREMPLOYERFEDERATION] [bit] NOT NULL,
 CONSTRAINT [PK_MIBFA] PRIMARY KEY CLUSTERED 
(
	[PKLMIBFAID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[MIBFA] ADD  CONSTRAINT [DF_MIBFA_INAGREEMENTWBC]  DEFAULT ((0)) FOR [INAGREEMENTWBC]
ALTER TABLE [dbo].[MIBFA] ADD  CONSTRAINT [DF_MIBFA_INDUSTRYWAGECATEGORY]  DEFAULT ('') FOR [INDUSTRYWAGECATEGORY]
ALTER TABLE [dbo].[MIBFA] ADD  CONSTRAINT [DF_MIBFA_EMPLOYERLEVYAMOUNT]  DEFAULT ((0)) FOR [EMPLOYERLEVYAMOUNT]
ALTER TABLE [dbo].[MIBFA] ADD  CONSTRAINT [DF_MIBFA_TOTALCOLLBARGEMPOYERLEVY]  DEFAULT ((185)) FOR [TOTALCOLLBARGEMPOYERLEVY]
ALTER TABLE [dbo].[MIBFA] ADD  CONSTRAINT [DF_MIBFA_EMPLOYERPENSIONAMOUNT]  DEFAULT ('NTM') FOR [EMPLOYERPENSIONAMOUNT]
ALTER TABLE [dbo].[MIBFA] ADD  CONSTRAINT [DF_MIBFA_COUNCILADMINISTRATIONEMPLOYEELEVY]  DEFAULT ('NTM') FOR [COUNCILADMINISTRATIONEMPLOYEELEVY]
ALTER TABLE [dbo].[MIBFA] ADD  CONSTRAINT [DF_MIBFA_COUNCILCOLLECTIVEBARGAININGEMPLOYEELEVY]  DEFAULT ('NTM') FOR [COUNCILCOLLECTIVEBARGAININGEMPLOYEELEVY]
ALTER TABLE [dbo].[MIBFA] ADD  CONSTRAINT [DF_MIBFA_COUNCILDISPUTERESOLUTIONEMPLOYEELEVY]  DEFAULT ('NTM') FOR [COUNCILDISPUTERESOLUTIONEMPLOYEELEVY]
ALTER TABLE [dbo].[MIBFA] ADD  CONSTRAINT [DF_MIBFA_EMPLOYEEPENSIONAMOUNT]  DEFAULT ('NTM') FOR [EMPLOYEEPENSIONAMOUNT]
ALTER TABLE [dbo].[MIBFA] ADD  CONSTRAINT [DF_MIBFA_EMPLOYEEPOVIDENTAMOUNT]  DEFAULT ('NTM') FOR [EMPLOYEEPOVIDENTAMOUNT]
ALTER TABLE [dbo].[MIBFA] ADD  CONSTRAINT [DF_MIBFA_EMPLOYERPOVIDENTAMOUNT]  DEFAULT ('NTM') FOR [EMPLOYERPOVIDENTAMOUNT]
ALTER TABLE [dbo].[MIBFA] ADD  CONSTRAINT [DF_MIBFA_SICKPAYEMPLOYEEAMOUNT]  DEFAULT ('NTM') FOR [SICKPAYEMPLOYEEAMOUNT]
ALTER TABLE [dbo].[MIBFA] ADD  CONSTRAINT [DF_MIBFA_SICKPAYEMPLOYERAMOUNT]  DEFAULT ('NTM') FOR [SICKPAYEMPLOYERAMOUNT]
ALTER TABLE [dbo].[MIBFA] ADD  CONSTRAINT [DF_MIBFA_VOLUNTARYEMPLOYEEAMOUNT]  DEFAULT ('NTM') FOR [VOLUNTARYEMPLOYEEAMOUNT]
ALTER TABLE [dbo].[MIBFA] ADD  CONSTRAINT [DF_MIBFA_VOLUNTARYEMPLOYEEPOVIDENAMOUNT]  DEFAULT ('NTM') FOR [VOLUNTARYEMPLOYEEPOVIDENAMOUNT]
ALTER TABLE [dbo].[MIBFA] ADD  CONSTRAINT [DF_MIBFA_VOLUNTARYEMPLOYERAMOUNT]  DEFAULT ('NTM') FOR [VOLUNTARYEMPLOYERAMOUNT]
ALTER TABLE [dbo].[MIBFA] ADD  CONSTRAINT [DF_MIBFA_VOLUNTARYEMPLOYERPOVIDENAMOUNT]  DEFAULT ('NTM') FOR [VOLUNTARYEMPLOYERPOVIDENAMOUNT]
ALTER TABLE [dbo].[MIBFA] ADD  CONSTRAINT [DF_MIBFA_ISMEMBEREMPLOYERFEDERATION]  DEFAULT ((0)) FOR [ISMEMBEREMPLOYERFEDERATION]