/****** Object:  Table [dbo].[ORD]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[ORD](
	[ORDID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[BORGID] [int] NOT NULL,
	[ORDNUMBER] [nvarchar](55) NOT NULL,
	[ORDSTATUSID] [int] NOT NULL,
	[ORDSTATUSDATE] [datetime] NOT NULL,
	[USERID] [int] NOT NULL,
	[CREATEDATE] [datetime] NOT NULL,
	[SHORTDESCR] [nvarchar](125) NOT NULL,
	[MIMETYPE] [nvarchar](100) NOT NULL,
	[FILESIZEINKB] [int] NOT NULL,
	[FILEPATH] [nvarchar](255) NOT NULL,
	[ORIGINALFILEPATH] [nvarchar](255) NOT NULL,
	[EID] [char](10) NOT NULL,
	[ATTMESSAGE] [ntext] NOT NULL,
	[SENDATTTOSUPP] [bit] NOT NULL,
	[INVTOID] [int] NOT NULL,
	[LASTCHANGE] [datetime] NULL,
	[LASTCHANGEBY] [int] NULL,
	[REQID] [int] NOT NULL,
	[SUPPID] [int] NOT NULL,
	[CURRENCY] [nvarchar](3) NOT NULL,
	[CHANGENOTE] [ntext] NULL,
	[SUPPREPLIED] [bit] NOT NULL,
	[SUPPREJECTED] [bit] NOT NULL,
	[ACCEPTED] [bit] NOT NULL,
	[ISEXTPO] [bit] NOT NULL,
	[RECTYPE] [nvarchar](3) NOT NULL,
	[SENTTOSUPP] [bit] NOT NULL,
	[HOMECURRENCY] [nvarchar](3) NOT NULL,
	[EXCHRATE] [decimal](23, 6) NOT NULL,
	[WHTID] [int] NULL,
	[TERM] [int] NOT NULL,
	[ISBULKORDER] [bit] NOT NULL,
	[IMPORTED] [bit] NOT NULL,
	[LOGUSERID] [int] NOT NULL,
	[LOGDATETIME] [datetime] NOT NULL,
 CONSTRAINT [PK_ORD] PRIMARY KEY CLUSTERED 
(
	[ORDID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

CREATE NONCLUSTERED INDEX [IX_ORD_BORGID] ON [dbo].[ORD]
(
	[BORGID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
CREATE NONCLUSTERED INDEX [IX_ORD_BORGID_ORDID_SUPPID] ON [dbo].[ORD]
(
	[BORGID] ASC,
	[ORDID] ASC,
	[SUPPID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [IX_ORD_ORDNUMBER] ON [dbo].[ORD]
(
	[ORDNUMBER] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
CREATE NONCLUSTERED INDEX [IX_ORD_ORDSTATUSID] ON [dbo].[ORD]
(
	[ORDSTATUSID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [IX_ORD_RECTYPE] ON [dbo].[ORD]
(
	[RECTYPE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
CREATE NONCLUSTERED INDEX [IX_ORD_REQID] ON [dbo].[ORD]
(
	[REQID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
ALTER TABLE [dbo].[ORD] ADD  CONSTRAINT [DF_ORD_ORDNUMBER]  DEFAULT ('') FOR [ORDNUMBER]
ALTER TABLE [dbo].[ORD] ADD  CONSTRAINT [DF_ORD_CURRENCY]  DEFAULT ('ZAR') FOR [CURRENCY]
ALTER TABLE [dbo].[ORD] ADD  CONSTRAINT [DF_ORD_SUPPREPLIED]  DEFAULT ((0)) FOR [SUPPREPLIED]
ALTER TABLE [dbo].[ORD] ADD  CONSTRAINT [DF_ORD_SUPPREJECTED]  DEFAULT ((0)) FOR [SUPPREJECTED]
ALTER TABLE [dbo].[ORD] ADD  CONSTRAINT [DF_ORD_ACCEPTED]  DEFAULT ((0)) FOR [ACCEPTED]
ALTER TABLE [dbo].[ORD] ADD  CONSTRAINT [DF_ORD_ISEXTPO]  DEFAULT ((0)) FOR [ISEXTPO]
ALTER TABLE [dbo].[ORD] ADD  CONSTRAINT [DF_ORD_RECTYPE]  DEFAULT ('STD') FOR [RECTYPE]
ALTER TABLE [dbo].[ORD] ADD  CONSTRAINT [DF_ORD_SENTTOSUPP]  DEFAULT ((0)) FOR [SENTTOSUPP]
ALTER TABLE [dbo].[ORD] ADD  CONSTRAINT [DF_ORD_HOMECURRENCY]  DEFAULT ('') FOR [HOMECURRENCY]
ALTER TABLE [dbo].[ORD] ADD  CONSTRAINT [DF_ORD_EXCHRATE]  DEFAULT ((1)) FOR [EXCHRATE]
ALTER TABLE [dbo].[ORD] ADD  CONSTRAINT [DF_ORD_TERM]  DEFAULT ((0)) FOR [TERM]
ALTER TABLE [dbo].[ORD] ADD  CONSTRAINT [DF_ORD_ISBULKORDER]  DEFAULT ((0)) FOR [ISBULKORDER]
ALTER TABLE [dbo].[ORD] ADD  CONSTRAINT [DF_ORD_IMPORTED]  DEFAULT ('0') FOR [IMPORTED]
ALTER TABLE [dbo].[ORD] ADD  CONSTRAINT [DF_ORD_LOGUSERID]  DEFAULT ((-1)) FOR [LOGUSERID]
ALTER TABLE [dbo].[ORD] ADD  CONSTRAINT [DF_ORD_LOGDATETIME]  DEFAULT (getdate()) FOR [LOGDATETIME]
ALTER TABLE [dbo].[ORD]  WITH CHECK ADD  CONSTRAINT [FK_ORD_BILLTOADDRESSES] FOREIGN KEY([INVTOID])
REFERENCES [dbo].[BILLTOADDRESSES] ([BILLTOID])
ALTER TABLE [dbo].[ORD] CHECK CONSTRAINT [FK_ORD_BILLTOADDRESSES]
ALTER TABLE [dbo].[ORD]  WITH CHECK ADD  CONSTRAINT [FK_ORD_BORGS] FOREIGN KEY([BORGID])
REFERENCES [dbo].[BORGS] ([BORGID])
ALTER TABLE [dbo].[ORD] CHECK CONSTRAINT [FK_ORD_BORGS]
ALTER TABLE [dbo].[ORD]  WITH CHECK ADD  CONSTRAINT [FK_ORD_CURRENCIES] FOREIGN KEY([CURRENCY])
REFERENCES [dbo].[CURRENCIES] ([CURRCODE])
ALTER TABLE [dbo].[ORD] CHECK CONSTRAINT [FK_ORD_CURRENCIES]
ALTER TABLE [dbo].[ORD]  WITH CHECK ADD  CONSTRAINT [FK_ORD_REQ] FOREIGN KEY([REQID])
REFERENCES [dbo].[REQ] ([REQID])
ALTER TABLE [dbo].[ORD] CHECK CONSTRAINT [FK_ORD_REQ]
ALTER TABLE [dbo].[ORD]  WITH CHECK ADD  CONSTRAINT [FK_ORD_TAXWHT] FOREIGN KEY([WHTID])
REFERENCES [dbo].[TAXWHT] ([WHTID])
ALTER TABLE [dbo].[ORD] CHECK CONSTRAINT [FK_ORD_TAXWHT]
ALTER TABLE [dbo].[ORD]  WITH CHECK ADD  CONSTRAINT [FK_ORD_USERS] FOREIGN KEY([USERID])
REFERENCES [dbo].[USERS] ([USERID])
ALTER TABLE [dbo].[ORD] CHECK CONSTRAINT [FK_ORD_USERS]
ALTER TABLE [dbo].[ORD]  WITH NOCHECK ADD  CONSTRAINT [FK_ORD_USERS1] FOREIGN KEY([LASTCHANGEBY])
REFERENCES [dbo].[USERS] ([USERID])
NOT FOR REPLICATION 
ALTER TABLE [dbo].[ORD] NOCHECK CONSTRAINT [FK_ORD_USERS1]
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON

CREATE TRIGGER LOGORD ON ORD
AFTER UPDATE, INSERT
AS 

SET NOCOUNT ON

declare @columnName nvarchar(500)
declare @keyColumn nvarchar(500)
declare @tableName nvarchar(500)
declare @sSql nvarchar(4000)
declare @primaryKey nvarchar(500)
declare @_ID nvarchar(500)
declare @logUserID int
declare @logDateTime datetime
declare @context_info int

SELECT @tableName = o.name
FROM sysobjects t
JOIN sysobjects o ON t.parent_obj = o.id
WHERE t.id = @@PROCID

set @context_info = -1
set @primaryKey = ''
set @logUserID = -1
set @logDateTime = DATEADD(M, -1, getDate()) 


/*GETS THE PRIMARY KEY COLUMNS*/
SELECT COLUMN_NAME
into #primanyKeys
FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE
WHERE OBJECTPROPERTY(OBJECT_ID(constraint_name), 'IsPrimaryKey') = 1
AND table_name = @tableName

select ORDID into #inserted from INSERTED

set @sSql = 'DECLARE attribCursor CURSOR FOR '
set @sSql = @sSql + 'select '
DECLARE keyCursor CURSOR FOR
select COLUMN_NAME FROM #primanyKeys
OPEN keyCursor
FETCH NEXT FROM keyCursor into @keyColumn
WHILE @@FETCH_STATUS=0
BEGIN	
	if @primaryKey <> '' 
	BEGIN
		set @sSql = @sSql + ' + '' AND '' + '
	END
	set @sSql = @sSql + ''''+ @keyColumn +'='' + '''''''' + cast(rtrim(' + @keyColumn + ') as nvarchar(100)) + '''''''' '
	set @primaryKey = @keyColumn
FETCH NEXT FROM keyCursor into @keyColumn
END   
CLOSE keyCursor
DEALLOCATE keyCursor
set @sSql = @sSql + 'as _ID '
set @sSql = @sSql + 'FROM #inserted '
 
exec sp_executesql @sSql

SELECT @context_info = cast(replace(cast(CONTEXT_INFO as varchar(128)), char(0) COLLATE SQL_Latin1_General_CP1_CI_AS,'') as int) FROM master.dbo.sysprocesses WHERE spid = @@SPID

select @logUserID = isnull(USERID, -1),
@logDateTime = isnull(LOGDATETIME, DATEADD(M, -1, getDate()))
from logcontext 
where LOGID = @context_info
	
delete FROM LOGCONTEXT where LOGID = @context_info
  
OPEN attribCursor
FETCH NEXT FROM attribCursor into @_ID

WHILE @@FETCH_STATUS=0
BEGIN	 
  set @primaryKey = @_ID
  
  if DATEDIFF(s,@logDateTime, getDate()) > 5 or @logDateTime is null
	BEGIN
		set @logUserID= -1
	END

  set @sSql = 'UPDATE ORD SET LOGUSERID = ' + cast(@logUserID as nvarchar(5)) + ', LOGDATETIME = getDate() WHERE ' + @primaryKey + ''
	
  exec sp_executesql @sSql

	FETCH NEXT FROM attribCursor into @_ID
END   

close attribCursor
DEALLOCATE attribCursor

DROP TABLE #inserted
DROP TABLE #primanyKeys

		
ALTER TABLE [dbo].[ORD] ENABLE TRIGGER [LOGORD]