/****** Object:  Table [dbo].[ORDITEMSHISTORY]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[ORDITEMSHISTORY](
	[ORDITEMHISTID] [int] IDENTITY(1,1) NOT NULL,
	[HISTDATE] [datetime] NOT NULL,
	[HISTUSERID] [int] NOT NULL,
	[ORDID] [char](10) NOT NULL,
	[LINENUMBER] [int] NOT NULL,
	[ITEMDESCRIPTION] [nvarchar](255) NOT NULL,
	[BUYERPARTNUMBER] [nvarchar](50) NOT NULL,
	[PARTNUMBER] [nvarchar](50) NOT NULL,
	[PARTNUMBEREXT] [nvarchar](50) NOT NULL,
	[UOM] [nvarchar](25) NOT NULL,
	[QTY] [decimal](19, 4) NOT NULL,
	[PRICE] [money] NOT NULL,
	[PAYMENTID] [int] NOT NULL,
	[DLVRID] [int] NOT NULL,
	[INSTRUCTIONS] [ntext] NOT NULL,
	[VATPERC] [decimal](18, 4) NOT NULL,
	[PROJECTID] [int] NOT NULL,
	[CONTRACTID] [int] NOT NULL,
	[MIMETYPE] [nvarchar](100) NOT NULL,
	[FILESIZEINKB] [int] NOT NULL,
	[ORIGINALFILEPATH] [nvarchar](255) NOT NULL,
	[SENDTOSUPP] [bit] NOT NULL,
	[DIVISIONID] [int] NOT NULL,
	[RESOURCECODE] [nvarchar](25) NOT NULL,
	[FILEPATH] [nvarchar](255) NOT NULL,
	[DISCOUNT] [decimal](18, 4) NOT NULL,
	[ITEMSTATUSID] [int] NOT NULL,
	[LASTCHANGE] [datetime] NULL,
	[LASTCHANGEBY] [int] NULL,
	[ITEMSTATUSDATE] [datetime] NOT NULL,
	[ISFREEITEM] [bit] NOT NULL,
	[LONGDESCR] [ntext] NOT NULL,
	[CATORTENDITEM] [int] NOT NULL,
	[ITEMID] [int] NOT NULL,
	[GLCODEID] [int] NOT NULL,
	[ACTID] [int] NOT NULL,
	[ALLOCATION] [char](25) NOT NULL,
	[PENUMBER] [char](10) NOT NULL,
	[STOCKID] [int] NOT NULL,
	[ATTMESSAGE] [nvarchar](200) NOT NULL,
	[VATID] [nvarchar](100) NOT NULL,
	[TBORGID] [int] NULL,
	[TERMS] [nvarchar](250) NOT NULL,
	[EID] [char](10) NOT NULL,
	[VATAMOUNT] [decimal](18, 4) NOT NULL,
	[STKCONVERTFLAG] [bit] NOT NULL,
	[STKBUYCONV] [numeric](18, 4) NULL,
	[WHTID] [int] NOT NULL,
	[WHTAMOUNT] [money] NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

ALTER TABLE [dbo].[ORDITEMSHISTORY] ADD  CONSTRAINT [DF_ORDITEMSHISTORY_VATID]  DEFAULT ('Z') FOR [VATID]
ALTER TABLE [dbo].[ORDITEMSHISTORY] ADD  CONSTRAINT [DF_ORDITEMSHISTORY_TERMS]  DEFAULT ('Current') FOR [TERMS]
ALTER TABLE [dbo].[ORDITEMSHISTORY] ADD  DEFAULT ('') FOR [EID]
ALTER TABLE [dbo].[ORDITEMSHISTORY] ADD  CONSTRAINT [DF_ORDITEMSHISTORY_VATAMOUNT]  DEFAULT ((0)) FOR [VATAMOUNT]
ALTER TABLE [dbo].[ORDITEMSHISTORY] ADD  CONSTRAINT [DF_ORDITEMSHISTORY_STKCONVERTFLAG]  DEFAULT ((0)) FOR [STKCONVERTFLAG]
ALTER TABLE [dbo].[ORDITEMSHISTORY] ADD  CONSTRAINT [DF_ORDITEMSHISTORY_WHTID]  DEFAULT ((-1)) FOR [WHTID]
ALTER TABLE [dbo].[ORDITEMSHISTORY] ADD  CONSTRAINT [DF_ORDITEMSHISTORY_WHTAMOUNT]  DEFAULT ((0)) FOR [WHTAMOUNT]