/****** Object:  Table [dbo].[ORDSUPPASN]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[ORDSUPPASN](
	[SNID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[ORDID] [int] NOT NULL,
	[LINENUMBER] [int] NOT NULL,
	[QTY] [int] NOT NULL,
	[NOTE] [nvarchar](255) NULL,
	[SHIPDATE] [datetime] NOT NULL,
 CONSTRAINT [PK_ORDSUPPASN] PRIMARY KEY CLUSTERED 
(
	[SNID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[ORDSUPPASN]  WITH CHECK ADD  CONSTRAINT [FK_ORDSUPPASN_ORDITEMS] FOREIGN KEY([ORDID], [LINENUMBER])
REFERENCES [dbo].[ORDITEMS] ([ORDID], [LINENUMBER])
ALTER TABLE [dbo].[ORDSUPPASN] CHECK CONSTRAINT [FK_ORDSUPPASN_ORDITEMS]