/****** Object:  Table [dbo].[PAYCARDS]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[PAYCARDS](
	[CARDID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[PAYTYPEID] [int] NOT NULL,
	[CREDITCARDNUM] [nvarchar](120) NOT NULL,
	[CORPORATE] [bit] NOT NULL,
	[DESCRIPTION] [nvarchar](100) NOT NULL,
	[CARDCODE] [nvarchar](35) NULL,
	[REFNO] [nvarchar](35) NULL,
	[NAMEONCARD] [nvarchar](50) NULL,
	[USERID] [nvarchar](15) NOT NULL,
	[EXPIRE] [datetime] NULL,
 CONSTRAINT [PK_PAYCARDS] PRIMARY KEY CLUSTERED 
(
	[CARDID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[PAYCARDS] ADD  CONSTRAINT [DF_PAYCARDS_USERID]  DEFAULT (0) FOR [USERID]