/****** Object:  Table [dbo].[PAYMENTS]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[PAYMENTS](
	[ID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[BATCHNO] [int] NOT NULL,
	[PAYYEAR] [char](10) NOT NULL,
	[PAYPERIOD] [int] NOT NULL,
	[PAYID] [int] NOT NULL,
	[PAYAMOUNT] [money] NULL,
	[PAYTAX] [money] NULL,
	[PAYDISC] [money] NULL,
	[PAYWHT] [money] NULL,
	[PAYREF] [nvarchar](10) NULL,
	[ORGID] [int] NOT NULL,
	[PAYTODATE] [money] NULL,
	[PAYTYPE] [char](1) NULL,
	[PAYMETH] [int] NOT NULL,
	[CREDNO] [nvarchar](10) NULL,
	[TRANGRP] [int] NULL,
	[EXCLUDE] [bit] NOT NULL,
	[CONTRNUMBER] [nvarchar](10) NOT NULL,
 CONSTRAINT [PK_PAYMENTS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[PAYMENTS] ADD  CONSTRAINT [DF_PAYMENTS_BATCHNO]  DEFAULT ((-1)) FOR [BATCHNO]
ALTER TABLE [dbo].[PAYMENTS] ADD  CONSTRAINT [DF_PAYMENTS_PAYYEAR]  DEFAULT ('') FOR [PAYYEAR]
ALTER TABLE [dbo].[PAYMENTS] ADD  CONSTRAINT [DF_PAYMENTS_PAYPERIOD]  DEFAULT ((-1)) FOR [PAYPERIOD]
ALTER TABLE [dbo].[PAYMENTS] ADD  CONSTRAINT [DF_PAYMENTS_PAYID]  DEFAULT ((-1)) FOR [PAYID]
ALTER TABLE [dbo].[PAYMENTS] ADD  CONSTRAINT [DF_PAYMENTS_PAYAMOUNT]  DEFAULT ((0)) FOR [PAYAMOUNT]
ALTER TABLE [dbo].[PAYMENTS] ADD  CONSTRAINT [DF_PAYMENTS_PAYTAX]  DEFAULT ((0)) FOR [PAYTAX]
ALTER TABLE [dbo].[PAYMENTS] ADD  CONSTRAINT [DF_PAYMENTS_PAYDISC]  DEFAULT ((0)) FOR [PAYDISC]
ALTER TABLE [dbo].[PAYMENTS] ADD  CONSTRAINT [DF_PAYMENTS_PAYWHT]  DEFAULT ((0)) FOR [PAYWHT]
ALTER TABLE [dbo].[PAYMENTS] ADD  CONSTRAINT [DF_PAYMENTS_PAYREF]  DEFAULT ('') FOR [PAYREF]
ALTER TABLE [dbo].[PAYMENTS] ADD  CONSTRAINT [DF_PAYMENTS_ORGID]  DEFAULT ((-1)) FOR [ORGID]
ALTER TABLE [dbo].[PAYMENTS] ADD  CONSTRAINT [DF_PAYMENTS_PAYTODATE]  DEFAULT ((0)) FOR [PAYTODATE]
ALTER TABLE [dbo].[PAYMENTS] ADD  CONSTRAINT [DF_PAYMENTS_PAYTYPE]  DEFAULT ('C') FOR [PAYTYPE]
ALTER TABLE [dbo].[PAYMENTS] ADD  CONSTRAINT [DF_PAYMENTS_PAYMETH]  DEFAULT ((2)) FOR [PAYMETH]
ALTER TABLE [dbo].[PAYMENTS] ADD  CONSTRAINT [DF_PAYMENTS_CREDNO]  DEFAULT ('') FOR [CREDNO]
ALTER TABLE [dbo].[PAYMENTS] ADD  CONSTRAINT [DF_PAYMENTS_TRANGRP]  DEFAULT ((-1)) FOR [TRANGRP]
ALTER TABLE [dbo].[PAYMENTS] ADD  CONSTRAINT [DF_PAYMENTS_EXCLUDE]  DEFAULT ('0') FOR [EXCLUDE]
ALTER TABLE [dbo].[PAYMENTS] ADD  CONSTRAINT [DF_PAYMENTS_CONTRNUMBER]  DEFAULT ('') FOR [CONTRNUMBER]