/****** Object:  Table [dbo].[PAYPOINTS]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[PAYPOINTS](
	[PPID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[PPNUMBER] [nvarchar](15) NOT NULL,
	[PPDESC] [nvarchar](75) NOT NULL,
	[PAYROLLID] [int] NOT NULL,
 CONSTRAINT [PK_PAYPOINTS] PRIMARY KEY CLUSTERED 
(
	[PPID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY],
 CONSTRAINT [IX_PAYPOINTS] UNIQUE NONCLUSTERED 
(
	[PPNUMBER] ASC,
	[PAYROLLID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[PAYPOINTS] ADD  CONSTRAINT [DF_PAYPOINTS_PPNUMBER]  DEFAULT ('') FOR [PPNUMBER]
ALTER TABLE [dbo].[PAYPOINTS] ADD  CONSTRAINT [DF_PAYPOINTS_PPDESC]  DEFAULT ('') FOR [PPDESC]
ALTER TABLE [dbo].[PAYPOINTS] ADD  CONSTRAINT [DF_PAYPOINTS_PAYROLLID]  DEFAULT (1) FOR [PAYROLLID]
ALTER TABLE [dbo].[PAYPOINTS]  WITH CHECK ADD  CONSTRAINT [FK_PAYPOINTS_PAYROLLS] FOREIGN KEY([PAYROLLID])
REFERENCES [dbo].[PAYROLLS] ([PAYROLLID])
ALTER TABLE [dbo].[PAYPOINTS] CHECK CONSTRAINT [FK_PAYPOINTS_PAYROLLS]