/****** Object:  Table [dbo].[PAYROLLTAXYEARS]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[PAYROLLTAXYEARS](
	[PAYROLLID] [int] NOT NULL,
	[TAXYEAR] [smallint] NOT NULL,
	[STARTDATE] [datetime] NOT NULL,
	[ENDDATE] [datetime] NOT NULL,
 CONSTRAINT [PK_PAYROLLTAXYEARS] PRIMARY KEY CLUSTERED 
(
	[PAYROLLID] ASC,
	[TAXYEAR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[PAYROLLTAXYEARS]  WITH CHECK ADD  CONSTRAINT [FK_PAYROLLTAXYEARS_PAYROLLS] FOREIGN KEY([PAYROLLID])
REFERENCES [dbo].[PAYROLLS] ([PAYROLLID])
ALTER TABLE [dbo].[PAYROLLTAXYEARS] CHECK CONSTRAINT [FK_PAYROLLTAXYEARS_PAYROLLS]