/****** Object:  Table [dbo].[PAYROLLSITEAMOUNTS]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[PAYROLLSITEAMOUNTS](
	[PAYROLLID] [int] NOT NULL,
	[TAXYEAR] [smallint] NOT NULL,
	[SITEAMOUNT] [decimal](18, 2) NOT NULL,
	[SITEAMOUNT65] [decimal](18, 2) NOT NULL,
	[MAXSITETAXAMOUNT] [decimal](18, 2) NOT NULL,
 CONSTRAINT [PK_PAYROLLSITEAMOUNTS] PRIMARY KEY CLUSTERED 
(
	[PAYROLLID] ASC,
	[TAXYEAR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[PAYROLLSITEAMOUNTS]  WITH CHECK ADD  CONSTRAINT [FK_PAYROLLSITEAMOUNTS_PAYROLLS] FOREIGN KEY([PAYROLLID])
REFERENCES [dbo].[PAYROLLS] ([PAYROLLID])
ALTER TABLE [dbo].[PAYROLLSITEAMOUNTS] CHECK CONSTRAINT [FK_PAYROLLSITEAMOUNTS_PAYROLLS]