/****** Object:  Table [dbo].[PAYTYPES]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[PAYTYPES](
	[PTYPEID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[CODE] [nvarchar](20) NOT NULL,
	[DESCRIPTION] [nvarchar](120) NOT NULL,
	[ISCREDITCARD] [bit] NOT NULL,
	[PTYPE] [int] NOT NULL,
 CONSTRAINT [PK_PAYTYPE] PRIMARY KEY CLUSTERED 
(
	[PTYPEID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[PAYTYPES] ADD  CONSTRAINT [DF_PAYTYPES_ISCREDITCARD]  DEFAULT (0) FOR [ISCREDITCARD]
ALTER TABLE [dbo].[PAYTYPES] ADD  CONSTRAINT [DF_PAYTYPES_PTYPE]  DEFAULT (0) FOR [PTYPE]