/****** Object:  Table [dbo].[PAYTERMS]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[PAYTERMS](
	[TERMID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[TERMCODE] [nvarchar](20) NOT NULL,
	[DESCRIPTION] [nvarchar](120) NOT NULL,
	[DISCPERC] [int] NULL,
	[DISCDAYSDUE] [int] NULL,
	[DISCTIMEREF] [int] NULL,
	[DISCDUEDATE] [datetime] NULL,
	[NETDAYSDUE] [int] NULL,
	[NETTIMEREF] [numeric](18, 0) NULL,
 CONSTRAINT [PK_PAYTERMS] PRIMARY KEY CLUSTERED 
(
	[TERMID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[PAYTERMS] ADD  CONSTRAINT [DF_PAYTERMS_DISCPERC]  DEFAULT (0) FOR [DISCPERC]
ALTER TABLE [dbo].[PAYTERMS] ADD  CONSTRAINT [DF_PAYTERMS_DISCDAYSDUE]  DEFAULT (0) FOR [DISCDAYSDUE]
ALTER TABLE [dbo].[PAYTERMS] ADD  CONSTRAINT [DF_PAYTERMS_DISCTIMEREF]  DEFAULT (0) FOR [DISCTIMEREF]
ALTER TABLE [dbo].[PAYTERMS] ADD  CONSTRAINT [DF_PAYTERMS_NETDAYSDUE]  DEFAULT (0) FOR [NETDAYSDUE]
ALTER TABLE [dbo].[PAYTERMS] ADD  CONSTRAINT [DF_PAYTERMS_NETTIMEREF]  DEFAULT (0) FOR [NETTIMEREF]