/****** Object:  Table [dbo].[PDBUDGETS]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[PDBUDGETS](
	[BORGID] [int] NOT NULL,
	[DIVID] [int] NOT NULL,
	[LEDGERID] [int] NOT NULL,
	[YEARNO] [char](10) NOT NULL,
	[PERIOD] [int] NOT NULL,
	[BUDGET] [money] NOT NULL,
	[BUDGETID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
 CONSTRAINT [PK_PDBUDGETS] PRIMARY KEY CLUSTERED 
(
	[BORGID] ASC,
	[DIVID] ASC,
	[LEDGERID] ASC,
	[YEARNO] ASC,
	[PERIOD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[PDBUDGETS] ADD  CONSTRAINT [DF_PDBUDGETS_BORGID]  DEFAULT ((-1)) FOR [BORGID]
ALTER TABLE [dbo].[PDBUDGETS] ADD  CONSTRAINT [DF_PDBUDGETS_DIVID]  DEFAULT ((-1)) FOR [DIVID]
ALTER TABLE [dbo].[PDBUDGETS] ADD  CONSTRAINT [DF_PDBUDGETS_LEDGERID]  DEFAULT ((-1)) FOR [LEDGERID]
ALTER TABLE [dbo].[PDBUDGETS] ADD  CONSTRAINT [DF_PDBUDGETS_YEARNO]  DEFAULT ('') FOR [YEARNO]
ALTER TABLE [dbo].[PDBUDGETS] ADD  CONSTRAINT [DF_PDBUDGETS_PERIOD]  DEFAULT ((-1)) FOR [PERIOD]
ALTER TABLE [dbo].[PDBUDGETS] ADD  CONSTRAINT [DF_PDBUDGETS_BUDGET]  DEFAULT ((0)) FOR [BUDGET]