/****** Object:  Table [dbo].[PDFORECAST]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[PDFORECAST](
	[BORGID] [int] NOT NULL,
	[DIVID] [int] NOT NULL,
	[LEDGERID] [int] NOT NULL,
	[YEARNO] [char](10) NOT NULL,
	[PERIOD] [int] NOT NULL,
	[FORECAST1] [money] NOT NULL,
	[FORECAST2] [money] NOT NULL,
	[FORECAST3] [money] NOT NULL,
	[FORECAST4] [money] NOT NULL,
	[FORECAST5] [money] NOT NULL,
	[FORECAST6] [money] NOT NULL,
	[FORECAST7] [money] NOT NULL,
	[FORECAST8] [money] NOT NULL,
	[FORECAST9] [money] NOT NULL,
	[FORECAST10] [money] NOT NULL,
	[FORECAST11] [money] NOT NULL,
	[FORECAST12] [money] NOT NULL,
	[FORECASTID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
 CONSTRAINT [PK_PDFORECAST] PRIMARY KEY CLUSTERED 
(
	[BORGID] ASC,
	[DIVID] ASC,
	[LEDGERID] ASC,
	[YEARNO] ASC,
	[PERIOD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[PDFORECAST] ADD  CONSTRAINT [DF_PDFORECAST_BORGID]  DEFAULT ((-1)) FOR [BORGID]
ALTER TABLE [dbo].[PDFORECAST] ADD  CONSTRAINT [DF_PDFORECAST_DIVID]  DEFAULT ((-1)) FOR [DIVID]
ALTER TABLE [dbo].[PDFORECAST] ADD  CONSTRAINT [DF_PDFORECAST_LEDGERID]  DEFAULT ((-1)) FOR [LEDGERID]
ALTER TABLE [dbo].[PDFORECAST] ADD  CONSTRAINT [DF_PDFORECAST_YEARNO]  DEFAULT ('') FOR [YEARNO]
ALTER TABLE [dbo].[PDFORECAST] ADD  CONSTRAINT [DF_PDFORECAST_PERIOD]  DEFAULT ((-1)) FOR [PERIOD]
ALTER TABLE [dbo].[PDFORECAST] ADD  CONSTRAINT [DF_PDFORECAST_FORECAST1]  DEFAULT ((0)) FOR [FORECAST1]
ALTER TABLE [dbo].[PDFORECAST] ADD  CONSTRAINT [DF_PDFORECAST_FORECAST2]  DEFAULT ((0)) FOR [FORECAST2]
ALTER TABLE [dbo].[PDFORECAST] ADD  CONSTRAINT [DF_PDFORECAST_FORECAST3]  DEFAULT ((0)) FOR [FORECAST3]
ALTER TABLE [dbo].[PDFORECAST] ADD  CONSTRAINT [DF_PDFORECAST_FORECAST4]  DEFAULT ((0)) FOR [FORECAST4]
ALTER TABLE [dbo].[PDFORECAST] ADD  CONSTRAINT [DF_PDFORECAST_FORECAST5]  DEFAULT ((0)) FOR [FORECAST5]
ALTER TABLE [dbo].[PDFORECAST] ADD  CONSTRAINT [DF_PDFORECAST_FORECAST6]  DEFAULT ((0)) FOR [FORECAST6]
ALTER TABLE [dbo].[PDFORECAST] ADD  CONSTRAINT [DF_PDFORECAST_FORECAST7]  DEFAULT ((0)) FOR [FORECAST7]
ALTER TABLE [dbo].[PDFORECAST] ADD  CONSTRAINT [DF_PDFORECAST_FORECAST8]  DEFAULT ((0)) FOR [FORECAST8]
ALTER TABLE [dbo].[PDFORECAST] ADD  CONSTRAINT [DF_PDFORECAST_FORECAST9]  DEFAULT ((0)) FOR [FORECAST9]
ALTER TABLE [dbo].[PDFORECAST] ADD  CONSTRAINT [DF_PDFORECAST_FORECAST10]  DEFAULT ((0)) FOR [FORECAST10]
ALTER TABLE [dbo].[PDFORECAST] ADD  CONSTRAINT [DF_PDFORECAST_FORECAST11]  DEFAULT ((0)) FOR [FORECAST11]
ALTER TABLE [dbo].[PDFORECAST] ADD  CONSTRAINT [DF_PDFORECAST_FORECAST12]  DEFAULT ((0)) FOR [FORECAST12]