/****** Object:  Table [dbo].[PERCS]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[PERCS](
	[PARENTID] [int] NOT NULL,
	[ORGID] [int] NOT NULL,
	[PERC] [decimal](18, 4) NOT NULL
) ON [PRIMARY]

ALTER TABLE [dbo].[PERCS] ADD  CONSTRAINT [DF_PERCS_PARENTID]  DEFAULT ('-1') FOR [PARENTID]
ALTER TABLE [dbo].[PERCS] ADD  CONSTRAINT [DF_PERCS_ORGID]  DEFAULT ('-1') FOR [ORGID]
ALTER TABLE [dbo].[PERCS] ADD  CONSTRAINT [DF_PERCS_PERC]  DEFAULT ('0') FOR [PERC]