/****** Object:  Table [dbo].[PLANTSTOCKREQUIREMENT]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[PLANTSTOCKREQUIREMENT](
	[PENUMBER] [char](10) NOT NULL,
	[STKCODE] [char](20) NOT NULL,
	[MINREQUIRED] [numeric](18, 4) NOT NULL,
 CONSTRAINT [PK_PLANTSTOCKREQUIREMENT] PRIMARY KEY CLUSTERED 
(
	[PENUMBER] ASC,
	[STKCODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[PLANTSTOCKREQUIREMENT] ADD  CONSTRAINT [DF_PLANTSTOCKREQUIREMENT_PENUMBER]  DEFAULT ('') FOR [PENUMBER]
ALTER TABLE [dbo].[PLANTSTOCKREQUIREMENT] ADD  CONSTRAINT [DF_PLANTSTOCKREQUIREMENT_STKCODE]  DEFAULT ('') FOR [STKCODE]
ALTER TABLE [dbo].[PLANTSTOCKREQUIREMENT] ADD  CONSTRAINT [DF_PLANTSTOCKREQUIREMENT_MINREQUIRED]  DEFAULT ('0') FOR [MINREQUIRED]