/****** Object:  Table [dbo].[PlantOperators]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[PlantOperators](
	[PlOID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[PlOPrefix] [char](10) NOT NULL,
	[PlOName] [char](20) NULL,
	[PlONotes] [nvarchar](500) NULL,
 CONSTRAINT [PK_PlantOperators] PRIMARY KEY CLUSTERED 
(
	[PlOID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY],
 CONSTRAINT [IX_PlantOperators] UNIQUE NONCLUSTERED 
(
	[PlOPrefix] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]