/****** Object:  Table [dbo].[PlantGroups]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[PlantGroups](
	[PltGroupID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[PltGroupNumber] [nvarchar](10) NULL,
	[PltGroupName] [nvarchar](100) NULL,
 CONSTRAINT [PK_PlantGroups] PRIMARY KEY CLUSTERED 
(
	[PltGroupID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY],
 CONSTRAINT [exb_unique] UNIQUE NONCLUSTERED 
(
	[PltGroupNumber] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]