/****** Object:  Table [dbo].[POEMAIL]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[POEMAIL](
	[POEMAILID] [int] IDENTITY(1,1) NOT NULL,
	[BORDID] [int] NOT NULL,
	[AJUSTEDTO] [nvarchar](250) NOT NULL,
	[CC] [nvarchar](250) NULL,
	[SUBJECT] [nvarchar](150) NOT NULL,
	[ATTACHMENTIDS] [nvarchar](150) NULL,
	[USERID] [int] NOT NULL,
	[CREATEDDATE] [datetime] NOT NULL,
	[SUBMITTEDDATE] [datetime] NULL,
	[ERROR] [nvarchar](4000) NULL,
	[ORDERID] [int] NULL,
	[BODY] [text] NOT NULL,
 CONSTRAINT [PK_POEMAIL] PRIMARY KEY CLUSTERED 
(
	[POEMAILID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

ALTER TABLE [dbo].[POEMAIL] ADD  CONSTRAINT [DF_POEMAIL_AJUSTEDTO]  DEFAULT ('') FOR [AJUSTEDTO]
ALTER TABLE [dbo].[POEMAIL] ADD  CONSTRAINT [DF_POEMAIL_CC]  DEFAULT ('') FOR [CC]
ALTER TABLE [dbo].[POEMAIL] ADD  CONSTRAINT [DF_POEMAIL_SUBJECT]  DEFAULT ('') FOR [SUBJECT]
ALTER TABLE [dbo].[POEMAIL] ADD  CONSTRAINT [DF_POEMAIL_ATTACHMENTIDS]  DEFAULT ('') FOR [ATTACHMENTIDS]
ALTER TABLE [dbo].[POEMAIL] ADD  CONSTRAINT [DF_POEMAIL_BODY]  DEFAULT ('') FOR [BODY]