/****** Object:  Table [dbo].[PROJECTHISTORY]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[PROJECTHISTORY](
	[ActName] [char](35) NOT NULL,
	[LedgerName] [char](80) NOT NULL,
	[oEst] [money] NOT NULL,
	[VarApp] [money] NOT NULL,
	[VarUnApp] [money] NOT NULL,
	[RevEst] [money] NOT NULL,
	[oCost] [money] NOT NULL,
	[oCostApp] [money] NOT NULL,
	[oCostUnApp] [money] NOT NULL,
	[oCostInt] [money] NOT NULL,
	[TotComm] [money] NOT NULL,
	[ProvCTC] [money] NOT NULL,
	[TotFFC] [money] NOT NULL,
	[CostToDate] [money] NOT NULL,
	[CostTC] [money] NOT NULL,
	[GainLoss] [money] NOT NULL,
	[Contract] [int] NOT NULL,
	[Activity] [char](10) NULL,
	[Ledger] [int] NULL,
	[BorgID] [int] NOT NULL,
	[Year] [char](4) NOT NULL,
	[Period] [int] NOT NULL,
	[Projid] [int] IDENTITY(1,1) NOT NULL
) ON [PRIMARY]

ALTER TABLE [dbo].[PROJECTHISTORY] ADD  CONSTRAINT [DF_PROJECTHISTORY_ActName]  DEFAULT ('') FOR [ActName]
ALTER TABLE [dbo].[PROJECTHISTORY] ADD  CONSTRAINT [DF_PROJECTHISTORY_LedgerName]  DEFAULT ('') FOR [LedgerName]
ALTER TABLE [dbo].[PROJECTHISTORY] ADD  CONSTRAINT [DF_PROJECTHISTORY_oEst]  DEFAULT (0) FOR [oEst]
ALTER TABLE [dbo].[PROJECTHISTORY] ADD  CONSTRAINT [DF_PROJECTHISTORY_VarApp]  DEFAULT (0) FOR [VarApp]
ALTER TABLE [dbo].[PROJECTHISTORY] ADD  CONSTRAINT [DF_PROJECTHISTORY_VarUnApp]  DEFAULT (0) FOR [VarUnApp]
ALTER TABLE [dbo].[PROJECTHISTORY] ADD  CONSTRAINT [DF_PROJECTHISTORY_RevEst]  DEFAULT (0) FOR [RevEst]
ALTER TABLE [dbo].[PROJECTHISTORY] ADD  CONSTRAINT [DF_PROJECTHISTORY_oCostApp]  DEFAULT (0) FOR [oCostApp]
ALTER TABLE [dbo].[PROJECTHISTORY] ADD  CONSTRAINT [DF_PROJECTHISTORY_oCostUnApp]  DEFAULT (0) FOR [oCostUnApp]
ALTER TABLE [dbo].[PROJECTHISTORY] ADD  CONSTRAINT [DF_PROJECTHISTORY_oCostInt]  DEFAULT (0) FOR [oCostInt]
ALTER TABLE [dbo].[PROJECTHISTORY] ADD  CONSTRAINT [DF_PROJECTHISTORY_TotComm]  DEFAULT (0) FOR [TotComm]
ALTER TABLE [dbo].[PROJECTHISTORY] ADD  CONSTRAINT [DF_PROJECTHISTORY_ProvCTC]  DEFAULT (0) FOR [ProvCTC]
ALTER TABLE [dbo].[PROJECTHISTORY] ADD  CONSTRAINT [DF_PROJECTHISTORY_TotFFC]  DEFAULT (0) FOR [TotFFC]
ALTER TABLE [dbo].[PROJECTHISTORY] ADD  CONSTRAINT [DF_PROJECTHISTORY_CostTC]  DEFAULT (0) FOR [CostTC]
ALTER TABLE [dbo].[PROJECTHISTORY] ADD  CONSTRAINT [DF_PROJECTHISTORY_Contract]  DEFAULT ((-1)) FOR [Contract]
ALTER TABLE [dbo].[PROJECTHISTORY] ADD  CONSTRAINT [DF_PROJECTHISTORY_Activity]  DEFAULT ('') FOR [Activity]
ALTER TABLE [dbo].[PROJECTHISTORY] ADD  CONSTRAINT [DF_PROJECTHISTORY_Ledger]  DEFAULT ((-1)) FOR [Ledger]
ALTER TABLE [dbo].[PROJECTHISTORY] ADD  CONSTRAINT [DF_PROJECTHISTORY_BorgID]  DEFAULT ((-1)) FOR [BorgID]
ALTER TABLE [dbo].[PROJECTHISTORY] ADD  CONSTRAINT [DF_PROJECTHISTORY_Year]  DEFAULT ('') FOR [Year]
ALTER TABLE [dbo].[PROJECTHISTORY] ADD  CONSTRAINT [DF_PROJECTHISTORY_Period]  DEFAULT (1) FOR [Period]