/****** Object:  Table [dbo].[PUBHOLSETT]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[PUBHOLSETT](
	[PHID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[NAME] [nvarchar](55) NOT NULL,
	[THEDAY] [int] NOT NULL,
	[THEMONTH] [int] NOT NULL,
	[THEYEAR] [int] NOT NULL,
	[PAYABLE] [bit] NOT NULL,
	[RECURRENCE] [nvarchar](55) NOT NULL,
 CONSTRAINT [PK_PUBHOLSETT] PRIMARY KEY CLUSTERED 
(
	[PHID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[PUBHOLSETT] ADD  CONSTRAINT [DF_PUBHOLSETT_NAME]  DEFAULT ('') FOR [NAME]
ALTER TABLE [dbo].[PUBHOLSETT] ADD  CONSTRAINT [DF_PUBHOLSETT_RECURRENCE]  DEFAULT ('') FOR [RECURRENCE]