/****** Object:  Table [dbo].[PUPSHEADER]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[PUPSHEADER](
	[PUPID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[PUPNAME] [nvarchar](75) NOT NULL,
	[SUPPID] [int] NOT NULL,
 CONSTRAINT [PK_CATALOGS] PRIMARY KEY CLUSTERED 
(
	[PUPID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]