/****** Object:  Table [dbo].[REBATE]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[REBATE](
	[FORMULA] [nvarchar](255) NOT NULL,
	[VAL] [money] NOT NULL,
	[TAXALLOC] [nvarchar](3) NOT NULL,
	[REBATEID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[FORMULAVAL] [nvarchar](125) NOT NULL,
 CONSTRAINT [PK_REBATE] PRIMARY KEY CLUSTERED 
(
	[REBATEID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[REBATE] ADD  CONSTRAINT [DF_REBATE_TAXALLOC]  DEFAULT ('') FOR [TAXALLOC]
ALTER TABLE [dbo].[REBATE] ADD  CONSTRAINT [DF_REBATE_FORMULAVAL]  DEFAULT ('') FOR [FORMULAVAL]