/****** Object:  Table [dbo].[REPORTLANG]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[REPORTLANG](
	[RLID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[NAME] [nvarchar](250) NOT NULL,
	[ALT] [nvarchar](250) NOT NULL,
	[USERID] [int] NOT NULL,
	[BORGID] [int] NOT NULL,
	[PAGE] [nvarchar](250) NOT NULL,
	[LANG] [nvarchar](3) NOT NULL,
 CONSTRAINT [PK_REPORTLANG] PRIMARY KEY CLUSTERED 
(
	[RLID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[REPORTLANG] ADD  CONSTRAINT [DF_REPORTLANG_NAME]  DEFAULT ('') FOR [NAME]
ALTER TABLE [dbo].[REPORTLANG] ADD  CONSTRAINT [DF_REPORTLANG_ALT]  DEFAULT ('') FOR [ALT]
ALTER TABLE [dbo].[REPORTLANG] ADD  CONSTRAINT [DF_REPORTLANG_USERID]  DEFAULT ((-1)) FOR [USERID]
ALTER TABLE [dbo].[REPORTLANG] ADD  CONSTRAINT [DF_REPORTLANG_BORGID]  DEFAULT ((-1)) FOR [BORGID]
ALTER TABLE [dbo].[REPORTLANG] ADD  CONSTRAINT [DF_REPORTLANG_PAGE]  DEFAULT ('') FOR [PAGE]
ALTER TABLE [dbo].[REPORTLANG] ADD  CONSTRAINT [DF_REPORTLANG_LANG]  DEFAULT ('') FOR [LANG]