/****** Object:  Table [dbo].[REPORTUSAGE]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[REPORTUSAGE](
	[RPTNAME] [nvarchar](100) NOT NULL,
	[SYS] [nvarchar](3) NOT NULL,
	[THEYEAR] [int] NOT NULL,
	[THEMONTH] [int] NOT NULL,
	[COUNTER] [int] NOT NULL,
 CONSTRAINT [PK_REPORTUSAGE] PRIMARY KEY CLUSTERED 
(
	[RPTNAME] ASC,
	[SYS] ASC,
	[THEYEAR] ASC,
	[THEMONTH] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[REPORTUSAGE] ADD  CONSTRAINT [DF_REPORTUSAGE_RPTNAME]  DEFAULT ('') FOR [RPTNAME]
ALTER TABLE [dbo].[REPORTUSAGE] ADD  CONSTRAINT [DF_REPORTUSAGE_SYS]  DEFAULT ('') FOR [SYS]
ALTER TABLE [dbo].[REPORTUSAGE] ADD  CONSTRAINT [DF_REPORTUSAGE_THEYEAR]  DEFAULT ((-1)) FOR [THEYEAR]
ALTER TABLE [dbo].[REPORTUSAGE] ADD  CONSTRAINT [DF_REPORTUSAGE_THEMONTH]  DEFAULT ((-1)) FOR [THEMONTH]
ALTER TABLE [dbo].[REPORTUSAGE] ADD  CONSTRAINT [DF_REPORTUSAGE_COUNTER]  DEFAULT ((0)) FOR [COUNTER]