/****** Object:  Table [dbo].[REPORTS]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[REPORTS](
	[RID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[NAME] [nvarchar](50) NOT NULL,
	[DESCR] [nvarchar](250) NOT NULL,
	[REPORT] [nvarchar](50) NOT NULL,
	[SYS] [nvarchar](5) NOT NULL,
	[ENABLED] [bit] NOT NULL,
	[SEQ] [int] NOT NULL,
 CONSTRAINT [PK_REPORTS] PRIMARY KEY CLUSTERED 
(
	[RID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[REPORTS] ADD  CONSTRAINT [DF_REPORTS_ENABLED]  DEFAULT ((0)) FOR [ENABLED]
ALTER TABLE [dbo].[REPORTS] ADD  CONSTRAINT [DF_REPORTS_SEQ]  DEFAULT ((1)) FOR [SEQ]