/****** Object:  Table [dbo].[REPORTTABLES]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[REPORTTABLES](
	[RTID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[RID] [int] NOT NULL,
	[TABLENAME] [nvarchar](50) NOT NULL,
	[SEQ] [int] NOT NULL,
 CONSTRAINT [PK_REPORTTABLES] PRIMARY KEY CLUSTERED 
(
	[RTID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[REPORTTABLES] ADD  CONSTRAINT [DF_REPORTTABLES_SEQ]  DEFAULT ((1)) FOR [SEQ]
ALTER TABLE [dbo].[REPORTTABLES]  WITH CHECK ADD  CONSTRAINT [FK_REPORTTABLES_REPORTS] FOREIGN KEY([RID])
REFERENCES [dbo].[REPORTS] ([RID])
ALTER TABLE [dbo].[REPORTTABLES] CHECK CONSTRAINT [FK_REPORTTABLES_REPORTS]