/****** Object:  Table [dbo].[REPORT_CONFIG]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[REPORT_CONFIG](
	[Id] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[OrgId] [int] NOT NULL,
	[Report] [nvarchar](50) NULL,
	[HeadPicLogo] [nvarchar](50) NULL,
	[HeadPic_ON] [bit] NOT NULL,
	[HeadText] [nvarchar](250) NULL,
	[HeadText_LCRN] [nvarchar](1) NOT NULL,
	[HeadText_bold] [bit] NOT NULL,
	[HeadText_uline] [bit] NOT NULL,
	[HeadText_size] [int] NOT NULL,
	[OrgPicLLogo] [nvarchar](50) NULL,
	[OrgPicL_ON] [bit] NOT NULL,
	[OrgPicRLogo] [nvarchar](50) NULL,
	[OrgPicR_ON] [bit] NOT NULL,
	[Org_LCRN] [nvarchar](1) NOT NULL,
	[StatPic_ON] [bit] NOT NULL,
	[TaxColumn_ON] [bit] NOT NULL,
	[TaxTotal_ON] [bit] NOT NULL,
	[WordMoney_ON] [bit] NOT NULL,
	[BankDetails_ON] [bit] NOT NULL,
	[FootText] [nvarchar](500) NULL,
	[FootText_LCRN] [nvarchar](1) NOT NULL,
	[FootText_bold] [bit] NOT NULL,
	[FootText_uline] [bit] NOT NULL,
	[FootText_size] [int] NOT NULL,
	[FootPicLogo] [nvarchar](50) NULL,
	[FootPic_ON] [bit] NOT NULL,
	[Allocation_ON] [bit] NOT NULL,
	[Statement_detail] [nvarchar](2) NULL,
	[opt1_ON] [bit] NOT NULL,
	[opt2_ON] [bit] NOT NULL,
	[opt3_ON] [bit] NOT NULL,
	[opt4_ON] [bit] NOT NULL,
	[opt5_ON] [bit] NOT NULL,
	[opt6_ON] [bit] NOT NULL,
	[opt7_ON] [bit] NOT NULL,
	[opt8_ON] [bit] NOT NULL,
	[opt9_ON] [bit] NOT NULL,
	[RepDesc] [nvarchar](250) NULL,
	[RepGroup] [nvarchar](20) NULL,
	[Opt_ShowRegON] [bit] NOT NULL,
	[HeadTitle] [nvarchar](100) NULL,
	[ShowProforma_ON] [bit] NOT NULL,
	[ShowVatPercent_ON] [bit] NOT NULL,
	[RcmRemoveFromTotal_ON] [bit] NOT NULL,
	[RcmMessage] [nvarchar](150) NOT NULL,
	[opt10_ON] [bit] NOT NULL,
	[WHTSHOW] [bit] NOT NULL,
	[WHTTEXT] [nvarchar](250) NOT NULL,
	[opt11_ON] [bit] NULL,
	[opt12_ON] [bit] NULL,
 CONSTRAINT [PK_REPORT_CONFIG] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[REPORT_CONFIG] ADD  CONSTRAINT [DF_REPORT_CONFIG_OrgId]  DEFAULT ('-1') FOR [OrgId]
ALTER TABLE [dbo].[REPORT_CONFIG] ADD  CONSTRAINT [DF_REPORT_CONFIG_HeadPicLogo]  DEFAULT ('') FOR [HeadPicLogo]
ALTER TABLE [dbo].[REPORT_CONFIG] ADD  CONSTRAINT [DF_REPORT_CONFIG_HeadPic_ON]  DEFAULT ('0') FOR [HeadPic_ON]
ALTER TABLE [dbo].[REPORT_CONFIG] ADD  CONSTRAINT [DF_REPORT_CONFIG_HeadText_LCRN]  DEFAULT ('N') FOR [HeadText_LCRN]
ALTER TABLE [dbo].[REPORT_CONFIG] ADD  CONSTRAINT [DF_REPORT_CONFIG_HeadText_bold]  DEFAULT ('0') FOR [HeadText_bold]
ALTER TABLE [dbo].[REPORT_CONFIG] ADD  CONSTRAINT [DF_REPORT_CONFIG_HeadText_uline]  DEFAULT ('0') FOR [HeadText_uline]
ALTER TABLE [dbo].[REPORT_CONFIG] ADD  CONSTRAINT [DF_REPORT_CONFIG_HeadText_size]  DEFAULT ('8') FOR [HeadText_size]
ALTER TABLE [dbo].[REPORT_CONFIG] ADD  CONSTRAINT [DF_REPORT_CONFIG_OrgPicLLogo]  DEFAULT ('') FOR [OrgPicLLogo]
ALTER TABLE [dbo].[REPORT_CONFIG] ADD  CONSTRAINT [DF_REPORT_CONFIG_OrgPicL_ON]  DEFAULT ('0') FOR [OrgPicL_ON]
ALTER TABLE [dbo].[REPORT_CONFIG] ADD  CONSTRAINT [DF_REPORT_CONFIG_OrgPicRLogo]  DEFAULT ('') FOR [OrgPicRLogo]
ALTER TABLE [dbo].[REPORT_CONFIG] ADD  CONSTRAINT [DF_REPORT_CONFIG_OrgPicR_ON]  DEFAULT ('0') FOR [OrgPicR_ON]
ALTER TABLE [dbo].[REPORT_CONFIG] ADD  CONSTRAINT [DF_REPORT_CONFIG_Org_LCRN]  DEFAULT ('N') FOR [Org_LCRN]
ALTER TABLE [dbo].[REPORT_CONFIG] ADD  CONSTRAINT [DF_REPORT_CONFIG_StatPic_ON]  DEFAULT ('0') FOR [StatPic_ON]
ALTER TABLE [dbo].[REPORT_CONFIG] ADD  CONSTRAINT [DF_REPORT_CONFIG_TaxColumn_ON]  DEFAULT ('0') FOR [TaxColumn_ON]
ALTER TABLE [dbo].[REPORT_CONFIG] ADD  CONSTRAINT [DF_REPORT_CONFIG_TaxTotal_ON]  DEFAULT ('0') FOR [TaxTotal_ON]
ALTER TABLE [dbo].[REPORT_CONFIG] ADD  CONSTRAINT [DF_REPORT_CONFIG_WordMoney_ON]  DEFAULT ('0') FOR [WordMoney_ON]
ALTER TABLE [dbo].[REPORT_CONFIG] ADD  CONSTRAINT [DF_REPORT_CONFIG_BankDetails_ON]  DEFAULT ('0') FOR [BankDetails_ON]
ALTER TABLE [dbo].[REPORT_CONFIG] ADD  CONSTRAINT [DF_REPORT_CONFIG_FootText_LCRN]  DEFAULT ('N') FOR [FootText_LCRN]
ALTER TABLE [dbo].[REPORT_CONFIG] ADD  CONSTRAINT [DF_REPORT_CONFIG_FootText_bold]  DEFAULT ('0') FOR [FootText_bold]
ALTER TABLE [dbo].[REPORT_CONFIG] ADD  CONSTRAINT [DF_REPORT_CONFIG_FootText_uline]  DEFAULT ('0') FOR [FootText_uline]
ALTER TABLE [dbo].[REPORT_CONFIG] ADD  CONSTRAINT [DF_REPORT_CONFIG_FootText_size]  DEFAULT ('8') FOR [FootText_size]
ALTER TABLE [dbo].[REPORT_CONFIG] ADD  CONSTRAINT [DF_REPORT_CONFIG_FootPicLogo]  DEFAULT ('') FOR [FootPicLogo]
ALTER TABLE [dbo].[REPORT_CONFIG] ADD  CONSTRAINT [DF_REPORT_CONFIG_FootPic_ON]  DEFAULT ('0') FOR [FootPic_ON]
ALTER TABLE [dbo].[REPORT_CONFIG] ADD  CONSTRAINT [DF_REPORT_CONFIG_Allocation_ON]  DEFAULT ('0') FOR [Allocation_ON]
ALTER TABLE [dbo].[REPORT_CONFIG] ADD  CONSTRAINT [DF_REPORT_CONFIG_opt1_ON]  DEFAULT ('0') FOR [opt1_ON]
ALTER TABLE [dbo].[REPORT_CONFIG] ADD  CONSTRAINT [DF_REPORT_CONFIG_opt2_ON]  DEFAULT ('0') FOR [opt2_ON]
ALTER TABLE [dbo].[REPORT_CONFIG] ADD  CONSTRAINT [DF_REPORT_CONFIG_opt3_ON]  DEFAULT ('0') FOR [opt3_ON]
ALTER TABLE [dbo].[REPORT_CONFIG] ADD  CONSTRAINT [DF_REPORT_CONFIG_opt4_ON]  DEFAULT ('0') FOR [opt4_ON]
ALTER TABLE [dbo].[REPORT_CONFIG] ADD  CONSTRAINT [DF_REPORT_CONFIG_opt5_ON]  DEFAULT ('0') FOR [opt5_ON]
ALTER TABLE [dbo].[REPORT_CONFIG] ADD  CONSTRAINT [DF_REPORT_CONFIG_opt6_ON]  DEFAULT ('0') FOR [opt6_ON]
ALTER TABLE [dbo].[REPORT_CONFIG] ADD  CONSTRAINT [DF_REPORT_CONFIG_opt7_ON]  DEFAULT ('0') FOR [opt7_ON]
ALTER TABLE [dbo].[REPORT_CONFIG] ADD  CONSTRAINT [DF_REPORT_CONFIG_opt8_ON]  DEFAULT ('0') FOR [opt8_ON]
ALTER TABLE [dbo].[REPORT_CONFIG] ADD  CONSTRAINT [DF_REPORT_CONFIG_opt9_ON]  DEFAULT ('0') FOR [opt9_ON]
ALTER TABLE [dbo].[REPORT_CONFIG] ADD  CONSTRAINT [DF_REPORT_CONFIG_Opt_ShowRegON]  DEFAULT ('1') FOR [Opt_ShowRegON]
ALTER TABLE [dbo].[REPORT_CONFIG] ADD  CONSTRAINT [DF_REPORT_CONFIG_HeadTitle]  DEFAULT ('') FOR [HeadTitle]
ALTER TABLE [dbo].[REPORT_CONFIG] ADD  CONSTRAINT [DF_REPORT_CONFIG_ShowProforma_ON]  DEFAULT (N'0') FOR [ShowProforma_ON]
ALTER TABLE [dbo].[REPORT_CONFIG] ADD  CONSTRAINT [DF_REPORT_CONFIG_ShowVatPercent_ON]  DEFAULT (N'0') FOR [ShowVatPercent_ON]
ALTER TABLE [dbo].[REPORT_CONFIG] ADD  CONSTRAINT [DF_REPORT_CONFIG_RcmRemoveFromTotal_ON]  DEFAULT ('0') FOR [RcmRemoveFromTotal_ON]
ALTER TABLE [dbo].[REPORT_CONFIG] ADD  CONSTRAINT [DF_REPORT_CONFIG_RcmMessage]  DEFAULT ('') FOR [RcmMessage]
ALTER TABLE [dbo].[REPORT_CONFIG] ADD  CONSTRAINT [DF_REPORT_CONFIG_opt10_ON]  DEFAULT ('0') FOR [opt10_ON]
ALTER TABLE [dbo].[REPORT_CONFIG] ADD  CONSTRAINT [DF_REPORT_CONFIG_WHTSHOW]  DEFAULT ('0') FOR [WHTSHOW]
ALTER TABLE [dbo].[REPORT_CONFIG] ADD  CONSTRAINT [DF_REPORT_CONFIG_WHTTEXT]  DEFAULT ('') FOR [WHTTEXT]