/****** Object:  Table [dbo].[REQ]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[REQ](
	[REQID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[BORGID] [int] NOT NULL,
	[REQNUMBER] [nvarchar](55) NOT NULL,
	[REQSUBJECT] [nvarchar](125) NOT NULL,
	[REQSTATUSID] [int] NOT NULL,
	[REQSTATUSDATE] [datetime] NOT NULL,
	[USERID] [int] NOT NULL,
	[CREATEDATE] [datetime] NOT NULL,
	[SUBMITIONDATE] [datetime] NULL,
	[SHORTDESCR] [nvarchar](125) NOT NULL,
	[MIMETYPE] [nvarchar](100) NOT NULL,
	[FILESIZEINKB] [int] NOT NULL,
	[FILEPATH] [nvarchar](255) NOT NULL,
	[ORIGINALFILEPATH] [nvarchar](255) NOT NULL,
	[EID] [char](10) NOT NULL,
	[ATTMESSAGE] [ntext] NOT NULL,
	[SENDATTTOSUPP] [bit] NOT NULL,
	[INVTOID] [int] NOT NULL,
	[LASTCHANGE] [datetime] NULL,
	[LASTCHANGEBY] [int] NULL,
	[REQUIREDBY] [datetime] NULL,
	[CURRENCY] [nvarchar](3) NOT NULL,
	[INFO] [ntext] NOT NULL,
	[APPROVER] [int] NOT NULL,
	[ISEXTPO] [bit] NOT NULL,
	[RECTYPE] [nvarchar](3) NOT NULL,
	[SCORDNUMBER] [nvarchar](55) NOT NULL,
	[FORCEAPPROVER] [int] NOT NULL,
	[HOMECURRENCY] [nvarchar](3) NOT NULL,
	[EXCHRATE] [decimal](23, 6) NOT NULL,
	[ORIGUSERID] [int] NOT NULL,
	[WHTID] [int] NULL,
	[TERM] [int] NOT NULL,
	[ISBULKORDER] [bit] NOT NULL,
	[IMPORTED] [bit] NOT NULL,
	[BUYERUSERID] [int] NULL,
	[ERFQID] [int] NULL,
	[PACKAGE] [nvarchar](30) NOT NULL,
	[WFVALUEAPPROVED] [bit] NOT NULL,
	[LOGUSERID] [int] NOT NULL,
	[LOGDATETIME] [datetime] NOT NULL,
	[TEMPWFAPPROVER] [int] NOT NULL,
 CONSTRAINT [PK_REQ] PRIMARY KEY CLUSTERED 
(
	[REQID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

CREATE NONCLUSTERED INDEX [IX_REQ_BORGID] ON [dbo].[REQ]
(
	[BORGID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [IX_REQ_BORGID_RECTYPE] ON [dbo].[REQ]
(
	[BORGID] ASC,
	[RECTYPE] ASC
)
INCLUDE([APPROVER],[USERID]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [IX_REQ_RECTYPE] ON [dbo].[REQ]
(
	[RECTYPE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [IX_REQ_REQNUMBER] ON [dbo].[REQ]
(
	[REQNUMBER] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
CREATE NONCLUSTERED INDEX [IX_REQ_REQSTATUSID] ON [dbo].[REQ]
(
	[REQSTATUSID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
CREATE NONCLUSTERED INDEX [IX_REQ_REQSTATUSID_APPROVER] ON [dbo].[REQ]
(
	[REQSTATUSID] ASC,
	[APPROVER] ASC
)
INCLUDE([BORGID],[USERID],[RECTYPE]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
ALTER TABLE [dbo].[REQ] ADD  CONSTRAINT [DF_REQ_REQNUMBER]  DEFAULT ('') FOR [REQNUMBER]
ALTER TABLE [dbo].[REQ] ADD  CONSTRAINT [DF_REQ_REQNAME]  DEFAULT ('') FOR [REQSUBJECT]
ALTER TABLE [dbo].[REQ] ADD  CONSTRAINT [DF_REQ_REQSTATUSDATE]  DEFAULT (getdate()) FOR [REQSTATUSDATE]
ALTER TABLE [dbo].[REQ] ADD  CONSTRAINT [DF_REQ_CREATEDATE]  DEFAULT (getdate()) FOR [CREATEDATE]
ALTER TABLE [dbo].[REQ] ADD  CONSTRAINT [DF_REQ_SHORTDESCR]  DEFAULT ('') FOR [SHORTDESCR]
ALTER TABLE [dbo].[REQ] ADD  CONSTRAINT [DF_REQ_MIMETYPE]  DEFAULT ('') FOR [MIMETYPE]
ALTER TABLE [dbo].[REQ] ADD  CONSTRAINT [DF_REQ_FILESIZEINKB]  DEFAULT ((0)) FOR [FILESIZEINKB]
ALTER TABLE [dbo].[REQ] ADD  CONSTRAINT [DF_REQ_FILEPATH]  DEFAULT ('') FOR [FILEPATH]
ALTER TABLE [dbo].[REQ] ADD  CONSTRAINT [DF_REQ_ORIGINALFILEPATH]  DEFAULT ('') FOR [ORIGINALFILEPATH]
ALTER TABLE [dbo].[REQ] ADD  CONSTRAINT [DF_REQ_EID]  DEFAULT ('') FOR [EID]
ALTER TABLE [dbo].[REQ] ADD  CONSTRAINT [DF_REQ_ATTMSG]  DEFAULT ('') FOR [ATTMESSAGE]
ALTER TABLE [dbo].[REQ] ADD  CONSTRAINT [DF_REQ_SENDATTTOSUPP]  DEFAULT ((0)) FOR [SENDATTTOSUPP]
ALTER TABLE [dbo].[REQ] ADD  CONSTRAINT [DF_REQ_REQUIREDBY]  DEFAULT (getdate()+(5)) FOR [REQUIREDBY]
ALTER TABLE [dbo].[REQ] ADD  CONSTRAINT [DF_REQ_HOMECURR]  DEFAULT ('ZAR') FOR [CURRENCY]
ALTER TABLE [dbo].[REQ] ADD  CONSTRAINT [DF_REQ_INFO]  DEFAULT ('') FOR [INFO]
ALTER TABLE [dbo].[REQ] ADD  CONSTRAINT [DF__REQ__APPROVER__51085328]  DEFAULT ((-1)) FOR [APPROVER]
ALTER TABLE [dbo].[REQ] ADD  CONSTRAINT [DF_REQ_ISEXTPO]  DEFAULT ((0)) FOR [ISEXTPO]
ALTER TABLE [dbo].[REQ] ADD  CONSTRAINT [DF_REQ_RECTYPE]  DEFAULT ('STD') FOR [RECTYPE]
ALTER TABLE [dbo].[REQ] ADD  CONSTRAINT [DF_REQ_SCORDNUMBER]  DEFAULT ('') FOR [SCORDNUMBER]
ALTER TABLE [dbo].[REQ] ADD  CONSTRAINT [DF_REQ_FORCEAPPROVER]  DEFAULT ((0)) FOR [FORCEAPPROVER]
ALTER TABLE [dbo].[REQ] ADD  CONSTRAINT [DF_REQ_HOMECURRENCY]  DEFAULT ('') FOR [HOMECURRENCY]
ALTER TABLE [dbo].[REQ] ADD  CONSTRAINT [DF_REQ_EXCHRATE]  DEFAULT ((1)) FOR [EXCHRATE]
ALTER TABLE [dbo].[REQ] ADD  CONSTRAINT [DF_REQ_ORIGUSERID]  DEFAULT ((-1)) FOR [ORIGUSERID]
ALTER TABLE [dbo].[REQ] ADD  CONSTRAINT [DF_REQ_TERM]  DEFAULT ((0)) FOR [TERM]
ALTER TABLE [dbo].[REQ] ADD  CONSTRAINT [DF_REQ_ISBULKORDER]  DEFAULT ((0)) FOR [ISBULKORDER]
ALTER TABLE [dbo].[REQ] ADD  CONSTRAINT [DF_REQ_IMPORTED]  DEFAULT ('0') FOR [IMPORTED]
ALTER TABLE [dbo].[REQ] ADD  CONSTRAINT [DF_REQ_PACKAGE]  DEFAULT ('') FOR [PACKAGE]
ALTER TABLE [dbo].[REQ] ADD  CONSTRAINT [DF_REQ_WFVALUEAPPROVED]  DEFAULT ('0') FOR [WFVALUEAPPROVED]
ALTER TABLE [dbo].[REQ] ADD  CONSTRAINT [DF_REQ_LOGUSERID]  DEFAULT ((-1)) FOR [LOGUSERID]
ALTER TABLE [dbo].[REQ] ADD  CONSTRAINT [DF_REQ_LOGDATETIME]  DEFAULT (getdate()) FOR [LOGDATETIME]
ALTER TABLE [dbo].[REQ] ADD  CONSTRAINT [DF_REQ_TEMPWFAPPROVER]  DEFAULT ((-1)) FOR [TEMPWFAPPROVER]
ALTER TABLE [dbo].[REQ]  WITH CHECK ADD  CONSTRAINT [FK_REQ_BILLTOADDRESSES] FOREIGN KEY([INVTOID])
REFERENCES [dbo].[BILLTOADDRESSES] ([BILLTOID])
ALTER TABLE [dbo].[REQ] CHECK CONSTRAINT [FK_REQ_BILLTOADDRESSES]
ALTER TABLE [dbo].[REQ]  WITH CHECK ADD  CONSTRAINT [FK_REQ_BORGS] FOREIGN KEY([BORGID])
REFERENCES [dbo].[BORGS] ([BORGID])
ALTER TABLE [dbo].[REQ] CHECK CONSTRAINT [FK_REQ_BORGS]
ALTER TABLE [dbo].[REQ]  WITH CHECK ADD  CONSTRAINT [FK_REQ_CURRENCIES] FOREIGN KEY([CURRENCY])
REFERENCES [dbo].[CURRENCIES] ([CURRCODE])
ALTER TABLE [dbo].[REQ] CHECK CONSTRAINT [FK_REQ_CURRENCIES]
ALTER TABLE [dbo].[REQ]  WITH CHECK ADD  CONSTRAINT [FK_REQ_TAXWHT] FOREIGN KEY([WHTID])
REFERENCES [dbo].[TAXWHT] ([WHTID])
ALTER TABLE [dbo].[REQ] CHECK CONSTRAINT [FK_REQ_TAXWHT]
ALTER TABLE [dbo].[REQ]  WITH CHECK ADD  CONSTRAINT [FK_REQ_USERS] FOREIGN KEY([USERID])
REFERENCES [dbo].[USERS] ([USERID])
ALTER TABLE [dbo].[REQ] CHECK CONSTRAINT [FK_REQ_USERS]
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON

CREATE TRIGGER LOGREQ ON REQ
AFTER UPDATE, INSERT
AS 

SET NOCOUNT ON

declare @columnName nvarchar(500)
declare @keyColumn nvarchar(500)
declare @tableName nvarchar(500)
declare @sSql nvarchar(4000)
declare @primaryKey nvarchar(500)
declare @_ID nvarchar(500)
declare @logUserID int
declare @logDateTime datetime
declare @context_info int

SELECT @tableName = o.name
FROM sysobjects t
JOIN sysobjects o ON t.parent_obj = o.id
WHERE t.id = @@PROCID

set @context_info = -1
set @primaryKey = ''
set @logUserID = -1
set @logDateTime = DATEADD(M, -1, getDate()) 


/*GETS THE PRIMARY KEY COLUMNS*/
SELECT COLUMN_NAME
into #primanyKeys
FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE
WHERE OBJECTPROPERTY(OBJECT_ID(constraint_name), 'IsPrimaryKey') = 1
AND table_name = @tableName

select 
REQID, BORGID, REQNUMBER, REQSUBJECT, REQSTATUSID, REQSTATUSDATE, USERID, CREATEDATE, SUBMITIONDATE, SHORTDESCR, EID, 
INVTOID, LASTCHANGE, LASTCHANGEBY, REQUIREDBY, CURRENCY, APPROVER, ISEXTPO, RECTYPE, SCORDNUMBER, FORCEAPPROVER, HOMECURRENCY, 
EXCHRATE, ORIGUSERID, WHTID, TERM
into #inserted from INSERTED

set @sSql = 'DECLARE attribCursor CURSOR FOR '
set @sSql = @sSql + 'select '
DECLARE keyCursor CURSOR FOR
select COLUMN_NAME FROM #primanyKeys
OPEN keyCursor
FETCH NEXT FROM keyCursor into @keyColumn
WHILE @@FETCH_STATUS=0
BEGIN	
	if @primaryKey <> '' 
	BEGIN
		set @sSql = @sSql + ' + '' AND '' + '
	END
	set @sSql = @sSql + ''''+ @keyColumn +'='' + '''''''' + cast(rtrim(' + @keyColumn + ') as nvarchar(100)) + '''''''' '
	set @primaryKey = @keyColumn
FETCH NEXT FROM keyCursor into @keyColumn
END   
CLOSE keyCursor
DEALLOCATE keyCursor
set @sSql = @sSql + 'as _ID '
set @sSql = @sSql + 'FROM #inserted '
 
exec sp_executesql @sSql

SELECT @context_info = cast(replace(cast(CONTEXT_INFO as varchar(128)), char(0) COLLATE SQL_Latin1_General_CP1_CI_AS,'') as int) FROM master.dbo.sysprocesses WHERE spid = @@SPID

select @logUserID = isnull(USERID, -1),
@logDateTime = isnull(LOGDATETIME, DATEADD(M, -1, getDate()))
from logcontext 
where LOGID = @context_info
	
delete FROM LOGCONTEXT where LOGID = @context_info
  
OPEN attribCursor
FETCH NEXT FROM attribCursor into @_ID

WHILE @@FETCH_STATUS=0
BEGIN	 
  set @primaryKey = @_ID
  
  if DATEDIFF(s,@logDateTime, getDate()) > 5 or @logDateTime is null
	BEGIN
		set @logUserID= -1
	END

  set @sSql = 'UPDATE REQ SET LOGUSERID = ' + cast(@logUserID as nvarchar(5)) + ', LOGDATETIME = getDate() WHERE ' + @primaryKey + ''
	
  exec sp_executesql @sSql

	FETCH NEXT FROM attribCursor into @_ID
END   

close attribCursor
DEALLOCATE attribCursor

DROP TABLE #inserted
DROP TABLE #primanyKeys

		
ALTER TABLE [dbo].[REQ] ENABLE TRIGGER [LOGREQ]