/****** Object:  Table [dbo].[REQAPPROVALHIST]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[REQAPPROVALHIST](
	[AHID] [int] IDENTITY(1,1) NOT NULL,
	[REQID] [int] NOT NULL,
	[SEQ] [int] NOT NULL,
	[USERID] [int] NOT NULL,
	[THEDATE] [datetime] NOT NULL,
	[REQSTATUSID] [int] NOT NULL,
	[DESCRIPTION] [text] NULL,
	[WDID] [int] NOT NULL,
	[WFVALUEAPPROVED] [bit] NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

CREATE NONCLUSTERED INDEX [IX_REQAPPROVALHIST_REQID] ON [dbo].[REQAPPROVALHIST]
(
	[REQID] ASC
)
INCLUDE([WDID]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
ALTER TABLE [dbo].[REQAPPROVALHIST] ADD  CONSTRAINT [DF_REQAPPROVALHIST_THEDATE]  DEFAULT (getdate()) FOR [THEDATE]
ALTER TABLE [dbo].[REQAPPROVALHIST] ADD  CONSTRAINT [DF_REQAPPROVALHIST_REQSTATUSID]  DEFAULT ((26)) FOR [REQSTATUSID]
ALTER TABLE [dbo].[REQAPPROVALHIST] ADD  CONSTRAINT [DF_REQAPPROVALHIST_WDID]  DEFAULT ((-1)) FOR [WDID]
ALTER TABLE [dbo].[REQAPPROVALHIST] ADD  CONSTRAINT [DF_REQAPPROVALHIST_WFVALUEAPPROVED]  DEFAULT ('0') FOR [WFVALUEAPPROVED]