/****** Object:  Table [dbo].[REQITEMS]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[REQITEMS](
	[REQID] [int] NOT NULL,
	[LINENUMBER] [int] NOT NULL,
	[CATALOGITEMID] [int] NOT NULL,
	[ITEMDESCRIPTION] [nvarchar](255) NOT NULL,
	[BUYERPARTNUMBER] [nvarchar](50) NOT NULL,
	[SUPPID] [int] NOT NULL,
	[PARTNUMBER] [nvarchar](50) NOT NULL,
	[PARTNUMBEREXT] [nvarchar](50) NOT NULL,
	[UOM] [nvarchar](25) NOT NULL,
	[QTY] [decimal](19, 4) NOT NULL,
	[PRICE] [money] NOT NULL,
	[PAYMENTID] [int] NOT NULL,
	[DLVRID] [int] NOT NULL,
	[INSTRUCTIONS] [ntext] NOT NULL,
	[VATPERC] [decimal](18, 4) NOT NULL,
	[PROJECTID] [int] NOT NULL,
	[CONTRACTID] [int] NOT NULL,
	[MIMETYPE] [nvarchar](100) NOT NULL,
	[FILESIZEINKB] [int] NOT NULL,
	[ORIGINALFILEPATH] [nvarchar](255) NOT NULL,
	[SENDTOSUPP] [bit] NOT NULL,
	[DIVISIONID] [int] NOT NULL,
	[RESOURCECODE] [nvarchar](25) NOT NULL,
	[FILEPATH] [nvarchar](255) NOT NULL,
	[DISCOUNT] [decimal](18, 4) NOT NULL,
	[ITEMSTATUSID] [int] NOT NULL,
	[LASTCHANGE] [datetime] NULL,
	[LASTCHANGEBY] [int] NULL,
	[ITEMSTATUSDATE] [datetime] NOT NULL,
	[ISFREEITEM] [bit] NOT NULL,
	[CATORTENDITEM] [int] NOT NULL,
	[GLCODEID] [int] NOT NULL,
	[ACTID] [int] NOT NULL,
	[ALLOCATION] [char](25) NOT NULL,
	[PENUMBER] [char](10) NOT NULL,
	[STOCKID] [int] NOT NULL,
	[ATTMESSAGE] [nvarchar](200) NOT NULL,
	[VATID] [nvarchar](100) NOT NULL,
	[JOBCARDID] [int] NULL,
	[JOBCARDVATID] [char](2) NULL,
	[JOBCARDLEDGERID] [int] NULL,
	[JOBCARDACTID] [char](10) NULL,
	[TBORGID] [int] NULL,
	[TERMS] [nvarchar](250) NOT NULL,
	[EID] [char](10) NOT NULL,
	[VATAMOUNT] [decimal](18, 4) NOT NULL,
	[STKCONVERTFLAG] [bit] NOT NULL,
	[STKBUYCONV] [numeric](18, 4) NULL,
	[TENDERPRICE] [money] NULL,
	[CATID] [int] NULL,
	[WHTID] [int] NOT NULL,
	[WHTAMOUNT] [money] NOT NULL,
 CONSTRAINT [PK_REQITEMS] PRIMARY KEY CLUSTERED 
(
	[REQID] ASC,
	[LINENUMBER] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [IX_REQITEMS_ALLOCATION] ON [dbo].[REQITEMS]
(
	[ALLOCATION] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
CREATE NONCLUSTERED INDEX [IX_REQITEMS_CATORTENDITEM_STOCKID] ON [dbo].[REQITEMS]
(
	[CATORTENDITEM] ASC,
	[STOCKID] ASC
)
INCLUDE([REQID],[CATALOGITEMID]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
ALTER TABLE [dbo].[REQITEMS] ADD  CONSTRAINT [DF_REQITEMS_ITEMDESCRIPTION]  DEFAULT ('') FOR [ITEMDESCRIPTION]
ALTER TABLE [dbo].[REQITEMS] ADD  CONSTRAINT [DF_REQITEMS_BUYERPARTNUMBER]  DEFAULT ('') FOR [BUYERPARTNUMBER]
ALTER TABLE [dbo].[REQITEMS] ADD  CONSTRAINT [DF_REQITEMS_SUPPPARTNUMBER]  DEFAULT ('') FOR [PARTNUMBER]
ALTER TABLE [dbo].[REQITEMS] ADD  CONSTRAINT [DF_REQITEMS_SUPPPARTNUMBEREXT]  DEFAULT ('') FOR [PARTNUMBEREXT]
ALTER TABLE [dbo].[REQITEMS] ADD  CONSTRAINT [DF_REQITEMS_UOM]  DEFAULT ('') FOR [UOM]
ALTER TABLE [dbo].[REQITEMS] ADD  CONSTRAINT [DF_REQITEMS_QTY]  DEFAULT (0) FOR [QTY]
ALTER TABLE [dbo].[REQITEMS] ADD  CONSTRAINT [DF_REQITEMS_PRICE]  DEFAULT (0) FOR [PRICE]
ALTER TABLE [dbo].[REQITEMS] ADD  CONSTRAINT [DF_REQITEMS_PAYMENTID]  DEFAULT ((-1)) FOR [PAYMENTID]
ALTER TABLE [dbo].[REQITEMS] ADD  CONSTRAINT [DF_REQITEMS_DELIVERYTOID]  DEFAULT ((-1)) FOR [DLVRID]
ALTER TABLE [dbo].[REQITEMS] ADD  CONSTRAINT [DF_REQITEMS_INSTRUCTIONS]  DEFAULT ('') FOR [INSTRUCTIONS]
ALTER TABLE [dbo].[REQITEMS] ADD  CONSTRAINT [DF_REQITEMS_VATPERC]  DEFAULT (0) FOR [VATPERC]
ALTER TABLE [dbo].[REQITEMS] ADD  CONSTRAINT [DF_REQITEMS_PROJECTID]  DEFAULT ((-1)) FOR [PROJECTID]
ALTER TABLE [dbo].[REQITEMS] ADD  CONSTRAINT [DF_REQITEMS_CONTRACTID]  DEFAULT ((-1)) FOR [CONTRACTID]
ALTER TABLE [dbo].[REQITEMS] ADD  CONSTRAINT [DF_REQITEMS_MIMETYPE]  DEFAULT ('') FOR [MIMETYPE]
ALTER TABLE [dbo].[REQITEMS] ADD  CONSTRAINT [DF_REQITEMS_FILESIZEINKB]  DEFAULT (0) FOR [FILESIZEINKB]
ALTER TABLE [dbo].[REQITEMS] ADD  CONSTRAINT [DF_REQITEMS_ORIGINALFILEPATH]  DEFAULT ('') FOR [ORIGINALFILEPATH]
ALTER TABLE [dbo].[REQITEMS] ADD  CONSTRAINT [DF_REQITEMS_SENDTOSUPP]  DEFAULT (0) FOR [SENDTOSUPP]
ALTER TABLE [dbo].[REQITEMS] ADD  CONSTRAINT [DF_REQITEMS_DIVISIONID]  DEFAULT ((-1)) FOR [DIVISIONID]
ALTER TABLE [dbo].[REQITEMS] ADD  CONSTRAINT [DF_REQITEMS_RESOURCECODE]  DEFAULT ('') FOR [RESOURCECODE]
ALTER TABLE [dbo].[REQITEMS] ADD  CONSTRAINT [DF_REQITEMS_FILEPATH]  DEFAULT ('') FOR [FILEPATH]
ALTER TABLE [dbo].[REQITEMS] ADD  CONSTRAINT [DF_REQITEMS_DISCOUNT]  DEFAULT (0) FOR [DISCOUNT]
ALTER TABLE [dbo].[REQITEMS] ADD  CONSTRAINT [DF_REQITEMS_REQITEMSTATUS]  DEFAULT (163) FOR [ITEMSTATUSID]
ALTER TABLE [dbo].[REQITEMS] ADD  CONSTRAINT [DF_REQITEMS_ITEMSTATUSDATE]  DEFAULT (getdate()) FOR [ITEMSTATUSDATE]
ALTER TABLE [dbo].[REQITEMS] ADD  CONSTRAINT [DF_REQITEMS_ISFREEITEM]  DEFAULT (0) FOR [ISFREEITEM]
ALTER TABLE [dbo].[REQITEMS] ADD  CONSTRAINT [DF_REQITEMS_CATORTENDITEM]  DEFAULT (1) FOR [CATORTENDITEM]
ALTER TABLE [dbo].[REQITEMS] ADD  CONSTRAINT [DF_REQITEMS_GLCODEID]  DEFAULT ((-1)) FOR [GLCODEID]
ALTER TABLE [dbo].[REQITEMS] ADD  CONSTRAINT [DF_REQITEMS_ACTID]  DEFAULT ((-1)) FOR [ACTID]
ALTER TABLE [dbo].[REQITEMS] ADD  CONSTRAINT [DF_REQITEMS_ALLOCATION]  DEFAULT ('Contracts') FOR [ALLOCATION]
ALTER TABLE [dbo].[REQITEMS] ADD  CONSTRAINT [DF_REQITEMS_PENUMBER]  DEFAULT ('') FOR [PENUMBER]
ALTER TABLE [dbo].[REQITEMS] ADD  CONSTRAINT [DF_REQITEMS_STOCKID]  DEFAULT ((-1)) FOR [STOCKID]
ALTER TABLE [dbo].[REQITEMS] ADD  CONSTRAINT [DF__REQITEMS__ATTMES__4067D70B]  DEFAULT ('') FOR [ATTMESSAGE]
ALTER TABLE [dbo].[REQITEMS] ADD  CONSTRAINT [DF_REQITEMS_VATID]  DEFAULT ('Z') FOR [VATID]
ALTER TABLE [dbo].[REQITEMS] ADD  CONSTRAINT [DF_REQITEMS_TERMS]  DEFAULT ('Current') FOR [TERMS]
ALTER TABLE [dbo].[REQITEMS] ADD  DEFAULT ('') FOR [EID]
ALTER TABLE [dbo].[REQITEMS] ADD  CONSTRAINT [DF_REQITEMS_VATAMOUNT]  DEFAULT ((0)) FOR [VATAMOUNT]
ALTER TABLE [dbo].[REQITEMS] ADD  CONSTRAINT [DF_REQITEMS_STKCONVERTFLAG]  DEFAULT ((0)) FOR [STKCONVERTFLAG]
ALTER TABLE [dbo].[REQITEMS] ADD  CONSTRAINT [DF_REQITEMS_WHTID]  DEFAULT ((-1)) FOR [WHTID]
ALTER TABLE [dbo].[REQITEMS] ADD  CONSTRAINT [DF_REQITEMS_WHTAMOUNT]  DEFAULT ((0)) FOR [WHTAMOUNT]
ALTER TABLE [dbo].[REQITEMS]  WITH NOCHECK ADD  CONSTRAINT [FK_REQITEMS_ACTIVITIES] FOREIGN KEY([ACTID])
REFERENCES [dbo].[ACTIVITIES] ([ActID])
NOT FOR REPLICATION 
ALTER TABLE [dbo].[REQITEMS] NOCHECK CONSTRAINT [FK_REQITEMS_ACTIVITIES]
ALTER TABLE [dbo].[REQITEMS]  WITH NOCHECK ADD  CONSTRAINT [FK_REQITEMS_CONTRACTS] FOREIGN KEY([CONTRACTID])
REFERENCES [dbo].[CONTRACTS] ([CONTRID])
NOT FOR REPLICATION 
ALTER TABLE [dbo].[REQITEMS] NOCHECK CONSTRAINT [FK_REQITEMS_CONTRACTS]
ALTER TABLE [dbo].[REQITEMS]  WITH NOCHECK ADD  CONSTRAINT [FK_REQITEMS_DIVISIONS] FOREIGN KEY([DIVISIONID])
REFERENCES [dbo].[DIVISIONS] ([DivID])
NOT FOR REPLICATION 
ALTER TABLE [dbo].[REQITEMS] NOCHECK CONSTRAINT [FK_REQITEMS_DIVISIONS]
ALTER TABLE [dbo].[REQITEMS]  WITH NOCHECK ADD  CONSTRAINT [FK_REQITEMS_INVENTORY] FOREIGN KEY([STOCKID])
REFERENCES [dbo].[INVENTORY] ([StkID])
NOT FOR REPLICATION 
ALTER TABLE [dbo].[REQITEMS] NOCHECK CONSTRAINT [FK_REQITEMS_INVENTORY]
ALTER TABLE [dbo].[REQITEMS]  WITH NOCHECK ADD  CONSTRAINT [FK_REQITEMS_LEDGERCODES] FOREIGN KEY([GLCODEID])
REFERENCES [dbo].[LEDGERCODES] ([LedgerID])
ALTER TABLE [dbo].[REQITEMS] NOCHECK CONSTRAINT [FK_REQITEMS_LEDGERCODES]
ALTER TABLE [dbo].[REQITEMS]  WITH NOCHECK ADD  CONSTRAINT [FK_REQITEMS_PLANTANDEQ] FOREIGN KEY([PENUMBER])
REFERENCES [dbo].[PLANTANDEQ] ([PeNumber])
NOT FOR REPLICATION 
ALTER TABLE [dbo].[REQITEMS] NOCHECK CONSTRAINT [FK_REQITEMS_PLANTANDEQ]
ALTER TABLE [dbo].[REQITEMS]  WITH NOCHECK ADD  CONSTRAINT [FK_REQITEMS_PROJECTS] FOREIGN KEY([PROJECTID])
REFERENCES [dbo].[PROJECTS] ([PROJID])
NOT FOR REPLICATION 
ALTER TABLE [dbo].[REQITEMS] NOCHECK CONSTRAINT [FK_REQITEMS_PROJECTS]
ALTER TABLE [dbo].[REQITEMS]  WITH CHECK ADD  CONSTRAINT [FK_REQITEMS_REQ] FOREIGN KEY([REQID])
REFERENCES [dbo].[REQ] ([REQID])
ALTER TABLE [dbo].[REQITEMS] CHECK CONSTRAINT [FK_REQITEMS_REQ]
ALTER TABLE [dbo].[REQITEMS]  WITH CHECK ADD  CONSTRAINT [FK_REQITEMS_SHIPTOADDRESSES] FOREIGN KEY([DLVRID])
REFERENCES [dbo].[SHIPTOADDRESSES] ([SHIPTOID])
ALTER TABLE [dbo].[REQITEMS] CHECK CONSTRAINT [FK_REQITEMS_SHIPTOADDRESSES]
ALTER TABLE [dbo].[REQITEMS]  WITH CHECK ADD  CONSTRAINT [FK_REQITEMS_TBORGID] FOREIGN KEY([TBORGID])
REFERENCES [dbo].[BORGS] ([BORGID])
ALTER TABLE [dbo].[REQITEMS] CHECK CONSTRAINT [FK_REQITEMS_TBORGID]