/****** Object:  Table [dbo].[REQITEMSADD]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[REQITEMSADD](
	[REQID] [int] NOT NULL,
	[LINENUMBER] [int] NOT NULL,
	[RAID] [int] NOT NULL,
	[VALUE] [decimal](18, 4) NOT NULL,
 CONSTRAINT [PK_REQITEMSADD] PRIMARY KEY CLUSTERED 
(
	[REQID] ASC,
	[LINENUMBER] ASC,
	[RAID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[REQITEMSADD] ADD  CONSTRAINT [DF_REQITEMSADD_REQID]  DEFAULT ((-1)) FOR [REQID]
ALTER TABLE [dbo].[REQITEMSADD] ADD  CONSTRAINT [DF_REQITEMSADD_LINENUMBER]  DEFAULT ((-1)) FOR [LINENUMBER]
ALTER TABLE [dbo].[REQITEMSADD] ADD  CONSTRAINT [DF_REQITEMSADD_RAID]  DEFAULT ((-1)) FOR [RAID]
ALTER TABLE [dbo].[REQITEMSADD] ADD  CONSTRAINT [DF_REQITEMSADD_VALUE]  DEFAULT ((0)) FOR [VALUE]