/****** Object:  Table [dbo].[RFDITEMS]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[RFDITEMS](
	[RFDID] [int] NOT NULL,
	[ORDITEMLINENO] [int] NOT NULL,
	[QTY] [decimal](18, 4) NOT NULL,
	[DELIVEREDQTY] [decimal](18, 4) NOT NULL,
 CONSTRAINT [PK_RFDITEMS] PRIMARY KEY CLUSTERED 
(
	[RFDID] ASC,
	[ORDITEMLINENO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[RFDITEMS] ADD  CONSTRAINT [DF_RFDITEMS_DELIVEREDQTY]  DEFAULT ((0)) FOR [DELIVEREDQTY]
ALTER TABLE [dbo].[RFDITEMS]  WITH CHECK ADD  CONSTRAINT [FK_RFDITEMS_RFD] FOREIGN KEY([RFDID])
REFERENCES [dbo].[RFD] ([RFDID])
ALTER TABLE [dbo].[RFDITEMS] CHECK CONSTRAINT [FK_RFDITEMS_RFD]