/****** Object:  Table [dbo].[ROLEDETAILSW]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[ROLEDETAILSW](
	[ROLEID] [int] NOT NULL,
	[ITEMENABLED] [bit] NOT NULL,
	[ITEMPOSITION] [int] NOT NULL,
 CONSTRAINT [PK_ROLEDETAILSW] PRIMARY KEY CLUSTERED 
(
	[ROLEID] ASC,
	[ITEMPOSITION] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[ROLEDETAILSW] ADD  CONSTRAINT [DF_RELEDETAILSW_ITEMENABLED]  DEFAULT (0) FOR [ITEMENABLED]
ALTER TABLE [dbo].[ROLEDETAILSW]  WITH CHECK ADD  CONSTRAINT [FK_ROLEDETAILSW_ROLEHEADERW] FOREIGN KEY([ROLEID])
REFERENCES [dbo].[ROLEHEADERW] ([ROLEID])
ALTER TABLE [dbo].[ROLEDETAILSW] CHECK CONSTRAINT [FK_ROLEDETAILSW_ROLEHEADERW]
ALTER TABLE [dbo].[ROLEDETAILSW]  WITH CHECK ADD  CONSTRAINT [FK_ROLEDETAILSW_ROLETEMPLATEW] FOREIGN KEY([ITEMPOSITION])
REFERENCES [dbo].[ROLETEMPLATEW] ([ITEMPOSITION])
ALTER TABLE [dbo].[ROLEDETAILSW] CHECK CONSTRAINT [FK_ROLEDETAILSW_ROLETEMPLATEW]