/****** Object:  Table [dbo].[ROLEHEADERP]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[ROLEHEADERP](
	[ROLEID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[ROLENAME] [nvarchar](50) NULL,
	[EID] [char](10) NOT NULL,
	[LOCKED] [bit] NOT NULL,
 CONSTRAINT [PK_RELEHEADER] PRIMARY KEY CLUSTERED 
(
	[ROLEID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[ROLEHEADERP] ADD  CONSTRAINT [DF_RELEHEADER_ROLENAME]  DEFAULT (N'( '')') FOR [ROLENAME]
ALTER TABLE [dbo].[ROLEHEADERP] ADD  CONSTRAINT [DF_ROLEHEADERP_EID]  DEFAULT ('') FOR [EID]
ALTER TABLE [dbo].[ROLEHEADERP] ADD  CONSTRAINT [DF_ROLEHEADERP_LOCKED]  DEFAULT ('0') FOR [LOCKED]