/****** Object:  Table [dbo].[ROLEHEADERA]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[ROLEHEADERA](
	[ROLEID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[ROLENAME] [nvarchar](50) NULL,
	[EID] [char](10) NOT NULL,
	[LOCKED] [bit] NOT NULL,
 CONSTRAINT [PK_ROLEHEADERA] PRIMARY KEY CLUSTERED 
(
	[ROLEID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[ROLEHEADERA] ADD  CONSTRAINT [DF_ROLEHEADERA_ROLENAME]  DEFAULT ('') FOR [ROLENAME]
ALTER TABLE [dbo].[ROLEHEADERA] ADD  CONSTRAINT [DF_ROLEHEADERA_EID]  DEFAULT ('') FOR [EID]
ALTER TABLE [dbo].[ROLEHEADERA] ADD  CONSTRAINT [DF_ROLEHEADERA_LOCKED]  DEFAULT ('0') FOR [LOCKED]