/****** Object:  Table [dbo].[ROLETEMPLATEW]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[ROLETEMPLATEW](
	[ITEMCATEGORY] [nvarchar](55) NULL,
	[ITEMACTION] [nvarchar](55) NULL,
	[ITEMDESCRIPTION] [nvarchar](255) NULL,
	[ITEMPOSITION] [int] NOT NULL,
	[LANG] [nvarchar](3) NOT NULL,
	[ISUAECOMPATIBLE] [bit] NOT NULL,
 CONSTRAINT [PK_ROLETEMPLATEW] PRIMARY KEY CLUSTERED 
(
	[ITEMPOSITION] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[ROLETEMPLATEW] ADD  CONSTRAINT [DF_ROLETEMPLATEW_ITEMCATEGORY]  DEFAULT ('') FOR [ITEMCATEGORY]
ALTER TABLE [dbo].[ROLETEMPLATEW] ADD  CONSTRAINT [DF_ROLETEMPLATEW_ITEMACTION]  DEFAULT ('') FOR [ITEMACTION]
ALTER TABLE [dbo].[ROLETEMPLATEW] ADD  CONSTRAINT [DF_ROLETEMPLATEW_ITEMDESCRIPTION]  DEFAULT ('') FOR [ITEMDESCRIPTION]
ALTER TABLE [dbo].[ROLETEMPLATEW] ADD  CONSTRAINT [DF_ROLETEMPLATEW_LANG_1]  DEFAULT ('ENG') FOR [LANG]
ALTER TABLE [dbo].[ROLETEMPLATEW] ADD  DEFAULT ((1)) FOR [ISUAECOMPATIBLE]