/****** Object:  Table [dbo].[ROLEHEADER]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[ROLEHEADER](
	[ROLECATEGORY] [char](25) NULL,
	[ROLENAME] [nvarchar](50) NOT NULL,
	[ROLEHEADERID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[LOCKED] [bit] NOT NULL,
 CONSTRAINT [PK_ROLEHEADER] PRIMARY KEY CLUSTERED 
(
	[ROLEHEADERID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[ROLEHEADER] ADD  CONSTRAINT [DF_ROLEHEADER_ROLENAME]  DEFAULT ('') FOR [ROLENAME]
ALTER TABLE [dbo].[ROLEHEADER] ADD  CONSTRAINT [DF_ROLEHEADER_LOCKED]  DEFAULT ('0') FOR [LOCKED]