/****** Object:  Table [dbo].[ROLETEMPLATEE]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[ROLETEMPLATEE](
	[ITEMCATEGORY] [nvarchar](55) NULL,
	[ITEMACTION] [nvarchar](55) NULL,
	[ITEMDESCRIPTION] [nvarchar](255) NULL,
	[ITEMPOSITION] [int] NOT NULL,
	[LANG] [nvarchar](3) NOT NULL,
 CONSTRAINT [PK_ROLETEMPLATEE] PRIMARY KEY CLUSTERED 
(
	[ITEMPOSITION] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[ROLETEMPLATEE] ADD  CONSTRAINT [DF_ROLETEMPLATEE_ITEMCATEGORY]  DEFAULT ('') FOR [ITEMCATEGORY]
ALTER TABLE [dbo].[ROLETEMPLATEE] ADD  CONSTRAINT [DF_ROLETEMPLATEE_ITEMACTION]  DEFAULT ('') FOR [ITEMACTION]
ALTER TABLE [dbo].[ROLETEMPLATEE] ADD  CONSTRAINT [DF_ROLETEMPLATEE_ITEMDESCRIPTION]  DEFAULT ('') FOR [ITEMDESCRIPTION]
ALTER TABLE [dbo].[ROLETEMPLATEE] ADD  CONSTRAINT [DF_ROLETEMPLATEE_LANG_1]  DEFAULT ('ENG') FOR [LANG]