/****** Object:  Table [dbo].[SHIFTCODES]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[SHIFTCODES](
	[SHIFTCODE] [nvarchar](50) NOT NULL,
	[PAYROLLID] [int] NOT NULL,
	[DESCRIPTION] [nvarchar](250) NOT NULL,
	[ISNIGHTSHIFT] [bit] NOT NULL,
	[SHOWONPAYSLIP] [bit] NOT NULL,
 CONSTRAINT [PK_SHIFTCODES] PRIMARY KEY CLUSTERED 
(
	[SHIFTCODE] ASC,
	[PAYROLLID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[SHIFTCODES] ADD  DEFAULT ((0)) FOR [ISNIGHTSHIFT]
ALTER TABLE [dbo].[SHIFTCODES] ADD  DEFAULT ((0)) FOR [SHOWONPAYSLIP]