/****** Object:  Table [dbo].[SHIPTOADDRESSES]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[SHIPTOADDRESSES](
	[SHIPTOID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[CONTACTID] [int] NOT NULL,
	[ADDRID] [int] NOT NULL,
	[TAXABLE] [bit] NOT NULL,
	[TAXPERC] [real] NOT NULL,
	[FOB] [nvarchar](20) NOT NULL,
	[SHIPPING] [nvarchar](60) NOT NULL,
	[MEMO] [nvarchar](255) NOT NULL,
	[HOMEBORGID] [int] NOT NULL,
	[SHIPTONAME] [nvarchar](50) NULL,
	[EID] [char](10) NOT NULL,
 CONSTRAINT [PK_ShipTo] PRIMARY KEY CLUSTERED 
(
	[SHIPTOID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[SHIPTOADDRESSES] ADD  CONSTRAINT [DF_ShipTo_TAXABLE]  DEFAULT (0) FOR [TAXABLE]
ALTER TABLE [dbo].[SHIPTOADDRESSES] ADD  CONSTRAINT [DF_ShipTo_TAXPERC]  DEFAULT (0) FOR [TAXPERC]
ALTER TABLE [dbo].[SHIPTOADDRESSES] ADD  CONSTRAINT [DF_ShipTo_FOB]  DEFAULT ('') FOR [FOB]
ALTER TABLE [dbo].[SHIPTOADDRESSES] ADD  CONSTRAINT [DF_ShipTo_SHIPPING]  DEFAULT ('') FOR [SHIPPING]
ALTER TABLE [dbo].[SHIPTOADDRESSES] ADD  CONSTRAINT [DF_ShipTo_MEMO]  DEFAULT ('') FOR [MEMO]
ALTER TABLE [dbo].[SHIPTOADDRESSES] ADD  DEFAULT ('') FOR [EID]