/****** Object:  Table [dbo].[SNAPSHOTADJUSTMENTS]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[SNAPSHOTADJUSTMENTS](
	[ID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[SnapshotsID] [int] NOT NULL,
	[LedgerCode] [nchar](10) NOT NULL,
	[ActNumber] [nchar](10) NOT NULL,
	[AdjustmentDesc] [nvarchar](100) NULL,
	[TotalReallocation] [money] NOT NULL,
	[TotalAccruals] [money] NOT NULL,
	[TotalSCLiability] [money] NOT NULL,
	[TotalMaterials] [money] NOT NULL,
	[TotalContras] [money] NOT NULL,
	[TotalResidual] [money] NOT NULL,
	[TotalOthers] [money] NOT NULL,
	[CreatedDate] [datetime] NOT NULL,
	[CreatedUser] [nvarchar](50) NOT NULL,
	[IsDeleted] [bit] NOT NULL,
	[DeletedDate] [datetime] NULL,
	[DeletedUser] [nvarchar](50) NULL,
 CONSTRAINT [PK_SNAPSHOTADJUSTMENTS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

CREATE NONCLUSTERED INDEX [IX_SNAPSHOTADJUSTMENTS_SnapshotsID] ON [dbo].[SNAPSHOTADJUSTMENTS]
(
	[SnapshotsID] ASC
)
INCLUDE([LedgerCode],[ActNumber],[TotalReallocation],[TotalAccruals],[TotalSCLiability],[TotalMaterials],[TotalContras],[TotalResidual],[TotalOthers]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
ALTER TABLE [dbo].[SNAPSHOTADJUSTMENTS] ADD  CONSTRAINT [DF_SNAPSHOTADJUSTMENTS_SnapshotsID]  DEFAULT ((0)) FOR [SnapshotsID]
ALTER TABLE [dbo].[SNAPSHOTADJUSTMENTS] ADD  CONSTRAINT [DF_SNAPSHOTADJUSTMENTS_TotalReallocation]  DEFAULT ((0)) FOR [TotalReallocation]
ALTER TABLE [dbo].[SNAPSHOTADJUSTMENTS] ADD  CONSTRAINT [DF_SNAPSHOTADJUSTMENTS_TotalAccruals]  DEFAULT ((0)) FOR [TotalAccruals]
ALTER TABLE [dbo].[SNAPSHOTADJUSTMENTS] ADD  CONSTRAINT [DF_SNAPSHOTADJUSTMENTS_TotalSCLiability]  DEFAULT ((0)) FOR [TotalSCLiability]
ALTER TABLE [dbo].[SNAPSHOTADJUSTMENTS] ADD  CONSTRAINT [DF_SNAPSHOTADJUSTMENTS_TotalMaterials]  DEFAULT ((0)) FOR [TotalMaterials]
ALTER TABLE [dbo].[SNAPSHOTADJUSTMENTS] ADD  CONSTRAINT [DF_SNAPSHOTADJUSTMENTS_TotalContras]  DEFAULT ((0)) FOR [TotalContras]
ALTER TABLE [dbo].[SNAPSHOTADJUSTMENTS] ADD  CONSTRAINT [DF_SNAPSHOTADJUSTMENTS_TotalResidual]  DEFAULT ((0)) FOR [TotalResidual]
ALTER TABLE [dbo].[SNAPSHOTADJUSTMENTS] ADD  CONSTRAINT [DF_SNAPSHOTADJUSTMENTS_TotalOthers]  DEFAULT ((0)) FOR [TotalOthers]
ALTER TABLE [dbo].[SNAPSHOTADJUSTMENTS] ADD  CONSTRAINT [DF_SNAPSHOTADJUSTMENTS_IsDeleted]  DEFAULT (N'0') FOR [IsDeleted]