/****** Object:  Table [dbo].[SNAPSHOTPOSTSETUP]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[SNAPSHOTPOSTSETUP](
	[ID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[ContrLedgerCode] [nvarchar](10) NOT NULL,
	[ContrLedgerName] [nvarchar](35) NOT NULL,
	[BSheetLedgerCode] [nvarchar](10) NOT NULL,
	[OrgID] [int] NOT NULL,
	[HistID] [int] NOT NULL,
	[IsUserEntry] [bit] NOT NULL,
	[SysLedgerName] [nvarchar](35) NOT NULL,
 CONSTRAINT [PK_SNAPSHOTPOSTSETUP] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[SNAPSHOTPOSTSETUP] ADD  CONSTRAINT [DF_SNAPSHOTPOSTSETUP_ContrLedgerCode]  DEFAULT ('') FOR [ContrLedgerCode]
ALTER TABLE [dbo].[SNAPSHOTPOSTSETUP] ADD  CONSTRAINT [DF_SNAPSHOTPOSTSETUP_ContrLedgerName]  DEFAULT ('') FOR [ContrLedgerName]
ALTER TABLE [dbo].[SNAPSHOTPOSTSETUP] ADD  CONSTRAINT [DF_SNAPSHOTPOSTSETUP_BSheetLedgerCode]  DEFAULT ('') FOR [BSheetLedgerCode]
ALTER TABLE [dbo].[SNAPSHOTPOSTSETUP] ADD  CONSTRAINT [DF_SNAPSHOTPOSTSETUP_OrgID]  DEFAULT ((0)) FOR [OrgID]
ALTER TABLE [dbo].[SNAPSHOTPOSTSETUP] ADD  CONSTRAINT [DF_SNAPSHOTPOSTSETUP_HistID]  DEFAULT ((0)) FOR [HistID]
ALTER TABLE [dbo].[SNAPSHOTPOSTSETUP] ADD  CONSTRAINT [DF_SNAPSHOTPOSTSETUP_IsUserEntry]  DEFAULT (N'0') FOR [IsUserEntry]
ALTER TABLE [dbo].[SNAPSHOTPOSTSETUP] ADD  CONSTRAINT [DF_SNAPSHOTPOSTSETUP_SysLedgerName]  DEFAULT ('') FOR [SysLedgerName]