/****** Object:  Table [dbo].[SNAPSHOTADJUSTMENTDETAILS]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[SNAPSHOTADJUSTMENTDETAILS](
	[ID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[SnapshotsID] [int] NOT NULL,
	[LedgerCode] [nchar](10) NOT NULL,
	[ActNumber] [nchar](10) NOT NULL,
	[Unit] [nvarchar](25) NOT NULL,
	[Quantity] [numeric](22, 8) NOT NULL,
	[Rate] [numeric](22, 8) NOT NULL,
	[AdjustmentType] [nchar](20) NOT NULL,
	[Amount] [money] NOT NULL,
	[AdjustmentDesc] [nvarchar](100) NOT NULL,
	[SnapshotAdjustmentID] [int] NOT NULL,
	[ResourceCode] [nvarchar](20) NULL,
	[CreatedDate] [datetime] NOT NULL,
	[CreatedUser] [nvarchar](50) NOT NULL,
	[IsDeleted] [bit] NOT NULL,
	[DeletedDate] [datetime] NULL,
	[DeletedUser] [nvarchar](50) NULL,
 CONSTRAINT [PK_SNAPSHOTADJUSTMENTDETAILS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[SNAPSHOTADJUSTMENTDETAILS] ADD  CONSTRAINT [DF_SNAPSHOTADJUSTMENTDETAILS_SnapshotsID]  DEFAULT ((0)) FOR [SnapshotsID]
ALTER TABLE [dbo].[SNAPSHOTADJUSTMENTDETAILS] ADD  CONSTRAINT [DF_SNAPSHOTADJUSTMENTDETAILS_Quantity]  DEFAULT (N'0') FOR [Quantity]
ALTER TABLE [dbo].[SNAPSHOTADJUSTMENTDETAILS] ADD  CONSTRAINT [DF_SNAPSHOTADJUSTMENTDETAILS_Rate]  DEFAULT (N'0') FOR [Rate]
ALTER TABLE [dbo].[SNAPSHOTADJUSTMENTDETAILS] ADD  CONSTRAINT [DF_SNAPSHOTADJUSTMENTDETAILS_AdjustmentType]  DEFAULT (N'0') FOR [AdjustmentType]
ALTER TABLE [dbo].[SNAPSHOTADJUSTMENTDETAILS] ADD  CONSTRAINT [DF_SNAPSHOTADJUSTMENTDETAILS_IsDeleted]  DEFAULT (N'0') FOR [IsDeleted]