/****** Object:  Table [dbo].[SREQCOMMENTS]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[SREQCOMMENTS](
	[CID] [int] IDENTITY(1,1) NOT NULL,
	[HID] [int] NOT NULL,
	[DID] [int] NOT NULL,
	[CDATETIME] [datetime] NOT NULL,
	[USERID] [int] NOT NULL,
	[COMMENT] [nvarchar](250) NULL,
 CONSTRAINT [PK_SREQCOMMENTS] PRIMARY KEY CLUSTERED 
(
	[CID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[SREQCOMMENTS] ADD  CONSTRAINT [DF_SREQCOMMENTS_CDATETIME]  DEFAULT (getdate()) FOR [CDATETIME]