/****** Object:  Table [dbo].[SREQITEMS]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[SREQITEMS](
	[DID] [int] IDENTITY(1,1) NOT NULL,
	[HID] [int] NOT NULL,
	[DEPARTMENT] [nvarchar](3) NOT NULL,
	[STKSTORE] [nvarchar](15) NOT NULL,
	[STKCODE] [nvarchar](20) NOT NULL,
	[LEDGERCODE] [nvarchar](10) NOT NULL,
	[ACTNUMBER] [nvarchar](10) NOT NULL,
	[DESCRIPTION] [nvarchar](225) NOT NULL,
	[REQQTY] [numeric](18, 4) NOT NULL,
	[RESCODE] [nvarchar](20) NOT NULL,
	[ITEMID] [int] NOT NULL,
	[CONTRNUMBER] [nvarchar](10) NOT NULL,
	[PENUMBER] [nvarchar](10) NOT NULL,
	[DIVID] [int] NOT NULL,
	[CATID] [int] NOT NULL,
	[COSTCODE] [nvarchar](10) NOT NULL,
	[UNIT] [varchar](10) NOT NULL,
	[CATALOGITEMID] [int] NOT NULL,
	[SUPPID] [int] NOT NULL,
	[PROJECTID] [int] NOT NULL,
	[CONTRACTID] [int] NOT NULL,
	[DLVRID] [int] NOT NULL,
	[STOCKID] [int] NOT NULL,
	[TBORGID] [int] NOT NULL,
	[EID] [varchar](10) NOT NULL,
	[STATUS] [nvarchar](50) NOT NULL,
	[ATTENTIONTO] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_SREQITEMS] PRIMARY KEY CLUSTERED 
(
	[DID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[SREQITEMS] ADD  CONSTRAINT [DF_SREQITEMS_HID]  DEFAULT ((-1)) FOR [HID]
ALTER TABLE [dbo].[SREQITEMS] ADD  CONSTRAINT [DF_SREQITEMS_DEPARTMENT]  DEFAULT ('') FOR [DEPARTMENT]
ALTER TABLE [dbo].[SREQITEMS] ADD  CONSTRAINT [DF_SREQITEMS_STKSTORE]  DEFAULT ('') FOR [STKSTORE]
ALTER TABLE [dbo].[SREQITEMS] ADD  CONSTRAINT [DF_SREQITEMS_STKCODE]  DEFAULT ('') FOR [STKCODE]
ALTER TABLE [dbo].[SREQITEMS] ADD  CONSTRAINT [DF_SREQITEMS_LEDGERCODE]  DEFAULT ('') FOR [LEDGERCODE]
ALTER TABLE [dbo].[SREQITEMS] ADD  CONSTRAINT [DF_SREQITEMS_ACTNUMBER]  DEFAULT ('') FOR [ACTNUMBER]
ALTER TABLE [dbo].[SREQITEMS] ADD  CONSTRAINT [DF_SREQITEMS_DESCRIPTION]  DEFAULT ('') FOR [DESCRIPTION]
ALTER TABLE [dbo].[SREQITEMS] ADD  CONSTRAINT [DF_SREQITEMS_REQQTY]  DEFAULT ('0') FOR [REQQTY]
ALTER TABLE [dbo].[SREQITEMS] ADD  CONSTRAINT [DF_SREQITEMS_RESCODE]  DEFAULT ('') FOR [RESCODE]
ALTER TABLE [dbo].[SREQITEMS] ADD  CONSTRAINT [DF_SREQITEMS_ITEMID]  DEFAULT ((-1)) FOR [ITEMID]
ALTER TABLE [dbo].[SREQITEMS] ADD  CONSTRAINT [DF_SREQITEMS_CONTRNUMBER]  DEFAULT ('') FOR [CONTRNUMBER]
ALTER TABLE [dbo].[SREQITEMS] ADD  CONSTRAINT [DF_SREQITEMS_PENUMBER]  DEFAULT ('') FOR [PENUMBER]
ALTER TABLE [dbo].[SREQITEMS] ADD  CONSTRAINT [DF_SREQITEMS_DIVID]  DEFAULT ((-1)) FOR [DIVID]
ALTER TABLE [dbo].[SREQITEMS] ADD  CONSTRAINT [DF_SREQITEMS_CATID]  DEFAULT ((-1)) FOR [CATID]
ALTER TABLE [dbo].[SREQITEMS] ADD  CONSTRAINT [DF_SREQITEMS_COSTCODE]  DEFAULT ('') FOR [COSTCODE]
ALTER TABLE [dbo].[SREQITEMS] ADD  CONSTRAINT [DF_SREQITEMS_UNIT]  DEFAULT ('') FOR [UNIT]
ALTER TABLE [dbo].[SREQITEMS] ADD  CONSTRAINT [DF_SREQITEMS_CATALOGITEMID]  DEFAULT ((-1)) FOR [CATALOGITEMID]
ALTER TABLE [dbo].[SREQITEMS] ADD  CONSTRAINT [DF_SREQITEMS_SUPPID]  DEFAULT ((-1)) FOR [SUPPID]
ALTER TABLE [dbo].[SREQITEMS] ADD  CONSTRAINT [DF_SREQITEMS_PROJECTID]  DEFAULT ((-1)) FOR [PROJECTID]
ALTER TABLE [dbo].[SREQITEMS] ADD  CONSTRAINT [DF_SREQITEMS_CONTRACTID]  DEFAULT ((-1)) FOR [CONTRACTID]
ALTER TABLE [dbo].[SREQITEMS] ADD  CONSTRAINT [DF_SREQITEMS_DLVRID]  DEFAULT ((-1)) FOR [DLVRID]
ALTER TABLE [dbo].[SREQITEMS] ADD  CONSTRAINT [DF_SREQITEMS_STOCKID]  DEFAULT ((-1)) FOR [STOCKID]
ALTER TABLE [dbo].[SREQITEMS] ADD  CONSTRAINT [DF_SREQITEMS_TBORGID]  DEFAULT ((-1)) FOR [TBORGID]
ALTER TABLE [dbo].[SREQITEMS] ADD  CONSTRAINT [DF_SREQITEMS_EID]  DEFAULT ('') FOR [EID]
ALTER TABLE [dbo].[SREQITEMS] ADD  CONSTRAINT [DF_SREQITEMS_STATUS]  DEFAULT ('') FOR [STATUS]
ALTER TABLE [dbo].[SREQITEMS] ADD  CONSTRAINT [DF_SREQITEMS_ATTENTIONTO]  DEFAULT ('') FOR [ATTENTIONTO]