/****** Object:  Table [dbo].[SREQ]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[SREQ](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NUMBER] [nvarchar](55) NOT NULL,
	[CREATEDON] [datetime] NOT NULL,
	[REQUIREDBY] [datetime] NOT NULL,
	[ATTENTIONTO] [nvarchar](50) NOT NULL,
	[BORGID] [int] NOT NULL,
	[USERID] [int] NOT NULL,
	[LOGUSER] [int] NOT NULL,
	[LOGDATETIME] [datetime] NULL,
	[REQNOTES] [nvarchar](256) NULL,
	[STATUS] [nvarchar](50) NOT NULL,
	[COSTCODE] [nvarchar](10) NOT NULL,
	[ALLOCATION] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_SREQ] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[SREQ] ADD  CONSTRAINT [DF_SREQ_NUMBER]  DEFAULT ('') FOR [NUMBER]
ALTER TABLE [dbo].[SREQ] ADD  CONSTRAINT [DF_SREQ_CREATEDON]  DEFAULT (getdate()) FOR [CREATEDON]
ALTER TABLE [dbo].[SREQ] ADD  CONSTRAINT [DF_SREQ_REQUIREDBY]  DEFAULT (getdate()) FOR [REQUIREDBY]
ALTER TABLE [dbo].[SREQ] ADD  CONSTRAINT [DF_SREQ_ATTENTIONTO]  DEFAULT ('') FOR [ATTENTIONTO]
ALTER TABLE [dbo].[SREQ] ADD  CONSTRAINT [DF_SREQ_BORGID]  DEFAULT ((-1)) FOR [BORGID]
ALTER TABLE [dbo].[SREQ] ADD  CONSTRAINT [DF_SREQ_USERID]  DEFAULT ((-1)) FOR [USERID]
ALTER TABLE [dbo].[SREQ] ADD  CONSTRAINT [DF_SREQ_LOGUSER]  DEFAULT ((-1)) FOR [LOGUSER]
ALTER TABLE [dbo].[SREQ] ADD  CONSTRAINT [DF_SREQ_STATUS]  DEFAULT ('') FOR [STATUS]
ALTER TABLE [dbo].[SREQ] ADD  CONSTRAINT [DF_SREQ_COSTCODE]  DEFAULT ('') FOR [COSTCODE]
ALTER TABLE [dbo].[SREQ] ADD  CONSTRAINT [DF_SREQ_ALLOCATION]  DEFAULT ('') FOR [ALLOCATION]