/****** Object:  Table [dbo].[STAMPS]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[STAMPS](
	[STAMPCODE] [nvarchar](4) NOT NULL,
	[STAMPDESCR] [nvarchar](50) NOT NULL,
	[STAMPVALUE] [money] NOT NULL,
	[PAYROLLID] [int] NOT NULL,
	[STAMPID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
 CONSTRAINT [PK_STAMPS] PRIMARY KEY CLUSTERED 
(
	[STAMPCODE] ASC,
	[PAYROLLID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[STAMPS] ADD  CONSTRAINT [DF_STAMPS_STAMPCODE]  DEFAULT ('') FOR [STAMPCODE]