/****** Object:  Table [dbo].[STANNICVOUCHERS]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[STANNICVOUCHERS](
	[CODE] [nvarchar](3) NOT NULL,
	[ORGID] [int] NOT NULL,
	[VATTYPE] [nvarchar](100) NOT NULL,
	[INUSE] [bit] NOT NULL,
 CONSTRAINT [PK_STANNICVOUCHERS] PRIMARY KEY CLUSTERED 
(
	[CODE] ASC,
	[ORGID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[STANNICVOUCHERS] ADD  CONSTRAINT [DF_STANNICVOUCHERS_ORGID]  DEFAULT ('-1') FOR [ORGID]
ALTER TABLE [dbo].[STANNICVOUCHERS] ADD  CONSTRAINT [DF_STANNICVOUCHERS_VATTYPE]  DEFAULT ('') FOR [VATTYPE]
ALTER TABLE [dbo].[STANNICVOUCHERS] ADD  CONSTRAINT [DF_STANNICVOUCHERS_INUSE]  DEFAULT ('1') FOR [INUSE]