/****** Object:  Table [dbo].[STANNICVEHICLES]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[STANNICVEHICLES](
	[CODE] [nvarchar](5) NOT NULL,
	[ALLOC] [nvarchar](15) NOT NULL,
	[COSTCODE] [nvarchar](15) NOT NULL,
	[SUBCOSTCODE] [nvarchar](15) NOT NULL,
 CONSTRAINT [PK_STANNICVEHICLES] PRIMARY KEY CLUSTERED 
(
	[CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[STANNICVEHICLES] ADD  CONSTRAINT [DF_STANNICVEHICLES_SUBCOSTCODE]  DEFAULT ('') FOR [SUBCOSTCODE]