/****** Object:  Table [dbo].[STANNICSUBCODES]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[STANNICSUBCODES](
	[CODE] [nvarchar](3) NOT NULL,
	[DESCRIPTION] [nvarchar](255) NOT NULL,
 CONSTRAINT [PK_STANNICSUBCODES] PRIMARY KEY CLUSTERED 
(
	[CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[STANNICSUBCODES] ADD  CONSTRAINT [DF_STANNICSUBCODES_DESCRIPTION]  DEFAULT ('') FOR [DESCRIPTION]