/****** Object:  Table [dbo].[STANNICCODES]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[STANNICCODES](
	[CODE] [nvarchar](3) NOT NULL,
	[PLANTLC] [nvarchar](10) NOT NULL,
	[OVERHEADLC] [nvarchar](10) NOT NULL,
	[BALANCESHEETLC] [nvarchar](10) NOT NULL,
	[CONTRACTLC] [nvarchar](10) NOT NULL,
	[SUMMARY] [bit] NOT NULL,
 CONSTRAINT [PK_STANNICCODES] PRIMARY KEY CLUSTERED 
(
	[CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[STANNICCODES] ADD  CONSTRAINT [DF_STANNICCODES_PLANTLC]  DEFAULT ('') FOR [PLANTLC]
ALTER TABLE [dbo].[STANNICCODES] ADD  CONSTRAINT [DF_STANNICCODES_OVERHEADLC]  DEFAULT ('') FOR [OVERHEADLC]
ALTER TABLE [dbo].[STANNICCODES] ADD  CONSTRAINT [DF_STANNICCODES_BALANCESHEETLC]  DEFAULT ('') FOR [BALANCESHEETLC]
ALTER TABLE [dbo].[STANNICCODES] ADD  CONSTRAINT [DF_STANNICCODES_CONTRACTLC]  DEFAULT ('') FOR [CONTRACTLC]
ALTER TABLE [dbo].[STANNICCODES] ADD  CONSTRAINT [DF_STANNICCODES_SUMMARY]  DEFAULT ('0') FOR [SUMMARY]