/****** Object:  Table [dbo].[STOCKHIREPERIOD]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[STOCKHIREPERIOD](
	[PSID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[ORGID] [int] NOT NULL,
	[YEAR] [int] NOT NULL,
	[PERIOD] [int] NOT NULL,
	[DESCR] [nvarchar](100) NOT NULL,
	[PEDATE] [datetime] NOT NULL,
	[STATUS] [int] NOT NULL,
	[NCSTARTDATE] [datetime] NULL,
	[NCENDDATE] [datetime] NULL,
 CONSTRAINT [PK_STOCKHIREPERIOD] PRIMARY KEY CLUSTERED 
(
	[PSID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[STOCKHIREPERIOD] ADD  CONSTRAINT [DF_STOCKHIREPERIOD_ORGID]  DEFAULT ((-1)) FOR [ORGID]
ALTER TABLE [dbo].[STOCKHIREPERIOD] ADD  CONSTRAINT [DF_STOCKHIREPERIOD_YEAR]  DEFAULT ((-1)) FOR [YEAR]
ALTER TABLE [dbo].[STOCKHIREPERIOD] ADD  CONSTRAINT [DF_STOCKHIREPERIOD_PERIOD]  DEFAULT ((-1)) FOR [PERIOD]
ALTER TABLE [dbo].[STOCKHIREPERIOD] ADD  CONSTRAINT [DF_STOCKHIREPERIOD_DESCR]  DEFAULT ('') FOR [DESCR]
ALTER TABLE [dbo].[STOCKHIREPERIOD] ADD  CONSTRAINT [DF_STOCKHIREPERIOD_PEDATE]  DEFAULT (getdate()) FOR [PEDATE]
ALTER TABLE [dbo].[STOCKHIREPERIOD] ADD  CONSTRAINT [DF_STOCKHIREPERIOD_STATUS]  DEFAULT ((-1)) FOR [STATUS]