/****** Object:  Table [dbo].[STOCKHIREROLLUP]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[STOCKHIREROLLUP](
	[SRID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[ORGID] [int] NOT NULL,
	[YEAR] [int] NOT NULL,
	[PERIOD] [int] NOT NULL,
	[CONTRACT] [nvarchar](10) NOT NULL,
	[DEBTOR] [nvarchar](10) NOT NULL,
	[STORE] [nvarchar](10) NOT NULL,
	[STOCKNO] [nvarchar](20) NOT NULL,
	[QUANTITY] [decimal](18, 2) NOT NULL,
	[ACTIVITY] [nvarchar](10) NOT NULL,
	[OHLEDGERCODE] [nvarchar](10) NOT NULL,
 CONSTRAINT [PK_STOCKHIREROLLUP] PRIMARY KEY CLUSTERED 
(
	[SRID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[STOCKHIREROLLUP] ADD  CONSTRAINT [DF_STOCKHIREROLLUP_ORGID]  DEFAULT ((-1)) FOR [ORGID]
ALTER TABLE [dbo].[STOCKHIREROLLUP] ADD  CONSTRAINT [DF_STOCKHIREROLLUP_YEAR]  DEFAULT ((-1)) FOR [YEAR]
ALTER TABLE [dbo].[STOCKHIREROLLUP] ADD  CONSTRAINT [DF_STOCKHIREROLLUP_PERIOD]  DEFAULT ((-1)) FOR [PERIOD]
ALTER TABLE [dbo].[STOCKHIREROLLUP] ADD  CONSTRAINT [DF_STOCKHIREROLLUP_CONTRACT]  DEFAULT ('') FOR [CONTRACT]
ALTER TABLE [dbo].[STOCKHIREROLLUP] ADD  CONSTRAINT [DF_STOCKHIREROLLUP_DEBTOR]  DEFAULT ('') FOR [DEBTOR]
ALTER TABLE [dbo].[STOCKHIREROLLUP] ADD  CONSTRAINT [DF_STOCKHIREROLLUP_STORE]  DEFAULT ('') FOR [STORE]
ALTER TABLE [dbo].[STOCKHIREROLLUP] ADD  CONSTRAINT [DF_STOCKHIREROLLUP_STOCKNO]  DEFAULT ('') FOR [STOCKNO]
ALTER TABLE [dbo].[STOCKHIREROLLUP] ADD  CONSTRAINT [DF_STOCKHIREROLLUP_QUANTITY]  DEFAULT ((0)) FOR [QUANTITY]
ALTER TABLE [dbo].[STOCKHIREROLLUP] ADD  CONSTRAINT [DF_STOCKHIREROLLUP_ACTIVITY]  DEFAULT ('') FOR [ACTIVITY]
ALTER TABLE [dbo].[STOCKHIREROLLUP] ADD  CONSTRAINT [DF_STOCKHIREROLLUP_OHLEDGERCODE]  DEFAULT ('') FOR [OHLEDGERCODE]