/****** Object:  Table [dbo].[SUBCRECONSADD]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[SUBCRECONSADD](
	[ID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[ReconID] [int] NOT NULL,
	[TYPE] [nvarchar](10) NOT NULL,
	[DATED] [datetime] NOT NULL,
	[Certno] [nvarchar](10) NOT NULL,
	[CandyID] [int] NULL,
	[ActNumber] [nvarchar](10) NULL,
	[LedgerCode] [nvarchar](10) NULL,
	[Description] [nvarchar](50) NULL,
	[Unit] [nvarchar](10) NULL,
	[Qty] [decimal](22, 8) NOT NULL,
	[Rate] [decimal](22, 8) NOT NULL,
	[Amount] [money] NOT NULL,
	[INVQTY] [decimal](22, 8) NULL,
	[INVRATE] [decimal](22, 8) NULL,
	[Remarks] [nvarchar](255) NULL,
	[ReconHistID] [int] NOT NULL,
	[IsSysEntry] [bit] NOT NULL,
	[INVAMOUNT] [money] NOT NULL,
 CONSTRAINT [PK_SUBCRECONSADD] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[SUBCRECONSADD] ADD  CONSTRAINT [DF_SUBCRECONSADD_DATED]  DEFAULT (getdate()) FOR [DATED]
ALTER TABLE [dbo].[SUBCRECONSADD] ADD  CONSTRAINT [DF_SUBCRECONSADD_Qty]  DEFAULT ((0)) FOR [Qty]
ALTER TABLE [dbo].[SUBCRECONSADD] ADD  CONSTRAINT [DF_SUBCRECONSADD_Rate]  DEFAULT ((0)) FOR [Rate]
ALTER TABLE [dbo].[SUBCRECONSADD] ADD  CONSTRAINT [DF_SUBCRECONSADD_Amount]  DEFAULT ((0)) FOR [Amount]
ALTER TABLE [dbo].[SUBCRECONSADD] ADD  CONSTRAINT [DF_SUBCRECONSADD_INVQTY]  DEFAULT ((0)) FOR [INVQTY]
ALTER TABLE [dbo].[SUBCRECONSADD] ADD  CONSTRAINT [DF_SUBCRECONSADD_INVRATE]  DEFAULT ((0)) FOR [INVRATE]
ALTER TABLE [dbo].[SUBCRECONSADD] ADD  CONSTRAINT [DF_SUBCRECONSADD_ReconHistID]  DEFAULT ((-1)) FOR [ReconHistID]
ALTER TABLE [dbo].[SUBCRECONSADD] ADD  CONSTRAINT [DF_SUBCRECONSADD_IsSysEntry]  DEFAULT (N'0') FOR [IsSysEntry]
ALTER TABLE [dbo].[SUBCRECONSADD] ADD  CONSTRAINT [DF_SUBCRECONSADD_INVAMOUNT]  DEFAULT ((0)) FOR [INVAMOUNT]