/****** Object:  Table [dbo].[SUBCRECONS]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[SUBCRECONS](
	[OrgID] [int] NOT NULL,
	[SubConNumber] [char](10) NULL,
	[Contract] [char](10) NULL,
	[Activity] [char](10) NULL,
	[ValNo] [numeric](18, 0) NULL,
	[Certno] [numeric](18, 0) NULL,
	[ContValue] [money] NULL,
	[WorkDoneTot] [money] NULL,
	[WorkDonePrev] [money] NULL,
	[WorkDoneThisMonth] [money] NULL,
	[EscalationTot] [money] NULL,
	[EscalationPrev] [money] NULL,
	[EscalationThisMonth] [money] NULL,
	[MOSTot] [money] NULL,
	[MOSPrev] [money] NULL,
	[MOSThisMonth] [money] NULL,
	[AdditionalTot] [money] NULL,
	[AdditionalPrev] [money] NULL,
	[AdditionalThisMonth] [money] NULL,
	[BFWDTot] [money] NULL,
	[BFWDPrev] [money] NULL,
	[BFWDThisMonth] [money] NULL,
	[VATTot] [money] NULL,
	[VATPrev] [money] NULL,
	[VATThisMonth] [money] NULL,
	[DiscountTot] [money] NULL,
	[DiscountPrev] [money] NULL,
	[DiscountThisMonth] [money] NULL,
	[AdvanceTot] [money] NULL,
	[AdvancePrev] [money] NULL,
	[AdvanceThisMonth] [money] NULL,
	[RetentionTot] [money] NULL,
	[RetentionPrev] [money] NULL,
	[RetentionThisMonth] [money] NULL,
	[ContraTot] [money] NULL,
	[ContraPrev] [money] NULL,
	[ContraThisMonth] [money] NULL,
	[WithholdTot] [money] NULL,
	[WithholdPrev] [money] NULL,
	[WithholdThisMonth] [money] NULL,
	[WithholdPerc] [decimal](18, 3) NULL,
	[OhrTot] [money] NOT NULL,
	[OhrPrev] [money] NOT NULL,
	[OhrThisMonth] [money] NOT NULL,
	[AmountDue] [money] NULL,
	[PrevPaid] [money] NULL,
	[TotDue] [money] NULL,
	[VATPerc] [decimal](18, 4) NOT NULL,
	[VATAmount] [money] NULL,
	[Paid] [money] NULL,
	[Name] [char](55) NULL,
	[SupName] [nvarchar](127) NOT NULL,
	[Code] [char](10) NULL,
	[Credno] [char](10) NULL,
	[Ret1] [money] NULL,
	[Ret2] [money] NULL,
	[RCo1] [money] NULL,
	[RCo2] [money] NULL,
	[Disc] [money] NULL,
	[Posted] [bit] NOT NULL,
	[LPosted] [bit] NOT NULL,
	[Printed] [bit] NOT NULL,
	[SCType] [char](10) NULL,
	[VATno] [char](10) NULL,
	[Remark] [char](200) NULL,
	[GLCode] [char](10) NULL,
	[ReconID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[UserID] [nvarchar](15) NOT NULL,
	[RetPerc] [decimal](18, 4) NOT NULL,
	[PostDate] [datetime] NULL,
	[PostRef] [char](55) NULL,
	[Orderno] [char](55) NULL,
	[ContrGLID] [char](10) NOT NULL,
	[ProvID] [int] NOT NULL,
	[Allocation] [char](25) NOT NULL,
	[Ledger] [char](10) NOT NULL,
	[exchrate] [float] NOT NULL,
	[contrexchrate] [float] NOT NULL,
	[currency] [char](3) NOT NULL,
	[VATonAdv] [money] NOT NULL,
	[VATonWDone] [money] NOT NULL,
	[ContraAlloc] [char](19) NOT NULL,
	[DIVID] [int] NULL,
	[WCATOT] [money] NOT NULL,
	[WCATHISMONTH] [money] NOT NULL,
	[WCAPREV] [money] NOT NULL,
	[UIFTOT] [money] NOT NULL,
	[UIFTHISMONTH] [money] NOT NULL,
	[UIFPREV] [money] NOT NULL,
	[SDLPERC] [numeric](18, 4) NOT NULL,
	[SDLTOT] [money] NOT NULL,
	[SDLTHISMONTH] [money] NOT NULL,
	[SDLPREV] [money] NOT NULL,
	[UIFPERC] [numeric](18, 4) NOT NULL,
	[WCAPERC] [numeric](18, 4) NOT NULL,
	[SCAPPROVER] [int] NULL,
	[SCAPPDATE] [datetime] NULL,
	[SCPOSTBY] [int] NULL,
	[SCPOSTDATE] [datetime] NULL,
	[VatType] [nvarchar](100) NULL,
	[WithholdID] [int] NULL,
	[CERTNOA] [nvarchar](10) NOT NULL,
	[FROMDATE] [datetime] NULL,
	[OVERRIDETAX] [int] NOT NULL,
	[OVERRIDEWHT] [int] NOT NULL,
	[SELFINVOICE] [int] NOT NULL,
	[PACKAGE] [varchar](30) NOT NULL,
	[PROVID2] [bit] NOT NULL,
	[LINKVAR] [bit] NOT NULL,
	[LINKESC] [bit] NOT NULL,
	[LINKMOS] [bit] NOT NULL,
	[LINKCONTRA] [bit] NOT NULL,
	[RETRELEASEDATE] [datetime] NULL,
	[LINKBILL] [bit] NOT NULL,
	[WFVALUEAPPROVED] [bit] NULL,
	[SUBMITTED] [bit] NULL,
	[APPROVED] [bit] NULL,
	[REJECTED] [bit] NULL,
	[FINALAMOUNT] [money] NOT NULL,
	[FINALCOST] [money] NOT NULL,
	[RECEIVEDDATE] [datetime] NULL,
	[RESPONSEDATE] [datetime] NULL,
	[LOGUSERID] [int] NOT NULL,
	[LOGDATETIME] [datetime] NOT NULL,
	[ReconHistID] [int] NOT NULL,
	[ADVANCEPERC] [decimal](18, 4) NOT NULL,
	[EXPAYMENTDATE] [datetime] NULL,
	[RevBudget] [money] NOT NULL,
	[CLASSID] [int] NOT NULL,
 CONSTRAINT [PK_SUBCRECONS] PRIMARY KEY CLUSTERED 
(
	[ReconID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [IX_SUBCRECONS_OrgID_PostDate_Allocation_Posted_Contract_SubConNumber_Activity] ON [dbo].[SUBCRECONS]
(
	[OrgID] ASC,
	[PostDate] ASC,
	[Allocation] ASC,
	[Posted] ASC,
	[Contract] ASC,
	[SubConNumber] ASC,
	[Activity] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
ALTER TABLE [dbo].[SUBCRECONS] ADD  CONSTRAINT [DF_SUBCRECONS_ContValue]  DEFAULT ((0)) FOR [ContValue]
ALTER TABLE [dbo].[SUBCRECONS] ADD  CONSTRAINT [DF_SUBCRECONS_WorkDoneTot]  DEFAULT ((0)) FOR [WorkDoneTot]
ALTER TABLE [dbo].[SUBCRECONS] ADD  CONSTRAINT [DF_SUBCRECONS_WorkDonePrev]  DEFAULT ((0)) FOR [WorkDonePrev]
ALTER TABLE [dbo].[SUBCRECONS] ADD  CONSTRAINT [DF_SUBCRECONS_WorkDoneThisMonth]  DEFAULT ((0)) FOR [WorkDoneThisMonth]
ALTER TABLE [dbo].[SUBCRECONS] ADD  CONSTRAINT [DF_SUBCRECONS_EscalationTot]  DEFAULT ((0)) FOR [EscalationTot]
ALTER TABLE [dbo].[SUBCRECONS] ADD  CONSTRAINT [DF_SUBCRECONS_EscalationPrev]  DEFAULT ((0)) FOR [EscalationPrev]
ALTER TABLE [dbo].[SUBCRECONS] ADD  CONSTRAINT [DF_SUBCRECONS_EscalationThisMonth]  DEFAULT ((0)) FOR [EscalationThisMonth]
ALTER TABLE [dbo].[SUBCRECONS] ADD  CONSTRAINT [DF_SUBCRECONS_MOSTot]  DEFAULT ((0)) FOR [MOSTot]
ALTER TABLE [dbo].[SUBCRECONS] ADD  CONSTRAINT [DF_SUBCRECONS_MOSPrev]  DEFAULT ((0)) FOR [MOSPrev]
ALTER TABLE [dbo].[SUBCRECONS] ADD  CONSTRAINT [DF_SUBCRECONS_MOSThisMonth]  DEFAULT ((0)) FOR [MOSThisMonth]
ALTER TABLE [dbo].[SUBCRECONS] ADD  CONSTRAINT [DF_SUBCRECONS_AdditionalTot]  DEFAULT ((0)) FOR [AdditionalTot]
ALTER TABLE [dbo].[SUBCRECONS] ADD  CONSTRAINT [DF_SUBCRECONS_AdditionalPrev]  DEFAULT ((0)) FOR [AdditionalPrev]
ALTER TABLE [dbo].[SUBCRECONS] ADD  CONSTRAINT [DF_SUBCRECONS_AdditionalThisMonth]  DEFAULT ((0)) FOR [AdditionalThisMonth]
ALTER TABLE [dbo].[SUBCRECONS] ADD  CONSTRAINT [DF_SUBCRECONS_BFWDTot]  DEFAULT ((0)) FOR [BFWDTot]
ALTER TABLE [dbo].[SUBCRECONS] ADD  CONSTRAINT [DF_SUBCRECONS_BFWDPrev]  DEFAULT ((0)) FOR [BFWDPrev]
ALTER TABLE [dbo].[SUBCRECONS] ADD  CONSTRAINT [DF_SUBCRECONS_BFWDThisMonth]  DEFAULT ((0)) FOR [BFWDThisMonth]
ALTER TABLE [dbo].[SUBCRECONS] ADD  CONSTRAINT [DF_SUBCRECONS_VATTot]  DEFAULT ((0)) FOR [VATTot]
ALTER TABLE [dbo].[SUBCRECONS] ADD  CONSTRAINT [DF_SUBCRECONS_VATPrev]  DEFAULT ((0)) FOR [VATPrev]
ALTER TABLE [dbo].[SUBCRECONS] ADD  CONSTRAINT [DF_SUBCRECONS_VATThisMonth]  DEFAULT ((0)) FOR [VATThisMonth]
ALTER TABLE [dbo].[SUBCRECONS] ADD  CONSTRAINT [DF_SUBCRECONS_DiscountTot]  DEFAULT ((0)) FOR [DiscountTot]
ALTER TABLE [dbo].[SUBCRECONS] ADD  CONSTRAINT [DF_SUBCRECONS_DiscountPrev]  DEFAULT ((0)) FOR [DiscountPrev]
ALTER TABLE [dbo].[SUBCRECONS] ADD  CONSTRAINT [DF_SUBCRECONS_DiscountThisMonth]  DEFAULT ((0)) FOR [DiscountThisMonth]
ALTER TABLE [dbo].[SUBCRECONS] ADD  CONSTRAINT [DF_SUBCRECONS_AdvanceTot]  DEFAULT ((0)) FOR [AdvanceTot]
ALTER TABLE [dbo].[SUBCRECONS] ADD  CONSTRAINT [DF_SUBCRECONS_AdvancePrev]  DEFAULT ((0)) FOR [AdvancePrev]
ALTER TABLE [dbo].[SUBCRECONS] ADD  CONSTRAINT [DF_SUBCRECONS_AdvanceThisMonth]  DEFAULT ((0)) FOR [AdvanceThisMonth]
ALTER TABLE [dbo].[SUBCRECONS] ADD  CONSTRAINT [DF_SUBCRECONS_RetentionTot]  DEFAULT ((0)) FOR [RetentionTot]
ALTER TABLE [dbo].[SUBCRECONS] ADD  CONSTRAINT [DF_SUBCRECONS_RetentionPrev]  DEFAULT ((0)) FOR [RetentionPrev]
ALTER TABLE [dbo].[SUBCRECONS] ADD  CONSTRAINT [DF_SUBCRECONS_RetentionThisMonth]  DEFAULT ((0)) FOR [RetentionThisMonth]
ALTER TABLE [dbo].[SUBCRECONS] ADD  CONSTRAINT [DF_SUBCRECONS_ContraTot]  DEFAULT ((0)) FOR [ContraTot]
ALTER TABLE [dbo].[SUBCRECONS] ADD  CONSTRAINT [DF_SUBCRECONS_ContraPrev]  DEFAULT ((0)) FOR [ContraPrev]
ALTER TABLE [dbo].[SUBCRECONS] ADD  CONSTRAINT [DF_SUBCRECONS_ContraThisMonth]  DEFAULT ((0)) FOR [ContraThisMonth]
ALTER TABLE [dbo].[SUBCRECONS] ADD  CONSTRAINT [DF_SUBCRECONS_WithholdTot]  DEFAULT ((0)) FOR [WithholdTot]
ALTER TABLE [dbo].[SUBCRECONS] ADD  CONSTRAINT [DF_SUBCRECONS_WithholdPrev]  DEFAULT ((0)) FOR [WithholdPrev]
ALTER TABLE [dbo].[SUBCRECONS] ADD  CONSTRAINT [DF_SUBCRECONS_WithholdThisMonth]  DEFAULT ((0)) FOR [WithholdThisMonth]
ALTER TABLE [dbo].[SUBCRECONS] ADD  CONSTRAINT [DF_SUBCRECONS_WithholdPerc]  DEFAULT ((0)) FOR [WithholdPerc]
ALTER TABLE [dbo].[SUBCRECONS] ADD  CONSTRAINT [DF_SUBCRECONS_OhrTot]  DEFAULT ('0') FOR [OhrTot]
ALTER TABLE [dbo].[SUBCRECONS] ADD  CONSTRAINT [DF_SUBCRECONS_OhrPrev]  DEFAULT ('0') FOR [OhrPrev]
ALTER TABLE [dbo].[SUBCRECONS] ADD  CONSTRAINT [DF_SUBCRECONS_OhrThisMonth]  DEFAULT ('0') FOR [OhrThisMonth]
ALTER TABLE [dbo].[SUBCRECONS] ADD  CONSTRAINT [DF_SUBCRECONS_AmountDue]  DEFAULT ((0)) FOR [AmountDue]
ALTER TABLE [dbo].[SUBCRECONS] ADD  CONSTRAINT [DF_SUBCRECONS_PrevPaid]  DEFAULT ((0)) FOR [PrevPaid]
ALTER TABLE [dbo].[SUBCRECONS] ADD  CONSTRAINT [DF_SUBCRECONS_TotDue]  DEFAULT ((0)) FOR [TotDue]
ALTER TABLE [dbo].[SUBCRECONS] ADD  CONSTRAINT [DF_SUBCRECONS_VATPerc]  DEFAULT ((0)) FOR [VATPerc]
ALTER TABLE [dbo].[SUBCRECONS] ADD  CONSTRAINT [DF_SUBCRECONS_Paid]  DEFAULT ((0)) FOR [Paid]
ALTER TABLE [dbo].[SUBCRECONS] ADD  CONSTRAINT [DF_SUBCRECONS_SUPNAME]  DEFAULT ('') FOR [SupName]
ALTER TABLE [dbo].[SUBCRECONS] ADD  CONSTRAINT [DF_SUBCRECONS_Posted]  DEFAULT ((0)) FOR [Posted]
ALTER TABLE [dbo].[SUBCRECONS] ADD  CONSTRAINT [DF_SUBCRECONS_LPosted]  DEFAULT ((0)) FOR [LPosted]
ALTER TABLE [dbo].[SUBCRECONS] ADD  CONSTRAINT [DF_SUBCRECONS_Printed]  DEFAULT ((0)) FOR [Printed]
ALTER TABLE [dbo].[SUBCRECONS] ADD  CONSTRAINT [DF_SUBCRECONS_USERID]  DEFAULT ('') FOR [UserID]
ALTER TABLE [dbo].[SUBCRECONS] ADD  CONSTRAINT [DF_SUBCRECONS_RetPerc]  DEFAULT ((10)) FOR [RetPerc]
ALTER TABLE [dbo].[SUBCRECONS] ADD  CONSTRAINT [DF_SUBCRECONS_ContrGLID]  DEFAULT ('') FOR [ContrGLID]
ALTER TABLE [dbo].[SUBCRECONS] ADD  CONSTRAINT [DF_SUBCRECONS_ProvID]  DEFAULT ((0)) FOR [ProvID]
ALTER TABLE [dbo].[SUBCRECONS] ADD  CONSTRAINT [DF_SUBCRECONS_Allocation]  DEFAULT ('Contracts') FOR [Allocation]
ALTER TABLE [dbo].[SUBCRECONS] ADD  CONSTRAINT [DF_SUBCRECONS_Ledger]  DEFAULT ('') FOR [Ledger]
ALTER TABLE [dbo].[SUBCRECONS] ADD  CONSTRAINT [DF_SUBCRECONS_EXCHRATE]  DEFAULT ((0)) FOR [exchrate]
ALTER TABLE [dbo].[SUBCRECONS] ADD  CONSTRAINT [DF_SUBCRECONS_CONTREXCHRATE]  DEFAULT ((0)) FOR [contrexchrate]
ALTER TABLE [dbo].[SUBCRECONS] ADD  CONSTRAINT [DF_SUBCRECONS_currency]  DEFAULT ('ZAR') FOR [currency]
ALTER TABLE [dbo].[SUBCRECONS] ADD  CONSTRAINT [DF_SUBCRECONS_VATonAdv]  DEFAULT ((0)) FOR [VATonAdv]
ALTER TABLE [dbo].[SUBCRECONS] ADD  CONSTRAINT [DF_SUBCRECONS_VATonWDone]  DEFAULT ((0)) FOR [VATonWDone]
ALTER TABLE [dbo].[SUBCRECONS] ADD  CONSTRAINT [DF_SUBCRECONS_ContraAlloc]  DEFAULT ('') FOR [ContraAlloc]
ALTER TABLE [dbo].[SUBCRECONS] ADD  CONSTRAINT [DF__SUBCRECON__WCATO__18E3F596]  DEFAULT ((0)) FOR [WCATOT]
ALTER TABLE [dbo].[SUBCRECONS] ADD  CONSTRAINT [DF__SUBCRECON__WCATH__19D819CF]  DEFAULT ((0)) FOR [WCATHISMONTH]
ALTER TABLE [dbo].[SUBCRECONS] ADD  CONSTRAINT [DF__SUBCRECON__WCAPR__1ACC3E08]  DEFAULT ((0)) FOR [WCAPREV]
ALTER TABLE [dbo].[SUBCRECONS] ADD  CONSTRAINT [DF__SUBCRECON__UIFTO__6880B55D]  DEFAULT ((0)) FOR [UIFTOT]
ALTER TABLE [dbo].[SUBCRECONS] ADD  CONSTRAINT [DF__SUBCRECON__UIFTH__6974D996]  DEFAULT ((0)) FOR [UIFTHISMONTH]
ALTER TABLE [dbo].[SUBCRECONS] ADD  CONSTRAINT [DF__SUBCRECON__UIFPR__6A68FDCF]  DEFAULT ((0)) FOR [UIFPREV]
ALTER TABLE [dbo].[SUBCRECONS] ADD  CONSTRAINT [DF__SUBCRECON__SDLPE__66E023A9]  DEFAULT ((1)) FOR [SDLPERC]
ALTER TABLE [dbo].[SUBCRECONS] ADD  CONSTRAINT [DF__SUBCRECON__SDLTO__67D447E2]  DEFAULT ((0)) FOR [SDLTOT]
ALTER TABLE [dbo].[SUBCRECONS] ADD  CONSTRAINT [DF__SUBCRECON__SDLTH__68C86C1B]  DEFAULT ((0)) FOR [SDLTHISMONTH]
ALTER TABLE [dbo].[SUBCRECONS] ADD  CONSTRAINT [DF__SUBCRECON__SDLPR__69BC9054]  DEFAULT ((0)) FOR [SDLPREV]
ALTER TABLE [dbo].[SUBCRECONS] ADD  CONSTRAINT [DF__SUBCRECON__UIFPE__6AB0B48D]  DEFAULT ((1)) FOR [UIFPERC]
ALTER TABLE [dbo].[SUBCRECONS] ADD  CONSTRAINT [DF__SUBCRECON__WCAPE__6F7569AA]  DEFAULT ((0)) FOR [WCAPERC]
ALTER TABLE [dbo].[SUBCRECONS] ADD  CONSTRAINT [DF_SUBCRECONS_SCAPPROVER]  DEFAULT ((-1)) FOR [SCAPPROVER]
ALTER TABLE [dbo].[SUBCRECONS] ADD  CONSTRAINT [DF_SUBCRECONS_SCAPPDATE]  DEFAULT (getdate()) FOR [SCAPPDATE]
ALTER TABLE [dbo].[SUBCRECONS] ADD  CONSTRAINT [DF_SUBCRECONS_SCPOSTBY]  DEFAULT ((-1)) FOR [SCPOSTBY]
ALTER TABLE [dbo].[SUBCRECONS] ADD  CONSTRAINT [DF_SUBCRECONS_SCPOSTDATE]  DEFAULT (getdate()) FOR [SCPOSTDATE]
ALTER TABLE [dbo].[SUBCRECONS] ADD  CONSTRAINT [DF_SUBCRECONS_VatType]  DEFAULT ('') FOR [VatType]
ALTER TABLE [dbo].[SUBCRECONS] ADD  CONSTRAINT [DF_SUBCRECONS_CERTNOA]  DEFAULT ('') FOR [CERTNOA]
ALTER TABLE [dbo].[SUBCRECONS] ADD  CONSTRAINT [DF_SUBCRECONS_OVERRIDETAX]  DEFAULT ((0)) FOR [OVERRIDETAX]
ALTER TABLE [dbo].[SUBCRECONS] ADD  CONSTRAINT [DF_SUBCRECONS_OVERRIDEWHT]  DEFAULT ((0)) FOR [OVERRIDEWHT]
ALTER TABLE [dbo].[SUBCRECONS] ADD  CONSTRAINT [DF_SUBCRECONS_SELFINVOICE]  DEFAULT ((0)) FOR [SELFINVOICE]
ALTER TABLE [dbo].[SUBCRECONS] ADD  CONSTRAINT [DF_SUBCRECONS_PACKAGE]  DEFAULT ('') FOR [PACKAGE]
ALTER TABLE [dbo].[SUBCRECONS] ADD  CONSTRAINT [DF_SUBCRECONS_PROVID2]  DEFAULT ('0') FOR [PROVID2]
ALTER TABLE [dbo].[SUBCRECONS] ADD  CONSTRAINT [DF_SUBCRECONS_LINKVAR]  DEFAULT ('0') FOR [LINKVAR]
ALTER TABLE [dbo].[SUBCRECONS] ADD  CONSTRAINT [DF_SUBCRECONS_LINKESC]  DEFAULT ('0') FOR [LINKESC]
ALTER TABLE [dbo].[SUBCRECONS] ADD  CONSTRAINT [DF_SUBCRECONS_LINKMOS]  DEFAULT ('0') FOR [LINKMOS]
ALTER TABLE [dbo].[SUBCRECONS] ADD  CONSTRAINT [DF_SUBCRECONS_LINKCONTRA]  DEFAULT ((1)) FOR [LINKCONTRA]
ALTER TABLE [dbo].[SUBCRECONS] ADD  CONSTRAINT [DF__SUBCRECON__LINKB__4528C53F]  DEFAULT ('0') FOR [LINKBILL]
ALTER TABLE [dbo].[SUBCRECONS] ADD  CONSTRAINT [DF_SUBCRECONS_WFVALUEAPPROVED]  DEFAULT (N'0') FOR [WFVALUEAPPROVED]
ALTER TABLE [dbo].[SUBCRECONS] ADD  CONSTRAINT [DF_SUBCRECONS_SUBMITTED]  DEFAULT (N'0') FOR [SUBMITTED]
ALTER TABLE [dbo].[SUBCRECONS] ADD  CONSTRAINT [DF_SUBCRECONS_APPROVED]  DEFAULT (N'0') FOR [APPROVED]
ALTER TABLE [dbo].[SUBCRECONS] ADD  CONSTRAINT [DF_SUBCRECONS_REJECTED]  DEFAULT (N'0') FOR [REJECTED]
ALTER TABLE [dbo].[SUBCRECONS] ADD  CONSTRAINT [DF_SUBCRECONS_FINALAMOUNT]  DEFAULT ((0)) FOR [FINALAMOUNT]
ALTER TABLE [dbo].[SUBCRECONS] ADD  CONSTRAINT [DF_SUBCRECONS_FINALCOST]  DEFAULT ((0)) FOR [FINALCOST]
ALTER TABLE [dbo].[SUBCRECONS] ADD  CONSTRAINT [DF_SUBCRECONS_LOGUSERID]  DEFAULT ((-1)) FOR [LOGUSERID]
ALTER TABLE [dbo].[SUBCRECONS] ADD  CONSTRAINT [DF_SUBCRECONS_LOGDATETIME]  DEFAULT (getdate()) FOR [LOGDATETIME]
ALTER TABLE [dbo].[SUBCRECONS] ADD  CONSTRAINT [DF_SUBCRECONS_ReconHistID]  DEFAULT ((-1)) FOR [ReconHistID]
ALTER TABLE [dbo].[SUBCRECONS] ADD  CONSTRAINT [DF_SUBCRECONS_ADVANCEPERC]  DEFAULT ((0)) FOR [ADVANCEPERC]
ALTER TABLE [dbo].[SUBCRECONS] ADD  CONSTRAINT [DF_SUBCRECONS_RevBudget]  DEFAULT ((0)) FOR [RevBudget]
ALTER TABLE [dbo].[SUBCRECONS] ADD  CONSTRAINT [DF_SUBCRECONS_CLASSID]  DEFAULT ((-1)) FOR [CLASSID]
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON

CREATE TRIGGER LOGSUBCRECONS ON SUBCRECONS
AFTER UPDATE, INSERT
AS 

SET NOCOUNT ON

declare @columnName nvarchar(500)
declare @keyColumn nvarchar(500)
declare @tableName nvarchar(500)
declare @sSql nvarchar(4000)
declare @primaryKey nvarchar(500)
declare @_ID nvarchar(500)
declare @logUserID int
declare @logDateTime datetime
declare @context_info int

SELECT @tableName = o.name
FROM sysobjects t
JOIN sysobjects o ON t.parent_obj = o.id
WHERE t.id = @@PROCID

set @context_info = -1
set @primaryKey = ''
set @logUserID = -1
set @logDateTime = DATEADD(M, -1, getDate()) 


/*GETS THE PRIMARY KEY COLUMNS*/
SELECT COLUMN_NAME
into #primanyKeys
FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE
WHERE OBJECTPROPERTY(OBJECT_ID(constraint_name), 'IsPrimaryKey') = 1
AND table_name = @tableName

select * into #inserted from INSERTED

set @sSql = 'DECLARE attribCursor CURSOR FOR '
set @sSql = @sSql + 'select '
DECLARE keyCursor CURSOR FOR
select COLUMN_NAME FROM #primanyKeys
OPEN keyCursor
FETCH NEXT FROM keyCursor into @keyColumn
WHILE @@FETCH_STATUS=0
BEGIN	
	if @primaryKey <> '' 
	BEGIN
		set @sSql = @sSql + ' + '' AND '' + '
	END
	set @sSql = @sSql + ''''+ @keyColumn +'='' + '''''''' + cast(rtrim(' + @keyColumn + ') as nvarchar(100)) + '''''''' '
	set @primaryKey = @keyColumn
FETCH NEXT FROM keyCursor into @keyColumn
END   
CLOSE keyCursor
DEALLOCATE keyCursor
set @sSql = @sSql + 'as _ID '
set @sSql = @sSql + 'FROM #inserted '
 
exec sp_executesql @sSql

SELECT @context_info = cast(replace(cast(CONTEXT_INFO as varchar(128)), char(0) COLLATE SQL_Latin1_General_CP1_CI_AS,'') as int) FROM master.dbo.sysprocesses WHERE spid = @@SPID

select @logUserID = isnull(USERID, -1),
@logDateTime = isnull(LOGDATETIME, DATEADD(M, -1, getDate()))
from logcontext 
where LOGID = @context_info
	
delete FROM LOGCONTEXT where LOGID = @context_info
  
OPEN attribCursor
FETCH NEXT FROM attribCursor into @_ID

WHILE @@FETCH_STATUS=0
BEGIN	 
  set @primaryKey = @_ID
  
  if DATEDIFF(s,@logDateTime, getDate()) > 5 or @logDateTime is null
	BEGIN
		set @logUserID= -1
	END

  set @sSql = 'UPDATE SUBCRECONS SET LOGUSERID = ' + cast(@logUserID as nvarchar(5)) + ', LOGDATETIME = getDate() WHERE ' + @primaryKey + ''
	
  exec sp_executesql @sSql

	FETCH NEXT FROM attribCursor into @_ID
END   

close attribCursor
DEALLOCATE attribCursor

DROP TABLE #inserted
DROP TABLE #primanyKeys

		
ALTER TABLE [dbo].[SUBCRECONS] ENABLE TRIGGER [LOGSUBCRECONS]