/****** Object:  Table [dbo].[SUBCRECONHEAD]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[SUBCRECONHEAD](
	[ID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[CODE] [nvarchar](10) NULL,
	[DESCRIPTION] [nvarchar](250) NULL,
	[MASTA] [nvarchar](50) NULL,
	[MASTB] [nvarchar](50) NULL,
	[MASTC] [nvarchar](50) NULL,
	[MASTD] [nvarchar](50) NULL,
	[MASTE] [nvarchar](50) NULL,
	[ACCSPEC] [int] NULL,
	[POST_ON] [int] NULL,
	[NUM] [int] NULL,
	[TAXIE] [int] NULL,
	[WD_REF] [nvarchar](50) NOT NULL,
	[ESC_REF] [nvarchar](50) NOT NULL,
	[MOS_REF] [nvarchar](50) NOT NULL,
	[VAR_REF] [nvarchar](50) NOT NULL,
	[CONTRA_REF] [nvarchar](50) NOT NULL,
	[TRANSREFCOL] [nvarchar](10) NOT NULL,
 CONSTRAINT [PK_SUBCRECONHEAD] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[SUBCRECONHEAD] ADD  CONSTRAINT [DF_SUBCRECONHEAD_WD_REF]  DEFAULT ('') FOR [WD_REF]
ALTER TABLE [dbo].[SUBCRECONHEAD] ADD  CONSTRAINT [DF_SUBCRECONHEAD_ESC_REF]  DEFAULT ('') FOR [ESC_REF]
ALTER TABLE [dbo].[SUBCRECONHEAD] ADD  CONSTRAINT [DF_SUBCRECONHEAD_MOS_REF]  DEFAULT ('') FOR [MOS_REF]
ALTER TABLE [dbo].[SUBCRECONHEAD] ADD  CONSTRAINT [DF_SUBCRECONHEAD_VAR_REF]  DEFAULT ('') FOR [VAR_REF]
ALTER TABLE [dbo].[SUBCRECONHEAD] ADD  CONSTRAINT [DF_SUBCRECONHEAD_CONTRA_REF]  DEFAULT ('') FOR [CONTRA_REF]
ALTER TABLE [dbo].[SUBCRECONHEAD] ADD  CONSTRAINT [DF_SUBCRECONHEAD_TRANSREFCOL]  DEFAULT ('CERTNOA') FOR [TRANSREFCOL]