/****** Object:  Table [dbo].[SUBCONTRADETAIL]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[SUBCONTRADETAIL](
	[BorgID] [int] NOT NULL,
	[ReconID] [int] NOT NULL,
	[ContraAlloc1] [char](25) NOT NULL,
	[ContraLedger1] [char](10) NOT NULL,
	[ContraDesc1] [char](125) NOT NULL,
	[ContraUnit1] [char](5) NOT NULL,
	[ContraQuant1] [numeric](19, 4) NOT NULL,
	[ContraRate1] [money] NOT NULL,
	[ContraVat1] [numeric](18, 0) NOT NULL,
	[ContraAlloc2] [char](25) NOT NULL,
	[ContraLedger2] [char](10) NOT NULL,
	[ContraDesc2] [char](125) NOT NULL,
	[ContraUnit2] [char](5) NOT NULL,
	[ContraQuant2] [numeric](19, 4) NOT NULL,
	[ContraRate2] [money] NOT NULL,
	[ContraVat2] [numeric](18, 0) NOT NULL,
	[ContraAlloc3] [char](25) NOT NULL,
	[ContraLedger3] [char](10) NOT NULL,
	[ContraDesc3] [char](125) NOT NULL,
	[ContraUnit3] [char](8) NOT NULL,
	[ContraQuant3] [numeric](19, 4) NOT NULL,
	[ContraRate3] [money] NOT NULL,
	[ContraVat3] [numeric](18, 0) NOT NULL,
	[ContraAlloc4] [char](25) NOT NULL,
	[ContraLedger4] [char](10) NOT NULL,
	[ContraDesc4] [char](125) NOT NULL,
	[ContraUnit4] [char](8) NOT NULL,
	[ContraQuant4] [numeric](19, 4) NOT NULL,
	[ContraRate4] [money] NOT NULL,
	[ContraVat4] [numeric](18, 0) NOT NULL,
	[ContraAlloc5] [char](25) NOT NULL,
	[ContraLedger5] [char](10) NOT NULL,
	[ContraDesc5] [char](125) NOT NULL,
	[ContraUnit5] [char](8) NOT NULL,
	[ContraQuant5] [numeric](19, 4) NOT NULL,
	[ContraRate5] [money] NOT NULL,
	[ContraVat5] [numeric](18, 0) NOT NULL,
	[ContraAlloc6] [char](25) NOT NULL,
	[ContraLedger6] [char](10) NOT NULL,
	[ContraDesc6] [char](125) NOT NULL,
	[ContraUnit6] [char](8) NOT NULL,
	[ContraQuant6] [numeric](19, 4) NOT NULL,
	[ContraRate6] [money] NOT NULL,
	[ContraVat6] [numeric](18, 0) NOT NULL,
	[ContraTotal] [money] NOT NULL,
	[ContraVAT] [money] NOT NULL,
	[CONTRAACT1] [char](10) NOT NULL,
	[CONTRAACT2] [char](10) NOT NULL,
	[CONTRAACT3] [char](10) NOT NULL,
	[CONTRAACT4] [char](10) NOT NULL,
	[CONTRAACT5] [char](10) NOT NULL,
	[CONTRAACT6] [char](10) NOT NULL
) ON [PRIMARY]

ALTER TABLE [dbo].[SUBCONTRADETAIL] ADD  CONSTRAINT [DF_SUBCONTRADETAIL_BorgID]  DEFAULT ((-1)) FOR [BorgID]
ALTER TABLE [dbo].[SUBCONTRADETAIL] ADD  CONSTRAINT [DF_SUBCONTRADETAIL_ReconID]  DEFAULT ((-1)) FOR [ReconID]
ALTER TABLE [dbo].[SUBCONTRADETAIL] ADD  CONSTRAINT [DF_SUBCONTRADETAIL_ContraAlloc1]  DEFAULT ('') FOR [ContraAlloc1]
ALTER TABLE [dbo].[SUBCONTRADETAIL] ADD  CONSTRAINT [DF_SUBCONTRADETAIL_ContraLedger1]  DEFAULT ('') FOR [ContraLedger1]
ALTER TABLE [dbo].[SUBCONTRADETAIL] ADD  CONSTRAINT [DF_SUBCONTRADETAIL_ContraDesc1]  DEFAULT ('') FOR [ContraDesc1]
ALTER TABLE [dbo].[SUBCONTRADETAIL] ADD  CONSTRAINT [DF_SUBCONTRADETAIL_ContraUnit1]  DEFAULT ('') FOR [ContraUnit1]
ALTER TABLE [dbo].[SUBCONTRADETAIL] ADD  CONSTRAINT [DF_SUBCONTRADETAIL_ContraQuant1]  DEFAULT (0) FOR [ContraQuant1]
ALTER TABLE [dbo].[SUBCONTRADETAIL] ADD  CONSTRAINT [DF_SUBCONTRADETAIL_ContraRate1]  DEFAULT (0) FOR [ContraRate1]
ALTER TABLE [dbo].[SUBCONTRADETAIL] ADD  CONSTRAINT [DF_SUBCONTRADETAIL_ContraVat1]  DEFAULT (0) FOR [ContraVat1]
ALTER TABLE [dbo].[SUBCONTRADETAIL] ADD  CONSTRAINT [DF_SUBCONTRADETAIL_ContraAlloc2]  DEFAULT ('') FOR [ContraAlloc2]
ALTER TABLE [dbo].[SUBCONTRADETAIL] ADD  CONSTRAINT [DF_SUBCONTRADETAIL_ContraLedger2]  DEFAULT ('') FOR [ContraLedger2]
ALTER TABLE [dbo].[SUBCONTRADETAIL] ADD  CONSTRAINT [DF_SUBCONTRADETAIL_ContraDesc2]  DEFAULT ('') FOR [ContraDesc2]
ALTER TABLE [dbo].[SUBCONTRADETAIL] ADD  CONSTRAINT [DF_SUBCONTRADETAIL_ContraUnit2]  DEFAULT ('') FOR [ContraUnit2]
ALTER TABLE [dbo].[SUBCONTRADETAIL] ADD  CONSTRAINT [DF_SUBCONTRADETAIL_ContraQuant2]  DEFAULT (0) FOR [ContraQuant2]
ALTER TABLE [dbo].[SUBCONTRADETAIL] ADD  CONSTRAINT [DF_SUBCONTRADETAIL_ContraRate2]  DEFAULT (0) FOR [ContraRate2]
ALTER TABLE [dbo].[SUBCONTRADETAIL] ADD  CONSTRAINT [DF_SUBCONTRADETAIL_ContraVat2]  DEFAULT (0) FOR [ContraVat2]
ALTER TABLE [dbo].[SUBCONTRADETAIL] ADD  CONSTRAINT [DF_SUBCONTRADETAIL_ContraAlloc3]  DEFAULT ('') FOR [ContraAlloc3]
ALTER TABLE [dbo].[SUBCONTRADETAIL] ADD  CONSTRAINT [DF_SUBCONTRADETAIL_ContraLedger3]  DEFAULT ('') FOR [ContraLedger3]
ALTER TABLE [dbo].[SUBCONTRADETAIL] ADD  CONSTRAINT [DF_SUBCONTRADETAIL_ContraDesc3]  DEFAULT ('') FOR [ContraDesc3]
ALTER TABLE [dbo].[SUBCONTRADETAIL] ADD  CONSTRAINT [DF_SUBCONTRADETAIL_ContraUnit3]  DEFAULT ('') FOR [ContraUnit3]
ALTER TABLE [dbo].[SUBCONTRADETAIL] ADD  CONSTRAINT [DF_SUBCONTRADETAIL_ContraQuant3]  DEFAULT (0) FOR [ContraQuant3]
ALTER TABLE [dbo].[SUBCONTRADETAIL] ADD  CONSTRAINT [DF_SUBCONTRADETAIL_ContraRate3]  DEFAULT (0) FOR [ContraRate3]
ALTER TABLE [dbo].[SUBCONTRADETAIL] ADD  CONSTRAINT [DF_SUBCONTRADETAIL_ContraVat3]  DEFAULT (0) FOR [ContraVat3]
ALTER TABLE [dbo].[SUBCONTRADETAIL] ADD  CONSTRAINT [DF_SUBCONTRADETAIL_ContraAlloc4]  DEFAULT ('') FOR [ContraAlloc4]
ALTER TABLE [dbo].[SUBCONTRADETAIL] ADD  CONSTRAINT [DF_SUBCONTRADETAIL_ContraLedger4]  DEFAULT ('') FOR [ContraLedger4]
ALTER TABLE [dbo].[SUBCONTRADETAIL] ADD  CONSTRAINT [DF_SUBCONTRADETAIL_ContraDesc4]  DEFAULT ('') FOR [ContraDesc4]
ALTER TABLE [dbo].[SUBCONTRADETAIL] ADD  CONSTRAINT [DF_SUBCONTRADETAIL_ContraUnit4]  DEFAULT ('') FOR [ContraUnit4]
ALTER TABLE [dbo].[SUBCONTRADETAIL] ADD  CONSTRAINT [DF_SUBCONTRADETAIL_ContraQuant4]  DEFAULT (0) FOR [ContraQuant4]
ALTER TABLE [dbo].[SUBCONTRADETAIL] ADD  CONSTRAINT [DF_SUBCONTRADETAIL_ContraRate4]  DEFAULT (0) FOR [ContraRate4]
ALTER TABLE [dbo].[SUBCONTRADETAIL] ADD  CONSTRAINT [DF_SUBCONTRADETAIL_ContraVat4]  DEFAULT (0) FOR [ContraVat4]
ALTER TABLE [dbo].[SUBCONTRADETAIL] ADD  CONSTRAINT [DF_SUBCONTRADETAIL_ContraAlloc5]  DEFAULT ('') FOR [ContraAlloc5]
ALTER TABLE [dbo].[SUBCONTRADETAIL] ADD  CONSTRAINT [DF_SUBCONTRADETAIL_ContraLedger5]  DEFAULT ('') FOR [ContraLedger5]
ALTER TABLE [dbo].[SUBCONTRADETAIL] ADD  CONSTRAINT [DF_SUBCONTRADETAIL_ContraDesc5]  DEFAULT ('') FOR [ContraDesc5]
ALTER TABLE [dbo].[SUBCONTRADETAIL] ADD  CONSTRAINT [DF_SUBCONTRADETAIL_ContraUnit5]  DEFAULT ('') FOR [ContraUnit5]
ALTER TABLE [dbo].[SUBCONTRADETAIL] ADD  CONSTRAINT [DF_SUBCONTRADETAIL_ContraQuant5]  DEFAULT (0) FOR [ContraQuant5]
ALTER TABLE [dbo].[SUBCONTRADETAIL] ADD  CONSTRAINT [DF_SUBCONTRADETAIL_ContraRate5]  DEFAULT (0) FOR [ContraRate5]
ALTER TABLE [dbo].[SUBCONTRADETAIL] ADD  CONSTRAINT [DF_SUBCONTRADETAIL_ContraVat5]  DEFAULT (0) FOR [ContraVat5]
ALTER TABLE [dbo].[SUBCONTRADETAIL] ADD  CONSTRAINT [DF_SUBCONTRADETAIL_ContraAlloc6]  DEFAULT ('') FOR [ContraAlloc6]
ALTER TABLE [dbo].[SUBCONTRADETAIL] ADD  CONSTRAINT [DF_SUBCONTRADETAIL_ContraLedger6]  DEFAULT ('') FOR [ContraLedger6]
ALTER TABLE [dbo].[SUBCONTRADETAIL] ADD  CONSTRAINT [DF_SUBCONTRADETAIL_ContraDesc6]  DEFAULT ('') FOR [ContraDesc6]
ALTER TABLE [dbo].[SUBCONTRADETAIL] ADD  CONSTRAINT [DF_SUBCONTRADETAIL_ContraUnit6]  DEFAULT ('') FOR [ContraUnit6]
ALTER TABLE [dbo].[SUBCONTRADETAIL] ADD  CONSTRAINT [DF_SUBCONTRADETAIL_ContraQuant6]  DEFAULT (0) FOR [ContraQuant6]
ALTER TABLE [dbo].[SUBCONTRADETAIL] ADD  CONSTRAINT [DF_SUBCONTRADETAIL_ContraRate6]  DEFAULT (0) FOR [ContraRate6]
ALTER TABLE [dbo].[SUBCONTRADETAIL] ADD  CONSTRAINT [DF_SUBCONTRADETAIL_ContraVat6]  DEFAULT (0) FOR [ContraVat6]
ALTER TABLE [dbo].[SUBCONTRADETAIL] ADD  CONSTRAINT [DF_SUBCONTRADETAIL_ContraTotal]  DEFAULT (0) FOR [ContraTotal]
ALTER TABLE [dbo].[SUBCONTRADETAIL] ADD  CONSTRAINT [DF_SUBCONTRADETAIL_ContraVAT]  DEFAULT (0) FOR [ContraVAT]
ALTER TABLE [dbo].[SUBCONTRADETAIL] ADD  DEFAULT ('') FOR [CONTRAACT1]
ALTER TABLE [dbo].[SUBCONTRADETAIL] ADD  DEFAULT ('') FOR [CONTRAACT2]
ALTER TABLE [dbo].[SUBCONTRADETAIL] ADD  DEFAULT ('') FOR [CONTRAACT3]
ALTER TABLE [dbo].[SUBCONTRADETAIL] ADD  DEFAULT ('') FOR [CONTRAACT4]
ALTER TABLE [dbo].[SUBCONTRADETAIL] ADD  DEFAULT ('') FOR [CONTRAACT5]
ALTER TABLE [dbo].[SUBCONTRADETAIL] ADD  DEFAULT ('') FOR [CONTRAACT6]