/****** Object:  Table [dbo].[SUPPLIERQUOTE]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[SUPPLIERQUOTE](
	[SupplierID] [int] NOT NULL,
	[ERFQID] [int] NOT NULL,
	[LineNumber] [int] NOT NULL,
	[AuditDate] [datetime] NOT NULL,
	[IsQuoteReady] [bit] NOT NULL,
	[Price] [money] NOT NULL,
	[IsSelected] [bit] NOT NULL,
	[IsQuoteSent] [bit] NOT NULL,
	[CONTACTID] [int] NOT NULL,
	[NOTE] [nvarchar](500) NULL,
	[SUPPLIERUOM] [nvarchar](50) NULL,
	[QUOTEVALIDATYLENGTH] [nvarchar](150) NULL,
	[EXPIRYDATE] [datetime] NULL,
	[VATOPTION] [nvarchar](50) NULL,
	[VATAMOUNT] [decimal](18, 4) NULL,
	[VATPERCENTAGE] [decimal](18, 4) NULL,
	[DISCOUNTPERCENTAGE] [decimal](18, 4) NULL,
	[DISCOUNTAMOUNT] [decimal](18, 4) NULL,
	[ITEMPRICE] [decimal](18, 4) NULL,
	[QUANTITY] [int] NULL,
 CONSTRAINT [PK_SupplierQuote_1] PRIMARY KEY CLUSTERED 
(
	[SupplierID] ASC,
	[ERFQID] ASC,
	[LineNumber] ASC,
	[CONTACTID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[SUPPLIERQUOTE] ADD  CONSTRAINT [DF_SupplierQuote_AuditDate]  DEFAULT (getdate()) FOR [AuditDate]
ALTER TABLE [dbo].[SUPPLIERQUOTE] ADD  CONSTRAINT [DF_SupplierQuote_IsQuoteReady]  DEFAULT ((0)) FOR [IsQuoteReady]
ALTER TABLE [dbo].[SUPPLIERQUOTE] ADD  CONSTRAINT [DF_SupplierQuote_Price]  DEFAULT ((0)) FOR [Price]
ALTER TABLE [dbo].[SUPPLIERQUOTE] ADD  CONSTRAINT [DF_SupplierQuote_IsSelected]  DEFAULT ((1)) FOR [IsSelected]
ALTER TABLE [dbo].[SUPPLIERQUOTE] ADD  CONSTRAINT [DF_SUPPLIERQUOTE_IsQuoteSent]  DEFAULT ((0)) FOR [IsQuoteSent]
ALTER TABLE [dbo].[SUPPLIERQUOTE] ADD  DEFAULT ((-1)) FOR [CONTACTID]
ALTER TABLE [dbo].[SUPPLIERQUOTE]  WITH CHECK ADD  CONSTRAINT [FK_SUPPLIERQUOTE_ERFQITEM] FOREIGN KEY([ERFQID], [LineNumber])
REFERENCES [dbo].[ERFQITEMS] ([ERFQID], [LINENUMBER])
ALTER TABLE [dbo].[SUPPLIERQUOTE] CHECK CONSTRAINT [FK_SUPPLIERQUOTE_ERFQITEM]
ALTER TABLE [dbo].[SUPPLIERQUOTE]  WITH CHECK ADD  CONSTRAINT [FK_SUPPLIERQUOTE_SUPPLIERS] FOREIGN KEY([SupplierID])
REFERENCES [dbo].[SUPPLIERS] ([SUPPID])
ALTER TABLE [dbo].[SUPPLIERQUOTE] CHECK CONSTRAINT [FK_SUPPLIERQUOTE_SUPPLIERS]