/****** Object:  Table [dbo].[SUPPLIERSDISPATCH]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[SUPPLIERSDISPATCH](
	[DISPID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[SUPPID] [int] NOT NULL,
	[DISPTYPE] [int] NOT NULL,
	[PRIORITY] [int] NOT NULL,
	[DISPNAME] [nvarchar](25) NOT NULL,
	[DISPDESCRIPTION] [nvarchar](255) NOT NULL,
 CONSTRAINT [PK_SUPPLIERSDISPATCH] PRIMARY KEY CLUSTERED 
(
	[DISPID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]