/****** Object:  Table [dbo].[SUPPLIERSPAYMENTTYPES]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[SUPPLIERSPAYMENTTYPES](
	[SUPPID] [int] NOT NULL,
	[PTYPEID] [int] NOT NULL,
	[PRIORITY] [int] NOT NULL,
	[PTERMID] [int] NOT NULL,
 CONSTRAINT [PK_SUPPLIERSPAYMENTTYPES] PRIMARY KEY CLUSTERED 
(
	[SUPPID] ASC,
	[PTYPEID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]