/****** Object:  Table [dbo].[SUPPLIERSSHIPMETHOD]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[SUPPLIERSSHIPMETHOD](
	[SUPPID] [int] NOT NULL,
	[SHIPID] [char](55) NOT NULL,
 CONSTRAINT [PK_SUPPLIERSSHIPMETHOD] PRIMARY KEY CLUSTERED 
(
	[SUPPID] ASC,
	[SHIPID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]