/****** Object:  Table [dbo].[TAXINDIATDS]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[TAXINDIATDS](
	[TDSID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[TDSCODE] [nvarchar](50) NOT NULL,
	[TDSDESCR] [nvarchar](75) NOT NULL,
	[MAXEXEMPTION] [money] NOT NULL,
 CONSTRAINT [PK_TAXINDIATDS] PRIMARY KEY CLUSTERED 
(
	[TDSID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[TAXINDIATDS] ADD  CONSTRAINT [DF_TAXINDIATDS_MAXEXEMPTION]  DEFAULT ((0)) FOR [MAXEXEMPTION]