/****** Object:  Table [dbo].[TAXPT]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[TAXPT](
	[TAXID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[TABLETYPE] [nvarchar](3) NOT NULL,
	[UPTOAMOUNT] [money] NOT NULL,
	[ND0] [decimal](8, 2) NOT NULL,
	[ND1] [decimal](8, 2) NOT NULL,
	[ND2] [decimal](8, 2) NOT NULL,
	[ND3] [decimal](8, 2) NOT NULL,
	[ND4] [decimal](8, 2) NOT NULL,
	[ND5] [decimal](8, 2) NOT NULL,
 CONSTRAINT [PK_TAXPT] PRIMARY KEY CLUSTERED 
(
	[TAXID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[TAXPT] ADD  CONSTRAINT [DF_TAXPT_ND0]  DEFAULT ((0)) FOR [ND0]
ALTER TABLE [dbo].[TAXPT] ADD  CONSTRAINT [DF_TAXPT_ND1]  DEFAULT ((0)) FOR [ND1]
ALTER TABLE [dbo].[TAXPT] ADD  CONSTRAINT [DF_TAXPT_ND2]  DEFAULT ((0)) FOR [ND2]
ALTER TABLE [dbo].[TAXPT] ADD  CONSTRAINT [DF_TAXPT_ND3]  DEFAULT ((0)) FOR [ND3]
ALTER TABLE [dbo].[TAXPT] ADD  CONSTRAINT [DF_TAXPT_ND4]  DEFAULT ((0)) FOR [ND4]
ALTER TABLE [dbo].[TAXPT] ADD  CONSTRAINT [DF_TAXPT_ND5]  DEFAULT ((0)) FOR [ND5]