/****** Object:  Table [dbo].[TAXWHT]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[TAXWHT](
	[WHTID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[SECTION] [nvarchar](10) NOT NULL,
	[CODE] [nvarchar](10) NOT NULL,
	[DESCRIPTION] [nvarchar](250) NOT NULL,
	[RATE1] [numeric](18, 4) NOT NULL,
	[RATE2] [numeric](18, 4) NOT NULL,
	[RATE3] [numeric](18, 4) NOT NULL,
	[THRESHOLD] [decimal](18, 4) NOT NULL,
 CONSTRAINT [PK_TAXWHT] PRIMARY KEY CLUSTERED 
(
	[WHTID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[TAXWHT] ADD  CONSTRAINT [DF_TAXWHT_SECTION]  DEFAULT ('') FOR [SECTION]
ALTER TABLE [dbo].[TAXWHT] ADD  CONSTRAINT [DF_TAXWHT_CODE]  DEFAULT ('') FOR [CODE]
ALTER TABLE [dbo].[TAXWHT] ADD  CONSTRAINT [DF_TAXWHT_DESCRIPTION]  DEFAULT ('') FOR [DESCRIPTION]
ALTER TABLE [dbo].[TAXWHT] ADD  CONSTRAINT [DF_TAXWHT_RATE1]  DEFAULT ((0)) FOR [RATE1]
ALTER TABLE [dbo].[TAXWHT] ADD  CONSTRAINT [DF_TAXWHT_RATE2]  DEFAULT ((0)) FOR [RATE2]
ALTER TABLE [dbo].[TAXWHT] ADD  CONSTRAINT [DF_TAXWHT_RATE3]  DEFAULT ((0)) FOR [RATE3]
ALTER TABLE [dbo].[TAXWHT] ADD  CONSTRAINT [DF_TAXWHT_THRESHOLD]  DEFAULT ((0)) FOR [THRESHOLD]