/****** Object:  Table [dbo].[TENDERITEMS]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[TENDERITEMS](
	[ITEMID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[RESCODE] [nvarchar](20) NOT NULL,
	[DESCR] [ntext] NOT NULL,
	[RATE] [money] NOT NULL,
	[UNIT] [nvarchar](15) NOT NULL,
	[QTY] [decimal](18, 4) NOT NULL,
	[BORG] [int] NOT NULL,
	[PROJECT] [int] NOT NULL,
	[CONTRACT] [int] NOT NULL,
	[ORDEREDQTY] [decimal](18, 4) NOT NULL,
	[EID] [char](10) NOT NULL,
	[LEDGERCODE] [nvarchar](10) NOT NULL,
	[CURRENCY] [nvarchar](3) NOT NULL,
	[SUPPCODE] [nvarchar](10) NOT NULL,
	[CATEGORY] [nvarchar](55) NOT NULL,
	[PERIODQTY] [decimal](18, 4) NOT NULL,
	[ORDEREDAMOUNT] [decimal](18, 4) NOT NULL,
	[FINALWASTE] [decimal](18, 4) NOT NULL,
	[REMARK] [nvarchar](255) NOT NULL,
	[PERIODWASTE] [decimal](18, 4) NOT NULL,
	[COSTRATE] [decimal](18, 4) NOT NULL,
	[COSTQTY] [decimal](18, 4) NOT NULL,
	[BILLQTY] [decimal](18, 4) NOT NULL,
	[COSTWASTE] [decimal](18, 4) NOT NULL,
	[EXCHRATE] [decimal](23, 6) NOT NULL,
	[ACTNUMBER] [nvarchar](10) NOT NULL,
	[ISACTDETAIL] [bit] NOT NULL,
	[ACTUALUSAGE] [decimal](18, 4) NOT NULL,
	[ACTUALWASTE] [decimal](18, 4) NOT NULL,
	[SYSDATE] [datetime] NOT NULL,
	[ORDEREDDISCOUNT] [decimal](18, 4) NOT NULL,
	[TEMP6] [nvarchar](10) NOT NULL,
	[RATETYPE] [int] NOT NULL,
	[BUYRATE] [money] NOT NULL,
	[USERID] [int] NOT NULL,
	[AUTOUPDATE] [bit] NOT NULL,
	[BUYRATESYSDATE] [datetime] NULL,
 CONSTRAINT [PK_TENDERITEMS] PRIMARY KEY CLUSTERED 
(
	[ITEMID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

ALTER TABLE [dbo].[TENDERITEMS] ADD  CONSTRAINT [DF_TENDERITEMS_RESCODE]  DEFAULT ('') FOR [RESCODE]
ALTER TABLE [dbo].[TENDERITEMS] ADD  CONSTRAINT [DF_TENDERITEMS_DESCR]  DEFAULT ('') FOR [DESCR]
ALTER TABLE [dbo].[TENDERITEMS] ADD  CONSTRAINT [DF_TENDERITEMS_RATE]  DEFAULT (0) FOR [RATE]
ALTER TABLE [dbo].[TENDERITEMS] ADD  CONSTRAINT [DF_TENDERITEMS_UNIT]  DEFAULT ('') FOR [UNIT]
ALTER TABLE [dbo].[TENDERITEMS] ADD  CONSTRAINT [DF_TENDERITEMS_QTY]  DEFAULT (0.000) FOR [QTY]
ALTER TABLE [dbo].[TENDERITEMS] ADD  CONSTRAINT [DF_TENDERITEMS_ORDEREDQTY]  DEFAULT (0.0000) FOR [ORDEREDQTY]
ALTER TABLE [dbo].[TENDERITEMS] ADD  DEFAULT ('') FOR [EID]
ALTER TABLE [dbo].[TENDERITEMS] ADD  CONSTRAINT [DF_TENDERITEMS_LEDGERCODE]  DEFAULT ('') FOR [LEDGERCODE]
ALTER TABLE [dbo].[TENDERITEMS] ADD  CONSTRAINT [DF_TENDERITEMS_CURRENCY]  DEFAULT ('ZAR') FOR [CURRENCY]
ALTER TABLE [dbo].[TENDERITEMS] ADD  CONSTRAINT [DF_TENDERITEMS_SUPPCODE]  DEFAULT ('') FOR [SUPPCODE]
ALTER TABLE [dbo].[TENDERITEMS] ADD  CONSTRAINT [DF_TENDERITEMS_CATEGORY]  DEFAULT ('') FOR [CATEGORY]
ALTER TABLE [dbo].[TENDERITEMS] ADD  CONSTRAINT [DF_TENDERITEMS_PERIODQTY]  DEFAULT ((0)) FOR [PERIODQTY]
ALTER TABLE [dbo].[TENDERITEMS] ADD  CONSTRAINT [DF_TENDERITEMS_ORDEREDAMOUNT]  DEFAULT ((0)) FOR [ORDEREDAMOUNT]
ALTER TABLE [dbo].[TENDERITEMS] ADD  CONSTRAINT [DF_TENDERITEMS_FINALWASTE]  DEFAULT ((0)) FOR [FINALWASTE]
ALTER TABLE [dbo].[TENDERITEMS] ADD  CONSTRAINT [DF_TENDERITEMS_REMARK]  DEFAULT ('') FOR [REMARK]
ALTER TABLE [dbo].[TENDERITEMS] ADD  CONSTRAINT [DF_TENDERITEMS_PERIODWASTE]  DEFAULT ((0)) FOR [PERIODWASTE]
ALTER TABLE [dbo].[TENDERITEMS] ADD  CONSTRAINT [DF_TENDERITEMS_COSTRATE]  DEFAULT ((0)) FOR [COSTRATE]
ALTER TABLE [dbo].[TENDERITEMS] ADD  CONSTRAINT [DF_TENDERITEMS_COSTQTY]  DEFAULT ((0)) FOR [COSTQTY]
ALTER TABLE [dbo].[TENDERITEMS] ADD  CONSTRAINT [DF_TENDERITEMS_BILLQTY]  DEFAULT ((0)) FOR [BILLQTY]
ALTER TABLE [dbo].[TENDERITEMS] ADD  CONSTRAINT [DF_TENDERITEMS_COSTWASTE]  DEFAULT ((0)) FOR [COSTWASTE]
ALTER TABLE [dbo].[TENDERITEMS] ADD  CONSTRAINT [DF_TENDERITEMS_EXCHRATE]  DEFAULT ((0)) FOR [EXCHRATE]
ALTER TABLE [dbo].[TENDERITEMS] ADD  CONSTRAINT [DF_TENDERITEMS_ACTNUMBER]  DEFAULT ('') FOR [ACTNUMBER]
ALTER TABLE [dbo].[TENDERITEMS] ADD  CONSTRAINT [DF_TENDERITEMS_ISACTDETAIL]  DEFAULT ('0') FOR [ISACTDETAIL]
ALTER TABLE [dbo].[TENDERITEMS] ADD  CONSTRAINT [DF_TENDERITEMS_ACTUALUSAGE]  DEFAULT ((0)) FOR [ACTUALUSAGE]
ALTER TABLE [dbo].[TENDERITEMS] ADD  CONSTRAINT [DF_TENDERITEMS_ACTUALWASTE]  DEFAULT ((0)) FOR [ACTUALWASTE]
ALTER TABLE [dbo].[TENDERITEMS] ADD  CONSTRAINT [DF_TENDERITEMS_SYSDATE]  DEFAULT (getdate()) FOR [SYSDATE]
ALTER TABLE [dbo].[TENDERITEMS] ADD  DEFAULT ((0)) FOR [ORDEREDDISCOUNT]
ALTER TABLE [dbo].[TENDERITEMS] ADD  DEFAULT ('') FOR [TEMP6]
ALTER TABLE [dbo].[TENDERITEMS] ADD  CONSTRAINT [DF_TENDERITEMS_RATETYPE]  DEFAULT ((1)) FOR [RATETYPE]
ALTER TABLE [dbo].[TENDERITEMS] ADD  CONSTRAINT [DF_TENDERITEMS_BUYRATE]  DEFAULT ((0)) FOR [BUYRATE]
ALTER TABLE [dbo].[TENDERITEMS] ADD  CONSTRAINT [DF_TENDERITEMS_USERID]  DEFAULT ((-1)) FOR [USERID]
ALTER TABLE [dbo].[TENDERITEMS] ADD  CONSTRAINT [DF_TENDERITEMS_AUTOUPDATE]  DEFAULT ((0)) FOR [AUTOUPDATE]
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON

CREATE TRIGGER TR_TENDERITEMSSNAPSHOT ON TENDERITEMS
AFTER UPDATE
AS 

SET NOCOUNT ON

insert into TENDERITEMSSNAPSHOT (ITEMID, QTY, ORDEREDQTY, ORDEREDAMOUNT, SYSDATE)
SELECT D.ITEMID, D.QTY, D.ORDEREDQTY, D.ORDEREDAMOUNT, getDate()
FROM INSERTED I inner join DELETED D on I.ITEMID = D.ITEMID
WHERE I.QTY <> D.QTY
OR I.ORDEREDQTY <> D.ORDEREDQTY
OR I.ORDEREDAMOUNT <> D.ORDEREDAMOUNT

		
ALTER TABLE [dbo].[TENDERITEMS] ENABLE TRIGGER [TR_TENDERITEMSSNAPSHOT]