/****** Object:  Table [dbo].[TENDERITEMSSNAPSHOT]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[TENDERITEMSSNAPSHOT](
	[TSID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[ITEMID] [int] NOT NULL,
	[QTY] [decimal](18, 4) NOT NULL,
	[ORDEREDQTY] [decimal](18, 4) NOT NULL,
	[ORDEREDAMOUNT] [decimal](18, 4) NOT NULL,
	[SYSDATE] [datetime] NOT NULL,
 CONSTRAINT [PK_TENDERITEMSSNAPSHOT] PRIMARY KEY CLUSTERED 
(
	[TSID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[TENDERITEMSSNAPSHOT] ADD  CONSTRAINT [DF_TENDERITEMSSNAPSHOT_SYSDATE]  DEFAULT (getdate()) FOR [SYSDATE]