/****** Object:  Table [dbo].[TERMS]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[TERMS](
	[TERM] [int] NOT NULL,
	[TERMNAME] [nvarchar](55) NOT NULL,
 CONSTRAINT [PK_TERMS] PRIMARY KEY CLUSTERED 
(
	[TERM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[TERMS] ADD  CONSTRAINT [DF_TERMS_TERMNAME]  DEFAULT ('') FOR [TERMNAME]