/****** Object:  Table [dbo].[TIMESHEETHEADER]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[TIMESHEETHEADER](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[PAYROLLID] [int] NOT NULL,
	[EMPID] [int] NOT NULL,
	[EMPNUMBER] [nvarchar](15) NOT NULL,
	[NOTES] [nvarchar](225) NULL,
	[TIMEIN] [time](7) NULL,
	[TIMEOUT] [time](7) NULL,
	[DATE] [date] NOT NULL,
	[DAYNO] [int] NULL,
	[HEADERID] [int] NULL,
 CONSTRAINT [PK_TIMESHEETHEADER] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]