/****** Object:  Table [dbo].[TIMESHEETDETAIL]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[TIMESHEETDETAIL](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[HEADERID] [int] NOT NULL,
	[COSTALLOCATION] [nvarchar](50) NOT NULL,
	[LEDGERCODE] [char](10) NOT NULL,
	[ACTNUMBER] [char](10) NOT NULL,
	[CONTRNUMBER] [nchar](10) NOT NULL,
	[PENUMBER] [char](10) NOT NULL,
	[NTM] [decimal](18, 2) NOT NULL,
	[OT1] [decimal](18, 2) NOT NULL,
	[OT2] [decimal](18, 2) NOT NULL,
	[OT3] [decimal](18, 2) NOT NULL,
	[OT4] [decimal](18, 2) NOT NULL,
	[OT5] [decimal](18, 2) NOT NULL,
 CONSTRAINT [PK_TIMESHEETDETAIL] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[TIMESHEETDETAIL] ADD  CONSTRAINT [DF_TIMESHEETDETAIL_CONTRNUMBER]  DEFAULT ('') FOR [CONTRNUMBER]
ALTER TABLE [dbo].[TIMESHEETDETAIL] ADD  CONSTRAINT [DF_TIMESHEETDETAIL_NTM]  DEFAULT ((0)) FOR [NTM]
ALTER TABLE [dbo].[TIMESHEETDETAIL] ADD  CONSTRAINT [DF_TIMESHEETDETAIL_OT1]  DEFAULT ((0)) FOR [OT1]
ALTER TABLE [dbo].[TIMESHEETDETAIL] ADD  CONSTRAINT [DF_TIMESHEETDETAIL_OT2]  DEFAULT ((0)) FOR [OT2]
ALTER TABLE [dbo].[TIMESHEETDETAIL] ADD  CONSTRAINT [DF_TIMESHEETDETAIL_OT3]  DEFAULT ((0)) FOR [OT3]
ALTER TABLE [dbo].[TIMESHEETDETAIL] ADD  CONSTRAINT [DF_TIMESHEETDETAIL_OT4]  DEFAULT ((0)) FOR [OT4]
ALTER TABLE [dbo].[TIMESHEETDETAIL] ADD  CONSTRAINT [DF_TIMESHEETDETAIL_OT5]  DEFAULT ((0)) FOR [OT5]