/****** Object:  Table [dbo].[TRANSACTIONSSNAPSHOT]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[TRANSACTIONSSNAPSHOT](
	[TRID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[TRANSID] [int] NOT NULL,
	[PAIDFOR] [bit] NOT NULL,
	[PAIDTODATE] [money] NOT NULL,
	[PAIDTHISPERIOD] [money] NOT NULL,
	[RECONSTATUS] [int] NOT NULL,
	[SYSDATE] [datetime] NOT NULL,
 CONSTRAINT [PK_TRANSACTIONSSNAPSHOT] PRIMARY KEY CLUSTERED 
(
	[TRID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

CREATE NONCLUSTERED INDEX [IX_TRANSACTIONSSNAPSHOT_TRANSID_SYSDATE] ON [dbo].[TRANSACTIONSSNAPSHOT]
(
	[TRANSID] ASC,
	[SYSDATE] ASC
)
INCLUDE([PAIDFOR],[PAIDTODATE],[PAIDTHISPERIOD],[RECONSTATUS]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
ALTER TABLE [dbo].[TRANSACTIONSSNAPSHOT] ADD  CONSTRAINT [DF_TRANSACTIONSSNAPSHOT_SYSDATE]  DEFAULT (getdate()) FOR [SYSDATE]