/****** Object:  Table [dbo].[TRANSACTIONS]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[TRANSACTIONS](
	[OrgID] [int] NOT NULL,
	[Year] [char](10) NOT NULL,
	[Period] [int] NOT NULL,
	[PDate] [datetime] NULL,
	[BatchRef] [char](10) NOT NULL,
	[TransRef] [char](10) NOT NULL,
	[MatchRef] [char](10) NOT NULL,
	[TransType] [char](10) NOT NULL,
	[Allocation] [char](25) NOT NULL,
	[LedgerCode] [char](10) NOT NULL,
	[Contract] [nvarchar](10) NOT NULL,
	[Activity] [char](10) NOT NULL,
	[Description] [char](255) NOT NULL,
	[ForeignDescription] [char](255) NOT NULL,
	[Currency] [nvarchar](3) NOT NULL,
	[Debit] [money] NOT NULL,
	[Credit] [money] NOT NULL,
	[VatDebit] [money] NOT NULL,
	[VatCredit] [money] NOT NULL,
	[Credno] [char](10) NOT NULL,
	[Store] [char](20) NOT NULL,
	[Plantno] [char](10) NOT NULL,
	[Stockno] [char](20) NOT NULL,
	[Quantity] [numeric](23, 4) NOT NULL,
	[Unit] [char](10) NOT NULL,
	[Rate] [money] NOT NULL,
	[ReqNo] [char](55) NOT NULL,
	[OrderNo] [char](55) NOT NULL,
	[Age] [int] NOT NULL,
	[TransID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[SubConTran] [char](20) NOT NULL,
	[VATType] [char](2) NOT NULL,
	[HomeCurrAmount] [money] NULL,
	[ConversionDate] [datetime] NULL,
	[ConversionRate] [money] NOT NULL,
	[PaidFor] [bit] NOT NULL,
	[PaidToDate] [money] NOT NULL,
	[PaidThisPeriod] [money] NOT NULL,
	[WhtThisPeriod] [money] NOT NULL,
	[DiscThisPeriod] [money] NOT NULL,
	[ReconStatus] [int] NOT NULL,
	[UserID] [char](10) NULL,
	[DivID] [int] NOT NULL,
	[ForexVal] [money] NOT NULL,
	[HeadID] [char](10) NULL,
	[XGLCODE] [char](10) NOT NULL,
	[XVATA] [money] NOT NULL,
	[XVATT] [char](2) NOT NULL,
	[DOCNUMBER] [nchar](50) NULL,
	[WHTID] [int] NULL,
	[FBID] [int] NULL,
	[TERM] [int] NULL,
	[SYSDATE] [datetime] NULL,
	[RECEIVEDDATE] [datetime] NULL,
	[ORIGTRANSID] [int] NULL,
	[HCTODATE] [numeric](18, 4) NULL,
	[TRANGRP] [int] NULL,
	[ROLLEDFWD] [int] NULL,
	[TRANSREFEXT] [nvarchar](55) NULL,
	[HOMECURRAMOUNTALT] [money] NULL,
	[CLASSID] [int] NOT NULL,
 CONSTRAINT [PK_TRANSACTIONS] PRIMARY KEY CLUSTERED 
(
	[TransID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

CREATE NONCLUSTERED INDEX [IX_OrgID_VATType] ON [dbo].[TRANSACTIONS]
(
	[OrgID] ASC
)
INCLUDE([VATType]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
CREATE NONCLUSTERED INDEX [IX_TRANSACTIONS__OrgID] ON [dbo].[TRANSACTIONS]
(
	[OrgID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [IX_TRANSACTIONS__Year_Period] ON [dbo].[TRANSACTIONS]
(
	[Year] ASC,
	[Period] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [IX_TRANSACTIONS_Allocation] ON [dbo].[TRANSACTIONS]
(
	[Allocation] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [IX_TRANSACTIONS_Allocation_OrgID_Year_Period_Contract_LedgerCode_Credno_Plantno_PDate] ON [dbo].[TRANSACTIONS]
(
	[Allocation] ASC,
	[OrgID] ASC,
	[Year] ASC,
	[Period] ASC,
	[Contract] ASC,
	[LedgerCode] ASC,
	[Credno] ASC,
	[Plantno] ASC,
	[PDate] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [IX_TRANSACTIONS_BatchRef] ON [dbo].[TRANSACTIONS]
(
	[BatchRef] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [IX_TRANSACTIONS_Contract_Activity] ON [dbo].[TRANSACTIONS]
(
	[Contract] ASC,
	[Activity] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [IX_TRANSACTIONS_Contract_OrgID_Allocation_Year_CrednoLedgerCode_Period_PDate_Plantno] ON [dbo].[TRANSACTIONS]
(
	[Contract] ASC,
	[OrgID] ASC,
	[Allocation] ASC,
	[Year] ASC,
	[Credno] ASC,
	[LedgerCode] ASC,
	[Period] ASC,
	[PDate] ASC,
	[Plantno] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [IX_TRANSACTIONS_Credno_PaidFor_ReconStatus] ON [dbo].[TRANSACTIONS]
(
	[Credno] ASC,
	[PaidFor] ASC,
	[ReconStatus] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [IX_TRANSACTIONS_IX_TRANSACTIONS_Credno] ON [dbo].[TRANSACTIONS]
(
	[Credno] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [IX_TRANSACTIONS_LedgerCode] ON [dbo].[TRANSACTIONS]
(
	[LedgerCode] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [IX_TRANSACTIONS_LedgerCode_WhtThisPeriod] ON [dbo].[TRANSACTIONS]
(
	[LedgerCode] ASC,
	[WhtThisPeriod] ASC
)
INCLUDE([TransType],[TransID]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [IX_TRANSACTIONS_OrderNo] ON [dbo].[TRANSACTIONS]
(
	[OrderNo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [IX_TRANSACTIONS_OrgID_ReconStatus_SubConTran] ON [dbo].[TRANSACTIONS]
(
	[OrgID] ASC,
	[ReconStatus] ASC,
	[SubConTran] ASC
)
INCLUDE([LedgerCode],[PaidThisPeriod],[DiscThisPeriod]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [IX_TRANSACTIONS_OrgID_Store_Stockno] ON [dbo].[TRANSACTIONS]
(
	[OrgID] ASC,
	[Store] ASC,
	[Stockno] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [IX_TRANSACTIONS_OrgID_TransType_TransRef_Credno] ON [dbo].[TRANSACTIONS]
(
	[OrgID] ASC,
	[TransRef] ASC,
	[TransType] ASC,
	[Credno] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [IX_TRANSACTIONS_ORGID_YEAR_LCODE_CREDNO] ON [dbo].[TRANSACTIONS]
(
	[OrgID] ASC,
	[Year] ASC,
	[LedgerCode] ASC,
	[Credno] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [IX_TRANSACTIONS_Plantno] ON [dbo].[TRANSACTIONS]
(
	[Plantno] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [IX_TRANSACTIONS_ReqNo] ON [dbo].[TRANSACTIONS]
(
	[ReqNo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [IX_TRANSACTIONS_Stockno] ON [dbo].[TRANSACTIONS]
(
	[Stockno] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
CREATE NONCLUSTERED INDEX [IX_TRANSACTIONS_TRANGRP] ON [dbo].[TRANSACTIONS]
(
	[TRANGRP] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [IX_TRANSACTIONS_TRANSREF] ON [dbo].[TRANSACTIONS]
(
	[TransRef] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [IX_TRANSACTIONS_TransRef_MatchRef] ON [dbo].[TRANSACTIONS]
(
	[TransRef] ASC,
	[MatchRef] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [IX_TRANSACTIONS_TransType] ON [dbo].[TRANSACTIONS]
(
	[TransType] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
CREATE NONCLUSTERED INDEX [IX_TRANSACTIONS_WHTID] ON [dbo].[TRANSACTIONS]
(
	[WHTID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [New] ON [dbo].[TRANSACTIONS]
(
	[OrgID] ASC,
	[Year] ASC,
	[LedgerCode] ASC,
	[Credno] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = OFF, FILLFACTOR = 90) ON [PRIMARY]
ALTER TABLE [dbo].[TRANSACTIONS] ADD  CONSTRAINT [DF_TRANSACTIONS_OrgID]  DEFAULT (0) FOR [OrgID]
ALTER TABLE [dbo].[TRANSACTIONS] ADD  CONSTRAINT [DF_TRANSACTIONS_Year]  DEFAULT ('2000') FOR [Year]
ALTER TABLE [dbo].[TRANSACTIONS] ADD  CONSTRAINT [DF_TRANSACTIONS_Period]  DEFAULT (1) FOR [Period]
ALTER TABLE [dbo].[TRANSACTIONS] ADD  CONSTRAINT [DF_TRANSACTIONS_BatchRef]  DEFAULT (' ') FOR [BatchRef]
ALTER TABLE [dbo].[TRANSACTIONS] ADD  CONSTRAINT [DF_TRANSACTIONS_TransRef]  DEFAULT (' ') FOR [TransRef]
ALTER TABLE [dbo].[TRANSACTIONS] ADD  CONSTRAINT [DF_TRANSACTIONS_MatchRef]  DEFAULT (' ') FOR [MatchRef]
ALTER TABLE [dbo].[TRANSACTIONS] ADD  CONSTRAINT [DF_TRANSACTIONS_TransType]  DEFAULT (' ') FOR [TransType]
ALTER TABLE [dbo].[TRANSACTIONS] ADD  CONSTRAINT [DF_TRANSACTIONS_Allocation]  DEFAULT ('Balance Sheet') FOR [Allocation]
ALTER TABLE [dbo].[TRANSACTIONS] ADD  CONSTRAINT [DF_TRANSACTIONS_LedgerCode]  DEFAULT (9999) FOR [LedgerCode]
ALTER TABLE [dbo].[TRANSACTIONS] ADD  CONSTRAINT [DF_TRANSACTIONS_Contract]  DEFAULT (' ') FOR [Contract]
ALTER TABLE [dbo].[TRANSACTIONS] ADD  CONSTRAINT [DF_TRANSACTIONS_Activity]  DEFAULT (' ') FOR [Activity]
ALTER TABLE [dbo].[TRANSACTIONS] ADD  CONSTRAINT [DF_TRANSACTIONS_Description]  DEFAULT (' ') FOR [Description]
ALTER TABLE [dbo].[TRANSACTIONS] ADD  CONSTRAINT [DF_TRANSACTIONS_ForeignDescription]  DEFAULT ('') FOR [ForeignDescription]
ALTER TABLE [dbo].[TRANSACTIONS] ADD  CONSTRAINT [DF_TRANSACTIONS_Currency]  DEFAULT ('ZAR') FOR [Currency]
ALTER TABLE [dbo].[TRANSACTIONS] ADD  CONSTRAINT [DF_TRANSACTIONS_Debit]  DEFAULT (0.00) FOR [Debit]
ALTER TABLE [dbo].[TRANSACTIONS] ADD  CONSTRAINT [DF_TRANSACTIONS_Credit]  DEFAULT (0.00) FOR [Credit]
ALTER TABLE [dbo].[TRANSACTIONS] ADD  CONSTRAINT [DF_TRANSACTIONS_VatDebit]  DEFAULT (0.00) FOR [VatDebit]
ALTER TABLE [dbo].[TRANSACTIONS] ADD  CONSTRAINT [DF_TRANSACTIONS_VatCredit]  DEFAULT (0.00) FOR [VatCredit]
ALTER TABLE [dbo].[TRANSACTIONS] ADD  CONSTRAINT [DF_TRANSACTIONS_Credno]  DEFAULT (' ') FOR [Credno]
ALTER TABLE [dbo].[TRANSACTIONS] ADD  CONSTRAINT [DF_TRANSACTIONS_Store]  DEFAULT ('') FOR [Store]
ALTER TABLE [dbo].[TRANSACTIONS] ADD  CONSTRAINT [DF_TRANSACTIONS_Plantno]  DEFAULT (' ') FOR [Plantno]
ALTER TABLE [dbo].[TRANSACTIONS] ADD  CONSTRAINT [DF_TRANSACTIONS_Stockno]  DEFAULT (' ') FOR [Stockno]
ALTER TABLE [dbo].[TRANSACTIONS] ADD  CONSTRAINT [DF_TRANSACTIONS_Quantity]  DEFAULT (0) FOR [Quantity]
ALTER TABLE [dbo].[TRANSACTIONS] ADD  CONSTRAINT [DF_TRANSACTIONS_Unit]  DEFAULT (' ') FOR [Unit]
ALTER TABLE [dbo].[TRANSACTIONS] ADD  CONSTRAINT [DF_TRANSACTIONS_Rate]  DEFAULT (0) FOR [Rate]
ALTER TABLE [dbo].[TRANSACTIONS] ADD  CONSTRAINT [DF_TRANSACTIONS_ReqNo]  DEFAULT (' ') FOR [ReqNo]
ALTER TABLE [dbo].[TRANSACTIONS] ADD  CONSTRAINT [DF_TRANSACTIONS_OrderNo]  DEFAULT (' ') FOR [OrderNo]
ALTER TABLE [dbo].[TRANSACTIONS] ADD  CONSTRAINT [DF_TRANSACTIONS_Age]  DEFAULT (0) FOR [Age]
ALTER TABLE [dbo].[TRANSACTIONS] ADD  CONSTRAINT [DF_TRANSACTIONS_SubConTran]  DEFAULT (' ') FOR [SubConTran]
ALTER TABLE [dbo].[TRANSACTIONS] ADD  CONSTRAINT [DF_TRANSACTIONS_VATType]  DEFAULT ('Z') FOR [VATType]
ALTER TABLE [dbo].[TRANSACTIONS] ADD  CONSTRAINT [DF_TRANSACTIONS_HomeCurrAmount]  DEFAULT (0) FOR [HomeCurrAmount]
ALTER TABLE [dbo].[TRANSACTIONS] ADD  CONSTRAINT [DF_TRANSACTIONS_ConversionRate]  DEFAULT (1) FOR [ConversionRate]
ALTER TABLE [dbo].[TRANSACTIONS] ADD  CONSTRAINT [DF_TRANSACTIONS_PaidFor]  DEFAULT (0) FOR [PaidFor]
ALTER TABLE [dbo].[TRANSACTIONS] ADD  CONSTRAINT [DF_TRANSACTIONS_PaidToDate]  DEFAULT (0) FOR [PaidToDate]
ALTER TABLE [dbo].[TRANSACTIONS] ADD  CONSTRAINT [DF_TRANSACTIONS_PaidThisPeriod]  DEFAULT (0) FOR [PaidThisPeriod]
ALTER TABLE [dbo].[TRANSACTIONS] ADD  CONSTRAINT [DF_TRANSACTIONS_WhtThisPeriod]  DEFAULT (0) FOR [WhtThisPeriod]
ALTER TABLE [dbo].[TRANSACTIONS] ADD  CONSTRAINT [DF_TRANSACTIONS_DiscThisPeriod]  DEFAULT (0) FOR [DiscThisPeriod]
ALTER TABLE [dbo].[TRANSACTIONS] ADD  CONSTRAINT [DF_TRANSACTIONS_ReconStatus]  DEFAULT (0) FOR [ReconStatus]
ALTER TABLE [dbo].[TRANSACTIONS] ADD  CONSTRAINT [DF_TRANSACTIONS_UserID]  DEFAULT ('Admin') FOR [UserID]
ALTER TABLE [dbo].[TRANSACTIONS] ADD  CONSTRAINT [DF_TRANSACTIONS_DivID]  DEFAULT (3) FOR [DivID]
ALTER TABLE [dbo].[TRANSACTIONS] ADD  CONSTRAINT [DF_TRANSACTIONS_ForexVal]  DEFAULT (0) FOR [ForexVal]
ALTER TABLE [dbo].[TRANSACTIONS] ADD  DEFAULT ('') FOR [XGLCODE]
ALTER TABLE [dbo].[TRANSACTIONS] ADD  DEFAULT ((0.00)) FOR [XVATA]
ALTER TABLE [dbo].[TRANSACTIONS] ADD  DEFAULT ('Z') FOR [XVATT]
ALTER TABLE [dbo].[TRANSACTIONS] ADD  CONSTRAINT [DF_TRANSACTIONS_WHTID]  DEFAULT ((-1)) FOR [WHTID]
ALTER TABLE [dbo].[TRANSACTIONS] ADD  CONSTRAINT [DF_TRANSACTIONS_FBID]  DEFAULT ((-1)) FOR [FBID]
ALTER TABLE [dbo].[TRANSACTIONS] ADD  CONSTRAINT [DF_TRANSACTIONS_TERM]  DEFAULT ((0)) FOR [TERM]
ALTER TABLE [dbo].[TRANSACTIONS] ADD  CONSTRAINT [DF_TRANSACTIONS_SYSDATE]  DEFAULT (getdate()) FOR [SYSDATE]
ALTER TABLE [dbo].[TRANSACTIONS] ADD  CONSTRAINT [DF_TRANSACTIONS_CLASSID]  DEFAULT ((-1)) FOR [CLASSID]
ALTER TABLE [dbo].[TRANSACTIONS]  WITH CHECK ADD  CONSTRAINT [FK_TRANSACTIONS_ACTIVITIES] FOREIGN KEY([Activity])
REFERENCES [dbo].[ACTIVITIES] ([ActNumber])
ALTER TABLE [dbo].[TRANSACTIONS] CHECK CONSTRAINT [FK_TRANSACTIONS_ACTIVITIES]
ALTER TABLE [dbo].[TRANSACTIONS]  WITH CHECK ADD  CONSTRAINT [FK_TRANSACTIONS_BORGS] FOREIGN KEY([OrgID])
REFERENCES [dbo].[BORGS] ([BORGID])
ALTER TABLE [dbo].[TRANSACTIONS] CHECK CONSTRAINT [FK_TRANSACTIONS_BORGS]
ALTER TABLE [dbo].[TRANSACTIONS]  WITH CHECK ADD  CONSTRAINT [FK_TRANSACTIONS_CURRENCIES] FOREIGN KEY([Currency])
REFERENCES [dbo].[CURRENCIES] ([CURRCODE])
ALTER TABLE [dbo].[TRANSACTIONS] CHECK CONSTRAINT [FK_TRANSACTIONS_CURRENCIES]
ALTER TABLE [dbo].[TRANSACTIONS]  WITH CHECK ADD  CONSTRAINT [FK_TRANSACTIONS_LEDGERCODES] FOREIGN KEY([LedgerCode])
REFERENCES [dbo].[LEDGERCODES] ([LedgerCode])
ALTER TABLE [dbo].[TRANSACTIONS] CHECK CONSTRAINT [FK_TRANSACTIONS_LEDGERCODES]
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON

CREATE TRIGGER LOGMASTERTRANSACTIONS ON TRANSACTIONS
AFTER DELETE
AS 

SET NOCOUNT ON

declare @tableName varChar(25)
declare @primaryKey varChar(25)
declare @ignoreList varChar(500)

set @tableName = 'TRANSACTIONS'
set @primaryKey = 'TransID'
set @ignoreList = ''

declare @action varChar(25)
declare @logUserID int
declare @logDateTime datetime
declare @borgid int
declare @page varChar(100)
declare @info varChar(250)
declare @application varChar(3)
declare @version varChar(15)
declare @context_info int
declare @sqlTblCols nVarChar(max)
declare @sql nVarChar(max)

set @context_info = -1
set @ignoreList = ',' + replace(@ignoreList, ' ', '') + ','
set @action = ''
set @logUserID = -1
set @logDateTime = DATEADD(M, -1, getDate()) 
set @borgid = -1
set @page = ''
set @info = ''
set @application = ''
set @version = ''
set @sqlTblCols = ''
set @sql = ''

if exists(select * from INSERTED)
BEGIN
	set @action = 'UPDATE'
END
ELSE
BEGIN
	if exists(select * from DELETED)
	BEGIN
		set @action = 'DELETE'
	END
END
 
select * into #inserted from INSERTED
select * into #deleted from DELETED

SELECT @context_info = cast(replace(cast(CONTEXT_INFO as varchar(128)), char(0) COLLATE SQL_Latin1_General_CP1_CI_AS,'') as int) FROM master.dbo.sysprocesses WHERE spid = @@SPID

select @logUserID = isnull(USERID, -1),
@logDateTime = isnull(LOGDATETIME, DATEADD(M, -1, getDate())),
@borgid = isnull(BORGID, @borgid),
@page = isnull(PAGE, @page),
@info = isnull(INFO, @info),
@application  = isnull(APPLICATION, @application),
@version = isnull(VERSION, @version)
from logcontext 
where LOGID = @context_info
	
delete FROM LOGCONTEXT where LOGID = @context_info
   
if @action = 'UPDATE'
BEGIN		
	Select @sqlTblCols = @sqlTblCols + 'Case when rtrim(cast(IsNull(i.[' + Column_Name + '],0) as varChar(100)))=rtrim(cast(IsNull(d.[' + Column_Name + '],0) as varChar(100))) then '''' else ' + '''[' + Column_Name + ']:'' + rtrim(cast(IsNull(d.[' + Column_Name + '],0) as varChar(100)) collate SQL_LATIN1_GENERAL_CP1_CI_AS) + ''' + ' -> '' + rtrim(cast(IsNull(i.[' + Column_Name + '],0) as varChar(100)) collate SQL_LATIN1_GENERAL_CP1_CI_AS) + ''' + ''' + '', ''' + ' end +'
	from information_schema.columns 
	where TABLE_NAME = @tableName
	and PATINDEX('%,' + COLUMN_NAME + ',%', @ignoreList) = 0
	and DATA_TYPE not like '%text%'
	and DATA_TYPE not like '%image%'
	and DATA_TYPE not like '%binary%' 
		
	set @sqlTblCols = Substring(@sqlTblCols, 1 , len(@sqlTblCols) - 1)

	set @sql = 'select ''' + cast(@logUserID as varChar(10)) + ''', ''' + cast(@borgid as varChar(10)) + ''', ''' + @application + ''', ''' + @tableName + ''', ''' + @action + ''', ''' + @page + ''', ''' + @info + ''', ''' + @version + ''', '''+ @primaryKey +' = '' + cast(i.'+ @primaryKey +' as varChar(10)), Substring(' + @sqlTblCols + ', 1 , len(' + @sqlTblCols + ') - 1) '
	set @sql = @sql + 'From #inserted i inner join #deleted d on i.'+ @primaryKey +' = d.'+ @primaryKey +' where isnull(' + @sqlTblCols + ', '''') <> '''' ' 

	insert into LOGMASTER (USERID, BORGID, APPLICATION, TABLENAME, ACTION, PAGE, INFO, VERSION, PRIMARYKEY, DETAILS)
	exec sp_executesql @sql
END   

if @action = 'DELETE'
BEGIN
	Select @sqlTblCols = @sqlTblCols + '''[' + Column_Name + ']:'' + rtrim(cast(IsNull(d.[' + Column_Name + '],0) as varChar(100)) collate SQL_LATIN1_GENERAL_CP1_CI_AS) + '', '' + '
	from information_schema.columns 
	where TABLE_NAME = @tableName
	and PATINDEX('%,' + COLUMN_NAME + ',%', @ignoreList) = 0
	and DATA_TYPE not like '%text%'
	and DATA_TYPE not like '%image%'
	and DATA_TYPE not like '%binary%' 
		
	set @sqlTblCols = Substring(@sqlTblCols, 1, len(@sqlTblCols) - 5) + ''''
	
	set @sql = 'select ''' + cast(@logUserID as varChar(10)) + ''', ''' + cast(@borgid as varChar(10)) + ''', ''' + @application + ''', ''' + @tableName + ''', ''' + @action + ''', ''' + @page + ''', ''' + @info + ''', ''' + @version + ''', '''+ @primaryKey +' = '' + cast(d.'+ @primaryKey +' as varChar(10)), ' + @sqlTblCols + ' '
	set @sql = @sql + 'From #deleted d ' 
 
	insert into LOGMASTER (USERID, BORGID, APPLICATION, TABLENAME, ACTION, PAGE, INFO, VERSION, PRIMARYKEY, DETAILS)
	exec sp_executesql @sql
END

DROP TABLE #inserted
DROP TABLE #deleted

		
ALTER TABLE [dbo].[TRANSACTIONS] ENABLE TRIGGER [LOGMASTERTRANSACTIONS]
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON

CREATE TRIGGER TR_TRANSACTIONSSNAPSHOT ON TRANSACTIONS
AFTER UPDATE
AS 

SET NOCOUNT ON

insert into TRANSACTIONSSNAPSHOT (TRANSID, PAIDFOR, PAIDTODATE, PAIDTHISPERIOD, RECONSTATUS, SYSDATE)
SELECT D.TRANSID, D.PAIDFOR, D.PAIDTODATE, D.PAIDTHISPERIOD, D.RECONSTATUS, getDate()
FROM INSERTED I inner join DELETED D on I.TRANSID = D.TRANSID
WHERE I.PAIDFOR <> D.PAIDFOR
OR I.PAIDTODATE <> D.PAIDTODATE
OR I.PAIDTHISPERIOD <> D.PAIDTHISPERIOD
OR I.RECONSTATUS <> D.RECONSTATUS

		
ALTER TABLE [dbo].[TRANSACTIONS] ENABLE TRIGGER [TR_TRANSACTIONSSNAPSHOT]