/****** Object:  Table [dbo].[UDATABLES]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[UDATABLES](
	[TID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[TABLENAME] [nvarchar](255) NOT NULL,
	[COLKEY] [nvarchar](55) NOT NULL,
	[ALIAS] [nvarchar](255) NOT NULL,
	[EXCLUDE] [bit] NOT NULL,
	[Application] [char](3) NOT NULL,
 CONSTRAINT [PK_UDATABLES] PRIMARY KEY CLUSTERED 
(
	[TID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[UDATABLES] ADD  CONSTRAINT [DF_UDATABLES_TABLENAME]  DEFAULT ('') FOR [TABLENAME]
ALTER TABLE [dbo].[UDATABLES] ADD  CONSTRAINT [DF_UDATABLES_COLKEY]  DEFAULT ('') FOR [COLKEY]
ALTER TABLE [dbo].[UDATABLES] ADD  CONSTRAINT [DF_UDATABLES_ALIAS]  DEFAULT ('') FOR [ALIAS]
ALTER TABLE [dbo].[UDATABLES] ADD  CONSTRAINT [DF_UDATABLES_EXCLUDE]  DEFAULT ('0') FOR [EXCLUDE]
ALTER TABLE [dbo].[UDATABLES] ADD  CONSTRAINT [DF_UDATABLES_Application]  DEFAULT ('ACC') FOR [Application]