/****** Object:  Table [dbo].[UDATABLECOLUMNS]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[UDATABLECOLUMNS](
	[CID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[TID] [int] NOT NULL,
	[COLUMNNAME] [nvarchar](255) NOT NULL,
	[ALIAS] [nvarchar](255) NOT NULL,
	[EXCLUDE] [bit] NOT NULL,
	[LOOKUPTABLESQL] [nvarchar](4000) NOT NULL,
	[LOOKUPREQUIRED] [bit] NOT NULL,
 CONSTRAINT [PK_UDATABLECOLUMNS] PRIMARY KEY CLUSTERED 
(
	[CID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[UDATABLECOLUMNS] ADD  CONSTRAINT [DF_UDATABLECOLUMNS_TID]  DEFAULT ((-1)) FOR [TID]
ALTER TABLE [dbo].[UDATABLECOLUMNS] ADD  CONSTRAINT [DF_UDATABLECOLUMNS_COLUMNNAME]  DEFAULT ('') FOR [COLUMNNAME]
ALTER TABLE [dbo].[UDATABLECOLUMNS] ADD  CONSTRAINT [DF_UDATABLECOLUMNS_ALIAS]  DEFAULT ('') FOR [ALIAS]
ALTER TABLE [dbo].[UDATABLECOLUMNS] ADD  CONSTRAINT [DF_UDATABLECOLUMNS_EXCLUDE]  DEFAULT ('0') FOR [EXCLUDE]
ALTER TABLE [dbo].[UDATABLECOLUMNS] ADD  CONSTRAINT [DF_UDATABLECOLUMNS_LOOKUPTABLESQL]  DEFAULT ('') FOR [LOOKUPTABLESQL]
ALTER TABLE [dbo].[UDATABLECOLUMNS] ADD  CONSTRAINT [DF_UDATABLECOLUMNS_LOOKUPREQUIRED]  DEFAULT ('0') FOR [LOOKUPREQUIRED]