/****** Object:  Table [dbo].[UDIDATA]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[UDIDATA](
	[ID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[HID] [int] NOT NULL,
	[DATA] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_UDIDATA] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

ALTER TABLE [dbo].[UDIDATA] ADD  CONSTRAINT [DF_UDIDATA_HID]  DEFAULT ((-1)) FOR [HID]
ALTER TABLE [dbo].[UDIDATA] ADD  CONSTRAINT [DF_UDIDATA_DATA]  DEFAULT ('') FOR [DATA]