/****** Object:  Table [dbo].[UDIDATAHEADER]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[UDIDATAHEADER](
	[ID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[FILENAME] [nvarchar](255) NOT NULL,
	[AMDID] [int] NOT NULL,
	[TID] [int] NOT NULL,
	[SYSDATE] [datetime] NULL,
	[STATUS] [nvarchar](255) NOT NULL,
 CONSTRAINT [PK_UDIDATAHEADER] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[UDIDATAHEADER] ADD  CONSTRAINT [DF_UDIDATAHEADER_FILENAME]  DEFAULT ('') FOR [FILENAME]
ALTER TABLE [dbo].[UDIDATAHEADER] ADD  CONSTRAINT [DF_UDIDATAHEADER_AMDID]  DEFAULT ((-1)) FOR [AMDID]
ALTER TABLE [dbo].[UDIDATAHEADER] ADD  CONSTRAINT [DF_UDIDATAHEADER_TID]  DEFAULT ((-1)) FOR [TID]
ALTER TABLE [dbo].[UDIDATAHEADER] ADD  CONSTRAINT [DF_UDIDATAHEADER_SYSDATE]  DEFAULT (getdate()) FOR [SYSDATE]
ALTER TABLE [dbo].[UDIDATAHEADER] ADD  CONSTRAINT [DF_UDIDATAHEADER_STATUS]  DEFAULT ('') FOR [STATUS]