/****** Object:  Table [dbo].[UDITABLECOLUMNS]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[UDITABLECOLUMNS](
	[CID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[TID] [int] NOT NULL,
	[COLUMNNAME] [nvarchar](255) NOT NULL,
	[ALIAS] [nvarchar](255) NOT NULL,
	[EXCLUDE] [bit] NOT NULL,
	[VALS] [nvarchar](4000) NOT NULL,
	[COLTYPE] [nvarchar](55) NOT NULL,
	[COLSIZE] [nvarchar](55) NULL,
	[COLDEFAULT] [nvarchar](55) NULL,
	[CANUPDATE] [bit] NOT NULL,
	[ISUNIQUE] [bit] NOT NULL,
	[ISREQUIRED] [bit] NOT NULL,
	[SEQ] [int] NOT NULL,
	[INSERTPK] [bit] NOT NULL,
	[INFO] [nvarchar](max) NOT NULL,
	[ALTCODEVAL] [nvarchar](250) NOT NULL,
	[UPDATEONLY] [bit] NOT NULL,
 CONSTRAINT [PK_UDITABLECOLUMNS] PRIMARY KEY CLUSTERED 
(
	[CID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

ALTER TABLE [dbo].[UDITABLECOLUMNS] ADD  CONSTRAINT [DF_UDITABLECOLUMNS_TID]  DEFAULT ((-1)) FOR [TID]
ALTER TABLE [dbo].[UDITABLECOLUMNS] ADD  CONSTRAINT [DF_UDITABLECOLUMNS_COLUMNNAME]  DEFAULT ('') FOR [COLUMNNAME]
ALTER TABLE [dbo].[UDITABLECOLUMNS] ADD  CONSTRAINT [DF_UDITABLECOLUMNS_ALIAS]  DEFAULT ('') FOR [ALIAS]
ALTER TABLE [dbo].[UDITABLECOLUMNS] ADD  CONSTRAINT [DF_UDITABLECOLUMNS_EXCLUDE]  DEFAULT ('0') FOR [EXCLUDE]
ALTER TABLE [dbo].[UDITABLECOLUMNS] ADD  CONSTRAINT [DF_UDITABLECOLUMNS_VALS]  DEFAULT ('') FOR [VALS]
ALTER TABLE [dbo].[UDITABLECOLUMNS] ADD  CONSTRAINT [DF_UDITABLECOLUMNS_COLTYPE]  DEFAULT ('') FOR [COLTYPE]
ALTER TABLE [dbo].[UDITABLECOLUMNS] ADD  CONSTRAINT [DF_UDITABLECOLUMNS_COLSIZE]  DEFAULT ('') FOR [COLSIZE]
ALTER TABLE [dbo].[UDITABLECOLUMNS] ADD  CONSTRAINT [DF_UDITABLECOLUMNS_COLDEFAULT]  DEFAULT ('') FOR [COLDEFAULT]
ALTER TABLE [dbo].[UDITABLECOLUMNS] ADD  CONSTRAINT [DF_UDITABLECOLUMNS_CANUPDATE]  DEFAULT ('0') FOR [CANUPDATE]
ALTER TABLE [dbo].[UDITABLECOLUMNS] ADD  CONSTRAINT [DF_UDITABLECOLUMNS_ISUNIQUE]  DEFAULT ('0') FOR [ISUNIQUE]
ALTER TABLE [dbo].[UDITABLECOLUMNS] ADD  CONSTRAINT [DF_UDITABLECOLUMNS_ISREQUIRED]  DEFAULT ('0') FOR [ISREQUIRED]
ALTER TABLE [dbo].[UDITABLECOLUMNS] ADD  CONSTRAINT [DF_UDITABLECOLUMNS_SEQ]  DEFAULT ((-1)) FOR [SEQ]
ALTER TABLE [dbo].[UDITABLECOLUMNS] ADD  CONSTRAINT [DF_UDITABLECOLUMNS_INSERTPK]  DEFAULT (N'0') FOR [INSERTPK]
ALTER TABLE [dbo].[UDITABLECOLUMNS] ADD  CONSTRAINT [DF_UDITABLECOLUMNS_INFO]  DEFAULT ('') FOR [INFO]
ALTER TABLE [dbo].[UDITABLECOLUMNS] ADD  CONSTRAINT [DF_UDITABLECOLUMNS_ALTCODEVAL]  DEFAULT ('') FOR [ALTCODEVAL]
ALTER TABLE [dbo].[UDITABLECOLUMNS] ADD  CONSTRAINT [DF_UDITABLECOLUMNS_UPDATEONLY]  DEFAULT (N'0') FOR [UPDATEONLY]