/****** Object:  Table [dbo].[UDITABLECHECKS]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[UDITABLECHECKS](
	[CID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[TID] [int] NOT NULL,
	[SQL] [text] NOT NULL,
	[SEQ] [int] NOT NULL,
	[PRECHECK] [bit] NOT NULL,
 CONSTRAINT [PK_UDITABLECHECKS] PRIMARY KEY CLUSTERED 
(
	[CID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

ALTER TABLE [dbo].[UDITABLECHECKS] ADD  CONSTRAINT [DF_UDITABLECHECKS_TID]  DEFAULT ((-1)) FOR [TID]
ALTER TABLE [dbo].[UDITABLECHECKS] ADD  CONSTRAINT [DF_UDITABLECHECKS_SQL]  DEFAULT ('') FOR [SQL]
ALTER TABLE [dbo].[UDITABLECHECKS] ADD  CONSTRAINT [DF_UDITABLECHECKS_SEQ]  DEFAULT ((0)) FOR [SEQ]
ALTER TABLE [dbo].[UDITABLECHECKS] ADD  CONSTRAINT [DF_UDITABLECHECKS_PRECHECK]  DEFAULT ('0') FOR [PRECHECK]