/****** Object:  Table [dbo].[UDITABLES]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[UDITABLES](
	[TID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[TABLENAME] [nvarchar](255) NOT NULL,
	[COLKEY] [nvarchar](55) NOT NULL,
	[ALIAS] [nvarchar](255) NOT NULL,
	[EXCLUDE] [bit] NOT NULL,
	[HASHEADER] [nvarchar](255) NOT NULL,
	[DELIMITER] [nvarchar](10) NOT NULL,
	[HEADERTID] [int] NOT NULL,
	[CANUPDATE] [bit] NOT NULL,
	[EXCLUDEATTRIB] [bit] NOT NULL,
 CONSTRAINT [PK_UDITABLES] PRIMARY KEY CLUSTERED 
(
	[TID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[UDITABLES] ADD  CONSTRAINT [DF_UDITABLES_TABLENAME]  DEFAULT ('') FOR [TABLENAME]
ALTER TABLE [dbo].[UDITABLES] ADD  CONSTRAINT [DF_UDITABLES_COLKEY]  DEFAULT ('') FOR [COLKEY]
ALTER TABLE [dbo].[UDITABLES] ADD  CONSTRAINT [DF_UDITABLES_ALIAS]  DEFAULT ('') FOR [ALIAS]
ALTER TABLE [dbo].[UDITABLES] ADD  CONSTRAINT [DF_UDITABLES_EXCLUDE]  DEFAULT ('0') FOR [EXCLUDE]
ALTER TABLE [dbo].[UDITABLES] ADD  CONSTRAINT [DF_UDITABLES_HASHEADER]  DEFAULT ('') FOR [HASHEADER]
ALTER TABLE [dbo].[UDITABLES] ADD  CONSTRAINT [DF_UDITABLES_DELIMITER]  DEFAULT (N',') FOR [DELIMITER]
ALTER TABLE [dbo].[UDITABLES] ADD  CONSTRAINT [DF_UDITABLES_HEADERTID]  DEFAULT ((-1)) FOR [HEADERTID]
ALTER TABLE [dbo].[UDITABLES] ADD  CONSTRAINT [DF_UDITABLES_CANUPDATE]  DEFAULT (N'1') FOR [CANUPDATE]
ALTER TABLE [dbo].[UDITABLES] ADD  CONSTRAINT [DF_UDITABLES_EXCLUDEATTRIB]  DEFAULT (N'0') FOR [EXCLUDEATTRIB]