/****** Object:  Table [dbo].[UDRROLELINKS]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[UDRROLELINKS](
	[ID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[TID] [int] NOT NULL,
	[ROLEID] [int] NOT NULL,
 CONSTRAINT [PK_UDRROLELINKS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]