/****** Object:  Table [dbo].[UDRTABLEFILTERS]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[UDRTABLEFILTERS](
	[FID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[TID] [int] NOT NULL,
	[DESCR] [nvarchar](255) NOT NULL,
	[REQUIRED] [bit] NOT NULL,
	[EDITABLE] [bit] NOT NULL,
	[COLUMNNAME] [nvarchar](255) NOT NULL,
	[CONDITION] [nvarchar](10) NOT NULL,
	[DEFVAL] [nvarchar](255) NOT NULL,
 CONSTRAINT [PK_UDRTABLEFILTERS] PRIMARY KEY CLUSTERED 
(
	[FID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[UDRTABLEFILTERS] ADD  CONSTRAINT [DF_UDRTABLEFILTERS_TID]  DEFAULT ('-1') FOR [TID]
ALTER TABLE [dbo].[UDRTABLEFILTERS] ADD  CONSTRAINT [DF_UDRTABLEFILTERS_DESCR]  DEFAULT ('') FOR [DESCR]
ALTER TABLE [dbo].[UDRTABLEFILTERS] ADD  CONSTRAINT [DF_UDRTABLEFILTERS_REQUIRED]  DEFAULT ('0') FOR [REQUIRED]
ALTER TABLE [dbo].[UDRTABLEFILTERS] ADD  CONSTRAINT [DF_UDRTABLEFILTERS_EDITABLE]  DEFAULT ('0') FOR [EDITABLE]
ALTER TABLE [dbo].[UDRTABLEFILTERS] ADD  CONSTRAINT [DF_UDRTABLEFILTERS_COLUMNNAME]  DEFAULT ('') FOR [COLUMNNAME]
ALTER TABLE [dbo].[UDRTABLEFILTERS] ADD  CONSTRAINT [DF_UDRTABLEFILTERS_CONDITION]  DEFAULT ('') FOR [CONDITION]
ALTER TABLE [dbo].[UDRTABLEFILTERS] ADD  CONSTRAINT [DF_UDRTABLEFILTERS_DEFVAL]  DEFAULT ('') FOR [DEFVAL]