/****** Object:  Table [dbo].[UDRTABLES]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[UDRTABLES](
	[TID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[TABLENAME] [nvarchar](255) NOT NULL,
	[ALIAS] [nvarchar](255) NOT NULL,
	[EXCLUDE] [bit] NOT NULL,
	[EXPORTONLY] [bit] NOT NULL,
	[PRERUN] [nvarchar](255) NOT NULL,
	[POSTRUN] [nvarchar](255) NOT NULL,
	[APPLICATION] [nvarchar](3) NOT NULL,
 CONSTRAINT [PK_UDRTABLES] PRIMARY KEY CLUSTERED 
(
	[TID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[UDRTABLES] ADD  CONSTRAINT [DF_UDRTABLES_TABLENAME]  DEFAULT ('') FOR [TABLENAME]
ALTER TABLE [dbo].[UDRTABLES] ADD  CONSTRAINT [DF_UDRTABLES_ALIAS]  DEFAULT ('') FOR [ALIAS]
ALTER TABLE [dbo].[UDRTABLES] ADD  CONSTRAINT [DF_UDRTABLES_EXCLUDE]  DEFAULT ('0') FOR [EXCLUDE]
ALTER TABLE [dbo].[UDRTABLES] ADD  CONSTRAINT [DF_UDRTABLES_EXPORTONLY]  DEFAULT ('0') FOR [EXPORTONLY]
ALTER TABLE [dbo].[UDRTABLES] ADD  CONSTRAINT [DF_UDRTABLES_PRERUN]  DEFAULT ('') FOR [PRERUN]
ALTER TABLE [dbo].[UDRTABLES] ADD  CONSTRAINT [DF_UDRTABLES_POSTRUN]  DEFAULT ('') FOR [POSTRUN]
ALTER TABLE [dbo].[UDRTABLES] ADD  CONSTRAINT [DF_UDRTABLES_APPLICATION]  DEFAULT ('ACC') FOR [APPLICATION]