/****** Object:  Table [dbo].[USERSINEST]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[USERSINEST](
	[USERID] [int] NOT NULL,
	[ESTID] [int] NOT NULL,
	[roleID] [int] NOT NULL,
 CONSTRAINT [PK_USERSINEST] PRIMARY KEY CLUSTERED 
(
	[USERID] ASC,
	[ESTID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]