/****** Object:  Table [dbo].[users_backup]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[users_backup](
	[LOGINID] [char](15) NOT NULL,
	[PASSWORD] [char](150) NOT NULL,
	[USERNAME] [char](75) NULL,
	[STARTIN] [smallint] NOT NULL,
	[DEPARTMENT] [char](30) NULL,
	[TELEPHONE1] [char](30) NULL,
	[TELEPHONE2] [char](30) NULL,
	[TELEPHONE3] [char](30) NULL,
	[LOCATION] [char](50) NULL,
	[FAX1] [char](30) NULL,
	[EMAIL] [char](60) NULL,
	[VALIDFROM] [datetime] NOT NULL,
	[VALIDTO] [datetime] NOT NULL,
	[NEVEREXPIRES] [bit] NOT NULL,
	[ISADMIN] [int] NOT NULL,
	[LOCKED] [bit] NOT NULL,
	[FAX2] [char](30) NULL,
	[FAX3] [char](30) NULL,
	[USERID] [int] IDENTITY(1,1) NOT NULL,
	[ITEMSTOLIST] [int] NOT NULL,
	[HOMEORGID] [int] NOT NULL,
	[ERFQADMIN] [bit] NOT NULL,
	[FIRSTTIMELOGIN] [bit] NOT NULL,
	[EID] [char](10) NOT NULL,
	[LASTLOGIN] [datetime] NULL,
	[LASTTCPIP] [char](50) NULL,
	[ISSELAPPROVER] [bit] NOT NULL,
	[SCONRECAPP] [bit] NOT NULL,
	[DEBTRECAPP] [bit] NOT NULL,
	[INVAPP] [bit] NOT NULL,
	[ROLEIDA] [int] NOT NULL,
	[IsPlantAdmin] [bit] NOT NULL,
	[IsWorkshopAdmin] [bit] NOT NULL,
	[IsWSandPlantPosting] [bit] NOT NULL,
	[CanSeeDashboard] [bit] NOT NULL,
	[MasterAddEdit] [bit] NOT NULL,
	[HASERFQ] [bit] NOT NULL,
	[CANSEEDATABASEWARNING] [bit] NOT NULL,
	[REMCAPP] [bit] NOT NULL,
	[REMSAPP] [bit] NOT NULL,
	[BENEFICIARYEFTCAPTURE] [bit] NOT NULL,
	[REMCBAT] [bit] NOT NULL,
	[REMSBAT] [bit] NOT NULL,
	[ISBUYER] [bit] NOT NULL,
	[ALLOWIC] [bit] NOT NULL,
	[HASRPTLANG] [bit] NOT NULL,
	[VIEWNEWSFEED] [bit] NOT NULL,
	[IRECON] [int] NOT NULL,
	[USERPERC] [decimal](18, 4) NOT NULL,
	[OUTOFOFFICE] [bit] NOT NULL,
	[WORKFLOWESCALATION] [bit] NOT NULL,
	[PRLBATCHAPP] [bit] NOT NULL,
	[SUBCCLAIMEDIT] [bit] NOT NULL,
	[SUBCRECONBOQLINKSEDIT] [bit] NOT NULL,
	[SUBCRECONCONTRACTVALUEEDIT] [bit] NOT NULL,
	[POORDBY] [int] NOT NULL
) ON [PRIMARY]