/****** Object:  Table [dbo].[USERSUSAGE]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[USERSUSAGE](
	[USERID] [int] NOT NULL,
	[SYS] [nvarchar](3) NOT NULL,
	[THEYEAR] [int] NOT NULL,
	[THEMONTH] [int] NOT NULL,
	[LOGINCOUNTER] [int] NOT NULL,
	[FAILCOUNTER] [int] NOT NULL,
	[LOGOFFCOUNTER] [int] NOT NULL,
 CONSTRAINT [PK_USERSUSAGE] PRIMARY KEY CLUSTERED 
(
	[USERID] ASC,
	[SYS] ASC,
	[THEYEAR] ASC,
	[THEMONTH] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[USERSUSAGE] ADD  CONSTRAINT [DF_USERSUSAGE_USERID]  DEFAULT ((-1)) FOR [USERID]
ALTER TABLE [dbo].[USERSUSAGE] ADD  CONSTRAINT [DF_USERSUSAGE_SYS]  DEFAULT ('') FOR [SYS]
ALTER TABLE [dbo].[USERSUSAGE] ADD  CONSTRAINT [DF_USERSUSAGE_THEYEAR]  DEFAULT ((-1)) FOR [THEYEAR]
ALTER TABLE [dbo].[USERSUSAGE] ADD  CONSTRAINT [DF_USERSUSAGE_THEMONTH]  DEFAULT ((-1)) FOR [THEMONTH]
ALTER TABLE [dbo].[USERSUSAGE] ADD  CONSTRAINT [DF_USERSUSAGE_LOGINCOUNTER]  DEFAULT ((0)) FOR [LOGINCOUNTER]
ALTER TABLE [dbo].[USERSUSAGE] ADD  CONSTRAINT [DF_USERSUSAGE_FAILCOUNTER]  DEFAULT ((0)) FOR [FAILCOUNTER]
ALTER TABLE [dbo].[USERSUSAGE] ADD  CONSTRAINT [DF_USERSUSAGE_LOGOFFCOUNTER]  DEFAULT ((0)) FOR [LOGOFFCOUNTER]