/****** Object:  Table [dbo].[USERINVSTORES]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[USERINVSTORES](
	[USERID] [int] NOT NULL,
	[STORECODE] [nvarchar](15) NOT NULL,
	[INC] [bit] NOT NULL,
 CONSTRAINT [PK_USERINVSTORES] PRIMARY KEY CLUSTERED 
(
	[USERID] ASC,
	[STORECODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[USERINVSTORES] ADD  CONSTRAINT [DF_USERINVSTORES_USERID]  DEFAULT ((-1)) FOR [USERID]
ALTER TABLE [dbo].[USERINVSTORES] ADD  CONSTRAINT [DF_USERINVSTORES_STORECODE]  DEFAULT ('') FOR [STORECODE]
ALTER TABLE [dbo].[USERINVSTORES] ADD  CONSTRAINT [DF_USERINVSTORES_INC]  DEFAULT (N'1') FOR [INC]