/****** Object:  Table [dbo].[USERDEFAULTSDETAIL]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[USERDEFAULTSDETAIL](
	[DID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[HID] [int] NOT NULL,
	[KEY] [nvarchar](100) NOT NULL,
	[VALUE] [nvarchar](255) NOT NULL,
 CONSTRAINT [PK_USERDEFAULTSDETAIL] PRIMARY KEY CLUSTERED 
(
	[DID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[USERDEFAULTSDETAIL] ADD  CONSTRAINT [DF_USERDEFAULTSDETAIL_HID]  DEFAULT ((-1)) FOR [HID]
ALTER TABLE [dbo].[USERDEFAULTSDETAIL] ADD  CONSTRAINT [DF_USERDEFAULTSDETAIL_KEY]  DEFAULT ('') FOR [KEY]
ALTER TABLE [dbo].[USERDEFAULTSDETAIL] ADD  CONSTRAINT [DF_USERDEFAULTSDETAIL_VALUE]  DEFAULT ('') FOR [VALUE]