/****** Object:  Table [dbo].[USERDEFAULTSGRIDCONFIG]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[USERDEFAULTSGRIDCONFIG](
	[ID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[USERID] [int] NOT NULL,
	[ORGID] [int] NOT NULL,
	[PAGE] [nvarchar](100) NOT NULL,
	[NAME] [nvarchar](100) NOT NULL,
	[ISDEFAULT] [bit] NOT NULL,
	[APPLICATION] [nvarchar](3) NOT NULL,
	[CONFIGXML] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_USERDEFAULTSGRIDCONFIG] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

ALTER TABLE [dbo].[USERDEFAULTSGRIDCONFIG] ADD  CONSTRAINT [DF_USERDEFAULTSGRIDCONFIG_USERID]  DEFAULT ((-1)) FOR [USERID]
ALTER TABLE [dbo].[USERDEFAULTSGRIDCONFIG] ADD  CONSTRAINT [DF_USERDEFAULTSGRIDCONFIG_ORGID]  DEFAULT ((-1)) FOR [ORGID]
ALTER TABLE [dbo].[USERDEFAULTSGRIDCONFIG] ADD  CONSTRAINT [DF_USERDEFAULTSGRIDCONFIG_ISDEFAULT]  DEFAULT (N'0') FOR [ISDEFAULT]