/****** Object:  Table [dbo].[VATGROUPS]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[VATGROUPS](
	[VATGC] [nvarchar](3) NOT NULL,
	[SEQUENCE] [int] NOT NULL,
	[ISACCUM] [bit] NOT NULL,
	[LEDGERCODE] [nvarchar](10) NOT NULL,
	[NAME] [nvarchar](25) NOT NULL,
	[ISSURCHARGE] [bit] NOT NULL,
	[SURCHARGEAPPLIES] [bit] NOT NULL,
 CONSTRAINT [PK_VATGROUPS] PRIMARY KEY CLUSTERED 
(
	[VATGC] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[VATGROUPS] ADD  CONSTRAINT [DF_VATGROUPS_VATGC]  DEFAULT ('') FOR [VATGC]
ALTER TABLE [dbo].[VATGROUPS] ADD  CONSTRAINT [DF_VATGROUPS_SEQUENCE]  DEFAULT ((0)) FOR [SEQUENCE]
ALTER TABLE [dbo].[VATGROUPS] ADD  CONSTRAINT [DF_VATGROUPS_ISACCUM]  DEFAULT ((0)) FOR [ISACCUM]
ALTER TABLE [dbo].[VATGROUPS] ADD  CONSTRAINT [DF_VATGROUPS_LEDGERCODE]  DEFAULT ('') FOR [LEDGERCODE]
ALTER TABLE [dbo].[VATGROUPS] ADD  CONSTRAINT [DF_VATGROUPS_NAME]  DEFAULT ('') FOR [NAME]
ALTER TABLE [dbo].[VATGROUPS] ADD  CONSTRAINT [DF_VATGROUPS_ISSURCHARGE]  DEFAULT ((0)) FOR [ISSURCHARGE]
ALTER TABLE [dbo].[VATGROUPS] ADD  CONSTRAINT [DF_VATGROUPS_SURCHARGEAPPLIES]  DEFAULT ((0)) FOR [SURCHARGEAPPLIES]