/****** Object:  Table [dbo].[WHTTRANS]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[WHTTRANS](
	[TRANSID] [int] NOT NULL,
	[SOURCEAMOUNT] [money] NOT NULL,
	[SOURCEAMOUNTVAT] [money] NOT NULL,
 CONSTRAINT [PK_WHTTRANS] PRIMARY KEY CLUSTERED 
(
	[TRANSID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[WHTTRANS] ADD  CONSTRAINT [DF_WHTTRANS_TRANSID]  DEFAULT ((-1)) FOR [TRANSID]
ALTER TABLE [dbo].[WHTTRANS] ADD  CONSTRAINT [DF_WHTTRANS_SOURCEAMOUNT]  DEFAULT ((0)) FOR [SOURCEAMOUNT]
ALTER TABLE [dbo].[WHTTRANS] ADD  CONSTRAINT [DF_WHTTRANS_SOURCEAMOUNTVAT]  DEFAULT ((0)) FOR [SOURCEAMOUNTVAT]