/****** Object:  Table [dbo].[WORKFLOWHIST]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[WORKFLOWHIST](
	[WHID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[PROC] [nvarchar](10) NOT NULL,
	[THEID] [int] NOT NULL,
	[SEQ] [int] NOT NULL,
	[USERID] [int] NOT NULL,
	[DESCRIPTION] [nvarchar](250) NOT NULL,
	[THEDATE] [datetime] NULL,
	[WDID] [int] NOT NULL,
	[STATUSID] [int] NOT NULL,
	[WFVALUEAPPROVED] [bit] NOT NULL,
	[JUMPSEQ] [int] NOT NULL,
	[BRANCHID] [int] NOT NULL,
 CONSTRAINT [PK_WORKFLOWHIST] PRIMARY KEY CLUSTERED 
(
	[WHID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

CREATE NONCLUSTERED INDEX [IX_WORKFLOWHIST_THEID] ON [dbo].[WORKFLOWHIST]
(
	[THEID] ASC
)
INCLUDE([WDID]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
ALTER TABLE [dbo].[WORKFLOWHIST] ADD  CONSTRAINT [DF_WORKFLOWHIST_PROC]  DEFAULT ('') FOR [PROC]
ALTER TABLE [dbo].[WORKFLOWHIST] ADD  CONSTRAINT [DF_WORKFLOWHIST_THEID]  DEFAULT ((-1)) FOR [THEID]
ALTER TABLE [dbo].[WORKFLOWHIST] ADD  CONSTRAINT [DF_WORKFLOWHIST_SEQ]  DEFAULT ((-1)) FOR [SEQ]
ALTER TABLE [dbo].[WORKFLOWHIST] ADD  CONSTRAINT [DF_WORKFLOWHIST_USERID]  DEFAULT ((-1)) FOR [USERID]
ALTER TABLE [dbo].[WORKFLOWHIST] ADD  CONSTRAINT [DF_WORKFLOWHIST_DESCRIPTION]  DEFAULT ('') FOR [DESCRIPTION]
ALTER TABLE [dbo].[WORKFLOWHIST] ADD  CONSTRAINT [DF_WORKFLOWHIST_THEDATE]  DEFAULT (getdate()) FOR [THEDATE]
ALTER TABLE [dbo].[WORKFLOWHIST] ADD  CONSTRAINT [DF_WORKFLOWHIST_WDID]  DEFAULT ((-1)) FOR [WDID]
ALTER TABLE [dbo].[WORKFLOWHIST] ADD  CONSTRAINT [DF_WORKFLOWHIST_STATUSID]  DEFAULT ((-1)) FOR [STATUSID]
ALTER TABLE [dbo].[WORKFLOWHIST] ADD  CONSTRAINT [DF_WORKFLOWHIST_WFVALUEAPPROVED]  DEFAULT (N'0') FOR [WFVALUEAPPROVED]
ALTER TABLE [dbo].[WORKFLOWHIST] ADD  CONSTRAINT [DF_WORKFLOWHIST_JUMPSEQ]  DEFAULT ((-1)) FOR [JUMPSEQ]
ALTER TABLE [dbo].[WORKFLOWHIST] ADD  CONSTRAINT [DF_WORKFLOWHIST_BRANCHID]  DEFAULT ((-1)) FOR [BRANCHID]