/****** Object:  Table [dbo].[WORKFLOWSTATUS]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[WORKFLOWSTATUS](
	[WDID] [int] NOT NULL,
	[PROC] [nvarchar](5) NOT NULL,
	[THEID] [int] NOT NULL,
	[BRANCHID] [int] NOT NULL
) ON [PRIMARY]

ALTER TABLE [dbo].[WORKFLOWSTATUS] ADD  CONSTRAINT [DF_WORKFLOWSTATUS_PROC]  DEFAULT ('') FOR [PROC]
ALTER TABLE [dbo].[WORKFLOWSTATUS] ADD  CONSTRAINT [DF_WORKFLOWSTATUS_THEID]  DEFAULT ((-1)) FOR [THEID]
ALTER TABLE [dbo].[WORKFLOWSTATUS] ADD  CONSTRAINT [DF_WORKFLOWSTATUS_BRANCHID]  DEFAULT ((-1)) FOR [BRANCHID]