/****** Object:  Table [dbo].[WORKFLOWSKIPCONDITION]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[WORKFLOWSKIPCONDITION](
	[WDID] [int] NOT NULL,
	[LEV] [int] NOT NULL,
	[ALLOC] [nvarchar](15) NOT NULL,
	[THEID] [int] NOT NULL,
 CONSTRAINT [PK_WORKFLOWSKIPCONDITION] PRIMARY KEY CLUSTERED 
(
	[WDID] ASC,
	[ALLOC] ASC,
	[LEV] ASC,
	[THEID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[WORKFLOWSKIPCONDITION] ADD  CONSTRAINT [DF_WORKFLOWSKIPCONDITION_WDID]  DEFAULT ((-1)) FOR [WDID]
ALTER TABLE [dbo].[WORKFLOWSKIPCONDITION] ADD  CONSTRAINT [DF_WORKFLOWSKIPCONDITION_LEV]  DEFAULT ((-1)) FOR [LEV]
ALTER TABLE [dbo].[WORKFLOWSKIPCONDITION] ADD  CONSTRAINT [DF_WORKFLOWSKIPCONDITION_ALLOC]  DEFAULT ('') FOR [ALLOC]
ALTER TABLE [dbo].[WORKFLOWSKIPCONDITION] ADD  CONSTRAINT [DF_WORKFLOWSKIPCONDITION_THEID]  DEFAULT ((-1)) FOR [THEID]