/****** Object:  Procedure [BS].[AWAITINGAPPROVAL]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE [BS].[AWAITINGAPPROVAL]
AS

DECLARE @FILENAME VARCHAR(100)
DECLARE @FILEID   VARCHAR(10)
DECLARE @SQL      VARCHAR(250)
DECLARE @ORGID INT

SET @FILENAME = 'BSBS_TEMP.DBO.AWAITING'


SELECT R.REQNUMBER,R.REQSUBJECT,R.SUBMITIONDATE, R.CREATEDATE,R.SHORTDESCR,R.USERID,R.APPROVER,R.RECTYPE,R.BORGID,B.BORGNAME,U.USERNAME
INTO #TEMP0 
FROM REQ R INNER JOIN BORGS B ON R.BORGID = B.BORGID INNER JOIN USERS U ON R.APPROVER = U.USERID
WHERE R.REQSTATUSID=32 AND LEFT(REQNUMBER,3)<>'CSL'


SELECT @FILEID= CONVERT(INT,RAND( (DATEPART(mm, GETDATE()) * 100000 )
	+ (DATEPART(ss, GETDATE()) * 1000 )
	+ DATEPART(ms, GETDATE()) )*1000)

SET @FILENAME = @FILENAME+LTRIM(RTRIM(CONVERT(VARCHAR(3),@FILEID)))
SELECT @FILENAME 
SET @SQL = 'SELECT *  INTO '+@FILENAME+ ' FROM   #TEMP0   ORDER BY RECTYPE,USERNAME,BORGNAME,CREATEDATE DESC  '

EXEC(@SQL)

RETURN @FILEID