/****** Object:  Procedure [BS].[CHEQUEPRINTING]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE [BS].[CHEQUEPRINTING] 
(@BORGID INT,
 @FINYEAR INT,
 @LOGINID VARCHAR(15),
 @CHEQUEAMOUNT DECIMAL(18,2),
 @CHEQUEDATE VARCHAR(15),
 @BANKLEDGER VARCHAR(10),
 @CHEQUENUMBER VARCHAR(25),
 @LEDGERCODE VARCHAR(10),
 @NARRATION VARCHAR(100),
 @DESCRIPTION VARCHAR(255),
 @CURRENCY VARCHAR(10),
 @PARTYCODE VARCHAR(10),
 @INTERCOMPANY INT,
 @WHTAMOUNT DECIMAL(18,2),
 @WHTINDEX INT
)
  
AS

IF @LEDGERCODE NOT IN ('1315000','1320000','2540000') 
   SET @PARTYCODE = SPACE(20)

DECLARE @FILENAME VARCHAR(100)
DECLARE @FILEID   VARCHAR(10)
DECLARE @SQL      VARCHAR(250)

DECLARE @SAVED INT
DECLARE @USERLOGIN INT 
SELECT @USERLOGIN = USERID FROM USERS WHERE LOGINID = @LOGINID
SET @SAVED=0

SET @FILENAME = 'BSBS_TEMP.DBO.PAYMENTVOUCHER'

  
CREATE TABLE #TEMP0
(
 INDEXCODE INT , 
 FINYEAR CHAR(10),
 ORGID  INT,
 PERIOD INT,
 PDATE DATETIME,
 BATCHREF CHAR(10),
 TRANSREF CHAR(15),
 TRANSTYPE CHAR(10),
 LEDGERCODE CHAR(10),
 LEDGERNAME CHAR(100),
 CONTRACT CHAR(10),
 CONTRNAME CHAR(100),
 DESCRIPTION VARCHAR(255),
 CURRENCY VARCHAR(3),
 DEBIT DECIMAL(18,2),
 CREDIT DECIMAL(18,2),
 CREDNO VARCHAR(10),
 PARTY VARCHAR(100),
 SUBCONTRN CHAR(20),
 USERID CHAR(60),
 DOCNUMBER NCHAR(50),
 CREDITOR  VARCHAR(100),
 BATCHTRANS VARCHAR(20),
 MATCHREF INT,
 SUPPLIERBILL VARCHAR(100),
 MATERIALTYPE VARCHAR(100),
 WHTINDEX  INT,
 WHTAMOUNT DECIMAL(18,2),
 ORDERNUMBER VARCHAR(10),
 INTERCOMPANY INT,
 TYPENAME VARCHAR(10),
 BORGNAME VARCHAR(100),
 TRANSACTIONDATE DATETIME,
 TRANSTYPELEDGER  VARCHAR(10),
 RECEIVEORG VARCHAR(250),
 WHTNAME VARCHAR(100) ,
 INWORDS VARCHAR(200)
)
 

 INSERT INTO #TEMP0 VALUES (1,@FINYEAR,@BORGID,0,CONVERT(DATETIME,@CHEQUEDATE,103),SPACE(10),@CHEQUENUMBER,SPACE(10),@LEDGERCODE,[BS].[fnGetLedgerName](@LEDGERCODE),
 SPACE(10),SPACE(10),@DESCRIPTION,@CURRENCY,@CHEQUEAMOUNT,0,@PARTYCODE, [BS].[fnGetParty](@PARTYCODE) ,SPACE(10),
 SPACE(10),SPACE(10),[BS].[fnGetLedgerName](@BANKLEDGER),SPACE(10),SPACE(10),SPACE(100),
 SPACE(10),@WHTINDEX,@WHTAMOUNT ,SPACE(10),@INTERCOMPANY,'Bank',SPACE(100),GETDATE(), @BANKLEDGER, SPACE(250),SPACE(10),SPACE(200) )

   
 UPDATE #TEMP0 SET RECEIVEORG = BORGS.BORGNAME FROM BORGS INNER JOIN #TEMP0 ON #TEMP0.INTERCOMPANY=BORGS.BORGID 
 UPDATE #TEMP0 SET BORGNAME = BORGS.BORGNAME FROM BORGS INNER JOIN #TEMP0 ON #TEMP0.ORGID = BORGS.BORGID


 ALTER TABLE #TEMP0 ADD BOOKINGORG VARCHAR(200)
 UPDATE #TEMP0 SET BOOKINGORG = BORGS.BORGNAME FROM BORGS INNER JOIN #TEMP0 ON #TEMP0.ORGID=BORGS.BORGID 

 UPDATE #TEMP0 SET WHTNAME = TAXWHT.DESCRIPTION FROM TAXWHT INNER JOIN #TEMP0 ON #TEMP0.WHTINDEX-1 = TAXWHT.WHTID

  CREATE TABLE #TEMPADD(ID INT,ADDRESS VARCHAR(100))
  DECLARE @BORGNEWS VARCHAR(4000)
  SELECT @BORGNEWS = BORGNEWS FROM BORGS WHERE BORGID=@BORGID
  INSERT INTO #TEMPADD
  SELECT * FROM  [dbo].[SplitString](@BORGNEWS,'|') 
 
 ALTER TABLE #TEMP0 ADD TITLE1 VARCHAR(100)
 ALTER TABLE #TEMP0 ADD TITLE2 VARCHAR(100)
 ALTER TABLE #TEMP0 ADD TITLE3 VARCHAR(100)
 ALTER TABLE #TEMP0 ADD TITLE4 VARCHAR(100)
 ALTER TABLE #TEMP0 ADD TITLE5 VARCHAR(100)
 
 DECLARE @SITEADDRESS VARCHAR(100)
 SET @SITEADDRESS=''
 SELECT @SITEADDRESS = ADDRESS FROM #TEMPADD WHERE ID=1   
 UPDATE #TEMP0 SET TITLE1 = @SITEADDRESS
 SET @SITEADDRESS=''
 SELECT @SITEADDRESS = ADDRESS FROM #TEMPADD WHERE ID=2   
 UPDATE #TEMP0 SET TITLE2 = @SITEADDRESS
 SET @SITEADDRESS=''
 SELECT @SITEADDRESS = ADDRESS FROM #TEMPADD WHERE ID=3   
 UPDATE #TEMP0 SET TITLE3= @SITEADDRESS
 SET @SITEADDRESS=''
 SELECT @SITEADDRESS = ADDRESS FROM #TEMPADD WHERE ID=4  
 UPDATE #TEMP0 SET TITLE4 = @SITEADDRESS
 SET @SITEADDRESS=''
 SELECT @SITEADDRESS = ADDRESS FROM #TEMPADD WHERE ID=5  
 UPDATE #TEMP0 SET TITLE5 = @SITEADDRESS
 
 DECLARE @NETPAYABLE DECIMAL(18,2)
 SELECT @NETPAYABLE = (DEBIT-CREDIT-WHTAMOUNT) FROM #TEMP0 
  

 DECLARE @INWORDS VARCHAR(200)
 SELECT @INWORDS=DBO.FN_SPELLNUMBER(@NETPAYABLE, 'UK',0) 
  
 DECLARE @USERNAME VARCHAR(60)
 SELECT @USERNAME = USERNAME FROM USERS WHERE LOGINID = @LOGINID 
 UPDATE #TEMP0 SET USERID = @USERNAME

 UPDATE #TEMP0 SET INWORDS = 'Amount In Words '+ LTRIM(RTRIM(@INWORDS))   

--SELECT @FILEID= CONVERT(INT,RAND( (DATEPART(mm, GETDATE()) * 100000 )
--+ (DATEPART(ss, GETDATE()) * 1000 )
--+ DATEPART(ms, GETDATE()) )*1000)

--SET @FILENAME = @FILENAME+LTRIM(RTRIM(CONVERT(VARCHAR(3),@FILEID)))
--SELECT * FROM #TEMP0 

-- Before the Final Save verifying whether this transaction has been saved into the Transactions Table

--SELECT @SAVED= COUNT(*)
--FROM TRANSACTIONS 
--WHERE 
--  ORGID = @BORGID AND 
--  YEAR=@FINYEAR AND
--  PDATE = CONVERT(DATETIME,@CHEQUEDATE,103) AND
--  LEFT(TRANSTYPE,3)= 'CBC'  AND
--  TRANSREF = @CHEQUENUMBER AND
--  LEDGERCODE = @BANKLEDGER AND
--  CREDIT= @CHEQUEAMOUNT AND
--  CREDNO= @PARTYCODE AND
--  USERID = @USERLOGIN 

--  INSERT INTO VRTESTING VALUES(@BORGID,@FINYEAR,CONVERT(DATETIME,@CHEQUEDATE,103),'CBC',@BANKLEDGER,@CHEQUEAMOUNT,@PARTYCODE,@USERLOGIN,@CHEQUENUMBER,GETDATE()) 

     DECLARE @Random INT;
	 DECLARE @Upper INT;
	 DECLARE @Lower INT
 
	 SET @Lower = 1 ---- The lowest random number
	 SET @Upper = 99999 ---- The highest random number
	 SELECT @Random = ROUND(((@Upper - @Lower -1) * RAND() + @Lower), 0)

	 SELECT @FILEID= CONVERT(INT,RAND( (DATEPART(mm, GETDATE()) * 100000 )
		+ (DATEPART(ss, GETDATE()) * 1000 )
		+ DATEPART(ms, GETDATE()) )*1000) + STR(@RANDOM) 

	 SET @FILENAME = @FILENAME+LTRIM(RTRIM(CONVERT(VARCHAR(6),@FILEID)))
	 SET @SQL = 'SELECT *  INTO '+@FILENAME+ ' FROM   #TEMP0  ORDER BY PDATE  '

	 EXEC(@SQL)

	 RETURN @FILEID
     --   SET @SQL = 'SELECT *  INTO '+@FILENAME+ ' FROM   #TEMP1  ORDER BY SUPPLIERNAME,ORGID  '
	 --   EXEC(@SQL)
	 --   SELECT @FILENAME 
     --   RETURN @FILEID 
--IF @SAVED=0 
--  -- DELETE FROM #TEMP0 