/****** Object:  Procedure [BS].[CHEQUEPREPARE_BATCH]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE [BS].[CHEQUEPREPARE_BATCH](@CHEQUEDAY CHAR(2),@CHEQUEMONTH CHAR(2),@CHEQUEYEAR CHAR(4),@BATCHNO INT,@BORGID INT,@FINYEAR INT )
AS 

DECLARE @CREDNO VARCHAR(10) 
DECLARE @AMOUNT DECIMAL(18,2)
DECLARE @COUNTS INT 
DECLARE @PARTY INT 
SET @PARTY = 0
SET @COUNTS=0
SELECT @COUNTS=ISNULL( COUNT(*) ,0) FROM CREDITORS WHERE CREDNUMBER=@CREDNO 
IF @COUNTS >0 
   SET @PARTY = 1

IF @COUNTS=0 
 BEGIN
   SELECT @COUNTS = ISNULL( COUNT(*) ,0 ) FROM SUBCONTRACTORS WHERE SUBNUMBER = @CREDNO 
   IF @COUNTS >0 
      SET @PARTY= 2
 END 

IF @PARTY = 1
   SELECT @CREDNO=CREDNO,@AMOUNT=PAYAMOUNT FROM PAYMENTS WHERE BATCHNO=@BATCHNO AND ORGID=@BORGID AND PAYTYPE='C'
ELSE
   SELECT @CREDNO=CREDNO,@AMOUNT=PAYAMOUNT FROM PAYMENTS WHERE BATCHNO=@BATCHNO AND ORGID=@BORGID AND PAYTYPE='S'

IF EXISTS (select * from dbo.sysobjects where id = object_id(N'[dbo].[CHEQUESR]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)   drop table [dbo].[CHEQUESR] 

CREATE TABLE [dbo].[CHEQUESR] (  
	 [BorgID] [int] NOT NULL ,  
	 [CREDNO] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,  
     [CREDNAME] [char] (155) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,  
     [AMNT] [money] NOT NULL ,  
     [DISC] [money] NOT NULL,  
     [CHEQUEDATE]   DATETIME , 
     [CHEQUEAMOUNT] VARCHAR(250),     
     [CHEQUEDAY]    CHAR(2) ,
	 [CHEQUEMONTH]  CHAR(2),
	 [CHEQUEYEAR]   CHAR(4) ) ON [PRIMARY]  



 

 
 

INSERT INTO [CHEQUESR] VALUES (@BORGID , @CREDNO ,[BS].[fnGetParty](@CREDNO) , @AMOUNT , 0 , GETDATE(), dbo.fn_spellNumber(@AMOUNT,'UK',0), @CHEQUEDAY , @CHEQUEMONTH, @CHEQUEYEAR )

select * from CHEQUESR   