/****** Object:  Procedure [BS].[CONSOLIDATE_UNRECON_DELIVERIES]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE [BS].[CONSOLIDATE_UNRECON_DELIVERIES]
AS

DECLARE @FILENAME VARCHAR(100)
DECLARE @FILEID   VARCHAR(10)
DECLARE @SQL      VARCHAR(250)
DECLARE @ORGID INT

SET @FILENAME = 'BSBS_TEMP.DBO.CONUNRECONDELIVERY'
    
	 
SELECT 
   D.TBORGID,
   B.BORGNAME,
   D.ORDID,
   O.ORDNUMBER,
   O.SUPPID,
   S.SUPPCODE,
   S.SUPPNAME,
   O.CREATEDATE ORDDATE,
   OI.LINENUMBER,
   OI.BUYERPARTNUMBER,
   OI.ITEMDESCRIPTION,
   OI.UOM,
   D.GRNNO,
   D.DLVRDATE GRNDATE,
   D.DLVRNO,
   D.DLVRQTY,
   D.RECONQTY,
   D.PRICE
INTO #TEMP0 
FROM 
   DELIVERIES D INNER JOIN    ORD   O  ON D.ORDID = O.ORDID 
                INNER JOIN    BORGS B  ON D.TBORGID = B.BORGID 
				INNER JOIN ORDITEMS OI ON O.ORDID = OI.ORDID AND D.ORDITEMLINENO=OI.LINENUMBER
				INNER JOIN SUPPLIERS S ON O.SUPPID = S.SUPPID 
WHERE
   D.DLVRQTY <> D.RECONQTY AND LEFT(B.BORGNAME,1)='9'

UPDATE #TEMP0  SET DLVRQTY = ( DLVRQTY-RECONQTY )

SELECT @FILEID= CONVERT(INT,RAND( (DATEPART(mm, GETDATE()) * 100000 )
	+ (DATEPART(ss, GETDATE()) * 1000 )
	+ DATEPART(ms, GETDATE()) )*1000)

SET @FILENAME = @FILENAME+LTRIM(RTRIM(CONVERT(VARCHAR(3),@FILEID)))
SELECT @FILENAME 
SET @SQL = 'SELECT *  INTO '+@FILENAME+ ' FROM   #TEMP0   ORDER BY TBORGID,SUPPNAME,ORDDATE DESC '

EXEC(@SQL)

RETURN @FILEID