/****** Object:  Procedure [BS].[CORRECTASSETS]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE  PROCEDURE [BS].[CORRECTASSETS] 
AS

DECLARE @ASSETBOOKVALUE DECIMAL(18,2)
DECLARE @ASSETACCUMDEP DECIMAL(18,2)
DECLARE @ASSETDEP DECIMAL(18,2)
DECLARE @ASSETDEPPROG DECIMAL(18,2) 
DECLARE @ASSETNUMBER VARCHAR(15)
DECLARE @MONTHLY DECIMAL(18,2) 
DECLARE @ASSETID INT 
 
DECLARE ASSETS CURSOR FOR
SELECT ASSETID,ASSETNUMBER,ASSETBOOKVALUE,ASSETACCUMDEP,ASSETDEP,ASSETDEPPROG,[LASTDEPTM]  FROM [VRASSETFIXING]  
 
OPEN ASSETS 
FETCH NEXT FROM ASSETS INTO @ASSETID,@ASSETNUMBER,@ASSETBOOKVALUE,@ASSETACCUMDEP,@ASSETDEP,@ASSETDEPPROG,@MONTHLY

WHILE @@FETCH_STATUS = 0
BEGIN
   
   UPDATE ASSETS SET AssetBookValue = @ASSETBOOKVALUE,
                     AssetAccumDep = @ASSETACCUMDEP,
					 ASSETPOST=1, ASSETDEP=@ASSETDEP,
					 ASSETDEPPROG= @ASSETDEPPROG,
					 ASSETLASTPOSTDATE  = '30-JUNE-2016',
					 LASTDEPTM = @MONTHLY
					 WHERE ASSETID = @ASSETID 
   FETCH NEXT FROM ASSETS INTO @ASSETID,@ASSETNUMBER,@ASSETBOOKVALUE,@ASSETACCUMDEP,@ASSETDEP,@ASSETDEPPROG,@MONTHLY

END

CLOSE ASSETS
DEALLOCATE ASSETS 
 