/****** Object:  Procedure [BS].[CREDITOR_TRANSACTIONS_ORGWISE]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE [BS].[CREDITOR_TRANSACTIONS_ORGWISE]( @STARTDATESTRING AS VARCHAR(15),@ENDDATESTRING AS VARCHAR(15),@CREDNO VARCHAR(10))
AS
    DECLARE @CREDITORCONTROL VARCHAR(10)
    SELECT @CREDITORCONTROL = CONTROLFROMGL FROM CONTROLCODES WHERE CONTROLNAME='Creditors'
   
    DECLARE @FILENAME VARCHAR(100)
	DECLARE @FILEID   VARCHAR(10)
	DECLARE @SQL      VARCHAR(250)
 

	SET @FILENAME = 'BSBS_TEMP.DBO.CREDITOR_MOVEMENT'
    DECLARE @FINYEAR INT
	DECLARE @TRANSSTARTDATE    DATETIME
	DECLARE @TRANSENDDATE      DATETIME
    SELECT  @TRANSSTARTDATE = CONVERT(DATETIME, @STARTDATESTRING,103) -- dd/mm/yyyy 
	SELECT  @TRANSENDDATE   = CONVERT(DATETIME, @ENDDATESTRING,103) -- dd/mm/yyyy 

	IF MONTH(@TRANSSTARTDATE) IN (1,2,3)
		SET @FINYEAR = YEAR(@TRANSSTARTDATE)
	ELSE
		SET @FINYEAR = YEAR(@TRANSSTARTDATE)+1
  
   DECLARE @BORGID INT
   DECLARE @KEYS INT
   DECLARE @ORDERNUMBER VARCHAR(25)
   DECLARE @ORDID INT
   DECLARE @ALLOCATION VARCHAR(20) 
   DECLARE @FIRSTSTOCKID INT
   DECLARE @STORENAME   VARCHAR(15) 
   DECLARE @CONTRACTNO  VARCHAR(10)
   DECLARE @CONTRACT    VARCHAR(125)
   SELECT @CREDNO 

   CREATE TABLE #TEMP0
   (
   KEYS  INT IDENTITY(1,1),
   INDEXCODE    INT,
   PERIOD		INT,
   BATCHREF		VARCHAR(10),
   TRANSREF		VARCHAR(10),
   TRANSTYPE	VARCHAR(10),
   PDATE		DATETIME,
   DESCRIPTION	VARCHAR(250),
   DEBIT		DECIMAL(18,2),
   CREDIT		DECIMAL(18,2),
   CREDNO		VARCHAR(10),
   CREDITORNAME VARCHAR(100),
   DOCUNUMBER	VARCHAR(25),
   USERID		VARCHAR(10),
   ORDERNUMBER  VARCHAR(100),
   TRANGRP      INT,
   ORGID        INT,
   PROJECT      VARCHAR(150),
   SHORTDESCRIPTION VARCHAR(150),
   BANKNAME     VARCHAR(30)
   )
   DELETE FROM #TEMP0
   DECLARE ORGLIST CURSOR FOR 
   SELECT DISTINCT BORGID FROM BORGS 

   OPEN ORGLIST 
   FETCH NEXT FROM ORGLIST INTO @BORGID 
     
     WHILE @@FETCH_STATUS = 0 
       BEGIN 
          INSERT INTO #TEMP0
		   SELECT 
			2,
			T.PERIOD,
			T.BATCHREF,
			T.TRANSREF,
			T.TRANSTYPE,
			T.PDATE,
			T.DESCRIPTION,
			T.DEBIT,
			T.CREDIT,
			T.CREDNO,
			SPACE(100),
			T.DOCNUMBER,
			T.USERID,
			T.ORDERNO ,
			T.TRANGRP ,
			@BORGID,
			SPACE(150),
			SPACE(150),
			SPACE(150)
		  FROM
			TRANSACTIONS T
		  WHERE
			LEDGERCODE = @CREDITORCONTROL AND 
			ORGID = @BORGID  AND 
			T.PDATE >=@TRANSSTARTDATE AND T.PDATE<=@TRANSENDDATE AND 
			YEAR=@FINYEAR AND 
			T.CREDNO =@CREDNO

  
		  DECLARE STORES CURSOR FOR
		  SELECT KEYS, ORDERNUMBER FROM #TEMP0 WHERE TRANSTYPE='DEL' 
		  OPEN STORES
		  FETCH NEXT FROM STORES INTO @KEYS, @ORDERNUMBER 
		  WHILE @@FETCH_STATUS = 0
		  BEGIN
			 SELECT @ORDID=ORDID FROM ORD WHERE ORDNUMBER = @ORDERNUMBER
			 SELECT @ALLOCATION = LTRIM(RTRIM(ALLOCATION)) FROM ORDITEMS WHERE ORDID=@ORDID
			 SET @CONTRACT = SPACE(25) 
			 IF @ALLOCATION ='Balance Sheet'   
			   BEGIN
				  SELECT TOP 1  @FIRSTSTOCKID = STOCKID FROM ORDITEMS WHERE ORDID = @ORDID 
				  SELECT @STORENAME = STKSTORE  FROM INVENTORY WHERE STKID = @FIRSTSTOCKID 
				  SELECT @CONTRACTNO = STORECONTNUMBER FROM INVSTORES WHERE STORECODE = @STORENAME 
				  SELECT @CONTRACT = CONTRNAME FROM CONTRACTS WHERE CONTRNUMBER=@CONTRACTNO 
				  UPDATE #TEMP0 SET  PROJECT = @CONTRACT WHERE KEYS = @KEYS
				  UPDATE #TEMP0 SET  SHORTDESCRIPTION = R.SHORTDESCR  FROM REQ R INNER JOIN ORD ON 
				  ORD.REQID = R.REQID AND ORD.ORDID = @ORDID WHERE KEYS = @KEYS 
			   END
     
			 IF @ALLOCATION ='Contracts'   
			   BEGIN
	  			  SELECT @CONTRACTNO = CONTRACTID  FROM ORDITEMS WHERE ORDID = @ORDID 
				  SELECT @CONTRACT = CONTRNAME FROM CONTRACTS WHERE contrid=@CONTRACTNO 
				  UPDATE #TEMP0 SET  PROJECT = @CONTRACT WHERE KEYS = @KEYS
				  UPDATE #TEMP0 SET  SHORTDESCRIPTION = R.SHORTDESCR  FROM REQ R INNER JOIN ORD ON 
				  ORD.REQID = R.REQID AND ORD.ORDID = @ORDID WHERE KEYS=@KEYS
			   END
			 FETCH NEXT FROM STORES INTO @KEYS, @ORDERNUMBER 

		  END 
		  CLOSE STORES
		  DEALLOCATE STORES 
  

          INSERT INTO #TEMP0 (INDEXCODE,DESCRIPTION,DEBIT,CREDIT,CREDNO,ORGID ) 
		  SELECT 
			1,
			'Opening Balance',
			SUM(DEBIT) ,
			SUM(CREDIT) ,
			@CREDNO ,
			@BORGID 
		  FROM 
			TRANSACTIONS 
		  WHERE  
			 LEDGERCODE = @CREDITORCONTROL AND ORGID = @BORGID  AND PDATE <@TRANSSTARTDATE  AND YEAR= @FINYEAR AND CREDNO = @CREDNO 
		  HAVING 
			 ( SUM(DEBIT)>0 OR SUM(CREDIT)>0 ) 
  
	FETCH NEXT FROM ORGLIST INTO @BORGID 
END
CLOSE ORGLIST
DEALLOCATE ORGLIST 

SELECT DISTINCT ORGID,PROJECT INTO #PROJECT FROM #TEMP0 WHERE PROJECT <>''
UPDATE #TEMP0 SET PROJECT = P.PROJECT FROM #PROJECT P INNER JOIN #TEMP0 ON #TEMP0.ORGID=P.ORGID  

 

  ALTER TABLE #TEMP0 ADD ADDRESS1 VARCHAR(100)
  ALTER TABLE #TEMP0 ADD ADDRESS2 VARCHAR(100) 
  ALTER TABLE #TEMP0 ADD ADDRESS3 VARCHAR(100)
  ALTER TABLE #TEMP0 ADD PIN      VARCHAR(10)

  UPDATE #TEMP0 SET CREDITORNAME = CR.CREDNAME FROM CREDITORS CR INNER JOIN #TEMP0 ON #TEMP0.CREDNO=CR.CredNumber 
  UPDATE #TEMP0 SET ADDRESS1 = CR.CredAddress1 FROM CREDITORS CR INNER JOIN #TEMP0 ON #TEMP0.CREDNO=CR.CredNumber 
  UPDATE #TEMP0 SET ADDRESS2 = CR.CredAddress2 FROM CREDITORS CR INNER JOIN #TEMP0 ON #TEMP0.CREDNO=CR.CredNumber 
  UPDATE #TEMP0 SET ADDRESS3 = CR.CredAddress3 FROM CREDITORS CR INNER JOIN #TEMP0 ON #TEMP0.CREDNO=CR.CredNumber 
  UPDATE #TEMP0 SET PIN      = CR.CredPCode    FROM CREDITORS CR INNER JOIN #TEMP0 ON #TEMP0.CREDNO=CR.CredNumber 

  ALTER TABLE #TEMP0 ADD  BORGNAME VARCHAR(100) 
  UPDATE #TEMP0 SET BORGNAME = (SELECT BORGNAME FROM BORGS WHERE BORGID=@BORGID)
  ALTER TABLE #TEMP0 ADD FROMPERIOD VARCHAR(20)
  ALTER TABLE #TEMP0 ADD TOPERIOD   VARCHAR(20)
  UPDATE #TEMP0 SET FROMPERIOD = @STARTDATESTRING
  UPDATE #TEMP0 SET TOPERIOD =   @ENDDATESTRING

  ALTER TABLE #TEMP0 ADD FINYEAR CHAR(4)
  UPDATE #TEMP0 SET FINYEAR=@FINYEAR



  ALTER TABLE #TEMP0 ADD CREDITORCONTROL VARCHAR(10)
  UPDATE #TEMP0 SET CREDITORCONTROL = @CREDITORCONTROL
  UPDATE #TEMP0 SET PDATE=@TRANSSTARTDATE WHERE INDEXCODE=1 

  ALTER TABLE #TEMP0 ADD MONTHNAMES VARCHAR(20)
  ALTER TABLE #TEMP0 ADD MONTHID    INT
  UPDATE #TEMP0 SET MONTHNAMES = datename(month, PDATE)
  UPDATE #TEMP0 SET MONTHID = PM.PERIODID FROM PERIODMASTER PM INNER JOIN #TEMP0 ON #TEMP0.MONTHNAMES = PM.PERIODDESC 
 -- UPDATE #TEMP0 SET MONTHID    = DATEPART(MONTH, PDATE)
 
  SELECT T.TRANGRP,R.LEDGERCODE INTO #TEMP88 FROM #TEMP0 T INNER JOIN TRANSACTIONS R  ON T.TRANGRP=R.TRANGRP 
         WHERE T.TRANGRP>0 AND R.LEDGERCODE IN (SELECT BANKLEDGER FROM BANKS) 
  ALTER TABLE #TEMP88 ADD BANKNAME VARCHAR(50)
  
  UPDATE #TEMP88 SET BANKNAME =BANKS.BANKNAME FROM BANKS INNER JOIN #TEMP88 ON #TEMP88.LEDGERCODE = BANKS.BANKLEDGER
  UPDATE #TEMP0 SET BANKNAME = #TEMP88.BANKNAME FROM #TEMP88 INNER JOIN #TEMP0 ON #TEMP0.TRANGRP = #TEMP88.TRANGRP  WHERE  LEFT(#TEMP0.BATCHREF,3)='CBC'
 
    
  SELECT @FILEID= CONVERT(INT,RAND( (DATEPART(mm, GETDATE()) * 100000 )
	+ (DATEPART(ss, GETDATE()) * 1000 )
	+ DATEPART(ms, GETDATE()) )*1000)

  SET @FILENAME = @FILENAME+LTRIM(RTRIM(CONVERT(VARCHAR(3),@FILEID)))
  SELECT @FILENAME 
  SET @SQL = 'SELECT *  INTO '+@FILENAME+ ' FROM   #TEMP0   ORDER BY CREDNO,INDEXCODE,PERIOD,PDATE '

  EXEC(@SQL)

  RETURN @FILEID
 