/****** Object:  Procedure [BS].[CREDITOR_REGISTER]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE [BS].[CREDITOR_REGISTER](@BORGID INT, @STARTDATESTRING AS VARCHAR(15),@ENDDATESTRING AS VARCHAR(15))
AS
    DECLARE @CREDITORCONTROL VARCHAR(10)
    SELECT @CREDITORCONTROL = CONTROLFROMGL FROM CONTROLCODES WHERE CONTROLNAME='Creditors'
 

    DECLARE @FINYEAR      INT
	DECLARE @TRANSSTARTDATE    DATETIME
	DECLARE @TRANSENDDATE      DATETIME
    SELECT  @TRANSSTARTDATE = CONVERT(DATETIME, @STARTDATESTRING,103) -- dd/mm/yyyy 
	SELECT  @TRANSENDDATE   = CONVERT(DATETIME, @ENDDATESTRING,103) -- dd/mm/yyyy 

	IF MONTH(@TRANSSTARTDATE) IN (1,2,3)
		SET @FINYEAR = YEAR(@TRANSSTARTDATE)
	ELSE
		SET @FINYEAR = YEAR(@TRANSSTARTDATE)+1

   SELECT @TRANSSTARTDATE,@TRANSENDDATE

   CREATE TABLE #TEMP0
   (
   KEYS  INT IDENTITY(1,1),
   CREDNO		  VARCHAR(10),
   CREDNAME       VARCHAR(250),
   CATEGORY       VARCHAR(25),
   OPENINGBALANCE DECIMAL(18,2),
   DEBIT		  DECIMAL(18,2),
   CREDIT		  DECIMAL(18,2),
   CLOSINGBALANCE DECIMAL(18,2)
   )

   INSERT INTO #TEMP0(CREDNO,CREDNAME,CATEGORY)
   SELECT CREDNUMBER,CREDNAME,CREDSELECT  FROM CREDITORS 

   SELECT * FROM #TEMP0 

   SELECT
    CREDNO,
	SUM(DEBIT-CREDIT) AS OPBAL 
   INTO #TEMP1
   FROM 
    TRANSACTIONS 
   WHERE
    YEAR = @FINYEAR AND
	LEDGERCODE = @CREDITORCONTROL AND
	ORGID = @BORGID AND 
	PDATE  < @TRANSSTARTDATE
   GROUP BY 
    CREDNO 

	 

   UPDATE #TEMP0 SET OPENINGBALANCE = T.OPBAL FROM #TEMP1 T INNER JOIN #TEMP0 ON #TEMP0.CREDNO=T.CREDNO 

	
   SELECT
    CREDNO,
	SUM(DEBIT) AS DEBIT,
	SUM(CREDIT) AS CREDIT 
   INTO #TEMP2
   FROM 
    TRANSACTIONS 
   WHERE
    YEAR = @FINYEAR AND
	LEDGERCODE = @CREDITORCONTROL AND
	ORGID = @BORGID AND 
	PDATE >= @TRANSSTARTDATE AND PDATE <= @TRANSENDDATE
   GROUP BY 
    CREDNO 
 


   UPDATE #TEMP0 SET DEBIT = T.DEBIT, CREDIT=T.CREDIT FROM #TEMP2 T INNER JOIN #TEMP0 ON #TEMP0.CREDNO = T.CREDNO 
 
   UPDATE #TEMP0 SET OPENINGBALANCE =0 WHERE OPENINGBALANCE IS NULL
   UPDATE #TEMP0 SET DEBIT = 0 WHERE DEBIT IS NULL
   UPDATE #TEMP0 SET CREDIT = 0 WHERE CREDIT IS NULL

   DELETE FROM #TEMP0 WHERE OPENINGBALANCE = 0 AND DEBIT=0 AND CREDIT = 0

   UPDATE #TEMP0 SET CLOSINGBALANCE = OPENINGBALANCE + DEBIT - CREDIT 

   ALTER TABLE #TEMP0 ADD  BORGNAME VARCHAR(100) 
   UPDATE #TEMP0 SET BORGNAME = (SELECT BORGNAME FROM BORGS WHERE BORGID=@BORGID)
   ALTER TABLE #TEMP0 ADD FROMPERIOD VARCHAR(20)
   ALTER TABLE #TEMP0 ADD TOPERIOD   VARCHAR(20)
   UPDATE #TEMP0 SET FROMPERIOD = @STARTDATESTRING
   UPDATE #TEMP0 SET TOPERIOD =   @ENDDATESTRING

   ALTER TABLE #TEMP0 ADD FINYEAR CHAR(4)
   UPDATE #TEMP0 SET FINYEAR=@FINYEAR

   ALTER TABLE #TEMP0 ADD BORGID INT
   UPDATE #TEMP0 SET BORGID= @BORGID

   ALTER TABLE #TEMP0 ADD CREDITORCONTROL VARCHAR(10)
   UPDATE #TEMP0 SET CREDITORCONTROL = @CREDITORCONTROL
   IF OBJECT_ID ('BSBS_TEMP.DBO.CREDITOR_REGISTER','U') IS NOT NULL
      DROP TABLE BSBS_TEMP.DBO.CREDITOR_REGISTER 
  
   SELECT * INTO BSBS_TEMP.DBO.CREDITOR_REGISTER FROM #TEMP0 ORDER BY CREDNO 

   SELECT * FROM  BSBS_TEMP.DBO.CREDITOR_REGISTER