/****** Object:  Procedure [BS].[DEBTORREGISTER]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE BS.DEBTORREGISTER( @FINYEAR INT,@STARTDATESTRING VARCHAR(15),@ENDDATESTRING VARCHAR(15),@ORGID INT,@ZONEID INT ) 
AS
    DECLARE @FILENAME VARCHAR(100)
	DECLARE @FILEID   VARCHAR(10)
	DECLARE @SQL      VARCHAR(250)
	DECLARE @WIP      VARCHAR(10)

	SELECT @WIP = CONTROLFROMGL FROM CONTROLCODES WHERE CONTROLNAME='Work In Progress'
 
	DECLARE @STARTDATE     DATETIME
	DECLARE @ENDDATE       DATETIME
	SELECT @STARTDATE = CONVERT(DATETIME, @STARTDATESTRING,103) -- dd/mm/yyyy 
	SELECT @ENDDATE   = CONVERT(DATETIME, @ENDDATESTRING,103) -- dd/mm/yyyy 
	SET @FILENAME = 'BSBS_TEMP.DBO.DRT' 

 
    CREATE TABLE #BORGS(BORGID INT) 
    IF @ZONEID <> 0 
	    INSERT INTO #BORGS 
	    SELECT BORGID FROM BORGS WHERE PARENTBORG = @ZONEID 
	ELSE
	    INSERT INTO #BORGS(BORGID) VALUES (@ORGID) 

	SELECT T.ORGID,T.YEAR,T.PERIOD,T.BATCHREF,T.TRANGRP,T.PDATE,T.TRANSID,
	       T.TRANSREF,T.LEDGERCODE,T.ACTIVITY,T.DESCRIPTION,T.DEBIT,
		   T.CREDIT,T.CREDNO,UPPER(D.DEBTNAME) DEBTNAME,B.BORGNAME,UPPER(L.LEDGERNAME) LEDGERNAME ,
		   T.ALLOCATION,A.ACTNAME,AR.REMARK 
	INTO #TEMP1
    FROM TRANSACTIONS T INNER JOIN BORGS B ON T.ORGID = B.BORGID 
    INNER JOIN LEDGERCODES L ON L.LEDGERCODE=T.LEDGERCODE  
    INNER JOIN DEBTORS D ON D.DEBTNUMBER = T.CREDNO 
	INNER JOIN ACTIVITIES A ON T.Activity = A.ActNumber
	INNER JOIN DEBTRECONS_ARCHIEVE AR ON T.TRANGRP=AR.TRANGRP 
	WHERE LEFT(BATCHREF,3)='DTI'  AND T.LEDGERCODE<>@WIP AND
	T.ORGID IN (SELECT BORGID FROM #BORGS) AND
	T.YEAR = @FINYEAR 
	ORDER BY ORGID,TRANGRP,TRANSID 


	DECLARE @Random INT;
	DECLARE @Upper INT;
	DECLARE @Lower INT
 
	SET @Lower = 1 ---- The lowest random number
	SET @Upper = 999 ---- The highest random number
	SELECT @Random = ROUND(((@Upper - @Lower -1) * RAND() + @Lower), 0)

	SELECT @FILEID= CONVERT(INT,RAND( (DATEPART(mm, GETDATE()) * 100000 )
	+ (DATEPART(ss, GETDATE()) * 1000 )
	+ DATEPART(ms, GETDATE()) )*1000) + STR(@RANDOM) 

	SET @FILENAME = @FILENAME+LTRIM(RTRIM(CONVERT(VARCHAR(6),@FILEID)))
    SET @SQL = 'SELECT *  INTO '+@FILENAME+ ' FROM   #TEMP1  ORDER BY ORGID,DEBTNAME,TRANGRP,ALLOCATION,LEDGERCODE DESC   '
	EXEC(@SQL)
	SELECT @FILENAME 
    RETURN @FILEID