/****** Object:  Procedure [BS].[FIX_MATERIAL_MASTER]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE  PROCEDURE [BS].[FIX_MATERIAL_MASTER]
AS
BEGIN
 DECLARE VMAINSTORE CURSOR FOR
 SELECT STKCODE FROM INVENTORY WHERE STKSTORE='VMAINSTORE' AND BORGID=2  

 DECLARE @STOCKNAME VARCHAR(250)
 DECLARE @STKUNIT VARCHAR(8)
 DECLARE @STKGLCODE VARCHAR(10)
 DECLARE @STKSTATUS VARCHAR(10)
 DECLARE @MASTERCODE VARCHAR(20)

 OPEN VMAINSTORE 
 FETCH NEXT FROM VMAINSTORE INTO @MASTERCODE 

 WHILE @@FETCH_STATUS = 0
 BEGIN
    SELECT @STOCKNAME = STKDESC,@STKUNIT = STKUNIT,@STKGLCODE=STKGLCODE ,@STKSTATUS= STKSTATUS 
	FROM INVENTORY WHERE STKCODE=@MASTERCODE AND STKSTORE='VMAINSTORE' AND BORGID=2 
	UPDATE INVENTORY SET STKDESC = @STOCKNAME,STKUNIT=@STKUNIT,STKGLCODE=@STKGLCODE  ,STKSTATUS=@STKSTATUS 
	WHERE STKCODE=@MASTERCODE AND STKSTORE<>'VMAINSTORE' AND BORGID<>2 AND
	LEFT(STKSTORE,4)<>'MS-5'  AND STKSTORE<>'VMAINCSL'   
 
	FETCH NEXT FROM VMAINSTORE INTO @MASTERCODE 
 END

 UPDATE INVENTORY SET STKBUYUNIT=STKUNIT , STKSELLUNIT = STKUNIT 
 UPDATE INVENTORY SET STKDEFGL = STKGLCODE
  
 CLOSE VMAINSTORE 
 DEALLOCATE VMAINSTORE 
END