/****** Object:  Procedure [BS].[FIXWHT]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE [BS].[FIXWHT]
AS
BEGIN
  --UPDATE TRANSACTIONS SET LEDGERCODE='1320000' ,SUBCONTRAN='Advance'  WHERE  LEDGERCODE = '1320003'  
  UPDATE TRANSACTIONS SET HEADID=0 WHERE HEADID IS NULL 
  UPDATE TRANSACTIONS SET WHTTHISPERIOD=0  WHERE LEFT(TRANSTYPE,3) IN ('CBC','PCP') AND LEDGERCODE='1320000' AND WHTTHISPERIOD<0 
  DECLARE @TRANSGRP INT
  DECLARE @TRANSTYPES VARCHAR(3) 
  DECLARE @LEDGERTOMAKEZERO INT
  DECLARE @EXCHANGEDEBITCREDIT INT
  DECLARE @EXCHANGEAMOUNT DECIMAL(18,2)
  DECLARE @BANKORCASH INT
  DECLARE @TDSAMOUNT DECIMAL(18,2)
  DECLARE @CONTROLFROMGL VARCHAR(10)
  DECLARE @COUNTS INT
  DECLARE @LINECOUNT INT
  DECLARE @BORGID INT 
  DECLARE @STCOUNT INT
  DECLARE @CONTROLTOGL VARCHAR(10) 
  SELECT  @CONTROLFROMGL= CONTROLFROMGL,@CONTROLTOGL = CONTROLTOGL FROM CONTROLCODES WHERE CONTROLNAME='Bank' 
  SELECT LEDGERCODE INTO  #BANKS  FROM LEDGERCODES   WHERE LEDGERCODE BETWEEN @CONTROLFROMGL   AND  @CONTROLTOGL

  DECLARE TRANGRP  CURSOR FOR
  SELECT DISTINCT TRANGRP,ORGID  FROM  
  TRANSACTIONS WHERE LEDGERCODE='1310005' AND LEFT(TRANSTYPE,3) IN ( 'CBC', 'PCP') AND DEBIT>0 AND YEAR>=2019  AND PERIOD<>0 AND   HEADID<>1   


 
  
  OPEN TRANGRP 
  FETCH NEXT FROM TRANGRP INTO @TRANSGRP,@BORGID 

  WHILE @@FETCH_STATUS = 0
  BEGIN
    SET @STCOUNT = 0
	SET @COUNTS=0
	SET @LINECOUNT=0
    SELECT @COUNTS = COUNT(*) FROM TRANSACTIONS WHERE TRANGRP= @TRANSGRP AND LEDGERCODE IN ('1315000', '1320000') AND ORGID=@BORGID 
    SELECT @LINECOUNT = COUNT(*) FROM TRANSACTIONS WHERE TRANGRP= @TRANSGRP AND ORGID=@BORGID 
    SELECT @STCOUNT = COUNT(*) FROM TRANSACTIONS WHERE TRANGRP= @TRANSGRP AND LEDGERCODE = '1310002' AND ORGID=@BORGID 
	IF (@COUNTS >= 1 )  AND (  ((@LINECOUNT=3) or  (@LINECOUNT=4) or ( (@LINECOUNT=5) AND @STCOUNT=1) ) )
	BEGIN 

	    SELECT @EXCHANGEDEBITCREDIT = TRANSID , @TDSAMOUNT=DEBIT ,@EXCHANGEAMOUNT = DEBIT  FROM TRANSACTIONS
	    WHERE LEDGERCODE='1310005' AND SUBCONTRAN = 'WITHHOLDING TAX'  AND  TRANGRP = @TRANSGRP    
		   
		
		SELECT @LEDGERTOMAKEZERO=TRANSID  
	    FROM TRANSACTIONS WHERE LEDGERCODE IN ('1320000','1315000') AND ForeignDescription LIKE ' WithHolding Tax%'  AND  TRANGRP = @TRANSGRP    
		AND CREDIT=@TDSAMOUNT 
	  
	   
	    
		SELECT TOP 1 @TRANSTYPES = LEFT(TRANSTYPE,3) FROM TRANSACTIONS WHERE TRANGRP = @TRANSGRP 


	 
		SELECT @BANKORCASH = TRANSID  FROM TRANSACTIONS
				   WHERE LEDGERCODE IN (SELECT LEDGERCODE  FROM #BANKS)    AND       TRANGRP = @TRANSGRP       
		
	
		--SELECT  'TRANGRP ' ,   @TRANSGRP 	                                                             
		--SELECT  ' LEDGER TO ZERO' ,  @LEDGERTOMAKEZERO
		--SELECT  ' EXCHANGE DEBIT TO CREDIT '  , @EXCHANGEDEBITCREDIT   
		--SELECT  ' TDS AMOUNT '  , @TDSAMOUNT 
		--SELECT  ' BANK TRANSID  ' ,  @BANKORCASH 

		UPDATE TRANSACTIONS SET DEBIT=0,CREDIT=0 WHERE TRANSID = @LEDGERTOMAKEZERO
		UPDATE TRANSACTIONS SET DEBIT=0,CREDIT=@EXCHANGEAMOUNT WHERE TRANSID = @EXCHANGEDEBITCREDIT 
		UPDATE TRANSACTIONS SET CREDIT=CREDIT-@TDSAMOUNT WHERE TRANSID = @BANKORCASH
		UPDATE TRANSACTIONS SET HEADID=1 WHERE TRANGRP=@TRANSGRP  
    END 
	                                                                                                                                                                
	FETCH NEXT FROM TRANGRP INTO @TRANSGRP,@BORGID 
  END

  CLOSE TRANGRP
  DEALLOCATE TRANGRP 


  DECLARE TRANGRP  CURSOR FOR
  SELECT DISTINCT TRANGRP,ORGID  FROM  
  TRANSACTIONS WHERE LEDGERCODE='1310005' AND LEFT(TRANSTYPE,3) IN ( 'CBD', 'PCR') AND CREDIT>0 AND YEAR>=2018  AND PERIOD<>0 AND   HEADID<>1   


 
  
  OPEN TRANGRP 
  FETCH NEXT FROM TRANGRP INTO @TRANSGRP,@BORGID 

  WHILE @@FETCH_STATUS = 0
  BEGIN
    SET @STCOUNT = 0
	SET @COUNTS=0
	SET @LINECOUNT=0
    SELECT @COUNTS = COUNT(*) FROM TRANSACTIONS WHERE TRANGRP= @TRANSGRP AND LEDGERCODE IN ('1315000', '1320000') AND ORGID=@BORGID 
    SELECT @LINECOUNT = COUNT(*) FROM TRANSACTIONS WHERE TRANGRP= @TRANSGRP AND ORGID=@BORGID 
    SELECT @STCOUNT = COUNT(*) FROM TRANSACTIONS WHERE TRANGRP= @TRANSGRP AND LEDGERCODE = '1310002' AND ORGID=@BORGID 
	IF (@COUNTS >= 1 )  AND (  ((@LINECOUNT=3) or  (@LINECOUNT=4) or ( (@LINECOUNT=5) AND @STCOUNT=1) ) )
	BEGIN 

	    SELECT @EXCHANGEDEBITCREDIT = TRANSID , @TDSAMOUNT=CREDIT ,@EXCHANGEAMOUNT = CREDIT  FROM TRANSACTIONS
	    WHERE LEDGERCODE='1310005' AND SUBCONTRAN = 'WITHHOLDING TAX'  AND  TRANGRP = @TRANSGRP    
		   
		
		SELECT @LEDGERTOMAKEZERO=TRANSID  
	    FROM TRANSACTIONS WHERE LEDGERCODE IN ('1320000','1315000') AND ForeignDescription LIKE ' WithHolding Tax%'  AND  TRANGRP = @TRANSGRP    
		AND DEBIT=@TDSAMOUNT 
	  
	   
	    
		SELECT TOP 1 @TRANSTYPES = LEFT(TRANSTYPE,3) FROM TRANSACTIONS WHERE TRANGRP = @TRANSGRP 


	 
		SELECT @BANKORCASH = TRANSID  FROM TRANSACTIONS
				   WHERE LEDGERCODE IN (SELECT LEDGERCODE  FROM #BANKS)    AND       TRANGRP = @TRANSGRP       
		
	
		--SELECT  'TRANGRP ' ,   @TRANSGRP 	                                                             
		--SELECT  ' LEDGER TO ZERO' ,  @LEDGERTOMAKEZERO
		--SELECT  ' EXCHANGE DEBIT TO CREDIT '  , @EXCHANGEDEBITCREDIT   
		--SELECT  ' TDS AMOUNT '  , @TDSAMOUNT 
		--SELECT  ' BANK TRANSID  ' ,  @BANKORCASH 

		UPDATE TRANSACTIONS SET DEBIT=0,CREDIT=0 WHERE TRANSID = @LEDGERTOMAKEZERO
		UPDATE TRANSACTIONS SET CREDIT=0,DEBIT=@EXCHANGEAMOUNT WHERE TRANSID = @EXCHANGEDEBITCREDIT 
		UPDATE TRANSACTIONS SET DEBIT=DEBIT-@TDSAMOUNT WHERE TRANSID = @BANKORCASH
		UPDATE TRANSACTIONS SET HEADID=1 WHERE TRANGRP=@TRANSGRP  
    END 
	                                                                                                                                                                
	FETCH NEXT FROM TRANGRP INTO @TRANSGRP,@BORGID 
  END

  CLOSE TRANGRP
  DEALLOCATE TRANGRP 


END