/****** Object:  Procedure [BS].[PAIDFORCHECKING1608]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE BS.PAIDFORCHECKING1608
AS
DELETE FROM BS.PAIDFORCHECKING
SELECT ORGID,CREDNO,SUM(DEBIT-CREDIT) NETAMOUNT 
INTO #TEMP0 
FROM TRANSACTIONS 
WHERE LEDGERCODE='1315000' 
AND YEAR=2020 
AND PAIDFOR=1 
GROUP BY ORGID,CREDNO 

INSERT INTO  BS.PAIDFORCHECKING
SELECT ORGID,CREDNO,NETAMOUNT 
FROM #TEMP0 WHERE NETAMOUNT<>0

SELECT * FROM BS.PAIDFORCHECKING