/****** Object:  Procedure [BS].[POSTDEPRECIATION]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE [BS].[POSTDEPRECIATION](@FINYEAR INT,@PERIODID INT)
AS

-- TWO FIELDS ARE USING FOR STORING LAST DEPRECIATION YEAR AND DEPRECIATION PERIOD 
-- ASSETTAXDEPTYPE,ASSETOIRATE
--  ASSETTAXDEPTYPE = DEPRECIATION = YEAR & ASSETOIRATE - LAST PERIOD 


SELECT GETDATE()

UPDATE ASSETS SET ASSETNUMBER=LTRIM(RTRIM(ASSETNUMBER)) 
--UPDATE ASSETS SET AssetPost=0,ASSETDEPPROG=0,ASSETBOOKVALUE=ASSETPPRICE,LASTDEPTM=(ASSETPPRICE-ASSETSALVAGE)/ASSETDEPTM ,AssetAccumDep=0          WHERE AssetPDate>='01-APR-2016' 
DECLARE @ASSETPOSTDATE DATETIME
DECLARE @ASSETDEPCODE VARCHAR(10)
DECLARE @ASSETOPPCODE VARCHAR(10)
DECLARE @LASTDEPTM DECIMAL(18,2)
DECLARE @ASSETNUMBER VARCHAR(15)
DECLARE @LASTDENUMBER INT
DECLARE @ASSETID INT 

DECLARE @BORGID INT 
SET @BORGID= 2

DECLARE @TRANGRP INT

SELECT @ASSETPOSTDATE = PEDATE FROM PERIODSETUP WHERE ORGID=2 AND PERIOD=@PERIODID  AND YEAR=@FINYEAR 
SELECT @TRANGRP = MAX(TRANGRP) FROM TRANSACTIONS 

UPDATE ASSETS SET ASSETPOST=1 , ASSETFINPOST=1
 
--UPDATE ASSETS SET ASSETPOST = 0 , ASSETFINPOST = 0 WHERE 
-- ASSETBOOKVALUE > ASSETACCUMDEP AND ASSETPPRICE > 0 AND ASSETPDATE <= @ASSETPOSTDATE 
-- AND ASSETNUMBER NOT IN (SELECT DISTINCT PLANTNO FROM ASSETPOSTS WHERE PERIOD=@PERIODID )

--UPDATE ASSETS SET ASSETPOST = 0 , ASSETFINPOST = 0  WHERE 
-- ASSETBOOKVALUE < ASSETACCUMDEP AND ASSETPPRICE < 0 AND ASSETPDATE <= @ASSETPOSTDATE
-- AND ASSETNUMBER NOT IN (SELECT DISTINCT PLANTNO FROM ASSETPOSTS WHERE PERIOD=@PERIODID )

UPDATE ASSETS SET ASSETPOST=0
WHERE ASSETOPPCODE= '2200006' AND 
      ASSETPDATE <= @ASSETPOSTDATE  AND 
	  ASSETNUMBER NOT IN (SELECT DISTINCT PLANTNO FROM ASSETPOSTS WHERE PERIOD=@PERIODID) 

SELECT * FROM ASSETS WHERE ASSETPOST=0

 



 
DECLARE @MAXIMUMNUMBER INT
DECLARE @CURRENTNUMBER INT
 
 
DECLARE ASSETS CURSOR FOR
SELECT ASSETID , ASSETNUMBER   FROM ASSETS WHERE ASSETPOST=0 AND ASSETNUMBER NOT IN (SELECT DISTINCT PLANTNO FROM ASSETPOSTS WHERE PERIOD=@PERIODID )

OPEN ASSETS 
FETCH NEXT FROM ASSETS INTO @ASSETID , @ASSETNUMBER 

WHILE @@FETCH_STATUS = 0
BEGIN
   SELECT @ASSETDEPCODE=ASSETDEPCODE,@ASSETOPPCODE=ASSETOPPCODE, @LASTDEPTM = LASTDEPTM, @LASTDENUMBER = ASSETDEPPROG  FROM ASSETS WHERE ASSETID = @ASSETID 
   SET @TRANGRP = @TRANGRP + 1
   SET @LASTDENUMBER = @LASTDENUMBER + 1 

  BEGIN TRAN
   INSERT INTO [ASSETPOSTS] VALUES (@BORGID,@FINYEAR,@PERIODID,@ASSETPOSTDATE,'FED2270520','DEP',0,'FED','Overheads'    ,@ASSETDEPCODE, ' ',' ',  'Fixed Asset Depreciation Posting','  ' ,'INR',@LASTDEPTM,0,  0,0,SPACE(10),SPACE(10),@ASSETNUMBER    ,SPACE(10),0,SPACE(10),0.0,SPACE(10),SPACE(10),0,SPACE(10),'Z',NULL,NULL,0,0,0,0,0,0,0,'227',2,0.0,NULL,SPACE(10),0.0,'Z',NULL,-1,-1,0,GETDATE(),NULL,NULL,NULL,@TRANGRP,NULL)
   INSERT INTO [ASSETPOSTS] VALUES (@BORGID,@FINYEAR,@PERIODID,@ASSETPOSTDATE,'FED2270520','DEP',0,'FED','Balance Sheet',@ASSETOPPCODE, ' ',' ',  'Fixed Asset Depreciation Posting','  ' ,'INR',0,@LASTDEPTM,  0,0,SPACE(10),SPACE(10),@ASSETNUMBER    ,SPACE(10),0,SPACE(10),0.0,SPACE(10),SPACE(10),0,SPACE(10),'Z',NULL,NULL,0,0,0,0,0,0,0,'227',2,0.0,NULL,SPACE(10),0.0,'Z',NULL,-1,-1,0,GETDATE(),NULL,NULL,NULL,@TRANGRP,NULL)
   INSERT INTO [ASSETPOSTS] VALUES (@BORGID,@FINYEAR,@PERIODID,@ASSETPOSTDATE,'FED2270520','DEP',0,'FED','Balance Sheet','1100005',     ' ',' ',  'Fixed Asset Depreciation Posting','   ','INR',@LASTDEPTM,0,  0,0,SPACE(10),SPACE(10),@ASSETNUMBER    ,SPACE(10),0,SPACE(10),0.0,SPACE(10),SPACE(10),0,SPACE(10),'Z',NULL,NULL,0,0,0,0,0,0,0,'227',2,0.0,NULL,SPACE(10),0.0,'Z',NULL,-1,-1,0,GETDATE(),NULL,NULL,NULL,@TRANGRP,NULL)
   --UPDATE ASSETS SET AssetBookValue = AssetBookValue-@LASTDEPTM,
   --                  AssetAccumDep = AssetAccumDep+@LASTDEPTM, 
			--		 ASSETPOST=1, ASSETDEP=ASSETDEP+ 1,
			--		 ASSETDEPPROG= @LASTDENUMBER , 
			--		 ASSETLASTPOSTDATE  = @ASSETPOSTDATE,
			--		 AssetiDate = @ASSETPOSTDATE, ASSETFINPOST = 1, 
			--		 ASSETTAXDEPTYPE = @FINYEAR , ASSETOIRATE = @PERIODID
			--		 WHERE ASSETID = @ASSETID 
   COMMIT TRAN

   FETCH NEXT FROM ASSETS INTO @ASSETID, @ASSETNUMBER

END

CLOSE ASSETS
DEALLOCATE ASSETS 

UPDATE ASSETS SET ASSETPOST=1

SELECT GETDATE()