/****** Object:  Procedure [BS].[ReconciledStatement]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE   procedure BS.ReconciledStatement (@ORGID INT,@LEDGERCODE VARCHAR(10), @YEAR INT) 
as

   
    DECLARE @FILENAME VARCHAR(100)
	DECLARE @FILEID   VARCHAR(10)
	DECLARE @SQL      VARCHAR(250)
 

	SET @FILENAME = 'BSBS_TEMP.DBO.RECONLIST'

	SELECT T.ORGID,T.YEAR,T.PERIOD,T.PDATE,T.BATCHREF,T.TRANSREF,T.TRANSTYPE,T.LEDGERCODE,T.DESCRIPTION,
	-1.0* T.CREDIT CHEQUES, T.DEBIT DEPOSITS ,T.RECEIVEDDATE,B.BORGNAME,L.LEDGERNAME
	INTO #TEMP0
	FROM 
	TRANSACTIONS T  INNER JOIN BORGS B  ON T.ORGID=B.BORGID 
	INNER JOIN LEDGERCODES L ON T.LEDGERCODE=L.LEDGERCODE 
	WHERE ORGID=@ORGID AND T.LEDGERCODE= @LEDGERCODE  AND RECONSTATUS=0 AND YEAR=@YEAR ORDER BY PDATE  

	SELECT @FILEID= CONVERT(INT,RAND( (DATEPART(mm, GETDATE()) * 100000 )
	+ (DATEPART(ss, GETDATE()) * 1000 )
	+ DATEPART(ms, GETDATE()) )*1000)

    SET @FILENAME = @FILENAME+LTRIM(RTRIM(CONVERT(VARCHAR(3),@FILEID)))
    SELECT @FILENAME 
    SET @SQL = 'SELECT *  INTO '+@FILENAME+ ' FROM   #TEMP0   ORDER BY PDATE '

    EXEC(@SQL)

    RETURN @FILEID