/****** Object:  Procedure [BS].[spAssignContraInvoice080920]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE [BS].[spAssignContraInvoice080920]
AS
 
DECLARE @POSTDATE DATETIME 
DECLARE @FINYEAR INT 
DECLARE @FINMONTH INT 
DECLARE @RECONID INT 
DECLARE @BORGID INT 
DECLARE @NEXTNUMBER INT 
DECLARE @BORGNAME VARCHAR(10)
DECLARE @NEXTINVOICENUMBER VARCHAR(35) 
DECLARE @SUBCRECONID INT 
DECLARE @NEWNUMBER CHAR(4) 

DECLARE RECONIDS CURSOR FOR SELECT CONTRAID FROM CONTRAS WHERE ContraVATType<>', , , ,' AND CONTRAVATAMNT<>0 AND   REMARKS=''    ORDER BY CONTRAID
--DECLARE RECONIDS CURSOR FOR SELECT CONTRAID FROM CONTRAS WHERE ContraVATType LIKE '%G%'  AND   REMARKS=''    ORDER BY CONTRAID
OPEN RECONIDS 
FETCH NEXT FROM RECONIDS INTO @RECONID 

WHILE @@FETCH_STATUS=0
BEGIN
 SELECT @SUBCRECONID = ContraReconID    FROM CONTRAS WHERE CONTRAID= @RECONID
 SELECT @POSTDATE=POSTDATE, @BORGID = ORGID  FROM SUBCRECONS WHERE RECONID=@SUBCRECONID
 SELECT @BORGNAME = LTRIM(RTRIM(LEFT(BORGNAME,6))) FROM BORGS WHERE BORGID =@BORGID 
 SELECT @FINYEAR = YEAR(@POSTDATE)
 SELECT @FINMONTH = MONTH(@POSTDATE) 
 IF @FINMONTH BETWEEN 4 AND 12 
    SET @FINYEAR = @FINYEAR+1
 ELSE
    SET @FINYEAR = @FINYEAR 

 SET @NEXTNUMBER = 0
 SELECT @NEXTNUMBER = ISNULL(MAX(NEXTINVNO),0) FROM BS.CONTRANUMBERS WHERE CONTRABORGID=@BORGID AND FINYEAR=@FINYEAR 
 SET @NEXTNUMBER= @NEXTNUMBER+ 1
 IF @NEXTNUMBER <= 9
    SET  @NEWNUMBER='000'+LTRIM(RTRIM(STR(@NEXTNUMBER,1)))
 ELSE IF @NEXTNUMBER BETWEEN 10 AND 99 
    SET  @NEWNUMBER='00'+ LTRIM(RTRIM(STR(@NEXTNUMBER,2)))
 ELSE IF @NEXTNUMBER BETWEEN 100 AND 999
    SET  @NEWNUMBER ='0'+ LTRIM(RTRIM(STR(@NEXTNUMBER,3))) 
 ELSE
    SET  @NEWNUMBER = STR(@NEXTNUMBER,4) 


  
 SET @NEXTINVOICENUMBER = @BORGNAME+'SCR'+LTRIM(RTRIM(STR(@FINYEAR)))+@NEWNUMBER 
 


 BEGIN TRAN 
   INSERT INTO  BS.CONTRANUMBERS(CONTRABORGID , FINYEAR , NEXTINVNO, CONTRARECONID ) 
   VALUES (@BORGID,@FINYEAR,@NEXTNUMBER,@RECONID)
   UPDATE CONTRAS SET REMARKS=@NEXTINVOICENUMBER WHERE CONTRAID = @RECONID
 
 COMMIT TRAN  

 FETCH NEXT FROM RECONIDS INTO @RECONID
END
CLOSE RECONIDS 
DEALLOCATE RECONIDS
 