/****** Object:  Procedure [BS].[spBankCashReceiptVouchers]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROC [BS].[spBankCashReceiptVouchers](@BORGID INT,@FINYEAR INT ,@TRANSTYPE AS VARCHAR(10),@TRANSACTIONDATE varchar(15),@TYPENAME VARCHAR(10))
AS

DECLARE @BATCHREF       VARCHAR(10)
DECLARE @TRANSREF       VARCHAR(10)
DECLARE @WORKINPROGRESS VARCHAR(10)
DECLARE @LEDGERCODE     VARCHAR(10)
DECLARE @CREDITOR       VARCHAR(100)
DECLARE @STARTDATE      DATETIME
DECLARE @ENDDATE        DATETIME
DECLARE @RETAINEDINCOME VARCHAR(10)
DECLARE @DOCNUMBER      VARCHAR(25)
DECLARE @TRANSDATE      DATETIME
DECLARE @TRANGRP        INT
DECLARE @WHTCOUNT       INT
DECLARE @WHTCODE        VARCHAR(10)
DECLARE @WHTAMOUNT      DECIMAL(18,2)
DECLARE @WHTID          INT
DECLARE @CREDITORCONTROL VARCHAR(10)
DECLARE @LASTINDEX INT

SELECT @TRANSDATE = CONVERT(DATETIME, @TRANSACTIONDATE,103) -- dd/mm/yyyy 
SELECT @LEDGERCODE =  TypeOppGlCode  FROM TRANSTYPES WHERE TypeName=@TRANSTYPE
 
SELECT @LEDGERCODE 

SELECT @WORKINPROGRESS=CONTROLFROMGL FROM CONTROLCODES WHERE ControlName='Work In Progress'  
SELECT @RETAINEDINCOME=CONTROLFROMGL FROM CONTROLCODES WHERE ControlName='Retained Income'
SELECT @CREDITORCONTROL = CONTROLFROMGL FROM CONTROLCODES WHERE CONTROLNAME = 'Creditors'
SELECT @CREDITOR = LEDGERNAME FROM LEDGERCODES WHERE LEDGERCODE=@LEDGERCODE
SELECT @WHTCODE  = CONTROLFROMGL FROM CONTROLCODES WHERE CONTROLNAME = 'Creditors Withholding Tax'    
      
SELECT ICGLCODE LEDGERCODE INTO #IC FROM BORGS  
DELETE FROM #IC WHERE LEDGERCODE IS NULL

INSERT INTO #IC VALUES (@RETAINEDINCOME)
INSERT INTO #IC VALUES (@WORKINPROGRESS)

DECLARE @FILENAME VARCHAR(100)
DECLARE @FILEID   VARCHAR(10)
DECLARE @SQL      VARCHAR(250)
DECLARE @OPENINGDATE DATE
DECLARE @CURRENTBATCHREF VARCHAR(10)


SET @FILENAME = 'BSBS_TEMP.DBO.RECEIPTVOUCHER'
         
CREATE TABLE #TEMP0
(
 INDEXCODE INT IDENTITY, 
 YEAR CHAR(10),
 ORGID  INT,
 PERIOD INT,
 PDATE DATETIME,
 BATCHREF CHAR(10),
 TRANSREF CHAR(10),
 TRANSTYPE CHAR(10),
 LEDGERCODE CHAR(10),
 LEDGERNAME CHAR(100),
 CONTRACT CHAR(10),
 CONTRNAME CHAR(100),
 DESCRIPTION VARCHAR(255),
 CURRENCY VARCHAR(3),
 DEBIT MONEY,
 CREDIT MONEY,
 CREDNO VARCHAR(10),
 PARTY VARCHAR(100),
 SUBCONTRN CHAR(20),
 USERID CHAR(60),
 DOCNUMBER NCHAR(50),
 CREDITOR  VARCHAR(100),
 BATCHTRANS VARCHAR(20),
 MATCHREF INT,
 SUPPLIERBILL VARCHAR(100),
 MATERIALTYPE VARCHAR(100),
 WHTINDEX  INT,
 WHTAMOUNT DECIMAL(18,2),
 INWORDS VARCHAR(200)

)
 

 SELECT 
 DISTINCT T.BATCHREF,T.TRANSREF ,T.TRANGRP 
FROM 
 TRANSACTIONS T
WHERE
 T.TransType  = @TRANSTYPE  AND
 T.LedgerCode = @LEDGERCODE AND
 T.PDATE      = @TRANSDATE  AND LEDGERCODE NOT IN (SELECT LEDGERCODE FROM #IC ) AND
 T.ORGID      = @BORGID     AND T.YEAR = @FINYEAR AND  T.DEBIT > 0
 

DECLARE BATCHES  CURSOR FOR
SELECT 
 DISTINCT T.BATCHREF,T.TRANSREF ,T.TRANGRP 
FROM 
 TRANSACTIONS T
WHERE
 T.TransType  = @TRANSTYPE  AND
 T.LedgerCode = @LEDGERCODE AND
 T.PDATE      = @TRANSDATE  AND LEDGERCODE NOT IN (SELECT LEDGERCODE FROM #IC ) AND
 T.ORGID      = @BORGID     AND T.YEAR = @FINYEAR AND  T.DEBIT > 0
 
OPEN BATCHES
FETCH NEXT FROM BATCHES INTO @BATCHREF,@TRANSREF,@TRANGRP 

WHILE @@FETCH_STATUS=0
BEGIN
    
  
    
	INSERT INTO #TEMP0 (YEAR,ORGID,PERIOD,PDATE,BATCHREF,TRANSREF,TRANSTYPE,LEDGERCODE,LEDGERNAME,
	CONTRACT,CONTRNAME,DESCRIPTION,CURRENCY,DEBIT,CREDIT,CREDNO,PARTY,SUBCONTRN,USERID,DOCNUMBER,CREDITOR,MATCHREF)  
	SELECT 
		   T.YEAR,
		   T.OrgID,
		   T.PERIOD,
		   T.PDATE,
		   T.BATCHREF,
		   T.TRANSREF,
		   T.TRANSTYPE,
		   T.LEDGERCODE,
		   [BS].[fnGetLedgerName](T.LEDGERCODE) LEDGERNAME,
		   T.CONTRACT,
		   C.CONTRNAME,
		   LTRIM(RTRIM(T.DESCRIPTION)) DESCRIPTION ,
		   T.CURRENCY,
		   T.DEBIT,
		   T.CREDIT,
		   T.CREDNO,
		   [BS].[fnGetParty](T.CREDNO) PARTY,
		   T.SUBCONTRAN,
		   [BS].[fnGetUserName](T.USERID) USERID ,
		   T.DOCNUMBER ,
		   @CREDITOR,
		   MATCHREF
	FROM 
			TRANSACTIONS T 
			LEFT OUTER  JOIN CONTRACTS C ON C.CONTRNUMBER=T.CONTRACT
	WHERE 
			BatchRef = @BATCHREF AND TransRef=@TRANSREF AND
			LEDGERCODE  NOT IN (SELECT LEDGERCODE FROM #IC ) AND 
			LEDGERCODE NOT IN (@WORKINPROGRESS,@RETAINEDINCOME ) AND
			TRANGRP = @TRANGRP  AND YEAR=@FINYEAR 
    
	FETCH NEXT FROM BATCHES INTO @BATCHREF,@TRANSREF,@TRANGRP 

 END

CLOSE BATCHES
DEALLOCATE BATCHES

UPDATE #TEMP0 SET DESCRIPTION = LTRIM(RTRIM(DESCRIPTION))+' ' + [BS].[fnGetDescriptionOppositeLeg](#TEMP0.MATCHREF) WHERE #TEMP0.MATCHREF>0

ALTER TABLE #TEMP0 ADD ORDERNUMBER VARCHAR(50) 
UPDATE #TEMP0 SET CONTRACT = RI.CONTRACTID FROM REQITEMS RI INNER JOIN ORD ON ORD.REQID=RI.REQID INNER JOIN #TEMP0 ON ORD.ORDNUMBER=#TEMP0.ORDERNUMBER 
UPDATE #TEMP0 SET CONTRNAME = CON.CONTRNAME FROM CONTRACTS CON INNER JOIN #TEMP0    ON CON.CONTRID=#TEMP0.CONTRACT WHERE #TEMP0.CONTRACT>1




ALTER TABLE #TEMP0 ADD INTERCOMPANY VARCHAR(200)
UPDATE #TEMP0 SET INTERCOMPANY = SPACE(200)
UPDATE #TEMP0 SET INTERCOMPANY = BORGNAME FROM BORGS INNER JOIN #TEMP0 ON #TEMP0.ORGID=BORGS.BORGID WHERE #TEMP0.ORGID<>@BORGID 

ALTER TABLE #TEMP0 ADD BOOKINGORG VARCHAR(255)
UPDATE #TEMP0 SET BOOKINGORG = BORGS.BORGNAME FROM BORGS INNER JOIN #TEMP0 ON #TEMP0.ORGID=BORGS.BORGID 
UPDATE #TEMP0  SET BATCHTRANS = TRANSREF+BATCHREF


ALTER TABLE #TEMP0 ADD TYPENAME VARCHAR(20)
UPDATE #TEMP0 SET TYPENAME = @TYPENAME 

ALTER TABLE #TEMP0 ADD BORGNAME VARCHAR(75)
UPDATE #TEMP0 SET BORGNAME = (SELECT BORGNAME FROM BORGS WHERE BORGID=@BORGID) 

 ALTER TABLE #TEMP0 ADD TRANSACTIONDATE DATETIME
 UPDATE #TEMP0 SET TRANSACTIONDATE =  @TRANSDATE

 ALTER TABLE #TEMP0 ADD FINYEAR CHAR(4)
 UPDATE #TEMP0 SET FINYEAR=@FINYEAR

 ALTER TABLE #TEMP0 ADD BORGID INT
 UPDATE #TEMP0 SET BORGID= @BORGID



  ALTER TABLE #TEMP0 ADD TRANSTYPELEDGER VARCHAR(10)
  UPDATE #TEMP0 SET TRANSTYPELEDGER = @LEDGERCODE 
 
  ALTER TABLE #TEMP0 ADD RECEIVEORG VARCHAR(250)
  UPDATE #TEMP0 SET RECEIVEORG =LTRIM(RTRIM(B.BORGNAME)) FROM BORGS B INNER JOIN #TEMP0 ON #TEMP0.ORGID=B.BORGID
  
  UPDATE #TEMP0 SET SUPPLIERBILL = T.TRANSREF FROM TRANSACTIONS T INNER JOIN #TEMP0 ON #TEMP0.MATCHREF = T.TRANSID 

  DELETE FROM #TEMP0 WHERE LEDGERCODE=@LEDGERCODE AND ORGID=@BORGID AND CREDIT >0 
 
  CREATE TABLE #TEMPADD(ID INT,ADDRESS VARCHAR(100))
  DECLARE @BORGNEWS VARCHAR(4000)
  SELECT @BORGNEWS = BORGNEWS FROM BORGS WHERE BORGID=@BORGID
  INSERT INTO #TEMPADD
  SELECT * FROM  [dbo].[SplitString](@BORGNEWS,'|') 
 
 ALTER TABLE #TEMP0 ADD TITLE1 VARCHAR(200)
 ALTER TABLE #TEMP0 ADD TITLE2 VARCHAR(200)
 ALTER TABLE #TEMP0 ADD TITLE3 VARCHAR(200)
 ALTER TABLE #TEMP0 ADD TITLE4 VARCHAR(200)
 ALTER TABLE #TEMP0 ADD TITLE5 VARCHAR(200)
 
 DECLARE @SITEADDRESS VARCHAR(100)
 SET @SITEADDRESS=''
 SELECT @SITEADDRESS = ADDRESS FROM #TEMPADD WHERE ID=1   
 UPDATE #TEMP0 SET TITLE1 = @SITEADDRESS
 SET @SITEADDRESS=''
 SELECT @SITEADDRESS = ADDRESS FROM #TEMPADD WHERE ID=2   
 UPDATE #TEMP0 SET TITLE2 = @SITEADDRESS
 SET @SITEADDRESS=''
 SELECT @SITEADDRESS = ADDRESS FROM #TEMPADD WHERE ID=3   
 UPDATE #TEMP0 SET TITLE3= @SITEADDRESS
 SET @SITEADDRESS=''
 SELECT @SITEADDRESS = ADDRESS FROM #TEMPADD WHERE ID=4  
 UPDATE #TEMP0 SET TITLE4 = @SITEADDRESS
 SET @SITEADDRESS=''
 SELECT @SITEADDRESS = ADDRESS FROM #TEMPADD WHERE ID=5  
 UPDATE #TEMP0 SET TITLE5 = @SITEADDRESS
 

 DELETE FROM #TEMP0 WHERE LEDGERCODE='1320000' AND DEBIT=0 
 DELETE FROM #TEMP0 WHERE DEBIT=0 AND CREDIT=0 

 --UPDATE #TEMP0 SET DEBIT=-1.0*DEBIT,CREDIT=-1.0*CREDIT WHERE LEDGERCODE= '1310005' 
  
 SELECT PDATE,TRANSREF,SUM(DEBIT-CREDIT) NETPAYABLE INTO #TEMPNETPAYABLE FROM #TEMP0 GROUP BY TRANSREF,PDATE
 SELECT * FROM #TEMPNETPAYABLE
 ALTER TABLE #TEMPNETPAYABLE ADD AMOUNTINWORDS VARCHAR(200)


 UPDATE #TEMPNETPAYABLE SET AMOUNTINWORDS=DBO.FN_SPELLNUMBER(NETPAYABLE, 'UK',0) 

 UPDATE #TEMP0 SET INWORDS = AMOUNTINWORDS FROM #TEMPNETPAYABLE INNER JOIN #TEMP0 ON #TEMP0.TRANSREF=#TEMPNETPAYABLE.TRANSREF AND 
 #TEMP0.PDATE=#TEMPNETPAYABLE.PDATE 
 
 SELECT * FROM #TEMPNETPAYABLE



 UPDATE #TEMP0 SET INWORDS = 'Amount In Words '+ LTRIM(RTRIM(INWORDS)) 
 SELECT * FROM #TEMP0 

 DECLARE @RCOUNT INT
 SELECT @RCOUNT = COUNT(DISTINCT(BOOKINGORG)) FROM #TEMP0 
 IF @RCOUNT>1 
   UPDATE #TEMP0 SET BOOKINGORG = SPACE(10) 

DELETE FROM #TEMP0 WHERE LEDGERCODE=@LEDGERCODE AND ORGID=@BORGID AND CREDIT >0 
 
	 DECLARE @Random INT;
	 DECLARE @Upper INT;
	 DECLARE @Lower INT
 
	 SET @Lower = 1 ---- The lowest random number
	 SET @Upper = 9999 ---- The highest random number
	 SELECT @Random = ROUND(((@Upper - @Lower -1) * RAND() + @Lower), 0)

	 SELECT @FILEID= CONVERT(INT,RAND( (DATEPART(mm, GETDATE()) * 100000 )
		+ (DATEPART(ss, GETDATE()) * 1000 )
		+ DATEPART(ms, GETDATE()) )*1000) + STR(@RANDOM) 

	 SET @FILENAME = @FILENAME+LTRIM(RTRIM(CONVERT(VARCHAR(6),@FILEID)))
     SET @SQL = 'SELECT *  INTO '+@FILENAME+ ' FROM   #TEMP0  ORDER BY PDATE  '
	 EXEC(@SQL)
	 SELECT @FILENAME
     RETURN @FILEID
 