/****** Object:  Procedure [BS].[spBankPaymentAndReceipts]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE BS.spBankPaymentAndReceipts(@FINYEAR INT)
AS

DECLARE @WIP VARCHAR(15)
DECLARE @RETAINED VARCHAR(15) 
SET @WIP = '2990000'
SET @RETAINED = '1100005'   
 

--CREATE TABLE VINODBANKDUMP2020(TRANGRP INT, TRANSID INT, ORGID INT,ORGNAME VARCHAR(100), FINYEAR INT,PERIOD INT, PERIODNAME VARCHAR(25),
--PDATE DATETIME,BATCHREF VARCHAR(15), TRANSREF VARCHAR(25), TRANSTYPE VARCHAR(20), PARTYCODE VARCHAR(15) , PARTYNAME VARCHAR(150), LEDGERCODE VARCHAR(10),
--LEDGERNAME VARCHAR(200),DESCRIPTION VARCHAR(255) , DEBIT DECIMAL(18,2), CREDIT DECIMAL(18,2)) 
DELETE FROM VINODBANKDUMP2020
DECLARE @BANKSTART VARCHAR(15)
DECLARE @BANKEND   VARCHAR(15)
SELECT  @BANKSTART=CONTROLFROMGL, @BANKEND=CONTROLTOGL FROM CONTROLCODES WHERE CONTROLNAME='Bank'

CREATE TABLE #BANKS(BANKLEDGERCODE VARCHAR(15)) 
INSERT INTO #BANKS 
SELECT LEDGERCODE FROM LEDGERCODES WHERE LEDGERCODE BETWEEN @BANKSTART AND @BANKEND 

SELECT DISTINCT TRANGRP INTO #TRANGRPS FROM TRANSACTIONS WHERE YEAR=@FINYEAR AND LEDGERCODE IN (SELECT BANKLEDGERCODE  FROM #BANKS)  AND PERIOD<>0 

INSERT INTO VINODBANKDUMP2020(TRANGRP,TRANSID,ORGID,FINYEAR,PERIOD,PDATE,BATCHREF,TRANSREF,TRANSTYPE,PARTYCODE,LEDGERCODE,DESCRIPTION,DEBIT,CREDIT)
SELECT TRANGRP,TRANSID,ORGID,YEAR,PERIOD,PDATE,BATCHREF,TRANSREF,TRANSTYPE,CREDNO,LEDGERCODE,DESCRIPTION,DEBIT,CREDIT 
FROM TRANSACTIONS 
WHERE TRANGRP IN (SELECT TRANGRP FROM #TRANGRPS) AND PERIOD<>0

DELETE FROM VINODBANKDUMP2020 WHERE LEDGERCODE=@WIP 
DELETE FROM VINODBANKDUMP2020 WHERE LEDGERCODE=@RETAINED

UPDATE VINODBANKDUMP2020 SET ORGNAME = B.BORGNAME FROM BORGS B INNER JOIN VINODBANKDUMP2020 ON VINODBANKDUMP2020.ORGID=B.BORGID 
UPDATE VINODBANKDUMP2020 SET PERIODNAME=P.PERIODDESC FROM PERIODMASTER P INNER JOIN VINODBANKDUMP2020 ON VINODBANKDUMP2020.PERIOD  = P.PERIODID 
UPDATE VINODBANKDUMP2020 SET PARTYNAME=C.CREDNAME FROM CREDITORS C INNER JOIN VINODBANKDUMP2020 ON VINODBANKDUMP2020.PARTYCODE=C.CREDNUMBER 
UPDATE VINODBANKDUMP2020 SET PARTYNAME=D.DEBTNAME FROM DEBTORS D INNER JOIN VINODBANKDUMP2020 ON VINODBANKDUMP2020.PARTYCODE=D.DEBTNUMBER 
UPDATE VINODBANKDUMP2020 SET PARTYNAME=S.SUBNAME  FROM SUBCONTRACTORS S INNER JOIN VINODBANKDUMP2020 ON VINODBANKDUMP2020.PARTYCODE=S.SUBNUMBER 
UPDATE VINODBANKDUMP2020 SET LEDGERNAME =L.LEDGERNAME FROM LEDGERCODES L INNER JOIN VINODBANKDUMP2020 ON VINODBANKDUMP2020.LEDGERCODE =  L.LEDGERCODE 

SELECT * FROM VINODBANKDUMP2020 ORDER BY TRANGRP,TRANSID 