/****** Object:  Procedure [BS].[spCashFlowMakers]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE  [BS].[spCashFlowMakers](@BORGID INT ,@FINYEAR INT ,@STARTPERIOD INT,@ENDPERIOD INT)
AS

DECLARE @FILENAME VARCHAR(100)
DECLARE @FILEID   VARCHAR(10)
DECLARE @SQL      VARCHAR(250)
SET @FILENAME = 'BSBS_TEMP.DBO.CASHFLOW'


DELETE FROM BS.CASHFLOW 
DECLARE @COL1MAX INT
DECLARE @COL2MAX INT
DECLARE @MAXROW INT
DECLARE @I  INT
SELECT @COL1MAX = MAX(POSTIONINDEX) FROM BS.CASHFLOWINDICATORS WHERE COLINDEX=1
SELECT @COL2MAX = MAX(POSTIONINDEX) FROM BS.CASHFLOWINDICATORS WHERE COLINDEX=2
IF @COL1MAX > @COL2MAX 
  SET @MAXROW = @COL1MAX
ELSE 
  SET @MAXROW = @COL2MAX

SET @I  = 1
WHILE @I <= @MAXROW 
BEGIN
  INSERT INTO BS.CASHFLOW(ROWINDEX) VALUES ( @I )
  SET @I = @I+1
END

UPDATE BS.CASHFLOW 
 SET CATEGORY  = I.CATEGORY ,
     COL1INDEX = I.INDEXCODE,
	 COL1CODE  = I.COLID,
	 COL1NAME  = I.DESCRIPTION,
	 COL1FONT  = I.FONTID ,
	 COL1VALUE  = 0
FROM 
     BS.CASHFLOWINDICATORS I 
	 INNER JOIN BS.CASHFLOW ON BS.CASHFLOW.ROWINDEX = I.POSTIONINDEX AND I.COLINDEX = 1

UPDATE BS.CASHFLOW 
 SET CATEGORY  = I.CATEGORY ,
     COL2INDEX = I.INDEXCODE,
	 COL2CODE  = I.COLID,
	 COL2NAME  = I.DESCRIPTION,
	 COL2FONT  = I.FONTID ,
	 COL1VALUE  = 0
FROM 
     BS.CASHFLOWINDICATORS I 
	 INNER JOIN BS.CASHFLOW ON BS.CASHFLOW.ROWINDEX = I.POSTIONINDEX AND I.COLINDEX = 2




DECLARE @PURCHASENET DECIMAL(18,2)
DECLARE @TEMPSUM DECIMAL(18,2)
DECLARE @WIP VARCHAR(10)
DECLARE @SALE VARCHAR(10)
DECLARE @UNCERTIFIED VARCHAR(10)
DECLARE @RECOVERYUNCERTIFIED DECIMAL(18,2)
DECLARE @ITEMONE DECIMAL(18,2)
DECLARE @ITEMTWO DECIMAL(18,2)
DECLARE @ITEMTHREE DECIMAL(18,2) 

DECLARE @T1SUM DECIMAL(18,2)
DECLARE @T2SUM DECIMAL(18,2) 
DECLARE @T3SUM DECIMAL(18,2)
DECLARE @ISUM DECIMAL(18,2)      
DECLARE @SUBTRACTSUM DECIMAL(18,2) 
DECLARE @ESUM DECIMAL(18,2)

SET @SALE = '2540000'                        
SET @WIP= '2990000'
SET @UNCERTIFIED = '4010001'

SELECT  @RECOVERYUNCERTIFIED = SUM(DEBIT) FROM TRANSACTIONS
 WHERE  LEDGERCODE NOT IN ( '2540000','2990000') AND
 TRANGRP IN (SELECT TRANGRP FROM TRANSACTIONS WHERE YEAR=@FINYEAR AND ORGID = @BORGID AND LEFT(BATCHREF,3)='DTI' AND LEDGERCODE =  @UNCERTIFIED AND PERIOD BETWEEN @STARTPERIOD AND @ENDPERIOD ) 
UPDATE BS.CASHFLOW SET COL2VALUE = @RECOVERYUNCERTIFIED/100000.00 WHERE COL2INDEX= 9000



SELECT LEDGERCODE, (SUM(DEBIT-CREDIT)) AMOUNT 
INTO #TEMP0 
FROM TRANSACTIONS 
WHERE YEAR = @FINYEAR AND ORGID = @BORGID AND PERIOD BETWEEN @STARTPERIOD AND @ENDPERIOD
GROUP BY LEDGERCODE
ORDER BY LEDGERCODE 


--DELETE FROM #TEMP0 WHERE LEFT(LEDGERCODE,1) IN (6,7)
ALTER TABLE #TEMP0 ADD CASHFLOWINDEX  NVARCHAR(55)
ALTER TABLE #TEMP0 ADD CASHFLOWMARKER VARCHAR(50)

UPDATE #TEMP0 SET CASHFLOWINDEX = AT.VALUE FROM ATTRIBVALUE AT INNER JOIN #TEMP0 
ON #TEMP0.LedgerCode = AT.COLKEY AND AT.TABLENAME = 'LEDGERCODES' AND ATTRIBUTE = 'Cash Flow Markers'
select * from #temp0 where ledgercode='6030191'  
DELETE  FROM #TEMP0 WHERE CASHFLOWINDEX IS NULL 
DELETE  FROM #TEMP0 WHERE CASHFLOWINDEX = '9999' 

UPDATE #TEMP0 SET CASHFLOWINDEX='5100' WHERE LEDGERCODE='2590100'
UPDATE #TEMP0 SET CASHFLOWINDEX='5041' WHERE LEDGERCODE='4510005'

SELECT * FROM ATTRIBLOOKUP AV WHERE AV.TABLENAME='Ledgercodes' AND AV.ATTRIBUTE='Cash Flow Markers' ORDER BY VALUE 

UPDATE #TEMP0 SET CASHFLOWMARKER = AV.DESCR FROM ATTRIBLOOKUP AV
 INNER JOIN #TEMP0 ON #TEMP0.CASHFLOWINDEX = AV.VALUE WHERE AV.TABLENAME='Ledgercodes' AND AV.ATTRIBUTE='Cash Flow Markers'

select * from #temp0 where ledgercode='6030191'  

SELECT ledgercode,(amount/100000) amt  FROM #TEMP0 where cashflowindex='1020' ORDER BY CASHFLOWINDEX 

SELECT CASHFLOWMARKER,CASHFLOWINDEX,SUM(AMOUNT) NETAMOUNT 
INTO #TEMP1
FROM #TEMP0 
WHERE CASHFLOWINDEX<>'9999'
GROUP BY CASHFLOWMARKER,CASHFLOWINDEX

SELECT * FROM #TEMP1 ORDER BY  CASHFLOWINDEX 
 
UPDATE #TEMP1 SET NETAMOUNT = NETAMOUNT/100000.00



-- Purchase is Purchase in Contracts + Store Ledger 
SELECT @PURCHASENET = NETAMOUNT FROM #TEMP1 WHERE CASHFLOWMARKER IN ('Closing Stock Materials','Purchase')
UPDATE BS.CASHFLOW SET COL1VALUE = @PURCHASENET WHERE COL1CODE = 'E1'  

DELETE FROM #TEMP1 WHERE CASHFLOWINDEX IS NULL 
SELECT * FROM #TEMP1  

UPDATE BS.CASHFLOW SET COL1VALUE = T.NETAMOUNT FROM #TEMP1 T INNER JOIN BS.CASHFLOW ON BS.CASHFLOW.COL1INDEX=T.CASHFLOWINDEX 
UPDATE BS.CASHFLOW SET COL2VALUE = T.NETAMOUNT FROM #TEMP1 T INNER JOIN BS.CASHFLOW ON BS.CASHFLOW.COL2INDEX=T.CASHFLOWINDEX 

SELECT * FROM BS.CASHFLOW 

UPDATE BS.CASHFLOW SET COL1VALUE = ABS(COL1VALUE) WHERE COL1CODE IN ('E14','E15','E16','E17','E18','E19','E20','E21') 

SELECT @TEMPSUM = SUM(COL1VALUE) FROM BS.CASHFLOW WHERE COL1CODE IN ('E1','E2','E3')
UPDATE BS.CASHFLOW SET COL1VALUE = @TEMPSUM WHERE COL1CODE='E4' 
SET @TEMPSUM = 0

SELECT @TEMPSUM = SUM(COL1VALUE) FROM BS.CASHFLOW WHERE COL1CODE IN ('E5','E6','E7','E8','E9','E10','E11','E12') 
UPDATE BS.CASHFLOW SET COL1VALUE = @TEMPSUM WHERE COL1CODE='E13' 
SET @TEMPSUM = 0


SELECT @TEMPSUM = SUM(COL1VALUE) FROM BS.CASHFLOW WHERE COL1CODE IN ('E14','E15','E16','E17','E18','E19','E20') 
UPDATE BS.CASHFLOW SET COL1VALUE = @TEMPSUM WHERE  COL1CODE='E21'
SET @TEMPSUM =0


SELECT @TEMPSUM = SUM(COL1VALUE) FROM BS.CASHFLOW WHERE COL1CODE IN ('E4','E13')
SET @SUBTRACTSUM = 0 
SELECT @SUBTRACTSUM = SUM(COL1VALUE) FROM BS.CASHFLOW WHERE COL1CODE IN ( 'E21' )

UPDATE BS.CASHFLOW SET COL1VALUE = @TEMPSUM-@SUBTRACTSUM WHERE COL1CODE='O'
SET @TEMPSUM =0


SELECT * FROM #TEMP0 

-- Second Column 
UPDATE BS.CASHFLOW SET COL2VALUE = 0 WHERE COL2VALUE IS NULL

-- MAKING BOTH ADVANCE POSITEIVE VALUE 
UPDATE BS.CASHFLOW SET COL2VALUE = -1.0*(COL2VALUE) WHERE COL2CODE IN ( 'R1','R2' ) 
UPDATE BS.CASHFLOW SET COL2VALUE = -1.0*COL2VALUE WHERE COL2CODE IN ( 'R3','R4','R5','R6','R7','R8') 

SELECT @T1SUM = SUM(COL2VALUE) FROM BS.CASHFLOW 
WHERE COL2CODE IN ('R1','R2','R3','R4','R5','R6','R7','R8','R9')
UPDATE BS.CASHFLOW SET COL2VALUE = @T1SUM  WHERE COL2CODE = 'T1'


SELECT @T2SUM = SUM(COL2VALUE) FROM BS.CASHFLOW 
WHERE COL2CODE IN ('R10','R11','R12','R13', 'R13A')
UPDATE BS.CASHFLOW SET COL2VALUE = @T2SUM  WHERE COL2CODE = 'T2'

SELECT @T3SUM = SUM(COL2VALUE) FROM BS.CASHFLOW 
WHERE COL2CODE IN ('R14','R15')
UPDATE BS.CASHFLOW SET COL2VALUE = @T3SUM  WHERE COL2CODE = 'T3'


SELECT @ISUM = @T1SUM - @T2SUM - @T3SUM  
UPDATE  BS.CASHFLOW SET COL2VALUE = @ISUM  WHERE COL2CODE = 'I'

--SELECT @TEMPSUM = SUM(COL2VALUE) FROM BS.CASHFLOW WHERE COL2INDEX BETWEEN 5000 AND 5040
--UPDATE BS.CASHFLOW SET COL2VALUE = @TEMPSUM WHERE COL2INDEX=1
--SET @TEMPSUM = 0

--SELECT @TEMPSUM = SUM(COL2VALUE) FROM BS.CASHFLOW WHERE COL2INDEX BETWEEN 5010 AND 5010
--UPDATE BS.CASHFLOW SET COL2VALUE = @TEMPSUM WHERE COL2INDEX=2
--SET @TEMPSUM = 0
--SELECT * FROM BS.CASHFLOW

--SELECT @ITEMONE = COL2VALUE FROM BS.CASHFLOW WHERE COL2INDEX= 5120
--SELECT @ITEMTWO = COL2VALUE FROM BS.CASHFLOW WHERE COL2INDEX= 9000
--SET @TEMPSUM = @ITEMONE - @ITEMTWO
--UPDATE BS.CASHFLOW SET COL2VALUE = @TEMPSUM WHERE COL2INDEX=3
--SET @TEMPSUM =0

 
--SELECT @ITEMONE = COL2VALUE FROM BS.CASHFLOW WHERE COL2INDEX= 5120
--SELECT @ITEMTWO = COL2VALUE FROM BS.CASHFLOW WHERE COL2INDEX= 3
--SET @TEMPSUM = @ITEMONE - @ITEMTWO
--UPDATE BS.CASHFLOW SET COL2VALUE = @TEMPSUM WHERE COL2INDEX=4
--SET @TEMPSUM = 0

--SELECT @ITEMONE = COL2VALUE FROM BS.CASHFLOW WHERE COL2INDEX= 3
--SELECT @ITEMTWO = COL2VALUE FROM BS.CASHFLOW WHERE COL2INDEX= 4
--SELECT @ITEMTHREE = COL2VALUE FROM BS.CASHFLOW WHERE COL2INDEX= 5140
--SET @TEMPSUM = @ITEMONE + @ITEMTWO +@ITEMTHREE 
--UPDATE BS.CASHFLOW SET COL2VALUE = @TEMPSUM WHERE COL2INDEX=5
--SET @TEMPSUM = 0


--SELECT @ITEMONE    = COL2VALUE FROM BS.CASHFLOW WHERE COL2INDEX= 1
--SELECT @ITEMTWO    = COL2VALUE FROM BS.CASHFLOW WHERE COL2INDEX= 2
--SELECT @ITEMTHREE  = COL2VALUE FROM BS.CASHFLOW WHERE COL2INDEX= 5
--SET @TEMPSUM = @ITEMONE - @ITEMTWO- @ITEMTHREE 
--UPDATE BS.CASHFLOW SET COL2VALUE = @TEMPSUM WHERE COL2INDEX=6
--SET @TEMPSUM = 0


-- Final First Column


SELECT @ITEMONE    = COL2VALUE FROM BS.CASHFLOW WHERE COL2INDEX= 6
SELECT @ITEMTWO    = COL1VALUE FROM BS.CASHFLOW WHERE COL1INDEX= 4
 
SET @TEMPSUM =  @ITEMONE - @ITEMTWO 

UPDATE BS.CASHFLOW SET COL1VALUE = @TEMPSUM WHERE COL1INDEX=5
SET @TEMPSUM = 0

SELECT @ESUM = COL1VALUE FROM BS.CASHFLOW WHERE COL1CODE='O'
 


UPDATE BS.CASHFLOW SET COL1VALUE = @ISUM-@ESUM WHERE COL1CODE ='N'


SELECT * INTO #TEMP9 FROM BS.CASHFLOW WHERE CATEGORY<=3
ALTER TABLE #TEMP9 ADD BORGID INT
ALTER TABLE #TEMP9 ADD BORGNAME VARCHAR(100)
ALTER TABLE #TEMP9 ADD STARTPERIOD VARCHAR(25)
ALTER TABLE #TEMP9 ADD ENDPERIOD VARCHAR(25)
UPDATE #TEMP9 SET BORGID = @BORGID 
UPDATE #TEMP9 SET BORGNAME = B.BORGNAME FROM BORGS B WHERE B.BORGID=@BORGID 
UPDATE #TEMP9 SET STARTPERIOD = PS.DESCR FROM PERIODSETUP PS WHERE PERIOD=@STARTPERIOD AND YEAR=@FINYEAR AND ORGID=@BORGID 
UPDATE #TEMP9 SET ENDPERIOD = PS.DESCR FROM PERIODSETUP PS WHERE PERIOD=@ENDPERIOD AND YEAR=@FINYEAR AND ORGID=@BORGID 
 

DECLARE @Random INT;
DECLARE @Upper INT;
DECLARE @Lower INT
 
SET @Lower = 1 ---- The lowest random number
SET @Upper = 999 ---- The highest random number
SELECT @Random = ROUND(((@Upper - @Lower -1) * RAND() + @Lower), 0)

SELECT @FILEID= CONVERT(INT,RAND( (DATEPART(mm, GETDATE()) * 100000 )
+ (DATEPART(ss, GETDATE()) * 1000 )
+ DATEPART(ms, GETDATE()) )*1000) + STR(@RANDOM) 

SET @FILENAME = @FILENAME+LTRIM(RTRIM(CONVERT(VARCHAR(6),@FILEID)))
SET @SQL = 'SELECT *  INTO '+@FILENAME+ ' FROM   #TEMP9 ORDER BY CATEGORY  '
EXEC(@SQL)

SELECT @FILENAME 
RETURN @FILEID
 