/****** Object:  Procedure [BS].[spCashFlowMakers_NEW]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE  [BS].[spCashFlowMakers_NEW](@BORGID INT ,@FINYEAR INT ,@STARTPERIOD INT,@ENDPERIOD INT)
AS
/***** LATEST CASH FLOW REPORT - MODIFIED ON 06 MARCH 2019 *******/

DECLARE @UNRECONDELIVERY DECIMAL(18,2)
 

-- FOREIGN EXCHANGE TO BE CONSIDERED - UN RECON DELIVERY --

SELECT D.ORDID,D.PRICE,D.DLVRQTY 
INTO #TEMPUNRECONDLVRY
FROM DELIVERIES D
WHERE D.TBORGID=@BORGID AND D.ALLOCATED=0 

ALTER TABLE #TEMPUNRECONDLVRY ADD CURRENCY VARCHAR(10)
ALTER TABLE #TEMPUNRECONDLVRY ADD EXCHANGERATE DECIMAL(18,2)
ALTER TABLE #TEMPUNRECONDLVRY ADD HOMECURRENCY VARCHAR(10)

UPDATE #TEMPUNRECONDLVRY
SET CURRENCY =O.CURRENCY , EXCHANGERATE = O.EXCHRATE, HOMECURRENCY = O.HOMECURRENCY 
FROM ORD O INNER JOIN #TEMPUNRECONDLVRY ON #TEMPUNRECONDLVRY.ORDID = O.ORDID 

UPDATE #TEMPUNRECONDLVRY SET PRICE = PRICE * EXCHANGERATE WHERE CURRENCY <>'INR' 
SELECT @UNRECONDELIVERY= SUM(DLVRQTY*PRICE) FROM #TEMPUNRECONDLVRY

---- FE ENDS HERE 












DECLARE @FILENAME VARCHAR(100)
DECLARE @FILEID   VARCHAR(10)
DECLARE @SQL      VARCHAR(250)
SET @FILENAME = 'BSBS_TEMP.DBO.CASHFLOW'


DECLARE @FILENAMEWSHEET VARCHAR(100)
SET @FILENAMEWSHEET = 'BSBS_TEMP.DBO.CASHFLOWWSHEET'


DECLARE @STORECODE VARCHAR(25)
SELECT  DISTINCT @STORECODE=  STKSTORE FROM INVENTORY WHERE BORGID=@BORGID AND LEFT(STKSTORE,2)='MS'
DECLARE @STORELEDGER VARCHAR(10)
SELECT @STORELEDGER = STKCTL FROM INVSTORES WHERE STORECODE=@STORECODE 
 
DECLARE @WIP VARCHAR(10)
DECLARE @RETAINED VARCHAR(10)
SELECT @WIP = CONTROLFROMGL FROM CONTROLCODES WHERE CONTROLNAME='Work In Progress'                   
SELECT @RETAINED = CONTROLFROMGL FROM CONTROLCODES WHERE CONTROLNAME='Retained Income'                    

DELETE FROM BS.CASHFLOW_NEW 

DECLARE @COL1MAX DECIMAL(6,2)
DECLARE @COL2MAX DECIMAL(6,2)
DECLARE @MAXROW INT
DECLARE @I  DECIMAL(6,2)
SELECT @COL1MAX = MAX(POSTIONINDEX) FROM BS.CASHFLOWINDICATORS_NEW WHERE COLINDEX=1 AND PAGENO=1
SELECT @COL2MAX = MAX(POSTIONINDEX) FROM BS.CASHFLOWINDICATORS_NEW WHERE COLINDEX=2 AND PAGENO=1
IF @COL1MAX > @COL2MAX 
  SET @MAXROW = @COL1MAX
ELSE 
  SET @MAXROW = @COL2MAX

SET @I  = 1
WHILE @I <= @MAXROW 
BEGIN
  INSERT INTO BS.CASHFLOW_NEW(ROWINDEX) VALUES ( @I )
  SET @I = @I+1
END




UPDATE BS.CASHFLOW_NEW 
 SET CATEGORY  = I.CATEGORY ,
     COL1INDEX = I.INDEXCODE,
	 COL1CODE  = I.COLID,
	 COL1NAME  = I.DESCRIPTION,
	 COL1FONT  = I.FONTID ,
	 COL1VALUE  = 0,
	 PAGENO = I.PAGENO 
FROM 
     BS.CASHFLOWINDICATORS_NEW I 
	 INNER JOIN BS.CASHFLOW_NEW ON BS.CASHFLOW_NEW.ROWINDEX = I.POSTIONINDEX AND I.COLINDEX = 1 AND I.PAGENO=1

UPDATE BS.CASHFLOW_NEW 
 SET CATEGORY  = I.CATEGORY ,
     COL2INDEX = I.INDEXCODE,
	 COL2CODE  = I.COLID,
	 COL2NAME  = I.DESCRIPTION,
	 COL2FONT  = I.FONTID ,
	 COL1VALUE  = 0,
	 PAGENO = I.PAGENO 
FROM 
     BS.CASHFLOWINDICATORS_NEW I 
	 INNER JOIN BS.CASHFLOW_NEW ON BS.CASHFLOW_NEW.ROWINDEX = I.POSTIONINDEX AND I.COLINDEX = 2 AND I.PAGENO=1



SELECT @COL1MAX = MAX(POSTIONINDEX) FROM BS.CASHFLOWINDICATORS_NEW WHERE COLINDEX=1 AND PAGENO=2
SELECT @COL2MAX = MAX(POSTIONINDEX) FROM BS.CASHFLOWINDICATORS_NEW WHERE COLINDEX=2 AND PAGENO=2
IF @COL1MAX > @COL2MAX 
  SET @MAXROW = @COL1MAX
ELSE 
  SET @MAXROW = @COL2MAX

--SET @I  = 1
WHILE @I <= @MAXROW 
BEGIN
  INSERT INTO BS.CASHFLOW_NEW(ROWINDEX) VALUES ( @I )
  SET @I = @I+1
END

UPDATE BS.CASHFLOW_NEW 
 SET CATEGORY  = I.CATEGORY ,
     COL1INDEX = I.INDEXCODE,
	 COL1CODE  = I.COLID,
	 COL1NAME  = I.DESCRIPTION,
	 COL1FONT  = I.FONTID ,
	 COL1VALUE  = 0,
	 PAGENO = I.PAGENO 
FROM 
     BS.CASHFLOWINDICATORS_NEW I 
	 INNER JOIN BS.CASHFLOW_NEW ON BS.CASHFLOW_NEW.ROWINDEX = I.POSTIONINDEX AND I.COLINDEX = 1 AND I.PAGENO=2

UPDATE BS.CASHFLOW_NEW 
 SET CATEGORY  = I.CATEGORY ,
     COL2INDEX = I.INDEXCODE,
	 COL2CODE  = I.COLID,
	 COL2NAME  = I.DESCRIPTION,
	 COL2FONT  = I.FONTID ,
	 COL1VALUE  = 0,
	 PAGENO = I.PAGENO 
FROM 
     BS.CASHFLOWINDICATORS_NEW I 
	 INNER JOIN BS.CASHFLOW_NEW ON BS.CASHFLOW_NEW.ROWINDEX = I.POSTIONINDEX AND I.COLINDEX = 2 AND I.PAGENO=2

UPDATE BS.CASHFLOW_NEW SET COL1VALUE  = 0,COL2VALUE= 0


DECLARE @TEMPSUM DECIMAL(18,2)
DECLARE @ITEMONE DECIMAL(18,2)
DECLARE @ITEMTWO DECIMAL(18,2)

 

SELECT PDATE,BATCHREF,TRANSREF,LEDGERCODE,DESCRIPTION,DEBIT,CREDIT,CREDNO,TRANGRP,CURRENCY,HOMECURRAMOUNT	
INTO #MASTERLIST 
FROM TRANSACTIONS 
WHERE YEAR = @FINYEAR AND ORGID = @BORGID AND PERIOD BETWEEN @STARTPERIOD AND @ENDPERIOD  
ORDER BY TRANGRP 

ALTER TABLE #MASTERLIST ADD NETAMOUNT DECIMAL(18,2) 
UPDATE #MASTERLIST SET NETAMOUNT = (DEBIT-CREDIT) WHERE CURRENCY = 'INR'
UPDATE #MASTERLIST SET NETAMOUNT = HomeCurrAmount WHERE CURRENCY <> 'INR' AND DEBIT>0
UPDATE #MASTERLIST SET NETAMOUNT = -1.0*HOMECURRAMOUNT WHERE CURRENCY <>'INR' AND CREDIT>0 

SELECT LEDGERCODE, (SUM(NETAMOUNT)) AMOUNT 
INTO #TEMP0 
FROM #MASTERLIST  
GROUP BY LEDGERCODE
ORDER BY LEDGERCODE 



-- ADD EXTRA TWO COLUMNS INDEX AND MARKEER NAME 
ALTER TABLE #MASTERLIST ADD CASHFLOWINDEX  NVARCHAR(55)
ALTER TABLE #MASTERLIST ADD CASHFLOWMARKER VARCHAR(50)
ALTER TABLE #MASTERLIST ADD COLID VARCHAR(10) 
UPDATE #MASTERLIST SET CASHFLOWINDEX = AV.VALUE   FROM  ATTRIBVALUE AV INNER JOIN #MASTERLIST 
ON #MASTERLIST.LedgerCode = AV.COLKEY AND AV.TABLENAME = 'LEDGERCODES' AND ATTRIBUTE = 'Cash Flow Markers' 
UPDATE #MASTERLIST SET    CASHFLOWMARKER = FI.DESCRIPTION , COLID = FI.COLID  FROM   BS.CASHFLOWINDICATORS_NEW FI
 INNER JOIN #MASTERLIST ON #MASTERLIST.CASHFLOWINDEX = FI.INDEXCODE WHERE FI.PAGENO=1
DELETE  FROM #MASTERLIST WHERE CASHFLOWINDEX IS NULL 
DELETE  FROM #MASTERLIST WHERE CASHFLOWINDEX = '0' 
DELETE  FROM #MASTERLIST WHERE CASHFLOWMARKER IS NULL
DELETE  FROM #MASTERLIST WHERE COLID IS NULL
ALTER TABLE #MASTERLIST ADD COLINDEX INT
ALTER TABLE #MASTERLIST ADD POSITIONINDEX INT
UPDATE #MASTERLIST SET COLINDEX = IND.COLINDEX,POSITIONINDEX = IND.POSTIONINDEX
FROM #MASTERLIST INNER JOIN BS.CASHFLOWINDICATORS_NEW IND ON #MASTERLIST.COLID = IND.COLID WHERE IND.PAGENO=1 
 


-- ADD EXTRA TWO COLUMNS INDEX AND MARKEER NAME 
ALTER TABLE #TEMP0 ADD CASHFLOWINDEX  NVARCHAR(55)
ALTER TABLE #TEMP0 ADD CASHFLOWMARKER VARCHAR(50)
UPDATE #TEMP0 SET CASHFLOWINDEX = AV.VALUE   FROM  ATTRIBVALUE AV INNER JOIN #TEMP0 
ON #TEMP0.LedgerCode = AV.COLKEY AND AV.TABLENAME = 'LEDGERCODES' AND ATTRIBUTE = 'Cash Flow Markers' 
UPDATE #TEMP0 SET    CASHFLOWMARKER = AV.DESCR  FROM   ATTRIBLOOKUP AV
 INNER JOIN #TEMP0 ON #TEMP0.CASHFLOWINDEX = AV.VALUE WHERE AV.TABLENAME='LEDGERCODES' AND AV.ATTRIBUTE='Cash Flow Markers'
DELETE  FROM #TEMP0 WHERE CASHFLOWINDEX IS NULL 
DELETE  FROM #TEMP0 WHERE CASHFLOWINDEX = '0' 
 






SELECT CASHFLOWMARKER,CASHFLOWINDEX,SUM(AMOUNT) NETAMOUNT 
INTO #TEMP1
FROM #TEMP0 
GROUP BY CASHFLOWMARKER,CASHFLOWINDEX
DELETE FROM #TEMP1 WHERE CASHFLOWINDEX IS NULL 
UPDATE #TEMP1 SET NETAMOUNT = NETAMOUNT/100000.00
SELECT CASHFLOWMARKER,CASHFLOWINDEX,NETAMOUNT FROM #TEMP1 WHERE CASHFLOWINDEX='1000' 
SELECT sum(debit-credit)/100000.00 FROM #MASTERLIST  where cashflowindex='1000'
 
-- CASHFLOW MARKERS  - OUTFLOW 
-- 1000	E1	PURCHASE
-- 1005	E2	FIM
-- 1010 E3  DIRECT EXPENSE 
-- 1020 E4  INDIRECT EXPENSE
-- 1    (1000 + 1005 + 1010 + 1020 ) 
-- 1030	3	E6	Pre Paid Expense
-- 1040	3	E7	Pre Operative Expense
-- 1050	3	E8	Other - Deposit
-- 1060	3	E9	Loan & Advance
-- 1070	3	E10	Inter Site Balances
-- 1080	3	E11	Input VAT Receivable/Payable
-- 1090	3	E12	Service Tax Receivable/Payable
-- 1100	3	E13	Fixed Assets
-- 2	3	E14	Total Assets( 1030 .. 1100 )
-- 1120	3	E15	Creditors For Materials
-- 1130	3	E16	Creditors For Sub Contract
-- 1160	3	E17	Provision for Expense
-- 1170	3	E18	Security Deposit
-- 1180	3	E19	Statutory Liabilities(TDS/VAT/Service Tax etc)
-- 3	3	E20	Total Creditors/Outstanding ( 1120 .. 1180 ) 
-- 4	3	O	Total Outflow  ( SUM OF  1 ,  2 AND 3 ) 

UPDATE BS.CASHFLOW_NEW SET COL1VALUE = T.NETAMOUNT FROM #TEMP1 T INNER JOIN BS.CASHFLOW_NEW ON BS.CASHFLOW_NEW.COL1INDEX=T.CASHFLOWINDEX WHERE PAGENO=1
UPDATE BS.CASHFLOW_NEW SET COL2VALUE =-1.0 * T.NETAMOUNT FROM #TEMP1 T INNER JOIN BS.CASHFLOW_NEW ON BS.CASHFLOW_NEW.COL2INDEX=T.CASHFLOWINDEX WHERE PAGENO=1
-- THIS LINE HAS BEEN MODIFIED - PUT A MULTIPLICATION FACTOR -1.0 FOR COLUMN 2 VALUES 


-- REPLACING UNRECON DELIVERY AND COMMITTED COST TO TEMPLATE 

UPDATE BS.CASHFLOW_NEW SET COL1VALUE = @UNRECONDELIVERY/100000.00 WHERE BS.CASHFLOW_NEW.COL1INDEX=1001
UPDATE BS.CASHFLOW_NEW SET COL1VALUE = -1.0*@UNRECONDELIVERY/100000.00 WHERE BS.CASHFLOW_NEW.COL1INDEX=1121

 

-- TOTAL DIRECT EXPENSE AND PURCHASE 
SET @TEMPSUM = 0
SELECT @TEMPSUM = SUM(COL1VALUE) FROM BS.CASHFLOW_NEW WHERE COL1INDEX IN ( '1000', '1001', '1005', '1010', '1020' ) 
UPDATE BS.CASHFLOW_NEW SET COL1VALUE = @TEMPSUM WHERE COL1INDEX = 1  AND PAGENO=1

-- TOTAL ASSETS 
SET @TEMPSUM = 0
SELECT @TEMPSUM = SUM(COL1VALUE) FROM BS.CASHFLOW_NEW WHERE COL1INDEX IN ( '1030', '1040', '1050', '1060',  '1080', '1090', '1100 ')  
UPDATE BS.CASHFLOW_NEW SET COL1VALUE = @TEMPSUM WHERE COL1INDEX=2 AND PAGENO=1

-- TOTAL CREDITOR / OUTSTANDING 
SET @TEMPSUM = 0
SELECT @TEMPSUM = SUM(COL1VALUE) FROM BS.CASHFLOW_NEW WHERE COL1INDEX IN ( '1120','1121', '1130', '1160' , '1170', '1180')  
UPDATE BS.CASHFLOW_NEW SET COL1VALUE = @TEMPSUM WHERE  COL1INDEX=3 AND PAGENO=1

-- DIVIDEND
DECLARE @DIVIDEND DECIMAL(18,2)
SET @DIVIDEND = 0 
SELECT @DIVIDEND = ISNULL( SUM(COL1VALUE),0 ) FROM BS.CASHFLOW_NEW WHERE COL1INDEX='8020'  AND COL1CODE='E21' 

 
--INVESTMENTS 
DECLARE @INVESTMENT  DECIMAL(18,2)
SET @INVESTMENT = 0 
SELECT @INVESTMENT = ISNULL( SUM(COL1VALUE),0 ) FROM BS.CASHFLOW_NEW WHERE COL1INDEX='8040'  AND COL1CODE='E22' 

-- Total Outflow  ( SUM OF  1 ,  2 AND 3 ) 
SET @TEMPSUM = 0
SELECT @TEMPSUM = SUM(COL1VALUE) FROM BS.CASHFLOW_NEW WHERE COL1INDEX IN (  '1', '2', '3')  AND PAGENO=1
--ADD DIVIDEND AND INVESTMENT TOO
SET @TEMPSUM = @TEMPSUM + @DIVIDEND + @INVESTMENT 

UPDATE BS.CASHFLOW_NEW SET COL1VALUE = @TEMPSUM WHERE  COL1INDEX=4 AND PAGENO=1



--5000	3	R1	Moblization Advance
--5005	3	R2	Secured Advance
--5010	3	R3	Certified Value
--5015	3	R4	Certified FIM
--5020	3	R5	Un Certified Value
--5025	3	R6	Un Certified FIM
--5030	3	R7	Sales VAT
--5040	3	R8	Service Tax on Sales
--5041	3	R9	Income From Other Sources
--6515	3	R10	Scrap Sales
--5070	3	R11	Sundry Balance Written Off
--1	    3	T1	Advance + Sales (R1..R11)
--5050	3	R12	Retention Money
--5089	3	R13	Amount on Hold By Client
--5090	3	R14	Income Tax (TDS Deducted by Clients)
--5100	3	R15	VAT TDS (TDS Deducted by Clients)
--5110	3	R16	Labour Cess on sales
--2	3	T2	Total Deduction (R10..R14)
--5120	3	R17	Net Receivables (Debtor)
--5140	3	R18	Other Receivables
--3	3	T3	Total Receivables  
--4	3	I 	Total Inflow (  T1 + T2 + T3 )

SELECT 'NOW TO CHECK'
SELECT * FROM BS.CASHFLOW_NEW ORDER BY PAGENO 
-- Advance + Sales (R1..R11)
SET @TEMPSUM =0
SELECT @TEMPSUM = SUM(COL2VALUE) FROM BS.CASHFLOW_NEW WHERE COL2INDEX IN ( '5000','5005', '5010',  '5020',  '5030','5035', '5040', '5041', '6515', '5070' )
UPDATE BS.CASHFLOW_NEW SET COL2VALUE = @TEMPSUM  WHERE  COL2INDEX=1 AND PAGENO=1
SELECT 'TESTING '
SELECT @TEMPSUM 

-- Total Deduction (R10..R14)
SET @TEMPSUM =0
SELECT @TEMPSUM = SUM(COL2VALUE) FROM BS.CASHFLOW_NEW WHERE COL2INDEX IN ( '5050','5060', '5090', '5100', '5110' )
UPDATE BS.CASHFLOW_NEW SET COL2VALUE = @TEMPSUM  WHERE  COL2INDEX=2 AND PAGENO=1
-- Total Receivables   
SET @TEMPSUM =0
SELECT @TEMPSUM = SUM(COL2VALUE) FROM BS.CASHFLOW_NEW WHERE COL2INDEX IN ( '5120', '5140')
UPDATE BS.CASHFLOW_NEW SET COL2VALUE = @TEMPSUM  WHERE  COL2INDEX=3 AND PAGENO=1


-- Total Inflow   ( SUM OF  1 ,  2 AND 3 ) 
SET @TEMPSUM = 0
SELECT @TEMPSUM = SUM(COL2VALUE) FROM BS.CASHFLOW_NEW WHERE COL2INDEX IN (  '1', '2', '3')  AND PAGENO=1

-- Share Capital 
DECLARE @SHARE DECIMAL(18,2)
SET @SHARE = 0
SELECT @SHARE = ISNULL(SUM(COL2VALUE),0) FROM BS.CASHFLOW_NEW WHERE COL2INDEX='8000' AND COL2CODE='T4' 

-- IND Adjustment 
DECLARE @IND DECIMAL(18,2)
SET @IND= 0 
SELECT @IND =ISNULL( SUM(COL2VALUE),0) FROM BS.CASHFLOW_NEW WHERE COL2INDEX='8010'  AND COL2CODE = 'T5' 

-- ADDING FINAL INFLOW WITH SHARE AND IND 

SET @TEMPSUM = @TEMPSUM+ @SHARE+@IND 
UPDATE BS.CASHFLOW_NEW SET COL2VALUE = @TEMPSUM WHERE  COL2INDEX=4 AND PAGENO=1




-- Final NET CASH FLOW
SELECT @ITEMONE    = COL2VALUE FROM BS.CASHFLOW_NEW WHERE COL2INDEX= 4 AND PAGENO = 1
SELECT @ITEMTWO    = COL1VALUE FROM BS.CASHFLOW_NEW WHERE COL1INDEX= 4 AND PAGENO = 1
SET @TEMPSUM =    @ITEMONE - @ITEMTWO 
UPDATE BS.CASHFLOW_NEW SET COL1VALUE = @TEMPSUM WHERE COL1INDEX=5

 

-- Cash and Bank Balances - This is a Special Case where Cash + Bank caputre in Single Field 
SET @TEMPSUM = 0
SELECT @TEMPSUM = SUM(AMOUNT) FROM #TEMP0 WHERE CASHFLOWINDEX IN ( '2010','2020','2030' )  
SELECT @TEMPSUM 
--SELECT @TEMPSUM = SUM(COL1VALUE) FROM BS.CASHFLOW_NEW WHERE COL1INDEX IN (  '5', '1070' )  AND PAGENO=1
UPDATE BS.CASHFLOW_NEW SET COL1VALUE =+1.0* @TEMPSUM / 100000.00 WHERE  COL1INDEX=6 AND PAGENO=1
 

--- PAGE NUMBER 2
-- Line Number 101 to 106 & 109
UPDATE BS.CASHFLOW_NEW SET COL2VALUE = (SELECT COL2VALUE FROM BS.CASHFLOW_NEW WHERE COL2INDEX='5010' AND PAGENO=1 ) WHERE COL2INDEX='5010' AND PAGENO=2
UPDATE BS.CASHFLOW_NEW SET COL2VALUE = (SELECT COL2VALUE FROM BS.CASHFLOW_NEW WHERE COL2INDEX='5020' AND PAGENO=1 ) WHERE COL2INDEX='5020' AND PAGENO=2
UPDATE BS.CASHFLOW_NEW SET COL2VALUE = (SELECT COL2VALUE FROM BS.CASHFLOW_NEW WHERE COL2INDEX='5030' AND PAGENO=1 ) WHERE COL2INDEX='5030' AND PAGENO=2
UPDATE BS.CASHFLOW_NEW SET COL2VALUE = (SELECT COL2VALUE FROM BS.CASHFLOW_NEW WHERE COL2INDEX='5040' AND PAGENO=1 ) WHERE COL2INDEX='5040' AND PAGENO=2
 
UPDATE BS.CASHFLOW_NEW SET COL2VALUE = (SELECT COL2VALUE FROM BS.CASHFLOW_NEW WHERE COL2INDEX='5120' AND PAGENO=1 ) WHERE COL2INDEX='5120' AND PAGENO=2
-- Line 107 which is sum of 101 to 106
SET @TEMPSUM = 0
SELECT @TEMPSUM = SUM(COL2VALUE) FROM BS.CASHFLOW_NEW WHERE 
COL2INDEX IN ( '5010','5020', '5030', '5040' )   AND 
COL2CODE IN ('S1','S2','S3','S4') AND
PAGENO=2
UPDATE BS.CASHFLOW_NEW SET COL2VALUE = @TEMPSUM WHERE  COL2INDEX=11 AND PAGENO=2


DECLARE @TOTALPAYMENTOUTSTANDING  DECIMAL(18,2)
DECLARE @TOTALSALES DECIMAL(18,2)
SELECT  @TOTALPAYMENTOUTSTANDING = COL2VALUE FROM BS.CASHFLOW_NEW WHERE COL2INDEX='5120' AND PAGENO=2 
SET @TOTALSALES = @TEMPSUM  
UPDATE  BS.CASHFLOW_NEW SET COL2VALUE = (   @TEMPSUM -  @TOTALPAYMENTOUTSTANDING   )  WHERE PAGENO=2 AND COL2INDEX = '12'

SET @TEMPSUM = 0
SELECT @TEMPSUM = SUM(COL2VALUE) FROM BS.CASHFLOW_NEW WHERE COL2INDEX IN (  '12', '5120' )  AND PAGENO=2
UPDATE BS.CASHFLOW_NEW SET COL2VALUE = @TEMPSUM WHERE  COL2INDEX=13 AND PAGENO=2


-- Proftablity 
UPDATE BS.CASHFLOW_NEW SET COL1VALUE = (SELECT COL1VALUE FROM BS.CASHFLOW_NEW WHERE COL1INDEX='1000' AND PAGENO=1 ) WHERE COL1INDEX='1000' AND PAGENO=2
UPDATE BS.CASHFLOW_NEW SET COL1VALUE = (SELECT COL1VALUE FROM BS.CASHFLOW_NEW WHERE COL1INDEX='1010' AND PAGENO=1 ) WHERE COL1INDEX='1010' AND PAGENO=2
UPDATE BS.CASHFLOW_NEW SET COL1VALUE = (SELECT COL1VALUE FROM BS.CASHFLOW_NEW WHERE COL1INDEX='1020' AND PAGENO=1 ) WHERE COL1INDEX='1020' AND PAGENO=2



-- Profitablity Column 2

UPDATE BS.CASHFLOW_NEW SET COL2VALUE = (SELECT COL2VALUE FROM BS.CASHFLOW_NEW WHERE COL2INDEX='11' AND PAGENO=2 ) WHERE PAGENO=2 AND COL2INDEX = '30000'


SET @TEMPSUM = 0
SELECT @TEMPSUM = ISNULL(SUM(COL2VALUE),0) FROM  BS.CASHFLOW_NEW  WHERE COL2CODE IN ('R10')  AND PAGENO=1
UPDATE BS.CASHFLOW_NEW SET COL2VALUE = @TEMPSUM WHERE  COL2INDEX = '30100' AND PAGENO=2 


DECLARE @MATERIALSTORE   DECIMAL(18,2)
select   @STORELEDGER
SELECT * FROM #TEMP0 WHERE LEDGERCODE=@STORELEDGER 

SELECT * FROM #TEMP0 WHERE LEDGERCODE='2512002'
SELECT  @MATERIALSTORE =  ISNULL(SUM(AMOUNT),0)/100000.00 FROM #TEMP0 WHERE LEDGERCODE IN (@STORELEDGER, '2512002') 

SET @MATERIALSTORE = @MATERIALSTORE * -1.0 

UPDATE BS.CASHFLOW_NEW SET COL2VALUE = @MATERIALSTORE WHERE PAGENO=2 AND COL2INDEX = '30110'


DECLARE @WIPAMOUT   DECIMAL(18,2)
SELECT @WIPAMOUT =    ISNULL(SUM(AMOUNT),0)/100000.00 FROM #TEMP0 WHERE LEDGERCODE IN ('2990100') 

SET @WIPAMOUT = -1.0 * @WIPAMOUT

UPDATE BS.CASHFLOW_NEW SET COL2VALUE = @WIPAMOUT WHERE PAGENO=2 AND COL2INDEX = '30120'

DECLARE @PLYBATTERN   DECIMAL(18,2)
SELECT @PLYBATTERN =  ISNULL(SUM(AMOUNT),0)/100000.00 FROM #TEMP0 WHERE LEDGERCODE IN ('2990101') 

SET @PLYBATTERN = -1.0 * @PLYBATTERN

UPDATE BS.CASHFLOW_NEW SET COL2VALUE = @PLYBATTERN WHERE PAGENO=2 AND COL2INDEX = '30130'
 
DECLARE @SITEESTABLISHMENTAMT   DECIMAL(18,2)
SELECT @SITEESTABLISHMENTAMT =  ISNULL(SUM(AMOUNT),0)/100000.00 FROM #TEMP0 WHERE LEDGERCODE IN ( '2510097','2512000','2100099')

SET @SITEESTABLISHMENTAMT = -1.0  * @SITEESTABLISHMENTAMT

UPDATE BS.CASHFLOW_NEW SET COL2VALUE = @SITEESTABLISHMENTAMT WHERE PAGENO=2 AND COL2INDEX = '30140'

DECLARE @SITEESTABLISHMENT   DECIMAL(18,2)
SELECT @SITEESTABLISHMENT =   ISNULL(SUM(AMOUNT),0)/100000.00 FROM #TEMP0 WHERE LEDGERCODE IN ( '2512001','2560000')
 
SET @SITEESTABLISHMENT = -1.0 * @SITEESTABLISHMENT

UPDATE BS.CASHFLOW_NEW SET COL2VALUE = @SITEESTABLISHMENT WHERE PAGENO=2 AND COL2INDEX = '30150'
  
DECLARE @TOTALB   DECIMAL(18,2)
SELECT @TOTALB = ISNULL(SUM(COL2VALUE),0) FROM BS.CASHFLOW_NEW WHERE COL2INDEX IN ('30000','30100', '30110', '30120','30130', '30140', '30150')
UPDATE BS.CASHFLOW_NEW SET COL2VALUE = @TOTALB WHERE PAGENO=2 AND COL2INDEX = '21'



DECLARE @TOTALA   DECIMAL(18,2)
SELECT @TOTALA = SUM(COL1VALUE) FROM BS.CASHFLOW_NEW WHERE COL1INDEX IN (  '1000', '1010', '1020' )  AND PAGENO=2
--UPDATE BS.CASHFLOW_NEW SET COL1VALUE =( @TOTALB- @TEMPSUM ) WHERE  COL1INDEX=11  AND   PAGENO=2 
UPDATE BS.CASHFLOW_NEW SET COL1VALUE =( @TOTALA) WHERE  COL1INDEX=11  AND   PAGENO=2 


SET @TEMPSUM=0.0
--SET @TEMPSUM =  @TOTALB+@TOTALA  - UPDATING 13 MARCH 2018
SET @TEMPSUM =  @TOTALB-@TOTALA
UPDATE BS.CASHFLOW_NEW SET COL1VALUE = @TEMPSUM WHERE PAGENO=2 AND COL1INDEX = '12'




SELECT * INTO #TEMP9 FROM BS.CASHFLOW_NEW  WHERE PAGENO IN (1,2)

ALTER TABLE #TEMP9 ADD BORGID INT
ALTER TABLE #TEMP9 ADD BORGNAME VARCHAR(100)
ALTER TABLE #TEMP9 ADD STARTPERIOD VARCHAR(25)
ALTER TABLE #TEMP9 ADD ENDPERIOD VARCHAR(25)
ALTER TABLE #TEMP9 ADD FINYEAR CHAR(4)
UPDATE #TEMP9 SET BORGID = @BORGID 
UPDATE #TEMP9 SET BORGNAME = B.BORGNAME FROM BORGS B WHERE B.BORGID=@BORGID 
UPDATE #TEMP9 SET STARTPERIOD = PS.DESCR FROM PERIODSETUP PS WHERE PERIOD=@STARTPERIOD AND YEAR=@FINYEAR AND ORGID=@BORGID 
UPDATE #TEMP9 SET ENDPERIOD = PS.DESCR FROM PERIODSETUP PS WHERE PERIOD=@ENDPERIOD AND YEAR=@FINYEAR AND ORGID=@BORGID 
UPDATE #TEMP9 SET FINYEAR = @FINYEAR 
 
ALTER TABLE #MASTERLIST ADD LEDGERNAME VARCHAR(100)
UPDATE #MASTERLIST SET LEDGERNAME = L.LEDGERNAME FROM LEDGERCODES L INNER JOIN #MASTERLIST ON #MASTERLIST.LEDGERCODE=L.LEDGERCODE 
ALTER TABLE #MASTERLIST ADD BORGID INT
ALTER TABLE #MASTERLIST ADD BORGNAME VARCHAR(100)
ALTER TABLE #MASTERLIST ADD STARTPERIOD VARCHAR(25)
ALTER TABLE #MASTERLIST ADD ENDPERIOD VARCHAR(25)
ALTER TABLE #MASTERLIST ADD FINYEAR CHAR(4)
UPDATE #MASTERLIST SET FINYEAR=@FINYEAR 
UPDATE #MASTERLIST SET BORGID = @BORGID 
UPDATE #MASTERLIST SET BORGNAME = B.BORGNAME FROM BORGS B WHERE B.BORGID=@BORGID 
UPDATE #MASTERLIST SET STARTPERIOD = PS.DESCR FROM PERIODSETUP PS WHERE PERIOD=@STARTPERIOD AND YEAR=@FINYEAR AND ORGID=@BORGID 
UPDATE #MASTERLIST SET ENDPERIOD = PS.DESCR FROM PERIODSETUP PS WHERE PERIOD=@ENDPERIOD AND YEAR=@FINYEAR AND ORGID=@BORGID


DECLARE @Random INT;
DECLARE @Upper INT;
DECLARE @Lower INT
 
SET @Lower = 1 ---- The lowest random number
SET @Upper = 99999 ---- The highest random number
SELECT @Random = ROUND(((@Upper - @Lower -1) * RAND() + @Lower), 0)

SELECT @FILEID= CONVERT(INT,RAND( (DATEPART(mm, GETDATE()) * 100000 )
+ (DATEPART(ss, GETDATE()) * 1000 )
+ DATEPART(ms, GETDATE()) )*1000) + STR(@RANDOM) 

SET @FILENAME = @FILENAME+LTRIM(RTRIM(CONVERT(VARCHAR(6),@FILEID)))
SET @SQL = 'SELECT *  INTO '+@FILENAME+ ' FROM   #TEMP9 ORDER BY CATEGORY  '
EXEC(@SQL)

SET @FILENAMEWSHEET = @FILENAMEWSHEET+LTRIM(RTRIM(CONVERT(VARCHAR(6),@FILEID)))
SET @SQL = 'SELECT *  INTO '+@FILENAMEWSHEET+ ' FROM   #MASTERLIST ORDER BY  COLINDEX,POSITIONINDEX,LEDGERCODE,PDATE'
EXEC(@SQL) 


SELECT @FILENAME 
SELECT @FILENAMEWSHEET
RETURN @FILEID
 
 