/****** Object:  Procedure [BS].[spChangeRNos]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE  PROCEDURE [BS].[spChangeRNos] 
as
DECLARE @OLDRECONID INT
DECLARE @START INT

SET @START = 32490

CREATE TABLE #TEMP0 (RECONID INT,NEWRECONID INT)
INSERT INTO #TEMP0(RECONID)
SELECT RECONID  FROM SUBCRECONS WHERE RECONID >= 33483 ORDER BY RECONID
UPDATE #TEMP0 SET NEWRECONID = 0
 
 
DECLARE RECONS CURSOR FOR SELECT RECONID FROM #TEMP0
OPEN RECONS
FETCH NEXT FROM RECONS INTO @OLDRECONID
WHILE @@FETCH_STATUS= 0 
BEGIN
 UPDATE #TEMP0 SET NEWRECONID = @START WHERE RECONID=@OLDRECONID
 SET @START= @START+1
 FETCH NEXT FROM RECONS INTO @OLDRECONID 
END
CLOSE RECONS
DEALLOCATE RECONS
SELECT * FROM #TEMP0 

SELECT * INTO BS.NEWRECONIDS FROM #TEMP0 
SELECT * FROM BS.NEWRECONIDS 

 UPDATE SUBCRECONS SET RECONID=T.NEWRECONID FROM #TEMP0 T INNER JOIN SUBCRECONS ON SUBCRECONS.RECONID=T.RECONID 
 UPDATE ACCBOQHEADER SET RECONID = T.NEWRECONID FROM #TEMP0 T INNER JOIN ACCBOQHEADER ON ACCBOQHEADER.RECONID= T.RECONID 
 UPDATE SUBCRECONDETAIL SET RECONID=T.NEWRECONID FROM #TEMP0 T INNER JOIN SUBCRECONDETAIL ON SUBCRECONDETAIL.RECONID =T.RECONID 
 UPDATE CONTRAS SET  CONTRARECONID = T.NEWRECONID FROM #TEMP0 T INNER JOIN CONTRAS ON CONTRAS.CONTRARECONID = T.RECONID 






 