/****** Object:  Procedure [BS].[spCheckMissingTDS]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE  BS.spCheckMissingTDS
as

SELECT DISTINCT TRANGRP   INTO #TRANGRP FROM TRANSACTIONS WHERE YEAR>=2015 AND LEFT(BATCHREF,3)='SCI'
ALTER TABLE #TRANGRP ADD TDSTRANSID INT
UPDATE #TRANGRP SET TDSTRANSID = 0

UPDATE #TRANGRP 
SET TDSTRANSID = TRANSID 
FROM TRANSACTIONS INNER JOIN #TRANGRP ON #TRANGRP.TRANGRP  = TRANSACTIONS.TRANGRP AND
TRANSACTIONS.LEDGERCODE= '1310005'   

SELECT * FROM #TRANGRP WHERE TDSTRANSID=0 