/****** Object:  Procedure [BS].[spCheckDepreciationPostings]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE [BS].[spCheckDepreciationPostings](@FINYEAR INT,@PERIOD INT)
AS

--DELETE  FROM VRTEMPA
--FIRST LINE TO EXECUTE BEFORE DOING THIS TASK 

DECLARE @STARTDATE DATETIME
DECLARE @ENDDATE DATETIME

DECLARE @STARTDATESTRING VARCHAR(15)
DECLARE @ENDDATESTRING   VARCHAR(15)

 

IF @PERIOD BETWEEN 1 AND 9 
     SET @STARTDATESTRING = '01/'+ LTRIM(RTRIM(STR(@PERIOD+3)))+'/'+LTRIM(RTRIM(STR(@FINYEAR-1))) 
  ELSE
     SET @STARTDATESTRING = '01/'+ LTRIM(RTRIM(STR(@PERIOD-9)))+ '/'+STR(@FINYEAR)
 


SELECT @STARTDATE = CONVERT(DATETIME,@STARTDATESTRING,103) 
SELECT @ENDDATE   = PEDATE FROM PERIODSETUP WHERE ORGID=2 AND YEAR=@FINYEAR AND PERIOD=@PERIOD 

SELECT @STARTDATE,@ENDDATE 

SELECT ASSETNUMBER INTO #TEMP0  FROM ASSETS WHERE ASSETPDATE BETWEEN @STARTDATE AND @ENDDATE 

--CREATE TABLE VRTEMPA(ASSETNUMBER VARCHAR(25),YEAR INT,PERIOD INT)
--INSERT INTO VRTEMPA 
--SELECT ASSETNUMBER,YEAR,PERIOD  FROM VRBIPOSTS260617 
--WHERE YEAR=@FINYEAR AND PERIOD<@PERIOD AND ASSETNUMBER IN (SELECT ASSETNUMBER FROM #TEMP0) 

--SELECT * FROM VRTEMPA 

--SELECT ASSETNUMBER,COUNT(*) FROM #TEMPA ORDER BY ASSETNUMBER 

SELECT ASSETNUMBER,YEAR,PERIOD 
INTO #TEMPTODELETE 
FROM BI.ASSETPOSTS 
WHERE YEAR=@FINYEAR AND PERIOD<@PERIOD AND ASSETNUMBER IN (SELECT ASSETNUMBER FROM #TEMP0) 

SELECT ASSETNUMBER,COUNT(*) CNT
INTO #TEMPFINAL 
FROM #TEMPTODELETE
GROUP BY ASSETNUMBER 
ORDER BY ASSETNUMBER 

SELECT * FROM #TEMPTODELETE
SELECT * FROM #TEMPFINAL 

DELETE FROM BI.ASSETPOSTS WHERE YEAR=@FINYEAR AND PERIOD<@PERIOD AND ASSETNUMBER IN (SELECT ASSETNUMBER FROM #TEMP0) 

UPDATE ASSETS SET AssetDepProg = ASSETDEPPROG - F.CNT  FROM #TEMPFINAL F INNER JOIN ASSETS ON ASSETS.ASSETNUMBER=F.ASSETNUMBER 
 