/****** Object:  Procedure [BS].[spCheckDuplicateSCIOTERS]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE [BS].[spCheckDuplicateSCIOTERS]
AS
SELECT ORGID,YEAR,PERIOD,PDATE,BATCHREF,TRANSREF,CREDNO,CREDIT,ORDERNO,COUNT(*) COUNTS
FROM TRANSACTIONS WHERE LEFT(BATCHREF,3)='SCI' AND YEAR=2019 AND LEDGERCODE='1320000' AND PERIOD>6
GROUP BY ORGID,YEAR,PERIOD,PDATE,BATCHREF,TRANSREF,CREDNO,CREDIT,ORDERNO
HAVING COUNT(*)>1
ORDER BY  PERIOD 


SELECT ORGID,YEAR,PERIOD,PDATE,BATCHREF,TRANSREF,CREDNO,CREDIT,ORDERNO,COUNT(*) COUNTS
FROM TRANSACTIONS WHERE LEFT(BATCHREF,3)='DTI' AND YEAR=2019 AND LEDGERCODE BETWEEN '2540000' 
AND '2540005'  AND PERIOD>6
GROUP BY ORGID,YEAR,PERIOD,PDATE,BATCHREF,TRANSREF,CREDNO,CREDIT,ORDERNO
HAVING COUNT(*)>1
ORDER BY  PERIOD 


SELECT * FROM CONTROLCODES 