/****** Object:  Procedure [BS].[spDeletePlant]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE BS.spDeletePlant(@PLANTNO VARCHAR(15))
AS
DELETE FROM PlantHireRates WHERE PENUMBER IN (SELECT PENUMBER FROM PLANTANDEQ WHERE PENAME LIKE 'PRIMAVERA%')
DELETE FROM PLANTHIREDETAIL WHERE PENUMBER IN (SELECT PENUMBER FROM PLANTANDEQ WHERE PENAME LIKE 'PRIMAVERA%')
DELETE FROM PLANTANDEQ WHERE PENUMBER IN ( (SELECT PENUMBER FROM PLANTANDEQ WHERE PENAME LIKE 'PRIMAVERA%') )  