/****** Object:  Procedure [BS].[spDropCancelledDeliveries]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE  PROCEDURE [BS].[spDropCancelledDeliveries]
as

DECLARE @DLVRID INT
DECLARE @ORGID INT
DECLARE @ORDID INT
DECLARE @LINENO INT
DECLARE @DLVRQTY DECIMAL(18,2)
DECLARE @MATCHFOUND INT 
DECLARE @PRICE DECIMAL(18,2)
DECLARE @COUNTER INT
DECLARE @LINECOUNT INT
DECLARE @QTYTOMATCH DECIMAL(18,2) 
DECLARE @CHECKQTY DECIMAL(18,2) 

SELECT DLVRID,TBORGID,ORDID,ORDITEMLINENO,DLVRQTY,PRICE  INTO #TEMP1 FROM DELIVERIES WHERE DLVRQTY<0   AND RECONQTY=0 


SELECT DLVRID,TBORGID,ORDID,ORDITEMLINENO,DLVRQTY,PRICE INTO #TEMP2 FROM #TEMP1  
ALTER TABLE #TEMP2 ADD MATCHFOUND INT
UPDATE #TEMP2 SET MATCHFOUND=3



CREATE TABLE #TEMP3 (DLVRID INT,TBORGID INT,ORDID INT,ORDITEMLINENO INT,DLVRQTY DECIMAL(18,2),PRICE DECIMAL(18,2) ,REFDLVRID INT) 



 
-- EXACT MATCH DROPPING

DECLARE MATCHFINDING CURSOR FOR SELECT * FROM #TEMP2 ORDER BY DLVRID 
OPEN MATCHFINDING

FETCH NEXT FROM MATCHFINDING INTO @DLVRID,@ORGID,@ORDID,@LINENO,@DLVRQTY,@PRICE,@MATCHFOUND

WHILE @@FETCH_STATUS = 0
BEGIN

 SELECT D.DLVRID,D.TBORGID,D.ORDID,D.ORDITEMLINENO,D.DLVRQTY,D.PRICE,@DLVRID REFDLVRID  INTO #TEMP4
  FROM DELIVERIES D WHERE TBORGID=@ORGID AND ORDID=@ORDID AND ORDITEMLINENO = @LINENO AND
  (DLVRQTY-RECONQTY) = ABS(@DLVRQTY) AND DLVRID NOT IN (SELECT DLVRID FROM #TEMP2) 
  AND DLVRID < @DLVRID 
 
 SET @LINECOUNT = 0
 SELECT @LINECOUNT = COUNT(*) FROM #TEMP4 
 IF @LINECOUNT > 0
 BEGIN
    INSERT INTO #TEMP3 
    SELECT * FROM #TEMP4

    UPDATE #TEMP2 SET MATCHFOUND=1 WHERE DLVRID=@DLVRID 
 END
 
 DROP TABLE #TEMP4

 FETCH NEXT FROM MATCHFINDING INTO @DLVRID,@ORGID,@ORDID,@LINENO,@DLVRQTY,@PRICE,@MATCHFOUND 
END

CLOSE MATCHFINDING
DEALLOCATE MATCHFINDING
 
 


--INSERT INTO BS.GRNDROPPED
--SELECT  T2.DLVRID ORIGINAL,T3.DLVRID REVERSAL   FROM #TEMP2 T2 INNER JOIN #TEMP3 T3 ON T2.DLVRID = T3.REFDLVRID 
 


---- SUM VALUES  MATCH DROPPING

DECLARE MATCHFINDING CURSOR FOR SELECT * FROM #TEMP2 WHERE MATCHFOUND=3 ORDER  BY DLVRID 
OPEN MATCHFINDING

FETCH NEXT FROM MATCHFINDING INTO @DLVRID,@ORGID,@ORDID,@LINENO,@DLVRQTY,@PRICE,@MATCHFOUND

WHILE @@FETCH_STATUS = 0
BEGIN

 SET @QTYTOMATCH = ABS(@DLVRQTY) 
 
 SELECT DLVRID,DLVRQTY INTO #TEMP5 FROM DELIVERIES WHERE RECONQTY=0 AND DLVRQTY > 0 AND  DLVRID <@DLVRID AND DLVRID NOT IN (SELECT DLVRID FROM #TEMP3) AND
 TBORGID=@ORGID AND ORDID=@ORDID AND ORDITEMLINENO = @LINENO
 SELECT @CHECKQTY = SUM(DLVRQTY) FROM #TEMP5 
 

 IF @CHECKQTY = @QTYTOMATCH 
  BEGIN
    SELECT D.DLVRID,D.TBORGID,D.ORDID,D.ORDITEMLINENO,D.DLVRQTY,D.PRICE,@DLVRID REFDLVRID  INTO #TEMP6
    FROM DELIVERIES D WHERE DLVRID IN (SELECT DLVRID FROM #TEMP5) 

    INSERT INTO #TEMP3 
    SELECT * FROM #TEMP6
	

    UPDATE #TEMP2 SET MATCHFOUND=4 WHERE DLVRID=@DLVRID 
 
	DROP TABLE #TEMP6
 END
 
 
 DROP TABLE #TEMP5

 FETCH NEXT FROM MATCHFINDING INTO @DLVRID,@ORGID,@ORDID,@LINENO,@DLVRQTY,@PRICE,@MATCHFOUND 
END

CLOSE MATCHFINDING
DEALLOCATE MATCHFINDING


--INSERT INTO BS.GRNDROPPED
--SELECT  T2.DLVRID ORIGINAL,T3.DLVRID REVERSAL   FROM #TEMP2 T2 INNER JOIN #TEMP3 T3 ON T2.DLVRID = T3.REFDLVRID 


SELECT * FROM #TEMP2 WHERE MATCHFOUND=3

 

























----SELECT * FROM #TEMP2 WHERE MATCHFOUND=3  

--SELECT T2.*,T3.* FROM #TEMP2 T2 LEFT   JOIN #TEMP3 T3 ON T2.DLVRID = T3.REFDLVRID 