/****** Object:  Procedure [BS].[spFetchPB]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE [BS].[spFetchPB](@APPROVER VARCHAR(10),@BATCHTYPE VARCHAR(1),@ORGID INT  )
AS

DECLARE @FINYEAR INT 
DECLARE @BATCHUNIQUEID INT
DECLARE @CURRENTBATCHNO INT 
DECLARE @CURRENTORGID INT
DECLARE @CURRENTBATCHTYPE VARCHAR(1) 

DECLARE @CREDITORLEDGERCODE VARCHAR(15)
DECLARE @SUBBIELEDGERCODE   VARCHAR(15)

SET @CREDITORLEDGERCODE = '1315000'
SET @SUBBIELEDGERCODE ='1320000' 

SELECT @FINYEAR =  MIN(YEAR) FROM PERIODSETUP WHERE ORGID=2 AND STATUS=0 AND PERIOD BETWEEN 1 AND 12


CREATE TABLE #BATCHSUMMARY(BATCHUNIQUEID INT PRIMARY KEY IDENTITY(1,1), BATCHNO INT, BATORGID INT,BATPROCESS VARCHAR(1),BATDESC VARCHAR(150),BATSTATUS INT, BATOWNER VARCHAR(15))
IF @BATCHTYPE ='Z'
BEGIN 
   -- ALL BATCHES 
   INSERT INTO #BATCHSUMMARY
   SELECT BATCHNO,BATORGID,BATPROCESS,BATDESC,BATSTATUS,BATOWNER
   FROM  BATCHREMIT
   WHERE
         BATOWNER = @APPROVER AND 
	     BATSTATUS =1  
		 
END

IF @BATCHTYPE <>'Z'
BEGIN 
   -- SELECTED TYPE CREDITOR/SUBBIE 
   INSERT INTO #BATCHSUMMARY
   SELECT BATCHNO,BATORGID,BATPROCESS,BATDESC,BATSTATUS,BATOWNER
   FROM  BATCHREMIT
   WHERE
         BATOWNER = @APPROVER AND 
         BATPROCESS=@BATCHTYPE AND 
	     BATSTATUS =1 
END

IF @ORGID <> -1
   DELETE FROM #BATCHSUMMARY WHERE BATORGID <>@ORGID 

 

ALTER TABLE #BATCHSUMMARY ADD PARTYCODE VARCHAR(15)
ALTER TABLE #BATCHSUMMARY ADD PARTYNAME VARCHAR(100)
ALTER TABLE #BATCHSUMMARY ADD USERNAME  VARCHAR(100)
ALTER TABLE #BATCHSUMMARY ADD PAYMENTRECOMMENDED DECIMAL(18,2)




UPDATE #BATCHSUMMARY 
SET USERNAME =UPPER(U.USERNAME)
FROM USERS U 
INNER JOIN #BATCHSUMMARY ON #BATCHSUMMARY.BATOWNER = U.LOGINID 

 
CREATE TABLE #TOTALTRANSACTIONS
(BATCHUNIQUEID INT , ORGID INT, CREDNO VARCHAR(15), PARTYNAME VARCHAR(200),
LEDGERCODE VARCHAR(15), TRANSID INT, INVOICEVALUE DECIMAL(18,2), 
PAIDTODATE DECIMAL(18,2), PAIDTHISPERIOD DECIMAL(18,2),RECONSTATUS INT,BATCHTYPE VARCHAR(1),DESCRIPTION VARCHAR(200),
INVOICENUMBER VARCHAR(20),INVOICEDATE DATETIME ) 

 

DECLARE BATCHLIST CURSOR 
FOR SELECT BATCHUNIQUEID , BATCHNO INT, BATORGID, BATPROCESS FROM #BATCHSUMMARY

OPEN BATCHLIST
FETCH NEXT FROM BATCHLIST INTO @BATCHUNIQUEID, @CURRENTBATCHNO, @CURRENTORGID ,@CURRENTBATCHTYPE

WHILE @@FETCH_STATUS = 0 
BEGIN
   IF @CURRENTBATCHTYPE ='C'
    INSERT INTO #TOTALTRANSACTIONS
	SELECT @BATCHUNIQUEID,ORGID,CREDNO,'',LEDGERCODE,TRANSID,(CREDIT-DEBIT) INVOICEVALUE,PAIDTODATE,PAIDTHISPERIOD,RECONSTATUS,@CURRENTBATCHTYPE,
	LEFT(DESCRIPTION,200),TRANSREFEXT,PDATE
	FROM TRANSACTIONS  
	WHERE  TRANSACTIONS.RECONSTATUS = @CURRENTBATCHNO AND TRANSACTIONS.ORGID=@CURRENTORGID 
	AND    LEDGERCODE = @CREDITORLEDGERCODE  
   IF @CURRENTBATCHTYPE ='S'
    INSERT INTO #TOTALTRANSACTIONS
	SELECT @BATCHUNIQUEID,ORGID,CREDNO,'',LEDGERCODE,TRANSID,(CREDIT-DEBIT) INVOICEVALUE,PAIDTODATE,PAIDTHISPERIOD,RECONSTATUS,@CURRENTBATCHTYPE,
	LEFT(DESCRIPTION,200),TRANSREFEXT,PDATE
	FROM TRANSACTIONS  
	WHERE  TRANSACTIONS.RECONSTATUS = @CURRENTBATCHNO AND TRANSACTIONS.ORGID=@CURRENTORGID  
	AND LEDGERCODE = @SUBBIELEDGERCODE  

    FETCH NEXT FROM BATCHLIST INTO @BATCHUNIQUEID, @CURRENTBATCHNO, @CURRENTORGID ,@CURRENTBATCHTYPE
	
END
CLOSE BATCHLIST
DEALLOCATE BATCHLIST 
 
 
 

UPDATE #TOTALTRANSACTIONS
SET PARTYNAME = C.CREDNAME FROM CREDITORS C INNER JOIN #TOTALTRANSACTIONS ON #TOTALTRANSACTIONS.CREDNO = C.CREDNUMBER
UPDATE #TOTALTRANSACTIONS
SET PARTYNAME = S.SUBNAME FROM SUBCONTRACTORS S INNER JOIN #TOTALTRANSACTIONS ON #TOTALTRANSACTIONS.CREDNO = S.SUBNUMBER 

 
SELECT ORGID, RECONSTATUS,CREDNO,SUM(PAIDTHISPERIOD) PAYMENTRECOMMENDED
INTO #PAYMENTRECOMMENDED 
FROM #TOTALTRANSACTIONS
GROUP BY  ORGID, RECONSTATUS,CREDNO  
 

SELECT DISTINCT ORGID, RECONSTATUS,CREDNO 
INTO #BATCHNOS
FROM #TOTALTRANSACTIONS 
  

UPDATE #BATCHSUMMARY 
SET PARTYCODE = #BATCHNOS.CREDNO 
FROM #BATCHNOS INNER JOIN #BATCHSUMMARY 
ON #BATCHNOS.RECONSTATUS = #BATCHSUMMARY.BATCHNO AND #BATCHNOS.ORGID = #BATCHSUMMARY.BATORGID 


UPDATE #BATCHSUMMARY 
SET PAYMENTRECOMMENDED = T.PAYMENTRECOMMENDED
FROM #PAYMENTRECOMMENDED T 
INNER JOIN  #BATCHSUMMARY ON #BATCHSUMMARY.BATCHNO=T.RECONSTATUS AND  #BATCHSUMMARY.PARTYCODE=T.CREDNO AND  #BATCHSUMMARY.BATORGID =T.ORGID 



CREATE TABLE #TOTALOUTSTANDING (ORGID INT, CREDNO VARCHAR(15), TOTALOUTSTANDING DECIMAL(18,2)) 
INSERT INTO #TOTALOUTSTANDING
SELECT ORGID, CREDNO,SUM(CREDIT-DEBIT) TOTALOUTSTANDING 
FROM TRANSACTIONS 
WHERE YEAR = @FINYEAR AND 
      LEDGERCODE = @CREDITORLEDGERCODE  AND 
	  CREDNO IN (SELECT CREDNO FROM #BATCHNOS)  
GROUP BY ORGID, CREDNO 
 

INSERT INTO #TOTALOUTSTANDING
SELECT ORGID,CREDNO,SUM(CREDIT-DEBIT) TOTALOUTSTANDING 
FROM TRANSACTIONS 
WHERE YEAR = @FINYEAR AND 
      LEDGERCODE = @SUBBIELEDGERCODE   AND 
	  CREDNO IN (SELECT CREDNO FROM #BATCHNOS)  
GROUP BY ORGID,CREDNO 


 
SELECT BATCHUNIQUEID,
       BATCHTYPE,
	   RECONSTATUS,
       ORGID,
	   CREDNO,
	   PARTYNAME,
	   SUM(PAIDTHISPERIOD) PAYMENTAMOUNT
INTO
       #TOTALTRANSACTIONSUMMARY
FROM 
       #TOTALTRANSACTIONS
GROUP BY 
       BATCHUNIQUEID,
	   BATCHTYPE,
	   RECONSTATUS,
	   ORGID,
	   CREDNO,
	   PARTYNAME

 
 




ALTER TABLE #TOTALTRANSACTIONSUMMARY ADD TOTALOUTSTANDING DECIMAL(18,2)
UPDATE #TOTALTRANSACTIONSUMMARY 
SET TOTALOUTSTANDING = TT.TOTALOUTSTANDING 
FROM #TOTALOUTSTANDING TT 
INNER JOIN #TOTALTRANSACTIONSUMMARY ON #TOTALTRANSACTIONSUMMARY.ORGID = TT.ORGID AND #TOTALTRANSACTIONSUMMARY.CREDNO = TT.CREDNO 

UPDATE #TOTALTRANSACTIONSUMMARY SET TOTALOUTSTANDING = TOTALOUTSTANDING+PAYMENTAMOUNT 

SELECT ORGID,RECONSTATUS,COUNT(DISTINCT CREDNO) SUPPLIERCOUNT 
INTO #SUPPLIERCOUNTS
FROM #TOTALTRANSACTIONS
GROUP BY ORGID,RECONSTATUS 

 
ALTER TABLE #BATCHSUMMARY ADD NUMBEROFSUPPLIERS INT
UPDATE #BATCHSUMMARY SET NUMBEROFSUPPLIERS = SC.SUPPLIERCOUNT FROM #SUPPLIERCOUNTS SC INNER JOIN #BATCHSUMMARY 
ON #BATCHSUMMARY.BATORGID = SC.ORGID  AND #BATCHSUMMARY.BATCHNO =SC.RECONSTATUS 

ALTER TABLE #BATCHSUMMARY ADD MULTIPLEPARTY VARCHAR(10)
UPDATE #BATCHSUMMARY SET MULTIPLEPARTY = ''
UPDATE #BATCHSUMMARY SET MULTIPLEPARTY='RTGS' WHERE  NUMBEROFSUPPLIERS>1
 
UPDATE #BATCHSUMMARY SET PARTYNAME = C.CREDNAME FROM CREDITORS C INNER JOIN #BATCHSUMMARY ON #BATCHSUMMARY.PARTYCODE=C.CREDNUMBER
UPDATE #BATCHSUMMARY SET PARTYNAME = S.SUBNAME  FROM SUBCONTRACTORS S INNER JOIN #BATCHSUMMARY ON #BATCHSUMMARY.PARTYCODE = S.SUBNUMBER

ALTER TABLE #BATCHSUMMARY ADD PROJECTNAME VARCHAR(150)
UPDATE #BATCHSUMMARY SET PROJECTNAME =UPPER(B.BORGNAME) FROM BORGS B INNER JOIN #BATCHSUMMARY ON #BATCHSUMMARY.BATORGID=B.BORGID 

ALTER TABLE #BATCHSUMMARY ADD BATCHMODEL VARCHAR(20)
UPDATE #BATCHSUMMARY SET BATCHMODEL = 'Creditor'  WHERE BATPROCESS='C'
UPDATE #BATCHSUMMARY SET BATCHMODEL = 'SubCon'  WHERE BATPROCESS='S'

CREATE  TABLE #UID(SLNO INT PRIMARY KEY IDENTITY(1,1),ID INT)
INSERT INTO #UID
SELECT BATCHUNIQUEID 
FROM #BATCHSUMMARY ORDER BY BATCHMODEL,PROJECTNAME

 

ALTER TABLE #BATCHSUMMARY ADD SLNO INT 
ALTER TABLE #TOTALTRANSACTIONSUMMARY  ADD SLNO INT
ALTER TABLE #TOTALTRANSACTIONS ADD SLNO INT
UPDATE #BATCHSUMMARY SET SLNO = #UID.SLNO FROM #UID INNER JOIN #BATCHSUMMARY ON #BATCHSUMMARY.BATCHUNIQUEID= #UID.ID
UPDATE #TOTALTRANSACTIONSUMMARY SET SLNO = #UID.SLNO FROM #UID INNER JOIN #TOTALTRANSACTIONSUMMARY ON #TOTALTRANSACTIONSUMMARY.BATCHUNIQUEID= #UID.ID
UPDATE #TOTALTRANSACTIONS SET SLNO = #UID.SLNO FROM #UID INNER JOIN #TOTALTRANSACTIONS ON #TOTALTRANSACTIONS.BATCHUNIQUEID= #UID.ID

ALTER TABLE #BATCHSUMMARY ADD TOTALOUTSTANDING DECIMAL(18,2)
UPDATE #BATCHSUMMARY SET TOTALOUTSTANDING = T.TOTALOUTSTANDING FROM #TOTALOUTSTANDING T INNER JOIN #BATCHSUMMARY ON #BATCHSUMMARY.BATORGID=T.ORGID AND #BATCHSUMMARY.PARTYCODE=T.CREDNO 


SELECT SLNO,BATCHMODEL,LEFT(PROJECTNAME,50) PROJECTNAME,BATCHNO,BATDESC  AS HEADER,PARTYCODE,LEFT(PARTYNAME,60) PARTYNAME,PAYMENTRECOMMENDED,TOTALOUTSTANDING,MULTIPLEPARTY,BATORGID,BATPROCESS, 1 AS  APPROVED FROM #BATCHSUMMARY ORDER BY SLNO 
SELECT SLNO,CREDNO,PARTYNAME,TOTALOUTSTANDING,PAYMENTAMOUNT FROM #TOTALTRANSACTIONSUMMARY ORDER BY SLNO 
SELECT SLNO,ORGID,CREDNO,PARTYNAME,DESCRIPTION,INVOICENUMBER,INVOICEDATE,INVOICEVALUE,PAIDTODATE,PAIDTHISPERIOD FROM #TOTALTRANSACTIONS ORDER BY SLNO