/****** Object:  Procedure [BS].[spFixCBD_DEL]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE  PROCEDURE [BS].[spFixCBD_DEL]
AS

DECLARE @TRANSID INT
DECLARE @DESCRIPTION VARCHAR(250)
DECLARE @BANKSTART VARCHAR(10)
DECLARE @BANKEND   VARCHAR(10)

SELECT TRANSID,'Order Number '+ LTRIM(RTRIM(ORDERNO)) NEWDESCRIPTION 
INTO #TEMP0
FROM TRANSACTIONS 
WHERE LEDGERCODE='1315000' AND TRANSTYPE='DEL' AND DESCRIPTION='' 
SELECT * FROM #TEMP0 
UPDATE TRANSACTIONS SET DESCRIPTION = T.NEWDESCRIPTION FROM #TEMP0 T INNER JOIN TRANSACTIONS ON TRANSACTIONS.TRANSID = T.TRANSID 
DROP TABLE #TEMP0 

SELECT @BANKSTART=CONTROLFROMGL ,@BANKEND=CONTROLTOGL FROM CONTROLCODES WHERE CONTROLNAME='Bank'
CREATE TABLE #LEDGERCODE(LEDGERCODE VARCHAR(10)) 
INSERT INTO #LEDGERCODE 
SELECT ICGLCODE FROM BORGS 

INSERT INTO #LEDGERCODE 
SELECT LEDGERCODE FROM LEDGERCODES WHERE LEDGERCODE  BETWEEN @BANKSTART AND @BANKEND

UPDATE TRANSACTIONS SET DESCRIPTION = LTRIM(RTRIM(DESCRIPTION)) WHERE LEFT(TRANSTYPE,3)='CBD'    

SELECT TRANGRP,DESCRIPTION AS CBDNARRATION
INTO #CBDDESCRIPTION 
FROM TRANSACTIONS
WHERE ASCII(LEFT(DESCRIPTION,1))<>160
AND TRANGRP IN (
  SELECT DISTINCT TRANGRP  
  FROM TRANSACTIONS 
  WHERE LEFT(TRANSTYPE,3)='CBD'  AND ASCII(LEFT(DESCRIPTION,1))=160 AND PERIOD<>0 AND YEAR>=2016 )

--SELECT T.TRANSID , T.LEDGERCODE, L.LEDGERNAME 
--INTO #LEDGERNAME 
--FROM TRANSACTIONS T
--INNER JOIN LEDGERCODES L
--ON T.LEDGERCODE = L.LEDGERCODE AND 
--LEFT(T.TRANSTYPE,3)='CBD' AND T.LEDGERCODE IN (SELECT LEDGERCODE FROM #LEDGERCODE) AND ASCII(LEFT(T.DESCRIPTION,1))=160
 
UPDATE TRANSACTIONS  
SET DESCRIPTION = LTRIM(RTRIM(CBDNARRATION)) 
FROM #CBDDESCRIPTION INNER JOIN TRANSACTIONS ON TRANSACTIONS.TRANGRP = #CBDDESCRIPTION.TRANGRP 
WHERE  ASCII(LEFT(DESCRIPTION,1))=160