/****** Object:  Procedure [BS].[spFix163TDS]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE BS.spFix163TDS
AS

DECLARE @BATCHREF VARCHAR(10)
DECLARE @TRANSREF VARCHAR(10)
DECLARE @TRANGRP  INT
DECLARE @WHTID INT
 
DECLARE BATCHLIST CURSOR FOR 
SELECT DISTINCT BATCHREF,TRANSREF,TRANGRP  FROM TRANSACTIONS WHERE YEAR=2016 AND 
ORDERNO IN (SELECT ORDERNO FROM SUBCRECONS WHERE CODE='16.3')   AND PERIOD<>0  

OPEN BATCHLIST
FETCH NEXT FROM BATCHLIST INTO @BATCHREF,@TRANSREF,@TRANGRP 

WHILE @@FETCH_STATUS=0
BEGIN
  SET @WHTID=-1
  SELECT @WHTID =ISNULL(WHTID,-1)  FROM TRANSACTIONS WHERE BATCHREF=@BATCHREF AND TRANSREF= @TRANSREF  AND TRANGRP = @TRANGRP AND SUBCONTRAN='Certified Amount    '
  UPDATE TRANSACTIONS SET WHTID = @WHTID WHERE LEDGERCODE='1310005' AND BATCHREF=@BATCHREF AND TRANSREF= @TRANSREF  AND TRANGRP = @TRANGRP  AND @WHTID<>-1
  FETCH NEXT FROM BATCHLIST INTO @BATCHREF,@TRANSREF,@TRANGRP 


END
CLOSE BATCHLIST
DEALLOCATE BATCHLIST
                               
 