/****** Object:  Procedure [BS].[spFORMWORKVALUE]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE BS.spFORMWORKVALUE
AS

DECLARE @FILENAME VARCHAR(100)
DECLARE @FILEID   VARCHAR(10)
DECLARE @SQL      VARCHAR(250)

SET @FILENAME = 'BSBS_TEMP.DBO.FORMWORK'


SELECT T.STKSTORE,V.STORENAME,T.AMOUNT 
INTO  #TEMP0 
FROM (
       SELECT STKSTORE,SUM(STKQUANTITY*STKCOSTRATE) AMOUNT FROM INVENTORY WHERE LEFT(STKSTORE,3)='FWK' GROUP BY STKSTORE ) T
INNER JOIN INVSTORES V ON T.STKSTORE=V.STORECODE  ORDER BY T.STKSTORE 

SELECT @FILEID= CONVERT(INT,RAND( (DATEPART(mm, GETDATE()) * 100000 )
+ (DATEPART(ss, GETDATE()) * 1000 )
+ DATEPART(ms, GETDATE()) )*1000)

SET @FILENAME = @FILENAME+LTRIM(RTRIM(CONVERT(VARCHAR(3),@FILEID)))

 
SET @SQL = 'SELECT *  INTO '+@FILENAME+ ' FROM   #TEMP0    '
 
EXEC(@SQL)

RETURN @FILEID