/****** Object:  Procedure [BS].[spFormSEStock]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE  [BS].[spFormSEStock](@BORGID INT)
AS
DECLARE @FILENAME VARCHAR(100)
DECLARE @FILEID   VARCHAR(10)
DECLARE @SQL      VARCHAR(250)
DECLARE @ORGID INT

SET @FILENAME = 'BSBS_TEMP.DBO.FORMSITE'

 
DECLARE @BORGSHORTCODE VARCHAR(5)
DECLARE @FORMWORKSTORE VARCHAR(15) 
DECLARE @SITEESTABLISHSTORE  VARCHAR(15)

SELECT @BORGSHORTCODE =LEFT(BORGNAME,5) FROM BORGS WHERE BORGID=@BORGID
SET @FORMWORKSTORE = 'FWK-'+LTRIM(RTRIM(@BORGSHORTCODE))
SET @SITEESTABLISHSTORE = 'SE-'+LTRIM(RTRIM(@BORGSHORTCODE))

SELECT STKSTORE,STKCODE,STKDESC,STKUNIT  ,StkQuantity, STKCOSTRATE ,LEFT(STKSTORE,2) AS STORETYPE
INTO #TEMP0 
FROM INVENTORY 
WHERE BORGID=2 AND STKSTORE IN (@FORMWORKSTORE,@SITEESTABLISHSTORE) AND STKQUANTITY>0 


SELECT @FILEID= CONVERT(INT,RAND( (DATEPART(mm, GETDATE()) * 100000 )
+ (DATEPART(ss, GETDATE()) * 1000 )
+ DATEPART(ms, GETDATE()) )*1000)

SET @FILENAME = @FILENAME+LTRIM(RTRIM(CONVERT(VARCHAR(3),@FILEID)))
SELECT @FILENAME 
SET @SQL = 'SELECT *  INTO '+@FILENAME+ ' FROM   #TEMP0  ORDER BY STKSTORE,STKCODE'

EXEC(@SQL)

RETURN @FILEID