/****** Object:  Procedure [BS].[spGenerateAssetSummarySheet]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE [BS].[spGenerateAssetSummarySheet](@OPENINGDATE VARCHAR(15), @ENDDATE VARCHAR(15))
AS
    DECLARE @TRANSSTARTDATE    DATETIME
	DECLARE @TRANSENDDATE      DATETIME
    SELECT  @TRANSSTARTDATE = CONVERT(DATETIME, @OPENINGDATE,103) -- dd/mm/yyyy 
	SELECT  @TRANSENDDATE   = CONVERT(DATETIME, @ENDDATE,103) -- dd/mm/yyyy 

	SELECT @TRANSSTARTDATE,@TRANSENDDATE 

	CREATE TABLE #ASSETSUMMARY(LEDGERCODE VARCHAR(10),LEDGERNAME VARCHAR(150),OPENING DECIMAL(18,0), ADDITIONS DECIMAL(18,0), DELETIONS DECIMAL(18,0), CLOSING DECIMAL(18,0),
	OPENIGDEP  DECIMAL(18,0), ADDITIONSDEP DECIMAL(18,0), DELETIONSDEP DECIMAL(18,0), CLOSINGDEP DECIMAL(18,0),NETVALUE DECIMAL(18,0)  ) 

	SELECT 
	  ASSETOPPCODE,SUM(ASSETPPRICE) OPENING   
	  INTO #TEMP0 
	  FROM ASSETS 
	  WHERE AssetPDate <  @TRANSSTARTDATE 
      GROUP BY ASSETOPPCODE  

	INSERT INTO #ASSETSUMMARY(LEDGERCODE,OPENING ) 
	SELECT * FROM #TEMP0 

	UPDATE #ASSETSUMMARY SET ADDITIONS = 0.0, ADDITIONSDEP = 0.0 ,OPENIGDEP=0
	select * from #temp0 
	SELECT LEDGERCODE,SUM(CREDIT-DEBIT) OPENINGDEP 
	INTO #TEMPOPDEP
	FROM TRANSACTIONS WHERE ORGID=2  AND YEAR=2017 AND PERIOD=0 AND LEDGERCODE IN (SELECT ASSETOPPCODE FROM #TEMP0) GROUP BY LEDGERCODE 
	select * from #TEMPOPDEP
	UPDATE #ASSETSUMMARY SET OPENIGDEP = TP.OPENINGDEP FROM #TEMPOPDEP TP INNER JOIN #ASSETSUMMARY ON #ASSETSUMMARY.LEDGERCODE =TP.LEDGERCODE 


 
  

	SELECT 
	  ASSETOPPCODE,SUM(ASSETPPRICE) SUMADDITIONS   
	  INTO #TEMP1 
	  FROM ASSETS 
	  WHERE CONVERT(DATE,AssetPDate) >=  @TRANSSTARTDATE AND CONVERT(DATE,ASSETPDATE)<=   @TRANSENDDATE
      GROUP BY ASSETOPPCODE  
     SELECT * FROM #TEMP1 


    DECLARE @STARTPERIOD INT 
	DECLARE @ENDPERIOD INT

	IF @TRANSSTARTDATE = '01-APR-2016'  
	   SET @STARTPERIOD = 1
	IF @TRANSSTARTDATE = '31-MAY-2016' 
	   SET @STARTPERIOD = 2
	IF @TRANSSTARTDATE = '01-JAN-2017' 
	   SET @STARTPERIOD = 10

    IF @TRANSENDDATE = '30-JUN-2016' 
	   SET @ENDPERIOD = 3
	IF @TRANSENDDATE = '31-JUL-2016' 
	   SET @ENDPERIOD = 4
	IF @TRANSENDDATE = '31-AUG-2016' 
	   SET @ENDPERIOD = 5
	IF @TRANSENDDATE = '30-SEP-2016' 
	   SET @ENDPERIOD = 6 

    IF @TRANSENDDATE = '31-OCT-2016' 
	   SET @ENDPERIOD = 7
	IF @TRANSENDDATE = '30-NOV-2016' 
	   SET @ENDPERIOD = 8
	IF @TRANSENDDATE = '31-DEC-2016' 
	   SET @ENDPERIOD = 9 

	IF @TRANSENDDATE = '31-JAN-2017' 
	   SET @ENDPERIOD = 10
	IF @TRANSENDDATE = '28-FEB-2016' 
	   SET @ENDPERIOD = 11
	IF @TRANSENDDATE = '31-MAR-2016' 
	   SET @ENDPERIOD = 12 


	   SELECT * FROM BI.[ASSETPOSTS] 
	   SELECT @STARTPERIOD,@ENDPERIOD 
    SELECT 
	  LEDGERCODE ,SUM(DEBIT) SUMADDITIONSDEP     
	  INTO #TEMP2 
	  FROM BI.[ASSETPOSTS] 
	  WHERE PERIOD BETWEEN @STARTPERIOD AND @ENDPERIOD  
      GROUP BY LEDGERCODE  


	UPDATE #ASSETSUMMARY 
	SET ADDITIONS = #TEMP1.SUMADDITIONS   FROM #TEMP1 INNER JOIN #ASSETSUMMARY ON #ASSETSUMMARY.LEDGERCODE = #TEMP1.AssetOppCode

	UPDATE #ASSETSUMMARY 
	SET   ADDITIONSDEP =#TEMP2.SUMADDITIONSDEP  FROM #TEMP2 INNER JOIN #ASSETSUMMARY ON #ASSETSUMMARY.LEDGERCODE = #TEMP2.LEDGERCODE

	UPDATE #ASSETSUMMARY SET DELETIONS = 0,DELETIONSDEP = 0.0 
	UPDATE #ASSETSUMMARY SET CLOSING = OPENING+ADDITIONS-DELETIONS
	UPDATE #ASSETSUMMARY SET CLOSINGDEP = OPENIGDEP+ADDITIONSDEP-DELETIONSDEP 
	UPDATE #ASSETSUMMARY SET NETVALUE = CLOSING - CLOSINGDEP 


	UPDATE #ASSETSUMMARY SET LEDGERNAME = 'PLANT AND MACHINERY   ' WHERE LEDGERCODE = '2200001'
	UPDATE #ASSETSUMMARY SET LEDGERNAME = 'FURNITURE AND FIXTURES' WHERE LEDGERCODE = '2200002'
	UPDATE #ASSETSUMMARY SET LEDGERNAME = 'COMPUTERS AND PRINTERS' WHERE LEDGERCODE = '2200003'
	UPDATE #ASSETSUMMARY SET LEDGERNAME = 'FORMWORK              ' WHERE LEDGERCODE = '2200004'
	UPDATE #ASSETSUMMARY SET LEDGERNAME = 'VEHICLES              ' WHERE LEDGERCODE = '2200005'
	UPDATE #ASSETSUMMARY SET LEDGERNAME = 'OFFICE EQUIPMENTS     ' WHERE LEDGERCODE = '2200006'
	UPDATE #ASSETSUMMARY SET LEDGERNAME = 'BUILDINGS             ' WHERE LEDGERCODE = '2200007'
	UPDATE #ASSETSUMMARY SET LEDGERNAME = 'COMPUTER SOFTWARE     ' WHERE LEDGERCODE = '2201000'


	ALTER TABLE #ASSETSUMMARY ADD STARTDATE DATETIME 
	ALTER TABLE #ASSETSUMMARY ADD ENDDATE   DATETIME

	UPDATE #ASSETSUMMARY SET STARTDATE = @TRANSSTARTDATE
	UPDATE #ASSETSUMMARY SET ENDDATE   = @TRANSENDDATE 


	DECLARE @FILENAME VARCHAR(100)
	DECLARE @FILEID   VARCHAR(10)
	DECLARE @SQL      VARCHAR(250)
    DECLARE @ORGID INT

	SET @FILENAME = 'BSBS_TEMP.DBO.ASSETSUMMARY'
	   
    SELECT @FILEID= CONVERT(INT,RAND( (DATEPART(mm, GETDATE()) * 100000 )
	+ (DATEPART(ss, GETDATE()) * 1000 )
	+ DATEPART(ms, GETDATE()) )*1000)

    SET @FILENAME = @FILENAME+LTRIM(RTRIM(CONVERT(VARCHAR(3),@FILEID)))
    SELECT @FILENAME 
    SET @SQL = 'SELECT *  INTO '+@FILENAME+ ' FROM   #ASSETSUMMARY   ORDER BY LEDGERNAME '

    EXEC(@SQL)

  RETURN @FILEID
 