/****** Object:  Procedure [BS].[spGenerateSubbieRegister]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE [BS].[spGenerateSubbieRegister](@BORGID INT,@FINYEAR INT,@STARTPERIOD INT, @ENDPERIOD INT ) 
AS
DECLARE @FILENAME VARCHAR(100)
DECLARE @FILEID   VARCHAR(10)
DECLARE @SQL      VARCHAR(250)
DECLARE @ORGID INT

SET @FILENAME = 'BSBS_TEMP.DBO.SUBBIEREGISTER'


CREATE TABLE #SUBBIE(LEDGERCODE VARCHAR(10)  COLLATE SQL_Latin1_General_CP1_CI_AS )

DECLARE @STARTSUBBIE VARCHAR(10)
DECLARE @ENDSUBBIE   VARCHAR(10)
SELECT  @STARTSUBBIE=CONTROLFROMGL FROM CONTROLCODES WHERE CONTROLNAME='Sub Contractors'
SELECT  @ENDSUBBIE  =CONTROLTOGL   FROM CONTROLCODES WHERE CONTROLNAME='Sub Contractors'
DECLARE @TRANGRP     INT
DECLARE @RETAINED    VARCHAR(10)
DECLARE @WIP         VARCHAR(10)
DECLARE @TRANSID     INT
DECLARE @CREDNO VARCHAR(10) 

DECLARE @ADVANCE VARCHAR(10)
DECLARE @CERTIFIED VARCHAR(10)
DECLARE @VAT  VARCHAR(10)
DECLARE @ST   VARCHAR(10)
DECLARE @RETENTION VARCHAR(10)
DECLARE @WHT  VARCHAR(10)
DECLARE @CONTRA VARCHAR(10)
DECLARE @SUBBIE  VARCHAR(10)
DECLARE @THISWORKDONE DECIMAL(18,2) 
DECLARE @THISNETPAYABLE DECIMAL(18,2)
DECLARE @THISWHT  DECIMAL(18,2) 
DECLARE @THISCONTRA DECIMAL(18,2) 
DECLARE @THISST DECIMAL(18,2) 
DECLARE @ADMINCHARGE VARCHAR(10)
DECLARE @STBYSP VARCHAR(10)

DECLARE @OB DECIMAL(18,2) 
DECLARE @OBRETENTION DECIMAL(18,2)
DECLARE @OBADVANCE DECIMAL(18,2) 

SET @ADVANCE = '1320003'
SET @ST = '1310002'
SET @VAT = '1310000' 
SET @RETENTION = '1320001' 
SET @WHT = '1310005' 
SET @CONTRA = '630313'
SET @SUBBIE = '1320000'
SET @ADMINCHARGE = '5120241'   
SET @STBYSP = '1310008'  

SELECT @RETAINED = CONTROLFROMGL FROM CONTROLCODES WHERE CONTROLNAME='Retained Income'
SELECT @WIP      = CONTROLFROMGL FROM CONTROLCODES WHERE CONTROLNAME='Work In Progress'                  
                    
 

CREATE TABLE #STATEMENT (
   CREDNO VARCHAR(10) 
 , ADVANCE MONEY
 , CERTIFIED MONEY
 , VAT MONEY
 , ST MONEY 
 , RETENTION MONEY
 , CONTRA MONEY 
 , TDS MONEY 
 , ADMINCHARGE MONEY
 , STBYSP MONEY 
 , NETPAYABLE MONEY 
 , PAID MONEY
 , ID  INT
 , PERIOD INT 
 ) 

 

INSERT INTO #SUBBIE 
SELECT LEDGERCODE FROM LEDGERCODES WHERE LEDGERCODE BETWEEN @STARTSUBBIE AND @ENDSUBBIE
--INSERT INTO #SUBBIE VALUES ( @ADVANCE ) REQUIRED TO TAKE CARE DIRECT ADVANCE PAYMENT THROUGH CBC OR PCP 

-- GETTING ALL THE SUBCONTRACTORS 
DECLARE SUBBIES CURSOR FOR
SELECT DISTINCT CREDNO FROM TRANSACTIONS WHERE YEAR=@FINYEAR AND LEDGERCODE=@SUBBIE AND ORGID=@BORGID 
OPEN SUBBIES
FETCH NEXT FROM SUBBIES INTO @CREDNO 

WHILE @@FETCH_STATUS = 0
BEGIN


        -- OTHER THAN OPENING BALANCE
		DECLARE TRANGRPS CURSOR FOR
		SELECT DISTINCT TRANGRP FROM TRANSACTIONS WHERE LEDGERCODE IN (SELECT LEDGERCODE FROM #SUBBIE)
		 AND YEAR=@FINYEAR  AND ORGID=@BORGID AND CREDNO = @CREDNO AND PERIOD >=1  AND PERIOD <= @ENDPERIOD   
		 --AND TRANGRP= 269580

		OPEN TRANGRPS 
		FETCH NEXT FROM TRANGRPS INTO @TRANGRP 

		WHILE @@FETCH_STATUS = 0 
		BEGIN
		  SELECT LEDGERCODE,DESCRIPTION ,DEBIT,CREDIT,CREDNO ,SUBCONTRAN ,TRANGRP,ALLOCATION,PERIOD,TRANSTYPE
		  INTO #TEMP 
		  FROM TRANSACTIONS 
		  WHERE TRANGRP = @TRANGRP AND LEDGERCODE NOT IN (@WIP,@RETAINED) 
  
 

		  INSERT INTO #STATEMENT (ID,CREDNO,PERIOD  ) 
		  SELECT TOP 1 TRANGRP,CREDNO,PERIOD  FROM #TEMP WHERE LEDGERCODE=@SUBBIE

		  UPDATE #STATEMENT SET ADVANCE = (DEBIT-CREDIT) FROM #TEMP WHERE LEDGERCODE = @ADVANCE   AND  ID = @TRANGRP 
		  SET @THISWORKDONE = 0
		  SELECT @THISWORKDONE = SUM(DEBIT-CREDIT) FROM #TEMP WHERE ALLOCATION = 'Contracts' AND ( SUBCONTRAN='WorkDone'  OR SUBCONTRAN= 'Work Done' ) 
		  UPDATE #STATEMENT SET CERTIFIED = @THISWORKDONE WHERE ID=@TRANGRP 
		  SET @THISST = 0
		  SELECT @THISST = SUM(DEBIT-CREDIT) FROM #TEMP WHERE LEDGERCODE=@ST 
		  UPDATE #STATEMENT SET ST = @THISST  WHERE  ID = @TRANGRP 
		  UPDATE #STATEMENT SET VAT = (DEBIT-CREDIT) FROM #TEMP WHERE LEDGERCODE = @VAT AND  ID = @TRANGRP 
		  UPDATE #STATEMENT SET RETENTION = (CREDIT-DEBIT) FROM #TEMP WHERE LEDGERCODE = @RETENTION AND  ID = @TRANGRP 
		  SET @THISWHT = 0
		  SELECT @THISWHT = SUM(CREDIT-DEBIT) FROM #TEMP WHERE LEDGERCODE=@WHT 
		  UPDATE #STATEMENT SET TDS = @THISWHT WHERE    ID = @TRANGRP 
		  SET @THISCONTRA = 0
		  SELECT @THISCONTRA = SUM(CREDIT-DEBIT) FROM #TEMP WHERE SUBCONTRAN LIKE 'Contra%' 
		  UPDATE #STATEMENT SET CONTRA = @THISCONTRA WHERE   ID = @TRANGRP 
		  UPDATE #STATEMENT SET ADMINCHARGE = CREDIT FROM #TEMP WHERE LEDGERCODE=@ADMINCHARGE AND ID=@TRANGRP 
		  SET @THISNETPAYABLE = 0 
		  SELECT @THISNETPAYABLE = CREDIT-DEBIT FROM #TEMP WHERE LEDGERCODE=@SUBBIE AND  ( SUBCONTRAN LIKE '%Certified Amount%' OR SUBCONTRAN LIKE '%Payable%' )
		  UPDATE #STATEMENT SET NETPAYABLE = @THISNETPAYABLE  WHERE   ID = @TRANGRP 
		  UPDATE #STATEMENT SET STBYSP = CREDIT FROM #TEMP WHERE LEDGERCODE=@STBYSP AND ID=@TRANGRP 
		  UPDATE #STATEMENT SET PAID  = DEBIT  FROM #TEMP WHERE LEDGERCODE=@SUBBIE AND SUBCONTRAN='Payment' AND  ID = @TRANGRP AND #TEMP.CREDNO=@CREDNO 
          UPDATE #STATEMENT SET PAID = -1.0*CREDIT FROM #TEMP WHERE LEDGERCODE=@SUBBIE AND SUBCONTRAN ='Payment' AND ID=@TRANGRP AND  #TEMP.CREDNO=@CREDNO AND LEFT(#TEMP.TRANSTYPE,3)='CBD'

		  DROP TABLE #TEMP 
		  FETCH NEXT FROM TRANGRPS INTO @TRANGRP 
		END


		CLOSE TRANGRPS
		DEALLOCATE TRANGRPS

		
		-- OPENING BALANCE 
	    SET @OB = 0 
		SELECT 
		  @OB = SUM(DEBIT-CREDIT)   FROM TRANSACTIONS 
		  WHERE YEAR=@FINYEAR AND PERIOD=0 AND ORGID=@BORGID AND LEDGERCODE=@SUBBIE AND CREDNO=@CREDNO  

		SET @OBRETENTION = 0 
		SELECT 
		  @OBRETENTION = SUM(CREDIT-DEBIT)   FROM TRANSACTIONS 
		  WHERE YEAR=@FINYEAR AND PERIOD=0 AND ORGID=@BORGID AND LEDGERCODE=@RETENTION AND CREDNO=@CREDNO  

		SET @OBADVANCE  = 0 
		SELECT 
		  @OBADVANCE = SUM(CREDIT-DEBIT)   FROM TRANSACTIONS 
		  WHERE YEAR=@FINYEAR AND PERIOD=0 AND ORGID=@BORGID AND LEDGERCODE=@ADVANCE AND CREDNO=@CREDNO

		IF ( @OB < 0  OR @OBRETENTION > 0  OR @OBADVANCE > 0 )

			INSERT INTO #STATEMENT (CREDNO,ADVANCE,RETENTION,NETPAYABLE,PAID,PERIOD) 
			SELECT @CREDNO,@OBADVANCE,@OBRETENTION,@OB,0,0

		IF @OB > 0 
			INSERT INTO #STATEMENT (CREDNO,ADVANCE,RETENTION,NETPAYABLE,PAID,PERIOD) 
			SELECT @CREDNO,@OBADVANCE,@OBRETENTION, 0,@OB,0 
 
        -- Filtering Periods

        DELETE FROM #STATEMENT WHERE PERIOD > @ENDPERIOD  AND CREDNO=@CREDNO  

FETCH NEXT FROM SUBBIES INTO @CREDNO 
END
CLOSE SUBBIES
DEALLOCATE SUBBIES

UPDATE #STATEMENT SET ADVANCE = 0 WHERE ADVANCE IS NULL
UPDATE #STATEMENT SET CERTIFIED = 0 WHERE CERTIFIED IS NULL
UPDATE #STATEMENT SET ST = 0 WHERE ST IS NULL
UPDATE #STATEMENT SET VAT = 0 WHERE VAT IS NULL
UPDATE #STATEMENT SET RETENTION = 0  WHERE RETENTION IS NULL 
UPDATE #STATEMENT SET TDS = 0 WHERE TDS IS NULL
UPDATE #STATEMENT SET CONTRA = 0 WHERE CONTRA IS NULL
UPDATE #STATEMENT SET NETPAYABLE = 0 WHERE NETPAYABLE IS NULL
UPDATE #STATEMENT SET ADMINCHARGE = 0 WHERE ADMINCHARGE IS NULL 
UPDATE #STATEMENT SET PAID = 0 WHERE PAID IS NULL 
UPDATE #STATEMENT SET STBYSP = 0 WHERE STBYSP IS NULL 

IF @FINYEAR < 2016 
  DELETE FROM #STATEMENT 

CREATE TABLE #OB (CREDNO VARCHAR(10), OUTSTANDING DECIMAL(18,2)) 

IF @STARTPERIOD = 0 
 BEGIN
        INSERT INTO #OB 
		SELECT 
		  CREDNO,
		  SUM(PAID-NETPAYABLE) OUTSTANDING 
		FROM 
		  #STATEMENT 
		WHERE
		  PERIOD = 0 
		GROUP BY
		  CREDNO 
 END
ELSE
 BEGIN
        INSERT INTO #OB 
		SELECT 
		  CREDNO,
		  SUM(PAID-NETPAYABLE) OUTSTANDING 
		FROM 
		  #STATEMENT 
		WHERE
		  PERIOD < @STARTPERIOD 
		GROUP BY
		  CREDNO 
  END 

SELECT 
  CREDNO,
  0  AS OB,
  ISNULL( SUM(ADVANCE),0)  ADVANCE,
  ISNULL( SUM(CERTIFIED),0)  CERTIFIED,
  ISNULL( SUM(VAT),0)  VAT,
  ISNULL( SUM(ST),0)  ST,
  ISNULL( SUM(RETENTION),0 )  RETENTION,
  ISNULL( SUM(CONTRA),0 )  CONTRA,
  ISNULL( SUM(TDS), 0)  TDS,
  ISNULL( SUM(ADMINCHARGE),0 )  ADMINCHARGE,
  ISNULL( SUM(STBYSP) ,0 ) STBYSP,
  ISNULL( SUM(NETPAYABLE), 0)  NETPAYABLE,
  ISNULL ( SUM(PAID),  0)  PAID
INTO 
  #REGISTER 
FROM 
  #STATEMENT
WHERE
  PERIOD >= @STARTPERIOD AND PERIOD <= @ENDPERIOD 
GROUP BY
  CREDNO


SELECT * FROM #STATEMENT WHERE CREDNO = 'AAABT3230B'


SELECT * FROM #REGISTER WHERE CREDNO = 'AAABT3230B'

UPDATE #REGISTER SET OB = #OB.OUTSTANDING FROM #OB INNER JOIN #REGISTER ON #REGISTER.CREDNO=#OB.CREDNO 
INSERT INTO #REGISTER(CREDNO,OB,PAID,NETPAYABLE,ADVANCE,CERTIFIED,VAT,ST,RETENTION,CONTRA,ADMINCHARGE,TDS,STBYSP) 
SELECT CREDNO,OUTSTANDING ,0,0 ,0,0,0,0,0,0,0,0,0
FROM #OB 
WHERE CREDNO NOT IN (SELECT CREDNO FROM #REGISTER) 




ALTER TABLE #REGISTER ADD SUBBIENAME VARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS
UPDATE #REGISTER SET SUBBIENAME = S.SUBNAME FROM SUBCONTRACTORS S INNER JOIN #REGISTER ON #REGISTER.CREDNO=S.SUBNUMBER 

ALTER TABLE #REGISTER ADD BORGNAME VARCHAR(100)
UPDATE #REGISTER SET BORGNAME = (SELECT BORGNAME FROM BORGS WHERE BORGID=@BORGID) 

DECLARE @YEARNAME VARCHAR(25)
SET @YEARNAME = STR(@FINYEAR-1) + ' - ' + LTRIM(RTRIM(STR(@FINYEAR)))
ALTER TABLE #REGISTER ADD FINYEAR VARCHAR(25)
UPDATE #REGISTER SET FINYEAR = @YEARNAME
 
ALTER TABLE #REGISTER ADD STARTPERIOD VARCHAR(25)
ALTER TABLE #REGISTER ADD ENDPERIOD VARCHAR(25)
UPDATE #REGISTER SET STARTPERIOD = P.PERIODDESC  FROM PERIODMASTER  P WHERE P.PERIODID= @STARTPERIOD 
UPDATE #REGISTER SET ENDPERIOD = P.PERIODDESC  FROM PERIODMASTER  P WHERE P.PERIODID= @ENDPERIOD 
UPDATE #REGISTER SET STARTPERIOD='Opening Balance' WHERE @STARTPERIOD=0
UPDATE #REGISTER SET ENDPERIOD='Opening Balance' WHERE @ENDPERIOD =0
 
 SELECT * FROM #REGISTER 

SELECT @FILEID= CONVERT(INT,RAND( (DATEPART(mm, GETDATE()) * 100000 )
+ (DATEPART(ss, GETDATE()) * 1000 )
+ DATEPART(ms, GETDATE()) )*1000)

SET @FILENAME = @FILENAME+LTRIM(RTRIM(CONVERT(VARCHAR(3),@FILEID)))
SELECT @FILENAME 
SET @SQL = 'SELECT *  INTO '+@FILENAME+ ' FROM   #REGISTER   ORDER BY SUBBIENAME '

EXEC(@SQL)

RETURN @FILEID