/****** Object:  Procedure [BS].[spGenerateStockItems]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE  PROCEDURE [BS].[spGenerateStockItems] (@CATEGORY VARCHAR(10),  @STARTDATESTRING VARCHAR(15),@ENDDATESTRING VARCHAR(15) )
as

DECLARE @CATLENGTH INT
SET @CATLENGTH = LEN(LTRIM(RTRIM(@CATEGORY)))
SELECT @CATLENGTH 

DECLARE @CATEGORYNAME VARCHAR(25)
SELECT @CATEGORYNAME = CLASSNAME FROM STOCKCLASS WHERE CLASSNUMBER=@CATEGORY

DECLARE @STARTDATE     DATETIME
DECLARE @ENDDATE       DATETIME
SELECT @STARTDATE = CONVERT(DATETIME, @STARTDATESTRING,103) -- dd/mm/yyyy 
SELECT @ENDDATE   = CONVERT(DATETIME, @ENDDATESTRING,103) -- dd/mm/yyyy 

SELECT ORDID,ORDNUMBER,CREATEDATE,BORGID ,SUPPID 
INTO #ORD 
FROM ORD 
WHERE CREATEDATE BETWEEN @STARTDATE AND @ENDDATE 

SELECT ORDID,LINENUMBER ,ITEMDESCRIPTION,BUYERPARTNUMBER,UOM,QTY,PRICE 
INTO #ORDITEMS 
FROM ORDITEMS 
WHERE LEFT(BUYERPARTNUMBER,@CATLENGTH)= @CATEGORY  AND 
      ORDID IN (SELECT ORDID FROM #ORD) 


SELECT ORDID,ORDITEMLINENO,SUM(DLVRQTY) DLVRQTY 
INTO #DEL
FROM DELIVERIES 
WHERE ORDID IN (SELECT ORDID FROM #ORDITEMS) 
GROUP BY ORDID,ORDITEMLINENO 


DELETE FROM #ORD WHERE ORDID NOT IN (SELECT ORDID FROM  #ORDITEMS ) 
DELETE FROM #DEL WHERE ORDID NOT IN (SELECT ORDID FROM  #ORDITEMS )


 

SELECT O.BORGID,O.ORDNUMBER,O.CREATEDATE,S.SUPPNAME,OI.ITEMDESCRIPTION,OI.BUYERPARTNUMBER,OI.UOM,OI.QTY ORDEREDQTY,OI.PRICE RATE ,O.ORDID ,OI.LINENUMBER
INTO #ORDERS
FROM #ORD O INNER JOIN #ORDITEMS OI ON O.ORDID = OI.ORDID 
INNER JOIN SUPPLIERS  S ON O.SUPPID = S.SUPPID 
 
SELECT ORD.*,D.DLVRQTY ,B.BORGNAME 
INTO #FINAL
FROM #ORDERS ORD INNER JOIN #DEL D 
ON ORD.ORDID = D.ORDID AND ORD.LINENUMBER = D.ORDITEMLINENO
INNER JOIN BORGS B ON ORD.BORGID = B.BORGID 
ORDER BY BORGID,ORDNUMBER 

SELECT BUYERPARTNUMBER,ITEMDESCRIPTION,ORDNUMBER,CREATEDATE, ORDEREDQTY,UOM,RATE,SUPPNAME,DLVRQTY,BORGID,BORGNAME 
FROM #FINAL WHERE   SUPPNAME<>'TALLY RECORD'
ORDER BY BUYERPARTNUMBER,ITEMDESCRIPTION,CREATEDATE  

ALTER TABLE #FINAL ADD STARTDATESTRING VARCHAR(15)
ALTER TABLE #FINAL ADD ENDDATESTRING   VARCHAR(15)
ALTER TABLE #FINAL ADD CATEGORY VARCHAR(50)

UPDATE #FINAL SET STARTDATESTRING = @STARTDATESTRING
UPDATE #FINAL SET ENDDATESTRING = @ENDDATESTRING
UPDATE #FINAL SET CATEGORY = @CATEGORYNAME 

DECLARE @FILENAME VARCHAR(100)
DECLARE @FILEID   VARCHAR(10)
DECLARE @SQL      VARCHAR(250)
SET @FILENAME = 'BSBS_TEMP.DBO.PURCHASEHISTORY'

SELECT @FILEID= CONVERT(INT,RAND( (DATEPART(mm, GETDATE()) * 100000 )
+ (DATEPART(ss, GETDATE()) * 1000 )
+ DATEPART(ms, GETDATE()) )*1000)

SET @FILENAME = @FILENAME+LTRIM(RTRIM(CONVERT(VARCHAR(3),@FILEID)))
SELECT @FILENAME 
SET @SQL = 'SELECT *  INTO '+@FILENAME+ ' FROM   #FINAL   ORDER BY BUYERPARTNUMBER,ITEMDESCRIPTION,BORGNAME,SUPPNAME,CREATEDATE  '

EXEC(@SQL)

RETURN @FILEID
 