/****** Object:  Procedure [BS].[spGeneratePlantHire]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE [BS].[spGeneratePlantHire](@FINYEAR VARCHAR(4),@PERIOD INT, @CATEGORY VARCHAR(10) , @REPORTTYPE INT )
AS

DECLARE @FILENAME1 VARCHAR(100)
DECLARE @FILENAME2 VARCHAR(100)
DECLARE @FILEID1   VARCHAR(10)
DECLARE @FILEID2   VARCHAR(10)
DECLARE @SQL      VARCHAR(250)
DECLARE @ORGID INT

SET @FILENAME1 = 'BSBS_TEMP.DBO.ASSETRETNAL'
SET @FILENAME2 = 'BSBS_TEMP.DBO.RENTALSUMMARY'
CREATE TABLE #TEMP0 (PENUMBER VARCHAR(25),PENAME VARCHAR(255),ASSETPRICE VARCHAR(25) ,CATID INT, VALUE VARCHAR(25),DESCR VARCHAR(255), RENT MONEY ) 
DELETE FROM #TEMP0 

IF @CATEGORY = 1 
 BEGIN
  INSERT INTO #TEMP0 
  SELECT 
	 PE.PENUMBER,
	 PE.PENAME,
	 PE.PEPPRICE,
	 PE.CATID,
	 AV.VALUE,
	 AL.DESCR,
	 CA.CATRATE1 RENT
  FROM PLANTANDEQ PE 
		 INNER JOIN ATTRIBVALUE  AV ON PE.PENUMBER = AV.COLKEY 
		 INNER JOIN ATTRIBLOOKUP AL ON AL.VALUE  = AV.VALUE 
		 INNER JOIN PLANTCATEGORIES CA ON CA.CATID=PE.CATID 
  WHERE 
     AV.TABLENAME = 'PLANTANDEQ' AND AV.ATTRIBUTE = 'LOC' AND
	 LEFT(PE.PENUMBER,2)='IT' AND PE.PeStatus = 0 AND AL.TABLENAME = 'PLANTANDEQ'
 END
ELSE
 BEGIN
  INSERT INTO #TEMP0 
  SELECT 
	 PE.PENUMBER,
	 PE.PENAME,
	 PE.PEPPRICE,
	 PE.CATID,
	 AV.VALUE,
	 AL.DESCR,
	 CA.CATRATE1 RENT
  FROM PLANTANDEQ PE 
		 INNER JOIN ATTRIBVALUE  AV ON PE.PENUMBER = AV.COLKEY 
		 INNER JOIN ATTRIBLOOKUP AL ON AL.VALUE  = AV.VALUE 
		 INNER JOIN PLANTCATEGORIES CA ON CA.CATID=PE.CATID 
  WHERE 
     AV.TABLENAME = 'PLANTANDEQ' AND AV.ATTRIBUTE = 'LOC' AND
	 LEFT(PE.PENUMBER,2)<>'IT' AND PE.PeStatus = 0 AND AL.TABLENAME = 'PLANTANDEQ'
 END
 
 SELECT * FROM #TEMP0 

SELECT DESCR,SUM(RENT) TOTALRENT 
   INTO #TEMP1 
   FROM #TEMP0 
   GROUP BY DESCR
   ORDER BY DESCR

ALTER TABLE #TEMP0 ADD FINYEAR VARCHAR(4)
ALTER TABLE #TEMP0 ADD PERIODNAME VARCHAR(20)
IF @PERIOD >=11 AND @PERIOD<=13 
   UPDATE #TEMP0 SET FINYEAR=@FINYEAR
ELSE
   UPDATE #TEMP0 SET FINYEAR =@FINYEAR-1
 
UPDATE #TEMP0 SET PERIODNAME = (SELECT PERIODDESC FROM PERIODMASTER WHERE PERIODID=@PERIOD) 

ALTER TABLE #TEMP1 ADD FINYEAR VARCHAR(4)
ALTER TABLE #TEMP1 ADD PERIODNAME VARCHAR(20)
IF @PERIOD >=11 AND @PERIOD<=13 
   UPDATE #TEMP1 SET FINYEAR=@FINYEAR
ELSE
   UPDATE #TEMP1 SET FINYEAR =@FINYEAR-1


SELECT * FROM #TEMP0 


UPDATE #TEMP1 SET PERIODNAME = (SELECT PERIODDESC FROM PERIODMASTER WHERE PERIODID=@PERIOD) 

ALTER TABLE #TEMP1 ADD ORGID VARCHAR(10)

 SELECT * FROM #TEMP1 


UPDATE #TEMP1 SET ORGID=B.BORGID FROM BORGS B INNER JOIN #TEMP1 ON LEFT(LTRIM(#TEMP1.DESCR),5) =LEFT(LTRIM(B.BORGNAME),5)  

   SELECT * FROM #TEMP1 



SELECT @FILEID1= CONVERT(INT,RAND( (DATEPART(mm, GETDATE()) * 100000 )
+ (DATEPART(ss, GETDATE()) * 1000 )
+ DATEPART(ms, GETDATE()) )*1000)
SET @FILENAME1 = @FILENAME1+LTRIM(RTRIM(CONVERT(VARCHAR(3),@FILEID1)))
SET @SQL = 'SELECT *  INTO '+@FILENAME1+ ' FROM   #TEMP0   ORDER BY DESCR,PENUMBER '
EXEC(@SQL)



SET @FILENAME2 = @FILENAME2+LTRIM(RTRIM(CONVERT(VARCHAR(3),@FILEID1)))
SET @SQL = 'SELECT *  INTO '+@FILENAME2+ ' FROM   #TEMP1   ORDER BY DESCR '
EXEC(@SQL)

SELECT @FILENAME1
SELECT @FILENAME2

 
RETURN @FILEID1
 
 
 