/****** Object:  Procedure [BS].[spGenerateSiteEstablishment_Summary]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE [BS].[spGenerateSiteEstablishment_Summary] 
AS

DECLARE @FILENAME VARCHAR(100)
DECLARE @FILEID   VARCHAR(10)
DECLARE @SQL      VARCHAR(250)

SET @FILENAME = 'BSBS_TEMP.DBO.SITEESTABLISHMENTSUMMARY'

SELECT 
 A.ASSETID,
 A.BORGID,
 B.PERIOD,
 B.CURRENTYEAR,
 PM.PERIODDESC,
 B.BORGNAME,
 A.ASSETNUMBER,
 A.ASSETNAME,
 A.ASSETPDATE,
 A.ASSETPPRICE,
 A.ASSETACCUMDEP,
 A.ASSETBOOKVALUE,
 A.AssetDepProg,
 A.ASSETPERIOD,
 A.ASSETLOCATION,
 A.ASSETCATEGORY,
 A.LASTDEPTM
INTO #TEMP0
FROM
 ASSETS A 
 INNER JOIN BORGS B ON A.BORGID=B.BORGID 
 INNER JOIN PERIODMASTER PM ON PM.PERIODID = B.PERIOD 
WHERE LEFT(A.ASSETCATEGORY,2)='SE'  

ALTER TABLE #TEMP0 ADD QTY   DECIMAL(18,2)
ALTER TABLE #TEMP0 ADD RATE  DECIMAL(18,2)
ALTER TABLE #TEMP0 ADD UNIT  VARCHAR(10)
ALTER TABLE #TEMP0 ADD DEPPERIOD VARCHAR(50)

UPDATE #TEMP0 SET QTY = AV.VALUE  FROM ATTRIBVALUE AV INNER JOIN #TEMP0 ON AV.COLKEY = #TEMP0.ASSETID AND AV.ATTRIBUTE ='QTY'
UPDATE #TEMP0 SET RATE = AV.VALUE FROM ATTRIBVALUE AV INNER JOIN #TEMP0 ON AV.COLKEY = #TEMP0.ASSETID AND AV.ATTRIBUTE ='RATE'
UPDATE #TEMP0 SET UNIT = AV.VALUE FROM ATTRIBVALUE AV INNER JOIN #TEMP0 ON AV.COLKEY = #TEMP0.ASSETID AND AV.ATTRIBUTE ='UNIT'
UPDATE #TEMP0 SET DEPPERIOD =  LTRIM(RTRIM(PERIODDESC))+'-'+STR(CURRENTYEAR) 

SELECT BORGID,BORGNAME,SUM(LASTDEPTM) DEPRECIATEDVALUE,DEPPERIOD INTO #TEMP1  FROM #TEMP0 GROUP BY BORGID,BORGNAME,DEPPERIOD ORDER BY BORGID 

SELECT @FILEID= CONVERT(INT,RAND( (DATEPART(mm, GETDATE()) * 100000 )
+ (DATEPART(ss, GETDATE()) * 1000 )
+ DATEPART(ms, GETDATE()) )*1000)

SET @FILENAME = @FILENAME+LTRIM(RTRIM(CONVERT(VARCHAR(3),@FILEID)))

 
SET @SQL = 'SELECT *  INTO '+@FILENAME+ ' FROM   #TEMP1   ORDER BY BORGID,BORGNAME '
 
EXEC(@SQL)

RETURN @FILEID