/****** Object:  Procedure [BS].[spGetCashFlowMarkers]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE Procedure [BS].[spGetCashFlowMarkers]
as
SELECT CF.INDEXCODE,upper(CF.DESCRIPTION) DESCRIPTION, 
       AT.VALUE,UPPER(AL.DESCR) DESCR ,AT.COLKEY,
	   L.LEDGERCODE,UPPER(L.LEDGERNAME ) LEDGERNAME 
FROM 
      BS.CASHFLOWINDICATORS_NEW CF 
	  INNER JOIN ATTRIBVALUE AT ON CF.INDEXCODE=AT.VALUE 
	  INNER JOIN LEDGERCODES L ON AT.COLKEY = L.LEDGERCODE 
	  INNER JOIN ATTRIBLOOKUP AL ON AT.VALUE = AL.VALUE 
      WHERE AT.tablename='LEDGERCODES' AND AT.ATTRIBUTE='Cash Flow Markers' 
ORDER BY CF.INDEXCODE 