/****** Object:  Procedure [BS].[spIPLA]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE [BS].[spIPLA](@FINYEAR INT,@FROMPERIOD INT,@TOPERIOD INT,@BORGID INT)
AS

DECLARE @CURRENTIPLA VARCHAR(10)

SELECT BORGID,ICGLCODE INTO #IPLA FROM BORGS 
DELETE FROM #IPLA WHERE ICGLCODE IS NULL

SELECT @CURRENTIPLA = ICGLCODE FROM #IPLA WHERE BORGID=@BORGID 


SELECT 
   ORGID,
   YEAR,
   PERIOD,
   PDATE,
   TRANGRP,
   BATCHREF,
   TRANSREF,
   TRANSTYPE,
   DESCRIPTION,
   CREDNO,
   DEBIT,
   CREDIT,
   LEDGERCODE
INTO #TEMP0 
FROM TRANSACTIONS 
WHERE 
   ORGID=@BORGID AND 
   YEAR=@FINYEAR AND 
   PERIOD BETWEEN @FROMPERIOD AND @TOPERIOD  AND 
   LEDGERCODE IN (SELECT ICGLCODE FROM #IPLA WHERE  ICGLCODE<> @CURRENTIPLA ) 

ALTER TABLE #TEMP0 ADD WHICHORG INT 
UPDATE #TEMP0 SET WHICHORG = I.BORGID FROM #IPLA I INNER JOIN #TEMP0 ON #TEMP0.LEDGERCODE=I.ICGLCODE 

ALTER TABLE #TEMP0 ADD BORGNAME VARCHAR(200)
ALTER TABLE #TEMP0 ADD PARTYNAME VARCHAR(150)
UPDATE #TEMP0 SET BORGNAME =B.BORGNAME FROM BORGS B INNER JOIN #TEMP0 ON #TEMP0.WHICHORG = B.BORGID 
UPDATE #TEMP0 SET PARTYNAME = C.CREDNAME FROM CREDITORS C INNER JOIN #TEMP0 ON #TEMP0.CREDNO = C.CREDNUMBER 
UPDATE #TEMP0 SET PARTYNAME = S.SUBNAME  FROM SUBCONTRACTORS S INNER JOIN #TEMP0 ON #TEMP0.CREDNO = S.SUBNUMBER 
UPDATE #TEMP0 SET PARTYNAME = D.DEBTNAME FROM DEBTORS D INNER JOIN #TEMP0 ON #TEMP0.CREDNO = D.DEBTNUMBER 

ALTER TABLE #TEMP0 ADD EXPENSELEDGER VARCHAR(10)
UPDATE   #TEMP0 SET EXPENSELEDGER  =   T.LEDGERCODE FROM TRANSACTIONS T INNER JOIN #TEMP0 ON #TEMP0.TRANGRP = T.TRANGRP
WHERE LEFT(#TEMP0.BATCHREF,3)<>'JNL' AND TRANSID = (SELECT MIN(TRANSID) FROM TRANSACTIONS WHERE TRANGRP=T.TRANGRP) 

ALTER TABLE #TEMP0 ADD EXPENSELEDGERNAME  VARCHAR(200)
UPDATE #TEMP0  SET EXPENSELEDGERNAME = L.LEDGERNAME FROM LEDGERCODES L INNER JOIN #TEMP0 ON #TEMP0.EXPENSELEDGER = L.LEDGERCODE 

SELECT 
  WHICHORG  RECEIVINGORG,
  BORGNAME,
  LEDGERCODE,
  EXPENSELEDGER,
  EXPENSELEDGERNAME,
  CREDNO,
  PARTYNAME,
  DEBIT,
  CREDIT,
  DESCRIPTION,
  YEAR,
  PERIOD,
  PDATE,
  BATCHREF,
  TRANSREF,
  TRANGRP
FROM 
  #TEMP0  
ORDER BY 
  WHICHORG,PDATE