/****** Object:  Procedure [BS].[spJournalLog]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE BS.spJournalLog
as
 

CREATE TABLE #TEMP0(LOGID INT,LOGDATE DATETIME,LOGACTION VARCHAR(255),LOGUSERID VARCHAR(10),LOGBOGID INT) 

INSERT INTO #TEMP0
SELECT LOGID,LOGDATE,LOGACTION,LOGUSERID,LOGBORGID 
FROM LOG WHERE LOGACTION LIKE '%Journal%' AND YEAR(LOGDATE)=2020

ALTER TABLE #TEMP0 ADD ACTIONID INT 
UPDATE #TEMP0 SET LOGACTION =UPPER(LOGACTION) 
UPDATE #TEMP0 SET ACTIONID=1 WHERE LEFT(LOGACTION,4)='SAVE'
UPDATE #TEMP0 SET ACTIONID=2 WHERE LEFT(LOGACTION,4)='POST' 
ALTER TABLE #TEMP0 ADD POSITION INT 
UPDATE #TEMP0 SET POSITION=0 
UPDATE #TEMP0 SET POSITION=CHARINDEX('ID',LOGACTION) WHERE ACTIONID=2
UPDATE #TEMP0 SET POSITION=CHARINDEX('FOR JOURNAL',LOGACTION) WHERE ACTIONID=1
UPDATE #TEMP0 SET POSITION=CHARINDEX('ID',LOGACTION) WHERE ACTIONID=1 AND POSITION=0
ALTER TABLE #TEMP0 ADD HEADERID CHAR(15)
UPDATE #TEMP0 SET HEADERID=''
UPDATE #TEMP0 SET HEADERID = SUBSTRING(LOGACTION,POSITION+2,10) WHERE ACTIONID=2
UPDATE #TEMP0 SET HEADERID = SUBSTRING(LOGACTION,POSITION+12,10) WHERE ACTIONID=1 
UPDATE #TEMP0 SET HEADERID = SUBSTRING(LOGACTION,POSITION+2,10) WHERE ACTIONID=1 AND HEADERID=''
UPDATE #TEMP0 SET HEADERID = LTRIM(RTRIM(HEADERID))

DELETE FROM #TEMP0 WHERE ACTIONID IS NULL

ALTER TABLE #TEMP0 ADD HEADERDESCRIPTION VARCHAR(255)
ALTER TABLE #TEMP0 ADD ORGNAME VARCHAR(200)
ALTER TABLE #TEMP0 ADD LOGINNAME VARCHAR(200)
UPDATE #TEMP0 SET ORGNAME=B.BORGNAME FROM BORGS B INNER JOIN #TEMP0 ON #TEMP0.LOGBOGID=B.BORGID 
UPDATE #TEMP0 SET LOGINNAME = U.USERNAME FROM USERS U INNER JOIN #TEMP0 ON #TEMP0.LOGUSERID=U.USERID 
UPDATE #TEMP0 SET HEADERDESCRIPTION = J.JNLHEADDESCRIPTION FROM JOURNALHEADER J INNER JOIN #TEMP0 ON #TEMP0.HEADERID=J.JNLHEADID 

ALTER TABLE #TEMP0 ADD ACTIONNAME VARCHAR(200)
UPDATE #TEMP0 SET ACTIONNAME='SAVED' WHERE ACTIONID=1
UPDATE #TEMP0 SET ACTIONNAME='POSTED' WHERE ACTIONID=2 

 

SELECT LOGBOGID ORGID,
       ORGNAME   PROJECT,
	   LOGDATE   TRANSACTIONDATE,
	   HEADERID  JOURNALID,
	   ACTIONNAME,
	   HEADERDESCRIPTION JOURNALHEADER,
	   LOGINNAME 
FROM #TEMP0 
ORDER BY  ORGID,HEADERID,ACTIONNAME DESC 