/****** Object:  Procedure [BS].[SPListOfUnMatchedPayments]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE BS.SPListOfUnMatchedPayments(@FINYEAR INT)
as
    DECLARE @FILENAME VARCHAR(100)
	DECLARE @FILEID   VARCHAR(10)
	DECLARE @SQL      VARCHAR(250)
	SET @FILENAME = 'BSBS_TEMP.DBO.UNMATCHED'

	DECLARE @CREDITORS VARCHAR(10)
	SELECT @CREDITORS = CONTROLFROMGL FROM CONTROLCODES WHERE CONTROLNAME='Creditors'

    SELECT T.ORGID,
         B.BORGNAME,
		 T.CREDNO,
		 C.CREDNAME,
		 T.YEAR,
		 T.PERIOD,
		 T.PDATE,
		 T.BATCHREF,
		 T.TRANSREF,
		 T.TRANSTYPE,
		 T.DESCRIPTION,
		 T.DEBIT ,
		 T.CREDIT,
		 T.TRANGRP
	INTO #TEMP0 	
	FROM 
	     TRANSACTIONS T
		 INNER JOIN BORGS B ON T.ORGID = B.BORGID 
		 INNER JOIN CREDITORS C ON T.CREDNO= C.CREDNUMBER 
	WHERE
	     YEAR = @FINYEAR AND T.PAIDFOR=0 AND 
		 LEDGERCODE=@CREDITORS AND 
		 LEFT(TRANSTYPE,3) IN ( 'CBC', 'CBD','PCP','PCR','JNL','REV'  )
	ORDER BY 
	     T.ORGID,T.CREDNO,T.PDATE DESC 


     DECLARE @Random INT;
	 DECLARE @Upper INT;
	 DECLARE @Lower INT
 
	 SET @Lower = 1 ---- The lowest random number
	 SET @Upper = 999 ---- The highest random number
	 SELECT @Random = ROUND(((@Upper - @Lower -1) * RAND() + @Lower), 0)

	 SELECT @FILEID= CONVERT(INT,RAND( (DATEPART(mm, GETDATE()) * 100000 )
		+ (DATEPART(ss, GETDATE()) * 1000 )
		+ DATEPART(ms, GETDATE()) )*1000) + STR(@RANDOM) 

	 SET @FILENAME = @FILENAME+LTRIM(RTRIM(CONVERT(VARCHAR(6),@FILEID)))
     SET @SQL = 'SELECT *  INTO '+@FILENAME+ ' FROM   #TEMP0 T ORDER BY   T.ORGID,T.CREDNO,T.PDATE DESC   '
	 EXEC(@SQL)
	 SELECT @FILENAME 
     RETURN @FILEID
 