/****** Object:  Procedure [BS].[spMatchingTransactions]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE BS.spMatchingTransactions
AS
SELECT * INTO #TEMP0 FROM BS.TRANSMATCHING
DECLARE @BATCHID BIGINT
DECLARE @TRANSID BIGINT
DECLARE BATCHIDS CURSOR FOR SELECT DISTINCT BATCHID FROM #TEMP0 
OPEN BATCHIDS
FETCH NEXT FROM BATCHIDS INTO @BATCHID 
WHILE @@FETCH_STATUS = 0 
BEGIN
  UPDATE TRANSACTIONS SET PAIDFOR=1,MATCHREF=@BATCHID WHERE TRANSID IN (SELECT TRANSID FROM #TEMP0 WHERE BATCHID=@BATCHID) 
  FETCH NEXT FROM BATCHIDS INTO @BATCHID 
END
CLOSE BATCHIDS
DEALLOCATE BATCHIDS 
DELETE FROM BS.TRANSMATCHING