/****** Object:  Procedure [BS].[spModifyInvoiceDate]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE [BS].[spModifyInvoiceDate](@BORGID INT,@FINYEAR INT,@PERIOD INT,@CREDNO VARCHAR(10),@INVOICENO VARCHAR(10),@NEWDATESTRING VARCHAR(15))
AS

DECLARE @FOUNDEDTRANGRP  INT
DECLARE @NEWDATE DATETIME

SET @NEWDATE = CONVERT(DATETIME, @NEWDATESTRING,103) -- dd/mm/yyyy 
SET @FOUNDEDTRANGRP=0

SELECT @FOUNDEDTRANGRP =ISNULL(TRANGRP,0)  
FROM TRANSACTIONS 
WHERE ORGID = @BORGID AND 
      YEAR = @FINYEAR AND
	  PERIOD = @PERIOD AND 
	  CREDNO = @CREDNO AND 
	  LEFT(BATCHREF,3) = 'DEL ' AND
	  TRANSREF = LTRIM(RTRIM(@INVOICENO)) 

IF @FOUNDEDTRANGRP <> 0 
   BEGIN 
     SELECT @FOUNDEDTRANGRP 
     UPDATE TRANSACTIONS SET RECEIVEDDATE = @NEWDATE WHERE TRANGRP = @FOUNDEDTRANGRP
	 RETURN 1
   END
ELSE
     RETURN 0

   