/****** Object:  Procedure [BS].[SPPOSTDATEDTRANS]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE  PROCEDURE BS.SPPOSTDATEDTRANS(@FINYEAR INT) 
AS
BEGIN
  DECLARE @FILENAME VARCHAR(100)
  DECLARE @FILEID   VARCHAR(10)
  DECLARE @SQL      VARCHAR(250)
  SET @FILENAME = 'BSBS_TEMP.DBO.EXCEPTIONS'
  DECLARE @Random INT;
  DECLARE @Upper INT;
  DECLARE @Lower INT

  SELECT 
	 T.ORGID,
	 B.BORGNAME,
	 T.YEAR,
	 T.RECEIVEDDATE BOOKEDATE,
	 T.ORDERNO,
	 T.CREDNO,
	 C.CREDNAME,
	 T.BATCHREF,
	 T.TRANSREF REFNO,
	 T.TRANSTYPE,
	 T.DESCRIPTION,
	 T.DEBIT,
	 T.CREDIT,
	 T.USERID ,
	 U.USERNAME
	INTO #TEMP0 
	FROM 
	 TRANSACTIONS T
	INNER JOIN 
	 BORGS B ON T.ORGID = B.BORGID  
	INNER JOIN 
	 CREDITORS C ON T.CREDNO = C.CREDNUMBER 
	INNER JOIN 
	 USERS U ON U.LOGINID = T.USERID 
	WHERE
	 T.YEAR=@FINYEAR  AND
	 T.TRANSTYPE='DEL' AND
	 T.LEDGERCODE= '1315000' AND
	 T.RECEIVEDDATE > GETDATE()
	
   SELECT 
     T.ORGID,
	 B.BORGNAME,
	 T.YEAR,
	 T.PDATE BOOKEDATE,
	 T.ORDERNO,
	 T.CREDNO,
	 C.CREDNAME,
	 T.BATCHREF,
	 T.TRANSREF REFNO,
	 T.TRANSTYPE,
	 T.DESCRIPTION,
	 T.DEBIT,
	 T.CREDIT,
	 T.USERID ,
	 U.USERNAME
	INTO #TEMP1 
	FROM 
	 TRANSACTIONS T
	INNER JOIN 
	 BORGS B ON T.ORGID = B.BORGID  
	INNER JOIN 
	 CREDITORS C ON T.CREDNO = C.CREDNUMBER 
	INNER JOIN 
	 USERS U ON U.LOGINID = T.USERID 
	WHERE
	 T.YEAR=@FINYEAR  AND
	 T.TRANSTYPE<>'DEL' AND
	 T.LEDGERCODE IN ( '1315000' , '1320000' ) AND
	 (T.DEBIT>0 OR T.CREDIT>0)    AND 
	 T.PDATE > GETDATE()
	SELECT * FROM #TEMP1 
  INSERT INTO #TEMP0 
  SELECT * FROM #TEMP1 


 
  SET @Lower = 1 ---- The lowest random number
  SET @Upper = 999 ---- The highest random number
  SELECT @Random = ROUND(((@Upper - @Lower -1) * RAND() + @Lower), 0)

  SELECT @FILEID= CONVERT(INT,RAND( (DATEPART(mm, GETDATE()) * 100000 )
		+ (DATEPART(ss, GETDATE()) * 1000 )
		+ DATEPART(ms, GETDATE()) )*1000) + STR(@RANDOM) 

  SET @FILENAME = @FILENAME+LTRIM(RTRIM(CONVERT(VARCHAR(6),@FILEID)))
  SET @SQL = 'SELECT *  INTO '+@FILENAME+ ' FROM   #TEMP0  ORDER BY TRANSTYPE,ORGID,BOOKEDATE,USERID  '
  EXEC(@SQL)
  SELECT @FILENAME 
  RETURN @FILEID
 

END