/****** Object:  Procedure [BS].[spPopulateVAT]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE  PROCEDURE BS.spPopulateVAT
AS
 
select *  INTO #TEMP from vattypes WHERE VATGC BETWEEN 'G1' AND 'G9' AND BORGID = 137 ORDER BY VATID 

DECLARE BORGIDS CURSOR FOR SELECT BORGID FROM BORGS WHERE BORGID NOT IN (1,137) 
DECLARE @BORGID INT
OPEN BORGIDS 
FETCH NEXT FROM BORGIDS INTO @BORGID 
WHILE @@FETCH_STATUS =0
BEGIN
  UPDATE #TEMP SET BORGID=@BORGID 
  INSERT INTO VATTYPES 
  SELECT * FROM #TEMP 
  FETCH NEXT FROM BORGIDS INTO @BORGID
END
CLOSE BORGIDS 
DEALLOCATE BORGIDS 
 