/****** Object:  Procedure [BS].[spProjectTBConsolidate]    Committed by VersionSQL https://www.versionsql.com ******/

-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [BS].[spProjectTBConsolidate] (@ORGLISTS VARCHAR(800),@YEAR INT,@STARTPERIOD INT,@ENDPERIOD INT,@REPORTTYPE INT ,@IsConsoildate INT)
AS
BEGIN

-- Report Type 1 = TB
-- Report Type 2 = P & L
DECLARE @FILENAME VARCHAR(100)
DECLARE @FILEID   VARCHAR(10)
DECLARE @SQL      VARCHAR(250)


SELECT PERIOD,ORGID,LEDGERCODE,
   DEBIT=  CASE 
             WHEN (T.CURRENCY  <> 'INR' ) and T.DEBIT<> 0 THEN T.HOMECURRAMOUNT
            ELSE T.DEBIT
          END,
   CREDIT = CASE 
             WHEN (T.CURRENCY  <> 'INR' ) and T.CREDIT<> 0 THEN T.HOMECURRAMOUNT
            ELSE T.CREDIT
           END 
INTO #TRANSMASTER 
FROM TRANSACTIONS  T WHERE YEAR=@YEAR   

SET @FILENAME = 'BSBS_TEMP.DBO.PROJECTPANDL'

DECLARE @RETAIN INT
DECLARE @WIP    INT
DECLARE @R1     INT
DECLARE @R2     INT
SELECT @RETAIN=CONTROLFROMGL FROM CONTROLCODES WHERE CONTROLNAME='Retained Income'
SELECT @WIP=CONTROLFROMGL    FROM CONTROLCODES WHERE CONTROLNAME='Work In Progress' 
SELECT @R1=CONTROLFROMGL     FROM CONTROLCODES WHERE CONTROLNAME='Contract Revenue'
SELECT @R2=CONTROLTOGL       FROM CONTROLCODES WHERE CONTROLNAME='Contract Revenue'

DECLARE @SQL1 VARCHAR(4000)

 
 	
SELECT 
	B.BORGID,
	L.LEDGERCODE,
	L.LEDGERNAME,
	L.LEDGERSUMMARY
INTO
	#TEMP1
FROM
	BORGS B
CROSS JOIN
	LEDGERCODES L
WHERE
	B.BORGID IN (SELECT DISTINCT ORGID FROM TRANSACTIONS) 
ORDER BY
	BORGID,LEDGERCODE  

SELECT 
   T1.BORGID,
   T1.LEDGERCODE LEDGERCODE,
   T1.LEDGERNAME,
   T1.LEDGERSUMMARY,
   ISNULL(P.OPENINGBALANCE,0) OPENINGBALANCE,
   ISNULL(P.DEBIT,0) DEBIT,
   ISNULL(P.CREDIT,0) CREDIT
INTO
  #TEMP0
FROM 
   #TEMP1 T1 
   FULL OUTER JOIN 
	(
		(SELECT 
		   ISNULL(O.ORGID,T.ORGID) ORGID,
		   ISNULL(O.LEDGERCODE,T.LEDGERCODE)  LEDGERCODE,
		   ISNULL(O.OPENINGBALANCE,0) OPENINGBALANCE,
		   ISNULL(T.DEBIT,0) DEBIT,
		   ISNULL(T.CREDIT,0) CREDIT
		FROM 
		  (SELECT 
		    T.ORGID,
			T.LEDGERCODE,
			SUM(DEBIT-CREDIT) OPENINGBALANCE 
		   FROM 
			#TRANSMASTER T 
		   WHERE 
			T.PERIOD<@STARTPERIOD 
		   GROUP BY 
		    T.ORGID,
			T.LEDGERCODE
	      ) O
 		  FULL OUTER JOIN 
		   (SELECT
		      T.ORGID,
			  T.LedgerCode,
			  SUM(T.Debit)  DEBIT,
			  SUM(T.CREDIT) CREDIT
			FROM
			  #TRANSMASTER T 
			WHERE
			  T.PERIOD BETWEEN @STARTPERIOD AND @ENDPERIOD  
			GROUP BY 
			  T.ORGID,
			  T.LEDGERCODE
		   ) T 
		   ON O.LEDGERCODE=T.LEDGERCODE AND O.ORGID=T.ORGID
		 )
		 ) P
	 ON T1.LEDGERCODE=P.LEDGERCODE AND T1.BORGID=P.ORGID
 ORDER BY  BORGID,LEDGERCODE 
 
 
PRINT 'OVER'

 IF @ORGLISTS<>'0' 
  BEGIN
    SELECT DATA AS BORGID INTO #TEMP9 FROM  DBO.SplitString(@ORGLISTS,',')
	DELETE FROM #TEMP0 WHERE BORGID NOT IN (SELECT BORGID FROM #TEMP9) 
  END
 ELSE
  DELETE FROM #TEMP0 WHERE BORGID <> @ORGLISTS



    DELETE FROM #TEMP0 WHERE LEDGERCODE IN (SELECT LEDGERCODE FROM LEDGERCODES WHERE LEDGERALLOC<>'Balance Sheet')
 

 ALTER TABLE #TEMP0 ADD ORGNAME VARCHAR(50)
 UPDATE #TEMP0 SET ORGNAME =  LEFT(BORGNAME,50)  FROM BORGS INNER JOIN #TEMP0 ON #TEMP0.BORGID=BORGS.BORGID

 
 ALTER TABLE #TEMP0 ADD FROMPERIOD VARCHAR(50)
 UPDATE  #TEMP0 SET FROMPERIOD = (SELECT PERIODDESC FROM PERIODMASTER WHERE PERIODID=@STARTPERIOD)

 
 ALTER TABLE #TEMP0 ADD TOPERIOD VARCHAR(50)
 UPDATE  #TEMP0 SET TOPERIOD = (SELECT PERIODDESC FROM PERIODMASTER WHERE PERIODID=@ENDPERIOD)

 
 ALTER TABLE #TEMP0 ADD FINYEAR INT
 UPDATE  #TEMP0 SET FINYEAR = @YEAR 

 ALTER TABLE #TEMP0 ADD CLOSING DECIMAL(18,2)
 UPDATE  #TEMP0 SET CLOSING = OPENINGBALANCE+DEBIT-CREDIT 



 ALTER TABLE #TEMP0 ADD COSTTYPE VARCHAR(10)
 IF @REPORTTYPE=2
  BEGIN
    UPDATE  #TEMP0 SET COSTTYPE='2' 
    UPDATE  #TEMP0 SET COSTTYPE='1' WHERE LEDGERCODE IN (SELECT LEDGERCODE FROM LEDGERCODES WHERE 
													LEDGERCODE >= (SELECT CONTROLFROMGL FROM CONTROLCODES WHERE CONTROLNAME='Contract Revenue') AND
													LEDGERCODE<=(SELECT CONTROLTOGL FROM CONTROLCODES WHERE CONTROLNAME='Contract Revenue'))
 

    UPDATE #TEMP0 SET COSTTYPE='1' WHERE LEDGERCODE=LEFT(@R1,1)
    UPDATE #TEMP0 SET COSTTYPE='1' WHERE LEDGERCODE=LEFT(@R1,2)
  END
 ELSE
  UPDATE #TEMP0 SET COSTTYPE='1'
END 

DELETE FROM #TEMP0 WHERE CLOSING=0 AND LEDGERSUMMARY=0
 DELETE FROM #TEMP0   WHERE LEN(LTRIM(RTRIM(LEDGERCODE)))=1
 
 ALTER TABLE #TEMP0  ADD FILLER INT
 ALTER TABLE #TEMP0  ADD LEVEL INT

 UPDATE #TEMP0 SET LEVEL=1,FILLER = 2  WHERE LEN(LTRIM(RTRIM(LEDGERCODE)))=2
 UPDATE #TEMP0 SET LEVEL=2,FILLER = 5  WHERE LEN(LTRIM(RTRIM(LEDGERCODE)))=3
 UPDATE #TEMP0 SET LEVEL=3,FILLER = 8  WHERE LEN(LTRIM(RTRIM(LEDGERCODE)))>3
 
 PRINT 'LAST LINE'


DECLARE @Random INT;
DECLARE @Upper INT;
DECLARE @Lower INT
 
SET @Lower = 1 ---- The lowest random number
SET @Upper = 999 ---- The highest random number
SELECT @Random = ROUND(((@Upper - @Lower -1) * RAND() + @Lower), 0)
 
SELECT @FILEID= CONVERT(INT,RAND( (DATEPART(mm, GETDATE()) * 100000 )
	+ (DATEPART(ss, GETDATE()) * 1000 )
	+ DATEPART(ms, GETDATE()) )*1000) + STR(@RANDOM) 

SET @FILENAME = @FILENAME+LTRIM(RTRIM(CONVERT(VARCHAR(6),@FILEID)))

SET @SQL = 'SELECT  COSTTYPE,LEDGERCODE, LEDGERNAME,ORGNAME,CLOSING,level, FILLER,FROMPERIOD,TOPERIOD,FINYEAR INTO '+ @FILENAME+ ' FROM   #TEMP0  ORDER BY BORGID,LEDGERCODE  '

EXEC(@SQL)
select * from #temp0 
RETURN @FILEID