/****** Object:  Procedure [BS].[spSLOWMOVINGITEMS]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE  PROCEDURE [BS].[spSLOWMOVINGITEMS]( @CUTOFFDATE DATETIME, @BORGID INT   )
AS

DECLARE @FILENAME VARCHAR(100)
DECLARE @FILEID   VARCHAR(10)
DECLARE @SQL      VARCHAR(250)
SET @FILENAME = 'BSBS_TEMP.DBO.SLOWMOVING'

SELECT TYPENAME INTO #TYPENAMES  FROM STOCKTYPES WHERE ISDEBIT=0
 

DECLARE @STORECODE VARCHAR(10)
SELECT DISTINCT @STORECODE =  STORE FROM TRANSACTIONS WHERE ORGID= @BORGID AND LEFT(STORE,2)= 'MS' 

CREATE TABLE #TEMP9 (  STOCKNO VARCHAR(10), RECEIPTS DECIMAL(18,4), ISSUES DECIMAL(18,4) ) 

DECLARE @LEDGECODE VARCHAR(10)
SELECT  @LEDGECODE = STKCTL FROM INVSTORES WHERE STORECODE = @STORECODE 

-- RECEIPTS ONLY - DELIVERY
SELECT STOCKNO,SUM(QUANTITY) RECEIPTS INTO #TEMP0 FROM TRANSACTIONS WHERE PDATE<=@CUTOFFDATE AND TRANSTYPE='DEL' AND 
LEDGERCODE =@LEDGECODE  GROUP BY  STOCKNO,STORE  

-- ALL TRANSFERS 
SELECT STOCKNO,SUM(QUANTITY) TRANSFERS INTO #TEMP1 FROM TRANSACTIONS WHERE   TRANSTYPE='XFR' AND 
LEDGERCODE =@LEDGECODE  GROUP BY  STOCKNO,STORE 

-- ALL ISSUES 
SELECT STOCKNO,SUM(QUANTITY) ISSUES INTO #TEMP2 FROM TRANSACTIONS WHERE  
TRANSTYPE IN (SELECT TYPENAME FROM #TYPENAMES ) AND 
LEDGERCODE =@LEDGECODE  GROUP BY  STOCKNO,STORE  

-- ALL TRANSFERS 
SELECT STOCKNO,SUM(QUANTITY) BULKISSUE  INTO #TEMP3 FROM TRANSACTIONS WHERE  
TRANSTYPE ='STB' AND 
LEDGERCODE =@LEDGECODE  GROUP BY  STOCKNO,STORE

-- A NEW TABLE TO STORE STOCKCODE ONLY
CREATE TABLE #STOCKCODES (STOCKCODE VARCHAR(10))
INSERT INTO #STOCKCODES 
SELECT STOCKNO FROM #TEMP0

INSERT INTO #STOCKCODES 
SELECT STOCKNO FROM #TEMP1 

INSERT INTO #STOCKCODES 
SELECT STOCKNO FROM #TEMP2

INSERT INTO #STOCKCODES 
SELECT STOCKNO FROM #TEMP3 

INSERT INTO #TEMP9 (STOCKNO,RECEIPTS,ISSUES)
SELECT DISTINCT STOCKCODE,0,0 FROM #STOCKCODES

-- COPY DELIVERY ONLY
UPDATE #TEMP9 SET RECEIPTS = #TEMP0.RECEIPTS  FROM #TEMP0  INNER JOIN #TEMP9  ON #TEMP0.STOCKNO= #TEMP9.STOCKNO 

-- COPY ISSUES ONLY
UPDATE #TEMP9 SET ISSUES = #TEMP2.ISSUES FROM #TEMP2 INNER JOIN #TEMP9 ON #TEMP2.STOCKNO = #TEMP9.STOCKNO 

-- COPY TRANSFER + VE VALUE AS RECEIPTS
UPDATE #TEMP9 SET RECEIPTS = RECEIPTS + TRANSFERS FROM #TEMP1 INNER JOIN #TEMP9 ON #TEMP1.STOCKNO = #TEMP9.STOCKNO WHERE #TEMP1.TRANSFERS > 0

-- COPY TRANSFERS - VE VALUE AS ISSUES
UPDATE #TEMP9 SET ISSUES = ISSUES + TRANSFERS FROM #TEMP1 INNER JOIN #TEMP9 ON #TEMP1.STOCKNO  = #TEMP9.STOCKNO WHERE #TEMP1.TRANSFERS < 0 

-- COPY BUILK ISSUE STB 
UPDATE #TEMP9 SET ISSUES = ISSUES - BULKISSUE FROM #TEMP3 INNER JOIN #TEMP9 ON #TEMP3.STOCKNO = #TEMP9.STOCKNO 

SELECT * FROM #TEMP0 WHERE STOCKNO='SS00580'

SELECT * FROM #TEMP1 WHERE STOCKNO='SS00580'

SELECT * FROM #TEMP2 WHERE STOCKNO='SS00580'

SELECT * FROM #TEMP3 WHERE STOCKNO='SS00580'

ALTER TABLE #TEMP9 ADD STORE VARCHAR(10)
ALTER TABLE #TEMP9 ADD ITEMNAME VARCHAR(250)
ALTER TABLE #TEMP9 ADD CUTOFF DATETIME
ALTER TABLE #TEMP9 ADD RATE DECIMAL(18,2)
ALTER TABLE #TEMP9 ADD VALUE DECIMAL(18,2)
ALTER TABLE #TEMP9 ADD ORGNAME VARCHAR(100)

DELETE FROM #TEMP9 WHERE ISSUES<>0
 

UPDATE #TEMP9 SET CUTOFF = @CUTOFFDATE 
UPDATE #TEMP9 SET STORE = @STORECODE
UPDATE #TEMP9 SET ITEMNAME = I.STKDESC FROM INVENTORY I INNER JOIN #TEMP9 ON #TEMP9.STOCKNO = I.STKCODE 
UPDATE #TEMP9 SET RATE = I.STKCOSTRATE FROM INVENTORY I INNER JOIN #TEMP9 ON #TEMP9.STOCKNO = I.STKCODE WHERE I.STKSTORE= @STORECODE 
UPDATE #TEMP9 SET VALUE = RATE * RECEIPTS 
UPDATE #TEMP9 SET ORGNAME = B.BORGNAME FROM BORGS B WHERE B.BORGID=@BORGID 

SELECT * FROM #TEMP9 


DECLARE @Random INT;
DECLARE @Upper INT;
DECLARE @Lower INT
 
SET @Lower = 1 ---- The lowest random number
SET @Upper = 999 ---- The highest random number
SELECT @Random = ROUND(((@Upper - @Lower -1) * RAND() + @Lower), 0)

SELECT @FILEID= CONVERT(INT,RAND( (DATEPART(mm, GETDATE()) * 100000 )
	+ (DATEPART(ss, GETDATE()) * 1000 )
	+ DATEPART(ms, GETDATE()) )*1000) + STR(@RANDOM) 

SET @FILENAME = @FILENAME+LTRIM(RTRIM(CONVERT(VARCHAR(6),@FILEID)))
SET @SQL = 'SELECT *  INTO '+@FILENAME+ ' FROM   #TEMP9  ORDER BY STOCKNO   '
EXEC(@SQL)

SELECT @FILENAME 
RETURN @FILEID