/****** Object:  Procedure [BS].[SPSTOCKSTATEMENT]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE BS.SPSTOCKSTATEMENT
AS
BEGIN

 SELECT STKCODE,STKDESC,STKUNIT INTO #TEMP0 FROM INVENTORY WHERE STKSTORE='MS-90080'      
 SELECT PDATE,STOCKNO,QUANTITY,RATE,DEBIT,1  AS INDEXCODE INTO #TEMP1 FROM TRANSACTIONS WHERE  STORE='MS-90080' AND  DESCRIPTION LIKE 'Opening Stock%' 
 SELECT PDATE,STOCKNO,QUANTITY,RATE,CREDIT,2 AS INDEXCODE INTO #TEMP2 FROM TRANSACTIONS WHERE STORE='MS-90080' AND  CREDIT>0 AND DEBIT=0 
 SELECT PDATE,STOCKNO,QUANTITY,RATE,DEBIT,1  AS INDEXCODE INTO #TEMP3 FROM TRANSACTIONS WHERE STORE='MS-90080' AND  DEBIT>0  AND CREDIT=0 AND TRANSTYPE='DEL' 

 SELECT D.DLVRDATE,I.STKCODE,I.STKDESC, D.DLVRQTY,D.PRICE,(D.DLVRQTY*D.PRICE) AMOUNT, D.DLVRID ,D.GRNNO,2 AS INDEXCODE INTO #TEMP4
	FROM DELIVERIES D 
	INNER JOIN ORDITEMS OI ON OI.LINENUMBER=D.ORDITEMLINENO 
	INNER JOIN ORD O ON OI.ORDID = O.ORDID 
	INNER JOIN INVENTORY I ON I.STKID = OI.STOCKID	
	WHERE D.TBORGID=8 AND D.ALLOCATED=0 
 
 SELECT T1.PDATE,T1.STOCKNO,T1.QUANTITY,T1.RATE,T1.AMOUNT,T1.INDEXCODE INTO #TEMP5
 FROM 
 (
    (SELECT PDATE,STOCKNO,QUANTITY,RATE,DEBIT AMOUNT, INDEXCODE FROM #TEMP1 
	  UNION
	SELECT PDATE,STOCKNO,QUANTITY,RATE,CREDIT AMOUNT,INDEXCODE FROM #TEMP2  
	  UNION
	SELECT PDATE,STOCKNO,QUANTITY,RATE,DEBIT AMOUNT,INDEXCODE FROM #TEMP3 
	  UNION 
	SELECT DLVRDATE PDATE,STKCODE STOCKNO,DLVRQTY QUANTITY,PRICE RATE,AMOUNT,INDEXCODE FROM #TEMP4) 
 ) T1  ORDER BY STOCKNO,PDATE 

 SELECT * FROM #TEMP5

 ALTER TABLE #TEMP0 ADD OPENINGQTY   DECIMAL(18,4)
 ALTER TABLE #TEMP0 ADD OPENINGVALUE DECIMAL(18,2)

 ALTER TABLE #TEMP0 ADD RECEIPTS     DECIMAL(18,4)
 ALTER TABLE #TEMP0 ADD RECEIPTVALUE DECIMAL(18,2)

 ALTER TABLE #TEMP0 ADD ISSUES       DECIMAL(18,2)
 ALTER TABLE #TEMP0 ADD ISSUEVALUE   DECIMAL(18,2)

 ALTER TABLE #TEMP0 ADD CLOSING      DECIMAL(18,4)
 ALTER TABLE #TEMP0 ADD CLOSINGVALUE DECIMAL(18,2)



END
 