/****** Object:  Procedure [BS].[spSubConLastBillBookDetails]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE BS.spSubConLastBillBookDetails
AS


--SELECT MIN(PDATE)  FROM TRANSACTIONS WHERE CREDNO='09AAECJ138' AND YEAR=2020 AND LEDGERCODE='1320000'  
--SELECT * FROM TRANSACTIONS WHERE TRANSID=17768530
--17770400




DECLARE @SUBBIECODE VARCHAR(15)
SET @SUBBIECODE ='1320000'

SELECT CREDNO,SUM(DEBIT-CREDIT) OUTSTANDING 
INTO #OUTSTANDING 
FROM TRANSACTIONS 
WHERE YEAR=2020 AND LEDGERCODE=@SUBBIECODE AND 
ORGID IN (SELECT BORGID FROM BORGS WHERE PARENTBORG IN (23,24,25,26,27,172,209) )
GROUP BY CREDNO 

 

DELETE FROM #OUTSTANDING WHERE OUTSTANDING=0 
DELETE FROM #OUTSTANDING WHERE CREDNO=''

ALTER TABLE #OUTSTANDING ADD CONTRACT VARCHAR(15)
ALTER TABLE #OUTSTANDING ADD BILLNUMBER VARCHAR(15)
ALTER TABLE #OUTSTANDING ADD BILLAMOUNT DECIMAL(18,2)
ALTER TABLE #OUTSTANDING ADD BILLDATE   DATETIME 
ALTER TABLE #OUTSTANDING ADD TRANSID    INT
ALTER TABLE #OUTSTANDING ADD TRANGRP    INT
ALTER TABLE #OUTSTANDING ADD PERIOD INT
ALTER TABLE #OUTSTANDING ADD STATUSID  INT 
UPDATE #OUTSTANDING SET STATUSID =0 
DECLARE @MINDATE DATETIME 
DECLARE @PARTYCODE VARCHAR(15) 
DECLARE @TRANSID INT 
DECLARE @CREDNO VARCHAR(15) 

 
DECLARE SUBBIEE CURSOR FOR SELECT CREDNO FROM #OUTSTANDING 
--WHERE CREDNO IN ('03AAAFG702','03AAXFM973','03ABAPM069','03AIRPK743','03CAZPK017','03CSLPG682','04AAEFN600','05AAACC090')
OPEN SUBBIEE
FETCH NEXT FROM SUBBIEE INTO @PARTYCODE 
WHILE @@FETCH_STATUS = 0 
BEGIN
  SELECT @MINDATE=MAX(PDATE) FROM TRANSACTIONS WHERE CREDNO=@PARTYCODE AND LEDGERCODE=@SUBBIECODE AND YEAR=2020 
  AND ORGID IN (SELECT BORGID FROM BORGS WHERE PARENTBORG IN (23,24,25,26,27,172,209) ) AND ( LEFT(BATCHREF,3)='SCI' OR LEFT(BATCHREF,3)='CBC' )

  SELECT @TRANSID=TRANSID FROM TRANSACTIONS WHERE PDATE=@MINDATE AND CREDNO=@PARTYCODE AND LEDGERCODE=@SUBBIECODE AND YEAR=2020 

  
  UPDATE #OUTSTANDING 
  SET CONTRACT = T.CONTRACT,
      BILLNUMBER = T.TRANSREF,
	  BILLAMOUNT = (T.DEBIT-T.CREDIT),
	  BILLDATE = T.PDATE,
	  TRANSID = T.TRANSID ,
	  TRANGRP = T.TRANGRP ,
	  PERIOD = T.PERIOD,
	  STATUSID=1 
   FROM TRANSACTIONS T 
   WHERE #OUTSTANDING.CREDNO=@PARTYCODE AND T.TRANSID =@TRANSID 

  FETCH NEXT FROM SUBBIEE INTO @PARTYCODE 
END
CLOSE SUBBIEE
DEALLOCATE SUBBIEE

ALTER TABLE #OUTSTANDING ADD CREDNAME VARCHAR(200)
UPDATE #OUTSTANDING SET CREDNAME=S.SubName  FROM SUBCONTRACTORS S INNER JOIN #OUTSTANDING ON #OUTSTANDING.CREDNO=S.SUBNUMBER 
SELECT * FROM #OUTSTANDING 
--WHERE CREDNO IN ('03AAAFG702','03AAXFM973','03ABAPM069','03AIRPK743','03CAZPK017','03CSLPG682','04AAEFN600','05AAACC090') 
ORDER BY CREDNAME 

 