/****** Object:  Procedure [BS].[spSUBBIESTATEMENT_SUMMARY]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE [BS].[spSUBBIESTATEMENT_SUMMARY](@BORGID INT, @STARTDATESTRING AS VARCHAR(15),@ENDDATESTRING AS VARCHAR(15)) 
AS
   DECLARE @CREDITORCONTROL VARCHAR(10)
   SELECT @CREDITORCONTROL = CONTROLFROMGL FROM CONTROLCODES WHERE CONTROLNAME='Sub Contractors'
   SELECT @CREDITORCONTROL 
    DECLARE @FILENAME VARCHAR(100)
	DECLARE @FILEID   VARCHAR(10)
	DECLARE @SQL      VARCHAR(250)
	

	SET @FILENAME = 'BSBS_TEMP.DBO.SUBBIE_SUMMARY'
    DECLARE @FINYEAR INT
	DECLARE @TRANSSTARTDATE    DATETIME
	DECLARE @TRANSENDDATE      DATETIME
    SELECT  @TRANSSTARTDATE = CONVERT(DATETIME, @STARTDATESTRING,103) -- dd/mm/yyyy 
	SELECT  @TRANSENDDATE   = CONVERT(DATETIME, @ENDDATESTRING,103) -- dd/mm/yyyy 

	DECLARE @CREDNO       VARCHAR(10)
	DECLARE @STARTBANK    VARCHAR(10)
	DECLARE @ENDBANK      VARCHAR(10)
	DECLARE @BANKLEDGER   VARCHAR(10)
	DECLARE @CHEQUENUMBER VARCHAR(10)
	DECLARE @CHEQUEAMOUNT DECIMAL(18,2)
	DECLARE @CHEQUEDATE   DATE 
	DECLARE @BANKNAME     VARCHAR(50)
	DECLARE @NARRATION    VARCHAR(250)
	DECLARE @TRANTYPE     VARCHAR(10)
	DECLARE @PETTYCASH    VARCHAR(10)
	DECLARE @WIP          VARCHAR(10) 
	DECLARE @CONTRACTID   VARCHAR(10)
	DECLARE @ID           INT

	SELECT @WIP = CONTROLFROMGL FROM CONTROLCODES WHERE CONTROLNAME LIKE 'Work In Progress%'                  
	SELECT @PETTYCASH = CONTROLFROMGL FROM CONTROLCODES WHERE CONTROLNAME LIKE 'Petty Cash%'
	SELECT  @STARTBANK = CONTROLFROMGL, @ENDBANK   = CONTROLTOGL   FROM CONTROLCODES WHERE CONTROLNAME='Bank'
 
 

	IF MONTH(@TRANSSTARTDATE) IN (1,2,3)
		SET @FINYEAR = YEAR(@TRANSSTARTDATE)
	ELSE
		SET @FINYEAR = YEAR(@TRANSSTARTDATE)+1

    
	SELECT ICGLCODE INTO #INTERCOMPANY FROM BORGS WHERE ICGLCODE IS NOT NULL
	SELECT LEDGERCODE INTO #BANKS FROM LEDGERCODES WHERE LEDGERCODE BETWEEN @STARTBANK AND @ENDBANK

    DECLARE @TRANGRP   INT
	DECLARE @TRANSID   INT
	DECLARE @TRANSTYPE  VARCHAR(10) 
    
	DECLARE @CERTIFIED  DECIMAL(18,2)
	DECLARE @ADVANCE    DECIMAL(18,2)
	DECLARE @ST         DECIMAL(18,2)
	DECLARE @VAT        DECIMAL(18,2)
	DECLARE @RETENTION  DECIMAL(18,2)
	DECLARE @TDS        DECIMAL(18,2)
	DECLARE @ADMINFEE   DECIMAL(18,2)
	DECLARE @DEBITS     DECIMAL(18,2)
	DECLARE @NETPAYABLE DECIMAL(18,2) 
	DECLARE @SUBCONTRAN VARCHAR(10)
	DECLARE @WITHHELD   DECIMAL(18,2) 
	DECLARE @STREVERSE  DECIMAL(18,2) 
	DECLARE @PERIOD     INT

	CREATE TABLE #TEMP0
	(
	 TRANGRP INT,
	 TRANSTYPE    VARCHAR(10),
	 YEAR		  INT,
	 TRANSDATE    DATETIME,
	 CREDNUMBER   VARCHAR(10),
	 CREDNAME     VARCHAR(60),
	 CONTRACTID   VARCHAR(10),
	 CONTRACTNAME VARCHAR(50),
	 NARRATION    VARCHAR(250),
	 ADVANCE      DECIMAL(18,2),
	 CERTIFIED    DECIMAL(18,2),
	 ST           DECIMAL(18,2),
	 VAT          DECIMAL(18,2),
	 RETENTION    DECIMAL(18,2),
	 WITHHELD     DECIMAL(18,2),
	 DEBITS       DECIMAL(18,2),
	 ADMINFEE     DECIMAL(18,2),
	 STREVERSE    DECIMAL(18,2),
	 TDS          DECIMAL(18,2),
	 NETPAYABLE   DECIMAL(18,2),
	 CHEQUENO     VARCHAR(10),
	 BANKNAME     VARCHAR(50),
	 PAIDAMOUNT   DECIMAL(18,2) 
	
	)

			
DECLARE CREDNUMBERS CURSOR FOR
SELECT DISTINCT CREDNO FROM TRANSACTIONS 
WHERE PDATE BETWEEN @TRANSSTARTDATE AND @TRANSENDDATE AND
	    YEAR = @FINYEAR AND
		ORGID = @BORGID AND 
		LEDGERCODE=@CREDITORCONTROL 
		ORDER BY CREDNO 

OPEN CREDNUMBERS 
FETCH NEXT FROM CREDNUMBERS INTO @CREDNO
WHILE @@FETCH_STATUS = 0
BEGIN	
 

	DECLARE SUBBIES CURSOR FOR 
	SELECT DISTINCT TRANGRP,TRANSID  FROM TRANSACTIONS
    WHERE PDATE BETWEEN @TRANSSTARTDATE AND @TRANSENDDATE AND YEAR = @FINYEAR AND ORGID = @BORGID AND CREDNO= @CREDNO  AND LEDGERCODE=@CREDITORCONTROL 
	ORDER BY TRANGRP 

	OPEN SUBBIES 
	FETCH  NEXT FROM SUBBIES INTO @TRANGRP , @ID

	WHILE @@FETCH_STATUS = 0
	BEGIN
		SELECT @TRANSTYPE = LEFT(BATCHREF,3),@TRANTYPE=TRANSTYPE,@CONTRACTID = CONTRACT  FROM TRANSACTIONS WHERE TRANGRP = @TRANGRP AND TRANSID = @ID
 
		SET @RETENTION = 0
		SET @WITHHELD = 0 
		SET @CERTIFIED=0
		SET @ST = 0
		SET @TDS = 0
		SET @NETPAYABLE = 0
		SET @VAT = 0
		SET @ADMINFEE = 0
		SET @VAT = 0
		SET @DEBITS = 0 
		SET @STREVERSE = 0 
		SET @ADVANCE = 0 
		SET @CHEQUEAMOUNT  = 0 


		IF @TRANSTYPE IN ('CBC','CBD','SCP','CRA')  
		BEGIN
		  IF @TRANTYPE<>'REV'
		   BEGIN
		    SELECT  @NARRATION=DESCRIPTION FROM TRANSACTIONS WHERE TRANGRP=@TRANGRP AND LEDGERCODE = @CREDITORCONTROL 
			SELECT  @TRANSID = TRANSID  FROM TRANSACTIONS WHERE TRANGRP =@TRANGRP   AND LEDGERCODE IN (SELECT LEDGERCODE FROM #BANKS ) 
			SELECT  @BANKLEDGER=LEDGERCODE , @CHEQUENUMBER=TRANSREF,@CHEQUEAMOUNT=(CREDIT-DEBIT) ,@CHEQUEDATE = PDATE FROM TRANSACTIONS  WHERE TRANSID=@TRANSID 
			SELECT  @BANKNAME=LEDGERNAME FROM LEDGERCODES  WHERE LEDGERCODE=@BANKLEDGER
			INSERT INTO #TEMP0 (TRANGRP,TRANSTYPE,YEAR,TRANSDATE,CREDNUMBER,CREDNAME,CONTRACTID,CONTRACTNAME,NARRATION,ADVANCE,CERTIFIED,ST,VAT,RETENTION,
							    WITHHELD,DEBITS,ADMINFEE,STREVERSE,NETPAYABLE,CHEQUENO,BANKNAME,PAIDAMOUNT,TDS ) 
			VALUES (@TRANGRP,@TRANSTYPE,@FINYEAR,@CHEQUEDATE,@CREDNO,SPACE(50),@CONTRACTID,SPACE(10), @NARRATION,0,0,0,0,0,0,0,0,0,0,@CHEQUENUMBER,@BANKNAME,@CHEQUEAMOUNT,0) 
		  END
         ELSE
		  BEGIN
		    SELECT @NARRATION=DESCRIPTION,@CHEQUEAMOUNT = (DEBIT-CREDIT),@CHEQUEDATE=PDATE  FROM TRANSACTIONS WHERE TRANGRP=@TRANGRP AND LEDGERCODE = @CREDITORCONTROL
			INSERT INTO #TEMP0 (TRANGRP,TRANSTYPE,YEAR,TRANSDATE,CREDNUMBER,CREDNAME,CONTRACTID,CONTRACTNAME,NARRATION,ADVANCE,CERTIFIED,ST,VAT,RETENTION,
							    WITHHELD,DEBITS,ADMINFEE,STREVERSE,NETPAYABLE,CHEQUENO,BANKNAME,PAIDAMOUNT,TDS) 
			VALUES (@TRANGRP,@TRANSTYPE,@FINYEAR,@CHEQUEDATE,@CREDNO,SPACE(50),@CONTRACTID,SPACE(10), @NARRATION,0,0,0,0,0,0,0,0,0,0,0,SPACE(10),@CHEQUEAMOUNT,0) 
		  END
		END 
		

		IF @TRANSTYPE IN ('PCP','PCR')  
		BEGIN
	 
		  IF @TRANTYPE<>'REV'
		   BEGIN
		    SELECT  @NARRATION=DESCRIPTION FROM TRANSACTIONS WHERE TRANGRP=@TRANGRP AND LEDGERCODE = @CREDITORCONTROL
			SELECT  @TRANSID = TRANSID  FROM TRANSACTIONS WHERE TRANGRP =@TRANGRP   AND LEDGERCODE =@PETTYCASH 
			SELECT  @BANKLEDGER=LEDGERCODE , @CHEQUENUMBER=TRANSREF,@CHEQUEAMOUNT=(CREDIT-DEBIT) ,@CHEQUEDATE = PDATE FROM TRANSACTIONS  WHERE TRANSID=@TRANSID 
			SELECT  @BANKNAME=LEDGERNAME FROM LEDGERCODES  WHERE LEDGERCODE=@BANKLEDGER
			INSERT INTO #TEMP0 (TRANGRP,TRANSTYPE,YEAR,TRANSDATE,CREDNUMBER,CREDNAME,CONTRACTID,CONTRACTNAME,NARRATION,ADVANCE,CERTIFIED,ST,VAT,RETENTION,
							    WITHHELD,DEBITS,ADMINFEE,STREVERSE,NETPAYABLE,CHEQUENO,BANKNAME,PAIDAMOUNT,TDS) 
			VALUES (@TRANGRP,@TRANSTYPE,@FINYEAR,@CHEQUEDATE,@CREDNO,SPACE(50),@CONTRACTID,SPACE(10), @NARRATION,0,0,0,0,0,0,0,0,0,0,@CHEQUENUMBER,@BANKNAME,@CHEQUEAMOUNT,0) 
		  END
         ELSE
		  BEGIN
		    SELECT @NARRATION=DESCRIPTION,@CHEQUEAMOUNT = (DEBIT-CREDIT),@CHEQUEDATE=PDATE  FROM TRANSACTIONS WHERE TRANGRP=@TRANGRP AND LEDGERCODE = @CREDITORCONTROL
			INSERT INTO #TEMP0 (TRANGRP,TRANSTYPE,YEAR,TRANSDATE,CREDNUMBER,CREDNAME,CONTRACTID,CONTRACTNAME,NARRATION,ADVANCE,CERTIFIED,ST,VAT,RETENTION,
							    WITHHELD,DEBITS,ADMINFEE,STREVERSE,NETPAYABLE,CHEQUENO,BANKNAME,PAIDAMOUNT,TDS) 
			VALUES (@TRANGRP,@TRANSTYPE,@FINYEAR,@CHEQUEDATE,@CREDNO,SPACE(50),@CONTRACTID,SPACE(10), @NARRATION,0,0,0,0,0,0,0,0,0,0,0,SPACE(10),@CHEQUEAMOUNT,0) 
		  END
		END 
		
		
		IF @TRANSTYPE = 'JNL' 
		 BEGIN
		
		   SELECT @CHEQUEDATE=PDATE,@NARRATION=DESCRIPTION, @CERTIFIED = (CREDIT-DEBIT),@CHEQUENUMBER=TRANSREF, @SUBCONTRAN=LTRIM(RTRIM(SUBCONTRAN))  FROM TRANSACTIONS 
		   WHERE TRANGRP=@TRANGRP AND CREDNO=@CREDNO AND TRANSTYPE='JNL' AND TRANSID = @ID 
 
		   SET @ADVANCE = 0
		   SET @RETENTION = 0
		   IF @SUBCONTRAN='Advance'
		      BEGIN
			    SET @ADVANCE = @CERTIFIED 
				SET @CERTIFIED = 0
				SET @RETENTION =0 
			  END
		   IF @SUBCONTRAN = 'Retention'
		      BEGIN
			    SET @RETENTION = @CERTIFIED
				SET @CERTIFIED = 0 
				SET @ADVANCE=0
			  END
            IF @SUBCONTRAN='Certified Amount' 
			  BEGIN
			    SET @CERTIFIED = @CERTIFIED
				SET @RETENTION = 0
				SET @ADVANCE = 0
			  END
			SET @NETPAYABLE = @ADVANCE+@CERTIFIED+@ST+@VAT-@DEBITS-@ADMINFEE-@WITHHELD-@RETENTION-@TDS 
		    INSERT INTO #TEMP0 (TRANGRP,TRANSTYPE,YEAR,TRANSDATE,CREDNUMBER,CREDNAME,CONTRACTID,CONTRACTNAME,NARRATION,ADVANCE,CERTIFIED,ST,VAT,RETENTION,
							    WITHHELD,DEBITS,ADMINFEE,STREVERSE,NETPAYABLE,CHEQUENO,BANKNAME,PAIDAMOUNT,TDS) 
			VALUES (@TRANGRP,'JNL',@FINYEAR,@CHEQUEDATE,@CREDNO,SPACE(50),@CONTRACTID,SPACE(10), @NARRATION,@ADVANCE,@CERTIFIED,@ST,@VAT,
			@RETENTION,@WITHHELD,@DEBITS,@ADMINFEE,@STREVERSE,@NETPAYABLE,@CHEQUENUMBER,SPACE(1),@CHEQUEAMOUNT,@TDS) 
		    
		 END
		
		 IF @TRANSTYPE = 'SCI'
		 BEGIN
		    SELECT @PERIOD=PERIOD,@CHEQUEDATE=PDATE FROM TRANSACTIONS WHERE TRANGRP=@TRANGRP AND CREDNO=@CREDNO 
			SELECT @NARRATION=DESCRIPTION,@CHEQUENUMBER=TRANSREF FROM TRANSACTIONS WHERE TRANGRP=@TRANGRP AND CREDNO=@CREDNO AND SUBCONTRAN IN ('Payment','Advance', 'Retention') 
			IF @PERIOD=0 
			BEGIN
			  SELECT @TRANGRP 
			  SELECT @CHEQUEDATE=PDATE,@CERTIFIED = (CREDIT-DEBIT),@CHEQUENUMBER=TRANSREF, @SUBCONTRAN=SUBCONTRAN  FROM TRANSACTIONS 
			  WHERE TRANGRP=@TRANGRP AND CREDNO=@CREDNO 
		     SET @ADVANCE = 0
		     SET @RETENTION = 0
		     IF @SUBCONTRAN='Advance'
		      BEGIN
			    SET @ADVANCE = @CERTIFIED 
				SET @CERTIFIED = 0
			  END
		     IF @SUBCONTRAN = 'Retention'
		      BEGIN
			    SET @RETENTION = @CERTIFIED
				SET @CERTIFIED = 0 
			  END
			END
			IF @PERIOD<>0
			BEGIN
			  SET @RETENTION = 0
			  SET @WITHHELD = 0 
			  SET @CERTIFIED=0
			  SET @ST = 0
			  SET @TDS = 0
			  SET @NETPAYABLE = 0
			  SET @VAT = 0
			  SET @ADMINFEE = 0
			  SET @VAT = 0
			  SET @DEBITS = 0 
			  SET @STREVERSE = 0 
			  SET @ADVANCE = 0 

			  SELECT ALLOCATION,LEDGERCODE,SUM(DEBIT-CREDIT) AMOUNTS INTO #TEMP9 FROM 
			  TRANSACTIONS WHERE TRANGRP = @TRANGRP   
			  GROUP BY ALLOCATION,LEDGERCODE 
			  SELECT @RETENTION  =ABS(ISNULL( SUM(DEBIT-CREDIT),0))  FROM TRANSACTIONS WHERE TRANGRP= @TRANGRP AND DESCRIPTION LIKE  '%Retention%' AND LEDGERCODE=@CREDITORCONTROL
			  SELECT @CERTIFIED = ABS(AMOUNTS) FROM #TEMP9 WHERE ALLOCATION='Contracts' AND LEDGERCODE NOT IN ( '5120242','5120241') 
			  SELECT @ST =ABS(AMOUNTS) FROM #TEMP9 WHERE LEDGERCODE='1310002'
			  SELECT @TDS =ABS(AMOUNTS) FROM #TEMP9 WHERE LEDGERCODE='1310005'
			  
			  SELECT @DEBITS = ABS(AMOUNTS) FROM #TEMP9 WHERE LEDGERCODE='1300213'
			  SELECT @VAT = ABS(AMOUNTS) FROM #TEMP9 WHERE LEDGERCODE='1310000'
			  SELECT @STREVERSE = ABS(AMOUNTS) FROM #TEMP9 WHERE LEDGERCODE='1310010'
			  SELECT @ADVANCE =  AMOUNTS  FROM #TEMP9 WHERE LEDGERCODE='1320003' 
			  SELECT @ADMINFEE = ABS(AMOUNTS) FROM #TEMP9 WHERE LEDGERCODE= '5120241'
			  SELECT @WITHHELD = ABS(AMOUNTS) FROM #TEMP9 WHERE LEDGERCODE= '5120242'
			  SET @CERTIFIED = @CERTIFIED - @RETENTION
			  SET @NETPAYABLE = @ADVANCE+@CERTIFIED+@ST+@VAT-@DEBITS-@ADMINFEE-@WITHHELD-@RETENTION-@TDS 
		 

			  DROP TABLE #TEMP9 
			
			  INSERT INTO #TEMP0 (TRANGRP,TRANSTYPE,YEAR,TRANSDATE,CREDNUMBER,CREDNAME,CONTRACTID,CONTRACTNAME,NARRATION,ADVANCE,CERTIFIED,ST,VAT,RETENTION,
							    WITHHELD,DEBITS,ADMINFEE,STREVERSE,NETPAYABLE,CHEQUENO,BANKNAME,PAIDAMOUNT,TDS ) 
			  VALUES (@TRANGRP,@TRANSTYPE,@FINYEAR,@CHEQUEDATE,@CREDNO,SPACE(50),@CONTRACTID,SPACE(10), @NARRATION,@ADVANCE,
			  @CERTIFIED,@ST,@VAT,@RETENTION,@WITHHELD,@DEBITS,@ADMINFEE,@STREVERSE,@NETPAYABLE ,@CHEQUENUMBER,SPACE(1),0,@TDS ) 
			END 
		 END 
		
		FETCH  NEXT FROM SUBBIES INTO @TRANGRP ,@ID 
	END
	CLOSE SUBBIES
	DEALLOCATE SUBBIES

	FETCH NEXT FROM CREDNUMBERS INTO @CREDNO


END
CLOSE CREDNUMBERS
DEALLOCATE CREDNUMBERS


SELECT CREDNUMBER,
       SUM(ADVANCE) ADVANCE,
	   SUM(CERTIFIED) CERTIFIED,
	   SUM(ST) ST,
	   SUM(VAT) VAT,
	   SUM(RETENTION) RETENTION, 
	   SUM(WITHHELD) WITHHELD,
	   SUM(DEBITS) DEBITS,
       SUM(ADMINFEE) ADMINFEE,
	   SUM(TDS) TDS, 
	   SUM(NETPAYABLE) NETPAYABLE,
	   SUM(PAIDAMOUNT) PAID 
INTO #TEMPN
FROM #TEMP0
GROUP BY CREDNUMBER 

ALTER TABLE #TEMPN ADD CREDNAME VARCHAR(250)
UPDATE #TEMPN SET CREDNAME=S.SUBNAME FROM SUBCONTRACTORS S INNER JOIN #TEMPN ON #TEMPN.CREDNUMBER=S.SUBNUMBER 

 

 

	ALTER TABLE #TEMPN ADD BORGID INT
	ALTER TABLE #TEMPN ADD BORGNAME VARCHAR(100)
	ALTER TABLE #TEMPN ADD STARTDATE DATETIME
	ALTER TABLE #TEMPN ADD ENDDATE   DATETIME 
	UPDATE #TEMPN SET BORGID = @BORGID 
	UPDATE #TEMPN SET STARTDATE = @TRANSSTARTDATE
	UPDATE #TEMPN SET ENDDATE =@TRANSENDDATE
	UPDATE #TEMPN SET BORGNAME = B.BORGNAME FROM BORGS B INNER JOIN #TEMPN ON #TEMPN.BORGID = B.BORGID 


	 

    
	DECLARE @Random INT;
	DECLARE @Upper INT;
	DECLARE @Lower INT
 
	SET @Lower = 1 ---- The lowest random number
	SET @Upper = 999 ---- The highest random number
	SELECT @Random = ROUND(((@Upper - @Lower -1) * RAND() + @Lower), 0)

	SELECT @FILEID= CONVERT(INT,RAND( (DATEPART(mm, GETDATE()) * 100000 )
		+ (DATEPART(ss, GETDATE()) * 1000 )
		+ DATEPART(ms, GETDATE()) )*1000) + STR(@RANDOM) 

	SET @FILENAME = @FILENAME+LTRIM(RTRIM(CONVERT(VARCHAR(6),@FILEID)))

	SET @SQL = 'SELECT *  INTO '+@FILENAME+ ' FROM   #TEMPN  ORDER BY CREDNAME '
 
   EXEC(@SQL)

   RETURN @FILEID
 