/****** Object:  Procedure [BS].[spSUBBIESTATEMENT1]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE  PROCEDURE [BS].[spSUBBIESTATEMENT1](@BORGID INT, @STARTDATESTRING AS VARCHAR(15),@ENDDATESTRING AS VARCHAR(15),@CREDNO VARCHAR(10)) 
AS
    DECLARE @CREDITORCONTROL VARCHAR(10)
    SELECT @CREDITORCONTROL = CONTROLFROMGL FROM CONTROLCODES WHERE CONTROLNAME='Sub Contractors'
    SELECT @CREDITORCONTROL 
    DECLARE @FILENAME VARCHAR(100)
	DECLARE @FILEID   VARCHAR(10)
	DECLARE @SQL      VARCHAR(250)
	

	SET @FILENAME = 'BSBS_TEMP.DBO.SUBBIE_MOVEMENT'
    DECLARE @FINYEAR INT
	DECLARE @TRANSSTARTDATE    DATETIME
	DECLARE @TRANSENDDATE      DATETIME
    SELECT  @TRANSSTARTDATE = CONVERT(DATETIME, @STARTDATESTRING,103) -- dd/mm/yyyy 
	SELECT  @TRANSENDDATE   = CONVERT(DATETIME, @ENDDATESTRING,103) -- dd/mm/yyyy 
	
	IF MONTH(@TRANSSTARTDATE) IN (1,2,3)
		SET @FINYEAR = YEAR(@TRANSSTARTDATE)
	ELSE
		SET @FINYEAR = YEAR(@TRANSSTARTDATE)+1
	
 

	SELECT 
      PDATE,BATCHREF,TRANSREF,TRANSTYPE,LEDGERCODE,DESCRIPTION,CREDNO,DEBIT,CREDIT,TRANGRP,PERIOD
	INTO #TEMPFILE
    FROM 
	  TRANSACTIONS
    WHERE LEDGERCODE=@CREDITORCONTROL  AND CREDNO=@CREDNO AND PDATE BETWEEN  @TRANSSTARTDATE  AND @TRANSENDDATE AND  YEAR=@FINYEAR    AND ORGID = @BORGID
	
	SELECT * FROM #TEMPFILE 

	DECLARE @STARTBANK    VARCHAR(10)
	DECLARE @ENDBANK      VARCHAR(10)
	DECLARE @BANKLEDGER   VARCHAR(10)
	DECLARE @CHEQUENUMBER VARCHAR(10)
	DECLARE @CHEQUEAMOUNT DECIMAL(18,2)
	DECLARE @CHEQUEDATE   DATE 
	DECLARE @BANKNAME     VARCHAR(50)
	DECLARE @NARRATION    VARCHAR(250)
	DECLARE @TRANTYPE     VARCHAR(10)
	DECLARE @PETTYCASH    VARCHAR(10)
	DECLARE @WIP          VARCHAR(10) 
	DECLARE @CONTRACTID   VARCHAR(10)
	DECLARE @ID           INT

	SELECT  @WIP = CONTROLFROMGL FROM CONTROLCODES WHERE CONTROLNAME LIKE 'Work In Progress%'                  
	SELECT  @PETTYCASH = CONTROLFROMGL FROM CONTROLCODES WHERE CONTROLNAME LIKE 'Petty Cash%'
	SELECT  @STARTBANK = CONTROLFROMGL, @ENDBANK   = CONTROLTOGL   FROM CONTROLCODES WHERE CONTROLNAME='Bank'
 
 


    
	SELECT ICGLCODE INTO #INTERCOMPANY FROM BORGS WHERE ICGLCODE IS NOT NULL
	SELECT LEDGERCODE INTO #BANKS FROM LEDGERCODES WHERE LEDGERCODE BETWEEN @STARTBANK AND @ENDBANK

    DECLARE @TRANGRP   INT
	DECLARE @TRANSID   INT
	DECLARE @TRANSTYPE  VARCHAR(10) 
    
	DECLARE @CERTIFIED  DECIMAL(18,2)
	DECLARE @ADVANCE    DECIMAL(18,2)
	DECLARE @ST         DECIMAL(18,2)
	DECLARE @VAT        DECIMAL(18,2)
	DECLARE @RETENTION  DECIMAL(18,2)
	DECLARE @TDS        DECIMAL(18,2)
	DECLARE @ADMINFEE   DECIMAL(18,2)
	DECLARE @DEBITS     DECIMAL(18,2)
	DECLARE @NETPAYABLE DECIMAL(18,2) 
	DECLARE @SUBCONTRAN VARCHAR(10)
	DECLARE @WITHHELD   DECIMAL(18,2) 
	DECLARE @STREVERSE  DECIMAL(18,2) 
	DECLARE @PERIOD     INT
	DECLARE @TRANSREF   VARCHAR(10)

	CREATE TABLE #TEMP0
	(
	 TRANGRP INT,
	 TRANSTYPE    VARCHAR(10),
	 YEAR		  INT,
	 TRANSDATE    DATETIME,
	 CREDNUMBER   VARCHAR(10),
	 CREDNAME     VARCHAR(60),
	 CONTRACTID   VARCHAR(10),
	 CONTRACTNAME VARCHAR(50),
	 NARRATION    VARCHAR(250),
	 ADVANCE      DECIMAL(18,2),
	 CERTIFIED    DECIMAL(18,2),
	 ST           DECIMAL(18,2),
	 VAT          DECIMAL(18,2),
	 RETENTION    DECIMAL(18,2),
	 WITHHELD     DECIMAL(18,2),
	 DEBITS       DECIMAL(18,2),
	 ADMINFEE     DECIMAL(18,2),
	 STREVERSE    DECIMAL(18,2),
	 TDS          DECIMAL(18,2),
	 NETPAYABLE   DECIMAL(18,2),
	 CHEQUENO     VARCHAR(10),
	 BANKNAME     VARCHAR(50),
	 PAIDAMOUNT   DECIMAL(18,2) 
	
	)
	
	CREATE TABLE #TEMPJNL
	(
	 TRANGRP INT,
	 TRANSTYPE    VARCHAR(10),
	 YEAR		  INT,
	 TRANSDATE    DATETIME,
	 CREDNUMBER   VARCHAR(10),
	 CREDNAME     VARCHAR(60),
	 CONTRACTID   VARCHAR(10),
	 CONTRACTNAME VARCHAR(50),
	 NARRATION    VARCHAR(250),
	 ADVANCE      DECIMAL(18,2),
	 CERTIFIED    DECIMAL(18,2),
	 ST           DECIMAL(18,2),
	 VAT          DECIMAL(18,2),
	 RETENTION    DECIMAL(18,2),
	 WITHHELD     DECIMAL(18,2),
	 DEBITS       DECIMAL(18,2),
	 ADMINFEE     DECIMAL(18,2),
	 STREVERSE    DECIMAL(18,2),
	 TDS          DECIMAL(18,2),
	 NETPAYABLE   DECIMAL(18,2),
	 CHEQUENO     VARCHAR(10),
	 BANKNAME     VARCHAR(50),
	 PAIDAMOUNT   DECIMAL(18,2) 
	
	)



	DECLARE SUBBIES CURSOR FOR 
	SELECT DISTINCT TRANGRP,TRANSREF,PERIOD    FROM #TEMPFILE
  	ORDER BY TRANGRP 
 

	OPEN SUBBIES 
	FETCH  NEXT FROM SUBBIES INTO @TRANGRP,@TRANSREF, @PERIOD 

	WHILE @@FETCH_STATUS = 0
	BEGIN
	

		SELECT @TRANSTYPE = LEFT(BATCHREF,3), @TRANTYPE=TRANSTYPE, @CONTRACTID = CONTRACT  FROM TRANSACTIONS WHERE
		 TRANGRP = @TRANGRP AND LEDGERCODE=@CREDITORCONTROL  AND ORGID=@BORGID AND YEAR=@FINYEAR AND CREDNO=@CREDNO AND PERIOD=@PERIOD AND
		 TRANSREF=@TRANSREF 
   
        SELECT @TRANGRP      , @TRANSTYPE , @TRANTYPE 


		SET @RETENTION = 0
		SET @WITHHELD = 0 
		SET @CERTIFIED=0
		SET @ST = 0
		SET @TDS = 0
		SET @NETPAYABLE = 0
		SET @VAT = 0
		SET @ADMINFEE = 0
		SET @VAT = 0
		SET @DEBITS = 0 
		SET @STREVERSE = 0 
		SET @ADVANCE = 0 
		SET @CHEQUEAMOUNT  = 0 

 

		IF @TRANSTYPE IN ('CBC','CBD','SCP','CRA')  
		BEGIN
		  IF @TRANTYPE<>'REV'
		   BEGIN
		    SELECT  @NARRATION=DESCRIPTION FROM TRANSACTIONS WHERE TRANGRP=@TRANGRP AND LEDGERCODE = @CREDITORCONTROL 
			SELECT  @TRANSID = TRANSID  FROM TRANSACTIONS WHERE TRANGRP =@TRANGRP   AND LEDGERCODE IN (SELECT LEDGERCODE FROM #BANKS ) 
			SELECT  @BANKLEDGER=LEDGERCODE , @CHEQUENUMBER=TRANSREF,@CHEQUEAMOUNT=(CREDIT-DEBIT) ,@CHEQUEDATE = PDATE FROM TRANSACTIONS  WHERE TRANSID=@TRANSID 
			SELECT  @BANKNAME=LEDGERNAME FROM LEDGERCODES  WHERE LEDGERCODE=@BANKLEDGER
			INSERT INTO #TEMP0 (TRANGRP,TRANSTYPE,YEAR,TRANSDATE,CREDNUMBER,CREDNAME,CONTRACTID,CONTRACTNAME,NARRATION,ADVANCE,CERTIFIED,ST,VAT,RETENTION,
							    WITHHELD,DEBITS,ADMINFEE,STREVERSE,NETPAYABLE,CHEQUENO,BANKNAME,PAIDAMOUNT,TDS ) 
			VALUES (@TRANGRP,@TRANSTYPE,@FINYEAR,@CHEQUEDATE,@CREDNO,SPACE(50),@CONTRACTID,SPACE(10), @NARRATION,0,0,0,0,0,0,0,0,0,0,@CHEQUENUMBER,@BANKNAME,@CHEQUEAMOUNT,0) 
		  END
         ELSE
		  BEGIN
		    SELECT @NARRATION=DESCRIPTION,@CHEQUEAMOUNT = (DEBIT-CREDIT),@CHEQUEDATE=PDATE  FROM TRANSACTIONS WHERE TRANGRP=@TRANGRP AND LEDGERCODE = @CREDITORCONTROL
			INSERT INTO #TEMP0 (TRANGRP,TRANSTYPE,YEAR,TRANSDATE,CREDNUMBER,CREDNAME,CONTRACTID,CONTRACTNAME,NARRATION,ADVANCE,CERTIFIED,ST,VAT,RETENTION,
							    WITHHELD,DEBITS,ADMINFEE,STREVERSE,NETPAYABLE,CHEQUENO,BANKNAME,PAIDAMOUNT,TDS) 
			VALUES (@TRANGRP,@TRANSTYPE,@FINYEAR,@CHEQUEDATE,@CREDNO,SPACE(50),@CONTRACTID,SPACE(10), @NARRATION,0,0,0,0,0,0,0,0,0,0,0,SPACE(10),@CHEQUEAMOUNT,0) 
		  END
		END 
		

		IF @TRANSTYPE IN ('PCP','PCR')  
		BEGIN
	 
		  IF @TRANTYPE<>'REV'
		   BEGIN
		    SELECT  @NARRATION=DESCRIPTION FROM TRANSACTIONS WHERE TRANGRP=@TRANGRP AND LEDGERCODE = @CREDITORCONTROL
			SELECT  @TRANSID = TRANSID  FROM TRANSACTIONS WHERE TRANGRP =@TRANGRP   AND LEDGERCODE =@PETTYCASH 
			SELECT  @BANKLEDGER=LEDGERCODE , @CHEQUENUMBER=TRANSREF,@CHEQUEAMOUNT=(CREDIT-DEBIT) ,@CHEQUEDATE = PDATE FROM TRANSACTIONS  WHERE TRANSID=@TRANSID 
			SELECT  @BANKNAME=LEDGERNAME FROM LEDGERCODES  WHERE LEDGERCODE=@BANKLEDGER
			INSERT INTO #TEMP0 (TRANGRP,TRANSTYPE,YEAR,TRANSDATE,CREDNUMBER,CREDNAME,CONTRACTID,CONTRACTNAME,NARRATION,ADVANCE,CERTIFIED,ST,VAT,RETENTION,
							    WITHHELD,DEBITS,ADMINFEE,STREVERSE,NETPAYABLE,CHEQUENO,BANKNAME,PAIDAMOUNT,TDS) 
			VALUES (@TRANGRP,@TRANSTYPE,@FINYEAR,@CHEQUEDATE,@CREDNO,SPACE(50),@CONTRACTID,SPACE(10), @NARRATION,0,0,0,0,0,0,0,0,0,0,@CHEQUENUMBER,@BANKNAME,@CHEQUEAMOUNT,0) 
		  END
         ELSE
		  BEGIN
		    SELECT @NARRATION=DESCRIPTION,@CHEQUEAMOUNT = (DEBIT-CREDIT),@CHEQUEDATE=PDATE  FROM TRANSACTIONS WHERE TRANGRP=@TRANGRP AND LEDGERCODE = @CREDITORCONTROL
			INSERT INTO #TEMP0 (TRANGRP,TRANSTYPE,YEAR,TRANSDATE,CREDNUMBER,CREDNAME,CONTRACTID,CONTRACTNAME,NARRATION,ADVANCE,CERTIFIED,ST,VAT,RETENTION,
							    WITHHELD,DEBITS,ADMINFEE,STREVERSE,NETPAYABLE,CHEQUENO,BANKNAME,PAIDAMOUNT,TDS) 
			VALUES (@TRANGRP,@TRANSTYPE,@FINYEAR,@CHEQUEDATE,@CREDNO,SPACE(50),@CONTRACTID,SPACE(10), @NARRATION,0,0,0,0,0,0,0,0,0,0,0,SPACE(10),@CHEQUEAMOUNT,0) 
		  END
		END 
		
		
		IF @TRANSTYPE = 'JNL' 
		 BEGIN
		   INSERT INTO #TEMPJNL (TRANGRP,TRANSTYPE,YEAR,TRANSDATE,CREDNUMBER,CREDNAME,CONTRACTID,CONTRACTNAME,NARRATION,ADVANCE,CERTIFIED,ST,VAT,RETENTION,
						    WITHHELD,DEBITS,ADMINFEE,STREVERSE,NETPAYABLE,CHEQUENO,BANKNAME,PAIDAMOUNT,TDS) 
		   SELECT @TRANGRP,'JNL',YEAR,PDATE,CREDNO,SPACE(50),CONTRACT,SUBCONTRAN, DESCRIPTION,(CREDIT-DEBIT),0,0,0,0,0,0,0,0,0,SPACE(10),SPACE(10),0,0 
		   FROM TRANSACTIONS WHERE TRANGRP=@TRANGRP AND LEDGERCODE=@CREDITORCONTROL AND CREDNO=@CREDNO AND ORGID=@BORGID AND YEAR=@FINYEAR AND PERIOD=@PERIOD 

		   SELECT * FROM #TEMPJNL 
	       UPDATE #TEMPJNL SET CERTIFIED=ADVANCE WHERE CONTRACTNAME='Certified Amount' 
		   UPDATE #TEMPJNL SET RETENTION=ADVANCE WHERE CONTRACTNAME='Retention'
		  
		   UPDATE #TEMPJNL SET ADVANCE = 0 WHERE CONTRACTNAME IN ('Certified Amount','Retention' )
		   UPDATE #TEMPJNL SET NETPAYABLE = ADVANCE+CERTIFIED+ST+VAT-DEBITS-ADMINFEE-WITHHELD+RETENTION-TDS
		   INSERT INTO #TEMP0 
		   SELECT * FROM #TEMPJNL
		   DELETE FROM #TEMPJNL

				    
		 END
		SELECT @TRANSTYPE 
		 IF @TRANSTYPE = 'SCI'
		 BEGIN
		    SELECT @PERIOD=PERIOD,@CHEQUEDATE=PDATE FROM TRANSACTIONS WHERE TRANGRP=@TRANGRP AND CREDNO=@CREDNO 
			SELECT @NARRATION=DESCRIPTION,@CHEQUENUMBER=TRANSREF FROM TRANSACTIONS WHERE TRANGRP=@TRANGRP AND CREDNO=@CREDNO AND SUBCONTRAN IN ('Payment','Advance', 'Retention') 
			  SET @RETENTION = 0
			  SET @WITHHELD = 0 
			  SET @CERTIFIED=0
			  SET @ST = 0
			  SET @TDS = 0
			  SET @NETPAYABLE = 0
			  SET @VAT = 0
			  SET @ADMINFEE = 0
			  SET @VAT = 0
			  SET @DEBITS = 0 
			  SET @STREVERSE = 0 
			  SET @ADVANCE = 0 

			  SELECT ALLOCATION,SUBCONTRAN,LEDGERCODE,ABS(SUM(CREDIT-DEBIT)) AMOUNTS INTO #TEMP9 FROM 
			  TRANSACTIONS WHERE TRANGRP = @TRANGRP   AND ORGID=@BORGID AND CREDNO=@CREDNO AND PERIOD=@PERIOD
			  GROUP BY ALLOCATION,SUBCONTRAN,LEDGERCODE 
			  SELECT * FROM #TEMP9 
			  SELECT @RETENTION  =ABS(ISNULL( SUM(DEBIT-CREDIT),0))  
			    FROM TRANSACTIONS WHERE TRANGRP= @TRANGRP AND DESCRIPTION LIKE  '%Retention%' AND LEDGERCODE=@CREDITORCONTROL AND ORGID=@BORGID AND PERIOD<>0  AND
				CREDNO=@CREDNO 
			  SELECT @CERTIFIED =  ABS(AMOUNTS)  FROM #TEMP9 WHERE ALLOCATION='Contracts' AND ( LEDGERCODE NOT IN ( '5120242','5120241')  ) OR ( SUBCONTRAN='Certified Amount')
			  SELECT @ADVANCE = AMOUNTS   FROM #TEMP9 WHERE SUBCONTRAN='Advance' 
			  SELECT @ST =ABS(AMOUNTS) FROM #TEMP9 WHERE LEDGERCODE='1310002'
			  SELECT @TDS =ABS(AMOUNTS) FROM #TEMP9 WHERE LEDGERCODE='1310005'
			  
			  SELECT @DEBITS = ABS(AMOUNTS) FROM #TEMP9 WHERE LEDGERCODE='1300213'
			  SELECT @VAT = ABS(AMOUNTS) FROM #TEMP9 WHERE LEDGERCODE='1310000'
			  SELECT @STREVERSE = ABS(AMOUNTS) FROM #TEMP9 WHERE LEDGERCODE='1310010'
			  SELECT @ADVANCE =  AMOUNTS  FROM #TEMP9 WHERE LEDGERCODE='1320003' 
			  SELECT @ADMINFEE = ABS(AMOUNTS) FROM #TEMP9 WHERE LEDGERCODE= '5120241'
			  SELECT @WITHHELD = ABS(AMOUNTS) FROM #TEMP9 WHERE LEDGERCODE= '5120242'
			  SET @CERTIFIED = @CERTIFIED - @RETENTION
			  SELECT @RETENTION,@CERTIFIED,@ST,@TDS,@DEBITS,@VAT,@STREVERSE,@ADVANCE,@ADMINFEE,@WITHHELD 
			  SET @NETPAYABLE = @ADVANCE+@CERTIFIED+@ST+@VAT-@DEBITS-@ADMINFEE-@WITHHELD-@TDS +@RETENTION
		 

			  DROP TABLE #TEMP9 
			
			  INSERT INTO #TEMP0 (TRANGRP,TRANSTYPE,YEAR,TRANSDATE,CREDNUMBER,CREDNAME,CONTRACTID,CONTRACTNAME,NARRATION,ADVANCE,CERTIFIED,ST,VAT,RETENTION,
							    WITHHELD,DEBITS,ADMINFEE,STREVERSE,NETPAYABLE,CHEQUENO,BANKNAME,PAIDAMOUNT,TDS ) 
			  VALUES (@TRANGRP,@TRANSTYPE,@FINYEAR,@CHEQUEDATE,@CREDNO,SPACE(50),@CONTRACTID,SPACE(10), @NARRATION,@ADVANCE,
			  @CERTIFIED,@ST,@VAT,@RETENTION,@WITHHELD,@DEBITS,@ADMINFEE,@STREVERSE,@NETPAYABLE ,@CHEQUENUMBER,SPACE(1),0,@TDS ) 
	 
			END 
	 
		FETCH  NEXT FROM SUBBIES INTO  @TRANGRP,@TRANSREF, @PERIOD 
	END

	ALTER TABLE #TEMP0 ADD BORGID INT
	ALTER TABLE #TEMP0 ADD BORGNAME VARCHAR(100)
	ALTER TABLE #TEMP0 ADD STARTDATE DATETIME
	ALTER TABLE #TEMP0 ADD ENDDATE   DATETIME 
	UPDATE #TEMP0 SET BORGID = @BORGID 
	UPDATE #TEMP0 SET STARTDATE = @TRANSSTARTDATE
	UPDATE #TEMP0 SET ENDDATE =@TRANSENDDATE
	UPDATE #TEMP0 SET NARRATION='TOTAL GROSS BILLING' WHERE TRANSTYPE='SCI'
	UPDATE #TEMP0 SET NARRATION=UPPER(NARRATION)  ,BANKNAME=UPPER(BANKNAME) 
    UPDATE #TEMP0 SET CONTRACTNAME = C.CONTRNAME  FROM CONTRACTS C INNER JOIN #TEMP0 ON #TEMP0.CONTRACTID = C.CONTRNUMBER 
	UPDATE #TEMP0 SET CREDNAME = S.SUBNAME FROM SUBCONTRACTORS S INNER JOIN #TEMP0 ON #TEMP0.CREDNUMBER = S.SUBNUMBER 
	UPDATE #TEMP0 SET BORGNAME = B.BORGNAME FROM BORGS B INNER JOIN #TEMP0 ON #TEMP0.BORGID = B.BORGID 

	ALTER TABLE #TEMP0 ADD INDEXCODE INT
	UPDATE #TEMP0 SET INDEXCODE=1 WHERE TRANSTYPE   IN  ('CBC','CBD','PCP','PCR','SCP','CRA')
	UPDATE #TEMP0 SET INDEXCODE=0 WHERE TRANSTYPE   IN ('JNL','SCI')
	SELECT SUM(NETPAYABLE-PAIDAMOUNT) FROM #TEMP0 
	SELECT * FROM #TEMP0   ORDER BY INDEXCODE,TRANSDATE,TRANSTYPE
	CLOSE SUBBIES
	DEALLOCATE SUBBIES 

    
	DECLARE @Random INT;
	DECLARE @Upper INT;
	DECLARE @Lower INT
 
	SET @Lower = 1 ---- The lowest random number
	SET @Upper = 999 ---- The highest random number
	SELECT @Random = ROUND(((@Upper - @Lower -1) * RAND() + @Lower), 0)

	SELECT @FILEID= CONVERT(INT,RAND( (DATEPART(mm, GETDATE()) * 100000 )
		+ (DATEPART(ss, GETDATE()) * 1000 )
		+ DATEPART(ms, GETDATE()) )*1000) + STR(@RANDOM) 

	SET @FILENAME = @FILENAME+LTRIM(RTRIM(CONVERT(VARCHAR(6),@FILEID)))

	SET @SQL = 'SELECT *  INTO '+@FILENAME+ ' FROM   #TEMP0  ORDER BY TRANSDATE,TRANSTYPE '
 
   EXEC(@SQL)

   RETURN @FILEID
 