/****** Object:  Procedure [BS].[spSUBBIESTATEMENT]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE [BS].[spSUBBIESTATEMENT] (@BORGID INT,@ZONEID INT,@FINYEAR INT,@CREDNO VARCHAR(10),@STARTDATESTRING VARCHAR(15),@ENDDATEDATESTRING VARCHAR(15) )
AS

DECLARE @STARTDATE     DATETIME
DECLARE @ENDDATE       DATETIME
SELECT  @STARTDATE = CONVERT(DATETIME, @STARTDATESTRING,103) -- dd/mm/yyyy 
SELECT  @ENDDATE   = CONVERT(DATETIME, @ENDDATEDATESTRING,103) -- dd/mm/yyyy 

DECLARE @FILENAME VARCHAR(100)
DECLARE @FILEID   VARCHAR(10)
DECLARE @SQL      VARCHAR(250)
SET @FILENAME = 'BSBS_TEMP.DBO.SUBBIESTATEMENT'

CREATE TABLE #TEMP0 
(
 INDEXCODE  INT,
 BORGID     INT,
 BORGNAME   VARCHAR(50),
 ZONEID     INT,
 ZONENAME   VARCHAR(25),
 FINYEAR    INT,
 STARTDATE  DATETIME,
 ENDDATE    DATETIME,
 CREDNO     VARCHAR(10),
 SUBBIE     VARCHAR(50),
 PERIOD     INT,
 PDATE      DATETIME,
 CERTNO     VARCHAR(10),
 ACTIVITY   INT,
 ACTNAME    VARCHAR(50),
 ADVANCE    MONEY,
 WORKDONE   MONEY,
 ST         MONEY,
 VAT        MONEY,
 RETENTION  MONEY,
 WHT        MONEY,
 CONTRA     MONEY,
 ADMINFEE   MONEY,
 NETPAYABLE MONEY,
 BANKNAME   VARCHAR(75),
 CHEQUENO   VARCHAR(10),
 PAIDAMOUNT MONEY,
 REMARKS    VARCHAR(250),
 TRANGRP    INT
)

CREATE TABLE #BORGS(BORGID INT)

IF @ZONEID= 1 
    INSERT INTO #BORGS SELECT BORGID FROM BORGS WHERE PARENTBORG = @ZONEID 
ELSE
    INSERT INTO #BORGS VALUES (@BORGID) 

CREATE TABLE #SUBBIE(CREDNO VARCHAR(10)) 
IF @CREDNO='0'
    INSERT INTO #SUBBIE SELECT DISTINCT  CREDNO FROM TRANSACTIONS WHERE YEAR=@FINYEAR AND LEDGERCODE='1320000'
ELSE
    INSERT INTO #SUBBIE VALUES (@CREDNO)

DECLARE @WIP VARCHAR(10)
DECLARE @SUBCONTRACTOR VARCHAR(10)
SELECT @WIP = CONTROLFROMGL FROM CONTROLCODES WHERE CONTROLNAME='Work In Progress'
SELECT @SUBCONTRACTOR = CONTROLFROMGL FROM CONTROLCODES WHERE CONTROLNAME='Sub Contractors'                    

-- OPENING BALANCE
 

-- BILLS 

 SELECT TRANGRP,PERIOD,PDATE,LEDGERCODE,DEBIT ,CREDIT,CREDNO,SUBCONTRAN,ALLOCATION,ORGID,ACTIVITY 
 INTO #TEMPTRAN
 FROM TRANSACTIONS
 WHERE
   YEAR=@FINYEAR AND 
   PDATE BETWEEN @STARTDATE AND @ENDDATE AND 
   ORGID IN (SELECT BORGID FROM #BORGS)  AND 
   LEFT(BATCHREF,3)='SCI' AND
   LEDGERCODE <> @WIP AND
   CREDNO IN (SELECT CREDNO FROM #SUBBIE) 

 
 UPDATE #TEMPTRAN SET SUBCONTRAN = 'Advance' WHERE LEDGERCODE= '1320003'
 UPDATE #TEMPTRAN SET SUBCONTRAN = 'Work Done' WHERE DEBIT>0 AND ALLOCATION='Contracts' 
 UPDATE #TEMPTRAN SET SUBCONTRAN = 'ST' WHERE LEDGERCODE= '1310002'
 UPDATE #TEMPTRAN SET SUBCONTRAN = 'VAT' WHERE LEDGERCODE= '1310000'
 UPDATE #TEMPTRAN SET SUBCONTRAN = 'AdminFee' WHERE LEDGERCODE='5120241'
 UPDATE #TEMPTRAN SET SUBCONTRAN = 'Retention' WHERE LEDGERCODE='1320001'
 UPDATE #TEMPTRAN SET SUBCONTRAN = 'Contra' WHERE CREDIT>0 AND ALLOCATION='Contracts' AND LEDGERCODE<>'5120241'
 UPDATE #TEMPTRAN SET SUBCONTRAN = 'Withholding Tax'  WHERE LEDGERCODE = '1310005'
 UPDATE #TEMPTRAN SET SUBCONTRAN = 'Certified Amount' WHERE LEDGERCODE=@SUBCONTRACTOR
 UPDATE #TEMPTRAN SET SUBCONTRAN = 'Reverse Charge' WHERE LEDGERCODE='1310008'
  

 SELECT TRANGRP,SUBCONTRAN,SUM(DEBIT-CREDIT) AMOUNT  
 INTO #TEMP9
 FROM #TEMPTRAN 
 GROUP BY TRANGRP,SUBCONTRAN 

 INSERT INTO #TEMP0(INDEXCODE,TRANGRP) 
 SELECT DISTINCT 1,TRANGRP FROM #TEMPTRAN  

 UPDATE #TEMP0 SET ADVANCE=0, WORKDONE=0,ST=0,VAT=0,CONTRA=0,RETENTION=0,ADMINFEE=0,NETPAYABLE=0,WHT=0

 UPDATE #TEMP0 SET ADVANCE =AMOUNT  FROM #TEMP9 T
  INNER JOIN #TEMP0   ON #TEMP0.TRANGRP=T.TRANGRP    WHERE  T.SUBCONTRAN ='Advance'
 UPDATE #TEMP0 SET WORKDONE =AMOUNT  FROM #TEMP9 T
  INNER JOIN #TEMP0   ON #TEMP0.TRANGRP=T.TRANGRP    WHERE  T.SUBCONTRAN ='Work Done'
 UPDATE #TEMP0 SET ST = AMOUNT       FROM #TEMP9 T
  INNER JOIN #TEMP0   ON #TEMP0.TRANGRP = T.TRANGRP  WHERE  T.SUBCONTRAN= 'ST'
 UPDATE #TEMP0 SET VAT=  AMOUNT       FROM #TEMP9  T
  INNER JOIN #TEMP0  ON #TEMP0.TRANGRP = T.TRANGRP  WHERE  T.SUBCONTRAN= 'VAT'
 UPDATE #TEMP0 SET CONTRA=  AMOUNT    FROM #TEMP9 T
  INNER JOIN #TEMP0  ON #TEMP0.TRANGRP = T.TRANGRP  WHERE  T.SUBCONTRAN='Contra'  
 UPDATE #TEMP0 SET RETENTION=  AMOUNT   FROM #TEMP9 T
  INNER JOIN #TEMP0   ON #TEMP0.TRANGRP = T.TRANGRP  WHERE  T.SUBCONTRAN= 'Retention'
 UPDATE #TEMP0 SET ADMINFEE= AMOUNT    FROM #TEMP9 T
  INNER JOIN #TEMP0   ON #TEMP0.TRANGRP = T.TRANGRP  WHERE  T.SUBCONTRAN= 'AdminFee'
 UPDATE #TEMP0 SET NETPAYABLE= -1.0* AMOUNT  FROM #TEMP9 T
  INNER JOIN #TEMP0   ON #TEMP0.TRANGRP = T.TRANGRP WHERE  T.SUBCONTRAN= 'Certified Amount'
 UPDATE #TEMP0 SET WHT=  AMOUNT         FROM #TEMP9 T
  INNER JOIN #TEMP0  ON #TEMP0.TRANGRP = T.TRANGRP  WHERE  T.SUBCONTRAN= 'Withholding Tax'


 UPDATE #TEMP0 SET BORGID=T.ORGID, ACTIVITY=T.ACTIVITY , 
   CREDNO=T.CREDNO,PERIOD=T.PERIOD, PDATE = T.PDATE 
   FROM #TEMPTRAN T   INNER JOIN #TEMP0 ON #TEMP0.TRANGRP = T.TRANGRP 
   






 -- PAYMENTS 

 SELECT TRANGRP,PERIOD,PDATE,LEDGERCODE,DEBIT ,CREDIT,CREDNO,SUBCONTRAN,ALLOCATION,ORGID  
 INTO #TEMPPAYMENTS
 FROM TRANSACTIONS
 WHERE
   YEAR=@FINYEAR AND 
   PDATE BETWEEN @STARTDATE AND @ENDDATE AND 
   ORGID IN (SELECT BORGID FROM #BORGS)  AND 
   LEFT(BATCHREF,3) IN ( 'SCP','JNL','CBC', 'CBD' )  AND
   LEDGERCODE <> @WIP AND
   CREDNO IN (SELECT CREDNO FROM #SUBBIE) AND
   LEDGERCODE = @SUBCONTRACTOR
 SELECT @SUBCONTRACTOR

 INSERT INTO #TEMP0(INDEXCODE,TRANGRP) 
 SELECT DISTINCT 2,TRANGRP FROM #TEMPPAYMENTS  

 UPDATE #TEMP0 SET BORGID=T.ORGID,  CREDNO=T.CREDNO,PERIOD=T.PERIOD, PDATE = T.PDATE 
   FROM #TEMPPAYMENTS T   INNER JOIN #TEMP0 ON #TEMP0.TRANGRP = T.TRANGRP WHERE  #TEMP0.INDEXCODE= 2 
 
 CREATE TABLE #BANKS(BANKLEDGER VARCHAR(10))
 DECLARE @BANKFROM VARCHAR(10)
 DECLARE @BANKTO   VARCHAR(10)
 SELECT @BANKFROM = CONTROLFROMGL, @BANKTO   = CONTROLTOGL FROM CONTROLCODES WHERE CONTROLNAME='Bank'

 INSERT INTO #BANKS 
  SELECT LEDGERCODE FROM LEDGERCODES WHERE LEDGERCODE BETWEEN @BANKFROM AND @BANKTO 

 SELECT T.TRANGRP,T.LEDGERCODE,T.TRANSREF,L.LEDGERNAME ,(T.CREDIT-T.DEBIT) CHEQUEAMOUNT 
 INTO #CHEQUPAYMENTS 
 FROM  TRANSACTIONS T INNER JOIN #TEMPPAYMENTS ON #TEMPPAYMENTS.TRANGRP = T.TRANGRP 
                INNER JOIN LEDGERCODES  L ON T.LEDGERCODE = L.LEDGERCODE 
				WHERE  T.LEDGERCODE IN (SELECT BANKLEDGER  FROM #BANKS) 

 UPDATE #TEMP0 SET BANKNAME = C.LEDGERNAME, CHEQUENO = C.TRANSREF , PAIDAMOUNT = C.CHEQUEAMOUNT  FROM #CHEQUPAYMENTS C
  INNER JOIN #TEMP0 ON #TEMP0.TRANGRP  = C.TRANGRP   WHERE #TEMP0.INDEXCODE = 2 


 UPDATE #TEMP0 SET ZONEID=@ZONEID , FINYEAR=@FINYEAR, STARTDATE = @STARTDATE, ENDDATE = @ENDDATE
 UPDATE #TEMP0 SET BORGNAME = B.BORGNAME FROM BORGS B INNER JOIN #TEMP0 ON #TEMP0.BORGID = B.BORGID 
 UPDATE #TEMP0 SET ZONENAME = B.BORGNAME FROM BORGS B INNER JOIN #TEMP0 ON #TEMP0.BORGID = @ZONEID 
 UPDATE #TEMP0 SET SUBBIE   = S.SUBNAME  FROM SUBCONTRACTORS S INNER JOIN #TEMP0 ON #TEMP0.CREDNO = S.SUBNUMBER 
 UPDATE #TEMP0 SET ACTNAME  = A.ACTNAME  FROM ACTIVITIES A INNER JOIN #TEMP0 ON #TEMP0.ACTIVITY = A.ACTNUMBER  

DECLARE @Random INT;
DECLARE @Upper INT;
DECLARE @Lower INT
 
SET @Lower = 1 ---- The lowest random number
SET @Upper = 999 ---- The highest random number
SELECT @Random = ROUND(((@Upper - @Lower -1) * RAND() + @Lower), 0)

SELECT @FILEID= CONVERT(INT,RAND( (DATEPART(mm, GETDATE()) * 100000 )
		+ (DATEPART(ss, GETDATE()) * 1000 )
		+ DATEPART(ms, GETDATE()) )*1000) + STR(@RANDOM) 

SET @FILENAME = @FILENAME+LTRIM(RTRIM(CONVERT(VARCHAR(6),@FILEID)))
SET @SQL = 'SELECT *  INTO '+@FILENAME+ ' FROM   #TEMP0  ORDER BY PERIOD,PDATE  '
EXEC(@SQL)

ALTER TABLE #TEMP0 ADD CHECKPAID MONEY
UPDATE #TEMP0 SET CHECKPAID =ADVANCE+WORKDONE+ST+VAT+RETENTION+CONTRA+ADMINFEE+WHT 

SELECT * FROM #TEMP0 

RETURN @FILEID