/****** Object:  Procedure [BS].[spTransactionCounts]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE [BS].[spTransactionCounts](@FINYEAR INT)
as
CREATE TABLE #TEMP0 ( ORGID INT, ORGNAME VARCHAR(100),FINYEAR INT,PERIOD INT,TRANSTYPE VARCHAR(5), USERID CHAR(10),USERNAME VARCHAR(100),TRANSCOUNT INT) 
INSERT INTO #TEMP0 
SELECT T.ORGID,B.BORGNAME,T.YEAR,T.PERIOD,LEFT(T.TRANSTYPE,3) TRANSTYPE,T.USERID,SPACE(100),COUNT(TRANGRP) COUNTS 
FROM TRANSACTIONS T 
INNER JOIN BORGS B ON T.ORGID=B.BORGID
WHERE T.YEAR=@FINYEAR AND T.PERIOD<>0
GROUP BY T.ORGID,T.YEAR,T.PERIOD,B.BORGNAME,LEFT(T.TRANSTYPE,3),T.USERID 
ORDER BY ORGID,PERIOD,TRANSTYPE


UPDATE #TEMP0 SET USERNAME='NA'

 
UPDATE #TEMP0 SET USERNAME = USERS.USERNAME FROM USERS INNER JOIN #TEMP0 ON #TEMP0.USERID =USERS.USERID WHERE ISNUMERIC(#TEMP0.USERID)=1
 
UPDATE #TEMP0 SET USERNAME = USERS.USERNAME FROM USERS INNER JOIN #TEMP0 ON #TEMP0.USERID =USERS.LOGINID  WHERE ISNUMERIC(#TEMP0.USERID)=0

SELECT * FROM #TEMP0  ORDER BY ORGID,FINYEAR,PERIOD,TRANSTYPE
 
 