/****** Object:  Procedure [BS].[spUpdateGSTIN]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE [BS].[spUpdateGSTIN]
as
UPDATE SUPPLIERS SET BUSREG=SC.ISOCERTIFICATION FROM SUBCONTRACTORS SC INNER JOIN SUPPLIERS ON SUPPLIERS.SUPPCODE=SC.SUBNUMBER WHERE SC.ISOCERTIFICATION<>''