/****** Object:  Procedure [BS].[spUpdateTransRefExtPostYearEnd]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE BS.spUpdateTransRefExtPostYearEnd(@NEWFINYEAR INT)
AS
SELECT TRANSID, ORIGTRANSID INTO #TEMP0 FROM TRANSACTIONS WHERE YEAR=@NEWFINYEAR AND PERIOD=0 
ALTER TABLE #TEMP0 ADD TRANSREFEXT VARCHAR(50) 
UPDATE #TEMP0 SET TRANSREFEXT = T.TRANSREFEXT FROM TRANSACTIONS T INNER JOIN #TEMP0 ON #TEMP0.ORIGTRANSID = T.TRANSID 

DELETE FROM #TEMP0 WHERE TRANSREFEXT IS NULL
UPDATE TRANSACTIONS SET TRANSREFEXT = T.TRANSREFEXT FROM #TEMP0 T INNER JOIN TRANSACTIONS  ON TRANSACTIONS.TRANSID = T.TRANSID 