/****** Object:  Procedure [BS].[spUpdateReconArchieve]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE  PROCEDURE BS.spUpdateReconArchieve
as
SELECT 
  D.RECONID,
  T.TRANGRP
INTO #TEMP
FROM 
  DEBTRECONS_ARCHIEVE D ,
  TRANSACTIONS T,
  DEBTORS DB
WHERE 
  D.TRANGRP = 0
  AND D.ORGID = T.ORGID 
  AND D.SubConNumber = DB.DEBTID   
  AND T.CREDNO = DB.DebtNumber   
  AND T.PDATE = D.POSTDATE  
  AND LEFT(BATCHREF,3) = 'DTI' 
  AND T.LEDGERCODE= D.LEDGER 
 
 UPDATE DEBTRECONS_ARCHIEVE SET TRANGRP = T.TRANGRP FROM #TEMP T
 INNER JOIN DEBTRECONS_ARCHIEVE D ON D.RECONID = T.RECONID  
 WHERE D.TRANGRP= 0 
   