/****** Object:  Procedure [BS].[spUpdateSubcReconArchieve]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE BS.spUpdateSubcReconArchieve
AS

SELECT 
 S.RECONID,
 T.TRANGRP 
INTO 
 #TEMP
FROM 
 SUBCRECONS_ARCHIEVE S ,
 TRANSACTIONS T,
 SUBCONTRACTORS SUBBIE
WHERE
  S.ORGID = T.ORGID 
  AND S.SubConNumber = SUBBIE.SUBID   
  AND T.CREDNO = SUBBIE.SubNumber   
  AND T.TRANSREF  = S.CERTNOA  
  AND T.PDATE = S.POSTDATE  
  AND LEFT(BATCHREF,3) = 'SCI' 
  AND S.TRANGRP = 0 
  AND T.LEDGERCODE='1320000' 
  AND T.SUBCONTRAN = 'Certified Amount' 

UPDATE SUBCRECONS_ARCHIEVE 
SET TRANGRP= T.TRANGRP
FROM #TEMP T 
INNER JOIN SUBCRECONS_ARCHIEVE S
ON S.RECONID = T.RECONID 
WHERE S.TRANGRP = 0 
 