/****** Object:  Procedure [BS].[spUpdateDebtorRecons]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE [BS].[spUpdateDebtorRecons]
as

DECLARE @ORGID INT
DECLARE @SUBCONNUMBER INT
DECLARE @CONTRACT INT
DECLARE @ACTIVITY INT
DECLARE @VALNO VARCHAR(10)
DECLARE @CERTNO VARCHAR(10)
DECLARE @POSTREF VARCHAR(15)
DECLARE @DRPOSTDATE DATE
DECLARE @LEDGER VARCHAR(10)
DECLARE @RECONID INT
DECLARE @DEBTNAME VARCHAR(50)

DECLARE @CONTRACTCODE VARCHAR(10)
DECLARE @ACTIVITYCODE VARCHAR(10)
DECLARE @CREDNO VARCHAR(10)
DECLARE @TRANSID INT
DECLARE @COUNT INT
DECLARE @ORDERNO VARCHAR(10)
DECLARE @STARTLEDGER VARCHAR(10)
DECLARE @ENDLEDGER   VARCHAR(10)

DECLARE @REMARKS VARCHAR(250)

SELECT @STARTLEDGER = CONTROLFROMGL FROM CONTROLCODES WHERE CONTROLNAME='Contract Revenue'
SELECT @ENDLEDGER   = CONTROLTOGL   FROM CONTROLCODES WHERE CONTROLNAME='Contract Revenue'
 
CREATE TABLE #TRANSID (TRANGRP INT,TRANSID INT,RECONID INT,REMARKS VARCHAR(250))


DECLARE RECONS CURSOR FOR
SELECT RECONID,ORGID,SUBCONNUMBER,CONTRACT,ACTIVITY,VALNO,CERTNO,POSTREF,POSTDATE,LEDGER,SUPNAME,ORDERNO
 FROM DEBTRECONS WHERE POSTED=1 AND BOQPOSTDETAIL=0  ORDER BY RECONID 

OPEN RECONS

FETCH NEXT FROM RECONS INTO @RECONID,@ORGID,@SUBCONNUMBER,@CONTRACT,@ACTIVITY,@VALNO,@CERTNO,@POSTREF,@DRPOSTDATE,@LEDGER,@DEBTNAME,@ORDERNO

WHILE @@FETCH_STATUS = 0 
BEGIN

DELETE FROM #TRANSID 

SELECT @CONTRACTCODE=CONTRNUMBER FROM CONTRACTS WHERE CONTRID = @CONTRACT 
SELECT @ACTIVITYCODE = ACTNUMBER FROM ACTIVITIES  WHERE ACTID = @ACTIVITY 
SELECT @CREDNO = DEBTNUMBER FROM DEBTORS WHERE  DEBTID= @SUBCONNUMBER 
SELECT @REMARKS = REMARK FROM DEBTRECONS WHERE RECONID=@RECONID 
 
SELECT @COUNT = COUNT(*) 
FROM TRANSACTIONS WHERE 
ORGID = @ORGID AND
PDATE = @DRPOSTDATE AND
CONTRACT = @CONTRACTCODE AND
ACTIVITY = @ACTIVITYCODE AND
TRANSREF = @CERTNO AND
CREDNO = @CREDNO AND
ORDERNO = @ORDERNO AND 
LEFT(BATCHREF,3) = 'DTI'  

 

IF @COUNT >0 
 BEGIN
   INSERT INTO #TRANSID 
   SELECT TRANGRP,TRANSID,@RECONID,@REMARKS  
		FROM TRANSACTIONS WHERE 
		ORGID = @ORGID AND
		PDATE = @DRPOSTDATE AND
		CONTRACT = @CONTRACTCODE AND
		ACTIVITY = @ACTIVITYCODE AND
		TRANSREF = @CERTNO AND
		CREDNO = @CREDNO AND
		ORDERNO = @ORDERNO AND 
		LEFT(BATCHREF,3) = 'DTI'  
 END
ELSE
 BEGIN
  INSERT INTO #TRANSID 
  SELECT TRANGRP,TRANSID,@RECONID,@REMARKS 
    FROM TRANSACTIONS WHERE 
    ORGID = @ORGID AND
    PDATE = @DRPOSTDATE AND 
    CONTRACT = @CONTRACTCODE AND
    ACTIVITY = @ACTIVITYCODE AND
    CREDNO = @CREDNO AND
    LEDGERCODE BETWEEN @STARTLEDGER AND @ENDLEDGER AND
    LEFT(BATCHREF,3) = 'DTI' AND  
    DESCRIPTION = 'Total Gross Billing'
 END
 



 


INSERT INTO VRREMARKS 
SELECT * FROM  #TRANSID T



FETCH NEXT FROM RECONS INTO @RECONID,@ORGID,@SUBCONNUMBER,@CONTRACT,@ACTIVITY,@VALNO,@CERTNO,@POSTREF,@DRPOSTDATE,@LEDGER,@DEBTNAME,@ORDERNO

END
CLOSE RECONS
DEALLOCATE RECONS