/****** Object:  Procedure [BS].[STOCKUPDATE]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE procedure [BS].[STOCKUPDATE]
AS

 


CREATE TABLE #TEMPS(
   	[ORGID] [int] NULL,
	[STORE] [varchar](55) NULL,
	[STOCKCODE] [varchar](25) NULL,
	[TRANSACTIONDATE] [datetime] NULL,
	[INQTY] [decimal](18, 4) NULL,
	[OUTQTY] [decimal](18, 4) NULL,
	[RATE] [decimal](18, 2) NULL,
	[GRNNO] [varchar](50) NULL,
	[TRANSTYPE] [varchar](20) NULL,
	[UNIT] [varchar](25) NULL,
	[DLVRID] [BIGINT] NULL,
	[TRANSID] [int] NULL,
	[REFNO] [varchar](50) NULL,
	[REQNO] [varchar](175) NULL,
	[SUBBIENAME] [varchar](60) NULL
)  

INSERT INTO #TEMPS (ORGID,    STORE,       STOCKCODE,  TRANSACTIONDATE,INQTY,    RATE,   UNIT,       GRNNO,  DLVRID,  TRANSTYPE)
SELECT              D.TBORGID,INV.STKSTORE,INV.STKCODE,D.DLVRDATE,     D.DLVRQTY,D.PRICE,INV.STKUNIT,D.GRNNO,D.DLVRID,'DEL' 
FROM DELIVERIES D  INNER JOIN ORDITEMS OI ON D.ORDID=OI.ORDID AND D.ORDITEMLINENO = OI.LINENUMBER 
                   INNER JOIN INVENTORY INV ON OI.STOCKID = INV.STKID 
				   WHERE D.STORECODE <> 1  AND LEFT(INV.STKSTORE,2)='MS'

 

SELECT TRANSID,ORGID,PDATE,STORE,STOCKNO,QUANTITY,UNIT,RATE, TRANSTYPE ,TRANSREF,REQNO 
INTO #TRANS
FROM  TRANSACTIONS WHERE LEDGERCODE IN (SELECT  STKCTL FROM INVSTORES WHERE LEFT(STORECODE,2)='MS' )
	   AND TRANSTYPE NOT IN ('DEL','JNL','OPB') AND LEFT(STORE,2)='MS' AND FBID=-1

ALTER TABLE #TRANS ADD STOCKIN  DECIMAL(18,4)
ALTER TABLE #TRANS ADD STOCKOUT DECIMAL(18,4) 
UPDATE #TRANS SET STOCKIN=0,STOCKOUT = 0

UPDATE #TRANS SET STOCKIN   = QUANTITY       WHERE TRANSTYPE = 'STW' 
UPDATE #TRANS SET STOCKOUT  = ABS(QUANTITY)  WHERE TRANSTYPE = 'STB'
UPDATE #TRANS SET STOCKOUT  = ABS(QUANTITY)  WHERE Quantity < 0  AND TRANSTYPE NOT IN ('STB','STW')
UPDATE #TRANS SET STOCKIN   = ABS(QUANTITY)  WHERE QUANTITY > 0  AND TRANSTYPE NOT IN ('STB','STW')




INSERT INTO #TEMPS(ORGID,STORE,STOCKCODE,TRANSACTIONDATE,INQTY,  OUTQTY  ,RATE,TRANSTYPE,UNIT,TRANSID,REFNO,   REQNO) 
SELECT             ORGID,STORE,STOCKNO,  PDATE  ,        STOCKIN,STOCKOUT,RATE,TRANSTYPE,UNIT,TRANSID,TRANSREF,REQNO FROM #TRANS 


 

UPDATE #TEMPS SET INQTY = 0 WHERE INQTY IS NULL
UPDATE #TEMPS SET OUTQTY = 0 WHERE OUTQTY IS NULL 
UPDATE #TEMPS SET TRANSTYPE=SPACE(10) WHERE TRANSTYPE IS NULL 
UPDATE #TEMPS SET GRNNO =SPACE(10) WHERE GRNNO IS NULL 
UPDATE #TEMPS SET DLVRID = 0 WHERE DLVRID IS NULL
UPDATE #TEMPS SET TRANSID = 0 WHERE TRANSID IS NULL
UPDATE #TEMPS SET REFNO = SPACE(10) WHERE REFNO IS NULL
UPDATE #TEMPS SET REQNO = SPACE(75) WHERE REQNO IS NULL
UPDATE #TEMPS SET SUBBIENAME = S.SUBNAME FROM SUBCONTRACTORS S INNER JOIN #TEMPS ON #TEMPS.REQNO=S.SUBNUMBER 



BEGIN TRAN T1
 INSERT INTO BS.STOCKREPORT 
 SELECT * FROM #TEMPS
 UPDATE DELIVERIES   SET STORECODE  = 1 WHERE  DLVRID IN (SELECT DLVRID FROM #TEMPS) 
 UPDATE TRANSACTIONS SET FBID  = 1 WHERE  TRANSID IN (SELECT TRANSID FROM #TRANS) 
COMMIT TRAN T1 

 