/****** Object:  Procedure [BS].[UpdateMissingContraInvoiceInGST]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE  BS.UpdateMissingContraInvoiceInGST
as

SELECT C.SALESINDEX, C.ORGID GSTORGID, C.ORDERNO GSTORDERNO,C.INVOICEDATE,C.SUPPCODE,C.SUPPLIERNAME ,C.INVOICENUMBER 
INTO #TEMP0 
FROM BI.SALESHISTORY C 
WHERE INVOICENUMBER='' AND FINYEAR=2019 AND PERIOD=5
 
SELECT * FROM #TEMP0 

SELECT ORGID,RECONID,SUPNAME,ORDERNO  INTO #TEMP1   FROM SUBCRECONS WHERE ORDERNO IN (SELECT GSTORDERNO FROM #TEMP0) 

SELECT * FROM #TEMP1 

SELECT *
INTO #TEMP2 
FROM #TEMP0 LEFT OUTER  JOIN #TEMP1 ON #TEMP0.GSTORDERNO = #TEMP1.ORDERNO 

SELECT CONTRARECONID, ContraVATAmnt ,REMARKS 
INTO #TEMP3
FROM CONTRAS WHERE CONTRARECONID IN (SELECT RECONID FROM #TEMP2)  

SELECT * 
INTO #TEMP4
FROM #TEMP2 LEFT OUTER JOIN #TEMP3 ON #TEMP2.RECONID = #TEMP3.CONTRARECONID 

DELETE FROM #TEMP4 WHERE ContraVATAmnt IS NULL

SELECT * FROM #TEMP4 

UPDATE BI.SALESHISTORY
 SET INVOICENUMBER=T.REMARKS FROM #TEMP4 T INNER JOIN BI.SALESHISTORY BIS ON BIS.SALESINDEX = T.SALESINDEX 