/****** Object:  Procedure [BS].[updateWHTJournals]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE BS.updateWHTJournals(@TRANSREF VARCHAR(10)) 
AS 
UPDATE JOURNALS SET WHTID = 2 WHERE JNLLEDGERCODE='1310005'  AND WHTID=-1 AND JNLHEADID =  
 (SELECT JNLHEADID  FROM JOURNALHEADER  WHERE JNLHEADTRANSREF=@TRANSREF AND JNLHEADPOSTED=0)