/****** Object:  Procedure [BS].[UpKeepStores]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE  PROCEDURE [BS].[UpKeepStores]
as


SELECT IV.STORECODE,PJ.BORGID INTO #TEMP1  FROM 
INVSTORES IV INNER JOIN CONTRACTS CO ON IV.STORECONTNUMBER = CO.CONTRNUMBER  INNER JOIN PROJECTS PJ 
ON  PJ.PROJID= CO.PROJID WHERE LEFT(IV.STORECODE,2)= 'MS' 

DELETE FROM #TEMP1 WHERE STORECODE='VMAINSTORE'  
 
DECLARE STORES CURSOR FOR 
SELECT STORECODE,BORGID FROM #TEMP1

DECLARE @STORECODE VARCHAR(10)
DECLARE @BORGID INT

OPEN STORES 
FETCH NEXT FROM STORES INTO @STORECODE,@BORGID 
WHILE @@FETCH_STATUS = 0 
BEGIN 
  DELETE FROM INVENTORY 
    WHERE 
	  STKSTORE= @STORECODE  AND
	  BORGID <> @BORGID   AND 
	  STKQUANTITY=0
	  
 
  FETCH NEXT FROM STORES INTO @STORECODE,@BORGID 


END
CLOSE STORES
DEALLOCATE  STORES   
 
DELETE  FROM INVENTORY WHERE LEFT(STKSTORE,2)='SE' AND BORGID<>2 AND STKQUANTITY=0
DELETE  FROM INVENTORY WHERE LEFT(STKSTORE,2)='FW' AND BORGID<>2 AND STKQUANTITY=0

DELETE  FROM INVENTORY WHERE STKSTORE='VMAINSTORE' AND BORGID<>2
DELETE  FROM INVENTORY WHERE STKSTORE='VMAINCSL' AND BORGID<>86