/****** Object:  Procedure [BS].[VR9]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE BS.VR9
AS
 SELECT ID,ASSETID,ASSETNUMBER,DEBIT INTO #NEG FROM BI.ASSETPOSTS WHERE YEAR=2019 AND PERIOD=0 AND DEBIT<0
 SELECT ID,ASSETID,ASSETNUMBER,DEBIT FROM BI.ASSETPOSTS WHERE YEAR=2019 AND PERIOD=1 AND ASSETID IN (SELECT ASSETID FROM #NEG) 