/****** Object:  Procedure [BS].[VRA9]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE BS.VRA9
AS
 SELECT ID,ASSETID,ASSETNUMBER,DEBIT INTO #NEG  FROM BI.ASSETPOSTS WHERE YEAR=2019 AND PERIOD=0 AND DEBIT<0
 SELECT ID,ASSETID,ASSETNUMBER,DEBIT INTO #NEG1 FROM BI.ASSETPOSTS WHERE YEAR=2019 AND PERIOD=1 AND ASSETID IN (SELECT ASSETID FROM #NEG) 
 SELECT ID,ASSETID,ASSETNUMBER,DEBIT INTO #NEG2 FROM BI.ASSETPOSTS WHERE YEAR=2019 AND PERIOD=0 AND ASSETID IN (SELECT ASSETID FROM #NEG)
 SELECT * FROM #NEG1


 --SELECT * FROM #NEG1 ORDER BY ASSETID
 --SELECT * FROM #NEG2 ORDER BY ASSETID

 ----SELECT * INTO VRASSETNEG1 FROM #NEG1 

 --DELETE FROM BI.ASSETPOSTS WHERE ID IN (SELECT ID FROM #NEG1) 
 --UPDATE ASSETS SET ASSETDEPPROG=ASSETDEPPROG-1 WHERE ASSETNUMBER  IN (SELECT ASSETNUMBER FROM  #NEG1) 
 --UPDATE ASSETS SET AssetAccumDep = DEBIT FROM #NEG2 INNER JOIN ASSETS ON ASSETS.ASSETNUMBER=#NEG2.ASSETNUMBER
 --UPDATE ASSETS SET ASSETBOOKVALUE = ASSETPPRICE-ASSETACCUMDEP 

 



 SELECT ASSETID,ASSETNUMBER,ASSETPPRICE,ASSETBOOKVALUE,ASSETSALVAGE,LASTDEPTM ,ASSETPDATE,DATEDIFF(MONTH,ASSETPDATE,GETDATE()) MONTHS,ASSETACCUMDEP
 INTO #NEGITEMS
 FROM ASSETS WHERE ASSETNUMBER IN (SELECT ASSETNUMBER FROM #NEG) 

 ALTER TABLE #NEGITEMS ADD NEWBOOKVALUE DECIMAL(18,2) 
 UPDATE #NEGITEMS SET NEWBOOKVALUE  = ASSETPPRICE-ASSETACCUMDEP 

 SELECT * FROM #NEGITEMS ORDER BY ASSETBOOKVALUE 
 
 ----SELECT * FROM #NEG1