/****** Object:  Procedure [BS].[VRMONI]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE BS.VRMONI
AS

SELECT * INTO #TEMP1 FROM VRMONI
ALTER TABLE #TEMP1 ADD TBORGID INT
UPDATE #TEMP1 SET TBORGID = B.BORGID FROM BORGS B INNER JOIN #TEMP1 ON #TEMP1.PROJECTCODE=LEFT(B.BORGNAME,5)
SELECT * FROM #TEMP1 
ALTER TABLE #TEMP1 ADD ORDID INT 