/****** Object:  Procedure [BS].[VRPOSTDEPRECIATIONFIX]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE [BS].[VRPOSTDEPRECIATIONFIX] 
AS

--SELECT PLANTNO,COUNT(*) CNTS INTO VREXCESSPOSTING FROM ASSETPOSTS WHERE PERIOD=5 GROUP BY PLANTNO HAVING COUNT(*)>3
DECLARE @ASSETPOSTDATE DATETIME
DECLARE @ASSETDEPCODE VARCHAR(10)
DECLARE @ASSETOPPCODE VARCHAR(10)
DECLARE @LASTDEPTM DECIMAL(18,2)
DECLARE @ASSETNUMBER VARCHAR(15)
DECLARE @LASTDENUMBER INT
DECLARE @TRANGRP INT

DECLARE ASSETS CURSOR FOR
SELECT  PLANTNO   FROM VREXCESSPOSTING  

OPEN ASSETS 
FETCH NEXT FROM ASSETS INTO @ASSETNUMBER

WHILE @@FETCH_STATUS = 0
BEGIN
   
   
   SELECT @ASSETDEPCODE=ASSETDEPCODE,@ASSETOPPCODE=ASSETOPPCODE, @LASTDEPTM = LASTDEPTM, @LASTDENUMBER = ASSETDEPPROG  FROM ASSETS WHERE ASSETNUMBER= @ASSETNUMBER 
   SELECT  @TRANGRP =  MAX(TRANGRP) FROM ASSETPOSTS  WHERE PLANTNO=@ASSETNUMBER AND PERIOD=5 
   SET @LASTDENUMBER = @LASTDENUMBER -1  
   DELETE FROM ASSETPOSTS WHERE TRANGRP = @TRANGRP 

   UPDATE ASSETS SET AssetBookValue = AssetBookValue+@LASTDEPTM,
                     AssetAccumDep = AssetAccumDep-@LASTDEPTM, 
					 ASSETPOST=1, ASSETDEP=ASSETDEP- 1,
					 ASSETDEPPROG= @LASTDENUMBER  
					 WHERE ASSETNUMBER= @ASSETNUMBER
   FETCH NEXT FROM ASSETS INTO @ASSETNUMBER

END

CLOSE ASSETS
DEALLOCATE ASSETS 
SELECT GETDATE()