/****** Object:  Procedure [BS].[VRSPLITCHECKENTRIES]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE  PROCEDURE BS.VRSPLITCHECKENTRIES 
AS

DELETE FROM BS.VRSPLITCHECK

DECLARE @ID INT 
DECLARE @TRANSID INT
DECLARE @AMOUNT_HOLD DECIMAL(18,2) 
DECLARE @AMOUNT_KNOCK DECIMAL(18,2)


DECLARE @BORGID INT
DECLARE @BATCHREF VARCHAR(10)
DECLARE @TRANSREF VARCHAR(10)
DECLARE @TRANGRP  INT
DECLARE @CREDNO   VARCHAR(15) 
DECLARE @LEDGERCODE VARCHAR(10)
SET @LEDGERCODE = '1320000'

DECLARE @NEWHOLD DECIMAL(18,2)
DECLARE @NEWKNOCK DECIMAL(18,2)
DECLARE @NEWTRANSID INT 

DECLARE TRANSLISTS CURSOR FOR 
SELECT ID,TRANSID,AMOUNT_HOLD,AMOUNT_KNOCK FROM BS.SPLITSUBCONS

OPEN TRANSLISTS 
FETCH NEXT FROM TRANSLISTS INTO @ID,@TRANSID,@AMOUNT_HOLD,@AMOUNT_KNOCK
WHILE @@FETCH_STATUS = 0
BEGIN
  INSERT INTO BS.VRSPLITCHECK VALUES (@ID,@TRANSID,@AMOUNT_HOLD,@AMOUNT_KNOCK,0,0,0) 
  SELECT @BORGID= ORGID, @BATCHREF=BATCHREF, @TRANSREF=TRANSREF ,@CREDNO=CREDNO,@TRANGRP=TRANGRP,@NEWKNOCK =CREDIT  
  FROM TRANSACTIONS WHERE TRANSID=@TRANSID 
  
  SELECT @NEWTRANSID = TRANSID FROM TRANSACTIONS WHERE ORGID=@BORGID AND BATCHREF=@BATCHREF AND TRANSREF=@TRANSREF AND CREDNO=@CREDNO AND TRANGRP=@TRANGRP 
  AND LEDGERCODE=@LEDGERCODE 

  SELECT @NEWHOLD = CREDIT FROM TRANSACTIONS WHERE TRANSID = @NEWTRANSID 

  UPDATE BS.VRSPLITCHECK SET NEWTRANSID = @NEWTRANSID , NEWHOLD = @NEWHOLD , NEWKNOCK=@NEWKNOCK WHERE ID=@ID 

  FETCH NEXT FROM TRANSLISTS INTO @ID,@TRANSID,@AMOUNT_HOLD,@AMOUNT_KNOCK
END
CLOSE TRANSLISTS
DEALLOCATE TRANSLISTS