/****** Object:  Procedure [EC].[spDetailReport]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE [EC].[spDetailReport](@BORGID INT,@FINYEAR INT,@FROMPERIOD INT, @TOPERIOD INT,@LIFETODATE INT) 
AS

IF @LIFETODATE=1
 BEGIN
    SELECT @FINYEAR = CURRENTFINYEAR FROM EC.PROJECTS WHERE BSBORGID=@BORGID 
	SET @FROMPERIOD=0 
	SET @TOPERIOD=13
 END


EXEC [EC].[spUpdateTRANGRPSales]

EXEC [EC].[spUpdateTRANGRPSubbie]

DECLARE @WIPASSETS VARCHAR(15)
SET @WIPASSETS = '2990102'

DECLARE @OBFINYEAR INT
DECLARE @OBPERIOD INT 
DECLARE @OBCUTOFFDATE DATETIME 
DECLARE @CURRENTFINYEAR INT 
DECLARE @LASTTRANGRP INT 
DECLARE @BORGNAME VARCHAR(100)
DECLARE @FROMPERIODNAME VARCHAR(100)
DECLARE @TOPERIODNAME VARCHAR(100)
 
SELECT @FROMPERIODNAME = DESCR FROM PERIODSETUP WHERE PERIOD =@FROMPERIOD AND YEAR=2014 AND ORGID=1
SELECT @TOPERIODNAME = DESCR FROM PERIODSETUP WHERE PERIOD=@TOPERIOD AND YEAR=2014 AND ORGID=1

 

SELECT @OBFINYEAR=ISNULL(FINYEAR,2020),@OBPERIOD=ISNULL(PERIOD,5),@OBCUTOFFDATE=ISNULL(CUTOFFDATE,GETDATE()),
@CURRENTFINYEAR = CURRENTFINYEAR ,@LASTTRANGRP = LASTTRANGRP ,@BORGNAME=BSBORGNAME 
FROM EC.PROJECTS WHERE BSBORGID=@BORGID 

CREATE TABLE #OB(CATEGORY VARCHAR(35), ACTIVITYCODE VARCHAR(15), AMOUNT DECIMAL(18,2)) 

IF (@LIFETODATE=1) AND ( @FINYEAR =@OBFINYEAR )
      INSERT INTO #OB 
      SELECT [CATEGORY],ACTIVITYCODE,AMOUNT  
	  FROM EC.OPENINGBALANCE WHERE ORGID=@BORGID AND FINYEAR=@FINYEAR
ELSE  IF (@LIFETODATE=0) AND ( @FINYEAR =@OBFINYEAR )
      INSERT INTO #OB 
      SELECT [CATEGORY],ACTIVITYCODE,AMOUNT  
	  FROM EC.OPENINGBALANCE WHERE ORGID=@BORGID AND FINYEAR=@FINYEAR
ELSE
      INSERT INTO #OB 
	  SELECT [CATEGORY],ACTIVITYCODE,AMOUNT 
	  FROM EC.OPENINGBALANCE WHERE ORGID=@BORGID AND FINYEAR=@FINYEAR AND PERIOD =0 


ALTER TABLE #OB ADD ACTIVITYNAME  VARCHAR(200)
UPDATE #OB SET ACTIVITYNAME = ECM.ACTIVITYNAME FROM EC.ENGINEERINGCODEMASTER ECM INNER JOIN #OB ON #OB.ACTIVITYCODE = ECM.ACTNUMBER 

 

CREATE TABLE #TEMPECREPORT(ID INT PRIMARY KEY IDENTITY(1,1),LINENUMBER INT, ACTIVITYNAME VARCHAR(100),REVENUE DECIMAL(18,2),WIP DECIMAL(18,2),MATERIAL DECIMAL(18,2),LABOUR DECIMAL(18,2),INDIRECTS DECIMAL(18,2),TOTAL DECIMAL(18,2) ) 
INSERT INTO #TEMPECREPORT(ACTIVITYNAME) 
SELECT DISTINCT ACTIVITYNAME   FROM EC.ENGINEERINGCODEMASTER   

UPDATE #TEMPECREPORT SET  REVENUE=0,WIP=0,MATERIAL=0,LABOUR=0,INDIRECTS=0 


-- MATERIAL 

CREATE TABLE #STOCKTRANS(TRANGRP INT,TRANSID INT,YEAR INT,PERIOD INT,PDATE DATETIME,BATCHREF VARCHAR(15),TRANSREF VARCHAR(15),TRANSTYPE VARCHAR(10),
LEDGERCODE VARCHAR(15),CONTRACT VARCHAR(25),ACTIVITY VARCHAR(15), DESCRIPTION VARCHAR(200),STORE VARCHAR(15),STOCKNO VARCHAR(15),QUANTITY DECIMAL(18,2),
UNIT VARCHAR(15),RATE DECIMAL(18,2),DEBIT DECIMAL(18,2),CREDIT DECIMAL(18,2) )

INSERT INTO #STOCKTRANS 
SELECT TRANGRP,TRANSID,YEAR,PERIOD,PDATE,BATCHREF,TRANSREF,TRANSTYPE,LEDGERCODE,CONTRACT,ACTIVITY,DESCRIPTION,STORE,STOCKNO,QUANTITY,UNIT,RATE,DEBIT,CREDIT 
FROM TRANSACTIONS 
WHERE ORGID=@BORGID AND 
      YEAR=@FINYEAR AND 
      PERIOD BETWEEN @FROMPERIOD AND @TOPERIOD AND 
	  TRANGRP > @LASTTRANGRP AND 
	  TRANSTYPE IN (SELECT TYPENAME FROM STOCKTYPES) AND ALLOCATION='Contracts' 

SELECT ACTIVITY,(DEBIT-CREDIT) AMOUNT 
INTO #STOCKSUMMARY
FROM #STOCKTRANS 

ALTER TABLE #STOCKSUMMARY ADD ACTIVITYNAME VARCHAR(100)
UPDATE #STOCKSUMMARY 
SET ACTIVITYNAME = EC.ACTIVITYNAME 
FROM EC.ENGINEERINGCODEMASTER EC 
INNER JOIN #STOCKSUMMARY ON #STOCKSUMMARY.ACTIVITY = EC.ACTNUMBER 

UPDATE #TEMPECREPORT SET MATERIAL = 0 
 
UPDATE #TEMPECREPORT
SET MATERIAL = +1.0 * SS.AMOUNT 
FROM #STOCKSUMMARY  SS INNER JOIN #TEMPECREPORT ON #TEMPECREPORT.ACTIVITYNAME = SS.ACTIVITYNAME

 
-- SALES
SELECT DISTINCT TRANGRP 
INTO #TRANSSALES
FROM TRANSACTIONS WHERE 
LEFT(BATCHREF,3)='DTI' AND 
ORGID=@BORGID AND 
YEAR=@FINYEAR AND 
PERIOD BETWEEN @FROMPERIOD AND @TOPERIOD AND
TRANGRP >@LASTTRANGRP 


SELECT ACTIVITYCODE,AMOUNT 
INTO #ACTIVITYAMOUNT 
FROM EC.SALESDETAILS WHERE AMOUNT>0 AND TRANGRP IN (SELECT TRANGRP FROM #TRANSSALES) 

SELECT ACTIVITYCODE ACTIVITY ,SUM(AMOUNT) AMOUNT 
INTO #ACTIVTYAMOUNTSUMMARY
FROM #ACTIVITYAMOUNT 
GROUP BY ACTIVITYCODE

ALTER TABLE #ACTIVTYAMOUNTSUMMARY ADD ACTIVITYNAME VARCHAR(150) 
UPDATE #ACTIVTYAMOUNTSUMMARY 
SET ACTIVITYNAME = EC.ACTIVITYNAME 
FROM EC.ENGINEERINGCODEMASTER EC 
INNER JOIN #ACTIVTYAMOUNTSUMMARY ON #ACTIVTYAMOUNTSUMMARY.ACTIVITY = EC.ACTNUMBER 

UPDATE #TEMPECREPORT SET REVENUE = 0 

UPDATE #TEMPECREPORT
SET REVENUE =+1.0 *  SS.AMOUNT 
FROM #ACTIVTYAMOUNTSUMMARY  SS INNER JOIN #TEMPECREPORT ON #TEMPECREPORT.ACTIVITYNAME = SS.ACTIVITYNAME


-- WIP
SELECT DISTINCT TRANGRP INTO #WIPTRANGRPS 
FROM TRANSACTIONS WHERE 
ORGID=@BORGID AND 
YEAR=@FINYEAR AND 
PERIOD BETWEEN @FROMPERIOD AND @TOPERIOD AND
TRANGRP >@LASTTRANGRP AND 
LEDGERCODE = @WIPASSETS 

SELECT ACTIVITY,(DEBIT-CREDIT) AMOUNT 
INTO #WIPAMOUNT 
FROM TRANSACTIONS 
WHERE TRANGRP IN (SELECT TRANGRP FROM #WIPTRANGRPS) 

 

SELECT ACTIVITY,SUM(AMOUNT) AMOUNT 
INTO #WIPAMOUNTSUMMARY 
FROM #WIPAMOUNT 
GROUP BY ACTIVITY 

 

ALTER TABLE #WIPAMOUNTSUMMARY ADD ACTIVITYNAME VARCHAR(100) 
UPDATE #WIPAMOUNTSUMMARY 
SET ACTIVITYNAME = EC.ACTIVITYNAME 
FROM EC.ENGINEERINGCODEMASTER EC 
INNER JOIN #WIPAMOUNTSUMMARY ON #WIPAMOUNTSUMMARY.ACTIVITY = EC.ACTNUMBER 

UPDATE #TEMPECREPORT SET WIP = 0 

UPDATE #TEMPECREPORT
SET WIP =+1.0 *  SS.AMOUNT 
FROM #WIPAMOUNTSUMMARY  SS INNER JOIN #TEMPECREPORT ON #TEMPECREPORT.ACTIVITYNAME = SS.ACTIVITYNAME

-- LABOUR

SELECT DISTINCT TRANGRP INTO #TRANGRPSCI FROM TRANSACTIONS 
WHERE 
ORGID=@BORGID AND 
YEAR=@FINYEAR AND 
PERIOD BETWEEN @FROMPERIOD  AND  @TOPERIOD  AND 
LEFT(TRANSTYPE,3)='SCI' AND 
TRANGRP >@LASTTRANGRP 
 

DELETE FROM #TRANGRPSCI WHERE TRANGRP NOT IN (SELECT TRANGRP FROM EC.SUBBIEHEADER) 

ALTER TABLE  #TRANGRPSCI ADD HEADERID INT 
UPDATE #TRANGRPSCI SET HEADERID = SH.HEADERID FROM EC.SUBBIEHEADER SH  INNER JOIN #TRANGRPSCI ON #TRANGRPSCI.TRANGRP = SH.TRANGRP

 
SELECT ACTIVITYCODE,QTY,RATE,(QTY*RATE)AMOUNT 
INTO #SUBBIEAMOUNTS 
FROM EC.SUBBIEDETAILS WHERE HEADERID IN (SELECT HEADERID FROM #TRANGRPSCI) AND QTY>0 

SELECT ACTIVITYCODE ACTIVITY ,SUM(AMOUNT) AMOUNT 
INTO #SUBBIETOTALS
FROM #SUBBIEAMOUNTS
GROUP BY ACTIVITYCODE 

ALTER TABLE #SUBBIETOTALS ADD ACTIVITYNAME VARCHAR(200)
UPDATE #SUBBIETOTALS 
SET ACTIVITYNAME = EC.ACTIVITYNAME 
FROM EC.ENGINEERINGCODEMASTER EC 
INNER JOIN #SUBBIETOTALS ON #SUBBIETOTALS.ACTIVITY = EC.ACTNUMBER 

UPDATE #TEMPECREPORT SET LABOUR = 0 

UPDATE #TEMPECREPORT
SET LABOUR = +1.0 *  SS.AMOUNT 
FROM #SUBBIETOTALS  SS INNER JOIN #TEMPECREPORT ON #TEMPECREPORT.ACTIVITYNAME = SS.ACTIVITYNAME

-- INDIRECTS 

SELECT DISTINCT TRANGRP 
INTO #TRANGRPINDIRECTS
FROM TRANSACTIONS WHERE 
ORGID=@BORGID AND 
YEAR=@FINYEAR AND 
PERIOD BETWEEN @FROMPERIOD AND @TOPERIOD AND
TRANGRP > @LASTTRANGRP


DELETE FROM #TRANGRPINDIRECTS WHERE TRANGRP IN (SELECT  TRANGRP FROM #STOCKTRANS)
DELETE FROM #TRANGRPINDIRECTS WHERE TRANGRP IN (SELECT  TRANGRP FROM #TRANSSALES)
DELETE FROM #TRANGRPINDIRECTS WHERE TRANGRP IN (SELECT  TRANGRP FROM #WIPTRANGRPS)
DELETE FROM #TRANGRPINDIRECTS WHERE TRANGRP IN (SELECT  TRANGRP FROM #TRANGRPSCI)

SELECT ACTIVITY,(DEBIT-CREDIT) AMOUNT 
INTO #INDIRECTAMOUNT 
FROM TRANSACTIONS 
WHERE TRANGRP IN  (SELECT TRANGRP FROM #TRANGRPINDIRECTS)

SELECT ACTIVITY,SUM(AMOUNT) AMOUNT 
INTO #INDIRECTAMOUNTSUMMARY
FROM #INDIRECTAMOUNT
GROUP BY ACTIVITY 


ALTER TABLE #INDIRECTAMOUNTSUMMARY ADD ACTIVITYNAME VARCHAR(200)
UPDATE #INDIRECTAMOUNTSUMMARY 
SET ACTIVITYNAME = EC.ACTIVITYNAME 
FROM EC.ENGINEERINGCODEMASTER EC 
INNER JOIN #INDIRECTAMOUNTSUMMARY ON #INDIRECTAMOUNTSUMMARY.ACTIVITY = EC.ACTNUMBER 
 
UPDATE #TEMPECREPORT SET INDIRECTS  = 0 

UPDATE #TEMPECREPORT
SET INDIRECTS = +1.0 *  SS.AMOUNT 
FROM #INDIRECTAMOUNTSUMMARY  SS INNER JOIN #TEMPECREPORT ON #TEMPECREPORT.ACTIVITYNAME = SS.ACTIVITYNAME

 
    
-- OPENING BALANCE
UPDATE #TEMPECREPORT
SET REVENUE  = REVENUE +  OB.AMOUNT FROM #OB OB
INNER JOIN #TEMPECREPORT ON  OB.ACTIVITYNAME = #TEMPECREPORT.ACTIVITYNAME WHERE OB.CATEGORY = 'REVENUE' 

UPDATE #TEMPECREPORT
SET MATERIAL  = MATERIAL +  OB.AMOUNT FROM #OB OB
INNER JOIN #TEMPECREPORT ON  OB.ACTIVITYNAME = #TEMPECREPORT.ACTIVITYNAME WHERE OB.CATEGORY = 'MATERIAL'

UPDATE #TEMPECREPORT
SET LABOUR  = LABOUR +  OB.AMOUNT FROM #OB OB
INNER JOIN #TEMPECREPORT ON  OB.ACTIVITYNAME = #TEMPECREPORT.ACTIVITYNAME WHERE OB.CATEGORY = 'LABOUR'

UPDATE #TEMPECREPORT
SET INDIRECTS  = INDIRECTS +  OB.AMOUNT FROM #OB OB
INNER JOIN #TEMPECREPORT ON  OB.ACTIVITYNAME = #TEMPECREPORT.ACTIVITYNAME WHERE OB.CATEGORY = 'INDIRECT'


DECLARE @SUMSALES DECIMAL(18,2) 
DECLARE @SUMWIP DECIMAL(18,2)
DECLARE @SUMMATERIAL DECIMAL(18,2) 
DECLARE @SUMLABOUR DECIMAL(18,2) 
DECLARE @SUMINDIRECTS DECIMAL(18,2) 
DECLARE @SUMTOTAL DECIMAL(18,2) 

DECLARE @PANDLPERIOD VARCHAR(200)
IF @LIFETODATE = 1
   SET @PANDLPERIOD = 'Life To Date' 
ELSE
   SET @PANDLPERIOD = 'Financial Year: '+LTRIM(RTRIM(@FINYEAR))+'  Period From ' + LTRIM(RTRIM(@FROMPERIODNAME)) + ' To ' + LTRIM(RTRIM(@TOPERIODNAME)) 

UPDATE #TEMPECREPORT SET TOTAL = REVENUE+WIP+MATERIAL+LABOUR+INDIRECTS 

SELECT @SUMSALES = SUM(REVENUE),@SUMWIP = SUM(WIP), @SUMMATERIAL=SUM(MATERIAL) ,@SUMLABOUR=SUM(LABOUR),@SUMINDIRECTS=SUM(INDIRECTS),@SUMTOTAL = SUM(TOTAL)  FROM #TEMPECREPORT




SELECT ID,ACTIVITYNAME,REVENUE,WIP,MATERIAL,LABOUR,INDIRECTS,TOTAL,LINENUMBER,@BORGNAME PROJECTNAME,@PANDLPERIOD PERIODNAME
INTO #COSTINGREPORT
FROM #TEMPECREPORT
ORDER BY ID 


UPDATE #COSTINGREPORT SET LINENUMBER = 0
UPDATE #TEMPECREPORT  SET LINENUMBER = 0 


UPDATE #COSTINGREPORT SET LINENUMBER = ECM.LINENUMBER FROM EC.ENGINEERINGCODEMASTER  ECM 
INNER JOIN #COSTINGREPORT ON #COSTINGREPORT.ACTIVITYNAME=ECM.ACTIVITYNAME WHERE ECM.CATEGORY = 'REVENUE' 

UPDATE #COSTINGREPORT SET LINENUMBER = ECM.LINENUMBER FROM EC.ENGINEERINGCODEMASTER  ECM 
INNER JOIN #COSTINGREPORT ON #COSTINGREPORT.ACTIVITYNAME=ECM.ACTIVITYNAME WHERE ECM.CATEGORY = 'INDIRECT' AND #COSTINGREPORT.LINENUMBER=0

UPDATE #TEMPECREPORT SET LINENUMBER = ECM.LINENUMBER FROM EC.ENGINEERINGCODEMASTER  ECM 
INNER JOIN #TEMPECREPORT ON #TEMPECREPORT.ACTIVITYNAME=ECM.ACTIVITYNAME WHERE ECM.CATEGORY = 'REVENUE' 

UPDATE #TEMPECREPORT SET LINENUMBER = ECM.LINENUMBER FROM EC.ENGINEERINGCODEMASTER  ECM 
INNER JOIN #TEMPECREPORT ON #TEMPECREPORT.ACTIVITYNAME=ECM.ACTIVITYNAME WHERE ECM.CATEGORY = 'INDIRECT' AND #TEMPECREPORT.LINENUMBER=0


SELECT * INTO #FINAL FROM #TEMPECREPORT 
ALTER TABLE #FINAL ADD TOTALREVENUE DECIMAL(18,2) 
ALTER TABLE #FINAL ADD TOTALCOST DECIMAL(18,2) 
ALTER TABLE #FINAL ADD NETAMOUNT DECIMAL(18,2) 

 
UPDATE #FINAL SET TOTALREVENUE = REVENUE + WIP 
UPDATE #FINAL SET TOTALCOST = MATERIAL + LABOUR + INDIRECTS 
UPDATE #FINAL SET NETAMOUNT = TOTALREVENUE - TOTALCOST 

SELECT ID , ACTIVITYNAME ,REVENUE ,WIP ,MATERIAL ,LABOUR ,INDIRECTS ,TOTAL ,LINENUMBER   FROM #TEMPECREPORT  ORDER BY LINENUMBER
SELECT * FROM #COSTINGREPORT ORDER BY LINENUMBER
SELECT ID,ACTIVITYNAME,REVENUE,WIP,TOTALREVENUE,MATERIAL,LABOUR,INDIRECTS,TOTALCOST,NETAMOUNT , LINENUMBER FROM #FINAL ORDER BY LINENUMBER