/****** Object:  Procedure [EC].[spFixEngineeringCodesSubbiee]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE  [EC].[spFixEngineeringCodesSubbiee](@SUBBIEERECONID BIGINT ) 
AS 
BEGIN 
	--EXEC  EC.spUpdateTRANGRPSUBBIE
	DECLARE @COLKEY VARCHAR(25) 
	SET @COLKEY = STR(@SUBBIEERECONID)
	DECLARE @ACCBOQDETAILID BIGINT
	DECLARE @DESCRIPTION VARCHAR(255)
	DECLARE @ACCBOQHEADERID  BIGINT
 	DECLARE @ORDERNO VARCHAR(50)
	DECLARE @ORDERID INT 
	DECLARE @GLCODEID INT
	DECLARE @LINENUMBER INT
	DECLARE @UNIT VARCHAR(15)
	DECLARE @QUANTITY DECIMAL(18,2)
	DECLARE @RATE DECIMAL(18,2) 
	DECLARE @LEDGERCODE VARCHAR(15)
	DECLARE @ORDEREDQTY DECIMAL(18,2)

	DECLARE @VALNO INT
	DECLARE @CERTNO VARCHAR(15)
	DECLARE @POSTREF VARCHAR(25)
	DECLARE @HEADERREFERENCEID INT
	DECLARE @ACTIVITYID INT 
	DECLARE @EXISTING INT 
	DECLARE @ACTIVITYNAME VARCHAR(100)
	DECLARE @ENGINEERINGCODE VARCHAR(15)

	SELECT @VALNO=VALNO,@CERTNO=CERTNOA,@POSTREF=POSTREF FROM SUBCRECONS WHERE RECONID=@SUBBIEERECONID AND POSTED=0
	SET @EXISTING=0
	SELECT @EXISTING=ISNULL(HEADERID,0) FROM EC.SUBBIEHEADER 
	WHERE RECONID=@SUBBIEERECONID  AND TRANGRP=0 
	
 

	IF @EXISTING = 0
	 BEGIN
	   INSERT INTO EC.SUBBIEHEADER (RECONID,VALNO,CERTNO,POSTREF,TRANGRP) 
	   SELECT @SUBBIEERECONID,@VALNO,@CERTNO,@POSTREF,0 
	   
	   SELECT @HEADERREFERENCEID= HEADERID  FROM EC.SUBBIEHEADER 
	   WHERE RECONID=@SUBBIEERECONID AND VALNO=@VALNO AND CERTNO=@CERTNO AND POSTREF=@POSTREF AND TRANGRP=0 

	   SELECT @ACCBOQHEADERID = HEADERID FROM ACCBOQHEADER WHERE RECONID=@SUBBIEERECONID

 
	   SELECT DETAILID ACCBOQDETAILID 
   	   INTO #WORKORDERLINEITEMS
	   FROM ACCBOQDETAIL WHERE HEADERID = @ACCBOQHEADERID AND SUBSTRING(UNIT,1,2)<>'H1' AND RECONHISTID=-1 AND LASTDETAILID=-1 and PREVDETAILID <>-1

	  


	   DECLARE WORKITEMS CURSOR FOR SELECT ACCBOQDETAILID FROM #WORKORDERLINEITEMS
	   OPEN WORKITEMS 
	   FETCH NEXT FROM WORKITEMS INTO @ACCBOQDETAILID 
	   WHILE @@FETCH_STATUS = 0
	   BEGIN
	        
	        SELECT  @DESCRIPTION =SUBSTRING(DESCRIPTION,1,255),@UNIT=UNIT,@QUANTITY=([PROG QTY]-[PREV QTY]),
			@RATE=RATE ,@ACTIVITYID=ACTID ,@ORDEREDQTY = quantity 
			FROM ACCBOQDETAIL WHERE DETAILID=@ACCBOQDETAILID
			select @ACCBOQDETAILID,@DESCRIPTION,@unit,@QUANTITY,@rate ,@ACTIVITYID 
			SELECT @ACTIVITYNAME = UPPER(ACTNAME),@ENGINEERINGCODE=ACTNUMBER  FROM ACTIVITIES WHERE ACTID =@ACTIVITYID
			
			 

		 	SELECT @ORDERNO = ORDERNO FROM SUBCRECONS WHERE RECONID=@SUBBIEERECONID 
			SELECT @ORDERID = ORDID FROM ORD WHERE ORDNUMBER=@ORDERNO 
			SELECT @GLCODEID =GLCODEID, @LINENUMBER = LINENUMBER
			FROM ORDITEMS WHERE ORDID=@ORDERID AND UPPER(SUBSTRING(ITEMDESCRIPTION,1,255))=UPPER(@DESCRIPTION) 
			SELECT @LEDGERCODE=LEDGERCODE FROM LEDGERCODES WHERE LEDGERID=@GLCODEID 

			INSERT INTO EC.SUBBIEDETAILS(HEADERID,ACCBOQDETAILID,ORDID,LINENUMBER,LEDGERCODE,ECCATEGORY,ACTIVITYCODE,QTY,RATE,AMOUNT)
			SELECT                       @HEADERREFERENCEID,@ACCBOQDETAILID,@ORDERID,@LINENUMBER,@LEDGERCODE,'LABOUR',ACTNUMBER,0,@RATE,0 
			FROM EC.ENGINEERINGCODEMASTER WHERE CATEGORY IN ('LABOUR')
			INSERT INTO EC.SUBBIEDETAILS(HEADERID,ACCBOQDETAILID,ORDID,LINENUMBER,LEDGERCODE,ECCATEGORY,ACTIVITYCODE,QTY,RATE,AMOUNT)
			SELECT			        	  @HEADERREFERENCEID,@ACCBOQDETAILID,@ORDERID,@LINENUMBER,@LEDGERCODE,'INDIRECT',ACTNUMBER,0,@RATE,0 
			FROM EC.ENGINEERINGCODEMASTER WHERE CATEGORY IN ('INDIRECT')

			SELECT * FROM EC.SUBBIEDETAILS
			WHERE HEADERID=@HEADERREFERENCEID AND ACCBOQDETAILID=@ACCBOQDETAILID AND ORDID=@ORDERID AND LTRIM(RTRIM(ACTIVITYCODE))=LTRIM(RTRIM(@ENGINEERINGCODE))
 
		    UPDATE EC.SUBBIEDETAILS SET QTY=@ORDEREDQTY ,RATE = @RATE ,AMOUNT=@ORDEREDQTY*@RATE 
			WHERE HEADERID=@HEADERREFERENCEID AND ACCBOQDETAILID=@ACCBOQDETAILID AND ORDID=@ORDERID AND ACTIVITYCODE=@ENGINEERINGCODE

	        FETCH NEXT FROM WORKITEMS INTO @ACCBOQDETAILID 
	   END
	   CLOSE WORKITEMS
	   DEALLOCATE WORKITEMS 
	   
	   UPDATE ATTRIBVALUE SET Value = 'Not Verified'  WHERE COLKEY  = @COLKEY


	 END
	ELSE 
	 BEGIN
	        UPDATE EC.SUBBIEHEADER 
			 SET VALNO=@VALNO, CERTNO=@CERTNO,POSTREF=@POSTREF WHERE RECONID=@SUBBIEERECONID  AND TRANGRP=0 
			UPDATE ATTRIBVALUE SET Value = 'Not Verified'  WHERE COLKEY  = @COLKEY
	 END

	SELECT * INTO #TEMP0 FROM EC.SUBBIEHEADER WHERE RECONID=@SUBBIEERECONID  AND TRANGRP=0 
	SELECT * FROM #TEMP0 

END

 