/****** Object:  Procedure [EC].[spTransactionDetails]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE procedure [EC].[spTransactionDetails](@PROJECTID INT,@CATEGORYID INT,@YEAR INT,@FROMPERIOD INT,@TOPERIOD INT) 
as
DECLARE @ROWCOUNT INT
DECLARE @LASTTRANGRP INT
DECLARE @OBYEAR INT 
DECLARE @CUTOFFDATE DATETIME 
SELECT @LASTTRANGRP = LASTTRANGRP ,@OBYEAR = FINYEAR,@CUTOFFDATE = CUTOFFDATE  FROM EC.PROJECTS WHERE BSBORGID=@PROJECTID 

CREATE TABLE #TRANSACTIONS(YEAR INT,PERIOD INT,PDATE DATETIME,TRANGRP INT,ACTIVITY VARCHAR(15),BATCHREF VARCHAR(15), TRANSREF VARCHAR(15),TRANSTYPE VARCHAR(15),LEDGERCODE VARCHAR(15),
DESCRIPTION VARCHAR(200),CREDNO VARCHAR(25),STORE VARCHAR(25), STOCKNO VARCHAR(25), REQNO VARCHAR(25),ORDERNO VARCHAR(25),QTY DECIMAL(18,2),RATE DECIMAL(18,2), AMOUNT DECIMAL(18,2),USERNAME VARCHAR(35),TIMESTAMP DATETIME )
 
CREATE TABLE #RESULTS(YEAR INT,PERIOD INT,PDATE DATETIME,TRANGRP INT,ACTIVITY VARCHAR(15),BATCHREF VARCHAR(15), TRANSREF VARCHAR(15),TRANSTYPE VARCHAR(15),LEDGERCODE VARCHAR(15),
DESCRIPTION VARCHAR(200),CREDNO VARCHAR(25),STORE VARCHAR(25), STOCKNO VARCHAR(25), REQNO VARCHAR(25),ORDERNO VARCHAR(25),QTY DECIMAL(18,2),RATE DECIMAL(18,2) ,AMOUNT DECIMAL(18,2),USERNAME VARCHAR(35), TIMESTAMP DATETIME )
 


INSERT INTO #TRANSACTIONS
SELECT YEAR,PERIOD,PDATE,TRANGRP,ACTIVITY,BATCHREF,TRANSREF,TRANSTYPE,LEDGERCODE,LEFT(DESCRIPTION,200),CREDNO,STORE,STOCKNO,REQNO,ORDERNO,QUANTITY,RATE,(DEBIT-CREDIT),USERID ,SYSDATE 
FROM TRANSACTIONS WHERE ORGID=@PROJECTID AND YEAR = @YEAR AND PERIOD  BETWEEN @FROMPERIOD AND @TOPERIOD AND TRANGRP >@LASTTRANGRP AND ALLOCATION='Contracts'


SELECT @ROWCOUNT = ISNULL(COUNT(*),0) FROM #TRANSACTIONS 
 

IF @ROWCOUNT >0 
 BEGIN 
    IF @CATEGORYID = 3 
	    INSERT INTO #RESULTS 
        SELECT *  FROM #TRANSACTIONS WHERE TRANSTYPE IN (SELECT TYPENAME  FROM STOCKTYPES) 
	ELSE 
	    INSERT INTO #RESULTS 
		SELECT * FROM #TRANSACTIONS WHERE 1=2

    UPDATE #RESULTS SET USERNAME =UPPER(U.USERNAME) FROM USERS U INNER JOIN #RESULTS ON #RESULTS.USERNAME=U.USERID 

    SELECT * FROM #RESULTS ORDER BY PERIOD,TRANGRP 
 END
ELSE
 SELECT * FROM #RESULTS  WHERE 1=2 