/****** Object:  Procedure [EC].[spUpdateTRANGRPSales]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE [EC].[spUpdateTRANGRPSales]
AS
DECLARE @HEADERID INT
DECLARE @RECONID INT
DECLARE @TRANGRP INT

DECLARE @BORGID INT
DECLARE @DEBTID  INT 
DECLARE @PARTYCODE VARCHAR(15)
DECLARE @POSTREF VARCHAR(25)
DECLARE @POSTINGDATE DATETIME 
DECLARE @AMOUNT DECIMAL(18,2)
DECLARE @DEBTORLEDGERCODE VARCHAR(15)
DECLARE @CODE VARCHAR(15)
DECLARE @NETRECEIVABLE DECIMAL(18,2)
DECLARE @EINVOICE VARCHAR(200)
DECLARE @INVOICEID INT 
DECLARE @ACKNUMBER VARCHAR(25)
DECLARE @ACKDATE DATETIME 
DECLARE @IRN VARCHAR(100)

DECLARE TRANGRPS CURSOR FOR SELECT DISTINCT DEBTRECONID FROM EI.DEBTORINVOICEHEADER EI WHERE EI.EISTATUS=1 AND ( EI.TRANGRP=0 OR EI.TRANGRP IS NULL)
OPEN TRANGRPS
FETCH NEXT FROM TRANGRPS INTO  @RECONID 

WHILE @@FETCH_STATUS=0
BEGIN
  SET @CODE=''
  SET @BORGID = 0
  SET @DEBTID= 0
  SET @POSTREF = ''
  SET @POSTINGDATE = GETDATE() 
  SET @AMOUNT = 0 

  SELECT @NETRECEIVABLE = NETRECEIVABLE,@PARTYCODE=PARTYCODE ,@BORGID=BORGID  FROM EI.DEBTORINVOICEHEADER WHERE DEBTRECONID=@RECONID 

  SELECT @INVOICEID=INVOICEID,@BORGID=BORGID,@ACKNUMBER=ACKNUMBER,@ACKDATE=ACKDATE,@IRN=IRN 
  FROM EI.EINVOICE WHERE PARTYCODE = @PARTYCODE AND BORGID=@BORGID AND INVOICEAMOUNT=@NETRECEIVABLE AND TRANSGROUP=-1

  SET @EINVOICE = 'e-Invoice Generated For Total Gross BIll Value  with Acknowledgement Number '+ @ACKNUMBER + '  Dated: '+CONVERT(VARCHAR(20),@ACKDATE,103) + ' IRN: ' + @IRN 
  SELECT @CODE=CODE FROM DEBTRECONS WHERE RECONID=@RECONID 
  IF @CODE IN ('16.20','16.22','16.24') 
     SET @DEBTORLEDGERCODE = '2540009'
  ELSE
     SET @DEBTORLEDGERCODE = '2540000'

 
 

  SELECT @BORGID=ORGID,@DEBTID=SUBCONNUMBER,@POSTREF=CERTNO,@POSTINGDATE=CONVERT(DATE,POSTDATE) ,@AMOUNT=PAID 
  FROM DEBTRECONS WHERE RECONID=@RECONID AND POSTED=1
  SELECT @PARTYCODE = DEBTNUMBER FROM DEBTORS  WHERE DEBTID =@DEBTID 

  SET @TRANGRP = 0

  SELECT @TRANGRP=TRANGRP 
  FROM TRANSACTIONS 
  WHERE ORGID=@BORGID AND PDATE=@POSTINGDATE AND CREDNO=@PARTYCODE AND (DEBIT-CREDIT)=@AMOUNT AND LEDGERCODE=@DEBTORLEDGERCODE AND
  LEFT(BATCHREF,3)='DTI' 

 

  IF @TRANGRP<>0 
  BEGIN
   BEGIN TRAN
      UPDATE EI.DEBTORINVOICEHEADER SET TRANGRP=@TRANGRP, EISTATUS=2 WHERE  DEBTRECONID=@RECONID 
	  UPDATE DEBTRECONS SET POSTDATE = RETRELEASEDATE WHERE RECONID=@RECONID 
	  UPDATE DEBTRECONS SET REMARK  = @EINVOICE WHERE RECONID=@RECONID 
	  UPDATE EI.EINVOICE SET TRANSGROUP = @TRANGRP WHERE INVOICEID=@INVOICEID
   COMMIT TRAN
  END
  FETCH NEXT FROM TRANGRPS INTO @RECONID 

END
CLOSE TRANGRPS
DEALLOCATE TRANGRPS 