/****** Object:  Procedure [EC].[spUpdateTRANGRPSubbie]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE [EC].[spUpdateTRANGRPSubbie]
AS
DECLARE @HEADERID INT
DECLARE @RECONID VARCHAR(25)
DECLARE @TRANGRP INT

DECLARE @BORGID INT
DECLARE @SUBCONID INT 
DECLARE @PARTYCODE VARCHAR(15)
DECLARE @POSTREF VARCHAR(25)
DECLARE @POSTINGDATE DATETIME 
DECLARE @AMOUNT DECIMAL(18,2)
DECLARE @SUBBIEELEDGERCODE VARCHAR(15)
SET @SUBBIEELEDGERCODE = '1320000' 

DECLARE TRANGRPS CURSOR FOR SELECT HEADERID,RECONID FROM EC.SUBBIEHEADER WHERE TRANGRP=0
OPEN TRANGRPS
FETCH NEXT FROM TRANGRPS INTO @HEADERID,@RECONID 

WHILE @@FETCH_STATUS=0
BEGIN

  SET @BORGID = 0
  SET @SUBCONID= 0
  SET @POSTREF = ''
  SET @POSTINGDATE = GETDATE() 
  SET @AMOUNT = 0 

  SELECT @BORGID=ORGID,@SUBCONID=SUBCONNUMBER,@POSTREF=POSTREF,@POSTINGDATE=CONVERT(DATE,POSTDATE) ,@AMOUNT=PAID 
  FROM SUBCRECONS WHERE RECONID=@RECONID AND POSTED=1
  SELECT @PARTYCODE = SUBNUMBER FROM SUBCONTRACTORS WHERE SUBID=@SUBCONID

  SET @TRANGRP = 0

  SELECT @TRANGRP=TRANGRP 
  FROM TRANSACTIONS 
  WHERE ORGID=@BORGID AND PDATE=@POSTINGDATE AND CREDNO=@PARTYCODE AND CREDIT=@AMOUNT AND LEDGERCODE=@SUBBIEELEDGERCODE AND
  LEFT(BATCHREF,3)='SCI' 

 

  IF @TRANGRP<>0 
   BEGIN
     UPDATE EC.SUBBIEHEADER SET TRANGRP=@TRANGRP WHERE HEADERID=@HEADERID AND RECONID=@RECONID 
	 DELETE FROM EC.SUBBIEDETAILS WHERE QTY=0 AND HEADERID=@HEADERID 
	 UPDATE ATTRIBVALUE SET Value = 'POSTED'  WHERE COLKEY  = @RECONID 
   END

  FETCH NEXT FROM TRANGRPS INTO @HEADERID,@RECONID 

END
CLOSE TRANGRPS
DEALLOCATE TRANGRPS 