/****** Object:  Procedure [BT].[AddEditDPRMachinery]    Committed by VersionSQL https://www.versionsql.com ******/

--SELECT * FROM BT.SALES

--CREATE TABLE BT.DPR(DPRID INT Primary Key,ProjectCode int, BOQNumber Varchar(15), DPRDate DateTime, DPRQty Decimal(18,2) )

CREATE Procedure [BT].[AddEditDPRMachinery](@DPRID int,@ProjectCode int, @DPRDATESTRING Varchar(15),
@EquipmentID int,@STARTREADING DECIMAL(18,2),@ENDREADING DECIMAL(18,2),@IDLEHOURS DECIMAL(18,2),@BREAKDOWNHOURS DECIMAL(18,2),
@WORKINGHOURS DECIMAL(18,2) )

AS

DECLARE @NEXTID INT
SELECT @NEXTID =ISNULL( MAX(DPRID) ,0 ) FROM BT.DPRMachinery
SET @NEXTID = @NEXTID + 1

DECLARE @DPRDATE DATETIME 
SET @DPRDATE = CONVERT(DATETIME,@DPRDATESTRING,103);




IF @DPRID= 0 
 BEGIN
       INSERT INTO BT.DPRMachinery (DPRID,PROJECTCODE,DPRDATE,EQUIPMENTCODE,STARTREADING,ENDREADING,IDLEHOURS,BREAKDOWNHOURS,WORKINGHOURS)  
       VALUES     (@NEXTID,@ProjectCode,@DPRDATE,@EQUIPMENTID,@STARTREADING,@ENDREADING,@IDLEHOURS,@BREAKDOWNHOURS,@WORKINGHOURS)
 END
ELSE
 BEGIN
       UPDATE BT.DPRMachinery SET STARTREADING=@STARTREADING,ENDREADING =@ENDREADING, IDLEHOURS =@IDLEHOURS,BREAKDOWNHOURS=@BREAKDOWNHOURS,
	   WORKINGHOURS = @WORKINGHOURS 	   WHERE DPRID=@DPRID
 END