/****** Object:  Procedure [BT].[DELETEUPLOADEDWOITEMS]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE [BT].[DELETEUPLOADEDWOITEMS](@PROJECTCODE INT,@TASKID INT)
AS
DECLARE @BORGID INT 
SELECT @BORGID=BORGID FROM BT.PROJECTS WHERE PROJECTID=@PROJECTCODE
 
-- TASKID = 1 MEANS DELETE 
IF @TASKID = 1
 BEGIN 
	DELETE  FROM TENDERITEMS WHERE BORG=@BORGID AND CATEGORY='SUBCONTRACTORS'
	DELETE  FROM BT.WORKORDER WHERE PROJECTCODE=@PROJECTCODE
	DELETE  FROM BT.WORKORDERITEMS WHERE PROJECT=@PROJECTCODE
	DELETE FROM BT.REVISIONIDS WHERE PROJECTCODE=@PROJECTCODE AND BUDGETSHORTCODE='WO'
	DELETE FROM BT.WORKORDEROB WHERE PROJECTCODE=@PROJECTCODE 
 END

 -- TASKID =2  MEANS UPLOAD OPENING BALANCE 
IF @TASKID = 2
 BEGIN 
  UPDATE TENDERITEMS SET 
   ORDEREDQTY = OB.OPENINGQTY ,
   ORDEREDAMOUNT = OB.OPENINGVALUE
  FROM  BT.WORKORDEROB  OB INNER JOIN TENDERITEMS ON TENDERITEMS.RESCODE=OB.TOOLCODE 
  WHERE OB.PROJECTCODE=@PROJECTCODE AND TENDERITEMS.BORG = @BORGID AND TENDERITEMS.CATEGORY='SUBCONTRACTORS' 
  SELECT * FROM TENDERITEMS WHERE BORG=@BORGID AND TENDERITEMS.CATEGORY='SUBCONTRACTORS' 
END 
 