/****** Object:  Procedure [BT].[fetchDPRBOQEntry]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE [BT].[fetchDPRBOQEntry](@PROJECTCODE INT,@DPRDATESTRING VARCHAR(15), @INDEX INT)
AS
DECLARE @DPRDATE DATETIME 
SET @DPRDATE = CONVERT(DATETIME,@DPRDATESTRING,103)

CREATE TABLE #BOQ(BOQNUMBER  VARCHAR(15), BOQ VARCHAR(255), UOM VARCHAR(15), RATE DECIMAL(18,2),
THISDAYQTY DECIMAL(18,2), THISDAYVALUE DECIMAL(18,2),
THISMONTHQTY DECIMAL(18,2), THISMONTHVALUE DECIMAL(18,2),
TODATEQTY DECIMAL(18,2), TODATEVALUE DECIMAL(18,2)) 


  

INSERT INTO #BOQ(BOQNUMBER,BOQ,UOM,RATE) 
SELECT BOQNUMBER,BOQ,UOM,RATE 
FROM BT.SALES WHERE PROJECTCODE=@PROJECTCODE
UPDATE #BOQ SET THISDAYQTY=0,THISMONTHQTY=0,TODATEQTY=0

SELECT D.BOQNUMBER,D.DPRQTY THISDAYQTY
INTO #THISDAY
FROM BT.DPR D  
WHERE D.PROJECTCODE=@PROJECTCODE AND D.DPRDATE=@DPRDATE 


SELECT D.BOQNUMBER,SUM(D.DPRQTY) THISMONTHQTY 
INTO #THISMONTH 
FROM BT.DPR D  
WHERE D.PROJECTCODE=@PROJECTCODE AND MONTH(D.DPRDATE)=MONTH(@DPRDATE) AND YEAR(D.DPRDATE)=YEAR(@DPRDATE) 
GROUP BY D.BOQNumber
 
SELECT D.BOQNUMBER,SUM(D.DPRQTY) TODATEQTY
INTO #TODATEQTY
FROM BT.DPR D  
WHERE D.PROJECTCODE=@PROJECTCODE  
GROUP BY D.BOQNUMBER 


UPDATE #BOQ SET THISDAYQTY    = T.THISDAYQTY   FROM #THISDAY   T INNER JOIN #BOQ ON #BOQ.BOQNUMBER = T.BOQNUMBER 
UPDATE #BOQ SET TODATEQTY     = T.TODATEQTY    FROM #TODATEQTY T INNER JOIN #BOQ ON #BOQ.BOQNUMBER = T.BOQNumber 
UPDATE #BOQ SET THISMONTHQTY  = T.THISMONTHQTY FROM #THISMONTH T INNER JOIN #BOQ ON #BOQ.BOQNUMBER = T.BOQNumber 
UPDATE #BOQ SET THISDAYVALUE = THISDAYQTY*RATE,THISMONTHVALUE = THISMONTHQTY* RATE , TODATEVALUE = TODATEQTY*RATE  
 
ALTER TABLE #BOQ ADD PROJECTCODE INT
UPDATE #BOQ SET PROJECTCODE=@PROJECTCODE 


IF @INDEX = 1
 BEGIN
   DELETE FROM #BOQ WHERE THISDAYQTY=0
   SELECT BOQNUMBER,BOQ,UOM,RATE,THISDAYQTY [This Day Qty],THISDAYVALUE  [This Day Value]  FROM #BOQ ORDER BY BOQNUMBER
 END

IF @INDEX = 2
 BEGIN
   DELETE FROM #BOQ WHERE THISDAYQTY=0
   SELECT BOQNUMBER,BOQ,UOM,RATE,THISDAYQTY [This Day Qty],THISDAYVALUE  [This Day Value],THISMONTHQTY [This Month Qty],
   THISMONTHVALUE [This Month Value], TODATEQTY [Till Date Qty],TODATEVALUE [Till Date Value] FROM #BOQ ORDER BY BOQNUMBER  
 END

IF @INDEX = 3
 BEGIN
   DELETE FROM #BOQ WHERE THISMONTHQTY=0
   SELECT BOQNUMBER,BOQ,UOM,RATE,THISMONTHQTY [This Month Qty],THISMONTHVALUE [This Month Value] FROM #BOQ ORDER BY BOQNUMBER 
 END

IF @INDEX = 4
 BEGIN
   DELETE FROM #BOQ WHERE TODATEQTY = 0
   SELECT BOQNUMBER,BOQ,UOM,RATE,TODATEQTY [Till Date Qty],TODATEVALUE [Till Date Value] FROM #BOQ ORDER BY BOQNUMBER 
 END