/****** Object:  Procedure [BT].[spAddEditMinorWorkHead]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE [BT].[spAddEditMinorWorkHead](@MINORWORKHEADID INT,@MAJORWORKHEADCODE INT,@MINORWORKHEAD VARCHAR(200),@UOM VARCHAR(10))
AS
DECLARE @NEXTNUMBER INT 

IF @MINORWORKHEADID = 0
 SELECT @NEXTNUMBER =ISNULL(MAX(MINORWORKHEADID),0)  FROM BT.MINORWORKHEAD 

IF @MINORWORKHEADID =0 
 BEGIN
  INSERT INTO  BT.MINORWORKHEAD(MINORWORKHEADID,MAJORWORKHEADCODE,MINORWORKHEAD,UOM) 
   VALUES (@NEXTNUMBER+1,@MAJORWORKHEADCODE,@MINORWORKHEAD,@UOM) 
 END
ELSE
 BEGIN
   UPDATE BT.MINORWORKHEAD SET MINORWORKHEAD=@MINORWORKHEAD , UOM=@UOM WHERE MINORWORKHEADID=@MINORWORKHEADID 
 END 


       