/****** Object:  Procedure [BT].[spAddEditProjects]    Committed by VersionSQL https://www.versionsql.com ******/

 
CREATE PROCEDURE [BT].[spAddEditProjects](@PROJECTID int,@PROJECTCODE VARCHAR(10),@BORGID int,@STARTDATE DATETIME,@ENDDATE DATETIME,@REVISIONID INT) 
AS
DECLARE @NEXTPROJECTID INT 
DECLARE @PROJECTNAME   VARCHAR(100) 
DECLARE @BEGINYEARPERIOD INT 
DECLARE @ENDYEARPERIOD INT
DECLARE @DURATION INT 
DECLARE @BSCONTRACTNUMBER VARCHAR(15)
DECLARE @BSPROJECTID INT
DECLARE @BSCONTRACTID INT 

DECLARE @BSDELIVERYID INT 
DECLARE @BSSTORENAME VARCHAR(25)
DECLARE @BSSTORELEDGERCODE VARCHAR(10)
DECLARE @BSSTORELEDGERID INT 
DECLARE @EXISTINGBMTPROJECTID INT
DECLARE @REVISIONTEXT VARCHAR(15)
SET @REVISIONTEXT = 'REV(';

SELECT @BSDELIVERYID = ISNULL(SHIPTOID,0) FROM BORGDELADDR  WHERE BORGID=@BORGID 
SELECT @BSPROJECTID = PROJID   FROM DBO.PROJECTS   WHERE BORGID=@BORGID 
SELECT @BSCONTRACTID = CONTRID,@BSCONTRACTNUMBER =LTRIM(RTRIM(SUBSTRING(CONTRNUMBER,4,15)))  FROM CONTRACTS WHERE PROJID=@BSPROJECTID 
 
DECLARE @SCOUNTER VARCHAR(15)
SELECT  @SCOUNTER = CONTRNUMBER FROM CONTRACTS WHERE CONTRID=@BSCONTRACTID

SELECT @BSSTORENAME=UPPER(STORECODE),@BSSTORELEDGERCODE= STKCTL FROM INVSTORES WHERE STORECONTNUMBER = @SCOUNTER
SELECT @BSSTORELEDGERID = LEDGERID FROM LEDGERCODES WHERE LEDGERCODE=@BSSTORELEDGERCODE
 


IF @PROJECTID=0 
 SELECT @NEXTPROJECTID =ISNULL( MAX(PROJECTID)+1,1) FROM BT.PROJECTS 
   
SELECT @PROJECTNAME=BORGNAME FROM BORGS WHERE BORGID=@BORGID  

IF @REVISIONID <>1
   BEGIN
      SET @REVISIONTEXT = LTRIM(RTRIM(@REVISIONTEXT))+ LTRIM(RTRIM(STR(@REVISIONID))) +')'
	  SET @PROJECTNAME = @PROJECTNAME +'-' + @REVISIONTEXT 
	  SELECT @EXISTINGBMTPROJECTID = PROJECTID FROM BT.PROJECTS WHERE BORGID=@BORGID 
   END

SELECT @BEGINYEARPERIOD = YEARPERIODID FROM BT.YearPeriodMaster WHERE @STARTDATE>=STARTDATE AND @STARTDATE<=ENDDATE 
SELECT @ENDYEARPERIOD   = YEARPERIODID FROM BT.YearPeriodMaster WHERE @ENDDATE>=STARTDATE   AND @ENDDATE<=ENDDATE 
 
SET @DURATION = (YEAR(@ENDDATE) - YEAR(@STARTDATE))*12 + (MONTH(@ENDDATE)-MONTH(@STARTDATE))+1
 

IF @PROJECTID = 0
 BEGIN
   INSERT INTO BT.PROJECTS(PROJECTID,PROJECTCODE,BORGID,PROJECTNAME,STARTDATE,ENDDATE,DURATION,BEGINYEARPERIODCODE,ENDYEARPERIODCODE,BSPROJECTID,BSCONTRACTID,STATUS,
   BSDELIVERYID,BSSTORENAME,BSSTORELEDGERCODE,BSStoreLedgerID,CTCRevisionID,CTCRevisionDate ) 
   VALUES (@NEXTPROJECTID,@PROJECTCODE,@BORGID,@PROJECTNAME,@STARTDATE,@ENDDATE,@DURATION,@BEGINYEARPERIOD,@ENDYEARPERIOD,@BSPROJECTID,@BSCONTRACTID, 1,
   @BSDELIVERYID,@BSSTORENAME,@BSSTORELEDGERCODE,@BSSTORELEDGERID,@REVISIONID,GETDATE())
 END 
ELSE
 BEGIN
   UPDATE BT.PROJECTS 
     SET PROJECTCODE=@PROJECTCODE,PROJECTNAME=@PROJECTNAME,STARTDATE=@STARTDATE,ENDDATE=@ENDDATE,DURATION=@DURATION,BORGID=@BORGID,
	     BEGINYEARPERIODCODE = @BEGINYEARPERIOD, ENDYEARPERIODCODE=@ENDYEARPERIOD ,BSSTORENAME=@BSSTORENAME,BSSTORELEDGERCODE=@BSSTORELEDGERCODE
	 WHERE PROJECTID=@PROJECTID 
 END

IF (@REVISIONID=1)
BEGIN
	INSERT INTO BT.BMTUSERPROJECTMAPPING(LOGINID,PROJECTID,ROLEID)  VALUES ('CIPL1113',@NEXTPROJECTID,2 )
	INSERT INTO BT.BMTUSERPROJECTMAPPING(LOGINID,PROJECTID,ROLEID)  VALUES ('CIPL2866',@NEXTPROJECTID,2 )
	INSERT INTO BT.BMTUSERPROJECTMAPPING(LOGINID,PROJECTID,ROLEID)  VALUES ('CIPL3738',@NEXTPROJECTID,2 )
	INSERT INTO BT.BMTUSERPROJECTMAPPING(LOGINID,PROJECTID,ROLEID)  VALUES ('CIPL61',@NEXTPROJECTID,2 )
	INSERT INTO BT.BMTUSERPROJECTMAPPING(LOGINID,PROJECTID,ROLEID)  VALUES ('PPSL974',@NEXTPROJECTID,2 )
	INSERT INTO BT.BMTUSERPROJECTMAPPING(LOGINID,PROJECTID,ROLEID)  VALUES ('vinod',@NEXTPROJECTID,2 )
END 


IF @REVISIONID<>1 
BEGIN
  UPDATE BT.PROJECTS SET BORGID=-1 WHERE PROJECTCODE=@PROJECTCODE AND CTCREVISIONID <> @REVISIONID
  UPDATE TENDERITEMS SET BORG=-1,PROJECT=-1,CONTRACT=-1 WHERE BORG = @BORGID AND CATEGORY='SUBCONTRACTORS'
  UPDATE TENDERITEMS SET BORG=-1,PROJECT=-1,CONTRACT=-1 WHERE BORG = @BORGID AND CATEGORY='MATERIAL'
  UPDATE BT.BMTUSERPROJECTMAPPING  SET PROJECTID=@NEXTPROJECTID WHERE PROJECTID=@EXISTINGBMTPROJECTID
 
END




 
RETURN  1
 