/****** Object:  Procedure [BT].[spAddMorePeriodEnds]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE [BT].[spAddMorePeriodEnds]
AS
DECLARE @STARTYEAR INT  
DECLARE @ENDYEAR   INT
DECLARE @MONTH INT
DECLARE @CURRENTYEAR INT
DECLARE @CURRENTMONTH INT 
DECLARE @STARTDATESTRING VARCHAR(15)
DECLARE @ENDDATESTRING VARCHAR(15)
DECLARE @PERIODSTARTDATESTRING VARCHAR(15) 
DECLARE @STARTDATE DATETIME
DECLARE @ENDDATE   DATETIME 
DECLARE @YEARPERIODID INT 
DECLARE @PERIOD INT 
DECLARE @PERIODFULLNAME VARCHAR(15) 
DECLARE @FINYEAR INT 
DECLARE @YEAR INT 
DECLARE @MONTHFULLNAME VARCHAR(25) 
SET @YEARPERIODID=99

DELETE FROM BT.YEARPERIODMASTER 

SET @STARTYEAR= 2018 
SET @ENDYEAR = @STARTYEAR+50 

SET @CURRENTYEAR = @STARTYEAR 

WHILE @CURRENTYEAR <= @ENDYEAR 
BEGIN
   SET @YEAR = @CURRENTYEAR 
   SET @CURRENTMONTH=1
   WHILE @CURRENTMONTH<=12 
    BEGIN
	  SET @STARTDATESTRING = '01/'+LTRIM(RTRIM(STR(@CURRENTMONTH)))+'/'+LTRIM(RTRIM(STR(@CURRENTYEAR)))
	   
	  IF @CURRENTMONTH IN (1,3,5,7,8,10,12) 
	     SET @ENDDATESTRING = '31/'+LTRIM(RTRIM(STR(@CURRENTMONTH)))+'/'+LTRIM(RTRIM(STR(@CURRENTYEAR)))
	  ELSE IF @CURRENTMONTH IN (4,6,9,11) 
	     SET @ENDDATESTRING = '30/'+LTRIM(RTRIM(STR(@CURRENTMONTH)))+'/'+LTRIM(RTRIM(STR(@CURRENTYEAR)))
	  ELSE IF @CURRENTMONTH=2
	     SET @ENDDATESTRING = '28/'+LTRIM(RTRIM(STR(@CURRENTMONTH)))+'/'+LTRIM(RTRIM(STR(@CURRENTYEAR)))
	  
	  IF @CURRENTMONTH = 1 	     SET @PERIOD=10
	    IF @CURRENTMONTH = 2 	     SET @PERIOD=11
		  IF @CURRENTMONTH = 3 	     SET @PERIOD=12
		    IF @CURRENTMONTH = 4 	     SET @PERIOD=1
			  IF @CURRENTMONTH = 5 	     SET @PERIOD=2
			    IF @CURRENTMONTH = 6 	     SET @PERIOD=3
				  IF @CURRENTMONTH = 7 	     SET @PERIOD=4
				    IF @CURRENTMONTH = 8 	     SET @PERIOD=5
					  IF @CURRENTMONTH = 9 	     SET @PERIOD=6
					    IF @CURRENTMONTH = 10 	     SET @PERIOD=7
						  IF @CURRENTMONTH = 11 	     SET @PERIOD=8
						    IF @CURRENTMONTH = 12 	     SET @PERIOD=9
      
       IF @PERIOD = 1 	         SET @PERIODFULLNAME='January'
	    IF @PERIOD = 2 	          SET @PERIODFULLNAME='February'
		  IF @PERIOD = 3 	       SET @PERIODFULLNAME='March'   
		    IF @PERIOD = 4 	        SET @PERIODFULLNAME='April'  
			  IF @PERIOD = 5 	     SET @PERIODFULLNAME='May'    
			    IF @PERIOD = 6 	      SET @PERIODFULLNAME='June'    
				  IF @PERIOD = 7       SET @PERIODFULLNAME='July'     
				    IF @PERIOD = 8 	    SET @PERIODFULLNAME='August'    
					  IF @PERIOD = 9     SET @PERIODFULLNAME='September'	    
					    IF @PERIOD = 10   SET @PERIODFULLNAME='October'	  
						  IF @PERIOD = 11  SET @PERIODFULLNAME='November'	     
						    IF @PERIOD = 12  SET @PERIODFULLNAME='December'	      
	  
	  
	  
	  IF @PERIOD IN (1,2,3,4,5,6,7,8,9) 
	     SET @FINYEAR = @CURRENTYEAR+1 
	  ELSE
	     SET @FINYEAR = @CURRENTYEAR 

	  SELECT @STARTDATE = CONVERT(DATETIME,@STARTDATESTRING,103) 
	  SELECT @ENDDATE   = CONVERT(DATETIME,@ENDDATESTRING,103) 
	  
	  SELECT @MONTHFULLNAME = DATENAME(month, @STARTDATE)
 
	  SELECT @PERIODFULLNAME =  DATENAME(month, @STARTDATE)
	  SET @YEARPERIODID = @YEARPERIODID+1


	  INSERT INTO BT.YEARPERIODMASTER(YEARPERIODID,[YEAR],CALENDARMONTH,STARTDATE,ENDDATE,MONTHFULLNAME,MONTHNAME,FINYEAR,PERIOD,PERIODFULLNAME,PERIODNAME) 
	  VALUES (@YEARPERIODID,@YEAR,@CURRENTMONTH,@STARTDATE,@ENDDATE,@MONTHFULLNAME,LEFT(@MONTHFULLNAME,3),@FINYEAR,@PERIOD,@PERIODFULLNAME,LEFT(@PERIODFULLNAME,3)) 
	    
	  SET @CURRENTMONTH = @CURRENTMONTH+1
	END
   



   SET @CURRENTYEAR = @CURRENTYEAR+1
END 

SELECT * FROM BT.YEARPERIODMASTER 