/****** Object:  Procedure [BT].[spAddEditTenderItems]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE [BT].[spAddEditTenderItems](@ITEMID INT,@RESOURCECODE VARCHAR(10),@DESR VARCHAR(250),@RATE DECIMAL(18,2),@UOM VARCHAR(10),@QTY DECIMAL(18,4),@BORG INT,@PROJECT INT,@CONTRACT INT,@GLCODE VARCHAR(10))
AS
DECLARE @NEXTID INT
DECLARE @EXISTING INT 
DECLARE @NEWDESCR VARCHAR(250) 
SELECT @NEWDESCR =  REPLACE(@DESR,'|','-')
 

SET @EXISTING =0 

SELECT @EXISTING = COUNT(*) FROM DBO.TENDERITEMS WHERE RESCODE=@RESOURCECODE AND BORG=@BORG AND PROJECT=@PROJECT AND CONTRACT=@CONTRACT 



IF @EXISTING=0 
 BEGIN
   INSERT INTO TENDERITEMS(RESCODE,      DESCR,    RATE, UNIT,QTY, BORG,  PROJECT, CONTRACT, LEDGERCODE,CATEGORY,CURRENCY)
   VALUES (                @RESOURCECODE,@NEWDESCR,@RATE,@UOM,@QTY,@BORG, @PROJECT,@CONTRACT,'5002900','MATERIAL','INR')
 END
ELSE
 BEGIN
   UPDATE TENDERITEMS SET QTY = QTY + @QTY WHERE RESCODE=@RESOURCECODE AND BORG=@BORG AND PROJECT=@PROJECT AND CONTRACT =@CONTRACT  
 END