/****** Object:  Procedure [BT].[spAddReqDetails]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE [BT].[spAddReqDetails](@REQHEADERID  INT ,@TOOLCODE VARCHAR(25),@LINENUMBER INT, @STOCKID INT, @QTY DECIMAL(18,4),@INSTRUCTIONS VARCHAR(255),@SUPPLIERID INT  )

AS
--CREATE TABLE VREQ(HEADERID INT,TOOLCODE VARCHAR(25),LINENUMBER INT,STOCKID INT,QTY DECIMAL(18,4))

--DROP TABLE VINOD180301
--SELECT @REQHEADERID  A,@TOOLCODE B,@LINENUMBER C,@STOCKID D,@QTY E,@INSTRUCTIONS F,@SUPPLIERID G INTO VINOD180301
 

DECLARE @ORIGINALTOOLCODE VARCHAR(25)
DECLARE @ORIGINALTOOLNAME VARCHAR(200)
DECLARE @ORIGINALBUYINGCATEGORY VARCHAR(10)
DECLARE @ORIGINALSTOCKID INT
DECLARE @CATELOGID INT
DECLARE @PRICE DECIMAL(18,2)
DECLARE @ITEMDESCRIPTION VARCHAR(255) 
DECLARE @BUYERPARTNUMBER VARCHAR(10)
DECLARE @UOM VARCHAR(15)
DECLARE @PROJECTID INT
DECLARE @CONTRACTID INT 
DECLARE @ALLOCATION VARCHAR(15)
DECLARE @ACTID INT 
DECLARE @GLCODEID INT 
DECLARE @STORECODE VARCHAR(15)
DECLARE @STOREGLCODE INT 
DECLARE @STOCKCTL VARCHAR(10)
DECLARE @BORGID INT
DECLARE @DELIVERYID INT 
DECLARE @INVENTORYSTORE  VARCHAR(10)
DECLARE @CATORTENDITEM INT 
DECLARE @FETCHTEMPLATECODE VARCHAR(15)
DECLARE @BUDGETRATEDEFINED DECIMAL(18,4)
DECLARE @CONVERTIONFACTOR DECIMAL(18,5)
DECLARE @MONTHLYBUDGETID INT
DECLARE @BMTPROJECTID INT
DECLARE @BUDGETQTYTOREDUCE DECIMAL(18,4) 
DECLARE @BUDGETCATEGORY VARCHAR(15)
DECLARE @TEMPLATECODE VARCHAR(15)
DECLARE @SPACES VARCHAR(2)
DECLARE @ITISAMATERIAL INT 
DECLARE @ITISSTATIONARY INT


SET @SPACES = ' '

SET @ORIGINALSTOCKID = @STOCKID

SET @CATORTENDITEM =  1 
SELECT @BORGID=BORGID FROM REQ WHERE REQID = @REQHEADERID
SELECT @BMTPROJECTID=PROJECTID, @PROJECTID = BSPROJECTID, @CONTRACTID =BSCONTRACTID ,@DELIVERYID = BSDELIVERYID FROM BT.PROJECTS WHERE BORGID=@BORGID 
SELECT TOP 1 @INVENTORYSTORE = STKSTORE  FROM INVENTORY WHERE BORGID=@BORGID 


 
DECLARE @CHECKROUTE INT
DECLARE @SPECIALROUTE INT 
IF (@TOOLCODE='-1') OR (@TOOLCODE='-2')  OR (@TOOLCODE='-3')
 BEGIN
  SET @SPECIALROUTE= @TOOLCODE 
  SET @CHECKROUTE  = @TOOLCODE
  SET @ORIGINALTOOLCODE=@TOOLCODE
  SET @CONVERTIONFACTOR=0
 END
ELSE
 BEGIN
  SET @SPECIALROUTE = 0
  SET @CHECKROUTE  = 0
 END  


 

IF @SUPPLIERID<=0 
   SET @SUPPLIERID = -1 


IF @SPECIALROUTE=0
BEGIN
	SET @ORIGINALSTOCKID = @STOCKID 
	SET @ITISAMATERIAL = 0
	SET @ITISSTATIONARY = 0
	SELECT @ITISAMATERIAL = COUNT(*) FROM BT.MasterMaterialDetail WHERE    STOCKID = @STOCKID

	IF @ITISAMATERIAL=0 
	  BEGIN
	   SELECT @ITISSTATIONARY = COUNT(*) FROM   BS.STATIONARYMASTER WHERE STOCKID=@STOCKID 
	   IF @ITISSTATIONARY >0 
		  SET    @ORIGINALTOOLCODE =  '9000000000'
		  SET    @TOOLCODE ='9000000000'
	  END                    
	ELSE
	  BEGIN
	   SELECT @CONVERTIONFACTOR = CONVERSIONFATCTOR,@TOOLCODE=TEMPLATECODE  FROM  BT.MasterMaterialDetail WHERE    STOCKID = @STOCKID
	   SET    @ORIGINALTOOLCODE = @TOOLCODE 
	   SELECT @ORIGINALTOOLNAME = UPPER(TEMPLATENAME),@ORIGINALBUYINGCATEGORY =UOM  FROM BT.MasterMaterialBudget WHERE TEMPLATECODE=@TOOLCODE 
	   IF @CONVERTIONFACTOR =0 OR @CONVERTIONFACTOR IS NULL
		      SET @CONVERTIONFACTOR=1
	  END
END


/** TOOLCODE = 1 : TRANSPORTATION CHARGES  **/

 
 
IF  (@TOOLCODE='9000000000') AND  @SPECIALROUTE NOT IN (-1,-2,-3)
BEGIN
  SET @CATELOGID = -1
  SET @ITEMDESCRIPTION = @INSTRUCTIONS
  SET @UOM ='Nos' 
  SET @BUYERPARTNUMBER =''
  SET @PRICE = 0.0  
  SET @ALLOCATION = 'Contracts' 
  SET @ACTID = 4
  SET @TOOLCODE=''
  SET @CATORTENDITEM = -1 
  SET @INSTRUCTIONS =' '
  SET @CHECKROUTE = -4 
  SELECT @ITEMDESCRIPTION = MATERIALNAME,
         @BUYERPARTNUMBER = MATERIALCODE,
		 @UOM=UOM ,
		 @PRICE = LASTPURCHASERATE,
		 @CONVERTIONFACTOR = CONVERSIONFATCTOR 
		 FROM BS.STATIONARYMASTER WHERE STOCKID=@STOCKID 
  SET @STOCKID = -1 
  SET @GLCODEID=657
  SET @CHECKROUTE=-4
  SET @FETCHTEMPLATECODE=@TOOLCODE
  SELECT @CATELOGID=ITEMID  FROM TENDERITEMS WHERE RESCODE=@FETCHTEMPLATECODE AND BORG=@BORGID
  SELECT @MONTHLYBUDGETID = MonthlyMaterialBudgetCode FROM BT.MonthlyMaterialBudget WHERE  PROJECTCODE=@BMTPROJECTID AND TOOLCODE= '9000000000'
  UPDATE BT.MonthlyMaterialBudget SET BudgetAmount  = BudgetAmount- @QTY*@PRICE  WHERE MonthlyMaterialBudgetCode=@MONTHLYBUDGETID
  UPDATE BT.MonthlyMaterialBudget SET CumulativeQty = BudgetAmount   WHERE MonthlyMaterialBudgetCode=@MONTHLYBUDGETID
  
END



IF @SPECIALROUTE= -1 
BEGIN
  SET @CATELOGID = -1
  SET @ITEMDESCRIPTION = 'Transportation Charges'
  SET @UOM ='Sum' 
  SET @BUYERPARTNUMBER =''
  SET @PRICE = CONVERT(DECIMAL(18,4),@INSTRUCTIONS)
  SET @ALLOCATION = 'Contracts' 
  SET @ACTID = 4
  SET @GLCODEID=614
  SET @STOCKID = -1 
  SET @TOOLCODE=''
  SET @CATORTENDITEM = -1 
  SET @INSTRUCTIONS =' '
  SET @ORIGINALTOOLCODE = @TOOLCODE 
END

 
IF @SPECIALROUTE =  -2 
BEGIN
 SET @CATELOGID = -1
 SET @ITEMDESCRIPTION = 'Loading Charges'
 SET @UOM ='Sum' 
 SET @BUYERPARTNUMBER =''
 SET @PRICE = 0
 SET @PRICE = CONVERT(DECIMAL(18,4),@INSTRUCTIONS)  
 SELECT @PRICE 
 SET @ALLOCATION = 'Contracts' 
 SET @ACTID = 4
 SET @GLCODEID=607
 SET @STOCKID = -1 
 SET @TOOLCODE=''
 SET @CATORTENDITEM = -1 
 SET @INSTRUCTIONS =' '
 SET @ORIGINALTOOLCODE = @TOOLCODE 
END 

IF @SPECIALROUTE =  -3 
BEGIN
 SET @CATELOGID = -1
 SET @ITEMDESCRIPTION = 'Pumping Charges'
 SET @UOM ='Sum' 
 SET @BUYERPARTNUMBER =''
 SET @PRICE = 0
 SET @PRICE = CONVERT(DECIMAL(18,4),@INSTRUCTIONS)  
 SET @ALLOCATION = 'Contracts' 
 SET @ACTID = 4
 SET @GLCODEID=593
 SET @STOCKID = -1 
 SET @TOOLCODE=''
 SET @CATORTENDITEM = -1 
 SET @INSTRUCTIONS =' '
 SET @ORIGINALTOOLCODE = @TOOLCODE 
 -- GLCODE = 5001900 RMC ONLY
END 


 

IF @SPECIALROUTE  =0
BEGIN
  SELECT TOP 1 @STORECODE = STKSTORE  FROM INVENTORY WHERE BORGID=@BORGID
  SELECT @STOCKCTL = STKCTL FROM INVSTORES WHERE STORECODE=@STORECODE 
  SELECT @STOREGLCODE = LEDGERID FROM LEDGERCODES WHERE LEDGERCODE = @STOCKCTL 

  SELECT 
     @ITEMDESCRIPTION = MATERIALNAME,
	 @BUYERPARTNUMBER = MATERIALCODE,
	 @UOM=UOM ,
	 @FETCHTEMPLATECODE=TEMPLATECODE,
	 @PRICE=LASTPURCHASERATE 
  FROM BT.MasterMaterialDetail WHERE STOCKID=@ORIGINALSTOCKID
 
  SELECT @CATELOGID=ITEMID  FROM TENDERITEMS WHERE RESCODE=@FETCHTEMPLATECODE AND BORG=@BORGID  

  SELECT @STOCKID = STKID FROM INVENTORY WHERE STKSTORE=@INVENTORYSTORE  AND STKCODE=@BUYERPARTNUMBER

  SELECT @MONTHLYBUDGETID = MonthlyMaterialBudgetCode FROM BT.MonthlyMaterialBudget WHERE 
  PROJECTCODE=@BMTPROJECTID AND TOOLCODE=@FETCHTEMPLATECODE

  SELECT @TEMPLATECODE =   TEMPLATECODE     FROM BT.MasterMaterialDetail WHERE MATERIALCODE=@BUYERPARTNUMBER

  SELECT @BUDGETCATEGORY =  UPPER(UOM)      FROM BT.MasterMaterialBudget WHERE TEMPLATECODE=@TEMPLATECODE  
  -- PLEASE NOTE ERROR SO UOM IS PICKED UP INSTEAD OF CATEGORY 
  SET @BUDGETCATEGORY = UPPER(@BUDGETCATEGORY) 

  IF ( (UPPER(@BUDGETCATEGORY)='LUMPSUM')   OR  ( UPPER(@BUDGETCATEGORY)='L' ) OR ( UPPER(@BUDGETCATEGORY)='LUMSUM' )   )
   BEGIN
     --   SELECT @BUDGETRATEDEFINED = LASTPURCHASERATE FROM BT.MasterMaterialDETAIL WHERE MATERIALCODE=@BUYERPARTNUMBER
	    --SET @PRICE = @BUDGETRATEDEFINED
        UPDATE BT.MonthlyMaterialBudget SET BudgetAmount = BudgetAmount- @QTY*@PRICE  WHERE MonthlyMaterialBudgetCode=@MONTHLYBUDGETID
   END
  ELSE 
   BEGIN
 	SET @BUDGETQTYTOREDUCE =@QTY * @CONVERTIONFACTOR
    UPDATE BT.MonthlyMaterialBudget SET CumulativeQty = CumulativeQty- @BUDGETQTYTOREDUCE WHERE MonthlyMaterialBudgetCode=@MONTHLYBUDGETID
   END
 
  IF UPPER(@BUDGETCATEGORY)='LUMPSUM' 
     SET   @CATORTENDITEM = -1

  SET @PROJECTID = -1
  SET @CONTRACTID = -1 
  SET @ALLOCATION = 'Balance Sheet            ' 
  SET @ACTID = -1
  SET @GLCODEID=@STOREGLCODE
END 

IF ( @ITISSTATIONARY=1 )
BEGIN
         SELECT  
     	 @PRICE = LASTPURCHASERATE 
		 FROM BS.STATIONARYMASTER WHERE MATERIALCODE=@BUYERPARTNUMBER
END

DECLARE @REQNUMBER VARCHAR(25)
SELECT @REQNUMBER=REQNUMBER FROM REQ WHERE REQID=@REQHEADERID

IF (@CATELOGID ='') OR (@CATELOGID IS NULL)
   SET @CATELOGID=-1

INSERT INTO [dbo].[REQITEMS]
           ([REQID]
           ,[LINENUMBER]
           ,[CATALOGITEMID]
           ,[ITEMDESCRIPTION]
           ,[BUYERPARTNUMBER]
           ,[SUPPID]
           ,[PARTNUMBER]
           ,[PARTNUMBEREXT]
           ,[UOM]
           ,[QTY]
           ,[PRICE]
           ,[PAYMENTID]
           ,[DLVRID]
           ,[INSTRUCTIONS]
           ,[VATPERC]
           ,[PROJECTID]
           ,[CONTRACTID]
           ,[MIMETYPE]
           ,[FILESIZEINKB]
           ,[ORIGINALFILEPATH]
           ,[SENDTOSUPP]
           ,[DIVISIONID]
           ,[RESOURCECODE]
           ,[FILEPATH]
           ,[DISCOUNT]
           ,[ITEMSTATUSID]
           ,[LASTCHANGE]
           ,[LASTCHANGEBY]
           ,[ITEMSTATUSDATE]
           ,[ISFREEITEM]
           ,[CATORTENDITEM]
           ,[GLCODEID]
           ,[ACTID]
           ,[ALLOCATION]
           ,[PENUMBER]
           ,[STOCKID]
           ,[ATTMESSAGE]
           ,[VATID]
           ,[JOBCARDID]
           ,[JOBCARDVATID]
           ,[JOBCARDLEDGERID]
           ,[JOBCARDACTID]
           ,[TBORGID]
           ,[TERMS]
           ,[EID]
           ,[VATAMOUNT]
           ,[STKCONVERTFLAG]
           ,[STKBUYCONV]
           ,[TENDERPRICE])
     VALUES
           (@REQHEADERID
           ,@LINENUMBER
           ,@CATELOGID
           ,@ITEMDESCRIPTION
           ,@BUYERPARTNUMBER
           ,@SUPPLIERID 
           ,@SPACES 
           ,@SPACES 
           ,@UOM
           ,@QTY
           ,@PRICE
           ,-1
           ,@DELIVERYID
           ,@INSTRUCTIONS
           ,0
           ,@PROJECTID
           ,@CONTRACTID 
           ,@SPACES 
           ,0
           ,@SPACES
           ,0
           ,-1
           ,@ORIGINALTOOLCODE
           ,@SPACES
           ,0
           ,163
           ,NULL
           ,NULL
           ,GETDATE()
           ,1
           ,@CATORTENDITEM
           ,@GLCODEID 
           ,@ACTID
           ,@ALLOCATION 
           ,-1
           ,@STOCKID 
           ,@SPACES
           ,', , , , , '
           ,@SPACES
           ,@SPACES
           ,@MONTHLYBUDGETID
           ,-1
           ,@BORGID
           ,@SPACES
           ,'CIL'
           ,0
           ,0
           ,@CONVERTIONFACTOR
           ,NULL)

DECLARE @INDEXID INT


IF @SPECIALROUTE=0
 BEGIN 
 SELECT @CATELOGID
  UPDATE TENDERITEMS SET ORDEREDQTY = ORDEREDQTY + (@QTY * @CONVERTIONFACTOR)    WHERE ITEMID=@CATELOGID
  
  
  INSERT INTO BT.BUDGETMATERIALMOVEMENTDETAIL(PROJECTCODE,  REQID,       REQDATE, REQNUMBER,  LINENUMBER ,STOCKCODE,       STOCKNAME,       PRQTY,PRRATE,PRAMOUNT   ,PRSTATUS,FINALIZED,TOOLCODE,TOOLNAME,CONVERTIONFACTOR,BUYINGCATEGORY,PRUOM,BUDGETPRQTY) 
  SELECT                                      @BMTPROJECTID,@REQHEADERID,GETDATE(),@REQNUMBER,@LINENUMBER,@BUYERPARTNUMBER,@ITEMDESCRIPTION,@QTY ,@PRICE,@QTY*@PRICE,163,0,@ORIGINALTOOLCODE,@ORIGINALTOOLNAME,@CONVERTIONFACTOR,@ORIGINALBUYINGCATEGORY,@UOM,-1


  INSERT INTO BT.MATERIALBUDGETLOG(LOGDATE,  TRANSACTIONTYPE,PROJECTCODE,  TOOLCODE,QTY, RATE,   AMOUNT,     CROSSREFERENCEID)
  SELECT                           GETDATE(),'P',            @BMTPROJECTID,@ORIGINALTOOLCODE,@QTY,@PRICE,@QTY*@PRICE,@REQHEADERID


 END 
 


 