/****** Object:  Procedure [BT].[spBMTLogin]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE [BT].[spBMTLogin](@USERID VARCHAR(15),@PWD VARCHAR(15))
AS
DECLARE @REGISTEREDUSER INT 
DECLARE @VALIDUSER INT
DECLARE @ROLEID INT
DECLARE @USERCATEGORY INT 
SELECT @REGISTEREDUSER = COUNT(*) FROM BT.BMTUSERS WHERE BSLOGINID=@USERID  
IF @REGISTEREDUSER >= 1
 BEGIN
    SELECT @VALIDUSER = COUNT(*) FROM BT.BMTUSERS WHERE BSLOGINID=@USERID AND BSPASSWORD=@PWD
	IF @VALIDUSER = 1 
	 BEGIN
	   SELECT @USERCATEGORY = USERCATEGORY FROM BT.BMTUSERS WHERE BSLOGINID=@USERID 
	   SELECT @ROLEID = ROLEID FROM BT.BMTUSERPROJECTMAPPING WHERE LOGINID=@USERID  
	   SELECT 1,'VALID',@ROLEID ROLEID,@USERCATEGORY USERCATEGORY
	 END
	ELSE
	   SELECT 0,'INVALID',0 ,-1
 END
ELSE
 SELECT 0,'INVALID',0  ,-1

  

 