/****** Object:  Procedure [BT].[spBudgetMaterialMovement]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE [BT].[spBudgetMaterialMovement](@PROJECTCODE INT)
as

--EXEC [BT].[spBUDGETAGENT] 

EXEC BT.spCrossCheckBudget @PROJECTCODE,1

DECLARE @TOOLCODEID INT
DECLARE @TOOLCODE VARCHAR(35) 
DECLARE @PROJECTNAME VARCHAR(100)
SELECT  @PROJECTNAME = PROJECTNAME FROM  BT.PROJECTS WHERE PROJECTID=@PROJECTCODE 
 

CREATE TABLE #TOOLCODE(TOOLCODEID INT PRIMARY KEY IDENTITY(1,1),PROJECTNAME VARCHAR(100),TOOLCODE VARCHAR(25),TOOLNAME VARCHAR(200), CATEGORY VARCHAR(25),UOM VARCHAR(15),
BUDGETQTY DECIMAL(18,4), BUDGETRATE DECIMAL(18,4),BUDGETAMOUNT DECIMAL(18,4), RELEASED DECIMAL(18,4),
OPENPR DECIMAL(18,4),CANCELLED DECIMAL(18,4),REJECTED DECIMAL(18,4),ORDERED DECIMAL(18,4),DELIVERED DECIMAL(18,4),COMPLETED DECIMAL(18,4),
BALANCEFORPURCHASE DECIMAL(18,4)) 

CREATE TABLE #DETAIL(DETAILID INT PRIMARY KEY IDENTITY(1,1),TOOLCODEID INT,LINENUMBER INT,
STOCKCODE VARCHAR(15),STOCKNAME VARCHAR(150),CONVERTIONFACTOR DECIMAL(18,4),PRUOM VARCHAR(15),
PRQTY DECIMAL(18,4),PRRATE DECIMAL(18,4),PRAMOUNT DECIMAL(18,4), REQID INT,REQNUMBER VARCHAR(25),REQDATE DATETIME,
OPENPR    DECIMAL(18,4),
CANCELLED DECIMAL(18,4),
REJECTED  DECIMAL(18,4) ,
ORDQTY DECIMAL(18,4),ORDRATE DECIMAL(18,4),ORDAMOUNT DECIMAL(18,4),ORDID INT,ORDNUMBER VARCHAR(25),ORDDATE DATETIME,
DELIVEREDQTY DECIMAL(18,4),COMPLETED DECIMAL(18,4))


SELECT TOOLCODE,SUM(BUDGETQTY) BUDGETQTY,SUM(BUDGETAMOUNT) BUDGETAMONT 
INTO #TEMPTOTALBUDGET 
FROM BT.ProjectMaterialBudgetMaster
WHERE PROJECTCODE=@PROJECTCODE 
GROUP BY TOOLCODE 



INSERT INTO #TOOLCODE(PROJECTNAME,TOOLCODE,BUDGETQTY,BUDGETAMOUNT)
SELECT @PROJECTNAME,* FROM #TEMPTOTALBUDGET 

UPDATE #TOOLCODE SET  BUDGETRATE=0,RELEASED=0,OPENPR=0,ORDERED=0,CANCELLED=0,COMPLETED=0,BALANCEFORPURCHASE=0 

 
UPDATE #TOOLCODE 
SET TOOLNAME = M.TEMPLATENAME,UOM=M.CATEGORY,CATEGORY=M.UOM
FROM BT.MasterMaterialBudget M 
INNER JOIN #TOOLCODE ON #TOOLCODE.TOOLCODE=M.TEMPLATECODE 

UPDATE #TOOLCODE 
SET BUDGETRATE = (BUDGETAMOUNT/BUDGETQTY) WHERE CATEGORY='Q' AND BUDGETQTY>0 



SELECT TOOLCODE,SUM(RELEASEQTY) RELEASEQTY 
INTO #TEMPRELEASESUMMARY
FROM BT.RELEASESUMMARY 
WHERE PROJECTCODE=@PROJECTCODE 
GROUP BY TOOLCODE 


UPDATE #TOOLCODE 
SET RELEASED = R.RELEASEQTY FROM #TEMPRELEASESUMMARY R 
INNER JOIN #TOOLCODE ON #TOOLCODE.TOOLCODE = R.TOOLCODE 


-- OPEN PR 
SELECT TOOLCODE,SUM(PRQTY) OPENPRQTY ,SUM(PRAMOUNT) OPENPRAMOUNT
INTO #OPENPR 
FROM BT.BUDGETMATERIALMOVEMENTDETAIL WHERE PRSTATUS IN (163,32) AND PROJECTCODE=@PROJECTCODE 
GROUP BY TOOLCODE 

UPDATE #TOOLCODE 
SET OPENPR = O.OPENPRQTY  FROM #OPENPR O
INNER JOIN #TOOLCODE ON #TOOLCODE.TOOLCODE = O.TOOLCODE WHERE #TOOLCODE.CATEGORY='Q'

UPDATE #TOOLCODE 
SET OPENPR = O.OPENPRAMOUNT  FROM #OPENPR O
INNER JOIN #TOOLCODE ON #TOOLCODE.TOOLCODE = O.TOOLCODE WHERE #TOOLCODE.CATEGORY='L'



---CANCELLED 
SELECT TOOLCODE,SUM(PRQTY) CANCELLEDQTY
INTO #CANCELLEDQTY
FROM BT.BUDGETMATERIALMOVEMENTDETAIL  WHERE  PROJECTCODE=@PROJECTCODE 
GROUP BY TOOLCODE 
 
SELECT TOOLCODE,SUM(CANCELLEDQTY) CANCELLEDAMOUNT
INTO #CANCELLEDAMOUNT
FROM BT.BUDGETMATERIALMOVEMENTDETAIL  WHERE  PROJECTCODE=@PROJECTCODE 
GROUP BY TOOLCODE 

UPDATE #TOOLCODE 
SET   CANCELLED = C.CANCELLEDQTY FROM #CANCELLEDQTY  C 
INNER JOIN #TOOLCODE ON #TOOLCODE.TOOLCODE = C.TOOLCODE WHERE #TOOLCODE.CATEGORY='Q'

UPDATE #TOOLCODE 
SET   CANCELLED = C.CANCELLEDAMOUNT FROM #CANCELLEDAMOUNT  C 
INNER JOIN #TOOLCODE ON #TOOLCODE.TOOLCODE = C.TOOLCODE WHERE #TOOLCODE.CATEGORY='L'


-- REJECTIONS
SELECT TOOLCODE,SUM(REJECTQTY) REJECTEDQTY
INTO #REJECTEDQTY
FROM BT.BUDGETMATERIALMOVEMENTDETAIL  WHERE  PROJECTCODE=@PROJECTCODE 
GROUP BY TOOLCODE

SELECT TOOLCODE,SUM(REJECTQTY*PRRATE ) REJECTEDAMOUNT
INTO #REJECTEDAMOUNT 
FROM BT.BUDGETMATERIALMOVEMENTDETAIL  WHERE  PROJECTCODE=@PROJECTCODE 
GROUP BY TOOLCODE

UPDATE #TOOLCODE 
SET   REJECTED = R.REJECTEDQTY FROM #REJECTEDQTY  R 
INNER JOIN #TOOLCODE ON #TOOLCODE.TOOLCODE = R.TOOLCODE WHERE #TOOLCODE.CATEGORY='Q'

UPDATE #TOOLCODE 
SET   REJECTED = R.REJECTEDAMOUNT  FROM #REJECTEDAMOUNT   R 
INNER JOIN #TOOLCODE ON #TOOLCODE.TOOLCODE = R.TOOLCODE WHERE #TOOLCODE.CATEGORY='L'



--- ORDERD 
SELECT TOOLCODE,SUM(ORDQTY) ORDEREDQTY
INTO #ORDEREDQTY
FROM BT.BUDGETMATERIALMOVEMENTDETAIL  WHERE ORDSTATUS IN (41,274)  AND PROJECTCODE=@PROJECTCODE 
GROUP BY TOOLCODE

SELECT TOOLCODE,SUM(ORDAMOUNT) ORDERAMOUNT
INTO #ORDEREDAMOUNT
FROM BT.BUDGETMATERIALMOVEMENTDETAIL  WHERE ORDSTATUS=274  AND PROJECTCODE=@PROJECTCODE 
GROUP BY TOOLCODE

UPDATE #TOOLCODE 
SET   ORDERED = O.ORDEREDQTY FROM #ORDEREDQTY  O
INNER JOIN #TOOLCODE ON #TOOLCODE.TOOLCODE = O.TOOLCODE WHERE #TOOLCODE.CATEGORY='Q'

UPDATE #TOOLCODE 
SET   ORDERED = O.ORDERAMOUNT FROM #ORDEREDAMOUNT  O
INNER JOIN #TOOLCODE ON #TOOLCODE.TOOLCODE = O.TOOLCODE WHERE #TOOLCODE.CATEGORY='L'


---DELIVERY 
SELECT TOOLCODE,SUM(DELIVEREDQTY) DELIVEREDQTY
INTO #DELIVEREDQTY
FROM BT.BUDGETMATERIALMOVEMENTDETAIL  WHERE  PROJECTCODE=@PROJECTCODE 
GROUP BY TOOLCODE

SELECT TOOLCODE,SUM(DELIVERYAMOUNT) DELIVEREDAMOUNT
INTO #DELIVEREDAMOUNT
FROM BT.BUDGETMATERIALMOVEMENTDETAIL  WHERE  PROJECTCODE=@PROJECTCODE 
GROUP BY TOOLCODE

UPDATE #TOOLCODE 
SET   DELIVERED = D.DELIVEREDQTY FROM #DELIVEREDQTY  D
INNER JOIN #TOOLCODE ON #TOOLCODE.TOOLCODE = D.TOOLCODE WHERE #TOOLCODE.CATEGORY='Q'

UPDATE #TOOLCODE 
SET   DELIVERED = D.DELIVEREDAMOUNT FROM #DELIVEREDAMOUNT  D
INNER JOIN #TOOLCODE ON #TOOLCODE.TOOLCODE = D.TOOLCODE WHERE #TOOLCODE.CATEGORY='L'



--- COMPLETED
-- COMPLETED 
SELECT TOOLCODE,SUM(BUDGETORDCOMPDIFF) COMPLETED 
INTO #COMPLETED
FROM BT.BUDGETMATERIALMOVEMENTDETAIL  WHERE  PROJECTCODE=@PROJECTCODE 
GROUP BY TOOLCODE

UPDATE #TOOLCODE 
SET   COMPLETED =-1.0*C.COMPLETED FROM #COMPLETED C
INNER JOIN #TOOLCODE ON #TOOLCODE.TOOLCODE = C.TOOLCODE 







DECLARE DETAILS CURSOR FOR SELECT TOOLCODEID,TOOLCODE FROM #TOOLCODE  
OPEN DETAILS 
FETCH NEXT FROM DETAILS INTO @TOOLCODEID,@TOOLCODE 
WHILE @@FETCH_STATUS = 0 
BEGIN
  INSERT INTO #DETAIL(TOOLCODEID, REQID,REQNUMBER,REQDATE,LINENUMBER,STOCKCODE,STOCKNAME,CONVERTIONFACTOR,PRUOM,PRQTY,PRRATE,PRAMOUNT,CANCELLED,REJECTED,
  ORDID,ORDNUMBER,ORDDATE,ORDQTY,ORDRATE,ORDAMOUNT,DELIVEREDQTY,COMPLETED,OPENPR  ) 
  SELECT              @TOOLCODEID,REQID,REQNUMBER,REQDATE,LINENUMBER,STOCKCODE,STOCKNAME,CONVERTIONFACTOR,PRUOM,PRQTY,PRRATE,PRAMOUNT,CANCELLEDQTY,REJECTQTY,
  ORDID,ORDNUMBER,ORDDATE,ORDQTY,ORDRATE,ORDAMOUNT,DELIVEREDQTY,BUDGETORDCOMPDIFF,OPENPR 
  FROM   BT.BUDGETMATERIALMOVEMENTDETAIL WHERE TOOLCODE=@TOOLCODE AND PROJECTCODE=@PROJECTCODE 
  FETCH NEXT FROM DETAILS INTO @TOOLCODEID,@TOOLCODE 
END
CLOSE DETAILS
DEALLOCATE DETAILS 


SELECT TOOLCODE,CUMULATIVEQTY BALANCEQTY
INTO #BALANCEQTY
FROM BT.MonthlyMaterialBudget WHERE PROJECTCODE=@PROJECTCODE 
ORDER BY TOOLCODE 

UPDATE #TOOLCODE SET BALANCEFORPURCHASE = BALANCEQTY FROM #BALANCEQTY INNER JOIN #TOOLCODE ON #TOOLCODE.TOOLCODE=#BALANCEQTY.TOOLCODE 

UPDATE #TOOLCODE SET CATEGORY='Amount Based' WHERE CATEGORY<>'Q'
UPDATE #TOOLCODE SET CATEGORY='Quantity Based'  WHERE CATEGORY='Q'
UPDATE #TOOLCODE SET REJECTED=0  WHERE REJECTED IS NULL
UPDATE #TOOLCODE SET DELIVERED=0 WHERE DELIVERED IS NULL
UPDATE #TOOLCODE SET COMPLETED=0 WHERE COMPLETED IS NULL
UPDATE #TOOLCODE SET ORDERED=0   WHERE ORDERED IS NULL
UPDATE #DETAIL   SET ORDQTY =0   WHERE ORDQTY IS NULL
UPDATE #DETAIL   SET ORDRATE=0   WHERE ORDRATE IS NULL
UPDATE #DETAIL   SET ORDAMOUNT=0   WHERE ORDAMOUNT IS NULL
UPDATE #DETAIL   SET DELIVEREDQTY=0 WHERE DELIVEREDQTY IS NULL
UPDATE #DETAIL   SET COMPLETED = 0 WHERE COMPLETED IS NULL
UPDATE #DETAIL   SET ORDNUMBER='' WHERE ORDNUMBER IS NULL
 

SELECT * FROM #TOOLCODE ORDER BY CATEGORY,TOOLCODE
SELECT TOOLCODEID,STOCKCODE,STOCKNAME,CONVERTIONFACTOR,PRUOM,PRQTY,PRRATE,PRAMOUNT,REQNUMBER,REQDATE,OPENPR,CANCELLED,REJECTED,ORDQTY,ORDRATE,ORDAMOUNT,ORDNUMBER,ORDDATE,DELIVEREDQTY,COMPLETED FROM #DETAIL 