/****** Object:  Procedure [BT].[spBudgetVsActual]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE [BT].[spBudgetVsActual](@PROJECTCODE INT,@TOPERIOD INT)
AS

DECLARE @FINYEAR INT 
DECLARE @ENDPERIOD INT 
DECLARE @BORGID INT 
 
SELECT @BORGID = BORGID FROM BT.PROJECTS WHERE PROJECTID=@PROJECTCODE 
SELECT @FINYEAR=FINYEAR , @ENDPERIOD=PERIOD FROM BT.YEARPERIODMASTER WHERE YEARPERIODID = @TOPERIOD 


-- GET ALL THE TRANSACTIONS FROM INCEPTION  
SELECT YEAR,PERIOD,LEDGERCODE,DEBIT,CREDIT
INTO #TRANSACTIONS
FROM TRANSACTIONS 
WHERE  ORGID=@BORGID AND ALLOCATION='Contracts' AND PERIOD<>0 AND YEAR = @FINYEAR 

-- DELETE FUTURE PERIOD TRANSACTIONS 
DELETE FROM #TRANSACTIONS WHERE YEAR=@FINYEAR AND PERIOD>@ENDPERIOD 
 

-- TILL INCEPTION 
SELECT LEDGERCODE,SUM(DEBIT-CREDIT) AMOUNT 
INTO #TILLINCEPTION
FROM #TRANSACTIONS 
GROUP BY LEDGERCODE
 





-- MAKE SIGN CHANGE FOR REVENUE 
UPDATE #TILLINCEPTION SET AMOUNT = -1.0*AMOUNT WHERE LEFT(LEDGERCODE,1)='4' 

ALTER TABLE #TILLINCEPTION ADD REPORTCODE VARCHAR(25)
UPDATE #TILLINCEPTION SET REPORTCODE = LM.REPORTCODE FROM BT.LEDGERMAPPING LM INNER JOIN #TILLINCEPTION ON LM.LEDGERCODE=#TILLINCEPTION.LEDGERCODE 
DELETE FROM #TILLINCEPTION WHERE REPORTCODE=''
DELETE FROM #TILLINCEPTION WHERE LEDGERCODE=''
 

SELECT REPORTCODE,SUM(AMOUNT) REPORTCODESUM 
INTO #REPORTCODESUMTILLINCEPTION
FROM #TILLINCEPTION
GROUP BY REPORTCODE 




-- ACTUAL TO THE CURRENT PERIOD 
SELECT LEDGERCODE,SUM(DEBIT-CREDIT) AMOUNT 
INTO #ACTUALSTHISPERIOD
FROM #TRANSACTIONS WHERE PERIOD=@ENDPERIOD
GROUP BY LEDGERCODE 

-- MAKE SIGN CHANGE FOR REVENUE 
UPDATE #ACTUALSTHISPERIOD SET AMOUNT = -1.0*AMOUNT WHERE LEFT(LEDGERCODE,1)='4' 

ALTER TABLE #ACTUALSTHISPERIOD ADD REPORTCODE VARCHAR(15)
UPDATE #ACTUALSTHISPERIOD SET REPORTCODE = LM.REPORTCODE FROM BT.LEDGERMAPPING LM INNER JOIN #ACTUALSTHISPERIOD ON LM.LEDGERCODE=#ACTUALSTHISPERIOD.LEDGERCODE  


SELECT REPORTCODE,SUM(AMOUNT) REPORTCODESUM 
INTO #REPORTCODESUM
FROM #ACTUALSTHISPERIOD
GROUP BY REPORTCODE 
 


-- FINAL IS THE TABLE FOR PRESENATION 
SELECT LEVELCODE,SECTION,HEADERCODE,SPACE(SPACECODE)+DESCRIPTION AS BUDGETHEAD,FORMULA
INTO #FINAL 
FROM BT.CTCREPORT 

ALTER TABLE #FINAL ADD PERIODACTUAL DECIMAL(18,2) 
UPDATE #FINAL SET PERIODACTUAL=0
UPDATE #FINAL SET PERIODACTUAL = RS.REPORTCODESUM FROM #REPORTCODESUM RS  INNER JOIN #FINAL ON #FINAL.LEVELCODE=RS.REPORTCODE 
 

ALTER TABLE #FINAL ADD PERIODBUDGET DECIMAL(18,2) 
UPDATE #FINAL SET PERIODBUDGET = 0.0

SELECT BUDGETCODE,SUM(PERIODBUDGET) PERIODBUDGET 
INTO #PERIODBUDGET
FROM BT.MASTERBUDGETSPREAD 
WHERE PROJECTCODE=@PROJECTCODE AND YEARPERIODCODE  =@TOPERIOD
GROUP BY BUDGETCODE 

UPDATE #FINAL SET PERIODBUDGET = PB.PERIODBUDGET 
FROM #PERIODBUDGET PB
INNER JOIN #FINAL ON #FINAL.LEVELCODE  = PB.BUDGETCODE 

--- TILL INCEPTION ACTUAL AND BUDGET 


ALTER TABLE #FINAL ADD TILLINCEPTIONACTUAL DECIMAL(18,2) 
UPDATE #FINAL SET TILLINCEPTIONACTUAL = 0.0
UPDATE #FINAL SET TILLINCEPTIONACTUAL = RS.REPORTCODESUM FROM #REPORTCODESUMTILLINCEPTION RS  INNER JOIN #FINAL ON #FINAL.LEVELCODE=RS.REPORTCODE 

 
SELECT BUDGETCODE,SUM(PERIODBUDGET) TILLINCEPTIONBUDGET
INTO #TILLINCEPTIONBUDGET
FROM BT.MASTERBUDGETSPREAD 
WHERE PROJECTCODE=@PROJECTCODE AND YEARPERIODCODE  <=@TOPERIOD
GROUP BY BUDGETCODE 


ALTER TABLE #FINAL ADD TILLINCEPTIONBUDGET DECIMAL(18,2) 
UPDATE #FINAL SET TILLINCEPTIONBUDGET = 0.0

UPDATE #FINAL SET TILLINCEPTIONBUDGET = PB.TILLINCEPTIONBUDGET
FROM #TILLINCEPTIONBUDGET PB
INNER JOIN #FINAL ON #FINAL.LEVELCODE  = PB.BUDGETCODE

 

DECLARE @SQL1 VARCHAR(500)
DECLARE @SQL2 VARCHAR(500)
DECLARE @SQL3 VARCHAR(500)
DECLARE @SQL4 VARCHAR(500)
DECLARE @FORMULA VARCHAR(500)
DECLARE @SUMMARYLEVELCODE VARCHAR(25)
 
 
DECLARE COMPUTELOGIC  CURSOR FOR SELECT LEVELCODE,FORMULA FROM BT.CTCREPORT  WHERE PARENTID=-1
OPEN COMPUTELOGIC 
FETCH NEXT FROM COMPUTELOGIC INTO @SUMMARYLEVELCODE,@FORMULA
WHILE @@FETCH_STATUS = 0 
BEGIN 
  SET @SQL1 = 'DECLARE @TOTALAMOUNTA DECIMAL(18,2);SELECT @TOTALAMOUNTA =  SUM(PERIODACTUAL) FROM #FINAL WHERE LEVELCODE IN '+@FORMULA +
           ';UPDATE #FINAL SET PERIODACTUAL=@TOTALAMOUNTA WHERE LEVELCODE='+CHAR(39)+@SUMMARYLEVELCODE+CHAR(39) 
  EXEC (@SQL1) 
  SET @SQL2 = 'DECLARE @TOTALAMOUNTB DECIMAL(18,2);SELECT @TOTALAMOUNTB =  SUM(PERIODBUDGET) FROM #FINAL WHERE LEVELCODE IN '+@FORMULA +
           ';UPDATE #FINAL SET PERIODBUDGET=@TOTALAMOUNTB WHERE LEVELCODE='+CHAR(39)+@SUMMARYLEVELCODE+CHAR(39) 
  EXEC (@SQL2) 
  SET @SQL3 = 'DECLARE @TOTALAMOUNTC DECIMAL(18,2);SELECT @TOTALAMOUNTC =  SUM(TILLINCEPTIONACTUAL) FROM #FINAL WHERE LEVELCODE IN '+@FORMULA +
           ';UPDATE #FINAL SET TILLINCEPTIONACTUAL=@TOTALAMOUNTC WHERE LEVELCODE='+CHAR(39)+@SUMMARYLEVELCODE+CHAR(39) 
  EXEC (@SQL3)
  SET @SQL4 = 'DECLARE @TOTALAMOUNTD DECIMAL(18,2);SELECT @TOTALAMOUNTD =  SUM(TILLINCEPTIONBUDGET) FROM #FINAL WHERE LEVELCODE IN '+@FORMULA +
           ';UPDATE #FINAL SET TILLINCEPTIONBUDGET=@TOTALAMOUNTD WHERE LEVELCODE='+CHAR(39)+@SUMMARYLEVELCODE+CHAR(39) 
  EXEC (@SQL4)



  FETCH NEXT FROM COMPUTELOGIC INTO @SUMMARYLEVELCODE,@FORMULA
END 
CLOSE COMPUTELOGIC
DEALLOCATE COMPUTELOGIC





/*  300000000	III		300000000	H1	2	SITE MARGIN (I - II)	-2	(100000999,209999999)  */

DECLARE @DIFFERENCE DECIMAL(18,2)
DECLARE @SECTIONA DECIMAL(18,2)
DECLARE @SECTIONB DECIMAL(18,2)
SELECT @SECTIONA = PERIODACTUAL FROM #FINAL WHERE LEVELCODE = '100000999'
SELECT @SECTIONB = PERIODACTUAL FROM #FINAL WHERE LEVELCODE = '209999999'
SET @DIFFERENCE  = @SECTIONA - @SECTIONB 
UPDATE #FINAL SET  PERIODACTUAL = @DIFFERENCE   WHERE LEVELCODE ='300000000'
SET @SECTIONA = 0 
SET @SECTIONB = 0 
SELECT @SECTIONA = PERIODBUDGET FROM #FINAL WHERE LEVELCODE = '100000999'
SELECT @SECTIONB = PERIODBUDGET FROM #FINAL WHERE LEVELCODE = '209999999'
SET @DIFFERENCE  = @SECTIONA - @SECTIONB 
UPDATE #FINAL SET  PERIODBUDGET = @DIFFERENCE   WHERE LEVELCODE ='300000000' 
SET @SECTIONA = 0 
SET @SECTIONB = 0 
SELECT @SECTIONA = TILLINCEPTIONACTUAL FROM #FINAL WHERE LEVELCODE = '100000999'
SELECT @SECTIONB = TILLINCEPTIONACTUAL FROM #FINAL WHERE LEVELCODE = '209999999'
SET @DIFFERENCE  = @SECTIONA - @SECTIONB 
UPDATE #FINAL SET  TILLINCEPTIONACTUAL = @DIFFERENCE   WHERE LEVELCODE ='300000000' 
SET @SECTIONA = 0 
SET @SECTIONB = 0 
SELECT @SECTIONA = TILLINCEPTIONBUDGET FROM #FINAL WHERE LEVELCODE = '100000999'
SELECT @SECTIONB = TILLINCEPTIONBUDGET FROM #FINAL WHERE LEVELCODE = '209999999'
SET @DIFFERENCE  = @SECTIONA - @SECTIONB 
UPDATE #FINAL SET  TILLINCEPTIONBUDGET = @DIFFERENCE   WHERE LEVELCODE ='300000000' 


/*  50000000	V		50000000	H1	2	PROFIT BEFORE TAX (III - IV)	-3	(300000000-400000199)  */

SELECT @SECTIONA = PERIODACTUAL FROM #FINAL WHERE LEVELCODE = '300000000'
SELECT @SECTIONB = PERIODACTUAL FROM #FINAL WHERE LEVELCODE = '400000199'
SET @DIFFERENCE  = @SECTIONA - @SECTIONB 
UPDATE #FINAL SET  PERIODACTUAL = @DIFFERENCE   WHERE LEVELCODE ='50000000' 
SET @SECTIONA = 0 
SET @SECTIONB = 0 
SELECT @SECTIONA = PERIODBUDGET FROM #FINAL WHERE LEVELCODE = '300000000'
SELECT @SECTIONB = PERIODBUDGET FROM #FINAL WHERE LEVELCODE = '400000199'
SET @DIFFERENCE  = @SECTIONA - @SECTIONB 
UPDATE #FINAL SET  PERIODBUDGET = @DIFFERENCE   WHERE LEVELCODE ='50000000' 
SET @SECTIONA = 0 
SET @SECTIONB = 0 
SELECT @SECTIONA = TILLINCEPTIONACTUAL FROM #FINAL WHERE LEVELCODE = '300000000'
SELECT @SECTIONB = TILLINCEPTIONACTUAL FROM #FINAL WHERE LEVELCODE = '400000199'
SET @DIFFERENCE  = @SECTIONA - @SECTIONB 
UPDATE #FINAL SET  TILLINCEPTIONACTUAL = @DIFFERENCE   WHERE LEVELCODE ='50000000' 
SET @SECTIONA = 0 
SET @SECTIONB = 0 
SELECT @SECTIONA = TILLINCEPTIONBUDGET FROM #FINAL WHERE LEVELCODE = '300000000'
SELECT @SECTIONB = TILLINCEPTIONBUDGET FROM #FINAL WHERE LEVELCODE = '400000199'
SET @DIFFERENCE  = @SECTIONA - @SECTIONB 
UPDATE #FINAL SET  TILLINCEPTIONBUDGET = @DIFFERENCE   WHERE LEVELCODE ='50000000' 

UPDATE #FINAL SET TILLINCEPTIONACTUAL = NULL WHERE TILLINCEPTIONACTUAL=0
UPDATE #FINAL SET TILLINCEPTIONBUDGET = NULL WHERE TILLINCEPTIONBUDGET=0
UPDATE #FINAL SET PERIODBUDGET = NULL WHERE PERIODBUDGET=0
UPDATE #FINAL SET PERIODACTUAL = NULL WHERE PERIODACTUAL=0
SELECT LEVELCODE,SECTION,BUDGETHEAD,PERIODBUDGET,PERIODACTUAL,TILLINCEPTIONBUDGET,TILLINCEPTIONACTUAL,HEADERCODE  FROM #FINAL ORDER BY LEVELCODE 
 