/****** Object:  Procedure [BT].[spBUDGETAGENTWORKORDER]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE [BT].[spBUDGETAGENTWORKORDER]
AS


UPDATE BT.BUDGETWORKORDERMOVEMENTDETAIL SET ORDQTY=0,ORDAMOUNT=0 WHERE ORDQTY IS NULL
 
UPDATE BT.BUDGETWORKORDERMOVEMENTDETAIL SET PRPOQTYDIFF=0 WHERE PRPOQTYDIFF IS NULL
 
UPDATE BT.BUDGETWORKORDERMOVEMENTDETAIL SET COMPLETED = 0 WHERE COMPLETED IS NULL
 
DELETE FROM  BT.BUDGETWORKORDERMOVEMENTDETAIL WHERE TOOLCODE IS NULL
 
UPDATE BT.BUDGETWORKORDERMOVEMENTDETAIL SET FINALIZED=0 WHERE FINALIZED IS NULL
 
UPDATE BT.BUDGETWORKORDERMOVEMENTDETAIL SET BILLEDQTY=0,BILLEDAMOUNT =0 WHERE BILLEDQTY IS NULL
UPDATE BT.BUDGETWORKORDERMOVEMENTDETAIL SET ORDBILLEDDIFF  =0 WHERE ORDBILLEDDIFF IS NULL
UPDATE BT.BUDGETWORKORDERMOVEMENTDETAIL SET CANCELLEDQTY=0 WHERE CANCELLEDQTY IS NULL
UPDATE BT.BUDGETWORKORDERMOVEMENTDETAIL SET REJECTQTY = 0 WHERE REJECTQTY IS NULL
UPDATE BT.BUDGETWORKORDERMOVEMENTDETAIL SET ORDQTY = 0 WHERE ORDQTY IS NULL
UPDATE BT.BUDGETWORKORDERMOVEMENTDETAIL SET ORDAMOUNT=0 WHERE ORDAMOUNT IS NULL

 
DECLARE @REQID INT
DECLARE @DETAILID INT
DECLARE @PRQTY DECIMAL(18,4)
DECLARE @HEADERID INT 
DECLARE @CATEGORY VARCHAR(15) 
DECLARE @PRRATE DECIMAL(18,4)
DECLARE @PRAMOUNT DECIMAL(18,4) 
DECLARE @PROJECTCODE INT
DECLARE @TOOLCODE VARCHAR(25) 
DECLARE @PRSTATUS INT
DECLARE @LINENUMBER INT
DECLARE @LINEITEMEXISTING INT

DECLARE @CANCELLED DECIMAL(18,4) 
DECLARE @CANCELPRECONVERTION DECIMAL(18,4)

DECLARE @DELIVERYQTY DECIMAL(18,4) 
DECLARE @DIFFDEIVERYORDQTY DECIMAL(18,4) 
DECLARE @DELIVERYAMOUNT DECIMAL(18,4) 
DECLARE @WWWITEMCODE INT
DECLARE @ORDDELIVERYDIFF DECIMAL(18,4) 

DECLARE @BSBORGID INT
DECLARE @CURRNETBUDGETQTY DECIMAL(18,4)
DECLARE @CURRENTBUDGETAMOUNT DECIMAL(18,4) 
DECLARE @CURRENTCATEGORYTYPE VARCHAR(1)

--- CHECK WHETHER LINEITEMS IN THE DETAIL TABLE AND REQITEMS ARE MATCHING. IF USER REMOVE THE ITEMS FROM REQITEMS THIS MUST BE REMOVED FROM DETAIL TABLE
DECLARE LINEITEMS CURSOR FOR SELECT REQID,LINENUMBER FROM BT.BUDGETWORKORDERMOVEMENTDETAIL WHERE FINALIZED=0 
OPEN LINEITEMS 
FETCH NEXT FROM LINEITEMS INTO @REQID,@LINENUMBER 
WHILE @@FETCH_STATUS  = 0
BEGIN
  SELECT @LINEITEMEXISTING = ISNULL(COUNT(*),0) FROM REQITEMS WHERE REQID=@REQID AND LINENUMBER=@LINENUMBER 
  IF @LINEITEMEXISTING=0 
     BEGIN
	  UPDATE BT.BUDGETWORKORDERMOVEMENTDETAIL SET CANCELLEDQTY = PRQTY,PRSTATUS=99,FINALIZED=2    WHERE  REQID=@REQID AND LINENUMBER=@LINENUMBER 

      SELECT @CANCELLED=CANCELLEDQTY ,@WWWITEMCODE=WWWITEMCODE 
	  FROM BT.BUDGETWORKORDERMOVEMENTDETAIL WHERE REQID=@REQID AND LINENUMBER=@LINENUMBER
      UPDATE BT.WEBWORKORDERITEMS 
			 SET ORDEREDQTY = ORDEREDQTY - @CANCELLED, ORDEREDAMOUNT = ORDEREDAMOUNT - (@CANCELLED * RATE)   WHERE WWWITEMCODE = @WWWITEMCODE 
	  UPDATE BT.WEBWORKORDERITEMS SET TOTALBALANCEQTY = TOTALQTY - ORDEREDQTY WHERE WWWITEMCODE = @WWWITEMCODE
  
	  UPDATE BT.BUDGETWORKORDERMOVEMENTDETAIL SET CANCELLEDQTY=-1.0* CANCELLEDQTY  , FINALIZED=1  WHERE  WWWITEMCODE = @WWWITEMCODE
	 END 
  FETCH NEXT FROM LINEITEMS INTO @REQID,@LINENUMBER 
END
CLOSE LINEITEMS
DEALLOCATE LINEITEMS 





-- GET OPEN PRS FROM REQS AND CHECK THE CURRENT STATUS 
SELECT DETAILID,REQID,LINENUMBER,PRSTATUS 
INTO  #TEMP0 
FROM  BT.BUDGETWORKORDERMOVEMENTDETAIL
WHERE PRSTATUS=163 AND FINALIZED=0

ALTER TABLE #TEMP0 ADD NEWSTATUS INT
UPDATE #TEMP0 SET NEWSTATUS=REQ.REQSTATUSID FROM REQ INNER JOIN #TEMP0 ON #TEMP0.REQID=REQ.REQID 

UPDATE BT.BUDGETWORKORDERMOVEMENTDETAIL SET OPENPR = PRQTY  WHERE  DETAILID IN (SELECT DETAILID FROM #TEMP0 WHERE NEWSTATUS=163) 

DELETE FROM #TEMP0 WHERE NEWSTATUS=163

 
UPDATE BT.BUDGETWORKORDERMOVEMENTDETAIL
SET PRSTATUS=T.NEWSTATUS,OPENPR=0  FROM #TEMP0 T INNER JOIN BT.BUDGETWORKORDERMOVEMENTDETAIL ON BT.BUDGETWORKORDERMOVEMENTDETAIL.DETAILID=T.DETAILID 



-- CANCELLED PRS
UPDATE BT.BUDGETWORKORDERMOVEMENTDETAIL SET CANCELLEDQTY=0 WHERE CANCELLEDQTY IS NULL
UPDATE BT.BUDGETWORKORDERMOVEMENTDETAIL SET CANCELLEDQTY = PRQTY    WHERE PRSTATUS=36 AND FINALIZED=0  
 

DECLARE CANCELLED CURSOR FOR SELECT DETAILID,REQID,LINENUMBER  FROM #TEMP0 WHERE NEWSTATUS=36 
OPEN CANCELLED 
FETCH NEXT FROM CANCELLED INTO @DETAILID,@REQID,@LINENUMBER 
WHILE @@FETCH_STATUS=0
BEGIN
    SELECT  @WWWITEMCODE         = WWWITEMCODE,
	     	@CANCELLED           = PRQTY 
	FROM BT.BUDGETWORKORDERMOVEMENTDETAIL
	WHERE DETAILID=@DETAILID 
	
	UPDATE BT.WEBWORKORDERITEMS 
			 SET ORDEREDQTY = ORDEREDQTY - @CANCELLED, ORDEREDAMOUNT = ORDEREDAMOUNT - (@CANCELLED * RATE)   WHERE WWWITEMCODE = @WWWITEMCODE 

	UPDATE BT.WEBWORKORDERITEMS SET TOTALBALANCEQTY = TOTALQTY - ORDEREDQTY WHERE WWWITEMCODE = @WWWITEMCODE
  
	UPDATE BT.BUDGETWORKORDERMOVEMENTDETAIL SET CANCELLEDQTY= -1.0 * CANCELLEDQTY    WHERE  WWWITEMCODE = @WWWITEMCODE

	
	FETCH NEXT FROM CANCELLED INTO @DETAILID,@REQID,@LINENUMBER 
END
CLOSE CANCELLED 
DEALLOCATE CANCELLED 
 
 
--- REJECTED
DECLARE @REJECTED DECIMAL(18,4)
DECLARE @REJECTPRECONVERTION DECIMAL(18,4) 
SELECT DETAILID,REQID,LINENUMBER,PRSTATUS 
INTO #TEMPR 
FROM  BT.BUDGETWORKORDERMOVEMENTDETAIL
WHERE PRSTATUS IN (32,163,202)  AND FINALIZED=0
 

ALTER TABLE #TEMPR ADD NEWSTATUS INT
UPDATE #TEMPR SET NEWSTATUS=REQ.REQSTATUSID FROM REQ INNER JOIN #TEMPR ON #TEMPR.REQID=REQ.REQID 
 
DELETE FROM #TEMPR WHERE NEWSTATUS=32

UPDATE BT.BUDGETWORKORDERMOVEMENTDETAIL
SET PRSTATUS=T.NEWSTATUS FROM #TEMPR T INNER JOIN BT.BUDGETWORKORDERMOVEMENTDETAIL ON BT.BUDGETWORKORDERMOVEMENTDETAIL.DETAILID=T.DETAILID 
UPDATE BT.BUDGETWORKORDERMOVEMENTDETAIL SET REJECTQTY=0 WHERE REJECTQTY IS NULL

UPDATE BT.BUDGETWORKORDERMOVEMENTDETAIL SET REJECTQTY = PRQTY    WHERE PRSTATUS=202  AND FINALIZED=0   
 
 

DECLARE REJECTED CURSOR FOR SELECT DETAILID,REQID,LINENUMBER  FROM #TEMPR WHERE NEWSTATUS=202
OPEN REJECTED 
FETCH NEXT FROM REJECTED INTO @DETAILID,@REQID,@LINENUMBER 
WHILE @@FETCH_STATUS=0
BEGIN
    UPDATE REQ SET REQSTATUSID=36 WHERE REQSTATUSID=202 AND REQID=@REQID
    SELECT  @WWWITEMCODE           = WWWITEMCODE,
	        @REJECTED              = REJECTQTY 
	FROM BT.BUDGETWORKORDERMOVEMENTDETAIL
	WHERE DETAILID=@DETAILID 

	UPDATE BT.WEBWORKORDERITEMS 
			 SET ORDEREDQTY = ORDEREDQTY - @REJECTED, ORDEREDAMOUNT = ORDEREDAMOUNT - (@REJECTED * RATE)   WHERE WWWITEMCODE = @WWWITEMCODE 
	UPDATE BT.WEBWORKORDERITEMS SET TOTALBALANCEQTY = TOTALQTY - ORDEREDQTY WHERE WWWITEMCODE = @WWWITEMCODE
  
	UPDATE BT.BUDGETWORKORDERMOVEMENTDETAIL SET REJECTQTY= -1.0* REJECTQTY    WHERE  WWWITEMCODE = @WWWITEMCODE

 
 FETCH NEXT FROM REJECTED INTO @DETAILID,@REQID,@LINENUMBER 
END
CLOSE REJECTED 
DEALLOCATE REJECTED 


--- PR CONVERTED TO PO ; NOW CHECK THE PO QTY OR PO AMOUNT AND DO NEEDFUL BUDGET CORRECTIONS

DECLARE @ORDID INT
DECLARE @ORDNUMBER VARCHAR(25)
DECLARE @ORDDATE DATETIME
DECLARE @ORDQTY DECIMAL(18,4)
DECLARE @ORDRATE DECIMAL(18,4)
DECLARE @ORDAMOUNT DECIMAL(18,4) 
DECLARE @DIFFPRPOQTY DECIMAL(18,4)

SELECT DETAILID,REQID,LINENUMBER,PRSTATUS 
INTO #TEMPO 
FROM   BT.BUDGETWORKORDERMOVEMENTDETAIL
WHERE   FINALIZED=0
ALTER TABLE #TEMPO ADD NEWSTATUS INT
UPDATE #TEMPO SET NEWSTATUS=REQ.REQSTATUSID FROM REQ INNER JOIN #TEMPO ON #TEMPO.REQID=REQ.REQID 
DELETE FROM #TEMPO WHERE NEWSTATUS<>173
 
UPDATE BT.BUDGETWORKORDERMOVEMENTDETAIL
SET PRSTATUS=T.NEWSTATUS FROM #TEMPO T INNER JOIN BT.BUDGETWORKORDERMOVEMENTDETAIL ON BT.BUDGETWORKORDERMOVEMENTDETAIL.DETAILID=T.DETAILID 


DECLARE @ORDERNUMBERS INT
DECLARE @CURRENTPRQTY DECIMAL(18,4)
DECLARE @CURRENTREQID INT 

DECLARE ORDERED CURSOR FOR SELECT DETAILID,REQID,LINENUMBER  FROM #TEMPO  
OPEN ORDERED 
FETCH NEXT FROM ORDERED INTO @DETAILID,@REQID,@LINENUMBER 
WHILE @@FETCH_STATUS=0
BEGIN
    
	SELECT  @WWWITEMCODE = WWWITEMCODE,
	        @REJECTED    = PRQTY
	FROM BT.BUDGETWORKORDERMOVEMENTDETAIL
	WHERE DETAILID=@DETAILID 

	UPDATE BT.BUDGETWORKORDERMOVEMENTDETAIL SET ORDID=0,ORDNUMBER='',ORDQTY=0,ORDRATE=0,ORDAMOUNT=0,PRPOQTYDIFF=0 WHERE DETAILID=@DETAILID AND LINENUMBER=@LINENUMBER

	SELECT ORDID INTO #ORDERLISTS FROM ORD WHERE REQID=@REQID 

	DECLARE ORDERSLIST CURSOR FOR SELECT ORDID FROM #ORDERLISTS
	OPEN ORDERSLIST
	FETCH NEXT FROM ORDERSLIST INTO @ORDERNUMBERS
	WHILE @@FETCH_STATUS=0 
	BEGIN 

	   SELECT @ORDID=ORDID,@ORDNUMBER=ORDNUMBER,@ORDDATE=CREATEDATE,@CURRENTREQID=REQID  FROM ORD    WHERE ORDID = @ORDERNUMBERS
	
	   SET @ORDQTY=0
	   SET @ORDRATE=0
	   SET @ORDAMOUNT=0

       SELECT @ORDQTY=QTY,@ORDRATE=PRICE,@ORDAMOUNT=QTY*PRICE       FROM ORDITEMS WHERE ORDID=@ORDERNUMBERS AND LINENUMBER=@LINENUMBER 
	   SELECT @CURRENTPRQTY = QTY FROM REQITEMS WHERE REQID=@CURRENTREQID AND LINENUMBER=@LINENUMBER 
	   UPDATE BT.BUDGETWORKORDERMOVEMENTDETAIL SET PRQTY = @CURRENTPRQTY  WHERE REQID=@CURRENTREQID AND LINENUMBER = @LINENUMBER 
	   -- CROSS CHECK - BEFFORE PO THE QTY GOT CHANGED

	   IF @ORDQTY >0 
	   BEGIN
	     UPDATE BT.BUDGETWORKORDERMOVEMENTDETAIL SET
			 ORDID=@ORDID,ORDNUMBER=@ORDNUMBER,ORDDATE=@ORDDATE,ORDQTY=@ORDQTY,ORDRATE=@ORDRATE,ORDAMOUNT=@ORDAMOUNT,ORDSTATUS=274 
			 WHERE DETAILID=@DETAILID   AND LINENUMBER=@LINENUMBER 
	   END
	 
    FETCH NEXT FROM ORDERSLIST INTO @ORDERNUMBERS 
   END
   CLOSE ORDERSLIST 
   DEALLOCATE ORDERSLIST
   DROP TABLE #ORDERLISTS
  FETCH NEXT FROM ORDERED INTO @DETAILID,@REQID,@LINENUMBER 
END
CLOSE ORDERED 
DEALLOCATE ORDERED 


--DECLARE @RECONDETAILID INT
--DECLARE @RECONHEADERID INT
--DECLARE @BOOKINGDETAILID INT 
---- RECONID 
--UPDATE BT.BUDGETWORKORDERMOVEMENTDETAIL
--SET RECONID=SC.RECONID 
--FROM SUBCRECONS SC 
--INNER JOIN BT.BUDGETWORKORDERMOVEMENTDETAIL  BTB ON BTB.ORDNUMBER = SC.Orderno WHERE BTB.RECONID IS NULL

--CREATE TABLE #RECONS(RECONKEY INT PRIMARY KEY IDENTITY(1,1),DETAILID INT,ORDID INT,LINENUMBER INT,RECONID INT,HEADERID INT,BOOKINGDETAILID INT)
--CREATE TABLE #BOOKINGDETAILS(BOOKINGDETAILSKEY INT PRIMARY KEY IDENTITY(1,1),BOOKINGDETAILID INT) 

--INSERT INTO #RECONS 
--SELECT DETAILID,ORDID,LINENUMBER,RECONID ,0,0
--FROM BT.BUDGETWORKORDERMOVEMENTDETAIL 
--WHERE  RECONID IS not null ORDER BY  RECONID,ORDID,LINENUMBER

--UPDATE #RECONS SET HEADERID = AH.HeaderId FROM ACCBOQHEADER AH INNER JOIN #RECONS ON #RECONS.RECONID = AH.ReconID 

--DECLARE RECONS CURSOR FOR  SELECT DISTINCT  HEADERID FROM #RECONS 
--OPEN RECONS 
--FETCH NEXT FROM RECONS INTO @RECONHEADERID 
--WHILE @@FETCH_STATUS = 0 
--BEGIN
--    SELECT @RECONHEADERID
--	DELETE FROM #BOOKINGDETAILS
--	INSERT INTO #BOOKINGDETAILS
--    SELECT DETAILID  
--	FROM ACCBOQDETAIL WHERE HEADERID=@RECONHEADERID AND RECONHISTID=-1 AND cast([UNIT] as nvarchar(max)) <>'H1' ORDER BY DETAILID 

--    UPDATE #RECONS SET   BOOKINGDETAILID = BD.BOOKINGDETAILID FROM #BOOKINGDETAILS BD INNER JOIN #RECONS R  ON R.RECONKEY = BD.BOOKINGDETAILSKEY

--	FETCH NEXT FROM RECONS INTO @RECONHEADERID 
	
--END
--CLOSE RECONS 
--DEALLOCATE RECONS 


--UPDATE BT.BUDGETWORKORDERMOVEMENTDETAIL
--SET BILLINGDETAILID = R.BOOKINGDETAILID
--FROM #RECONS R
--INNER JOIN BT.BUDGETWORKORDERMOVEMENTDETAIL BTD ON BTD.DETAILID = R.DETAILID 

--SELECT * FROM BT.BUDGETWORKORDERMOVEMENTDETAIL
 
 
---- -----  UPDATING THE TENDERITEMS TABLE ----
----SELECT PROJECTCODE,TOOLCODE,SUM(ORDQTY*CONVERTIONFACTOR-BUDGETORDCOMPDIFF) FINALORDERQTY,SUM(ORDAMOUNT-BUDGETORDCOMPDIFF) FINALORDERVALUE,BUYINGCATEGORY 
----INTO #FINALORDER
----FROM BT.BUDGETWORKORDERMOVEMENTDETAIL 
----GROUP BY PROJECTCODE,TOOLCODE,BUYINGCATEGORY


----ALTER TABLE #FINALORDER ADD BSBORG INT
----UPDATE #FINALORDER SET BSBORG = BORGID FROM BT.PROJECTS  BTP INNER JOIN #FINALORDER ON #FINALORDER.PROJECTCODE=BTP.ProjectID 

----UPDATE TENDERITEMS 
----SET ORDEREDQTY = F.FINALORDERQTY 
----FROM #FINALORDER F
----INNER JOIN TENDERITEMS ON TENDERITEMS.BORG=F.BSBORG  AND TENDERITEMS.RESCODE=F.TOOLCODE 
----WHERE UPPER(F.BUYINGCATEGORY)='Q'

----UPDATE TENDERITEMS 
----SET ORDEREDQTY = F.FINALORDERVALUE
----FROM #FINALORDER F
----INNER JOIN TENDERITEMS ON TENDERITEMS.BORG=F.BSBORG  AND TENDERITEMS.RESCODE=F.TOOLCODE 
----WHERE UPPER(F.BUYINGCATEGORY)='L'