/****** Object:  Procedure [BT].[spBudgetActual]    Committed by VersionSQL https://www.versionsql.com ******/

/*******   FOR   DPR  *************************/

CREATE PROCEDURE [BT].[spBudgetActual](@PROJECTCODE INT,@YEARPERIODID INT)
AS

DECLARE @REPORTPERIOD VARCHAR(50)
DECLARE @MONTH INT 
DECLARE @YEAR  INT
DECLARE @QUARTERSTARTID INT
DECLARE @QUEARTERENDID  INT
DECLARE @FULLMONTHNAME VARCHAR(45)

DECLARE @MONTHSTARTDATE DATETIME 
DECLARE @MONTHENDDATE   DATETIME

DECLARE @QUARTERSTARTDATE DATETIME 
DECLARE @QUARTERENDDATE   DATETIME

 


SELECT @YEAR=YEAR,
       @MONTH=CALENDARMONTH,
	   @MONTHSTARTDATE=STARTDATE , 
	   @MONTHENDDATE = ENDDATE,
	   @FULLMONTHNAME = MONTHFULLNAME
FROM BT.YEARPERIODMASTER
WHERE YEARPERIODID=@YEARPERIODID 
 

SET @REPORTPERIOD =LTRIM(RTRIM(STR(@YEAR)))+' - '+ LTRIM(RTRIM(@FULLMONTHNAME))

IF @MONTH BETWEEN 1 AND 3 
 BEGIN
   SET @QUARTERSTARTID = 1
   SET @QUEARTERENDID  = 3
 END
IF @MONTH BETWEEN 4 AND 6 
   BEGIN
   SET @QUARTERSTARTID = 4
   SET @QUEARTERENDID  = 6
 END
IF @MONTH BETWEEN 7 AND 9 
   BEGIN
   SET @QUARTERSTARTID = 7
   SET @QUEARTERENDID  = 9
 END
IF @MONTH BETWEEN 10 AND 12 
   BEGIN
   SET @QUARTERSTARTID = 10
   SET @QUEARTERENDID  = 12
 END

SELECT @QUARTERSTARTDATE = STARTDATE FROM BT.YEARPERIODMASTER WHERE YEARPERIODID = 
(SELECT YEARPERIODID FROM [BT].[YearPeriodMaster] WHERE [YEAR]=@YEAR AND CALENDARMONTH=@QUARTERSTARTID)
SELECT @QUARTERENDDATE = ENDDATE FROM BT.YEARPERIODMASTER WHERE YEARPERIODID = 
(SELECT YEARPERIODID FROM [BT].[YearPeriodMaster] WHERE [YEAR]=@YEAR AND CALENDARMONTH=@QUEARTERENDID)

  

DELETE FROM BT.BUDGETACTUAL
INSERT INTO BT.BUDGETACTUAL(BOQNUMBER  ,BOQ ,UOM  ,RATE   ,MONTHBUDGET ,MONTHACTUAL  , QUARTERBUDGET  , QUARTERACTUAL  ,TILLDATEBUDGET  ,TILLDATEACTUAL  )
SELECT BOQNUMBER,BOQ,UOM,RATE,0,0,0,0,0,0 FROM BT.SALES WHERE PROJECTCODE=2

--  SECTION A : TILL DATE 

SELECT  BOQNUMBER,SUM(QTY) QTY
INTO #TILLPERIODBUDGET  
FROM BT.SALESSPREAD 
WHERE PROJECTCODE=2 AND YEARPERIODCODE <=@YEARPERIODID  GROUP BY BOQNUMBER

SELECT BOQNUMBER, SUM(DPRQTY) DPRQTY  
INTO #TILLDATEACTUAL
FROM BT.DPR 
WHERE    PROJECTCODE=2
GROUP BY BOQNUMBER 

UPDATE BT.BUDGETACTUAL 
SET TILLDATEBUDGET = ISNULL(QTY,0) FROM #TILLPERIODBUDGET INNER JOIN BT.BUDGETACTUAL ON BT.BUDGETACTUAL.BOQNUMBER=#TILLPERIODBUDGET.BOQNumber
UPDATE BT.BUDGETACTUAL 
SET TILLDATEACTUAL  = ISNULL(DPRQTY,0) FROM #TILLDATEACTUAL INNER JOIN BT.BUDGETACTUAL  ON BT.BUDGETACTUAL.BOQNUMBER = #TILLDATEACTUAL.BOQNUMBER 


---- SECTION B : QUARTER 

SELECT  BOQNUMBER,SUM(QTY) QTY 
INTO #QUARTERBUDGET
FROM BT.SALESSPREAD 
WHERE PROJECTCODE=2 AND 
YEARPERIODCODE >=(SELECT YEARPERIODID FROM [BT].[YearPeriodMaster] WHERE [YEAR]=@YEAR AND CALENDARMONTH=@QUARTERSTARTID) AND
YEARPERIODCODE <=(SELECT YEARPERIODID FROM [BT].[YearPeriodMaster] WHERE [YEAR]=@YEAR AND CALENDARMONTH=@QUEARTERENDID)
GROUP BY BOQNUMBER


SELECT BOQNUMBER, SUM(DPRQTY) DPRQTY  
INTO #QUARTERACTUAL 
FROM BT.DPR 
WHERE DPRDATE BETWEEN @QUARTERSTARTDATE AND @QUARTERENDDATE AND PROJECTCODE=2
GROUP BY BOQNUMBER 

UPDATE BT.BUDGETACTUAL 
SET QUARTERBUDGET = ISNULL(QTY,0) FROM #QUARTERBUDGET INNER JOIN BT.BUDGETACTUAL ON BT.BUDGETACTUAL.BOQNUMBER=#QUARTERBUDGET.BOQNumber
UPDATE BT.BUDGETACTUAL 
SET QUARTERACTUAL  = ISNULL(DPRQTY,0) FROM #QUARTERACTUAL INNER JOIN BT.BUDGETACTUAL  ON BT.BUDGETACTUAL.BOQNUMBER = #QUARTERACTUAL.BOQNUMBER 


--- SECTION C : THIS MONTH 


SELECT  BOQNUMBER,QTY 
INTO #MONTHBUDGET
FROM BT.SALESSPREAD 
WHERE PROJECTCODE=2 AND YEARPERIODCODE =@YEARPERIODID



SELECT BOQNUMBER, SUM(DPRQTY) DPRQTY  
INTO #MONTHACTUAL 
FROM BT.DPR 
WHERE DPRDATE BETWEEN @MONTHSTARTDATE AND @MONTHENDDATE AND PROJECTCODE=2
GROUP BY BOQNUMBER 

UPDATE BT.BUDGETACTUAL 
SET MONTHBUDGET = ISNULL(QTY,0) FROM #MONTHBUDGET INNER JOIN BT.BUDGETACTUAL ON BT.BUDGETACTUAL.BOQNUMBER=#MONTHBUDGET.BOQNumber
UPDATE BT.BUDGETACTUAL 
SET MONTHACTUAL = ISNULL(DPRQTY,0) FROM #MONTHACTUAL INNER JOIN BT.BUDGETACTUAL  ON BT.BUDGETACTUAL.BOQNUMBER = #MONTHACTUAL.BOQNUMBER 


--- SECTION D : FINAL PRINT FORMATTING

SELECT * 
INTO #FINAL
FROM BT.BUDGETACTUAL 

ALTER TABLE #FINAL ADD MONTHBUDGETAMOUNT DECIMAL(18,2)
ALTER TABLE #FINAL ADD QUARTERBUDGETAMOUNT   DECIMAL(18,2)
ALTER TABLE #FINAL ADD TILLDATEBUDGETAMOUNT  DECIMAL(18,2) 

ALTER TABLE #FINAL ADD MONTHACTUALAMOUNT DECIMAL(18,2)
ALTER TABLE #FINAL ADD QUARTERACTUALAMOUNT   DECIMAL(18,2)
ALTER TABLE #FINAL ADD TILLDATEACTUALAMOUNT  DECIMAL(18,2) 

ALTER TABLE #FINAL ADD REPORTPERIOD VARCHAR(50)

UPDATE #FINAL SET REPORTPERIOD = @REPORTPERIOD

UPDATE #FINAL SET MONTHBUDGETAMOUNT = MONTHBUDGET*RATE
UPDATE #FINAL SET MONTHACTUALAMOUNT = MONTHACTUAL*RATE 

UPDATE #FINAL SET QUARTERBUDGETAMOUNT = QUARTERBUDGET*RATE
UPDATE #FINAL SET QUARTERACTUALAMOUNT = QUARTERACTUAL*RATE 

UPDATE #FINAL SET TILLDATEBUDGETAMOUNT = TILLDATEBUDGET*RATE
UPDATE #FINAL SET TILLDATEACTUALAMOUNT = TILLDATEACTUAL*RATE 

SELECT  
 BOQNUMBER  ,
 BOQ ,
 UOM  ,
 RATE   ,
 MONTHBUDGET ,
 MONTHBUDGETAMOUNT,
 MONTHACTUAL  , 
 MONTHACTUALAMOUNT,
 QUARTERBUDGET  , 
 QUARTERBUDGETAMOUNT,
 QUARTERACTUAL  ,
 QUARTERACTUALAMOUNT,
 TILLDATEBUDGET  ,
 TILLDATEBUDGETAMOUNT,
 TILLDATEACTUAL,
 TILLDATEACTUALAMOUNT,
 REPORTPERIOD 
FROM 
 #FINAL 
ORDER BY 
 BOQNUMBER

 