/****** Object:  Procedure [BT].[spBUDGETAGENT]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE [BT].[spBUDGETAGENT]
AS

UPDATE BT.BUDGETMATERIALMOVEMENTDETAIL SET BUYINGCATEGORY=UPPER(BUYINGCATEGORY) 



UPDATE BT.BUDGETMATERIALMOVEMENTDETAIL SET BUDGETPRQTY=0 WHERE BUDGETPRQTY IS NULL
UPDATE BT.BUDGETMATERIALMOVEMENTDETAIL SET ORDQTY=0,ORDAMOUNT=0 WHERE ORDQTY IS NULL
UPDATE BT.BUDGETMATERIALMOVEMENTDETAIL SET BUDGETORDERQTY=0 WHERE BUDGETORDERQTY IS NULL
UPDATE BT.BUDGETMATERIALMOVEMENTDETAIL SET PRPOQTYDIFF=0 WHERE PRPOQTYDIFF IS NULL
UPDATE BT.BUDGETMATERIALMOVEMENTDETAIL SET BUDGETPRPODIFF = 0 WHERE BUDGETPRPODIFF IS NULL
UPDATE BT.BUDGETMATERIALMOVEMENTDETAIL SET DELIVEREDQTY=0 WHERE DELIVEREDQTY IS NULL
UPDATE BT.BUDGETMATERIALMOVEMENTDETAIL SET DELIVERYAMOUNT=0   WHERE DELIVERYAMOUNT IS NULL
UPDATE BT.BUDGETMATERIALMOVEMENTDETAIL SET BUDGETORDERQTY=0 WHERE BUDGETORDERQTY IS NULL
UPDATE BT.BUDGETMATERIALMOVEMENTDETAIL SET BUDGETDELIVERY=0 WHERE BUDGETDELIVERY IS NULL
UPDATE BT.BUDGETMATERIALMOVEMENTDETAIL SET COMPLETED = 0 WHERE COMPLETED IS NULL
UPDATE BT.BUDGETMATERIALMOVEMENTDETAIL SET BUDGETORDCOMPDIFF=0 WHERE BUDGETORDCOMPDIFF IS NULL
UPDATE BT.BUDGETMATERIALMOVEMENTDETAIL SET ORDCOMPDIFF = 0 WHERE ORDCOMPDIFF IS NULL

DELETE FROM  BT.BUDGETMATERIALMOVEMENTDETAIL WHERE TOOLCODE IS NULL
 

UPDATE BT.BUDGETMATERIALMOVEMENTDETAIL SET TOOLNAME=UPPER('Printing and Stationary'),BUYINGCATEGORY='L' WHERE TOOLCODE='9000000000'



UPDATE BT.BUDGETMATERIALMOVEMENTDETAIL 
SET BUDGETPRQTY = PRQTY*CONVERTIONFACTOR WHERE    UPPER(BUYINGCATEGORY) ='Q' AND BUDGETPRQTY= -1
UPDATE BT.BUDGETMATERIALMOVEMENTDETAIL 
SET BUDGETPRQTY = PRAMOUNT               WHERE    UPPER(BUYINGCATEGORY) ='L' AND BUDGETPRQTY= -1
   
DECLARE @REQID INT
DECLARE @DETAILID INT
DECLARE @PRQTY DECIMAL(18,4)
DECLARE @HEADERID INT 
DECLARE @CATEGORY VARCHAR(15) 
DECLARE @PRRATE DECIMAL(18,4)
DECLARE @PRAMOUNT DECIMAL(18,4) 
DECLARE @PROJECTCODE INT
DECLARE @TOOLCODE VARCHAR(25) 
DECLARE @PRSTATUS INT
DECLARE @LINENUMBER INT
DECLARE @LINEITEMEXISTING INT

DECLARE @CANCELLED DECIMAL(18,4) 
DECLARE @CANCELPRECONVERTION DECIMAL(18,4)

DECLARE @DELIVERYQTY DECIMAL(18,4) 
DECLARE @DIFFDEIVERYORDQTY DECIMAL(18,4) 
DECLARE @DELIVERYAMOUNT DECIMAL(18,4) 

DECLARE @ORDDELIVERYDIFF DECIMAL(18,4) 

DECLARE @BSBORGID INT
DECLARE @CURRNETBUDGETQTY DECIMAL(18,4)
DECLARE @CURRENTBUDGETAMOUNT DECIMAL(18,4) 
DECLARE @CURRENTCATEGORYTYPE VARCHAR(1)
DECLARE @CONVERTIONFACTOR DECIMAL(18,4)


--- CHECK WHETHER LINEITEMS IN THE DETAIL TABLE AND REQITEMS ARE MATCHING. IF USER REMOVE THE ITEMS FROM REQITEMS THIS MUST BE REMOVED FROM DETAIL TABLE
DECLARE LINEITEMS CURSOR FOR SELECT REQID,LINENUMBER FROM BT.BUDGETMATERIALMOVEMENTDETAIL WHERE FINALIZED=0 
OPEN LINEITEMS 
FETCH NEXT FROM LINEITEMS INTO @REQID,@LINENUMBER 
WHILE @@FETCH_STATUS  = 0
BEGIN
  SELECT @LINEITEMEXISTING = ISNULL(COUNT(*),0) FROM REQITEMS WHERE REQID=@REQID AND LINENUMBER=@LINENUMBER 
  IF @LINEITEMEXISTING=0 
     BEGIN
	  UPDATE BT.BUDGETMATERIALMOVEMENTDETAIL SET CANCELLEDQTY = PRQTY,PRSTATUS=99,FINALIZED=2    WHERE  REQID=@REQID AND LINENUMBER=@LINENUMBER  AND UPPER(BUYINGCATEGORY)='Q'
	  UPDATE BT.BUDGETMATERIALMOVEMENTDETAIL SET CANCELLEDQTY = PRAMOUNT,PRSTATUS=99,FINALIZED=2 WHERE  REQID=@REQID AND LINENUMBER=@LINENUMBER  AND UPPER(BUYINGCATEGORY)='L'
      UPDATE BT.BUDGETMATERIALMOVEMENTDETAIL SET BUDGETPRQTY  = CANCELLEDQTY * CONVERTIONFACTOR  WHERE  REQID=@REQID AND LINENUMBER=@LINENUMBER  AND UPPER(BUYINGCATEGORY)='Q'
 	  UPDATE BT.BUDGETMATERIALMOVEMENTDETAIL SET BUDGETPRQTY  = PRAMOUNT                         WHERE  REQID=@REQID AND LINENUMBER=@LINENUMBER  AND UPPER(BUYINGCATEGORY)='L'
      SELECT @TOOLCODE=TOOLCODE,@PROJECTCODE=PROJECTCODE,@CANCELLED=BUDGETPRQTY,@CATEGORY=BUYINGCATEGORY
	  FROM BT.BUDGETMATERIALMOVEMENTDETAIL WHERE REQID=@REQID AND LINENUMBER=@LINENUMBER
      UPDATE BT.MonthlyMaterialBudget 
			 SET BudgetAmount = BUDGETAMOUNT + @CANCELLED
		     WHERE PROJECTCODE= @PROJECTCODE AND  TOOLCODE=@TOOLCODE AND UPPER(@CATEGORY)='L'
      UPDATE BT.MonthlyMaterialBudget 
			 SET CumulativeQty = BUDGETAMOUNT  
		     WHERE PROJECTCODE= @PROJECTCODE AND  TOOLCODE=@TOOLCODE AND UPPER(@CATEGORY)='L'
	  UPDATE BT.MonthlyMaterialBudget
		     SET CumulativeQty = CumulativeQty + @CANCELLED 
		     WHERE PROJECTCODE= @PROJECTCODE AND  TOOLCODE=@TOOLCODE AND UPPER(@CATEGORY)='Q'

	  INSERT INTO BT.MATERIALBUDGETLOG(LOGDATE,TRANSACTIONTYPE,PROJECTCODE,TOOLCODE,QTY,RATE,AMOUNT,CROSSREFERENCEID) 
	  SELECT GETDATE(),'C',@PROJECTCODE,@TOOLCODE,0,@PRRATE,-1.0* @CANCELLED,@REQID 
	  UPDATE BT.BUDGETMATERIALMOVEMENTDETAIL SET CANCELLEDQTY=-1.0* CANCELLEDQTY    WHERE  REQID=@REQID AND LINENUMBER=@LINENUMBER 
	 END 
  FETCH NEXT FROM LINEITEMS INTO @REQID,@LINENUMBER 
END
CLOSE LINEITEMS
DEALLOCATE LINEITEMS 





-- GET OPEN PRS FROM REQS AND CHECK THE CURRENT STATUS 
SELECT DETAILID,REQID,LINENUMBER,PRSTATUS 
INTO  #TEMP0 
FROM  BT.BUDGETMATERIALMOVEMENTDETAIL
WHERE PRSTATUS=163 AND FINALIZED=0

ALTER TABLE #TEMP0 ADD NEWSTATUS INT
UPDATE #TEMP0 SET NEWSTATUS=REQ.REQSTATUSID FROM REQ INNER JOIN #TEMP0 ON #TEMP0.REQID=REQ.REQID 

UPDATE BT.BUDGETMATERIALMOVEMENTDETAIL SET OPENPR = PRQTY * CONVERTIONFACTOR WHERE UPPER(BUYINGCATEGORY)='Q' AND DETAILID IN (SELECT DETAILID FROM #TEMP0 WHERE NEWSTATUS=163) 
UPDATE BT.BUDGETMATERIALMOVEMENTDETAIL SET OPENPR = PRAMOUNT                 WHERE UPPER(BUYINGCATEGORY)='L' AND DETAILID IN (SELECT DETAILID FROM #TEMP0 WHERE NEWSTATUS=163) 
DELETE FROM #TEMP0 WHERE NEWSTATUS=163

 
UPDATE BT.BUDGETMATERIALMOVEMENTDETAIL
SET PRSTATUS=T.NEWSTATUS,OPENPR=0  FROM #TEMP0 T INNER JOIN BT.BUDGETMATERIALMOVEMENTDETAIL ON BT.BUDGETMATERIALMOVEMENTDETAIL.DETAILID=T.DETAILID 



-- CANCELLED PRS
UPDATE BT.BUDGETMATERIALMOVEMENTDETAIL SET CANCELLEDQTY=0 WHERE CANCELLEDQTY IS NULL
UPDATE BT.BUDGETMATERIALMOVEMENTDETAIL SET CANCELLEDQTY = PRQTY    WHERE PRSTATUS=36 AND FINALIZED=0 AND UPPER(BUYINGCATEGORY)='Q'
UPDATE BT.BUDGETMATERIALMOVEMENTDETAIL SET CANCELLEDQTY = PRAMOUNT WHERE PRSTATUS=36 AND FINALIZED=0 AND UPPER(BUYINGCATEGORY)='L'

UPDATE BT.BUDGETMATERIALMOVEMENTDETAIL SET BUDGETPRQTY = CANCELLEDQTY * CONVERTIONFACTOR  WHERE CANCELLEDQTY>0 AND PRSTATUS=36 AND UPPER(BUYINGCATEGORY)='Q'
UPDATE BT.BUDGETMATERIALMOVEMENTDETAIL SET BUDGETPRQTY = PRAMOUNT                         WHERE PRAMOUNT >0    AND PRSTATUS=36 AND UPPER(BUYINGCATEGORY)='L'

DECLARE CANCELLED CURSOR FOR SELECT DETAILID,REQID,LINENUMBER  FROM #TEMP0 WHERE NEWSTATUS=36 
OPEN CANCELLED 
FETCH NEXT FROM CANCELLED INTO @DETAILID,@REQID,@LINENUMBER 
WHILE @@FETCH_STATUS=0
BEGIN
    SELECT  @PROJECTCODE         = PROJECTCODE,
	        @TOOLCODE            = TOOLCODE ,
			@CANCELPRECONVERTION = CANCELLEDQTY,
			@CANCELLED           = CANCELLEDQTY ,
			@CATEGORY            = BUYINGCATEGORY,
			@CONVERTIONFACTOR    = CONVERTIONFACTOR 
	FROM BT.BUDGETMATERIALMOVEMENTDETAIL
	WHERE DETAILID=@DETAILID 
	

	SELECT  @CANCELLED = @CANCELLED * @CONVERTIONFACTOR WHERE @CATEGORY = 'Q'
	

    UPDATE BT.MonthlyMaterialBudget  SET CumulativeQty = CumulativeQty  + @CANCELLED    
		          WHERE PROJECTCODE=@PROJECTCODE AND TOOLCODE=@TOOLCODE AND CATEGORYTYPE='Q'
	UPDATE BT.MonthlyMaterialBudget  SET BudgetAmount  = BUDGETAMOUNT   + @CANCELLED    
		          WHERE PROJECTCODE=@PROJECTCODE AND TOOLCODE=@TOOLCODE AND CATEGORYTYPE='L'

	UPDATE BT.MONTHLYMATERIALBUDGET  SET BUDGETAMOUNT = CUMULATIVEQTY * BUDGETRATE 
	              WHERE PROJECTCODE=@PROJECTCODE AND TOOLCODE=@TOOLCODE AND CATEGORYTYPE ='Q'
	UPDATE BT.MONTHLYMATERIALBUDGET  SET CumulativeQty= BUDGETAMOUNT 
		          WHERE PROJECTCODE=@PROJECTCODE AND TOOLCODE=@TOOLCODE AND CATEGORYTYPE ='L'
     
	 INSERT INTO BT.MATERIALBUDGETLOG(LOGDATE,TRANSACTIONTYPE,PROJECTCODE,TOOLCODE,QTY,RATE,AMOUNT,CROSSREFERENCEID) 
	 SELECT GETDATE(),'C',@PROJECTCODE,@TOOLCODE,0,0,-1.0*@CANCELLED,@REQID 
	
	UPDATE BT.BUDGETMATERIALMOVEMENTDETAIL SET CANCELLEDQTY=-1.0* @CANCELPRECONVERTION , PRSTATUS=36, FINALIZED=1  WHERE DETAILID=@DETAILID
	

	
	FETCH NEXT FROM CANCELLED INTO @DETAILID,@REQID,@LINENUMBER 
END
CLOSE CANCELLED 
DEALLOCATE CANCELLED 
 
 
--- REJECTED
DECLARE @REJECTED DECIMAL(18,4)
DECLARE @REJECTPRECONVERTION DECIMAL(18,4) 


SELECT DETAILID,REQID,LINENUMBER,PRSTATUS 
INTO #TEMPR 
FROM  BT.BUDGETMATERIALMOVEMENTDETAIL
WHERE PRSTATUS IN (32,163,202)  AND FINALIZED=0
 

ALTER TABLE #TEMPR ADD NEWSTATUS INT
UPDATE #TEMPR SET NEWSTATUS=REQ.REQSTATUSID FROM REQ INNER JOIN #TEMPR ON #TEMPR.REQID=REQ.REQID 
 
DELETE FROM #TEMPR WHERE NEWSTATUS=32

UPDATE BT.BUDGETMATERIALMOVEMENTDETAIL
SET PRSTATUS=T.NEWSTATUS FROM #TEMPR T INNER JOIN BT.BUDGETMATERIALMOVEMENTDETAIL ON BT.BUDGETMATERIALMOVEMENTDETAIL.DETAILID=T.DETAILID 

UPDATE BT.BUDGETMATERIALMOVEMENTDETAIL SET REJECTQTY=0 WHERE REJECTQTY IS NULL

UPDATE BT.BUDGETMATERIALMOVEMENTDETAIL SET REJECTQTY = PRQTY    WHERE PRSTATUS=202  AND FINALIZED=0  AND BUYINGCATEGORY='Q'
UPDATE BT.BUDGETMATERIALMOVEMENTDETAIL SET REJECTQTY = PRAMOUNT WHERE PRSTATUS=202  AND FINALIZED=0  AND BUYINGCATEGORY='L'

UPDATE BT.BUDGETMATERIALMOVEMENTDETAIL SET BUDGETPRQTY = REJECTQTY  * CONVERTIONFACTOR  WHERE REJECTQTY>0 AND PRSTATUS=202 AND BUYINGCATEGORY='Q'
UPDATE BT.BUDGETMATERIALMOVEMENTDETAIL SET BUDGETPRQTY = PRAMOUNT                       WHERE PRAMOUNT >0 AND PRSTATUS=202 AND BUYINGCATEGORY='L'

 

DECLARE REJECTED CURSOR FOR SELECT DETAILID,REQID,LINENUMBER  FROM #TEMPR WHERE NEWSTATUS=202
OPEN REJECTED 
FETCH NEXT FROM REJECTED INTO @DETAILID,@REQID,@LINENUMBER 
WHILE @@FETCH_STATUS=0
BEGIN

    UPDATE REQ SET REQSTATUSID=36 WHERE REQSTATUSID=202 AND REQID=@REQID

    SELECT  @PROJECTCODE           = PROJECTCODE,
			@TOOLCODE              = TOOLCODE ,
			@REJECTPRECONVERTION   = REJECTQTY,
	        @REJECTED              = REJECTQTY,
		    @CATEGORY              = BUYINGCATEGORY,
			@CONVERTIONFACTOR      = CONVERTIONFACTOR 
	FROM BT.BUDGETMATERIALMOVEMENTDETAIL
	WHERE DETAILID=@DETAILID 
	
	SELECT  @REJECTED = @REJECTED * @CONVERTIONFACTOR WHERE @CATEGORY = 'Q'
	

    UPDATE BT.MonthlyMaterialBudget  SET CumulativeQty = CumulativeQty  + @REJECTED    
		          WHERE PROJECTCODE=@PROJECTCODE AND TOOLCODE=@TOOLCODE AND CATEGORYTYPE='Q'
	UPDATE BT.MonthlyMaterialBudget  SET BudgetAmount  = BUDGETAMOUNT   + @REJECTED    
		          WHERE PROJECTCODE=@PROJECTCODE AND TOOLCODE=@TOOLCODE AND CATEGORYTYPE='L'

	UPDATE BT.MONTHLYMATERIALBUDGET  SET BUDGETAMOUNT = CUMULATIVEQTY * BUDGETRATE 
	              WHERE PROJECTCODE=@PROJECTCODE AND TOOLCODE=@TOOLCODE AND CATEGORYTYPE ='Q'
	UPDATE BT.MONTHLYMATERIALBUDGET  SET CumulativeQty= BUDGETAMOUNT 
		          WHERE PROJECTCODE=@PROJECTCODE AND TOOLCODE=@TOOLCODE AND CATEGORYTYPE ='L'
     
	 INSERT INTO BT.MATERIALBUDGETLOG(LOGDATE,TRANSACTIONTYPE,PROJECTCODE,TOOLCODE,QTY,RATE,AMOUNT,CROSSREFERENCEID) 
	 SELECT GETDATE(),'J',@PROJECTCODE,@TOOLCODE,0,0,-1.0*@REJECTED,@REQID 
	
	UPDATE BT.BUDGETMATERIALMOVEMENTDETAIL SET REJECTQTY=- 1.0* @REJECTPRECONVERTION,PRSTATUS=202,FINALIZED=1 	  WHERE DETAILID=@DETAILID     

    FETCH NEXT FROM REJECTED INTO @DETAILID,@REQID,@LINENUMBER 
END
CLOSE REJECTED 
DEALLOCATE REJECTED 


----- PR CONVERTED TO PO ; NOW CHECK THE PO QTY OR PO AMOUNT AND DO NEEDFUL BUDGET CORRECTIONS

DECLARE @ORDID INT
DECLARE @ORDNUMBER VARCHAR(25)
DECLARE @ORDDATE DATETIME
DECLARE @ORDQTY DECIMAL(18,4)
DECLARE @ORDRATE DECIMAL(18,4)
DECLARE @ORDAMOUNT DECIMAL(18,4) 
DECLARE @DIFFPRPOQTY DECIMAL(18,4)

SELECT DETAILID,REQID,LINENUMBER,PRSTATUS 
INTO #TEMPO 
FROM   BT.BUDGETMATERIALMOVEMENTDETAIL
WHERE   FINALIZED=0
ALTER TABLE #TEMPO ADD NEWSTATUS INT
UPDATE #TEMPO SET NEWSTATUS=REQ.REQSTATUSID FROM REQ INNER JOIN #TEMPO ON #TEMPO.REQID=REQ.REQID 
DELETE FROM #TEMPO WHERE NEWSTATUS<>173
 
UPDATE BT.BUDGETMATERIALMOVEMENTDETAIL
SET PRSTATUS=T.NEWSTATUS FROM #TEMPO T INNER JOIN BT.BUDGETMATERIALMOVEMENTDETAIL ON BT.BUDGETMATERIALMOVEMENTDETAIL.DETAILID=T.DETAILID 


DECLARE @ORDERNUMBERS INT
DECLARE @CURRENTPRQTY DECIMAL(18,4)
DECLARE @CURRENTREQID INT 

DECLARE ORDERED CURSOR FOR SELECT DETAILID,REQID,LINENUMBER  FROM #TEMPO  
OPEN ORDERED 
FETCH NEXT FROM ORDERED INTO @DETAILID,@REQID,@LINENUMBER 
WHILE @@FETCH_STATUS=0
BEGIN
    
	SELECT  @PROJECTCODE = PROJECTCODE,
			@TOOLCODE    = TOOLCODE ,
	        @REJECTED    = BUDGETPRQTY,
		    @CATEGORY    = BUYINGCATEGORY
	FROM BT.BUDGETMATERIALMOVEMENTDETAIL
	WHERE DETAILID=@DETAILID 

	UPDATE BT.BUDGETMATERIALMOVEMENTDETAIL SET ORDID=0,ORDNUMBER='',ORDQTY=0,ORDRATE=0,ORDAMOUNT=0,PRPOQTYDIFF=0 WHERE DETAILID=@DETAILID AND LINENUMBER=@LINENUMBER

	SELECT ORDID INTO #ORDERLISTS FROM ORD WHERE REQID=@REQID 

	DECLARE ORDERSLIST CURSOR FOR SELECT ORDID FROM #ORDERLISTS
	OPEN ORDERSLIST
	FETCH NEXT FROM ORDERSLIST INTO @ORDERNUMBERS
	WHILE @@FETCH_STATUS=0 
	BEGIN 

	   SELECT @ORDID=ORDID,@ORDNUMBER=ORDNUMBER,@ORDDATE=CREATEDATE,@CURRENTREQID=REQID  FROM ORD    WHERE ORDID = @ORDERNUMBERS
	
	   SET @ORDQTY=0
	   SET @ORDRATE=0
	   SET @ORDAMOUNT=0

       SELECT @ORDQTY=QTY,@ORDRATE=PRICE,@ORDAMOUNT=QTY*PRICE       FROM ORDITEMS WHERE ORDID=@ORDERNUMBERS AND LINENUMBER=@LINENUMBER 
	   SELECT @CURRENTPRQTY = QTY FROM REQITEMS WHERE REQID=@CURRENTREQID AND LINENUMBER=@LINENUMBER 
	   UPDATE BT.BUDGETMATERIALMOVEMENTDETAIL SET PRQTY = @CURRENTPRQTY  WHERE REQID=@CURRENTREQID AND LINENUMBER = @LINENUMBER 
	   -- A CROSS CHECK - BEFFORE PO THE QTY GOT CHANGED

	   IF @ORDQTY >0 
	   BEGIN
	     UPDATE BT.BUDGETMATERIALMOVEMENTDETAIL SET
			 ORDID=@ORDID,ORDNUMBER=@ORDNUMBER,ORDDATE=@ORDDATE,ORDQTY=@ORDQTY,ORDRATE=@ORDRATE,ORDAMOUNT=@ORDAMOUNT,ORDSTATUS=274 
			 WHERE DETAILID=@DETAILID   AND LINENUMBER=@LINENUMBER 


	    UPDATE BT.BUDGETMATERIALMOVEMENTDETAIL SET  BUDGETORDERQTY =  ORDQTY * CONVERTIONFACTOR     WHERE DETAILID=@DETAILID   AND  BUYINGCATEGORY='Q'
	    UPDATE BT.BUDGETMATERIALMOVEMENTDETAIL SET  BUDGETORDERQTY =  ORDAMOUNT                     WHERE DETAILID=@DETAILID   AND  BUYINGCATEGORY='L'      
     
	 
	    UPDATE BT.BUDGETMATERIALMOVEMENTDETAIL SET  PRPOQTYDIFF    = (PRQTY-ORDQTY)                 WHERE DETAILID=@DETAILID   AND BUYINGCATEGORY='Q'   
        UPDATE BT.BUDGETMATERIALMOVEMENTDETAIL SET  PRPOQTYDIFF    = (PRAMOUNT-ORDAMOUNT)           WHERE DETAILID=@DETAILID   AND BUYINGCATEGORY='L'   
	  
	   END
	  ELSE
	     BEGIN
	       UPDATE BT.BUDGETMATERIALMOVEMENTDETAIL   SET PRPOQTYDIFF=BUDGETPRQTY, BUDGETPRPODIFF = BUDGETPRQTY  WHERE DETAILID=@DETAILID 
	     END 

    FETCH NEXT FROM ORDERSLIST INTO @ORDERNUMBERS 
   END
   CLOSE ORDERSLIST 
   DEALLOCATE ORDERSLIST
   DROP TABLE #ORDERLISTS
  FETCH NEXT FROM ORDERED INTO @DETAILID,@REQID,@LINENUMBER 
END
CLOSE ORDERED 
DEALLOCATE ORDERED 

DECLARE  FINALIZATION CURSOR FOR SELECT DETAILID   FROM #TEMPO 
OPEN FINALIZATION
FETCH NEXT FROM FINALIZATION INTO @DETAILID 
WHILE @@FETCH_STATUS=0
BEGIN
  UPDATE BT.BUDGETMATERIALMOVEMENTDETAIL SET  BUDGETORDERQTY=0                                             WHERE BUDGETORDERQTY IS NULL AND DETAILID=@DETAILID 
  UPDATE BT.BUDGETMATERIALMOVEMENTDETAIL SET  BUDGETPRPODIFF = (BUDGETPRQTY-BUDGETORDERQTY),FINALIZED=1    WHERE DETAILID=@DETAILID 
  SET @DIFFPRPOQTY=0
  SELECT @DIFFPRPOQTY = BUDGETPRPODIFF FROM BT.BUDGETMATERIALMOVEMENTDETAIL                                WHERE DETAILID=@DETAILID  
  IF @DIFFPRPOQTY <>0 
	      BEGIN
	 	    

		   UPDATE BT.MonthlyMaterialBudget  SET CumulativeQty = CumulativeQty  + @DIFFPRPOQTY    
		          WHERE PROJECTCODE=@PROJECTCODE AND TOOLCODE=@TOOLCODE AND CATEGORYTYPE='Q'
		   UPDATE BT.MonthlyMaterialBudget  SET BudgetAmount  = BUDGETAMOUNT   + @DIFFPRPOQTY    
		          WHERE PROJECTCODE=@PROJECTCODE AND TOOLCODE=@TOOLCODE AND CATEGORYTYPE='L'

		   UPDATE BT.MONTHLYMATERIALBUDGET  SET BUDGETAMOUNT = CUMULATIVEQTY * BUDGETRATE 
		          WHERE PROJECTCODE=@PROJECTCODE AND TOOLCODE=@TOOLCODE AND CATEGORYTYPE ='Q'
		   UPDATE BT.MONTHLYMATERIALBUDGET  SET CumulativeQty= BUDGETAMOUNT 
		          WHERE PROJECTCODE=@PROJECTCODE AND TOOLCODE=@TOOLCODE AND CATEGORYTYPE ='L'

           

		   INSERT INTO BT.MATERIALBUDGETLOG(LOGDATE,TRANSACTIONTYPE,PROJECTCODE,TOOLCODE,QTY,RATE,AMOUNT,CROSSREFERENCEID) 
		   SELECT GETDATE(),'X',@PROJECTCODE,@TOOLCODE,-1.0*@DIFFPRPOQTY,0,0,@REQID
         END 
  FETCH NEXT FROM FINALIZATION INTO @DETAILID 
END 
	  
	  
-- ORDER CREATED - WITHOUT TAKING ANY DELIVERY CLOSED - ELSE AFTER TAKING DELIVERY IT IS CLOSED 

SELECT DETAILID,ORDID,LINENUMBER,ORDSTATUS
INTO #ORDCANCEL 
FROM   BT.BUDGETMATERIALMOVEMENTDETAIL
WHERE  FINALIZED=1 AND ORDSTATUS=274
ALTER TABLE #ORDCANCEL ADD NEWSTATUS INT
UPDATE #ORDCANCEL SET NEWSTATUS=ORD.ORDSTATUSID  FROM ORD INNER JOIN #ORDCANCEL ON #ORDCANCEL.ORDID=ORD.ORDID  
DELETE FROM #ORDCANCEL WHERE NEWSTATUS=274


DECLARE ORDERCANCEL CURSOR FOR SELECT DETAILID,ORDID,LINENUMBER  FROM #ORDCANCEL WHERE  NEWSTATUS=37
OPEN ORDERCANCEL 
FETCH NEXT FROM ORDERCANCEL INTO @DETAILID,@ORDID,@LINENUMBER 
WHILE @@FETCH_STATUS=0
BEGIN
     UPDATE BT.BUDGETMATERIALMOVEMENTDETAIL SET ORDSTATUS=37, FINALIZED = 4 WHERE DETAILID=@DETAILID 
     SELECT @DELIVERYQTY=ISNULL(SUM(DLVRQTY),0),@DELIVERYAMOUNT=ISNULL(SUM(DLVRQTY*PRICE),0)  FROM DELIVERIES WHERE ORDID=@ORDID AND ORDITEMLINENO=@LINENUMBER 
	 UPDATE BT.BUDGETMATERIALMOVEMENTDETAIL SET DELIVEREDQTY=@DELIVERYQTY,DELIVERYAMOUNT=@DELIVERYAMOUNT,BUDGETDELIVERY=0,COMPLETED=0,ORDCOMPDIFF=0 WHERE DETAILID=@DETAILID 
     UPDATE BT.BUDGETMATERIALMOVEMENTDETAIL SET BUDGETDELIVERY = DELIVEREDQTY * CONVERTIONFACTOR WHERE BUYINGCATEGORY='Q' AND DETAILID=@DETAILID 
	 UPDATE BT.BUDGETMATERIALMOVEMENTDETAIL SET BUDGETDELIVERY = DELIVERYAMOUNT                  WHERE BUYINGCATEGORY='L' AND DETAILID=@DETAILID 
	 UPDATE BT.BUDGETMATERIALMOVEMENTDETAIL SET COMPLETED      =  DELIVEREDQTY                   WHERE  DETAILID=@DETAILID  
 	 UPDATE BT.BUDGETMATERIALMOVEMENTDETAIL SET ORDCOMPDIFF = (ORDQTY - DELIVEREDQTY )           WHERE  DETAILID=@DETAILID  AND BUYINGCATEGORY='Q'
	 UPDATE BT.BUDGETMATERIALMOVEMENTDETAIL SET ORDCOMPDIFF = (ORDAMOUNT - DELIVERYAMOUNT )      WHERE  DETAILID=@DETAILID  AND BUYINGCATEGORY='L'
	 UPDATE BT.BUDGETMATERIALMOVEMENTDETAIL SET BUDGETORDCOMPDIFF = ORDCOMPDIFF*CONVERTIONFACTOR WHERE  DETAILID=@DETAILID
	 SET @ORDDELIVERYDIFF=0.0000
	 SELECT @ORDDELIVERYDIFF = BUDGETORDCOMPDIFF  FROM BT.BUDGETMATERIALMOVEMENTDETAIL           WHERE DETAILID=@DETAILID 
	 IF @ORDDELIVERYDIFF <>0  
	 BEGIN
	       SELECT  @PROJECTCODE = PROJECTCODE,
				   @TOOLCODE    = TOOLCODE ,
			       @CATEGORY    = BUYINGCATEGORY
		   FROM BT.BUDGETMATERIALMOVEMENTDETAIL
		   WHERE DETAILID=@DETAILID 

		   UPDATE BT.MonthlyMaterialBudget  SET CumulativeQty = CumulativeQty  + @ORDDELIVERYDIFF    
		          WHERE PROJECTCODE=@PROJECTCODE AND TOOLCODE=@TOOLCODE AND CATEGORYTYPE='Q'
		   UPDATE BT.MonthlyMaterialBudget  SET BudgetAmount  = BUDGETAMOUNT   + @ORDDELIVERYDIFF    
		          WHERE PROJECTCODE=@PROJECTCODE AND TOOLCODE=@TOOLCODE AND CATEGORYTYPE='L'

		   UPDATE BT.MONTHLYMATERIALBUDGET  SET BUDGETAMOUNT = CUMULATIVEQTY * BUDGETRATE 
		          WHERE PROJECTCODE=@PROJECTCODE AND TOOLCODE=@TOOLCODE AND CATEGORYTYPE ='Q'
		   UPDATE BT.MONTHLYMATERIALBUDGET  SET CumulativeQty= BUDGETAMOUNT 
		          WHERE PROJECTCODE=@PROJECTCODE AND TOOLCODE=@TOOLCODE AND CATEGORYTYPE ='L'
 
          


           INSERT INTO BT.MATERIALBUDGETLOG(LOGDATE,TRANSACTIONTYPE,PROJECTCODE,TOOLCODE,QTY,RATE,AMOUNT,CROSSREFERENCEID) 
		   SELECT GETDATE(),'Z',@PROJECTCODE,@TOOLCODE,-1.0*@ORDDELIVERYDIFF,0,0,@ORDID
     END 
	 FETCH NEXT FROM ORDERCANCEL INTO @DETAILID,@ORDID,@LINENUMBER 
END
CLOSE ORDERCANCEL
DEALLOCATE ORDERCANCEL 


---- UPDATE DELIVERY QTY 

SELECT DETAILID,ORDID,LINENUMBER,ORDSTATUS
INTO #TEMPL
FROM BT.BUDGETMATERIALMOVEMENTDETAIL
WHERE  FINALIZED=1 AND ORDSTATUS=274

DECLARE DELIVERED CURSOR FOR SELECT DETAILID,ORDID,LINENUMBER  FROM #TEMPL  
OPEN DELIVERED 
FETCH NEXT FROM DELIVERED INTO @DETAILID,@ORDID,@LINENUMBER 
WHILE @@FETCH_STATUS=0
BEGIN
    UPDATE BT.BUDGETMATERIALMOVEMENTDETAIL SET DELIVEREDQTY=0,DELIVERYAMOUNT=0,BUDGETDELIVERY=0,COMPLETED=0,ORDCOMPDIFF=0 WHERE DETAILID=@DETAILID 
    SELECT @DELIVERYQTY= SUM(DLVRQTY),@DELIVERYAMOUNT=SUM(DLVRQTY*PRICE)  FROM DELIVERIES WHERE ORDID=@ORDID AND ORDITEMLINENO=@LINENUMBER 
 	UPDATE BT.BUDGETMATERIALMOVEMENTDETAIL SET DELIVEREDQTY=@DELIVERYQTY,DELIVERYAMOUNT=@DELIVERYAMOUNT,BUDGETDELIVERY=0,COMPLETED=0,ORDCOMPDIFF=0 WHERE DETAILID=@DETAILID 
    UPDATE BT.BUDGETMATERIALMOVEMENTDETAIL SET BUDGETDELIVERY = DELIVEREDQTY * CONVERTIONFACTOR WHERE BUYINGCATEGORY='Q' AND DETAILID=@DETAILID 
	UPDATE BT.BUDGETMATERIALMOVEMENTDETAIL SET BUDGETDELIVERY = DELIVERYAMOUNT   WHERE BUYINGCATEGORY='L' AND DETAILID=@DETAILID 
	 
    FETCH NEXT FROM DELIVERED INTO @DETAILID,@ORDID,@LINENUMBER
END
CLOSE DELIVERED
DEALLOCATE DELIVERED 



-- COMPLETED 

SET @ORDDELIVERYDIFF =0.00000

SELECT DETAILID,ORDID,LINENUMBER,ORDSTATUS
INTO #TEMPC 
FROM   BT.BUDGETMATERIALMOVEMENTDETAIL
WHERE  FINALIZED=1 AND ORDSTATUS=274
ALTER TABLE #TEMPC ADD NEWSTATUS INT
UPDATE #TEMPC SET NEWSTATUS=ORD.ORDSTATUSID  FROM ORD INNER JOIN #TEMPC ON #TEMPC.ORDID=ORD.ORDID  
DELETE FROM #TEMPC WHERE NEWSTATUS=274

 
UPDATE BT.BUDGETMATERIALMOVEMENTDETAIL
SET ORDSTATUS=T.NEWSTATUS FROM #TEMPC T INNER JOIN BT.BUDGETMATERIALMOVEMENTDETAIL ON BT.BUDGETMATERIALMOVEMENTDETAIL.DETAILID=T.DETAILID 


DECLARE COMPLETED CURSOR FOR SELECT DETAILID,ORDID,LINENUMBER  FROM #TEMPC  
OPEN COMPLETED 
FETCH NEXT FROM COMPLETED INTO @DETAILID,@ORDID,@LINENUMBER 
WHILE @@FETCH_STATUS=0
BEGIN
   
	 
	UPDATE BT.BUDGETMATERIALMOVEMENTDETAIL SET DELIVEREDQTY=0,DELIVERYAMOUNT=0,BUDGETDELIVERY=0,COMPLETED=0,ORDCOMPDIFF=0,BUDGETORDCOMPDIFF=0
	WHERE DELIVEREDQTY IS NULL AND 	DETAILID=@DETAILID 
 	UPDATE BT.BUDGETMATERIALMOVEMENTDETAIL SET COMPLETED =  DELIVEREDQTY                         WHERE  DETAILID=@DETAILID  
 	UPDATE BT.BUDGETMATERIALMOVEMENTDETAIL SET ORDCOMPDIFF = (ORDQTY - DELIVEREDQTY )            WHERE DETAILID=@DETAILID  AND BUYINGCATEGORY='Q'
	UPDATE BT.BUDGETMATERIALMOVEMENTDETAIL SET ORDCOMPDIFF = (ORDAMOUNT - DELIVERYAMOUNT )       WHERE DETAILID=@DETAILID  AND BUYINGCATEGORY='L'

	UPDATE BT.BUDGETMATERIALMOVEMENTDETAIL SET BUDGETORDCOMPDIFF = ORDCOMPDIFF*CONVERTIONFACTOR  WHERE DETAILID=@DETAILID  AND BUYINGCATEGORY='Q'
	UPDATE BT.BUDGETMATERIALMOVEMENTDETAIL SET BUDGETORDCOMPDIFF = ORDCOMPDIFF                   WHERE DETAILID=@DETAILID  AND BUYINGCATEGORY='L'
 

	SET @ORDDELIVERYDIFF=0.0000
	SELECT @ORDDELIVERYDIFF = BUDGETORDCOMPDIFF  FROM BT.BUDGETMATERIALMOVEMENTDETAIL WHERE DETAILID=@DETAILID   

	IF @ORDDELIVERYDIFF <>0  
	 BEGIN
	       SELECT  @PROJECTCODE = PROJECTCODE,
				   @TOOLCODE    = TOOLCODE ,
			       @CATEGORY    = BUYINGCATEGORY
		   FROM BT.BUDGETMATERIALMOVEMENTDETAIL
		   WHERE DETAILID=@DETAILID 
	 	 

		   UPDATE BT.MonthlyMaterialBudget  SET CumulativeQty = CumulativeQty  + @ORDDELIVERYDIFF    
		          WHERE PROJECTCODE=@PROJECTCODE AND TOOLCODE=@TOOLCODE AND CATEGORYTYPE = 'Q'
		   UPDATE BT.MonthlyMaterialBudget  SET BudgetAmount  = BUDGETAMOUNT   + @ORDDELIVERYDIFF    
		          WHERE PROJECTCODE=@PROJECTCODE AND TOOLCODE=@TOOLCODE AND CATEGORYTYPE = 'L'

		
		   UPDATE BT.MONTHLYMATERIALBUDGET  SET BUDGETAMOUNT = CumulativeQty * BUDGETRATE 
		          WHERE PROJECTCODE=@PROJECTCODE AND TOOLCODE=@TOOLCODE AND CATEGORYTYPE='Q'
		   UPDATE BT.MONTHLYMATERIALBUDGET  SET CumulativeQty = BUDGETAMOUNT 
		          WHERE PROJECTCODE=@PROJECTCODE AND TOOLCODE=@TOOLCODE AND CATEGORYTYPE='L' 

           INSERT INTO BT.MATERIALBUDGETLOG(LOGDATE,TRANSACTIONTYPE,PROJECTCODE,TOOLCODE,QTY,RATE,AMOUNT,CROSSREFERENCEID) 
		   SELECT GETDATE(),'O',@PROJECTCODE,@TOOLCODE,-1.0*@ORDDELIVERYDIFF,0,0,@ORDID
     END 
    FETCH NEXT FROM COMPLETED INTO @DETAILID,@ORDID,@LINENUMBER
END
CLOSE COMPLETED
DEALLOCATE COMPLETED 

UPDATE BT.BUDGETMATERIALMOVEMENTDETAIL SET FINALIZED=2 WHERE PRSTATUS IN (36,202)
UPDATE BT.BUDGETMATERIALMOVEMENTDETAIL SET FINALIZED=2 WHERE ORDSTATUS=41
UPDATE BT.BUDGETMATERIALMOVEMENTDETAIL SET STOCKNAME=UPPER(STOCKNAME) 

UPDATE BT.BUDGETMATERIALMOVEMENTDETAIL SET OPENPR=0 WHERE OPENPR IS NULL
 

 

 
-- MODIFIED ON 31 AUGUST 2020
-- -----  UPDATING THE TENDERITEMS TABLE ----
--SELECT PROJECTCODE,TOOLCODE,SUM(ORDQTY*CONVERTIONFACTOR-BUDGETORDCOMPDIFF) FINALORDERQTY,SUM(ORDAMOUNT-BUDGETORDCOMPDIFF) FINALORDERVALUE,BUYINGCATEGORY 
--INTO #FINALORDER
--FROM BT.BUDGETMATERIALMOVEMENTDETAIL 
--GROUP BY PROJECTCODE,TOOLCODE,BUYINGCATEGORY


--ALTER TABLE #FINALORDER ADD BSBORG INT
--UPDATE #FINALORDER SET BSBORG = BORGID FROM BT.PROJECTS  BTP INNER JOIN #FINALORDER ON #FINALORDER.PROJECTCODE=BTP.ProjectID 

--UPDATE TENDERITEMS 
--SET ORDEREDQTY = F.FINALORDERQTY 
--FROM #FINALORDER F
--INNER JOIN TENDERITEMS ON TENDERITEMS.BORG=F.BSBORG  AND TENDERITEMS.RESCODE=F.TOOLCODE 
--WHERE UPPER(F.BUYINGCATEGORY)='Q'

--UPDATE TENDERITEMS 
--SET ORDEREDQTY = F.FINALORDERVALUE
--FROM #FINALORDER F
--INNER JOIN TENDERITEMS ON TENDERITEMS.BORG=F.BSBORG  AND TENDERITEMS.RESCODE=F.TOOLCODE 
--WHERE UPPER(F.BUYINGCATEGORY)='L'



--- MODIFIED ON 31 AUGUST 2020
-- CALLING THE FINAL UPDATE MODULE

DECLARE @CROSSCHKBORGID INT
DECLARE PROJECTLISTS CURSOR FOR SELECT PROJECTID FROM BT.PROJECTS WHERE BORGID<>-1
OPEN PROJECTLISTS
FETCH NEXT FROM PROJECTLISTS INTO @CROSSCHKBORGID
WHILE @@FETCH_STATUS = 0 
BEGIN
  EXEC [BT].[spCrossCheckBudget] @CROSSCHKBORGID,1
  FETCH NEXT FROM PROJECTLISTS INTO @CROSSCHKBORGID
END
CLOSE PROJECTLISTS
DEALLOCATE PROJECTLISTS 