/****** Object:  Procedure [BT].[spCrossCheckNarration]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE [BT].[spCrossCheckNarration](@PROJECTID INT) 
AS
 
DECLARE @BORGID INT 
SELECT @BORGID=BORGID FROM BT.PROJECTS WHERE PROJECTID=@PROJECTID 
 

SELECT PROJECTCODE,BOQCODE,REVISIONID,MINORWORKHEADID,UOM,TOTALQTY,RATE,TENDERITEMID 
INTO #TEMPWORKORDER 
FROM BT.WORKORDER WHERE PROJECTCODE=@PROJECTID 



 
 
SELECT PROJECT,ITEMTYPE,TOOLCODE,UPPER(WORKDESCRIPTION) WORKDESCRIPTION,UOM 
INTO #TEMPMASTER 
FROM BT.WORKORDERITEMS WHERE PROJECT=@PROJECTID 


--SELECT TOOLCODE,COUNT(*)
--FROM #TEMPMASTER 
--GROUP BY TOOLCODE HAVING COUNT(*)>1

CREATE TABLE #TEMPTENDER(ITEMID INT,RESCODE VARCHAR(30),DESCR VARCHAR(4000), RATE DECIMAL(18,2), UNIT VARCHAR(25), QTY DECIMAL(18,2))
INSERT INTO #TEMPTENDER
SELECT ITEMID,RESCODE,DESCR,RATE,UNIT,QTY 
FROM TENDERITEMS  
WHERE CATEGORY='SUBCONTRACTORS' AND BORG=@BORGID 
 

SELECT PROJECTCODE,BOQNUMBER,BOQ,CLIENTBOQ
INTO #TEMPSALES 
FROM BT.SALES 
WHERE PROJECTCODE=@PROJECTID 

 

ALTER TABLE #TEMPWORKORDER ADD ITEMTYPE VARCHAR(50)
ALTER TABLE #TEMPWORKORDER ADD BOQDESCRIPTION VARCHAR(4000)

ALTER TABLE #TEMPWORKORDER ADD CLIENTBOQ VARCHAR(100)
ALTER TABLE #TEMPWORKORDER ADD BOQ VARCHAR(800)
ALTER TABLE #TEMPWORKORDER ADD WORKDESCRTIPION VARCHAR(4000)
ALTER TABLE #TEMPWORKORDER ADD FINALDESCRIPTION VARCHAR(4000)

UPDATE #TEMPWORKORDER SET WORKDESCRTIPION='',FINALDESCRIPTION='' ,ITEMTYPE=''
UPDATE #TEMPWORKORDER SET 
  WORKDESCRTIPION = TM.WORKDESCRIPTION ,ITEMTYPE = TM.ITEMTYPE
  FROM #TEMPMASTER TM INNER JOIN #TEMPWORKORDER ON  TM.TOOLCODE = #TEMPWORKORDER.MINORWORKHEADID
 


UPDATE #TEMPWORKORDER 
SET CLIENTBOQ = S.CLIENTBOQ,BOQ = S.BOQ  FROM #TEMPSALES  S INNER JOIN #TEMPWORKORDER ON #TEMPWORKORDER.BOQCode = S.BOQNumber 


UPDATE #TEMPWORKORDER  SET BOQDESCRIPTION='' WHERE BOQDESCRIPTION IS NULL
UPDATE #TEMPWORKORDER 
SET BOQDESCRIPTION = UPPER(LTRIM(RTRIM(CLIENTBOQ)))+'-'+UPPER(LTRIM(RTRIM(BOQ)))
UPDATE #TEMPWORKORDER SET BOQDESCRIPTION='' WHERE BOQDESCRIPTION IS NULL 
UPDATE #TEMPWORKORDER SET FINALDESCRIPTION = LTRIM(RTRIM(BOQDESCRIPTION))+' '+LTRIM(RTRIM(WORKDESCRTIPION))
UPDATE #TEMPWORKORDER SET FINALDESCRIPTION = LTRIM(RTRIM(FINALDESCRIPTION))
 
ALTER TABLE #TEMPWORKORDER ADD TENDERDESCRIPTION VARCHAR(4000)
UPDATE #TEMPWORKORDER SET TENDERDESCRIPTION = DESCR FROM TENDERITEMS T INNER JOIN #TEMPWORKORDER ON #TEMPWORKORDER.MINORWORKHEADID=T.RESCODE 
WHERE T.BORG=168 AND T.CATEGORY='SUBCONTRACTORS' 

ALTER TABLE #TEMPWORKORDER ADD PROJECTNAME VARCHAR(200)
UPDATE #TEMPWORKORDER SET PROJECTNAME=(SELECT UPPER(PROJECTNAME) FROM BT.PROJECTS   WHERE  PROJECTID=6 )
 

  

 
SELECT PROJECTNAME,ITEMTYPE,CLIENTBOQ,BOQCODE,BOQ,REVISIONID,MINORWORKHEADID  TOOLCODE,WORKDESCRTIPION,FINALDESCRIPTION,UOM,TOTALQTY,RATE,(TOTALQTY*RATE) AMOUNT 
INTO #FINAL
FROM  #TEMPWORKORDER 

-- To Be Open for BMT
SELECT * FROM #FINAL 
ORDER BY ITEMTYPE,CLIENTBOQ,TOOLCODE ,REVISIONID 

 

-- To be Commented from Here ---

--SELECT * INTO #REPLACES  FROM #TEMPWORKORDER WHERE FINALDESCRIPTION<>TENDERDESCRIPTION 
--SELECT * FROM #REPLACES ORDER BY RevisionID

--UPDATE TENDERITEMS SET DESCR = R.FINALDESCRIPTION 
--FROM #REPLACES R INNER JOIN TENDERITEMS ON TENDERITEMS.ITEMID=R.TENDERITEMID 

--SELECT * FROM BT.WORKORDER WHERE PROJECTCODE=4 AND MINORWORKHEADID IN (SELECT MINORWORKHEADID FROM #REPLACES)

--ALTER TABLE #FINAL ADD TENDERID INT 
--UPDATE #FINAL 
--SET TENDERID = T.ITEMID 
--FROM #TEMPTENDER T 
--INNER JOIN #FINAL ON #FINAL.FINALDESCRIPTION = T.DESCR 
--UPDATE #FINAL SET TENDERID=0 WHERE TENDERID IS NULL

--SELECT * FROM #FINAL WHERE TENDERID=0 ORDER BY TOOLCODE 

--SELECT TOOLCODE,TENDERID INTO #MISSING FROM #FINAL WHERE TENDERID=0

--UPDATE #MISSING SET 
-- TENDERID=ITEMID FROM TENDERITEMS INNER JOIN #MISSING ON #MISSING.TOOLCODE=TENDERITEMS.RESCODE WHERE TENDERITEMS.BORG=168 AND TENDERITEMS.CATEGORY='SUBCONTRACTORS' 


--UPDATE BT.WORKORDER SET TENDERITEMID=M.TENDERID 
--FROM #MISSING M INNER JOIN BT.WORKORDER BTW ON BTW.MINORWORKHEADID=M.TOOLCODE WHERE BTW.PROJECTCODE=6 AND BTW.TENDERITEMID=0 

--SELECT * FROM BT.WORKORDER WHERE PROJECTCODE=6 ORDER BY TENDERITEMID 

--UPDATE [BT].[WORKORDER] SET   TENDERITEMID = F.TENDERID FROM #FINAL F INNER JOIN [BT].[WORKORDER] BTW ON F.TOOLCODE=BTW.MinorWorkHeadID  WHERE BTW.TENDERITEMID=0
 