/****** Object:  Procedure [BT].[spCurrentShoppingList]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE BT.spCurrentShoppingList(@PROJECTCODE INT) 
AS
 
CREATE TABLE #TEMP0(CATEGORY VARCHAR(15), RESCODE VARCHAR(25),BUDGETCATEGORYHEAD VARCHAR(200),QTY DECIMAL(18,2),UNIT  VARCHAR(10), 
RATE DECIMAL(18,2), BUDGET DECIMAL(18,2), ORDEREDQTY DECIMAL(18,2), ORDREDAMOUNT DECIMAL(18,2) )

INSERT INTO #TEMP0 
SELECT 'Lumsum',RESCODE,SUBSTRING(DESCR,1,200),0,'LumSum',
0,QTY,0,ORDEREDAMOUNT FROM TENDERITEMS WHERE CATEGORY='MATERIAL' AND UNIT='LumSum' 

UPDATE #TEMP0 SET BUDGET=ORDREDAMOUNT+500  WHERE ORDREDAMOUNT>BUDGET 

INSERT INTO #TEMP0 
SELECT 'Qty/Rate',RESCODE,SUBSTRING(DESCR,1,200),QTY,UNIT,
RATE,(QTY*RATE),ORDEREDQTY,ORDEREDAMOUNT FROM TENDERITEMS WHERE CATEGORY='MATERIAL' AND UNIT<>'LumSum' 

UPDATE #TEMP0 SET QTY=NULL,RATE=NULL,ORDEREDQTY=NULL  WHERE CATEGORY='Lumsum' 

SELECT * FROM #TEMP0    ORDER BY CATEGORY,BUDGETCATEGORYHEAD