/****** Object:  Procedure [BT].[spDeleteWorkOrderItem]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE BT.spDeleteWorkOrderItem(@PROJECTID INT,@TOOLCODE VARCHAR(15))
AS
DECLARE @BORGID INT
DECLARE @ITEMID INT 
DECLARE @ORDEREDQTY DECIMAL(18,2)

SELECT @BORGID = BORGID FROM BT.PROJECTS WHERE PROJECTID=@PROJECTID 

SELECT @ITEMID=ITEMID,@ORDEREDQTY=ORDEREDQTY 
FROM TENDERITEMS 
WHERE BORG=@BORGID AND RESCODE=@TOOLCODE 

IF (@ORDEREDQTY>0) 
 BEGIN
     UPDATE TENDERITEMS SET RATE=0,QTY=0 WHERE ITEMID=@ITEMID 
 END
ELSE
 BEGIN 
   DELETE FROM TENDERITEMS WHERE BORG=@BORGID AND RESCODE=@TOOLCODE
   DELETE FROM BT.WORKORDER WHERE PROJECTCODE=@PROJECTID AND MINORWORKHEADID=@TOOLCODE 
   DELETE FROM BT.WORKORDERITEMS WHERE PROJECT=@PROJECTID AND TOOLCODE=@TOOLCODE 
 END