/****** Object:  Procedure [BT].[spFetchWOSpreadDetails]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE [BT].[spFetchWOSpreadDetails](@PROJECTCODE INT,@STARTPERIOD INT,@ENDPERIOD INT)
AS

SELECT  LTRIM(RTRIM(YPM.YEAR))+'/'+LTRIM(RTRIM(YPM.MONTHNAME)) AS PERIODNAME 
FROM BT.YearPeriodMaster YPM WHERE YPM.YearPeriodID IN 
(SELECT YEARPERIODCODE FROM BT.WORKORDERSPREAD BTWOS 
 INNER JOIN BT.WORKORDER BTWO ON BTWOS.WorkOrderCode = BTWO.WorkOrderID
 WHERE PROJECTCODE =@PROJECTCODE AND  YEARPERIODCODE BETWEEN @STARTPERIOD AND @ENDPERIOD) ORDER BY YPM.YearPeriodID
 


 