/****** Object:  Procedure [BT].[spFetchDPRManPowerReport]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE [BT].[spFetchDPRManPowerReport](@PROJECTCODE INT, @STARTDATESTRING  VARCHAR(15),@ENDDATESTRING  VARCHAR(15)) 
AS
DECLARE @DPRSTARTDATE DATETIME 
SET @DPRSTARTDATE = CONVERT(DATETIME,@STARTDATESTRING,103)
DECLARE @DPRENDDATE DATETIME 
SET @DPRENDDATE = CONVERT(DATETIME,@ENDDATESTRING,103)
CREATE TABLE #TEMP0(DPRID INT, SKILLTYPEID VARCHAR(5),SKILLNAME VARCHAR(100) , DPRQTY DECIMAL(18,2), DPRDATE DATETIME) 

INSERT INTO #TEMP0(SKILLTYPEID,SKILLNAME ) 
SELECT SKILLTYPEID,SKILLNAME FROM BT.MANPOWERTYPES  


SELECT  DM.DPRID,SKILLTYPEID,SKILLNAME, DM.DPRQTY,CONVERT(DATETIME,DM.DPRDATE,103) as DPRDATE
FROM BT.DPRMANPOWER DM JOIN #TEMP0 MT ON DM.ManpowerSkillTypeID=MT.SKILLTYPEID  WHERE PROJECTCODE=@PROJECTCODE 
AND DM.DPRDATE BETWEEN @DPRSTARTDATE AND @DPRENDDATE 
ORDER BY DPRDATE 