/****** Object:  Procedure [BT].[spFetchOverheadSpreadDetails]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE [BT].[spFetchOverheadSpreadDetails](@PROJECTCODE INT,@STARTPERIOD INT,@ENDPERIOD INT)
AS

SELECT  LTRIM(RTRIM(YPM.YEAR))+'/'+LTRIM(RTRIM(YPM.MONTHNAME)) AS PERIODNAME 
FROM BT.YearPeriodMaster YPM WHERE YPM.YearPeriodID IN 
(SELECT YEARPERIODCODE FROM BT.OVERHEADSPREAD BTOVS
 INNER JOIN BT.OVERHEAD BTOV ON BTOVS.OVERHEADCODE  = BTOV.OVERHEADID
  WHERE PROJECTCODE =@PROJECTCODE AND  YEARPERIODCODE BETWEEN @STARTPERIOD AND @ENDPERIOD) ORDER BY YPM.YearPeriodID
 