/****** Object:  Procedure [BT].[spFetchBOQSummary]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE [BT].[spFetchBOQSummary](@PROJECTID INT,@STARTDATESTRING VARCHAR(15),@ENDDATESTRING VARCHAR(15))
AS
DECLARE @PROJECTNAME VARCHAR(50)
DECLARE @STARTDATE DATETIME
DECLARE @ENDDATE DATETIME
 
SET @STARTDATE = CONVERT(DATETIME,@STARTDATESTRING,103)
SET @ENDDATE = CONVERT(DATETIME,@ENDDATESTRING,103)
SELECT @PROJECTNAME = PROJECTNAME FROM BT.PROJECTS WHERE PROJECTID=@PROJECTID 

 

SELECT @PROJECTNAME PROJECTNAME,CONVERT(VARCHAR(10),DM.DPRDATE,103) DPRDATESTRING,MN.SKILLNAME,DM.DPRQTY 
FROM BT.DPRMANPOWER DM INNER JOIN BT.MANPOWERTYPES MN ON DM.MANPOWERSKILLTYPEID=MN.SKILLTYPEID 
WHERE PROJECTCODE=@PROJECTID AND DM.DPRDATE BETWEEN @STARTDATE AND @ENDDATE 
ORDER BY DPRDATE