/****** Object:  Procedure [BT].[spFetchDPRReport]    Committed by VersionSQL https://www.versionsql.com ******/

--Select * from bt.dpr
--select * from bt.sales

--[BT].[spFetchDPRReport] 2,'30-01-2018','01-10-2019'
CREATE PROCEDURE [BT].[spFetchDPRReport](@PROJECTCODE INT, @STARTDATESTRING  VARCHAR(15),@ENDDATESTRING  VARCHAR(15)) 
AS
DECLARE @DPRSTARTDATE DATETIME 
SET @DPRSTARTDATE = CONVERT(DATETIME,@STARTDATESTRING,103)
DECLARE @DPRENDDATE DATETIME 
SET @DPRENDDATE = CONVERT(DATETIME,@ENDDATESTRING,103)
CREATE TABLE #TEMP0(DPRID INT, BOQNUMBER VARCHAR(10),BOQ VARCHAR(600),UOM VARCHAR(15), DPRQTY DECIMAL(18,2), DPRDATE DATETIME) 

INSERT INTO #TEMP0(BOQNUMBER,BOQ,UOM,DPRDATE)
SELECT BOQNUMBER,BOQ,UOM,null FROM BT.SALES WHERE PROJECTCODE=@PROJECTCODE


SELECT  D.DPRID,D.BOQNUMBER,BOQ,UOM,D.DPRQTY,CONVERT(DATETIME,D.DPRDATE,103) as DPRDATE
FROM BT.DPR D JOIN #TEMP0 S ON D.BOQNumber=S.BOQNumber WHERE D.PROJECTCODE=@PROJECTCODE
AND D.DPRDATE BETWEEN @DPRSTARTDATE AND @DPRENDDATE ORDER BY DPRDATE 