/****** Object:  Procedure [BT].[spFetchClientBillDPR]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE procedure [BT].[spFetchClientBillDPR](@BILLID INT)
as

DECLARE @DPRENDDATE DATETIME
DECLARE @PROJECTCODE INT
DECLARE @CLIENTBILLNO VARCHAR(15)

 

SELECT @CLIENTBILLNO=BILLNUMBER, @PROJECTCODE = PROJECTCODE,@DPRENDDATE=DPRENDDATE  FROM BT.CLIENTBILL WHERE ID=@BILLID

CREATE TABLE #TEMP0(BOQNUMBER VARCHAR(20))
INSERT INTO #TEMP0
SELECT   BOQNUMBER FROM BT.CLIENTBILLDETAILS WHERE BILLID=@BILLID 


 

--INSERT INTO BT.CLIENTBILLDETAILS
--SELECT @BILLID,BOQNUMBER,UOM,RATE,0 
--FROM BT.SALES WHERE PROJECTCODE = @PROJECTCODE AND BOQNUMBER NOT IN (SELECT BOQNUMBER FROM  #TEMP0)
 

SELECT 
 BT.BILLDETAILID,
 BT.BOQNUMBER,
 SA.BOQ,
 BT.UOM,
 BT.RATE,
 BT.BILLEDQTY,
 0 AS DPRQTY 
INTO 
 #FINAL
FROM 
 BT.CLIENTBILLDETAILS BT INNER JOIN BT.SALES SA ON BT.BOQNUMBER = SA.BOQNUMBER AND 
 SA.ProjectCode = @PROJECTCODE 
 --AND BT.BILLEDQTY>0
ORDER BY 
 BT.BOQNUMBER 

  
 
SELECT BOQNUMBER,SUM(DPRQTY) DPRQTYSUM 
INTO #DPRQTY
FROM BT.DPR WHERE PROJECTCODE=@PROJECTCODE AND DPRDATE<=@DPRENDDATE GROUP BY BOQNUMBER 

UPDATE #FINAL SET DPRQTY = S.DPRQTYSUM FROM #DPRQTY S INNER JOIN #FINAL  F ON F.BOQNUMBER = S.BOQNUMBER 

--- DELETING INDIRECT COST ----
DELETE FROM #FINAL WHERE BOQNUMBER='9000000000'


SELECT 
  BILLDETAILID,
  BOQNUMBER,
  BOQ,
  UOM,
  RATE,
  BILLEDQTY,
  (BILLEDQTY*RATE) BILLEDVALUE,
  DPRQTY ,
  (DPRQTY*RATE) DPRVALUE
FROM
   #FINAL 
SELECT @CLIENTBILLNO CLIENTBILLNO ,	 @DPRENDDATE DPRENDDATE 