/****** Object:  Procedure [BT].[spFetchDPRManPower]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE [BT].[spFetchDPRManPower](@PROJECTCODE INT, @DPRDATESTRING  VARCHAR(15)) 
AS
DECLARE @DPRDATE DATETIME 
SET @DPRDATE = CONVERT(DATETIME,@DPRDATESTRING,103)
CREATE TABLE #TEMP0(DPRID INT, SKILLTYPEID VARCHAR(5),SKILLNAME VARCHAR(100) , DPRQTY DECIMAL(18,2)) 

INSERT INTO #TEMP0(SKILLTYPEID,SKILLNAME ) 
SELECT SKILLTYPEID,SKILLNAME FROM BT.MANPOWERTYPES  


SELECT  DPRID,MANPOWERSKILLTYPEID,DPRQTY 
INTO #TEMP1 
FROM BT.DPRMANPOWER WHERE PROJECTCODE=@PROJECTCODE AND DPRDATE=@DPRDATE 



UPDATE #TEMP0 SET DPRQTY = T.DPRQTY , DPRID= T.DPRID FROM #TEMP1 T INNER JOIN #TEMP0 ON T.MANPOWERSKILLTYPEID = #TEMP0.SKILLTYPEID 

UPDATE #TEMP0 SET DPRID=0 WHERE DPRID IS NULL
UPDATE #TEMP0 SET DPRQTY = 0 WHERE DPRQTY IS NULL

SELECT DPRID,SKILLTYPEID,SKILLNAME, DPRQTY FROM #TEMP0 ORDER BY SKILLTYPEID