/****** Object:  Procedure [BT].[spFetchClientBillDetails]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE procedure [BT].[spFetchClientBillDetails](@BILLID INT,@PROJECTID INT)
as
 

CREATE TABLE #TEMP0(BOQNUMBER VARCHAR(20))
INSERT INTO #TEMP0
SELECT BOQNUMBER FROM BT.CLIENTBILLDETAILS WHERE BILLID=@BILLID 

INSERT INTO BT.CLIENTBILLDETAILS
SELECT @BILLID,BOQNUMBER,UOM,RATE,0 
FROM BT.SALES WHERE PROJECTCODE = @PROJECTID AND BOQNUMBER NOT IN (SELECT BOQNUMBER FROM  #TEMP0)
 

SELECT 
 BT.BILLDETAILID,
 BT.BOQNUMBER,
 SA.BOQ,
 BT.UOM,
 BT.RATE,
 BT.BILLEDQTY 
INTO 
 #FINAL 
FROM 
 BT.CLIENTBILLDETAILS BT INNER JOIN BT.SALES SA ON BT.BOQNUMBER = SA.BOQNUMBER 


 
--- DELETING INDIRECT COST ----
DELETE FROM #FINAL WHERE BOQNUMBER='9000000000'

SELECT * FROM #FINAL 
ORDER BY 
 BOQNUMBER 