/****** Object:  Procedure [BT].[spFetchLastRevisionIDS]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE BT.spFetchLastRevisionIDS(@UPLOADCATEGROY VARCHAR(10), @PROJECTID INT)
AS
DECLARE @MAXMAJORREVISION INT
DECLARE @MAXMINORREVISION INT 

SELECT @MAXMAJORREVISION =ISNULL( MAX(MAJORREVISION),0) FROM BT.REVISIONIDS WHERE BUDGETSHORTCODE=@UPLOADCATEGROY AND PROJECTCODE=@PROJECTID
SELECT @MAXMINORREVISION =ISNULL( MAX(MINORREVISION),0) FROM BT.REVISIONIDS WHERE BUDGETSHORTCODE=@UPLOADCATEGROY AND MAJORREVISION=@MAXMAJORREVISION AND PROJECTCODE=@PROJECTID
SELECT @MAXMAJORREVISION,@MAXMINORREVISION