/****** Object:  Procedure [BT].[spFetchDPR]    Committed by VersionSQL https://www.versionsql.com ******/

--Select * from bt.dpr
--select * from bt.sales


CREATE PROCEDURE [BT].[spFetchDPR](@PROJECTCODE INT, @DPRDATESTRING  VARCHAR(15)) 
AS
DECLARE @DPRDATE DATETIME 
SET @DPRDATE = CONVERT(DATETIME,@DPRDATESTRING,103)
CREATE TABLE #TEMP0(DPRID INT, BOQNUMBER VARCHAR(35),BOQ VARCHAR(600),UOM VARCHAR(15), DPRQTY DECIMAL(18,2)) 

INSERT INTO #TEMP0(BOQNUMBER,BOQ,UOM) 
SELECT BOQNUMBER,BOQ,UOM FROM BT.SALES WHERE PROJECTCODE=@PROJECTCODE


SELECT  DPRID,BOQNUMBER,DPRQTY 
INTO #TEMP1 
FROM BT.DPR WHERE PROJECTCODE=@PROJECTCODE AND DPRDATE=@DPRDATE 

 

UPDATE #TEMP0 SET DPRQTY = T.DPRQTY , DPRID= T.DPRID FROM #TEMP1 T INNER JOIN #TEMP0 ON T.BOQNumber = #TEMP0.BOQNUMBER 

UPDATE #TEMP0 SET DPRID=0 WHERE DPRID IS NULL
UPDATE #TEMP0 SET DPRQTY = 0 WHERE DPRQTY IS NULL

SELECT DPRID,BOQNUMBER,BOQ,UOM,DPRQTY FROM #TEMP0 ORDER BY BOQ 