/****** Object:  Procedure [BT].[spFetchBOQSummaryDayWise]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE [BT].[spFetchBOQSummaryDayWise](@PROJECTID INT,@STARTDATESTRING VARCHAR(15),@ENDDATESTRING VARCHAR(15),@INDEX INT)
AS
DECLARE @PROJECTNAME VARCHAR(50)
DECLARE @STARTDATE DATETIME
DECLARE @ENDDATE DATETIME
 
SET @STARTDATE = CONVERT(DATETIME,@STARTDATESTRING,103)
SET @ENDDATE = CONVERT(DATETIME,@ENDDATESTRING,103)
SELECT @PROJECTNAME = PROJECTNAME FROM BT.PROJECTS WHERE PROJECTID=@PROJECTID 

IF @INDEX = 1 
BEGIN

  SELECT @PROJECTNAME PROJECTNAME,
       YEAR(D.DPRDATE)  YEAR,
	   MONTH(D.DPRDATE) MONTH,
	   DATENAME(month, D.DPRDATE) MONTHNAME,
	   DAY(D.DPRDATE)   DAY,
	   D.BOQNUMBER,
	   S.BOQ ,
	   S.UOM ,
	   D.DPRQTY 
FROM 
       BT.DPR D
INNER JOIN BT.SALES S ON D.BOQNUMBER = S.BOQNUMBER
WHERE 
       D.PROJECTCODE = @PROJECTID AND DPRDATE BETWEEN @STARTDATE AND @ENDDATE  AND
	   S.PROJECTCODE = @PROJECTID         
ORDER BY 
       YEAR,
	   MONTH,
	   DAY 

END

IF @INDEX = 2
BEGIN

  SELECT @PROJECTNAME PROJECTNAME,
       YEAR(D.DPRDATE)  YEAR,
	   MONTH(D.DPRDATE) MONTH,
	   DATENAME(month, D.DPRDATE) MONTHNAME,
	   DAY(D.DPRDATE)   DAY,
	   D.BOQNUMBER,
	   S.BOQ ,
	   S.UOM ,
	   ( D.DPRQTY * S.RATE ) BOQVALUE
FROM 
       BT.DPR D
INNER JOIN BT.SALES S ON D.BOQNUMBER = S.BOQNUMBER
WHERE 
       D.PROJECTCODE = @PROJECTID AND DPRDATE BETWEEN @STARTDATE AND @ENDDATE  AND
	   S.PROJECTCODE = @PROJECTID         
ORDER BY 
       YEAR,
	   MONTH,
	   DAY 

END