/****** Object:  Procedure [BT].[spFetchMaterialSpreadLumpSumDetails]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE [BT].[spFetchMaterialSpreadLumpSumDetails](@PROJECTCODE INT,@STARTPERIOD INT,@ENDPERIOD INT)
AS


SELECT  LTRIM(RTRIM(YPM.YEAR))+'/'+LTRIM(RTRIM(YPM.MONTHNAME)) AS PERIODNAME 
FROM BT.YearPeriodMaster YPM WHERE YPM.YearPeriodID IN 
(SELECT YEARPERIODCODE FROM BT.MATERIALLUMPSUMSPREAD BTMS 
 INNER JOIN BT.MATERIALLUMPSUM BTMA ON BTMS.MATERIALCODE = BTMA.MATERIALID
 WHERE PROJECTCODE = @PROJECTCODE  AND  YEARPERIODCODE BETWEEN @STARTPERIOD AND @ENDPERIOD) ORDER BY YPM.YearPeriodID
 



 