/****** Object:  Procedure [BT].[spGetMaterialLumpSumDetails]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE [BT].[spGetMaterialLumpSumDetails](@PROJECTCODE INT,@STARTPERIOD INT, @ENDPERIOD INT)
AS

SELECT * INTO #TEMP0 FROM [BT].[TempMaterialLumpSumSpread]



INSERT INTO #TEMP0(MATERIALID,GLCODE,LEDGERNAME,AMOUNT)
SELECT 
    MA.MATERIALID,
    MA.GLCODE,
	LA.LEDGERNAME,
    MA.AMOUNT 
FROM 
    [BT].[MATERIALLUMPSUM] MA INNER JOIN  LEDGERCODES LA
ON  
    MA.GLCODE = LA.LEDGERCODE 
WHERE 
    MA.PROJECTCODE = @PROJECTCODE 
 
 


DECLARE @SQL0 VARCHAR(4000)
DECLARE @SQL1 VARCHAR(200)
DECLARE @SQL2 VARCHAR(200)
DECLARE @SQL3 VARCHAR(200)
DECLARE @SQL4 VARCHAR(4000)
DECLARE @COUNTER INT
DECLARE @PERIODID INT 

SET @PERIODID=@STARTPERIOD
SET @COUNTER=0
SET @SQL0 = 'SELECT [GLCode],[LedgerName] ,[AMOUNT],' 
SET @SQL1 =''
SET @SQL2 =''
SET @SQL3 =''
 
WHILE @PERIODID <=@ENDPERIOD
BEGIN

   SET @COUNTER = @COUNTER+1
   SET @SQL1 = 'UPDATE #TEMP0 SET ['+LTRIM(RTRIM(STR(@COUNTER)))+'A]= BTS.AMOUNT  FROM BT.MATERIALLUMPSUMSPREAD BTS INNER JOIN #TEMP0 ON #TEMP0.GLCODE= BTS.GLCODE AND #TEMP0.MATERIALID = BTS.MATERIALCODE WHERE YEARPERIODCODE='+LTRIM(RTRIM(STR(@PERIODID)))
   EXEC(@SQL1)
   SET @SQL0 = @SQL0 + '['+LTRIM(RTRIM(STR(@COUNTER)))+'A], '

   SET @PERIODID = @PERIODID+1

   
END

 

SET @SQL4 = SUBSTRING(@SQL0,1,LEN(@SQL0)-1)+' FROM #TEMP0 ORDER BY GLCODE' 

EXEC(@SQL4)
 