/****** Object:  Procedure [BT].[spGetSalesDetails]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE [BT].[spGetSalesDetails](@PROJECTCODE INT,@STARTPERIOD INT, @ENDPERIOD INT,@REVISIONID DECIMAL(6,2) )
AS

SELECT * INTO #TEMP0 FROM BT.TempSaleSpread

 
 
IF @REVISIONID = -1.0 
 BEGIN 
 
   INSERT INTO #TEMP0(BOQNUMBER,BOQ,UOM,QTY,RATE,AMOUNT)
   SELECT 
       SA.BOQNUMBER,
	   SA.BOQ,
	   SA.UOM,
	   SA.QTY,
	   SA.RATE,
	   (SA.QTY*SA.RATE) AMOUNT
   FROM BT.SALES SA 
   WHERE 
     SA.PROJECTCODE = @PROJECTCODE  
   
   SELECT BOQNUMBER,
		  SUM(QTY) QTY,
		  SUM(AMOUNT) AMOUNT 
	INTO #TEMP1
	FROM #TEMP0 
	GROUP BY BOQNUMBER 
	ALTER TABLE #TEMP1 ADD RATE DECIMAL(18,2)
	UPDATE #TEMP1 SET RATE=AMOUNT/QTY WHERE QTY>0
	UPDATE #TEMP1 SET RATE=0 WHERE QTY=0
	UPDATE #TEMP0 
	SET QTY=T.QTY ,RATE=T.RATE,AMOUNT=T.AMOUNT 
	FROM #TEMP1 T 
	INNER JOIN #TEMP0 ON #TEMP0.BOQNUMBER=T.BOQNUMBER 

	SELECT DISTINCT BOQNUMBER,BOQ,UOM,QTY,RATE,AMOUNT 
	INTO #TEMPZERO
	FROM #TEMP0 


	DELETE FROM #TEMP0 
	INSERT INTO #TEMP0(BOQNUMBER,BOQ,UOM,QTY,RATE,AMOUNT)
	SELECT BOQNUMBER,BOQ,UOM,QTY,RATE,AMOUNT  FROM #TEMPZERO 

 

 END 
ELSE
 BEGIN
   INSERT INTO #TEMP0(BOQNUMBER,BOQ,UOM,QTY,RATE,AMOUNT)
   SELECT 
       SA.BOQNUMBER,
	   SA.BOQ,
	   SA.UOM,
	   ISNULL(SA.QTY,0),
	   ISNULL(SA.RATE,0),
	   ISNULL((SA.QTY*SA.RATE),0) AMOUNT
   FROM BT.SALES SA 
   WHERE 
     SA.PROJECTCODE = @PROJECTCODE AND REVISIONID = @REVISIONID 

 END
  
 
SELECT BOQNUMBER,YEARPERIODCODE,SUM(QTY) TOTALQTY ,SUM(QTY*RATE) TOTALAMOUNT  INTO 
#SALESPREAD 
FROM BT.SalesSpread
WHERE PROJECTCODE=@PROJECTCODE
GROUP BY BOQNUMBER ,YEARPERIODCODE

ALTER TABLE #SALESPREAD ADD RATE DECIMAL(18,2)
UPDATE #SALESPREAD SET RATE=0 WHERE RATE IS NULL
UPDATE #SALESPREAD SET TOTALAMOUNT = 0 WHERE TOTALAMOUNT IS NULL
UPDATE #SALESPREAD SET TOTALQTY =0 WHERE TOTALQTY IS NULL 

UPDATE #SALESPREAD SET RATE= TOTALAMOUNT/TOTALQTY WHERE TOTALQTY>0

SELECT BOQNUMBER,YEARPERIODCODE, TOTALQTY QTY,RATE,TOTALAMOUNT AMOUNT 
INTO #FINALSALESPREAD 
FROM #SALESPREAD 

 



--INSERT INTO #TEMP0(BOQNUMBER,BOQ,UOM,QTY,RATE,AMOUNT)
--SELECT 
--       SA.BOQNUMBEIR,
--	   SA.BOQ,
--	   SA.UOM,
--	   SA.QTY,
--	   SA.RATE,
--	   (SA.QTY*SA.RATE) AMOUNT
--FROM BT.SALES SA 
--WHERE 
--     SA.PROJECTCODE = @PROJECTCODE  
 
DECLARE @SQL0 VARCHAR(6000)
DECLARE @SQL1 VARCHAR(600)
DECLARE @SQL2 VARCHAR(600)
DECLARE @SQL3 VARCHAR(600)
DECLARE @SQL4 VARCHAR(6000)
DECLARE @COUNTER INT
DECLARE @PERIODID INT 

SET @PERIODID=@STARTPERIOD
SET @COUNTER=0
SET @SQL0 = 'SELECT [BOQNumber]      ,[BOQ]      ,[UOM]      ,[QTY]      ,[RATE]      ,[AMOUNT],' 
SET @SQL1 =''
SET @SQL2 =''
SET @SQL3 =''
 
WHILE @PERIODID <=@ENDPERIOD
BEGIN

   SET @COUNTER = @COUNTER+1
   SET @SQL1 = 'UPDATE #TEMP0 SET ['+LTRIM(RTRIM(STR(@COUNTER)))+'Q]= ISNULL(BTS.QTY,0)  FROM #FINALSALESPREAD  BTS INNER JOIN #TEMP0 ON #TEMP0.BOQNUMBER= BTS.BOQNumber WHERE YEARPERIODCODE='+LTRIM(RTRIM(STR(@PERIODID)))
   SET @SQL2 = 'UPDATE #TEMP0 SET ['+LTRIM(RTRIM(STR(@COUNTER)))+'R]= ISNULL(BTS.RATE,0)  FROM #FINALSALESPREAD  BTS INNER JOIN #TEMP0 ON #TEMP0.BOQNUMBER= BTS.BOQNumber WHERE YEARPERIODCODE='+LTRIM(RTRIM(STR(@PERIODID)))
   SET @SQL3 = 'UPDATE #TEMP0 SET ['+LTRIM(RTRIM(STR(@COUNTER)))+'A]=['+LTRIM(RTRIM(STR(@COUNTER)))+'Q]*['+LTRIM(RTRIM(STR(@COUNTER)))+'R]'
   EXEC(@SQL1)
   EXEC(@SQL2)
   EXEC(@SQL3)
   SET @SQL0 = @SQL0 + '['+LTRIM(RTRIM(STR(@COUNTER)))+'Q], ['+LTRIM(RTRIM(STR(@COUNTER)))+'R] ,['+LTRIM(RTRIM(STR(@COUNTER)))+'A],'

   SET @PERIODID = @PERIODID+1
END

 

SET @SQL4 = SUBSTRING(@SQL0,1,LEN(@SQL0)-1)+' FROM #TEMP0 ORDER BY BOQNUMBER' 

EXEC(@SQL4)
 