/****** Object:  Procedure [BT].[spGetOverheadDetails]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE [BT].[spGetOverheadDetails](@PROJECTCODE INT,@STARTPERIOD INT, @ENDPERIOD INT,@REVISIONID DECIMAL(6,2))
AS

SELECT * INTO #TEMP0 FROM  [BT].[TempOverHeadSpread]



INSERT INTO #TEMP0(GLCODE,LEDGERNAME,AMOUNT)
SELECT 
    OV.GLCODE,
	BTO.EXPENSESUBHEAD,
    OV.AMOUNT
FROM 
    [BT].[OVERHEAD] OV INNER JOIN  BT.OVERHEADEXPENSEMASTER BTO
ON  
    OV.GLCODE = BTO.GLCODE 
WHERE 
    OV.PROJECTCODE = @PROJECTCODE AND OV.REVISIONID = @REVISIONID 
 
 

DECLARE @SQL0 VARCHAR(4000)
DECLARE @SQL1 VARCHAR(200)
DECLARE @SQL2 VARCHAR(200)
DECLARE @SQL3 VARCHAR(200)
DECLARE @SQL4 VARCHAR(4000)
DECLARE @COUNTER INT
DECLARE @PERIODID INT 

SET @PERIODID=@STARTPERIOD
SET @COUNTER=0
SET @SQL0 = 'SELECT [GLCode],[LedgerName] ,[AMOUNT],' 
SET @SQL1 =''
SET @SQL2 =''
SET @SQL3 =''
 
WHILE @PERIODID <=@ENDPERIOD
BEGIN

   SET @COUNTER = @COUNTER+1
   SET @SQL1 = 'UPDATE #TEMP0 SET ['+LTRIM(RTRIM(STR(@COUNTER)))+'A]= BTS.AMOUNT  FROM BT.OVERHEADSPREAD BTS INNER JOIN #TEMP0 ON #TEMP0.GLCODE= BTS.GLCODE   WHERE YEARPERIODCODE='+LTRIM(RTRIM(STR(@PERIODID)))
   SET @SQL1 = @SQL1 + '  AND BTS.REVISIONID = ' + LTRIM(RTRIM(@REVISIONID)) 
   EXEC(@SQL1)
   SET @SQL0 = @SQL0 + '['+LTRIM(RTRIM(STR(@COUNTER)))+'A], '

   SET @PERIODID = @PERIODID+1

   
END

 

SET @SQL4 = SUBSTRING(@SQL0,1,LEN(@SQL0)-1)+' FROM #TEMP0 ORDER BY GLCODE' 

EXEC(@SQL4)
 