/****** Object:  Procedure [BT].[spGetLiveMaterialBudget]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE [BT].[spGetLiveMaterialBudget](@PROJECTCODE INT)
AS

SELECT TOOLCODE,SUM(BUDGETQTY) BUDGETQTY, SUM(BUDGETAMOUNT) BUDGETAMOUNT 
INTO #TEMP0
FROM BT.ProjectMaterialBudgetMaster 
WHERE PROJECTCODE=@PROJECTCODE
GROUP BY TOOLCODE 



SELECT T.TOOLCODE,T.BUDGETQTY,T.BUDGETAMOUNT,M.MATERIALMAJORHEAD,M.TEMPLATENAME,M.CATEGORY,M.UOM
INTO #TEMP1 
FROM #TEMP0 T INNER JOIN BT.MasterMaterialBudget M  ON T.TOOLCODE = M.TEMPLATECODE 
 

UPDATE #TEMP1 SET BUDGETQTY=0 WHERE UPPER(UOM)='L' 


 


SELECT TOOLCODE,
       MATERIALMAJORHEAD CATEGORY,
	   CASE 
	     WHEN UPPER(UOM)='L'  THEN 'Lumpsum Purchase' 
		 WHEN UPPER(UOM)='Q'  THEN 'Quantity/Rate' 
	   END AS TYPEOFPURCHASE ,
	   TEMPLATENAME AS MATERIALNAME,
	   CASE 
	     WHEN UPPER(CATEGORY)='LUMPSUM' THEN '' 
		 ELSE UPPER(CATEGORY) 
		END AS UOM,
	   BUDGETQTY,
	   BUDGETAMOUNT 
INTO #FINAL 
FROM #TEMP1 
ORDER BY UOM,MATERIALMAJORHEAD,MATERIALNAME 

UPDATE #FINAL SET BUDGETQTY = NULL WHERE UOM=''
SELECT * FROM #FINAL ORDER BY TYPEOFPURCHASE,TOOLCODE

 