/****** Object:  Procedure [BT].[spGetReleaseHistory]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE [BT].[spGetReleaseHistory](@PROJECTID INT,@TOOLCODE VARCHAR(15))
AS
BEGIN
  CREATE TABLE #TEMP0(RELEASESUMMARYID INT,RELEASEYEAR CHAR(4),RELEASEMONTH VARCHAR(25),RELEASEDATE DATETIME,RELEASEQTY DECIMAL(18,4),UNRELEASE BIT)
  INSERT INTO #TEMP0 
  SELECT RELEASESUMMARYID,YEAR(RELEASEDATE) RELEASEYEAR,FORMAT(RELEASEDATE, 'MMMM') AS RELEASEMONTH,RELEASEDATE,RELEASEQTY,0 AS UNRELEASE
  FROM BT.RELEASESUMMARY WHERE PROJECTCODE=@PROJECTID AND TOOLCODE=@TOOLCODE ORDER BY RELEASEDATE

  SELECT * FROM #TEMP0 ORDER  BY RELEASESUMMARYID
END

 