/****** Object:  Procedure [BT].[spGetWebWorkOrderItems]    Committed by VersionSQL https://www.versionsql.com ******/

--SELECT * FROM BT.BMTUSERS
--SELECT * FROM BT.WEBWOUSERPROEJCTS
--SELECT * FROM BT.WEBWORKORDERITEMS WHERE BSORGID=118

CREATE PROCEDURE [BT].[spGetWebWorkOrderItems](@BSLOGINID VARCHAR(15))
AS
DECLARE @BSORGID INT
SELECT @BSORGID = BSORGID FROM BT.WEBWOUSERPROEJCTS WHERE BSLOGINID=@BSLOGINID 
 


SELECT [WWWITEMCODE]
      ,[BMTPROJECTCODE]
      ,[BSORGID]
      ,[PROJECTCODE]
      ,[CONTRACTCODE]
      ,[DELIVERYID]
      ,[ACTIVITY]
      ,[LEDGERCODE]
      ,[CLIENTBOQ]
      ,[BOQCODE]
      ,[BOQDESCRIPTION]
      ,ITEMID AS [WORKITEMCODE]
      ,[WORKITEMDESCRIPTION]
      ,[WORKORDERITEMDESCRIPTION]
      ,[UOM]
      ,[RATE]
      ,[TOTALQTY]
      ,[ORDEREDQTY]
      ,[ORDEREDAMOUNT]
	  ,@BSLOGINID BSLOGINID
INTO #TEMP0 
FROM 
		[BT].[WEBWORKORDERITEMS]
WHERE 
		BSORGID = @BSORGID 

UPDATE #TEMP0 SET TOTALQTY=0

DELETE FROM #TEMP0 WHERE CLIENTBOQ='NONBOQ' 

SELECT * FROM #TEMP0  ORDER BY  CLIENTBOQ,WORKITEMCODE,WORKITEMDESCRIPTION 

 