/****** Object:  Procedure [BT].[spGetMaterialQtyDetails210219]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE [BT].[spGetMaterialQtyDetails210219](@PROJECTCODE INT,@STARTPERIOD INT, @ENDPERIOD INT)
AS

SELECT * INTO #TEMP0 FROM [BT].[TempMaterialSpread]
 
SELECT 
	--BTM.ProjectMaterialBudgetCode,
	BTM.PROJECTCODE,
	BTM.TOOLCODE,
	BTD.MONTHID,
	BTM.BUDGETQTY CUMQTY,
	BTM.BudgetRate CUMRATE,
	BTM.BUDGETAMOUNT CUMAMOUNT,
	BTD.BudgetQty,
	BTD.BUDGETRATE,
	BTD.BudgetAmount
INTO #TEMPBUDGET
FROM 
    [BT].[ProjectMaterialBudgetmaster] BTM INNER JOIN [BT].[ProjectMaterialBudgetdETAIL] BTD
ON 
    BTM.ProjectMaterialBudgetCode = BTD.ProjectMaterialBudgetID 
WHERE BTM.ProjectCode = @PROJECTCODE
  


INSERT INTO #TEMP0(TOOLCODE,BUDGETTOOLNAME,CATEGORY,UOM,QTY,RATE,AMOUNT)
SELECT 
    BTPM.TOOLCODE,
    BT.TEMPLATENAME,
	BT.CATEGORY,
	BT.UOM,
	BTPM.BUDGETQTY,
	BTPM.BUDGETRATE,
	BTPM.BUDGETAMOUNT
FROM BT.ProjectMaterialBudgetmaster BTPM  INNER JOIN BT.mastermaterialbudget BT ON BT.TEMPLATECODE = BTPM.TOOLCODE 
WHERE 
    BTPM.PROJECTCODE = @PROJECTCODE 


 --select * from #TEMP0
 select * from #TEMPBUDGET where toolcode='2011010005'


DECLARE @SQL0 VARCHAR(4000)
DECLARE @SQL1 VARCHAR(200)
DECLARE @SQL2 VARCHAR(200)
DECLARE @SQL3 VARCHAR(200)
DECLARE @SQL4 VARCHAR(4000)
DECLARE @COUNTER INT
DECLARE @PERIODID INT 

SET @PERIODID=@STARTPERIOD
SET @COUNTER=0
SET @SQL0 = 'SELECT [TOOLCODE]      ,[BUDGETTOOLNAME]      ,[CATEGORY], [UOM]      ,[QTY]      ,[RATE]      ,[AMOUNT],' 
SET @SQL1 =''
SET @SQL2 =''
SET @SQL3 =''
 
WHILE @PERIODID <=@ENDPERIOD
BEGIN

   SET @COUNTER = @COUNTER+1
   SET @SQL1 = 'UPDATE #TEMP0 SET ['+LTRIM(RTRIM(STR(@COUNTER)))+'Q]= BUDGETQTY     FROM  #TEMPBUDGET   INNER JOIN #TEMP0 ON #TEMP0.TOOLCODE= #TEMPBUDGET.TOOLCODE   WHERE MONTHID='+LTRIM(RTRIM(STR(@PERIODID)))
   SET @SQL2 = 'UPDATE #TEMP0 SET ['+LTRIM(RTRIM(STR(@COUNTER)))+'R]= BUDGETRATE    FROM  #TEMPBUDGET   INNER JOIN #TEMP0 ON #TEMP0.TOOLCODE= #TEMPBUDGET.TOOLCODE   WHERE MONTHID='+LTRIM(RTRIM(STR(@PERIODID)))
   SET @SQL3 = 'UPDATE #TEMP0 SET ['+LTRIM(RTRIM(STR(@COUNTER)))+'A]= BUDGETAMOUNT  FROM  #TEMPBUDGET   INNER JOIN #TEMP0 ON #TEMP0.TOOLCODE= #TEMPBUDGET.TOOLCODE   WHERE MONTHID='+LTRIM(RTRIM(STR(@PERIODID)))
   EXEC(@SQL1)
   EXEC(@SQL2)
   EXEC(@SQL3)
   SET @SQL0 = @SQL0 + '['+LTRIM(RTRIM(STR(@COUNTER)))+'Q], ['+LTRIM(RTRIM(STR(@COUNTER)))+'R] ,['+LTRIM(RTRIM(STR(@COUNTER)))+'A],'

   SET @PERIODID = @PERIODID+1

   
END



SET @SQL4 = SUBSTRING(@SQL0,1,LEN(@SQL0)-1)+' FROM #TEMP0 ORDER BY TOOLCODE' 

 
EXEC(@SQL4)
 