/****** Object:  Procedure [BT].[spGetMovementDetails]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE BT.spGetMovementDetails(@HEADERID VARCHAR(35))
AS
SELECT  
       [TOOLCODE]
      ,[TOOLNAME]
      ,[BUYINGCATEGORY]
      ,[CONVERTIONFACTOR]
	  ,[REQNUMBER]
      ,[REQDATE]
	  ,LINENUMBER
      ,[STOCKCODE]
      ,[STOCKNAME]
      ,[PRQTY]
	  ,PRUOM
      ,[PRRATE]
      ,[PRAMOUNT]
      ,[REJECTQTY]
      ,[CANCELLEDQTY]
      ,[PRSTATUS] PRSTATUSID
      ,[BUDGETPRQTY]
      ,[ORDNUMBER]
      ,[ORDDATE]
      ,[ORDQTY]
      ,[ORDRATE]
      ,[ORDAMOUNT]
      ,[BUDGETORDERQTY]
      ,[PRPOQTYDIFF]
      ,[BUDGETPRPODIFF]
      ,[ORDSTATUS] ORDSTATUSID
      ,[DELIVEREDQTY]
      ,[DELIVERYAMOUNT]
      ,[BUDGETDELIVERY]
      ,[COMPLETED]
      ,[ORDCOMPDIFF]
      ,[BUDGETORDCOMPDIFF]
  INTO #TEMP0 
  FROM [BT].[BUDGETMATERIALMOVEMENTDETAIL]
  WHERE HEADERID=@HEADERID

  UPDATE #TEMP0 SET BUYINGCATEGORY = 'Qty Based' WHERE BUYINGCATEGORY='Q'
  UPDATE #TEMP0 SET BUYINGCATEGORY = 'LumpSum'  WHERE BUYINGCATEGORY='L'

  ALTER TABLE  #TEMP0 ADD PRSTATUS VARCHAR(25)
  ALTER TABLE  #TEMP0 ADD ORDERSTATUS VARCHAR(25)
  UPDATE #TEMP0 SET PRSTATUS = 'OPEN'  WHERE PRSTATUSID IN (163,32) 
  UPDATE #TEMP0 SET PRSTATUS = 'CANCELLED'  WHERE PRSTATUSID = 36
  UPDATE #TEMP0 SET PRSTATUS = 'Rejected'  WHERE PRSTATUSID=202
  UPDATE #TEMP0 SET ORDERSTATUS = 'PO ReadY' WHERE ORDSTATUSID=41
  UPDATE #TEMP0 SET ORDERSTATUS = 'COMPLETED' WHERE ORDSTATUSID=274

  SELECT   
    PROJECTNAME,
	TOOLCODE,
	MAJORHEAD,
	TOOLNAME,
	CATEGORY,
	UOM,
	BUDGET,
	BUDGETRATE,
	RELEASED,
	FORPURCHASE,
	OPENPR,
	CANCELLED,
	REJECTED,
	ORDERED,
	DELIVERY,
	COMPLETED
  INTO #HEADER 
  FROM BT.BUDGETMATERAILMOVEMENTHEAD
  WHERE HEADERID=@HEADERID 
      
  SELECT 
	   [REQNUMBER]
      ,[REQDATE]
	  ,LINENUMBER
      ,[STOCKCODE]
      ,[STOCKNAME]
	  ,PRUOM
      ,[PRQTY]
	  ,[CONVERTIONFACTOR]
      ,[PRRATE]
      ,[PRAMOUNT]
	  ,[PRSTATUS]  
	  ,[CANCELLEDQTY]
      ,[REJECTQTY]
      ,[BUDGETPRQTY]
      ,[ORDNUMBER]
      ,[ORDDATE]
      ,[ORDQTY]
      ,[ORDRATE]
      ,[ORDAMOUNT]
      ,[BUDGETORDERQTY]
      ,[PRPOQTYDIFF]
      ,[BUDGETPRPODIFF]
      ,[ORDERSTATUS]  
      ,[DELIVEREDQTY]
      ,[DELIVERYAMOUNT]
      ,[BUDGETDELIVERY]
      ,[COMPLETED]
      ,[ORDCOMPDIFF]
      ,[BUDGETORDCOMPDIFF]
  INTO #DETAIL
  FROM #TEMP0 
 
SELECT * FROM #HEADER 
SELECT * FROM #DETAIL 