/****** Object:  Procedure [BT].[spGetLoginDetails]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE [BT].[spGetLoginDetails](@LOGINID VARCHAR(20),@PASSWORD VARCHAR(20) )
AS

DECLARE @EXISTS INT
SELECT @EXISTS = COUNT(*) FROM USERS WHERE UPPER(LOGINID) = UPPER(@LOGINID) AND UPPER(PASSWORD) = UPPER(@PASSWORD) 
 

IF @EXISTS  = 1
BEGIN
   SELECT U.LOGINID,U.USERNAME,UB.BORGID,PR.PROJECTID,(RTRIM(PR.PROJECTCODE)+' - '+PR.PROJECTNAME) PROJECTNAME 
   FROM USERS U INNER JOIN USERSINBORGP UB ON U.USERID=UB.USERID 
             INNER JOIN PROJECTS PR ON UB.BORGID = PR.BORGID
			 INNER JOIN BT.PROJECTS BTP ON BTP.BORGID = PR.BORGID 
			  WHERE LOGINID=@LOGINID 
END