/****** Object:  Procedure [BT].[spGetWODetails]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE [BT].[spGetWODetails](@PROJECTCODE INT,@REVISIONID DECIMAL(6,2) )
AS

CREATE TABLE #TEMP0(INDEXID INT PRIMARY KEY IDENTITY(1,1),BOQCODE VARCHAR(20),CLIENTBOQ VARCHAR(50),BOQ VARCHAR(600),WORKHEADID VARCHAR(15),DESCRIPTION VARCHAR(600),UOM VARCHAR(20),TOTALQTY DECIMAL(18,2),RATE DECIMAL(18,2),AMOUNT DECIMAL(18,2))

IF (@REVISIONID = -1 ) 
 BEGIN 
    INSERT INTO #TEMP0(BOQCODE,WORKHEADID,UOM,TOTALQTY,RATE,AMOUNT) 
	SELECT 
	BOQCODE, MINORWORKHEADID,UOM,TOTALQTY,RATE,(TOTALQTY*RATE) 
	FROM 
	BT.WORKORDER WHERE PROJECTCODE=@PROJECTCODE  ORDER BY BOQCODE 
 	

	UPDATE #TEMP0 
	  SET BOQ = S.BOQ ,CLIENTBOQ = S.CLIENTBOQ 
	  FROM BT.SALES S INNER JOIN #TEMP0 ON #TEMP0.BOQCODE= S.BOQNUMBER WHERE S.PROJECTCODE=@PROJECTCODE 

	UPDATE #TEMP0 
	  SET DESCRIPTION = UPPER(WI.WORKDESCRIPTION) 
	  FROM BT.WORKORDERITEMS WI INNER JOIN #TEMP0 ON #TEMP0.WORKHEADID = WI.TOOLCODE 
	  WHERE WI.PROJECT=@PROJECTCODE  

    SELECT BOQCODE,CLIENTBOQ,BOQ,WORKHEADID,DESCRIPTION,UOM,TOTALQTY,RATE,AMOUNT  FROM #TEMP0 ORDER BY INDEXID

 
 END
ELSE
 BEGIN
	INSERT INTO #TEMP0(BOQCODE,WORKHEADID,UOM,TOTALQTY,RATE,AMOUNT) 
	SELECT 
	BOQCODE, MINORWORKHEADID,UOM,TOTALQTY,RATE,(TOTALQTY*RATE) 
	FROM 
	BT.WORKORDER WHERE PROJECTCODE=@PROJECTCODE AND REVISIONID=@REVISIONID 


	UPDATE #TEMP0 SET BOQ = S.BOQ FROM BT.SALES S INNER JOIN #TEMP0 ON #TEMP0.BOQCODE= S.BOQNUMBER WHERE S.PROJECTCODE=@PROJECTCODE 
	UPDATE #TEMP0 SET DESCRIPTION = UPPER(WI.WORKDESCRIPTION) FROM BT.WORKORDERITEMS WI INNER JOIN #TEMP0 ON #TEMP0.WORKHEADID = WI.TOOLCODE WHERE WI.PROJECT=@PROJECTCODE 

	SELECT * FROM #TEMP0 ORDER BY BOQ,WORKHEADID 

END
 
 


 