/****** Object:  Procedure [BT].[spInsertMonthlyBudget]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE  PROCEDURE [BT].[spInsertMonthlyBudget](@PROJECTCODE INT,@TOOLCODE VARCHAR(10),@CATEGORYTYPE VARCHAR(5),
@BUDGETCATEGORYNAME VARCHAR(200),@UOM VARCHAR(10),@CUMULATIVEQTY DECIMAL(18,4),@BUDGETRATE DECIMAL(18,2), @BUDGETAMOUNT DECIMAL(18,2) )
AS
DECLARE @NEXTCODE INT 
SELECT @NEXTCODE = ISNULL( MAX([MonthlyMaterialBudgetCode]),1 )  FROM [BT].[MonthlyMaterialBudget]
SET @NEXTCODE = @NEXTCODE + 1
DECLARE @EXISTING INT 

DECLARE @MONTHLYBUDGETQTY DECIMAL(18,2)
DECLARE @CURRENTBUDGETRATE DECIMAL(18,2) 
DECLARE @MONTHLYBUDGETAMOUNT DECIMAL(18,2) 
DECLARE @EXISTINGCODE INT

IF @CATEGORYTYPE = 'Q' 
 BEGIN
   SET @MONTHLYBUDGETQTY =@CUMULATIVEQTY
   SET @CURRENTBUDGETRATE = @BUDGETRATE
   SET @MONTHLYBUDGETAMOUNT =0
 END
ELSE
 BEGIN
   SET @MONTHLYBUDGETQTY =0
   SET @CURRENTBUDGETRATE = 0
   SET @MONTHLYBUDGETAMOUNT =@CUMULATIVEQTY
 END

SET @EXISTING = 0
SELECT @EXISTING = COUNT(*) FROM [BT].[MonthlyMaterialBudget] WHERE PROJECTCODE=@PROJECTCODE AND TOOLCODE=@TOOLCODE 

IF @EXISTING<>0
   SELECT @EXISTINGCODE =  MonthlyMaterialBudgetCode  FROM [BT].[MonthlyMaterialBudget] WHERE PROJECTCODE=@PROJECTCODE AND TOOLCODE=@TOOLCODE 




IF @EXISTING = 0
  BEGIN
    INSERT INTO [BT].[MonthlyMaterialBudget]([MonthlyMaterialBudgetCode],[ProjectCode],ToolCode,[CategoryType],[BudgetCategoryName],[UOM],[CumulativeQty],[BudgetRate],[BudgetAmount],[OrderedQty],[OrderValue])
    VALUES (@NEXTCODE,@PROJECTCODE,@TOOLCODE,@CATEGORYTYPE,@BUDGETCATEGORYNAME,@UOM,@MONTHLYBUDGETQTY,@CURRENTBUDGETRATE,@MONTHLYBUDGETAMOUNT,0,0)
  END
ELSE
  BEGIN
    UPDATE [BT].[MonthlyMaterialBudget] SET  CUMULATIVEQTY =   CUMULATIVEQTY + @CUMULATIVEQTY, BUDGETRATE=@BUDGETRATE  
	WHERE MonthlyMaterialBudgetCode=@EXISTINGCODE  AND  CategoryType='Q'
	UPDATE [BT].[MonthlyMaterialBudget] SET  BUDGETAMOUNT  =   BUDGETAMOUNT  + @CUMULATIVEQTY   
	WHERE MonthlyMaterialBudgetCode=@EXISTINGCODE  AND  CategoryType='L'
  END

UPDATE [BT].[MonthlyMaterialBudget] SET CumulativeQty = 0, BudgetRate = 0 WHERE CategoryType = 'L' 
UPDATE [BT].[MonthlyMaterialBudget] SET BudgetAmount =CumulativeQty * BudgetRate WHERE CategoryType = 'G'