/****** Object:  Procedure [BT].[spMasterMaterialBudget]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE BT.spMasterMaterialBudget(@TEMPLATECODE VARCHAR(15),@MATERAILMAJORHEAD VARCHAR(50),@TEMPLATENAME VARCHAR(255),@CATEGORY VARCHAR(15),@UOM VARCHAR(15))
AS
DECLARE @NEXTCODE INT
SELECT @NEXTCODE = MAX(INDEXCODE) FROM BT.MASTERMATERIALBUDGET 
SET @NEXTCODE = @NEXTCODE+1
INSERT INTO BT.MASTERMATERIALBUDGET(INDEXCODE,TEMPLATECODE,MATERIALMAJORHEAD,TEMPLATENAME,CATEGORY,UOM) VALUES 
(@NEXTCODE,@TEMPLATECODE,@MATERAILMAJORHEAD,@TEMPLATENAME,@CATEGORY,@UOM)