/****** Object:  Procedure [BT].[spPopulateWOItemRelease]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE [BT].[spPopulateWOItemRelease](@PROJECTID INT,@REVISIONID DECIMAL(8,2))
AS
SELECT 
  BTW.MINORWORKHEADID   TOOLCODE,
  BTW.BOQCODE,
  BTWI.WORKDESCRIPTION  [WORK DESCRIPTION],
  BTW.UOM,
  BTW.TOTALQTY ,
  BTW.RATE 
INTO 
  #TEMP0 
FROM 
  BT.WORKORDER BTW 
  INNER JOIN BT.WORKORDERITEMS BTWI ON BTW.MINORWORKHEADID=BTWI.TOOLCODE 
WHERE 
  BTW.PROJECTCODE = @PROJECTID AND 
  BTW.REVISIONID  = @REVISIONID  AND
  BTWI.PROJECT= @PROJECTID AND 
  BTW.ReleaseStatus = 0
 

ALTER TABLE #TEMP0 ADD BOQ VARCHAR(500)
UPDATE #TEMP0 SET BOQ='NON BOQ' 

UPDATE #TEMP0 SET BOQ  = SA.CLIENTBOQ+' - '+SA.BOQ FROM BT.SALES SA WHERE SA.BOQNUMBER=#TEMP0.BOQCODE AND SA.PROJECTCODE=@PROJECTID

SELECT TOOLCODE,BOQ,[WORK DESCRIPTION],UOM,TOTALQTY,RATE FROM #TEMP0 ORDER BY BOQ

 