/****** Object:  Procedure [BT].[spQuickBudgetLines]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE [BT].[spQuickBudgetLines](@PROJECTID INT,@BOQNUMBER VARCHAR(15)) 
AS
DECLARE @START INT
DECLARE @END   INT
DECLARE @SALESCODE INT 
SELECT @START = BEGINYEARPERIODCODE,@END=EndYearPeriodCode FROM BT.PROJECTS WHERE PROJECTID=@PROJECTID 
CREATE TABLE #TEMP0(YEAR INT,MONTHNAME VARCHAR(25),QUANTITY DECIMAL(18,4), RATE DECIMAL(18,4), AMOUNT DECIMAL(18,4),YEARPERIODID INT) 
INSERT INTO #TEMP0(YEAR,MONTHNAME,YEARPERIODID)
SELECT YEAR,UPPER(MONTHFULLNAME),YEARPERIODID FROM BT.YEARPERIODMASTER WHERE YearPeriodID BETWEEN @START AND @END 

IF (@BOQNUMBER='NEW')
    UPDATE #TEMP0 SET QUANTITY=0,RATE=0,AMOUNT=0
ELSE
   BEGIN 
      SELECT @SALESCODE =   SALESID FROM BT.SALES WHERE BOQNUMBER=@BOQNUMBER AND PROJECTCODE=@PROJECTID 
	  UPDATE #TEMP0 SET 
	     QUANTITY  = D.QTY ,
		 RATE = D.RATE,
		 AMOUNT = D.QTY*D.RATE 
	  FROM BT.SALESSPREAD D INNER JOIN #TEMP0 ON #TEMP0.YEARPERIODID=D.YearPeriodCode WHERE D.SALESCODE=@SALESCODE 
   END
SELECT * FROM #TEMP0 