/****** Object:  Procedure [BT].[spReleaseQtyFromCancelPRS]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE [BT].[spReleaseQtyFromCancelPRS](@BORGID INT)
AS
BEGIN
  --- THIS PROCEDURE IS A SUB SET OF THE MAIN PROCEDURE - CALLED FROM BMT TOOL
  DECLARE @REQID INT
  DECLARE @LINENUMBER INT
  DECLARE @BUDGETCROSSREFID INT
  DECLARE @REQQTY DECIMAL(18,4)
  DECLARE @JOBCARDID INT
  DECLARE @TENDERID INT

  DECLARE CANCELLIST CURSOR FOR 
  SELECT BTM.REQID,BTM.LINENUMBER,BTM.BUDGETCROSSREFID,BTM.REQQTY,RI.JOBCARDID,BTM.TENDERID  FROM 
  BT.MATERIALMOVEMENTDETAIL BTM INNER JOIN REQITEMS RI ON BTM.REQID=RI.REQID and BTM.LINENUMBER=RI.LINENUMBER 
  WHERE BTM.REQSTATUS IN (36,202) AND BTM.BORGID = @BORGID  AND RI.JOBCARDID=99

  OPEN CANCELLIST 
  FETCH NEXT FROM CANCELLIST INTO @REQID,@LINENUMBER,@BUDGETCROSSREFID,@REQQTY,@JOBCARDID,@TENDERID  

  WHILE @@FETCH_STATUS = 0
  BEGIN
    BEGIN TRAN
      UPDATE BT.MONTHLYMATERIALBUDGET SET CUMULATIVEQTY   = CUMULATIVEQTY - @REQQTY WHERE  MONTHLYMATERIALBUDGETCODE=@BUDGETCROSSREFID
	  UPDATE REQITEMS SET JOBCARDID=98 WHERE REQID=@REQID AND LINENUMBER=@LINENUMBER AND JOBCARDLEDGERID=@BUDGETCROSSREFID
	  UPDATE TENDERITEMS SET QTY = QTY - @REQQTY WHERE ITEMID = @TENDERID 
    COMMIT TRAN 

    FETCH NEXT FROM CANCELLIST INTO @REQID,@LINENUMBER,@BUDGETCROSSREFID,@REQQTY,@JOBCARDID,@TENDERID 
  END
  CLOSE CANCELLIST
  DEALLOCATE CANCELLIST 

END