/****** Object:  Procedure [BT].[spReleaseMaterail]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE [BT].[spReleaseMaterail](@PROJECTCODE INT, @TOOLCODE VARCHAR(35), @MONTHID INT,@RELEASEQTY DECIMAL(18,4))
AS

DECLARE @TOOLNAME VARCHAR(200)
DECLARE @CATEGORY VARCHAR(15)
DECLARE @UOM VARCHAR(15) 
DECLARE @MONTHLYMATERAILBUDGETCODE INT 
DECLARE @BUDGETRATE DECIMAL(18,4) 
DECLARE @TENDERITEMEXISTING INT 
DECLARE @BORGID INT 
DECLARE @PROJECTID INT                                    
DECLARE @CONTRACTID INT 
DECLARE @TENDERITEMDESCR VARCHAR(800)
DECLARE @MAXIMUMID BIGINT 

SELECT @BORGID=BORGID,@PROJECTID=BSPROJECTID,@CONTRACTID=BSCONTRACTID FROM BT.PROJECTS WHERE PROJECTID=@PROJECTCODE
SELECT @CATEGORY=UOM,@UOM=CATEGORY,@TENDERITEMDESCR=TEMPLATENAME FROM BT.MASTERMATERIALBUDGET WHERE TEMPLATECODE=@TOOLCODE
SELECT @TENDERITEMDESCR =  REPLACE(@TENDERITEMDESCR,'|','-')
SELECT @BUDGETRATE=BUDGETRATE FROM BT.PROJECTMATERIALBUDGETMASTER WHERE TOOLCODE=@TOOLCODE

BEGIN TRAN
        -- Release Summary

		SELECT @MAXIMUMID =ISNULL(MAX(RELEASESUMMARYID),0) FROM BT.RELEASESUMMARY 
		SET @MAXIMUMID = @MAXIMUMID + 1
		INSERT INTO BT.RELEASESUMMARY(RELEASESUMMARYID,RELEASEDATE, PROJECTCODE, TOOLCODE, RELEASEQTY, YEARPERIODID) 
		VALUES(@MAXIMUMID,GETDATE(),@PROJECTCODE,@TOOLCODE,@RELEASEQTY,@MONTHID)

		-- Monthly Budget Updated
		SET @MONTHLYMATERAILBUDGETCODE=0
		SELECT @MONTHLYMATERAILBUDGETCODE=ISNULL(MONTHLYMATERIALBUDGETCODE,0) FROM BT.MONTHLYMATERIALBUDGET 
		WHERE PROJECTCODE=@PROJECTCODE AND TOOLCODE=@TOOLCODE

		IF @MONTHLYMATERAILBUDGETCODE=0 
			BEGIN
				SELECT @MONTHLYMATERAILBUDGETCODE =ISNULL(MAX(MONTHLYMATERIALBUDGETCODE),0) FROM BT.MONTHLYMATERIALBUDGET 
				SET @MONTHLYMATERAILBUDGETCODE =@MONTHLYMATERAILBUDGETCODE+1
				SELECT @TOOLNAME=TEMPLATENAME,@CATEGORY=UOM,@UOM=CATEGORY FROM BT.MASTERMATERIALBUDGET WHERE TEMPLATECODE=@TOOLCODE 
				SELECT @BUDGETRATE = BUDGETRATE FROM BT.PROJECTMATERIALBUDGETMASTER WHERE PROJECTCODE=@PROJECTCODE AND TOOLCODE=@TOOLCODE 
				INSERT INTO BT.MONTHLYMATERIALBUDGET(MONTHLYMATERIALBUDGETCODE,PROJECTCODE,TOOLCODE,CATEGORYTYPE,BUDGETCATEGORYNAME,UOM,CUMULATIVEQTY,BUDGETRATE,OrderedQty,ORDERVALUE)
				VALUES(@MONTHLYMATERAILBUDGETCODE,@PROJECTCODE,@TOOLCODE,@CATEGORY,@TOOLNAME,@UOM,@RELEASEQTY,@BUDGETRATE,0,0) 
			END
		 ELSE
		    BEGIN
			    UPDATE BT.MONTHLYMATERIALBUDGET SET CumulativeQty = CumulativeQty + @RELEASEQTY WHERE MonthlyMaterialBudgetCode=@MONTHLYMATERAILBUDGETCODE
			END 

	    -- TenderItems - Search if available else create ; if existing update 

		SET @TENDERITEMEXISTING =0 

		SELECT @TENDERITEMEXISTING = COUNT(*) FROM DBO.TENDERITEMS WHERE 
		RESCODE=@TOOLCODE AND BORG=@BORGID AND PROJECT=@PROJECTID AND CONTRACT=@CONTRACTID 
		IF @TENDERITEMEXISTING=0 
			BEGIN
				INSERT INTO TENDERITEMS(RESCODE,  DESCR,           RATE,       UNIT,QTY,        BORG,    PROJECT,   CONTRACT,   LEDGERCODE, CATEGORY,  CURRENCY,BUYRATE)
				VALUES (                @TOOLCODE,@TENDERITEMDESCR,@BUDGETRATE,@UOM,@RELEASEQTY,@BORGID, @PROJECTID,@CONTRACTID,'5002900',  'MATERIAL','INR'   ,999999.99  )
			END
		ELSE
			BEGIN
				UPDATE TENDERITEMS SET QTY = QTY + @RELEASEQTY WHERE RESCODE=@TOOLCODE AND BORG=@BORGID AND PROJECT=@PROJECTID AND CONTRACT=@CONTRACTID  
			END

        -- Log File Updated
	    INSERT INTO BT.MATERIALBUDGETLOG(LOGDATE,TRANSACTIONTYPE,PROJECTCODE,QTY,RATE,AMOUNT,CROSSREFERENCEID) 
		VALUES(GETDATE(),'R',@PROJECTCODE,@TOOLCODE,@RELEASEQTY,0,@MONTHLYMATERAILBUDGETCODE)

		UPDATE BT.MonthlyMaterialBudget set budgetamount=CumulativeQty*budgetrate where categorytype='Q'
		UPDATE BT.MonthlyMaterialBudget SET BUDGETAMOUNT=CUMULATIVEQTY WHERE CATEGORYTYPE='L'

COMMIT TRAN