/****** Object:  Procedure [BT].[spReleaseWorkOrderItems]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE [BT].[spReleaseWorkOrderItems] (@PROJECTID INT,@REVISIONID DECIMAL(8,2) )
AS

DECLARE @BORGID INT
DECLARE @PROJECT VARCHAR(35)
DECLARE @CONTRACT VARCHAR(35)
DECLARE @LEDGERCODE VARCHAR(15)
DECLARE @ACTNUMBER VARCHAR(5)
DECLARE @EMPTY VARCHAR(10)
DECLARE @DELIVERYID INT

SET @EMPTY = ''
SET @LEDGERCODE='5008012'
SET @ACTNUMBER='400'

 

Update BT.WORKORDERITEMS
Set    WORKDESCRIPTION = replace(WORKDESCRIPTION, '|', '-')  
UPDATE BT.WORKORDERITEMS
Set    WORKDESCRIPTION = replace(WORKDESCRIPTION, '"', ' inch ')  
 
 
SELECT 
  BTW.WORKORDERID,
  BTW.MINORWORKHEADID   TOOLCODE,
  BTW.BOQCODE,
  BTW.UOM,
  BTW.RATE,
  BTW.TOTALQTY 
INTO 
  #TEMP0 
FROM 
  BT.WORKORDER BTW 
 WHERE 
  BTW.PROJECTCODE = @PROJECTID AND 
  BTW.REVISIONID  = @REVISIONID  AND
  BTW.ReleaseStatus = 0 

 

ALTER TABLE #TEMP0 ADD WORKDESCRIPTION VARCHAR(700)
ALTER TABLE #TEMP0 ADD WORKTYPE VARCHAR(15)
 

UPDATE #TEMP0 SET WORKDESCRIPTION = WI.WORKDESCRIPTION,WORKTYPE=WI.ITEMTYPE FROM BT.WORKORDERITEMS WI
              INNER JOIN #TEMP0 ON #TEMP0.TOOLCODE = WI.TOOLCODE  WHERE  WI.PROJECT = @PROJECTID 

 

ALTER TABLE #TEMP0 ADD BOQ VARCHAR(500)
ALTER TABLE #TEMP0 ADD CLIENTBOQ VARCHAR(50)

UPDATE #TEMP0 SET BOQ=''
UPDATE #TEMP0 SET CLIENTBOQ=''
UPDATE #TEMP0 SET CLIENTBOQ=SA.CLIENTBOQ, BOQ  = UPPER(SA.CLIENTBOQ)+'-'+UPPER(SA.BOQ)   FROM BT.SALES SA 
              WHERE SA.BOQNUMBER=#TEMP0.BOQCODE AND SA.PROJECTCODE=@PROJECTID AND SA.CLIENTBOQ <>''

UPDATE #TEMP0 SET BOQ  =  UPPER(SA.BOQ)   FROM BT.SALES SA 
              WHERE SA.BOQNUMBER=#TEMP0.BOQCODE AND SA.PROJECTCODE=@PROJECTID AND SA.CLIENTBOQ =''


ALTER TABLE #TEMP0 ADD NARRATION VARCHAR(4000)
UPDATE #TEMP0 SET NARRATION = UPPER(LTRIM(RTRIM(BOQ)))+'-' +UPPER(LTRIM(RTRIM([WORKDESCRIPTION]))) WHERE BOQ<>''
UPDATE #TEMP0 SET NARRATION = UPPER(LTRIM(RTRIM([WORKDESCRIPTION]))) WHERE BOQ=''
 

 
 

SELECT @BORGID=BORGID,
       @PROJECT = BSPROJECTID,
	   @CONTRACT = BSCONTRACTID ,
	   @DELIVERYID = BSDeliveryID
FROM BT.PROJECTS WHERE PROJECTID=@PROJECTID 

DECLARE @STARTID INT
DECLARE @STARTWWWID INT
SELECT @STARTWWWID =ISNULL(MAX(WWWITEMCODE),0) FROM BT.WEBWORKORDERITEMS
SELECT @STARTID =ISNULL(MAX(ITEMID),0) FROM TENDERITEMS 


DECLARE @WORKORDERID INT 
DECLARE @TOOLCODE VARCHAR(20)
DECLARE @BOQCODE  VARCHAR(25)
DECLARE @UOM VARCHAR(20)
DECLARE @RATE DECIMAL(18,2)
DECLARE @TOTALQTY DECIMAL(18,5)
DECLARE @WORKDESCRIPTION VARCHAR(500)
DECLARE @BOQ VARCHAR(500)
DECLARE @NARRATION VARCHAR(4000)
DECLARE @ALREADYUPLOADED INT 
DECLARE @ITEMID INT 
DECLARE @SERACHEXISTING INT 
DECLARE @TENDERITEMID INT 
DECLARE @REMARKS VARCHAR(50)
DECLARE @CLIENTBOQ VARCHAR(25)


SET @TENDERITEMID =0

DECLARE WORKITEMSLIST CURSOR FOR SELECT WORKORDERID,TOOLCODE,BOQCODE,UOM,RATE,TOTALQTY,WORKDESCRIPTION,BOQ,NARRATION,WORKTYPE,CLIENTBOQ  FROM #TEMP0 
OPEN WORKITEMSLIST 

FETCH NEXT FROM  WORKITEMSLIST INTO 
                 @WORKORDERID,@TOOLCODE,@BOQCODE,@UOM,@RATE,@TOTALQTY,@WORKDESCRIPTION,@BOQ,@NARRATION,@REMARKS,@CLIENTBOQ  

WHILE @@FETCH_STATUS=0 
BEGIN

     
	 SET @SERACHEXISTING = 0
	 SELECT @SERACHEXISTING  =ISNULL( COUNT(*), 0 )
	   FROM TENDERITEMS 
	   WHERE  BORG=@BORGID AND CATEGORY='SUBCONTRACTORS' AND PROJECT=@PROJECT AND CONTRACT=@CONTRACT  AND RESCODE=@TOOLCODE



     IF @SERACHEXISTING = 0
	    BEGIN 
	         SET @ALREADYUPLOADED = 0
			 SELECT @TENDERITEMID=IDENT_CURRENT ('TENDERITEMS')  
			 SET @TENDERITEMID = @TENDERITEMID+1
			 
		END
	 ELSE
	    BEGIN
		    SET @ALREADYUPLOADED = 1
			SELECT @TENDERITEMID = ITEMID 
			 FROM TENDERITEMS 
			 WHERE  BORG=@BORGID AND CATEGORY='SUBCONTRACTORS' AND PROJECT=@PROJECT AND CONTRACT=@CONTRACT  AND RESCODE=@TOOLCODE
		END

   

      IF  @ALREADYUPLOADED = 0 
       BEGIN 
        SET @STARTID = @STARTID + 1 
        INSERT INTO [dbo].[TENDERITEMS]
           ([RESCODE]
           ,[DESCR]
           ,[RATE]
           ,[UNIT]
           ,[QTY]
           ,[BORG]
           ,[PROJECT]
           ,[CONTRACT]
           ,[ORDEREDQTY]
           ,[EID]
           ,[LEDGERCODE]
           ,[CURRENCY]
           ,[SUPPCODE]
           ,[CATEGORY]
           ,[PERIODQTY]
           ,[ORDEREDAMOUNT]
           ,[FINALWASTE]
           ,[REMARK]
           ,[PERIODWASTE]
           ,[COSTRATE]
           ,[COSTQTY]
           ,[BILLQTY]
           ,[COSTWASTE]
           ,[EXCHRATE]
           ,[ACTNUMBER]
           ,[ISACTDETAIL]
           ,[ACTUALUSAGE]
           ,[ACTUALWASTE]
           ,[SYSDATE]
           ,[ORDEREDDISCOUNT]
           ,[TEMP6]
		   ,BUYRATE)
        SELECT 
           TOOLCODE,
		   NARRATION,
		   RATE    ,
		   UOM,  
		   TOTALQTY     ,
		   @BORGID,   
		   @PROJECT,
		   @CONTRACT,
		   0,    
		   'CAP',   
		   @LEDGERCODE,      
		   'INR',
		   @EMPTY,
		   'SUBCONTRACTORS'  ,
		   0,
		   0,
		   0,
		   @REMARKS,
		   0,
		   0,
		   0,
		   0,
		   0,
		   1,
		   @ACTNUMBER,
		   0,
		   0,
		   0,
		   GETDATE(),
		   0,
		   WORKORDERID ,
		   RATE
		FROM 
		   #TEMP0
        WHERE 
		   TOOLCODE=@TOOLCODE 

        SET @STARTWWWID  = @STARTWWWID + 1
		 

		INSERT INTO [BT].[WEBWORKORDERITEMS]
           ([WWWITEMCODE]
           ,[BMTPROJECTCODE]
           ,[BSORGID]
           ,[PROJECTCODE]
           ,[CONTRACTCODE]
           ,[DELIVERYID]
           ,[ACTIVITY]
           ,[LEDGERCODE]
           ,[CLIENTBOQ]
           ,[BOQCODE]
           ,[BOQDESCRIPTION]
           ,[WORKITEMCODE]
           ,[WORKITEMDESCRIPTION]
           ,[WORKORDERITEMDESCRIPTION]
           ,[UOM]
           ,[RATE]
           ,[TOTALQTY]
           ,[ORDEREDQTY]
           ,[ORDEREDAMOUNT]
           ,[TOTALBALANCEQTY]
           ,[PRQTY]
           ,[ITEMID])
     VALUES
           (@STARTWWWID
           ,@PROJECTID
           ,@BORGID
           ,@PROJECT
           ,@CONTRACT
           ,@DELIVERYID
           ,@ACTNUMBER
           ,@LEDGERCODE
           ,@CLIENTBOQ
           ,@BOQCODE
           ,@BOQ
           ,@TOOLCODE
           ,@WORKDESCRIPTION
           ,@NARRATION
           ,@UOM
           ,@RATE
           ,@TOTALQTY
           ,0
           ,0
           ,@TOTALQTY
           ,0
           ,@TENDERITEMID)

 
 	    UPDATE BT.WORKORDER SET ReleaseStatus=1 ,TENDERITEMID=@TENDERITEMID   WHERE WORKORDERID= @WORKORDERID 
		

     END
   ELSE
    BEGIN
	    SELECT @TENDERITEMID,@TOTALQTY ,@WORKORDERID
        UPDATE 
		    TENDERITEMS
		SET 
		    RATE = @RATE ,
			QTY = QTY + @TOTALQTY,
			BUYRATE=@RATE
		WHERE 
		    ITEMID=@TENDERITEMID
    
	    UPDATE 
		     [BT].[WEBWORKORDERITEMS]
		SET 
		     [TOTALQTY] =[TOTALQTY]+@TOTALQTY,
			 [TOTALBALANCEQTY] = [TOTALBALANCEQTY] + @TOTALQTY 
		WHERE 
		     ITEMID = @TENDERITEMID

 	UPDATE BT.WORKORDER SET ReleaseStatus=1 ,TENDERITEMID=@TENDERITEMID   WHERE WORKORDERID= @WORKORDERID 
	END 

  FETCH NEXT FROM WORKITEMSLIST INTO 
  @WORKORDERID,@TOOLCODE,@BOQCODE,@UOM,@RATE,@TOTALQTY,@WORKDESCRIPTION,@BOQ,@NARRATION,@REMARKS,@CLIENTBOQ  

END

CLOSE WORKITEMSLIST
DEALLOCATE WORKITEMSLIST