/****** Object:  Procedure [BT].[spResetBMTTestEnvironment]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE BT.spResetBMTTestEnvironment
AS
SELECT * FROM BORGS WHERE BORGID=65
DELETE  FROM DELIVERIES WHERE TBORGID=65

DELETE FROM REQITEMS WHERE REQID IN (SELECT REQID FROM REQ WHERE BORGID=65)
DELETE FROM REQ WHERE BORGID=65

DELETE  FROM ORDITEMS WHERE ORDID IN (SELECT ORDID FROM ORD WHERE BORGID=65)
DELETE FROM ORD WHERE BORGID=65

DELETE  FROM BT.BUDGETMATERIALMOVEMENTDETAIL WHERE PROJECTCODE=17
DELETE  FROM BT.RELEASESUMMARY WHERE PROJECTCODE=17


DELETE  FROM BT.MonthlyMaterialBudget WHERE PROJECTCODE =17

DELETE  FROM BT.MATERIALBUDGETLOG WHERE PROJECTCODE=17

UPDATE TENDERITEMS SET ORDEREDAMOUNT=0,ORDEREDQTY=0 WHERE BORG=65