/****** Object:  Procedure [BT].[spShowBudgetReleaseBalance]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE [BT].[spShowBudgetReleaseBalance](@PROJECTID INT)
AS
 
 
DECLARE @BORGID INT
SELECT @BORGID = BORGID FROM BT.PROJECTS WHERE PROJECTID=@PROJECTID 

SELECT TOOLCODE,BUDGETQTY,BUDGETRATE,BUDGETAMOUNT
INTO #BUDGET
FROM   BT.ProjectMaterialBudgetMaster WHERE PROJECTCODE=@PROJECTID 

SELECT TOOLCODE,BUDGETCATEGORYNAME,CATEGORYTYPE,UOM,CUMULATIVEQTY RELEASEQTY
INTO #RELEASE
FROM BT.MONTHLYMATERIALBUDGET WHERE   PROJECTCODE=2

SELECT RESCODE,ORDEREDQTY ,ORDEREDAMOUNT 
INTO #ORDERED
FROM TENDERITEMS
WHERE CATEGORY='MATERIAL' AND  BORG= @BORGID 

 

CREATE TABLE #FINAL(TOOLCODE VARCHAR(15),CATEGORYNAME VARCHAR(55),CATEGORYTYPE VARCHAR(10),UOM VARCHAR(10),
BUDGETQTY DECIMAL(18,2),BUDGETRATE DECIMAL(18,2),BUDGETAMOUNT DECIMAL(18,2),
RELEASEQTY DECIMAL(18,2),
ORDEREDQTY DECIMAL(18,2),ORDERVALUE DECIMAL(18,2),
BALANCEQTY DECIMAL(18,2),BALANCEVALUE DECIMAL(18,2))

INSERT INTO #FINAL(TOOLCODE,BUDGETQTY,BUDGETRATE,BUDGETAMOUNT)
SELECT TOOLCODE,BUDGETQTY,BUDGETRATE,BUDGETAMOUNT
FROM #BUDGET

UPDATE #FINAL SET CATEGORYNAME=R.BUDGETCATEGORYNAME,CATEGORYTYPE=R.CATEGORYTYPE,RELEASEQTY=R.RELEASEQTY ,UOM=R.UOM
FROM #RELEASE R
INNER JOIN #FINAL ON #FINAL.TOOLCODE=R.TOOLCODE 

UPDATE #FINAL SET ORDEREDQTY=O.ORDEREDQTY, ORDERVALUE = O.ORDEREDAMOUNT 
FROM #ORDERED O 
INNER JOIN #FINAL ON #FINAL.TOOLCODE = O.RESCODE

UPDATE #FINAL SET BALANCEQTY=BUDGETQTY-ORDEREDQTY 
UPDATE #FINAL SET BALANCEVALUE = BUDGETAMOUNT-ORDERVALUE 
UPDATE #FINAL SET ORDEREDQTY=0,BALANCEQTY=0 WHERE CATEGORYTYPE='L'
UPDATE #FINAL SET BUDGETQTY=0,BUDGETRATE=0 WHERE CATEGORYTYPE='L' 

SELECT * FROM #FINAL ORDER BY CATEGORYTYPE,CATEGORYNAME



 