/****** Object:  Procedure [BT].[spUpdateBOQItem]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE  [BT].[spUpdateBOQItem](@SALESID INT, @BOQ VARCHAR(800), @UOM VARCHAR(20),@CLIENTBOQ VARCHAR(25)  )
AS
BEGIN
  
   UPDATE BT.SALES 
    SET BOQ = @BOQ, UOM =UPPER(@UOM) ,CLIENTBOQ = @CLIENTBOQ WHERE SALESID=@SALESID 
   
   DECLARE @PROJECTCODE INT
   DECLARE @BOQCODE VARCHAR(25)
   SELECT @PROJECTCODE=PROJECTCODE , @BOQCODE = BOQNUMBER  FROM BT.SALES WHERE SALESID=@SALESID 
    
   DECLARE @WORKODERID INT 
   DECLARE @MINORWORKHEADID VARCHAR(25)
   DECLARE @TENDERITEMID INT 
   DECLARE @WORKDESCRIPTION VARCHAR(600)
   DECLARE @FINALNARRATION VARCHAR(4000)

   DECLARE @ALREADYINUSE INT 
  
   SET @ALREADYINUSE = 0

   SELECT @ALREADYINUSE = ISNULL(COUNT(*),0) 
   FROM    BT.WORKORDER 
   WHERE PROJECTCODE=@PROJECTCODE AND BOQCODE = @BOQCODE

   SELECT @ALREADYINUSE 

   IF @ALREADYINUSE >0 
    BEGIN

      SELECT @WORKODERID = WORKORDERID , @MINORWORKHEADID = MINORWORKHEADID , @TENDERITEMID = TENDERITEMID 
      FROM    BT.WORKORDER 
      WHERE PROJECTCODE=@PROJECTCODE AND BOQCODE = @BOQCODE 
    
	  SELECT @WORKDESCRIPTION = UPPER(WORKDESCRIPTION) 
	  FROM BT.WORKORDERITEMS 
	  WHERE PROJECT=@PROJECTCODE AND ITEMTYPE='BOQ' AND TOOLCODE=@MINORWORKHEADID  

	  SET @FINALNARRATION = UPPER(LTRIM(RTRIM(@BOQ)))+'; ' +LTRIM(RTRIM(@WORKDESCRIPTION)) 
	  SELECT @FINALNARRATION 

	  UPDATE TENDERITEMS SET DESCR = @FINALNARRATION WHERE ITEMID=@TENDERITEMID 

	END 
 
	 
   RETURN 1






END
 