/****** Object:  Procedure [BT].[spUpdateLastPurcahseRate]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE [BT].[spUpdateLastPurcahseRate]
AS
DECLARE  MATERAILMASTER CURSOR   FOR SELECT INDEXCODE,MATERIALCODE FROM BT.MasterMaterialDetail
DECLARE @INDEXCODE INT 
DECLARE @MATERIALCODE VARCHAR(25) 
DECLARE @HIGHESTPRICE DECIMAL(18,2) 

UPDATE BT.MonthlyMaterialBudget set categorytype=upper(categorytype)


OPEN  MATERAILMASTER
FETCH NEXT FROM MATERAILMASTER INTO @INDEXCODE,@MATERIALCODE 

WHILE @@FETCH_STATUS=0 
BEGIN
  SET @HIGHESTPRICE=0
  SELECT @HIGHESTPRICE = MAX(STKCOSTRATE) FROM INVENTORY WHERE STKCODE=@MATERIALCODE 
  UPDATE BT.MasterMaterialDetail SET LASTPURCHASERATE=@HIGHESTPRICE WHERE INDEXCODE=@INDEXCODE 
  FETCH NEXT FROM MATERAILMASTER INTO @INDEXCODE,@MATERIALCODE
END
CLOSE MATERAILMASTER 
DEALLOCATE MATERAILMASTER 