/****** Object:  Procedure [BT].[spUpdateBudgetUploadLogs]    Committed by VersionSQL https://www.versionsql.com ******/

create  PROCEDURE  [BT].[spUpdateBudgetUploadLogs] (@START BIGINT,@END BIGINT)
AS
BEGIN

SELECT PROJECTMATERIALBUDGETCODE,PROJECTCODE,TOOLCODE,BUDGETQTY,BUDGETRATE,BUDGETAMOUNT 
INTO #TEMP1
FROM [BT].[ProjectMaterialBudgetMaster]
WHERE PROJECTMATERIALBUDGETCODE BETWEEN @START AND @END 

ALTER TABLE #TEMP1 ADD MAJORHEAD VARCHAR(200)
ALTER TABLE #TEMP1 ADD TOOLNAME VARCHAR(250)
ALTER TABLE #TEMP1 ADD CATEGORY VARCHAR(5)
ALTER TABLE #TEMP1 ADD UOM VARCHAR(15) 
ALTER TABLE #TEMP1 ADD EXISTING INT 


UPDATE #TEMP1 SET MAJORHEAD=M.MATERIALMAJORHEAD,
                  TOOLNAME=M.TEMPLATENAME,
				  CATEGORY=M.UOM,
				  UOM=M.CATEGORY 
FROM BT.MasterMaterialBudget M 
INNER JOIN #TEMP1 ON #TEMP1.TOOLCODE=M.TEMPLATECODE 




UPDATE #TEMP1 SET EXISTING=0
UPDATE #TEMP1 SET EXISTING = 1 FROM  BT.BUDGETMATERAILMOVEMENTHEAD H 
INNER JOIN #TEMP1 ON #TEMP1.PROJECTCODE=H.PROJECTCODE AND #TEMP1.TOOLCODE=H.TOOLCODE  

SELECT * FROM #TEMP1

INSERT INTO BT.BUDGETMATERAILMOVEMENTHEAD(PROJECTCODE,TOOLCODE,MAJORHEAD,TOOLNAME,CATEGORY,UOM,BUDGET)
SELECT PROJECTCODE,TOOLCODE,MAJORHEAD,TOOLNAME,CATEGORY,UOM,BUDGETQTY FROM #TEMP1 
WHERE EXISTING=0 AND CATEGORY='Q'

INSERT INTO BT.BUDGETMATERAILMOVEMENTHEAD(PROJECTCODE,TOOLCODE,MAJORHEAD,TOOLNAME,CATEGORY,UOM,BUDGET)
SELECT PROJECTCODE,TOOLCODE,MAJORHEAD,TOOLNAME,CATEGORY,UOM,BUDGETAMOUNT FROM #TEMP1 
WHERE EXISTING=0 AND CATEGORY='L'

UPDATE BT.BUDGETMATERAILMOVEMENTHEAD 
SET BUDGET = BUDGET+BUDGETQTY FROM #TEMP1 
INNER JOIN BT.BUDGETMATERAILMOVEMENTHEAD  H
ON #TEMP1.PROJECTCODE=H.PROJECTCODE AND #TEMP1.TOOLCODE=H.TOOLCODE 
WHERE #TEMP1.EXISTING=1 AND #TEMP1.CATEGORY='Q'

UPDATE BT.BUDGETMATERAILMOVEMENTHEAD 
SET BUDGET = BUDGET+BUDGETAMOUNT FROM #TEMP1 
INNER JOIN BT.BUDGETMATERAILMOVEMENTHEAD  H
ON #TEMP1.PROJECTCODE=H.PROJECTCODE AND #TEMP1.TOOLCODE=H.TOOLCODE 
WHERE #TEMP1.EXISTING=1 AND #TEMP1.CATEGORY='L'

INSERT INTO BT.MATERIALBUDGETLOG(LOGDATE,TRANSACTIONTYPE,PROJECTCODE,TOOLCODE,QTY,RATE,AMOUNT,CROSSREFERENCEID)
SELECT GETDATE(),'B',PROJECTCODE,TOOLCODE,BUDGETQTY,BUDGETRATE,BUDGETAMOUNT,PROJECTMATERIALBUDGETCODE FROM #TEMP1 
 

 
END 
 
 