/****** Object:  Procedure [BT].[spUpdateLastPurchaseRate]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE BT.spUpdateLastPurchaseRate
AS
DECLARE MATERIALMASTERS CURSOR FOR SELECT MATERIALCODE,LASTPURCHASERATE FROM BT.MASTERMATERIALDETAIL 
DECLARE @MATERIALCODE VARCHAR(15)
DECLARE @CURRENTVALUE DECIMAL(18,2)
DECLARE @LASTPURCHASERATE DECIMAL(18,2)
DECLARE @MATERIALNAME VARCHAR(250)
CREATE TABLE #TEMP0(STKID INT) 
OPEN MATERIALMASTERS
FETCH NEXT FROM MATERIALMASTERS INTO @MATERIALCODE,@CURRENTVALUE  
WHILE @@FETCH_STATUS = 0 
BEGIN
  DELETE FROM #TEMP0 
  INSERT INTO #TEMP0 
  SELECT STKID FROM INVENTORY WHERE STKCODE = @MATERIALCODE 
 
  SELECT @LASTPURCHASERATE = MAX(PRICE) FROM ORDITEMS WHERE STOCKID IN (SELECT STKID FROM #TEMP0) 
  IF @CURRENTVALUE < @LASTPURCHASERATE
     UPDATE BT.MasterMaterialDetail SET LASTPURCHASERATE = @LASTPURCHASERATE WHERE MATERIALCODE=@MATERIALCODE 
  FETCH NEXT FROM MATERIALMASTERS INTO @MATERIALCODE,@LASTPURCHASERATE  
END
CLOSE MATERIALMASTERS
DEALLOCATE MATERIALMASTERS
 
 