/****** Object:  Procedure [BT].[spUpdateWorkOrderItems]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE BT.spUpdateWorkOrderItems(@TEMPLATECODE VARCHAR(15),@WORKORDERITEM VARCHAR(500),@PROJECTID INT) 
AS 
DECLARE @PROJECT INT
SET @PROJECT  = @PROJECTID 
DECLARE @CATEGORY VARCHAR(1)
SET @CATEGORY='D'
DECLARE @ITEMTYPE VARCHAR(10)
SET @ITEMTYPE='BOQ'
DECLARE @UOM VARCHAR(10)
SET @UOM='LS' 
DECLARE @COUNTER INT
SET @COUNTER = 0
SELECT  @COUNTER =ISNULL( COUNT(*),0) FROM BT.WORKORDERITEMS WHERE PROJECT=@PROJECT AND TOOLCODE=@TEMPLATECODE 
IF @COUNTER > 0 
  SELECT 0
ELSE
  BEGIN 
    DECLARE @MAXID INT
	SELECT @MAXID = MAX(ID) FROM BT.WORKORDERITEMS 
	SET @MAXID=@MAXID+1
    INSERT INTO BT.WORKORDERITEMS VALUES (@MAXID,@PROJECT,@CATEGORY,@ITEMTYPE,@TEMPLATECODE,@WORKORDERITEM,@UOM)
	SELECT 1
  END