/****** Object:  Procedure [BT].[spUpdateWorkOrderMasterItem]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE  [BT].[spUpdateWorkOrderMasterItem](@PROJECTID INT, @ITEMTYPE VARCHAR(20), @WORKDESCRIPTION VARCHAR(600), @UOM VARCHAR(20), @TOOLCODE VARCHAR(15) )
AS
BEGIN
   DECLARE @BORGID INT 
   SELECT @BORGID = BORGID FROM BT.PROJECTS WHERE PROJECTID=@PROJECTID 
   SET @WORKDESCRIPTION = UPPER(LTRIM(RTRIM(@WORKDESCRIPTION)))

   DECLARE @BOQCODE VARCHAR(15)
   DECLARE @BOQ VARCHAR(800)
   DECLARE @DETAILWORKDESCRIPTION VARCHAR(4000)
   SET @BOQ=''
   SELECT @BOQCODE=BOQCODE FROM BT.WORKORDER WHERE PROJECTCODE=@PROJECTID AND MINORWORKHEADID = @TOOLCODE 
   SELECT @BOQ =  CLIENTBOQ+'-'+LTRIM(RTRIM(BOQ))   FROM BT.SALES WHERE PROJECTCODE=@PROJECTID AND BOQNUMBER=@BOQCODE

   SET @DETAILWORKDESCRIPTION = LTRIM(RTRIM(@BOQ))+' - ' + LTRIM(RTRIM(@WORKDESCRIPTION))
 
   UPDATE TENDERITEMS 
     SET DESCR = UPPER(@DETAILWORKDESCRIPTION),UNIT = @UOM  WHERE BORG=@BORGID AND RESCODE = @TOOLCODE 
   
   UPDATE BT.WORKORDER 
     SET UOM = @UOM WHERE PROJECTCODE=@PROJECTID AND MINORWORKHEADID = @TOOLCODE 
   SELECT @BOQCODE = BOQCODE FROM BT.WORKORDER 
   UPDATE BT.WORKORDERITEMS 
     SET ITEMTYPE=UPPER(@ITEMTYPE), WORKDESCRIPTION =UPPER(@WORKDESCRIPTION), UOM = @UOM 
	 WHERE PROJECT = @PROJECTID AND TOOLCODE=@TOOLCODE 

   RETURN 1






END
 