/****** Object:  Procedure [BT].[spUpdateMachineryMaster]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE procedure [BT].[spUpdateMachineryMaster](@PROJECTID INT) 
AS

 
 DECLARE   @PROJECTSHORTCODE VARCHAR(5)
 SELECT @PROJECTSHORTCODE = PROJECTCODE FROM BT.PROJECTS WHERE PROJECTID=@PROJECTID 
 

 SELECT PENUMBER  INTO #TEMP0  FROM PLANTANDEQ WHERE PELOCATION=@PROJECTSHORTCODE AND 
 PENUMBER IN (SELECT COLKEY FROM ATTRIBVALUE WHERE TABLENAME='PLANTANDEQ'  AND ATTRIBUTE='DPR ENTRY'  AND VALUE=1 )

 
 DECLARE @PENUMBER VARCHAR(20)
 DECLARE @PESTATUS INT
 DECLARE @EXISTING INT 
 DECLARE @NEXTNUMBER INT 
 DECLARE PELIST CURSOR FOR SELECT * FROM #TEMP0 
 OPEN PELIST
 FETCH NEXT FROM PELIST INTO @PENUMBER 
 WHILE @@FETCH_STATUS = 0 
 BEGIN
   SELECT @EXISTING = COUNT(*) FROM BT.EQUIPMENTMASTER WHERE EQUIPNUMBER = @PENUMBER AND PROJECTCODE =@PROJECTID 
   IF @EXISTING = 0 
     BEGIN
	    SELECT @NEXTNUMBER = ISNULL(MAX(EQUIPMENTID),0) FROM BT.EQUIPMENTMASTER WHERE PROJECTCODE=@PROJECTID AND OWNERID=1 
		SET @NEXTNUMBER = @NEXTNUMBER+1
		INSERT INTO BT.EQUIPMENTMASTER(EQUIPMENTID,PROJECTCODE,EQUIPNUMBER,EQUIPNAME,MAKE,MODEL,CAPACITY,TYPE,STATUS,OWNERID,OWNER,CHECKINDATE) 
		SELECT @NEXTNUMBER,@PROJECTID,PENUMBER,PENAME,PEUSER1,PEUSER2,PEUSER3,PEUSER4,1,1,'CIL',GETDATE() FROM PLANTANDEQ WHERE PENUMBER=@PENUMBER 
	 END
   FETCH NEXT FROM PELIST INTO @PENUMBER 
 END
 CLOSE PELIST
 DEALLOCATE PELIST