/****** Object:  Procedure [BT].[spVerifyBMTEntries]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE [BT].[spVerifyBMTEntries]
as

SELECT PROJECTCODE,TOOLCODE,SUM(RELEASEQTY) RELEASEQTY 
INTO #RELEASESUMMARY
FROM BT.RELEASESUMMARY 
GROUP BY PROJECTCODE,TOOLCODE 


SELECT PROJECTMATERIALBUDGETID,SUM(BUDGETQTY) BREAKUPQTY ,SUM(BUDGETAMOUNT) BREAKUPAMOUNT
INTO #BREAKUPS
FROM BT.ProjectMaterialBudgetDetail
GROUP BY PROJECTMATERIALBUDGETID


 
ALTER TABLE #BREAKUPS ADD TOOLCODE VARCHAR(25)
ALTER TABLE #BREAKUPS ADD PROJECTCODE INT 

UPDATE #BREAKUPS SET TOOLCODE = BTPM.TOOLCODE,PROJECTCODE=BTPM.ProjectCode  FROM BT.ProjectMaterialBudgetMaster BTPM 
INNER JOIN #BREAKUPS ON #BREAKUPS.ProjectMaterialBudgetID = BTPM.ProjectMaterialBudgetCode

SELECT PROJECTCODE,TOOLCODE,SUM(BREAKUPQTY) BREAKUPQTY,SUM(BREAKUPAMOUNT) BREAKUPAMOUNT
INTO #FINALBREAKUPS
FROM #BREAKUPS
GROUP BY PROJECTCODE,TOOLCODE 

 
SELECT PROJECTCODE,TOOLCODE,SUM(BUDGETQTY) TOTALBUDGETQTY, SUM(BUDGETAMOUNT) TOTALBUDGETAMOUNT 
INTO #BUDGETSUMMARY
FROM BT.PROJECTMATERIALBUDGETMASTER 
GROUP BY PROJECTCODE,TOOLCODE 
--UPDATE #BUDGETSUMMARY SET TOTALBUDGETQTY=0 WHERE TOTALBUDGETAMOUNT=0 
 


CREATE TABLE #MASTER(ID INT PRIMARY KEY IDENTITY(1,1),PROJECTCODE INT,BORGID INT, PROJECTNAME VARCHAR(150),
TOOLCODE VARCHAR(25),MAJORHEAD VARCHAR(200),TOOLCODENAME VARCHAR(250),CATEGORY VARCHAR(15),UOM VARCHAR(15),
TOTALBUDGETQTY DECIMAL(18,4),TOTALBUDGETAMOUNT DECIMAL(18,4),TOTALBREAKUPQTY DECIMAL(18,4),TOTALBREAKUPAMOUNT DECIMAL(18,4),
RELEASEQTY DECIMAL(18,2),TENDERITEMID INT,TENDERITEMQTY DECIMAL(18,4),
WEBPRQTYID INT, WEBPRQTY DECIMAL(18,4),OPENREQQTY DECIMAL(18,4),CANCELLEDQTY DECIMAL(18,4),REJECTEDQTY DECIMAL(18,4),
ORDERID INT,ORDEREDQTY DECIMAL(18,4),
DELIVERYQTY DECIMAL(18,4),BUDGETUTILIZED DECIMAL(18,4)) 

INSERT INTO #MASTER(PROJECTCODE,TOOLCODE)
SELECT DISTINCT PROJECTCODE,TOOLCODE FROM BT.ProjectMaterialBudgetMaster

UPDATE #MASTER SET MAJORHEAD=MMB.MATERIALMAJORHEAD, TOOLCODENAME=MMB.TEMPLATENAME,CATEGORY=MMB.UOM, UOM = MMB.CATEGORY  FROM BT.MasterMaterialBudget MMB 
INNER JOIN #MASTER ON #MASTER.TOOLCODE=MMB.TEMPLATECODE

UPDATE #MASTER SET CATEGORY=UPPER(CATEGORY) ,TOTALBUDGETAMOUNT=0,TOTALBUDGETQTY=0,TOTALBREAKUPAMOUNT=0,TOTALBREAKUPQTY=0

UPDATE #MASTER SET BORGID=BTP.BORGID, PROJECTNAME = BTP.PROJECTNAME FROM BT.PROJECTS BTP INNER JOIN #MASTER ON #MASTER.PROJECTCODE=BTP.PROJECTID 
UPDATE #MASTER SET TOTALBUDGETQTY = S.TOTALBUDGETQTY FROM #BUDGETSUMMARY  S INNER JOIN #MASTER ON #MASTER.PROJECTCODE=S.ProjectCode AND #MASTER.TOOLCODE=S.ToolCode WHERE #MASTER.CATEGORY='Q'
UPDATE #MASTER SET TOTALBUDGETAMOUNT = S.TOTALBUDGETAMOUNT FROM #BUDGETSUMMARY  S INNER JOIN #MASTER ON #MASTER.PROJECTCODE=S.ProjectCode AND #MASTER.TOOLCODE=S.ToolCode WHERE #MASTER.CATEGORY='L'
UPDATE #MASTER SET TOTALBREAKUPQTY =  B.BREAKUPQTY FROM #FINALBREAKUPS B INNER JOIN #MASTER ON #MASTER.TOOLCODE = B.TOOLCODE AND #MASTER.PROJECTCODE=B.PROJECTCODE WHERE #MASTER.CATEGORY='Q'
UPDATE #MASTER SET TOTALBREAKUPAMOUNT =  B.BREAKUPAMOUNT  FROM #FINALBREAKUPS B INNER JOIN #MASTER ON #MASTER.TOOLCODE = B.TOOLCODE AND #MASTER.PROJECTCODE=B.PROJECTCODE WHERE #MASTER.CATEGORY='L'
DELETE FROM #MASTER WHERE BORGID=-1


UPDATE #MASTER  SET RELEASEQTY=0 
UPDATE #MASTER SET RELEASEQTY = R.RELEASEQTY FROM #RELEASESUMMARY R INNER JOIN #MASTER ON #MASTER.PROJECTCODE=R.PROJECTCODE AND #MASTER.TOOLCODE=R.TOOLCODE 

UPDATE #MASTER SET TENDERITEMQTY=0,WEBPRQTY =0 

UPDATE #MASTER SET TENDERITEMQTY = T.QTY FROM TENDERITEMS T 
INNER JOIN #MASTER  ON #MASTER.BORGID=T.BORG AND #MASTER.TOOLCODE=T.RESCODE  
 
UPDATE #MASTER SET WEBPRQTYID = B.MONTHLYMATERIALBUDGETCODE, WEBPRQTY=B.CUMULATIVEQTY FROM BT.MonthlyMaterialBudget B INNER JOIN #MASTER ON #MASTER.PROJECTCODE=B.ProjectCode AND #MASTER.TOOLCODE = B.TOOLCODE 

 
 UPDATE #MASTER SET TENDERITEMID = T.ITEMID FROM TENDERITEMS T
 INNER JOIN #MASTER ON #MASTER.BORGID = T.BORG AND #MASTER.TOOLCODE=T.RESCODE AND T.CATEGORY ='MATERIAL' 

SELECT * FROM #MASTER WHERE ABS(TOTALBUDGETQTY-TOTALBREAKUPQTY)>1 AND CATEGORY='Q' ORDER BY PROJECTCODE,TOOLCODE 
SELECT * FROM #MASTER WHERE ABS(TOTALBUDGETAMOUNT-TOTALBREAKUPAMOUNT)>1 AND CATEGORY='L' ORDER BY PROJECTCODE,TOOLCODE 

SELECT CATALOGITEMID,ITEMSTATUSID,SUM(QTY) SUMQTY 
INTO #REQ 
FROM REQITEMS  
WHERE CATALOGITEMID IN (SELECT TENDERITEMID FROM #MASTER) AND UPPER(ITEMDESCRIPTION) NOT IN ('FREIGHT CHARGES','AOC Charges')
GROUP BY CATALOGITEMID,ITEMSTATUSID

UPDATE #MASTER SET OPENREQQTY=0,CANCELLEDQTY=0,REJECTEDQTY=0,ORDEREDQTY=0,BUDGETUTILIZED=0


UPDATE #MASTER SET OPENREQQTY = R.SUMQTY FROM #REQ  R INNER JOIN #MASTER ON #MASTER.TENDERITEMID = R.CATALOGITEMID AND R.ITEMSTATUSID IN (32,163)
UPDATE #MASTER SET CANCELLEDQTY = R.SUMQTY FROM #REQ  R INNER JOIN #MASTER ON #MASTER.TENDERITEMID = R.CATALOGITEMID AND R.ITEMSTATUSID IN (36)
UPDATE #MASTER SET REJECTEDQTY = R.SUMQTY FROM #REQ  R INNER JOIN #MASTER ON #MASTER.TENDERITEMID = R.CATALOGITEMID AND R.ITEMSTATUSID IN (202) 
UPDATE #MASTER SET ORDEREDQTY = R.SUMQTY FROM #REQ  R INNER JOIN #MASTER ON #MASTER.TENDERITEMID = R.CATALOGITEMID AND R.ITEMSTATUSID IN (173,500,501)  

UPDATE #MASTER SET BUDGETUTILIZED = OPENREQQTY+ORDEREDQTY 

--SELECT * FROM #MASTER WHERE  CATEGORY='Q' AND TOTALBUDGETQTY<BUDGETUTILIZED
SELECT * FROM #MASTER WHERE  CATEGORY='L' AND TOTALBUDGETAMOUNT<BUDGETUTILIZED 

-- FIXING OF TOTALBUDGETQTY < BUDGETUTILIZED 


SELECT ID,PROJECTCODE,BORGID,TOOLCODE,TOTALBUDGETQTY,RELEASEQTY,(TOTALBUDGETQTY-RELEASEQTY) BALANCETORELEASE,TENDERITEMID,WEBPRQTYID,BUDGETUTILIZED 
INTO #FIXINGTABLE
FROM #MASTER 
WHERE CATEGORY='Q' AND TOTALBUDGETQTY<BUDGETUTILIZED

SELECT * FROM #FIXINGTABLE 
SELECT * FROM #MASTER WHERE TOTALBUDGETQTY<BUDGETUTILIZED
---- MAKE WEBPRQTY = 0
--UPDATE BT.MonthlyMaterialBudget
--SET CumulativeQty=0 WHERE MonthlyMaterialBudgetCode IN (SELECT WEBPRQTYID FROM #FIXINGTABLE)

---- TENDERITEMS TABLE - MAKE QTY=TOTAL BUDGET AND ORDERED=TOTAL BUDGET 

--UPDATE TENDERITEMS 
--SET QTY=FT.TOTALBUDGETQTY,ORDEREDQTY=BUDGETUTILIZED 
--FROM #FIXINGTABLE FT INNER JOIN TENDERITEMS ON TENDERITEMS.ITEMID=FT.TENDERITEMID 


---- RELEASE BALANCE QTY AS ON DATE 

--DECLARE @PROJECTCODE INT
--DECLARE @TOOLCODE VARCHAR(15)
--DECLARE @RELEASEQTY DECIMAL(18,4) 
--DECLARE @LASTID INT 
--SELECT @LASTID = MAX(RELEASESUMMARYID) FROM BT.RELEASESUMMARY 

--DECLARE FIXING CURSOR FOR SELECT PROJECTCODE,TOOLCODE,BALANCETORELEASE FROM #FIXINGTABLE 
--OPEN FIXING 
--FETCH NEXT FROM FIXING INTO @PROJECTCODE,@TOOLCODE,@RELEASEQTY 

--WHILE @@FETCH_STATUS = 0 
--BEGIN
--    SET @LASTID = @LASTID+1
--	INSERT INTO BT.RELEASESUMMARY(RELEASESUMMARYID,RELEASEDATE,PROJECTCODE,TOOLCODE,RELEASEQTY) 
--    VALUES(@LASTID,GETDATE(),@PROJECTCODE,@TOOLCODE,@RELEASEQTY) 

--	FETCH NEXT FROM FIXING INTO @PROJECTCODE,@TOOLCODE,@RELEASEQTY 
--END
--CLOSE FIXING 
--DEALLOCATE FIXING 


----  FOR ALL THE ITEMS FIX THE TENDERITEMS TABLE -- FIXING BUDGETQTY AND ORDEREDQTY FOR CATEGORY='Q'
--UPDATE TENDERITEMS 
--SET QTY=M.TOTALBUDGETQTY , ORDEREDQTY = M.BUDGETUTILIZED  FROM #MASTER M 
--INNER JOIN TENDERITEMS  ON TENDERITEMS.ITEMID= M.TENDERITEMID WHERE M.CATEGORY = 'Q' 

--UPDATE TENDERITEMS SET ORDEREDAMOUNT = ORDEREDQTY*RATE WHERE CATEGORY='MATERIAL' 