/****** Object:  Procedure [PB].[getCILOutstanding]    Committed by VersionSQL https://www.versionsql.com ******/

 
create PROCEDURE [PB].[getCILOutstanding](@PARTYCODE VARCHAR(15),@PARTYCATEGORY VARCHAR(15))
AS
SELECT ORGID,MAX(YEAR) FINYEAR
INTO #TRANSYEARS
FROM PERIODENDLOGS 
WHERE ENDTYPE='LEDGERYE' 
GROUP BY ORGID  
ORDER BY ORGID 

UPDATE #TRANSYEARS SET FINYEAR=FINYEAR+1

ALTER TABLE #TRANSYEARS  ADD OUTSTANDING DECIMAL(18,2) 
UPDATE #TRANSYEARS SET OUTSTANDING=0

DECLARE @FINYEAR VARCHAR(15)
DECLARE @LEDGERCODE VARCHAR(15)
DECLARE @ORGOUTSTANDING DECIMAL(18,2) 
DECLARE @ORGID INT 

IF @PARTYCATEGORY ='SUPPLIER'
   SET @LEDGERCODE = '1315000'
ELSE
   SET @LEDGERCODE = '1320000'

SELECT DISTINCT ORGID,MAX(YEAR) LASTFINYEAR  
INTO #PARTYORGLISTS  
FROM TRANSACTIONS 
WHERE CREDNO=@PARTYCODE AND LEDGERCODE=@LEDGERCODE 
GROUP BY ORGID 

 
ALTER TABLE #PARTYORGLISTS ADD OUTSTANDING DECIMAL(18,2) 

DECLARE TRANSLISTS  CURSOR FOR SELECT ORGID,LASTFINYEAR FROM #PARTYORGLISTS

OPEN TRANSLISTS 
FETCH NEXT FROM TRANSLISTS  INTO @ORGID,@FINYEAR
WHILE @@FETCH_STATUS=0
BEGIN
  
  SET @ORGOUTSTANDING = 0
  SELECT @ORGOUTSTANDING =ISNULL( SUM(CREDIT-DEBIT) ,0 )
  FROM TRANSACTIONS 
  WHERE YEAR=@FINYEAR AND 
  CREDNO=@PARTYCODE AND 
  LEDGERCODE=@LEDGERCODE AND 
  ORGID=@ORGID 
 
  UPDATE #PARTYORGLISTS SET OUTSTANDING = @ORGOUTSTANDING WHERE ORGID=@ORGID 
 
  FETCH NEXT FROM TRANSLISTS  INTO @ORGID,@FINYEAR
END
CLOSE TRANSLISTS 
DEALLOCATE TRANSLISTS 


DELETE FROM #PARTYORGLISTS WHERE OUTSTANDING=0

ALTER TABLE #PARTYORGLISTS ADD PROJECTNAME VARCHAR(200)
UPDATE #PARTYORGLISTS SET PROJECTNAME=B.BORGNAME FROM BORGS B INNER JOIN #PARTYORGLISTS ON #PARTYORGLISTS.ORGID=B.BORGID

SELECT ORGID,PROJECTNAME,OUTSTANDING  FROM #PARTYORGLISTS ORDER BY PROJECTNAME 
 