/****** Object:  Procedure [PB].[spAddToRTGSWallet]    Committed by VersionSQL https://www.versionsql.com ******/

create PROCEDURE [PB].[spAddToRTGSWallet](@RTGSID INT,@DETAILID INT)
AS
DECLARE @PAYMENTAMOUNT DECIMAL(18,2)
DECLARE @PARTYCODE VARCHAR(25)
DECLARE @BENEFICIARYNAME VARCHAR(200)
DECLARE @BANKACCOUNTNUMBER VARCHAR(25)
DECLARE @BANKNAME VARCHAR(50)
DECLARE @IFSCCODE VARCHAR(25)
DECLARE @RTGDSTOTAL DECIMAL(18,2)

SELECT @PARTYCODE=PARTYCODE,@PAYMENTAMOUNT=BATCHOUTSTANDING FROM PB.PAYMENTBATCHDETAIL WHERE DETAILID=@DETAILID 
SELECT @BENEFICIARYNAME=BENEFICIARYNAME ,@BANKACCOUNTNUMBER=BENEFICIARYBANKACCOUNTNUMBER,@BANKNAME=BANKNAME,@IFSCCODE=IFSCCODE 
FROM PB.BENEFICIARYBANKS WHERE PARTYCODE=@PARTYCODE 

SELECT  @PARTYCODE,@BENEFICIARYNAME,@BANKACCOUNTNUMBER,@BANKNAME,@IFSCCODE,@RTGSID,@DETAILID

INSERT INTO PB.RTGSDETAIL(RTGSHeaderID,BatchDetailID,BeneficiaryName,BeneficiaryAccountNumber,IFSCCode,BeneficiaryBankName,PostingStatus,PaymentAmount)
SELECT @RTGSID,@DETAILID,@BENEFICIARYNAME,@BANKACCOUNTNUMBER,@IFSCCODE,@BANKNAME,0,@PAYMENTAMOUNT
SELECT @RTGDSTOTAL=SUM(PAYMENTAMOUNT) FROM PB.RTGSDETAIL WHERE RTGSHEADERID=@RTGSID

UPDATE PB.RTGSHEADER SET BATCHTOTALAMOUNT=@RTGDSTOTAL WHERE RTGSID=@RTGSID 
UPDATE PB.RTGSHEADER SET BATCHTOTALAMOUNTINWORDS = DBO.FN_TOWORDS(@RTGDSTOTAL,'UK',1) WHERE RTGSID=@RTGSID 

UPDATE PB.PAYMENTBATCHDETAIL SET APPROVALLEVELID=6 WHERE DETAILID=@DETAILID 