/****** Object:  Procedure [PB].[spChangeBatchStatus]    Committed by VersionSQL https://www.versionsql.com ******/

create PROCEDURE [PB].[spChangeBatchStatus](@BATCHID INT,@DETAILID INT,@PARTYCODE VARCHAR(15))
AS
-- IF BATCHID IS SENT IT IS A NEW BATCH AND DONE BY INITITATOR - SO WE HAVE TO WRITE IN DETAIL TABLE ALSO
-- IF DETAILID IS SENT FINDOUT THE CURRENT INDEX AND INCREMENT IT BY ONE
-- PARTYCODE WILL HAVE RELEVEANCE IF BATCHID=0 

-- IF IT IS FROM THE INITITATOR THE CALL WOULD BE WITH BATCHID ONLY AND DETAILID WOULD BE ZERO 

-- CHECK DETAILS ARE AVAIALBEL INT DETAIL TABLE OR NOT ?

DECLARE @EXISTING INT 
DECLARE @WORKFLOW VARCHAR(25)
DECLARE @CURRENTCUSTODIAN VARCHAR(15)

SET @EXISTING=0
SELECT @EXISTING =ISNULL( COUNT(*),0 ) FROM PB.PAYMENTBATCHDETAIL WHERE BATCHID=@BATCHID 
IF @EXISTING = 0
   SET @DETAILID=0 


IF @BATCHID>0 AND @DETAILID=0
   SET @WORKFLOW = 'INITIATOR APPROVAL' 
ELSE
   SET @WORKFLOW = 'SUBSEQUENT APPROVAL'

DECLARE @BATCHNO VARCHAR(15)
DECLARE @BATCHPROCESS VARCHAR(1)
DECLARE @MASTERLEDGERCODE VARCHAR(15)
DECLARE @OWNERAPPROVALROLEDID INT
DECLARE @ACTION VARCHAR(50)
DECLARE @BATCHOWER VARCHAR(50)
DECLARE @BATCHORGID INT 
DECLARE @CURRENTOWNER VARCHAR(50)
DECLARE @BANKID INT
DECLARE @BATDESCRIPTION VARCHAR(50)
DECLARE @PAYMENTBANK VARCHAR(15)
DECLARE @BANKLEDGERCODE VARCHAR(15)
DECLARE @BATCHOUTSTANDING DECIMAL(18,2)
DECLARE @HOWMANYPARTIES INT 
DECLARE @YETTOAPPROVE INT
DECLARE @BATCHTHISOUTSTANDING DECIMAL(18,2)
DECLARE @BATLOGINID VARCHAR(15)
DECLARE @CURRENTLEVELID  INT 
DECLARE @NEXTUSERID VARCHAR(15)
DECLARE @CURRENTFINYEAR INT
 
DECLARE @NEXTAPPROVALLEVELID INT 

SELECT @CURRENTFINYEAR = CURRENTYEAR  FROM BORGS WHERE BORGID=2 

IF @WORKFLOW = 'INITIATOR APPROVAL' 
BEGIN

  SELECT @BATCHNO=BATCHNO,@BATCHORGID=BATORGID,@BATCHPROCESS=BATPROCESS,@BANKLEDGERCODE=BATBANKLEDGERCODE,@BATDESCRIPTION=BATCHDESCRIPTION,@BATLOGINID=BATLOGINID
  FROM PB.PAYMENTBATCHHEADER  WHERE BATCHID=@BATCHID 

  SELECT @BANKID=BANKID  FROM PB.PAYMENTBANKS   WHERE LEDGERCODE=@BANKLEDGERCODE
 
  SELECT @OWNERAPPROVALROLEDID = APPROVERLEVELID FROM PB.PAYMENTBATCHUSERS WHERE BSLOGINID=@BATLOGINID 
  SET @NEXTAPPROVALLEVELID = @OWNERAPPROVALROLEDID + 1

  SELECT @NEXTUSERID=BSLOGINID,@NEXTAPPROVALLEVELID=@NEXTAPPROVALLEVELID
  FROM PB.PAYMENTBATCHUSERORGROLEMAPPING WHERE BSORGID=@BATCHORGID AND   BSPROCESS = @BATCHPROCESS  AND APPROVERLEVELID = @NEXTAPPROVALLEVELID

  IF @BATCHPROCESS = 'C'
     SET @MASTERLEDGERCODE = '1315000'
  ELSE
     SET @MASTERLEDGERCODE = '1320000'
  
  SELECT @CURRENTFINYEAR = BATYEAR FROM BATCHREMIT WHERE BATCHNO=@BATCHNO AND BATORGID=@BATCHORGID AND BATPROCESS=@BATCHPROCESS 
  

 
	
  -- LOCK THE BATCH
  -- UPDATE BANK
  -- UPDATE BATCHDETAIL TABLE
  -- UPDATE BATCHTRANSACTION TABLE
  -- UPDATE LOG
  -- UPDATE BATCHREMIT 

  UPDATE PB.PAYMENTBATCHHEADER SET APPROVERLEVELID = @NEXTAPPROVALLEVELID WHERE BATCHID = @BATCHID
  
  UPDATE BATCHREMIT SET BATSTATUS = -99 ,BATPROCESS='Z'  WHERE  BATCHNO=@BATCHNO AND BATORGID=@BATCHORGID AND BATPROCESS=@BATCHPROCESS 

 
  BEGIN 
		SELECT @BATCHTHISOUTSTANDING = SUM(PAIDTHISPERIOD) FROM TRANSACTIONS 
		WHERE LEDGERCODE = @MASTERLEDGERCODE AND RECONSTATUS=@BATCHNO AND ORGID=@BATCHORGID AND CREDNO=@PARTYCODE

		INSERT INTO [PB].[PAYMENTBATCHDETAIL](BATCHID,BATCHOWNER,        CURRENTOWNER,       APPROVALLEVELID,     PARTYCODE, BATCHOUTSTANDING,       NARRATION       , BANKID, SUBMITTEDBY,       SUBMISSIONTIME)
		SELECT                               @BATCHID,UPPER(@BATLOGINID),UPPER(@NEXTUSERID) ,@NEXTAPPROVALLEVELID,@PARTYCODE,@BATCHTHISOUTSTANDING,  @BATDESCRIPTION,  @BANKID,UPPER(@BATLOGINID),GETDATE()  
  

		SELECT @DETAILID = DETAILID   FROM PB.PAYMENTBATCHDETAIL WHERE BATCHID=@BATCHID AND PARTYCODE=@PARTYCODE 

		INSERT INTO [PB].[PAYMENTBATCHTRANSACTIONS](TRANSID,DETAILID,PDATE,BATCHREF,TRANSREF,TRANSTYPE,ORDERNO,DEBIT,CREDIT,PAIDTODATE,PAIDTHISPERIOD)
		SELECT TRANSID,@DETAILID,PDATE,BATCHREF,TRANSREFEXT,TRANSTYPE,ORDERNO,DEBIT,CREDIT,PAIDTODATE,PAIDTHISPERIOD 
		FROM TRANSACTIONS WHERE LEDGERCODE = @MASTERLEDGERCODE AND RECONSTATUS=@BATCHNO AND ORGID=@BATCHORGID AND CREDNO=@PARTYCODE 
		
		UPDATE PB.PAYMENTBATCHDETAIL  SET PARTYNAME=UPPER(C.CREDNAME) FROM CREDITORS      C INNER JOIN PB.PAYMENTBATCHDETAIL     PBP  ON PBP.PARTYCODE=C.CREDNUMBER  WHERE DETAILID=@DETAILID 
		UPDATE PB.PAYMENTBATCHDETAIL  SET PARTYNAME=UPPER(S.SUBNAME)  FROM SUBCONTRACTORS S INNER JOIN PB.PAYMENTBATCHDETAIL     PBP  ON PBP.PARTYCODE=S.SUBNUMBER   WHERE DETAILID=@DETAILID
		
		
  END
 

  UPDATE PB.PAYMENTBATCHDETAIL  SET CILOUTSTANDING=0,GSTOUTSTANDING=0  WHERE DETAILID=@DETAILID 

  INSERT INTO [PB].[BATCHLOG] (BATCHID,DETAILID,APPROVALLEVELID,LOGINID,TIMESTAMP) VALUES (@BATCHID,@DETAILID,@OWNERAPPROVALROLEDID,@BATLOGINID,GETDATE()) 

END 
 

IF @WORKFLOW = 'SUBSEQUENT APPROVAL'
BEGIN  

   SELECT @CURRENTLEVELID = APPROVALLEVELID   FROM PB.PAYMENTBATCHDETAIL WHERE DETAILID=@DETAILID 
   SELECT @CURRENTLEVELID = @CURRENTLEVELID+1
   SELECT @BATCHORGID = BATORGID ,@BATCHPROCESS = BATPROCESS FROM PB.PAYMENTBATCHHEADER WHERE BATCHID=@BATCHID 
   SELECT @NEXTUSERID = BSLOGINID FROM PB.PAYMENTBATCHUSERORGROLEMAPPING WHERE BSORGID= @BATCHORGID AND APPROVERLEVELID=@CURRENTLEVELID AND BSPROCESS =@BATCHPROCESS 
   UPDATE PB.PAYMENTBATCHDETAIL SET APPROVALLEVELID =@CURRENTLEVELID WHERE DETAILID = @DETAILID
   SELECT @CURRENTCUSTODIAN = CURRENTOWNER FROM PB.PAYMENTBATCHDETAIL WHERE DETAILID=@DETAILID 
   UPDATE PB.PAYMENTBATCHDETAIL SET CURRENTOWNER=@NEXTUSERID,SUBMITTEDBY=@CURRENTCUSTODIAN,SUBMISSIONTIME=GETDATE() WHERE DETAILID = @DETAILID AND @CURRENTLEVELID<=4
   UPDATE PB.PAYMENTBATCHDETAIL SET AMOUNTINWORDS = [dbo].[fn_spellNumber](BATCHOUTSTANDING,'UK',1) WHERE DETAILID = @DETAILID 
   INSERT INTO [PB].[BATCHLOG] (BATCHID,DETAILID,APPROVALLEVELID,LOGINID,TIMESTAMP) VALUES (@BATCHID,@DETAILID,@OWNERAPPROVALROLEDID,@NEXTUSERID,GETDATE()) 
END 

SELECT * FROM PB.PAYMENTBATCHDETAIL 


 

 