/****** Object:  Procedure [PB].[spGetBatches]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE [PB].[spGetBatches](@BATCHOWER VARCHAR(25),@BATCHSTATUS CHAR(1),@PROJECTLISTS VARCHAR(250))
AS
IF 1=0 BEGIN
    SET FMTONLY OFF
END

-- BATCH STATUS 0 - OPEN      (O)   --- FROM BATCHMASTER   AND REST EVERYTHING FROM BATCHDETAIL
-- BATCH STATUS 1 - APPROVED  (A)    -- ID = 4 
-- BATCH STATUS 2 - APPROVED AND MARKED FOR CHEQUES  - (C)  --  ID = 5
-- BATCH STATUS 3 - APPROVED AND MARKED FOR MANUAL RTGS  - (R)  -- ID = 6
-- BATCH STATUS 4 = APPROVED AND MARKED FOR API  (I)  -- ID = 7

CREATE TABLE #BORGS(BORGID INT) 
INSERT INTO #BORGS 
SELECT * 
FROM SPLIT(@PROJECTLISTS, ',')  
DELETE FROM #BORGS WHERE BORGID=NULL

 

DECLARE @STATUSOFBATCH INT 
IF @BATCHSTATUS = 'A' 
   SET @STATUSOFBATCH =5
 

DECLARE @PROCESSNAME VARCHAR(1)
DECLARE @CURRENTFINYEAR INT
DECLARE @BATCHID INT
DECLARE @BATORGID INT
DECLARE @BATCHNO  INT 
DECLARE @CILBALANCE DECIMAL(18,2)
DECLARE @ORGBALANCE DECIMAL(18,2)
DECLARE @MASTERLEDGERCODE VARCHAR(15)
DECLARE @PARTYCODE VARCHAR(35)
DECLARE @BORGID INT 
DECLARE @BATCHOWNERROLE INT
DECLARE @BATCHAPPROVERROLEID INT 
DECLARE @CURRENTOWNER VARCHAR(35)
DECLARE @DETAILID INT 
DECLARE @SELECTORGID INT
DECLARE @SELECTPROCESS VARCHAR(35)

SELECT @CURRENTFINYEAR = CURRENTYEAR  FROM BORGS WHERE BORGID=2 
SELECT @BATCHOWNERROLE = APPROVERLEVELID   FROM PB.PAYMENTBATCHUSERS    WHERE BSLOGINID=@BATCHOWER 

CREATE TABLE #FINAL(BATCHINDEX INT ,BATCHID INT,DETAILID INT, PROCESSNAME VARCHAR(35),BATCHNO VARCHAR(15),NARRATION VARCHAR(50),BATCHOWNER VARCHAR(100),
                    BORGID INT,BSORGNAME VARCHAR(150),
                    PARTYCODE VARCHAR(45),PARTYNAME VARCHAR(150),
					CILBALANCE DECIMAL(18,2),PROJECTBALANCE DECIMAL(18,2),BATCHBALANCE DECIMAL(18,2),GSTOUTSTANDING DECIMAL(18,2),AMOUNTINWORDS VARCHAR(255),
					CURRENTOWNER VARCHAR(100),APPROVALLEVELID INT,BANKID INT,BATSTATUS CHAR(1),SELECTED BIT )



CREATE TABLE #TEMP  (BATCHINDEX INT PRIMARY KEY IDENTITY (1,1) ,BATCHID INT,DETAILID INT, PROCESSNAME VARCHAR(35),BATCHNO VARCHAR(15),NARRATION VARCHAR(50),BATCHOWNER VARCHAR(15),
                    BORGID INT,BORGNAME VARCHAR(150),
                    PARTYCODE VARCHAR(45),PARTYNAME VARCHAR(150),
					CILBALANCE DECIMAL(18,2),PROJECTBALANCE DECIMAL(18,2),BATCHBALANCE DECIMAL(18,2),GSTOUTSTANDING DECIMAL(18,2),AMOUNTINWORDS VARCHAR(255),
					CURRENTOWNER VARCHAR(45),APPROVALLEVELID INT,BANKID INT )



CREATE TABLE #TEMP0 (BATCHID INT,BATORGID INT,BATCHNO INT,BATPROCESS CHAR(1),BATOWNER VARCHAR(100),BATBANKLEDGERCODE VARCHAR(15),NARRATION VARCHAR(50)) 


IF @BATCHSTATUS='A'
 BEGIN 
    INSERT INTO #FINAL(BATCHINDEX,BATCHID,DETAILID,NARRATION,BATCHOWNER, PARTYCODE,PARTYNAME,CILBALANCE,PROJECTBALANCE,BATCHBALANCE,
	GSTOUTSTANDING,AMOUNTINWORDS,CURRENTOWNER,APPROVALLEVELID, BANKID ) 
	SELECT DETAILID,BATCHID,DETAILID,NARRATION,SUBMITTEDBY,PARTYCODE,PARTYNAME,CILOUTSTANDING,PROJECTOUTSTANDING,BATCHOUTSTANDING,
	GSTOUTSTANDING,AMOUNTINWORDS,CURRENTOWNER,APPROVALLEVELID, BANKID 
	FROM PB.PAYMENTBATCHDETAIL WHERE BATCHOWNER =@BATCHOWER AND APPROVALLEVELID=5

	UPDATE #FINAL SET BORGID=H.BATORGID,PROCESSNAME=H.BATPROCESS,BATCHNO=H.BATCHNO  FROM PB.PAYMENTBATCHHEADER H INNER JOIN #FINAL ON #FINAL.BATCHID=H.BATCHID 
	UPDATE #FINAL SET BSORGNAME = B.BSORGNAME FROM PB.PAYMENTBATCHORGS B INNER JOIN #FINAL ON #FINAL.BORGID=B.BSORGID 
 END 
ELSE 
 BEGIN 
    IF @BATCHOWNERROLE =1  AND @BATCHSTATUS='O'
		BEGIN 
			INSERT INTO #TEMP0 
			SELECT PBB.BATCHID,PBB.BATORGID,PBB.BATCHNO,PBB.BATPROCESS,PBB.BATLOGINID,PBB.BATBANKLEDGERCODE,PBB.BATCHDESCRIPTION
			FROM PB.PAYMENTBATCHHEADER PBB  
			WHERE PBB.BATLOGINID = @BATCHOWER AND PBB.BATSTATUS=1 AND PBB.APPROVERLEVELID=1 AND BATORGID IN (SELECT BORGID FROM #BORGS)
			
		 

			ALTER TABLE #TEMP0 ADD BORGNAME VARCHAR(150)
			UPDATE #TEMP0 SET BORGNAME = B.BORGNAME  FROM BORGS  B INNER JOIN #TEMP0 ON #TEMP0.BATORGID = B.BORGID

			ALTER TABLE #TEMP0 ADD BANKID INT

			UPDATE #TEMP0 SET  BANKID = B.BANKID FROM PB.PAYMENTBANKS B INNER JOIN #TEMP0 ON #TEMP0.BATBANKLEDGERCODE=B.LEDGERCODE 
	 
			-- BATCH BALANCE - BASED ON PARTY CODE 
			CREATE TABLE #BATCHBALANCES(BATCHID INT,PARTYCODE VARCHAR(15),BATCHBALANCE DECIMAL(18,2))
	
			DECLARE BATCHES CURSOR FOR SELECT  BATCHID,BATORGID,BATCHNO,BATPROCESS FROM #TEMP0 
			OPEN BATCHES
			FETCH NEXT FROM BATCHES INTO @BATCHID,@BATORGID,@BATCHNO,@PROCESSNAME  
			WHILE @@FETCH_STATUS = 0
			BEGIN
				SELECT @CURRENTFINYEAR = BATYEAR FROM BATCHREMIT WHERE BATCHNO=@BATCHNO AND BATORGID=@BATORGID AND BATPROCESS=@PROCESSNAME 
				IF @PROCESSNAME='C'
				   SET @MASTERLEDGERCODE = '1315000'
				 ELSE
				   SET @MASTERLEDGERCODE = '1320000'
				INSERT INTO #BATCHBALANCES
				SELECT @BATCHID,CREDNO,SUM(PAIDTHISPERIOD)  
				FROM TRANSACTIONS 
				WHERE ORGID=@BATORGID AND RECONSTATUS=@BATCHNO AND LEDGERCODE=@MASTERLEDGERCODE AND YEAR=@CURRENTFINYEAR
				GROUP BY CREDNO 
				FETCH NEXT FROM BATCHES INTO @BATCHID,@BATORGID,@BATCHNO,@PROCESSNAME   
			END
			CLOSE BATCHES
			DEALLOCATE BATCHES
 

			INSERT INTO #TEMP  (BATCHID, PROCESSNAME,BORGID,    BORGNAME,  BATCHNO,  PARTYCODE,  BATCHBALANCE,  NARRATION,  BANKID ) 
			SELECT             T.BATCHID,T.BATPROCESS, T.BATORGID,T.BORGNAME,T.BATCHNO,B.PARTYCODE,B.BATCHBALANCE,T.NARRATION,BANKID  FROM #TEMP0 T 
			INNER JOIN #BATCHBALANCES B ON T.BATCHID = B.BATCHID

			-- WHICH ARE ON HOLD
			DELETE FROM #TEMP WHERE BATCHBALANCE=0

			-- ALREADY IN DETAIL TABLE 
			DELETE FROM #TEMP WHERE PARTYCODE IN (SELECT PARTYCODE FROM PB.PAYMENTBATCHDETAIL WHERE BATCHID = @BATCHID)
			

			UPDATE #TEMP SET PARTYNAME =UPPER(C.CREDNAME) FROM CREDITORS C INNER JOIN #TEMP ON #TEMP.PARTYCODE=C.CREDNUMBER 
			UPDATE #TEMP SET PARTYNAME =UPPER(S.SUBNAME)  FROM SUBCONTRACTORS S INNER JOIN #TEMP ON #TEMP.PARTYCODE = S.SUBNUMBER 
			UPDATE #TEMP SET DETAILID=0 WHERE DETAILID IS NULL

			INSERT INTO #FINAL(BATCHINDEX,BATCHID,PROCESSNAME,BORGID,BSORGNAME,BATCHNO,PARTYCODE,PARTYNAME,BATCHBALANCE,NARRATION,BANKID,DETAILID) 
			SELECT             BATCHINDEX,BATCHID,PROCESSNAME,BORGID,BORGNAME ,BATCHNO,PARTYCODE,PARTYNAME,BATCHBALANCE,NARRATION,BANKID,DETAILID
			FROM #TEMP ORDER BY BATCHINDEX 
	
			UPDATE #FINAL SET APPROVALLEVELID = 1,DETAILID=0 , BATCHOWNER=@BATCHOWER ,CURRENTOWNER=@BATCHOWER 
	
			
  END
ELSE
  BEGIN
  
    

    INSERT INTO #FINAL(BATCHINDEX,BATCHID,DETAILID,NARRATION,BATCHOWNER, PARTYCODE,PARTYNAME,CILBALANCE,PROJECTBALANCE,BATCHBALANCE,
	GSTOUTSTANDING,AMOUNTINWORDS,CURRENTOWNER,APPROVALLEVELID, BANKID ) 
	SELECT DETAILID,BATCHID,DETAILID,NARRATION,SUBMITTEDBY,PARTYCODE,PARTYNAME,CILOUTSTANDING,PROJECTOUTSTANDING,BATCHOUTSTANDING,
	GSTOUTSTANDING,AMOUNTINWORDS,CURRENTOWNER,APPROVALLEVELID, BANKID 
	FROM PB.PAYMENTBATCHDETAIL WHERE CURRENTOWNER =@BATCHOWER AND APPROVALLEVELID=@BATCHOWNERROLE 

	UPDATE #FINAL SET BORGID=H.BATORGID,PROCESSNAME=H.BATPROCESS,BATCHNO=H.BATCHNO  FROM PB.PAYMENTBATCHHEADER H INNER JOIN #FINAL ON #FINAL.BATCHID=H.BATCHID 
	UPDATE #FINAL SET BSORGNAME = B.BORGNAME  FROM BORGS  B INNER JOIN #FINAL ON #FINAL.BORGID=B.BORGID  
 
   END
 END

UPDATE #FINAL SET CILBALANCE=0,PROJECTBALANCE=0,GSTOUTSTANDING=0 

UPDATE #FINAL 
SET GSTOUTSTANDING = PBG.AMOUNT 
FROM PB.GSTOUTSTANDING PBG INNER JOIN #FINAL ON #FINAL.PARTYCODE = PBG.CREDNO 




DECLARE FINAL  CURSOR FOR SELECT BATCHID,BORGID,PARTYCODE,PROCESSNAME FROM #FINAL  
OPEN FINAL 
FETCH NEXT FROM FINAL INTO @BATCHID,@BORGID,@PARTYCODE,@PROCESSNAME  
WHILE @@FETCH_STATUS = 0 
BEGIN
  SET @CILBALANCE = 0
  SET @ORGBALANCE = 0 

  IF @PROCESSNAME='C'
     SET @MASTERLEDGERCODE = '1315000'
  ELSE
     SET @MASTERLEDGERCODE = '1320000'

  SELECT @ORGBALANCE  = SUM(CREDIT-DEBIT) FROM TRANSACTIONS WHERE CREDNO=@PARTYCODE AND LEDGERCODE=@MASTERLEDGERCODE  AND ORGID=@BORGID AND YEAR=@CURRENTFINYEAR
  SELECT @CILBALANCE  = SUM(CREDIT-DEBIT) FROM TRANSACTIONS WHERE CREDNO=@PARTYCODE AND LEDGERCODE=@MASTERLEDGERCODE  AND YEAR=@CURRENTFINYEAR
  UPDATE #FINAL SET   CILBALANCE=@CILBALANCE,PROJECTBALANCE=@ORGBALANCE WHERE BATCHID=@BATCHID AND PARTYCODE=@PARTYCODE 
  FETCH NEXT FROM FINAL INTO @BATCHID,@BORGID,@PARTYCODE,@PROCESSNAME 

END


CLOSE FINAL
DEALLOCATE FINAL


 
UPDATE #FINAL SET PROCESSNAME ='CREDITORS' WHERE PROCESSNAME='C'
UPDATE #FINAL SET PROCESSNAME ='SUB-CONTRACTORS' WHERE PROCESSNAME='S'
UPDATE #FINAL SET GSTOUTSTANDING =0 WHERE GSTOUTSTANDING IS NULL
UPDATE #FINAL SET SELECTED=0

 

UPDATE PB.PAYMENTBATCHDETAIL 
  SET  CILOUTSTANDING = F.CILBALANCE,
       GSTOUTSTANDING = F.GSTOUTSTANDING ,
	   PROJECTOUTSTANDING = F.PROJECTBALANCE
  FROM #FINAL F  INNER JOIN PB.PAYMENTBATCHDETAIL PBD ON PBD.DETAILID = F.DETAILID

UPDATE #FINAL SET BATSTATUS=@BATCHSTATUS 
ALTER TABLE #FINAL ADD BANKNAME VARCHAR(25)
ALTER TABLE #FINAL ADD BSUSERNAME VARCHAR(25)
ALTER TABLE #FINAL ADD PAYMODEDESC VARCHAR(25)

UPDATE #FINAL SET BATCHOWNER=U.USERNAME FROM USERS U INNER JOIN #FINAL ON #FINAL.BATCHOWNER = U.LOGINID 

IF @BATCHSTATUS ='O' 
BEGIN 
	SELECT 
	BATCHID,
	DETAILID,
    PROCESSNAME,
	BATCHNO,
	NARRATION,
	[BSORGNAME],
	PARTYCODE,
	PARTYNAME,BATCHBALANCE AS [BATCHOUTSTANDING],
	CILBALANCE AS [CILOUTSTANDING],
	PROJECTBALANCE AS [PROJECTOUTSTANDING],
	GSTOUTSTANDING ,
	[BATCHOWNER],
	SELECTED 
FROM #FINAL 
ORDER BY PROCESSNAME,[BSORGNAME],PARTYNAME
END 




IF @BATCHSTATUS = 'A'
BEGIN
SELECT 
	BATCHID,
	DETAILID,
    PROCESSNAME,
	BATCHNO,
	NARRATION,
	[BSORGNAME],
	PARTYCODE,
	PARTYNAME,
	BATCHBALANCE AS [BATCHOUTSTANDING],
	SELECTED 
FROM #FINAL 
ORDER BY PROCESSNAME,[BSORGNAME],PARTYNAME

SELECT DISTINCT BORGID, BSORGNAME FROM #FINAL 
SELECT BORGID,BANKID,BANKNAME FROM PB.PAYMENTBANKS WHERE BORGID IN (SELECT DISTINCT BORGID FROM #FINAL) 

END 