/****** Object:  Procedure [PB].[spPostToBuildSmart]    Committed by VersionSQL https://www.versionsql.com ******/

CREATE PROCEDURE  [PB].[spPostToBuildSmart](@RTGSHEADID INT)
AS
SELECT RTGSDETAILID,RTGSHEADERID,BATCHDETAILID  
INTO #TEMP0 
FROM PB.RTGSDETAIL WHERE RTGSHEADERID=@RTGSHEADID

DECLARE @RTGSDETAILID INT
DECLARE @RTGSHEADERID INT 
DECLARE @BATCHDETAILID INT 

DECLARE @PAYMENTTABLEID INT

DECLARE @PAYMENTYEAR VARCHAR(15)
DECLARE @PAYPERIOD INT
DECLARE @PAYAMOUNT DECIMAL(18,2)
DECLARE @PAIDTILLTHISPERIOD DECIMAL(18,2)
DECLARE @DEFAULTCONTRACT VARCHAR(15)
SET @DEFAULTCONTRACT =''
DECLARE @PAYREF VARCHAR(15)
DECLARE @PAYID INT 
DECLARE @UTRNUMBER VARCHAR(15)


DECLARE @BATCHNO VARCHAR(15)
DECLARE @BATCHID INT
DECLARE @BATBORGID INT
DECLARE @BATLOGINID VARCHAR(15)
DECLARE @BATBANKLEDGERCODE VARCHAR(15)
DECLARE @PARTYCODE VARCHAR(15)
DECLARE @OPENPARTYCODE INT
DECLARE @BATCHPROCESS VARCHAR(1)
DECLARE BATCHLISTS CURSOR FOR SELECT RTGSDETAILID,RTGSHEADERID,BATCHDETAILID FROM #TEMP0
OPEN BATCHLISTS
FETCH NEXT FROM BATCHLISTS INTO @RTGSDETAILID,@RTGSHEADERID,@BATCHDETAILID

WHILE @@FETCH_STATUS = 0 
BEGIN
  
  SELECT @BATCHNO=BATCHNO,@BATBORGID=BATORGID ,@BATBANKLEDGERCODE=BATBANKLEDGERCODE,@BATCHPROCESS=BATPROCESS ,@BATCHID=BATCHID   
  FROM PB.PAYMENTBATCHHEADER 
  WHERE BATCHID= (SELECT BATCHID  FROM PB.PAYMENTBATCHDETAIL WHERE DETAILID=@BATCHDETAILID)

  SELECT @PARTYCODE=PARTYCODE FROM PB.PAYMENTBATCHDETAIL WHERE DETAILID=@BATCHDETAILID 

  SELECT @UTRNUMBER = UTRNUMBER FROM PB.RTGSDETAIL WHERE RTGSDETAILID=@BATCHDETAILID

  IF @UTRNUMBER=''
     SET @PAYREF = @UTRNUMBER
  ELSE
     SET @PAYREF = @BATCHNO 

  
  UPDATE BATCHREMIT 
         SET BATSTATUS=2 ,BATUPDATE=GETDATE() , BATBANK=@BATBANKLEDGERCODE ,BATPROCESS = @BATCHPROCESS 
		 WHERE BATCHNO=@BATCHNO AND BATORGID=@BATBORGID
  UPDATE PB.PAYMENTBATCHDETAIL SET APPROVALLEVELID = 99 WHERE BATCHID=@BATCHID AND PARTYCODE=@PARTYCODE 

  

  SET @OPENPARTYCODE = 9999
  SELECT @OPENPARTYCODE = ISNULL(COUNT(*),0) FROM PB.PAYMENTBATCHDETAIL WHERE APPROVALLEVELID<>99 AND BATCHID=@BATCHID 

  IF @OPENPARTYCODE = 0
     UPDATE PB.PAYMENTBATCHHEADER SET BATSTATUS = 99 WHERE BATCHID=@BATCHID 

  SELECT @PAYAMOUNT = PAIDTHISPERIOD ,@PAIDTILLTHISPERIOD = PAIDTODATE,@PAYREF = TRANSREFEXT , @PAYID = TRANSID 
  FROM TRANSACTIONS WHERE ORGID=@BATBORGID AND RECONSTATUS=@BATCHNO 

  SELECT @PAYMENTYEAR = BATYEAR ,@PAYPERIOD = BATPERIOD
  FROM BATCHREMIT 
  WHERE BATCHNO=@BATCHNO AND BATORGID=@BATBORGID


  INSERT INTO [dbo].[PAYMENTS]
           ([BATCHNO]
           ,[PAYYEAR]
           ,[PAYPERIOD]
           ,[PAYID]
           ,[PAYAMOUNT]
           ,[PAYTAX]
           ,[PAYDISC]
           ,[PAYWHT]
           ,[PAYREF]
           ,[ORGID]
           ,[PAYTODATE]
           ,[PAYTYPE]
           ,[PAYMETH]
           ,[CREDNO]
           ,[TRANGRP]
           ,[EXCLUDE]
           ,[CONTRNUMBER])
     VALUES
           (@BATCHNO
           ,@PAYMENTYEAR
           ,@PAYPERIOD
           ,@PAYID
           ,@PAYAMOUNT
           ,0
           ,0
           ,0
           ,@PAYREF
           ,@BATBORGID
           ,@PAIDTILLTHISPERIOD
           ,@BATCHPROCESS
           ,2
           ,@PARTYCODE
           ,-1
           ,0
           ,@DEFAULTCONTRACT)
 

  SELECT @PAYMENTTABLEID = [ID]
  FROM PAYMENTS 
  WHERE BATCHNO= @BATCHNO  AND PAYID=@PAYID 

  UPDATE PB.RTGSDETAIL SET PAYMENTTABLEID = @PAYMENTTABLEID WHERE RTGSDETAILID=@RTGSDETAILID 


  FETCH NEXT FROM BATCHLISTS INTO @RTGSDETAILID,@RTGSHEADERID,@BATCHDETAILID
END
CLOSE BATCHLISTS
DEALLOCATE BATCHLISTS
UPDATE PB.RTGSHEADER SET RTGSSTATUS=2 WHERE RTGSID=  @RTGSHEADID