/****** Object:  Procedure [PB].[spTrackMyBatch]    Committed by VersionSQL https://www.versionsql.com ******/

create PROCEDURE [PB].[spTrackMyBatch]
AS



SELECT BATCHID,BATCHNO,BATORGID,BATPROCESS,BATLOGINID  INTO #BATCHID FROM PB.PAYMENTBATCHHEADER 
 
SELECT BATCHID,DETAILID,PARTYCODE,PARTYNAME,BATCHOUTSTANDING,NARRATION,CURRENTOWNER,SUBMITTEDBY,SUBMISSIONTIME 
INTO #BATCHLIST 
FROM PB.PAYMENTBATCHDETAIL 
WHERE APPROVALLEVELID<6 AND BATCHID IN (SELECT BATCHID FROM #BATCHID) 
 

SELECT BATCHID,MAX(LOGID) LOGID  INTO #LOGFILE FROM PB.BATCHLOG WHERE BATCHID IN (SELECT BATCHID FROM #BATCHID) GROUP BY BATCHID 

 

SELECT L.BATCHID,L.TIMESTAMP 
INTO #LOGTIMESTAMP 
FROM PB.BATCHLOG L 
WHERE LOGID IN (SELECT LOGID FROM #LOGFILE) 

ALTER TABLE #BATCHLIST ADD TIMESTAMP DATETIME 
UPDATE #BATCHLIST SET #BATCHLIST.TIMESTAMP = L.TIMESTAMP 
FROM #LOGTIMESTAMP L
INNER JOIN #BATCHLIST ON #BATCHLIST.BATCHID = L.BATCHID 

ALTER TABLE #BATCHLIST ADD BATPROCESS VARCHAR(1)
ALTER TABLE #BATCHLIST ADD BATORGID INT 
ALTER TABLE #BATCHLIST ADD PROCESS VARCHAR(15)
ALTER TABLE #BATCHLIST ADD PROJECT VARCHAR(100)
ALTER TABLE #BATCHLIST ADD BATCHNO VARCHAR(15)
ALTER TABLE #BATCHLIST ADD INITIATEDBY VARCHAR(100)

UPDATE #BATCHLIST 
SET BATPROCESS = H.BATPROCESS, BATORGID=H.BATORGID ,BATCHNO  = H.BATCHNO,INITIATEDBY=H.BATLOGINID
FROM #BATCHID H INNER JOIN #BATCHLIST ON #BATCHLIST.BATCHID=H.BATCHID 

UPDATE #BATCHLIST SET PROCESS = 'Creditors' WHERE BATPROCESS = 'C'
UPDATE #BATCHLIST SET PROCESS = 'Sub Contractors' WHERE BATPROCESS = 'S'
UPDATE #BATCHLIST SET PROJECT = B.BORGNAME FROM BORGS B INNER JOIN #BATCHLIST ON #BATCHLIST.BATORGID=B.BORGID 

ALTER TABLE #BATCHLIST ADD INITIATORNAME VARCHAR(200)
ALTER TABLE #BATCHLIST ADD CURRENTOWNERNAME VARCHAR(200)
ALTER TABLE #BATCHLIST ADD SUBMITTEDBYWHOM VARCHAR(200)

UPDATE   #BATCHLIST SET INITIATORNAME = U.USERNAME FROM USERS U INNER JOIN #BATCHLIST ON #BATCHLIST.INITIATEDBY=U.LOGINID
UPDATE   #BATCHLIST SET CURRENTOWNERNAME = U.USERNAME FROM USERS U INNER JOIN #BATCHLIST ON #BATCHLIST.CURRENTOWNER = U.LOGINID 
UPDATE   #BATCHLIST SET SUBMITTEDBYWHOM  = U.USERNAME FROM USERS U INNER JOIN #BATCHLIST ON #BATCHLIST.SUBMITTEDBY = U.LOGINID 
 
SELECT 
 INITIATORNAME    InitiatorName,
 PROCESS          BatchProcess,
 BATCHNO          BatchNo,
 NARRATION        Narration,
 PROJECT          BSBorgName,
 PARTYCODE        PartyCode,
 PARTYNAME        PartyName,
 BATCHOUTSTANDING BatchOutstanding,
 CURRENTOWNERNAME CurrentOwnerName,
 SUBMITTEDBYWHOM  SubmittedBy,
 SUBMISSIONTIME   LandedTime
FROM 
 #BATCHLIST
ORDER BY PROJECT 