/****** Object:  Table [BT].[DPRMachinery]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [BT].[DPRMachinery](
	[DPRID] [int] NOT NULL,
	[PROJECTCODE] [int] NULL,
	[EQUIPMENTCODE] [int] NULL,
	[DPRDATE] [datetime] NULL,
	[STARTREADING] [decimal](18, 2) NULL,
	[ENDREADING] [decimal](18, 2) NULL,
	[WORKINGHOURS] [decimal](18, 2) NULL,
	[IDLEHOURS] [decimal](18, 2) NULL,
	[BREAKDOWNHOURS] [decimal](18, 2) NULL,
 CONSTRAINT [PK__DPRMachi__2BB156883CC8D6E7] PRIMARY KEY CLUSTERED 
(
	[DPRID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]