/****** Object:  Table [BT].[EQUIPMENTMASTER]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [BT].[EQUIPMENTMASTER](
	[EQUIPMENTID] [int] NOT NULL,
	[PROJECTCODE] [int] NULL,
	[EQUIPNUMBER] [varchar](20) NULL,
	[EQUIPNAME] [varchar](200) NULL,
	[MAKE] [varchar](50) NULL,
	[MODEL] [varchar](50) NULL,
	[CAPACITY] [varchar](50) NULL,
	[TYPE] [varchar](50) NULL,
	[SHIFTS] [int] NULL,
	[OWNERID] [int] NULL,
	[OWNER] [varchar](50) NULL,
	[STATUS] [int] NULL,
	[CHECKINDATE] [datetime] NULL,
	[CHECKOUTDATE] [datetime] NULL,
	[HOURSPERSHIFT] [int] NULL,
 CONSTRAINT [PK_EQUIPMENTMASTER] PRIMARY KEY CLUSTERED 
(
	[EQUIPMENTID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]