/****** Object:  Table [BT].[LEDGERMAPPING]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [BT].[LEDGERMAPPING](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[LEDGERCODE] [varchar](10) NOT NULL,
	[REPORTCODE] [varchar](15) NOT NULL,
 CONSTRAINT [PK__LEDGERMA__3214EC2751CC5A0E] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]