/****** Object:  Table [BT].[MajorWorkHead]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [BT].[MajorWorkHead](
	[MAJORWORKHEADCODE] [varchar](10) NOT NULL,
	[MAJORGROUPID] [int] NULL,
	[MAJORGROUP] [varchar](25) NULL,
	[SUBGROUPID] [int] NULL,
	[SUBGROUP] [varchar](25) NULL,
	[WORKCATEGORYID] [int] NULL,
	[MAJORWORKHEAD] [varchar](255) NULL,
	[UOM] [varchar](15) NOT NULL,
	[TEMPLATECODE] [varchar](15) NULL,
	[WORKCATEGORY] [varchar](30) NULL,
	[OLDTEMPLATECODE] [varchar](15) NULL,
 CONSTRAINT [PK_MAJORWORKHEAD] PRIMARY KEY CLUSTERED 
(
	[MAJORWORKHEADCODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]