/****** Object:  Table [BT].[MATERIALMOVEMENT]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [BT].[MATERIALMOVEMENT](
	[INDEXCODE] [bigint] IDENTITY(1,1) NOT NULL,
	[BORGID] [int] NULL,
	[PROJECTCODE] [int] NULL,
	[PROJECTNAME] [varchar](100) NULL,
	[TOOLCODE] [varchar](15) NULL,
	[MAJORHEAD] [varchar](100) NULL,
	[TEMPLATENAME] [varchar](255) NULL,
	[CATEGORY] [varchar](25) NULL,
	[UOM] [varchar](25) NULL,
	[TENDERID] [bigint] NULL,
	[BUDGETQTY] [decimal](18, 4) NULL,
	[BUDGETRATE] [decimal](18, 2) NULL,
	[BUDGETAMOUNT] [decimal](18, 2) NULL,
	[RELEASEDQTY] [decimal](18, 4) NULL,
	[RELEASERATE] [decimal](18, 2) NULL,
	[RELEASEAMOUNT] [decimal](18, 2) NULL,
	[OPENPRQTY] [decimal](18, 4) NULL,
	[OPENPRAMOUNT] [decimal](18, 2) NULL,
	[CANCELLEDQTY] [decimal](18, 4) NULL,
	[CANCELLEDVALUE] [decimal](18, 2) NULL,
	[REJECTEDQTY] [decimal](18, 4) NULL,
	[REJECTEDVALUE] [decimal](18, 2) NULL,
	[CHANGEDORDERQTY] [decimal](18, 4) NULL,
	[CHANGEODERVALUE] [decimal](18, 2) NULL,
	[ORDERQTY] [decimal](18, 4) NULL,
	[ORDERRATE] [decimal](18, 2) NULL,
	[ORDERAMOUNT] [decimal](18, 2) NULL,
	[DELIVEREDQTY] [decimal](18, 4) NULL,
	[DELIVEREDVALUE] [decimal](18, 2) NULL,
	[QTYTODELIVER] [decimal](18, 4) NULL,
	[QTYTODELIVERAMOUNT] [decimal](18, 2) NULL,
	[BALANCEQTYTOPURCHASE] [decimal](18, 4) NULL,
	[BALANCEAMOUNTTOPURCHASE] [decimal](18, 2) NULL,
	[BALANCEBUDGET] [decimal](18, 4) NULL,
	[BALANCEBUDGETAMOUNT] [decimal](18, 2) NULL,
 CONSTRAINT [PK__MATERIAL__0A93C88A21E5DC74] PRIMARY KEY CLUSTERED 
(
	[INDEXCODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]