/****** Object:  Table [BT].[MATERIALBUDGETLOG]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [BT].[MATERIALBUDGETLOG](
	[LOGIID] [bigint] IDENTITY(1,1) NOT NULL,
	[LOGDATE] [datetime] NULL,
	[TRANSACTIONTYPE] [char](1) NULL,
	[PROJECTCODE] [int] NULL,
	[TOOLCODE] [varchar](25) NULL,
	[QTY] [decimal](18, 2) NULL,
	[RATE] [decimal](18, 4) NULL,
	[AMOUNT] [decimal](18, 2) NULL,
	[CROSSREFERENCEID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[LOGIID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]