/****** Object:  Table [BT].[TOTALBUDGETHEADS]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [BT].[TOTALBUDGETHEADS](
	[HEADID] [int] NOT NULL,
	[BUDGETCODE] [varchar](15) NULL,
	[BUDGETHEAD] [varchar](200) NULL,
 CONSTRAINT [PK_TOTALBUDGETHEADS] PRIMARY KEY CLUSTERED 
(
	[HEADID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]