/****** Object:  Table [BT].[TRANSACTIONTYPES]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [BT].[TRANSACTIONTYPES](
	[TRANSID] [int] NOT NULL,
	[TRANSACODE] [varchar](1) NULL,
	[NOTES] [varchar](50) NULL,
	[REFERENCEDETAILS] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[TRANSID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]