/****** Object:  Table [BT].[WEBWOUSERPROEJCTS]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [BT].[WEBWOUSERPROEJCTS](
	[USERPROJECTID] [int] IDENTITY(1,1) NOT NULL,
	[BSLOGINID] [varchar](15) NULL,
	[BMTPROJECTID] [int] NULL,
	[BSORGID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[USERPROJECTID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]