/****** Object:  Table [BT].[WEBWOMASTERITEMS]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [BT].[WEBWOMASTERITEMS](
	[ITEMID] [int] IDENTITY(1,1) NOT NULL,
	[BMTCODE] [nvarchar](20) NOT NULL,
	[WORKDESCRIPTION] [ntext] NOT NULL,
	[UNIT] [nvarchar](15) NOT NULL,
	[RATE] [money] NOT NULL,
	[TOTALQTY] [decimal](18, 4) NOT NULL,
	[ORGID] [int] NOT NULL,
	[PROJECTCODE] [int] NOT NULL,
	[CONTRACTCODE] [int] NOT NULL,
	[LEDGERCODE] [nvarchar](10) NOT NULL,
	[ORDEREDQTY] [decimal](18, 4) NOT NULL,
	[ORDEREDAMOUNT] [decimal](18, 4) NOT NULL,
	[ACTIVITYNUMBER] [nvarchar](10) NOT NULL,
	[CROSSREFERENCEID] [nvarchar](10) NOT NULL,
 CONSTRAINT [PK_WEBWOMASTERITEMS] PRIMARY KEY CLUSTERED 
(
	[ITEMID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]