/****** Object:  Table [BT].[WEBWOREQITEMS]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [BT].[WEBWOREQITEMS](
	[WEBWOREQITEMID] [int] IDENTITY(1,1) NOT NULL,
	[WEBWOREQID] [int] NULL,
	[BMTCODE] [varchar](20) NULL,
	[REQQTY] [decimal](18, 2) NULL,
	[BSREQID] [int] NULL,
	[BSREQLINEITEM] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[WEBWOREQITEMID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]