/****** Object:  Table [BT].[WORKSUBGROUP]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [BT].[WORKSUBGROUP](
	[MAJORGROUPID] [int] NOT NULL,
	[SUBGROUPID] [int] NOT NULL,
	[SUBGROUP] [varchar](25) NULL,
 CONSTRAINT [PK_WORKSUBGROUP] PRIMARY KEY CLUSTERED 
(
	[MAJORGROUPID] ASC,
	[SUBGROUPID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [BT].[WORKSUBGROUP]  WITH CHECK ADD  CONSTRAINT [FK_WORKSUBGROUP_WORKSUBGROUP] FOREIGN KEY([MAJORGROUPID], [SUBGROUPID])
REFERENCES [BT].[WORKSUBGROUP] ([MAJORGROUPID], [SUBGROUPID])
ALTER TABLE [BT].[WORKSUBGROUP] CHECK CONSTRAINT [FK_WORKSUBGROUP_WORKSUBGROUP]