/****** Object:  Table [BT].[WORKSUBTASK]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [BT].[WORKSUBTASK](
	[SUBTASKCODE] [varchar](10) NOT NULL,
	[TASKID] [varchar](8) NULL,
	[SUBTASKNUMBER] [int] NULL,
	[TEMPLATECODE] [varchar](15) NULL,
	[SUBTASKNAME] [varchar](255) NULL,
	[UOM] [varchar](15) NULL,
	[OLDTEMLATECODE] [varchar](15) NULL,
 CONSTRAINT [PK_WORKSUBTASK] PRIMARY KEY CLUSTERED 
(
	[SUBTASKCODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]