/****** Object:  Table [BT].[WORKMAJORGROUP]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [BT].[WORKMAJORGROUP](
	[MAJORGROUPID] [int] NOT NULL,
	[MAJORGROUP] [varchar](25) NULL,
 CONSTRAINT [PK_WORKMAJORGROUP] PRIMARY KEY CLUSTERED 
(
	[MAJORGROUPID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]