/****** Object:  Table [BT].[WORKORDERITEMS]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [BT].[WORKORDERITEMS](
	[ID] [bigint] NOT NULL,
	[PROJECT] [int] NULL,
	[CATEGORY] [varchar](1) NULL,
	[ITEMTYPE] [varchar](50) NULL,
	[TOOLCODE] [varchar](25) NULL,
	[WORKDESCRIPTION] [varchar](600) NULL,
	[UOM] [varchar](20) NULL,
 CONSTRAINT [PK__WORKORDE__3214EC273C93ADAE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]